### ISSUE TITLE
Document telemetry collection

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1003]
I just filed an issue on Focus-iOS for telemetry, and I think we should probably have a .md file for telemetry collection on Android. This can be simple, but at least linking to our TelemetryWrapper files and the telemetry-android repo, and maybe documenting what is being collected.

**Comment by pocmo** [comment]
We have this:
https://github.com/mozilla-mobile/focus-android/wiki/Telemetry

**Comment by liuche** [comment]
I definitely forgot about that, and I've actually made a PR to it before. Embarrassing, I'm going to just close this issue :P

**Comment by liuche** [comment]
Oh, I see how I was confused, these used to be in-tree as .md files, but are now a wiki.
https://github.com/mozilla-mobile/focus-android/commit/dd1b611ea12b64cb14ceb25e42e80bfd93e08717

I think that's fine, as long as we're sure to update the wiki along with telemetry changes.
