### ISSUE TITLE
First run tour not scrollable on Samsung Note 5

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1010]
(From user testing)

**Comment by ioana-chiorean** [comment]
Tried with Samsung Note 5 with Android 6.0.1 with both 1.2 RC 1 and  Build #2635   ( did not check if they are the same though) 
Works fine on my side.

**Comment by pocmo** [comment]
Thank you!

With that there's nothing we can do here. I'm closing this issue.
