### ISSUE TITLE
Opening downloaded APK from snackbar shows error: "There was a problem parsing the package."

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1011]
When downloading an APK (usually an update I get from buddybuild) and trying to install the APK from the Snackbar ("open" action) an error dialog pops up saying: "There was a problem parsing the package.". When opening the APK from the download manager notification everything is fine though.

**Comment by pocmo** [comment]
@ekager Do you have an idea what's causing this? Launching the APK from our snackbar is somehow behaving differently.

**Comment by pocmo** [comment]
![screenshot_20170725-154212](https://user-images.githubusercontent.com/89638/28589694-75dc2cf2-717f-11e7-8000-c154deb1b49c.png)

**Comment by ekager** [comment]
@pocmo I just tested this and downloaded an APK + launched with the snackbar successfully on API 24 + 26, which device+version are you finding this on? Does the error pop up immediately or after trying to open the file? Does this happen for every APK file you try to open? It might be something with the FileProvider and fetching the correct URI + Intent... I can investigate.

**Comment by pocmo** [comment]
I see this on a Pixel XL running the latest Android O beta. The popup shows up after clicking on the "open" snackbar action - instead of the "do you want to install this?" screen.

This is how it looks like when I try to download an APK from APKMirror:
https://youtu.be/CVlrd4okAxI

**Comment by ekager** [comment]
Okay now able to reproduce on latest Android O.
I'm looking into testing different scenarios. Strange part is I've tested a handful of apps from apkmirror.com and can only reproduce with the Reddit app so far. I also logged the uriFile string and mimeType and the Reddit app gives the correct mime type. I force set the file name to "reddit.apk" and was able to 'solve' the issue and not get the parsing error, so I'm going to continue to test + tweak file name code, we might have to simplify the generated file names somehow (perhaps remove special characters?).  

**Reddit:**
uriFile: content://org.mozilla.focus.debug.fileprovider/Download/Download/com.reddit.frontpage_2.13.0-21300_minAPI19(arm64-v8a%252Carmeabi%252Carmeabi-v7a%252Cmips%252Cmips64%252Cx86%252Cx86_64)(nodpi)_apkmirror.com-2.apk

mimeType: application/vnd.android.package-archive


**Netflix:**
uriFile: content://org.mozilla.focus.debug.fileprovider/Download/Download/com.netflix.mediaclient_5.2.0_build_19086-19086_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk

mimeType: application/vnd.android.package-archive

**Comment by pocmo** [comment]
Maybe try logging `file.exists()` to see if we created the right path / `File` object. I wonder if we create the wrong File object or if FileProvider creates a wrong URI.

It might be us who break the uri. Some properties in it seem to be encoded twice:

```
%252C
uri_decode(%252C) -> %2C
uri_decode(%2C) -> ,
```

**Comment by ekager** [comment]
Correct the file does not currently exist before generating the snackbar! Will look into this tomorrow!
