### ISSUE TITLE
Simplify URL matching a bit more, remove FocusString

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#1012]
I've realised our Trie searching code is considerably over-engineered.

Trie search (findNode()) could be implemented iteratively, whereas we currently have a recursive implementation. An iterative approach means keeping track of String offsets is a lot more viable (we currently use FocusString to hide offsets, we do that since passing String offsets around would IMHO introduce a lot of mental overhead - calling substring() is expensive, see #571 ). An iterative approach should also be (minimally) faster, since we avoid the overhead of method calls and one new FocusString instance per recursive call.

(Trie insertion also uses FocusString, and can be reimplemented in a similar way. Once we've cleaned both of those up, FocusString becomes unused and can also be removed.)

I've already got some patches locally, I still need to get some performance measurements on those though. We have plenty of tests for our url matching, so these changes should be fairly low risk.

These changes should also make #594 a little simpler to implement.

**Comment by ahunt** [comment]
I would appreciate it if someone could assign this to me, I seem to have lost those privileges a while back : ) .

**Comment by ekager** [comment]
Assigned! :)

**Comment by pocmo** [comment]
I guess you lost your super powers when you dropped out of the mozilla-mobile org. I added you to this repository manually and you should have received an invite. :)
