### ISSUE TITLE
Tag blocklist entries with owner (part 1 of "Show details about blocked trackers")

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#1014]
This issue is essentially a part 1 for #594, and proposes one approach to storing the "owner" for blocked hosts.

The blocklist ( https://github.com/mozilla-mobile/focus-android/blob/fb285e0b0749dc9a575e323e07a13b3e3262ab96/shavar-prod-lists/disconnect-blacklist.json ) is composed of:
(A) categories ("Disconnect"/"Advertising"/"Analytics"/etc), each of which contains a list of
 (B) owners ("AddThis", "Digg", "Facebook", etc) each of which has a domain name, and also supplies a list of
  (C) blocked hosts

(I recommend reading the "blacklist" section of https://github.com/mozilla-mobile/focus-android/wiki/Content-blocking for a bit more background.)

We already read the owner names in B, although we discard the domain name for that owner:
(Note: the comment is wrong, we only skip the owners domain, but the owner name is stored in siteOwner...)
https://github.com/mozilla-mobile/focus-android/blob/fb285e0b0749dc9a575e323e07a13b3e3262ab96/app/src/webkit/java/org/mozilla/focus/webkit/matcher/BlocklistProcessor.java#L180

We discard the owner name later when we insert the URL into the blocklist trie at:
https://github.com/mozilla-mobile/focus-android/blob/fb285e0b0749dc9a575e323e07a13b3e3262ab96/app/src/webkit/java/org/mozilla/focus/webkit/matcher/BlocklistProcessor.java#L106

Blocked hosts are stored in a Trie. A given Trie node currently stores a list of child nodes and a boolean to indicate whether that node represents a domain. We already extend Trie in WhiteListTrie in order to additionally store a whitelist (i.e. a specific domain points to a list of whitelisted domains) per node, we could similarly extend Trie (e.g. "BlocklistTrie") in order to store an owner/domain for each node in the blacklist. Then we can modify TrieCallback.put() to store the owner in our new BlocklistTrie, instead of discarding it.

(Our Trie implementation, including WhiteListTrie, lives at https://github.com/mozilla-mobile/focus-android/blob/fb285e0b0749dc9a575e323e07a13b3e3262ab96/app/src/webkit/java/org/mozilla/focus/webkit/matcher/Trie.java )

Once the owner is stored, we can read it again when searching for blocked domains in UrlMatcher. Currently we just check that findNode() returns !null to determine whether a site is blocked. Instead we could also read the owner name (and url if appropriate) from that node:
https://github.com/mozilla-mobile/focus-android/blob/fb285e0b0749dc9a575e323e07a13b3e3262ab96/app/src/webkit/java/org/mozilla/focus/webkit/matcher/UrlMatcher.java#L262

**Comment by ahunt** [comment]
Note: this is only needed if #594 requires displaying the owner for blocked sites. I believe that decision is up to UX to make!

**Comment by vesta0** [comment]
@brampitoyo let me know what you think of this. I like what are doing for iOS - I assume it's a similar idea?
