### ISSUE TITLE
Show black screen and/or focus wordmark in app switcher

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#103]
On iOS, focus shows a black or purple screen (with the focus wordmark) when in the app switcher.

Do we want the same on Android?

**Comment by pocmo** [comment]
We could set FLAG_SECURE. This will hide the activity's content int he app switcher. One downside of this is that you can't take screenshots of the activity anymore.

https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE

**Comment by ahunt** [comment]
Apparently this might work if we only want to affect the app switcher, but not screenshots:
https://developer.android.com/reference/android/app/Activity.html#onCreateThumbnail(android.graphics.Bitmap,%20android.graphics.Canvas)

**Comment by ahunt** [comment]
Lol no, it's not actually used and/or broken:
https://code.google.com/p/android/issues/detail?id=29370

**Comment by ahunt** [comment]
Setting FLAG_SECURE during onPause() is too late to disable the app preview, so toggling it on/off during onPause/Resume won't work. I think we pretty much just have to make a choice between not doing this, or breaking screenshots.

**Comment by pocmo** [comment]
During triage we decided to add the flag and see if there are users complaining. However I was just wondering whether this will break the screenshot automation from @npark-mozilla. If I remember correctly it is using uiautomatorviewer. So we need to test whether this still works. I guess in the worst case we could have a gradle configuration for a build that has this disabled - just for our screenshots.

**Comment by npark-mozilla** [comment]
if it's in a pref, I probably can access this and set the value to false to make it visible. For example, to always enable FIRSTRUN_PREF for the l10n screenshot testing (since it reruns many times for each locale), I do the following:
@Override
        protected void beforeActivityLaunched() {
            super.beforeActivityLaunched();
            Context appContext = InstrumentationRegistry.getInstrumentation()
                    .getTargetContext()
                    .getApplicationContext();
            PreferenceManager.getDefaultSharedPreferences(appContext)
                    .edit()
                    .putBoolean(FIRSTRUN_PREF, false)
                    .apply();
        }

**Comment by ahunt** [comment]
I've implemented this with a pref defined in preference_keys.xml, with value "pref_secure" (which can be retrieved using resources.getString(R.string.pref_key_secure)).

(Just some notes in case we ever have to revisit this: Signal does make this option configurable, they call the pref "Screen security", which states "Block screenshots in the recents list and inside the app" - they enable that by default.)
