### ISSUE TITLE
Search suggestions

### ISSUE THREAD

**Issue by dimqua** [mozilla-mobile/focus-android#1040]
Would be nice to have an option to enable/disable search suggestions.

**Comment by bbinto** [comment]
We are currently evaluating how useful the search suggestions actually are, and how much are those being used, as it stands right now, this might be something we'll remove in future versions.

Could you please help us understand why you would want to turn them on/off? use cases, etc.

Thanks :)

**Comment by dimqua** [comment]
Search suggestions do not work for me:

![](http://i.imgur.com/vAXQKcI.png)

**Comment by jpggithub** [comment]
Search suggestions simply do not protect our privacy...
Thanks

**Comment by pocmo** [comment]
They are not actually "search suggestions" (= autocompleting search terms, like Firefox for Android does). We are auto-completing top domains from a list that ships with the app. It is not talking to a search provider.

**Comment by jpggithub** [comment]
It's more clear now. It is perhaps an aspect to document somewhere.
Anyway, thank you very much for the explanation :-)

**Comment by bbinto** [comment]
closing this in favour of #1930
