### ISSUE TITLE
Hide vile "Turn on Analytics" and create useful "Maintain Logins" Pref

### ISSUE THREAD

**Issue by jimmoffet** [mozilla-mobile/focus-android#1042]
0% of your users want to turn on ads and analytics (that's literally the only reason we downloaded this app) and yet the preference exists in the settings. If you're willing to create a pref that destroys the core value of the app, why not add one that creates value?

I visit [________].com 10 times a day and logging in every time makes this app completely unusable for me, although I love everything else about it. I suspect there's a massive swath of users that are in my camp.

Please bury the switches to turn on ads/tracking (or move them to the in-browser settings menu and make them per-page, so they might actually serve a purpose) and give their prominent position in the settings UI to a switch to turn on login cookies, ideally both blanket and with a whitelist.

**Comment by bbinto** [comment]
see also #1041

**Comment by bbinto** [comment]
Talked to BD and we might want to discuss the effort / potential release for this.
