### ISSUE TITLE
Support for Android v4 (Jelly Bean, KitKat)

### ISSUE THREAD

**Issue by dapgo** [mozilla-mobile/focus-android#1048]
IMHO, FF Focus should be available for the above versions, since there are still quite a lot of users and devices using these versions.

https://commons.wikimedia.org/wiki/File:Android_version_distribution_%28January_2017%29.png
https://developer.android.com/about/dashboards/index.html#Platform

**Comment by pocmo** [comment]
This has been discussed before (e.g. #942). We are relying on WebView APIs that are not available on earlier versions of Android.
