### ISSUE TITLE
Chrome Custom Tab API support

### ISSUE THREAD

**Issue by dimqua** [mozilla-mobile/focus-android#1052]
Please consider to use Chrome Custom Tabs, if available, like [Chromer](https://github.com/arunkumar9t2/chromer) does.

**Comment by pocmo** [comment]
We already support custom tabs. What exactly are you missing that Chromer does?

**Comment by dimqua** [comment]
Chromer use existing Chrome Custom Tabs providers (including Focus, Nightly and Chromium-based browsers) to render web pages. Theoretically, Focus can do the same. If Chrome Custom Tabs providers are already installed, Focus can use one of them instead of WebView.

**Comment by pocmo** [comment]
Focus *is* a Custom Tab Provider. Using a different one instead of WebView doesn't make sense in our case - we want to be in control and influence what is loaded and how.

**Comment by dimqua** [comment]
@pocmo What about using Nightly (Firefox 56) specifically?

**Comment by pocmo** [comment]
As a Custom Tab Provider? The Custom Tabs API doesn't allow us to actually do content blocking unfortunately.
