### ISSUE TITLE
Settings polish: Users read the “Mozilla” section as “Make Mozilla the default browser.”

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1053]
UR recommends: Consider updating the menu item to “Make Firefox Focus default browser.”

Next steps: Will update with Michelle.

**Comment by lime124** [comment]
<img width="362" alt="screen shot 2017-08-24 at 9 15 07 am" src="https://user-images.githubusercontent.com/287322/29676375-c7686970-88ac-11e7-978e-9f571824a18d.png">

Please use "Make Firefox Focus default browser". I got @mheubusch 's approval over slack.

**Comment by antlam** [comment]
@mheubusch I feel like using the word "Make" here kind of clashes with the Material Design guidelines a bit (https://material.io/guidelines/patterns/settings.html#settings-writing-guidelines)

It kind of feels like "Use" or "Change" in the examples linked... thoughts?

**Comment by pocmo** [comment]
Because of the string freeze this landed as "Make Firefox Focus default browser" - However we can file a follow-up issue to update the string if needed.

**Comment by antlam** [comment]
@pocmo thanks! that works. We were discussing this further on Slack and concluded the same thing anyways. But I forgot to document it here.
