### ISSUE TITLE
Settings polish: The option to make Focus default is currently buried in the settings menu.

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1054]
UR recommends: Help users make Focus their default browser by better placement in the settings menu.

Next steps:
Address position soon.

**Comment by lime124** [comment]
@bbinto I think this is part of a bigger issue which is the whole Android Settings need a bit of love and organization. If we just keep fixing one off issues we're going to go in circles. 

I would advocate for letting UX look at the Settings menu holistically and propose a solution that address this issue as well as any others floating around. 

Unfortunately, with string freeze tomorrow and PTO I don't think this is doable for Cobalt, but we can get it done for Denim. 

Thoughts?

**Comment by brampitoyo** [comment]
I support this idea. By coming up with a way to put settings into subsections when we don’t have so many of them yet, we’ll get two benefits:

1. It will clear up other Settings-related visibility issues (#1053, #1173) and prevent every new setting from wanting to compete for the most important position (ie. be the topmost on the list).
2. It will offer a scalable structure that will allow us to easily add new settings in the future, while keeping the page short and browsable (e.g. what if things like Tor integration end up having a lot of settings?)

**Comment by bbinto** [comment]
I think #1173 should go out asap.

However, the rest of the items (this one, #834, #1053)  you've referenced, I'm fine with combining them into one release, e.g Ebony as this will be the next UX-heavier release. I've prefixed the affected issues with "Settings polish" for grouping.

**Comment by bbinto** [comment]
@lime124 - I saw what you did with TP for iOS via a [meta] issue, might be useful here as well.

Feel free to do the same here, whatever works best for you.

**Comment by antlam** [comment]
@bbinto as you also pointed out, string freeze is today! since we merged the Milestones, so I'm moving this to Granite* as there's already a lot in Folly, including the UX-heavy "What's New?" feature!

**Comment by BrianNJones** [comment]
As discussed, revamping Settings will require significant level of UX/content effort. Recommendation to move to Indigo.

**Comment by lime124** [comment]
Agreed with @BrianNJones. 

We really want to make sure we do this right and that is going to take time. We're going to have a meeting next week to kick of the effort and start with research into what we currently have to uncover existing issues. From there we can begin re-design efforts that will address the issues already opened as well as what we learn.

**Comment by ekager** [comment]
Closed by #2574
