### ISSUE TITLE
It's not clear to new users that Focus is also a content blocker.

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1056]
UR recommends: Communicate in first-run and/or settings.

Next steps: 
Try to clarify flow in iOS. Check if we have telemetry numbers for those using Focus iOS as Content Blocker (Barbara)

**Comment by ekager** [comment]
This isn't relevant to Focus for Android, right?

**Comment by bbinto** [comment]
Correct, closing this, my mistake
