### ISSUE TITLE
The drop-down search suggestions feels redundant without history-based suggestions to pull from

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1057]
UR recommends: Remove search suggestions

Next steps: Simplify/remove this. (But keep autocomplete for now)

**Comment by pocmo** [comment]
Telemetry for clicks on the "Search for ..." label:
* (action, select_query, search_bar)

**Comment by bbinto** [comment]
Seems also very little usage showing up from Telemetry (https://sql.telemetry.mozilla.org/queries/6424/source#12923)
<img width="583" alt="screen shot 2017-08-03 at 10 51 27 am" src="https://user-images.githubusercontent.com/122897/28935563-cdaf8dd2-7839-11e7-9c2d-1b9b9899815c.png">

**Comment by antlam** [comment]
Attaching screenshot for reference:
![screenshot_20170818-103142](https://user-images.githubusercontent.com/1994820/29470256-831c3216-8400-11e7-85f4-11cd576ba4c8.png)

I think we can remove this suggestion... but just wanted to flag that it does provide the option (like in this example) to search for something you've typed. Versus, hitting "return" which would send this user off to "sears.com".

So if we do remove this, we can think about some options to follow up after. For example:

1. Assuming users want suggestions, how can we offer search suggestions in a privacy centric way?
2. How might we polish this UI/UX now that there are no suggestions?

cc/ @gemmapetrie

**Comment by bbinto** [comment]
@pocmo can you please confirm that the event pings I'm using above https://github.com/mozilla-mobile/focus-android/issues/1057#issuecomment-320042639 are indeed the correct ones?

**Comment by pocmo** [comment]
Yeah, the query looks good to me (-> comparing typed search/URL [red] vs search hint clicked [blue]).

I have a hard time coming up with a value that I'd consider "good" or "bad" though. Is 5% (daily!) really "low" for this kind of interaction?
* Not every action is a search, so 100% is not something we can strive for.
* If we reverse it: @antlam mentioned a use case where a search can only be performed via the hint easily. Do we want to make this harder for 5%?
* We are looking at users / day. How do the numbers look like if we look at a week / month?

I really have no clue how to come up with a model for those kind of interactions that I can compare against.

**Comment by pocmo** [comment]
I wonder if "retention" (or some other indicator of app usage) would be interesting here: Those 5% of users -> Are those random users or are they actively using the app often?

**Comment by antlam** [comment]
> Those 5% of users -> Are those random users or are they actively using the app often?

@pocmo yeah thats a good point that requires more investigation I think.

**Comment by bbinto** [comment]
Some new developments here :)

I will get the following validated by our data expert wbeard but...the queries I ran to get retention cohorts show that users with search suggestions retain better than the ones not using this feature....

With: https://sql.telemetry.mozilla.org/queries/27277/source#71739
Without: https://sql.telemetry.mozilla.org/queries/27645/source#72774

**Comment by bbinto** [comment]
Talked with @wbeard, he'll look into this from a data perpective

**Comment by brampitoyo** [comment]
We now have the option to show search suggestions, so this issue can be closed.
