### ISSUE TITLE
Audit non-http/https resource loading

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#106]
See #35 (crash when trying to load a non URL link), and #32 (actually open app URI links).

I have a feeling that any site trying to load a non http/https resource will crash the app, since UrlMatcher only handles URLs. We should test this, and decide what to do in this case. I'm guessing we should simply block loading anything that is not a valid http/https URL, but we need to be careful to not break opening external (app) links correctly.

**Comment by ahunt** [comment]
I've done some testing (using an <img src="..."/>)
- file:// URIs are completely ignored by webkit (shouldInterceptRequest() isn't called)
- data:// URIs are parsed within webkit, no shouldInterceptRequest() call is made
- Same with market: URIs: completely ignored

- malformed URIs crash the app: I tried a market:://.... URI (note: double colon), that was passed into shouldInterceptRequest(), and crashed.

The safest solution seems to be to only try to match http/https URIs. If we're not loading the main frame AND the request isn't http/https, we should block the request. (The main frame could be trying to open an external app, see #32.)

**Comment by pocmo** [comment]
Yeah, the block lists only make sense for HTTP(s) I guess? Although it would be interesting if you could track someone over another protocol that is supported and allows to identify a user.

For blocking file URIs I saw something in WebSettings.

**Comment by ahunt** [comment]
file:// URIs actually appear to be enabled by default (they just don't go via WebViewClient). I'm guesing we'll want to disable them completely.
