### ISSUE TITLE
After installing a new app from Focus, 'Open' from notification tray does not work

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1063]
Found this while investigating #1011 
- Go to apkmirror.com
- Pick some apk, and download it
- Click the notification tray to open the app
- Install then app, and open it
- Pull notification tray, and select 'Open'

Actual:
Doesn't do anything, or sometimes the app crashes
Expected:
Go to Focus

What's interesting is, "Open and Erase" seem to work fine.

Around the time when this happened, logcat shows this:

08-02 13:21:41.609   974  3870 I ActivityManager: START u0 {act=open flg=0x10000000 cmp=org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity bnds=[129,275][416,371]} from uid 10276 on display 0
08-02 13:21:41.620   369  3331 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
08-02 13:21:41.648  7905  7905 D GeckoLocales: No selected locale. No correction needed.
08-02 13:21:41.654   369  3331 D AudioFlinger: mixer(0xae9c0000) throttle end: throttle time(7)
08-02 13:21:41.743   974  2098 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{4d2fc6d u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t722} time:674508542
08-02 13:21:41.817   974   983 I art     : Background partial concurrent mark sweep GC freed 99251(8MB) AllocSpace objects, 6(148KB) LOS objects, 30% free, 36MB/52MB, paused 1.545ms total 195.382ms
08-02 13:21:41.966  3896  3896 D PhoneStatusBar: disable: < expand icons* alerts system_info* back home recent clock search quick_settings >
08-02 13:21:42.389 10258 10279 I GAV2    : Thread[GAThread,5,main]: No campaign data found.

**Comment by Sdaswani** [comment]
@bbinto this still needs some more investigation - do you want to spend time on it in 6.0?

**Comment by bbinto** [comment]
Yes, @Sdaswani

**Comment by Sdaswani** [comment]
OK, then we may want to move it to 5.2 so we can NI it before 6.0 .
