### ISSUE TITLE
When google is set to search default, search term is not displayed outside U.S.

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1065]
Found this while verifying #891 

I'm in Canada, so it goes to google.ca site (not sure whether this matters)

STR:
- Set the default search to Google
- Enter search term, press enter to go to the search result webpage
- tap URL bar

Expected:
- Show highlighted search term
Actual:
- highlights actual long URL

**Comment by ekager** [comment]
google.ca isn't in our ca search resource folder which I use to check if it's a default search. google.ca is automatically used for you when you search from the focus homescreen? https://github.com/mozilla-mobile/focus-android/tree/master/app/src/main/assets/search/ca

**Comment by npark-mozilla** [comment]
Oh sorry, let me clarify, I chose google as the search engine in Settings, and since I'm in Canada, it uses google.ca and not google.com.

**Comment by pocmo** [comment]
Duplicate of #891
