### ISSUE TITLE
Cannot choose new locale-specific search engine after you change default language

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#1067]
STR:
1) Change default language from settings
2) Go to change default search engine

Expected:
Locale-specific search engines can be selected

Actual: 
Old locale-specific search engines remain and does not update with locale-specific engines. Need to restart app to see new options.

**Comment by pocmo** [comment]
Also see #245. Using the locale for determining the search engines was just a trade-off for the first release(s). Firefox for Android actually picks the defaults based on a GeoIP lookup.

**Comment by ekager** [comment]
1) Is accessing search engines based on GeoIP a privacy concern for users?
2) Can we be sure these will be accurate? 
3) Should we give users another way to change their search engines in case they're using VPNs etc

**Comment by ekager** [comment]
This receiver DOES work and update the search engine list, but only when System language is changed 
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/search/SearchEngineManager.java#L51

**Comment by pocmo** [comment]
> 1) Is accessing search engines based on GeoIP a privacy concern for users?

Mozilla runs its own location service that shouldn't be a privacy concern:
https://location.services.mozilla.com/

> 2) Can we be sure these will be accurate?

If they are accurate enough for Firefox for Android then I'd say yes. :)

On Android the locale is tied to the language selection. And our search engines are based on the locale only. All my devices are set to US English and therefore I get the US search engines currently.

> 3) Should we give users another way to change their search engines in case they're using VPNs etc

Eventually we should allow users to set arbritary search engines (see  #808, #961) - without them needing to change the language.

**Comment by lobontiumira** [comment]
This issue still reproduces on the latest RC 92.1.1 build.
Changing the language, updates the default search engines only after force closing Focus.
