### ISSUE TITLE
Cannot authorize sync when focus is default browser

### ISSUE THREAD

**Issue by mystor** [mozilla-mobile/focus-android#1069]
When focus is set as my default browser, and I click on the "Confirm Sign-in" link in the Firefox Accounts email which we send when you sign into sync for the first time on a new computer, an error message is shown complaining that you need cookies enabled in order to access Firefox accounts.

It seems bad that we can't authenticate our own sign-ins to one of our browsers if your default browser is set to a different one.

![screenshot](https://user-images.githubusercontent.com/1261662/28894346-6be3fbb6-7789-11e7-9ae2-bf52ff7c6926.png)

(NOTE: This might be a Firefox accounts issue - I can close this and open an account there if it is more appropriate).

**Comment by pocmo** [comment]
What version / build are you using? We recently fixed a local storage issue and I wonder if this version has already this fix.

**Comment by mystor** [comment]
@pocmo You're right, it was.

I was running focus 1.0, and for some reason hadn't received the 1.1 update yet. I pulled the new version and it works correctly now.

**Comment by pocmo** [comment]
Perfect. Thanks. :)
