### ISSUE TITLE
Resources$NotFoundException: File res/drawable/ic_tracking_protection_disabled.xml from drawable resource ID #0x7f020090

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1075]
From BuddyBuild.

Device: Aquaris E5 HD - Android 5.0

> android.view.InflateException: Binary XML file line #95: Error inflating class ImageView
> 
> Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_tracking_protection_disabled.xml from drawable resource ID #0x7f020090
> 
> Caused by: java.lang.NumberFormatException: Invalid float: ".107.01.106"

[View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/e49b806c40149317b241db223142c9e0)

**Comment by pocmo** [comment]
@ekager A problem with our Vector Drawable? I remember reading something about the support library and that vector drawables need to be referenced in the XML somehow differently than normally (Can't remember the details).

**Comment by ekager** [comment]
Let me look into this today!

**Comment by ekager** [comment]
Fixed! 
For future reference found the solution here: https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88
