### ISSUE TITLE
Fix or suppress lint errors

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#108]
Running lint on buddybuild is currently disabled. Let's fix or suppress the current list of warnings and then enable it.

- [x] Fix lint errors
- [ ] Fix lint warnings
- [x] Enable lint on buddybuild

**Comment by pocmo** [comment]
Builds on buddybuild already fail if there's a lint error. Currently we only have warnings left. After those are fixed we could fail the build for all lint issues.

**Comment by ahunt** [comment]
Do we care about Google App Indexing? I'm guessing we could offer direct links to the settings/about/rights screens, but I don't think that has any value, so I'm considering ignoring the GoogleAppIndexingWarning.

**Comment by pocmo** [comment]
> Do we care about Google App Indexing? I'm guessing we could offer direct links to the settings/about/rights screens, but I don't think that has any value, so I'm considering ignoring the GoogleAppIndexingWarning.

Absolutely not! What is the warning about?
