### ISSUE TITLE
Alpha animation of wordmark after erasing

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1085]
Follow-up from #832: After erasing a session add an alpha animation (0-1) to the wordmark translate animation.

**Comment by imjacobclark** [comment]
@pocmo @jenn-chaulk @bbinto is this something external Mozilla folk can work on (such as myself?)

**Comment by pocmo** [comment]
@imjacobclark In theory yes. When erasing the browsing history we go back to the home screen. The keyboard comes up and we animate the word mark moving up as well. Only in this situation we want to add an alpha animation (0f - 1f) to it.
There's currently a refactoring of certain parts of the app underway. So we probably can't merge this right now. But you could definitely investigate how to add this and then provide a patch on top of the refactored implementation once it lands. :)
Thank you for your help so far!

**Comment by grubdragon** [comment]
Hey can I take this up?

**Comment by bbinto** [comment]
Yes, @grubdragon -- Thanks, let @lime124 or @Sdaswani know if you need any assistance.

**Comment by mcomella** [comment]
@grubdragon Sorry we missed you on IRC!

The wordmark is the "Firefox Focus" text on the homescreen (the file for the asset is actually called `wordmark.png`). Note that the text under it will probably need an alpha animation too.

**Comment by mcomella** [comment]
@grubdragon On that note, I see you've already started working on another `good first issue` – it'd be great if you pull something from our `help wanted` issues for your next bug (if I remember, I'll probably include one in your PR once it's completed, if I haven't already).

**Comment by grubdragon** [comment]
Okay, I'll try something else :)

**Comment by noloman** [comment]
Hi! is this issue still valid, open and available for doing some work on it?

**Comment by grubdragon** [comment]
Hey, yes it is! You can start right away!

**Comment by noloman** [comment]
yes but not for this issue, or you mean that there's already a PR for this issue in particular?

**Comment by grubdragon** [comment]
This issue is for beginners, why don't you try some help-wanted ones?

**Comment by noloman** [comment]
yes sure, that'd work too. I consider myself a beginner in this repository, and that's why I chose it :)

**Comment by rohitramkumar308** [comment]
@noloman are you working on this one? Can I take it if you are not. I am a beginner too. Thanks

**Comment by shikhart98** [comment]
Can I just try it out? I'm new to open source.

**Comment by pocmo** [comment]
Hey @shikhart98! There's a pull request for this issue in flight already (#2268).

However there are other "good first issue" and "help wanted" issues available:
* https://github.com/mozilla-mobile/focus-android/labels/good%20first%20issue
* https://github.com/mozilla-mobile/focus-android/labels/help%20wanted

A very easy one to start with would be #2355.
