### ISSUE TITLE
Homescreen shortcut remembering the blocker switch status

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1091]
Currently add to homescreen feature does not support remembering the blocker switch status. If a site needs to be unblocked to properly view it, then having the blocker status remembered in the shortcut can reduce addtional step to unblock it.

From #833

**Comment by pocmo** [comment]
Adding UX label -> Maybe we want to make this more explicit and mention that in the dialog? Or even make it a checkbox.

**Comment by lime124** [comment]
Here is the proposal from UX. @mheubusch is working on final string wording. I'm off on PTO starting tomorrow, but @antlam can help with the visual spec stuff on Monday.

![add to homescreen](https://user-images.githubusercontent.com/287322/29687277-a8675972-88d0-11e7-8cd0-ffc37edde8ab.png)

FYI @bbinto

**Comment by mheubusch** [comment]
@bbinto Here is the recommended string: Shortcut will open with Tracking Protection disabled

**Comment by antlam** [comment]
![screen shot 2017-08-28 at 1 53 08 pm](https://user-images.githubusercontent.com/1994820/29793315-42648c00-8bf8-11e7-96fd-abc494ac0166.png)

Visual Design Specs!

**Comment by antlam** [comment]
[tracking-protection-16-disabledSVG.zip](https://github.com/mozilla-mobile/focus-android/files/1258353/tracking-protection-16-disabledSVG.zip)

Here's the SVG asset @pocmo
