### ISSUE TITLE
Update App Icon

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1092]
😉

**Comment by antlam** [comment]
![google play store](https://user-images.githubusercontent.com/1994820/29258879-5cdebc18-8072-11e7-95d9-d296a0f08898.png)

@pocmo Here's the Play Store asset - the rest to come. 

I think we could also update to the Photon iconography in the same release too

**Comment by pocmo** [comment]
> I think we could also update to the Photon iconography in the same release too

Sure! My only requirement is that we use SVGs for the icons inside the app. :)

**Comment by antlam** [comment]
[PhotonFocus_LauncherIcon.zip](https://github.com/mozilla-mobile/focus-android/files/1223188/PhotonFocus_LauncherIcon.zip)

@pocmo try these!

**Comment by antlam** [comment]
![xxxhdpi - beta launcher icon](https://user-images.githubusercontent.com/1994820/29295489-8144d104-8109-11e7-9269-b75bb4a3fb87.png)

[PhotonFocus_BetaIcon.zip](https://github.com/mozilla-mobile/focus-android/files/1223691/PhotonFocus_BetaIcon.zip)

And Beta

**Comment by antlam** [comment]
![xxxhdpi - dev launcher icon](https://user-images.githubusercontent.com/1994820/29295642-55ffb8aa-810a-11e7-9ac8-008eccaa0463.png)

[PhotonFocus_DevIcon.zip](https://github.com/mozilla-mobile/focus-android/files/1223700/PhotonFocus_DevIcon.zip)

And Dev

**Comment by bbinto** [comment]
@pocmo talked to mhan, all assets and dependencies should be cleared by August 31, so we can/should keep it in Burgundy
