### ISSUE TITLE
Request to localize "Your Rights" on Focus for Android

### ISSUE THREAD

**Issue by mchagas** [mozilla-mobile/focus-android#1095]
Hello,
@cynthiapereira noticed that "Your Rights" page on Focus for Android isn't available for localization on Pontoon. Would be great to have this strings to localize and turn Focus complete localized.

This is issue was noticed on pt-BR version of Focus for Android, I don't know whether this is only with pt-BR version.

 #![photo_2017-08-05_02-58-12](https://user-images.githubusercontent.com/287986/28997733-1a9b5928-79f2-11e7-834f-d4e3469036a7.jpg)

**Comment by pocmo** [comment]
Afaik we followed the iOS version here. There might be legal reasons why we did not translate this. But we'll discuss this in triage.

**Comment by Delphine** [comment]
I believe last I heard it was for legal reasons, yes.

**Comment by mchagas** [comment]
Hi @Delphine and @pocmo,
Thanks for you reply. But for me it don't make sense. We have all [Legal](https://www.mozilla.org/pt-BR/about/legal/) page localized, as you can see, if you could explain why, or it's just because iOS version have different legal treatment the Android version follow the same? Well, let us know if it change, we will appreciate to localize that section too.

Thanks.

**Comment by cynthiapereira** [comment]
I think we do not need to translate the licenses (MPL, GPL, etc) however this part has essential information for people interested in contributing or using it in some a independent way without violating any trademark and also let them know how the product works (blocklists).

**Comment by pocmo** [comment]
FYI: We moved this into the Cobalt milestone (you can find the deadlines and releases dates for that [here](https://wiki.mozilla.org/Mobile/Focus/Android/Train_Schedule)). At the start of the Cobalt iteration we will revisit the decision and investigate why it was made and whether we can make this page translatable.

**Comment by pocmo** [comment]
@eleemoz Did we do this on purpose or could we open this up for translators?

**Comment by eleemoz** [comment]
I don't think it was on purpose, so if you want to open it up for translation that'd be fine. Our Firefox [About Rights](https://www.mozilla.org/about/legal/terms/firefox/) page is also localized.

**Comment by eleemoz** [comment]
I don't think it was on purpose, so if you want to open it up for translation that'd be fine. Our Firefox [About Rights](https://www.mozilla.org/about/legal/terms/firefox/) page is also localized.
