### ISSUE TITLE
Set Stealth setting to OFF by default

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1104]
We made messaging changes in issue #718 but we had forgotten to file an issue to change the default setting. Since we want to change the default here, we'll have to also change it for the following cases:

1. User has not changed the pref before -> change it to OFF
2. New users on a fresh install -> set it to OFF
3. User has changed the pref before -> leave it as whatever they've set it to

Filing this and sticking it under the Burgundy Milestone for @bbinto when she comes online. 

cc @pocmo

**Comment by pocmo** [comment]
I'm confused by this decision - shouldn't the default settings be "privacy first"?

**Comment by bbinto** [comment]
Because of the double/confusing meaning, side effects of this setting, it's easier to focus on convenience in this case. So OFF by default.

**Comment by pocmo** [comment]
We discussed this in the triage meeting. (1) is not really possible because the default settings are written the first time the app is opened: So I think we do not really know whether the current value is user set or a default value. However (2) and (3) should be a simple fix.

**Comment by bbinto** [comment]
Some feedback: https://play.google.com/store/apps/details?id=org.mozilla.focus&reviewId=Z3A6QU9xcFRPSEs4bnZYRkVQTGxHZ1lQYm5Mei1MNEp5NjN0NmhPVHlWSUwwSkhkUXlock51MVhYMV8wTV8zN2NPeGF4SUxHV3NYb25hRjZwaDRlZUFJS2w4
