### ISSUE TITLE
Mozilla Firefox Focus, Mozilla Firefox Klar is connecting to mozilla servers. T/F

### ISSUE THREAD

**Issue by quakenet2** [mozilla-mobile/focus-android#1115]
> Firefox Focus: The privacy browser - Browse like no one’s watching.

But Mozilla is watching users.

How can we sure that you didn't send ANY information but the target website(which user want to visit)?

Here's SOME logs which latest Mozilla Firefox AUTOMATICALLY connect to without user consent.

url=https://normandy.cdn.mozilla.net/
url=https://snippets.cdn.mozilla.net/
url=http://detectportal.firefox.com/success.txt
url=https://www.mozilla.org/
url=https://discovery.addons.mozilla.org/

Really, how can we trust this app?

**Comment by quakenet2** [comment]
If you implement a proxy support(http/socks), I can monitor your app's activity.
Until then, I can't endorse your app as a "privacy app" even this is a open source.

**Comment by pocmo** [comment]
For proxy support, please follow #64.

For telemetry see our docs here:
https://github.com/mozilla-mobile/focus-android/wiki/Telemetry

> How can we sure that you didn't send ANY information but the target website(which user want to visit)?

If you don't trust the app and/or Mozilla in general then your only option is to (or hire someone to) read and compile the code manually.
