### ISSUE TITLE
Telemetry, Health Report, Anonymous Usage data

### ISSUE THREAD

**Issue by quakenet2** [mozilla-mobile/focus-android#1116]
By default, anonymous usage data is turned off. THIS IS GOOOD!
However, you forgot to add a killswitch to disable Telemetry and Health report.

Your Mozilla Firefox have 3 buttons(Telemetry, Health Report, Usage data).
So I assume Mozilla Focus / Mozilla Klar have that code too.

You can't call this app "privacy app" because there is no way to STOP sending ANY information
to your servers. Also when the user mistap the switch, it automatically turned it on.

Why not ask a user before turning on?

[O--]
(mistap happened)
Show dialogue: "Do you really want to send this data?"
(tap No)
[O--]

And I know you won't do this, because you want to collect our data...

**Comment by pocmo** [comment]
Our telemetry documentation can be found here:
https://github.com/mozilla-mobile/focus-android/wiki/Telemetry

There are two types of telemetry pings described in the documentation. Both are controlled by the switch in the settings.

Asking those questions (and opening issues) is absolutely valid. But it's mildly confusing that all the issues you opened come with wild accusations.
