### ISSUE TITLE
Privacy list - where to download these data?

### ISSUE THREAD

**Issue by quakenet2** [mozilla-mobile/focus-android#1117]
Privacy - 
Block ad trackers
Block analytics
Block social
Block other

To block them, you need data. The question is, where these data coming from?

Q1. Where Mozilla Focus / Mozilla Klar download them from? (server address, URL)
Q2. Do you transmit device information when downloading this data?
Q3. Do you transmit Unique ID to target user when downloading this data?

Really, this is an impotant question that must be documented publically.

**Comment by quakenet2** [comment]
In Mozilla Firefox, you use google server to download list. With sending Firefox's Unique ID.
If you did this to Mozilla Focus / Mozilla Klar, You can not call this privacy app.

All users who use Mozilla Focus or Mozilla Klar must be the same packet(not identifiable in any way)

**Comment by pocmo** [comment]
The blocklists live right here in our repo:
https://github.com/mozilla-mobile/focus-android/tree/master/shavar-prod-lists

They are shipping (and updating) with the app and are not downloaded currently.
