### ISSUE TITLE
Show clipboard URL as user starts typing

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1118]
_Added by @bbinto_

**Why**
- Provide users with a convenient way to quickly access the URL they just copied to the clipboard earlier

**What**
-  We detect that the string in the clipboard is a URL.
-  If true, then show “Link you copied: [url.com]” as soon as you type something into the URL bar.
- Tap on the URL shown to go to the URL.

**Acceptance Criteria (how do I know when I’m done?)**
- Basic flow as described above can be performed
- Probes included to show how often users 
   - come into the app, having a URL copied to their clipboard
   - use the feature, i.e. Tap on the URL

--
We have this in iOS right now and it seems to be a great way to provide value given the context of Focus. It's also a quick way to help users move links into Focus. But we're still learning and iterating on this feature. 

Filing this to see if we also want to bring this over to Android. @bbinto thoughts?

Latest bug here for iOS: https://github.com/mozilla-mobile/focus-ios/issues/269

**Comment by bbinto** [comment]
@antlam - Could you please past a dirty mock for me to understand the UX around this :) Thanks

**Comment by antlam** [comment]
![img_1086](https://user-images.githubusercontent.com/1994820/29199034-f25ec8f8-7e7b-11e7-8b8a-c90f0ccfa794.PNG)

@bbinto here's the UI I'm referring to on iOS. This bug is about considering if we want to do the same (after we improve it in issue #269) on Android.

**Comment by bbinto** [comment]
:) thanks @antlam -- seems like a neat convenience-like feature

**Comment by ekager** [comment]
An iteration of #125 ?

**Comment by antlam** [comment]
I guess its a dupe!

**Comment by antlam** [comment]
Note: will add strings-approved label once @mheubusch confirms

**Comment by codebu5ter** [comment]
@antlam Any update on this? 
I could work on this when the strings are updated.

**Comment by pocmo** [comment]
@lime124 -^

**Comment by antlam** [comment]
Thanks for following up @codebu5ter , I'm going to let @lime124 chime in here since she's been doing a lot more thinking about this than I have lately. 

@codebu5ter if you didn't want to wait, achieving parity with the iOS feature would be a great start so that we can see how it feels on Android. You could use placeholder strings for the time being so it doesn't block you.

**Comment by antlam** [comment]
@codebu5ter I followed up with @lime124 after leaving the message above^

To start, can we follow the iOS implementation here? We could the same strings as well.

Basic user flow:
1. User types any character 
2. User see's search suggestion and "Link you copied:" (as the screenshot above)
3. Tapping the second list item (Link) will load the link

Please post a screenshot of it once you're ready!

**Comment by lime124** [comment]
thanks @antlam ! I know the flow might not be ideal and we want to follow up on that, but I think the first step is to get parity with iOS. Thanks for your help @codebu5ter

**Comment by Sdaswani** [comment]
@brampitoyo just getting a status check - is the UX for this work done or do you still need time to finalize mocks?

**Comment by brampitoyo** [comment]
@Sdaswani The UX for this looks fairly straightforward, so it’s finished.

The idea is to follow iOS Focus’ implementation:

1. We detect that the string in the clipboard is a URL.
2. If true, then show “Link you copied: [url.com]” as soon as you type something into the URL bar.
3. Tap on the URL shown to go to the URL.

**Comment by Sdaswani** [comment]
@brampitoyo if it's finished should it be assigned to you? Does Eng still need something from you to get started? If so that's fine, just trying to understand.

**Comment by brampitoyo** [comment]
@Sdaswani Thanks for clarifying! I should’ve been more clear. When I’ve finished my work and it’s ready to be handed over to Engineering, I will unassign myself.

**Comment by Sdaswani** [comment]
@bbinto @brampitoyo is this something we still want to do since we are contemplating adding search suggestions in #1930 ?

**Comment by bbinto** [comment]
@Sdaswani - Good point, putting it on the back burner for now.

**Comment by brampitoyo** [comment]
@Sdaswani Actually, I think that this is something that we still want to do one day.

The only way it may be related to search suggestions, is if the suggestions occupy so much vertical space (let’s say that there are 5–6 suggestions) that it cuts off “URL you copied”.
