### ISSUE TITLE
More details needed about "Telemetry, Health Report, Anonymous Usage data"

### ISSUE THREAD

**Issue by quakenet2** [mozilla-mobile/focus-android#1119]
Thanks for replying my questions @pocmo, your answer is very helpful and these should be documented
to Wiki so other people can notice it. Klar without telemetry/data-sending code could become an alternative to Orfox.

Now, I have another question. Related to https://github.com/mozilla-mobile/focus-android/issues/1116 ,
I wrote "Telemetry, Health Report, Anonymous Usage data".

Is below 3 statements are correct?
If not, would you describe it?

1. Focus(default) and Klar(if opted-in) send "telemetry" using "core" and "event" system(2 functions).
2. Your app never connect to any mozilla servers or Adjust GMBH, if the user disable that "telemetry" push button.
3. Your app never collect "Health Report" and "Anonymous Usage data", these codes DO exist in Mozilla Firefox but not in Focus or Klar.

**Comment by quakenet2** [comment]
Suggestion to improve your wiki:
https://github.com/mozilla-mobile/focus-android/wiki/Telemetry

Why not adding below text(example)?

---

In Mozilla Firefox, we collect your information by default.
These are called "Firefox Health Report", "Additional Data", "Crash log", "Anonymous Usage data", and "Telemetry".
In Mozilla Focus and Mozilla Klar, we collect "Telemetry" only.
We *promise* you that we don't collect any other information.

**Comment by quakenet2** [comment]
^ also, please add a link to "Mozilla's telemetry service".

The reader will think "What the hell is 'Mozilla's telemetry service'?."

e.g. Mozilla's telemetry service use telemetry.mozilla.org as FQDN....

**Comment by quakenet2** [comment]
@pocmo Any idea why your employees are downvoting this issue?
Are you seriously think this app protect user's privacy?

https://www.reddit.com/r/privacytoolsIO/comments/6sss2e/mozilla_focusmozilla_klar_must_change_the_string/

**Comment by pocmo** [comment]
> Focus(default) and Klar(if opted-in) send "telemetry" using "core" and "event" system(2 functions).

Yes, if the option to send anonymous usage data is enabled then we send an event ping and a core ping as described in those documents:
https://github.com/mozilla-mobile/focus-android/wiki/Telemetry
I want to emphasize that those pings do not contain data about the user or about websites visited. Instead the collected data helps us to understand how the app is used and helps us developing and prioritizing features.

> Your app never connect to any mozilla servers or Adjust GMBH, if the user disable that "telemetry" push button.

Yes, both things are controlled by the setting. Adjust is not part of Klar builds. And even in Focus builds we only use a very tiny part of Adjust's services (counting installation sources).

> Your app never collect "Health Report" and "Anonymous Usage data", these codes DO exist in Mozilla Firefox but not in Focus or Klar.

Those are no technical terms and so this doesn't really make sense to answer. There's currently no additional service used apart from the two mentioned above.

> The reader will think "What the hell is 'Mozilla's telemetry service'?."

Thank your for letting us know. As part of #1123 we will try to make this more clear in the wiki.

**Comment by quakenet2** [comment]
> There's currently no additional service used apart from the two mentioned above.

= Focus & Klar *only* have 2 telemetry service, nothing more.

So how about adding this text below to https://github.com/mozilla-mobile/focus-android/wiki/Telemetry ?

> No other telemetry system(data sending) is included in both application.
> However, Focus will count installation sources when first install but NOT on Klar.


---

Very detailed answer. I like it :)
Thank you for your answer. I'll sure try Klar again.

> we will try to make this more clear in the wiki.

Yes, please do.

**Comment by pocmo** [comment]
> So how about adding this text below to https://github.com/mozilla-mobile/focus-android/wiki/Telemetry ?

Thanks. That's something to consider when updating the wiki. I guess it would make sense to have some data overview page and then more detailed pages for Adjust and Mozilla's Telemetry?
