### ISSUE TITLE
[Illegal] Change "Anonymous usage data" to "Identifiable usage data".

### ISSUE THREAD

**Issue by quakenet2** [mozilla-mobile/focus-android#1120]
https://www.wilderssecurity.com/threads/firefox-focus-privacy-scandal.391991/

> definition of “personal information” to include “a persistent identifier that can be used to recognize a user 
> over time and across different Web sites or online services [including but not limited to] a customer
> number held in a cookie, an Internet Protocol (IP) address, a processor or device serial number, or unique 
> device identifier.

> If you’re collecting persistent identifiers, be careful about making blanket statements to people assuring 
> them that you don’t collect any personal information or that the data you collect is anonymous.

---

> The data includes an advertising ID, IP address, timestamp, country, language/locale,
> operating system and app version.

What you're collecting is NOT ANONYMOUS information.
This is a violation of the law and you should change the name to "identifiable usage data".

**Comment by quakenet2** [comment]
https://github.com/mozilla-mobile/focus-ios/wiki/Install-Tracking-in-Firefox-Focus-with-the-Adjust-SDK

1. Device ID :(
2. Not documented in here(focus-android's wiki). Huh.

**Comment by quakenet2** [comment]
https://github.com/mozilla-mobile/focus-android/issues/718

**Comment by st3fan** [comment]
I see you are referring to the *Focus iOS* page about Adjust usage.

There is a lot of similarity between iOS and Android but there are probably some subtle differences.

I think it makes sense to have a separate Wiki page about Adjust usage in Focus for Android. I will file a bug for that.

**Comment by liuche** [comment]
After talking to Elvin, I also filed this bug [1] for Firefox iOS, and we can reuse whatever strings come out of that bug.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1390664
