### ISSUE TITLE
Create an Android specific Wiki page that explains Adjust usage

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/focus-android#1123]
In #1120 there is a discussion happening about Adjust integration details.

The author of that issue is referring to https://github.com/mozilla-mobile/focus-ios/wiki/Install-Tracking-in-Firefox-Focus-with-the-Adjust-SDK but that page is iOS specific.

There is a lot of similarity between iOS and Android but there are probably some subtle differences. For example how the Android Adjust SDK is generating the persistent id. And how that id is unique (or not, i don't know) to just Focus.

I think it makes sense to have a separate Wiki page about Adjust usage in Focus for Android. The iOS version can probably be a good base document for this.

**Comment by bbinto** [comment]
@mcomella could this be something for you to pick up?

**Comment by mcomella** [comment]
@bbinto How do we want to prioritize this with other open issues? At the moment, I'm working on Folly issues.

**Comment by bbinto** [comment]
Medium priority, ...what t-shirt size would you give this, S?

It's important to be transparent with our data collection, one of our core principles and so important as it relates to the brand.

It's more whenever you have time in between, but I'd love to have this done let's say mid November the latest? Do-able?

**Comment by mcomella** [comment]
> ...what t-shirt size would you give this, S?

To be safe, I'd say M – under the hood, Adjust uses the Google Advertising ID so I'd probably have to read their source to identify what it's used for. fwiw, @pocmo might already know how this works given the research into #1174.

> It's more whenever you have time in between, but I'd love to have this done let's say mid November the latest? Do-able?

Yeah, should be. I still am not comfortable with the Focus workflow so I'm concerned any on-the-side work might languish but I'll do my best to keep this on my radar (assigning to myself - feel free to take if you intend to tackle it sooner!).

**Comment by pocmo** [comment]
> Yeah, should be. I still am not comfortable with the Focus workflow so I'm concerned any on-the-side work might languish but I'll do my best to keep this on my radar (assigning to myself - feel free to take if you intend to tackle it sooner!).

I agree. This hasn't worked in the last sprints. We should move tasks into the milestone (as long that's what we define as our "sprint") even if they are not things that we release. It's something that competes with other tasks for our attention so we should make this visible. Now we are trying to avoid having to prioritize them against the other tasks but that's what we engineers now effectively have to do. :)

**Comment by mcomella** [comment]
@bbinto Given Sebastian's comment, should we try to move this into a milestone?

**Comment by bbinto** [comment]
Yes, ok, I just did.

**Comment by bbinto** [comment]
I think that might be a nice after 4.0 December task

**Comment by boek** [comment]
All that is left now is to get the example request/response in here and then I will close. https://github.com/mozilla-mobile/focus-android/wiki/Adjust-Usage
