### ISSUE TITLE
On small devices in landscape the snackbar can overlay the word mark

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1124]
Sony Z3C in landscape:

![small01](https://user-images.githubusercontent.com/89638/29174030-66cddc20-7de5-11e7-9dce-3ff71b76f95b.png)

---

![small02](https://user-images.githubusercontent.com/89638/29174032-69a6fe18-7de5-11e7-9f8b-6bef2dfaec04.png)

**Comment by codebu5ter** [comment]
What should be the desired behaviour in such a scenario? A Toast message would do?

**Comment by antlam** [comment]
@pocmo yeah, one of the problems with the transparent snackbar.

I would say it's not a high priority item for the time being, considering the device orientation and type.

**Comment by pocmo** [comment]
@lime124 @antlam This is in "Ready for Eng" - but what do we actually want to do here? Normally this Snackbar wouldn't be transparent... :)

**Comment by lime124** [comment]
I'm not sure why this is in Ready for Eng...we are working on the solution! :)

**Comment by lime124** [comment]
![homescreen - keyboard - toast](https://user-images.githubusercontent.com/287322/30929349-12d80b0a-a373-11e7-9129-fb90fc70269d.png)

Here is the answer that you seek! tl;dr is let's remove the transparency and replace with a solid background.

**Comment by layely** [comment]
@lime124 can i help here ?

**Comment by pocmo** [comment]
@layely Yeah! I just added the "good first bug" label. I think that's a good one for a new contributor.

**Comment by Obaied** [comment]
I'll gladly take this one over, if possible :)

**Comment by Obaied** [comment]
https://github.com/mozilla-mobile/focus-android/pull/1440

**Comment by pocmo** [comment]
Moving to Folly milestone. Implemented by @Obaied.
