### ISSUE TITLE
[Wiki] Tell user that your app never make 3rd party connection to grab the blocklist.

### ISSUE THREAD

**Issue by quakenet2** [mozilla-mobile/focus-android#1127]
https://github.com/mozilla-mobile/focus-android/wiki/Content-blocking

+
> When you enable the blocklist in settings, our app will load selected blocklist
> in background. We do not make any internet connection because "disconnect
> tracking protection lists" are built into our app. We will provide updated list
> as "App update".

Reason: Some people including me may think your app will connect to internet server to download
blocklist, such as Adblock|uBlock. So please consider updating your wiki.

**Comment by boek** [comment]
https://github.com/mozilla-mobile/focus-android/wiki/Content-blocking#miscellaneous-notes Added a paragraph at the top of Miscellaneous Notes. @bbinto can you review?

**Comment by bbinto** [comment]
Approved!
