### ISSUE TITLE
Does Mozilla Focus / Mozilla Klar check app update like Mozilla Firefox?

### ISSUE THREAD

**Issue by quakenet2** [mozilla-mobile/focus-android#1128]
By default, Mozilla Firefox automatically check update. It automatically send user's information.

Now here's the concern - what about Focus and Klar? (no mention in Wiki)

If such thing exists, I want a switch to disable it because I will use F-Droid to check update.

**Comment by pocmo** [comment]
No, Firefox Focus has no update capabilities. We rely on the app store that you have been using to install Focus (Google Play or F-Droid).

**Comment by quakenet2** [comment]
> Firefox Focus (and Klar, right?) has no update capabilities

Nice to know. And thanks for adding "documentation" tag.
