### ISSUE TITLE
Add an option to disguise itself as Mozilla Firefox Android.

### ISSUE THREAD

**Issue by quakenet2** [mozilla-mobile/focus-android#1129]
https://github.com/mozilla-mobile/focus-android/issues/902
https://github.com/mozilla-mobile/focus-android/issues/444

Can I suggest a simple fix?

Why not add a switch to force Focus/Klar to use Mozilla Firefox Android's user agent?
This will make an observer harder to identify. You can set that button OFF by default.

(O--) Use Mozilla Firefox Android's user agent

OFF(default) = Say Focus on UserAgent. It's like saying "Hello! I'm Focus! Don't spy on me!" to public.
ON = Use latest Mozilla Firefox Android's user agent, making it hard to distinguish from Android user.

**Comment by quakenet2** [comment]
FYI

Orfox:
Mozilla/5.0 (Android; Mobile; rv:31.0) Gecko/31.0 Firefox/31.0
Mozilla/5.0 (Android; Mobile; rv:38.0) Gecko/38.0 Firefox/38.0
Mozilla Firefox Android:
Mozilla/5.0 (Android; Mobile; rv:55.0) Gecko/55.0 Firefox/55.0

https://dev.guardianproject.info/issues/5404

**Comment by quakenet2** [comment]
FYI

> For comparison, Firefox for Android only reveals Android version, Orfox reveals none of the above.
> https://github.com/brave/browser-android-tabs/issues/130

**Comment by pocmo** [comment]
In #55 we decided against using a "Firefox" user agent as both apps use different rendering engines. Some Websites will expect Firefox's Gecko engine to render the page when they see the term "Firefox" in the user agent and then send us code that Focus might not be able to render correctly.

**Comment by quakenet2** [comment]
I see. But what if the user simply disable Javascript? (I don't use Javascript in Orfox(Mozilla Firefox Android Fork).)

If that's a problem, how about adding a "[X] I'm an advanced user" checkbox or menu to let people
allow to change this settings for their own use? Just like "about:config" in Mozilla Firefox.

**Comment by pocmo** [comment]
For disabling JavaScript -> #907 

Fingerprinting is currently a topic for the "Denim" milestone:
* https://github.com/mozilla-mobile/focus-android/projects/2
* https://wiki.mozilla.org/Mobile/Focus/Android/Train_Schedule

**Comment by pocmo** [comment]
This will be revisited as part of the fingerprinting update.
