### ISSUE TITLE
Consider aligning toolbar title left on tablets

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1131]
Current layout:

![nexus9](https://user-images.githubusercontent.com/89638/29209405-966772f8-7e8e-11e7-9bed-873d4fd68c6e.png)

**Comment by bbinto** [comment]
Should that not be left-aligned as per Google's guidelines?

**Comment by pocmo** [comment]
Oops, yeah, I updated the title.

**Comment by pocmo** [comment]
Screenshot:

![left_title_bar](https://user-images.githubusercontent.com/89638/29358781-9226bdce-827c-11e7-8a16-78c927bf886a.png)

Layout:

![layout](https://user-images.githubusercontent.com/89638/29358788-9684ff02-827c-11e7-980f-9517990a9b90.png)

**Comment by pocmo** [comment]
@antlam I've sent you build 2574.

**Comment by antlam** [comment]
Thanks @pocmo looks good!
