### ISSUE TITLE
Show more of progress bar when toolbar is collapsed 

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1132]
When a website is loading and the toolbar is collapsed then we show 1dp of the progress bar:

![loading_bar_collapsed](https://user-images.githubusercontent.com/89638/29212867-f99b52a6-7ea0-11e7-8b7f-8897651bbe82.png)

Talked to @antlam. Instead we could show the full 3dp progress bar.

**Comment by pocmo** [comment]
This would be easy to do. Here's a screenshot:

![progress_full](https://user-images.githubusercontent.com/89638/29213133-365830c8-7ea2-11e7-9579-3542e2478cc6.png)

@antlam What do you think?

**Comment by antlam** [comment]
@pocmo wow, that's pretty amazing!  I think that looks great!

How hard would it be to also move it up 1 dp so that it partly overlaps the status bar/collapsed app bar? 😬

**Comment by pocmo** [comment]
Uuuh, now you are getting greedy. The progress bar is still part of the container that scrolls below the status bar - it is just exceeds the bounds of it by 3 dp now (when collapsed).
I can try to get it to draw on top of the status bar by setting elevation on it - but it might start to cast its own shadow.

**Comment by antlam** [comment]
> Uuuh, now you are getting greedy.

Yes I am. This is fine :)
