### ISSUE TITLE
[1.2-RC2] welcome text stutters on homepage when returning to Focus

### ISSUE THREAD

**Issue by phunkular** [mozilla-mobile/focus-android#1135]
When opening Firefox Focus for the first time, the keyboard pops up and the "Firefox focus ... automatic private browsing. browse. erase. repeat" slides up to make room for the keyboard nice and smoothly.

However, if I press home and return to focus later, the text stutters into view in a jarring way. This seems to only happen when leaving the app with the keyboard open.

If instead I press 'back' to minimize the keyboard first before 'home' and finally return to focus from the home screen later on, the keyboard pops up and there is no stutter.

Returning to Focus via the recents page has the same stuttering effect,

thanks

**Comment by pocmo** [comment]
When resuming Focus the text moves down (because there's no keyboard on resume) then the keyboard comes up and the text goes up again. So I see the text move down and up again. Which is indeed looking a bit clunky. Is this what you are seeing too?

**Comment by phunkular** [comment]
yes it is.

When you leave the homepage with the keyboard out, the text is higher up. When you return, the text is still higher up. Then a fraction of a second later, the keyboard pops up and the text jumps down to its original spot in the middle and slides back up with the keyboard. As this happens within a second it looks messy as the text looks like it disappears and you then catch the end of the animation of it sliding back to where it started.

This is a common problem with apps that open the keyboard on startup and especially if you have any animations. I believe it is because when the app is opened it draws based on the size of the screen without the keyboard and then when the keyboard is activated in the middle of this process, the app has to redraw based on the  new size of the screen minus the keyboard... It always looks jagged. I noticed this with KISS launcher too. I think that the easiest solution is to have static content or to design around the premise that the keyboard is always open in the first place.

thanks

**Comment by brampitoyo** [comment]
There seems to be 3 conditions with 3 different animations here.

1. Cold start
![focus-android-cold-start](https://user-images.githubusercontent.com/51007/29515685-973f54be-8697-11e7-90e3-0238896df2d4.gif)

2. Warm start (returning to Focus) *without closing* the keyboard. This is where the logo first move down and then back up.
![focus-android-warm-start-keyboard-open](https://user-images.githubusercontent.com/51007/29515705-aa98f2e0-8697-11e7-913f-3ae1d5458fb1.gif)

3. Warm start (returning to Focus) *after closing* the keyboard
![focus-android-warm-start-keyboard-closed](https://user-images.githubusercontent.com/51007/29515736-c7530c18-8697-11e7-936a-4d30c1995d7d.gif)

On first glance – I might be wrong – there seems to be two easy ways to remove the awkward animation on condition 2.

Either:
* Remove the downward motion part of the logo, so the logo will only move up.
* Or, reuse the same animation on condition 3

I’d prefer a solution that will minimise variations for different states, as this will help keep our UX consistent. Maybe one for cold start and one for warm start?

**Comment by antlam** [comment]
Talked to @pocmo he's going to try bringing down the keyboard when Focus goes into the background
