### ISSUE TITLE
Word mark not moving up when app is set to Russian?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1137]
Somehow the home view looks different in Russian. The word mark is supposed to move up once the keyboard show sup.

![home_view_1502387735822](https://user-images.githubusercontent.com/89638/29268171-f935a792-80eb-11e7-89b7-4c59649ede67.png)

**Comment by npark-mozilla** [comment]
this happens intermittently, especially when I visit the focus app after putting it to background for a while (like, a day)

**Comment by pocmo** [comment]
@npark-mozilla Did you see this happen for all locales or Russian in particular? And did you see it when using the app yourself or only when taking screenshots?

As this is not easily reproducible I was wondering whether we are just taking the screenshot very early here (before the animation completed).

**Comment by npark-mozilla** [comment]
@pocmo I saw this for Russian only so far, when I was using it myself, but I haven't seen it since we added a patch that makes animation smooth after coming back from minimized state though.

**Comment by pocmo** [comment]
@npark-mozilla Oh right, I forgot about that one. It could have fixed that.

**Comment by pocmo** [comment]
For reference this was #1135.

**Comment by lobontiumira** [comment]
This issue no longer reproduces on RC 92.1.1 with Samsung Galaxy Note 8 (Android 9), OnePlus 5T (Android 10), nor on Samsung Galaxy Tab a6 (Android 5.1.1).

![russian](https://user-images.githubusercontent.com/40694158/134334813-02739672-ae82-4c7f-914d-57413d4e5d8b.jpg)
