### ISSUE TITLE
changing stealth settings may display (outdated) screenshot of focus in recent apps list

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1140]
STR:
Turn on stealth, go to webpage.
Go to settings, turn off stealth.
Go back to the webpage, and press recent apps button, check focus screenshot is shown
Go to settings, turn on stealth, exit settings to the web view, go to another website
Press recent apps button

Device:
z3c 5.1

Expected:
No display of web view should be shown
Actual:
Outdated screenshot of the previous web view is shown.

Workaround:
go to homescreen, and return to focus app, then press recent apps button.
I think we discussed it a while ago (not a regression/blocker), but haven't filed a bug about it. Would be a good idea to keep track of it.

**Comment by pocmo** [comment]
Yeah, we discussed this for our 1.0 release. Android will always show the screenshot of the last time the app was paused and it was allowed to take a screenshot. We can't influence this behavior unfortunately. :(
Back then the decision was made to release as-is.
