### ISSUE TITLE
Create public beta test

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1150]
We do not have automated releases yet. But it would still be helpful to push RC builds (that we already upload to Google Play) to a Beta audience to identify issues before sending it to production. I would like this to be a "public" beta where everyone who is interested can join.

**Comment by pocmo** [comment]
Also see #1156 - We need to get builds out to a test audience earlier.

**Comment by bbinto** [comment]
Barbara to setup legal/marketing related tasks

**Comment by pocmo** [comment]
Beta channel is now live (for now with the same build as the release channel).

**Comment by pocmo** [comment]
@eleemoz You can now test the flow in Google Play! :)
