### ISSUE TITLE
Have an option to bypass Strict Mode on UITests

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1152]
Some version of API/simulator combination causes the Focus app to crash early when strict mode is enabled. For example, Nexus 9 fails locally, but for some reason BB Nexus 9 setup currents runs tests with no issues.  If there is a way to turn off strict mode (i.e. command-line parameter) then we won't have to worry about picking the right sim/API for testing.

**Comment by pocmo** [comment]
Fixed in 25fe3b3f61d0bc1875b63ab1f68426b0792353e0
