### ISSUE TITLE
email client subject field not populated

### ISSUE THREAD

**Issue by njeyaakili** [mozilla-mobile/focus-android#1154]
When using the "share" capability to an email client, the "Subject:" field isn't populated with the page title. This does work properly with Firefox with both tested mail clients.

Tested: 

browsers:
Focus - 1.2 - doesn't populate
Firefox - 54.0.1 - populates

email clients:
Gmail - 7.7.16.164685024 
K-9 mail - 5.207

**Comment by bbinto** [comment]
UX: XS Eng: M
