### ISSUE TITLE
Guess better file names for downloads

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#1165]
An issue that came up in Play reviews and in my own testing, file names from many different domains (Google Drive, Dropbox, etc) are guessed using URLUtil.guessFileName and are often "guessed" as long random strings of letters + numbers or something else not representative of the file. Would be good to investigate if there's a better way to do this (and if so, replace where we guess the file name).

<img width="282" alt="screen shot 2017-08-17 at 10 16 51 am" src="https://user-images.githubusercontent.com/25442310/29424681-82ac154c-8335-11e7-89f8-da9baa5f2f26.png">

**Comment by ymhuang0808** [comment]
Hi @ekager 

I tested on Google Drive, `Content-Disposition` header looks like `attachment;filename="demo.zip";filename*=UTF-8''demo.zip`. However, the regular expression pattern in `URLUtil` is `attachment;\s*filename\s*=\s*("?)([^"]*)\1\s*$`.

 I don't know why the regex expression doesn't allow the `filename*` pattern.

Code snippet in `URLUtil`: https://github.com/android/platform_frameworks_base/blob/cb3c24e36b9efad8adeb72b5f814bf35c5db60bb/core/java/android/webkit/URLUtil.java#L387-L389

**Comment by Benestar** [comment]
Hi, I would like to work on this as it is labeled as a good first bug. However, I wonder how the `filename*` field should be handled. We can either just ignore it or we use that instead of the `filename` value if present. However, the latter may result in paths containing non-ASCII characters and I'm not sure whether Android's DownloadManager will handle these correctly in all cases.

**Comment by ekager** [comment]
Thanks for your help! All valid concerns! It would be great to start by testing downloads from Google Drive and Dropbox and any others we could find with strange file names in other Android browsers to see if they have more representative names. 
		
		

		Get Outlook for iOS
	




On Fri, Aug 25, 2017 at 5:25 AM -0700, "Bene" <notifications@github.com> wrote:












Hi, I would like to work on this as it is labeled as a good first bug. However, I wonder how the filename* field should be handled. We can either just ignore it or we use that instead of the filename value if present. However, the latter may result in paths containing non-ASCII characters and I'm not sure whether Android's DownloadManager will handle these correctly in all cases.

**Comment by ymhuang0808** [comment]
@Benestar Quote from [RFC6266](https://tools.ietf.org/html/rfc6266#section-4.3):

> Many user agent implementations predating this specification do not
   understand the "filename*" parameter.  Therefore, when both
   "filename" and "filename*" are present in a single header field
   value, recipients SHOULD pick "filename*" and ignore "filename".
   This way, senders can avoid special-casing specific user agents by
   sending both the more expressive "filename*" parameter, and the
   "filename" parameter as fallback for legacy recipients (see Section 5
   for an example).

I tested to download a file naming "**demo.zip 的副本**" in Traditional Chinese from Google Drive. The Content-Disposition HTTP Header is `attachment;filename="demo.zip ___";filename*=UTF-8''demo.zip%20%E7%9A%84%E5%89%AF%E6%9C%AC`.  And the value of `filename*` could be decoded by `URLDecoder` in UTF-8.

**Comment by Benestar** [comment]
Thanks for your comments so far. 😄 I have now created a pull request with an improved regex that can handle the `filename*` field and UTF-8 encoded file names correctly.
