### ISSUE TITLE
Add in-app link to Focus Privacy notice in "About" page

### ISSUE THREAD

**Issue by eleemoz** [mozilla-mobile/focus-android#1173]
Link to privacy notice is missing from About page.

https://www.mozilla.org/privacy/firefox-focus/

**Comment by lime124** [comment]
Here is my brilliant solution! Based on what's already there, it seemed to make more sense to put it under "Your Rights" in main settings page. That said, I think we need to re-organize our settings in some other issue. It's getting pretty long.

![settings-android](https://user-images.githubusercontent.com/287322/29639870-2da8d91e-8811-11e7-98fa-c84e431e45c2.png)

@mheubusch approved the string for iOS already.

**Comment by pocmo** [comment]
@eleemoz Should Klar builds link to the same URL?

**Comment by pocmo** [comment]
Feature landed in Cobalt. I'll re-open if need to update the URL.

**Comment by eleemoz** [comment]
It is workable to have the same URL for most cases, since Firefox Focus's privacy notice redirects to Klar for DE locales. However, the actual URL of the Klar privacy notice would be https://www.mozilla.org/de/privacy/firefox-klar/ -- which would thus also catch the few folks running Klar in another language.
