### ISSUE TITLE
Remove dependency on com.google.android.gms:play-services-analytics

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/focus-android#1174]
It unclear why this (closed source proprietary) library is in the Focus APK. Focus does not not google analytics and neither does Adjust. If it is save to remove this because nobody is calling the code then that is probably a good idea.

**Comment by pocmo** [comment]
It's in there because of Adjust:
https://github.com/adjust/android_sdk#sdk-gps
> Since the 1st of August of 2014, apps in the Google Play Store must use the Google Advertising ID to uniquely identify devices. To allow the adjust SDK to use the Google Advertising ID, you must integrate the Google Play Services. If you haven't done this yet, follow these steps: [..]

**Comment by bbinto** [comment]
I'll flag this with Mike Han to see if Adjust can provide another solution

**Comment by pocmo** [comment]
I'll move this into the "blocked" column so that we can revisit this.

**Comment by eldk** [comment]
Hello,

https://www.mozilla.org/en-US/foundation/licensing/

I think it's important.

Thanks,

Eric

**Comment by pocmo** [comment]
https://github.com/adjust/android_sdk/issues/297
