### ISSUE TITLE
What about adding Google Encrypted?

### ISSUE THREAD

**Issue by concatime** [mozilla-mobile/focus-android#1175]
Hi. Could you please add Google Encrypted to search engines? Something like [this](//gist.github.com/concatime/ad12dabe6c1e5468a2afb6961b79713a). It would be really nice!

** Didn't check if the XML files work perfectly, it's just a draft.

More information about it [here](//googleblog.blogspot.ca/2010/05/search-more-securely-with-encrypted.html).

**Comment by bbinto** [comment]
Could you please elaborate more on what issue/problem you are facing and trying to solve with the integration of this?

**Comment by concatime** [comment]
Well, I can't explain it more better than what Adi did on [Security.StackExchange](//security.stackexchange.com/a/32374). The main idea is advantage websites using HTTPS.

**Comment by wesdawg** [comment]
@concatime encrypted.google.com is no longer necessary since www.google.com now supports full encryption using TLS and QUIC.
There is no additional benefit to using the `encrypted` subdomain.

See https://productforums.google.com/forum/#!topic/websearch/1LCUfb5q2O8
