### ISSUE TITLE
[Klar] What is the string of User Agent?

### ISSUE THREAD

**Issue by quakenet2** [mozilla-mobile/focus-android#1178]
I need to know Klar's User Agent string. I could do this myself but unfortunately Klar didn't provide proxy support yet, so I'm asking here.

Please consider writing a wiki like this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox

So, what is Klar's UserAgent? (I don't care Focus)

1. https://f-droid.org/packages/org.mozilla.klar/ <---- this one's v1.1
2. Current Klar's UA

**Comment by quakenet2** [comment]
Also can anyone show the result of these? I need those return result.

> !!window.opera
> !!window.chrome
> navigator.doNotTrack

> <html><script>
> if (!!window.opera){alert('I am opera');}// 1
> if (!!window.chrome){alert('I am chrome');}// 2
> if (navigator.doNotTrack==1){alert('DNT okay');}// 3
> </script></html>

expecting:
1 --- never happen
2 --- happen or not??
3 --- should happen

(again, I would do this myself if Klar support proxy)

**Comment by xfix** [comment]
Here is a sample user agent (note that it may vary between devices)

> Mozilla/5.0 (Linux; Android 7.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Klar/1.2.1 Chrome/51.0.2704.90 Mobile Safari/537.36

window.opera and window.chrome is `undefined`, `navigator.doNotTrack` is `null` (for some reason)

**Comment by mcomella** [comment]
For this bug, please create a page on our Wiki describing the User Agent and its meaning, like the link in the first comment. Please explain if there are any differences between Focus and Klar and include a "Last updated on <date>, with <commit>" at the bottom of the page.

**Comment by mcomella** [comment]
> navigator.doNotTrack is null (for some reason)

 [Do Not Track is officially sent as a header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT). [According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/navigator/doNotTrack), `navigator.doNotTrack` is an experimental JS API for this info and has an unknown implementation status on Android mobile. Since we're using WebView, we're relying on its behavior.

**Comment by miketaylr** [comment]
I've updated the docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#Klar_for_Android

This can probably be closed now. cc @mcomella

**Comment by mcomella** [comment]
@ekager Can you see if this can be closed?

**Comment by ekager** [comment]
This can be closed thanks @miketaylr ! Just a note that it's actually not until 7.0 that Klar has been GV if we want to get pedantic. :)

**Comment by mcomella** [comment]
On Tue, Oct 2, 2018 at 6:59 AM Emily Kager <notifications@github.com> wrote:

> This can be closed thanks @miketaylr <https://github.com/miketaylr> !
> Just a note that it's actually not until 7.0 that Klar has been GV if we
> want to get pedantic. :)
>

fwiw, I've been thinking we should move our docs in-tree so that they're
versioned by release, which would solve this problem. This is an annoying
problem for me, especially for telemetry! :P
