### ISSUE TITLE
Header and URL bar has seizure like flickers when scrolling horizontal images

### ISSUE THREAD

**Issue by clujin** [mozilla-mobile/focus-android#1179]
I'm using Android 7.1.2 with the latest Firefox Focus.

Steps to reproduce:
- Go to www.google.com
- Search something with news article that are placed horizontally like search for 'eclipse'.
- Horizontally scroll the news article bar left to right or right to left.

You see the header/notification bar at top flickering causing some degree of discomfort.

**Comment by mcomella** [comment]
I can reproduce on an API 23 Nexus 5X emulator. Some cases when we change the URL bar colors:
1) Loading pages
2) When enabling/disabling tracking protection

To debug, I'd recommend throwing a breakpoint in where we change the colors and seeing where it's getting called from.
