### ISSUE TITLE
Shortcuts to web pages on the launcher

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/focus-android#1181]
To keep Focus simple and uncluttered, it could be useful to be able to add shortcuts to web pages on the launcher screens. It could be kind of a replacement for bookmarks management.

**Comment by klint** [comment]
With a menu option in Focus itself

**Comment by klint** [comment]
With a menu option in Focus itself

**Comment by pocmo** [comment]
We implemented this in #833 and it should be available in Focus 1.2.1. The feature is currently hidden in Android O though (we need to implement a new API to support it).
