### ISSUE TITLE
Pinch zooming in focus doesn't preserve focus point

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/focus-android#1185]
When I pinch zoom in Focus on Android, the focus point of the pinch is not preserved. The page jumps when the pinch starts and ends, and it's very distracting - causes me to lose my place quite often.

**Comment by pocmo** [comment]
I don't seem to reproduce (or understand) this.

* What Android version and device are you using?
* Is this more noticeable on a specific page?
* Do you see the same behavior in Chrome?

**Comment by staktrace** [comment]
On a Sony Z3C (recycled FxOS phone) running Cyanogen Mod 12 (~Android 5.1.1)
I can repro it on many pages. Just now I did it on https://en.wikipedia.org/wiki/%22Hello,_World!%22_program
More specific STR:
- Load the above URL
- Scroll down a little bit so the first paragraph of the content is fully in view
- Place one finger on the first line of the paragraph (where it says "Hello, World!" in bold)
- Place second finger on the last line of the paragraph ("new to a language")
- As soon as the second finger goes down, the page "jumps"
- Now move your fingers around, this part is ok - the page scales in or out
- Lift the second finger, again the page "jumps"

I can make a video if you still can't repro.

And no, I don't see the same behaviour in Chrome.

**Comment by mcomella** [comment]
@staktrace Can you still reproduce this? I'm wondering if this was fixed when the WebView version was upgraded. Thanks!

**Comment by staktrace** [comment]
I've since uninstalled Focus so I'm not sure if this is still happening. It was happening last time I checked (which was after I installed the Android System WebView to fix #1238).

**Comment by pocmo** [comment]
FYI: We also landed a patch that fixed some problems with NestedWebView - which could have fixed this here too.

**Comment by bbinto** [comment]
Closing this unless you find another issue with this again
