### ISSUE TITLE
check_translations.py: Allow omitting duplicate placeholders

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1186]
See #1183.

We have a string that contains the same placeholder twice, e.g. "Hello %1$s World %1$s". Some translations only needed this placeholder once, e.g. "Hallo %1$s Welt". Our check_translations.py script failed the build because the translated string does not include all placeholders. We should check that all placeholders are in the translated string, but we should not enforce how often the placeholder is used.

**Comment by pocmo** [comment]
@mastizada You wrote the first version of check_translations.py -- in case you are interested in picking up this ehancement. :)

**Comment by mastizada** [comment]
@pocmo hi, of course, As I said before, will be happy for any python tasks in this project :)
So, as I understood, Android allows using multiple tags (as far as it is same tag) even if it is not matching the original string. Will check it ASAP.

**Comment by pocmo** [comment]
Yeah, to give you a real example from the automation failure:

values/strings.xml

**Comment by pocmo** [comment]
This just broke our release build (Esperanto only used the placeholder once). :)

**Comment by flodolo** [comment]
I think it would be enough to check if the placeholder exist in the target string, and only log a warning when the count doesn't match.
https://github.com/mozilla-mobile/focus-android/blob/master/tools/l10n/check_translations.py#L60

**Comment by mastizada** [comment]
I'm planning to send PR tonight, sorry for delay.

**Comment by mastizada** [comment]
I'm planning to send PR tonight, sorry for delay.
