### ISSUE TITLE
Switch to native app if available?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#119]
On Android specific URLs can be handled by apps that registered for it. For example a specific facebook URL could be opened in the Facebook app and display the content there. In such a scenario we show the little Android icon in the URL bar in Fennec. Do we want something similar for Focus?

**Comment by ahunt** [comment]
It looks like we have a js implementation to do app detection in fennec:
https://dxr.mozilla.org/mozilla-central/source/mobile/android/modules/HelperApps.jsm?q=path%3AHelperApps.jsm&redirect_type=single#107

**Comment by pocmo** [comment]
I talked to antlam and we might add this in #26 (the native app for this URL is treated like a "default browser").

**Comment by pocmo** [comment]
See #26.
