### ISSUE TITLE
App name should be put inside "Open With" string

### ISSUE THREAD

**Issue by petercpg** [mozilla-mobile/focus-android#120]
String `menu_open_with` does not include the app name to open with, which violates the grammar in Chinese. We usually use 使用 {app} 開啟, literally 'Use {app} to Open'.

The string itself should be changed to something like "Open With %s".

**Comment by ahunt** [comment]
FWIW we don't actually do anything with "Open With" right now (i.e. we have a menu item which actually only shows "open with" and does nothing and has no app now).

We'll be adding the actual functionality in Bug #26, but I'll try to fix the string now - that said, I don't know if this string will actually be used in future.

**Comment by pocmo** [comment]
Yeah, this string should go away soon. I'm working on the final menu (#52) and as part of that I'll talk to antlam to figure out how the browser switching should work (#26).

**Comment by pocmo** [comment]
#26 will introduce two strings:
* "Open with %1$s" - For opening the current URL in another browser or app
* "Open with…" - If there are multiple other options. Selecting this item will show a screen with all available options to choose from.

Mock from #26:
![screen shot 2017-03-02 at 12 01 18 pm](https://cloud.githubusercontent.com/assets/1994820/23524558/05ce44b0-ff40-11e6-8d5f-0dac8333fcfb.png)
