### ISSUE TITLE
"What's New" in app

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1201]
We want to inform our users of updates *inside* the app, rather than via the store update description.

UX to come up with a solution how to achieve that.

Requirements:
- needs to show the content of a What's New SUMO Page 
- shows after update of the app
- the presentation does not conflict with the simplicity of the app
- easily to be localized and to be updated if needed (without releasing another app update)

**Comment by gonzalde** [comment]
We could just add a small notification in the search bar with a message below indicating there was an update which can be clicked on to show whats new with the update. I attached a simple mock-up.
[updates-focus.pdf](https://github.com/mozilla-mobile/focus-android/files/1249802/updates-focus.pdf)

**Comment by gonzalde** [comment]
also should only be showm when starting a new search and not when browsing other pages

**Comment by bbinto** [comment]
Eng: S
UX: L

**Comment by antlam** [comment]
We should talk about this next week with the iOS issue (also Ebony, also L)

**Comment by antlam** [comment]
Moving to Folly for now, CC @bbinto

**Comment by lime124** [comment]
![ixd flow - what s new cards](https://user-images.githubusercontent.com/287322/30870002-8b45918e-a297-11e7-8318-843f0883e71b.png)
![ixd flow - what s new](https://user-images.githubusercontent.com/287322/30870003-8b4d4b40-a297-11e7-9c2b-2cb5e2bccf58.png)

Strings are TBD and visual spec is coming.LMK if you have any questions!

/cc @bbinto @pocmo

**Comment by bbinto** [comment]
@lime124 what's the difference between the top and the bottom spec? Or is this for us to choose what we prefer?

I'm a bit nervous to embed so much localizable text inside the app while features/updates listed in there could potentially fall off the release after string freeze. I was under the impressing we'd be pulling/linking to the SUMO page (which would be up to date at launch & localized).

Thoughts?

**Comment by pocmo** [comment]
Yeah, having those strings in the app can become a problem. Linking out to SUMO and giving the community indefinitely time to create those pages in languages they can maintain is definitely easier for us!

In Fennec we have this "home banner" concept which shows an icon and message at the bottom of the screen. Almost like a Snackbar[1] with a link. I wonder if that's a helpful concept here too. Visually your design is way nicer than a boring SUMO page though. :)

[1] https://material.io/guidelines/components/snackbars-toasts.html

**Comment by lime124** [comment]
@bbinto the spec is both pages. there was too much to fit on one page.

@brjones and I discussed that as well and we agree that string freeze makes it a lot more complicated as we don't know what's doing to get in or not until the end of the sprint. 

@pocmo is it possible to have the strings on a webpage and then pull them into that UI? Is there something we can do to accomplish both goals.

**Comment by pocmo** [comment]
> @pocmo is it possible to have the strings on a webpage and then pull them into that UI? Is there something we can do to accomplish both goals.

It's tricky. We would need a "loading" UI and loading the strings could fail of course. We'd almost build a little second browser for loading and rendering the "what's new" section. My gut feeling is that this would go from "S" to "L" for the engineering part.

**Comment by lime124** [comment]
Update: Card UI is TBD, so the what happens when you tap on "what's new" in the overflow menu is not final.

I believe the only strings that need to go into the actual app are:
"What's New" - overflow menu
and potentially "Next" and "Close" - card UI if that goes in
@BrianNJones what do you think of those strings?

**Comment by lime124** [comment]
This doesn't look like it got updated. @brianNJones approved the strings earlier today.

**Comment by BrianNJones** [comment]
That's on me, Tif. I forgot to ask Anthony to updated to strings-approved. Thank you!

**Comment by lime124** [comment]
Updated to remove card UI. Also here is the visual spec.

![ixd flow - what s new android](https://user-images.githubusercontent.com/287322/31158663-2e8b28fa-a878-11e7-848a-ca1160ee1f98.png)
![visual design - what s new android](https://user-images.githubusercontent.com/287322/31158662-2e8a2298-a878-11e7-970c-bbcc11317698.png)

@antlam is going to provide the overflow icon with the indicator. 

LMK if there are any questions or comments. Thanks!

**Comment by pocmo** [comment]
I think I'm going to try drawing the indicator icon in code - at least if it's only a colored circle then creating an "XML drawable" is simpler and it's a tiny file. However I'm unable to read the last spec slide. When opening it at full size the text gets blurry.

**Comment by antlam** [comment]
![screen shot 2017-10-04 at 10 51 49 am](https://user-images.githubusercontent.com/1994820/31191132-0e4aa50a-a8f2-11e7-9748-ade980bfe880.png)

@pocmo if you're drawing the dot in code for the overflow icon, here's a spec that might help.

Blue dot is #45A1FF (Blue 40)

**Comment by pocmo** [comment]
![whatsnew](https://user-images.githubusercontent.com/89638/31229125-fd4438cc-a9df-11e7-877a-1bdad990e3b5.png)

@lime124 How does this look like?

**Comment by lime124** [comment]
@pocmo and i chatted over Slack. Just a tiny tweak on padding. We're also going to remove "about" and "your rights" for a bit of menu consolidation. That's all I see. Thanks so much @pocmo !
