### ISSUE TITLE
Add telemetry for "screenshotting"

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1202]
If stealth mode is turned off, users can take screenshots. We'd like to know if that's a feature people use frequently. Therefore we'd need to add a probe

**Comment by pocmo** [comment]
This is quite tricky and almost impossible to do right:

* The system doesn't tell us when the user has taken a screenshot. So we never know for sure.
* What we tried in Fennec is watching the picture folder for new image with "screenshot" in their name. If there's a new one and we are in the front then we assume the user just took a screenshot.
* Watching the public folder only works on Android 6+ if we have the permission to do so. Focus (and also Fennec) only asks for the permission when we need it for downloading. Before this happens we can't monitor the folder.
* The Fennec implementation is/was very fragile and was over-counting screenshots taken.

**Comment by bbinto** [comment]
Thanks for the clarification. So this is not worth the effort. Closing it.
