### ISSUE TITLE
Unable to open comments page on reddit ( with some workaround)

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#1207]
1. Go to reddit and choose a well commented thread and tap the comments ( [ex](https://www.reddit.com/r/gaming/comments/6vwfmz/the_story_for_halflife_3_was_just_released_by_the) )

Expected Results - page is loaded with comments on
Actual Results - page returns 404  

See video - https://youtu.be/OQOuYM9lWPQ ( tapped Continue, Cancel, Tap me back)
Same steps on Fennec Androdi return the comments page.

**Comment by bbinto** [comment]
@ioana-chiorean is this still an issue?

**Comment by SubhrajyotiSen** [comment]
I tired it on the latest nightly and there seems to be no issue

**Comment by ioana-chiorean** [comment]
Indeed. Tried the same again and it doesn't reproduce anymore.
