### ISSUE TITLE
Tapping URL bar after search should highlight the searched terms 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#1208]
Steps:
1. In the url bar, type search term (not URL) like "hello world" then press enter
- Search result of the term in selected search engine is displayed
- URL bar displays full URL of search
2. Tap URL bar

Expected Result:
- the original search term is displayed and highlighted
Actual Result:
- the URL of the search is highlighted 

![photo_2017-08-25_15-36-53](https://user-images.githubusercontent.com/1391451/29714409-c8aba414-89ab-11e7-874c-369e60c3bc55.jpg)

**Comment by npark-mozilla** [comment]
ah, this feature was reverted, I should've marked it in the TC
