### ISSUE TITLE
Local CDN emulation

### ISSUE THREAD

**Issue by nico202** [mozilla-mobile/focus-android#1212]
Hi, I don't think this is currently implemented; I think that the "Local CDN emulation" (the one done by [decentraleyes](https://decentraleyes.org/) is quite important for privacy and should be integrated.

cc @Synzvato (decentraleyes dev)

Thanks, Nicolò

**Comment by pocmo** [comment]
* https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/
* https://github.com/Synzvato/decentraleyes/wiki/Simple-Introduction

**Comment by Synzvato** [comment]
It's very nice to hear that the concept of locally intercepting Content Delivery Network requests is up for consideration, so thanks @nico202 for bringing it to the table. Needless to say, I think CDN dominance is a significant privacy issue, and I'd be happy to see a wider adoption of this countermeasure.

Should this feature be accepted, and should you be interested my help, I would be happy to contribute, collaborate, and share what I've found out over the past couple of years.
