### ISSUE TITLE
Android 8: Create adaptive icons for home screen shortcuts

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1214]
Otherwise our shortcuts will be put into a white circle:

![launcher_guardian](https://user-images.githubusercontent.com/89638/29767082-5c6e6c5e-8be1-11e7-9e8a-11b6bcd52f22.png)

**Comment by bbinto** [comment]
UX: S
Eng: S

**Comment by antlam** [comment]
![screen shot 2017-09-25 at 11 41 28 am](https://user-images.githubusercontent.com/1994820/30825068-88e5b31c-a1e6-11e7-9906-0756cd11e2e3.png)

[Background Shortcut.zip](https://github.com/mozilla-mobile/focus-android/files/1330505/Background.Shortcut.zip)

Here's the background layer for adaptive icons in XHDPI, XXHDPI, and XXXHDPI.

The foreground layer is just a single alphabet character at 36sp, Roboto Regular, White color.

**Comment by mcomella** [comment]
> Here's the background layer for adaptive icons in XHDPI, XXHDPI, and XXXHDPI.

I opted to just use a color instead (to save APK size): it's `#401072`.

> The foreground layer is just a single alphabet character at 36sp

These icons don't change size with font size so I used 36dp instead.

**Comment by antlam** [comment]
@mcomella correction, the color is actually #4C0074, can you please update?

**Comment by mcomella** [comment]
@antlam Done. A screenshot is available in the PR: https://user-images.githubusercontent.com/759372/31290798-a34fc7f2-aa82-11e7-8f66-bc9f83c2d783.png
