### ISSUE TITLE
Page contents not rendered after a certain scroll offset

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/focus-android#1238]
Load https://sourceforge.net/p/nas4free/code/HEAD/tree/trunk/www/disks_manage.php in Focus and scroll down. At around line 106 of the code (on my Z3C) the content stops rendering. Doesn't happen in Firefox.

**Comment by pocmo** [comment]
* Does this happen in Chrome?
* What Android version is installed on your device?

**Comment by staktrace** [comment]
- No. Focus also renders the page more zoomed in than either Chrome or FF, but unsure if that's related.
- CyanogenMod 12.1 (~Android 5.1.1)

**Comment by mcomella** [comment]
I cannot reproduce this: Galaxy S5 Play Beta & API 23 emulator.

@staktrace Are you still seeing this issue?

**Comment by staktrace** [comment]
@mcomella Yeah I can still reproduce this.

**Comment by pocmo** [comment]
I can't reproduce this on a Z3C locally - the full file is rendered just fine.

@staktrace Can you post the user agent string of your Focus browser (I'm interested in the Android version and WebView/Chrome version)?

**Comment by staktrace** [comment]
@pocmo Mozilla/5.0 (Linux; Android 5.1.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/2.2 Chrome/39.0.0.0 Mobile Safari/537.36

**Comment by staktrace** [comment]
I see the "Android System WebView" app on the play store, but it's not installed. (And therefore probably not up-to-date)

**Comment by pocmo** [comment]
Would you like to try installing/updating it and trying whether this fixes the issue?

We had problems like this before and were wondering how/if we could warn the user about outdated WebView isntallations.

**Comment by staktrace** [comment]
Installing the Android System WebView fixed the issue, thanks!

**Comment by pocmo** [comment]
@staktrace Thank you for testing that!

We should add the user agent to an issue template (#1465) - Seems to be helpful. :)
