### ISSUE TITLE
[Multitasking] Update sheet expand/discard animation

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1245]
#960

See guidelines:
https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions

Example: from the page: "A floating action button transforming into a single sheet of material"

**Comment by jenn-chaulk** [comment]
@bbinto both UX and Eng would like to see this moved out to Folly or Granite

**Comment by antlam** [comment]
I think this is actually less noticeable and therefore lower priority than the other animation (tab switching) in issue #1249. Moving this to the Parking Lot since the other one was also moved out of a release.
