### ISSUE TITLE
eo: number of placeholders not matching, key: firstrun_shortcut_text

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1246]
Source:
> <string name="firstrun_shortcut_text">Return to your favorite sites in %1$s quickly. Just select \"Add to Home screen\" from the %1$s menu.</string>

Translation:
>   <string name="firstrun_shortcut_text">En %1$s, por reiri rapide al viaj plej ŝatataj retejoj, elektu \"Aldoni al hejmekrano\" en la menuo.</string>

**Comment by pocmo** [comment]
@mastizada I thought we fixed this issue?

**Comment by mastizada** [comment]
Yes, it should be only warning as you can see in if-else cases.

**Comment by mastizada** [comment]
Where you got that error? Can't find PR with failes buddybuild

**Comment by pocmo** [comment]
> Yes, it should be only warning as you can see in if-else cases.

Ah, I didn't know that. I was running the script locally before importing new strings (to make sure they are not going to break the build). Because of the output I thought the script stopped. But yeah, it didn't return an error code.

**Comment by mastizada** [comment]
@pocmo I use powerline shell (similar to zsh) which shows return code (0 success, others error) as red and green return icon. It helps a bit.
