### ISSUE TITLE
Crash noticed on BB Run (nexus 9)

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1251]
While loading a webpage, Focus crashed in this run: (https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/build/59a6fdf4e6e7e20001469ada#uitests) with following stacktrace:

08-30 14:12:19.991: D/LifecycleMonitor(6340): Lifecycle status change: org.mozilla.focus.activity.MainActivity@199fc46 in: STOPPED
08-30 14:12:19.991: D/LifecycleMonitor(6340): Lifecycle status change: org.mozilla.focus.activity.MainActivity@199fc46 in: DESTROYED
08-30 14:12:19.994: W/cr_AwContents(6340): Application attempted to call on a destroyed WebView
08-30 14:12:19.994: W/cr_AwContents(6340): java.lang.Throwable
08-30 14:12:19.994: W/cr_AwContents(6340): 	at org.chromium.android_webview.AwContents.isDestroyed(AwContents.java:1224)
08-30 14:12:19.994: W/cr_AwContents(6340): 	at org.chromium.android_webview.AwContents.getTitle(AwContents.java:1999)
08-30 14:12:19.994: W/cr_AwContents(6340): 	at org.chromium.android_webview.AwWebContentsDelegateAdapter.loadingStateChanged(AwWebContentsDelegateAdapter.java:275)
08-30 14:12:19.994: W/cr_AwContents(6340): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
08-30 14:12:19.994: W/cr_AwContents(6340): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
08-30 14:12:19.994: W/cr_AwContents(6340): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-30 14:12:19.994: W/cr_AwContents(6340): 	at android.os.Looper.loop(Looper.java:154)
08-30 14:12:19.994: W/cr_AwContents(6340): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
08-30 14:12:19.994: W/cr_AwContents(6340): 	at java.lang.reflect.Method.invoke(Native Method)
08-30 14:12:19.994: W/cr_AwContents(6340): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
08-30 14:12:19.994: W/cr_AwContents(6340): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by npark-mozilla** [comment]
It's intermittent, feel free to close if this is a trivial issue.

**Comment by npark-mozilla** [comment]
Full log is here: https://s3-us-west-2.amazonaws.com/buddybuild-gcloud-testlab-artifacts/584f67f6f3d6eb01000842d6/59a6fdf4e6e7e20001469ada/2017-08-30_18:09:37.536618_msUl/Nexus9-25-en-portrait/logcat

**Comment by pocmo** [comment]
@npark-mozilla Did this ever happen again?

**Comment by npark-mozilla** [comment]
No... haven't encountered this in BB for a while, let's close it for now.

**Comment by mcomella** [comment]
> Did this ever happen again?

@npark-mozilla If so, please add `help-wanted` if a contributor could help us out here. :)
