### ISSUE TITLE
Adverts shown on google

### ISSUE THREAD

**Issue by simonsteiner1984** [mozilla-mobile/focus-android#1253]
Search for "shoes" on google.com, near top has adverts, not shown if i use ublock origin in firefox

**Comment by bbinto** [comment]
Let's investigate how/if we can change that in the future. For triage today, please share Eng/UX t-shirt sizes

**Comment by simonsteiner1984** [comment]
What do you mean tshirt sizes?

**Comment by bbinto** [comment]
Sorry for the confusion, we will triage the request/issue and decide based on effort/value how to prioritize this request.

**Comment by jenn-chaulk** [comment]
Some inconsistency in message around whether we should be functioning as an ad blocker or not.  This particular ad does not have a tracker component, hence why it is being shown.  We also don't block content related to the site you are on.   Need some clarity on what we should or should not be doing/blocking before we can decide what to do with this.

**Comment by bbinto** [comment]
Thanks Jenn for the comment and explanation. 

@simonsteiner1984 -- let us know if that makes sense to you. 

We follow the guidelines listed here: https://disconnect.me/trackerprotection

We will need to discuss this internally first with our policy / legal team.

**Comment by simonsteiner1984** [comment]
Says you block ads at:
https://play.google.com/store/apps/details?id=org.mozilla.focus&hl=en_GB

**Comment by pocmo** [comment]
Also see #953 for supporting other blocklists.

**Comment by bbinto** [comment]
@pocmo - If we were to do #953, what would be the blocklist to add here to remove the adverts? Is this even possible?

**Comment by pocmo** [comment]
> @pocmo - If we were to do #953, what would be the blocklist to add here to remove the adverts? Is this even possible?

Looking at the popular [ublock extension](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) they come with various [lists of their own](https://github.com/uBlockOrigin/uAssets/tree/master/filters) and support a bunch of [third-party lists](https://github.com/gorhill/uBlock/blob/master/assets/ublock/filter-lists.json). One of the most popular lists is probably [EasyList](https://forums.lanik.us/). That's for example their German list: https://easylist-downloads.adblockplus.org/easylistgermany.txt

I guess we would need to look at some of them and decide which are trustworthy and block content we would like to block. Maintaining those lists seems to be a lot of work that we probably couldn't handle on our own.

Some things to consider:
* Those lists seem to update frequently. A good implementation would require us to download/update those lists often - at best without requiring an app update.
* Those lists are way more complex than our URL based tracking protection lists. They contain some CSS rules to hide elements etc. and other more advanced URL based filter rules. We would need to be able to read and process those lists. In addition to that we would need to check if some of those techniques are even possible on top of WebView.

**Comment by pocmo** [comment]
In some situations reader mode (#802) also removes ads by just showing the content. :)
