### ISSUE TITLE
On Android API 26, Clicking home screen shortcut opens two tabs

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1256]
On Android O, open multiple tabs
Select one tab, and add to homescreen
go to homescreen, and click the shortcut

Expected:
It only opens one more tab 
Actual:
It opens two tabs of identical content

This is not reproducible on API 25

**Comment by pocmo** [comment]
I'm not able to reproduce this (Pixel XL, API 26).

**Comment by npark-mozilla** [comment]
This i can still repro in the API 26 simulator (Pixel) zipped .mov file attached
[Two_tabs.zip](https://github.com/mozilla-mobile/focus-android/files/1278137/Two_tabs.zip)

**Comment by pocmo** [comment]
Oh, wait, I thought when clicking the shortcut we'd open two new tabs. Other than that: Yeah, whenever you click a link/shortcut we open a new tab currently.

**Comment by npark-mozilla** [comment]
On the first time I do it in video, I have no tabs open, went to homescreen, and clicked a shortcut - and it opens two new tabs with identical content.  On second example, one tab was open, then clicked a shortcut, and now the total tab count is 3, instead of 2.  So it seems that on API 26 it opens two new tabs each time?

**Comment by pocmo** [comment]
@npark-mozilla From the "click" sounds it sounds like you are doing double clicks on the icons? :)

**Comment by npark-mozilla** [comment]
@pocmo ahh, you're right! I didn't know Android O actually takes double clicks to open two tabs now.on simulator, I either tapped/double tapped since it made no difference before. Sorry about this, will close it.
