### ISSUE TITLE
Share option has Firefox Focus listed (again?)

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1258]
I thought this was fixed a while ago - is it a regression?

![screen shot 2017-08-31 at 4 46 37 pm](https://user-images.githubusercontent.com/6930774/29944589-054ee970-8e6c-11e7-917c-a629efe6dd14.png)

**Comment by pocmo** [comment]
We removed Focus from the list in "Open with..". This share dialog is from Android and will just show all options. We are not in control what shows up here.
