### ISSUE TITLE
Allow Homescreen shortcuts to display search term when user presses Toolbar

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#1259]
STR:
- do search on url field, like "Hello world"
- Create home screen shortcut
- Erase browsing history, and minimize the app, then click the shortcut
- When the website is displayed, click the url text field

Expected:
- It should display the search term
Actual:
- it displays url

Before the feature was disabled in last release, this behavior was seen, are we still displaying search terms in case of shortcuts as well?

**Comment by pocmo** [comment]
I don't think this is a bug: A home screen shortcut is a permanent "bookmark" of a URL - and not triggering a search.

**Comment by antlam** [comment]
From triage, we discussed how this wasn't a bug per se, but we also talked about how seeing the Search results web page set the expectation for the user that tapping the URL bar would show the search terms and not the long search-query URL.

I think we should rename this issue to be about supporting that "feature". We could call it something like "Allow Homescreen shortcuts to display search term when user presses Toolbar"

@bbinto thoughts?

**Comment by pocmo** [comment]
> Allow Homescreen shortcuts to display search term when user presses Toolbar"

We should be clear here whether we are still going to  "bookmark" the current URL when creating the shortcut -or- if we actually perform a search with the keywords every time the shortcut is opened. Both things could lead to different results (over time).

**Comment by antlam** [comment]
@pocmo very good point. Right now, I'm mostly concerned with the UX. Basically, allowing the user to have a consistent expectation when pressing the toolbar after they arrive at a search results page. 

Now, re-searching (firing off another call to Google/whoever) **every time** the user opens the Home screen shortcut, is something that I feel like is expected for these types of users. Especially given that the loading bar shows up and runs across the screen when I open a shortcut. But I am definitely making an assumption here.

I think our decisions here might have to optimize for users that have added a search results page to their home screen. What experience gives the greatest utility to these users?

Something to keep in mind and think more about.

**Comment by pocmo** [comment]
> @pocmo very good point. Right now, I'm mostly concerned with the UX. Basically, allowing the user to have a consistent expectation when pressing the toolbar after they arrive at a search results page.

Note that even the current implementation (ignoring shortcuts) only shows the keywords if you have actually *entered* them. If you somehow get to a search result page by other means then we won't show the keywords in the URL bar. (That's consistent with Fennec)
