### ISSUE TITLE
Add option to remove notification in notification shade

### ISSUE THREAD

**Issue by spocko** [mozilla-mobile/focus-android#1265]
_Added by @bbinto_

**Why**
- Users expressed being annoyed by notification
- The notification might be confusing to users
- People don't want something running in the phone background

**What**
- Ability to turn off notification

**Acceptance Criteria (how do I know when I’m done?)**
- Notification can be turned off and not visible in notification bar anymore

-----
Feature Request:
Please add an option to disable the persistent notification in the pull down notification shade.

Background:
The history erasing features in Firefox Focus are currently very much "in your face":
- Floating action button (FAB) in lower right.
- Persistent notification in pull down notification shade.
- Popup notification saying "Browsing history has been erased" when returning to start screen.

These features are not useful to me, and just add complexity to the UI. I would greatly prefer for Focus to do its job of erasing history simply and silently. Keep in mind that there is a strong use case for using Focus as the default browser even when not visiting sites with sensitive content. 

I strongly dislike the FAB, but that is discussed in issue #809, so I'll leave it at that.

**Comment by pocmo** [comment]
I understand where you are coming from. However erasing your browsing history at the end of a session is a primary use case.
There are other technical reasons for the notification: As long as its shown we are maintaining your session (and in 2.0 "tabs"). There's no "session restore" like other browsers do.
Note that in later versions of Android you can hide specific notifications. We are even going to support the notification channel feature of Android 8+ in the next release - which will give you fine controls for the notification(s).

**Comment by spocko** [comment]
Here's a specific example:
I installed Focus as the default browser on my wife's phone. The goals:
- Privacy and tracking protection when clicking on links from emails, etc.
- Avoid accumulating a bunch of open tabs and browser history when clicking on links from emails, etc.

She is a non-technical user, so the doesn't really understand all of that, but would still benefit from it. She is not directly concerned about visiting sensitive sites and deleting history.

Yesterday eve she came to me with her phone and showed me the notification, asking "What is this? What do these options mean? ..."  Clearly she just finds the notification confusing and does not need it.

You say that as long as the notification is shown, then the session is maintained. That's true as long as the app is open, regardless of whether a notification is displayed. I suppose The notification probably helps prevent Android from closing the app due to low memory, but for the use cases that I mentioned above, I don't think there's a strong need to keep the session after leaving the app.

I'm not suggesting that the notification or FAB be removed from Focus. I'm just asking that users be given the option to disable those features if desired. And keep in mind that most people are not going to get Android 8+ anytime soon.

Thanks

**Comment by smartfonreddit** [comment]
At least please consider removing the "Browsing history has been erased" popup message. When Focus is the primary browser and I use it to open links from Flamingo (twitter app), it gets on the way every time the back button is pressed to go back to Flamingo. This becomes a major annoyance after few minutes of use.

**Comment by pocmo** [comment]
@smartfonreddit This is unrelated. Please file a new issue for this. Thanks!

**Comment by bbinto** [comment]
>Note that in later versions of Android you can hide specific notifications. We are even going to >support the notification channel feature of Android 8+ in the next release - which will give you fine >controls for the notification(s).

@pocmo, if I turn off notification for Focus, it still says "Firefox Focus is running in the background" (via Android System notification), is this a notification that the user also can hide?

It might be worth adding some explanation to the SUMO page.

**Comment by TonyApuzzo** [comment]
My phone has way too many things running in background already, please implement this feature to allow fff to die quicker and not clutter the notification shade.

**Comment by mlda065** [comment]
I totally agree. I just installed Focus and my initial impression is that it is intrusive and poorly designed, mostly due to this.

Notifications are supposed to be temporary, that's what "notification" means.
A permanent notification is just bad design.

I don't see the purpose of a notification giving me the option to "open" the app.
No other app does that, so why should this one?

Use case: I only wear a medium sized tin-foil hat, so I don't feel the need to delete my browsing history every 5 minutes.

**Comment by DidiBear** [comment]
Add a preference "Clear session when exiting the app" would solve this issue. 
Which is exactly the same as pressing the trash fab button before exiting the app.

**Comment by colintheshots** [comment]
There's no easy answers to this. The notification isn't in the shade solely to provide a notification. It's there by Android OS requirements to keep a foreground service running, so your session stays in memory without writing out everything to disk. This is good if you don't want to lose your session when you put your phone in your pocket or take a phone call. Fixing this issue would require redesigning Focus to persist instance state on disk when in the background. We'll have a new browser soon that does this.
