### ISSUE TITLE
Screenshot of context menu when long pressing a link

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1267]
Looking at the screenshots I think we only have one of a context menu when long pressing an image. But not for links (or and images with a linl if that's easier).

**Comment by pocmo** [comment]
CC @npark-mozilla

**Comment by npark-mozilla** [comment]
patch made to npark-mozilla/l10ntest branch. waiting for a new batch of screenshots.

**Comment by npark-mozilla** [comment]
Screenshots are now updated.
