### ISSUE TITLE
Update list of licenses

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1271]
Our licenses.html file seems to be outdated and (partially?) copied from the iOS build. We should update this to reflect what we are using in the Android build.

**Comment by pocmo** [comment]
In the app we are currently using:
* Android support libraries  - https://developer.android.com/topic/libraries/support-library/index.html
  * appcompat
  * customtabs
  * design
  * cardview
  * recyclerview
* Android architecture components - https://developer.android.com/topic/libraries/architecture/index.html
  * runtime
  * extensions
  * compiler (annotation processor)
* Findbugs annotations (com.google.code.findbugs:annotations)
* Our own telemetry library - https://github.com/mozilla-mobile/telemetry-android
* The Adjust SDK - https://github.com/adjust/android_sdk
* Google Play services - Analytics (Dependency of Adjust)

Only for unit tests we use:
* junit - http://junit.org/junit4/
* robolectric - http://robolectric.org/
* mockito - http://site.mockito.org/

Only for UI tests we use:
* UI automator - https://developer.android.com/training/testing/ui-automator.html
* Espresso - https://developer.android.com/training/testing/espresso/index.html
  * core
  * idling-resource
  * web
* MockWebServer - https://github.com/square/okhttp/tree/master/mockwebserver

**Comment by pocmo** [comment]
Related legal bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1400284

**Comment by pocmo** [comment]
Moving to P1 - This is done and ready to land.

**Comment by npark-mozilla** [comment]
Assuming it's validated by Legal team
