### ISSUE TITLE
Add the compatibility with the "secret mode" for Gboard

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1277]
https://play.google.com/store/apps/details?id=org.mozilla.focus&reviewId=Z3A6QU9xcFRPR1g4c255NkxVWUdPZnFJcktkT012WGNzdE9aRThXbFROV0lMTlJnSmtEN1NrMWFuRHN3LUhCblppaUQ2dmlTSTg5Um1hUUZwTERPYnE4YWtr

**Comment by pocmo** [comment]
That's what we did in #1059 and this should ship with Cobalt. :)

**Comment by bbinto** [comment]
Perfect, and duh, it sounded familiar :)
