### ISSUE TITLE
Shortcut Icon change after restarting Nova Launcher (Android 6)

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/focus-android#1284]
I have created some shortcuts on my Moto X Play running Android 6 with Nova Launcher.
Icons are created quite correctly with the initial of the hostname (as it seems) on a square purple background -I would have preferred the favicon of the site, but that is another request ;).
Then, after restarting my phone or even after simply restarting Nova Launcher, all icons are reset to the default Focus icon with the white firefox on a purple circle.
Using Focus 1.3.

**Comment by pocmo** [comment]
Do you see the same issue when adding shortcuts via Firefox or Chrome? This looks like a launcher bug. The launcher app is responsible for the icon after we created the shortcut (saving to disk etc.).

**Comment by klint** [comment]
No, actually the other browsers I have work just fine (Firefox Beta and Chrome).
I had no other launcher left, so I have installed Hola and there it seems to work.

**Comment by pocmo** [comment]
@npark-mozilla Can you try to reproduce this?

**Comment by npark-mozilla** [comment]
@pocmo I was able to reproduce this with my Nexus 5 (API23) as well. This only happens with Nova launcher, and did not reproduce wit hthe regular launcher.

**Comment by Bringoff** [comment]
The same behavior on Moto E with Android 5.1.

**Comment by Sdaswani** [comment]
I will look into how many people this affects.

**Comment by Sdaswani** [comment]
So Nova Launcher has been installed 10M to 50M times, per Google Play: https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=en

The top two launchers have been installed 100M to 500M times, so Nova is by no means unpopular, but it isn't one of the top launchers.
https://play.google.com/store/apps/details?id=com.ksmobile.launcher
https://play.google.com/store/apps/details?id=com.gau.go.launcherex

Overall I'd say a fix is warranted, but with maybe P2/P3 on the timing front.

I'll let @bbinto make the final decision.

**Comment by klint** [comment]
Hi
I just made some other tests on my end and actually I'm not sure that the problem is with Focus.
Old shortcuts from any browser on Nova Launcher seem ok after restart. But all newly created shortcuts suffer from the problem now on my phone, whichever browser is used (Chrome, FF, FF beta, FF Nightly or Focus). So maybe Nova is not handling new shortcuts the right way. 
Do you confirm this behaviour on your end? I have sent a support request to Nova Launcher in the meantime.

**Comment by pocmo** [comment]
@klint Thanks for debugging this! It's very likely that this a bug in Nova launcher. Code-wise we are handing off the icon, title and intent to the Android system (depending on version to the ShortcutManager or by sending a broadcast) and from this point on are not touching them again (on most Android versions we can't even).

**Comment by bbinto** [comment]
@klint, probably worth filing a bug with Nova Launcher, thanks for reporting it, could I please get a screenshot of the issue so I can better understand the severity.

Thanks

**Comment by klint** [comment]
I have sent a mail to the Nova Launcher support already. Will let you know.

Please find the example of what it does an my home screen/
[https://i.imgur.com/KSYPjf4.png](url)
This example is not quite for Focus because most of the shortcuts are for Firefox Nightly, but you can guess it's difficult to tell what each shortcut is pointing to :)

By the way, are they any plan to use the favicon of a page as the shortcut image for Focus? Is it worth filing a bug for this? :)
Thanks

**Comment by klint** [comment]
The issue has just been solved by Nova in their last beta. And I have confirmed the resolution on my phone!
It was them actually ;)

**Comment by Sdaswani** [comment]
Awesome, thanks @klint !

**Comment by timeislove** [comment]
@pocmo 
no no. it is not only with nova launcher.

i am using nokia 6 which is using almost a native andriod 7.

i experience the same issues of homescreen shortcut. it would change names after a while (now i know from this post they changed after restart of focus)

i tried to add homescreen shortcut with chrome, it didn't see the problem.

pls fix it asap. as homescreen shortcut is kind of bookmark replacement for a private browser like focus.

tkyou!



Free Open Source Mac Windows Linux BSD PortableApps.com
WYSIWYG Support Built-in RSS reader Extensible by Plugins/Extensions Support for Firefox extensions ... Add a feature
Maxthon Cloud Browser icon
240
Maxthon Cloud Browser

Maxthon is a browser with innovative features, speed and security. Features Tabbed document interface Saves open tabs in case of program shutdown or...

Free Mac Windows Linux Android iPhone Android Tablet iPad PortableApps.com
Built-in Ad-blocker Built-in Download Manager Built-in RSS reader Extensible by Plugins/Extensions ... Add a feature

    Warning Maxthon apparently collects sensitive data without asking: http://news.softpedia.com/news/maxthon-browser-collects-sensitive-data-even-if-users-opt-out-506327.shtml

Firefox Developer Edition icon
78
Firefox Developer Edition

Firefox Developer Edition brings your core dev tools together with some powerful new ones that will extend your ability to work across multiple platforms from one place....

Free Open Source Mac Windows Linux PortableApps.com
Based on Firefox Add a feature
SRWare Iron icon
158
SRWare Iron

SRWare Iron, or simply Iron, is a fork of the free and open-source web browser Chromium , of which...

Free Mac Windows Linux Android PortableApps.com
Built-in Ad-blocker Based on Chromium Extensible by Plugins/Extensions Privacy focused Add a feature
Know any more alternatives to Firefox Focus?
Iridium icon
46
Iridium

Iridium is a free, open, and libre browser modification of the Chromium code base, with privacy being enhanced in several key areas.

Free Open Source Mac Windows Linux
Privacy focused Based on Chromium Security focused Add a feature
Otter Browser icon
52
Otter Browser

Web browser controlled by the user, not vice-versa. Otter Browser is a project aiming to recreate best aspects of classic Opera (12.x) UI using Qt5. Its primary...

Free Open Source Mac Windows Linux BSD Haiku
Built-in Download Manager Content Filtering Extensible by Plugins/Extensions Mouse gestures ... Add a feature
GNU IceCat icon
65
GNU IceCat

Gnuzilla is the GNU version of the Mozilla suite, and GNU IceCat is the GNU version of the Mozilla Firefox browser.

Free Open Source Mac Windows Linux Android
Built-in Ad-blocker Extensible by Plugins/Extensions Based on Firefox Tabbed browsing Add a feature

What's in this list?

Popular Alternatives to Firefox Focus for Linux. Explore 26 Linux apps like Firefox Focus, all suggested and ranked by the AlternativeTo user community.

List updated: 8/15/2017 1:02:00 PM
Sort alternatives

    Sort by rank
    Recent popularity
    Recently added

Filter by tags

    Portable11
    Warning1
    Discontinued1
    web-browser26
    extensible10
    tabbed-browsing8
    chromium-based8
    built-in-ad-blocker7
    firefox-based7
    built-in-download-m...6
    lightweight6
    integrated-pdf-view...4
    privacy-focused4
    blink-based4
    built-in-rss-reader4
    mobile-browser3
    webkit-based3
    xfce3
    mouse-gestures3
    bookmark-sync-own2
    firefox-extension2
    privacy-protection2
    resume-downloads2
    screen-capture2
    built-in-vpn2
    privacy-protected2
    firefox-extensions-...2
    no-tracking2
    security-focused2
    website-translation2

Recent comments

    Very primitive with 0 custom option.

    google as default search engine - default search engines can not be deleted - very private no add-on support (?) i don't see add-on page, add-ons are used to...

    igenn on Firefox Focus

    A lightweight solution finally for Android &amp; iOS!

    iaurinko on Firefox Focus
    open source?

    everything firefox does is open source, but

**Comment by Sdaswani** [comment]
Thanks @timeislove . @pocmo @klint @npark-mozilla did we ever find STRs?

**Comment by timeislove** [comment]
Tks for your quick response.If you require and I am allowed, I could post a screen capture showing the diff in shortcuts created by both focus and chrome.RegardsOn 24 Nov 2017 12:25, Susheel Daswani <notifications@github.com> wrote:Thanks @timeislove . @pocmo @klint @npark-mozilla did we ever find STRs?

**Comment by pocmo** [comment]
> did we ever find STRs?

Unfortunately no.

@timeislove Does this happen to other shortcuts from Chrome or Firefox too?

**Comment by timeislove** [comment]
@pocmoI tried focus for a nos of shortcut. All lost their names after restart of focus.I tried chrome to add same shortcuts to home screen. No any problem at all.Attached a photos the last two are by chrome.Regards
