### ISSUE TITLE
"Add to home screen " menu item is missing on Android O

### ISSUE THREAD

**Issue by Bringoff** [mozilla-mobile/focus-android#1288]
I have Nexus 5x running Android O and moto x with lollipop. I can add shortcuts to the home screen on Motorola, but don't have such option on nexus.

**Comment by pocmo** [comment]
I assume you are running Focus 1.3?

It will be available in Android O in the next release. :)

**Comment by Bringoff** [comment]
Yes, it reproduces on the version from google play. Looks like the version built from master is ok.

**Comment by pocmo** [comment]
Okay, thanks. Closing this one. We didn't ship this feature for Android O initially - we had some prep work to do in order to support building with the new SDK.
