### ISSUE TITLE
Clarify "Mozilla" grouping inside Settings

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1294]
From issue #1053, we mentioned clarifying this group that's labeled "Mozilla" would be something we want to follow up with

**Mozilla**
Make Firefox Focus default browser [switch]

Send usage data
Mozilla strives to collect only what we need to provide and improve Firefox Focus for everyone.
Learn more

**Comment by antlam** [comment]
@bbinto We're doing most of the Meta settings stuff in Granite*, so I'm going to move that there too. Also because Folly has the UX-heavy "What's new?" feature :)

**Comment by lime124** [comment]
I think @BrianNJones meant to comment on this issue?

We want to push this out to Indigo. We really want to make sure we do this right and that is going to take time. We're going to have a meeting next week to kick of the effort and start with research into what we currently have to uncover existing issues. From there we can begin re-design efforts that will address the issues already opened as well as what we learn.

**Comment by bbinto** [comment]
see #1205

**Comment by ekager** [comment]
Closed by #2590
