### ISSUE TITLE
Update Setup section in Localization wiki

### ISSUE THREAD

**Issue by idiotmax** [mozilla-mobile/focus-android#1296]
https://github.com/mozilla-mobile/focus-android/wiki/Localization

In Setup section before `./gradlew stringsSetup`, add an item to install python module dependency from `androidpo`.

1. Python, Pip and Git need to be installed.
2. Install python module dependency from `androidpo`
```shell
sudo pip install -r tools/l10n/android2po/requirements.txt
```
3. Run the `stringsSetup` gradle tasks to create a local checkout of the L10N repository (in folder `l10n-repo`) and to install the py
  ```shell
  ./gradlew stringsSetup
  ```

**Comment by liuche** [comment]
Wiki has been updated, and includes new scripts.
