### ISSUE TITLE
about:rights not localized 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#1299]
Pixel - Android 8.0
Have a different locale than English

Steps: 
1. Go to the 3 dot menu - Open Rights
2. Go to the 3 dot menu - About

Expected:
- bth pages should be localized

Actual:
- only About is localized, Rights opens English version. 

![notlocalized](https://user-images.githubusercontent.com/1391451/30206573-2697724e-9495-11e7-987f-59db2a18ad7b.png)

**Comment by pocmo** [comment]
The patches for this landed yesterday (Denim milestone) and translators are translating the strings currently. :)
