### ISSUE TITLE
Mozilla menu not localized

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#1300]
Pixel - Android 8.0
Build 2844
Use a different locale than english

1. Go to settings and check the Mozilla Menu

![photo_2017-09-08_12-39-28 2](https://user-images.githubusercontent.com/1391451/30206718-9bd4dff6-9495-11e7-97be-50b59e342aa7.jpg)

**Comment by pocmo** [comment]
Those two just landed for the Denim milestone and are being translated currently.
