### ISSUE TITLE
[2.0 RC1] address bar regression

### ISSUE THREAD

**Issue by phunkular** [mozilla-mobile/focus-android#1304]
on 2.0, when I visit page via search and tap the address bar, I only get the search terms appear - I can no longer view the full URL and edit it. If I visit a page via URL first instead then I can tap, highlight and then modify the full URL.

Eg. Visit the Firefox focus github by firstly searching for it and then by visiting GitHub directly. When you search for GitHub you will not be able to modify the URL to see the /releases page. However if you go to GitHub.com , search Firefox focus, you will then have full URL available and can browse /releases from there,

Thanks

**Comment by pocmo** [comment]
Back-ported to Cobalt milestone for 2.0-RC2 build.
