### ISSUE TITLE
Evaluate Kotlin code quality tools

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1308]
See #975 

Detekt -  "Static code analysis for Kotlin"
https://github.com/arturbosch/detekt

klint - "An anti-bikeshedding Kotlin linter with built-in formatter"
https://github.com/shyiko/ktlint

**Comment by pocmo** [comment]
klint seems to be helpful to keep a consistent code style, e.g.:

> /Users/skaspari/Projects/Mozilla/Focus/app/src/main/java/org/mozilla/focus/browser/DisplayToolbar.kt:46:1: Unexpected indentation (11) (it should be multiple of 4)
> /Users/skaspari/Projects/Mozilla/Focus/app/src/main/java/org/mozilla/focus/browser/DisplayToolbar.kt:46:16: Unnecessary space(s)

**Comment by pocmo** [comment]
detekt is now running on taskcluster for every PR / merge to master.

I'm still interested in understanding how much overlap there is with ktlint and whether it makes sense to add ktlint additionally.

**Comment by pocmo** [comment]
ktlint seems to add some additional style checks. I'll look into integrating it too.

**Comment by mcomella** [comment]
@pocmo ktlint and detekt are integrated – is there anything else to do in this bug?

**Comment by pocmo** [comment]
Done!
