### ISSUE TITLE
Migrate buddybuild Beta test group to Google Play Beta channel

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1309]
We should try to migrate our internal Beta test group in Buddybuild to the Google Play Beta channel. And email to inform them of the new channel might be enough.

**Comment by pocmo** [comment]
@bbinto Can you take this over? I guess we'd just need to send a mail to our buddybuild mozillians/translators tester that they can switch over to Google Play now. :)

**Comment by bbinto** [comment]
Will do!

**Comment by bbinto** [comment]
@pocmo quick confirmation here, after users signed up for the public Beta Google channel, they will get automatic updates, the same as with their release Focus app, correct?

**Comment by pocmo** [comment]
> a) after users signed up for the public Beta Google channel, they will get automatic updates, the same as with their release Focus app, correct?

Yes, that's correct.

> b) we only submit a beta build approx 1 week before public release, so they should expect less builds and no more emails from buddybuild :)

Also correct. :) If we find release blocking issues (like major crashes) then we might send out a new build to the beta group to verify that the issue is fixed. So they might see some more updates occasionally.

Some time ago I wrote a wiki page about how to sign up for the beta. Maybe that's helpful too:
https://github.com/mozilla-mobile/focus-android/wiki/Beta

**Comment by bbinto** [comment]
Thanks, I sent an email to "Mozillians / Trusted testers (Beta branding + Buddybuild SDK)", for the group of translators, it might make sense to keep them on BB, what do you think?
