### ISSUE TITLE
Copy Fennec's scrollable URL

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1318]
* https://bugzilla.mozilla.org/show_bug.cgi?id=1271998
* https://bugzilla.mozilla.org/attachment.cgi?id=8751297

**Comment by bbinto** [comment]
Would love to hear @lime124's take on that / effort etc.

**Comment by lime124** [comment]
Seems like a good idea and a good way to solve what I think is the problem: I can't see the entire URL to be confident it's not being spoofed.

I'd like to first talk with the Fennec designers and get their thoughts on the feature. I'll be happy to do that when it becomes a priority.

**Comment by pocmo** [comment]
> Seems like a good idea and a good way to solve what I think is the problem: I can't see the entire URL to be confident it's not being spoofed.

Yep!

> I'd like to first talk with the Fennec designers and get their thoughts on the feature. I'll be happy to do that when it becomes a priority.

I designed that 🙃 

It's in Firefox for Android 57 - implemented by a long-term contributor.
