### ISSUE TITLE
Toolbar jumps below status bar

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#133]
Could be related to #132. When scrolling (and maybe zooming) it can happen that the toolbar jumps down and you can see the website behind the status bar.

![statusbar_website](https://cloud.githubusercontent.com/assets/89638/23469232/5b54c668-fea3-11e6-9c81-3ae61f1971a4.png)

**Comment by ahunt** [comment]
I'm not seeing this anymore (in local builds) with my fix for #132, so I'll close this as a dup for now.
