### ISSUE TITLE
[2.0 RC2] Sleep is inhibited when Firefox focus is open

### ISSUE THREAD

**Issue by phunkular** [mozilla-mobile/focus-android#1333]
my device doesn't sleep now when Firefox is open on Miui 9 marshmallow

**Comment by Jacquester** [comment]
Same issue with android 5.1

**Comment by phunkular** [comment]
seems to happen intermittently on further investigation

**Comment by Jacquester** [comment]
@phunkular Where were you in the app when your device failed to sleep ?
Or could you maybe replicate the steps to when it failed to lock ?

**Comment by phunkular** [comment]
Yes I was in the app. Sorry I can not reproduce it reliably, I just noticed that my phone wasn't sleeping sometimes and that this was only the case when Firefox focus was open when it happened again some time later and I could test. Then when I began looking to see if I could narrow it down further I realized that it would come and go. Webview is freshly updated at 61 too.

**Comment by phunkular** [comment]
rereading the issue I see that I missed the "where" part of your question. It happened on both the welcome page and while viewing a website. Not sure about settings page. Haven't noticed it it lately though. Will test if it crops up again... anything to look at that would help narrow it down?

**Comment by phunkular** [comment]
I haven't noticed this at all lately, perhaps this issue should be closed?
