### ISSUE TITLE
 [meta] bring more value to the typing screen

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1336]
Let's take some time to examine the typing screen and make some improvements to it. iOS has a similar issue open.

- [ ] #1040 search suggestions/auto-complete
- [ ] #957 add whitelist
- [ ] #1337 auto-complete for top level domains

**Comment by bbinto** [comment]
@lime124 do you think you can merge this with #1525

**Comment by bbinto** [comment]
Also suggesting to remove #957 from this as this is related to blocking more/less tracking lists.

**Comment by lime124** [comment]
yes we can merge this with #1525. UX meta is #1546
