### ISSUE TITLE
Add ability to add domains to top domain list for autocomplete

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1337]
see https://github.com/mozilla-mobile/focus-ios/issues/433

**Comment by bbinto** [comment]
Could we do this for Granite (to align with iOS plans)?

**Comment by pocmo** [comment]
This sounds like a pretty inconvenient way to add history manually (or bookmarks). Are we sure that's the best way to solve the user problem of getting back to a page?

**Comment by pocmo** [comment]
Also: Android has "Add to Home screen" - I guess that's something iOS cannot have?
