### ISSUE TITLE
Does Focus block js from accessing basic broswer and device characteristics?

### ISSUE THREAD

**Issue by samirm** [mozilla-mobile/focus-android#1342]
Users can be identified and tracked based on a variety of variables that can be accessed through javascript such as: screen size and colour depth, hash of canvas fingerprint, hash of WebGL fingerprint, screen brightness, battery life, etc.

What I'm wondering is if Focus protects against these forms of fingerprinting and therefore tracking? Is this feature planned for the future? Is there a way to disable all JS?

Thank you.

**Comment by pocmo** [comment]
Disabling JavaScript -> #907

Currently we do not block most of those JavaScript features. See also #900 regarding fingerprinting. Some of those things we can't fully control as long as we are shipping the WebView version. With GeckoView there are more options.

**Comment by samirm** [comment]
Thanks for answering so quickly. Hopefully these features will be implemented eventually.

**Comment by bbinto** [comment]
Meta issue is here: #1344

**Comment by pocmo** [comment]
Looks like this issue is not actionable itself. I'm going to close it (in favor of the other ones linked from the meta issue).
