### ISSUE TITLE
Update "erase" icon (photon)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1349]
Follow-up from #938.

**Comment by antlam** [comment]
This was intended to be a low priority follow-up item for UX. A Photon-style Focus-specific Erase icon is in the backlog but its not high priority ATM so we shouldn't really be targeting a release Milestone yet. More of a nice-to-have ATM. 

Moving this out of Folly.

**Comment by liuche** [comment]
@antlam do you have an icon to attach? If you do, can you add the help-wanted label :)

**Comment by antlam** [comment]
@liuche not yet, most of the focus here on the visual design side has been on getting Photon polished, buffed, and shined for next week!

**Comment by bbinto** [comment]
@brampitoyo can this be closed in favour of our upcoming redesign / Android P?

**Comment by brampitoyo** [comment]
Yes. This should be closed because it’s a dupe of #2682.
