### ISSUE TITLE
Text selection action does not show up for "debug" builds.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1350]
Whenever I deploy a debug build (focusWebviewDebug) then the text selection action does not appear. However when deploying a Beta build it shows up. I do not know why though.

Note that there's a bug in Android O (It's reported but unfixed so far) that the first text selection in an app doesn't show third-party actions. Either use another Android version (6+) or select text twice to debug this issue.

**Comment by pocmo** [comment]
This is super confusing. The action showed up after I installed the beta version. But the action showing up is for the debug version... This looks like another Android O bug.

**Comment by ekager** [comment]
Have we ever seen this again? Or was it just an Android O bug

**Comment by pocmo** [comment]
No clue. Let's close :)
