### ISSUE TITLE
Empty screen in 'About' menu

### ISSUE THREAD

**Issue by djKooks** [mozilla-mobile/focus-android#1361]
Hello.
When I press sub menu button in right-top of main page and press `About` menu, it shows only empty screen.
Will it be better to show some information about this app?

![screenshot_20170922-191141](https://user-images.githubusercontent.com/1720209/30740038-6c51b5d4-9fca-11e7-8ca0-a2ecf32bb23c.png)

Thanks.

**Comment by pocmo** [comment]
* What app version are you using?
* What Android device / version are you using?
* What language have you set in your system settings (or in Focus)?

**Comment by djKooks** [comment]
@pocmo 
1. What app version are you using? => Installed via latest source in github
2. What Android device / version are you using? => Nexus6P / Android 8.0.0
3. What language have you set in your system settings (or in Focus) => English

**Comment by pocmo** [comment]
It should look like this:

![device-2017-09-22-133909](https://user-images.githubusercontent.com/89638/30742862-7c75d0f0-9f9b-11e7-8845-247fd0f90729.png)

**Comment by pocmo** [comment]
@npark-mozilla Are you able to reproduce this in any configuration?

**Comment by pocmo** [comment]
@djKooks If you build yourself. What buildVariant are you using? Make sure to select "focusWebviewDebug".

**Comment by djKooks** [comment]
@pocmo Oh, okay. I'll try it again.

**Comment by npark-mozilla** [comment]
@pocmo I think I came across this in BB sims a couple times, (when the device wasn't responding fast enough) but recently I haven't seen it in a while. we haven't seen this when running the screenshot generation though.

**Comment by djKooks** [comment]
@pocmo As you said, it works well in `focusWebviewDebug`(I tested on Gecko version before). Is it okay for this, or is it still a problem?

**Comment by pocmo** [comment]
@djKooks Thanks for testing this! In this case we are closing the issue. We want to still be able to compile a gecko version but we are maintaining it / keeping feature parity.
