### ISSUE TITLE
Close tab button

### ISSUE THREAD

**Issue by dimqua** [mozilla-mobile/focus-android#1362]
Please add a possibility to close a tab on a tabbar by using close button.

**Comment by codebu5ter** [comment]
Currently, there's no way to close an individual tab, but to repeatedly press the back button until it closes. I've implemented a more user-intuitive way, in which the user just has to long press the tab and it will be closed.

Also, the process of closing all tabs requires two clicks at the moment. I've implemented the same functionality to close all tabs, in which the floating action button needs to be long pressed to close all tabs, which is more user-intuitive.

**Comment by Benestar** [comment]
Instead of long pressing, I would rather implement some mechanism to swipe the tab away which seems to be more intuitive and consistent with material design guidelines (compare eg. the Gmail App). Also, in Firefox Mobile on Android, you can swipe a tab away to close it.

**Comment by bbinto** [comment]
Adding this to the [[meta]](https://github.com/mozilla-mobile/focus-android/issues/1250)

**Comment by pocmo** [comment]
@lime124 @antlam We have a contributor PR that implements "swipe-to-dismiss" for tabs. Is this something we are interested in? Managing single tabs has been debated a lot in the past.

**Comment by antlam** [comment]
@pocmo I'm going to leave this to @lime124 

But since this is a P5, I worry it could be kind of messy if we start pulling at this thread. This interaction on top of the expanded FAB isn't something that is very standard in Android and just feels a bit weird to me (versus say, simply an X button).

**Comment by lime124** [comment]
I agree with @antlam - i also worry about the ripple effects this could potentially have without a lot more investigation to make sure all the i's are dotted so to speak.

**Comment by asafh** [comment]
Hi,
I've implemented a swipe to dismiss over the new (kotlin) codebase. I believe the interaction feels natural for android.  
Should I do anything to get this reviewed or just wait patiently?

**Comment by ekager** [comment]
Hi @asafh ! Thank you for wanting to contribute but we currently don't have the bandwith on our team to accept feature patches for Focus. Please check out one of our other projects if you want to get involved:
https://github.com/mozilla-mobile/android-components
https://github.com/mozilla-mobile/fenix

**Comment by asafh** [comment]
Hi @ekager, that's unfortunate but no worries. I'll look into supporting my focus use case within fenix.

Cheers

**Comment by pocmo** [comment]
This is getting implemented in #5741
