### ISSUE TITLE
Always display erase button

### ISSUE THREAD

**Issue by dimqua** [mozilla-mobile/focus-android#1364]
Please add an option to display erase/tabbar button on scrolling.

**Comment by CamelCase11** [comment]
It may interfere while scrolling and hide page elements.

**Comment by pocmo** [comment]
@dimqua Can you elaborate why you want this feature? Are you annoyed by the animation - or is it sometimes hard to get it to appear again?

**Comment by dimqua** [comment]
I want to be able to switch between tabs when I at the bottom of the page.

**Comment by dimqua** [comment]
Probably, there is a better way to solve this problem. In Firefox, tabbar is visible every time when you scroll the page up.

**Comment by Benestar** [comment]
> In Firefox, tabbar is visible every time when you scroll the page up, and not always.

When you scroll up, the floating action button becomes visible as well, so I do not really understand your problem with the current situation.

**Comment by dimqua** [comment]
Probably, It was fixed, but the problem doesn't exist anymore.
