### ISSUE TITLE
Settings to disable multi tabs feature

### ISSUE THREAD

**Issue by rednaks** [mozilla-mobile/focus-android#1378]
One of the main reason I was happy with firefox focus, it's because you can actually focus on what you're browsing, only one tab, get what you want and leave.

Now with the new multi tabs, Iit's easy distracted ...

Can you at least add an option to disable multi tabs ?

PS. If anyone would give me some pointers I would be glad to contribute and provide a patch :)

**Comment by CamelCase11** [comment]
By default focus is not giving any option to open a new tab, it only shows up in link context menu. I believe that adding option to disable tabs will be redundant because it's up to a user to open a link in a new tab or not.

**Comment by bbinto** [comment]
closing this in favour of #1805
