### ISSUE TITLE
Make resource-id of menu items distinct for UI Test

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#138]
Currently the resource ID values of the menu texts ('Settings', 'About', 'Help', etc. ) are all set to 'title'. Making them correspond to its English locale text would make the test scripts a lot more easier to write.
EDIT: turns out espresso relies heavily on ids, will need this for the l10n test script.

**Comment by pocmo** [comment]
This seems to be a side effect of using the menu inflater. It doesn't set view ids.

**Comment by pocmo** [comment]
@npark-mozilla You mentioned that you are selecting by index now. Is this something you'll keep doing or should we still fix this? It's doable but it requires custom code instead of just using the menu APIs to create the menu.

**Comment by npark-mozilla** [comment]
ah if it is doable, it's best to use the id since it would make the tests much more simpler and readable, but if you have a lot of other pressing issues, I think we can wait until later

**Comment by npark-mozilla** [comment]
To add, every list item in the Settings menu has 'title' id as well.
