### ISSUE TITLE
Fingerprint Authentication 

### ISSUE THREAD

**Issue by Achintya999** [mozilla-mobile/focus-android#1380]
Added Fingerprint Authentication in the app

**Comment by pocmo** [comment]
What are you actually asking for? Can you elaborate a bit?

**Comment by Achintya999** [comment]
Its good to have a fingerprint authentication in the app for sign in purposes as it helps for security instead for using third party software for locking the app.

**Comment by boek** [comment]
We now have Biometrics 👍
