### ISSUE TITLE
Crash while double tapping a tab inside tablist.

### ISSUE THREAD

**Issue by CamelCase11** [mozilla-mobile/focus-android#1385]
Firefox focus always crash when I double tap any tab inside tablist.

**Comment by MrGeneric** [comment]
Good catch. I can reproduce this bug in 2.0.

**Comment by pocmo** [comment]
@liuche I saw that you assigned this issue a couple of days ago. There's also a contributor working on a patch in PR #1391. Maybe you can mentor this?

**Comment by pocmo** [comment]
Backported patch to Ebony branch too.
