### ISSUE TITLE
Change search engine list - KO

### ISSUE THREAD

**Issue by djKooks** [mozilla-mobile/focus-android#1386]
I just saw that search engine list in 'Setting > Search' when setup device as Korean. Other things seems OK, but it is bit strange that `Daum` search engine has been setup to find `Daum Maps` while `Naver` search engine setup to use its search engine. It is linked with Maps menu in source code, too.
If there is no other purpose, how about change `Daum` to use its search engine result?

**Comment by pocmo** [comment]
@djKooks We import the search plugins from Firefox for Android. Do you see the same problems in regular Firefox?

@flodolo Who actually maintains the localized search plugins - in this case Korean?

**Comment by flodolo** [comment]
File bugs in Mozilla Localizations::Korean if you want to discuss changes to search engines.

Also reminder that @delphine is the point of contact for mobile projects ;-)

**Comment by pocmo** [comment]
Thank you!

@djKooks Can you file this issue here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Mozilla%20Localizations&component=ko%20%2F%20Korean - Thank you! :)

**Comment by djKooks** [comment]
@pocmo Thanks. It has been updated!
https://bugzilla.mozilla.org/show_bug.cgi?id=1402829

**Comment by djKooks** [comment]
@pocmo @flodolo It has been decided to retain current state. You could refer bugzilla link above.
Thanks for help!
