### ISSUE TITLE
Don't switch to a new tab / Open tabs in background

### ISSUE THREAD

**Issue by dimqua** [mozilla-mobile/focus-android#1388]
Would be nice to have an option to open new tabs (links) in the background.

**Comment by layely** [comment]
@pocmo @antlam i would like to work on this.

**Comment by antlam** [comment]
Thanks for the interest @layely ! 

This issue has to be triaged by the team first before we decide on priority here.

But if you'd like to take the initiative and go ahead with a patch, I'm sure @pocmo or someone would be able to start reviewing the code while we prioritize this with Product.

**Comment by layely** [comment]
@pocmo @antlam Here is a screenshot of the context menu but i feel like the text "Open link in new tab in the background" is too long.

![screenshot_1506668912](https://user-images.githubusercontent.com/19215803/31004837-9f811a7e-a4e5-11e7-8643-d82746da49cf.png)


commit in my forked repo: https://github.com/layely/focus-android/commit/d6742fb165c92caa05f28c519769b8f364f7558e

I am waiting your feedback before sending a PR.

**Comment by MrGeneric** [comment]
How about "Open link in new background tab"?

**Comment by antlam** [comment]
@layely awesome start!

> but i feel like the text "Open link in new tab in the background" is too long.

I agree, **but** before we think more about the specific details here, we should think through _other_ UX possibilities too. That way, the overall experience of the entire product can be considered as well.

@lime124 should chime in here too :) note: this still needs to be prioritized

**Comment by pocmo** [comment]
After using Focus for a while I feel like opening tabs via the context menu should always open in the background. The current implementation forces you to do a mental context switch immediately. For me opening a tab is always an action where I want to defer something for later.

**Comment by antlam** [comment]
@pocmo yeah that's generally my expectation too nowadays because mostly the links I want to open are things I want to read _later_. So the action is almost like queueing up a couple of links for after... 🤔

**Comment by layely** [comment]
@antlam @pocmo yeah exactly what i was thinking too.

**Comment by dimqua** [comment]
Probably, "new tab in the background" should be the default action.

**Comment by TonnesM** [comment]
+1, also see [this support question.](https://support.mozilla.org/questions/1206905)

As Firefox for Android opens tabs in the background by default (something users may be accustomed to), why not just change the behavior to the same without adding a new option, as suggested? (Albeit a "Switch to tab" feature would be required, or simply _not_.)

**Comment by pocmo** [comment]
CC: @brampitoyo

**Comment by brampitoyo** [comment]
I agree that opening new tabs in the background should be a preferred behaviour.

The question is, should we also keep our existing behaviour to “Open in new tab, then switch to it?”. I put forth the proposal that we should adopt the new behaviour and drop the old one. This keeps our menu small and easily navigable.

But if we want this to be an option, I recommend using the wording “Open link in new background tab” – short and sweet – and putting this link underneath “Open link in new tab”.

**Comment by pocmo** [comment]
I like the snackbar confirmation that Firefox for Android shows when opening a tab in the background. It allows the user to switch to the background tab immediately if needed.

![tab-opened](https://user-images.githubusercontent.com/89638/36965132-0495724a-2059-11e8-8e2d-183f608c5797.png)

**Comment by antlam** [comment]
@pocmo +1, when we did that for Fennec, I think it was under the same circumstances. 

We should have Telemetry on that too!

**Comment by brampitoyo** [comment]
+1 for the snackbar confirmation.

Then we can just have one “Open link in new tab” item on the menu. This item will open the tab in the background. And with the snackbar, you’ll have the ability to switch to it almost immediately.

**Comment by ekager** [comment]
Closing for #3300
