### ISSUE TITLE
Already loaded tabs are reloading while switching (excess data usage?).

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1393]
UX #1513 

Originally filed in [bugzilla bug 1402665](https://bugzilla.mozilla.org/show_bug.cgi?id=1402665):

```
User Agent: Mozilla/5.0 (Linux; Android 7.1.2) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/2.0 Chrome/60.0.3112.78 Mobile Safari/537.36

Steps to reproduce:

Firefox Focus 2.0 (Build # 12571412) : I switched between already loaded tabs.


Actual results:

Tabs reloaded every time I switched to them, despite they were loaded completely before.


Expected results:

Switching fully loaded tabs shouldn't have loaded the page again causing excess data usage.
```

**Comment by pocmo** [comment]
I think we already have an issue for that. But I can't find it.

We do not fully reload the page - We restore the WebView state. It's much faster. However it does some kind of loading and is definitely slower than for example switching tabs in Fennec. One of the things I wanted to try is to keep a WebView reference in the session and re-use it when switching tabs. In the case of memory pressure we could just drop them and restore the state again like we do now.

**Comment by pocmo** [comment]
Found #1325 but this one doesn't contain much text. Will close the other one.

**Comment by bbinto** [comment]
@pocmo -- could you please give us a T-shirt size?

**Comment by shinilms12** [comment]
@bbinto Are you still working on this issue?

**Comment by jerryn70** [comment]
This is a big problem for me and Its really annoying . Hope you guys fix this soon.

**Comment by bbinto** [comment]
More from GPS

"Really nice browser WHEN IT WORKS. Won't load pages half the time without refreshing. And PLEASE make it stop reloading webpages every time we switch tabs or apps. Not only does this issue render the browser unsuitable for use with a limited data connection, but it also interrupts browsing sessions by requiring people to find their place (or refill text boxes) in a webpage whenever they've paused to view something else. Also, it is lacking the basic find-in-page function."

**Comment by Poopooracoocoo** [comment]
I think this is relevant again. I still have to re-enter text when I switch tabs @mcomella @bbinto

**Comment by mcomella** [comment]
afaik, we haven't changed the implementation so I'd be surprised if this is broken.

I'm no longer on Focus so CC @colintheshots who I think is still looking at Focus.
