### ISSUE TITLE
Need for a widget app.

### ISSUE THREAD

**Issue by itsrahul** [mozilla-mobile/focus-android#1395]
There should be a widget app, which allows the user to directly search in the browser.

**Comment by pocmo** [comment]
What would be different than pressing the launcher icon where you also can immediately perform a search?

**Comment by itsrahul** [comment]
It would be easier as the user would directly enter the query from home screen, rather than opening the app.

**Comment by bbinto** [comment]
Is this similar to #505?

**Comment by pocmo** [comment]
Yeah, I think so. Closing this as a duplicate of #505.
