### ISSUE TITLE
 Want to get Cookies data！

### ISSUE THREAD

**Issue by zjingye** [mozilla-mobile/focus-android#1400]
I want get Cookies data , how can i do?

**Comment by pocmo** [comment]
I'm not sure what exactly you mean.

In general cookies only exists as long as the browsing session does. As soon as you press the erase button everything, including cookies, is gone.

**Comment by zjingye** [comment]
Thank you for your answer！

I want to save the cookie data to a local file，But I do not know how to access cookie。How can I access the cookie?

**Comment by pocmo** [comment]
Sorry, there's no way to save a cookie to a file in Focus.

**Comment by zjingye** [comment]
Thank you!
