### ISSUE TITLE
reproducible builds: auto-generated LocaleList is not sorted

### ISSUE THREAD

**Issue by eighthave** [mozilla-mobile/focus-android#1401]
Apparently, Klar generates `org.mozilla.focus.generated.LocaleList` during the build.  This list is not sorted, so it breaks reproducible builds.  You can see the diff here:
https://verification.f-droid.org/org.mozilla.klar_10.apk.diffoscope.html

**Comment by pocmo** [comment]
Thank you for filing this.

Locally and in the right diff this list looks sorted already. But I guess it does not hurt to just call sort() on it.
