### ISSUE TITLE
tr: number of placeholders not matching, key: your_rights_content5

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1408]
The Turkish translation for "your_rights_content5" seems to be missing the `%3$s` placeholder (which links to the tracking protection wiki page).

**Comment by pocmo** [comment]
@delphine How can we notify the translator?

**Comment by Delphine** [comment]
I can go and edit this myself this time. 
The usual process is to file a bug under Mozilla Localizations and the locale code name. It notifies the localizer this way

**Comment by Delphine** [comment]
Hmmm I don't see that it's missing (see attached screenshot). Am I missing something? 
<img width="634" alt="screen shot 2017-09-28 at 3 05 02 pm" src="https://user-images.githubusercontent.com/399020/30965588-8b97bc0c-a45e-11e7-86c6-ef4a5ffd66d0.png">

**Comment by pocmo** [comment]
@Delphine Oh, I interpreted the output of our script wrong. It was only warning that %1$s is used twice in the translation. But that's fine. Sorry for the confusion. We can close this issue. :)
