### ISSUE TITLE
Write Sentry Entry for Focus 

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#1410]
This doc is a good template: https://github.com/mozilla-mobile/firefox-ios/wiki/Crash-Reporting-with-Sentry

I think we may as well cover both iOS and Android in the same doc and just place it in a common location or link to it from one project.

This was requested by @liuche during data review: https://bugzilla.mozilla.org/show_bug.cgi?id=1402946

iOS issue: https://github.com/mozilla-mobile/focus-ios/issues/508

**Comment by pocmo** [comment]
Although so far we are not using sentry (or any other crash reporter apart from Google Play) -> #823

**Comment by liuche** [comment]
The missing feature that Sentry would (probably add) is being able to see the crash rate differences between Beta build and Release - Google Play only shows the crash rate differences for staged rollout.

**Comment by pocmo** [comment]
What I'm wondering is: Can Sentry even tell us a crash rate if it doesn't know about users/sessions and only about crashes? Without that I'm not sure how to compare two releases because Beta doesn't have as much users as release (So we can't compare raw crash report counts).

**Comment by Sdaswani** [comment]
Agree @pocmo we probably can't get a meaningful crash rate - Sentry may just help with helping us identify what crashes the Beta release is seeing.

We definitely should make sure there is _value_ in integrating Sentry before we go through the effort. On the iOS side the value prop is clearer.

**Comment by pocmo** [comment]
Some other things that are annoying with Google Play and were Sentry might help (Don't know):
* I can't comment on crashes or link them with an issue on GitHub. Therefore I need to remember if I filed a bug already. This doesn't scale. Hopefully Sentry can either talk to GitHub directly - or I can at least post a link/comment or something.
* I can't search for crashes / stack traces in Google Play. This one is surprising for a Google product.

**Comment by Sdaswani** [comment]
Sentry can at least provide a link to the crasher, we used it at Lookout and I'd do it all the time - though it may not be accessible publicly. And yes you can search.

**Comment by pocmo** [comment]
Public access is interesting too. For Fennec crash-stats are public (I actually wanted to check if we could use this too - and again build a separate library) and it's great: Contributors can file issues, debug problems and fix them!

**Comment by Sdaswani** [comment]
I chose 'Share' in sentry and it generates this link, but I'm not sure what information folks who aren't logged in can really see: https://sentry.prod.mozaws.net/share/issue/3237372e363636383233/

**Comment by pocmo** [comment]
Closing in favor of #2326
