### ISSUE TITLE
Swipe down to refresh web page (Pull-To-Refresh)

### ISSUE THREAD

**Issue by codebu5ter** [mozilla-mobile/focus-android#1418]
A Swipe-down-to-refresh gesture would be a great addition to Focus, just like in Google Chrome. 
It would make the act of refreshing a web page more user-intuitive.

**Comment by Benestar** [comment]
Hi @lime124, I used the `photonMagenta70` color from `photon_colors.xml` which is the same color as the floating action button to erase browsing history. Its color code is `#ffb5007f`.

**Comment by lime124** [comment]
Awesome! Thanks again @Benestar !

**Comment by jolcsk** [comment]
I hate to disturb a development thread with my question, but can you make this feature optional (able to turn-off)? I absolutely hate the swipe-down-to-refresh feature (I trip it accidentally too often), that is one of the reasons I like using firefox (fennec) and focus too.

**Comment by max2505** [comment]
Hey all,

I would also like the option to turn off this feature.
On a website page where a chat conversation is shown and by default you're at the bottom (end of the conversation), you don't have the options to go up (by scrollingen down) when this feature is enabled (I hope the explaination is somewhat clear).

Tester on Oneplus 3T.

**Comment by SavageBiscuits** [comment]
I'd also like to chime in for an option to disable this feature. Already I've managed to trigger this feature a few times without wishing to. It gets a bit annoying. It's a useful feature to have, but it's not for everyone.

**Comment by Benestar** [comment]
Hi @max2505 @SavageBiscuits I created #1776 to address the issues with pull to refresh. Can you maybe provide the links to the pages where this feature causes issues?
