### ISSUE TITLE
fy-NL is not a valid locale

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#142]
Importing strings fails for fy-NL (Frisian, Netherlands) [[1]](http://www.localeplanet.com/dotnet/fy-NL/index.html).

We should test if it's only a2po which fails to recognize this locale or if it's actually Android that can't handle this locale.

**Comment by pocmo** [comment]
I "fixed" this locally by going to `/usr/local/lib/python2.7/site-packages/babel/localedata` and copying to `nl_NL.dat` to `fy_NL.dat` (and `nl.dat` to `fy.dat`). To my surprise it somehow knows about `fy` and doesn't think it's Dutch:

```
>>> from babel import Locale
>>> locale = Locale('fy', 'NL')
>>> locale
Locale('fy', territory='NL')
>>> locale.get_display_name('en_US')
u'Western Frisian (Netherlands)'
```

However after all it doesn't matter because none of the locale data is used. android2po writes some things based on that into comments into the header of the po file (like the name of the language) but this is not used by any our tools. This might change as soon as we require plurals support - but then nl and fy might use the same rules.

**Comment by Delphine** [comment]
Hi - we realized about this today with No-Jun since the screenshots turn out in English for testing Frisian locale. 
They are 100% complete l10n wise, so I'm wondering if this is something we can fix for v1 or not? (also, CC @flodolo)

**Comment by flodolo** [comment]
> but then nl and fy might use the same rules.

They do (2 forms).

**Comment by pocmo** [comment]
We didn't import fy-NL strings yet because of this bug. However we have a workaround and with the next import those strings should get into the app.

**Comment by pocmo** [comment]
@npark-mozilla I just imported strings again. Does this work for you now?

**Comment by npark-mozilla** [comment]
yup I see it now, thanks!
