### ISSUE TITLE
Update Telemetry dashboards to filter on "Focus" & "Klar" app names

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1420]
Our telemetry for "default browser" started to show "null" in addition to "true"/"false".

https://sql.telemetry.mozilla.org/queries/5766/source#117182

**Comment by pocmo** [comment]
It looks like pings from Zerda are going into the same table. They use a different app name but the same ping type. And it looks like the app name is not part of the table - so we can't filter by it.

**Comment by pocmo** [comment]
@fbertsch Can you confirm this? ---^

**Comment by pocmo** [comment]
After talking to frank I created a local fork of the query and added an additional filter for the app name and the null values disappeared:
> and metadata.app_name in ('Focus', 'Klar')

**Comment by fbertsch** [comment]
For others: We talked in Slack, can use `SELECT * FROM telemetry_focus_event_parquet WHERE metadata.app_name = 'Focus'`

**Comment by pocmo** [comment]
And I did the reverse check. If I look at all the null values then they all have the app name set to "Zerda".

**Comment by pocmo** [comment]
@bbinto We will need to check all our queries to make sure that we include the app name filter (`and metadata.app_name in ('Focus', 'Klar')`)so that our data is still valid after Zerda is released. :)

**Comment by mcomella** [comment]
Note: like Zerda, I'd expect this will affect other forks of our repo too.

> @bbinto We will need to check all our queries to make sure that we include the app name filter (and metadata.app_name in ('Focus', 'Klar'))so that our data is still valid after Zerda is released. :)

This seems error prone for new queries. :\ I wonder if we can do better, e.g. add a private token in our build step so others cannot use our telemetry?

**Comment by fbertsch** [comment]
There is no way to prevent other builds from using the same ping type. We could force them to add separate pings instead, but that would require new schemas server-side.

Why don't we do the following instead:
1. Make the table currently known as `telemetry_focus_events_parquet` be instead called `telemetry_mobile_events_parquet`
2. Create a new table, `telemetry_focus_events_parquet`, that is a view on the `telemetry_mobile_events_parquet` table, and only includes `Focus` and `Klar` data.

This way all existing queries can remain untouched, new queries can use the same table, and queries for other mobile apps can query the `telemetry_mobile_events_parquet` table.

**Comment by pocmo** [comment]
@fbertsch This sounds good.

@mcomella Telemetry is only enabled for Beta/Release builds - so at least developers running the debug version should not send telemetry. I'm about to land patches to build release versions in automation. With that and the upcoming feature flags we might be able to add another barrier and only enable this in automation builds.

**Comment by mcomella** [comment]
> I'm about to land patches to build release versions in automation.

Do we expect the builds, when running UI tests against them, to upload telemetry?

**Comment by pocmo** [comment]
> Do we expect the builds, when running UI tests against them, to upload telemetry?

UI tests are currently only running on buddybuild against debug versions (without telemetry).
