### ISSUE TITLE
[Partners] Customize Default Search Engine

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#1422]
Preload partners have a need to for the default search engine to go to partner specified source with search referral attribution link for accounting purposes.

Please provide a T-shirt estimate for this work.
S: 1 Sprint
M: 2 - 3 Sprints
L: 4 - 6 Sprints

**Comment by antlam** [comment]
There might also be some UX here. 

For example, we say "Search for **search term**" right now. To be clear, we could say "Search Partner.com for **search term**" or even incorporate a branded favicon

**Comment by mcomella** [comment]
@Sdaswani Is there a list of all the expected partner work here? I don't want to come up with a one-off solution for default search engines if it'd overlap with other solutions.

**Comment by antlam** [comment]
WIP Mock to show possibilities, not final design:

![typing suggestions - mdpi](https://user-images.githubusercontent.com/1994820/31141785-31c1275e-a82d-11e7-8142-4aba862bd256.png)

**Comment by mcomella** [comment]
Not actively working on this.
