### ISSUE TITLE
[Partners] 'Open With Firefox' Link Should Be Customizable

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#1424]
Partners should be able to specify the version Firefox to open from the 'Open in Firefox' menu item (through Adjust). UX is included here as the 'Open In Firefox' flow may be changing. If it's not changing it's largely an Engineering ask.

Please provide both a UX and Engineering T-shirt estimate for this work. The Engineering T-Shirt estimate will follow the UX designs.
S: 1 Sprint
M: 2 - 3 Sprints
L: 4 - 6 Sprints

**Comment by antlam** [comment]
Given that we've yet to finalize our next iteration of this UX, I'm over-sizing and calling this a M for now.

**Comment by antlam** [comment]
WIP Mock to show possibilities, not final design:

![menu - mdpi](https://user-images.githubusercontent.com/1994820/31141756-2082f148-a82d-11e7-894f-614e9043018f.png)

**Comment by pocmo** [comment]
Note that the static "Open with Firefox" that is mentioned in the first issue doesn't exist anymore. There's only "Open with..." and "Open with [default app]". I guess this would be a new additional menu item?

**Comment by antlam** [comment]
Yup, WIP still. But that's where our thinking is at right now.
