### ISSUE TITLE
[Partners] About Page Should Be Partner-Brandable

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#1425]
The about screen should be able to have branding elements of partners.

It should be easily-configurable so we don't have to do custom work on a per-partner basis.

Please provide both a UX and Engineering T-shirt estimate for this work. The Engineering T-Shirt estimate will follow the UX designs.
S: 1 Sprint
M: 2 - 3 Sprints
L: 4 - 6 Sprints

**Comment by antlam** [comment]
WIP Mock to show possibilities, not final design:

![about - mdpi](https://user-images.githubusercontent.com/1994820/31141726-0f7a2984-a82d-11e7-942e-a2d191ac33ef.png)
