### ISSUE TITLE
Firefox focus settings should be have an option for enable/disable screenshot protection

### ISSUE THREAD

**Issue by afarsi** [mozilla-mobile/focus-android#1426]
Hi there.
I'm testing Firefox Focus for Android via BuddyBuild.
I saw a problem in Firefox Focus for Android, that was related to RTL. But when i wanted to take screenshot from Firefox focus, it's screenshot protection, blocked me from taking screenshot. I forced to use camera of another phone and take a shot from screen of that phone!
Most of messengers and Apps, you can disable/enable screen protection via settings. I think we should have a thing like it, in Firefox Focus also.
Thanks.
Amir Farsi
Member of Persian L10n Team.

**Comment by yaron-tracxpoint** [comment]
Can you try the screencap method and tell us if it worked?
https://blog.shvetsov.com/2013/02/grab-android-screenshot-to-computer-via.html

**Comment by yarons** [comment]
Can you try the screencap method and tell us if it worked?
https://github.com/mozilla-mobile/focus-android/issues/1426

**Comment by afarsi** [comment]
My Phone is Huawei Y6 Pro(TIT-AL00) with Android 5.1 and Huawei's EMUI 3.1 Lite launcher.
It have an option in it's control center and if i press it;s it will take screenshot.

**Comment by pocmo** [comment]
There is a "Stealth" setting that controls taking screenshots.
