### ISSUE TITLE
Using https://encrypted.google.com/ instead of google.com in Firefox Focus

### ISSUE THREAD

**Issue by afarsi** [mozilla-mobile/focus-android#1428]
Hi there.
1-I saw focus using google.com for it's search engine(At least one of them is google). But it's using common version of google. I think use https://encrypted.google.com/ is more compatible with Focus mission.
2-In addition, why you don't add https://www.startpage.com as a secure search engine to focus? If because it's not mozilla's partner?

**Comment by afarsi** [comment]
If i want to describe why we need to use https://encrypted.google.com instead of https//:www.google.com it's reason is when in some countries gov make https slow or block https protocol, google will redirect https://www.google.com to http://www.google.com automaticly and finally, user will see the google(But non https version of google) and will do his search while gov can catch all of http connections and apply any filtering on specific keywords in search resuls. But google recommeded to users to enter https://encrypted.google.com to be sure they are using https version of google and it will not redirect to http version of it. In https:.//encrypted.google.com if https connection was slow, site will not show(via http version of it) and common users will understand filtering by gov and they will force to use VPN and like it to see google and they will sure gov will not catch their search by sneaky techniques.
Thanks.

**Comment by pocmo** [comment]
* encrypted.google.com -> #1175

 * startpage.com and others -> #808

**Comment by pocmo** [comment]
>  it's reason is when in some countries gov make https slow or block https protocol, google will redirect https://www.google.com to http://www.google.com automaticly and finally

Is this documented somewhere? Or is it just something you observed?

**Comment by afarsi** [comment]
Thre isn't official documents, because govs never publish official docs about these things.
But there is a sample news and find https in it and google in this page:
https://www.voanews.com/a/iran_gmail_block/1514149.html

Note: Currently, https version of google is open, but as i said, some times https is blocked.

Another document(If you can accept wikipedia):
https://en.wikipedia.org/wiki/Deep_packet_inspection
Look at China and Iran

Other docs that you can look at them:
https://xenatisch.wordpress.com/2011/03/24/ssl-security-issue-caused-by-the-iranian-government-in-depth-look/
https://en.wikipedia.org/wiki/Internet_censorship_in_Iran

**Comment by pocmo** [comment]
Oh, yeah, sorry, my question was not precise. I have no doubts that governments interfere in various ways. I was wondering whether the different behavior between google.com and encrypted.google.com is mentioned somewhere. I couldn't find anything about that.

**Comment by afarsi** [comment]
I think this section of this news in VOA is enough reason:
“Google is not accessible on https, but it's open on http,” a Tehran-based computer science graduate told VOA in a Facebook interview.

Websites using https are considered secure, while http sites are susceptible to monitoring by virtually anyone, including governments.

Look at here again: https://www.voanews.com/a/iran_gmail_block/1514149.html


In addition, i know about recently google using https in all of searchs by default. But i think use encrypted subdomain will have more trust to avoid any bad dns hijacking, change related records to google.com in country dns servers and like it.
**If there wasn't any benefit, why google countinued maitaining and using encrypted subdmain also, while using https in default google.com yet?**

Really, i coudn't find any document that can describe what's diffrent between default https://www.google.com and https://encrypted.google.com, but i **exprienced redirection of google.com https to http version of google.com some times in Iran**(As we as VOA's news article).

Finally, you can directly ask google about if there is any different thing between encrypted.google.com and https://www.google.com? and why they are using encrypted subdomain yet?

**Comment by liuche** [comment]
UX and Product to look into this @bbinto @lime124

**Comment by amiraliakbari** [comment]
Starting from May 2018, `encrypted.google.com` is turned off and it is simply redirected to `www.google.com`. See [Encrypted.google.com is going away](https://support.google.com/websearch/answer/7631341). I think this issue can be closed now.

**Comment by pocmo** [comment]
Thank you @amiraliakbari!
