### ISSUE TITLE
Switch from findbugs to spotbugs?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1433]
Following https://github.com/mozilla-mobile/telemetry-android/issues/41 - Should we switch from findbugs to spotbugs?

Spotbugs:
https://github.com/findbugsproject/findbugs#readme

**Comment by liuche** [comment]
This involves a small change to our build config.

**Comment by grubdragon** [comment]
Could I take this up?

**Comment by mcomella** [comment]
@grubdragon Sure! The steps for this bug:
- Summarize why findbugs development stopped: https://github.com/findbugsproject/findbugs#readme
- Switch to spotbugs

Thanks for your help! :)

**Comment by vladioan3** [comment]
Why to switch to Spotbugs?
- It can analyze programs compiled for any version of Java, from 1.0 to 1.9.
- Checks for more than 400 bug patterns
- Is extensible. New detectors can be added through plugins.
- Findbugs seems to be dead: https://github.com/findbugsproject/findbugs/issues/161
- Supports FindBugsFilter

**Comment by grubdragon** [comment]
Thanks @vladioan3, I'm short of time these days.
