### ISSUE TITLE
Research mocking frameworks for Kotlin

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1439]
It seems like I can't use Mockito with Kotlin code. This makes testing some of the "What's new" code complicated. I wonder if there are frameworks or tools to mock Kotlin code like Mockito does with Java code.

**Comment by pocmo** [comment]
Some resources:
* https://github.com/mockito/mockito/wiki/Mockito-for-Kotlin
* https://github.com/nhaarman/mockito-kotlin

**Comment by Bringoff** [comment]
@pocmo Mockito 2 should be able to mock Kotlin classes (that are final by default). https://antonioleiva.com/mockito-2-kotlin/

**Comment by pocmo** [comment]
@Bringoff Thanks! I'll have a look.

In my case I wanted to mock an extension property that I attached to Android's `Context` class. And I just wasn't able to. :)

**Comment by Bringoff** [comment]
@pocmo haven’t used extention properties yet, but if talking about extention functions, they are just static functions with extended object as the  first parameter, so PowerMock or something else what is able to mock static methods might be the solution.

**Comment by pocmo** [comment]
> @pocmo Mockito 2 should be able to mock Kotlin classes (that are final by default). https://antonioleiva.com/mockito-2-kotlin/

Just used this and adding the configuration file was enough. I think there's no need for additional research for now. Closing! :)
