### ISSUE TITLE
Android O allows you to create duplicate homescreen shortcuts but titles must unexpectedly be the same

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1444]
UX #1509 

STR:
0) On Android O
1) Open focus, navigate to a page
2) Create and place a homescreen shortcut
3) Return to Focus on the same page
4) Create another homescreen shortcut with a different title

Expected: either a) one homescreen shortcut can be created (the behavior in Marshmallow), b) you can create two shortcuts but can't modify the title on any but the first, or c) you can have two shortcuts with different titles
Actual: Two shortcuts appear but they have the same title (note: icons are the same too but they can't be modified so it's not an issue).

Notes:
* The behavior does not change if you close and reopen the app
* Clearing all of the homescreen shortcuts for that site and creating a new homescreen shortcut will allow you to customize the title again.

Since [we pass different titles into `IconCompat.set*Title` method](https://github.com/mozilla-mobile/focus-android/blob/342613b2be15ca788240219c9a0936bc80cd5d90/app/src/main/java/org/mozilla/focus/shortcut/HomeScreen.java#L55), I don't think c) is possible.

I would vote a) as the simplest solution (assuming we can identify if we already have shortcuts) that would prevent the users from being confused and frustrated.

Discovered while working on #1214.

**Comment by pocmo** [comment]
According to telemetry 3% of our users are on Android 8.

**Comment by pocmo** [comment]
I just noticed that we are using the URL as id for the shortcut (second parameter):
https://github.com/mozilla-mobile/focus-android/blob/342613b2be15ca788240219c9a0936bc80cd5d90/app/src/main/java/org/mozilla/focus/shortcut/HomeScreen.java#L53

Replacing this with a UUID seems to fix the issue. Marking this as a "good first issue".

**Comment by epq** [comment]
I'd like to try this issue. By replace with a UUID, do you mean use something like `UUID.randomUUID().toString()` for the second parameter?

**Comment by pocmo** [comment]
> I'd like to try this issue. By replace with a UUID, do you mean use something like UUID.randomUUID().toString() for the second parameter?

Yeah, I think that should work.

**Comment by epq** [comment]
@pocmo Thank you, I tried it and it does work but I realized it solves the issue with:
c) you can have two shortcuts with different titles 
rather than the solution you proposed above:
a) one homescreen shortcut can be created. 
Is that behaviour the one that is desired? I have just submitted a PR with this fix.

**Comment by pocmo** [comment]
> c) you can have two shortcuts with different titles

Yeah, that's the behavior on pre-O too. For now we want to let users create shortcuts (even duplicates) with whatever title they pick in the dialog. 👍
