### ISSUE TITLE
Invisible scrollbar

### ISSUE THREAD

**Issue by OpinionatedGeek** [mozilla-mobile/focus-android#1447]
UX Bug - #1499 

Firefox Focus just doesn't seem to display a vertical scrollbar for any web pages, no matter how long they are. This leads me to lose context of where I am in the page, how long it is, and how much more there is to read or see.

If I look closely, or if there's a coloured banner, I can just about see that there is in fact a white scrollbar on a white background. It auto-hides when not scrolling, but that's not the issue here. It's the fact that it's a white scrollbar on a white background that makes it invisible and therefor not useful.

To see what I mean you can visit any page, even [this list of Github issues](https://github.com/mozilla-mobile/focus-android/issues). I see no scrollbar, and have no context for where I am in the page.

It's much more of an issue with articles on Medium etc. With no proportionally-sized scrollbar, I have no idea how long the article is when I scroll down a bit. If I want to find out how long the article is, I have to repeatedly scroll down until I see the end, then scroll back up to where I was beforehand - something made more difficult by (again) not having a scrollbar to know my previous location.

Is this something peculiar to my setup, or is it generally true for all Focus users? I find it to be a real usability problem. Should it not show the scrollbar in a colour that contrasts sufficiently with the background?

Details:
Firefox Focus
Version: 2.1
Build: #12721912
Android Oreo
Pixel C tablet

**Comment by pocmo** [comment]
On my Pixel XL I can see a scroll bar. But only when scrolling and it's white and translucent - so invisible on white websites. Can you confirm this?

We need to check what our options are here with WebView.

**Comment by OpinionatedGeek** [comment]
@pocmo Yes, that's the behaviour I'm seeing - the scrollbar is invisible on a white background.

**Comment by pocmo** [comment]
For the UX team to decide.

We can:
* Define the scrollbar style: https://developer.android.com/reference/android/webkit/WebView.html#setScrollBarStyle(int)
* Whether the scrollbars should fade when the view is not scrolling: https://developer.android.com/reference/android/view/View.html#setScrollbarFadingEnabled(boolean)
* Define a drawable/color/shape how the scrollbars should look like: https://developer.android.com/reference/android/view/View.html#attr_android:scrollbarThumbVertical
