### ISSUE TITLE
Public wifi spot login page showing error - can't connect

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1448]
Noticed this while traveling last week, e.g

airborne.gogoinflight.com
loginportal8.wanderingwifi.com

all threw an error and I had to open it with Firefox/Chrome to connect to the Wifi.

Probably difficult to reproduce with the exact same URLs but maybe any public wifi spot will show the error.

**Comment by mheubusch** [comment]
FYI. Strings for captive portal detection on Firefox covered in this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1325013

Sharing in case it helps to know who worked on that bug in desktop.

**Comment by pocmo** [comment]
Okay, I need to expense some long distance flights to fix this issue. 🌤 🌴 🍸  :)

@bbinto Do you remember if the page showed any http error codes or some specific error message? Did you see our "dark style" error page?

**Comment by bbinto** [comment]
I'm sure @Sdaswani would approve that request :)

Joke aside, I'll be in Germany this week and will try it again, but it was def. a white standard Android page with the green Android mascot, not sure about the error message again, I should have take a screenshot, will do next time.

**Comment by mcomella** [comment]
Maybe related to SSL errors, which I can't reproduce in Firefox or Chrome: #1338

**Comment by liuche** [comment]
@bbinto wants to verify this
