### ISSUE TITLE
Export Granite Strings

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#1453]

**Comment by liuche** [comment]
Checked in with UX and it sounds like there will be strings up this evening: strings for the feature as well as alternative strings for a fallback version if the scope of the mocks ends up being too big for the feature (and Brian will be on PTO, so we can't get more strings).

I'll reassign if I need someone else to export these strings for Wednesday.

**Comment by liuche** [comment]
@pocmo If you don't get to this tomorrow during your work day I'll export the strings!

**Comment by liuche** [comment]
PR opened to l10n, and pinged Delphine. It might be at the end of her day so I'll monitor and make changes if needed.

...also for the record, doing strings export without mocks is *extremely* painful, and requires a lot of cross-referencing and constant real-time discussion, so let's not give UX such little lead time next time between prioritization and string freeze.

**Comment by pocmo** [comment]
> ...also for the record, doing strings export without mocks is extremely painful, and requires a lot of cross-referencing and constant real-time discussion, so let's not give UX such little lead time next time between prioritization and string freeze.

Absolutely agree. I'm more in more in favor of adding more time to translate things at the end of the sprint. If we run into issues actually implementing the feature we have no time to adapt anymore.

**Comment by Sdaswani** [comment]
Localizing after the strings are set is an option, but it’s a bit risky as since we don’t have an SLA that strings will be localized in a certain time frame it could risk our release date, which other cross functional teams depend on. We used to indeed localize at the end of development at Lookout but the localization turn around was something we could plan for and it was pretty short (2-3 Days).

**Comment by Sdaswani** [comment]
Also @antlam suggested we release features for English first and let the localizations follow but I’m worried about branching UI based on language 😂.
