### ISSUE TITLE
String import errors: cak, mix

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1456]
* https://bugzilla.mozilla.org/show_bug.cgi?id=1406938
* https://bugzilla.mozilla.org/show_bug.cgi?id=1406940

**Comment by Delphine** [comment]
Thanks Sebastian, looking into these now.

**Comment by Delphine** [comment]
Should be fixed for "cak" locale: https://bugzilla.mozilla.org/show_bug.cgi?id=1406938#c2
LMK if it's not the case. thanks!

**Comment by pocmo** [comment]
This seems to be fixed.
