### ISSUE TITLE
Remove overflow menu from settings

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#146]
Instead move help etc. into the list of settings as an item.

**Comment by pocmo** [comment]
@antlam I wonder if it's weird that on the start page you have settings AND help etc. And then when you go to settings you have those options again. Should we remove them from this overflow menu too (but then we only have settings in there) or only from the browser toolbar menu?

**Comment by antlam** [comment]
Yes! Sorry that must've been unclear. I was thinking we would have the following states for the Overflow button.

Home:
- Settings
- About
- Help
- Your rights

Browsing (toolbar):
- Settings
- plus everything else...

Settings:
-Remove

@pocmo can we try that ^?

**Comment by ahunt** [comment]
Just to double check: we don't want to link to about/help/rights from settings at all? (IIRC Sebastian was suggesting listing about/help/rights as settings items, like we do in firefox?)

**Comment by antlam** [comment]
We want to link to them. But have them as items in the list rather than shortcuts in the overflow button.

**Comment by ahunt** [comment]
![abouthelprights](https://cloud.githubusercontent.com/assets/1546915/23656673/f23ac2f8-033a-11e7-84f1-894b34f01b4a.png)

I'm wondering if we want better strings? E.g. "About Focus" (and possibly descriptions below the title?)

**Comment by antlam** [comment]
Yeah, we could say "About Firefox Focus". But we would need to localize those strings.

I don't think we need descriptions below.

@bbinto thoughts? Keep in mind "Send anonymous usage data - Learn more" will be change to be about the Core ping later. So this grouping still kind of makes sense to me ("Mozilla").

**Comment by bbinto** [comment]
@antlam, did you check with Michelle H. for wording?  

In general, I lean towards how we do things in Firefox Android. There it says "About Firefox", so I think "About Firefox Focus" sounds right.

**Comment by antlam** [comment]
@bbinto just reached out - stay tuned!

**Comment by pocmo** [comment]
String freeze is on Friday. We need a decision here.

**Comment by mheubusch** [comment]
I like the idea of About Firefox Focus - I don't know that it adds much beyond what a user would assume, but it does reiterate the name and the association between the app and Firefox.  I think also that because this is a link and not a setting, there is no descriptive content needed other than that title. The description should be reserved for settings you perform in the app.

**Comment by ahunt** [comment]
Are we doing this for just the item in Settings, or also for the main app menu?

**Comment by antlam** [comment]
> Are we doing this for just the item in Settings, or also for the main app menu?

Just for the item inside Settings
