### ISSUE TITLE
changeLocale() in SwitchLocaleTest persists after the tests sporadically

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1471]
In the latest master test result (https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/build/59df7d6f09336900015ebe51), all UITest failures are caused by the app being set to French locale intermittently.  This seem to be caused by SwitchLocaleTest.  When SwitchLocaleTest is disabled, this does not appear.  Looks like way we set the locale in [changeLocale()](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/androidTest/java/org/mozilla/focus/activity/SwitchLocaleTest.java#L67) persists after the test - we need a way to reset this change.  

@pocmo was anything changed locale wise in Focus recently?

**Comment by npark-mozilla** [comment]
Perhaps we should change locale within the app, rather than using the context.createConfigurationContext() ?

**Comment by pocmo** [comment]
I saw this locally too yesterday. But I thought I pushed a fix for that. Let me check.

**Comment by npark-mozilla** [comment]
So I am now seeing a slight behavior change on Focus app. On android API 25 simulator and Nexus 5, It appears that changeLocale() requires some time before changing the locale, as before it was near instantaneous.  If I step through the debugger and pause for good 3-4 seconds after changeLocale(), the locale is changed to French and the test passes with no issue.  If I don't wait, this test will fail and next test, EnglishSystemLocaleTest() will start in French locale.
I'm not sure what caused this delay - I wonder whether we can wait for the system locale to be changed.

**Comment by npark-mozilla** [comment]
Looks like switchLocaleTest requires various fixes as well, we should address it with this bug

**Comment by npark-mozilla** [comment]
Another possible issue is that when the Locale is set from the settings, it doesn't get reverted to system locale on next test.  When the locale is set to English in settings, and the test ends, on next test the locale is set to 'English' instead of 'System Locale' in the Language menu in settings.  I guess it gets stored in the app preference data?

**Comment by npark-mozilla** [comment]
https://github.com/mozilla-mobile/focus-android/pull/1480 created

**Comment by npark-mozilla** [comment]
Turns out #1480 really fixed the issue when I extended the timing between locale set and app start. Closing.
