### ISSUE TITLE
Consider checking webview version

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#148]
While working on error pages, I noticed that my phone was running an outdated webkit  (Nexus 5 running Android 6 - I had recently done a factory reset, so some things were out of date). In this case, I was using WebView 44 (56 is current?).

(Firefox error pages use a CSS feature that is only supported in chrome 49+, which is how I noticed this.)

Running an outdated browser engine as part of focus is obviously a bad idea, so do we want to have runtime checks / enforcement? According to google's docs ( https://developer.chrome.com/multidevice/webview/overview ) Android 5 and newer will have an auto-updating webview, so it's not unreasonable to ask users to make sure they've got a reasonably up-to-date webview version installed?

**Comment by ahunt** [comment]
To make this more fun: I didn't get any prompts to update the webview since the factory reset (i.e. in 24 hours). The "My apps and games" screen in Google play also doesn't list the webview. I had to search for the system webview in Google Play to actually update it. I wonder how well the "auto-update" aspect actually works in practice.

(I did have a prompt to install security updates though, so it's possible that would've also updated the webview and/or that was blocking automatic webview updates.)

**Comment by pocmo** [comment]
On Android N+ it's even more complicated: WebView isn't updated from Google Play but instead is using Chrome directly.

> (Firefox error pages use a CSS feature that is only supported in chrome 49+, which is how I noticed this.)

Is our plan to reuse the ones from Firefox? I thought we are going to start with our own very simplistic version. I guess no one cared about non-Gecko browsers for internal pages. :)

**Comment by ahunt** [comment]
antlam suggested using the fennec pages in https://github.com/mozilla-mobile/focus-android/issues/33#issuecomment-282168992 . I'm only reusing the html/css, since the JS isn't relevant to focus.

**Comment by pocmo** [comment]
We decided to not do a check in v1: We can't really know which version is the "latest" one for a specific device or whether it's WebView.apk or Chrome.apk (or the system) that needs updating.

For the error pages we should make sure that they do not use any fancy web features. We should be able to make simple ones that work even with Firefox 1. :)
