### ISSUE TITLE
TFL.gov website content problems

### ISSUE THREAD

**Issue by simonsteiner1984** [mozilla-mobile/focus-android#1481]
If you plan a journey at https://tfl.gov.uk/ from Tottenham Court Road, London, United Kingdom to Oxford Circus Underground Station for example, it only gives bus route not tube, works fine in chrome

**Comment by mcomella** [comment]
For this bug, please investigate, and report back, if this is a problem with Focus (and determine if we can fix it) or if it's a problem with the WebView (in which case we'll have to file a bug against chromium or add a comment to an existing bug).

**Comment by ekager** [comment]
This seems to be working with Nightly. @simonsteiner1984 could you confirm this is still a problem for you?
