### ISSUE TITLE
Feature request: cookies "gray-list" &  option to auto accept cookies / disable location

### ISSUE THREAD

**Issue by huuhaa** [mozilla-mobile/focus-android#1485]
Some sites (like duckduckgo.com or hight.fi  (Finnish news page] use cookies to store selected theme selection, or maybe for "starred news" at high.fi also.

So it would be great if user could add some sites at "gray list", which would mean that user could select that for this site remember only theme selection, delete everything other data when erasing history. Or if wishes for other site, remember also that "starred news" & theme, maybe location approvement selections for some site, but delete everything else when erasing history.

And since erase is one common things to do when ending browsing with Focus, I would like an option to auto accept cookies so I wouldn't have to answer that question every time I visit at some site. After all I erase that at the end anyway.

With that said, I would also like an option to auto disable location / allow only for sites at "gray list" with location approvement. So that question wouldn't pop up everytime eather.

Just some of my ideas.

**Comment by bbinto** [comment]
Closing this in favour of #1041 and #1651
