### ISSUE TITLE
Feature request: Possibility to add "quick selection" icon to start screen.

### ISSUE THREAD

**Issue by huuhaa** [mozilla-mobile/focus-android#1487]
Please add possibility to add "quick selection" icon of web page to start screen, It might be just me, but I feel it clumsy to open browser, then if you decide to go at some website you already have at home screen (or folder at heme screen), you have to switch browser to background or close it. Then looking the right shortcut from home screen...

I personally would love an option to add 9 quick selection icons at start screen and maybe side swipe for have 9 more (with dots at bottom to show how many pages there are and which page you at at the moment. Sure there should be some max limit for pages I think. Only for most used ones, like 3-5 pages).

**Comment by bbinto** [comment]
Thanks, please follow #1546 for more ideas and progress
