### ISSUE TITLE
Link to default browser SUMO page

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#149]
In #72 we added a setting that links to Android's "default apps" page for setting Focus as default browser (Android N+). On older versions we need to link to a SUMO page. Right now we just hide the setting in this case.

**Comment by ahunt** [comment]
I wonder if we should get a new focus-specific and/or generic version of this page - it mentions firefox multiple times:
https://support.mozilla.org/kb/make-firefox-default-browser-android?utm_source=inproduct&amp;utm_medium=settings&amp;utm_campaign=mobileandroid

**Comment by pocmo** [comment]
@bbinto @antlam What do you think? Who could help us create a page if needed?

**Comment by antlam** [comment]
I think we just talked about this and @bbinto mentioned she would reach out to Joni or Roland? Is that correct?

**Comment by bbinto** [comment]
+ @jonisavage, could we add Focus to this page as well for launch?

**Comment by pocmo** [comment]
@ahunt Here are the links: https://docs.google.com/a/mozilla.com/spreadsheets/d/1utt7lgWClxyl6LdnkLFEtFZH7wf-nBg5MTbFfuZLgf4/edit?disco=AAAAA-Tevfw&usp=comment_email_document
