### ISSUE TITLE
Calling preventDefault() in a contextmenu event doesn't work

### ISSUE THREAD

**Issue by MisaelK** [mozilla-mobile/focus-android#1493]
After setting an event listener on any element and using the `contextmenu` event, calling `event.preventDefault()` doesn't prevent the context menu from appearing.

My setup: OnePlus 2 A2005 (Android 6.0.1), Firefox Focus 2.1 (Build 12721912).

I wrote a small codepen to test this: https://codepen.io/MisaelK/pen/mBaZzG

I also tested this in Firefox 56.0 and Chrome 61.0.3163.98 in the same device, and both browsers display the expected behavior of not showing the context menu.

**Comment by pocmo** [comment]
Added the [help wanted] label: I'm not even sure if we can honor preventDefault() here - but if: Patches welcome!
