### ISSUE TITLE
[breakdown] Extract Fennec Switchboard into Reuseable Library

### ISSUE THREAD

**Issue by jenn-chaulk** [mozilla-mobile/focus-android#1494]
Breakdown Issue #1431

**Comment by pocmo** [comment]
### Tasks

#### Must-have
* Finalize and test Kinto configuration/admin for server-side configuration of experiments
* Create separate repository and minimal CI environment for library
* Implement client for loading (partial) experiment configuration from server
* Implement storage for saving experiment configuration to disk
* Implement code for evaluation configuration and bucketing users
* Implement simple API for checking if an installation is part of an experiment
* Deploy experiments library to jcenter
* Integrate experiments library into Focus

#### Nice-to-have / Improvements
* Implement simple API for getting experiment metadata
* Add mechanism for overriding the local experiment configuration
* Add developer/debug UI for setting experiment overrides

**Comment by pocmo** [comment]
Another Nice-to-have:
* Verify signatures of experiments collection

**Comment by pocmo** [comment]
Added this and some additional items to the meta bug #1431.
