### ISSUE TITLE
[breakdown] Block app install banners and EU cookie banners

### ISSUE THREAD

**Issue by jenn-chaulk** [mozilla-mobile/focus-android#1497]
Breakdown issue #1254

**Comment by pocmo** [comment]
@bbinto P2 and P3? :)

**Comment by pocmo** [comment]
Explanation of Adblock filter rules:
https://adblockplus.org/filters

Blocklist for Cookie banners etc:
https://www.fanboy.co.nz/fanboy-cookiemonster.txt

The cookie blocking list updates frequently. We might want to think about updating it from a server (and without an app update) or shipping updates in every dot release and somehow automating this.

**Comment by bbinto** [comment]
They might have to be vetted by policy/legal first.
