### ISSUE TITLE
[UX] Invisible scrollbar

### ISSUE THREAD

**Issue by jenn-chaulk** [mozilla-mobile/focus-android#1499]
Design for issue #1447

**Comment by pocmo** [comment]
@lime124 Here's a screenshot of the new scrollbar. The PR sets the scrollbar to be 4dp in size and to use color #aaaaaaaa (ARGB). The change is noticeable on white only really - where previously the scrollbar was invisible.

![nytimes](https://user-images.githubusercontent.com/89638/32556420-a9392348-c49f-11e7-9b42-b1c5cb55b180.png)

**Comment by pocmo** [comment]
@lime124 Did you make a decision here? Should we land the contributor patch?

**Comment by lime124** [comment]
Sorry for the delay! Can we try #b2b2b2 with 70% opacity? Thanks!

**Comment by pocmo** [comment]
@Benestar Do you have time to update your PR #1621 with those values? :)

**Comment by Benestar** [comment]
Sorry for my late response, quite busy irl right now. I will update the color code and create another screenshot.

**Comment by lime124** [comment]
Awesome - looks great! Thanks so much!

**Comment by Benestar** [comment]
Thanks for your quick feedback! :-)

**Comment by pocmo** [comment]
@lime124 Merged the patch from @Benestar and closed the engineering issue #1447. Should we close this one here too or do you want to revisit this?

**Comment by lime124** [comment]
oops good call :)
