### ISSUE TITLE
Add proper launcher icon

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#15]
Our current icon is the iOS icon dropped into Android's asset studio. The result looks quite bad. We need an actual icon.

**Comment by antlam** [comment]
Sean Martell made the current one. I'm going to ping him for an Android one.

**Comment by pocmo** [comment]
@antlam Soft ping: Is this in progress? :)

**Comment by antlam** [comment]
Yup! Will check in with Sean again

**Comment by antlam** [comment]
[Launcher icon.zip](https://github.com/mozilla-mobile/focus-android/files/817759/Launcher.icon.zip)

Try these!

**Comment by pocmo** [comment]
Thanks! I'll add them. Can you attach a xxxhdpi version too (192 x 192 px)?

**Comment by pocmo** [comment]
![icon_grid](https://cloud.githubusercontent.com/assets/89638/23615140/b5186b56-0285-11e7-8bbd-6cf10e1dcb3f.png)

The icon doesn't look too good on a bright background (This is the official Google launcher). Maybe it's better if we add the characteristic shadow?

* https://romannurik.github.io/AndroidAssetStudio/
* https://material.io/guidelines/style/icons.html

**Comment by pocmo** [comment]
Just for comparison, this is the result when throwing the icon into the asset studio mentioned above:

![ic_launcher](https://cloud.githubusercontent.com/assets/89638/23615706/99b48460-0287-11e7-92e7-ee92413b7fa3.png)

**Comment by antlam** [comment]
![focus_logo-hdpi-72](https://cloud.githubusercontent.com/assets/1994820/23641585/e689b0fe-02a9-11e7-8c21-50cf5c19812a.png)
![focus_logo-ldpi-32](https://cloud.githubusercontent.com/assets/1994820/23641583/e688de68-02a9-11e7-816c-6248354c42d8.png)
![focus_logo-mdpi-48](https://cloud.githubusercontent.com/assets/1994820/23641587/e68cd7b6-02a9-11e7-84ab-be1f062d1916.png)
![focus_logo-xhdpi-96](https://cloud.githubusercontent.com/assets/1994820/23641584/e68903d4-02a9-11e7-9419-2e0a8def8990.png)
![focus_logo-xxhdpi-144](https://cloud.githubusercontent.com/assets/1994820/23641588/e68ebb30-02a9-11e7-9a22-bf74796efc00.png)
![focus_logo-xxxhdpi-192](https://cloud.githubusercontent.com/assets/1994820/23641586/e68b1b9c-02a9-11e7-830d-ccd6df783e39.png)

Got some icons from Sean! Try these ^
