### ISSUE TITLE
ghacks.net UI issues

### ISSUE THREAD

**Issue by simonsteiner1984** [mozilla-mobile/focus-android#1500]
Goto ghacks.net and appearance is different from chrome, some pages on the site switch between styles/ reload as you scroll making it unusable

**Comment by pocmo** [comment]
Can you post your user agent string to help us debug this issue?

**Comment by simonsteiner1984** [comment]
Mozilla/5.0 (Linux; Android 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/2.2 Chrome/61.0.3163.98 Mobile Safari/537.36

**Comment by simonsteiner1984** [comment]
Phone is 480 x 854 pixels

**Comment by mcomella** [comment]
For this bug, please investigate, and report back, if this is a problem with Focus (and determine if we can fix it) or if it's a problem with the WebView (in which case we'll have to file a bug against chromium or add a comment to an existing bug).

One idea: we don't cache intermediate CAs so it's possible that we're dropping the SSL connections to the page's resources (#1338).

**Comment by ekager** [comment]
Hi @simonsteiner1984 are you still seeing this issue with newer versions of Focus? I don't see this with GV

**Comment by simonsteiner1984** [comment]
I'm no longer a user of focus
