### ISSUE TITLE
IllegalStateException: SessionDurationMeasurement.recordSessionEnd

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1502]
```
Caused by: java.lang.IllegalStateException:  
  at org.mozilla.telemetry.measurement.SessionDurationMeasurement.recordSessionEnd (SessionDurationMeasurement.java:41)
  at org.mozilla.telemetry.Telemetry.recordSessionEnd (Telemetry.java:143)
  at org.mozilla.focus.telemetry.TelemetryWrapper.stopSession (TelemetryWrapper.java:229)
  at org.mozilla.focus.activity.MainActivity.onPause (MainActivity.java:115)
```

**Comment by pocmo** [comment]
We call startSession() from MainActivity.onResume() and stopSession() from MainActivity.onPause(). For this error to occur there would be a call to onPause() without a call to onResume().

Almost all devices in the list have a "Galaxy ****" name. I wonder if this could be a device specific bug. Affected are Android 5.0, 5.1 and 6.0.

**Comment by pocmo** [comment]
Looks like there are other developers having problems with components that register/unregister in onResumse/onPause and Samsung devices:
https://issuetracker.google.com/issues/37001269#c3

**Comment by mcomella** [comment]
This happened in fennec – https://bugzilla.mozilla.org/show_bug.cgi?id=1317191 – and they fixed it there so see that bug for inspiration.

**Comment by mcomella** [comment]
There is also a newer `recordSessionStart` bug in fennec - https://bugzilla.mozilla.org/show_bug.cgi?id=1405192 - and that could be related to their fix for `recordSessionEnd`.

**Comment by pocmo** [comment]
The activity duplicates are interesting and I would like to debug if we see that too (MainActivity existing twice for a short amount of time).

I wonder how the Architecture Components handle that. They have to track the lifecycle state too. Maybe they have implemented a workaround too.
