### ISSUE TITLE
[meta] iterate on the onboarding experience

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1506]
As we saw during the work week, retention numbers are not ideal. One area we identified was to improve our onboarding experience. 

[ ] UX ticket #1507

**Comment by jenn-chaulk** [comment]
Kamino cloned this issue to mozilla-mobile/focus-android

**Comment by jenn-chaulk** [comment]
Kamino cloned this issue to mozilla-mobile/focus-android

**Comment by jenn-chaulk** [comment]
Kamino cloned this issue to mozilla-mobile/focus-android

**Comment by jenn-chaulk** [comment]
Kamino cloned this issue to mozilla-mobile/focus-android
