### ISSUE TITLE
[meta][ux] improve onboarding experience

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1507]
This ux ticket for this work.
- [ ] #1508 

From breakdown:
- [ ] #1593 research
- [ ] #1594 design phase I
- [ ] #1595 design phase II
- [ ] #1596 research/usability testing
- [ ] #1597 iterate designs
- [ ] #1598 deliverables

**Comment by bbinto** [comment]
@lime124 to create issues from task list

**Comment by bbinto** [comment]
Might be worth reviewing https://github.com/mozilla-mobile/focus-android/issues/762

**Comment by ekager** [comment]
@bbinto @vesta0 these tickets have sat in P2 for a long time but I don't think they've ever been worked on (UX+Engineering). Is this still a high priority?
