### ISSUE TITLE
Adaptive shortcut icons do not adapt

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1516]
Google Pixel XL, Google Launcher

I switched the icon shape in the launcher from circle to squircle. The home screen shortcuts didn't adapt to that. They are still circles, but on a white squircle. I added a new shortcut after the change and it also isn't a squircle.

**Comment by pocmo** [comment]
![screenshot_20171019-204452](https://user-images.githubusercontent.com/89638/31788442-f9055086-b50e-11e7-9df7-726626d1583b.png)

**Comment by mcomella** [comment]
Originally implemented in #1214.

**Comment by pocmo** [comment]
9d34d919b265a245bf95dcca110b0925ca559cbb

**Comment by npark-mozilla** [comment]
@pocmo When I run the latest build, I see the circle shortcut (but no white squircle) on Pixel 2 device, Android 8.0, instead of squircle. Is this specific to certain android api version?

**Comment by ekager** [comment]
Hi @npark-mozilla ! You have to [enable UI Tuner on Pixel ](https://www.howtogeek.com/270568/how-to-enable-android%E2%80%99s-%E2%80%9Csystem-ui-tuner%E2%80%9D-for-access-to-experimental-features/) and then [change icon shape](https://www.androidauthority.com/change-icon-shape-pixel-launcher-773473/).

**Comment by pocmo** [comment]
If you have the Google launcher installed you can also long press the home screen -> "home settings" -> Change icon shape

**Comment by npark-mozilla** [comment]
Ahh, thanks!
