### ISSUE TITLE
very.badssl.com shows lock icon

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1522]
We are showing a lock icon on https://very.badssl.com/ - Fennec and Chrome do not.

**Comment by ekager** [comment]
Logcat shows: 

10-26 16:57:02.246 4234-4234/org.mozilla.focus.debug I/chromium: [INFO:CONSOLE(39)] "Mixed Content: The page at 'https://very.badssl.com/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://http.badssl.com/resources/form-submitted.html'. This endpoint should be made available over a secure connection.", source: https://very.badssl.com/ (39)

10-26 16:57:02.246 4234-4234/org.mozilla.focus.debug I/chromium: [INFO:CONSOLE(49)] "Mixed Content: The page at 'https://very.badssl.com/' was loaded over HTTPS, but requested an insecure image 'http://very.badssl.com/image.jpg'. This request has been blocked; the content must be served over HTTPS.", source: https://very.badssl.com/ (49)

10-26 16:57:02.247 4234-4234/org.mozilla.focus.debug I/chromium: [INFO:CONSOLE(0)] "Mixed Content: The page at 'https://very.badssl.com/' was loaded over HTTPS, but requested an insecure script 'http://http.badssl.com/test/imported.js'. This request has been blocked; the content must be served over HTTPS.", source: https://very.badssl.com/ (0)

10-26 16:57:02.331 4234-4234/org.mozilla.focus.debug V/certificate: Issued to: CN=*.badssl.com,O=Lucas Garron,L=Walnut Creek,ST=California,C=US;
                                                                    Issued by: CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US;

It seems like we are able to detect that the site contains insecure images and forms, but the lock icon itself and the session boolean "secure" is currently based only on the certificate being null/non-null.

**Comment by pocmo** [comment]
Can you investigate if there's any way to know about the mix content in code? When filing this bug I looked at WebViewClient.onReceivedSslError() - but this one doesn't get called.

**Comment by ekager** [comment]
No neither WebViewClient.onReceivedSslError() nor WebViewClient.onReceivedError() gets called when loading very.badssl.com. I looked into [Lightning Browser](https://github.com/anthonycr/Lightning-Browser/blob/dev/app/src/main/java/acr/browser/lightning/view/LightningWebClient.kt) (another open source WebView based browser) and they also do not detect mixed content, in fact they allow it to be displayed, which we do not. Since API 21, WebView blocks Mixed Content by default.

**Comment by pocmo** [comment]
This is fixed in our GeckoView version 🎉
