### ISSUE TITLE
Increase 4MB apk size limit

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1523]
Currently build is failing on master because it's over 4MB limit

**Comment by pocmo** [comment]
Background: For our first release we decided to not exceed a limit of 4 MB. Back then we added this check that will fail the build once we exceed it. With a small app we wanted to explore whether this improves our install rate (especially in countries where mobile traffic is expensive or limited).

We deployed a quick fix to raise this limit to 4.5 MB - But we need to make a decision whether we still care about this limit (or pick a new one). With multitasking and other features we managed to squeeze a lot of things into 4 MB and it might be impossible to keep this forever. Some previous ideas and investigations are documented in #624.

**Comment by bbinto** [comment]
I think there is nothing wrong with keeping a cap on the size of the app. We should not deviate more than +1MB from the original APK size limit.

So can we up it to 5MB?

**Comment by pocmo** [comment]
> So can we up it to 5MB?

Alright!

**Comment by mcomella** [comment]
Closed in 3c06788eef9ddfa8cc628c1d7c628073ec7fd50b.
