### ISSUE TITLE
[Meta] Quick access to favourite sites 

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1525]
User Story:
- As a user, I want to access my frequently visited websites without always having to type in the full URL
- As a user, I want to frequent my favorite website without having to login each time

Some ideas that were floating around (without being prescriptive)
- Allow users to add their own defined sites to an autocomplete list
- Promote "Add to Homescreen" as a way of bookmarking things

---

- [ ] Autofill -> #1810
- [ ] Autocomplete -> #1820

**Comment by jenn-chaulk** [comment]
Kamino cloned this issue to mozilla-mobile/focus-android

**Comment by jenn-chaulk** [comment]
Kamino cloned this issue to mozilla-mobile/focus-android

**Comment by jenn-chaulk** [comment]
Kamino cloned this issue to mozilla-mobile/focus-android

**Comment by jenn-chaulk** [comment]
Kamino cloned this issue to mozilla-mobile/focus-android
