### ISSUE TITLE
No audio in GeckoView

### ISSUE THREAD

**Issue by shinilms** [mozilla-mobile/focus-android#1527]
There's no audio for videos in GeckoView. I tried to play videos on sites like youtube and vimeo, the video plays well, but there's no audio. And the audio files won't even play in sites like soundcloud.

Edit : Error - **NS_ERROR_DOM_MEDIA_MEDIASINK_ERR (0x806e000b)**

**Comment by pocmo** [comment]
@snorp FYI.

**Comment by shinilms12** [comment]
**this is the error i get on console while trying to play a song in muspleer.audio using geckoView**

`10-25 11:19:31.810 W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc`

`10-25 11:19:31.842 I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es    `                                  

`10-25 11:19:33.899 W/Web Content: [JavaScript Warning: "Media resource http://27.webmusic.in/music/english/artist/w/westlife/unbreakable_the_greatest_hits_vol_1/Miss-You-Nights_(webmusic.in).mp3 could not be decoded." {file: "http://musicpleer.audio/#!e039a5d752b5b5ef6401d0c9493afc84" line: 0}]`

`10-25 11:19:34.850 W/Web Content: [JavaScript Warning: "Media resource http://27.webmusic.in/music/english/artist/w/westlife/unbreakable_the_greatest_hits_vol_1/Miss-You-Nights_(webmusic.in).mp3 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_MEDIASINK_ERR (0x806e000b)
                                  Details: void mozilla::MediaDecoderStateMachine::OnMediaSinkAudioError(nsresult)" {file: "http://musicpleer.audio/#!e039a5d752b5b5ef6401d0c9493afc84" line: 0}]`

**and the following is what I get when trying to play a video in youtube,**

`10-25 11:15:36.809 W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc`

`10-25 11:15:36.844 I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es`

`10-25 11:15:36.946 E/GeckoHardwareCodecCapabilityUtils: Found candidate decoder OMX.google.vp9.decoder`

`10-25 11:15:36.947 E/GeckoHardwareCodecCapabilityUtils: Found candidate decoder OMX.google.vp9.decoder`

`10-25 11:15:36.947 E/GeckoHardwareCodecCapabilityUtils: Found candidate decoder OMX.google.vp9.decoder`

`10-25 11:15:36.948 E/GeckoHardwareCodecCapabilityUtils: Found candidate decoder OMX.google.vp9.decoder`

`10-25 11:15:36.952 E/GeckoHardwareCodecCapabilityUtils: Found candidate decoder OMX.google.vp9.decoder`

`10-25 11:15:36.953 E/GeckoHardwareCodecCapabilityUtils: Found candidate decoder OMX.google.vp9.decoder`

`10-25 11:15:36.954 E/GeckoHardwareCodecCapabilityUtils: Found candidate decoder OMX.google.vp9.decoder`

`10-25 11:15:36.954 E/GeckoHardwareCodecCapabilityUtils: Found candidate decoder OMX.google.vp9.decoder`

`10-25 11:15:36.955 E/GeckoHardwareCodecCapabilityUtils: Found candidate decoder OMX.google.vp9.decoder`

`10-25 11:15:36.956 E/GeckoHardwareCodecCapabilityUtils: Found candidate decoder OMX.google.vp9.decoder`

`10-25 11:15:37.199 E/Web Content: [JavaScript Error: "NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIXPCComponents_Utils.import]" {file: "resource://gre/modules/vtt.jsm" line: 31}]`

`10-25 11:15:37.405 E/Web Content: [JavaScript Error: "downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Roboto" style:italic weight:normal stretch:normal src index:0) source: https://fonts.gstatic.com/s/roboto/v16/vPcynSL0qHq_6dX7lKVByXYhjbSpvc47ee6xR_80Hnw.woff2" {file: "https://m.youtube.com/" line: 11 column: 2973 source: "@font-face {
                                    font-family: "Roboto";
                                    font-style: italic;
                                    font-weight: 400;
                                    src: url("//fonts.gstatic.com/s/roboto/v16/vPcynSL0qHq_6dX7lKVByXYhjbSpvc47ee6xR_80Hnw.woff2") format("woff2");
                                    unicode-range: U+0-FF, U+131, U+152-153, U+2C6, U+2DA, U+2DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
                                  }"}]`

`10-25 11:15:37.405 E/Web Content: [JavaScript Error: "downloadable font: Layout: Failed to parse script table 0 (font-family: "Roboto" style:italic weight:normal stretch:normal src index:0) source: https://fonts.gstatic.com/s/roboto/v16/vPcynSL0qHq_6dX7lKVByXYhjbSpvc47ee6xR_80Hnw.woff2" {file: "https://m.youtube.com/" line: 11 column: 2973 source: "@font-face {
                                    font-family: "Roboto";
                                    font-style: italic;
                                    font-weight: 400;
                                    src: url("//fonts.gstatic.com/s/roboto/v16/vPcynSL0qHq_6dX7lKVByXYhjbSpvc47ee6xR_80Hnw.woff2") format("woff2");
                                    unicode-range: U+0-FF, U+131, U+152-153, U+2C6, U+2DA, U+2DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
                                  }"}]`

`10-25 11:15:37.405 E/Web Content: [JavaScript Error: "downloadable font: GSUB: Failed to parse script list table (font-family: "Roboto" style:italic weight:normal stretch:normal src index:0) source: https://fonts.gstatic.com/s/roboto/v16/vPcynSL0qHq_6dX7lKVByXYhjbSpvc47ee6xR_80Hnw.woff2" {file: "https://m.youtube.com/" line: 11 column: 2973 source: "@font-face {
                                    font-family: "Roboto";
                                    font-style: italic;
                                    font-weight: 400;
                                    src: url("//fonts.gstatic.com/s/roboto/v16/vPcynSL0qHq_6dX7lKVByXYhjbSpvc47ee6xR_80Hnw.woff2") format("woff2");
                                    unicode-range: U+0-FF, U+131, U+152-153, U+2C6, U+2DA, U+2DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
                                  }"}]`

`10-25 11:15:37.405 E/Web Content: [JavaScript Error: "downloadable font: rejected by sanitizer (font-family: "Roboto" style:italic weight:normal stretch:normal src index:0) source: https://fonts.gstatic.com/s/roboto/v16/vPcynSL0qHq_6dX7lKVByXYhjbSpvc47ee6xR_80Hnw.woff2" {file: "https://m.youtube.com/" line: 11 column: 2973 source: "@font-face {
                                    font-family: "Roboto";
                                    font-style: italic;
                                    font-weight: 400;
                                    src: url("//fonts.gstatic.com/s/roboto/v16/vPcynSL0qHq_6dX7lKVByXYhjbSpvc47ee6xR_80Hnw.woff2") format("woff2");
                                    unicode-range: U+0-FF, U+131, U+152-153, U+2C6, U+2DA, U+2DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
                                  }"}]`

**Comment by snorp** [comment]
This is a Gecko bug caused by being in an SDK 24+ app. We're working on a fix here: https://bugzilla.mozilla.org/show_bug.cgi?id=1316934 (or here https://bugzilla.mozilla.org/show_bug.cgi?id=1410456)

**Comment by ekager** [comment]
Fixed

**Comment by trainoasis** [comment]
I'm developing for SDK 22 and it's not working. Should it?

**Comment by snorp** [comment]
> I'm developing for SDK 22 and it's not working. Should it?

Yes. If you're using GeckoView in your own app and experiencing a bug, please file here: https://bugzilla.mozilla.org/enter_bug.cgi?product=GeckoView

We may also be able to help you in #geckoview at https://chat.mozilla.org/
