### ISSUE TITLE
Bump version code in build.gradle

### ISSUE THREAD

**Issue by relan** [mozilla-mobile/focus-android#1528]
Hi,

F-Droid maintainer here. In F-Droid updates checking is decoupled from APK building, so dynamic version code (that depends on date/time) does not work. I decided to stick with the static value in [build.gradle](https://github.com/mozilla-mobile/focus-android/blob/v2.2/app/build.gradle#L19) as it suites our workflow perfectly.

But v2.2, v2.1 and v2.0 all have the same version code of 11 and this made F-Droid think that they are all the same version. Could you please bump `versionCode` every time when `versionName` changes? This will make F-Droid autoupdating work again. If I understand your release process correctly, this should not affect you.

If this is not an option and version code 11 is here forever, we can bump it manually on our side, but this means that F-Droid version will often be outdated.

**Comment by dennisguse** [comment]
@bbinto @pocmo 
It would be great to get an estimate on this issue.
Would this be possible?
And do you need help / what is actual issue preventing the regular bump of versionCode?

**Comment by jmichael2497** [comment]
i just followed link from f-droid notes when i saw how outdated the build was.

i am curious why F-Droid does not just use versionName or tags which are actually being updated?

> Could you please bump versionCode every time when versionName changes?

but also this seems just as trivial, and logical, too.

**Comment by Ryuno-Ki** [comment]
In case anybody comes across this issue and thought about pulling the APK from Mozilla servers:
I filled [#1539978](https://bugzilla.mozilla.org/show_bug.cgi?id=1539978) with Bugzilla to highlight an outdated file under „latest”. See there for more details.

From what I get from this issue here is that there is nothing Mozilla can do here, but the issue has to be filled with F-Droid. Amirite?

**Comment by Ryuno-Ki** [comment]
Related to #4182.

**Comment by Krawei** [comment]
@relan Could you please bump the F-Droid's Version oft Firefox Focus/Klar to the current one v8.0.6?

Is there a New status regarding this issue? Will there be automatic generatic builds in the next months?

Kind Regards,
Krawei.

**Comment by relan** [comment]
@Krawei, it's not that easy, see the discussion [starting from this comment](https://gitlab.com/fdroid/fdroiddata/issues/1390#note_106639294). If you wish to maintain Klar on F-Droid, you're welcome.

**Comment by Krawei** [comment]
It seems that there was some progress here. They current F-Droid-version is v8.0.15, the Play Store one's is v8.0.16. 

So I guess you fixed your build issues so far and you'll close the "app's version gap" soon? :). What happened in the meantime? I'm curious :).
I think you can close this ticket now.

**Comment by relan** [comment]
> So I guess you fixed your build issues so far and you'll close the "app's version gap" soon? :).

Now that we need to build GeckoView (Mozilla's builds include proprietary Google library, so we can't use them), the issue described in this ticket is just a tiny nuisance. It's still valid though.

> What happened in the meantime? I'm curious :).

One volunteer managed to build Gecko 68 without proprietary stuff (for Fennec 68.x) , another one used his work to build Klar 8.0.15.

**Comment by moshpirit** [comment]
So, is going to be more updates on F-droid?

**Comment by dennisguse** [comment]
Problem is still there.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802035

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
