### ISSUE TITLE
Custom Tabs: No option to open URL in Focus

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1529]
Usually in Custom Tabs you can switch to the full version of the browser. Some time ago we removed Focus from the "Open with" option in the menu; because we thought that while inside Focus no one wants to switch to Focus (#894).

However this is a valid use case while you are in a Custom Tab. Third-party apps control what options are available in the UI and only by switching to the full browser you are able to perform all the available actions.

**Comment by brampitoyo** [comment]
This patch looks good to me, and comprises a part of what I’m proposing with the custom tabs redesign (#1626).

Let’s make sure that the wording says “Open in Firefox Focus”.

**Comment by pocmo** [comment]
Talked to Bram about this an other custom tabs things on Vidyo.

We decided that we want to have an additional menu item in custom tabs that opens Focus. This means we do not need to add Focus to the "Open with..." list.

> Let’s make sure that the wording says “Open in Firefox Focus”.

@brampitoyo For other apps we show a menu item with the string "Open with XXX". Do we want to re-use this one or explicitly say "in" here?

**Comment by brampitoyo** [comment]
I use “Open in…” because it’s the string that other browsers’ Custom Tabs use. But if Focus already uses “Open with…”, and if this string aligns with Fennec, we should use “with”.

**Comment by pocmo** [comment]
Follow-up issues: #2188, #2187

**Comment by npark-mozilla** [comment]
#2335 opened
