### ISSUE TITLE
RTL problem in Your Rights section of Firefox Focus when it's language is Persian

### ISSUE THREAD

**Issue by afarsi** [mozilla-mobile/focus-android#1532]
Hi there.
1-I selected Persian as it's UI languge.
Note: If i select device language to Persian and Focus language to Default, this bug will happen also.

2-When i got to **Your Rights window**(That is localized now), i saw it's Left to right while it should be Right to left direction.

Pay attenton: It's similar to https://github.com/mozilla-mobile/focus-android/issues/740 that was in About window, and fixed bfore now, but it again happened for Your Rights section, not About section.

Note: **Second screenshot is About window that is correct. First screenshot is Your Rights window that is invalid should be like second screenshot.**

Device and Configuration:
Device: Huawei TIT-AL00 (Y6 Pro)
OS: Android 5.1 
Android Launcher: Huawei EMUI 3.1 Lite
Firefox Focus Version: 2.2 (Build 12861529) 
How i installed Focus: Installed and updatted to latest version From Google Play (I'm Not member of beta program in Google Play)
Device UI language: Persian
Force RTL in developer options from device settings: Disabled(Default in device)

![photo_ - - _ - -](https://user-images.githubusercontent.com/19834847/31894292-dce84548-b81a-11e7-99b8-87f84ce9426f.jpg)

![photo_2017-10-21_12-34-49](https://user-images.githubusercontent.com/19834847/31894312-f346d43a-b81a-11e7-80ea-f9e2395d5ad2.jpg)

**Comment by pocmo** [comment]
The your rights page is missing the `dir` property. We can try adding it and setting it to `auto`. However for the "about" page we added a variable and add `ltr` / `rtl` based on Android's View direction manually.

**Comment by pocmo** [comment]
This should be fixed in the next release. :)
