### ISSUE TITLE
Releng for 2.4

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1535]
[2.4 Milestone](https://github.com/mozilla-mobile/focus-android/milestone/17)

## Sprint start

- [x] Update versionName in build.gradle for the next milestone (preliminary version number)

## String freeze

- [x] Make sure all issues with label "strings needed" have strings assigned and the label updated to "strings approved"
- [x] Pre-land all strings for features that have not been implemented yet
- [x] Export strings and open PR in the L10N repository

## Feature complete

- [x] Create a branch for the current milestone. After that master is tracking the next milestone. Usually done on the Monday after feature complete on Friday.
- [x] Create an issue in the *current* milestone: "What's New Entry for [release]" to track work for the SUMO page ([example](https://github.com/mozilla-mobile/focus-android/issues/1670)).
- [x] Create an issue in the *upcoming* milestone: "Releng for [release]" and copy this checklist into it. Assign the next assignee ([example](https://github.com/mozilla-mobile/focus-android/issues/1535)).
- [x] Go through the list of bugs closed during this sprint and make sure all they're all added to the correct milestone.
- [x] Add either `ReadyForQA` or `QANotNeeded` flags on each of the bugs in the current milestone.

## L10N sign-off
This step should happen before the string Export (next step) to avoid conflicts with new strings.

Land these commits into the milestone branch:
- [x] Import latest strings from L10N repository
- [x] Add any additional locales that l10n says have reached their threshold for shipping. See [localization instructions](https://github.com/mozilla-mobile/focus-android/wiki/Localization). If l10n has said that locales should be removed from shipping, remove those locales. Otherwise, release should include all currently-shipping locales.
- [x] Cherry pick the commits above into the master branch

## Beta Submission [Thursday, 1st week of next milestone]

- [x] Tag first RC version in Github. For 1.0 the tag would be v1.0-RC1. This will kick off a build of the branch. The format for the Taskcluster task is `https://github.taskcluster.net/v1/repository/mozilla-mobile/focus-android/<milestone-branch>/latest`, or you can see it in the mouseover of the CI badge of the branch in the commits view.
    
    If you need to trigger a new RC build, you need to draft a publish a new (pre-release) release. Editing an existing release and creating a new tag will not trigger a new RC build.

- [x] Create a [Bugzilla bug](https://bugzilla.mozilla.org/enter_bug.cgi?format=__default__&product=Release%20Engineering&cloned_bug_id=1408386) for signing and uploading the builds [Friday after code release]. Include the planned dates for Beta and Release release, from the [train schedule](https://wiki.mozilla.org/Mobile/Focus/Android/Train_Schedule).
- [x] Let release engineering sign the builds and upload the signed builds to Bugzilla
- [x] Let release management upload the builds to the Alpha channel (internal distribution)
- [x] If the builds passed a smoke test let release management promote the build to the beta channel (public distribution)
- [x] Upload the APK to the [releases page](https://github.com/mozilla-mobile/focus-android/releases).
- [x] Upload the APK to archive.mozilla.org into a folder with the name of the version (e.g. /android/focus/2.2-RC1) (S3 bucket)

## During Beta

- [x] Check Google Play for new crashes. File issues and triage.
- [x] If bugs are considered release blocker then fix them on master and the milestone branch (cherry-pick / uplift)
- [x] If needed tag a new RC version (e.g. v1.0-RC2) and follow the submission checklist again.

## Release

- [x] Release management promotes the build from beta to the release channel. For minor releases this can happen at any time during the day. Major releases often need to be synchronized with other marketing activities (e.g. blog postings). Releases are rolled out to 99% of the population (otherwise the rollout can't be stopped).

## After the release

- [x] After some days release management sets the roll out to 100%
- [x] Check whether there are new crashes that need to be filed.
- [x] Tag the last and released RC version additionally with the tag of the release (v1.0-RC2 -> v1.0)
- [x] Upload signed APKs to the [release page](https://github.com/mozilla-mobile/focus-android/releases)
- [x] Upload the APK to archive.mozilla.org (S3 bucket) into a folder named like a release (e.g. /android/focus/2.2) and replace the APKs in /android/focus/latest/. Builds from the "latest" folder are linked from the mozilla.org website.

**Comment by pocmo** [comment]
@mcomella Are you taking this one this time?

@liuche I think you already started exporting some strings, right?

(I need to update the "submission" part now that we do not need to build releases manually)

**Comment by liuche** [comment]
I exported the strings and the PR merged to the l10n repo.

**Comment by liuche** [comment]
I updated the checklist to include the new Wed/Wed import/export.

**Comment by pocmo** [comment]
Release Bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1416182

**Comment by pocmo** [comment]
2.4 is now on Google Play (Beta channel)

**Comment by pocmo** [comment]
All patches uplifted and building RC 2 now.

* Updated search engine configurations to follow desktop
* Fixed a release blocking issue with pull to refresh (#1685)
* Updated "What's new" SUMO page.

**Comment by pocmo** [comment]
2.4 RC 2 release bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1418027

**Comment by pocmo** [comment]
We started the roll out to 20% on Friday. Everything's looking good today so we are going to roll out to 99%.
