### ISSUE TITLE
SSL Error handling

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#154]
Related to #33: what do we want to do with ssl errors?

Option 1: show an error page, don't allow overrides (users can then go to their full browser to ignore these)
Option 2: allow overriding/ignoring errors temporarily - this would require having the UX to explain what error happened (i.e. outdated cert, untrusted cert, etc), plus an override mechanism.

I'm not even sure how reliable an override could be: the docs are very vague:
"Note that the decision may be retained for use in response to future SSL errors."
https://developer.android.com/reference/android/webkit/WebViewClient.html#onReceivedSslError(android.webkit.WebView,%20android.webkit.SslErrorHandler,%20android.net.http.SslError)

I favour 1 since it's simple, and that avoids us having to implement a full ssl cert handling UX (that doesn't seem like a lightweight thing to do correctly). I don't actually know what iOS does in this case.

**Comment by st3fan** [comment]
You can try out the iOS version in the simulator and open https://badssl.com links to see.  I think it has a pretty generic 'this is not to be trusted' page with no way to override.

**Comment by pocmo** [comment]
We decided to go with Option 1: Show an error page.

**Comment by AaronMT** [comment]
iOS equiv https://bugzilla.mozilla.org/show_bug.cgi?id=1318071

**Comment by ahunt** [comment]
This will probably be done in (i.e. is essentially part of #33):
https://github.com/mozilla-mobile/focus-android/pull/161/commits/c12f304cabd67208e0699d943f2bbd941213a76c
