### ISSUE TITLE
No Focus sub-icon on shortcuts

### ISSUE THREAD

**Issue by Fjoerfoks** [mozilla-mobile/focus-android#1540]
Just downloaded the new Firefox Focus Beta and really wanted to try out the new "Add to homescreen" option, since I would really like to have the Focus-icon connected to the shortcut as shown in the What's new-page on https://support.mozilla.org/en-US/kb/whats-new-firefox-focus.
Sadly after adding a shortcut to the homescreen, there is no sub-icon.
Is this limited or dependent on Android version? I have a Sony Z3c with Android 5.1.1.

**Comment by pocmo** [comment]
> Is this limited or dependent on Android version?

Yeah, that's a new system feature on Android 8+. If an app creates a shortcut then the app's icon will be added automatically.

**Comment by Fjoerfoks** [comment]
Thanks!
