### ISSUE TITLE
[meta] Focus uses CPU when backgrounded

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1544]
According to the task manager on my Samsung Galaxy S5 (which I think is a Samsung application):

![screenshot_2017-10-24-08-05-55](https://user-images.githubusercontent.com/759372/31952225-fb4bb522-b894-11e7-89e2-2eb4668b67df.png)

Notes:
- Even with no tabs, this happens at about ~2% but sometimes will even jump to ~6%
- Chrome does this too but it's background rate is much lower, usually 0% but spikes to ~0.2%.

I wonder if this is related to #1472 – maybe WebKit is misbehaving because it can't save its files.

**Comment by pocmo** [comment]
We do at least telemetry in the background.

**Comment by mcomella** [comment]
I used the "Running services" developer menu item and Focus doesn't have any running services (which I think would cross off telemetry).

**Comment by bbinto** [comment]
"Pages weren't loading and the app was overloading my CPU. Everything else on my phone was getting incredibly slow and I would get alerts from my phone saying that Firefox Focus was using up my processor (even when I wasn't using the app). I have since deleted the app and my phone runs much better. I have a samsung galaxy s8+."

**Comment by bbinto** [comment]
related to #1216?

**Comment by boek** [comment]
So I can see the activity thats happening in the background. But it looks like something is listening / polling and then trying to update some UI? But it doesn’t look like its calling any of our application code.

![image](https://user-images.githubusercontent.com/1250545/37928763-d6d279ca-30f2-11e8-9af5-528ab3c163b4.png)

So I’m guessing we’re registering for something thats doing some sort of update that we might want to stop when backgrounded. But I’m not sure what I'm looking for. Any ideas?

**Comment by boek** [comment]
I think #2274 might have improved this. Profiling it again and I'm not seeing nearly as much activity while the app is backgrounded.

@mcomella Can you confirm on your device?

**Comment by mcomella** [comment]
I still see this behavior on the Play Store version, 4.1: with no tabs, Focus is still using ~2.5% even several minutes after backgrounding. Reopening...

**Comment by bbinto** [comment]
@mcomella any updates / suggestions on this?

**Comment by bbinto** [comment]
@boek to get @liuche and @mcomella to look at this during SF-all hands

**Comment by pocmo** [comment]
Focus seems to be affected by this issue causing high CPU usage:
https://github.com/mozilla-mobile/android-components/issues/622
