### ISSUE TITLE
[breakdown] Quick access to favourite sites (requiring login)

### ISSUE THREAD

**Issue by jenn-chaulk** [mozilla-mobile/focus-android#1545]
From focus-android created by [bbinto](https://github.com/bbinto) : mozilla-mobile/focus-android#1525  

User Story:
- As a user, I want to access my frequently visited websites without always having to type in the full URL
- As a user, I want to frequent my favorite website without having to login each time

Some ideas that were floating around (without being prescriptive)
- Allow users to add their own defined sites to an autocomplete list
- Promote "Add to Homescreen" as a way of bookmarking things
- If we can't tackle the login piece yet that's fine but would be amazing

Some quotes (login related)
- I get an email with a link to a website that requires my login info
- I have few websites which I visit frequently and I want to keep cookies for them (whitelist); for any other websites I want to block third-party and/or first-party cookies completely or destroy them
- I can't use focus because I read nytimes.com multiple times per day and would have to sign in each time I visit.
- any site must warn visitors about cookies.. So each time we go on a site we often visit, we get the same information message about cookies that we have to dismiss!
- My main issue is not being able to use my default search engine's custom settings since they're stored in a cookie
- Every time I open it, I have to resign into Twitter

**Comment by pocmo** [comment]
I feel like a breakdown is almost impossible at this time without us knowing what we actually want to do.

**Comment by pocmo** [comment]
For UX and the breakdown there are a bunch of things we want to research:

* Can we use the Autofill API to autofill passwords?
* Can we use the Smartlock API?
* Can we integrate third-party services?
  * LastPass
  * 1Password
  * Dashlane
* Could we make us of Firefox Sync to just have passwords available?
  * Can we use https://github.com/mozilla-mobile/FirefoxData-android for that?

**Comment by pocmo** [comment]
(Draft, .. editing)

# Autofill Framework

* https://developer.android.com/guide/topics/text/autofill.html

# Smartlock API

* https://developers.google.com/identity/smartlock-passwords/android/

# Third-party services

* LastPass, Dashlane and 1Password seem to support OpenYOLO (see below)

## 1Password

## Dashlane

# Firefox Sync

* https://github.com/mozilla-mobile/FirefoxData-android

# OpenYOLO

* https://github.com/openid/OpenYOLO-Android/tree/master/api

**Comment by pocmo** [comment]
* Autofill -> #1810
* Autocomplete -> #1766
