### ISSUE TITLE
[breakdown] [ux] Quick access to favourite sites (requiring login)

### ISSUE THREAD

**Issue by jenn-chaulk** [mozilla-mobile/focus-android#1547]
From focus-android created by [jenn-chaulk](https://github.com/jenn-chaulk) : mozilla-mobile/focus-android#1546  

From focus-android created by [bbinto](https://github.com/bbinto) : mozilla-mobile/focus-android#1525  

User Story:
- As a user, I want to access my frequently visited websites without always having to type in the full URL
- As a user, I want to frequent my favorite website without having to login each time

Some ideas that were floating around (without being prescriptive)
- Allow users to add their own defined sites to an autocomplete list
- Promote "Add to Homescreen" as a way of bookmarking things
- If we can't tackle the login piece yet that's fine but would be amazing

Some quotes (login related)
- I get an email with a link to a website that requires my login info
- I have few websites which I visit frequently and I want to keep cookies for them (whitelist); for any other websites I want to block third-party and/or first-party cookies completely or destroy them
- I can't use focus because I read nytimes.com multiple times per day and would have to sign in each time I visit.
- any site must warn visitors about cookies.. So each time we go on a site we often visit, we get the same information message about cookies that we have to dismiss!
- My main issue is not being able to use my default search engine's custom settings since they're stored in a cookie
- Every time I open it, I have to resign into Twitter

**Comment by lime124** [comment]
Breakdown listed in meta issue.
