### ISSUE TITLE
[breakdown][ux] iterate on the onboarding experience

### ISSUE THREAD

**Issue by jenn-chaulk** [mozilla-mobile/focus-android#1554]
From focus-android created by [jenn-chaulk](https://github.com/jenn-chaulk) : mozilla-mobile/focus-android#1552  

From focus-android created by [lime124](https://github.com/lime124) : mozilla-mobile/focus-android#1506  

As we saw during the work week, retention numbers are not ideal. One area we identified was to improve our onboarding experience. 

[ ] UX ticket #1507

**Comment by lime124** [comment]
completed and tasks added to meta #1507
