### ISSUE TITLE
Fix UI Tests fallout from search engines

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1560]
Broke the UI Tests with the new search engine page.

**Comment by liuche** [comment]
PR here: #1562 
(Can github auto-link PRs to an issue, rather than just the commit?)

**Comment by mcomella** [comment]
> (Can github auto-link PRs to an issue, rather than just the commit?)
- When opening a PR, in the first comment I specify the Issue # and that autolinks the Issue to the PR (in this case, it looks like you linked to the first issue's PR, presumably by accident)
- When you use, "Closes #" in the commit, I believe it'll autolink on close.
- An autolinked commit has a link to the PR it's in:
<img width="763" alt="screen shot 2017-10-26 at 11 17 02" src="https://user-images.githubusercontent.com/759372/32069948-9ae2cbf6-ba3f-11e7-83d5-d16bad665c91.png">

Unfortunately, it's not very simple. :(
