### ISSUE TITLE
Rename release branches

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1564]
We used to name release branches after our milestones (folly, granite, ..). Now that we are back to using just version numbers I would like to rename them (and future versions) to `releases/x.x` (e.g. releases/1.1). The releases prefix will make it easier to distinguish them from other branches and tags that follow the `vx.x` (e.g. v1.1) pattern.

**Comment by mcomella** [comment]
FYI: I created the v2.4 milestone branch with `releases/v2.4`

**Comment by pocmo** [comment]
I deleted the branches for cobalt to ebony. We are not updating them anymore and I checked that the tags will remain - so we will always be able to check them out and re-create branches if needed.

**Comment by pocmo** [comment]
> Granite seems to be the last one that needs to be renamed or removed.

Removed this one too now that Granite aka 2.3 is released.
