### ISSUE TITLE
update search engine manual entry error strings

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1567]
We're not in love with the error strings shown during manual entry - they aren't helpful. This ticket to update those. 

Depending on what @BrianNJones comes up with, this may need a little bit of eng effort in addition to just updating the strings

**Comment by pocmo** [comment]
@lime124 @BrianNJones This is the only P1 with "needs string" label. Is there anything we can export today so that the L10N team can start translating it?

**Comment by lime124** [comment]
i think @BrianNJones is still working on one string. i'll let him update. thanks!

**Comment by BrianNJones** [comment]
@pocmo, if you can confirm that tapping "Save" validates that text exists in the name and string fields, we'd need error messages for their empty states:
If no text entered in "Search engine name" field, string would be:
Enter search engine name
If no text entered in "Search string to use" field, string would be:
Enter search string

**Comment by liuche** [comment]
Looks like these strings are landed so going to close this - they'll get picked up in the next export.

**Comment by liuche** [comment]
Oh wait, the string and feature issues are the same, reopening.

**Comment by liuche** [comment]
Just a string change, should be picked up in UX review as the last step of #961.
