### ISSUE TITLE
UI bug in hint message

### ISSUE THREAD

**Issue by djKooks** [mozilla-mobile/focus-android#1568]
Hello.
This is some minor UI bug in hint message.
![focus-eng](https://user-images.githubusercontent.com/1720209/32083726-dcc87316-baff-11e7-8a0a-46289fd3a6d0.png)

This has no problem, but it shows like this in some other language(it has been tested with Korean, and Japanese has same problem).
![focus-kor](https://user-images.githubusercontent.com/1720209/32083744-0562fab2-bb00-11e7-8542-feece6293782.png)

As you see, bold part are being shown at the back of string.
```
content.setSpan(new StyleSpan(Typeface.BOLD), hint.length() - searchText.length(), hint.length(), 0);
```
This is the part of `UrlInputFragment.java`. It gives style in back of the hint string, but it works like above because it has different grammer with english.

I'm not sure which is good idea to solve it. It seems it is not a good idea to define style by language(it has too many language to compare) or by letter.

How do you think?

**Comment by pocmo** [comment]
Ha, good find.

The only solution I can come up with is not adding the search word to the string but a unique place holder. The find the position of the placeholder int the string, replace it and style the string at the given position.

**Comment by djKooks** [comment]
@pocmo I think so. Like `Search : XXX`, or other way. Do you have good idea?

**Comment by pocmo** [comment]
I was thinking of something like this:

```java
final String placeHolder = "5981086f-9d45-4f64-be99-7d2ffa03befb";
final String hint = getString(R.string.search_hint, placeHolder);

final int start = hint.indexOf(placeHolder);

final SpannableString content = new SpannableString(hint.replaceAll(placeHolder, searchText));
content.setSpan(new StyleSpan(Typeface.BOLD), start, searchText.length(), 0);
```

Add *something* into the string (where we are sure it is unlikely to be ever in a search string). Then find the position of the thing we added. Then add our actual search text and style from the position we determined early.

@djKooks Do you want to try if this works? Or can you think. of a better approach?

**Comment by djKooks** [comment]
@pocmo Looks good! I'll try and add it on if it works fine.

**Comment by djKooks** [comment]
@pocmo Code above cause failure in english (works well on Korean or Japanese)because start returns length of String `Search for` but search text length returns 1 when you input anything in search bar. I'll look for a bit more.

**Comment by djKooks** [comment]
@pocmo Sorry for late reply.
No, it does not looks like off-by-one issue. 
@ekager Would you follow this one?

**Comment by ekager** [comment]
@djKooks we got it, thanks for submitting the bug!!

**Comment by djKooks** [comment]
@ekager No problem!
