### ISSUE TITLE
Import translations on Monday (Oct 25th)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1572]
Delphine asked whether we can do an import on Monday so that they can verify the latest translations. Should be a quick thing to do.

I'll mark this as P1 as Monday will be part of the current sprint.

**Comment by pocmo** [comment]
@npark-mozilla Strings are ready for manual screenshot run. :)

**Comment by npark-mozilla** [comment]
Screenshots are generated.
