### ISSUE TITLE
Update Android SDK + related dependencies

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1573]
Yesterday the Android team released the Android 8.1 SDK (API 27), new support libraries, a new gradle plugin and Android Studio 3.0. Time to update a bunch of things.

**Comment by pocmo** [comment]
* Preview: https://developer.android.com/preview/download.html
* Migration guide: https://developer.android.com/preview/migration.html
* Support library 27: https://developer.android.com/topic/libraries/support-library/revisions.html

**Comment by shubham171294** [comment]
I can do it. Should I?

**Comment by pocmo** [comment]
> I can do it. Should I?

There's already a partial PR: #1590 - Currently we are blocked on some unit tests.

**Comment by bbinto** [comment]
Is this a P2 and should go into our last sprint before 4.0 or can this be done after? If so, I'd set P to P3.

**Comment by pocmo** [comment]
@bbinto This could be done after. If time permits I might squeeze this in before. I have an almost done patch for that.
