### ISSUE TITLE
add HTTP auth support

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#159]
We should probably show a simple auth dialog on:
WebViewClient.onReceivedHttpAuthRequest()
https://developer.android.com/reference/android/webkit/WebViewClient.html#onReceivedHttpAuthRequest(android.webkit.WebView,%20android.webkit.HttpAuthHandler,%20java.lang.String,%20java.lang.String)

We currently show an ugly Android error page when trying to load a page that requires authentication. Webkit then _doesn't_ call WebViewClient.onReceivedError(), so we'd still need to at least redirect to our own error page even if we don't add http auth support.

It looks like iOS doesn't support this yet:
https://bugzilla.mozilla.org/show_bug.cgi?id=1318896

**Comment by ahunt** [comment]
> We currently show an ugly Android error page when trying to load a page that requires authentication. Webkit then doesn't call WebViewClient.onReceivedError(), so we'd still need to at least redirect to our own error page even if we don't add http auth support.

(I'll try to handle at least this in #33, since it's about 2 lines of code.)

**Comment by pocmo** [comment]
This reminds me that I wanted to look through the WebViewClient / WebChromeClient APIs to see whether there are things we should implement or at least file bugs for. There are potentially other things we miss like alert dialogs, permission requests, ..

**Comment by st3fan** [comment]
Android does not do this, but if it really is 2 lines of code on Android, and we can assure that those credentials are not cached/stored anywhere, then I think it is a nice one to include.

**Comment by therbom** [comment]
Hi,

I tried to implement support for HTTP Basic Authentication. You can review my commit here: therbom/focus-android@0e8d2df09633c382a69d991140871e90f4369a4e. It is very basic with hardcoded credentials, but loading webpages and downloading files works fine on my end.

At least these things need to be considered, I think:
1. Show a UI to fill in the credentials when required.
2. The credentials somehow need to be exposed to the BrowserFragment, so it can be used when downloading files.

I'm not really an advanced programmer, so any help would be appreciated :-)

**Comment by mcomella** [comment]
@therbom Hey – could you open a pull request so we can keep track of your WIP?

Sorry it took so long to get back to you – issue comments are much less noticeable than pull requests  so I it's taking me a while to get through the old ones.

**Comment by kai-chi** [comment]
what is the status of it? can I take it as my first ticket?

**Comment by Sdaswani** [comment]
@kai-chi looks like you can - there is some foundational work here if you want to use it. https://github.com/therbom/focus-android/commit/0e8d2df09633c382a69d991140871e90f4369a4e

Also mention @therbom in case he has made any progress on this.

**Comment by therbom** [comment]
Hi @Sdaswani,

Unfortunately, I haven't had time to delve into it. That commit is all I've got, I'm afraid, so feel free to take it over.

This is currently all I know:

1. Whenever a page is opened, the webview should ask the user for credentials. I modified [app/src/webview/java/org/mozilla/focus/webview/TrackingProtectionWebViewClient.java](https://github.com/therbom/focus-android/commit/0e8d2df09633c382a69d991140871e90f4369a4e#diff-20fb988096940b809330f2de9afd4be5) to support hardcoded credentials, so it still needs to retrieve them from the user through the GUI.
2. The credentials should be stored for this session. I think we can use [WebViewDatabase](https://developer.android.com/reference/android/webkit/WebViewDatabase.html) for this purpose, but of course it needs to be cleared when the session ends (I don't know if the current setup already ensures this).
3. Whenever a file is going to be downloaded, the credentials should be sent with the HTTP request. My adjustments to [app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java](https://github.com/therbom/focus-android/commit/0e8d2df09633c382a69d991140871e90f4369a4e#diff-065f87691b423896c6e210a2d4daa9e2) allowed me to properly download files with hardcoded credentials, but I could not figure out how to detect when HTTP authentication is required and how to obtain the credentials from WebViewDatabase.

If you need help with testing, feel free to contact me. For my work I need to have access to a website that requires HTTP auth, but I cannot share the credentials for it.

**Comment by Sdaswani** [comment]
Thanks for the hand off @therbom , really appreciate your contributions.

**Comment by kai-chi** [comment]
thanks, @therbom. I'll start looking into it and contact you while testing.

**Comment by pocmo** [comment]
From #2454 (Quoting @brampitoyo):

![image](https://user-images.githubusercontent.com/89638/38797394-9771bd1e-415e-11e8-8b6e-884e23277183.png)

* Spacing and dimension should be identical to the Settings menu and page modal dialogues.
* Highlight and button colour values should be `blue-50`: `#0a84ff`
* Heading font should be identical to the size of our menu items: 16dp. Its weight should also be semibold.
