### ISSUE TITLE
[ux] improve onboarding experience - research

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1593]
#1507 [meta][ux] improve onboarding experience 

- [ ] gather and read existing research. talk to Jennifer.
- [ ] explore existing solutions. https://www.useronboard.com/
- [ ] review [Barbara's doc](https://docs.google.com/document/d/1LtZ4nJepdMpxgJ64jpTtlIp3zMEn6Aa7Bb6yNIGDNxY/edit)
- [ ] Sebastian's comment with android docs

**Comment by pocmo** [comment]
There are two pages about onboarding and feature discovery in the material guidelines, maybe they are useful too:
* https://material.io/guidelines/growth-communications/onboarding.html#
* https://material.io/guidelines/growth-communications/feature-discovery.html#

**Comment by lime124** [comment]
http://help.apple.com/macOS/high-sierra/macbook-pro/?lang=en&cases=kIFAGHvXTAepRptQXiXe5w,N0bfKOvERSiAp06mHOcgOQ&notification=1#outro

**Comment by lime124** [comment]
from susheel: http://info.localytics.com/blog/mobile-apps-whats-a-good-retention-rate
