### ISSUE TITLE
Add support for blocking web fonts

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#16]

**Comment by ahunt** [comment]
This is somewhat doable: shouldInterceptRequest() is called for webfonts.

However we'll probably need to write our own logic to detect when a webfont is being loaded. On iOS, the OS content blocking knows whether or not a given resource is a font ( https://github.com/mozilla-mobile/focus/blob/master/Lists/web-fonts.json ).

shouldInterceptRequest(WebView, String) on Android doesn't provide that kind of detail - and that's what we're currently using. There's an API 21+ (Android 5) shouldInteceptRequest(WebView, WebResourceRequest), but that doesn't seem to provide any useful functionality for webfont blocking:
https://developer.android.com/reference/android/webkit/WebResourceRequest.html

Detecting the file extension (woff/woff2/eot) would cover many fonts, but isn't perfect (I don't think site owners need to use the extension, and svg can be used as a font or image which would make blocking svg fonts harder).

(I've also looked at the http request headers - which you can see in the WebResourceRequest, but on at least Android 5, "Accept = */*" for webfonts being loaded from css.)

**Comment by pocmo** [comment]
This doesn't sound good. WebSettings has some methods for blocking images or network requests but unfortunately not web fonts.

**Comment by ahunt** [comment]
I wonder if we could add telemetry to firefox (nightly) to report whether webfonts are being loaded from files that don't have an expected (woff/woff2/eot/otf/ttf) extension - that would at least help us evaluate whether file extension based blocking would work for _most_ sites?

(And if this works we can then clarify that this setting isn't guaranteed to work for all sites.)

**Comment by pocmo** [comment]
Interesting idea to add telemetry! If blocking _most_ fonts is good enough depends on the user story around that.

@st3fan @thebnich What's actually the story behind blocking web fonts? Is it just for site loading performance or is this actually a feature for privacy / to prevent tracking?

**Comment by ahunt** [comment]
AFAICT the blocklists already take care of the privacy/tracking aspect (i.e. even if fonts are enabled, we still block any fonts being loaded from blocked domains). The wording of the preference seems to suggest it's just a performance issue?

I've got a patch which does extension based blocking - it seems to work for the sites I've tested. I've filed (and am working on) https://bugzilla.mozilla.org/show_bug.cgi?id=1342479 to get the relevant data from firefox, so we should probably leave this bug open until we've got that data.

**Comment by pocmo** [comment]
We could enable your extension based blocking in dev/beta builds and see how it behaves. Time to add some feature flags and dev/beta/release flags? :)

**Comment by st3fan** [comment]
@ahunt The list you linked to at https://github.com/mozilla-mobile/focus/blob/master/Lists/web-fonts.json is for the native content blocking that focus enables for Safari. That is not actually used in Focus the application since those native blocklists do not work there.

It looks like on iOS we do the same thing as you implemented: we block fonts based on their extension. See https://github.com/mozilla-mobile/focus/blob/master/Blockzilla/LocalContentBlocker.swift#L118 for a list of extensions which is later transformed in a blocking rule that looks at the file extension of the URL path.

This may not catch all fonts, but I think it is a good start.
