### ISSUE TITLE
(Interlingua) [failed] ia is not a valid locale

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1601]
Just imported strings for #1572 and noticed that Android2Po complains about "ai".

Maybe some custom handling is needed, see #1148.

**Comment by pocmo** [comment]
Interlingua: https://pontoon.mozilla.org/ia/focus-for-android/

**Comment by pocmo** [comment]
@mastizada Maybe another one we need to hack in manually? :)

**Comment by mastizada** [comment]
@pocmo yep, sending PR

**Comment by pocmo** [comment]
49fb2f87b4d6cc30d381965ab56210e42c599080 added support to Android2Po.

Additionally we will have to add the translation for the language itself to our Locale class.

**Comment by mcomella** [comment]
@pocmo How can QA test this locale?

**Comment by npark-mozilla** [comment]
Before this bug was fixed, running screenshottest with fastlane on 'ia' used to crash, Now it generates proper screenshots with valid texts (which is also checked by l10n people)
