### ISSUE TITLE
[ux] Quick access to favourite sites (requiring login) - research

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1604]
#1546 [Meta] [ux] Quick access to favourite sites (requiring login) 

- [x] write research brief
- [x] gather and read existing research. 
- [x] explore existing solutions. 
- [ ] do our own research study?

Relevant issues:
#1040 search suggestions/auto-complete 
#1337 auto-complete for top level domains
[iOS bug #598](https://github.com/mozilla-mobile/focus-ios/issues/598)

**Comment by pocmo** [comment]
Technical feedback: From tech side it seems to be super complicated to just delete some cookies or identify cookies that are *only* used for a login session. For example a login cookie for Facebook could be used to keep the user logged in AND track a user. (At least as long as we are using WebView).
So from a technical side it might be more promising to look into ways to integrate third-party password managers and/or Android/Google's Smart Lock: https://developers.google.com/identity/smartlock-passwords/android/

**Comment by lime124** [comment]
https://github.com/mozilla-mobile/focus-android/issues/958#issuecomment-341266373

**Comment by pocmo** [comment]
This "App fill" feature of Lastpass is interesting:
https://youtu.be/Ct3yPo2-V4U

Android 8+ comes with an Autofill API, not sure if it is helpful here though:
https://developer.android.com/guide/topics/text/autofill.html

**Comment by lime124** [comment]
@pocmo does autofill api work with all browsers (like us)? I couldn't easily tell if that is true or not.

It looks like 1password also is doing something - https://support.1password.com/android-autofill/

**Comment by pocmo** [comment]
> @pocmo does autofill api work with all browsers (like us)?

Good question. I haven't played with that API at all. There are also no hints in the documentation that I can see right now. However when long-pressing an input field on Android 8.1 it shows an "autofill" action here - although it doesn't autofill anything yet.

If this is something you want to know for your research then I can investigate this.

**Comment by lime124** [comment]
Exploring integration with password managers. We're looking at getting firefox passwords and also incorporating with 1password, last pass, and dashlane. Also going to catch up with Lockbox folks next week.

**Comment by lime124** [comment]
this requires reviewing the add to homescreen results before closing

**Comment by lime124** [comment]
oops...

**Comment by lime124** [comment]
here are the prelim results. just need to put them in a prettier format which I'll do on monday. 

https://docs.google.com/document/d/1L3HPUUvjtNw1madQeE42XJTMP3J__Ymv-ts0NggHoWQ/edit
