### ISSUE TITLE
Screen does not go to sleep

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1613]
From whuang via Slack:

> it actually brings a regression that the browser avoids the screen from going to sleep even not in media playback.
> 
> STR:
> 1. config your settings: let the screen sleep after 15 sec of inactivity
> 2. use Focus to play a youtube video and make it fullscreen
> 3. before the video ends, quickly switch to other app (such as Facebook) to open a link (website not a media), and open it with Focus
> Then, Focus avoids the screen to go to sleep even after 15 secs. The “track can” icon is gone as well, even if you navigates to other pages.

Could be causing battery problems: #1216

**Comment by npark-mozilla** [comment]
This fix is verified, but there is another potential issue.  When I open a media, and make it fullscreen, the screen does not sleep even though it's stopped/paused.  (This does not happen when the media is not in fullscreen mode) Is this expected? (similar battery drain issue might occur if one just pauses in fullscreen mode and leave it) @pocmo what do you think?

Just double checked that in Chrome paused fullscreen mode enters sleep mode normally.
