### ISSUE TITLE
Add Manual Search Engine page

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1617]
Meta: #961

Add preference screen for adding a new search engine manually.

**Comment by liuche** [comment]
Same as #1660 , this is Part 1 of the #961 meta - @npark-mozilla should we flag for QA upon partial landing of features, or should it be part of the meta when everything lands? Flagging QA+ for now to be safe.

**Comment by npark-mozilla** [comment]
@liuche I think flagging it for each bug is a good idea too. will check.
