### ISSUE TITLE
Update padding, size, and color of the Search Engine Selection screen

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1618]
Make it match the mocks :)

![visual design](https://user-images.githubusercontent.com/287322/32027376-8c9af278-b99d-11e7-8999-e6696dcb347b.png)

...and the coding style.

NOTE: this is just for the padding, sizing, color polish (the parts with colorful labels). The 3-dot menu and the "Add search engine" are handled by other issues.

A few comments:
* If a dimension seems like it will be reused in different places, add it to dimens.xml and reference it - that way we don't have one-off numbers everywhere in the code
* Colors should almost always be added to colors.xml - please name it generically. In this case, it can be something like settings_selection_highlight.
* When you've finished, please add a screenshot with the changes so UX can visually verify.

Please ask if you have any other questions!

**Comment by nigelmcintyre** [comment]
Hey, It's my first time contributing and I would like to take this issue if that's ok?

**Comment by liuche** [comment]
Ah @nigelmcintyre I was just going to un-first-bug this because we'd like to get this into the code freeze in two days. Do you think you can finish it by then? It shouldn't take that much work :)

The main files where the changes need to take place are:

Changing the padding in the custom RadioButton layout: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/res/layout/search_engine_radio_button.xml

Removing padding from RadioGroup layout: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/res/layout/preference_search_engine_chooser.xml

Updating the color of the "selected" state in the list selector: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/res/drawable/preference_search_engine_background.xml

**Comment by nigelmcintyre** [comment]
I probably could get it done in time, but as it's my first time I wan't to make sure I do it right. So just in case I better not take it. Is there something else I could have a go at that isn't as urgent? :)

**Comment by ekager** [comment]
<img width="313" alt="screen shot 2017-11-02 at 2 25 41 pm" src="https://user-images.githubusercontent.com/25442310/32351197-cc9b4d40-bfd9-11e7-9a39-91ea2f8972f3.png">

Hey @lime124 ! Does this look okay from your perspective?

**Comment by lime124** [comment]
hi @ekager! thanks for taking this on! 

Ideally the search engine name and the page title will line up. It looks like the icons might be bigger and that's pushing the text out of alignment?

**Comment by lime124** [comment]
oops forgot to reopen!

**Comment by ekager** [comment]
Woo okay, set a defined size for the icon and seems to be behaving correctly. Look good to you? 
<img width="327" alt="screen shot 2017-11-03 at 3 32 02 pm" src="https://user-images.githubusercontent.com/25442310/32398429-814ecbb8-c0ac-11e7-9c0f-1fbd5043a339.png">

**Comment by ekager** [comment]
Search Engine Icons still not quite the correct size on all devices

**Comment by ekager** [comment]
@lime124 Can you confirm that this screenshot fixes the name and title line up issue? :) 
<img width="311" alt="screen shot 2017-11-07 at 8 55 50 am" src="https://user-images.githubusercontent.com/25442310/32512061-8a1cfc82-c3aa-11e7-82f5-3aec8a2ef7ba.png">

**Comment by lime124** [comment]
Confirm! Thanks @ekager !
