### ISSUE TITLE
Dropdown on geckoView is not working.

### ISSUE THREAD

**Issue by shinilms** [mozilla-mobile/focus-android#1620]
The dropdown on a webpage loaded in geckoview is not working. When clicked on the dropdown, nothing happens. I'm using the geckoview inside my app and it doesn't work in focus(geckoview build) either.

**Comment by pocmo** [comment]
FYI @snorp

**Comment by pocmo** [comment]
Thank you for your report. The GeckoView version of Focus is not really supported by us. However I linked this issue from the meta issue in case we are going to switch to GeckoView in the future.

**Comment by shinilms** [comment]
Thanks for your response. Is there any way I can get the source code for `geckoview-latest.aar` used in ff?

**Comment by pocmo** [comment]
Yeah, you need to setup a Firefox for Android build, following this guide (pick the simpler "front-end" build):
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_for_Android_build

After that you can run "./gradlew tasks" and you should see a task like "geckoview:assembleReleaseWithGeckoBinaries" (I do not remember the actual name). This task will produce the AAR and you can replace it in your Focus build.

**Comment by shinilms** [comment]
Hell

I ran the ./gradlew tasks command as you said and the following is the
result I got. Can you tell me the exact task which will produce the
geckoView AAR file?


All tasks runnable from root project
------------------------------------------------------------

Android tasks
-------------
androidDependencies - Displays the Android dependencies of the project.
signingReport - Displays the signing info for each variant.
sourceSets - Prints out all the source sets defined in this project.

Build tasks
-----------
assemble - Assembles all variants of all applications and secondary
packages.
assembleAndroidTest - Assembles all the Test applications.
assembleDebug - Assembles all Debug builds.
assembleLocal - Assembles all Local builds.
assembleLocalOld - Assembles all LocalOld builds.
assembleLocalOldPhoton - Assembles all builds for flavor combination:
LocalOldPhoton
assembleLocalPhoton - Assembles all builds for flavor combination:
LocalPhoton
assembleOfficial - Assembles all Official builds.
assembleOfficialPhoton - Assembles all builds for flavor combination:
OfficialPhoton
assemblePhoton - Assembles all Photon builds.
assembleRelease - Assembles all Release builds.
assembleWithGeckoBinaries - Assembles all WithGeckoBinaries builds.
assembleWithoutGeckoBinaries - Assembles all WithoutGeckoBinaries builds.
build - Assembles and tests this project.
buildDependents - Assembles and tests this project and all projects that
depend on it.
buildNeeded - Assembles and tests this project and all projects it depends
on.
classes - Assembles main classes.
clean - Deletes the build directory.
cleanBuildCache - Deletes the build cache directory.
compileDebugAndroidTestSources
compileDebugSources
compileDebugUnitTestSources
compileLocalOldPhotonDebugAndroidTestSources
compileLocalOldPhotonDebugSources
compileLocalOldPhotonDebugUnitTestSources
compileLocalOldPhotonReleaseSources
compileLocalOldPhotonReleaseUnitTestSources
compileLocalPhotonDebugAndroidTestSources
compileLocalPhotonDebugSources
compileLocalPhotonDebugUnitTestSources
compileLocalPhotonReleaseSources
compileLocalPhotonReleaseUnitTestSources
compileOfficialPhotonDebugAndroidTestSources
compileOfficialPhotonDebugSources
compileOfficialPhotonDebugUnitTestSources
compileOfficialPhotonReleaseSources
compileOfficialPhotonReleaseUnitTestSources
compileReleaseSources
compileReleaseUnitTestSources
compileWithGeckoBinariesSources
compileWithGeckoBinariesUnitTestSources
compileWithoutGeckoBinariesAndroidTestSources
compileWithoutGeckoBinariesSources
compileWithoutGeckoBinariesUnitTestSources
extractDebugAnnotations - Extracts Android annotations for the debug
variant into the archive file
extractReleaseAnnotations - Extracts Android annotations for the release
variant into the archive file
extractWithGeckoBinariesAnnotations - Extracts Android annotations for the
withGeckoBinaries variant into the archive file
extractWithoutGeckoBinariesAnnotations - Extracts Android annotations for
the withoutGeckoBinaries variant into the archive file
jar - Assembles a jar archive containing the main classes.
mockableAndroidJar - Creates a version of android.jar that's suitable for
unit tests.
testClasses - Assembles test classes.

Build Setup tasks
-----------------
init - Initializes a new Gradle build. [incubating]

Documentation tasks
-------------------
javadoc - Generates Javadoc API documentation for the main source code.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root
project 'mozilla-central'.
components - Displays the components produced by root project
'mozilla-central'. [incubating]
dependencies - Displays all dependencies declared in root project
'mozilla-central'.
dependencyInsight - Displays the insight into a specific dependency in root
project 'mozilla-central'.
dependentComponents - Displays the dependent components of components in
root project 'mozilla-central'. [incubating]
help - Displays a help message.
model - Displays the configuration model of root project 'mozilla-central'.
[incubating]
projects - Displays the sub-projects of root project 'mozilla-central'.
properties - Displays the properties of root project 'mozilla-central'.
tasks - Displays the tasks runnable from root project 'mozilla-central'
(some of the displayed tasks may belong to subprojects).

IDE tasks
---------
cleanIdea - Cleans IDEA project files (IML, IPR)
idea - Generates IDEA project files (IML, IPR, IWS)

Install tasks
-------------
installDebug - Installs the Debug build.
installDebugAndroidTest - Installs the android (on device) tests for the
Debug build.
installLocalOldPhotonDebug - Installs the DebugLocalOldPhoton build.
installLocalOldPhotonDebugAndroidTest - Installs the android (on device)
tests for the LocalOldPhotonDebug build.
installLocalPhotonDebug - Installs the DebugLocalPhoton build.
installLocalPhotonDebugAndroidTest - Installs the android (on device) tests
for the LocalPhotonDebug build.
installOfficialPhotonDebug - Installs the DebugOfficialPhoton build.
installOfficialPhotonDebugAndroidTest - Installs the android (on device)
tests for the OfficialPhotonDebug build.
installWithGeckoBinaries - Installs the WithGeckoBinaries build.
installWithoutGeckoBinaries - Installs the WithoutGeckoBinaries build.
installWithoutGeckoBinariesAndroidTest - Installs the android (on device)
tests for the WithoutGeckoBinaries build.
uninstallAll - Uninstall all applications.
uninstallDebug - Uninstalls the Debug build.
uninstallDebugAndroidTest - Uninstalls the android (on device) tests for
the Debug build.
uninstallLocalOldPhotonDebug - Uninstalls the DebugLocalOldPhoton build.
uninstallLocalOldPhotonDebugAndroidTest - Uninstalls the android (on
device) tests for the LocalOldPhotonDebug build.
uninstallLocalOldPhotonRelease - Uninstalls the ReleaseLocalOldPhoton build.
uninstallLocalPhotonDebug - Uninstalls the DebugLocalPhoton build.
uninstallLocalPhotonDebugAndroidTest - Uninstalls the android (on device)
tests for the LocalPhotonDebug build.
uninstallLocalPhotonRelease - Uninstalls the ReleaseLocalPhoton build.
uninstallOfficialPhotonDebug - Uninstalls the DebugOfficialPhoton build.
uninstallOfficialPhotonDebugAndroidTest - Uninstalls the android (on
device) tests for the OfficialPhotonDebug build.
uninstallOfficialPhotonRelease - Uninstalls the ReleaseOfficialPhoton build.
uninstallRelease - Uninstalls the Release build.
uninstallWithGeckoBinaries - Uninstalls the WithGeckoBinaries build.
uninstallWithoutGeckoBinaries - Uninstalls the WithoutGeckoBinaries build.
uninstallWithoutGeckoBinariesAndroidTest - Uninstalls the android (on
device) tests for the WithoutGeckoBinaries build.

Reporting tasks
---------------
countLocalOldPhotonDebugDexMethods - Outputs dex method count for
localOldPhotonDebug.
countLocalOldPhotonReleaseDexMethods - Outputs dex method count for
localOldPhotonRelease.
countLocalPhotonDebugDexMethods - Outputs dex method count for
localPhotonDebug.
countLocalPhotonReleaseDexMethods - Outputs dex method count for
localPhotonRelease.
countOfficialPhotonDebugDexMethods - Outputs dex method count for
officialPhotonDebug.
countOfficialPhotonReleaseDexMethods - Outputs dex method count for
officialPhotonRelease.

Upload tasks
------------
uploadArchives - Uploads all artifacts belonging to configuration
':geckoview:archives'

Verification tasks
------------------
check - Runs all checks.
connectedAndroidTest - Installs and runs instrumentation tests for all
flavors on connected devices.
connectedCheck - Runs all device checks on currently connected devices.
connectedDebugAndroidTest - Installs and runs the tests for debug on
connected devices.
connectedLocalOldPhotonDebugAndroidTest - Installs and runs the tests for
localOldPhotonDebug on connected devices.
connectedLocalPhotonDebugAndroidTest - Installs and runs the tests for
localPhotonDebug on connected devices.
connectedOfficialPhotonDebugAndroidTest - Installs and runs the tests for
officialPhotonDebug on connected devices.
connectedWithoutGeckoBinariesAndroidTest - Installs and runs the tests for
withoutGeckoBinaries on connected devices.
deviceAndroidTest - Installs and runs instrumentation tests using all
Device Providers.
deviceCheck - Runs all device checks using Device Providers and Test
Servers.
findbugsHtmlLocalOldPhotonDebug - Analyze localOldPhotonDebug code with
findbugs (HTML report)
findbugsHtmlLocalOldPhotonRelease - Analyze localOldPhotonRelease code with
findbugs (HTML report)
findbugsHtmlLocalPhotonDebug - Analyze localPhotonDebug code with findbugs
(HTML report)
findbugsHtmlLocalPhotonRelease - Analyze localPhotonRelease code with
findbugs (HTML report)
findbugsHtmlOfficialPhotonDebug - Analyze officialPhotonDebug code with
findbugs (HTML report)
findbugsHtmlOfficialPhotonRelease - Analyze officialPhotonRelease code with
findbugs (HTML report)
findbugsXmlLocalOldPhotonDebug - Analyze localOldPhotonDebug code with
findbugs (XML report)
findbugsXmlLocalOldPhotonRelease - Analyze localOldPhotonRelease code with
findbugs (XML report)
findbugsXmlLocalPhotonDebug - Analyze localPhotonDebug code with findbugs
(XML report)
findbugsXmlLocalPhotonRelease - Analyze localPhotonRelease code with
findbugs (XML report)
findbugsXmlOfficialPhotonDebug - Analyze officialPhotonDebug code with
findbugs (XML report)
findbugsXmlOfficialPhotonRelease - Analyze officialPhotonRelease code with
findbugs (XML report)
lint - Runs lint on all variants.
lintDebug - Runs lint on the Debug build.
lintLocalOldPhotonDebug - Runs lint on the LocalOldPhotonDebug build.
lintLocalOldPhotonRelease - Runs lint on the LocalOldPhotonRelease build.
lintLocalPhotonDebug - Runs lint on the LocalPhotonDebug build.
lintLocalPhotonRelease - Runs lint on the LocalPhotonRelease build.
lintOfficialPhotonDebug - Runs lint on the OfficialPhotonDebug build.
lintOfficialPhotonRelease - Runs lint on the OfficialPhotonRelease build.
lintRelease - Runs lint on the Release build.
lintWithGeckoBinaries - Runs lint on the WithGeckoBinaries build.
lintWithoutGeckoBinaries - Runs lint on the WithoutGeckoBinaries build.
test - Run unit tests for all variants.
testDebugUnitTest - Run unit tests for the debug build.
testLocalOldPhotonDebugUnitTest - Run unit tests for the
localOldPhotonDebug build.
testLocalOldPhotonReleaseUnitTest - Run unit tests for the
localOldPhotonRelease build.
testLocalPhotonDebugUnitTest - Run unit tests for the localPhotonDebug
build.
testLocalPhotonReleaseUnitTest - Run unit tests for the localPhotonRelease
build.
testOfficialPhotonDebugUnitTest - Run unit tests for the
officialPhotonDebug build.
testOfficialPhotonReleaseUnitTest - Run unit tests for the
officialPhotonRelease build.
testReleaseUnitTest - Run unit tests for the release build.
testWithGeckoBinariesUnitTest - Run unit tests for the withGeckoBinaries
build.
testWithoutGeckoBinariesUnitTest - Run unit tests for the
withoutGeckoBinaries build.

**Comment by shinilms** [comment]
Hello again,

Assuming the gradle task you meant was "assembleWithGeckoBinaries -
Assembles all WithGeckoBinaries builds", I ran it and the build was
successful. But I couldn't find any AAR files generated. Can you help me
with this? Will the AAR file be generated automatically after the gradle
task? If so, where can I find it? Or do I need to export geckoView as a
library?

**Comment by pocmo** [comment]
The following steps should create the AAR:

```shellsession
$ ./mach build
$ ./mach package
$ ./mach gradle geckoview:assembleWithGeckoBinaries
````

After that you should find the AAR in:
> objdir-frontend/gradle/build/mobile/android/geckoview/outputs/aar

Note that **objdir-frontend** is the name I've set in mozconfig. The directory might be named differently in your case (or be generated). Usually it's a folder that starts with **obj**.

**Comment by shinilms** [comment]
Thank you for your time. It's working. And one more thing, What do I need
to do to get vouched in Mozillians?

**Comment by pocmo** [comment]
> And one more thing, What do I need to do to get vouched in Mozillians?

There's a wiki page about that:
https://wiki.mozilla.org/Mozillians/Vouching

> How do I get vouched?
> 
> Contribute! Once you have contributed significantly to any of Mozilla's projects, ask the people you are working with to vouch you on Mozillians.org. They will either do so, or will encourage you to make a few more contributions first.

**Comment by ekager** [comment]
Fixed

**Comment by trainoasis** [comment]
@ekager where was this fixed? Trying GeckoView via adb with 

```
 geckoview_channel = "armeabi-v7a"
  geckoview_version = "73.0.20200217142647"
```

and dropdowns don't open still. Am I expecting something I shouldn't ?
