### ISSUE TITLE
[ux] improve custom tabs experience - research and consider prior works

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#1625]
#1624 [meta][ux] improve custom tabs experience

- [x] competitive analysis – how has other browsers handle custom tabs and the interaction between custom tabs and their own browser?
- [x] consider ideas from prior works – how can we solve this problem using ideas we’ve thought of previously?

#### Other browsers to research

* Chrome
* Yandex
* (Browsers like Edge, Opera, UC, Dolphin, etc. doesn’t seem to have Custom Tabs – correct me if I’m wrong)

#### Prior works

* #1341 [Meta] Improve Custom Tabs Interactions
  * #1282 [meta] Interaction between custom tabs and normal tabs is weird.
  * #610 CustomTab followups
  * #1529 Custom Tabs: No option to open URL in Focus

**Comment by brampitoyo** [comment]
## Competitive analysis

### Chrome

Has a “Powered by Chrome” text underneath the menu – a handy feature to give user a ‘branded’ experience.

<img src="https://user-images.githubusercontent.com/51007/32421990-2ee60f64-c302-11e7-9e8c-c01029c18d3d.png" width="320"> <img src="https://user-images.githubusercontent.com/51007/32422002-4703eada-c302-11e7-99d9-15d460d28ee8.png" width="320">

### Yandex Browser

Has a bottom navigation and a custom menu with icons, identical to how things look like on their browser app, except without an editable address bar.

<img src="https://user-images.githubusercontent.com/51007/32422013-5bf6f036-c302-11e7-9a3f-52d015a2efb3.png" width="320"> <img src="https://user-images.githubusercontent.com/51007/32422029-82e0543a-c302-11e7-9778-614bf3baeef1.png" width="320">

### Brave

Has a custom Brave icon on the address bar, which controls their ‘shields’ and blockers. Their menu is identical to Chrome otherwise.

<img src="https://user-images.githubusercontent.com/51007/32422084-f9758d86-c302-11e7-87d6-0369d59791e3.png" width="320"> <img src="https://user-images.githubusercontent.com/51007/32422183-a1444c00-c303-11e7-9f11-f1753ad51c50.png" width="320"> <img src="https://user-images.githubusercontent.com/51007/32422094-033c82a2-c303-11e7-8144-5d54de1cf742.png" width="320">

### Focus

* We brand our custom tabs using a purple status bar, and leave the address bar coloured by the application itself.
  * There’s probably nothing we can do to change that colour.
  * But we should also note that other browsers are content to follow whatever colour the app has prescribed.
* Our address bar doesn’t show a site name
  * This is consistent with how the address bar in Focus.app behaves.
  * But every other browser with custom tabs display the site name.
* We have a dark menu. To me, this doesn’t look too much like an issue – just a minor visual difference.
  * The user can control blocking from inside the menu.


<img src="https://user-images.githubusercontent.com/51007/32422307-7cb3e476-c304-11e7-901e-dea7f9df49ca.png" width="320"> <img src="https://user-images.githubusercontent.com/51007/32422318-89b8e1b2-c304-11e7-8f2d-dcff8db6153a.png" width="320">


### Recommendations so far (which might change in the future)

Consider having a one-tap shortcut to “Open in Firefox Focus”. Show either a link or an icon in the address bar (like Brave).

What I’m still unsure about:

* The discrepancy between our purple-coloured status bar and whatever colour the app will choose for the address bar. Is it better to harmonise our custom tabs with the app colour scheme and have a little text that says “Powered by Firefox Focus” inside the menu, or is that too subtle?
* Our address bar doesn’t show a site name, but this seems like a nice to have feature rather than a strict requirement.

**Comment by brampitoyo** [comment]
## Ideas from prior works

After reviewing issues #1341, #1282, #610 and #1529, there are a couple more recommendations I’d like to note.

* Some users complained of the fact that they can’t edit the URL in the address bar
  * One of the functions that editing can enable is cut/copy/paste.
  * To help mitigate this problem, what if we allow URL copying when user long presses the address bar?
* Our in/out animation is different from every other browser with custom tabs. It would be good to follow what everybody else has done here. Demo:
  * Chrome: https://cl.ly/16163X361g08
  * Focus: https://cl.ly/2J1j1i282N3A

**Comment by brampitoyo** [comment]
A couple of ‘is this possible?’ questions for @pocmo:

* Can we colour our custom tabs so that it matches our purple colour scheme?
  * If not, consider branding our custom tab another way, e.g. inside the menu

* Some users have said that they’re ‘stuck’ and unable to ‘move forward’ when they open an address in our custom tabs.

  * Can we include an icon in the address bar, that when tapped, will open the address in Firefox Focus?
    * If not, can we include a text instead? (But text might be too long)
    * If not, then we need to make sure that “Open in Focus” or “Switch to Focus” – whatever the wording may be – is prominent and easy to access in the menu.

  * Since the user will almost always tap (or long press) the URL on the address bar to try and ‘do something’ with it, can we provide actions there? For example:
    * When the URL is tapped, can we open it on a new tab in Firefox Focus app?
    * When the URL is long pressed, can we show context menu with items such as `Copy` and `Open in Focus`?

**Comment by pocmo** [comment]
> Can we colour our custom tabs so that it matches our purple colour scheme?

So that in your example the status bar would not be red but use our purple gradient? Yeah, that would be possible.

> Some users have said that they’re ‘stuck’ and unable to ‘move forward’ when they open an address in our custom tabs.

Yeah, that's possible - although I wonder if it should really be in the toolbar. Unfortunately we accidentally removed Focus from the "Open with" menu which makes it even harder right now (#1529). I think the feeling of getting stuck is mostly triggered by #1282: Custom tabs should **not** show up in the tab switcher and should not **replace** the browser window. We should show multiple concurrent custom tab "windows" along with the normal "browser window".

> Since the user will almost always tap (or long press) the URL on the address bar to try and ‘do something’ with it, can we provide actions there? For example:

Yeah, we can add actions to that gesture too.

Note that: A "custom tab" is completely our own UI and we can do whatever we want. If a custom tab is launched the app tells us a bunch of configuration values (like toolbar color, menu items, etc.) - but we are free to do whatever we want with that - even ignore it.

**Comment by brampitoyo** [comment]
@pocmo Thanks for your answers. It’s really good to know that we can:

* Do whatever we want with custom tabs design – including having our own colour scheme. This is interesting, and I have to think about how much we want our own branding versus the app’s.
* Add a link, button, etc. to open the URL in Focus app

I also agree that there needs to be clear and explicit separation between custom tabs and browser tabs. When the user opens a link from a third-party app which opens a custom tab, our custom tab should be a part of that app, not a part of the Focus browser.

This means that, in the app switcher, our custom tab is shown (and titled) as the third-party app where it originates from. The user can quit that app, and it wouldn’t impact any tab currently open on the Focus browser.

When we separate the two, “transferring” a custom tab to a browser tab using an “Open in” or “Switch to” link makes sense.
