### ISSUE TITLE
[ux] improve custom tabs experience - design

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#1626]
#1624 [meta][ux] improve custom tabs experience

Explore and ideate on possible solutions.

Expect specs and flow-centred solutions that we all can discuss, rather than ones with a lot of visual design – which will be coming later on in the process.

**Comment by brampitoyo** [comment]
After thinking about the things we can do on Custom Tabs – the answer turned out to be “nearly everything”! – the least disruptive solution seems to be one that:

1. Explicity separates custom tabs from app tabs
2. Clarifies the path forward. Ie. You’ve opened custom tabs. Now what? Open it in Focus or other apps?

While making minimal change to the visual design (at least for now – even though we can do that, as well).

Although we may discuss the specs further down, any update I will make to the spec will be made on this post and labelled accordingly.

![spec android custom tabs](https://user-images.githubusercontent.com/51007/33000513-82e6a60a-cde3-11e7-8716-464976933478.png)

**Comment by pocmo** [comment]
@brampitoyo Nice! I like that. :)

**Comment by brampitoyo** [comment]
@pocmo Thank you! Just one tiny additional note, which I’ve updated above: we should always show the Share icon on the toolbar. This will help our users feel less ‘locked out’ when they’re opening our custom tab.

**Comment by pocmo** [comment]
@brampitoyo Note that apps using custom tabs can request to add their own icon (only one afaik) to the toolbar. If we continue to support this and always show the share icon then we would show up to three icons (including menu button).
Too make things even more complicated: Some apps deliberately do not want the default share button because they add their own share button to the toolbar. One example of this is Google+. With that we would show two share buttons in the toolbar.

**Comment by brampitoyo** [comment]
@pocmo What about deploying this logic?

* If the app requests adding a non-share button, show it alongside `focus-share` and `focus-menu`
* If the app requests adding its own share button, show it and hide `focus-share`. As a result, we show `app-share` and `focus-menu`

This might not be possible, or simply too complicated. If it is, we’ll think of another way forward.

**Comment by pocmo** [comment]
@brampitoyo The third-party app can set **one** action button that will show up in the toolbar. We do not really know whether it is a share button or something else.

https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.Builder.html#setActionButton(android.graphics.Bitmap,%20java.lang.String,%20android.app.PendingIntent,%20boolean)

**Comment by brampitoyo** [comment]
@pocmo Thanks for confirming that! So, at the risk of reiterating, if I understand correctly:

1. There’s no way for us to know the whether the button that the third-party app is going to display is a share button or not (and if we can, it might be hard to do, anyway)
2. It also looks like we cannot simply ignore the third-party app’s request to add a button. Once `setActionButton` is invoked, we must display it.

**Comment by pocmo** [comment]
1. Correct.

2. Technically we can ignore it. But I doubt that's helpful. For example the twitter app shows a "Tweet" button. If we hide that one - is this helpful?

**Comment by mcomella** [comment]
> There’s no way for us to know the whether the button that the third-party app is going to display is a share button or not (and if we can, it might be hard to do, anyway)

Two ideas:
1. (safest) If the app declares a custom action button, we don't show "Share". Otherwise, show "Share".
2. We could apply a heuristic based on the data from the custom action button, e.g. if their button description includes "Share", we hide our share item. If not, we show our share item.
    1. For the case where we incorrectly show two shares, maybe we should include extra text (e.g. Share from Firefox Focus) to disambiguate the actions.
    1. If we don't show share when we should, we're no worse off than we are now! The users can, "Open with...".

wrt 2), we could also put in some telemetry to find out how often apps add custom actions and thus how often we're likely to get this logic wrong. **We're really trying to help out users who don't get a "Share" action button from the app** so if the number of action buttons apps add overall is negligible, it makes sense to try a heuristic like the one above.

@brampitoyo @pocmo What do you think?

**Comment by pocmo** [comment]
> (safest) If the app declares a custom action button, we don't show "Share". Otherwise, show "Share".

Isn't this what Bram suggested initially? In the example of the twitter app this means we would hide the "tweet" button.

> We could apply a heuristic based on the data from the custom action button, e.g. if their button description includes "Share", we hide our share item. If not, we show our share item. 

I can see No-Jun file issues about duplicated share buttons already. :) L10N will make this a bit more complicated. Focus has its own language picker so the language of the third-party app and Focus might differ.

> wrt 2), we could also put in some telemetry to find out how often apps add custom actions and thus how often we're likely to get this logic wrong. 

We already have a bunch of custom tabs telemetry. Maybe we can answer this already.

**Comment by brampitoyo** [comment]
Thanks for the suggestion, @mcomella, and for reiterating our goal. We just want to show a share button. Whether it comes from the app or from us, it doesn’t really matter as long as it’s shown.

Solution 2 sounds similar to what I had proposed earlier on https://github.com/mozilla-mobile/focus-android/issues/1626#issuecomment-347849393, but didn’t know whether it would possible.

I’ve tested how different well known apps implement custom tabs:

* Facebook, Facebook Lite, Messenger and Instagram: own browser (we don’t control it)
* Twitter: custom tabs + `Tweet` action item
* Google Now: custom tabs + `Add to Collection` action icon
* Gmail, Yelp: custom tabs, no action
* LINE Messenger: custom tabs, no action
* Pinterest: opens link directly in browser

It seems that approach 2 will work and produce a good result for all of the apps above.

What do you think?

**Comment by pocmo** [comment]
Bram and I talked about this on Vidyo. Here's what we want to do:

* #1358 -> Always show the "Share" menu item (I'll prepare a patch)
* (To be filed) -> Show a share button in the toolbar if the app doesn't show its own action button (no matter what it is)
* (We have a related issue) -> Always show a "Open with Firefox Focus" menu item

**Comment by bbinto** [comment]
Thanks everyone for working through this.
> wrt 2), we could also put in some telemetry to find out how often apps add custom actions and thus how often we're likely to get this logic wrong.
> We already have a bunch of custom tabs telemetry. Maybe we can answer this already.

Is it "custom_tab_action_bu" [here](https://github.com/mozilla-mobile/focus-android/wiki/Telemetry#custom-tabs) ? 

> (To be filed) -> Show a share button in the toolbar if the app doesn't show its own action button (no matter what it is)

Filed: https://github.com/mozilla-mobile/focus-android/issues/1951

**Comment by pocmo** [comment]
> Is it "custom_tab_action_bu" here ?

That's for clicks on the button. If we want to see how often apps just show it then we should look at (action, intent_custom_tab, app) and then into the extras to see if it contains `hasActionButton: true`.

**Comment by brampitoyo** [comment]
I’ll close this issue now that all outstanding implementation bugs have been filed. Refer to the specs https://github.com/mozilla-mobile/focus-android/issues/1626#issuecomment-345580294 to answer any question about other behaviours.
