### ISSUE TITLE
[ux] improve custom tabs experience - deliverables

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#1629]
#1624 [meta][ux] improve custom tabs experience

- [ ] specs (IA, mocks, visual specs)
- [ ] copy
- [ ] assets

This step may consist of just slightly tweaking the specs, or altering them significantly.

**Comment by bbinto** [comment]
@brampitoyo Do we still need these [ux] bugs or is everything added to #1624

**Comment by brampitoyo** [comment]
This bug is for the tweaks that we’ll make after we launch custom tabs – but it sounds like it’s not needed for the moment. Closing for now (we can always reopen later).
