### ISSUE TITLE
some translated locales still displays in English ('id', 'nl')

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#163]
After setting the locale to 'id' (Bahasa Indonesia I believe), the Focus app still displays menus in English.  I also tried in Bahasa Melayu, but shows in English as well.  Tried both on simulator and Experia Z3C with marshmallow.  (Tried both manually and using screengrab)

![browserviewmenu_1488815180187](https://cloud.githubusercontent.com/assets/6930774/23617332/cb92f8fe-025a-11e7-9e26-5146c1219151.png)

**Comment by npark-mozilla** [comment]
Just found 'nl' also shows in english as well.

**Comment by tomer** [comment]
Hebrew is missing as well. It is 100% translated on Pontoon, and the generated screenshots show the strings in English. (But featuring an Hebrew keyboard layout…) 

Locale code `he` everywhere but `iw` on Java/Android.

**Comment by ahunt** [comment]
I'd filed #186 to fix the locale mappings (which would fix Hebrew, i.e. iw/he), but I then realised that Indonesian (id/ih) is also one of the locales needing a mapping, i.e. my bug is a dupe.

Outdated mappings doesn't explain Bahasa Melayu though, that might need more investigation

**Comment by ahunt** [comment]
> Just found 'nl' also shows some locales in english as well. it looks like perhaps not all locales that are marked as 100% in https://l10n.mozilla-community.org/webstatus/?product=focus-android are fully localized.

I think for that we just need to do a new string import values-nl/strings.xml in master only has 24-ish strings, whereas that dashboard states there are 37 strings.

**Comment by pocmo** [comment]
@npark-mozilla Is there any locale left that doesn't work (and has strings imported) or can this be closed?

**Comment by pocmo** [comment]
Looking at the latest screenshots 'nl' and 'id' show up correctly now.
