### ISSUE TITLE
Tesco Direct asks me to switch to chrome

### ISSUE THREAD

**Issue by simonsteiner1984** [mozilla-mobile/focus-android#1631]
Goto https://www.tesco.com/direct/

**Comment by liuche** [comment]
Action item: file a web evangelism bug on bugzilla.mozilla.org about this so that team can reach out.

**Comment by MrGeneric** [comment]
Here's a screenshot. The user is presented with a dialog, but is allowed to continue.

![image](https://user-images.githubusercontent.com/3923223/32521085-17e3138a-c40a-11e7-9716-fa1d4c23a9db.png)

Seems like the Focus cookie blocking is causing the dialog to appear.

`$.cookie('androidMessage')=== null`


```
 
if (isNative && isAndroid) {
      androidMobileVersion = ua.match(/Android (.*?);/);
      androidMobileVersion = androidMobileVersion ? parseFloat(androidMobileVersion[1]) : false;

      if (!isNaN(androidMobileVersion) && androidMobileVersion < 4.3 && $.cookie('androidMessage')=== null) {
        lightboxContent = '<div class="androidMessageWrapper"><p class="androidMessage">'
          + 'The browser you are using does not provide the optimal experience when using the Tesco Direct website.</p> '
          + '<p class="androidMessage">For the best experience, please download and use Chrome.</p><div class="button-wrapper">'
          + '<input type="submit" class="button" id="androidMessageDownload" value="Download">'
          + '<input type="submit" class="button" id="androidMessageClose" value="Continue Anyway"></div></div>';

```

**Comment by Jacquester** [comment]
Is this still open ?

**Comment by mcomella** [comment]
The action item for this bug is to file a web evangelism bug on Bugzilla: https://github.com/mozilla-mobile/focus-android/issues/1631#issuecomment-342544266

Web evangelism is a team at Mozilla that reaches out to various web properties to make them aware when there are incompatibilities with Firefox.

**Comment by Jacquester** [comment]
I only found a Tech Evangelism team on bugzilla, is this correct or am I looking in the wrong place ?

**Comment by kai-chi** [comment]
Created a bug on webcombat: https://webcompat.com/issues/15197

**Comment by Samollo** [comment]
Hi,

Is this issue still open ? I'd like to contribute. :)

**Comment by Sdaswani** [comment]
@Samollo i don’t think there is eng work here - we filed a bug with webcompat and now we have to wait. But thanks for your help and let’s find something else for you to work on.

**Comment by pocmo** [comment]
Closing this in favor of just keeping: https://github.com/webcompat/web-bugs/issues/15197

**Comment by simonsteiner1984** [comment]
webcompat/web-bugs#15197 is closed, is this issue fixed?

**Comment by pocmo** [comment]
I'll comment on the other bug.
