### ISSUE TITLE
Add probe to record when user opens Focus via tap on Focus app icon

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1635]
Besides knowing when a user opened Focus via shortcut or intent (via different apps), I'd like know when a user actually clicks on the Focus app icon.

https://github.com/mozilla-mobile/focus-android/wiki/Telemetry#browsing

**Comment by pocmo** [comment]
Technically there are two things we can track here:
* (1) Actual app launches from the launcher icon
* (2) App resumed from the launcher icon (The app could still be active)

Are you only interested in (1) or do you want to see all clicks on the launcher icon? Should we have two probes?

**Comment by bbinto** [comment]
I think (1) is enough, even if the app is already active, I'm only interested in the conscious choice that the user makes when opening Focus via clicking the app icon.
