### ISSUE TITLE
Comments via facebook comments plugin  not loading

### ISSUE THREAD

**Issue by layely** [mozilla-mobile/focus-android#1638]
When I read articles on [footmercato.net](footmercato.net), I can't see the comments. It's like focus can't load them.
e.g: 
- go to  [footmercato.net](footmercato.net)
- click on one article
- scroll down to see the comments

**Comment by pocmo** [comment]
Does it work if you disable content blocking in the menu? FWIW Facebook *is* a tracker in this situation.

**Comment by layely** [comment]
Well @pocmo It works when content blocking is disabled. 

>FWIW Facebook is a tracker in this situation.

But I think it's harsh considering it so ?

**Comment by pocmo** [comment]
> However I find it harsh considering it so ?

Maybe. :) But technically this is a way Facebook can (and probably does) track you across sites. This is controlled by the "Block social trackers" setting.

**Comment by layely** [comment]
>But technically this is a way Facebook can (and probably does) track you across sites.

Agree with that @pocmo. This is issue can be closed now. Thank you!
