### ISSUE TITLE
Language names missing after switching to a different language

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1640]
Android 5.1.1 (Sony Z3C).

When switching to a different language I see some language names disappear and getting replaced with the language code. That's strange as we are not translating the names based on the current language.

It also seems to depend on the language. If I set it to "Asturianu" then the following languages do not have a name anymore:
* Dsb
* Fy (NL)
* Hsb

I also wonder why they start with a uppercase letter?

**Comment by vickz84259** [comment]
Is anyone working on this? I would like to help

**Comment by lobontiumira** [comment]
This issue still reproduces on the latest RC 92.1.1 build with Samsung Galaxy Tab A6 (Android 5.1.1).
The FY (NL) is displayed also on Firefox RC 92.1.1.
Not reproducible with Samsung Galaxy Note 8 (Android 9).

![Untitled](https://user-images.githubusercontent.com/40694158/134460402-13855565-2ff5-4c51-8c2c-f52b00702f52.png)

**Comment by lobontiumira** [comment]
This issue still reproduces on Beta 95.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by delia-pop** [comment]
The issue could also be reproduced on Beta 95.0.0-beta.3 with Huawei P9 Lite (Android 8).
"Nv" is displayed in the language list after setting the "Aimara" language.

![Capture](https://user-images.githubusercontent.com/89388888/140496873-2f856ead-697e-4f2a-bf81-d294bd1908c6.PNG)

**Comment by lobontiumira** [comment]
I was able to reproduce this on Beta 96.0.0-beta.1 with:
* Samsung Galaxy Tab A6 (Android 5.1.1) Focus is set to Basa Jawa language, displays the Dsb.
* Sony Xperia Z5 Premium (Android 7.1.1) Focus is set to Basa Jawa language, displays the Nv:
![Screenshot_20211208-161804](https://user-images.githubusercontent.com/40694158/145224336-aefcd0e8-016c-4cd1-9213-8e2084ceb6f3.png)

**Comment by lobontiumira** [comment]
I was able to reproduce this by setting Focus app in Basa Jawa, and Aimara:

![l10n](https://user-images.githubusercontent.com/40694158/147647250-242987b5-0423-493e-a5ea-ecab979ea7dc.jpg)

Tested on Focus Nightly 97.0 (build 353631110 GV 97.0a1-20211228034259) with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
Reproducible in Beta 97.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by delia-pop** [comment]
Reproducible in Beta 97.0.0-beta.2 with Google Pixel (Android 12).

**Comment by lobontiumira** [comment]
Reproducible in Beta 98.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on RC 97.1.1 with ChiShona language, on Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 104.0a1 from 7/25 with Samsung Galaxy Note 8 (Android 9), and Oppo Reno 6 (Android 12):

![1640](https://user-images.githubusercontent.com/40694158/180744939-cfac56d0-c2ba-4717-9eba-185f8177f160.png)
