### ISSUE TITLE
Implement AutoFill functionality 

### ISSUE THREAD

**Issue by shubham171294** [mozilla-mobile/focus-android#1641]
Hi, I want to auto fill user credentials using this browser. I don't  want to use Android's Oreo Autofill API.  Do we have any module in firefox focus that we can use to achieve this? 

For Example- I want to fill username and password of Facebook when the user opens the website. Please note that I already have user credentials saved in my database and I've already integrated this project as a library.
A real perfect example is [LastPass(link)](https://play.google.com/store/apps/details?id=com.lastpass.lpandroid)

**Comment by pocmo** [comment]
From this and your previous questions I'm wondering: Are you working on a fork? Is anything of that work public?

Currently such functionality does not exist in Focus. You might be interested in following #1525.

**Comment by shubham171294** [comment]
No, it doesn't exist yet. Basically, I wanted to implement this functionality so needed to ask if it already exists or not.

I'll check the issue #1525 though.Thanks.
