### ISSUE TITLE
[meta] Retain cookies and login info 

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1651]
User Story:
- As a user, I want to frequent my favorite website without having to login each time

Some quotes (login related)
- I get an email with a link to a website that requires my login info
- I have few websites which I visit frequently and I want to keep cookies for them (whitelist); for any other websites I want to block third-party and/or first-party cookies completely or destroy them
- I can't use focus because I read nytimes.com multiple times per day and would have to sign in each time I visit.
- any site must warn visitors about cookies.. So each time we go on a site we often visit, we get the same information message about cookies that we have to dismiss!
- My main issue is not being able to use my default search engine's custom settings since they're stored in a cookie
- Every time I open it, I have to resign into Twitter

Follow-up to #1525 

- [x] #1042 
- [x] #1041
- [x] #1058 
- [ ] #1485 1485

**Comment by pocmo** [comment]
* So #1525 is not necessarily about saving login data?
* nit: "Retain cookies" is already a solution to the described problem. Are there others? Could making logging in easier solve some?

Having tracking protection and retaining cookies is a tough nut to crack. The same cookie that is used to remember your login session could be used to track you across sites. This might require that we either disable third-party cookies or use "first party isolation" (I guess that's only possible on Gecko) - both mechanisms could cause problems with some sites.

**Comment by bbinto** [comment]
@pocmo; followed your suggestion [here](https://github.com/mozilla-mobile/focus-android/issues/1525#issuecomment-338681446)

@lime124 let me know what your thinking around #1525 was so far as it relates to addressing the cookie/login issues? I was under the impressing, for 3.0 getting both done would probably be not possible? Happy to revise ;)

**Comment by pocmo** [comment]
> Having tracking protection and retaining cookies is a tough nut to crack. The same cookie that is used to remember your login session could be used to track you across sites. This might require that we either disable third-party cookies or use "first party isolation" (I guess that's only possible on Gecko) - both mechanisms could cause problems with some sites.

Just wondering - if we ever switch to GeckoView then this could be a problem too: We would need to modify private browsing mode to still save some data.

**Comment by lime124** [comment]
@bbinto I'm looking at password management integration (e.g. lastpass) as part of the solution set to solve the problem in #1525. 

Cookies, b/c of the concerns @pocmo initially mentioned to me, are not part of the solution.

**Comment by bbinto** [comment]
Supporting user story:  "as a French person and a Focus user myself, I think an important reason why I use it (and presumably others too) is not because of privacy concerns but because most of the major newspapers limit the number of articles you can read for free per week to 5. using focus you can bypass this restriction"

**Comment by sinelaw** [comment]
Isn't the fact that it doesn't save data between sessions the main feature of Firefox Focus?

**Comment by bbinto** [comment]
Mozilla stands for two things: Privacy and User's choice.

@sinelaw Erasing data between session is one of the main advantages of Focus, which we won't take away. If you don't want to use any password managers or keep any session information for different reasons, we still provide privacy by default. 

We've noticed that people like to use Focus as a simple and fast ad block browser and as a simplified browser without wanting to sacrifice convenience over privacy.
