### ISSUE TITLE
Consider including debug info (WebView version, user agent) in product

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1655]
This way it'll be easier to ask bug filers for debug information.

We could add a page like `about:debug` or include a menu option (maybe 3-dot -> Settings -> About Firefox Focus, which already has the build ID)

**Comment by mcomella** [comment]
Alternatively, we could:
- Create a page that indicates all the debug info we need (like https://www.whatismybrowser.com/detect/what-is-my-user-agent but Focus-specific)
- Provide a wiki page, that we can link to in bugs, that will give you steps to find all the important information (e.g. here is how you get your user agent, webView version, etc.)

**Comment by pocmo** [comment]
> about:debug

Note that we use "focus:XXX" for other internal pages as "about:" is primarily used and reserved by Chrome/WebView.

Also see #1465 for creating an issue template - Whatever we decide to do here should be mentioned in the template. :)

**Comment by grubdragon** [comment]
Is this something I can implement?

**Comment by mcomella** [comment]
@grubdragon Sure. I think the things I most often ask people for are:
- user agent
- Focus/Klar version
- Android version

I'd say we create a `focus:debug` URL that displays ^ this information to start. It doesn't need to be too pretty because it's a debug page.

Thanks!
