### ISSUE TITLE
"Open with..." does not show Rocket when user has default browser

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1656]
via https://github.com/mozilla-tw/Rocket/issues/1149#issuecomment-341329353

> Here's the brief:
> 1. If no default browser is set, we can easily identify all browsers that can handle this open intent.
> 2. However, when a default browser is set, this does not work anymore, Focus try to send intent to all those known browsers which is hardcoded to try find if these exist on user's environment. Firefox Rocket is not listed (yet) in this hardcoded known browsers.

If I understand this correctly, we should add Rocket to the known browsers list.

**Comment by mcomella** [comment]
In order to tackle this bug, you'll need to get added to the Firefox Rocket beta – let us know if you want access.

You'll then need to update the `KnownBrowser` list in `Browsers.java` to include Rocket.

**Comment by nosark** [comment]
I would like to work on this if it is still available

**Comment by pocmo** [comment]
@nosark Yes, this is still available. :) Do you need any help?

**Comment by nosark** [comment]
Yes Please :). I am trying to install rocket from github and i've got it, but it won't let me sign the apk and use (webkitDebug) variant, so I can't test Rocket and try to reproduce the issue or test it when I am finished. Double checking, am I simply adding Rocket to the Known Browsers Enum in Browsers.java in focus?

**Comment by mcomella** [comment]
> I am trying to install rocket from github and i've got it, but it won't let me sign the apk and use (webkitDebug) variant,

@nosark Perhaps it'd be easier to use the Google Play build? https://play.google.com/store/apps/details?id=org.mozilla.rocket Though I'm not sure if it'd be available in your locale.

That being said, I was not able to build a fresh Rocket download with the default variant (focusWebkitBeta) but switching to focusWebkitDebug allowed me to build focus (I wonder if there is a different package name though? - which may affect this bug).

> Am I simply adding Rocket to the Known Browsers Enum in Browsers.java in focus?

That's my understanding. :) But if it doesn't work, feel free to dig in a little yourself and let us know if you run into trouble!

**Comment by nosark** [comment]
I was able to reproduce getting Mozilla Rocket from mozilla-tw/Rocket focus android from 
mozilla-mobile/focus-android and reproduce the bug. I've made the update to Known Browsers and everything works as expected.I left the PR request below
 https://github.com/mozilla-mobile/focus-android/pull/1849

**Comment by pocmo** [comment]
@nosark Just merged your patch. Thank you! :)
