### ISSUE TITLE
Update 3-dot overflow menu to match mocks

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1658]
Check against the mocks from #1260: 

https://user-images.githubusercontent.com/1994820/30620468-61691760-9d5a-11e7-9ba5-400c67231760.png

And ensure we have the right colors and padding/spacing for both the start screen and the browser screens. Note that these may already be correct, in which case there are no code changes that need to be done in this bug.

@layely has been working on this. FYI, layely, that I broke this out from #1260.

**Comment by shikhart98** [comment]
Can I work on it?

**Comment by yatri1609** [comment]
Hey, I would like to work on this so can anyone either @mcomella  or @layely can guide me through this as it would be my first time contributing to open source. Thank you.

**Comment by mcomella** [comment]
Hey @yatri1609 – I'm not actively working on Focus anymore but @ekager or @boek can certainly help out! :)

**Comment by yatri1609** [comment]
@ekager and @boek  can anyone of you help me out and guide me what exactly I have to do in this?

**Comment by ekager** [comment]
Hey @yatri1609 you'll have to check the picture in the original post at the top and then make sure our colors match the mock for the 3 dot menu. They could already be correct in which case, you could verify that and close the bug. From a quick glance, looks like the pressed gray state may need to be changed as it's a bit too light.

**Comment by yatri1609** [comment]
@ekager  Sure I'll check it and correct it if needed. Thanks
