### ISSUE TITLE
Save newly added search engines

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1660]
Meta: #961 

#1617 added the screen to create new search engines, this issue is for actually saving them.

This bug should validate the search string, and then save the search engines in opensearch format, and then show them in the search engines page.

**Comment by liuche** [comment]
This is part 2, and only handles saving search engines.

I think we'll need to add some more strings because our error messages are not satisfactory/complete ( #1567 ) and there are still more parts, see #961 for meta and current progress.

@npark-mozilla alternatively I can flag you when all of #961 is done, what would you prefer?

**Comment by npark-mozilla** [comment]
@liuche i think current approach is good, if it becomes too cumbersome, let me know.
