### ISSUE TITLE
[Meta] Quick access to favourite sites 

### ISSUE THREAD

**Issue by jenn-chaulk** [mozilla-mobile/focus-android#1666]
From focus-android created by [jenn-chaulk](https://github.com/jenn-chaulk) : mozilla-mobile/focus-android#1665  

From focus-android created by [bbinto](https://github.com/bbinto) : mozilla-mobile/focus-android#1525  

User Story:
- As a user, I want to access my frequently visited websites without always having to type in the full URL
- As a user, I want to frequent my favorite website without having to login each time

Some ideas that were floating around (without being prescriptive)
- Allow users to add their own defined sites to an autocomplete list
- Promote "Add to Homescreen" as a way of bookmarking things

**Comment by pocmo** [comment]
Isn't #1525 the meta?
