### ISSUE TITLE
What's New Entry for 2.4

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#1670]
We need a What's New entry for version 2.4 of Focus Android. Looking at the [work list](https://github.com/mozilla-mobile/focus-android/milestone/17?closed=1) a few notable updates are - Swipe to refresh?

cc @mcomella we should add this to the releng list, i.e, file a ticket for what's new content.

**Comment by lime124** [comment]
Here is link to WIP doc: https://docs.google.com/a/mozilla.com/document/d/1kfz01x4vpoIQphbymmGsWcpY3CzytbjQ9sYWW0TX0ok/edit?usp=sharing

**Comment by lime124** [comment]
@BrianNJones said he would be able to finish by friday.

**Comment by mcomella** [comment]
> cc @mcomella we should add this to the releng list, i.e, file a ticket for what's new content.

Done.

**Comment by BrianNJones** [comment]
Added bullet point for "swipe/pull-to-refresh" feature. Looking through the rest of the list, #1306 is a candidate, but I think we can exclude given the smallish subset of affected users.

**Comment by lime124** [comment]
Pinged Joni that it's ready

**Comment by jonisavage** [comment]
Here's the URL you can use in product: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/whats-new-focus-android-24

**Comment by Sdaswani** [comment]
Hi @jonisavage why is this URL different than the previous what's new - we are hoping that the %VERSION% placeholder would allow us to use the same link so that we don't have to change this in every new app version.

**Comment by jonisavage** [comment]
Hi @Sdaswani, I'm double-checking with Roland but I know that the redirects on our platform will only work with the last part of the URL. 

For other OS (like Android) we can use one URL and have SUMO auto-detect that version and show conditional content, but we don't have that ability for iOS yet. Hoping Roland can give more insight.

**Comment by Sdaswani** [comment]
Ok thanks @jonisavage please let us know what Roland says. We have a patch ready for 3.11 to use the new URL but we should figure out a less error prone solution going forward.
