### ISSUE TITLE
Link color missing on some pages

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1674]
I noticed that on some pages the link color is missing and we are showing them in the default blue:

![linkcolor](https://user-images.githubusercontent.com/89638/32554960-bdbfb862-c49b-11e7-96f5-8ef80e395319.png)

Could be caused by 0ada32f4cdb8a80255bbb5f31ef0a5f7d643b562 (#1462)

**Comment by pocmo** [comment]
After reverting 0ada32f this is fixed. I'm going to push the revert to master.

**Comment by pocmo** [comment]
@mcomella I would like to uplift this to the 2.4 release branch.

**Comment by mcomella** [comment]
> @mcomella I would like to uplift this to the 2.4 release branch.

Done: https://github.com/mozilla-mobile/focus-android/commit/b00f12117d3306e223f9e7a7dc1c31e8cd69a8b6

**Comment by pocmo** [comment]
Thanks!

**Comment by npark-mozilla** [comment]
Was seeing it itermittently on automation too, good that it's fixed now
