### ISSUE TITLE
app:layout_behavior breaks geckoview

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#168]
A regression from #132: adding app:layout_behavior to the IWebView in BrowserFragment results in geckoview builds not rendering any web content: I just see a dark grey background, and no content. Pages still appear to load (i.e. I can see the progress bar, and URLs redirect), but they aren't visible.

We should fix our GeckoView wrapper to work again (we probably don't want to back out #132 since that's needed for the browser/toolbar to not look weird).

**Comment by pocmo** [comment]
@ahunt It looks like 82ddbcc41bf89ff901114bd68b5f0f35117e479f has fixed that?

**Comment by ahunt** [comment]
(2 months late...) Yeah, gecko seems to work : )
