### ISSUE TITLE
transformDexWithInstantRunDependenciesApkForFocusGeckoBeta

### ISSUE THREAD

**Issue by ZhangKuixun** [mozilla-mobile/focus-android#1680]
Error:Execution failed for task ':app:transformDexWithInstantRunDependenciesApkForFocusGeckoBeta'.
> Unexpected scopes found in folder '/Users/zhangkuixun/Downloads/focus-android-master/app/build/intermediates/transforms/dexMerger/focusGecko/beta'. Required: EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

**Comment by pocmo** [comment]
What are you intending to do? You might want to build "focusWebviewDebug" and not the Gecko version.
