### ISSUE TITLE
Error page will only load for one bad URL

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#1686]
Another Error page bug woo. Not sure if this is a known bug? 

STR:
1. Type invalid URL in URL bar and submit (ex- 'kkk.j')
2. Error page loads correctly 
3. Type another invalid URL in URL bar (ex - 'hhh.b')

Expected: Focus error page will load for new error
Actual: Generic webview error page loads

For fun - if you do it once more nothing loads and it's a blank page.

**Comment by pocmo** [comment]
> Not sure if this is a known bug?

Nope. :)

**Comment by ekager** [comment]
#1729 seemed to fix this as well ! :)

**Comment by pocmo** [comment]
Perfect! I'll close and let @npark-mozilla verify. :)
