### ISSUE TITLE
search engine sub text in edit mode

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1691]
This is a follow up issue to some leftover work before @liuche went on PTO. She said it should be really easy to get in before release. 

This is text to identify the default search engine in when in edit mode to help eliminate confusion over why it's grey out/disabled. 

We'll need a bit of copy from @BrianNJones

**Comment by BrianNJones** [comment]
I assume we're thinking something like the indicator (the word "Default") in reg'lar Firefox? If the selection is grey/disabled, do we really need it? Especially in changing a search engine, when the user is consciously changing "from" something (grey/default) to something.

**Comment by lime124** [comment]
@BrianNJones discussed today and talked me out of my crazy, "over-thinking it" idea. :)
