### ISSUE TITLE
RFE/C: Optionally Use Installed Search Engines For Browser Open Tiles/Fields

### ISSUE THREAD

**Issue by TPS** [mozilla-mobile/focus-android#1692]
Per https://github.com/mozilla-mobile/focus-android/issues/961#issuecomment-343262067, I'm moving this here:

![Opening shot](https://user-images.githubusercontent.com/287322/32563605-84e2d91e-c466-11e7-9f1f-6ebdc4440d1b.png)

There's a lot of blank (useless) space on the opening screen. All that space could serve us better. In regular Ff, we use tiles w/ user history. Since Focus/Klar doesn't have that, maybe search fields/tiles could optionally serve the same purpose of constructively using the space.

Any interest?

**Comment by TPS** [comment]
It's _better_ now that we can add 4 bookmarks here, but more/other would be good.…

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802036

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
