### ISSUE TITLE
Consider removing the "Browsing history has been erased" popup message

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1696]
See https://github.com/mozilla-mobile/focus-android/issues/1265#issuecomment-331670678 via @smartfonreddit 

When Focus is the primary browser and I use it to open links from Flamingo (twitter app), it gets on the way every time the back button is pressed to go back to Flamingo. This becomes a major annoyance after few minutes of use.

**Comment by bbinto** [comment]
should be done in combination of #1312

**Comment by lobontiumira** [comment]
I'll close this ticket as obsolete.
