### ISSUE TITLE
Transition from first-run screen to HomeFragment/BrowserFragment

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#170]
A better transition from first-run to either the main screen (or direct to the Browser if the first-run is shown when opening Focus via a VIEW intent) could be nice.

I'm guessing this isn't super important, but this is the first thing a user sees when using the app, so it's still quite nice to have?

**Comment by antlam** [comment]
On iOS, I believe we went with a 200ms linear fade just so its not so jarring.

Try that! @ahunt

**Comment by ahunt** [comment]
My phone doesn't seem to want to let me make great videos:
![fade2](https://cloud.githubusercontent.com/assets/1546915/24035742/11b41670-0af7-11e7-87e1-1ecf75ce8c8c.gif)

**Comment by antlam** [comment]
@ahunt I don't have my Android device with me right now so I'll have to give feedback later or you could try sending a .MOV file to me instead? QuickTime has a pretty easy way to record too. 

File > New Screen Recording and then click the Record button

**Comment by antlam** [comment]
@ahunt could you just push me a personal buddy build to try this out? I'm updating to master but I cant trigger this anymore
