### ISSUE TITLE
search engine example needs to be changed

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1705]
searchenginename.com

**Comment by pocmo** [comment]
This was briefly discussed when we landed the strings for the feature: https://github.com/mozilla-l10n/focus-android-l10n/pull/22 (Expand "outdated" comments).

![screenshot-2017-11-13 mozilla-l10n focus-android-l10n](https://user-images.githubusercontent.com/89638/32724377-584bc8a2-c871-11e7-820d-1fc4251f7d7e.png)

**Comment by lime124** [comment]
ok - so are we using example.com then? @BrianNJones is that ok or do you want to use searchenginename.com? Once we finalize, we should make sure ios is using the same string.

**Comment by BrianNJones** [comment]
It's fine. The IANA holds example.com open for this purpose. The original "searchengine.com" (instead of searchengineexample.com) was my brain hiccup. I prefer the more specific "searchengineexample," but "example" is fine.

**Comment by liuche** [comment]
Okay, sounds like we can close this.
