### ISSUE TITLE
Firefox Focus blocks Autofill Credentials javascript

### ISSUE THREAD

**Issue by shubham171294** [mozilla-mobile/focus-android#1717]
I wrote a javascript for autofill of username and password (I'm making kinda Password Manager). The script works fine. But when I try to click Login button, the login button does not work. When I see the number of trackers blocked it says 2(because I injected two pieces of Javascript). But when I enter the username and password manually, the login button works and I'm able to log in. This happens on all Social websites(Facebook, Twitter, Yahoo, Instagram etc)

Therefore, I went to browser settings and disabled the "**Block social Trackers**" switch. Then it started working fine. I could log in using autofill functionality.

My requirement is that, How should I prevent my own javascript to be blocked by Firefox focus? Or Can the code that blocks my javascript be altered without affecting privacy?

**Comment by pocmo** [comment]
Well, I can't help you debug your own unshared code. :)

The content blocking is based on URLs and I would be surprised if it blocked injected JS. Anyhow, you could start to investigate what happens inside shouldInterceptRequest and see if it's tracking protection that is blocking your JS or maybe something else:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/webview/java/org/mozilla/focus/webview/TrackingProtectionWebViewClient.java#L72

**Comment by shubham171294** [comment]
Ok Thanks. @pocmo Can we have a private chat so that I can share my javascript code and seek your help?

**Comment by shubham171294** [comment]
@pocmo Thanks for suggesting https://github.com/mozilla-mobile/focus-android/blob/master/app/src/webview/java/org/mozilla/focus/webview/TrackingProtectionWebViewClient.java#L72 . I made an exception to my own javascript. Now,it's working fine.
