### ISSUE TITLE
Ask the user to confirm telemetry action when the user mistap the button.

### ISSUE THREAD

**Issue by quakenet2** [mozilla-mobile/focus-android#1723]
As a privacy browser, I'm expecting this app to ask above thing.

Settings:
1. User is scrolling down menu.
2. User mistapped "Send anonymous usage data".
3. It was turned to "blue icon"(enabled).

Here, when 2 is happened(off->on), you should show a confirmation dialog:
"
Do you really want to send this data?
YES | NO(must bigger width than yes)
"

**Comment by quakenet2** [comment]
I'm talking about Klar because Klar is off by default

**Comment by bbinto** [comment]
I wonder if this is being over cautious, i.e. good UX, @lime124? 

Also @quakenet2, can you share some examples of such UX flow in other apps with a similar focus on privacy?

**Comment by lime124** [comment]
I think the answer hinges on if data is being sent the instant the toggle is turned on. In the event of a mis-tap, people immediately realize and set out to undo the action. 

If the answer is yes, I don't see the harm in confirming a potential data leak. 
If the answer is no (or we can delay it) then data isn't being leaked.

@pocmo would probably know.

**Comment by pocmo** [comment]
> I think the answer hinges on if data is being sent the instant the toggle is turned on. In the event of a mis-tap, people immediately realize and set out to undo the action.

No data will be sent in this case - we didn't collect any yet. If telemetry is disabled then we do not **collect** and do not **transmit** usage data. In addition to that there's a minimum amount of data that we collect before sending any ping - and we only do that if you leave the app. So while still in the settings screen nothing will happen.
