### ISSUE TITLE
Rewrite scrape_plugins.py

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1724]
Initially we imported this script from the Focus for iOS repository. The code is still pointing to the aurora repository and a file structure that doesn't exist anymore.

mozilla-central paths:

list.json:
https://hg.mozilla.org/mozilla-central/raw-file/default/mobile/locales/search/list.json

Search plugins:
https://hg.mozilla.org/mozilla-central/raw-file/default/mobile/locales/searchplugins

**Comment by pocmo** [comment]
In addition to that there seems to be a "regionOverrides" block now - which the old script doesn't use.

**Comment by pocmo** [comment]
Also see #1726 we should format the JSON file so that it can be read (and if needed modified) by humans.

**Comment by mastizada** [comment]
So, idea is to delete the current list.json file and import it in `scrape_plugins.py` from mozilla-central url - right?

**Comment by pocmo** [comment]
Yep.

The same script exists for Focus for iOS too.

**Comment by mastizada** [comment]
Ok, will check it tonight

**Comment by pocmo** [comment]
Not needed anymore since we use the component.
