### ISSUE TITLE
Image-blocking pref requires BrowserFragment restart to take effect

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#173]
STR:
1. Open website e.g. bbc.com (images are present)
2. Open menu->settings, enable "Block Images"
3. Press back to return to browser
4. Open menu->refresh
Expected: images disappear
Actual: images still visible (images continue being visible while you browse in this session)

If you exit the browser (and return to the homescreen), and reopen the same website, in place of step (3), then image blocking works.

We probably need to add a registerOnSharedPreferenceChangeListener() call to WebViewProvider, similar to what we do in UrlMatcher.

**Comment by pocmo** [comment]
Entering a new URL (and therefore replacing the browser fragment) should work too. But yeah, we might want to add a preference listener for the already existing WebView. :)

**Comment by ahunt** [comment]
It looks like cached images are still rendered. I'm guessing that's something we don't need to really worry about, but it does mean that refreshing an existing page wouldn't change anything if you start blocking images (but navigating to other pages without cached images will result in those images not being shown). I've already written the code, so I guess it's better to land that so that anyone who's testing the image blocking setting doesn't get confused by the presence of "unexpected" images.

**Comment by pocmo** [comment]
@antlam Do you think it makes sense to explicitly mention that this blocks images loaded over the network? Maybe as a description below "Block Images"?

**Comment by antlam** [comment]
Not sure I'm following along but that's how I would expect it to work. Why doesn't it work like that?
Shouldn't the images not load anyways after the user "Erases"?

@bbinto what're your thoughts on including this in V1? Should we still try and do that?

**Comment by pocmo** [comment]
We decided to skip image blocking in v1: We only added it because it seemed simple and now we discovered edge cases. I'll remove/hide the setting and file a new bug for re-adding it (and fixing/deciding on this here) - marked as "nice to have".

**Comment by antlam** [comment]
Note to self: 
- Subtitle to describe that there is a need to "restart"/"reload" the webpage the user is currently on in order for this to take effect
- Followed by a simple dialog to confirm the action (only applicable if the pref is not flipped on via the Home screen)
