### ISSUE TITLE
Remove unnecessary permission (RECEIVE_BOOT_COMPLETED)

### ISSUE THREAD

**Issue by quakenet2** [mozilla-mobile/focus-android#1732]
Why "run at startup" is necessary?

**Comment by pocmo** [comment]
This one is coming from our telemetry library and indeed seems to be unused.

**Comment by grubdragon** [comment]
Hey, should I remove the permission?

**Comment by Sdaswani** [comment]
@grubdragon will our telemetry library still work? Should the permission be removed from our telemetry library instead?

**Comment by grubdragon** [comment]
Hey @Sdaswani I'm not sure how focus works with the telemetry library, but seems that @pocmo and @bbinto have investigated it

**Comment by Sdaswani** [comment]
You can find the telemetry library here: https://github.com/mozilla-mobile/telemetry-android

Looks like this is where it is used: https://github.com/mozilla-mobile/telemetry-android/blob/790e5302fc866bfa2d50a80a4c8dfb6938f695e2/telemetry/src/main/AndroidManifest.xml#L8

If you confirmed it isn't needed and removed it from the telemetry library, one necessary step is to make sure that telemetry isn't affected, i.e., it's still working.

**Comment by grubdragon** [comment]
Actually, I would've gone ahead, but seems like its build is already breaking on TravisCI, and it doesn't seem like something I understand enough to fix.
