### ISSUE TITLE
Add telemetry to keep track of # of links clicked

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1753]
We do have probes to tell us when a user types in a query or URL into the search bar, or opens a link in a new tab, we don't have a probe that tells us about an event like user visits website A, clicks on link in A to go to B, loads website B etc.

With that data, we can not only define when a user is active, how active they are but also how they use the browser app and learn about their behavior to improve Focus.

**Comment by bbinto** [comment]
@eleemoz do you see any issues with that?

**Comment by bbinto** [comment]
We are thinking of just keeping track of a user clicking/tapping a link

**Comment by sinelaw** [comment]
As a user this goes against my expectations from a privacy-aware browser.

**Comment by bbinto** [comment]
I understand @sinelaw  - I might need to change the title of the issue. It's important for us to understand how users navigate through the app, is it one off searches or are users go from link A to link B etc. We would never store the information about what links were clicked or send it to another 3rd party.

Does that make sense?

**Comment by sinelaw** [comment]
Yes, that's clearer. Thanks!

**Comment by bbinto** [comment]
@liuche -- are we good from a data steward perspective? Legal didn't seem to have any objections

**Comment by liuche** [comment]
@bbinto If this is counting a telemetry event every time someone clicks a link this sounds fine. Adding this probe will involve:
* Adding the code
* Updating the telemetry part of the wiki to document the code usage
* Answering [these questions](https://github.com/mozilla/data-review/blob/master/request.md) in the bug (this is the new data review process) to document the reasons for collecting this data

**Comment by bbinto** [comment]
Ok, so how about we do the reverse, i.e. we do know how often people type in something in the URL bar, or open a tab. So, if we are able to track # of page loads overall, and assume a 1:1 relationship to pageload and URL typed in + opened link in new tab, we can subtract the number of these events to get the events that were triggered by a potential link. Is that correct?
