### ISSUE TITLE
[sumo] need article to describe Quick Access feature

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1754]
There are two "Learn more" links in the autocomplete settings screen. We will need SUMO URLs and content for them. The article should describe how the feature works in Focus and also show the built-in list (in alphabetical order)

meta: #1766 

Mocks: https://github.com/mozilla-mobile/focus-android/issues/1609#issuecomment-345856966

@pocmo can you point us to where we can find the list(s)? Thanks!

**Comment by pocmo** [comment]
Our lists are located here:
https://github.com/mozilla-mobile/focus-android/tree/master/app/src/main/assets/domains

They are derived from the Alexa top pages. When auto-completing we first look at the region specific lists (if available) and then in the global list.

For example my phone has en-US as primary locale and de-DE as secondary locale setup. When typing we try to autocomplete from the lists in this order:
* us
* de
* global

Related:
* #504

**Comment by pocmo** [comment]
This and #1787 are about the same pages, right?

**Comment by liuche** [comment]
@lime124 what do you think? I renamed while going through the 4.0 milestone so it was clearer, but if they are the same thing, then we could dupe one to the other.

**Comment by lime124** [comment]
yep it looks like they are dups. i don't think it matters which is closed as long as relevant info is pulled from the closed one.

**Comment by pocmo** [comment]
@lime124 We have two "Learn more" links in the settings page - Are they for two different sites?

@jonisavage Can we generate URLs for those pages already? :)

**Comment by liuche** [comment]
Assigning @ekager to update these 2 links to the product.

**Comment by lime124** [comment]
@liuche Both links should be the same page. Thanks!

**Comment by jonisavage** [comment]
https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/autofill-domain-android

We needed a separate link for the ios feature because the breadcrumb will show either ios or android on SUMO.

**Comment by jonisavage** [comment]
Android article is ready: https://support.mozilla.org/kb/autocomplete-settings-firefox-focus-address-bar.

The in-product link will automatically redirect to the article above.
