### ISSUE TITLE
[ux] search engine - implementation phase

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1755]
Track work done during implementation. Track with @liuche polish bug since there isn't a meta issue.

**Comment by lime124** [comment]
@liuche Feedback on build:

manual entry screen
- [ ] for the text fields - I want to use standard Android components. They should follow these states: https://material.io/guidelines/components/text-fields.html#text-fields-states
- [ ] can we get rid of the line under the example?
- [ ] is it possible to give 16dp padding on both sides of the text fields?

remove screen
- [ ] should be an X instead of a back

main search screen
- [ ] what size is the font in the new search engine icon? we need to make it a lot bigger :)
- [ ]  in the overflow menu - can we disable restore until one of the ones that ships is deleted

**Comment by liuche** [comment]
@lime124 made some changes, a few questions for you:

1. Standard Android Components:
There is a standard Android component for the label/text behavior of Material Design!...except it's a known issue that there are no "Placeholder" strings: https://issuetracker.google.com/issues/37065330

This means we don't get useful hint strings about copy-pasting the text in, and it looks like this:
![screenshot_1512115960](https://user-images.githubusercontent.com/1082253/33473746-7aaa6174-d62c-11e7-8b64-1b904c3d0b15.png)

I will take some time tomorrow to see if I can hack the hint strings in if there is no text, but which would you prefer?
a) No hint text but standard components
b) The way it is (non-standard text fields)

2. I have two icons with different text sizes, the "n" is 100f and the "u" is 64f. Do you like one of them, or do you have another size I should try?
![screenshot_1512115642](https://user-images.githubusercontent.com/1082253/33473867-fbb38cbe-d62c-11e7-827c-9dbbb12de6d8.png)

3. Having some trouble getting rid of the line under "example", if I don't figure out a way to do it, can we move it to the next sprint? or WONTFIX (but I have a few more things to try)

**Comment by liuche** [comment]
Okay, fixed all the issues but the line under, and after talking to @lime124 decided we can punt that for this release.

**Comment by liuche** [comment]
Closed by #1865.
