### ISSUE TITLE
"What's new" SUMO page for 4.0 release

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1773]

**Comment by rtanglao** [comment]
assign to joni pleae  @bbinto ?

**Comment by bbinto** [comment]
@jonisavage, please assign to yourself (I can't), I've added you to the NMX team.

**Comment by liuche** [comment]
Assigning @ekager to update this link to the product.

**Comment by jonisavage** [comment]
Here's the URL for Android: https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/whats-new-focus-android-4

The page will say "page not found" until we get the content up (coming soon).

**Comment by npark-mozilla** [comment]
Although content is not there, the page is correctly linked. @Sdaswani , when should we expect the content be available here?

**Comment by Sdaswani** [comment]
I just asked @jonisavage when we should expect the content.

**Comment by liuche** [comment]
@jonisavage do you need a list from us about what needs to be in the page? It's not clear to me where that communication needs to come from (Product, Releng, Eng)? Going to reopen because I need to track this as part of my work in #1765 .

**Comment by jonisavage** [comment]
Content is up. The in-product link should redirect here: https://support.mozilla.org/en-US/kb/whats-new-focus-android-4

Please comment in the Google Doc if you'd like to suggest any changes: https://docs.google.com/document/d/1BkNZyHUTvKR0EsbTlUa_d39bCjAQexIrb2tigSWx2w4/edit#

**Comment by bbinto** [comment]
Looks good Joni
