### ISSUE TITLE
Attempting to change search providers crashes

### ISSUE THREAD

**Issue by lexcyn** [mozilla-mobile/focus-android#1784]
Building via the latest code from git. If you go into Settings and select Search, it will force close and crash Focus. You cannot change the search provider.

**Comment by pocmo** [comment]
* Are you building the focusWebviewDebug variant?
* What's the stacktrace of the crash?

**Comment by lexcyn** [comment]
I'm building the Beta variant. I will get a stacktrace for you later today.

**Comment by bbinto** [comment]
Is this related to this #1819 , @lexcyn ?

**Comment by lexcyn** [comment]
@bbinto yes that seems to be the same info. I was not able to get a stacktrace of the issue on my phone but that seems to be what's happening. Can you merge this into that issue?

**Comment by pocmo** [comment]
Closing as duplicate of #1819
