### ISSUE TITLE
Focus can't open "https://search.app.goo.gl/" when opening it directly in Google feed

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1786]
Video [here](https://drive.google.com/open?id=1fAJdxvSLNhr5SkT39lJhmtxL872-MC6L)  apologies for the trial banners

STR:
1) -1 homescreen: Google feed
2) Click any URL that follows the search.app....URL scheme, e.g. https://search.app.goo.gl/U8Qd
3) Focus is set as default, therefore Google tries to open the URL Focus (via custom tab)
4) Blank page, even if you force to open the URL in Focus (via menu > open in Firefox Focus)

If you, however, click "share" on the Google news story tile, you get the source URL, and trying to copy/paste this URL into Focus directly gives you a dialog telling you to open the link in another app. Clicking ok, ends up opening the URL successfully in Focus.

Expected behaviour: clicking on any Google feed URL should render properly in Focus (even via custom tab).

**Comment by pocmo** [comment]
This seems to work here. @npark-mozilla can you try this on a device?

**Comment by bbinto** [comment]
Pixel (1), OS 8.0.0

**Comment by npark-mozilla** [comment]
@pocmo it works for me too, but I noticed something odd. When I paste the google search URL that I got from the mail app into focus, focus says that it'll open link with google play service. When I press 'OK', then it opens a new tab that shows the story, while showing 'Open link in another app' dialog open in the original tab.  I'm using build 1d2275dcc45d75c46eb57cbbd3ee1d4c70e9dec7, which is from Nov. 20th.

**Comment by bbinto** [comment]
It doesn't happy with all links in my Google feed but I'd say 40% of them behave like I recorded. I can't reproduce yet which sources of web content seem to trigger this behavior.

**Comment by npark-mozilla** [comment]
@bbinto Actually in my case, in your STR step 3, the browser it opens for me is Chrome based.  Under the menu bar, it says 'Powered by Chrome' even though I have set the Focus as my default.  (There is a separate 'Open in Firefox Focus') menu item too.

**Comment by bbinto** [comment]
Actually, @npark-mozilla - you are right, sorry, same for me, it also says "Powered by Chrome", so Chrome is having this issue, however, step 4 still shows a blank page in Focus. Maybe because it can't render the page in Chrome/custom tab from the Google feed, it's also not able to pass a correct link to Focus (via Open with Focus).
