### ISSUE TITLE
Autocomplete: "Learn more" SUMO pages

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1787]
meta: #1766 

Mocks: https://github.com/mozilla-mobile/focus-android/issues/1609#issuecomment-345856966

There are two "Learn more" links in the autocomplete settings screen. We will need SUMO URLs and content for them.

**Comment by liuche** [comment]
Copying this over to #1754 as a dupe and closing this issue.

**Comment by npark-mozilla** [comment]
It's kinda odd to see two different links in the same page points to exactly same SUMO page. Perhaps one can be removed and/or other moved to the top?

**Comment by pocmo** [comment]
@lime124 ---^
