### ISSUE TITLE
Dismiss "history erased" snackbar immediately after leaving the app.

### ISSUE THREAD

**Issue by NightlyNexus** [mozilla-mobile/focus-android#1792]
Once clearing browser history with the trash icon, the app shows the "Your browsing history has been erased." snackbar. This snackbar has a time delay for dismissing.

It'd be nice to have this snackbar immediately dismiss when leaving the app.
If you leave the app and come back a second later, you shouldn't see the snackbar still displaying.

**Comment by bbinto** [comment]
Meta: #1312

**Comment by pocmo** [comment]
Looking at the code and PR we decided that it's not worth adding code (and therefore complexity) fixing this minor issue. Therefore I'm going to close this issue.

As mentioned on the PR: Thank you for contributing and let us know if you are interested on working on other issues.

**Comment by NightlyNexus** [comment]
Cool, makes sense. Thanks for the review!
