### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#18]
Core Ping:
* [x] add core ping
* [x] add missing core ping fields

Events:
* [x] event: bring_to_foreground
* [x] event: send_to_background
* [x] event: (share)
* [x] event: (open...various types)
* [x] event: browse (enter)
* [x] event: browse (intent)
* [x] event: search (type)
* [x] event: search (select)
* [x] event: erase (button)
* [x] event: erase (back)
* [x] event: settings change

Misc:
* [x] Send to production endpoint
* [ ] Enforce limits (-> #428)

**Comment by bbinto** [comment]
currently gathering telemetry requests here: https://github.com/mozilla-mobile/focus-android/issues/59
