### ISSUE TITLE
First run is shown on every run

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#180]
This is probably related to:
c199e81d38e453c6d8d33aa9f3228c64c1843436

I've got no idea what's actually going wrong though.

**Comment by pocmo** [comment]
Could it be that this triggers different results based on which `Context` object is used? Does it work if we make sure that we always use the application context in `Settings`?

**Comment by pocmo** [comment]
Oh, you already found the problem. :)
