### ISSUE TITLE
Error message states that "Safari" can't find server

### ISSUE THREAD

**Issue by kontakt1** [mozilla-mobile/focus-android#1801]
I'm not really sure whether or not this actually qualifies as an issue but it irritates me.
When I enter domorris.de (intended to visit docmorris.de), I get the following (German) message:

"Safari kann den Server nicht finden. Safari kann die Seite domorris.de nicht öffnen, da Safari den Server "domorris.de" nicht findet."
which translates to:
"Safari can't reach the server. Safari can't display domorris.de as it can not find the server domorris.de"
Clearly, I am not using Safari so it should say "Firefox" instead of "Safari" in the message.

I just greped the source code from the master branch but couldn't find (parts of) the string above. So maybe this is not even related to this project.

For what it's worth, I got my copy of Firefox Klar via F-Droid (hopefully not a manipulated copy)

Further facts:
**Version:** Firefox Klar 2.0 (Build #11) /e: just upgraded to v. 2.3 (build #14) but the issue persists.
**Device:** BQ Aquarius U Plus
**OS:** Lineage 14.11 (~ Android 7.11)
**User-Agent:**
Your user agent: Mozilla/5.0 (Linux;
Android 7.1.2) AppleWebKit/537.36 (KHTML,
like Gecko) Version/4.0 Klar/2.0
Chrome/60.0.3112.78 Mobile Safari/537.36
Other HTTP headers Accept:
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language:
de-DE,en-DE;q=0.8,en-US;q=0.6 Host:
duckduckgo.com Referer:
https://duckduckgo.com/ User-Agent:
Mozilla/5.0 (Linux; Android 7.1.2)
AppleWebKit/537.36 (KHTML, like Gecko)
Version/4.0 Klar/2.0 Chrome/60.0.3112.78
Mobile Safari/537.36
UPGRADE-INSECURE-REQUESTS: 1
X-REQUESTED-WITH: org.mozilla.klar

**Comment by mcomella** [comment]
@kontakt1 Can you provide a screenshot of the issue?

Our intuition (via triage) says this is a server issue: we're specifying a user agent close to that of the default WebView and Chrome, which notably has Android in the but the server is parsing it as Safari.

Assuming this intuition is correct, for this bug, you should contact the host of the domain and ask them to correct the parsing but there is nothing to do client-side.
