### ISSUE TITLE
CPU issues

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1802]
Via [GPS](https://play.google.com/apps/publish?account=7083182635971239206#ReviewDetailsPlace:p=org.mozilla.focus&reviewid=gp:AOqpTOHSOpdAM8GdfJ1q4u4RBG8bNh87MaxVcr2WGGJ-vIyXAIJ71EJW6bEPbjTjNe7wO9d98wZ60gw1sjQkkG8) 

Pages weren't loading and the app was overloading my CPU. Everything else on my phone was getting incredibly slow and I would get alerts from my phone saying that Firefox Focus was using up my processor (even when I wasn't using the app). I have since deleted the app and my phone runs much better. I have a samsung galaxy s8+.

**Comment by pocmo** [comment]
Maybe related: #1544
