### ISSUE TITLE
Option to turn off multitasking

### ISSUE THREAD

**Issue by jbreckmckye** [mozilla-mobile/focus-android#1805]
_Added by @bbinto_

**Why/User Benefit**
- Allow users to only focus on one task at a time
- Help users improve their workflow

**What**
- Ability to turn off multi-tasking

**Acceptance Criteria (how do I know when I’m done?)**
- Only one tab is shown to the user
- Probe to inform product how many people turn off multitasking

---
I really liked having only one tab avaialble at the time - as someone who has real problems controlling his internet use, but has to reguarly go online for practical reasons, Focus really helped me stick to the task at hand. I wouldn't be exaggerating to say this feature made a measurable improvement to my quality of life.

Now multitasking is enabled, I find myself slipping back into old, bad habits. Is there a way I can disable this feature? Or is my only recourse to compile a suitable APK myself (something I would find very difficult)?

**Comment by pocmo** [comment]
Thank you for filing this issue.

Currently it is not possible to disable this feature. But you are not the first one interested in keeping a single tab workflow. Initially we were planning to limit the number of concurrent tabs; but with limited resources we decided to not implement that for the first version of multitasking.

**Comment by bbinto** [comment]
@brampitoyo - please let us know what ideas you might have for this.

**Comment by brampitoyo** [comment]
@jbreckmckye I hear you loud and clear! Let me tell you a story behind why we have made this decision.

Our original vision for Focus were for it to be privacy-first, to eliminate distractions, and to be simple to operate. Multitasking is a requirement for all browsers, but it comes at a compromise for this product’s vision. It not only means more potential distractions. It also means less privacy and more surface areas for attack.

Nevertheless, it was a feature that many of our users found to be helpful. We took that feedback and have built it – but only after making two trade-offs that preserved our original vision:

1. Never show a list of tabs when you only have a single tab open (which is most of the time).
2. Make multitasking only accessible via a context menu.

Why did we design multitasking with these trade-off?

1. To encourage a privacy-aware tab habit: only when new links are related to the initial page.
   * If the link you want to open is not related, it’s easy to tap the URL bar and start typing
   * It’s also very easy to tap “Erase”. If you do this, your old data is gone. Privacy preserved.
2. To encourage attentive browsing.
   * The most natural way to open links is by tapping them. They are always opened on the same tab, so your attention is kept on a single tab.
   * New tabs require an extra gesture (tap-and-hold, then select the menu item), so you have to be deliberate about wanting to multitask.

That’s our story so far.

Is it easy to design a control that turns multitasking on and off? I think so. We certainly have a place to put it inside Settings. We need to think of something understandable to say there.

Should we keep multitasking on by default (like our existing state) or off by default (like the initial version of our product)? My initial thought: keep it on, but put it in a prominent place within Settings so it’s easy to turn off.

I hope I’ve helped shine a light on the compromises and dilemma involved behind this feature! I happen to think that our current design has a lot of thought put behind it, but it relies on people having enough fortitude to “say no to tapping the context menu item”.

Ultimately, we can provide a way to multitasking off. But if we do this, would users similarly be tempted turn multitasking back on? The setting menu item will still not be very hidden. If we hide it too much, we risk compromising accessibility.

It’s an interesting area to discuss, and I hope I’ll get to hear your further thoughts on this!

**Comment by jbreckmckye** [comment]
Thanks for getting back to me @brampitoyo.

As it happens, several months in, my habits are actually mostly unchanged. I rarely use the 'new tab' feature, even though it's now available. I'm not sure why - I've also seen the same change when I use Chrome, so there may be some external factor. Maybe because Focus trained me to, well, focus? Or maybe I just learned to close my browser whenever I'm done. The 'clear session' button in FF Focus helps a lot with that.

I do think a settings control would be a good idea, though, and also that single-tasking shouldn't be the default. If it were available I probably _would_ switch it on.
