### ISSUE TITLE
Autofill support for third-party password managers

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1810]
Follow-up from #1545.

This issue is mostly for tracking purposes. On our side there's currently no code work to be done. We are waiting for other providers to let Focus autofill in web content.

Apps:
* [ ] Keeper
* [ ] 1Password
* [ ] Dashlane
* [ ] Keeper
* [ ] Lastpass
  * [ ] Lastpass Beta seems to prompt for autofill with every account on every login page
* [ ] Google Autofill

Checklist:
 * Does it work with the release(!) version of Focus AND Klar?
 * Can we autofill accounts AND save account data?

**Comment by bbinto** [comment]
Can this be closed? I thought it made it into 4.0, or did we only do this for iOS?

**Comment by Sdaswani** [comment]
It’s in 4.0 but I think we kept it open to see how the confirm the different providers are working.
