### ISSUE TITLE
Consider using WebViewProvider for About/Help/Your Rights (/ SUMO pages)

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#182]
Sebastian suggested using the WebViewProvider (in place of the system WebView) for the Your Rights screen.

We actually have multiple such screens (about/help/your rights will be hosted within the app, we also show SUMO pages for "set Default Browser", and also a "learn more" link for telemetry). I think it would be useful to have one Activity implementation, which is able to show all the different pages (i.e. we just need to change the URL and title for every page/screen).

Using WebViewProvider means those screens also inherit Focus's content blocking settings: that's not an issue for the bundled pages (I don't think any of those actually include images). However the SUMO pages do have images, so if Image Blocking is enabled, the SUMO pages looks a bit uglier.

I don't know whether that should be considered a bug or a feature. (Twiddling the web-settings just for this scenario seems like a bad idea, because we don't want to risk accidentally breaking those settings for the actual browser webview.) If it's a bug, it's probably easiest to just use the system WebView for all support pages, if it's a feature then the WebViewProvider is the way to go!

**Comment by pocmo** [comment]
I was mostly interested in using whatever engine is configured for this build variant (WebKit vs. Gecko). But you are right we shouldn't do the setup we do for blocking content. I think we can just ignore this for v1: We are going to use WebView - and we can look at Gecko once we switch. We already regressed the Gecko build anyways.

Having a single activity for all screens that are actually showing a website makes sense. Although we might need to translate some of them ("Your Rights" is always English afaik). Let's file a new issue for that. I'm going to remove the triage label from this one.

**Comment by ahunt** [comment]
One further issue which Sebastian brought up: even if we use a plain WebView, we're still sharing data with the (webkit variant) BrowserFragment - i.e. cache, cookies, webstorage are all shared. Ideally we'd have separate data storage to make InfoActivity and BrowserFragment independent - but WebView doesn't appear to offer any way of doing that.
