### ISSUE TITLE
[breakdown] Rethink/refactor our erase strategy

### ISSUE THREAD

**Issue by jenn-chaulk** [mozilla-mobile/focus-android#1822]
From focus-android created by [mcomella](https://github.com/mcomella) : mozilla-mobile/focus-android#1569  

Splitting from #1472 to avoid scope creep:

> Notes:
> - We have three kinds of erases: erases with a WebView instance, erases with static WebView methods, and erasing the files on disk. I'd suggest merging the last two.
> - We call each of these three at different times for what seem like a lot of redundant calls, e.g. when sessions becomes empty (delete files on disk), onPause and finishing (delete files on disk), when the erase button is actually hit (all three)
> - The methods are confusingly named, especially with the extra layers of abstraction like WebViewProvider
> 
> We should try to centralize the erase so it only happens in one place and perhaps when starting a completely fresh browsing session (since that's the workaround for #1306).
>
> Another note (for another bug?): @pocmo mentions we erase these files whenever a tab is removed (via back) and this seems extreme.

**Comment by mcomella** [comment]
Broken down into the meta bug.
