### ISSUE TITLE
Consider adding screenshot-tests for regression testing

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1826]
[`Facebook's screenshot-tests-for-android`](https://github.com/facebook/screenshot-tests-for-android) is a library for running a test that will take a screenshot of various screens in the app and return no error if all of the screenshots are identical – this prevents accidental UI changes, which is helpful for not regressing polish changes after we make them. If the changes were intentional, you can ignore the errors.

We should consider adding this to our CI suite.

**Comment by mcomella** [comment]
triage: No-Jun agrees this would be nice to have eventually.

**Comment by grubdragon** [comment]
Hey so I'm trying to add this to the gradle file right now

**Comment by Sdaswani** [comment]
Thanks @grubdragon I'm hoping @npark-mozilla can review for you.

**Comment by Sdaswani** [comment]
@boek No-Jun is away, can you evaluate the old PR and see if we even get value from doing this?

**Comment by npark-mozilla** [comment]
This is a good research project to perform, (if we incorporate this to our l10n screenshot tests, then we can identify UI issues right away - which'll be awesome) but currently we don't have a bandwidth to properly work on it at the moment.  @AaronMT , if you have some time, could you assess how much effort we would need to use this?
