### ISSUE TITLE
[SUMO] Add search engine manually feature

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1828]
We're adding a new feature to allow users to manually add a search engine ( #961 ).

We don't link to a specific SUMO page for from this feature, but since this could be a confusing feature (feedback given in-app about the correctness/acceptability of the user-entered search engine url is very minimal), a page could be useful. We'd like to improve this feature in a v2 ( #1561 ) which will add higher-visibility entry points for adding a search engine.

**Comment by liuche** [comment]
Intended to be assigned to @joni but can't find her username in the dropdown for this org.

**Comment by jonisavage** [comment]
https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/add-search-engine

**Comment by Sdaswani** [comment]
@ekager @liuche can one of you put this URL into the product?

**Comment by jonisavage** [comment]
The article is ready. The in-product link will automatically redirect to this: https://support.mozilla.org/kb/add-search-engine-firefox-focus-android

**Comment by liuche** [comment]
This doesn't need to be put in the product.

**Comment by npark-mozilla** [comment]
FYI, I was able to navigate to the article in 2 steps from the help menu.

**Comment by liuche** [comment]
Thanks for the pages, @jonisavage ! One correction, you don't need to hit "back" after saving/deleting engines to save the state - they should be updated as soon as you click the "Save" (or trashcan) button.

**Comment by bbinto** [comment]
@jonisavage we need to add [a bit more explanation](https://github.com/mozilla-mobile/focus-android/issues/1879#issuecomment-349767215) to the SUMO page on how to use this feature, I think the best is to add some example query URLs people could copy and paste:

For example:

https://www.bing.com/search?q=%s
https://en.wikipedia.org/wiki/%s
http://www.imdb.com/find?q=%s
https://bugzilla.mozilla.org/buglist.cgi?quicksearch=%s
https://www.reddit.com/search?q=%s
https://www.youtube.com/results?search_query=%s

**Comment by liuche** [comment]
Probably the "en" of wikipedia should not be included, wikipedia should redirect for you.

**Comment by liuche** [comment]
Reopening because we discovered that this needs more changes due to this feature being confusing for non-power users.

**Comment by liuche** [comment]
Closing, links have been included in the SUMO page. Thanks @jonisavage !

**Comment by npark-mozilla** [comment]
Sumo page looks good to me too.
