### ISSUE TITLE
Creating PDF's

### ISSUE THREAD

**Issue by Achintya999** [mozilla-mobile/focus-android#1829]
There should be an option that helps us to take screenshots or extended screenshots and automatically converts them into PDF's like there is an option in ios browser.

**Comment by mcomella** [comment]
Unfortunately, I'm not sure if it's possible to incorporate this functionality but if you want to take a stab, go for it!

**Comment by NachiketaVadera** [comment]
Hey. I'd like to try and solve this issue!

**Comment by mcomella** [comment]
@NachiketaVadera Thanks for wanting to help out! I don't think we have the cycles to mentor this issue: if you want to work on another Firefox product, I'd recommend checking out our [Hacktoberfest blog post](https://medium.com/firefox-mobile-engineering/participating-in-hacktoberfest-with-firefox-preview-fc68cc318643), which will give tips to contributing to Firefox Preview and the backing library, android-components.

**Comment by NachiketaVadera** [comment]
@mcomella Thanks!

**Comment by Hugoo98** [comment]
bonjour,

Je voudrai essayé de rajouté cette fonctionnalité, dans le cadre d'un cours suivis en licence 3, j'aimerai savoir si cela n'est pas deja fait...

Cordialement

**Comment by Hugoo98** [comment]
Hello,

I would like to try to add this functionality, within the framework of a course followed in license 3, I would like to know if it is not already done ...

cordially
