### ISSUE TITLE
InflateException: Error inflating class org.mozilla.focus.search.SearchEngineChooserPreference

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1831]
From Buddybuild. Happened a bunch of times on Android 6 devices.

[View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/070d31d8728f1ad4bd43a79f5b0633cd)

**Comment by pocmo** [comment]
> Caused by: java.lang.ClassNotFoundException: Didn't find class "org.mozilla.focus.search.SearchEngineChooserPreference" on path: DexPathList[[zip file "/data/app/org.mozilla.focus.beta-2/base.apk"],nativeLibraryDirectories=[/data/app/org.mozilla.focus.beta-2/lib/arm, /vendor/lib, /system/lib]]

**Comment by pocmo** [comment]
I can't see SearchEngineChooserPreference being referenced anywhere.

@liuche Maybe this is already fixed in master?

**Comment by liuche** [comment]
I also don't see any references to SECP, but the most recent crash is from #3542 which went out 2 days ago, so I'll investigate.

**Comment by liuche** [comment]
Last reports are from build 3542 and we are now past 3640, and there are no longer any references in the code base, so closing this.
