### ISSUE TITLE
In API 23, the switch for Autocomplete and Custom URL Autocomplete are not changed even when switched

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1835]
STR:
In android API 23 or below, go to Settings, tap Autocomplete menu
tap either switches in the submenu

Expected:
the switch correctly shows the state
Actual:
always off position

Note: this does not happen in API 25

**Comment by pocmo** [comment]
Duplicate of #1830. There's already a patch waiting for review. :)
