### ISSUE TITLE
When no Custom URL is selected, tapping trash can exits the Custom URLs dialog

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1836]
STR:
Add custom URL
Tap 3-dot menu and select 'Remove'
Tap Trash can icon without selecting custom URL checkbox

Expected:
- Since no url is selected, either the trash can should be greyed out or have no action
Actual:
- exits 'Remove custom URLs' dialog

**Comment by pocmo** [comment]
I followed the behavior of the "remove search engines" screen here.

@lime124 Is this a bug? What's the expected behavior?

**Comment by lime124** [comment]
Nice catch @npark-mozilla ! I didn't call out what should happen in this case and that's my fault. 

In this case we should disable the trash can until at least one item is selected. @pocmo can we make sure this behaviour is replicated for autocomplete too? Thanks!

**Comment by pocmo** [comment]
Okay, I will have a look.

CC @liuche In case you have time to do this for search engines. :)

**Comment by pocmo** [comment]
@npark-mozilla I have a patch for autocomplete in review. Can you file a separate issue for search engines?

**Comment by liuche** [comment]
@npark-mozilla One thing I found was that the trashcan doesn't look disabled when there are no items selected, but it **is** disabled - and maybe this varies by device?

**Comment by mcomella** [comment]
Closed with https://github.com/mozilla-mobile/focus-android/commit/e34247507e9915267c4d63bd73d93a9c46ead51d.

**Comment by mcomella** [comment]
At least, I think this is closed by ^.

@pocmo Can you use the "Closes #xxx" tag so we know which PRs close which issues (as opposed to some PRs which might partially address an issue)? Just in case you're ever not around to close issues.

**Comment by pocmo** [comment]
> @pocmo Can you use the "Closes #xxx" tag so we know which PRs close which issues (as opposed to some PRs which might partially address an issue)? Just in case you're ever not around to close issues.

I don't like auto-closing issues most of the time because landing the code is not always sufficient. I always check if there are additional tasks in the issue. E.g. this one doesn't have all labels set correctly. It's missing the sprint label. :)

**Comment by npark-mozilla** [comment]
@liuche Now I notice that with API 23, the trashcan is not greyed out, but it's disabled. In API 26 prior to the fix, it was actually exiting when pressed. Which I just verified that it's now greyed out and disabled.

**Comment by mcomella** [comment]
>> @pocmo Can you use the "Closes #xxx" tag so we know which PRs close which issues (as opposed to some PRs which might partially address an issue)? Just in case you're ever not around to close issues.
>
> I don't like auto-closing issues most of the time because landing the code is not always sufficient. I always check if there are additional tasks in the issue. E.g. this one doesn't have all labels set correctly. It's missing the sprint label. :)

Sorry, I got a little stressed out on Friday and jumped to a solution before understanding the problem. It makes sense to do a second sweep of the issue and it's not often that someone else needs to close issues for you (and in that case, the reviewer probably has enough context to know if the issue needs to be closed) so keep on doing it if it works for you. :)

**Comment by pocmo** [comment]
> @liuche Now I notice that with API 23, the trashcan is not greyed out, but it's disabled. In API 26 prior to the fix, it was actually exiting when pressed. Which I just verified that it's now greyed out and disabled.

@npark-mozilla Oh, please file an issue for that. That's definitely a bug in my code. @liuche mentioned that in the PR and I don't think I filed that.
