### ISSUE TITLE
Loading bar occassionally disappears during load after deleting data

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1837]
The loading bar will disappear until I try to load the next page.

I can't reproduce it consistently but I've been seeing it for 3-ish weeks and liuche can also see this (I asked via IRC).

@pocmo @ekager Any ideas what could have caused this?

**Comment by pocmo** [comment]
2.5 on Google Play is affected too.

There's some new code in BrowserFragment that does not update the loading bar and background etc. if we haven't been loading before. Maybe that's causing this?

**Comment by nosark** [comment]
@mcomella I would like to take this if it is available :)

**Comment by mcomella** [comment]
@nosark Sure, go for it! Thanks for your help! Please note that this is likely to be a high-priority issue so if it's not fixed quickly, one of the core maintainers may need to take it over from you. Our next release to get this issue in is in January though so you've got a bit of time. :)

Unfortunately, I'm not sure what could be the matter here but you could start investigating by:
- (from pocmo's suggestion) Looking at the git log for `BrowserFragment` - does anything look suspicious? Perhaps back out a changeset and see if it fixes the problem
- Bisecting: check out different changesets on master to find out which reproduce and which don't to narrow down which changeset could have caused the regression (this is less viable because the issue isn't consistently reproducible yet)
- Just reading the code! :)

Let us know if you need any assistance and don't forget you can find us at #focus on IRC generally during PST working hours.

**Comment by nosark** [comment]
ok well i'll get to it and pose any questions in IRC(irc handle: codeasaurusHex).

**Comment by mcomella** [comment]
Discussion regarding some tentative STR: https://mozilla.logbot.info/focus/20171201#c13944153

**Comment by mcomella** [comment]
When I reproduce, I'm also noticing that the URL bar doesn't seem to be changing to the multi-color gradient – this is probably related.

**Comment by pocmo** [comment]
> Our next release to get this issue in is in January (v4.1, see the calendar)

Depending on the fix and timing we should try to uplift to 4.0 though :)

**Comment by npark-mozilla** [comment]
I am not sure whether it's a same bug or not, but on latest FocusWebViewRelease build, the progress bar is only shown covering about 5% of the horizontal length of the screen, then disappears.  I'm on Pixel 2 API 26.

**Comment by nosark** [comment]
@npark-mozilla  I'm pretty sure it is. When the progressView is initialized it starts with a default of 5%. I can recreate the bug everytime now. I am using an original Pixel. I haven't guaranteed every try, but if I set a timer for 1 minute , the problem doesn't persist and the progressView and url bar act as expected. I am looking into the gradient problem with the URL as well because they happen concurrently.

**Comment by nosark** [comment]
The weird thing about the bug is that it can only be reproduced using certain websites.

If I hit "k" and enter to go to kohls.com, then delete, then hit "k" and enter again the loading bar disappears and the gradient on the urlBar doesn't draw.

If I try to do the same thing by hitting "m" and going to microsoftonline.com it acts as expected, no issues.

If I do it with mozilla.org by typing "moz" and hitting enter, it only reproduces rarely...

**Comment by nosark** [comment]
@mcomella I'm fairly certain I resolved it. The default value for this.loading in Session.java was false, Which was causing the disappearing loading bar and background issue. Changing it to true resolves the issue while loading pages. Should I create the pull request or should I find another work around for the issue in case this may cause other problems?

**Comment by nosark** [comment]
sorry for the string of commits, I was updating my fork with the up-to-date-master

**Comment by mcomella** [comment]
Thanks for the investigation!

> There is a race case between session.getLoading().observe(this, new NonNullObserver() {} and SessionCallBackProxy.onPageStarted()
>
> session.getLoading().observe() always gets called before SessionCallbackProxy.onPageStarted() can call session.setLoading(true)
which leads to session.getLoading().observe always hitting the else case(!loading) and causing the deletion of the loading bar and failure to reset the gradient transition and draw appropriately.

I'm not sure I can identify the race you're talking about – can you elaborate? Perhaps by specifying the specific call orders that cause this bug to occur and the call orders where this bug doesn't occur?

To try to find the race, I added log statements to:
- [`getLoading().observe`'s `onValueChanged`](https://github.com/mozilla-mobile/focus-android/blob/6fa67fa349fee6dba037d3537c1fa42229030182/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java#L236)
- [`Session()`](https://github.com/mozilla-mobile/focus-android/blob/6fa67fa349fee6dba037d3537c1fa42229030182/app/src/main/java/org/mozilla/focus/session/Session.java#L42), where the loading initial value is set
- [`SessionCallbackProxy.onPageStarted`](https://github.com/mozilla-mobile/focus-android/blob/6fa67fa349fee6dba037d3537c1fa42229030182/app/src/main/java/org/mozilla/focus/session/SessionCallbackProxy.java#L26) and [`onPageFinished`](https://github.com/mozilla-mobile/focus-android/blob/6fa67fa349fee6dba037d3537c1fa42229030182/app/src/main/java/org/mozilla/focus/session/SessionCallbackProxy.java#L39)

However, the call orders never changed between the bug being shown and the bug not being shown. For example, here is a run where the bug occurred for kohls.com:
```
12-04 17:35:51.810 2937-2937/? D/lol: loading init to false
12-04 17:35:51.983 2937-2937/? D/lol: onValueChanged: false
12-04 17:35:52.174 2937-2937/? D/lol: onPageStarted: http://kohls.com/
12-04 17:35:52.175 2937-2937/? D/lol: onValueChanged: true
12-04 17:35:52.250 2937-2937/? D/lol: onPageStarted: https://m.kohls.com/
12-04 17:35:52.250 2937-2937/? D/lol: onValueChanged: true
12-04 17:35:53.508 2937-2937/? D/lol: onPageFinished: true
12-04 17:35:53.508 2937-2937/? D/lol: onValueChanged: false
```

And for when it did not occur on rockpapershotgun.com:
```
12-04 17:39:34.118 2937-2937/? D/lol: loading init to false
12-04 17:39:34.246 2937-2937/? D/lol: onValueChanged: false
12-04 17:39:34.408 2937-2937/? D/lol: onPageStarted: http://rockpapershotgun.com/
12-04 17:39:34.408 2937-2937/? D/lol: onValueChanged: true
12-04 17:39:34.597 2937-2937/? D/lol: onPageStarted: https://www.rockpapershotgun.com/
12-04 17:39:34.597 2937-2937/? D/lol: onValueChanged: true
12-04 17:39:37.977 2937-2937/? D/lol: onPageFinished: true
12-04 17:39:37.977 2937-2937/? D/lol: onValueChanged: false
```

Besides the URLs, they are identical! This should mean there's no race condition between when these methods are called (though there could be a race for any asynchronous code they start!).

That being said, I noticed a pattern (which may be specific to my device, Pixel API 26 emulator, and internet speed):
- Sites that redirect once or never tend to show this issue (once: kohls.com; never: mcomella.xyz)
- Sites that redirect more than once tend NOT to show this issue (twice: apple.com, google.com; thrice: facebook.com)

However, it's not perfect – I've had runs where kohls.com passed successfully and rockpapershotgun.com has one redirect but still tends to load successfully. **My intuition says there is a correlation between shorter page load time and reproducing this issue** (since more redirects means longer page loads).

---

> Setting the default value to session.loading = true inside of Session.java alleviates the unexpected behaviors.

I can verify this seems to work but I don't clearly understand why that is so let me know if you figure it out and maybe it'd be an appropriate solution!

---

> sorry for the string of commits, I was updating my fork with the up-to-date-master. I still need to add comments back and remove any debug comments.

To update to the latest master, I use interactive rebase: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Similarly, you can use interactive rebase to remove, or squash, any commits that shouldn't be there (like the ones above!). If you join us on [IRC](https://wiki.mozilla.org/IRC), we can help out a little bit with any git questions you might have! We're generally around PST working hours.

**Comment by nosark** [comment]
@mcomella I apologize, race case was not the correct way to describe it. SessionCallbackProxy.onPageStarted() always gets called second to the session.getLoading().observe OnValuechanged. I have done some digging and  OnValueChanged  always beats onPageStarted. Instead of setting the default loading value to true by default, what if we set session.setLoading(true) inside of the SessionCallbackProxy constructor since the page is loading upon the Callback creation?
