### ISSUE TITLE
When deleting custom autocompletion site, app crashes

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1838]
STR:
create a custom autocompletion "somewhere.com", then exit to settings
create another autocompletion site with same name, exit to settings
enter the custom autocompletion settings again, select remove, and check both sites, and press trashcan

Expected:
- Site removed normally
Actual:
- the app crashes.

(This may not be 100% reproducible, but I ran into crash multiple times this way)

**Comment by pocmo** [comment]
> This may not be 100% reproducible

In this case a stracktrace would have been helpful. :)

**Comment by pocmo** [comment]
Okay, found an issue. Patch incoming!
