### ISSUE TITLE
Remove FindBugs suppression annotations in kotlin files

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1839]
[Sebastian recently stopped running findbugs on kotlin files](https://mail.mozilla.org/pipermail/firefox-focus-public/2017-November/000062.html) so we no longer need to suppress FindBugs warnings in kotlin files. Here are all the instances of the annotation we should remove:

```shell
$ find . -name "*kt" -exec grep SuppressFB {} +
./app/src/main/java/org/mozilla/focus/autocomplete/CustomAutocomplete.kt:import edu.umd.cs.findbugs.annotations.SuppressFBWarnings
./app/src/main/java/org/mozilla/focus/autocomplete/CustomAutocomplete.kt:@SuppressFBWarnings("ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD") // That's just how Kotlin singletons work...
./app/src/main/java/org/mozilla/focus/ext/AssetManager.kt:import edu.umd.cs.findbugs.annotations.SuppressFBWarnings
./app/src/main/java/org/mozilla/focus/utils/FileUtils.kt:import edu.umd.cs.findbugs.annotations.SuppressFBWarnings
```

You should remove these annotations and verify your patch worked by running findbugs:
```shell
./gradlew app:findbugs
```

Note that there will be some existing test and screenshots warnings – you can ignore those. Just make sure there are no warnings on kotlin files.

**Comment by siddware** [comment]
Could I work on this? :)

**Comment by pocmo** [comment]
@siddware Yes, absolutely! Let us know if you need any help.
