### ISSUE TITLE
Perhaps a 'Reset to Default' button is needed in Settings

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1848]
Now with many pref values in Settings, it would be handy to create a 'Reset to default' button in settings that resets the value. It'll definitely help UI automation too.

**Comment by pocmo** [comment]
In UI automation you can just clear the settings yourself. ;)

```
    @Before 
    @After // Before/After - whatever you need.
    public void clearSettings() {
        PreferenceManager.getDefaultSharedPreferences(
                InstrumentationRegistry.getInstrumentation().getTargetContext())
                .edit()
                .clear()
                .apply();
    }
```

**Comment by grubdragon** [comment]
Hey @pocmo is this still open?

**Comment by mcomella** [comment]
@grubdragon Should be – we're still a new project so generally if an issue is open, it's something we want! Feel free to add it to the bottom of the bottom of the list. I have some UX concerns (what happens to custom URLs and search engines?) but we can deal with that when we get to it.

**Comment by grubdragon** [comment]
Any guidance I could get here? The settings fragments/etc are pretty hard to understand.

**Comment by mcomella** [comment]
@grubdragon You'll want to look in settings.xml to add the button and respond to the event in SettingsFragment. You can use something similar to the code Sebastian posted above to clear the SharedPreferences. Make sure any data stored outside of SharedPreferences is also cleared!

**Comment by ohodovaniuk1** [comment]
Hey, since this issue has been inactive for a couple of month i would like to work on it. I will submit a pull request for your review and feedback tonight.

**Comment by pocmo** [comment]
Do we really need that?

* For testing there's an other solution (see above)
* And users already have the ability to reset an app to the default state

Reasons for not doing it:
* This is fragile. We are saving things in multiple places and whenever we add new things there's a high chance we forget about this reset button and it breaks (= Doesn't reset everything)
