### ISSUE TITLE
Custom tabs: Show a share button in the custom tabs toolbar

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1871]
meta: #1870

In custom tabs always show a share button in the custom tabs toolbar if the third-party app does not define an action button.

**Comment by mcomella** [comment]
@pocmo How does this interact with the Share menu item we always show for #1358?

**Comment by pocmo** [comment]
I'll redirect the question to @brampitoyo. As far as I remember we didn't discuss changing/removing the menu item in this case.

**Comment by brampitoyo** [comment]
@mcomella The share toolbar button and menu item are two identical ways to get to the same UI. Duplicating this functionality is fine, although I suspect the toolbar button will be much more used because it’s so visible.
