### ISSUE TITLE
Add "edit" option to custom search engine list

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#1881]
Why
- User doesn't have to remove and add a new entry if the current entry is incorret or not working

What
- Add ability to edit a search engine entry

Acceptance Criteria (how do I know when I’m done?)
- User can edit an existing search engine entry
- Probes to track when this event is triggered

-----

This is probably more of a feature, but I often find that when I test out the newly added search engine, I realize I made a typo or missed something, and want to revisit the search engine definition to make a quick fix.  Currently this is not possible, and only way to do that is to remove and retype the definition which is rather cumbersome.

**Comment by bbinto** [comment]
@brampitoyo to keep an eye out for this while improving the custom search engine UI

**Comment by Sdaswani** [comment]
@brampitoyo just getting a status check - is the UX for this work done or do you still need time to finalize mocks?

**Comment by brampitoyo** [comment]
On issue #1956, I proposed adding a selection mode with menu item called “Remove” (garbage bin icon) on long pressing the name of a search engine.

I propose adding a second item called “Edit”, which is selectable only when one search engine is selected on the list.

When tapped, the user is able to edit the search engine name and keyword URL.

<img width="1680" alt="search-engine-selection-mode 2x" src="https://user-images.githubusercontent.com/51007/37884864-8a4d98f2-310e-11e8-8e61-88f4647976bb.png">

**Comment by Sdaswani** [comment]
Thanks @brampitoyo for assigning to yourself until your work is completed!

**Comment by brampitoyo** [comment]
UX work is now finished.

**Comment by kfontecilla** [comment]
Jeff suggests we re-group w/ Barbara to make a decision on custom search engines direction.
