### ISSUE TITLE
Lastpass offers to autofill custom autocomplete url field

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1882]
STR:
Install lastpass, give permission to use autofill for Focus in Settings
Launch Focus, got to Add custom URL dialog

Expected:
No Lastpass presence
Actual:
Lastpass detects the URL field, offers to autofill it from the list of URLs.

Not sure whether this is a bug or not - it does offer you to fill in with some URL that's relevant to you, but I was under assumption that this would only work on browser view.  Thought it is worth mentioning.

![screenshot_20171201-152013](https://user-images.githubusercontent.com/6930774/33502055-af8ec97c-d6ac-11e7-8f83-7614616f111b.png)

**Comment by npark-mozilla** [comment]
![screenshot_20171201-152013](https://user-images.githubusercontent.com/6930774/33502055-af8ec97c-d6ac-11e7-8f83-7614616f111b.png)

One more thing - when a new url is added, the android system asks you whether the new url should be saved to Lastpass.

**Comment by pocmo** [comment]
Fixed in #1866
