### ISSUE TITLE
Lastpass is not filtering the autofill suggestion / only shows first few sites

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#1883]
On Pixel 2 API 26

STR:
Install lastpass, set permission in Android Settings
Install FocusWebViewRelease from BB

I already have autofill information for facebook.com

- Go to facebook.com and tap the login field

Expected:
Lastpass shows facebook related login credentials
Actual:
Lastpass only shows first few sites on my list as suggestions.

It seems that whichever site that I go to, the suggestion lists for autofill does not reflect the site that I am currently in.  The list does seem to change little bit.  I'm not sure whether this is our issue or Lastpass's, but this may not be the positive experience for the user.

**Comment by pocmo** [comment]
This needs to be filed with Lastpass.

**Comment by liuche** [comment]
There's an email thread with @Sdaswani and @npark-mozilla and Lastpass filing this as a bug.
