### ISSUE TITLE
After deleting autofilled username/passwords, lastpass no longer offers to autofill again

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1884]
STR:
Have Lastpass installed and permission set.

- Go to facebook.com or any site that lastpass has the login credentials
- Autofill the login/password field
- Delete the autofilled information
- Tap field again

Expected:
- Lastpass shows autofill suggestions again
Actual:
- Does not show anything

Workaround: refresh the site

**Comment by pocmo** [comment]
This seems to be the normal system behavior. Autofill behaves the same in other native apps.

**Comment by mcomella** [comment]
triage: agree with sebastian
