### ISSUE TITLE
'Custom URLs' menu item inside URL Autocomplete menu needs a unique identifier for UI Test

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1888]
In some locales, like th, zh-cn, zh-tw, the translated text for 'Custom URL' and 'Custom URLs' are identical.  This causes screenshot test to fail since it locates more than one element.  For now the workaround is to use the parent index, but ideally it should come with a unique identifier.

**Comment by pocmo** [comment]
Can you select additionally by type? One of them should be a Switch, I guess?

**Comment by npark-mozilla** [comment]
Actually from the uiautomatorviewer app, they seem identical, since it's not a toggle switch- it's a menu item.

<img width="712" alt="screen shot 2017-12-02 at 1 09 41 pm" src="https://user-images.githubusercontent.com/6930774/33518383-16410a26-d762-11e7-8584-9f4cbc76eaea.png">

**Comment by pocmo** [comment]
Hmm. I see. Those settings views are created by Android. So I would like to avoid that we need to write complex code to modify the default behavior.
I still wonder if we could select the element more reliably? For now maybe just selecting "the last one"?

**Comment by npark-mozilla** [comment]
In UiAutomator, you can you UiSelector.instance(), but with Espresso, I think the only option is to use the index value of the parent.  Luckily in this case, the index values were different.

**Comment by pocmo** [comment]
Espresso has a PreferenceMatchers helper class. Especially withKey() looks interesting:
https://developer.android.com/reference/android/support/test/espresso/matcher/PreferenceMatchers.html

I'll try and let you know if it works.. :)

**Comment by pocmo** [comment]
@npark-mozilla  This seems to work:

```java
        final String key = InstrumentationRegistry
                .getTargetContext()
                .getString(R.string.pref_key_screen_custom_domains);

        onData(withKey(key))
                .perform(click());
```

**Comment by npark-mozilla** [comment]
#1902 created to fix this issue
