### ISSUE TITLE
Use Dark theme color for App bar in Settings

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#189]
I think we used a custom color because of UX but since we're using the dark theme for the menu, it makes more sense to just match it everywhere for now.

I think it's #212121

**Comment by pocmo** [comment]
Using the dark theme and with no custom colors, except the blue accent color, it looks like this:

![settings_dark](https://cloud.githubusercontent.com/assets/89638/23791822/d168275e-0584-11e7-8625-8ad7ca62bec4.png)

**Comment by pocmo** [comment]
@antlam 👍 or 👎 ?
