### ISSUE TITLE
Kotlin build error shown in BB

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1890]
Latest master shows build failure with following reason:

    e: org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration AddActionViewHolder
    Cause: java.io.EOFException
    File being compiled and position: (279,5) in /tmp/sandbox/workspace/app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteListFragment.kt

https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/build/5a223683b708bf000111794d#logs

**Comment by pocmo** [comment]
After rebuilding without cache this is gone.
