### ISSUE TITLE
Lastpass tries to remember the newly added search engine name

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1896]
STR:
- Go to +Add another search engine
- Tap 'search engine name' field and type something
- Press x to cancel 

Expected:
Goes back to installed search engines
Actual
Goes back to installed search engines, and android system dialog shows up saying "Save in Lastpass Beta?"

At first, when tapping search engine name field, lastpass also shows a popup saying 'Please verify your identity'

**Comment by pocmo** [comment]
I recently fixed a similar thing in another screen. We might need to add importantForAutofill="no" to this view.

**Comment by liuche** [comment]
@npark-mozilla if you can verify this on master, I'll uplift it into the 4.0 branch.

**Comment by npark-mozilla** [comment]
@liuche yup looks good on my pixel.

**Comment by liuche** [comment]
Uplifted to release.
