### ISSUE TITLE
Support custom tabs

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#19]

**Comment by pocmo** [comment]
For the record: Focus currently pretends to support custom tabs and will just open the website normally whenever a third-party app opens a custom tab.

**Comment by pocmo** [comment]
#500

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Custom tabs](https://trello.com/c/KP8znwtU/20-custom-tabs)
