### ISSUE TITLE
Match line-height and width for "to be clear" section

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#190]
![screen shot 2017-03-08 at 11 22 19 am](https://cloud.githubusercontent.com/assets/1994820/23719845/b442ed10-03f1-11e7-9bda-4872965b88ae.png)

Two things going on here:

1. the "width" of the text box should be padded like the intro paragraph - 24 px in from the sides
2. the line-height should be the same as the intro paragraph too

**Comment by ahunt** [comment]
![firstrun_footer](https://cloud.githubusercontent.com/assets/1546915/23720154/2fc87544-043e-11e7-863f-0bd609743cb6.png)

(Ughh: I left a hardcoded width on the footer, which made it look weird.)

**Comment by ahunt** [comment]
Should hopefully be fixed now!
