### ISSUE TITLE
Kotlin: treat warnings as errors

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1900]
Kotlin 1.2 introduces a compiler flag to treat warnings as errors: https://kotlinlang.org/docs/reference/whatsnew12.html#warnings-as-errors

I've found this to be a good practice for toy programs in other languages so we should consider it here!

**Comment by pocmo** [comment]
Nice!

Currently I get this weird warning:

> w: [kapt] Sources output directory is not specified for app_focusGeckoBeta, skipping annotation processing
> e: warnings found and -Werror specified

**Comment by siddware** [comment]
@mcomella Thanks, will take a look :)
