### ISSUE TITLE
Consider integrating Leak Canary on local dev builds, potentially BB master builds

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1901]
To catch memory leaks!

We shouldn't do it on BB if we're 1) distributing that to a larger extended audience (in which case, maybe we should ship two) or 2) want the master builds to be representative of Play Builds (e.g. the fewer places we diverge, the less likely we'll find surprising bugs in Play builds but not regular CI builds)

**Comment by pocmo** [comment]
+1 for leak canary and fixing leaks.

Some input:
* Beta builds are distributed via buddybuild to the wider focus team as well as translators and SUMO contributors. For most of them leakcanary might be confusing.
* UI tests are running on debug builds. We do not want leak canary to interfere with them. :)

**Comment by mcomella** [comment]
Dupe #887.
