### ISSUE TITLE
In API 23, the trashcan is not greyed out when nothing is selected.

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1906]
From #1836.  

This can be reproduced on API 23 simulator.  Go to Settings -> URL Autocomplete -> Custom URLs, and select 'Delete' from More Options button.

**Comment by mcomella** [comment]
triage: let's try to get this into the release.

**Comment by liuche** [comment]
@npark-mozilla if you can verify this on master, I'll uplift it into the 4.0 branch.

**Comment by npark-mozilla** [comment]
@liuche With the autocomplete, now the trash can icon is properly greyed out. But I just realized that I forgot to mention the same bug with Remove search engines dialog.  Will create a new bug for it.

**Comment by liuche** [comment]
Uplifted to release.
