### ISSUE TITLE
Syntax check on custom autocomplete string may be needed

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#1907]
Currently custom autocomplete accepts any strings, like "hello" as autocomplete sites. when a non-url string is autocompleted on URL bar it uses the search engine, which is not a problem and probably a feature too.

But when the user type "www." prefix, it also uses the custom autocomplete strings as well, like "www.hello" which causes a "server not found" error. 

Possible feature would be that when the string does not have the URL syntax, it should not appear when typing "www." prefix

**Comment by mcomella** [comment]
triage: if I understood correctly, we're going to wait and see what kind of comments we get.
