### ISSUE TITLE
Title String truncated on some locales on Autocomplete_Custom_URL_Remove_Dialog screen

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#1910]
Seen in Italian and in French. Currently looking at other locales because probably happens on others too. FWIW since I can read French I can confirm this looks pretty bad 
![autocomplete_custom_url_remove_dialog_1512492140902](https://user-images.githubusercontent.com/399020/33629794-311b0c70-d9ba-11e7-927c-c37ba2288862.png)
![autocomplete_custom_url_remove_dialog_1512493552935](https://user-images.githubusercontent.com/399020/33629795-3132752c-d9ba-11e7-95de-9303db04074f.png)

**Comment by Delphine** [comment]
German, Arabic... all locales are affected including en-US!
@bbinto Could you help set the appropriate flags please? 
![autocomplete_custom_url_remove_dialog_1512498582982](https://user-images.githubusercontent.com/399020/33630213-67c0b62a-d9bb-11e7-834f-a0f4a5818e24.png)

**Comment by npark-mozilla** [comment]
So this was caused by the screenshot test not waiting until the menu dialog is completely drawn. It's one of those expanding dialog, and isDisplayed() passes even when it's partially displayed.  I just found out that using device.waitForIdle() fixes it.  

So, this does not happen in real product. Will fix the screenshottests soon

**Comment by Delphine** [comment]
That's really good to know, thanks for the update No-Jun (also, CC @flodolo so he knows his locale is OK)

**Comment by pocmo** [comment]
@npark-mozilla But even without the menu showing on top it looks like some of the strings in the background are truncated....? I'm not sure what to do about it though. Changing the source string to something shorter so that the translations are shorter too (but this has to be in one of the next releases)?

**Comment by pocmo** [comment]
>  I'm not sure what to do about it though.

We might not need to set a title at all (or a "subscreen") and instead show a contextual selection bar when the user is selecting items, see:
https://developer.android.com/design/patterns/actionbar.html
(-> UX, @lime124)

**Comment by npark-mozilla** [comment]
An example of what @pocmo mentions is https://npark-mozilla.github.io/ast/images/phoneScreenshots/Autocomplete_Add_Custom_URL_Dialog_1512520744956.png

But didn't we kind of agree that truncation is acceptable for devices with small screens? But I agree that actionbar does look better.

@Sdaswani, @bbinto , does this truncation look like a release blocker to you?

**Comment by Sdaswani** [comment]
If it was a blocker yesterday for @bbinto , it's probably still a blocker today? Since we can't shorten the string until the next release (i.e., new localization), can we fix this up today @pocmo @liuche @mcomella ?

**Comment by pocmo** [comment]
> But didn't we kind of agree that truncation is acceptable for devices with small screens?

Yes, for the notification. It might still be okay here - but we (or more: UX / product) should state that explicitly here. :)

**Comment by npark-mozilla** [comment]
@Sdaswani Ah, this issue was initially raised because the screenshots showed this ghost-like overlap of texts. that was because of timing of screenshots.  After fixing the screenshot test, it uncovered much less-severe truncation of the title text as shown in the link I pasted above.

**Comment by bbinto** [comment]
Before deciding, need some confirmation:

To clarify, @npark-mozilla this *only* happens on devices with small screens? Can you specify at which width that problem starts: I could look into Google Play Store what percentage of users are affected.

Also, this is the worst it can get, correct?  https://npark-mozilla.github.io/ast/images/phoneScreenshots/Autocomplete_Add_Custom_URL_Dialog_1512520744956.png

Can you share how the exact same screen looks on a Samsung Galaxy S7 or S8, or Google Pixel?

My two cents, this is a new feature we are introducing and promoting everywhere, anything that looks broken is not acceptable. Truncation is more acceptable than the issues we've encountered via the screenshot tool.

**Comment by npark-mozilla** [comment]
So in pixel 2, which has 5.1" screen, the truncation still happens a bit:
![screen](https://user-images.githubusercontent.com/6930774/33669815-76a93624-da71-11e7-9cca-31929d0216b8.png)

**Comment by bbinto** [comment]
Ok, it's not a release blocker, but I'd like @antlam and @lime124 to think about the suggestion @pocmo mentioned [here](https://github.com/mozilla-mobile/focus-android/issues/1910#issuecomment-349607956).

**Comment by antlam** [comment]
I noticed this on iOS as well, where `< URL Autocomplete` buts right up against `Custom URL` too.
