### ISSUE TITLE
Trash can icon active when no search engine are selected

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla-mobile/focus-android#1917]
Devices:
Nexus 5 (Android 6.0.1)
Nexus 6 (Android 7.1.1)
build: Focus 4.0 Beta Build #3691

Steps to reproduce:

Launch Focus and go to Settings.
Click default search engine name, and in 'Installed search engines' dialog, click more options button and select remove.

Expected results:
Remove search engines dialog shows up. The trash can icon is inactive when no engines are selected.

Actual results:
The trash can icon is active when no engines are selected. See screenshot:
![screenshot_20171206-160115](https://user-images.githubusercontent.com/24588037/33665333-3ff1fed0-da9f-11e7-9785-4c6ef7502eb4.png)

**Comment by npark-mozilla** [comment]
We have #1915 to work on this issue.
