### ISSUE TITLE
When changing orientation in any Settings submenu, the app exits to main settings UI

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1924]
In API 26 Pixel 2, if you go to any of the sub-dialog from settings, and change the orientation from landscape -> portrait and vice versa, it exits to the main settings menu instead of changing orientation.

**Comment by pocmo** [comment]
Aye, I stumbled upon this code today:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/activity/SettingsActivity.java#L37-L39

We always replace all fragments in SettingsActivity.onCreate(). We only want to `add` here and only if there is no fragment yet.

**Comment by npark-mozilla** [comment]
This doesn't look like a regression - so it's probably not a release blocker, but would be pretty awesome if it gets uplifted to 4.0 as well.

**Comment by npark-mozilla** [comment]
Actually we did with the language selection, that dialog is affected too :)
