### ISSUE TITLE
Search engine form error handling: Use setError() instead of Snackbar

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1927]
I think we should use setError() on the input fields (to show the error in context) instead of showing a snackbar when entering invalid search engines.

Example from the material guidelines:
![image](https://user-images.githubusercontent.com/89638/33674249-3a18d046-daaf-11e7-8022-9fc1327ca797.png)

**Comment by antlam** [comment]
+1 I was just going to post this :)

**Comment by pocmo** [comment]
Seems like there's another one now: #1939. As there's already working happening on #1939. I'll close this one as duplicate of #1939.
