### ISSUE TITLE
Add additional validation (just making a network request?) to add search engine

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1936]

**Comment by Sdaswani** [comment]
Yes @mcomella let's look for a 200. Do what is _reasonable_ about disabling the 'Save' button / UI while the network request is in flight and time limit it (e.g., max 5 seconds waiting on the request).

**Comment by liuche** [comment]
Going to switch to #1939 because it's a slight dependency.

**Comment by pocmo** [comment]
Are you really sure that's a reason to block the release? This looks like we are rushing something that has a bunch of side effects, e.g.:

* Redirects!
* Search engines do fancy things based on the client accesing them (user agent etc.) - They don't want you to scrape search results.

**Comment by Sdaswani** [comment]
@pocmo both of those are real risks, but I'd rather they are false negatives (i.e., don't report back 200) blocking the experience rather than leading to the white screen of nothingness (which makes Focus look totally broken).

**Comment by pocmo** [comment]
Agreed. Although we are not fixing the random redirect to a white about:blank here.

**Comment by Sdaswani** [comment]
@pocmo wouldn't we get a redirect at first and then say it isn't valid? So not sure how we would redirect to a random white screen. But we realize there is a risk that we get a 200 to a page the user doesn't expect (i.e., non search page).

**Comment by liuche** [comment]
Talked to @antlam about the UX, and the outcome is:
1) User fills out all the fields, but uses something like imdb.com/%s (which is incorrect)
2) Click "Save"
3) Show a spinner (for feedback)
4) If not successful, display the error message "Server not found" under the search string entry (this string is already shipped with Focus). (If successful, just add search engine and show confirmation)

**Comment by Sdaswani** [comment]
I like the spinner and the error message. The error message captures the 200 check and if the device doesn't have a connection.

**Comment by Sdaswani** [comment]
Cleared by security

**Comment by liuche** [comment]
@npark-mozilla I'm especially interested in how this tests on oreo - I thought I had an infinite timeout on the oreo emulator, but didn't have a physical device.

**Comment by npark-mozilla** [comment]
It seems to work well on actual device too - I can't make it fail.  It does complain if there is a suffix after %s like %s&where=aaa but this is probably expected.

**Comment by mcomella** [comment]
>  It does complain if there is a suffix after %s like %s&where=aaa but this is probably expected.

#1960
