### ISSUE TITLE
Add new "Learn more" string for Add Search Engine info button

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1941]
I re-used the string in #1935 but we should add a new one.

**Comment by liuche** [comment]
Actually, not going to export these strings because @lime124 might want to revisit this UX.

**Comment by lime124** [comment]
@brampitoyo - can you work with @BrianNJones to propose an appropriate string. Thanks!

**Comment by brampitoyo** [comment]
@mcomella @liuche Can you describe what you mean by “‘Learn More’ string” in the context of this info button?

Are we referring to the button description that would appear to screen-readers? Or are we replacing the ‘i’ icon with a text? Or are we looking to take out the ‘i’ icon and instead have a “Learn more” link somewhere down the page?

**Comment by mcomella** [comment]
@brampitoyo iirc, we have a link with the text, "Learn more", next to the Add Search Engine button. Instead of creating a new string (so that it gets retranslated because context matters), I re-used an existing string (which is bad because translation context matters) - this bug was to use a new string with the same english translation, "Learn more".

The way I filed it was primarily an engineering issue but it looks like Tif might want to update the UX here, so we may not want to do the engineering portion.

**Comment by BrianNJones** [comment]
@mcomella I'm curious re: your thinking that we need a new string here. I think it's contextually appropriate/clear/unambiguous here, and the linked-to SUMO page hits most of the expected "Learn More" content (context of use/instructions for use/examples). We could follow the Firefox "More" convention, though.

**Comment by mcomella** [comment]
Sorry if I'm being confusing: I don't think we need a new english String
– "learn more" is fine.

From an engineering perspective, it's bad practice to re-use an already
translated string in a new location because the context where that
string is used can make the translation incorrect. In this case, I re-
used the already translated string because we were past String freeze.
For correctness in non en-US locales, we should get this string re-
translated.

If the UX of this view doesn't need to change (and if not @brampitoyo,
please say so!), this is purely an engineering issue.

**Comment by BrianNJones** [comment]
@mcomella, thank you for the clarificaiton! I have learned more.

**Comment by mcomella** [comment]
> But I think that reusing “Learn More” is ok in this specific instance.

Then let's reduce our workload and close this. :)
