### ISSUE TITLE
SearchEngineManager.restoreDefaultSearchEngines() should use apply() instead of commit()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1944]
In `SearchEngineManager` we call `commit()` on the `SharedPreferences.Editor`:

https://github.com/mozilla-mobile/focus-android/blob/c3437f8618d8fbaa5a2ceb5dc50f7f9d7b760959/app/src/main/java/org/mozilla/focus/search/SearchEngineManager.java#L357-L359

Instead we should call `apply()` to avoid blocking the main thread. The changes will be updated in memory and be visible to callers immediately.

**Comment by Securter** [comment]
Hey @pocmo it's my first time contributing here, I've added a commit to my forked repo Is there anything else needed or I can submit a PR referencing this issue?

**Comment by pocmo** [comment]
@Securter Thank you for your help. Yes, please go ahead and submit a PR. :)
