### ISSUE TITLE
Create pull request template

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1950]
GitHub allows us to create a template for pull requests.

I like the one Firefox iOS uses a lot:
https://github.com/mozilla-mobile/firefox-ios/blob/master/PULL_REQUEST_TEMPLATE

Especially the checklist is great. In the list of pull request you'll instantly see the state of a PR (e.g. "2 of 6").

(For creating an issue template see #1465)

**Comment by Securter** [comment]
Hello, Can I work on this @pocmo ?

**Comment by pocmo** [comment]
> Hello, Can I work on this @pocmo ?

I think for this one the team first needs to decide what we want to add to this template. Is there anything specific you wanted to add?

For now it might be better to pick a different issues from our 'help wanted' or 'first good issue' list:
* https://github.com/mozilla-mobile/focus-android/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
* https://github.com/mozilla-mobile/focus-android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
