### ISSUE TITLE
Unable to add another search engine (InputEditText instantly loses focus)

### ISSUE THREAD

**Issue by Jacquester** [mozilla-mobile/focus-android#1953]
When trying to add a new search engine, the TextInputEditText for the search engine name and Search string instantly loses focus upon selection.

Device: Vodafone power tab 10
Android version: 5.1
Focus version: 4.0 build # 11

I'm pretty sure this is a device specific problem but could someone running an android 5.1 device confirm this ?

To replicate:
* go to settings > Search > Add another search engine
* Select either Search engine name or Search string to use

Expected: The hint animates out of the way allowing us to type into the TextInputEditText
Actual: The hint animates out of the way and instantly returns when focus on the TextInputEditText has been lost

Edit:
Here is a video better describing the bug: https://youtu.be/Sl7SG4JXCiI

**Comment by pocmo** [comment]
Thank you for the detailed report - especially the video.

@Jacquester Does this happen when adding an autocomplete domain too?

**Comment by Jacquester** [comment]
> @Jacquester Does this happen when adding an autocomplete domain too?

Funny enough no?

I just tested this on another device running android 5.1.1 "half" of the problem was found, I'll upload a video of that too since I have no logical way of explaining the behaviour of it :)

**Comment by Jacquester** [comment]
Here is the second video I made from another device that I "borrowed" from a family member:
https://youtu.be/nFz3H0S8WhY

Note that I am explicitly closing the keyboard to show the strange behaviour of the TextInputEditText that instantly drops focus. I'm starting to think this also has something to do with issue #1923 with the keyboard never dissapearing.

This video was tested on a device running android 5.1.1 making me think this might be a bug regarding all (or at least most) android lolipop devices

**Comment by pocmo** [comment]
@Jacquester Thanks for testing this. In the second video it looks like this only happens for the first time you click on one of the input fields. Can you still enter a search engine or are you complicated blocked?

@bbinto Potentially a release-blocker? What do you think?

**Comment by Jacquester** [comment]
> it looks like this only happens for the first time you click on one of the input fields
Rather say it only happens the first time I click on it and the keyboard is not shown.

I'm still able to add a search engine on the second device, the first one is completely blocked

**Comment by liuche** [comment]
I think this might be fixed with the #1939 PR actually - there's a small change to change to panAdjust rather than panResize.

**Comment by bbinto** [comment]
ok, let's confirm if #1939 fixes it, otherwise this might have to become a release blocker, unless it's very isolated to a rare device/setup.

**Comment by Jacquester** [comment]
I can confirm #1939 will solve this, changed the manifest to use panAdjust instead of panResize and it solved it. Thanx @liuche

**Comment by liuche** [comment]
Closing as resolved by #1939. Thanks for verifying for us, @Jacquester!
