### ISSUE TITLE
Custom search engine validation requires %s at the end of the string

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1960]
While many urls include search params as get query args, and thus this is possible to do, it won't always work (I don't have examples atm) and it requires the user to piece apart a query string on a mobile device, e.g. copy-pasta ebay: 

https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313.TR12.TRC2.A0.H0.Xstar+wars.TRS0&_nkw=star+wars&_sacat=0

Requires you to change it to:

https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313.TR12.TRC2.A0.H0.Xstar+wars.TRS0&_nkw=star+wars

(I removed the `_sacat` param, I hope it wasn't important!)

**Comment by mcomella** [comment]
Here's the problem regex: https://github.com/mozilla-mobile/focus-android/blob/e208a4d7e0ebc469d6036ba81065d38fad52d2ee/app/src/main/java/org/mozilla/focus/utils/UrlUtils.java#L58

**Comment by sv-ohorvath** [comment]
If I understand right, adding a custom search engine should work just by copy-pasting the URL, without adding the %s anymore. E.g https://bing.com/search?q=
If this is correct, do I reopen this bug or should I create a new one?
It's still currently asking to match the example and it wouldn't add the search engine until you add the %s.

**Comment by pocmo** [comment]
@sv-ohorvath Previously the %s was required to be added the end, e.g.:
```https://bing.com/search?q=%s```

Now you should be able to use it anywhere in the URL and we should fill in the parameter correctly, e.g.:
```https://bing.com/search?q=%s&param=something.else```

**Comment by sv-ohorvath** [comment]
Ok, thank you!

I verified with Bing and just replacing the search term with %s works (using a search results URL): https://www.bing.com/search?q=%s&qs=n&form=QBLH&sp=-1&pq=%s&sc=8-2&sk=&cvid=6835725AAD464FF8B8AEDD2A0C71E1EF 

Or, adding the ?q=%s in Bing's homepage URL: https://www.bing.com/?q=%s&toWww=1&redig=0E5D234F228145FFA6DEF2FEC81354D1

My 2 cents: this method of adding search engines is too complicated for inexperienced users, maybe it can be simplified. If it's not done right, the search doesn't work or just keeps returning the same search (based on the URL copied).
But, also, they might stick with Google which they know, and not want to add other engines.

**Comment by pocmo** [comment]
Yeah, there's an ongoing discussion about how we could make this easier and how much we want to invest into improving this.
