### ISSUE TITLE
Custom search engines aren't selected after creation even though they can't be used until selected

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1962]
after a user creates a search engine, we don’t select it for them. It’s seems wrong to do so but feels weird that I can’t use this search engine unless it’s the default so what’s the point of adding it?

antlam and liuche agreed on slack.

**Comment by pocmo** [comment]
Yeah, for now auto-selection might be a good idea. In the long run there was some UX discussion about adding something to quickly search with other search engines too (like with the quick search bar in fennec).

**Comment by liuche** [comment]
@lime124 says that this is supposed to happen.

**Comment by vickz84259** [comment]
Would like to work on this if no one is

**Comment by mcomella** [comment]
@ekager @boek ^

**Comment by ekager** [comment]
Hey @vickz84259 , you are welcome to work on this! Let's get @brampitoyo (UX) to confirm the new behavior before you start :)

**Comment by brampitoyo** [comment]
@ekager @vickz84259 Yes. I can confirm that we should set the newly-created custom search engine as a default, right after you finish adding it.

**Comment by sblatz** [comment]
@bbinto Do you want Telemetry to be updated in any way for this? In other words: the default search engine will now be set every time the user adds a new search engine, thus pinging two Telemetry events. Would you prefer that it _not_ ping the "change default search engine" Telemetry event?
