### ISSUE TITLE
Revisit context menu in SUMO page "Open link in new tab"

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1964]
In #1957 we show the basic Focus context menu when long-pressing a url so users can copy, and then paste into their "add search engines". This was a bandaid solution I came up with with @antlam, and we need to revisit because the "open links in new tab" definitely doesn't work, and "share" doesn't really make sense.

![screenshot_1512693023](https://user-images.githubusercontent.com/1082253/33748085-6ef85030-db7b-11e7-9585-7a4d6838ff16.png)

**Comment by antlam** [comment]
@liuche There's a "disabled" state that @ekager used for the Add to Homescreen item in the main menu. The easiest place to start would be to inherit that "disabled state" UI for the items here that the user cannot press.

**Comment by mcomella** [comment]
Dupe was a P2.

**Comment by brampitoyo** [comment]
This issue may be resolved when we find a better way to show in-content links #2107.

**Comment by vesta0** [comment]
@brampitoyo was this resolved/can we close?

**Comment by brampitoyo** [comment]
Yes. Let’s close this issue.
