### ISSUE TITLE
Fix PMD rule violations and let PMD break the build

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1969]
I noticed that we do run PMD on taskcluster but a rule violation does not break the build. It's also run by sputnik (but only on *new* code); however we have accumulated 212 rule violations already.

To make PMD useful we should let it break the build. So depending on the violation we should:

* Fix the issue
* Ignore the rule for this part of the code
* Update our configuration to not use rules that are not important to us

PMD report (Link expires 2017-12-15T08:25:15.406Z):
https://public-artifacts.taskcluster.net/IgnNFf1gSl6csTpUrAjvmQ/0/public/pmd/pmd.html

Break the build:
https://github.com/mozilla-mobile/focus-android/blob/e79c081104f741bafa75d30ff3b0729a0daf9b1c/app/build.gradle#L380

Configuration:
https://github.com/mozilla-mobile/focus-android/blob/master/quality/pmd-rules.xml

**Comment by vladioan3** [comment]
Related to what rules should remain, in my opinion we should keep the following set:
- basic;
- braces;
- clone;
- unusedcode(UnusedLocalVariable, UnusedPrivateField, UnusedPrivateMethod);
- imports;
- unnecessary(UnnecessaryConversionTemporary):
- empty(EmptyCatchBlock);
What do you think about that @pocmo ?

**Comment by pocmo** [comment]
@vladioan3 What's your reasoning for removing the others from the configuration? And how many violations are there currently for your set?

**Comment by vladioan3** [comment]
The idea is to run the PMD task on every PR to check the code against the ruleset. If we keep only a part of the ruleset we can get rid of issues that are straigth forward to fix. The other rules that I was thinking to remove would require more work for fixing the issues that are found, maybe refactoring some parts of code, reduce complexity of some methods and classes, in conclusion more time to take care of them. Maybe after no issues are found running the PMD we can add more rules to the set and fix the issues that appear.

For this configuration we have only 17 PMD rule violations.

**Comment by vladioan3** [comment]
I have found a new way to suppress PMD warnings without deleting rules from the xml file.

**Comment by pocmo** [comment]
With new code being Kotlin and old code getting migrated when touched I do not think we need PMD anymore.
