### ISSUE TITLE
Search engine validation: Maybe do HEAD request

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1970]
As we are not interested in the websites content and just look at the response code it might be worth doing a HEAD request which will not return the response body.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

**Comment by mcomella** [comment]
This didn't work on iOS – @boek what was the reason?

**Comment by mcomella** [comment]
via Slack, boek says some servers reject HEAD requests, like MDN.
