### ISSUE TITLE
ManualAddSearchEngineSettingsFragment: Add 'final' keyword to constant

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1972]
A good first issue for new contributors.

SEARCH_QUERY_VALIDATION_TIMEOUT_MILLIS in ManualAddSearchEngineSettingsFragment should be final:
https://github.com/mozilla-mobile/focus-android/blob/e79c081104f741bafa75d30ff3b0729a0daf9b1c/app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.java#L42

**Comment by Jacquester** [comment]
If no one wants this in about a day I'll take it :)
