### ISSUE TITLE
Search engine validation: Set user agent

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1973]
We should set a user agent for the validation request.

By default HttpUrlConnection uses on my device:

`User-Agent: Dalvik/2.1.0 (Linux; U; Android 8.1.0; Pixel XL Build/OPP6.171019.012)`

**Comment by 7a6ac0** [comment]
How about the following code?

```
HttpURLConnection connection = null;
connection.setRequestProperty("User-agent", "USER_AGENT_YOU_NEED");
```

**Comment by mcomella** [comment]
@7a6ac0 I think this particularly code snippet would throw a NullPointerException but yes, `setRequestProperty` is the way to go. Note that the header is "User-Agent", not "User-agent".

I'm sure that's not the only place we use the user agent header name in the code so we should make it a static final variable for use everywhere.

@7a6ac0 Feel free to write a patch for it! :) Thanks for the note!

**Comment by 7a6ac0** [comment]
@mcomella Thanks for your response. I use the user agent which generated by WebViewProvider, but there's a problem. It must to open the webview once to set up the variable. Any suggestion to fix that?
[https://github.com/7a6ac0/focus-android/commit/2775bfaef25fa95cfbaba345a3d6e699fef97273](url)

**Comment by mcomella** [comment]
> I use the user agent which generated by WebViewProvider, but there's a problem. It must to open the webview once to set up the variable. Any suggestion to fix that?

@7a6ac0 It looks like this is a `WebViewProvider.buildUserAgent` is a static method – can you call that rather than accessing the cached value?

**Comment by 7a6ac0** [comment]
@mcomella In `WebViewProvider.buildUserAgent` code, it use the WebView's default user agent by called the method `settings.getUserAgentString()`.
So, if we call `WebViewProvider.buildUserAgent`, it need to create a WebView to get the WebSettings class.
The user agent generated by `WebViewProvider.buildUserAgent` is `Mozilla/5.0 (Linux; Android 7.1.2) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36`
Now I comment out the code `settings.getUserAgentString();` to `""`, so the user agent is became `Mozilla/5.0 (Linux; Android 7.1.2) Focus/4.0`

How about replace `settings.getUserAgentString();` by a hard code?

**Comment by mcomella** [comment]
@7a6ac0 Ah, we need the WebView instance to get WebSettings – thanks for the info!

In this case, I think it's a good idea to replace `getUserAgentString` with a hard-coded one _because we're not actually using a WebView_. The question is: what should that user agent string be?

Can you use [this article on MDN explaining User-Agent formats](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) and our WebView user agent to come up with one? If this is too tedious, you can ask me to suggest one too. :) Thanks a bunch!

**Comment by 7a6ac0** [comment]
@mcomella I use the default webview UA string, and also refer to the [site](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent).

Now we can set User-Agent header into `HttpURLConnection` by calling `WebViewProvider.buildUserAgent`.

What do you think about this?
https://github.com/7a6ac0/focus-android/commit/07aeeaa7e319d113cbf28249517ea82b1a37b058

**Comment by mcomella** [comment]
> @mcomella I use the default webview UA string, and also refer to the site.

I recognize the intent (websites shouldn't be changing their behavior based on browsers) but changing the user agent for the whole browser to be a static value is a larger discussion – for example, major desktop browsers update their user agents with their current versions and there must be a good reason for that.

My expectations for this bug are that we take the "platform user agent" in `buildUserAgentString` where WebView can pass in it's UA and we can pass in a different value for HTTPUrlConnection requests.

**Comment by 7a6ac0** [comment]
@mcomella Thanks for your response. I think the solution is that we pass in hard-coded UA for HTTPUrlConnection request, and `buildUserAgentString` still remain the same.

Is it right?

**Comment by mcomella** [comment]
Yeah, that sounds fine.

I was originally thinking we should a UA substring with the browser and thus we should re-use `buildUserAgentString` but looking at the UA, it doesn't seem like much, if any of it, is usable.

Don't forget to look [at the UA article on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) to figure out what an appropriate user agent might be.
