### ISSUE TITLE
Changing orientation while entering search engine details wipes entered data

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1974]
This is on Pixel 2, Android O
STR:
Go to Settings -> Search Engine List -> Add Search engines
Enter details of new search engine
without saving or exiting, with the entered data shown, change orientation

Expected:
- Entered data survives
Actual:
Both fields are wiped clean

This bug is probably uncovered by #1924 fix.  Not sure this is a release blocker, but it would make users quite annoyed if they ever change the screen orientation for whatever reason during the add search engine step. @bbinto , @Sdaswani thoughts?

**Comment by npark-mozilla** [comment]
This also happens with search engine deletion selection as well.

**Comment by Jacquester** [comment]
The Auto-complete URLs deletion section is also affected by this

**Comment by Sdaswani** [comment]
Annoying but not a blocker.

**Comment by Jacquester** [comment]
Take the following with a large bag of salt:
I belive this should be resolved by #1945 (SettingsFragment being responsibe for showing sub-screens, like ManualAddSearchEngineSettingsFragment).

Can anyone with a more knowledge confirm this ?

**Comment by noloman** [comment]
I would like to work on this issue. Is it possible?

**Comment by Sdaswani** [comment]
yes @noloman , thanks for contribution - we will review your PR soon.

**Comment by noloman** [comment]
thank you guys!

**Comment by bbinto** [comment]
part of #1561
