### ISSUE TITLE
Search engine validation: Follow redirects

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1976]
We should allow HttpUrlConnection to follow redirects:

https://developer.android.com/reference/java/net/HttpURLConnection.html#setInstanceFollowRedirects(boolean)

Currently we accept a redirect as successful. That should be okay in most cases. I wouldn't be surprised if there are some http->https redirects that will end up in a 404 though.

**Comment by mcomella** [comment]
This is where we create the connect where we should follow redirects: https://github.com/mozilla-mobile/focus-android/blob/d60f63538b24f69771b3fc5fea532105da124d3d/app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.java#L221

**Comment by mohamadLy** [comment]
I can take this if it's alright with you.

**Comment by grubdragon** [comment]
Oh dang! @mohamadLy I didn't read your comment and went ahead and fixed it. Sorry :sweat:
