### ISSUE TITLE
Add to home screen broken on android 8.0.0

### ISSUE THREAD

**Issue by blokeley** [mozilla-mobile/focus-android#1978]
Add to home screen is not working on android 8.0.0 (Google Now launcher or KISS launcher).

Focus version 2.5.

It might be because android ingnores the add to home screen broadcast in android 8.0.0 but I could add shortcuts to the home screen before installing the KISS launcher.

Is anyone else having this issue and is there a workaround?

**Comment by pocmo** [comment]
It seems to work fine here on a Pixel XL, Default Launcher, Android 8.1.

Do you see the "Add to home screen" dialog? After clicking "Add" do you see a system dialog asking you whether you want to add the icon automatically?

**Comment by blokeley** [comment]
I press "Add to home screen", get the dialog asking what to call the shortcut, press Add, and nothing happens.

I see the same with the chrome browser.

Neither work with either the stock Google Now launcher, or the KISS launcher.

Strangely, both browsers did make shortcuts ok before I started alternating between the launchers.

The phone's a Google/LG Nexus 5X if that makes any difference. Maybe I should close this issue and raise one with Google for android.

**Comment by blokeley** [comment]
I think it's a launcher issue or something deeper in chrome so will close this issue
