### ISSUE TITLE
Campaign tracking

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#198]
We are going to use our own telemetry system for Focus (#18). However for campaign tracking we might still need to use Adjust.

**Comment by pocmo** [comment]
@bbinto Who can tell us what we need to do for campaign tracking?

**Comment by bbinto** [comment]
That'll be Fabio/Mike, stay tuned, I reached out to them

**Comment by st3fan** [comment]
@pocmo Campaign tracking will happen automatically when we integrate Adjust. I think you can simply follow their instructions at https://github.com/adjust/android_sdk

* We need to do at least https://github.com/adjust/android_sdk#basic-setup to get campaign tracking (attribution). If this happens every time the app starts up, we may want to keep a preference around to record that we have done the attribution and that we do not have to setup Adjust again.
* The docs at https://github.com/adjust/android_sdk#session-tracking describe how to do *Session Tracking* on `onResume()/onPause()` but I think that is the part that we want to skip and handle with our own telemetry.

**Comment by pocmo** [comment]
I added the SDK, tokens and enabled referrer tracking (release version only). Now we only need to somehow test that.

**Comment by pocmo** [comment]
There's a way to trigger the install referrer manually:
https://github.com/adjust/android_sdk#ts-broadcast-receiver

**Comment by pocmo** [comment]
I did a last test today and landed some additional patches. This is now ready to ship.
