### ISSUE TITLE
Indicate that "work is happening/please wait" after the user saves a new search engine

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1980]
After the user hits "Save" for adding a search engine, we should indicate and provide feedback (not with a snackbar) that there is work being done in the background.

Something we didnt have time to get to in the first version. I think @mcomella started with a system spinner. At the very least we can papercut out some sort of "please wait" indicator here :)

cc @lime124

**Comment by liuche** [comment]
Here's the current state.

![screenshot_1512766093](https://user-images.githubusercontent.com/1082253/33786981-20749086-dc20-11e7-862f-72e41ff4fe9e.png)

**Comment by lime124** [comment]
assigning to @brampitoyo for a UI proposal

**Comment by brampitoyo** [comment]
I looked through the Material Design Guidelines and found no specific recommendation for using a progress bar after submitting the form (it’s practically the action users do when they tap “Save”).

Our current state looks fine, but to improve its appearance, I recommend putting the circular progress underneath the grey line, and giving it a 32dp top margin.

<img src="https://user-images.githubusercontent.com/51007/37008894-30b9c484-2149-11e8-9036-12f534adf4c7.png" width="320">

(If our “Save” button is a FAB, let’s say, then there’s prior art. We can for example [integrate the circular loader into it](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B6Okdz75tqQsdk1oMG9KY2pCcms/components-progressactivity-typesofindicators-circular-wfab-xhdpi-003.mp4)).

**Comment by brampitoyo** [comment]
I did an Invision test of a few different progress bar transitions:

https://mozilla.invisionapp.com/share/3SG846BQ8MY

In order of appearance:

1. Existing solution (progress bar appear underneath text field)
2. Grey out the page (no progress bar shown)
3. Grey out the page (progress bar shown)
4. Do nothing (no progress bar shown)

I learnt a few things from going through the transitions (however imperfect) on my phone:

* The keyboard is always minimised after you tap “Save” and the progress bar is shown. Cover-ups will never happen, even on landscape and devices with shorter form factors.
* If the time it takes to check the server is short, then the blue progress bar flashes very briefly on the screen – very jumpy appearance. In some cases, you just notice something odd happening before it throws you an error (or a success).

My recommendation is to go with option 2, based on this hypothesis:

* On average, most users will not need to wait more than 1 second. Showing a progress bar will make things look jumpy.
* On the rare occasions that users will need to wait, they will still need to know that the page cannot be interacted with.

If my hypothesis is wrong (ie. most users wait a long time), we should definitely show the progress bar. Go with option 3, or stick with option 1 that we already have today.

Hope this clear things up!

**Comment by sblatz** [comment]
My findings are similar to @brampitoyo's. The check is extremely short, and thus the progress bar looks jumpy. I will be moving forward with option 2 (greying out the page with no progress bar).

**Comment by brampitoyo** [comment]
@sblatz If the server is taking too long, I wonder if – along with greying out the page – we should show a “cancel” button in the middle of the grey-out overlay? The idea being, in most cases it’s not required, but when you do need it, it’s very important. So it needs to be really prominent.

**Comment by sblatz** [comment]
@brampitoyo after how long should the "cancel" button be displayed? If we show it every time, we'll have the same issue we have now where it just flashes really quickly.

**Comment by brampitoyo** [comment]
@sblatz You’ve made a really good point about only showing the “Cancel” button after a certain wait time has elapsed.

Let’s set the “Cancel” button to only show up 1 second after the grey-out. It will prevent the flashing effect, but as soon as the wait time is unbearable (and research has shown that users have particularly low tolerance for waiting), the way out is shown immediately.

**Comment by sblatz** [comment]
@brampitoyo I found a way to just disable the textfields (not the whole screen i.e. the menu bar is still active). Because of this, I think it's okay to not display a big cancel button in the middle of the screen (as the user can clearly press the "X" in the top left). 

After one second of waiting, the loading indicator will be displayed to make it even more clear to the user that we're still trying to validate the URL (though most users will never see this). A demo of my implementation can be found below. Let me know if you think this should be any different!

![url demo](https://user-images.githubusercontent.com/4400286/43411221-6931e9f6-93de-11e8-98bc-b66c9f384088.gif)

**Comment by brampitoyo** [comment]
> I found a way to just disable the textfields […] the user can clearly press the "X" in the top left

@sblatz This is a superior solution to disabling the whole screen, while using our existing close action to cancel. Great work!
