### ISSUE TITLE
Write script that compares imported locales with locales.py

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1981]
To prevent something like #1975 in the future:

Let's write a script that checks if all the locales in the repo (values-*/strings.xml) are listed in [locales.py](https://github.com/mozilla-mobile/focus-android/blob/master/tools/l10n/locales.py) ... either in the release list or in the screenshot list.

Ignore non-language folders like `values-sw600dp`.

Let's run this at least on taskcluster.

**Comment by pocmo** [comment]
@mastizada Maybe something for you. :)

**Comment by pocmo** [comment]
To clarify:

* values-*/strings.xml exists but no entry in locales.py -> Error
* Entry in locales.py exists but no values-*/strings.xml -> Warning (or ignore this case if too complex)

**Comment by mastizada** [comment]
Yes, assign it to me, a bit busy these days, will try to solve till next Sunday.
Are non-language folders (`values-sw600dp`) fixed? - If yes, will write them in a list to ignore.
