### ISSUE TITLE
Custom search engine icon should be consistent with default icons

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1982]
![screenshot_20171208-115358](https://user-images.githubusercontent.com/1994820/33782744-bd28a58c-dc0e-11e7-9024-dbf98c4cab96.png)

The icon is a different size than the rest, and the single character isn't centered :)

**Comment by mcomella** [comment]
To fix this bug, please center the icon and make it the same size as the rest.

**Comment by tvalle** [comment]
I'm working on this issue, going to send a pull request soon

**Comment by brampitoyo** [comment]
@tvalle How are you going with fixing this issue? Are you ready to submit a pull request?

**Comment by tvalle** [comment]
@brampitoyo Sorry, since I last pushed something it had an error on ktlint. Now it should be fine:

see: [2026](https://github.com/mozilla-mobile/focus-android/pull/2026)

**Comment by boek** [comment]
@brampitoyo Since we're not using these icons anywhere we tossed the idea around of just using a generic icon to designate a custom search engine. This will simplify the code and this feature quite a bit. We can always re-visit if we surface them anywhere else. What do you think?

**Comment by brampitoyo** [comment]
@boek If it will simplify our code, I support the idea. We can simply use a generic search icon (https://design.firefox.com/icons/viewer/#search) in place of the coloured square with initial.

What do you think?

**Comment by kai-chi** [comment]
@tvalle, are you working on it? if not, can I take it?
