### ISSUE TITLE
Indicate "selected state" of default search engine more obviously

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1983]
Currently we're using a different background color to indicate which search engine a user has "selected" from this list.

![screenshot_20171208-115358](https://user-images.githubusercontent.com/1994820/33782971-a2c355ce-dc0f-11e7-8a4b-266e4016baf9.png)

As an idea, maybe we could also add an icon and even leverage the secondary text line in the list item to show "Default" like we do in Fennec? It would make it more obvious and also help with possible accessiblity issues.

Here are some examples that I'm referring to. We would obviously be using radio buttons instead of checkboxes to better reflect the selection relationship (cannot select multiple default search engines).

![](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B0iWdZjcphyMQ3VmdnV6bXVtQzQ/components-lists-keylines-two6.png)

![](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3eTQ1MUVSWWpWdHc/components-lists-keylines-three3.png)

@lime124 tthoughts?

**Comment by Jacquester** [comment]
>  and even leverage the secondary text line in the list item to show "Default" like we do in Fennec?

And if it's not a default search engine use the secondary text to display the search string since there is no way of viewing it after it has been saved ?

**Comment by ioana-chiorean** [comment]
Hey @grubdragon check this ticket if u started working on a patch for the search engine selection

**Comment by lobontiumira** [comment]
I think this issue is resolved now.
This is the behavior on RC 93.1.1:

![Screenshot_2021-10-04-16-48-58-293_org mozilla focus](https://user-images.githubusercontent.com/40694158/135863365-760a46df-c1e2-44f7-92df-09d75ea39777.png)
