### ISSUE TITLE
Url live validation check for imdb.com/%s passes, but is not a valid search engine

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1985]
It looks like our http validation substitutes "test" for %s to check for validity, and adds the engine if it's not an error (400+ response code).

However, in the case of imdb.com/%s (and possibly other sites), imdb.com/test *is* a valid site, but it's not a valid search query (e.g. imdb.com/movie will 404).

We should switch our test query to something else more randomized.

**Comment by Jacquester** [comment]
We could possibly generate a random string of lets say 5 characters long before making the network request ?
The possibility of that random string actually being a web page (similar to imdb.com/test) should be very small especially if we increase the length of the random string

**Comment by Jacquester** [comment]
`    private static String getRandomString(int length) {
        StringBuilder builder = new StringBuilder();

        for (int i = 0; i < 10; i++) {
            builder.append((char) (65 + (Math.random() * 31))); // generate random character
        }

        String str = builder.toString();
        Log.d(LOGTAG, "getRandomString: generated string: " + str);
        return builder.toString();
    }`

I just slapped this together and it seems to be working pretty good. Would you mind if I send a pull request ?

**Comment by liuche** [comment]
Let's keep it simple, it doesn't need to be random every time, because for the purposes of verifying a url, it there isn't a difference between websites (e.g., if you use a randomized string for imdb, changing it has no effect on whether wikipedia is more or less likely to resolve it).

Let's just not use something that everyone is going to use like "test" :) Event "test9428" would be fine!

**Comment by Jacquester** [comment]
Makes sense, mind if I take it ?

**Comment by mcomella** [comment]
@Jacquester Sure, go for it! Please post a pull request when you're ready! Thanks for your help!
