### ISSUE TITLE
Search bar pops up address autofill options every time app is opened

### ISSUE THREAD

**Issue by supnah** [mozilla-mobile/focus-android#1993]
Every time I open the android app, before taking any action, it pops up the address autofill options, which is never something i will need to do in Focus. I can't figure out what changed or if this is a setting from another app or android setting, but seems not at all useful, and intrusive/bad for UX. See attached img.

Using a Pixel 2 on Android 8.0.0. Focus 2.5 (Build #13311312) 

Let me know if I can provide any other information. 

![screenshot_20171208-210336](https://user-images.githubusercontent.com/1953038/33808442-37a119a6-dd9b-11e7-8739-890d3de01f59.png)

**Comment by ekager** [comment]
Hi @supnah , thanks for filing! Which autofill service are you using?

**Comment by supnah** [comment]
I have my addresses entered into Chrome and Firefox autofills. That's all I can think of. I could try deleting them from one or the other and see if that has an impact.

**Comment by bbinto** [comment]
@supnah - have you upgraded to Focus 4.0 yet? Is this still happening?

**Comment by supnah** [comment]
Hi - I have upgraded, and it does not seem to be happening anymore. Thank you.

**Comment by mcomella** [comment]
WORKSFORME.
