### ISSUE TITLE
Feature Request: Blocking images

### ISSUE THREAD

**Issue by JayVii** [mozilla-mobile/focus-android#2001]
blocking images is a really neat feature, when it comes to limited data plans (or for privacy reasons, when websites work with [Web beacons](https://en.wikipedia.org/wiki/Web_beacon)). I haven't seen a feature request for this yet (if i missed it, i am sorry to bother).

proper Firefox for Android does have this feature (you can even choose to only block images on cellular data, there).
As I understand it, Focus' purpose is to have a private and super fast webviewer for quick searches and the like. So it usually is the default browser, from which you can pass a website to your main browser (eg Firefox for Android) if needed. However, when trying to save cellular data or if you are on a very slow connection, it doesn't make sense to open up a website in Fx Focus, as it has to download all images.

it would make sense to implement a similar feature as in Firefox for Android, here as well.

**Comment by liuche** [comment]
@bbinto to look at Fennec studies on "blocking images".

**Comment by grubdragon** [comment]
Hey can I take this up?

**Comment by mcomella** [comment]
@grubdragon We're not sure we want to implement this yet (Barbara is looking into it) so please hold off on implementing this – thanks!

**Comment by grubdragon** [comment]
Okay cool I'll hold my horses :#

**Comment by bbinto** [comment]
see also #188 for status/progress

**Comment by orschiro** [comment]
+1 on this! Have below RSS feedburner page where I want to block images to make it fit my screen:

http://feeds2.feedburner.com/stadt-bremerhaven/dqXM
