### ISSUE TITLE
Refresh gesture from the top breaks Google maps

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-mobile/focus-android#2007]
STR:
1. Open Google Maps or probably any map portal.
1. Try to pinch to zoom/unzoom the map or slide down with your finger to go north on the map.
1. Icon appears on the top and page refresh is triggered.

**Comment by bbinto** [comment]
Could you please let us know what version of Firefox Focus you are using?

**Comment by bbinto** [comment]
Are you on a buddybuild? We have not disabled this feature in the debug/BB.

**Comment by liuche** [comment]
We've turned off swipe-to-refresh for release builds in order to clean up the function more - this will be present in Buddybuild dev builds though.

**Comment by mcomella** [comment]
@MikkCZ Please see Barbara's questions above.

**Comment by MikkCZ** [comment]
Yes, I have buddybuild 13481449.

**Comment by pocmo** [comment]
In the meantime we disabled pull to refresh in all builds. We are tracking issues with this feature in #1776.
