### ISSUE TITLE
Issues with random.org (redirecting)

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2008]
Via GPS

"It doesn't work for all websites. After turning on all trackers, m.timesofindia.com kept redirecting to random.org site."

**Comment by mcomella** [comment]
Some thoughts from triage:
- IP address of random.org in the code?
- DNS hijacking

**Comment by mcomella** [comment]
FYI: this was also filed for Focus Android on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1435492

**Comment by bbinto** [comment]
more here https://twitter.com/BhashkarSharma/status/961555651678932992

**Comment by Sdaswani** [comment]
@ekager when you have some cycles away from GV hacking, this may be something to investigate for an hour or two to see if you can suss out anything.

**Comment by chulliyilmahesh** [comment]
happens to me too with firefox focus. 
open the app google news, then open the link from times of india or economic times from the feed then it will redirect most of the time. firefox focus if my default browser.

**Comment by steptowards** [comment]
I tried and it was successfully reproduced. I started with India's news website TOI and after many attempts was able to reproduce it with an article from another news website Economic Times. 
Here is the [link](https://economictimes.indiatimes.com/small-biz/startups/newsbuzz/big-churn-at-rivigos-top-floor-as-the-logistics-firm-faces-management-crisis/articleshow/63164666.cms) to the article.

A 26 seconds video recorded for the same can be found on [this imgur link](https://imgur.com/VYZBF58).

This issue is consistently occurring and can be replicated with some other articles too. Did a search for random.org (and its IP) in the entire source code and found nothing. Random.org is hosted behind Cloudflare network and they do not allow opening websites via IP address. 
Needs further investigation.

Firefox Focus 4.0.2 on Redmi device (Also occurring on other devices I tried)

**Comment by pocmo** [comment]
@steptowards Thank you! This is super helpful. With your link I am able to reproduce this! 🎉

**Comment by pocmo** [comment]
Some observations:

* (1) The redirect only happens after I start scrolling the page
* It happens even if I disable all content blockers in settings.
* If I load the page, open the menu and press "reload" then it does not happen if I start scrolling the page. That's pretty weird. It almost looks like this only happens after a fresh load without cache?

**Comment by steptowards** [comment]
@pocmo These observations are correct.

- Redirection to random.org only starts when we start scrolling. 
- On pressing reload, and scrolling the redirection is not happening. 
- On cleaning history using the trash icon, opening the link and then scrolling, redirection is happening.

**Comment by bbinto** [comment]
Awesome investigation @steptowards, what are the next steps to fix it?

**Comment by steptowards** [comment]
**Found the issue (possibly)**

Indian news websites (TOI and ET) are probably loading an iframe which has an advertisement for a Cricket score app known as [Cricbuzz](http://www.cricbuzz.com/).

When a user scrolls [this](https://economictimes.indiatimes.com/small-biz/startups/newsbuzz/big-churn-at-rivigos-top-floor-as-the-logistics-firm-faces-management-crisis/articleshow/63164666.cms) page (on cache-cleared session), a call to method [shouldOverrideUrlLoading](https://github.com/mozilla-mobile/focus-android/blob/8ed26d723f44b500b230b5cfb73d9bafb46bd9c4/app/src/webview/java/org/mozilla/focus/webview/FocusWebViewClient.java#L218) results which tries to handle unsupported URL (The [comments](https://github.com/mozilla-mobile/focus-android/blob/8ed26d723f44b500b230b5cfb73d9bafb46bd9c4/app/src/webview/java/org/mozilla/focus/webview/FocusWebViewClient.java#L231) in the method are very helpful.).

The unsupported URL passed to this method is : 
`intent://www.colombia-sdk.com/dl#Intent;scheme=http;launchFlags=0x10000010;package=com.cricbuzz.android;component=com.cricbuzz.android/com.til.colombia.dmp.android.PsA;S.browser_fallback_url=http%3A%2F%2Frandom.org;S.id=be28ffe7-cc5e-478e-993b-05ff87cf3cc0-10o78;end`

The browser_fallback_url value contains random.org, which gets opened using this [handleUnsupportedLink](https://github.com/mozilla-mobile/focus-android/blob/8ed26d723f44b500b230b5cfb73d9bafb46bd9c4/app/src/main/java/org/mozilla/focus/utils/IntentUtils.java#L91) method.

There are two things which are still not understood (need help here) : 
- Despite installing Cricbuzz app for testing, the fallback URL (random.org) was opened and NOT the dialog to switch app.
- On reloading the article, redirection to random.org does not happen.

Unrelated note : Cricbuzz's parent company Times Internet is a subsidiary of Times of India Group which owns TOI (Times of India) and ET (Economics Times). This could be why the bug reports came mostly from India and also when users where browsing news articles on these two sites.
The JS loaded on ET was from domain static.clmbtech.com, which on Google search returns [this website](https://www.colombiaonline.com/). The top 2 publisher platform on its homePage are TOI and ET. The invalid URL intent also has _colombia_ in it.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Focus Nightly build 360530508 with GV 99.0a1-20220221094019 from 2/21, with Oppo Find X3 Lite (Android 11).
