### ISSUE TITLE
Dismissing "Add search engine" leaves keyboard visible

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2010]
STR:
- Settings -> Google default -> Installed search engines -> Add another...
- Click text field to raise keyboard
- Hit X

Expected: keyboard closes
Actual: keyboard stays open

Like #2011.

**Comment by Jacquester** [comment]
Related to #1923

**Comment by shahbazahmed1269** [comment]
@mcomella I would like to work on this issue and #2011 if no one else is working on them. I think just closing the keyboard in `onPause()` lifecycle callback would fix this issue.

**Comment by mcomella** [comment]
@shahbazahmed1269 I think this is being worked on in #2020. If not, Jacquester may also have some commits that fix this.

Perhaps you'd like to tackle #1193?
