### ISSUE TITLE
Dismissing "Add custom URL" leaves keyboard visible

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2011]
STR:
- Settings -> URL autocompelte -> custom URLs (must enable autocomplete first) -> Add custom URL
- Hit X

Expected: keyboard closes
Actual: keyboard stays open

Like #2010.

**Comment by Jacquester** [comment]
Related to #1923, I solved it by closing the keyboard in onPause() but the commits were later reverted

**Comment by Jacquester** [comment]
> Sorry about that!

No need to be sorry lol, it's your code I'm the one intruding

I just added the code from my old commits and it would seem it solves this and #2010. Although I think there should be a better way to approach the problem

**Comment by mcomella** [comment]
@Jacquester Great – do you think you could open a new PR with your old commits? I'll let you know if we envision a different way of solving the problem.

> No need to be sorry lol, it's your code I'm the one intruding

You don't need to feel like you're intruding – we want you to be welcome in the codebase and if there's anything that we're doing to make you unwelcome, please let us know what we can do better! It's true that Mozilla has the ultimate say about what gets into the codebase but we consider ourselves to be more like shepherds trying to do our best for our users rather than strict owners of the code! :)

**Comment by mcomella** [comment]
> do you think you could open a new PR with your old commits?

Please note that #2020 may also address this issue so it may conflict there – sorry about that! Don't be afraid to open issues if you have some idea of how to fix the problem and we'll help you work through it.

@Jacquester Please let me know if you want help finding another issue to hack on.

**Comment by Jacquester** [comment]
> Please note that #2020 may also address this issue

Coolness thank you :)

> @Jacquester Please let me know if you want help finding another issue to hack on.

I think I'll continue trying my luck with # 1974

**Comment by noloman** [comment]
hi! sorry but what's the status of this issue?

**Comment by Sdaswani** [comment]
I think it’s fixed by https://github.com/mozilla-mobile/focus-android/pull/2020 - right @ekager?

**Comment by ekager** [comment]
Yes #2020 will fix this

**Comment by noloman** [comment]
good thanks 👍

**Comment by ekager** [comment]
Fixed by #2108

**Comment by sv-ohorvath** [comment]
I think #2108 only fixed the keyboard to appear/disappear in the Add search engine menu and not in the Custom URL too. Still repro on Beta v5.0. 
Device Pixel XL (Android 8.1.0)

**Comment by ekager** [comment]
Looking into this today and will try to have a fix for 5.0

**Comment by sv-ohorvath** [comment]
Verified on Beta v5.0 build.
Devices: 
Google Pixel (Android 8.1.0)
Sony Xperia Z5 Premium (Android 6.0.1)
