### ISSUE TITLE
Implement a revised, comprehensive erase strategy

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2015]
Breakout from #1569. Notes:
- There's an open bug for having an UNDO option: #467

**Comment by bbinto** [comment]
Needs to break it down further

**Comment by Sdaswani** [comment]
@boek @colintheshots @ekager can you discuss if this and the related #1569 is still a live issues? I think it's actionable without any product or UX since it seems like improving our erase architecture.

**Comment by vesta0** [comment]
Addressed here: https://github.com/mozilla-mobile/focus-android/issues/3201
