### ISSUE TITLE
Autocomplete is not so privacy-wise.

### ISSUE THREAD

**Issue by YouMustKnowPrivacyIsOurRight** [mozilla-mobile/focus-android#2021]
[|  Search or enter address ]

_tap_

*www*

instantly become "www.google.com".
Can I disable it? Because Google never care your privacy.
If Firefox Klar is a privacy browser, why google is appearing here?

And when I input

*www.tor*

Nothing is returned as autocomplete.
Oh come on. Just add "www.torproject.org". Or don't you like Tor?

**Comment by mcomella** [comment]
> Can I disable it?

Settings -> URL Autocomplete -> Toggle Autocomplete

Note that in the latest version you can enable custom autocomplete for sites of your own choice independently of our built-in autocompletes.

> Because Google never care your privacy.
> Just add "www.torproject.org". Or don't you like Tor?

Our autocomplete lists come from the Alexa top 500 sites on the internet and unfortunately, adding websites individually could be potentially insecure (e.g. if the original host of a domain is sold). Do you have an alternative list of sites you would propose adding to autocomplete?

fwiw, we are considering Tor intergration (#66), but it's not practical while we're working on WebView so we're considering if we could replace it with GeckoView (#13).

This bug doesn't seem actionable so I'm going to close it but if you have further suggestions (or a list of sites we could add!), please let us know!
