### ISSUE TITLE
Not able to store 4th level domains in autocomplete list

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2022]
Via GPS

hello, in the URL autocomplete menu I'm not able to store a 4th level domain (at most only 3rd level). thanks

**Comment by mcomella** [comment]
I can't reproduce: I can add blogs.msdn.microsoft.com to custom autocomplete (assuming this is what they mean by 4th level domain).

Perhaps the address this person specified fails our validation check (e.g. is a redirect, they don't have a network connection, etc.).

@bbinto Are there any action items here?

**Comment by grubdragon** [comment]
I checked with blog.msdn.microsoft.com, it seems to work for me. @bbinto could you say what your UR was.

**Comment by bbinto** [comment]
I can't seem to find the GPS post anymore, so I'm fine with closing it!
