### ISSUE TITLE
Window no longer gets blanked out in multitasking view

### ISSUE THREAD

**Issue by samirm** [mozilla-mobile/focus-android#2028]
I don't know which update changed this (maybe the one that enabled multiple tabs), but when entering multitasking view, the Focus window is no longer blanked out and you can see the contents of the page you were on.

I don't know if this is a bug or a feature, but whatever the case may be it would be nice to give the user the option to change this behaviour to what it was before.

**Comment by Jacquester** [comment]
Is your stealth enabled ?

Stealth can be found in settings under Privacy

**Comment by samirm** [comment]
Oh wow, I'm surprised I miss that. Thank you!
