### ISSUE TITLE
Research Paper on Ad Blocking Countermeasures

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#2030]
Someone should read the paper [here](homepage.divms.uiowa.edu/~mshafiq/files/adblock-ndss2018.pdf) and evaluate whether we can apply anything to Focus.

**Comment by vesta0** [comment]
@Sdaswani do you remember which paper you shared here? I want to make sure that I've seen it.

**Comment by Sdaswani** [comment]
Wow @vesta0 that was so long ago that I don't remember.

Well, web search worked: http://homepage.divms.uiowa.edu/~mshafiq/files/adblock-ndss2018.pdf

https://techcrunch.com/2017/12/27/thousands-of-major-sites-are-taking-silent-anti-ad-blocking-measures/
