### ISSUE TITLE
Move CI setup from Buddybuild

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2032]
Since BB is discontinuing their Android support on March 1st, we need to look into alternatives.

**Comment by npark-mozilla** [comment]
It seems that the options are either we use TaskCluster, or use 3rd party services like CircleCi

**Comment by mcomella** [comment]
[I copied Sebastian's focus-public@ message](https://mail.mozilla.org/pipermail/firefox-focus-public/2018-January/000083.html) about what we still run on BB:

Luckily we moved a lot of our tasks from Buddybuild to taskcluster and
Travis for other reasons already. However there are some things left on
buddybuild exclusively:

*UI tests*
We are using buddybuild to run our UI tests on various device
configurations. Buddybuild didn't operate their own device farm. Instead
they used the Firebase Test Lab for Android [2]. I have been using the
Device Lab from my machine in the past. From that I feel like it would be
fairly easy to trigger the UI tests on Firebase Test Lab from taskcluster
for master builds. However we would need an official Test Lab account and
some budget (but not more than what we used via buddybuild already).

*Test build distribution*
Internally we are distributing builds to two groups via buddybuild: The
Focus team (engineers, product, design, QA, ...) gets builds for every
master change and the L10N/SUMO teams get master builds twice a week. This
one is more complicated to replace. In the long run my goal here is to ship
Nightly builds (from taskcluster) via the Alpha channel on Google Play.
However this requires a bit more work and it might be worth talking to the
release engineering team whether we can get something up in Q1. If not then
we should look for alternatives. There are a bunch that do distribution but
we might need building and signing too.

All other tasks like building PRs, running code quality tools and unit
tests, ... are not performed by buddybuild anymore.

**Comment by npark-mozilla** [comment]
I just realized TC also builds PRs after reading above.  If so, then perhaps TC can trigger UI Test on Google firebase directly with the compiled apk, rather than let buddybuild do it.  However, following questions should be addressed:
- How easy would it be to see the test results for each run?  (visible in TC/Treeherder?) Including screenshots/videos for debugging
- Would we be able to easily go through the history of test results?
- Would it be easy to change the test configuration for each PR? (i.e. device/API sim/real device) Somehow we need to send those parameters to Google each time the test is run.

**Comment by Sdaswani** [comment]
David Burns responded:

> 
>     Sebastian mentioned that currently BB is mainly used for distribution / UI testing for Focus Android. I mentioned my questions in the github issue (https://github.com/mozilla-mobile/focus-android/issues/2032) they are:
> 
>         How easy would it be to see the test results for each run? (visible in TC/Treeherder?) Including screenshots/videos/logs for debugging
> 
> 
> This is really easy. A push would have a link to build artifacts which screenshots/videos/logs are. This would be no different to how reftests work.
> 
>         Would we be able to easily go through the history of past test results?
> 
> Treeherder shows things chronologically so I am not sure I understand this question. You just go back through time on treeherder
>  
> 
>         Would it be easy to change the test configuration for each PR? (i.e. device/API sim/real device) Somehow we need to send those parameters to Google each time the test is run, if external test service like Google Firebase is being used.
> 
> 
> TC uses a yaml file for configuration that people can use and update themselves.

**Comment by npark-mozilla** [comment]
Great, so once the taskcluster/treeherder is setup, above concerns would be trivial.  So as long as TC can run tests on android API 22-25 sim, then that's all good.

**Comment by npark-mozilla** [comment]
Get Google testcloud account which can be used when TC starts a build job
Add Google credentials to Focus secret folder so TC can pull the credentials and log into google (I noticed Sebastian already obtained secrets service for storing credentials (https://bugzilla.mozilla.org/show_bug.cgi?id=1409353))
Modify the taskcluster.yml so:
installs gcloud and gutil API from Google
When the build is completed, send the test execution command to Google TestCloud. For 
Example from buddybuild:  gcloud --format="json" firebase test android run --app="5a552ebf7722040001523108/app-focus-webview-debug.apk" --test="5a552ebf7722040001523108/app-focus-webview-debug-androidTest.apk" --results-bucket="buddybuild-gcloud-testlabruns" --timeout="30m" --no-auto-google-login --test-runner-class="android.support.test.runner.AndroidJUnitRunner" --device="model=Nexus5X,version=23" --device="model=Nexus9,version=25" --device="model=sailfish,version=25" --device="model=sailfish,version=26”
We probably won’t be able to have a GUI-style changes to setup API and device config, one probably would need to configure the .yml file manually, which isn’t too much of a big deal at the moment
Wait until the response from Google is received
Access TestCloud folder to retrieve the artifacts, including test results, videos, logcat
Somehow parse the test_result_0.xml file to Pulse format so it can be published on treeherder (script maybe?)
Send the results to treeherder, including the links to the logs and videos
Send the results to Github 
Talk to the Treeherder team, file a bug to publish the test results in treeherder, 
Somebody should monitor our expenses with Google.

**Comment by npark-mozilla** [comment]
Sebastian suggested that we can skip treeherder for now, and just attach the reports to the taskcluster job.
