### ISSUE TITLE
Does our "Focus as default browser" target users intentionally setting the default?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2035]
We use the default browser metric for a lot of things so we should make sure it's reliable.

For example, in newer versions of Android, when users install a new browser, they're presented with a dialog: "Which app would you like to open in?" The user just installed Focus and is likely to click Focus. However, in newer versions of Android, this (unintuitively to me) sets the browser **as the default** when perhaps a user only intended to try Focus once and it's set as the default, affecting our metrics. If they don't click many links, they may not even know they're using focus.

Is there a way we can determine a user intentionally set the app as a default if we don't do so already? e.g. if we cross-reference our "default browser" metric with users who actively use Focus.

That being said, maybe our current metrics are good enough.

**Comment by pocmo** [comment]
I think the answer to your question is: Yes, we track users that intentionally set the default browser: Either in the system settings or as "Always open" when clicking a link.

We are asking the system to return the default activity for "http://www.mozilla.org" - if this returns our package then we are the default browser. If not then it either returns another browser or the activity chooser.

**Comment by mcomella** [comment]
> or as "Always open" when clicking a link.

On my personal device (GS5, Android 6?) I actually don't get a prompt to "Open once" or "Always open" – this is the key point I'm trying to make. When you click to open in an app from a prompt, it automatically acts like you pressed "Always open", meaning it gets set as the default even if the user didn't intend for it to be.

Does this happen on other Android devices as well? If not, I think we can close.

**Comment by pocmo** [comment]
> On my personal device (GS5, Android 6?) I actually don't get a prompt to "Open once" or "Always open" – this is the key point I'm trying to make. When you click to open in an app from a prompt, it automatically acts like you pressed "Always open", meaning it gets set as the default even if the user didn't intend for it to be.

Okay, setting the default on your device is weird - but it's the default nevertheless? I'm not sure how we should capture what the user intended to do?

**Comment by GammaBurst101** [comment]
Hey, it happens to me too. I tapped on a link and it gave me some options with the label "Open With". I clicked on "Firefox Focus".

After that, I tapped on another link but this time, I wasn't given the option to choose and it was opened in Firefoz Focus.

Device : Samsung Galaxy J7 Prime (Android 7.0)

**Comment by mcomella** [comment]
> I'm not sure how we should capture what the user intended to do?

I agree: I was raising this issue to emphasize the uncertainty of this metric for Product. it seemed like @bbinto had been using the "default browser" metric to make a lot of product decisions but I was questioning how accurate this metric really is.

I'm not sure how significant this metric still is in @bbinto 's thinking, but it's something to think about.

**Comment by bbinto** [comment]
Thanks for bringing this up, @mcomella.

Is there a way to figure out what devices/users don't get a prompt to "Open once" or "Always open" and carefully extract or separate them from our query?
