### ISSUE TITLE
Loosen up the HTTPS cert warning

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2039]
Via Google Translate (DE->EN)

> Unfortunately, you can not access https-encrypted websites that have not solved the certificate. But since many websites no longer opt for this blackmailer certificate, many sites do not have it. If you could set such pages to show anyway, firefox focus would be the perfect, simple and fast browser for me. Unfortunately with this problem absolutely useless. Too bad.

**Comment by mcomella** [comment]
We could allow users to ignore SSL errors (dupe #1563). That being said, this could also be caused by #1338 (Focus does not cache intermediate CAs) so fixing that could also solve this problem.
