### ISSUE TITLE
Firefox Focus is making sensor APIs available to cross-origin iFrames

### ISSUE THREAD

**Issue by anupam-das** [mozilla-mobile/focus-android#2044]
We are a group of researchers who have been investigating what sensors are accessible to third party scripts. We recently found that Firefox Focus is making sensor APIs available to cross-origin iFrames, which is not the case for native android Firefox. We believe Focus should not be doing this due to security and privacy risks listed at the following link https://www.w3.org/TR/generic-sensor/#main-privacy-security-threats 

**Details of the experiment**
Test device: Pixel 2 XL; Android 8.1.0
Demo site: https://web.iiit.ac.in/~amogh.pradeep/test.html
Procedure: visit the iFrame link and see what sensors are accessible, then visit the 3rd-party link and see what sensors are accessible.
Expected behavior: According to the following Firefox bug report (https://bugzilla.mozilla.org/show_bug.cgi?id=1197901) and W3C recommendation (https://www.w3.org/TR/generic-sensor/#top-level-browsing-context) sensor readings should only be available in the top-level browsing context. But as you can see from this experiment cross-origin iFrames are able to access more sensor data in the current version of Firefox Focus (version 4.0.1)

**Comment by dveditz** [comment]
Fennec (Firefox for Android) uses the Gecko browser engine. Focus uses the platform's built-in WebView. Sometimes we can work around issues but in this case I don't think we can. Chrome behaves the same as Focus for Android and the bug needs to be fixed by Google. Hopefully they agree that the spec is correct and that they should fix it.

**Comment by mozfreddyb** [comment]
If you think that allowing sensor data is a good idea (which I don't), then I don't think it really matters whether it's accessible to 3rd party iframes or not.
It does matter if you prompt for the top level and make the top level origin the permission bearer, though (but that's not the case here).

**Comment by gunesacar** [comment]
> The primary action item for this bug would be to file an issue against Chromium (if one doesn't exist already).

There's an open Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=598674.
[This comment says](https://bugs.chromium.org/p/chromium/issues/detail?id=598674#c11) the issue will be fixed with the introduction of the Feature Policies for the Device Orientation API.

**Comment by kbrosnan** [comment]
GV has made this issue obsolete.
