### ISSUE TITLE
Add leak canary watches for fragments

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2045]
After #887 lands, as per https://github.com/square/leakcanary/wiki/FAQ#how-do-i-use-it

**Comment by grubdragon** [comment]
I'll take this up when I can

**Comment by mcomella** [comment]
Sure, works for me!

**Comment by grubdragon** [comment]
For which fragments do we need watches?

**Comment by mcomella** [comment]
@grubdragon All of them. :) BrowserFragment in particular.

**Comment by swolfand** [comment]
👋 looks like the previous attempt at this hasn't seen life in a while. happy to help! butttt did leakcanary get removed at some point? I can find the commit where it's added through #887 and the referenced PR's but not in master or the latest RC. If it was removed maybe there's a reason and this issue is stale? LMK

**Comment by mcomella** [comment]
Yes – LeakCanary got removed a little while back because it was causing
problems with our GeckoView build. @ekager What are your thoughts about
adding LeakCanary back now?

**Comment by bansalayush** [comment]
Hey @mcomella  , can i pick this up ? :)

**Comment by ekager** [comment]
Happy to try again if LeakCanary is helpful from anyone else's experiences! I honestly don't remember the build issues we were having at that point, possibly would work fine now!

**Comment by VINOD242** [comment]
i want to join this community...

**Comment by dbekel** [comment]
@ekager Emily hi, I was trying to publish a branch and a pull request for this fix, but got _'Authentication Failed'_ error, can you please let me know on next steps.

**Comment by mcomella** [comment]
@VINOD242 @dbekel – thanks for wanting to help out! @ekager can correct me if I'm wrong but, unfortunately, I do not believe we have the resources to support contributions to Focus at this time. I'd recommend taking a look at [Firefox Preview](https://github.com/mozilla-mobile/fenix) or [Firefox for Fire TV](https://github.com/mozilla-mobile/firefox-tv) if you'd like to hack on an Android-based Firefox browser.

@dbekel Specifically wrt your authentication error, my best guesses are one of:
- You're trying to push to the upstream repo (`https://github.com/mozilla-mobile/focus-android.git`) instead of your fork (`https://github.com/dbekel/focus-android.git`)
- You're pushing to a git protocol address (`git@github.com:dbekel/focus-android.git`) that does not have properly configured SSH keys (see [the GitHub SSH guide](https://help.github.com/en/articles/connecting-to-github-with-ssh) for more assistance)

If you message us in #focus on #fenix on [IRC](https://wiki.mozilla.org/IRC) during PST working hours, we should be able to help you out too!

**Comment by ekager** [comment]
Correct! We are not currently supporting contributions to Focus. Please follow Mike's recommendations if you would like to contribute

**Comment by ionutbedregeanu** [comment]
Seems to be addressed by https://github.com/mozilla-mobile/focus-android/pull/6461
