### ISSUE TITLE
Long press over image > share image, shares address of image instead of image

### ISSUE THREAD

**Issue by huuhaa** [mozilla-mobile/focus-android#2046]
I'm not sure should this be linked to #531 and #502 but since both of those are closed and this is bit different case, I open new issue for this one.

When longpressing over image and selecting share image from the menu and after that for exaple whatsapp and contact from there, there is no image to be shared but a link to the image instead.

I think expected behavior would be to share actual image, at least this is what happens when using Chrome or Brave. On the other hand this same behavior as in Focus seems to be in Firefox for Android. I hope that both, Firefox Focus & Firefox for Android would share actual image when using this. After all there is separate "copy image address" at least in Focus which is supposed to do what this share image action does now. Also it's quite handy function in some cases when you don't have to download image first.

**Comment by lobontiumira** [comment]
I was able to reproduce this on Beta 94.0.0-beta.2 build, and RC 93.1.1 with Lenovo Tab M10 (Android 10), and RC 93.1.1.

**Comment by lobontiumira** [comment]
I was not able to reproduce this on the latest Focus Nightly build from 2/22 using a Xiaomi Mi 10 (Android 11), and an Oppo Find X3 Lite (Android 11).
