### ISSUE TITLE
Add UA String to Mozilla Developer List

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#2048]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Comment by mcomella** [comment]
@Sdaswani Is the action item to add Firefox Focus' UA string as an example in the linked page?

**Comment by Sdaswani** [comment]
@yes @mcomella .

**Comment by boek** [comment]
Hey Mike,

My apologies for not responding earlier, for some reason I missed that comment!

Unfortunately there isn't a straight forward answer to this. Focus has been shipping both WebView and GeckoView for quite some time. Even the latest beta (7.0.2) has users on both WebView and GeckoView.

I think the earliest that publicly started using it was June 22nd: https://github.com/mozilla-mobile/focus-android/pull/2774, which would have been version 6.0.

Does this help?

**Comment by miketaylr** [comment]
> Does this help?

Absolutely, thanks!

**Comment by miketaylr** [comment]
@Sdaswani documented here, this can probs be closed:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#Focus_for_Android
