### ISSUE TITLE
Blocked tracker count may be inaccurate (lower than actual)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2049]
I added log statements next to [`callback.countBlockedTracker()` in `TrackingProtectionWebViewClient.shouldInterceptRequest()`](https://github.com/mozilla-mobile/focus-android/blob/e4a762ce4469cdf616208b9677b575e8e7a22890/app/src/webview/java/org/mozilla/focus/webview/TrackingProtectionWebViewClient.java#L111) and for metacritic, it reported 9, while the UI reports "3".

I think the problem is that we get the value and then set the updated value asynchronously (a classic get-and-set problem):
- shouldInterceptRequest can be called from a non-UI thread
- callback.countBlockedTracker calls SessionCallbackProxy.countBlockedTracker, which is `session.setTrackersBlocked(session.getBlockedTrackers().getValue() + 1);` (two operations)
- `setTrackersBlocked` calls `this.trackersBlocked.postValue(trackersBlocked);`, which asynchronously updates the value

I don't understand why this code needs to be asynchronous at all so it'd be great if we could remove that.

**Comment by bansalayush** [comment]
I am picking this up :)

**Comment by mcomella** [comment]
@ekager is this still relevant? I'm concerned this code moved to android-components.

**Comment by ekager** [comment]
Ah true I think this code has moved. Closing
