### ISSUE TITLE
Wrong wiki link for first bugs

### ISSUE THREAD

**Issue by gillespiecd** [mozilla-mobile/focus-android#2050]
From `List of good first bugs for new contributors`

Current link: https://github.com/mozilla-mobile/focus-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22

Should be: https://github.com/mozilla-mobile/focus-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by mcomella** [comment]
Fixed, thanks!
