### ISSUE TITLE
(Optionally?) keep tabs in memory

### ISSUE THREAD

**Issue by Biskvit** [mozilla-mobile/focus-android#2052]
This might've been pointed out already, so I apologize if I'm just repeating something that has been said before. 
Switching between "tabs" (I don't know how exactly the implementation in Focus is called, but I'll be calling them tabs for now) causes the whole page to reload. Written data, performed actions and filled forms are not lost because it's not a refresh, but it is still a minor annoyance to have pages reload like that upon switching. Maybe it's a limitation of Webview, or something done on your part for privacy reasons. All I know is that this did not happen with Firefox, Chromium, or Lightning (another browser which utilises WebView) unless I had too much tabs opened -- and even then, reloading happened faster. 

>📱 Please include the Android device and Android version you are using
Sony Xperia L, Android 7.1.2. (microG+LineageOS fork)
    >🌐 Posting your user agent can help us debug problems.
Probably not applicable here, but the ROM ships with whatever the latest stable WebView is. Sites identify it as "Chromium 63". 
    >📓 Include a list of steps to reproduce the issue
Open two or more tabs, and switch between them. 
    >🔬 State what behavior you expected and what the actual behavior is on your device
I expected a nearly-seamless switch between tabs, similar to Chromium, Firefox, Lightning, etc., but there's a very noticeable reload in which the whole page goes to white upon switching tabs, even if you have only two or three of them open. Takes no more than a second to return to the way things were, but it is somewhat of an annoyance to have things reload each time.

**Comment by mcomella** [comment]
Dupe #1393 – this is possible to do, but it's not happening because of the way that we initially wrote it.
