### ISSUE TITLE
Use Latest GeckoView 🦎 

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#2056]
GeckoView has been updated - let’s use the latest and greatest one.

**Comment by mcomella** [comment]
FYI: Snorp has a PR opened for GeckoView changes – we should figure out if that will be replaced or is necessary for this to work.

**Comment by Sdaswani** [comment]
@snorp is this PR out of date or can be used for this work? https://github.com/mozilla-mobile/focus-android/pull/1377

**Comment by Sdaswani** [comment]
@ekager can this be closed?
