### ISSUE TITLE
Some wiki websites have their layout broken on Focus.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/focus-android#2066]
http://emulation.gametechwiki.com/index.php/Main_Page

The website above is just one example.

Some websites are not scrollable, for example: http://www.simplemysticmiracles.com/

I miss the option to request desktop site and close tabs. Could you add these features?

Love Firefox Focus. Keep with you great work.

**Comment by vesta0** [comment]
Thanks for the feedback! Request desktop was added in Focus 6.0
