### ISSUE TITLE
InfoActivity (e.g. SUMO links) may not be using tracking protection

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2070]
See: https://twitter.com/coxy/status/956124454962302976

Thoughts:
- We're using a separate web view - perhaps we forget to apply the tracking protection web view client?
- Maybe we should just open these links in the core browser now that we have tabs anyway.

**Comment by ekager** [comment]
We got rid of InfoActivity per the second bullet suggestion :) Closing!
