### ISSUE TITLE
website causes firefox focus to stop loading any other pages until app storage is deleted

### ISSUE THREAD

**Issue by pkellyuk** [mozilla-mobile/focus-android#2076]
on android with LG G5 going to http://www.thefragranceshop.co.uk 

the site does not load and causes subsequent sites to be very slow or not load. 

requires a local db wipe to fix

**Comment by pocmo** [comment]
local db wipe?

**Comment by Sdaswani** [comment]
@pkellyuk can you let us know what you meant by local db wipe?

**Comment by bbinto** [comment]
@pkellyuk - could you please let us know if you still experience this issue and if so please follow this template

### Steps to reproduce

### Expected behavior

### Actual behavior
