### ISSUE TITLE
testShareIntentWithTextViaNewIntent is missing @Test annotation

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2078]
https://github.com/mozilla-mobile/focus-android/blob/3ecc088d6ae090aa87e9ab61ea08ad0116b5b015/app/src/test/java/org/mozilla/focus/session/SessionManagerTest.java#L170

Add it and make sure it passes!

**Comment by BMB281** [comment]
Hey @mcomella, I'd like to contribute this project in anyway I can. Assuming this hasn't already been added, I've added the annotation and ran a SessionManagerTest; the function passes, however, I get a failed test on testShareIntentWithTextViaNewIntent(), line 177, stating: "java.lang.IllegalStateException: Attempting to retrieve search engines without a corresponding init()"
--Is this a problem on my end?

**Comment by Sdaswani** [comment]
Thanks for your contribution @BMB281 ! @npark-mozilla and @ekager may be able to advise too.

**Comment by berlinbra** [comment]
Happy to help! 
I've added a @Test (expected = IllegalStateException.class) and everything seems to run smoothly, with all asserts passing. @npark-mozilla  and @ekager ; is this acceptable annotation or does it go against the purpose of the test case?

**Comment by npark-mozilla** [comment]
since that's a unit test, @ekager would know better, but I think that seems okay to me, since it reaches line 183-187 and passes.

**Comment by berlinbra** [comment]
I've created the commit 'Closes #2078'. I don't have permissions to push; what's the next step?

**Comment by ekager** [comment]
Hi @berlinbra ! Did you fork and then clone to create your own copy of the repo? You can then put your changes on a branch and push to your remote where you can then open a PR to compare our version to yours. We'll then review your changes and merge it if everything looks good! Here's a good intro to opening a PR https://opensource.guide/how-to-contribute/#opening-a-pull-request
Let me know if you have any more questions.

**Comment by berlinbra** [comment]
Great, thank you!

**Comment by SubhrajyotiSen** [comment]
Since this issue has been inactive for a while, can I take it up?

**Comment by berlinbra** [comment]
Yes!
