### ISSUE TITLE
Cache isn't being cleared ever

### ISSUE THREAD

**Issue by auggy** [mozilla-mobile/focus-android#2079]
Unless I manually clear it.

**Comment by mcomella** [comment]
@auggy Can you provide steps to reproduce? In particular:
- How are you testing that the cache is not cleared?
- How are you clearing data in the app? e.g. pressing the erase button

Also, what version of Focus are you running? We fixed an issue with the cache not erasing in #1492.

**Comment by pocmo** [comment]
No response. Not actionable.
