### ISSUE TITLE
blinking of screen on help page firefox focus app

### ISSUE THREAD

**Issue by Itzmanz** [mozilla-mobile/focus-android#2081]
#### Expected behavior
what i quite expected was a good opening of the site help page   

#### Actual behavior
blinking of screen while opening the page 

#### How to reproduce
Open the application
click on the help tab, it might open correctly 

* Device used: Samsung galaxy A3
* Andriod version:6.0.1

#### Recording Of The Bug
![buggg.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517447862/yorr7jjqn5yhhxea8ewg.gif)
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@suleimanz/blinking-of-screen-on-help-page-firefox-focus-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by grubdragon** [comment]
Attach the gif somewhere else (eg. https://giphy.com/upload/) and paste the link here, I was hit with a content length exceeded error on opening your recording.

**Comment by Sdaswani** [comment]
May be fixed in #2388

**Comment by pocmo** [comment]
Just merged #2388. This should be gone now as we are opening new tabs now.
