### ISSUE TITLE
Focus/Klar 4.0.2 not on archive.mozilla.org?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2083]
I wanted to install Focus on my device from archive.mozilla.org (because it's not available from Google Play in Germany). The latest version available is 4.0.1. However I can see Klar 4.0.2 in Google Play. Did we forget to upload 4.0.2 to archive.mozilla.org?

**Comment by mcomella** [comment]
It looks like we're also missing it on github: https://github.com/mozilla-mobile/focus-android/releases

@liuche Do you know what happened here?

**Comment by liuche** [comment]
Ah, I forgot to upload them, I'll do it now.

**Comment by liuche** [comment]
Okay, should be fixed, updated the wiki too because I forgot the commands -_-;;
