### ISSUE TITLE
Fullscreen does not work properly with GeckoView

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2084]
STR:
1. Go to Youtube.com
2. Open video and display full screen

Expected:
Immersive mode will be entered

Reality:
Bottom controls remain and pressing "back" gets you stuck on black screen

**Comment by ekager** [comment]
I think this is a problem on our end in onEnterFullScreen (BrowserFragment) where we pass in a view (we pass in null when using the Gecko variant) and I am continuing to investigate.

**Comment by pocmo** [comment]
There is some code for this in here:
https://github.com/mozilla-mobile/focus-android/pull/1377

**Comment by ekager** [comment]
Hi @pocmo :) To be clear, I'm working off of #2067 which uses the fullscreen code from #1377 . The problem seems to be that we do not enter immersive mode in BrowserFragment when using GeckoView.

**Comment by ekager** [comment]
Closing because this seems to be working

**Comment by Mugurell** [comment]
> I'm having some issues with fullscreen on YouTube, where I can enter fullscreen, but can't exit, this seems to be only on geckoview. Any ideas why?

@sgebr01  Can you open a new ticket with details about the application you're seeing this in - what version of it and of the device? If there are important steps to reproduce please mention them also. Thank you!
