### ISSUE TITLE
LongClick does not work with GeckoView

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2088]
It is currently labeled as a to-do. We use a LinkHandler for Android WebView (implements View.OnLongClickListener) that uses Android WebView methods for HitTestResult. 
https://developer.android.com/reference/android/webkit/WebView.HitTestResult.html

**Comment by Sdaswani** [comment]
@ekager what’s labeled as a to-do?

**Comment by ekager** [comment]
It is commented as a to-do in the code, so this is a known issue
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java#L57

**Comment by ekager** [comment]
Context menu is implemented with GeckoView.
