### ISSUE TITLE
Disallow sensor access on insecure contexts

### ISSUE THREAD

**Issue by gunesacar** [mozilla-mobile/focus-android#2092]
**Description**:  Firefox Focus makes devicemotion and deviceorientation data available on insecure contexts. According to the [W3C Generic Sensor API spec](https://www.w3.org/TR/generic-sensor/#secure-context), sensor APIs should only be accessible on secure browsing contexts.

Chromium behaves the same way and has an open issue about it: https://bugs.chromium.org/p/chromium/issues/detail?id=520765.

**Steps to reproduce the issue:**
- Visit the demo page: http://homes.esat.kuleuven.be/~gacar/dev/test/sensor/

**Actual behavior**:  Sensor data is accessible by scripts in insecure contexts.
**Expected behavior**: The sensor data should only be available on secure contexts.

**Android version**: 7.0.0
**User agent:** Mozilla/5.0 (Linux; Android 7.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.0.2 Chrome/64.0.3282.137 Mobile Safari/537.3

PS: My collaborators and I noticed this issue during our research on sensor API usage. I'm reporting on behalf of them as well.

**Comment by pocmo** [comment]
For the WebView-based versions we just need to wait until this ships in Chrome/WebView.

For GeckoView we might need to file a bug or maybe this is already on some roadmap - @snorp?

**Comment by snorp** [comment]
GeckoView bug is on file here: https://bugzilla.mozilla.org/show_bug.cgi?id=1436874
