### ISSUE TITLE
Download Error Trying Opening a PDF

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#2097]
0. Launch Klar with GV
1. Try to load this link: https://www.whitehouse.gov/wp-content/uploads/2018/02/budget-fy2019.pdf
2. Observe

**Comment by ekager** [comment]
Blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1437701

**Comment by snorp** [comment]
The GeckoView bug is fixed. We added ContentDelegate.onExternalResponse(), which can be used to handle a download.

**Comment by ekager** [comment]
Hey @snorp in the latest master where I have `onExternalResponse` I cannot trigger this method when trying to download files even when manually giving storage permissions.

**Comment by ekager** [comment]
This seems to be working now with the example provided by @Sdaswani , please reopen if you find otherwise.
