### ISSUE TITLE
Add 'about' screen

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#21]

**Comment by pocmo** [comment]
iOS version:

![ios_about](https://cloud.githubusercontent.com/assets/89638/23545155/7aee4e60-fffa-11e6-92f7-44d5cfc89825.png)

Learn more links to the Mozilla manifesto (in a "full screen" WebView, not the browser view).

**Comment by antlam** [comment]
@pocmo @ahunt let's also make sure we're following the same font styles as the "Your rights" screen here. 

The "Learn more" link could also be White, underlined, just like issue #89

**Comment by ahunt** [comment]
Early preview (the styling needs to be done - it's using the same font/margins as "your rights", but the image and possibly spacing need to be adjusted):
@bbinto @antlam I'm guessing we can use the same strings as in iOS, but without the "Safari extension" part?
![about_v1](https://cloud.githubusercontent.com/assets/1546915/23924186/f7c79bf4-0909-11e7-8b4e-5bb64b7ea833.png)

**Comment by antlam** [comment]
> it's using the same font/margins as "your rights", but the image and possibly spacing need to be adjusted

@ahunt could you put 24 above and below the Firefox Focus word mark image?

**Comment by ahunt** [comment]
![about_v2](https://cloud.githubusercontent.com/assets/1546915/23941914/dd6acfcc-096a-11e7-84f7-4a2b353d3415.png)

**Comment by antlam** [comment]
Nice!
