### ISSUE TITLE
Add support for dialog-based authentication

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2100]
STR:
1) Visit https://www.ccsf.edu/Departments/Language_Center/oll/chinese/index.html
2) Select "Level 1 Part 1 Textbook"

Expected: An authentication dialog (to enter user and password)
Actual: Page reloads to "Authorization required"

You can get the expected behavior on desktop. I'm guessing we've never implemented authentication dialogs.

**Comment by Sdaswani** [comment]
@mcomella is this a dupe of https://github.com/mozilla-mobile/focus-android/issues/159 ?

**Comment by mcomella** [comment]
Looks like it.
