### ISSUE TITLE
Use GeckoView AAR from Maven repo

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/focus-android#2101]
### Why
This issue will make it easier to release GeckoView

- RelEng to create Maven Repo
- Focus frontend team to change the configuration file 

We're working on a more permanent solution, but the following repo URL will work for the 32-bit ARM lib:

https://index.taskcluster.net/v1/task/gecko.v2.mozilla-central.nightly.latest.mobile.android-api-16-opt/artifacts/public/android/maven

This will always refer to the most recent Nightly build of GeckoView, which I think is what we want.

**Comment by cpeterso** [comment]
Publishing a real maven repo is tracked in [bug 1433198](https://bugzilla.mozilla.org/show_bug.cgi?id=1433198).

**Comment by ekager** [comment]
We are using the repo URL successfully, but I will keep this open and label as Blocked for the real maven repo issue.
