### ISSUE TITLE
Use https for autocompleted URLs

### ISSUE THREAD

**Issue by stonewareslord** [mozilla-mobile/focus-android#2102]
It seems that Firefox focus does not store schemes with autocomplete URLs. If I add https://example.com, it only stores the example.com part of the url. When typing “exa” into the url bar, it autocompletes to the http version of the  site. 

Please either force https or allow storing the scheme with the url. 

 Version: F-Droid Firefox Klar 4.0.2 (build #18)
OxygenOS 5.0.2 on OnePlus5, rooted

**Comment by boek** [comment]
Dup of #2000
