### ISSUE TITLE
Search Terms or URL does not work with GeckoView

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2103]
STR: 
1. Type search terms + enter 
2. Click any link in search results 
3. Click URL Bar

Expectation: See link for page you've visited
Reality: See search terms

**Comment by Sdaswani** [comment]
cc @bbinto on losing this in Klar.

**Comment by bbinto** [comment]
Needs to be fixed --> P1

**Comment by ekager** [comment]
Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1439013
