### ISSUE TITLE
Custom tabs menu item is out of order

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2105]
Layely’s patch has implemented a custom tab menu option to open URL in Focus app:

https://github.com/mozilla-mobile/focus-android/pull/1634#issuecomment-365766514

<img src="https://user-images.githubusercontent.com/759372/36231605-7b3cc6c0-1193-11e8-938e-cbbdb78cc3b6.png" width="300">

For consistency and ease of access, we should reorder the menu item slightly, so that they align with the design spec found here:

https://github.com/mozilla-mobile/focus-android/issues/1626#issuecomment-345580294

1. Share…
2. Add to Home screen
3. Open in…
4. Open in Firefox Focus

(There’s no need for Settings. The user can go to the Focus app itself in order to do this).

<img src="https://user-images.githubusercontent.com/51007/36239526-35c27036-126f-11e8-90c6-5a44d37995bd.png" width="300">

**Comment by pocmo** [comment]
@brampitoyo I'm going to update the order of menu items. Your mocks say "Open in ..." while our strings are "Open with ..." currently. Is this something you want to update too?

**Comment by brampitoyo** [comment]
@pocmo Yes. I would like to update the menu item strings so they both say “Open in…”

String consistency is what I’m aiming for. The choice of “in” vs. “with” is less important – but “in” is preferrable.
