### ISSUE TITLE
Custom tabs menu needs to show branding

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2106]
Currently, there are only implicit hints to tell the user that the custom tabs she’s using is Firefox Focus:

* Thin topmost bar is coloured purple
* There’s a switch to turn Tracking Protection on/off inside the menu

We can make this visual hint more explicit by adding a small text that says “Powered by Firefox Focus” on the bottom of the custom tab.

<img src="https://user-images.githubusercontent.com/51007/36239526-35c27036-126f-11e8-90c6-5a44d37995bd.png" width="300">

**Comment by pocmo** [comment]
@brampitoyo How does this look like?

The values I used:

* padding left/right: 8dp
* padding top/bottom: 4dp
* text size: 12sp
* background: #272727

![ct-branding](https://user-images.githubusercontent.com/89638/37211986-03b04168-23ae-11e8-9f46-db339ee0c652.png)

**Comment by brampitoyo** [comment]
Hi @pocmo, apologies for not including the spec with my original design.

> The values I used:
> padding left/right: 8dp
> padding top/bottom: 4dp
> text size: 12sp
> background: #272727

The aim is to match the left/right padding value of the other menu item, so everything sits in line when you draw a vertical line through them. I think the side padding should be 16dp?

And the padding top/bottom value should be 8dp.

Everything else looks good!

**Comment by pocmo** [comment]
> And the text colour should match the one used by “Trackers Blocked” up above the menu. If I recall correctly, the value is #ffffff with 0.5 opacity.

Can you give me the color code of this combined with the background color (the opaque color that you get when drawing #ffffff with 0.5 opacity on top of the background). Reason is that drawing with opacity comes with a cost on Android and if possible I try to avoid it.

I tried replicating this in GIMP and got #929292 - Does this make sense?

**Comment by pocmo** [comment]
![custom-tabs-branding](https://user-images.githubusercontent.com/89638/37366824-d72998d6-2701-11e8-9082-770051926bfe.png)

@brampitoyo How is this?

**Comment by brampitoyo** [comment]
> I tried replicating this in GIMP and got `#929292` - Does this make sense?

Yes. If we try to replicate the colour value, then the one you use is correct. Thank you!

**Comment by pocmo** [comment]
Landed updates to follow spec.
