### ISSUE TITLE
Can't zoom into Desktop Version

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2110]
@ekager, might not be implemented yet?

STM for GeckoView+Klar version

1. Go to e.g. miliascoffee.de
2. Try to zoom in with both fingers

Expected behaviour:
Page zooms in (works on Chrome)

Actual behaviour:
Nothing happens

**Comment by ekager** [comment]
I can zoom in on the latest version of GeckoView+Klar for this page, you may have had an outdated build?

**Comment by ekager** [comment]
Haven't seen this issue again. Have you @bbinto ?

**Comment by bbinto** [comment]
Got the latest version -- works now, closing, thanks @ekager
