### ISSUE TITLE
Firefox Focus is vulnerable to WebGL fingerprinting

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#2111]
I tried the Panopticlick test on EFF website several times with Firefox Klar. Most of the fingerprints changed after erasing browsing history, but the WebGL fingerprint remained the same. I'm told this has to do with WebView.

**Comment by Sdaswani** [comment]
Thanks for the report @zekooooo . We are thinking hard about anti-fingerprinting measures, so we will consider this when we come up with a plan.

**Comment by Sdaswani** [comment]
Closing as a dupe of #2289
