### ISSUE TITLE
Text selection menu doesn't open on Klar+GeckoView

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2112]
STR:
1. Go to wikipedia.com.
2. Long press on a word.

Expected results:
The text selection menu should be displayed.

Actual result:
The text is just selected, with no tools to copy/share, etc.

**Comment by cpeterso** [comment]
Is this bug related to LongClick issue #2088?

**Comment by pocmo** [comment]
I implemented the floating text selection toolbar for Fennec.

There's actually quite some interaction between Fennec UI and the Gecko side of things happening. See:
* https://dxr.mozilla.org/mozilla-central/source/mobile/android/modules/ActionBarHandler.jsm
* https://dxr.mozilla.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/text/FloatingToolbarTextSelection.java
* https://dxr.mozilla.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/text/FloatingActionModeCallback.java
(This is the implementation for Android 6+)

**Comment by pocmo** [comment]
GeckoView: https://bugzilla.mozilla.org/show_bug.cgi?id=1441279

**Comment by ekager** [comment]
Closed by #2380!
