### ISSUE TITLE
Wrong message at the first download of the build  (3879/3898)

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#2113]
Steps:
1) Have no Focusversion installed on the device
2) Open the link to download the build #3879
3) Open a newer build mail aka #3898

Expected Results:
- you are able to download the message without any errors. 
- you are able to install an update without errors

Actual Results:
- after step 2 - you get a message in the buddybuild that you already have the version installed. ( which is not true) 
- no such message is displayed for newer build ( though it is displayed for a few seconds it is overwritten with "WIP End of Week 2 build" text) 

<img src="https://user-images.githubusercontent.com/1391451/36394310-5495c9c2-15bc-11e8-8833-726f590fe100.jpg" width="300" height="550" />

<img src="https://user-images.githubusercontent.com/1391451/36394309-54694604-15bc-11e8-9618-71a4b4f4a719.jpg" width="300" height="550" />

Device: Pixel 2 (Android 8.1.0)

**Comment by ioana-chiorean** [comment]
I am not able to add the label:Klar+Geckoview (but this is reported against that build as sit can be seen from the screenshots)

**Comment by ioana-chiorean** [comment]
@sv-ohorvath did u get this issue? I will try on several other devices too tomorrow.

**Comment by Sdaswani** [comment]
Thanks - just FYI that Build #3887 is the latest one @ekager published last week.

**Comment by Sdaswani** [comment]
Oh oops - I see that is the one you are using above, sorry!

**Comment by ioana-chiorean** [comment]
No worries. Thanks for checking anyway!

**Comment by ekager** [comment]
I'm not sure if this is a BB issue or something I'm doing.. @pocmo any thoughts?

**Comment by sv-ohorvath** [comment]
I see the second message replacing the "ready to be installed on your device" on build  #3898 too, just with a different wording "Try this!".
For the first image. I think you misread "already" as "ready" which is not hard to confuse. :)

**Comment by ioana-chiorean** [comment]
Indeed @sv-ohorvath - sorry, I read already not ready. My name does mean the blind one if u translate CHIOR to English (is that even an excuse?) 

The issue remains about the second screenshot and situation. .

**Comment by ekager** [comment]
Closing because not using BB anymore for distributing builds.
