### ISSUE TITLE
Show GeckoView version on About page

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#2114]
We should display both the Focus app version and GeckoView's Gecko version on Focus's About page, including Gecko's build ID or date. This information will be helpful when people report Gecko-related bugs in Focus.

**Comment by ekager** [comment]
Note - we are adding a focus:debug page #1655 which may be a better place for engine info. There is a PR #2089 open.

**Comment by cpeterso** [comment]
The following bug will add GeckoView version information to the GeckoRuntime:

https://bugzilla.mozilla.org/show_bug.cgi?id=1465939

**Comment by ekager** [comment]
I added a quick fix for this, grabbing the version from gradle and adding it to BuildConfig, but keeping this open for when information is in GeckoRuntime.

**Comment by cpeterso** [comment]
This bug probably doesn't need to block the Focus 7.0 milestone because Emily has a workaround and few users will need to know their GeckoView version. :)

**Comment by pocmo** [comment]
Don't we display the GeckoView version on the about page already?

**Comment by bbinto** [comment]
Alright, let's close this issue!
