### ISSUE TITLE
Feedback missing for choosing a different search engine 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#2117]
Device: Pixel 2 (Android 8.1.0)
Build: +GeckoView  #3898

Steps:
1) Go to settings -> Search
2) Tap a different search engine

Expected results:
- a toast notification (or anything else visually) should let me know my default search engine had changed

Actual results:
- no visual notification beside the lighter line over is displayed to confirm my default search engine has changes ( the lighter line might not be enough as people will touch it to drag them or just to see what will be displayed and with no feedback i did not consider my default has changed) 

<img src="https://user-images.githubusercontent.com/1391451/36424639-b88f9346-164c-11e8-9aca-1e1e1b0db08f.jpg" width="300" height="550" />

**Comment by Sdaswani** [comment]
This is more of a feature request, but it's a good one @ioana-chiorean . 👍

**Comment by ioana-chiorean** [comment]
Indeed. I was not sure if I need to tag it somehow, but yes it is a feature request 😅

**Comment by grubdragon** [comment]
I'll try working on this

**Comment by Sdaswani** [comment]
Thanks @grubdragon !

**Comment by pocmo** [comment]
Duplicate of #1983
