### ISSUE TITLE
No audible sound in videos played in browser

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#2118]
Device: Pixel 2 (Android 8.1.0) / Samsung Galaxy S8 (Android 7.0)
Build: +GeckoView #3898

Steps:
- Go to video sites like ted.com / vimeo.com / dailymotion, and play video

Expected results:
* videos should be played without issues -like missing sound, graphic jams etc

Actual results:
* no sound is audible 

Video - https://youtu.be/z3XKj-Bi03k

**Comment by ekager** [comment]
Known issue, Bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1410456

**Comment by ioana-chiorean** [comment]
@ekager just to make sure it was seen from the video, audio works perfect in Firefox for Android Nightly

**Comment by ekager** [comment]
@snorp this would work in FIrefox for Android and not Klar+GeckoView, correct?

**Comment by snorp** [comment]
Yeah, it's a problem when you build with targetSdk >= 24 (or 25?), which Fennec does not currently do.

**Comment by ioana-chiorean** [comment]
Thanks for the clarification @snorp and @ekager - it seems I misread the bug parameters.

**Comment by ekager** [comment]
Thanks for catching this @ioana-chiorean ! I think it will hopefully be fixed soon by 1410456 but we'll keep it open until it is resolved. :)

**Comment by sv-ohorvath** [comment]
Looks like the audio issue it's fixed in Klar+Gecko 4.0.

**Comment by ekager** [comment]
For which device(s) @sv-ohorvath ?

**Comment by sv-ohorvath** [comment]
*Only works on Android 6 and lower:
HTC Desire 820 (Android 6.0.1)
Samsung Galaxy Note 4 (Android 5.0.1)
Huawei Honor 5X (Android 5.1.1)

Still no audio on Android 7 & 8:
HTC 10 (Android 8.0)
Google Pixel (Android 8.0)
Samsung Galaxy S8 (Android 7.0)
Motorola Nexus 6 (Android 7.0)

**Comment by pocmo** [comment]
Updated to GeckoView 2018-03-04 (not merged yet!) and this seems to work now.

**Comment by pocmo** [comment]
@ioana-chiorean @sv-ohorvath Can you confirm that this is working for you with the latest version?
http://bit.ly/focus-preview-builds

**Comment by sv-ohorvath** [comment]
Verified on several devices and the audio is now working on all:
LG Nexus 5 (Android 6.0.1)
Huawei Nexus 6P (Android 8.0)
HTC 10 (Android 8.0)
Samsung Galaxy S8 (Android 7.0)
Motorola Nexus 6 (Android 7.0)
Samsung Galaxy Note 4 (Android 5.0.1)

**Comment by pocmo** [comment]
Thank you!
