### ISSUE TITLE
Open With suggestions miss the native apps

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#2120]
Device: Pixel 2 (Android 8.1.0)
Build: +GeckoView #3898

Steps:
1) Load amazon.com, facebook.com, twitter.com
2) Be sure to have the correspondent apps installed on your device
3) Tap de 3 dots button - top right 
4) Choose " Open with.."
5) Repeat for youtube,com

Expected results:
* Beside the browser options you should have the native app as open with suggestion

Actual results:
* Only the browser options are shown as open with suggestions
* **This works for pre installed apps like youtube**

![openwith](https://user-images.githubusercontent.com/1391451/36428940-ec0e9a98-1659-11e8-9122-d55f9adb5d3d.png)

**Comment by ekager** [comment]
Once you click on an item the option to open in the native app does sometimes appear with GeckoView for Amazon, Youtube, etc but it's not always consistent. It seems like Focus+WebView has the same issues though, so I'm going to remove the label for Klar+GeckoView specifically.

**Comment by GammaBurst101** [comment]
I agree with you @ekager . It is same with me. I opened [Sololean](https://www.sololearn.com) on focus and selected 'Open with' option but there was no option for the already installed **Sololearn** app.

Device: Samsung Galaxy J7 Prime (Android 7.0)
Focus Version: 4.0.2 (Build #20112247)

![screenshot_20180221-112625](https://user-images.githubusercontent.com/35678205/36465457-204df6a4-16fb-11e8-8672-192175188a3e.png)
![screenshot_20180221-112634](https://user-images.githubusercontent.com/35678205/36465463-2454fe64-16fb-11e8-9e05-733374776ac7.png)

 I hope this helps.

**Comment by pocmo** [comment]
This heavily depends on what the third-party app defines in the manifest and what actual URL patterns they register for (or not).

**Comment by Sdaswani** [comment]
@ioana-chiorean we believe we respect the manifests defined by third party apps, if you find that we are not, please re-open.
