### ISSUE TITLE
OnePlus3T issues

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2121]
<img width="727" alt="screen shot 2018-02-20 at 10 34 52 am" src="https://user-images.githubusercontent.com/122897/36433101-be78efd2-1629-11e8-9017-bc963f5793c3.png">

**Comment by ekager** [comment]
I'm not sure how to repro this without a device or the log. Any ideas @pocmo ?

**Comment by pocmo** [comment]
Yeah, not easy. :(

* Firebase Device Lab only has a OnePlus One (Android 5.1) in their list of devices. I did run a "robo test" but there was no crash.

* Maybe try to find a combination that is close (language, android version, maybe resolution?) and see if this triggers something

* Try to find a matching crash in the Google Play console. Afaik we can only filter by Android version and then would need to find a crash that happens at least on this device.

**Comment by pocmo** [comment]
I did start another "robo test" on two Android 8.0 devices set to French. I'll report back in case this finds something.

**Comment by pocmo** [comment]
None of the tests revealed anything. For now this isn't actionable unfortunately. :(
