### ISSUE TITLE
Remove additional referrer information from URL when sharing

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2127]
### Why/User Benefit/User Problem
When sharing a URL out from Focus, the feature will remove long URLs that are mostly used for tracking where the user came from (referrer parameters).

### What / Requirements
- should probably handled as a setting
- once turned on, trim URLs when user shares URL (use the canonical link defined in the page's markup (if it exists): https://en.wikipedia.org/wiki/Canonical_link_element)

### Acceptance Criteria (how do I know when I’m done?)
- Trimming won't break actual link (including when anchors are being used)

See similar feature in Chrome: https://www.theverge.com/2018/2/19/17029162/google-chrome-64-link-trim-feature

**Comment by bbinto** [comment]
@bbinto to fill out feature request template

**Comment by bbinto** [comment]
@boek suggested to create a list of referrer we could check against.

**Comment by pocmo** [comment]
> For GeckoView we'd need an API to actually get this metadata.

I filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1470387

**Comment by bbinto** [comment]
Great, let's discuss on Monday where this sits in the GeckoView team's priority list + effort
