### ISSUE TITLE
Security level indicator missing for insecure connections 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2130]
Build: 
Klar+GeckoView #3898
Focus 4.0.2 (play store version)

STR:
1. Go to google.com, emaramures.ro, or another website with an insecure connection.
2. Check the security icon displayed in the URL bar.

Expected results:
As long as the lock icon is displayed for secure websites, the security level should be shown for insecure websites too.

Actual result:
No security indicator for insecure connections, on both Klar+Gecko & Focus.
![screenshot_20180221-150516](https://user-images.githubusercontent.com/4037709/36481904-06f11816-171a-11e8-91b1-6c745e6a4de5.png)
![screenshot_20180221-150521](https://user-images.githubusercontent.com/4037709/36481905-070ea9f8-171a-11e8-8180-3d67d2720dcc.png)

**Comment by GammaBurst101** [comment]
@sv-ohorvath , Ya, that will be a great feature but there is already an open issue for this at #454. They are discussing this feature over there. You can check that out and if you feel that your problem is being addressed then you may remove this issue.

I hope I was helpful.

**Comment by Sdaswani** [comment]
@sv-ohorvath has #454 fixed your concern? If so, please re-open.

**Comment by sv-ohorvath** [comment]
Yes, I didn't see that bug. Thank you!
