### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2134]
We are now creating signed preview builds for every master push:
https://tools.taskcluster.net/index/project.focus.android/preview-builds

As GeckoView is changing frequently it might make sense to build nightly builds additionally (or

**Comment by pocmo** [comment]
A taskcluster hook + running the existing pipeline should be enough; We can just update the same indexed task with new builds from master.

**Comment by Sdaswani** [comment]
See ya!
