### ISSUE TITLE
Add logging for page start and page finished in GV

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2146]

**Comment by Sdaswani** [comment]
"We're using the GeckoSession.ProgressListener.onPage{Start, Stop} callbacks for autophone tests."

**Comment by Sdaswani** [comment]
Fair point @cpeterso - @ekager do you see a difference in the two APIs?

**Comment by ekager** [comment]
From WebView API :

void | onPageStarted(WebView view, String url, Bitmap favicon)     |                  Notify the host application that a page has started loading.
-- | -- | --
void | onPageFinished(WebView view, String url)           |            Notify the host application that a page has finished loading.

GeckoView API :

void | onPageStart(GeckoSession session,            String url) | A View has started loading content from the network.
-- | -- | -- |
void | onPageStop(GeckoSession session,           boolean success) | A View has finished loading content from the network.

From the front end, they seem to be the same.

**Comment by Sdaswani** [comment]
Agree, thanks @ekager !

**Comment by Sdaswani** [comment]
@snorp let us know if you disagree.
