### ISSUE TITLE
Implement GeckoSession.ContentListener.onCloseRequest()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2150]
GeckoSession.ContentListener.onCloseRequest() appeared in new builds. I just added an empty implementation to make the build pass. Let's figure out if we need to implement it properly.

**Comment by pocmo** [comment]
```
        /**
        * A page has requested to close
        * @param session The GeckoSession that initiated the callback.
        */
        void onCloseRequest(GeckoSession session);
```

In our case we should just ignore this callback.

**Comment by ekager** [comment]
Closing this issue
