### ISSUE TITLE
Implement GeckoSession.NavigationListener.onNewSession()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2151]
GeckoSession.NavigationListener.onNewSession() appeared in new builds. I just added an empty implementation to make the build pass. Let's figure out if we need to implement it properly.

**Comment by bbinto** [comment]
@pocmo to confirm in documentation how to proceed / what still needs to be done.

**Comment by pocmo** [comment]
```
        /**
        * A request has been made to open a new session. The URI is provided only for
        * informational purposes. Do not call GeckoSession.loadUri() here. Additionally, the
        * returned GeckoSession must be a newly-created one.
        *
        * @param session The GeckoSession that initiated the callback.
        * @param uri The URI to be loaded.
        *
        * @param response A Response which will hold the returned GeckoSession
        */
```

In Fennec activities using GeckoView throw an IllegalStateException here because they prevent new sessions to be created from `onLoadRequest`().

**Comment by ekager** [comment]
Closing
