### ISSUE TITLE
No sound when playing videos

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2155]
STR:

Klar+GeckoView build:

Go to https://olympics.cbc.ca/news/article/canada-play-for-men-hockey-bronze-after-being-stunned-germany.html

Expected behavior: 
Video plays with audio

Actual behavior:
Video plays without audio (tested it in Chrome, worked fine with audio)

**Comment by ekager** [comment]
Dupe of #2118
