### ISSUE TITLE
URL address bar hijacking when playing videos

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2156]
STR:

Klar + GeckoView

- Go to https://olympics.cbc.ca/news/article/canada-play-for-men-hockey-bronze-after-being-stunned-germany.html
- Click play on video
- Stop video
- Check URL in address bar 

Expected behavior: 
- Same URL as before (https://olympics.cbc.ca/news/article/canada-play-for-men-hockey-bronze-after-being-stunned-germany.html)

Actual behavior:
- Video player/SVG URL: https://olympics.cbc.ca/divaPlayer/html5/divaplayer.html?configurationFileUrl=https%3A%2F%2Folympics.cbc.ca%2Fdivaplayer%2Fsettings%2Fsettings-vod-en.xml&videoId=57395&cs1=https%3A%2F%2Folympics.cbc.ca%2Fnews%2Farticle%2Fcanada-play-for-men-hockey-bronze-after-being-stunned-germany.html&cs2=Ice-Hockey&cs3=&cs7=player-1519398164181&divalogo=%2Fdivaplayer%2Fimages%2Fpyeongchang-white-logo.svg

**Comment by ekager** [comment]
We currently detect live changes in the URL including redirects in onLocationChange but this method also seems to be picking up the web content URIs as well. 

In WebView, we are able to detect if the request is for the main frame in shouldInterceptRequest and update the URL accordingly. 

I already have a Bugzilla issue to add the functionality of shouldInterceptRequest to GeckoView, and I will update it with this information as well.

**Comment by ekager** [comment]
Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1439013

**Comment by ekager** [comment]
This should be resolved in the latest GeckoView builds please reopen if not
