### ISSUE TITLE
Android Autofill support for GeckoView

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2158]
not for initial launch

**Comment by vesta0** [comment]
@cpeterso is this still an issue?

**Comment by cpeterso** [comment]
GV 62 supports Android Autofill for filling password fields, but not for other field types, like credit cards. If filling other field types is a priority for Focus, the GV team will need to do more work.

**Comment by ekager** [comment]
FYI I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1489569 because autofill with GV currently seems broken. This would definitely be a prod blocker.

**Comment by cpeterso** [comment]
The fix for GV bug 1489569 will be uplifted to the GV 62 relbranch next week.

**Comment by vesta0** [comment]
@ekager @cpeterso I believe this is resolved (checked the bugzilla issue). Can we close this?
