### ISSUE TITLE
Use release builds of GeckoView

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2162]
There are none yet. However at some point (before the release) we want to use release builds. Currently we are using Nightly builds from mozilla-central. Those are not stable enough to use in production.

**Comment by bbinto** [comment]
@pocmo can we close this?

**Comment by pocmo** [comment]
No, we will have to build with a GV release build to ship... this will have to wait until there's a release that we want to ship with.

**Comment by ekager** [comment]
We are now using a rel branch of GV, closing
