### ISSUE TITLE
Strings import: oc / anp / an / wo / tt is not a valid locale

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2167]
The import of some locales fails:

>    [failed] oc is not a valid locale
>    [failed] anp is not a valid locale
>    [failed] an is not a valid locale
>    [failed] wo is not a valid locale

Occitan (oc)
https://pontoon.mozilla.org/oc/focus-for-android/

Angika (anp)
https://pontoon.mozilla.org/anp/focus-for-android/

Aragonese (an)
https://pontoon.mozilla.org/an/focus-for-android/

Wolof (wo)
https://pontoon.mozilla.org/wo/focus-for-android/

Tatar (tt) 
https://pontoon.mozilla.org/tt/focus-for-android/

**Comment by pocmo** [comment]
We have to add those manually to our import script again.

@Delphine Can you help me with getting the language names again? :)

**Comment by Delphine** [comment]
On it! Will update here once I get that :)

**Comment by Delphine** [comment]
@pocmo: I've just had a localizer ask me to enable Tatar (tt) locale for Focus Android, so I've added it to Pontoon. I expect him to start localizing very soon, so I'm adding him here as a mental note to the current list of locales we should add to screenshots :)
I've asked him for the language name as well, so I can report here once he (and the others) reply.

**Comment by Delphine** [comment]
@pocmo: 
* Occitan (oc) should be: occitan
* Aragonese (an): Aragonés
* Tatar (tt): татарча
* Wolof (wo): Wolof
(should respect title case)
Still waiting on Angika (anp) to reply!

**Comment by Delphine** [comment]
Here is Angika: अंगिका

Thanks Sebastian!

**Comment by pocmo** [comment]
Those locales are now getting imported and are in the list of "screenshot only" locales.
