### ISSUE TITLE
GeckoView-based version doesn't receive the tier1 sent to Chrome Android

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2171]
See "Firefox for Android" issue for the whole story:
https://bugzilla.mozilla.org/show_bug.cgi?id=975444

Our GeckoView-based versions have the same problem as Firefox for Android: Google doesn't send us their tier1 version/content. For example the search page looks pretty bad.

**Comment by pocmo** [comment]
![search-results](https://user-images.githubusercontent.com/89638/36689177-f9d5877a-1b2e-11e8-97de-509086ae4f66.png)

**Comment by Sdaswani** [comment]
@mkaply any way you can help with this? We would like Google to treat us better when answering Google search queries. Ping me if you need more information.

**Comment by bbinto** [comment]
@bbinto to reach out to Andreas B. for the latest.

**Comment by mkaply** [comment]
Sorry, I missed this somehow.

We've been trying to get Google to give us better results, but the basic answer is "you don't have enough users for us to warrant testing so we won't turn it on."

Mike Taylor has been the most involved in trying to make this happen.

We did have an internal meeting to lay out the needs (with Mike's team), but we haven't gotten Google to be willing to make the change.

**Comment by vesta0** [comment]
Google has rolled out their new "Heirloom" mobile search experience to Firefox user agents on Android. It is a fast and modern search experience and a vast improvement over the mobile search experience that was previously served to Firefox on Android.
