### ISSUE TITLE
GeckoView: Use custom error pages

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2173]
Currently they look like this and seem to be in the "loading" state indefinitely.

![error-page](https://user-images.githubusercontent.com/89638/36730604-48010a20-1bc8-11e8-926a-c966edf3132e.png)

**Comment by snorp** [comment]
We have plans to bring the Fennec error pages to GV. Does that sound reasonable?

**Comment by pocmo** [comment]
> We have plans to bring the Fennec error pages to GV. Does that sound reasonable?

That's something product/UX should decide: @bbinto, @lime124, @brampitoyo 

What we do in the WebView version is: In OnReceiveError (WebViewClient) we determine what error happened and then load our own page via loadDataWithBaseURL() [+ we set a flag to avoid calling some of the callbacks when loading an error page].

**Comment by pocmo** [comment]
@snorp If we can't define our own error pages and have to use the ones included in GV... can we localize them? We are using a different set of languages than Fennec.

**Comment by brampitoyo** [comment]
We have already planned to match Fennec’s style and behaviour on our SSL info modals (#454).

Therefore, porting along Fennec’s error pages would also be a natural next step and a good idea.

**Comment by brampitoyo** [comment]
To add a very important caveat: if there’s a good reason why the language of our error pages are different from Fennec’s, we should localise our own. It’s just good to maintain design/content consistency as a general principle, and diverge/go our own way only when necessary.

**Comment by bbinto** [comment]
Are we scope-creeping here? 
Can we not re-use the existing Focus/Klar error pages or since we are moving engines, we need to create / user our own?

**Comment by pocmo** [comment]
> Can we not re-use the existing Focus/Klar error pages or since we are moving engines, we need to create / user our own?

That's what I like to do too. Currently GeckoView doesn't allow us to define our own.

**Comment by ekager** [comment]
We could do a similar work around like the Localized pages, but we just won't have the specific error message reported to us from GeckoView.

**Comment by ekager** [comment]
I can work on the error page if the generic custom error page is acceptable for now

**Comment by pocmo** [comment]
> We could do a similar work around like the Localized pages, but we just won't have the specific error message reported to us from GeckoView.

* With the workaround we'd suddenly write traces of the browsing session to disk (e.g. they contain URLs)
* The URL bar would show a local file URL instead of the actual URL (e.g. try focus:about)

I wonder what the state of getting something like loadDataWithBaseUrl() is? (ping @snorp)

**Comment by ekager** [comment]
Closing this for more general #2471
