### ISSUE TITLE
UI Test script for Taskcluster is using old directory to look for apk files to upload

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2181]
Since the SDK update, apk location has been changed.  execute-firebase-test.sh should be updated from 

--app="app/build/outputs/apk/app-focus-webview-debug.apk" \
--test="app/build/outputs/apk/app-focus-webview-debug-androidTest.apk" \

to

--app="app/build/outputs/apk/focusWebview/debug/app-focus-webview-debug.apk" \
--test="app/build/outputs/apk/focusWebview/debug/app-focus-webview-debug-androidTest.apk" \

**Comment by pocmo** [comment]
Our "preview release" script should be affected by this too.
