### ISSUE TITLE
CustomTabsCallback not reporting navigation events

### ISSUE THREAD

**Issue by CoderSpinoza** [mozilla-mobile/focus-android#2183]
I am developing an OAuth login module with custom tabs and currently experiencing an issue with <a href="https://developer.android.com/reference/android/support/customtabs/CustomTabsCallback.html">CustomTabsCallback</a>'s <a href="https://developer.android.com/reference/android/support/customtabs/CustomTabsCallback.html#onNavigationEvent(int, android.os.Bundle)">onNavigationEvent()</a> method on Firefox Focus for Android. The issue is that none of the navigation events are being reported from the method.
```
    /**
     * Sent when the tab has started loading a page.
     */
    public static final int NAVIGATION_STARTED = 1;

    /**
     * Sent when the tab has finished loading a page.
     */
    public static final int NAVIGATION_FINISHED = 2;

    /**
     * Sent when the tab couldn't finish loading due to a failure.
     */
    public static final int NAVIGATION_FAILED = 3;

    /**
     * Sent when loading was aborted by a user action before it finishes like clicking on a link
     * or refreshing the page.
     */
    public static final int NAVIGATION_ABORTED = 4;

    /**
     * Sent when the tab becomes visible.
     */
    public static final int TAB_SHOWN = 5;

    /**
     * Sent when the tab becomes hidden.
     */
    public static final int TAB_HIDDEN = 6;
```
The documentation specifies 6 navigation events, of which none are called in Focus. SInce the official doc specifies them and chrome supports all of them, it would be better if these events are also reported in Focus. Developers working on custom tabs would expect same events to be invoked on every browser that supports custom tabs protocol.

I have looked through the issues and found none regarding this functionality. It would be meaningful to start discussion about supporting CustomTabsCallback. :)

**Comment by pocmo** [comment]
Thank you for filing this. Our Custom Tab protocol implementation is indeed very basic at the moment. :)

**Comment by CoderSpinoza** [comment]
Thanks for your comment. Would it be okay if I contribute to this feature? :)

**Comment by pocmo** [comment]
Yes, that's definitely okay! :)

**Comment by Deeps-in** [comment]
Guys, is this issue fixed?. we are seeing navigationEvent not triggered.
