### ISSUE TITLE
Calculated average load time is getting smaller over time

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2192]
We are calculating the average load time like this:

> average = (average + new_value) / loads

However this value is getting smaller over time:

> Load: #1 : 4084 (Average: 4084.0)
> Load: #2 : 4320 (Average: 4202.0)
> Load: #3 : 2358 (Average: 2186.6666666666665)
> Load: #4 : 2355 (Average: 1135.4166666666665)
> Load: #5 : 2158 (Average: 658.6833333333333)

We calculated 658 - but we want (4084 + 4320 + 2358 + 2355 + 2158) / 5 = 3055.

I didn't know that you can add additional values to a calculated average but math.stackexchange[1] says:

> average += (new_value - average) / loads

And this actually seems to work:

> Load: #1 : 4084 (Average: 4084)
> Load: #2 : 4320 (Average: 4202)
> Load: #3 : 2358 (Average: 3588)
> Load: #4 : 2355 (Average: 3280)
> Load: #5 : 2158 (Average: 3056)

[1] https://math.stackexchange.com/a/957376

**Comment by ekager** [comment]
Oops, I'll get right on this
