### ISSUE TITLE
Missing in locales.py: hr, am

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2195]
See #2025 - Our new script detected that two locales are missing in our locales configuration script.

**Comment by pocmo** [comment]
FYI @Delphine: I'll add those two to our screenshot list.

**Comment by Delphine** [comment]
Thanks Sebastian! I kinda stopped tracking since Focus was on pause. It's good to see things are starting again -  I'll start tracking once more and open an issue for new locales going onwards :)
