### ISSUE TITLE
Ads on m.heise.de/9gag.com with GeckoView version (Block all Disconnect trackers)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2196]
On https://m.heise.de I see an overlay ad and a banner at the top of the page. Those do not show up in the WebView version or in Fennec's private browsing mode.

**Comment by sv-ohorvath** [comment]
Same on 9gag.com.

**Comment by eamsen** [comment]
We don't block Disconnect category trackers because they are neither mapped to the existing blocklists (ad, social, analytic, content) nor served as a separate blocklist by shavar. That's currently blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1459037.

**Comment by cpeterso** [comment]
I think we can close this bug. [Disconnect blocklist bug 1459037](https://bugzil.la/1459037) was fixed last week and I no longer see ads on m.heise.de or m.9gag.com.

**Comment by pocmo** [comment]
Yes, this looks good here too!
