### ISSUE TITLE
Add 'help' screen

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#22]

**Comment by pocmo** [comment]
iOS Version: Showing a SUMO page in a full-screen WebView. 

![ios_help](https://cloud.githubusercontent.com/assets/89638/23545245/c84278e4-fffa-11e6-8274-9cd19c21bdda.png)

**Comment by pocmo** [comment]
It looks like the iOS version is linking to:
* Focus: https://support.mozilla.org/en-US/kb/focus (I wonder why always en_US?)
* Klar: https://support.mozilla.org/products/klar (Which is empty in English for example)

**Comment by bbinto** [comment]
1) @jonisavage, could you please create another SUMO page just for Focus Android.

2) Once that's done, Sebastian, is it possible to manipulate the HTML page and hide the header/footer/comments?

Basically, only the content between
-- START ---
This page describes 
...
Version history
--- END ---

And while loading the page, show a loading spinner?

**Comment by pocmo** [comment]
For removing the header/footer I filed #283 and marked it as `nice to have`. As soon as we are close to feature complete we can try to do that.

**Comment by pocmo** [comment]
Bugzilla duplicate: https://bugzilla.mozilla.org/show_bug.cgi?id=1348553

**Comment by pocmo** [comment]
URLs:
* https://docs.google.com/spreadsheets/d/1utt7lgWClxyl6LdnkLFEtFZH7wf-nBg5MTbFfuZLgf4/edit#gid=0

**Comment by pocmo** [comment]
I added the URLs from the doc. If there's no URL for the current locale we fall-back to using English.
