### ISSUE TITLE
Audio keeps playing when you switch tabs/clear history

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2209]
Build: Klar+gecko 4.0

STR:
1. Play a youtube/vimeo video with the volume turned on.
2. Open/switch to a new tab.
3. Clear the history.

Expected results:
The audio should stop when you go to a different tab.
More important: audio should stop when you erase the history.

Actual results:
Audio keeps playing.

**Comment by sv-ohorvath** [comment]
There's issue #2118 for that.
This issue reproduces on devices with Android 6 or lower. e.g.: 
HTC Desire 820 (Android 6.0.1)
Samsung Galaxy Note 4 (Android 5.0.1)

**Comment by pocmo** [comment]
Okay, now after fixing #2118 I see this on my device happening too!

**Comment by pocmo** [comment]
GeckoView bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1443105

**Comment by ekager** [comment]
Is this closed by #2261 ?

**Comment by ekager** [comment]
I think this is solved. Please reopen if still an issue!
