### ISSUE TITLE
(tt, Tatar) missing placeholder in translation

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2211]
Error when importing strings:

> Error: * [values-tt/strings.xml] missing placeholder in translation, key: preference_autocomplete_preinstalled_summary

This seems to be a typo. Translated string is:
> 450'дән артык мәшһүр сайт өчен %1$'та автотөгәлләүне кабызу.

Placeholder should be %1$s instead of %1$

**Comment by pocmo** [comment]
CC @Delphine

**Comment by Delphine** [comment]
Thanks, I've corrected this in Pontoon!
