### ISSUE TITLE
Clear Visited CSS feature breaks / throws JS errors in Chromium webview

### ISSUE THREAD

**Issue by calvinf** [mozilla-mobile/focus-android#2217]
When Firefox Focus opens pages on a website in the Android webview, it attempts to use a feature called "Clear Visited CSS" to alter the CSS selectors in any CSS files (loaded via `<link>`) to remove any selectors with `:visited` in them.

[Source](https://github.com/mozilla-mobile/focus-android/blob/5be3f3016a747e648101614c61115465bee51545/app/src/webview/java/org/mozilla/focus/webview/FocusWebViewClient.java#L43-L105)

In Chromium 64 webviews, this code fails to execute properly as the code injected into the webview does not have permission to access or alter `cssRules` for some of the stylesheets (presumably the ones without CORS headers / `crossorigin='anonymous'`).

The specific error I'm seeing in reports is: `"Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules"`. It surfaces from [here](https://github.com/mozilla-mobile/focus-android/blob/5be3f3016a747e648101614c61115465bee51545/app/src/webview/java/org/mozilla/focus/webview/FocusWebViewClient.java#L52) when the "Clear Visited CSS" script does not have permissions to access or manipulate the stylesheet.

Example User Agent: 
* `Mozilla/5.0 (Linux; Android 8.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.0.2 Chrome/64.0.3282.123 Mobile Safari/537.36`

I'm only seeing this issue on UA's containing "Focus/" and "Chrome/64" -- perhaps the Chromium webview had a change recently that started causing this error to surface?

Would it be possible to:
* Fix the code to _not_ run against stylesheets for which the webview JS does not have permission to edit the CSS?  (e.g. stylesheets without `crossorigin="anonymous"`)
* Update the code to catch these JS errors (avoid them leaking out to the window error handler)?

This JS error throws on pages like the Amazon product detail page ([example](https://www.amazon.co.uk/gp/aw/d/B004M2K6KG)).

**Comment by pocmo** [comment]
Thank you for this bug report!
