### ISSUE TITLE
GeckoView: Download without permission shows error dialog

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2221]
When trying to download a file an error dialog shows up: "could not be saved, because an unknown error occured. Try saying to a different location".

**Comment by pocmo** [comment]
Even after manually allowing storage access the dialog shows up.

**Comment by pocmo** [comment]
![download-dialog](https://user-images.githubusercontent.com/89638/36973410-2accf4be-2073-11e8-9e21-8bf7c6838146.png)

**Comment by ekager** [comment]
Also related to https://github.com/mozilla-mobile/focus-android/issues/2097

**Comment by bbinto** [comment]
@ekager will verify if this has been fixed and close accordingly.

**Comment by ekager** [comment]
I am able to download files, please reopen if you find this is still a problem.
