### ISSUE TITLE
Add bookends in the client code for NimbleDroid testing

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2235]
For performance measurement, we need to collect the time taken to load a webpage by measuring the time between Onpagestop and Onpagestart.

We will follow Example 1 in http://docs.nimbledroid.com/androidUserGuide.html#bookending-code , and the bookends can be added in https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/observer/AverageLoadTimeObserver.java

**Comment by npark-mozilla** [comment]
@pocmo Since the bookend pair can be used only once, we have to name them uniquely since the UI test will visit websites multiple times.
- Is the flavor/variant name visible inside AverageLoadTimeObserver.java?
- Is the requested URL visible inside AverageLoadTimeObserver.java?
- If the URL is not visible, I was thinking about creating a simple iterator like:
```
private static int i = 0 (in the AverageLoadTimeObserver definition)
Log.i("NimbleDroidV1", "Scenario.begin visitURL " + i)
Log.i("NimbleDroidV1", "Scenario.end visitURL " + i)
i += 1
```

would this work? if not we can look into adding bookends in the test script

**Comment by pocmo** [comment]
> Is the flavor/variant name visible inside AverageLoadTimeObserver.java?

Yes. The gradle build generates a BuildConfig class that contains those values as static members.

> Is the requested URL visible inside AverageLoadTimeObserver.java?

Yes. You can get it by calling session.getUrl().getValue().

> If the URL is not visible, I was thinking about creating a simple iterator like:

This sounds good too!
