### ISSUE TITLE
Update taskcluster script to submit builds to nimbledroid

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2237]
The test needs to be run on two variant:

focusWebviewDebug
klarGeckoviewDebug

The instruction is here: http://docs.nimbledroid.com/androidUserGuide.html#simple-example-curl

Will provide more details on json key and other parameter values shortly

**Comment by bbinto** [comment]
Tell us why/when you need this @npark-mozilla

**Comment by pocmo** [comment]
@npark-mozilla This is already done, isn't it?
