### ISSUE TITLE
Unify "Share" and "Open with.."

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#224]
@antlam:
> You know the share sheet on Google Photos?
> I wonder if we can unify the menu options of share + open with... with a custom share sheet
> We can have less options in the menu

**Comment by feikname** [comment]
They do 2 different things, so they should be 2 different buttons, in my opinion. Also, the "Open with..." item is very handy, and unifying it to be included into "Share" would remove this convenience.

**Comment by antlam** [comment]
@feikname that's a good point. I think we need to think more about this from that perspective :)

**Comment by Benestar** [comment]
So currently there are three different buttons with similar functionality: "Share...", "Open with Firefox" and "Open with..." In my opinion these could be collapsed into one single "Share" button or even just the common share icon for sake of simplicity.

**Comment by Primokorn** [comment]
@Benestar "Share" doesn't allow me to choose my other browsers while I can select them from the "Open With" dialog.

In a nutshell:
* Unify "Open with Firefox" and "Open with..." => OK
* Unify "Open with Firefox", "Open with..." and "Share" => please NO!
