### ISSUE TITLE
Is signing required?

### ISSUE THREAD

**Issue by paulrouget** [mozilla-mobile/focus-android#2244]
I'm trying to build Firefox Focus for the first time, and I get errors about signing:

First, when I press the Play button in Android Studio, I see this:
<img width="427" alt="screen shot 2018-03-07 at 12 12 08" src="https://user-images.githubusercontent.com/373579/37089463-f4a14432-2200-11e8-88a9-612c8449e774.png">

Then I try to fix it but it just shows these 2 screens:
<img width="289" alt="screen shot 2018-03-07 at 12 12 22" src="https://user-images.githubusercontent.com/373579/37089464-f4d28b00-2200-11e8-89b6-f5643f6262cc.png">
<img width="773" alt="screen shot 2018-03-07 at 12 12 30" src="https://user-images.githubusercontent.com/373579/37089465-f4fc4076-2200-11e8-82a6-c5dcda8f5880.png">

And if I run it, I get this error:
<img width="404" alt="screen shot 2018-03-07 at 12 13 14" src="https://user-images.githubusercontent.com/373579/37089466-f5298e28-2200-11e8-8df5-b7d79957b124.png">

How do I bypass this?

**Comment by pocmo** [comment]
Make sure to select the focusWebViewUniversal build flavor in Android Studio. It seems like you are trying to build the Beta variant. And this one indeed needs signing.

![image](https://user-images.githubusercontent.com/89638/37090716-b2570bac-2205-11e8-86ec-4849a28ad9e4.png)

**Comment by paulrouget** [comment]
It works. Thank you.
