### ISSUE TITLE
How to build without Android Studio?

### ISSUE THREAD

**Issue by paulrouget** [mozilla-mobile/focus-android#2245]
The doc says to do:

```
./gradlew clean app:assembleFocusWebviewUniversalDebug
```

What the next thing to do?

**Comment by pocmo** [comment]
See #2244. Opening the project in Android Studio and selecting the same build variant should be enough to set this up.

**Comment by paulrouget** [comment]
Is using Android Studio necessary? Can I build directly from the command line?

I have not experience with Android Studio and Gradle.

**Comment by pocmo** [comment]
@paulrouget It's not necessary. You can build/install from the command line by using "gradlew"
