### ISSUE TITLE
Change the UI Tests to use internal site

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2251]
Currently four test cases are failing intermittently while loading external site
- TrashTest()
- SystemBarTest()
- SimpleToggleTest()
- MismatchTest()

They should be using internal sites for better reliability.

**Comment by bbinto** [comment]
@npark-mozilla - how important is this? Px?

**Comment by npark-mozilla** [comment]
I'd say this is P3

**Comment by npark-mozilla** [comment]
Most of the sites are now using internal sites, with the exception of web search.
