### ISSUE TITLE
Klar+Geckoview need to block the Disconnect trackers

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2254]
Going to www.mozilla.org on Focus Webview will show 1 blocked tracker, but visiting the same site on Klar Geckoview shows that blocked tracker is 0.

**Comment by npark-mozilla** [comment]
esawin says:
_GV currently does not allow blocking trackers from the "Disconnect" category (https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json#L8970) which could explain the differences.  we're looking into a good solution on how to handle that category (block by default, expose it as a category in the API or distribute its contents  across the other  categories accordingly)_

**Comment by npark-mozilla** [comment]
BTW, mozilla site adheres to DNT header sent out by geckoview, and that is why it does not issue the tracker.

**Comment by pocmo** [comment]
I think this is. a duplicate of #2196 now.
