### ISSUE TITLE
Create a way to induce specific web connection errors

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#228]
With commit https://github.com/mozilla-mobile/focus-android/commit/243073f149b9cc9be366fa24763bba814b579e08, error messages show up when connection errors are present.  We need a way to induce each type of error if we need to check the localization of the page.

**Comment by pocmo** [comment]
@ahunt: Would it be possible to create a custom protocol that shows the error pages? A bit like about:neterror in Fennec.

**Comment by ahunt** [comment]
Yeah - a custom protocol might be useful for certain cases anyway.

Another option might be to find the WebView, get it's WebViewClient, and call onReceivedError() with the desired error code. That's hacky and specific to the webview edition of focus though.

**Comment by ahunt** [comment]
I've got a first draft. WebView does weird things when you try to use about: pages, so I'm using about2:neterror as the provisional URL.

Do we want any specific syntax? For now I'm using about2:neterror?wkerror=N, where N corresponds to the equivalent webkit error code as defined in:
https://developer.android.com/reference/android/webkit/WebViewClient.html

(Note: we don't yet support all those errorcodes, our list is at the top of ErrorPage.java)

**Comment by pocmo** [comment]
> Do we want any specific syntax? For now I'm using about2:neterror?wkerror=N, where N corresponds to the equivalent webkit error code as defined in:
https://developer.android.com/reference/android/webkit/WebViewClient.html

As long as we are only using this internal and are not exposing this to users I don't think it's important. How about
- focus:error?wkerror=-12
- or just: error:-12

**Comment by npark-mozilla** [comment]
i was gonna say about2:wkerror=N but I'm fine with anything

**Comment by ahunt** [comment]
@npark-mozilla It's landed with "error:<CODE>" syntax (that's simplest to implement, so least risky too)

The list of supported codes is here:
https://github.com/mozilla-mobile/focus-android/blob/b561c6e8c001ca2e53d219e3efbaa01c9a49f753/app/src/webkit/java/org/mozilla/focus/webkit/ErrorPage.java#L23

**Comment by npark-mozilla** [comment]
I see the customized error msgs now at will, nice!
