### ISSUE TITLE
Use GeckoView API to determine whether context menu is displayed for an image

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2283]
In #2272 we landed code for looking at the URL and guessing whether the context menu we are supposed to show is for an image. This is not 100% reliable and the GeckoView team will add an API for us. This is tracked by: https://bugzilla.mozilla.org/show_bug.cgi?id=1445240

Let's use this once the new API is available.

**Comment by pocmo** [comment]
There's no an additional parameter (elementType) for that :)

**Comment by ekager** [comment]
Should be closed by #2380 :)
