### ISSUE TITLE
Klar+GeckoView: add settings UI to enable/disable/configure fingerprinting protection

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#2289]
There are a number of knobs that we may want to expose in Klar's settings UI, such as:

* Enable basic protection (privacy.resistFingerprinting pref)
* Block canvas (without prompt) unless triggered by user input (independently from basic protection)

We will want some UX input on this feature.

Adding a GeckoView API to enable/disable/configure fingerprinting protection is [Firefox bug 1445400](https://bugzilla.mozilla.org/show_bug.cgi?id=1445400).

**Comment by cpeterso** [comment]
Some existing Klar fingerprinting issues that could be fixed by this feature:

meta bug #1344
Canvas #996
WebGL #2111

**Comment by cpeterso** [comment]
Canvas fingerprinting protection is a new feature that is not available in WebView, so it doesn't need to be in the initial Klar+GeckoView release (6.0).

**Comment by lobontiumira** [comment]
The fingerprinting protection is now available and working on all Focus builds.
I'll close this ticket.

**Comment by tomrittervg** [comment]
@lobontiumira  Would you be able to link to a commit or PR this was address in?

**Comment by cpeterso** [comment]
IIRC, this feature request was originally about setting Gecko's `privacy.resistFingerprinting` pref. Since this issue was filed, Firefox and Focus now support a fingerprinting blocklist. So the functionality is not the same, but addresses some of the same concerns.
