### ISSUE TITLE
Focus app instance from customTabTest persists, and closing from apps list fails the next test in queue

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2292]
On today's Firebase run, it appears that RestartTest is consistenly failing, and the video shows that it's because there is another instance of focus runnung.  It uses plain_test.html, and it's only being used on AddtoHSTest and CustomTabTest.  I suspect the Focus app instance from CustomTabTest persists beyond the test duration, since it starts with a different activityTestRule than others.

Is this something that we should be worried about? Or is this a new app behavior, and we just simply need to close it from the recent apps list?

![screen shot 2018-03-13 at 5 05 26 pm](https://user-images.githubusercontent.com/6930774/37370074-7a6b4ef2-26e1-11e8-8612-f3d4cdc42858.png)

**Comment by pocmo** [comment]
If one of them is a custom tab then this is intentional. We fixed #770 and now custom tabs and the regular browser are separate things. It looks confusing here because in our test it is Focus that is opening a custom tab in itself. Usually the other entry in "recent apps" would look like the app that opened the custom tab.

**Comment by pocmo** [comment]
Here is a good example.

All three entries here are actually Focus displaying a website. Two of them show a custom tab (launched from IRCCloud and Yahnac) and the other one is just the regular Focus browser.

![customtabs](https://user-images.githubusercontent.com/89638/37396530-747be248-2779-11e8-987e-2f9e92d8e582.png)

**Comment by npark-mozilla** [comment]
If I add UI actions at the end of CustomTabTest to close the custom tab instance from the recent apps list, the next test fails to start, with the error of : “java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1521040723603 and now the last time the queue went idle was: 1521040768605. If these numbers are the same your activity might be hogging the event queue.
”  Logcat: https://pastebin.mozilla.org/9079999

**Comment by Sdaswani** [comment]
@npark-mozilla to see if this is fixed or not.

**Comment by npark-mozilla** [comment]
actually now I remember that @pocmo will look at this issue because of the above issue of failing to start the next test.  But with the other custom tab bug fix, I'll retry to see whether above is still the case.

**Comment by Sdaswani** [comment]
@pocmo feel free to have @boek or @ekager look at this based on your workload.

**Comment by ekager** [comment]
Is this still failing @npark-mozilla ? I took a look today and it seemed if I opened a custom tab + ran RestartTest locally it is passing, but I may have misunderstood the current problem?

**Comment by npark-mozilla** [comment]
Ah my bad, this was actually mysteriously fixed a couple weeks back, and I based my previous uitestfix on it. This issue should be closed.

**Comment by npark-mozilla** [comment]
Reopening this issue. this happens on Nexus 5X API 24 simulator again.
