### ISSUE TITLE
Security icons are not tinted anymore

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2294]
In Custom Tabs the calling application can set the toolbar color. Depending on the color we either choose white or black for the text and icons. Our security icon (globe, lock, ..) are not tinted anymore. Maybe this was caused by the introduction of the security popup.

**Comment by pocmo** [comment]
![tint](https://user-images.githubusercontent.com/89638/37396833-4bf2f388-277a-11e8-80a8-23d104e4d6ed.png)

**Comment by pocmo** [comment]
@ekager Do you have time to look at this?

**Comment by ekager** [comment]
Yes I’ll do this today
