### ISSUE TITLE
Custom Tabs: Support bottom toolbar

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2296]
From #610 and #1870.

Third-party apps can define that they want to show a bottom toolbar with additional action items. In practice I haven't seen this being used by any app. Probably not worth implementing for now.

**Comment by hjoshi123** [comment]
@pocmo Is this still open? Can I work on this?

**Comment by pocmo** [comment]
@hjoshi123 We haven't made a decision yet whether we want to add this (We'll add a priority label in this case).

Please take a look at the issues with label "good first issue" or "help wanted":
* https://github.com/mozilla-mobile/focus-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
* https://github.com/mozilla-mobile/focus-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
