### ISSUE TITLE
Custom Tabs: Allow copying URL

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2297]
From #610 and #1870.

In a Custom Tab you can't edit the URL. FF and Chrome let you long-press to copy the current URL. Do we want to do this too? At least on my device I can copy the URL in a custom tab by going to the menu, select "share" and then "copy to clipboard".

**Comment by brampitoyo** [comment]
Yes. We definitely want to do this. When you long-press the URL, we should show a toast that says “URL copied”.

**Comment by bbinto** [comment]
@pocmo any idea if we should do this in combination with Fenix/Android components?

Also, how much work would it be?

**Comment by pocmo** [comment]
@bbinto This could be something we do here before introducing the component.

**Comment by ekager** [comment]
Hm @boek would this be similar to/conflict with #2498 ? Long press URL in custom tab should copy the URL?

**Comment by pocmo** [comment]
We might want to transform this in a context menu (@brampitoyo ?).

If not then you can either use MainActivity.isCustomTabMode() or ask the session object whether you are in a custom tab.

**Comment by brampitoyo** [comment]
@pocmo Although having a context menu would clarify the intent, it would also require the user to take one more step, and require us to define a new context menu. I’d say that the copy URL action should happen instantly, on long-press.

**Comment by bbinto** [comment]
@pocmo + @brampitoyo is this UX-approved and good to go for eng?

**Comment by bbinto** [comment]
@ekager could you give an estimate based on Bram's latest comments, are will eyeballing an M?

**Comment by ekager** [comment]
I think a S. Do we want to pull this into 6.0?

**Comment by bbinto** [comment]
> I think a S. Do we want to pull this into 6.0?

I'd <3 that

**Comment by npark-mozilla** [comment]
@ekager just to double check - should it do both 1. copying the URL to clipboard and 2. making entry in the 'Add custom URL' list?  The issue looks to me that it's only talking about copying the URL to clipboard.

**Comment by ekager** [comment]
Yes this issue is just talking about copying the URL to the clipboard while in a custom tab.
