### ISSUE TITLE
Custom Tabs: Consider showing page title in URL bar.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2298]
User Benefit / Why
- Provide more information about the website users are visiting
- Be consistent with our other products + custom tabs

From #610 and #1870.

Chrome and Firefox show the page title in the URL bar in a Custom Tab. Do we want to do that too?

**Comment by pocmo** [comment]
Firefox:

![ct-ff](https://user-images.githubusercontent.com/89638/37408994-8cfbe5d8-279d-11e8-976c-579d8ca93e7e.png)

**Comment by pocmo** [comment]
Chrome:

![ct-chrome](https://user-images.githubusercontent.com/89638/37409005-93c2d6a6-279d-11e8-9262-82878046490c.png)

**Comment by pocmo** [comment]
The app might be able to control this by setting NO_TITLE, SHOW_PAGE_TITLE;

* https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.html#NO_TITLE
* https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.html#SHOW_PAGE_TITLE

**Comment by shikhart98** [comment]
Can I work on this issue?

**Comment by shikhart98** [comment]
Okay 👍

**Comment by bbinto** [comment]
@brampitoyo quick input on the UI @pocmo suggested?

@pocmo is this touching the regular URL/address bar code for Focus?

**Comment by brampitoyo** [comment]
For sure. It makes a lot of sense for us to be consistent with Firefox and show the site name and URL on our custom tabs.

I do notice that the “X” button on the Firefox UI is far too large, and the font size is a bit too small. Chrome’s icon and font sizes are good for us to follow. It’s just that the font colour that Chrome uses isn’t consistent with the font colour used on the system status bar. On this, we should aim to match.

**Comment by pocmo** [comment]
@pocmo is this touching the regular URL/address bar code for Focus?

Yes, we would need to support two modes. If this doesn't have high priority then we could wait until our "toolbar" component is ready and use that one in Focus. The toolbar component will be able to support different modes like that.

**Comment by pocmo** [comment]
@bbinto Depends on the fenix feature prioritization.. :) I think it will take some time until the component has feature-parity with Focus. So, maybe in Q3 we can make the switch to the component.

**Comment by Sdaswani** [comment]
@pocmo @csadilek can one of the Focus engineers start on this component? We are keen to get this into Focus.

**Comment by csadilek** [comment]
@Sdaswani definitely! This would require bringing the toolbar component to Focus which would be great, imo.

**Comment by Sdaswani** [comment]
@vesta0 I suggest someone on the Focus team work on this in this Sprint - is that cool? Maybe @ekager's first component?

**Comment by vesta0** [comment]
@Sdaswani that would be good. Sounds like the toolbar component is ready and can be brought over to Focus - is that correct? If so then @ekager do you want to pick this up?

**Comment by Sdaswani** [comment]
No @vesta0 sounds like we have to 1) integrate the toolbar component and then 2) maybe make some changes. I think @ekager can pick this up if she is free.

**Comment by ekager** [comment]
I can pick this up after my current ticket in this sprint

**Comment by lobontiumira** [comment]
On the latest RC 93.1.1, the custom tab displays the page title in the URL bar.
I'll close this issue.
