### ISSUE TITLE
Custom Tabs: Support custom animations

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2299]
From #610 and #1870.

A third-party app can define enter/exit animations when displaying (and leaving) a custom tab.

It would be interesting to know how many apps request that. We are collecting telemetry about custom tab features apps want to use.

**Comment by bbinto** [comment]
@pocmo any idea if we should do this in combination with Fenix/Android components?

Also, how much work would it be?

**Comment by pocmo** [comment]
M; Something we could do earlier without the components. Might be worth looking at telemetry whether apps actually request custom animations.

**Comment by bbinto** [comment]
Here some stats about what extras are currently being used: https://sql.telemetry.mozilla.org/queries/4950/source#10134
