### ISSUE TITLE
Add 'Your Rights' screen

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#23]

**Comment by pocmo** [comment]
@antlam: I can't find a "Your Rights" screen in Focus for iOS anymore (Only About/Help). Has this been removed?

**Comment by pocmo** [comment]
There's still code to go from the "About" page (See #21) to a "Your Rights" screen. But I do not see it in the app anymore.

**Comment by pocmo** [comment]
Okay, found it. The about screen is scrollable... :)

![your_rights](https://cloud.githubusercontent.com/assets/89638/23565499/1c4eea1e-004e-11e7-9aca-f10ae2227043.png)

**Comment by antlam** [comment]
Let's make sure we keep the text styles, and padding the same across all 3 pages here. The "About" page is the styling we should follow.

On iOS we have an issue to make that all consistent too.
