### ISSUE TITLE
Custom Tabs: Support pre-warming

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2300]
### User Benefit
- Faster loading of links clicked on in third-party apps

---
From #610 and #1870.

A third-party app can request to "pre-warm" the browser before it displays a custom tab. This will make launching the custom tab faster at a later time - because the engine is already running.

I doubt that we can do this with WebView. But with GeckoView that might be possible. We are doing this in Fennec already.

**Comment by bbinto** [comment]
@pocmo any idea if we should do this in combination with Fenix/Android components?

Also, how much work would it be?

**Comment by pocmo** [comment]
We can't really do that with WebVIew. So this is something we could only do with GeckoView. This is also something we could try before introducing components.

**Comment by bbinto** [comment]
Thanks. @pocmo -- something maybe for the 7.0 feature wishlist.

We should still clearly define user benefit. I'll need to review the telemetry for Custom Tabs, no real uptake lately.

**Comment by bbinto** [comment]
> We can't really do that with WebVIew. So this is something we could only do with GeckoView. This is > also something we could try before introducing components.

@pocmo is this already available to us to use in GV?

**Comment by vesta0** [comment]
@pocmo does this issue have a corresponding GV bug open?

**Comment by pocmo** [comment]
Not that I know of. A new API on the GV may not necessarily be needed. Let's talk to the GV team and ask them what they recommend doing.

For reference this is what Fennec does:
https://dxr.mozilla.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/customtabs/GeckoCustomTabsService.java

**Comment by vesta0** [comment]
@cpeterson just wondering if GV has looked into this or if there is a bug open?
