### ISSUE TITLE
Bundled autocomplete url link broken

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#2303]
microsoftonline.com is one of the autocomplete urls, and it doesn't load anymore (checked from a desktop browser).

More general problem is, do we ever update that list to prune dead links?

**Comment by pocmo** [comment]
> More general problem is, do we ever update that list to prune dead links?

We haven't so far. However there is one update in the making right now. Those autocomplete lists are one of the things that I would like to move to a library - and then test/verify/(propose update?) in automation.

**Comment by bbinto** [comment]
see #2252 for another update to the list

**Comment by Sdaswani** [comment]
Fixed in https://github.com/mozilla-mobile/focus-android/pull/2366
