### ISSUE TITLE
Add upload script for nimbledroid performance measurement

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#2322]
On every checkin to master, we should upload the app apk and test apk to nimbledroid.

The upload itself is pretty simple, which can be done via a curl command:
curl -v -F apk=@app.apk -F test_apk=@androidTest.apk -F auto_scenarios=false -u "your secret api key": https://nimbledroid.com/api/v2/apks

We need to decide:
- where to store the api key (probably in TC secret)
- which TC task to build the app apk test apk for both webview and geckoview. (i.e. should we do it inside generate_ui_test_task or should we create a new task?  currently it only builds webviewUniversalDebug within the task, so another gradle job should be added)
- which TC task to actually upload to nimbledroid (probably inside generate_ui_task again?)

Unfortunately nimbledroid executes every test, instead of a specific UI test, so it might take more time than needed to obtain the performance data.  If it's not too much hassle, would it make sense to create a build variant that ONLY runs nimbledroid related UI test script(s)?

@pocmo when you're done with 4.1, could we discuss above issues?

**Comment by pocmo** [comment]
Yes!

Quick answers:
* API Key -> TC secrets
* Build & Upload in new, separate task with same dependencies as UI test task
* Build variant: I would like to avoid that. More build variants slows down builds. I want to kill our coverage build type too: #2313

**Comment by npark-mozilla** [comment]
TC secret is now added, will work on creating a separate task.
