### ISSUE TITLE
Add crash reporting via Sentry

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2326]
Why
- GeckoView cannot leverage GPS crash reporting
- Baseline for comparing GPS crash reporting for WebView vs. Sentry crash reporting for GeckoView
- Provide stable product for Gecko-view powered Klar
- Better crash handling (e.g. search for crashes etc.)
- With GeckoView we will need our own custom crash reporting and cannot rely on Google Play crash reporting anymore.

What/ Requirements:
* [x] Enable crash reporting with sentry for release builds
* [x] Use sentry instance hosted by Mozilla
* [ ] Make sure that this works with GeckoView crash reporting ([Bug 1433968](https://bugzilla.mozilla.org/show_bug.cgi?id=1433968)) and native crashes show up in Sentry
* [x] Make Sentry DSN configurable at build time (like Adjust token)
 * [x] Configure taskcluster to pick up Sentry DSN from secrets service and configure build
* [x] Figure out with product/ux/legal if/what user-facing toggles are needed
* [x] Document in wiki (see https://github.com/mozilla-mobile/firefox-ios/wiki/Crash-Reporting-with-Sentry)
* [ ] Look into reporting to Sentry AND Google Play crash reporting

Acceptance Criteria (how do I know when I’m done?)
- Crash reporting in Sentry is accurate
- APT to view and analyze crash reporting
- Receiving crash reporting by default (in Klar, currently crash reporting is connected to "share usage data" which is off by default in Klar)

**Comment by Sdaswani** [comment]
@bbinto Sentry is approved in our mobile products - can you confirm we don't need a separate toggle for this?

**Comment by Sdaswani** [comment]
If we do need a toggle @bbinto then we may need UX work from @brampitoyo

**Comment by mcomella** [comment]
Firefox TV's requirements are fewer but our Sentry PR is up: https://github.com/mozilla-mobile/firefox-tv/issues/429

**Comment by ekager** [comment]
@Sdaswani looks like we want to receive crash reporting by default, but since Klar is opt-in for all usage-data, we may need to create a new opt-out toggle for Focus+Klar.

**Comment by Sdaswani** [comment]
Can we just shut it off for Klar @ekager ?

**Comment by ekager** [comment]
Right, it can be shut off, but then we won't have crash reporting for Klar (and GeckoView) unless people opted in to usage data. I'm understanding from the above bullets that we want Crash reporting on by default, so we will need to introduce a new toggle. Is that right, @bbinto ?

**Comment by bbinto** [comment]
I believe we agreed on that during Portland: for now as it relates to Klar and Focus, it should be included in the general data collection toggle, which indeed would not provide crash reporting for klar by default. For now, that's fine.

**Comment by ekager** [comment]
Closing this and opening new issues for:
-Make sure that this works with GeckoView crash reporting (Bug 1433968) and native crashes show up in Sentry
and 
-Look into reporting to Sentry AND Google Play crash reporting
