### ISSUE TITLE
Add an about:telemetry to show current pings

### ISSUE THREAD

**Issue by fbertsch** [mozilla-mobile/focus-android#2328]
_Added by @bbinto_

**Why/User Benefit**
- Inform the user of what events and information we collect about them

**What**
- An about:telemetry page listing the current pings to our servers

**Acceptance Criteria (how do I know when I’m done?)**
- User can access this page
- It lists all pings

----
This is not only a user-friendly feature (what am I actually sending?) but really helps during development and testing.

**Comment by pocmo** [comment]
Note that currently the telemetry library does not archive pings. We only store them to disk to "queue" them. Once uploaded we remove them again. This behavior would need to be changed (or made configurable) in the telemetry component.

**Comment by bbinto** [comment]
De-prioritizing due to amount of work and timing
