### ISSUE TITLE
Support blocking of 3rd party cookies

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2330]
Why
- Provide additional tracking protection for users
- Protects users during an active session

What
- User can turn on 3rd party cookie blocking

Acceptance Criteria (how do I know when I’m done?)
- 3rd party cookies are blocked and off by default
- User can turn this feature on/off via settings
- Toggle off in menu will turn off 3rd party cookie blocking as well
- Probes to see if users have setting turned off/on

@bbinto to check with Softvision to test blockage for top 10 Alexa websites

-----
More info:

We do block trackers and some ads, but not 3rd party cookies by default.

After talking to @snorp and @pocmo, it seems to not be a huge effort to include this, and promote it once GDPR goes into effect. 

Will it cause more breakage?

Hoping for 5.0

**Comment by bbinto** [comment]
@pocmo to check if WebView API provides this (5.0), otherwise we'll do it in 6.0 with GeckoView

**Comment by ekager** [comment]
Third party cookies API for WebView - https://developer.android.com/reference/android/webkit/CookieManager.html#setAcceptThirdPartyCookies(android.webkit.WebView,%20boolean)

**Comment by ekager** [comment]
GeckoView request on Bugzilla - https://bugzilla.mozilla.org/show_bug.cgi?id=1447390

**Comment by brampitoyo** [comment]
Just checking in to let you know that we may need a Settings control for Cookies.

Thankfully, it’s pretty straightforward. Cookies is an item that belongs under “Privacy” (in current structure) or under “Privacy & Security” (in future structure, as discussed in #2357).

Cookies can have three values under it:

1. Enabled
2. Enabled, excluding 3rd party
3. Disabled

We will follow Fennec’s implementation for UX – it’s a simple modal menu.

**Comment by Sdaswani** [comment]
@bbinto please decide if this is going in 5.0 or not.

**Comment by bbinto** [comment]
I’d love to get the in for 5.0.Does @BrianNJones need to provide strings?On Mar 27, 2018, at 11:59 AM, Susheel Daswani <notifications@github.com> wrote:@bbinto please decide if this is going in 5.0 or not.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Sdaswani** [comment]
Assigning to @BrianNJones for strings.

**Comment by brampitoyo** [comment]
@Sdaswani I don’t think we need help from @BrianNJones on this, since the strings is straightforward. Use what I’ve suggested up there.

**Comment by brampitoyo** [comment]
Summarising my conversation with @ekager about the cookie blocking state in each menu item:

1. Enabled = no cookies blocked
2. Enabled, excluding 3rd party = some cookies blocked
3. Disabled = all cookies blocked

**Comment by brampitoyo** [comment]
Hi @ekager, the behaviour you noted is as expected.

Users who have turned their cookies off do expect their login state to change. If they were signed in when cookies is enabled, they’re not going to be signed in when cookies are disabled.

When cookies is re-enabled, I would expect whatever problems I’ve had to be fixed. This means that the cookies that Focus had stored should be restored, as long as the garbage bin icon hadn’t been tapped.

**Comment by brampitoyo** [comment]
Additionally, this is how the TP toggle should behave in response to different cookie states.

* Cookie states does not impact the TP toggle. Whatever cookie state you have set, TP toggle is set to `on` by default.
* On the other hand, the TP toggle _does_ impact cookie states. Whatever cookie state you have set, when TP toggle is set to `off`, cookie state must be set to `enabled`.

By accepting all cookies, we will ensure that website problems have a higher chance to be solved when the TP toggle is turned `off`.

**Comment by BrianNJones** [comment]
@brampitoyo I think we do need new strings. We're already using a "Block xxx xxx" construction for TP. This structure aligns with that:

Block cookies
- Yes
- Block 3rd-party cookies only
- No

Also not confident most users will understand reference to 3rd-party cookies.

**Comment by ekager** [comment]
Looks good to me! @BrianNJones and @brampitoyo are these the final strings for this feature?

**Comment by brampitoyo** [comment]
I agree with @BrianNJones about using the “Block” verbiage to match with other menu items. Let’s use that.

I similarly worry about user understanding of 3rd-party cookies. [SUMO wrote a great plain language explanation](https://support.mozilla.org/en-US/kb/disable-third-party-cookies):

> Third-party cookies are cookies that are set by a website other than the one you are currently on. For example, cnn.com might have a Facebook like button on their site. That like button will set a cookie that can be read by Facebook. That would be considered a third-party cookie.
>
> Some advertisers use these types of cookies to track your visits to the various websites on which they advertise. If you are concerned about this, you can disable third-party cookies in Firefox.

I wonder if there’s a way for us to include a link to this SUMO article, or to shorten the explanation down to a few words?

But anyway, since the string now looks okay, let’s close this issue and open another one to talk about how to best explain this concept.

**Comment by sv-ohorvath** [comment]
Verified this feature on the Focus Beta v5.0 build.
Devices:
Sony Xperia Z5 Premium (Android 6.0.1)
Google Pixel (Android 8.1.0)

**Comment by jonisavage** [comment]
We've written a SUMO article for this feature and linked it from the "What's New..." page: https://support.mozilla.org/en-US/kb/block-cookies-firefox-focus-android

**Comment by ekager** [comment]
Hey @brampitoyo should we open a new issue to include a link to the cookies SUMO page in the Settings menu?

**Comment by brampitoyo** [comment]
@ekager Will you post a screenshot of what this menu item looks like currently? Just to get an idea of where the link to the SUMO page can go on the UI.

**Comment by brampitoyo** [comment]
My proposal: when you tap on “Block cookies”, instead of a modal menu item, a separate page should appear.

This page will give us some space to include a link to SUMO, below all the options.

<img width="791" alt="cookies 2x" src="https://user-images.githubusercontent.com/51007/39460428-6180599a-4d57-11e8-9ffb-d9202ce0e33e.png">

[Google’s material design guidelines](https://material.io/guidelines/patterns/settings.html#settings-labels-secondary-text) wrote:

> Settings that require longer explanations may add a description on a second screen. 

<img src="https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B1PhAWhtrRTraUx2VEtZTXlyaWs/settings-switch2.png" width="360">

What do you think?

**Comment by brampitoyo** [comment]
@ekager Yes, we should. I’ve filed #2569 to do this.
