### ISSUE TITLE
TelemetryWrapper: openFullBrowser() does not queue event.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2331]
There's a call to queue() missing. We are never queuing/sending the event:

https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt#L529-L535

**Comment by pocmo** [comment]
Reopened so that we remember uplifting this.

**Comment by boek** [comment]
uplifted
