### ISSUE TITLE
Opening a site using 'Open in Focus' in custom view causes tabs to be inaccessible

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2335]
STR:
Open focus, open two tabs
Go to homescreen, open another app, and open a link to be opened in Focus custom tab.
From the menu, select 'Open in Focus'

Expected:
Site opens in Focus app, and previously opened tabs are accessible
Actual:
Site opens in Focus app, but selecting sites in the tab list does nothing.

**Comment by pocmo** [comment]
I can reproduce this and this looks like a release blocker for 4.1.
