### ISSUE TITLE
Pressing back button after opening a site in Focus from custom tab causes Focus to crash

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2336]
On:
FocusWebviewUniversalDebug

STR:
Open an app, click a link to open in custom tab
From custom tab, select "Open in Focus"
When Focus is opened, press back button

Expected:
Focus goes back to either the originating app, or doesn't do anything
Actual:
Focus crashes

Logcat:
55.873 14528 14528 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {org.mozilla.focus.debug/org.mozilla.focus.activity.CustomTabActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.mozilla.focus.customtabs.CustomTabConfig.id' on a null object reference
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3912)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.app.ActivityThread.-wrap15(Unknown Source:0)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.mozilla.focus.customtabs.CustomTabConfig.id' on a null object reference
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at org.mozilla.focus.session.SessionManager.getCustomTabSessionByCustomTabId(SessionManager.java:131)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at org.mozilla.focus.activity.CustomTabActivity.onPause(CustomTabActivity.kt:35)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:7143)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3901)
03-19 16:41:55.873 14528 14528 E AndroidRuntime: 	... 11 more

**Comment by pocmo** [comment]
E  java.lang.RuntimeException: Unable to pause activity {org.mozilla.focus.debug/org.mozilla.focus.activity.CustomTabActivity}: java.lang.NullPointerExcep
                            tion: Attempt to read from field 'java.lang.String org.mozilla.focus.customtabs.CustomTabConfig.id' on a null object reference

**Comment by npark-mozilla** [comment]
Same bug also happens with below STR:
- Open app, press link to open custom tab
- Select 'Open in Firefox Focus'
- Go to Home, close Focus and the app
- Open app, and select link to open custom tab

Actual:
Popup notification shows up, saying Firefox Focus has crashed.
