### ISSUE TITLE
Progressbar does not move at after about 5% of progression

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2337]
On:
FocusWebviewUniversalDebug

On Pixel 2, API 27

STR:
Visit a website, i.e. cnn.com
Expected:
Progress bar should gradually fill 
Actual:
Progress bar shows only a bit, and remains static until it disappears

This seems to be a regression bug of #818

**Comment by ekager** [comment]
Ah on GV builds? I can repro I'll look into it.

**Comment by npark-mozilla** [comment]
@ekager oh actually those I find from Focus webview.

This reminds me.. I should somehow mark where I saw the bugs.

**Comment by ekager** [comment]
Can reliably reproduce on WebView builds by 
1) Going to cnn.com from home screen
2) Longpress and open a link in new tab

**Comment by npark-mozilla** [comment]
Probably a dupe of #1837
