### ISSUE TITLE
On Split view, pressing Trash icon of one Focus instance removes the view of a different Focus instance

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2338]
On:
FocusWebviewUniversalDebug

STR:
Open Focus, go to a site (i.e. cnn.com)
Enable split view, open an app and press link to open custom view at the bottom
From the custom view, select 'Open in Firefox Focus'
From the newly opened focus instance at the bottom, press Trash icon

Expected:
the bottom view is cleared
Actual:
the top view instance is cleared, and there is no system notification item for Focus

**Comment by bbinto** [comment]
should be fixed with  pull request #2353

**Comment by pocmo** [comment]
@npark-mozilla Can you confirm this is fixed?

**Comment by npark-mozilla** [comment]
yes it is fixed. now a new tab is added to Focus on the top of the split view, whenever 'Open in Focus' is selected.
