### ISSUE TITLE
After opening a page in custom tab with "Open in Firefox Focus" it still appears to be in custom tab mode

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2342]
On:
FocusWebViewUniversalDebug
STR:
Open app, click a link to open in custom tab, then select 'Open in Firefox Focus' 
After the page is opened in Focus app, press Home to exit
Now select the app from step 1
Expected:
Since it is opened in Focus app, it should either show custom tab view, or the original app view
Actual:
It shows the Firefox Focus instance of the page

**Comment by pocmo** [comment]
Oh, yes, that's right. In this case we'd need to switch tasks to separate ourselves from the third-party app task.

Potentially a release blocker.
