### ISSUE TITLE
[l10n] Sign-off on v4.1 locales

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#2344]
Today is l10n deadline so opening this issue to sign-off on localizations.

Testing over the weekend surfaced 2 bugs, and I wanted to call them out here: 
*  [l10n] "Trackers blocked" string truncates in multiple locales #2341 
*  Inconsistencies in string use: "Custom URLs" vs "Custom URL" #2343 

I'm especially worried about the 1st one, so I was wondering if this is something we should flag for the release or not, and get fixed before I sign-off on localization and we cut it off for this release? (CC @Sdaswani)

**Comment by Delphine** [comment]
If we can't get a fix in time for #2341 here are the locales that are at more than 30%.
Overview:
* Total of 75 locales
* 6 new locales: an (Aragonese), gu-IN (Gujarati), hr (Croatian), oc (Occitan) and tt (Tatar) 

am
an
ar
ast
az
bg
bn-BD
bn-IN
bs
ca
cak
cs
cy
da
de
dsb
el
eo
es-AR
es-CL
es-ES
es-MX
eu
fa
fi
fr
fy-NL
ga-IE
gu-IN
he
hi-IN
hr
hsb
hu
hy-AM
ia
id
it
ja
ka
kab
kk
ko
lo
meh
mix
ms
my
nb-NO
ne-NP
nl
nn-NO
oc
pl
pt-BR
ro
ru
sk
sl
sq
sr
sv-SE
ta
te
th
tr
trs
tt
uk
ur
vi
wo
zam
zh-CN
zh-TW

----
Locales not shipping but should be getting screenshots: anp, lt
(CC @boek)

**Comment by Sdaswani** [comment]
@pocmo any advice here on whether we should get these fixed for 4.1, or can we ship them with 4.2? I think the latter is fine as AFAICT they are not new issues in 4.1.

**Comment by pocmo** [comment]
@Sdaswani I agree. Those issues are something we should take care of in this sprint (4.2). But they already exist in the release version. So releasing 4.1 _as-is_ doesn't degrade quality here (but improves a lot of other things).

Depending on the solution/risk (I pinged UX in the issue) we could consider uplifting / a dot release. Especially if we encounter other issues.

**Comment by boek** [comment]
yep!
