### ISSUE TITLE
Investigate + Fix ANR Elevations

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#2345]
![screen shot 2018-03-19 at 4 19 28 pm](https://user-images.githubusercontent.com/4879954/37627381-58005db2-2b91-11e8-8915-967198351eab.png)

@pocmo did you have a chance to investigate? If so can you drop ant findings here for @ekager to use before she starts her investigation.

Thanks!

**Comment by pocmo** [comment]
I do not have any findings to report.

It is interesting that this started to happen without an app release. So I wonder if we can limit the scope in Google Play:
* Does this happen on specific devices more often (New device release?)
* Does this happen on a specific Android version (Devices updated?)
* Did WebView/Chrome update and might be causing this (Probably impossible to pin down)

I also wonder if we see this anomaly with Klar too?

**Comment by Sdaswani** [comment]
Thanks @pocmo - once @ekager gets GP access she can look into these things.

**Comment by ekager** [comment]
Think I found the culprit by investigating on GP dash. Seems to be when "executing service org.mozilla.focus/.session.SessionNotificationService" for 7.0 and 7.1 devices almost exclusively. Graphs look like this for top 3 ANR issues all are almost identical.

<img width="967" alt="screen shot 2018-03-20 at 2 20 12 pm" src="https://user-images.githubusercontent.com/25442310/37683450-e3759778-2c49-11e8-97c2-d8f10b8d0091.png">

**Comment by Sdaswani** [comment]
@ekager any explanation of why this mysteriously cropped up? It's so odd it seems to have started happening on OSes that _didn't change_?

**Comment by ekager** [comment]
Yeah it is odd, exactly. Wondering if there was some Android patch that affects only those 7.0 and 7.1 devices? Otherwise maybe some WebView update that is acting up? I’m not really sure how to proceed or investigate because I can’t repro on my device even though it’s running 7.1. 

Also not positive the SessionNotificationService is 100% related, but that’s what the dashboard is displaying for the top 3 ANRs... 

@pocmo any ideas from here?

**Comment by Sdaswani** [comment]
Yeah the odd thing is the patch should hopefully result in a new version number. Do you know if 7.0 and 7.1 buckets various minor releases (like 7.0.1 and 7.1.5)? If so that would explain why it looks like this just happened from thin air...

**Comment by ekager** [comment]
Some update was released on March 9, 2018 for certain devices? 
 https://www.att.com/devicehowto/tutorial.html#!/stepbystep/id/stepbystep_KM1230781?make=Samsung&model=SamsungN950U

**Comment by Sdaswani** [comment]
Yeah, maybe @ekager . Ugh _fragmentation_. What are your thoughts on getting a fix in?

**Comment by ekager** [comment]
This elevation is no longer being flagged in GP, so I will check back in a few days to see if it is still happening.

**Comment by ekager** [comment]
Closing for now, and can reopen if this continues to be an issue.
