### ISSUE TITLE
Use Switchboard to run A/B experiments

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2350]

**Comment by pocmo** [comment]
Related meta: #1431

FYI: This year I'll be mentoring a Google Summer of Code student who will be turning our switchboard code/logic in Fennec into a standalone library that we can use in other apps. The project time for GSoC will start April 23rd and end in early August. We might be able to use versions of the library in Focus earlier.

**Comment by pocmo** [comment]
FYI: GSoC work is happening here: https://github.com/mozilla-mobile/fretboard

And progress can be seen here:
https://github.com/mozilla-mobile/fretboard/projects/1

We are not that far away from using the library in apps.

**Comment by bbinto** [comment]
@pocmo amazing news, any rough ETA = "not far away" :) ?

Could we start using it for 7.0?

**Comment by bbinto** [comment]
closing this in favour of #1431
