### ISSUE TITLE
Use WebURLFinder from Utils Package 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2355]
We are in the process of adding the WebURLFinder class to https://github.com/mozilla-mobile/android-components-utils and updating the library version. We should use WebURLFinder from the library when it's added.

**Comment by pocmo** [comment]
In order to fix this bug you'll need to:
* Update the org.mozilla.components:utils dependency to 0.2.2 (which includes WebURLFinder)
* Remove WebURLFinder from the repository
* Fix imports so that the app still builds

**Comment by shikhart98** [comment]
I think now we just need to update the utils dependency to 0.2.2! there are now no imports for WebURLFinder in this repo! should I file a PR?
