### ISSUE TITLE
Add option for disabling JavaScript to Klar+GV

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2356]
See #907 and #2293 for WebView implementation. Waiting for methods to be added to GV.

**Comment by cpeterso** [comment]
GeckoRuntimeSettings now has a setJavaScriptEnabled method to control JavaScript:

https://bugzilla.mozilla.org/show_bug.cgi?id=1440708

**Comment by ekager** [comment]
Should be closed by #2380 :)
