### ISSUE TITLE
Preference title wrapping

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#236]
Some languages have longer preference titles. On Android, they get truncated (on iOS, they wrap around).

We could possibly hack around that by calling the following on every preference.
findViewById(android.R.id.title).setSomething();

**Comment by pocmo** [comment]
Random other ideas:
* If this only affects CheckboxPreference then we could create our own variant
* It would be really nice if there's just a style we can change in our theme

**Comment by pocmo** [comment]
![17349564_10209380809782619_765925423_o_1024](https://cloud.githubusercontent.com/assets/89638/23952053/72f7cf48-0990-11e7-8a55-4fabfd0eed7a.png)

**Comment by pocmo** [comment]
iOS:

![img_0128](https://cloud.githubusercontent.com/assets/89638/23952089/91ccee1c-0990-11e7-850c-90c823b24d12.PNG)

**Comment by ahunt** [comment]
It looks like Android tries to make the preferences auto-scroll using marquee - but that clearly doesn't work (they use the same in the base non-support version):
http://androidxref.com/7.1.1_r6/xref/frameworks/support/v7/preference/res/layout/preference.xml#48

I'm not able to get any effective changes using styling - I can change other attributes, but I can't seem to override the hardcoded singleLine

It turns out it's not possible (or at least not simple) to get the underlying views (we can traverse the Preferences themselves, but they're not linked to the view).

It seems to be possible to override the entire preference layout using R.styleable.Preference_layout, which might work (i.e. we can just copy the default layout, and make the title multine).

**Comment by ahunt** [comment]
A preview with garbage strings:
![settings_multiline](https://cloud.githubusercontent.com/assets/1546915/23958353/294e8abe-09a2-11e7-9d62-55d374c4b3f0.png)
