### ISSUE TITLE
4.1 RC - A User Should Not Be Able to Add Duplicate Custom URLs

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#2363]
Build from:
https://bugzilla.mozilla.org/show_bug.cgi?id=1447461  - app-focus-webview-universal-release-signed-and-aligned.apk
Pixel 2 - Android 8.1

Steps:
1) Go to Settings -> URL Autocomplete -> Custom URL 
2) Enable Custom URL and tap on it
3) add several custom URLs ( try same one different times)
4) Tap 3 dots menu and choose remove
5) Choose one of the duplicates

Expected:
- at step 3 you should not be able to add duples 

Actual:
- at step 3 you are able to add dupes

Note:
- I have added the deletion steps because i got to this enhancement by mistake - I have added Mozilla.org and mozilla.org and thought they are displayed the same name but read different but when deleting one mozilla.org both are deleted. 
- if we keep allowing dupes we should not delete all instance at once

<img src="https://user-images.githubusercontent.com/1391451/37728647-8274e3f2-2d43-11e8-9292-1f234d49f8e0.jpg" width="300" height="550" />

**Comment by Sdaswani** [comment]
@bbinto to decide where to put this.

**Comment by boek** [comment]
@brampitoyo Do we want to show a toast if the user tries to add a domain that already exists? Or is it okay for it to just act like its been added since the domain is already in the list?

**Comment by shikhart98** [comment]
Is this issue solved or is still pending?

**Comment by boek** [comment]
Hey @shikhart98, the issue is pending an answer from UX with the expected behavior. :) Once we get an answer you're more than welcome to pick it up

**Comment by brampitoyo** [comment]
The expected behaviour is for the form to give a “URL already exists” error on submission.

![url-already-exists](https://user-images.githubusercontent.com/51007/38220568-fbb50964-372e-11e8-843c-cedae62d5339.png)

If everything else looks good, this issue is now ready to pick up.

**Comment by shikhart98** [comment]
I'm working on it! almost done! will make a PR today.

**Comment by shikhart98** [comment]
Previously I have added a tost over there

**Comment by brampitoyo** [comment]
I think this is an engineering question for @boek or @pocmo! Pinging them here.

**Comment by shikhart98** [comment]
@brampitoyo I have solved the problem and this issue! just making a PR to this.

**Comment by shikhart98** [comment]
Can someone just review my PR on this issue.
