### ISSUE TITLE
Determine region for default search engine

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2374]
**Why**
- Provide accurate search engines and codes to user's locale
- Requested by mkaply/search team

**What**
- Location lookup to determine the default search engines for the user

**Acceptance Criteria (how do I know when I’m done?)**
- User gets the correct search engine and code based on their locale

**Comment by Sdaswani** [comment]
Needs @bbinto prioritization.

**Comment by bbinto** [comment]
What's the benefit for the user, would you mind providing a bit more info. Thanks

**Comment by Sdaswani** [comment]
@pocmo I think that request was for you.

**Comment by pocmo** [comment]
#245
