### ISSUE TITLE
Add a “Report a site issue” feature

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2378]
Once we move to Geckoview+Klar, we should give the user an option to report webcompat issues.

**Comment by pocmo** [comment]
Basic version: Attach current URL to webcompat reporting tool, e.g:
https://webcompat.com/issues/new?url=http%3A%2F%2Fwww.mozilla.org

**Comment by cpeterso** [comment]
This feature would be useful for finding websites that are broken by fingerprinting or tracking protection if the report includes information about the reporter's various privacy settings.

**Comment by miketaylr** [comment]
It would be nice to have screenshots as well, I'm happy to elaborate on what needs to happen for that to work.

**Comment by shikhart98** [comment]
Can someone help me to understand what Geckoview and Klar is. I saw many of your issues related to these.

**Comment by Sdaswani** [comment]
@shikhart98 GeckoView is our custom browsing engine, which we will be using in Klar in a few months (swapping it in for Android Webview).

**Comment by shikhart98** [comment]
Is there any documentation about it?

**Comment by Sdaswani** [comment]
https://wiki.mozilla.org/Mobile/GeckoView

**Comment by brampitoyo** [comment]
In terms of UI, “Report Site Issue” is an item that we will put inside the main menu. Pretty straightforward. Tapping the menu item will open the webcompat.com link in a new tab.

**Comment by RomanWuattier** [comment]
I can work on this one. Can someone provide me the strings needed?

**Comment by Sdaswani** [comment]
@BrianNJones can you provide strings for this?

**Comment by brampitoyo** [comment]
Actually, there’s no need for new strings. We can simply use “Report Site Issue”. @RomanWuattier, hopefully this will make your work go faster.

**Comment by BrianNJones** [comment]
Sounds right to me.

**Comment by miketaylr** [comment]
If possible, we should grab a screenshot of the visible tab as well: https://dxr.mozilla.org/mozilla-central/source/mobile/android/chrome/content/WebcompatReporter.js#72

And then postMessage it to the webcompat.com tab: https://dxr.mozilla.org/mozilla-central/source/mobile/android/chrome/content/WebcompatReporter.js#129

**Comment by RomanWuattier** [comment]
@miketaylr It would be a nice to have

I created a first PR without the screenshot feature. The goal here is to split into small PRs.
I'm going to work on a second one to add the screenshot feature.

**Comment by miketaylr** [comment]
Makes sense, let me know how I can help!

**Comment by RomanWuattier** [comment]
@miketaylr I'm working on the screenshot feature, but I'm encountering difficulties. That is the state of affairs.
I tried to grab and post a screenshot by running the script below: 
```java
String js = "function(tab) {" +
        "let win = tab.window;" + "let dpr = win.devicePixelRatio;" +
        "let canvas = win.document.createElement("canvas");" +
        "let ctx = canvas.getContext("2d");" +
        // Grab the visible viewport coordinates
        "let x = win.document.documentElement.scrollLeft;" +
        "let y = win.document.documentElement.scrollTop;" +
        "let w = win.innerWidth;" +
        "let h = win.innerHeight;" +
        // Scale according to devicePixelRatio and coordinates
        "canvas.width = dpr * w;" +
        "canvas.height = dpr * h;" +
        "ctx.scale(dpr, dpr);" +
        "ctx.drawWindow(win, x, y, w, h, "#ffffff");" +
        "let screenshot = canvas.toDataURL();" +
        "win.postMessage(screenshot, "https://webcompat.com/issues/newurl={reportedUrl}");" +
"};"
```
And post it asynchronously to the window:
```java
this.post(new Runnable() {
        @Override
        public void run() {
            evaluateJavascript(js);
        }
});
```
This should create a new "canvas" and add it to the window.

But nothing happens. Did I miss something? Is there a way to directly use the `WebcompatReporter` class?

**Comment by miketaylr** [comment]
> I tried to grab and post a screenshot by running the script below:

Assuming that the script works the way you intend it to (I have no idea...), here's a few ideas:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L118

We require the event origin to match `webcompat.com`, and currently you're sending the entire URI, rather than just `http://webcompat.com`:

`win.postMessage(screenshot, "https://webcompat.com")` is probably what you want.

If you get stuck, ping me again, and I can push some debug code to our staging server so you can at least see if a message is getting sent correctly and we can go from there.

> Is there a way to directly use the WebcompatReporter class?

Unfortunately I'm not much of an Android dev, so I don't know. :(

**Comment by bbinto** [comment]
@pocmo GeckoView as that way it will most actionable for us.

**Comment by pocmo** [comment]
Landed a contributor patch that implements this feature. Filed to follow-ups:

* Only show “Report a site issue” in GeckoView builds #2606
* Report site issue: Upload screenshot #2607
