### ISSUE TITLE
Give meaningful option for searching in text selection

### ISSUE THREAD

**Issue by GammaBurst101** [mozilla-mobile/focus-android#2383]
When I select a text in focus and tap on the three dots, I get two options with the same name "Search Privately" but with different functionality. One of them searches by opening a new tab and the other opens a new browser window for searching.
![screenshot_20180310-192640](https://user-images.githubusercontent.com/35678205/37873561-c6417c2a-303c-11e8-84f1-1041ba2d22f0.png)
Wouldn't it be great if the user gets more info on which option will search in what way?

**Comment by pocmo** [comment]
Are you sure you do not have two builds of Focus and/or Klar installed?

**Comment by GammaBurst101** [comment]
I do have focus installed from play store and klar from a website which Sdaswani emailed me. Does it have any effect?

**Comment by pocmo** [comment]
Yes, the text selection actions are not limited to an application. If you have two builds installed then both will add the action to *all* apps that support selecting text.
