### ISSUE TITLE
Semantic animations for opening in-content links

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2384]
This is a follow-up issue for #2107, to be implemented after version 4.2.

The story so far: in version 4.2, Firefox Focus will start opening in-content links in browser tabs. Unfortunately, opening in-content links “in the back, on the main view” doesn’t match the user’s mental model very well. The user expects the link to open “in front, as a Settings sub-page”.

Fortunately, semantic animations can help clarify this action, and should be implemented after we’ve finished implementing #2107.

@aminalhazwani wrote:

For a truly semantic animation we should opt for something like this

<img width="1054" alt="screen shot 2018-03-22 at 1 03 52 pm" src="https://user-images.githubusercontent.com/1721875/37769540-a31f89d4-2dd1-11e8-8eb8-632ecafdfa29.png">

where the tab grows out of the list item. Now, of course I understand that we have some OS constrains that for the time being we have to acknowledge, so there are a couple of things we could add to make this even more clear.

Choreography plays a big role here: there are a lot of things moving. How can we direct the users eyes in order to let them understand what is happening? The FAB button is a good actor, it can really help users understand that a second tab is being open. It would be interesting to explore more how to sync and direct different animations because FAB, progress bar and URL bar in the demo are animated all at the same time. 

Related to the FAB what was initially a Erase button becomes a Tabs button. Some improvements that we could consider: show immediately the "1" and then bump it to "2". We could also use the same tab signifier that we use for tabs on Firefox for Android. 

<img width="71" alt="screen shot 2018-03-22 at 1 06 43 pm" src="https://user-images.githubusercontent.com/1721875/37771186-1c70f278-2dd7-11e8-8287-8bdbb31a3d98.png">

Another possible small improvement is the icon choice for the "Help" list item. While we use the "Open in New" for external links in web properties in this case we could use the "Tab New" icon since everything is happening inside the app and would reinforce the idea that a new tab is being open.

<img width="271" alt="screen shot 2018-03-22 at 1 06 51 pm" src="https://user-images.githubusercontent.com/1721875/37771219-398dee06-2dd7-11e8-93ca-db0d3ea38ba2.png">

**Comment by Sdaswani** [comment]
@brampitoyo is this issue still relevant or has the product changed and/or improved so it's moot?
