### ISSUE TITLE
Easier way to add custom search engines

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2385]
Why
- Users are currently unable to easily add custom search engine
- Target users will use custom search engine to perform more searches

What
- Adding an easy way to quickly add custom search engine

Acceptance Criteria (how do I know when I’m done?)
- User can add any search engine they like
- Solution is less error-prone

-----

This issue is focused specifically on the **context menu item that allows you to add a search engine**

This menu item is called “Add Search Engine”. It appears when you tap and hold a search text field that uses the OpenSearch description format.

<img src="https://user-images.githubusercontent.com/51007/37881501-9e70ad6a-30f5-11e8-9c90-a9cfa1be6a8f.png" width="360">

The UX for this work is finished.

**Comment by pocmo** [comment]
This *might* not be possible with WebView. And even with GeckoView this won't be straight-forward.

> It appears when you tap and hold a search text field that uses the OpenSearch description format.

Just to clarify: Afaik the OpenSearch description is attached to the website's meta data and independent from input fields on the page. Yet we only want to show this item if the OpenSearch description exists and *not* try to reconstruct the search structure from the input field like Fennec does - Is this correct?

**Comment by brampitoyo** [comment]
@pocmo I think so. By not trying to reconstruct the search structure from the input field like Fennec does, I feel like it will save us engineering time and energy. But this is just a hypothesis. Is porting this feature from Fennec easy, or even possible?

If it’s impossible, then we’ll have to do something like #1561.

If it takes a lot of time and effort, then given how only a few users are likely want to use this feature (and maybe all they want is just one certain search engine), then our time may be best spent elsewhere.

So, although the visual UI for this work is finished, there’s a chance that it might not make it because it’s just not worth it.

**Comment by pocmo** [comment]
> @pocmo I think so. By not trying to reconstruct the search structure from the input field like Fennec does, I feel like it will save us engineering time and energy. But this is just a hypothesis. Is porting this feature from Fennec easy, or even possible?

That's something an engineer could research as a separate task. Afaik WebView doesn't have an API for that and we shouldn't try to hack something. If we want to have this in the future then we could talk to the GeckoView team about an API (either explicitly for this or metadata in general) - but this would be out of scope for 5.0.

> If it takes a lot of time and effort, then given how only a few users are likely want to use this feature (and maybe all they want is just one certain search engine), then our time may be best spent elsewhere.

I wonder if we put too much effort into adding search engines already. Yes, telemetry shows that the current implementation is not used by many users. But if you look at the market share of the existing default options then not many users will be interested in adding a new search engine (Assuming Focus users are an accurate sample of the search engine market).

**Comment by brampitoyo** [comment]
> I wonder if we put too much effort into adding search engines already. Yes, telemetry shows that the current implementation is not used by many users. But if you look at the market share of the existing default options then not many users will be interested in adding a new search engine (Assuming Focus users are an accurate sample of the search engine market).

I agree that we have put a lot – possibly too much – effort into adding a feature that may only result in such a minor improvement in new users, retention or app store ratings. Adding a URL seems easier to build and would have more use cases?
