### ISSUE TITLE
Refactor URLBar states

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#2394]
While fixing #1837 it feels like this area could be simplified a bit.

Assigning this to myself to expand on this thought later

**Comment by bbinto** [comment]
@pocmo could this be handled by the android components

**Comment by pocmo** [comment]
Yes, I expect the toolbar component to be usable in Focus too. However it will take some time until we can do the switch.

**Comment by boek** [comment]
Sounds good, I'm going to close this and when the component is done we can talk about pulling it into Focus 🙌
