### ISSUE TITLE
Samsung Keyboard Private Mode support.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/focus-android#2397]
Hi, can you add support for the private mode of Samsung Keyboard? When using both Samsung Internet in Private Window  and Samsung Keyboard it doesn't record typed information and doesn't show suggestions. Can you make it work like this too in Firefox Focus?

Thank you.

**Comment by pocmo** [comment]
In UrlInputFragment we set IME_FLAG_NO_PERSONALIZED_LEARNING which enables the private mode of Google's keyboard. The Samsung keyboard seems to expect something else?

See also #2304 which is trying to disable text prediction via setting the input type to TYPE_TEXT_VARIATION_PASSWORD. But I'd prefer to keep typeUri to still display the keyboard variant for entering URLs.

**Comment by pocmo** [comment]
Input types can be combined. We could try:
```xml
android:inputType="textUri|textNoSuggestions"
```

Instead of using just "textUri" (in fragment_urlinput.xml).

**Comment by mcarare** [comment]
@Lululalu is this still an issue?
