### ISSUE TITLE
Block ads on startpage.com search results

### ISSUE THREAD

**Issue by bbcom77** [mozilla-mobile/focus-android#2405]
Problem: 
When searching with startpage.com there are ads showing in the result. 

Solution:
Block ALL advertisements, also in the search results of startpage.com.

Why doesn't Firefox Focus block all advertisements?

**Comment by bbinto** [comment]
Focus primarily blocks trackers that are in ads, hence not all ads are being blocked, we are working on ideas to include more ad blocking capabilities #953

**Comment by pocmo** [comment]
Closing in favor of #953
