### ISSUE TITLE
With WIFI off, Klar redirects to other apps

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2413]
Build: Klar+GeckoView

Devices:
Xiaomi Mi Pad 2 (Android 5.1) - x86
HTC Desire 820 (Android 6.0.1) - arm

STR:
1. Turn off the Wifi.
2. Open a page in Klar+GeckoView.
3. Check the dialog displayed: 
![screenshot_20180330-164648](https://user-images.githubusercontent.com/4037709/38139898-1f89953c-343a-11e8-8a26-5ac599d34002.png)

Expected result: 
As on Focus: a network error page.

Actual result: See the above screenshot.

**Comment by bbinto** [comment]
@ekager to confirm if this is still an issue for Klar (and Focus)

**Comment by ekager** [comment]
I think now, it just fails to load an error page, which is expected. Closing for now.
