### ISSUE TITLE
Klar+GeckoView: Can't add new search engines

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2415]
Build: Klar+GeckoView

Devices:
Xiaomi Mi Pad 2 (Android 5.1) - x86
HTC Desire 820 (Android 6.0.1) - arm

STR:
1. Go to Settings>Search>Add new search engine.
2. Add a new name and a valid search url. Save.

Expected result: A new search engine is added.
Actual result: Can't save because an installed search engine is already using the name.
Works on Focus 4.0.2.

**Comment by ekager** [comment]
This should be fixed now by #2408, please reopen if you're still seeing on latest master
