### ISSUE TITLE
Add additional erase data tests to cover every erase flow

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2422]
Deleting user data is a mission critical feature and it's one we never want to regress: we should make sure our tests cover *all* the ways that users can erase data, e.g.:
- Click notification
- Click FAB
- Swipe close apps tray
- System OOM app
- App is force killed

We have UI tests to verify some of these cases but we've had regressions before (#1875, #1306) and it'd be great if that didn't happen again. :)

**Comment by vesta0** [comment]
@mcomella was this item addressed?

**Comment by mcomella** [comment]
@vesta0 I haven't addressed this issue and it was not addressed when I was on the team. Looking at the erase data test, it doesn't look like this has changed either: https://github.com/mozilla-mobile/focus-android/blob/cbe6e3b84a9dedbd7cbb189d0fd3fddd933a7555/app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.java#L100
