### ISSUE TITLE
Update search_configuration.json to match list.json

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2423]
PR #2373 updated list.json but not search_configuration.json which we actually use.

**Comment by pocmo** [comment]
^- @mkaply

**Comment by mkaply** [comment]
That's odd. I had definitely modified that file in my original patch. Checking.

**Comment by bbinto** [comment]
@pocmo can you please review and get this in asap.

**Comment by pocmo** [comment]
All good. It seems like I was testing an outdated build.
