### ISSUE TITLE
Settings: Don't update screen when search engine was selected

### ISSUE THREAD

**Issue by FabioBeneditto** [mozilla-mobile/focus-android#243]
In Settings screen, default search engine was not updated on screen when I selected other than Yahoo.

In AwesomeBar new search engine works fine.

**Comment by pocmo** [comment]
This hasn't been implemented yet. Currently always DuckDuckGo is used and the search engine selection is not stored. I'm working on this as part of #184 - We'll need to parse all the search plugins before we can use them and save the selection. But thank your for testing and reporting! :)

**Comment by pocmo** [comment]
This is now in `master`. :)
