### ISSUE TITLE
Refactor domain/url auto-completion to use new android-components

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/focus-android#2435]
Our new [android-components](https://github.com/mozilla-mobile/android-components) repository now has reusable components for `InlineAutocompleteEditText` and a domain list auto-complete provider for built-in and custom domains.

We should migrate to these components to avoid code duplication and diverging changes.

**Comment by csadilek** [comment]
Commit is ready, but waiting for the latest android-components release to hit jcenter.

**Comment by bbinto** [comment]
@pocmo to confirm if/when that's needed
