### ISSUE TITLE
What's New Entry for 4.2

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2440]
_added by @bbinto_

**Why**
- Inform users about the latest update & changes 

**What**
- SUMO page link explaining any new features/improvements of the version the user has just installed.

**Acceptance Criteria (how do I know when I’m done?)**
- User can access and exit the SUMO What's New Page

**Comment by jonisavage** [comment]
We can give you a new link but if you prefer not to change your link, we can easily make sure that users get to the 4.2 page on our end. Just let me know what you decide to do.

How's this description?
"We've added the ability to turn Javascript off or on in the Settings menu. Turning Javascript off makes websites load faster and prevents websites from assigning you a "fingerprint" and tracking you, but this might also break some websites that rely on Javascript to work properly. "

**Comment by BrianNJones** [comment]
Hi Joni,
That's a really helpful way to describe what the Javascript setting does!
Only thought is that it might be possible to simplify the second sentence?
Turning Javascript off makes websites load faster and helps prevent them
from tracking you, but may cause some websites to break or behave
unexpectedtly...???

-Brian

**Comment by ekager** [comment]
I think we're running behind a bit on this release so maybe we should reuse the link, what do you think @boek and @pocmo ?

**Comment by jonisavage** [comment]
That's a good suggestion, Brian. I'll edit the description and publish it.

**Comment by ekager** [comment]
Closing because this has been published. Thanks all!
