### ISSUE TITLE
Use GeckoView in e10s mode

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/focus-android#2445]
We should switch Klar+GeckoView to use GeckoView in e10s mode (GeckoSessionSettings.USE_MULTIPROCESS). The current thinking is that this is the configuration we want to ship with, so we should start using it now. There will be a different set of broken things that we need to work through, so the earlier the better.

**Comment by bbinto** [comment]
Why: 
Test earlier than waiting to long

**Comment by bbinto** [comment]
@ekager to confirm estimates

**Comment by ekager** [comment]
Hey @snorp , when I set `USE_MULTIPROCESS` to `true`, I'm getting a blank screen and no content rendered. Should I file a Bugzilla bug or do you know about this already?

**Comment by ekager** [comment]
Closed by #2572
