### ISSUE TITLE
New settings page for blocking cookies

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2452]
In issue #2330, we will support blocking 3rd party cookies.

@BrianNJones wrote:
> Also not confident most users will understand reference to 3rd-party cookies.

This issue will figure out ways to explain the 3rd party cookie option better.

**User Benefit**
- Explain and inform our users why and how they can use cookie management to protect themselves.

**What**
- Add more explanation about cookie management into settings page

**Acceptance Criteria**
- Explanation is presented
- Probe on "learn more" link

**KPI/Data**
- get baseline of current usage
- compare to new improved feature

**Comment by brampitoyo** [comment]
[SUMO wrote a great plain language explanation](https://support.mozilla.org/en-US/kb/disable-third-party-cookies):

> Third-party cookies are cookies that are set by a website other than the one you are currently on. For example, cnn.com might have a Facebook like button on their site. That like button will set a cookie that can be read by Facebook. That would be considered a third-party cookie.
>
> Some advertisers use these types of cookies to track your visits to the various websites on which they advertise. If you are concerned about this, you can disable third-party cookies in Firefox.

**Comment by brampitoyo** [comment]
This is the newest iteration of the design that we should use:

<img width="791" alt="cookies 2x" src="https://user-images.githubusercontent.com/51007/39460428-6180599a-4d57-11e8-9ffb-d9202ce0e33e.png">

**Comment by bbinto** [comment]
@bbinto @mmccorks to confirm how many users are accessing the cookie management

**Comment by ekager** [comment]
So @brampitoyo is this design final? I know our Settings menu has changed a bit since these designs.

**Comment by brampitoyo** [comment]
@ekager Currently, our design looks like this:

<img width="320" src="https://user-images.githubusercontent.com/51007/45458726-0473e580-b749-11e8-89ca-6b1929fc78c6.png"><img width="320" src="https://user-images.githubusercontent.com/51007/45458737-10f83e00-b749-11e8-8759-0dcc47935813.png">

We want to tweak the latest iteration (circa May 17) slightly, to something that looks like this:

<img width="320" src="https://user-images.githubusercontent.com/51007/45458726-0473e580-b749-11e8-89ca-6b1929fc78c6.png"><img width="320" src="https://user-images.githubusercontent.com/51007/45459179-3b4afb00-b74b-11e8-9787-916ae1aef820.png">

Notable changes:

1. The 3 options are now called `No`, `Third-party cookies` and `All` (in order of severity). The word `Block` doesn’t repeat and won’t clash with the item title.
2. We borrow verbiage and description from desktop, where we warn if choosing certain options will (or may) break sites.
3. The informational SUMO link is still there (and still links to [this article](https://support.mozilla.org/en-US/kb/block-cookies-firefox-focus-android)). On that page, we’re mainly interested in the `Notes` section.

However, in v8.0, we will want to change it to something that looks like this:

![settings - privacy security - cookies and site data 2x](https://user-images.githubusercontent.com/51007/45459464-7ef23480-b74c-11e8-82f6-d57eb470586b.png)

I was thinking that it will be worth our time and effort to change it once in v8.0, instead of changing it in a point release, and then again in v8.0?

**Comment by brampitoyo** [comment]
@ekager @boek I’ve updated the cookie blocking UI to keep in mind this fact:

* We won’t redesign the whole Privacy & Security settings page drastically
* We want the current name to stay intact
* We also want a new option called “Block third-party trackers cookies”
* As much as possible, we’d like to align our verbiage and labels with desktop Firefox

The page looks like this:

![slice 2x](https://user-images.githubusercontent.com/51007/49704869-72af4200-fc7d-11e8-9f6d-0e8aceb6e35d.png)

* The menu item label “Block cookies” is kept the same. Because we won’t redesign our settings page, almost all items will consistently say “Block x”.
* I’ve eliminated text labels underneath each cookie blocking option, as they’re trickier to implement. Instead, we’ll just use brackets in the headings themselves.
* Each option now uses the same wording that Firefox desktop uses to describe its cookie blocking options. Note the similarity below.

<img width="606" alt="screen shot 2018-12-10 at 1 17 50 pm" src="https://user-images.githubusercontent.com/51007/49704927-041eb400-fc7e-11e8-9126-cfc401810686.png">

**Comment by vesta0** [comment]
@brampitoyo I understand why the option to allow cookies is stated as "No" considering the main heading "Block cookies" but I worry that it might still not be clear enough. What do you think of "No, allow all cookies" or something similar?

**Comment by brampitoyo** [comment]
@vesta0 I like “No, allow all cookies”. Let’s do that. I’ve updated the mockup above to match.

**Comment by vesta0** [comment]
Thank you @brampitoyo!

@boek this is ready for engineering :)

**Comment by BrianNJones** [comment]
Given that we're using parenthetical references to explain things, what about: 
No
(allow all cookies)

**Comment by brampitoyo** [comment]
@BrianNJones Agreed! I’ve updated the mockup again to reflect this.

**Comment by vesta0** [comment]
Thank you @brampitoyo and @BrianNJones

**Comment by sblatz** [comment]
Since we are no longer planning on doing a full-blown settings reorganization (#3508) this is still presented as a fragment:
<img width=300 src=https://user-images.githubusercontent.com/4400286/50169759-3a7eb380-02bc-11e9-9e98-e092780da636.png>

We could also *just* update this setting to push to a new page since this fragment looks awfully crowded with the new strings. Thoughts @brampitoyo, @vesta0?

**Comment by vesta0** [comment]
@sblatz is this in response to Bram's latest mocks?

**Comment by brampitoyo** [comment]
@sblatz wrote:

> We could also _just_ update this setting to push to a new page since this fragment looks awfully crowded with the new strings.

Agreed. Even without a big Settings reorganisation, it’s still worth it to make this fragment into a new page that can sufficiently contain all the information. Let’s do that.

**Comment by sblatz** [comment]
@vesta0 that was the android emulator after just plugging in some new strings. So I was suggesting we still go with bram’s mock-up which may require a little more effort than just updating the strings.

**Comment by vesta0** [comment]
@sblatz let's go ahead with this change assuming that it's still a small medium, but if it ends up being more work please let me know.

**Comment by sblatz** [comment]
After working on a fragment for this, I've hit a roadblock that would require more custom UI, as RadioGroups cannot be added to a PreferenceScreen. We have made custom UI like this before with our [RadioSearchEngineListPreference](https://github.com/mozilla-mobile/focus-android/blob/f5ca439424491ff63688deb574594d3ccb60db1d/app/src/main/java/org/mozilla/focus/search/RadioSearchEngineListPreference.kt) but I'm just not sure it's worth the effort.

Here's what I have currently have, using checkboxes which is our only "small" effort solution

<img width="300" src="https://user-images.githubusercontent.com/4400286/50612080-c3920f00-0ea6-11e9-84b1-0fefe19d4341.png">

I can set the checkboxes to only allow users to select one, it just may be a little confusing.

@vesta0, @brampitoyo: Would this be an acceptable solution or would we prefer just using the crowded ListPreference I posted [here](https://github.com/mozilla-mobile/focus-android/issues/2452#issuecomment-448293403)? Considering how few users go into this setting, I think this would be sufficient, but I know it doesn't match the original specs so I wanted to confirm 😄

**Comment by vesta0** [comment]
@sblatz thank you for looking into this, and for flagging the complexity level early on! 

My preference is to use the original ListPreference even though it is crowded. Would it still be possible to have a Learn More link underneath though + 4 cookie options (see image)?

![image](https://user-images.githubusercontent.com/42752644/50659628-382e8180-0f6b-11e9-857b-bae136be5492.png)

**Comment by brampitoyo** [comment]
@sblatz Are you able to add radio buttons to the preference page, or did you revert back to using fragments?

**Comment by sblatz** [comment]
@brampitoyo we decided to move forward with just using the fragment as using the new settings page was going to require too much custom work than we were comfortable with. Please let me know if you have any major concerns with this 😄

**Comment by brampitoyo** [comment]
@sblatz Going with the fragment approach is all good. Thanks!

**Comment by sv-ohorvath** [comment]
Verified as done on Master (both GV & WV) 8.0.6.
