### ISSUE TITLE
In Focus Webview Debug, About Focus and Your Rights page have about:blank URL

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2455]
Going to those pages shows about:blank for Focus webview debug builds, and they are causing the UI tests to fail as well.
![screen shot 2018-04-12 at 5 04 50 pm](https://user-images.githubusercontent.com/6930774/38704225-a344c85e-3e73-11e8-80b1-35843cefea2e.png)

**Comment by pocmo** [comment]
Is this in the GeckoView or WebView builds? Afaik the WebView version should show URLs like focus:about (that a user could also type manually).

**Comment by npark-mozilla** [comment]
This is on Webview build, on Geckoview, it shows focus:about or other focus:* URLs properly

**Comment by sv-ohorvath** [comment]
Verified on Beta v5.0 and Dev build.
Device: Google Pixel (Android 8.1.0)
