### ISSUE TITLE
the custom pages (About / Your Rights / Help) are not removed when user exits to Settings

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2456]
(Both on Focus and Klar)
STR:
- Go to settings, and open 'Your Rights'
- From the dropdown, go to Settings, and select 'Privacy Notice'

Expected:
- There should be only one tab
Actual:
- There are two tabs open (the current one and the previous 'Your Rights' tab)

**Comment by ekager** [comment]
This is intended behavior now see #2107

**Comment by npark-mozilla** [comment]
Got it, closing.
