### ISSUE TITLE
About the focus

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/focus-android#2459]
Hi!
1. Please increase the function of automatic update and upgrade software version. Other versions have read only on him!
2. Please increase the forbidden web page to automatically play video and audio functions.
Thank you!

**Comment by pocmo** [comment]
> Please increase the function of automatic update and upgrade software version. Other versions have read only on him!

Sorry, I do not understand what you are asking for. Do you want Focus to update itself independently from Google Play?

> Please increase the forbidden web page to automatically play video and audio functions.

Do you want to disable "autoplay" of videos and audio? This is tracked by #2003.

**Comment by edenftp** [comment]
What I mean is that I can update directly through your direct server instead of through the three-way website!
And I'm not sure if your focus is automatic or more functional?
