### ISSUE TITLE
Web icon in address bar

### ISSUE THREAD

**Issue by Shankdevilz** [mozilla-mobile/focus-android#2463]
While opening webpage if i click on web icon in address bar app freezes after displaying "Insecure Connection ".
![screenshot_2018-04-16-21-54-19-1](https://user-images.githubusercontent.com/38435441/38823194-58f3115e-41c3-11e8-9224-1428f86a0f31.png)

**Comment by pocmo** [comment]
@ekager @brampitoyo Mhhh. Maybe we just want to show no doorhanger while the page is still loading?

**Comment by brampitoyo** [comment]
Yes. If the page is still loading, let’s not show any doorhanger.

**Comment by Shankdevilz** [comment]
Same issue with lock icon also.
![screenshot_2018-04-17-08-14-49-1](https://user-images.githubusercontent.com/38435441/38845993-b128f52e-4217-11e8-8a2f-2513c069ea2a.png)

**Comment by ekager** [comment]
Closed by #2464 to not allow popup while loading.

**Comment by levimatheri** [comment]
Can I take up this bug?
