### ISSUE TITLE
Error on gradle build

### ISSUE THREAD

**Issue by levimatheri** [mozilla-mobile/focus-android#2465]
Why am I getting these errors?

`The SourceSet 'androidTestGeckoCompile' is not recognized by the Android Gradle Plugin. Perhaps you misspelled something?`

and...

`The SourceSet 'klarWebviewDebug' is not recognized by the Android Gradle Plugin. Perhaps you misspelled something?`

**Comment by ekager** [comment]
Never seen these before so I'm not sure, but make sure gradle is version 3.0.1 (`classpath 'com.android.tools.build:gradle:3.0.1'`) and try to invalidate+restart.

**Comment by levimatheri** [comment]
Thank you @ekager. It worked!
