### ISSUE TITLE
Upgrade gradle plugin (whenever you want)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2467]
I upgraded the gradle plugin to 3.1.1 for TV in https://github.com/mozilla-mobile/firefox-tv/issues/806 in order to fix some Android Lint bugs. One unexpected requirement is that you'll need to bump the  jacoco-android version too.

**Comment by ekager** [comment]
Just attempted this and ran into a new error.
`The SourceSet 'klarWebviewDebug' is not recognized by the Android Gradle Plugin. Perhaps you misspelled something?`

Found this link that perhaps has a work around that would work for us but not sure if we should upgrade if we have to add a work around? 
https://stackoverflow.com/questions/48846879/new-error-after-update-to-gradle-tool-to-3-1-0-beta3-or-3-2-0-alpha03

**Comment by boek** [comment]
I would love to keep things up to date while its easy.

@pocmo what do you think about that workaround?

**Comment by pocmo** [comment]
@boek I think the workaround is okay-ish. We just have a lot of source sets. Some of them are shared though; so maybe we can come up with something that's actually more compact than what we have right now. :)
