### ISSUE TITLE
Create Download with User Agent from GeckoView

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2470]
Waiting for method to get user agent from GeckoView tracked here: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1454444

**Comment by cpeterso** [comment]
@ekager What is the scenario where GV's User-Agent string will be used for downloads? Is the downloading managed by Android instead of Focus and thus needs to be told to spoof GV's User-Agent string?

**Comment by cpeterso** [comment]
@pocmo - Does this issue need to block the Focus+GV release? Does setting the User-Agent string in the Android Download Manager fix a problem (e.g. do download requests need matching User-Agent string and user cookies)?

**Comment by pocmo** [comment]
I don't think it does need to block the release. Especially not if we are not going to block on cookies (which barbara indicated).
