### ISSUE TITLE
Make sure Sentry works with GeckoView crash reporting (Bug 1433968)

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2494]
### Why/User Benefit/User Problem
Need to be able to track GeckoView crashes in the wild to report them back to GV team to be fixed to benefit Klar+GV users.

### What / Requirements
- Currently blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1433968

### Acceptance Criteria (how do I know when I’m done?)
Useful data for GV crashes show up in Sentry dashboard.

**Comment by cpeterso** [comment]
@ekager - Are Focus+GeckoView crashes showing up in the Sentry dashboard? Can we close this bug? The [GeckoView crash reporting bug 1433968](https://bugzil.la/1433968) was fixed two months ago.

**Comment by bbinto** [comment]
@ekager to confirm if it can be closed.

**Comment by ekager** [comment]
I'm seeing Gecko related crashes in Sentry, so closing this.
