### ISSUE TITLE
Implement mobile-metrics ping type

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2495]
### Why/User Benefit/User Problem

* We need GeckoView metrics to understand how it's performing in the wild
* We want to get this in early to test the whole telemetry pipeline

### What / Requirements

* The new ping type can be used to implement #2347

Actual work happens here:
https://github.com/mozilla-mobile/android-components/issues/113

**Comment by pocmo** [comment]
The GeckoView API for this should be available now.

**Comment by ekager** [comment]
Closed by #2692
