### ISSUE TITLE
Look into reporting to Sentry AND Google Play crash reporting

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2496]
### What / Requirements
Crash reporting will be disabled by default for Klar and with Sentry we’ll want Google Play reporting too

**Comment by ekager** [comment]
As discussed in #2326 , we can also create a new toggle in Settings to toggle collecting crash reporting separately than all usage data and have it be opt-out for Focus+Klar. @brampitoyo provided possible strings there as well. CC @bbinto

**Comment by Sdaswani** [comment]
@ekager so can we move on this now that we have Sentry?

**Comment by ekager** [comment]
Do we still need both? Is Sentry not meeting our crash reporting needs?

**Comment by Sdaswani** [comment]
I don't think we need both - what says @colintheshots and @boek and @ekager ?
