### ISSUE TITLE
Replace example.com with mozilla.org

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#2504]
### Why/User Benefit/User Problem
When adding a custom URL you are given the following hint

> Example: example.com

which is a little confusing. We could be more clear by using an actual domain:

> Example: mozilla.org

<img width="615" alt="image" src="https://user-images.githubusercontent.com/1250545/39147692-2fa462e0-46ef-11e8-9d72-b7fcb93a0503.png">

### What / Requirements
- [ ] Replace the contents of the string

### Acceptance Criteria (how do I know when I’m done?)
Hint reads more clearly.

**Comment by daivat15** [comment]
@boek The URL should be added without the "http://" right?

**Comment by daivat15** [comment]
I am thinking of making it:

`Please omit the http:// prefix.\nExample: mozilla.org`

Sounds good?

**Comment by boek** [comment]
@daivat15 With the changes in #2498 we are now saving the `http/s` as part of the url. So I think just having the example be `mozilla.org` should be fine. But lets wait until UX signs off on it :)

**Comment by bbinto** [comment]
@BrianNJones to think about updated string

**Comment by brampitoyo** [comment]
I agree with @boek. The example `mozilla.org` was something I suggested. It’s neutral (not pointing Google, Facebook, Apple, etc.), and it exemplifies the kind of URL that we want our users to type (don’t worry about typing the prefix `https://` – this was why we updated our custom URL logic in the first place).

**Comment by BrianNJones** [comment]
After thinking more about this, I'm with @boek and @brampitoyo. Let's go w/ mozilla.org.

**Comment by daivat15** [comment]
Cool. Should I send a PR for this?

**Comment by pocmo** [comment]
@daivat15 Yeah, go ahead. :)

**Comment by pocmo** [comment]
@daivat15 Please make sure to use a new String name (e.g. preference_autocomplete_add_example -> preference_autocomplete_add_example2) so that translators will be required to re-translate the string.

**Comment by pocmo** [comment]
@daivat15 You can use the new string immediately. No need to wait for translations here.
