### ISSUE TITLE
[l10n] New truncations on many locales 

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#2505]
Seems like there are new truncations on many locales this time around (and that concern "top market locales" such as French, German and Polish - just to give an example). I'm going to list them all here, let me know if I should file a separate issue for each truncation and I can do that.

* [Add custom URL](https://github.com/npark-mozilla/npark-mozilla.github.io/blob/master/en-US/images/phoneScreenshots/Autocomplete_Add_Custom_URL_Dialog_1524247043833.png)
* [Remove custom URLs](https://github.com/npark-mozilla/npark-mozilla.github.io/blob/master/en-US/images/phoneScreenshots/Autocomplete_Custom_URL_Remove_Dialog_1524247048864.png)
* [URL autocomplete](https://github.com/npark-mozilla/npark-mozilla.github.io/blob/master/en-US/images/phoneScreenshots/Autocomplete_Menu_Item_1524247042021.png)
* [Erase and...](https://github.com/npark-mozilla/npark-mozilla.github.io/blob/master/en-US/images/phoneScreenshots/DeleteHistory_NotificationBar_1524247024020.png): this also truncates in en-US
* [Add search engine](https://github.com/npark-mozilla/npark-mozilla.github.io/blob/master/en-US/images/phoneScreenshots/SearchEngine_Add_Search_Engine_1524247038804.png)
* [Add search engine](https://github.com/npark-mozilla/npark-mozilla.github.io/blob/master/en-US/images/phoneScreenshots/SearchEngine_Add_Search_Engine_Warning_1524247039599.png)
* [Remove search engines](https://github.com/npark-mozilla/npark-mozilla.github.io/blob/master/en-US/images/phoneScreenshots/SearchEngine_Remove_Search_Engines_1524247037482.png)
* [Installed search engines](https://github.com/npark-mozilla/npark-mozilla.github.io/blob/master/en-US/images/phoneScreenshots/SearchEngine_Selection_1524247034548.png)

These corresponding truncations can be seen here: https://npark-mozilla.github.io/index.html

**Comment by pocmo** [comment]
CC @brampitoyo

**Comment by bbinto** [comment]
@Delphine -- could you please explain why you've put [5.0] in the title? Do you want us to fix this for 5.0?

**Comment by Delphine** [comment]
I put 5.0 in the title because that's the version I was testing. It seems that although some of these are not new strings, they weren't truncating in previous versions - so seems like some are regressions? 
I don't have a previous build or screenshots to tell though. But I filed truncation issues for the previous release, and these strings weren't part of it, I believe.

**Comment by Delphine** [comment]
Talking with Jeff right now. It may be that some of these were previously filed as issues, but not corrected in the meantime.
I can gladly take a look through some of these and see if some seem more "critical" than others. I feel like some of these are ok to not fix right away because you already clicked on the the full string in a previous screen, so you kinda know what it means.

**Comment by bbinto** [comment]
Thanks @Delphine - @boek can you guestimate the effort to fix this? @brampitoyo needs to take a stab at it first, right?

Making this a P3 for now.

**Comment by pocmo** [comment]
@npark-mozilla Can you post again what device you are using to take the screenshots. It seems to be a quite small one too. :)

**Comment by npark-mozilla** [comment]
I'm using Sony Z3C, the 4-inch screen device (yes, it's one of the smallest android phones).  Last time we decided to stay with it since it will show issues that larger screen ones cannot.

**Comment by Delphine** [comment]
FWIW I have a Pixel 2 and saw all the truncations there as well this time around

**Comment by brampitoyo** [comment]
This is a tricky issue, because

**Comment by Delphine** [comment]
Yes, when we worked on Firefox OS truncations happened a lot in the beginning, so people made sure to have the text be able to wrap around, or make the size of the text smaller so that it fits.
Asking the localizers to shorten a string would be something that we'd ask for as a last resort, because as you mention, most of the time it's not possible (and most of our localizers already try to use the shortest strings possible).
We'd usually not change the English string if it already was exposed. 
A rule of thumb we have was: design keeping in mind that localized strings are going to be at least 30% longer than any English one.
Hope this kinda helps :)

**Comment by brampitoyo** [comment]
Paging @BrianNJones for assistance.

### Summary

On a few locales, some heading and menu texts don’t fit the available space.

Thankfully, you only see these headings after tapping on a menu item that has the same text – and the menu item does fit the space.

For example:

* A menu item is titled “Add new search engine”
    * In all locales, this menu item can be displayed in full
* When you tap it, a page with the heading “Add new search engine” appears
    * In some locales, this heading doesn’t fit the title bar space

Although the problem isn’t as bad, it results in an ugly and less usable experience.

We’re trying to fix it, but are a bit perplexed as to what the solution should be:

1. Reduce font size of headings, until the string fits
    * Pros: doesn’t rely on other teams – we can make this alteration ourselves
    * Cons: makes our design inconsistent between pages, and introduces a bunch of new size values that are only used once or twice
2. Ask our localisers to shorten the strings; maybe establish a maximum character limit?
    * Pros: keeps our design consistent
    * Cons: most of the time, our localisers already try to use the shortest possible strings
3. Shorten our own English strings so it localises shorter, too
    * Pros: we can make this alteration ourselves, keeps our design consistent
    * Cons: hard to do (how do you shorten “add new search engine”?), and results not guaranteed – but maybe we can work closely with our localisers from some of the longest locales?

I’m curious to hear your comment and advise on this!

**Comment by BrianNJones** [comment]
@brampitoyo, thank you for all the context. 

1. Cons outweighs the pros

2. Do we have a sense of whether localisers would even be able to shorten the string (or would they run into the same problem of trying to shorten "add search engine" in the relevant language?). As Delphine points out, it's the final screen strings that are being truncated; we could look a derivative of the original string on these final screens. It's not consistent, but we wouldn't sacrifice context. 
- Add custom URL | Add URL
- Remove custom URL | Remove URL
- URL autocomplete | Autocomplete
- Erase and | Erase (not sure about this one)
- Add search engine | Add
- Remove search engine | Remove
- Installed search engines | Installed

3. As you note, there's not a great way to shorten "add search engine." As strings become shorter, they have a way of becoming increasingly difficult to interpret and/or taking on unintended contexts. If it doesn't add too much friction to the process, it would be helpful to understand exactly how many characters localisers need to "get back."

**Comment by brampitoyo** [comment]
Thanks a lot @BrianNJones for your reply!

@Delphine, would you be able to help us answer question 2 and 3 above, and maybe have some of our localisers judge the accuracy and brevity of my poor man’s translation attempt below?

For now, we can already try out what these string derivatives look like on different locales, as seen below (caveat: my translation may be inaccurate – it’s just a first-round test).

| en | es-MX |  de |  fr | pl |
| --- | --- | --- | --- | --- |
| Add URL | Agregar URL | Addresse hinzufügen | Ajouter l'adresse | Dodaj adres |
| Remove URL | Eliminar las URL | Addresse entfernen | Supprimer l'adresse | Usuń adres |
| Autocomplete | Autocompletar | Autovervollständigung | Saisie semi-automatique | Autouzupełnianie |
| Installed | Instalar | Installierte | Installée | Zainstalowany |

From this limited example and admittedly amateurish translation, we can learn that shortening strings will help alleviate our headings-don’t-fit problem, but some shortened strings will still be too long.

I also learnt that even more space can be saved if we’re willing to switch some terms, like ‘address’ → ‘URL’. But I’m not sure if it’s a concept that translates across languages.

**Comment by brampitoyo** [comment]
> If you want to make the English strings shorter, that's really up to you. And as you say, it may still continue to truncate in some locales, and we have no way of predicting that (and which locales).

For me, this is the kicker. Even when we make the English string shorter, there’s no way for us to make sure that its localised strings will fit on all (or even most) locales.

And furthermore:

>  We can't get a sense if the localizers could shorten the strings as they are now - and in most cases they probably can't (and have probably tried to already).

Which means that, if we want to impose some sort of a character limits, it won’t help. The localisation is already as short as it’s possibly could.

The move I would recommend is either:

* To ask our localisers to take a second look at the 7 problematic strings, and make sure that the translations are as succinct as possible. Then we can review the screenshots.
* Or, to do nothing and keep the truncation as is. Not ideal, but because the cut-off strings appear on the last screens, they’re not such a big problem.

@Delphine, do you think that it’s worth asking our localisers to review these strings?

If they already have brevity in mind when the UI was originally localised, then our best move is to do nothing.

**Comment by BrianNJones** [comment]
To ask our localisers to take a second look at the 7 problematic strings,
and make sure that the translations are as succinct as possible. Then we
can review the screenshots
- Agree here

Or, to do nothing and keep the truncation as is. Not ideal, but because the
cut-off strings appear on the last screens, they’re not such a big problem.
- I do wonder if there's a distraction factor here. The truncations are
visually distracting. It's hard to see w/o a mock, but would be good to
compare a truncation with an option like: Remove search engine | Remove

**Comment by Delphine** [comment]
I'll ask localizers to check and try to shorten those as much as possible. 
However please note: I really don't have the bandwidth to go over 7 strings for each and ever one of our 81 different locales, to check which ones are truncating and which ones are not - and then later compare the results.
So we'll have to see if most of them stop truncating or not, in an approximative way
(also note one of the strings truncates even in English, so there's nothing we could do about that on l10n side). This is clearly not an optimal solution, and it would be better if there was a way to make the strings show entirely.
How about we get updated screenshots on Friday and see if there's been any improvement? CC @npark-mozilla to make sure he's able to do that, before I ping localizers.
Thanks

**Comment by brampitoyo** [comment]
@Delphine Thanks a lot. Yes, I completely understand your situation, and am happy to do some of the checking for you manually!

@BrianNJones, when we try to go from Remove search engine | Remove, and Add search engine | Add, I think that we’ll save a significant amount of space!

Example mock in 4 locales:

<img width="1724" alt="screen shot 2018-05-16 at 12 47 23 pm" src="https://user-images.githubusercontent.com/51007/40090694-93126ea6-5907-11e8-9592-bbca983e7e83.png">

**Comment by brampitoyo** [comment]
@Delphine and I talked today and managed to isolate the specific string IDs that our localisers can try to shorten.

### Summary

Recall our root issue. It came from the fact that each string showed up in at least two places: one for menu item, one for the page title. And the latter truncated.

Some of these strings have separate IDs. This means that it’s easy to re-translate and shorten one instance (page title) without compromising the verbosity of the other instance (menu item). We simply comment in the page title instance, “Refer to this screenshot, and try to shorten the translation as much as possible”.

However, some strings use the same IDs. This means that, if we shorten the translation of the page title (for example), we will also shorten the menu item. But fixing it isn’t impossible: create a new ID for the page title, and translate that separately – noting that it needs to be shortened.

Of course, this is not all. To successfully communicate the request to some of our localisers who aren’t  technical, we will need to link to a specific screenshot a specific locale and write something like “If you see the title on this screenshot truncate in your language, go to this string ID on Pontoon, and try to shorten them”. We’ll need to do this for all the truncated screens.

I think that’s roughly how this issue will move forward. Here’s hoping that doing so will fix most (if not all) of our truncation without too much complications.

Delphine will draft an email to our localisers. After the translations are finished and the screenshots are updated, we’ll reevaluate.

**Comment by Delphine** [comment]
Thanks Bram for sending this out!
Some comments

> This means that it’s easy to re-translate and shorten one instance (page title) without compromising the verbosity of the other instance (menu item). We simply comment in the page title instance, “Refer to this screenshot, and try to shorten the translation as much as possible”.

Well, I wouldn't say it's "easy" because I think in some cases they won't be able to shorten it very much.  But at least, they should know that they should try :) 
Also please note: if you just change the localization comment, unfortunately localizers won't get a notification and won't see it. Changing the string msgid would give them a notification that the string is fuzzy and without having to retranslate - and then they may see the comment - but since we don't want to change the existing string, I don't think that makes sense (please correct me if I'm wrong on that last bit though).
So, since we're talking about a very little number of strings here, I think it would make sense to just create brand new strings for these (so, create a new ID), and have the localizers translate them again. Pontoon should have translation memory that will help localizers too. That way we're sure they see the comment as well. How does that sound?

> However, some strings use the same IDs. This means that, if we shorten the translation of the page title (for example), we will also shorten the menu item. But fixing it isn’t impossible: create a new ID for the page title, and translate that separately – noting that it needs to be shortened.

Agreed with this.

> Of course, this is not all. To successfully communicate the request to some of our localisers who aren’t technical, we will need to link to a specific screenshot a specific locale and write something like “If you see the title on this screenshot truncate in your language, go to this string ID on Pontoon, and try to shorten them”. We’ll need to do this for all the truncated screens.

Oh I think we misunderstood each other for that part. So let me clarify: having a link to the specific screen where it truncates in the localization comment is a definitely plus (but not a must). It's super useful, but I can also help point them to the screens if needed. If the localization comment is updated, and clearly states that there is a strong risk that the string will truncate in that area (calling out the total number of possible characters would help too), then I think that's already super helpful. As I said, if it's not too much hassle, why not link to the screenshot as well there!
What's more the localizers will see that comment within Pontoon, next to the string in question, so localizers don't need to be sent to a specific string ID. 
So to recap: just an updated comment, with the max. number of possible characters for that string, saying it will truncate otherwise, and a link to the screen in the same comment, would be perfect.

To conclude, and if everyone agrees, I'd like to propose something slightly different: I think the simplest way of moving forwards - if there's absolutely no way to make more space for these strings in the areas where they truncate (and that's not my area of expertise) - would be to create a string export with the changes mentioned above (so, just change the IDs + update comment, and localizers will re-translate). Before merging, I can send an email to localizers to notify more clearly about all this, and give specific details. And then, we can reevaluate later and see if the situation got better.

I guess this is a lesson for us not to reuse strings that are long on mobile, when they will be used in areas that we think may end up truncating (like in page titles) :P (note that words in other languages are at least +30-50% longer than English - and most of the top marketshare locales are in the higher range. So if it barely fits in English, we can be sure it won't fit most other languages).

(ps Hope I haven't made this even more confusing)

**Comment by Sdaswani** [comment]
@Delphine we spoke to @BrianNJones and he feels while there has been good progress this will probably stall a bit since Bram is on vacation, and won't be completed by the end of next week. If you disagree let me know, else I will push it into 6.0.

**Comment by Delphine** [comment]
That sounds fine, I don't this this absolutely needs to be fixed immediately. Let's wait for Bram to come back from vacation. Thanks for asking Susheel! :)

**Comment by brampitoyo** [comment]
Hi @Delphine, I was back from vacation yesterday but didn’t quite get to this issue until today. Hope that’s okay!

Your proposal was:
> […] create a string export with the changes mentioned above (so, just change the IDs + update comment, and localizers will re-translate). Before merging, I can send an email to localizers to notify more clearly about all this, and give specific details. And then, we can reevaluate later and see if the situation got better.

I agree. Let’s do this, then wait for their work on Pontoon (we can check how many problematic strings stay the same after your email – this means that it’s simply impossible to shorten) and also wait for the new batch of screenshot (maybe it will fix it in some locales).

**Comment by Delphine** [comment]
Sounds good, thanks for all the help with this!

**Comment by bbinto** [comment]
@Delphine  - Difficult for me to follow here - what's the latest action item? Can this go into 6.1 (sprint ends this week Friday)

**Comment by Delphine** [comment]
Yes, this issue got complicated. 
Next step is for me to get a string export with localization notes updated where needed. For those cases we will need a new string ID. The comment should call out the max. number of possible characters for that string, and saying it will truncate otherwise.
@brampitoyo should know what these are since we've been going back and forth together about this.

I don't know by when you need to final strings for 6.1. I guess the fact if this can go into 6.1 also depends on when I get the export.

**Comment by Delphine** [comment]
WFM!

**Comment by brampitoyo** [comment]
As mentioned by @st3fan:

> The latest round of screenshots for Focus iOS are available at:
> https://wopr.norad.org/~fxios/screenshots/focus/20180703-1629/

@Delphine is this a good moment to re-check the truncated strings?

**Comment by Delphine** [comment]
I'm confused, those are iOS :)
Also, we're supposed to check the strings once the changes to comments are done, as we discussed in this thread. Maybe we should follow-up about this offline, because this issue is getting confusing?
As per my last comment:
"Next step is for me to get a string export with localization notes updated where needed. For those cases we will need a new string ID. The comment should call out the max. number of possible characters for that string, and saying it will truncate otherwise."
Once I get an export with these changes, *then* we can check the screenshots.

**Comment by brampitoyo** [comment]
> I'm confused, those are iOS :)

@Delphine You’re right. Sorry. It was my mistake for not double checking the screenshots!
