### ISSUE TITLE
Klar Geckoview does not display focus:<keyword> in About Firefox /Help/ Your Rights / Privacy Notic 

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2506]
Please let me know if this is not a bug, or geckoview limitation.  UI Test is failing on Klar on this, and I'll need to disable the test if that is the case.

### Steps to reproduce
Go to above mentioned pages from settings.
### Expected behavior
Show 'about: <keyword> on the url side
### Actual behavior
shows raw doc info as below:
<img width="387" alt="screen shot 2018-04-23 at 11 59 04 pm" src="https://user-images.githubusercontent.com/6930774/39153083-cacfeccc-4752-11e8-89e8-304e746a7dbb.png">

### Device information

* On Nexus 5X API 27 Sim

**Comment by ekager** [comment]
This is known so you can disable the test for now? But thanks for filing, let's keep this open and we should definitely follow up and fix this before Klar+GV release.

**Comment by ekager** [comment]
We actually pass in a `baseURL` and `historyURL`to WebView in the `loadDataWithBaseURL` and whatever you pass in for those params becomes the WebView's URL that we get passed back. 
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/webview/java/org/mozilla/focus/webview/SystemWebView.java#L210

Do you think this would be possible to add something similar to the GeckoView `loadData` method? I could also figure out a hack to override the URL when these internal links are loaded for now.

**Comment by cpeterso** [comment]
@ekager I don't see a GeckoView bug either, so I filed one:

https://bugzilla.mozilla.org/show_bug.cgi?id=1465634

**Comment by cpeterso** [comment]
@ekager - The GeckoView team thinks that Focus should be able to workaround this in the app, since Focus controls the address bar's state and rendering, not GeckoView. Also, the Gecko module owners are unlikely to want to support changing history URLs.
