### ISSUE TITLE
Resources.updateConfiguration is deprecated

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2507]
We use it here: https://github.com/mozilla-mobile/focus-android/blob/0c2232bde92eddbff7e1096fbdb49ec3cd1b6c6c/app/src/main/java/org/mozilla/focus/fragment/WebFragment.java#L94

See https://github.com/mozilla-mobile/firefox-tv/issues/850 for more details and user value.

**Comment by pocmo** [comment]
This could turn into a problem for our custom locale switcher.
