### ISSUE TITLE
Back button in Settings/About Us/Your Rights exits the app 

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#251]
STR:
- Open Focus
- Open About Us Page
- Press list app button (right of the home button) to list currently opened apps, and pick some other app
- Press list app button again, and select Focus
- Press back button on the heading
Expected:
Go back to the main view
Actual:
Exits to the finder

**Comment by pocmo** [comment]
> Open About Us Page

Seems like this can be reproduce with other screens like "settings" too.

**Comment by pocmo** [comment]
Oops. Didn't want to close this issue.
