### ISSUE TITLE
Enable javascript for the current page when globally disabled

### ISSUE THREAD

**Issue by RichyHBM** [mozilla-mobile/focus-android#2512]
### Why/User Benefit/User Problem
Currently if JS is disabled globally the only quick way to enable it on a page is to turn of focus tracker blocking, as opposed to going to the settings page and enable js. This would add a toggle to the drop down menu to enable js for just the current site

### What / Requirements
Have a toggle to enable JS for the current webpage
If JavaScript is not disabled in settings this toggle could be disabled

### Acceptance Criteria (how do I know when I’m done?)
- When I can enable JS for the current site without having to go into settings or disable all tracker blocking
- Navigating to a new page would again disable JS

**Comment by bbinto** [comment]
@brampitoyo - would you mind outlining our decision so @RichyHBM understands why we decided to UX that way.

**Comment by brampitoyo** [comment]
Hi @RichyHBM.

If I’m understanding you correctly, what you’d like to do is to have JS be enabled or disabled on a site-by-site basis, while having Tracking Protection be always on. Is this correct?

I’m going to try and explain why things are the way they are, below.

In Firefox Focus, all of our blocking settings is wrapped up into “one toggle to rule them all”. This toggle was never designed to replace your default settings. Actually, it will always default to ON every time you tap Erase.

This toggle was originally designed for the scenario below. Let me back up a bit.

Focus works by blocking stuff, right? And the more you block, the faster the page load, and the less ads and distractions you see. Unfortunately, the more things you block, the more likely will websites behave unexpectedly. There’s nothing you or we can do about this. This is just a side effect of blocking. More blocking means faster and less ads, but more chance for pages to not load normally.

To deal with this problem, we’ve designed a way for you to say “I want this site to _work, right now_”: by turning all of our blocking off with one “master switch”. If JavaScript was disabled, it’s enabled. If Cookies were refused, it’s accepted. If trackers were blocked, they’re allowed. Then the page can open normally, and you can get to what you want to see.

This “master switch” is so powerful, but at the moment we call it “Tracking Protection”, as if to imply that it only turns trackers blocking on and off.

Well, what about JavaScript? JavaScript is not considered a tracker, right? So we need a separate toggle for that. This was your question.

Based on that assumption, your question was entirely correct and understandable. Our original intention was to create a master switch. We haven’t gotten round to think of a good name for this switch. Surely, Tracking Protection is not inclusive enough.

I hope the thinking behind our decision can help answer your question!

I do have one request: would you help us think of some names for this master switch? Here are some that we’ve considered – not yet perfect:

* Privacy status [ON/OFF]
* Protection [ON/OFF]
* Content Blocker [ON/OFF]

**Comment by RichyHBM** [comment]
Fully understand, I do feel like the tracking side of things could be different to the performance options but also understand and agree that for some sites enabling the performance settings may not fix the site and its easier to just have a master toggle

Yes, I think a more generic name would be much more beneficial, I like the suggestion of content blockers, as the other two suggest that its privacy. Maybe even just *Blockers* [On/Off]

I also do think it could be beneficial to have a button to disable the blockers just for the current site, with a change of domain resetting it as currently you could forget to reenable the blockers when going to a different site

**Comment by bbinto** [comment]
cc'ing @BrianNJones to be kept in the loop

**Comment by brampitoyo** [comment]
@RichyHBM I like your suggestions. Calling this toggle something along the lines of _Blockers_ would reinforce the connection to the way we’ve described our setting menu item (we always call it _Block x tracker_ or _Block y_).

> I also do think it could be beneficial to have a button to disable the blockers just for the current site, with a change of domain resetting it as currently you could forget to reenable the blockers when going to a different site.

This is the way that our toggle work today. Its initial state is always `on`. Even if you’ve switched it `off`, all links that opens in a new tab will have the state set to `on`.

Or did you mean that you’d like all links that open in the same tab, including if you edit the URL, to have blockers set to `on`?

This is also an interesting idea. Let me ask our group and see!

**Comment by RichyHBM** [comment]
@brampitoyo 

> Or did you mean that you’d like all links that open in the same tab, including if you edit the URL, to have blockers set to on?

That was my initial idea, im not sure what the behaviour is when you click on a link on a website, does it open it in a new tab or does it open it in the same tab? If the former then its probably not a big deal, but if the latter then you might click on a link and not realise that trackers are disabled

**Comment by brampitoyo** [comment]
@RichyHBM 

> im not sure what the behaviour is when you click on a link on a website, does it open it in a new tab or does it open it in the same tab?

Our default is open in the same tab, unless the website gives the link a `target="_blank"` property.

So, yes. The user may click on a link and not realise that trackers are still disabled.

But we have two visual cues to help you know this:

1. The URL bar will be coloured dark purple (the normal state is bright purple)
2. A crossed out shield icon appears besides the menu

**Comment by bbinto** [comment]
@brampitoyo what's your final UX proposal so we can start prioritizing this.

**Comment by bbinto** [comment]
Sounds good, @brampitoyo - do you have any idea when we can work with UR to finalize mocks/strings etc?

**Comment by brampitoyo** [comment]
I expect this to happen by v7.0, or maybe even later. But it’s high on my priority list!

**Comment by bbinto** [comment]
I don't think that's as urgent as some of the other proposed 7.0 feature issues, moving this to a P3 to backlog

**Comment by bbinto** [comment]
Related to #2603

**Comment by brampitoyo** [comment]
When “Tracking Protection” is able to block many things more than trackers, it will be renamed to “Content Blocking” – to align with Firefox on Desktop.

Doing so will resolve this issue.

**Comment by GingerPlusPlus** [comment]
In my experience, disabling JS is far more likely to cause breakage than blocking all of ad trackers, analytic trackers and social trackers.
