### ISSUE TITLE
[l10n] Adding Purépecha to Focus Android on Pontoon

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#2516]
Heads-up that I just added Purépecha (tsz) to Pontoon.
This means they will need screenshots for testing, but aren't shipping yet.
(CC @pocmo mainly, I think)

**Comment by pocmo** [comment]
Let's add this to ADDITIONAL_SCREENSHOT_LOCALES in locales.py:
https://github.com/mozilla-mobile/focus-android/blob/master/tools/l10n/locales.py#L103
