### ISSUE TITLE
Cannot dismiss security popup

### ISSUE THREAD

**Issue by Debdeep009** [mozilla-mobile/focus-android#2518]
### Steps to reproduce
Load a webpage, Click on security `ImageView` inside the toolbar, Popup appears.

### Expected Behaviour
Popup could've been dismissed on touching outside or on backpress.

### Actual Behaviour
Couldn't be dismissed. Background was null when debugged in the mentioned device.

### Device information
Yu YU5010A
5.1.1 Lollipop

### Firefox version
Any

### User Agent
`Your user agent: Mozilla/5.0 (Linux; Android 5.1.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.1 Chrome/66.0.3359.106 Mobile Safari/537.36 Other HTTP headers Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8 Accept-Encoding: gzip, deflate Accept-Language: en-IN,en-US;q=0.9 Host: duckduckgo.com Referer: https://duckduckgo.com/ User-Agent: Mozilla/5.0 (Linux; Android 5.1.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.1 Chrome/66.0.3359.106 Mobile Safari/537.36 UPGRADE-INSECURE-REQUESTS: 1 X-REQUESTED-WITH: org.mozilla.focus.debug`

### Screenshot
![screenshot_2018-04-25-02-11-22 1](https://user-images.githubusercontent.com/18580237/39216451-59608fb4-4839-11e8-8bed-573ad4cdd6bb.png)

**Comment by Debdeep009** [comment]
@pocmo Gets fixed by adding a transparent background to the `PopupWindow`. Shall I make a pull request of this?

**Comment by ekager** [comment]
Sure @Debdeep009 go ahead and make a PR, I can review.
