### ISSUE TITLE
3rd party cookies are not blocked by default

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2521]
Steps to reproduce:
1. With a fresh Focus build install, go to Settings.
2. Tap the "Block cookies" menu.

Expected behavior
Based on the acceptance criteria in bug #2330 :
-"3rd party cookies are blocked and off by default"
"Blocking 3rd party cookies" is set by default.

Actual behavior
Blocking 3rd party cookies is not the default. The option "No" (don't block cookies) is the default value.

Device information:
Samsung Galaxy S6 (Android 6.0.1)

Build:
Focus Beta Build 5.0

**Comment by pocmo** [comment]
@bbinto @ekager Release blocker?

**Comment by ekager** [comment]
This is for 5.0 so we have until friday code freeze to fix. I’m on it!

**Comment by bbinto** [comment]
Yes, release blocker, @pocmo

**Comment by bbinto** [comment]
@pocmo + @boek + @ekager 

Apologies, this was my mistake, I misread the ticket.

We've agreed in sprint review:

"Block 3rd party cookies" toggle should be off by default

(the least intrusive setting to avoid any breakage)

We can always change it later, in future releases, set on by default with a better intro / onboarding for existing users.
