### ISSUE TITLE
TP toggle off in menu should turn off 3rd party cookie blocking

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2522]
Steps to reproduce:
1. With a fresh Focus build install, go to Settings.
2. Tap the "Block cookies" menu: it should have block 3rd party cookies blocked.
3. Back on the homepage toggle off the TP from the menu.
4. Return to the Block Cookies settings.

Expected behavior:
Based on the acceptance criteria in bug #2330 :
-"Toggle off in menu will turn off 3rd party cookie blocking as well"
And the following comment: https://github.com/mozilla-mobile/focus-android/issues/2330#issuecomment-379594338

The tracking protection toggle should affect the cookies enabled state.

Actual behavior:
The trackers toggle in the menu does not affect the cookies settings: turning it off doesn't change the cookies state from blocked to enabled, nor vice-versa.

Device information:
Samsung Galaxy S6 (Android 6.0.1)

Build:
Focus Beta Build 5.0

**Comment by pocmo** [comment]
The acceptance criteria is not clear in this case: While the main switch in the menu is off cookies should not be blocked (and JavaScript should be on, and no trackers should be blocked) for this tab anymore. However it should not change the global settings.

**Comment by sv-ohorvath** [comment]
Ok, I misunderstood that. Thank you!
