### ISSUE TITLE
Request to include Findx.com as alternative search engine

### ISSUE THREAD

**Issue by br-privacore** [mozilla-mobile/focus-android#2525]
We kindly request that Findx is included in the list of alternative search engines, potentially globally like DuckDuckGo, or for specific countries like e.g. Qwant.

### Why/User Benefit/User Problem
A growing number of users are concerned about the data collection and user profiling done by Google. At Findx, we offer an alternative. Findx is a **European privacy-first search engine** that never stores or shares information about our users.

We are not just another meta search engine. We operate our **own search index**, and our core code is **open source**. This means our ranking algorithm is transparent, and later this year we will be giving users the choice to modify ranking factors.

Primary supported markets are all European countries, USA, Canada and Australia.

More information at https://get.findx.com/ - try it out at https://www.findx.com
Contact: Brian Rasmusson, br@privacore.com, mobile +45 31616263

### What / Requirements
Please include Findx.com as a default alternative search engine. Configuration file is attached.
[findx.zip](https://github.com/mozilla-mobile/focus-android/files/1947423/findx.zip)

For Denmark specifically:
[da-findx.zip](https://github.com/mozilla-mobile/focus-android/files/1947619/da-findx.zip)

### Acceptance Criteria (how do I know when I’m done?)
Findx can be selected as default search engine.

**Comment by pocmo** [comment]
Duckduckgo is included globally. Qwant is listed in de, en-GB and fr.

**Comment by br-privacore** [comment]
Sorry about that mistake, you are correct of course.

**Comment by bbinto** [comment]
@br-privacore we have search agreements with the providers listed on the default search provider list. Please reach out to our BD team for more details.

As for now, I will close this issue. Users who really want to use findx can do so by following these steps: https://support.mozilla.org/en-US/kb/add-search-engine-firefox-focus-android

**Comment by br-privacore** [comment]
@bbinto OK, will get in touch with BD. I thought you only had agreements with "the big guys", and not our competitors DuckDuckGo and Qwant.
