### ISSUE TITLE
CDATA escaping missing when importing strings.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#253]
I just did a string import (See #252) and saw that the CDATA escaping is missing from the strings.xml files. Because of that we are loosing the HTML tags / formatting when displaying those strings.

**Comment by pocmo** [comment]
@ahunt: I wonder if we could just wrap an imported string in CDATA whenever there's something in there that looks like a tag.

**Comment by ahunt** [comment]
I think I forgot to push my branch, I'm trying to recover it now...

**Comment by ahunt** [comment]
nvm: this isn't working:
https://github.com/mozilla-mobile/focus-android/commit/da1293679f0727c80b1b0fc38d112d525dfe2974

We need to expand our detection for at least the about page which doesn't have <ul>

**Comment by ahunt** [comment]
Looking at the latest import, I noticed even <ul> isn't being detected - which is really odd. (I'd been testing on some fake data locally), so this might need more work:
https://github.com/mozilla-mobile/focus-android/pull/252/commits/28e24734b3c8198f01781c0492d38b93265d7c61
