### ISSUE TITLE
Unexpected behaviour when clicking on secure icon

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2537]
Via Google Play Store

<img width="772" alt="screen shot 2018-04-26 at 7 48 50 pm" src="https://user-images.githubusercontent.com/122897/39337450-ff510050-498a-11e8-8dba-0b3a73fb1e4c.png">

**Comment by pocmo** [comment]
>  Is this a release blocker for 4.2?

4.2. is already in staged rollout. At this point we could only make a dot release - but we are going to release 5.0 now anyways. Is it fixed in 5.0?

**Comment by Serkan-devel** [comment]
Same on Android 5.0.1 with the latest F-Droid build

**Comment by Serkan-devel** [comment]
When will it be pushed on f-droid?

**Comment by pocmo** [comment]
The f-droid builds are not maintained by us.
