### ISSUE TITLE
First run tour on small devices: needs spacing between the Skip button and the slides

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2542]
### Steps to reproduce
1. Start a fresh install of Focus.
2. Look at the Skip button in the first run tour.

### Expected behavior
On smaller devices, there should be a little spacing between the Skip button and the tour slides.

### Actual behavior
On small devices, the slides are too large, covering a bit the Skip button. See screenshot from a Google Pixel (5.0-inch screen).

### Device information
Affected: Google Pixel, 5.0 inch display.
Not affected: Sony Xperia Z5 Premium, 5.5 inch display.
![screenshot_20180427-100526](https://user-images.githubusercontent.com/4037709/39349709-91e9b758-4a04-11e8-8451-c32cdc91be75.png)

* Focus version: 
Play store version: v4.1
Beta v 5.0

**Comment by Sdaswani** [comment]
Since this is not a new regression in 5.0, we don't need to fix for 5.0.

**Comment by brampitoyo** [comment]
<img width="770" alt="screen shot 2018-05-03 at 5 05 54 pm" src="https://user-images.githubusercontent.com/51007/39560689-59066e32-4ef4-11e8-91a0-bad714fc7442.png">

Let me know if a scaling like this doesn’t work on smaller devices, and I can propose an alternative design.

**Comment by pocmo** [comment]
@brampitoyo There's no fixed margin currently - because initially we didn't want to have gigantic cards on tablets.

CC @antlam

**Comment by brampitoyo** [comment]
@pocmo That makes sense.

So to make the content works down to the smallest screen, we want to set a min-width and min-height value, rather than specify a static margin?

As @npark-mozilla had shown with truncation on many locales (#2505), some other UI elements may truncate on this particular screen size.

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on Google Pixel (Android 10) with RC 92.1.1:

![Screenshot_20210923-222610](https://user-images.githubusercontent.com/40694158/134469688-9de1c319-6dec-4884-86d3-c2b0e4c6867c.png)
