### ISSUE TITLE
Focus v5.0 'What's new' page returns "Page not found"

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2543]
### Steps to reproduce
Open the What's new page from the menu.

### Expected behavior
The SUMO page for Focus 5.0 should open.

### Actual behavior
The link returns a "Page not found." error.

### Device information

Build: Focus Beta v5.0

**Comment by Sdaswani** [comment]
@ekager @boek is the 5.0 page not ready yet? may need to check with @jonisavage

**Comment by boek** [comment]
@Sdaswani we have the link, I think we're just waiting for the sumo page to go live

**Comment by boek** [comment]
Page is now live, link works in app 🙌

https://support.mozilla.org/en-US/kb/new-focus-android-5
