### ISSUE TITLE
URL bar not updated after a search

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2544]
### Steps to reproduce
1. Type a search term in the URL bar and submit.
2. Tap the URL bar, try to copy the search results URL.

### Expected behavior
The search results URL should be visible after taping the bar.

### Actual behavior
The search term is displayed when tapping the URL. Can't copy/edit the URL.

### Device information
Google Pixel (Android 8.1.0)

###Builds: 
Focus Beta v5.0 Build & Focus 4.1

**Comment by pocmo** [comment]
Hehe. That's actually a feature I think. :) #891

**Comment by ekager** [comment]
Yep that's correct behavior (Doesn't work on GV builds yet). Closing.
