### ISSUE TITLE
Accessibility Improvements to First Run, Loading, and Erase Button

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2553]
### Why/User Benefit/User Problem
We've been adding a lot of features/UX changes and we should make sure they are all accessible for our users.

### What / Requirements
- Get feedback from accessibility team 
- Implement any needed changes

### Acceptance Criteria (how do I know when I’m done?)
Focus is accessible to all users.

**Comment by ekager** [comment]
cc @eeejay

**Comment by ekager** [comment]
Thanks for this @eeejay ! Definitely looks like some good issues to tackle, I will rename the issue and we can put the work into an upcoming sprint :)

**Comment by bbinto** [comment]
@ekager to break down into further issues

**Comment by MarcoZehe** [comment]
I took another look at the current Play Store version, and @eeejay really covered it all in his comment above. Thanks for jumping in while I was away, Eitan! And, on top, I would probably not have noticed a couple of these things since I can't see the screen. :)

**Comment by bbinto** [comment]
@ekager already fixed the first issue, will break down the other ones in further GH issues

**Comment by rpappalax** [comment]
Navigating with talkback seems to work well now  with exception of last screen where the user gets 'trapped' unless they know where on the screen to double press "OK, got it."  Perhaps a final swipe should exit the first run dialogue?

**Comment by ekager** [comment]
@sblatz did you close all of the breakdowns of this bug? If so this can be closed

**Comment by sblatz** [comment]
@ekager I did close all of them, but perhaps @rpappalax's comment should be filed as a follow-up issue?

**Comment by sblatz** [comment]
#3308 Fixes the last portion of this issue. Ready for closing :)
