### ISSUE TITLE
Remove Deprecated Compile

### ISSUE THREAD

**Issue by gupta1anubhav** [mozilla-mobile/focus-android#2554]
Steps to reproduce
1. Build project 
2. Check build info.

We need to change androidTestCompile to androidTestImplementation as compile is deprecated.

![1](https://user-images.githubusercontent.com/31107831/39393004-7c3a50b4-4add-11e8-92d2-921caca9b81c.png)

Would you like to work on this issue?
Yes, I want to work on this issue.

**Comment by pocmo** [comment]
Yes, that would be nice to fix. 👍 

@gupta1anubhav Feel free to open a PR for this. :)

**Comment by ekager** [comment]
Closed by #2562
