### ISSUE TITLE
Feature Request: Ability to block websites

### ISSUE THREAD

**Issue by peterbraden** [mozilla-mobile/focus-android#2556]
### Why/User Benefit/User Problem

On android at the moment there is no way to block arbitrary websites without rooting your phone. There are a ton of distracting websites that I would like to block on my mobile device. If Firefox focus included the ability to block arbitrary sites then I would be able to focus better.

### What / Requirements

The ability to create a list of domains that are blocked, similar to redirecting to 127.0.0.1 in /etc/hosts.

### Acceptance Criteria (how do I know when I’m done?)

When I can block arbitrary websites in Firefox Focus

**Comment by levimatheri** [comment]
What about [this](https://github.com/levimatheri/focus-android/commit/65b6c49ae3eb71f8f2247fc59c04c8dc2a394f6a) for a start? It's only UI for now, almost identical to CustomDomains

**Comment by levimatheri** [comment]
@ekager do you mind taking a look at my commit above? I want to make sure I have the right UI for this before implementing functionality

**Comment by pocmo** [comment]
@levimatheri Unfortunately this feature request currently has a P5 priority - which makes it unlikely to get attention from the UX team at this time.
