### ISSUE TITLE
lo: missing placeholder in translation, key: security_popup_security_verified

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2557]
Our string import is failing with a missing placeholder:

> Error: * [values-lo/strings.xml] missing placeholder in translation, key: security_popup_security_verified

**Comment by pocmo** [comment]
CC @Delphine

**Comment by Delphine** [comment]
Just fixed this in Pontoon. Will communicate with "lo" team to let them know for future reference too.

**Comment by bbinto** [comment]
No eng work needed
