### ISSUE TITLE
Error "Expected resource of type raw"

### ISSUE THREAD

**Issue by gupta1anubhav** [mozilla-mobile/focus-android#2571]
ResourceId in the red underlined text is the problem here.

Android lint: Wrong Resource Type error in HtmlLoader.java

Expected resource of type raw is the error description.

![3](https://user-images.githubusercontent.com/31107831/39476238-dd9312e0-4d78-11e8-9f5e-52bcb8fc0db2.png)

Would you like to work on this issue?
Yes, I want to work on this issue.

**Comment by bbinto** [comment]
Feel free to pick this up, and create a PR

**Comment by gupta1anubhav** [comment]
Thank you @bbinto

**Comment by gupta1anubhav** [comment]
This error is not anymore in the latest build. Hence, I am closing the issue.
