### ISSUE TITLE
Google Play release notes for 5.0

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#2575]
We were going to use the content of "What's New" but both of the line items had links

> Block third-party cookies. This is off by default. To block all or third-party cookies, see [Block cookies in Firefox Focus for Android].
> Add custom URLs to your autocomplete list by long-tapping on the address bar. See [Autocomplete settings] to learn more.

Could we get a simplified version for the Google Play store release notes?

**Comment by BrianNJones** [comment]
Sounds great.

**Comment by BrianNJones** [comment]
@boek, how's this look?
- Control cookie blocking : block all cookies, block 3rd-party cookies, or accept all cookies
- Long press address bar to add a URL to your autocomplete list

(If "long tap" is in the Release Notes, we should update to "long press")

@bbinto, Focus has evolved to the point it makes sense to take another look at the general Google Play description and at the "About" content under Settings. I can take a swing at the GP content to run by marketing.

**Comment by boek** [comment]
I think that looks good. @bbinto Could we get a German translation?

**Comment by bbinto** [comment]
@BrianNJones - the cookie bullet is correct, however it washes away our additional feature of only now being able to block 3rd party cookies.

Thougths?

**Comment by BrianNJones** [comment]
@bbinto - if i'm understanding correctly, your concern is it's not doing enough to highlight the "3rd party" part? i was thinking it's more about "cookie blocking' than "3rd-party cookies." We could revise to:

- Block cookies: block 3rd-party cookies, block all cookies, or accept all cookies

**Comment by bbinto** [comment]
@BrianNJones - sorry for being so picky about this, since this additional 3rd party blocking feature is opt-in, I want to draw attention to it. However, to be honest looking at the toggle again, it seems confusing to me that this is a new "additional" feature, because of the toggle switch (3rd party cookies, "only"). 

I might have missed this in the sprint review. At this point, I think we need to keep it as is let's go with your string.

**Comment by bbinto** [comment]
@boek here is the German translation

Block cookies: block 3rd-party cookies, block all cookies, or accept all cookies

Blockieren von Cookies: Cookies von Drittanbietern blockieren, alle Cookies blockieren oder alle Cookies akzeptieren

**Comment by bbinto** [comment]
@boek here is the German translation

Blockieren von Cookies: Cookies von Drittanbietern blockieren, alle Cookies blockieren oder alle Cookies akzeptieren

**Comment by boek** [comment]
@bbinto Sylvestre has concerns about the "Whats New" copy here: https://bugzilla.mozilla.org/show_bug.cgi?id=1459837#c7

**Comment by bbinto** [comment]
@boek -- sorry can't get the 2FA working for Bugzilla, therefore here my comments

English:
Improved cookie management, users can now setup more granular cookie blocking: block 3rd-party cookies, block all cookies, or accept all cookies

German:
Verbessertes Cookie Management: Benutzer können nun das Blockieren von Cookies detaillierter einstellen, z.b. Cookies von Drittanbietern blockieren, alle Cookies blockieren oder alle Cookies akzeptieren.

**Comment by BrianNJones** [comment]
If we're going to start using language like "improved," we need to address
both before (the "unimproved") and the "improved." Takes quite a bit of
space and doesn't make sense in this instance. "Granular" is not likely to
be a word that makes sense to all users in this context. I don't see
Sylvestre's point, but a compromise could be:

English:
Improved cookie management: users can now block 3rd-party cookies, block
all cookies, or accept all cookies.

-Brian

**Comment by bbinto** [comment]
Ok @BrianNJones 

Here is the updated German translation:

Verbessertes Cookie Management: Benutzer können nun das Blockieren von Cookies einstellen, z.b. Cookies von Drittanbietern blockieren, alle Cookies blockieren oder alle Cookies akzeptieren.

**Comment by bbinto** [comment]
@boek, can this be closed?

**Comment by boek** [comment]
Looks great! thank you!
