### ISSUE TITLE
No crashes showing up for 5.0 in Sentry/Google Play

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2583]
5.0 has been in Beta for >24h now and we do not see any crashes in Sentry or Google Play. Something seems to be wrong.

I unpacked the release APK yesterday and the token seems to be in the APK.

**Comment by pocmo** [comment]
This shows up in the logs whenever we want to send something to Sentry:
```
             System.err  W  SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
                         W  SLF4J: Defaulting to no-operation MDCAdapter implementation.
                         W  SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
```

**Comment by pocmo** [comment]
Events I send manually via `Sentry.capture()` seem to come through regardless. But crashes still do not show up.

**Comment by ekager** [comment]
Could this be related...? Copied from TV's implementation https://github.com/mozilla-mobile/focus-android/blob/master/app/proguard-rules.pro#L89

**Comment by ekager** [comment]
And maybe we want to do their recommended gradle config instead of manual  https://docs.sentry.io/clients/java/modules/android/#proguard

**Comment by boek** [comment]
We took our Sentry and it looks like Focus is still stuck on the Google Play side. We're going to go to 100% on Monday see if that clears it up.
