### ISSUE TITLE
Obsolete Gradle Dependencies

### ISSUE THREAD

**Issue by gupta1anubhav** [mozilla-mobile/focus-android#2584]
AndroidLint: Correctness warning
Few issues
1.Obsolete Gradle dependencies
2.Spelling error
3.Using sp instead of dp for text sizes.

![5](https://user-images.githubusercontent.com/31107831/39621003-cad2623a-4faa-11e8-8491-29526b93f3ef.png)

Would you like to work on this issue?
Yes, I want to work on this issue.

**Comment by gupta1anubhav** [comment]
@pocmo can I work on this issue?

**Comment by pocmo** [comment]
@gupta1anubhav Yes. Please create separate PRs for the different issues. :)
