### ISSUE TITLE
Add "force enable zoom" accessibility option

### ISSUE THREAD

**Issue by hackel** [mozilla-mobile/focus-android#2594]
### Why/User Benefit/User Problem

Many websites prevent zooming, making small text and images difficult to see.  This presents an accessibility problem even for those who are not visually impaired.  I often find myself having to open a site in Firefox just to be able to zoom in on something—particularly images.

### What / Requirements

I assume this is merely a flag for the Webview, since it's supported by Chrome, but I have no idea technically.

### Acceptance Criteria (how do I know when I’m done?)

When enabled, pinch-to-zoom works on every website, all the time, no matter what.

**Comment by brampitoyo** [comment]
What you can always pinch-to-zoom on every website by default, without a way to turn it off?

This is good for 2 reasons:

1. If publishers design websites correctly for mobile, it will handle pinch-to-zoom without breaking elements.
2. “Let Users Control Font Size” is important for usability, and aligns with our principle of giving control back to the user.

Will this introduce unintended consequences for websites that force a non-zoomable layout?

**Comment by TPS** [comment]
https://stackoverflow.com/questions/7121053/how-to-enable-zoom-controls-and-pinch-zoom-in-a-webview for code & tips.

**Comment by pocmo** [comment]
This exists in Fennec: Settings -> Accessibility -> Always enable zoom (Off by default)

**Comment by brampitoyo** [comment]
If there’s a precent from Fennec, let’s do exactly what they’re doing in our product.
