### ISSUE TITLE
DatePicker is broken

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#2595]
### Steps to reproduce
Access http://www.456bereastreet.com/lab/html5-input-types/
Press the **Date** input type
Rotate screen
### Actual behavior
Because when rotating the screen the previous layout is kept, selecting a date can be impossible for the user.

GIF screen recording - https://user-images.githubusercontent.com/11428869/39920849-45539012-5521-11e8-90f4-c734ad54d138.gif

### Device information
Samsung S7 with Android 7.0
(but I think the problem is not related to a specific device)

**Comment by bbinto** [comment]
@Sdaswani to confirm with reporter

**Comment by Mugurell** [comment]
To confirm, this is exactly what happens to Chrome 66 on Android also: 
![chrome66_broken_datepicker](https://user-images.githubusercontent.com/11428869/40408368-f4efc516-5e6f-11e8-8d41-d9b92666697a.gif)

I only got to this on Focus because we received tickets about it for Fennec and was curious how Focus dealt with it.

Because all 3 browsers are using platform's APIs (broken), all seem to be affected by the same inherent bugs.

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the 93.1.1 RC build, with Lenovo Tab M10 (Android 10), nor on Xiaomi mi4i (Android 5.0.2).

**Comment by Mugurell** [comment]
Tested on today's code. These pickers are still broken.

https://user-images.githubusercontent.com/11428869/136001305-59a0e8bf-b7a4-4af4-bfa5-83222c6ee01d.mp4
