### ISSUE TITLE
TimePicker is broken

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#2596]
### Steps to reproduce
Access http://www.456bereastreet.com/lab/html5-input-types/
Press the **Time** input type
Rotate screen
### Actual behavior
Because when rotating the screen the previous layout is kept, selecting a time can be impossible for the user. Trying to start the time picker widget while in landscape doesn't show any actionable items.

GIF screen recording - https://user-images.githubusercontent.com/11428869/39921118-697b9d94-5522-11e8-88f0-6c22140e1f1f.gif

### Device information
Samsung S7 with Android 7.0
(but I think the problem is not related to a specific device)

**Comment by bbinto** [comment]
@Sdaswani to confirm with reporter.

**Comment by Mugurell** [comment]
To confirm, this is exactly what happens to Chrome 66 on Android also:
https://user-images.githubusercontent.com/11428869/40408520-8d219d82-5e70-11e8-9bdf-06850d2f3a52.gif


I only got to this on Focus because we received tickets about it for Fennec and was curious how Focus dealt with it.

Because all 3 browsers are using platform's APIs (broken), all seem to be affected by the same inherent bugs.

**Comment by ekager** [comment]
Should we file a bug with the Android/Chromium team @pocmo for this and #2595 ?

**Comment by pocmo** [comment]
Yes! Let's file this there:
https://bugs.chromium.org/p/chromium/issues/list
