### ISSUE TITLE
Report site issue: Upload screenshot

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2607]
Follow-up from #2378.

The issue reporter allows screenshots to be attached. 

Related code in Firefox for Android:
* https://dxr.mozilla.org/mozilla-central/source/mobile/android/chrome/content/WebcompatReporter.js#72
* https://dxr.mozilla.org/mozilla-central/source/mobile/android/chrome/content/WebcompatReporter.js#129

**Comment by RomanWuattier** [comment]
Following #2378, can I work on this one?

I already started in #2378. That is the state of affairs.

- [ ] Grab a screenshot
The screenshot is always transparent for now
- [x] Post the screenshot

**Comment by pocmo** [comment]
@RomanWuattier Yes, you can take it. I'm not sure whether this is ready yet though. This needs to run in a GeckoView build and afaik we can't inject JavaScript yet.

**Comment by RomanWuattier** [comment]
Indeed, I wasn't working with GeckoView build till now. Should I wait for a GeckoView update?

**Comment by pocmo** [comment]
I filed a bug to get screenshot support in GeckoView:
https://bugzilla.mozilla.org/show_bug.cgi?id=1462018

**Comment by lobontiumira** [comment]
This issue still reproduce on Focus 92,1,1, with a Google Pixel (Android 10), and a Samsung Galaxy Tab A6 (Android 5,1,1).
I cannot upload a screenshot when filing a site issue on webcompat page.

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly 102.0a1 from 5/11.
Tested with several devices:
* Sony Xperia Z5 Premium (Android 7.1.1),
* Oppo Find X3 Lite (Android 11), and
* Samsung Galaxy Note 8 (Android 9).
