### ISSUE TITLE
Cannot add a link to Home screen if the screen has no space left

### ISSUE THREAD

**Issue by kai-chi** [mozilla-mobile/focus-android#2620]
### Steps to reproduce
1. Fill your home screen with apps so it doesn't have any space left
2. Open Focus and go to any website
3. Try to add a link to it using "Add to Home screen" -> "Add"
4. The phone goes back to home screen and you can see a toast "No space left on current screen."

### Expected behavior
A new home screen page is created and the link is added there. (This is the behavior of Google Play when installing a new app)

### Actual behavior
The link is not added to the home screen. The user has to manually create a new home screen page or free space in the current one and repeat the process of adding the link.

### Device information
Huawei P10 lite
Android 7.0

* Firefox version: 4.1

**Comment by bbinto** [comment]
@kai-chi - what kind of a launcher do you use?

**Comment by kai-chi** [comment]
@bbinto it's "Huawei Home"
