### ISSUE TITLE
Search suggestion UI in URL Overlay

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#2629]
Part of #1930 

- [ ] Search suggestion / Autocomplete compatibility

---

![image](https://user-images.githubusercontent.com/1250545/40245860-a40d102e-5a7b-11e8-99cb-06c1f0c65d9a.png)

![image](https://user-images.githubusercontent.com/1250545/40245791-6fc33dc0-5a7b-11e8-883e-2579cf13f046.png)

**Comment by boek** [comment]
@brampitoyo This is what it looks like with the new strings.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/1250545/43743708-c6773208-998b-11e8-8a58-e6a0b8020d5a.png">

Is this good with you?

**Comment by brampitoyo** [comment]
@boek Let’s try something like this:

<img width="360" src="https://user-images.githubusercontent.com/51007/43745919-6851795e-9a35-11e8-9711-1586e4fd6ba0.png">

#### Spec

<img width="360" src="https://user-images.githubusercontent.com/51007/43745933-6ea6cfe8-9a35-11e8-8351-2e19b5841df2.png">
