### ISSUE TITLE
Don't advertise custom tabs until support is complete

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#263]
We probably shouldn't advertise custom tabs support until we're happy they're properly supported.

If we do leave CT enabled, we need to double check the interactions with our custom tab usage for info pages. My WIP patches prefer using focus as the custom tabs provider, but since MainActivity is singleInstance/singleTask, we end up losing existing browsing data if you do something like MainActivity->Browser URL_X->settings->Help (which opens in the same activity as URL_X). Pressing back you get Help->Settings->Home Screen (if our custom tabs were in a separate independent Activity, and/or if we allowed multiple instances of MainActivity, this wouldn't be an issue).

**Comment by pocmo** [comment]
See #19 - I would actually like to keep that. I don't really like that CT supporting browsers are stealing my session even though they are not my default browser. But yeah, let's discuss this and come up with a solution.

**Comment by pocmo** [comment]
Closing this as we are not landing the patches for now. We can use #19 to track improving custom tabs in a future iteration.
