### ISSUE TITLE
Search engine selection should be based on country

### ISSUE THREAD

**Issue by mueller-ma** [mozilla-mobile/focus-android#2632]
Currently the available search engines are based on the language. I have set my phone to en-DE and I guess it makes more sense to have amazon.de (also available in english) as available search engine. I know that I can add all websites as custom search engine, but it should be listed by default.

**Comment by pocmo** [comment]
Okay, thanks! In this case I'm closing this issue for now. We just managed to get into a state where we use list.json across all our products and I do not want to diverge from that again. :)
