### ISSUE TITLE
Pressing "back" does not dismiss text selection toolbar

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2633]
### Steps to reproduce

* Select text on a website
* Press "back" button

### Expected behavior

* The floating text selection toolbar should disappear

### Actual behavior

* WebView builds: We navigate back or leave the app
* GeckoView builds: We navigate back or leave the app AND the text selection toolbar is still visible; even if there's no web content shown anymore.

**Comment by ekager** [comment]
Did you already file a Bugzilla bug for this? And should we add a Klar/GeckoView tag?

**Comment by pocmo** [comment]
I don't think I did... doing now!

**Comment by pocmo** [comment]
![textselection](https://user-images.githubusercontent.com/89638/42652288-3a10d364-8612-11e8-847c-c1735ba32d8c.png)

**Comment by pocmo** [comment]
This seems to be fixed in the latest Nightly.
