### ISSUE TITLE
How to add class as a jar

### ISSUE THREAD

**Issue by levimatheri** [mozilla-mobile/focus-android#2634]
CustomDomains is contained within mozilla.components and is located in .gradle/caches/modules-2/files-2.1/org.mozilla.components. How does one add another item into org.mozilla.components so that it's seen by Android Studio?

**Comment by pocmo** [comment]
Everything in mozilla.components.* is from binaries pulled form jcenter (see build.gradle). If any of the components need to be modified then take a look at our components repository:
https://github.com/mozilla-mobile/android-components

**Comment by levimatheri** [comment]
I see. Thank you
