### ISSUE TITLE
Klar (Geckoview) crashes when trash icon is clicked after site is loaded

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2635]
### Steps to reproduce
- Do a fresh install of Klar
- Load website (e.g. cnn.com or buzzfeed.com)
- After loading is complete, press trash icon

### Expected behavior
- Goes back to the main view

### Actual behavior
- Goes back to the main view, then exits the app
- This only seems to happen with fresh install.

### Device information
- Pixel 2

Logcat is attached.  This also affects nimbledroid runs, because the app crashes before the tests are completed.  It might be a strictmode issue?
[log.txt](https://github.com/mozilla-mobile/focus-android/files/2026552/log.txt)

**Comment by boek** [comment]
@npark-mozilla verify that its fixed

**Comment by npark-mozilla** [comment]
Actually, this is still here, I can repro this on release Build.

**Comment by npark-mozilla** [comment]
But it looks like it's an intermittent issue - I can only repro this only a handful of times.

**Comment by npark-mozilla** [comment]
05-25 15:34:52.985 19432 19458 I nsScreenManagerAndroid: nsWindow[0x91bd8970]::Resize [0.000000 72.000000 1080.000000 1704.000000] (repaint 0)
05-25 15:34:53.225 19465 19493 D GeckoViewContent[C]: handleEvent: DOMTitleChanged
05-25 15:34:53.236 19432 19458 D GeckoViewProgress: onStateChange: isTopLevel=false, flags=0xc0010, status=NS_OK
05-25 15:34:53.291 19432 19458 D GeckoViewProgress: onStateChange: isTopLevel=false, flags=0xc0010, status=NS_BINDING_ABORTED
05-25 15:34:53.335 19432 19458 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 19458 (Gecko)
05-25 15:34:53.335   437   437 W         : debuggerd: handling request: pid=19432 uid=10131 gid=10131 tid=19458
05-25 15:34:53.344 19811 19811 W debuggerd: type=1400 audit(0.0:162): avc: denied { search } for uid=0 name="org.mozilla.klar" dev="dm-1" ino=3706 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-25 15:34:53.344 19811 19811 W debuggerd: type=1400 audit(0.0:163): avc: denied { search } for uid=0 name="org.mozilla.klar" dev="dm-1" ino=3706 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-25 15:34:53.344 19811 19811 W debuggerd: type=1400 audit(0.0:164): avc: denied { search } for uid=0 name="org.mozilla.klar" dev="dm-1" ino=3706 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-25 15:34:53.344 19811 19811 W debuggerd: type=1400 audit(0.0:165): avc: denied { search } for uid=0 name="org.mozilla.klar" dev="dm-1" ino=3706 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-25 15:34:53.344 19811 19811 W debuggerd: type=1400 audit(0.0:166): avc: denied { search } for uid=0 name="org.mozilla.klar" dev="dm-1" ino=3706 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-25 15:34:53.344 19811 19811 W debuggerd: type=1400 audit(0.0:167): avc: denied { search } for uid=0 name="org.mozilla.klar" dev="dm-1" ino=3706 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-25 15:34:53.344 19811 19811 W debuggerd: type=1400 audit(0.0:168): avc: denied { search } for uid=0 name="org.mozilla.klar" dev="dm-1" ino=3706 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-25 15:34:53.354 19811 19811 W debuggerd: type=1400 audit(0.0:169): avc: denied { search } for uid=0 name="org.mozilla.klar" dev="dm-1" ino=3706 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-25 15:34:53.419  1501  2301 I WindowManager: WIN DEATH: Window{6aafecd u0 SurfaceView - org.mozilla.klar/org.mozilla.focus.activity.MainActivity}
05-25 15:34:53.420  1501  2301 I WindowManager: Destroying surface Surface(name=SurfaceView - org.mozilla.klar/org.mozilla.focus.activity.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2069 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:897 com.android.server.wm.WindowState.removeLocked:1464 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2552 com.android.server.wm.WindowManagerService.removeWindowLocked:2510 com.android.server.wm.WindowState$DeathRecipient.binderDied:1808 android.os.BinderProxy.sendDeathNotice:688 <bottom of call stack> 
05-25 15:34:53.420  1501  1523 D GraphicsStats: Buffer count: 5
05-25 15:34:53.420  1501  1705 I ActivityManager: Process org.mozilla.klar (pid 19432) has died
05-25 15:34:53.420  1501  1705 D ActivityManager: cleanUpApplicationRecord -- 19432
05-25 15:34:53.422 19811 19811 E DEBUG   : unexpected waitpid response: n=19458, status=00000b00
05-25 15:34:53.422 19811 19811 E         : debuggerd: timed out waiting for signal
05-25 15:34:53.424  1501  3593 I WindowManager: WIN DEATH: Window{8a91f28 u0 org.mozilla.klar/org.mozilla.focus.activity.MainActivity}
05-25 15:34:53.424  1501  1705 W ActivityManager: Scheduling restart of crashed service org.mozilla.klar/org.mozilla.gecko.gfx.SurfaceAllocatorService in 1000ms
05-25 15:34:53.424  1501  1705 W ActivityManager: Scheduling restart of crashed service org.mozilla.klar/org.mozilla.focus.session.SessionNotificationService in 10999ms
05-25 15:34:53.425  1501  3593 I WindowManager: Destroying surface Surface(name=org.mozilla.klar/org.mozilla.focus.activity.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2069 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:897 com.android.server.wm.WindowState.removeLocked:1464 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2552 com.android.server.wm.WindowManagerService.removeWindowLocked:2510 com.android.server.wm.WindowState$DeathRecipient.binderDied:1808 android.os.BinderProxy.sendDeathNotice:688 <bottom of call stack> 
05-25 15:34:53.425  1501  1705 W ActivityManager: Force removing ActivityRecord{fcb3ce0 u0 org.mozilla.klar/org.mozilla.focus.activity.MainActivity t38}: app died, no saved state
05-25 15:34:53.426 19465 19465 I GeckoServiceChildProcess: Service has been unbound. Stopping.

**Comment by cpeterso** [comment]
I filed [GeckoView bug 1465626](https://bugzilla.mozilla.org/show_bug.cgi?id=1465626) to track this crash.

**Comment by npark-mozilla** [comment]
This is no longer reproducible in Klar release build. closing
