### ISSUE TITLE
Language leakage. 

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/focus-android#2636]
Firefox Focus leaks the system languages. By default it uses the system languages to ask the websites for a local version. It's ok, afterall it's your "default". But if I change the default language to Spanish for example, it continues to leak my system languages below.
![screenshot_20180522-110451_firefox klar](https://user-images.githubusercontent.com/32398857/40367991-3519f2f2-5dca-11e8-8523-3e67432116a3.jpg)

**Comment by pocmo** [comment]
What's your concern here? Do you consider the default languages to be sensitive information?

You could argue that this is a feature: You want web content in a language you can understand. And this may be multiple languages; not only the language you wanted the Focus interface in.

**Comment by Lululalu** [comment]
It's not sensitive, but it can be used to fingerprint I think. And Firefox Focus is a private browser.

**Comment by brampitoyo** [comment]
I don’t think this needs another privacy/security setting menu item.

Meaning: if we choose not to broadcast the system language information along with the user selected language to the website, it should be a policy that applies to the whole product. There should not be a way to turn it off or on, I think.

In this scenario, we assume: if the user modifies the language away from “System default”, then they would like the UI – and webpages – to be displayed in the language of their choice. And maybe there’s an argument to be made about not giving away what the “System default” value is.

Is not broadcasting the right policy? It feels like it is, but I don’t have a strong opinion about it, and will defer to @pocmo. Furthermore, it may be worth it to ask the Security Engineering team for advise.

**Comment by pocmo** [comment]
Related:
* Explanation of the Accept-Language header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
* A related issue in the Tor browser tracker: https://trac.torproject.org/projects/tor/ticket/14351

The Tor browser seems to always only send this hard-coded very common value:

```Accept-Language:    en-us,en;q=0.5```

We may want to wrap this into fingerprinting protection (#1344) and not track it as a separate thing/setting.

As far as I know there's not much we can do in the WebView version; but with GeckoView we may have more control over this.
