### ISSUE TITLE
Enable remote debugging

### ISSUE THREAD

**Issue by digitarald** [mozilla-mobile/focus-android#2647]
### Why/User Benefit/User Problem

Klar has to have a way to enable remote debugging, both for content debugging and performance profiling.

### What / Requirements

Add an option to enable remote debugging for Klar, possibly via commandline.

### Acceptance Criteria (how do I know when I’m done?)

Firefox can remote debug Klar via USB.

Note: [Bug 1462019](https://bugzilla.mozilla.org/show_bug.cgi?id=1462019) possibly impacts this for some Android O.

**Comment by bbinto** [comment]
@digitarald - Harald, are you talking about GeckoView?

**Comment by digitarald** [comment]
> @digitarald - Harald, are you talking about GeckoView?

This applies to the GeckoView version of Klar, yes.

> We would need a setting to not have this enabled for all web content / users.

Yes, Fennec has this setting in the Advanced settings group. Meanwhile a launch intent that sets the flag could also help internal developers.

**Comment by digitarald** [comment]
Related: https://twitter.com/snorp/status/1010562965555367937

**Comment by digitarald** [comment]
During all hands, one idea as first step was to simply enable remote debugging by default on dev/nightly builds.

**Comment by ekager** [comment]
In theory, all GV builds are currently debug or nightly builds. Should we turn this on for all GV builds now and turn it off before release? Or we could add a setting to turn it on for all GV builds?

**Comment by pocmo** [comment]
@brampitoyo Are you okay with adding a setting?

Fennec has: Settings -> Advanced -> Developer tools -> Remote debugging via USB/Wi-Fi

Having this setting in all our versions (including release) will be helpful to debug web issues (for us, but also regular web developers).

> Should we turn this on for all GV builds now and turn it off before release?

We can do that. We should only make sure to file a separate release blocker issue to not ship that. :)

**Comment by ekager** [comment]
Reopening because GV team has informed me turning it on for all builds will slow start up. We should update to put it behind a setting.

**Comment by pocmo** [comment]
Oops. I thought you are on PTO today and wanted to merge it early. :)

**Comment by brampitoyo** [comment]
> Are you okay with adding a setting?
> Settings -> Advanced -> Developer tools -> Remote debugging via USB/Wi-Fi

Yes. Adding this section sounds good to me.

Our “Advanced” section in setting should be described as follows:

> **Advanced**
> Developer tools

In terms of placement, “Advanced” should be positioned above “Make default browser”.

Every section in Settings is supposed to have an icon. Unfortunately, we don’t currently have one for “Advanced”, but it’s okay for the time being. Just leave it blank.

**Comment by ekager** [comment]
Hey @brampitoyo , should this setting only be shown on GV builds?

**Comment by brampitoyo** [comment]
@ekager Yes, this setting should only be shown on GV builds.

**Comment by past** [comment]
I have enabled the "Remote debugging via USB/Wi-Fi" setting, but I can't seem to connect to the latest Focus Nightly, following the [process](https://perf-html.io/docs/#/./guide-remote-profiling) that works for Fennec.

This is what I'm getting in the Browser Console:
```
Connection status changed: connecting app-manager.js:144:5
Connection status changed: disconnected app-manager.js:144:5
Exception { name: "NS_BASE_STREAM_CLOSED", message: "Component returned failure code: 0x80470002 (NS_BASE_STREAM_CLOSED) [nsIInputStream.available]", result: 2152136706, filename: "resource://devtools/shared/base-loader.js -> resource://devtools/shared/security/socket.js", lineNumber: 329, columnNumber: 0, data: null, stack: "onInputStreamReady@resource://devtools/shared/base-loader.js -> resource://devtools/shared/security/socket.js:329:9\n", location: XPCWrappedNative_NoHelper } connection-manager.js:323:9
_clientConnect/< resource://devtools/shared/client/connection-manager.js:323:9
Operation failed: Connecting to Firefox Custom on Android (Moto G (5) Plus) webide.js:280:5
reportError chrome://webide/content/webide.js:280:5
busyUntil/< chrome://webide/content/webide.js:261:9
```

Any ideas?

**Comment by makotokato** [comment]
@past if target sdk of GV app is 26+, it is https://bugzilla.mozilla.org/show_bug.cgi?id=1462019 (when I got r+ for network part, then I send review to devtools part).

**Comment by past** [comment]
Oh, I hadn't thought of that! Is Focus Nightly built with target SDK 26+?

**Comment by makotokato** [comment]
Target SDK seems to be 27 according to https://github.com/mozilla-mobile/focus-android/issues/1573
