### ISSUE TITLE
Automated screenshots: No wordmark in about page 

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#265]
See:
https://people-mozilla.org/~npark/Focus_Screenshot/de-/images/phoneScreenshots/About_Page_1489618936635.html

**Comment by ahunt** [comment]
I can kindof reproduce when building:
klarWebkitDebug/klarWebkitBeta (I can't build klarWebkitRelease)

However I get a much smaller image box than in the screenshots (which might just be webview version dependent), so I've got no idea if that's even related. (We need to fix the klar issue regardless.)

@npark-mozilla Do you know what webview version the emulator/device is running? Based on the bug linked to below, I suspect this could be happening if you're on webview < 53?

For Klar, it's definitely the preexisting android resource bug ( https://code.google.com/p/android/issues/detail?id=211768 ):
03-16 16:07:50.224 21247-21317/org.mozilla.klar.debug E/AndroidProtocolHandler: Unable to open resource URL: file:///android_res/drawable/wordmark.png
                                                                                java.lang.ClassNotFoundException: Didn't find class "org.mozilla.klar.debug.R$drawable" on path: DexPathList[[zip file "/data/app/org.mozilla.klar.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/org.mozilla.klar.debug-1/lib/arm, /vendor/lib, /system/lib]]

**Comment by npark-mozilla** [comment]
Ah, I was about to raise this bug, yes on newer android image the missing image box is much smaller.  The screenshot was taken on Android 5.1 with the webview verson 39, as the newer simulators had stability issues with fastlane screengrab.

**Comment by ahunt** [comment]
I think my solution here (which should fix both Klar, and older webviews) will be one of:
- move the wordmark into assets: that works regardless of app ID (but that's unnecessary duplication)
- stuff the wordmark into a data:/ URI

(I've tried using android.resource:// URIs, but those don't seem to work in a webview - i.e. I'm gettin an ERR_UNKNOWN_URL_SCHEME with that.)

**Comment by pocmo** [comment]
@npark-mozilla Should be fixed on master now.

**Comment by ahunt** [comment]
Yeah, the latest screenshots have the wordmark, e.g.:
https://people-mozilla.org/~npark/Focus_Screenshot/de-/images/phoneScreenshots/dirindex.html
