### ISSUE TITLE
URI scheme filtering causes erroneous "open in app" dialog

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/focus-android#2651]
With a GV build, if you click a javascript: link, for example, you get the external app dialog. I don't think Focus needs to do this kind of filtering at all, and instead rely on things like onExternalResponse().

**Comment by pocmo** [comment]
May be related to #2413

**Comment by ekager** [comment]
Yes this and #2413 can be fixed by removing filtering for `IntentUtils.handleExternalUri` but this is how we handle external links like `market://` URLs (see #2258).

**Comment by ekager** [comment]
We could also extend our permitted protocols. https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/utils/UrlUtils.java#L108

Was it a conscious decision to not allow `javascript

**Comment by pocmo** [comment]
> Was it a conscious decision to not allow javascript @pocmo ?

No, it was more the opposite: Explicitly only allow what we want to allow. We do not want to open javascript: links coming from other apps but if they are clicked in content then it makes a lot of sense to allow them. I actually do not know if this works in WebView or if it never asks us about javascript links?

**Comment by ekager** [comment]
The same happens in WebView. We can remove the Klar+GeckoView specific label
