### ISSUE TITLE
[l10n][New locale] Pai pai

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#2654]
Just added Pai pai to Focus Android on Pontoon: https://pontoon.mozilla.org/pai/focus-for-android/
They'll be needing screenshots for now, before being added to the list of shipping locales.
Note: I'm also asking the community how "Pai pai" is said locally, since I assume you'll need to know that for that locale.
Thanks!
(CC @pocmo)

**Comment by pocmo** [comment]
> I'm also asking the community how "Pai pai" is said locally, since I assume you'll need to know that for that locale.

Yep. Thank you!

**Comment by Delphine** [comment]
Name would be: paa ipai
