### ISSUE TITLE
Block images for security and data savings

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/focus-android#2655]
Can you please Implement an option to disable images for better security/privacy and to save mobile data?

**Comment by pocmo** [comment]
Probably a duplicate: #2001, #836, #188

Background: We added this feature in 1.0 and then decided to not ship it because of some usability issues.

**Comment by bbinto** [comment]
@soaringowl2145 could you please fill out our feature request template:

### Why/User Benefit/User Problem

### What / Requirements

### Acceptance Criteria (how do I know when I’m done?)
