### ISSUE TITLE
Telemetry error at Gradle Build

### ISSUE THREAD

**Issue by gupta1anubhav** [mozilla-mobile/focus-android#2657]
Gradle error at building FocusWebUnviersalDebug or any other build variant.

![screenshot from 2018-05-23 15-36-28](https://user-images.githubusercontent.com/31107831/40477324-cd0fc060-5f63-11e8-8b99-dc27ccf51838.png)

**Comment by pocmo** [comment]
See https://github.com/mozilla-mobile/android-components/issues/208

**Comment by gupta1anubhav** [comment]
Got it

**Comment by pocmo** [comment]
This is fixed in master now.
