### ISSUE TITLE
Create "public" Nightly channel for Focus/Klar with GeckoView

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2659]
Setup:

* [x] Create a new Nightly track on Google Play
* [x] Create a public Google Group for Nightly testers
* [x] Link the track to the Google Group
* [x] Setup the Nightly build pipeline to upload GeckoView builds to the new track

Cleanup:

* [ ] Close down the internal Nightly track.

**Comment by setuidroot** [comment]
Hi, I'd like to help test the latest Firefox Focus Nightlies for you guys... I always stay current with the latest APK RC posted on github releases.  I don't normally have the time (or server power) to build nightlies from dev branch.

I personally don't use Google Play services or Play Store, I use F-Droid and third party FOSS app stores.  I keep nearly everything FOSS on all of my devices.

Would it be possible/not inconvenient for you to upload nightlies here to github?  Or if you gave me (the community) a link where I (we) could download them as prebuilt APKs; I would happily test the builds for you (all anonymous analytics included and any issues I find I'll post here.)  I use Firefox Focus and Firefox Klar (I like having two for simultaneous browsing) on all 4 of my devices daily; I have real devices with SDKs: 21, 23, 25 and 27.

Just trying to help with development growth here, this is not meant to pester you guys for Nightlies... although I want them lol.  

Thanks to everyone (developers, support team, etc) who keep this great project alive!

**Comment by bbinto** [comment]
@pocmo please close once all items in your checklist are done, I assume we are close to done, but moving this to 6.2

**Comment by pocmo** [comment]
Done! I'll file a new issue for the "cleanup" as it's not that important.
