### ISSUE TITLE
[l10n][New Locale] Afrikaans (af)

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#2660]
Just added Afrikaans to Pontoon: https://pontoon.mozilla.org/af/focus-for-android/
They'll be needing screenshots for now, before being added to the list of shipping locales.
Thanks!
(CC @pocmo)

**Comment by pocmo** [comment]
Added "af" to list of screenshot locales in 045d0d54f98ea3635062eb0e0f769c23d32b3f49
