### ISSUE TITLE
Breakdown for feature issue: Undo erase while snackbar is showing #467

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2662]
Breakdown as discussed [here](https://github.com/mozilla-mobile/focus-android/issues/467#issuecomment-391361447)

Scope - restore as much as possible (multiple tabs, history of each session, etc).

- [ ] Add "undo" action to snackbar
- [ ] Implement undo based on scope.
- [ ] UX / animation for "reverse" action detailed [here](https://github.com/mozilla-mobile/focus-android/issues/467#issuecomment-381473959)
- [ ] Add telemetry probe for undo action

**Comment by bbinto** [comment]
@boek - will this be done today otherwise, we need to move to 6.1

**Comment by boek** [comment]
@bbinto It'll be done today 🙌
