### ISSUE TITLE
Klar Geckoview crashes while nimbledroid run after pm clear <pkg> and load website

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2663]
STR:
Nimbledroid script does the following:

    visit www.google.com
    visit website (i.e. cnn.com, buzzfeed.com)
    do 'adb shell pm clear org.mozilla.klar' (closes the app and removes the process from memory)
    visit www.google.com again
    visit next website in the list
    Expected:
    Website opens normally
    Actual:
    Klar crashes

This doesn't happen with Focus, and we suspect it may have something to do with either geckoview bug, or how we clear the memory.

[crashlog.txt](https://github.com/mozilla-mobile/focus-android/files/2040634/crashlog.txt)

**Comment by npark-mozilla** [comment]
This issue might be also related to #2635

**Comment by cpeterso** [comment]
I filed [GeckoView bug 1465627](https://bugzilla.mozilla.org/show_bug.cgi?id=1465627) to track this crash.

**Comment by npark-mozilla** [comment]
This is no longer reproducible on 5.31.18 GV
