### ISSUE TITLE
[l10n] Some locales missing from language list

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#2666]
Seems like there are at least two locales missing from the builds (both release and Nightly): "zam" and tsz" although they are listed in [locales.py](https://github.com/mozilla-mobile/focus-android/blob/master/tools/l10n/locales.py).
Maybe there are more, but I was only able to identify these two for now. 

Since they are both "lesser" known languages that Android doesn't offer, I'm guessing this may have something to do (it seems like others made it to the language list though).

(CC @pocmo @boek)

**Comment by Delphine** [comment]
Update: I was wrong about "zam"... I got confused about the name of the locale and was looking up "zapoteco" instead of "DíɁztè"

**Comment by boek** [comment]
I think this is blocked by #2706
