### ISSUE TITLE
Check default browser sumo link

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#267]
We're hardcoding the following (which is the same as what Firefox on Android does):
https://support.mozilla.org/kb/make-firefox-default-browser-android?utm_source=inproduct&amp;utm_medium=settings&amp;utm_campaign=mobileandroid

Should we be constructing a URL using:
"https://support.mozilla.org/1/mobile/" + appVersion + "/" + osTarget + "/" + langTag + "/" + escapedTopic?

**Comment by ahunt** [comment]
Also make sure the generated sumo links work, when I'm testing in German I get English for the default browser page, and also for the telemetry->learn more link: we're inserting the right locale, but something is wrong:
https://support.mozilla.org/1/mobile/1.0/Android/de-DE/usage-data

**Comment by ahunt** [comment]
The same happens on Firefox release, so it's not a focus specific bug : /

**Comment by pocmo** [comment]
Also see #149 about a Focus specific URL.

**Comment by pocmo** [comment]
I've added the URLs for the SUMO pages in #149. Unfortunately SUMO doesn't support automatic redirects currently, so we have to ship a fixed list of URLs.
