### ISSUE TITLE
Redesign URL bar – active (initial state only)

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2677]
Old:

<img src="https://user-images.githubusercontent.com/51007/40751845-17344848-64c1-11e8-9fe8-2ad76a8c3486.png" width="360">

New:

<img src="https://user-images.githubusercontent.com/51007/40751850-1f438102-64c1-11e8-957c-3d2cce91e082.png" width="360">

Spec:

<img src="https://user-images.githubusercontent.com/51007/41008740-c039b82e-6980-11e8-9399-e0ba2771752b.png" width="360">

**Comment by waah42** [comment]
Hi, I would like to do it.

**Comment by ninad458** [comment]
Hi, I would like to work on some of the beginner issues. Can I start with this one? Or is anyone already on it? @waah42

**Comment by ekager** [comment]
Looks like #2713 is open and almost complete to close this issue.

**Comment by colintheshots** [comment]
This appears to be completed in the current Nightly. Please close if so.
