### ISSUE TITLE
Redesign URL bar – active (typing)

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2678]
Old:
<img src="https://user-images.githubusercontent.com/51007/40752112-4d942f92-64c2-11e8-8412-99a59df50f1f.png" width="360">

New:

<img src="https://user-images.githubusercontent.com/51007/40752207-b2849dd8-64c2-11e8-9279-3ebcce6c20f2.png" width="360">

Spec:

<img src="https://user-images.githubusercontent.com/51007/40752177-8709b666-64c2-11e8-81d9-6a2139bf6044.png" width="360">

**Comment by jayeshsolanki93** [comment]
Hi @brampitoyo 
The color spec (ink-80) for the background gradient on the url input toolbar seemed incorrect. I used colors which closely matched the screenshot. This is how it looks now:
![webp net-compress-image](https://user-images.githubusercontent.com/6861614/41040344-c59b3e30-69b9-11e8-9e31-5eddf4c75879.jpg)

**Comment by brampitoyo** [comment]
Hi @jayeshsolanki93, it seems that I’ve neglected to give you the gradient colour value for the typing state. See https://github.com/mozilla-mobile/focus-android/issues/2679#issuecomment-396107105 for these.

You’ll notice that it’s the same value we use for the loading state.

**Comment by brampitoyo** [comment]
This looks great.
