### ISSUE TITLE
Redesign URL bar – loading

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2679]
Old:

<img src="https://user-images.githubusercontent.com/51007/40752266-e02e38f2-64c2-11e8-8ec3-d14e4718e707.png" width="360">

New:

<img src="https://user-images.githubusercontent.com/51007/40752545-1eab8926-64c4-11e8-9891-0e633bc2dabb.png" width="360">

Spec:

<img src="https://user-images.githubusercontent.com/51007/40752270-e5f974d6-64c2-11e8-8b2c-5a8984f090b0.png" width="360">

**Comment by pocmo** [comment]
@brampitoyo Like #2680: Can you provide us with the "combined" color codes?

Currently we use those colors:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/res/values/colors.xml#L19-L21

**Comment by brampitoyo** [comment]
* colorInactiveGradientStart: `#421c41`
* colorInactiveGradientCenter: `#3e1c4d`
* colorInactiveGradientEnd: `#271c44`

**Comment by cgomezmendez** [comment]
I would like to take this issue.

**Comment by cgomezmendez** [comment]
Got the PR for the change in #2735

**Comment by suhailsinghbains** [comment]
I wanted to solve this bug, can someone mentor me on this?

**Comment by brampitoyo** [comment]
@suhailsinghbains I think this bug has been solved already. Feel free to look at other bugs that need fixing. Thanks!
