### ISSUE TITLE
Redesign URL bar – site loaded, Tracking Protection ON

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2680]
Old:

<img src="https://user-images.githubusercontent.com/51007/40752956-f1e11058-64c5-11e8-9bea-8bee35e5aca8.png" width="360">

New:

<img src="https://user-images.githubusercontent.com/51007/40753058-68907e78-64c6-11e8-9f8d-79f0f45025f7.png" width="360">

Spec:

<img src="https://user-images.githubusercontent.com/51007/40752957-f360fb82-64c5-11e8-9088-8386ba6868d7.png" width="360">

**Comment by pocmo** [comment]
@brampitoyo Can you provide us with the "combined" color codes? Drawing multiple layers / overdraw is very expensive and seems to be unnecessary here.

Those are the colors we currently use:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/res/values/colors.xml#L12-L14

**Comment by SrChip15** [comment]
@brampitoyo hi, I see that the browser toolbar already has a gradient set as background already.

@ekager any idea on how to achieve this?

**Comment by SrChip15** [comment]
Refer PR #2727

**Comment by ekager** [comment]
Closed by #2924
