### ISSUE TITLE
 Redesign URL bar – site loaded, Tracking Protection OFF

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2681]
Old:

<img src="https://user-images.githubusercontent.com/51007/40753089-8f7de5b6-64c6-11e8-9b5f-cc82f5b25f3f.png" width="360">

New:

<img src="https://user-images.githubusercontent.com/51007/40753108-a71c28ea-64c6-11e8-94b9-b0d667e21a1b.png" width="360">

Spec:

<img src="https://user-images.githubusercontent.com/51007/41273285-f6b8aaf4-6e6c-11e8-8559-7ce4710eef44.png" width="360">

**Comment by SrChip15** [comment]
@brampitoyo since the for spec you have just pasted the browser toolbar, I went with the first color in the gradient - `colorGradientStart`.

**Comment by SrChip15** [comment]
@brampitoyo As for the browser toolbar, could you tell me the exact color?

**Comment by brampitoyo** [comment]
@SrChip15 Sorry. This is totally my mistake.

Instead of `colorGradientStart`, we should use `ink-90`.

The `magenta-70` value is for the background color of the “Tracking Protection OFF” status badge.

**Comment by SrChip15** [comment]
@brampitoyo the gradient has two other colors (#ff433446, #ff3b3445). are we still using a gradient or just a single color? They are actually part of a transition.

**Comment by brampitoyo** [comment]
@SrChip15 The gradient value is used for the URL bar when it’s in the “Loading” and “Typing” states. This is a different state, so we just use `ink-90` by itself.

**Comment by brampitoyo** [comment]
Hi @SrChip15. Sorry once again. It seems that I’ve submitted the wrong value the first time around.

The correct value for this state should be `ink-80`, not `ink-90`.

Hope that’s a simple change for you. Sorry for the inconvenience!

**Comment by SrChip15** [comment]
@brampitoyo sorry, just got back to this.

Ok, I think, I have found the right state and refreshed the appropriate colors to the new spec. So, now it looks like the below pasted image. Please let me know if this is ok as soon as you see this. I'll create a PR for this right away.

<img src="https://user-images.githubusercontent.com/12288245/41557486-ae86f350-72f2-11e8-9ad6-3693cd7d2254.png" width="250" height="500">

**Comment by ekager** [comment]
Closed by  #2924
