### ISSUE TITLE
Redesign FAB – Erase

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2682]
Old:

<img src="https://user-images.githubusercontent.com/51007/40753253-4c15998a-64c7-11e8-9353-7a36e7edb0bf.png" width="72">

New:

<img src="https://user-images.githubusercontent.com/51007/40753243-3ef8a698-64c7-11e8-8edd-fa0c7a3223eb.png" width="72">

Asset: [Delete.svg](https://design.firefox.com/icons/viewer/#delete)

**Comment by vince-nyanga** [comment]
Would like to work on it

**Comment by ekager** [comment]
Hi @vince-nyanga thank you so much for your contribution! It looks like the svg is slightly off center which looks like our fault. I got new vector path data that you can swap out if you're still interested in making a PR. Sorry about that! Thanks again for your help!

`<path android:fillColor="#FFFFFF" android:pathData="M6,12a0.5,0.5 0,0 0,0.5 -0.5v-6a0.5,0.5 0,0 0,-1 0v6a0.5,0.5 0,0 0,0.5 0.5zM8,12a0.5,0.5 0,0 0,0.5 -0.5v-6a0.5,0.5 0,0 0,-1 0v6a0.5,0.5 0,0 0,0.5 0.5zM10,12a0.5,0.5 0,0 0,0.5 -0.5v-6a0.5,0.5 0,0 0,-1 0v6a0.5,0.5 0,0 0,0.5 0.5z"/>`

`<path android:fillColor="#FFFFFF" android:pathData="M13.5,2h-3.05a2.5,2.5 0,0 0,-4.9 0L2.5,2a1,1 0,0 0,0 2v9a3,3 0,0 0,3 3h5a3,3 0,0 0,3 -3L13.5,4a1,1 0,0 0,0 -2zM8,1a1.49,1.49 0,0 1,1.391 1L6.609,2A1.49,1.49 0,0 1,8 1zM11.5,13a1,1 0,0 1,-1 1h-5a1,1 0,0 1,-1 -1L4.5,4h7z"/> `

**Comment by vince-nyanga** [comment]
Hi @ekager Sorry for taking long. Let me add the new one.
