### ISSUE TITLE
 Redesign FAB – Multitasking (number of tabs)

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2683]
Old:

<img src="https://user-images.githubusercontent.com/51007/40753379-ef4a4060-64c7-11e8-9b01-487e40003b3f.png" width="72">

New:

<img src="https://user-images.githubusercontent.com/51007/40753788-029f30a6-64ca-11e8-85b5-db5ea41a36da.png" width="72">

Spec:

<img src="https://user-images.githubusercontent.com/51007/40753814-19a42e00-64ca-11e8-8d1e-5d19ac015b9e.png" width="180">

Asset: [Tab.svg](https://cl.ly/253L0q2k2o47/Tab.svg)

**Comment by Nistenf** [comment]
Hi, can I work on this?

**Comment by ekager** [comment]
Hi @Nistenf ! Thanks for your help! If you take out the `strokeAlpha` and `strokeColor` attributes and change `fillColor` to `#FFFFFF` that should have it match the mock.

**Comment by brampitoyo** [comment]
Hi @Nistenf. Good eye!

For icons inside the main menu, we want their default colour value to be `#f9f9fa` a80. But for icons prominently displayed in the Floating Action Button, we want that to be coloured `#ffffff`.

I have overlooked that colour value in my original SVG asset. Thanks for checking in!

**Comment by ekager** [comment]
Hi @Nistenf just tried it out myself because it did look a little slim in your screenshot, I think if we add back in the original vector attributes and change the `strokeAlpha` to `1` and the `strokeColor` to `#FFFFFF` that should fix the width. Sorry about that! I guess those were needed :)
