### ISSUE TITLE
Redesign menu & dialog – Multitasking (list of tabs)

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2684]
Old:

<img src="https://user-images.githubusercontent.com/51007/40754252-6f135134-64cc-11e8-8369-9f9f6a8e700b.png" width="360">

New:

<img src="https://user-images.githubusercontent.com/51007/40754254-71b1229a-64cc-11e8-9200-ec49e0a4822a.png" width="360">

Spec:

<img src="https://user-images.githubusercontent.com/51007/40754197-246f16cc-64cc-11e8-921b-c15f6c0509c1.png" width="312">

Just a note that the icon fill for the link icons follows our default value: `#f9f9fa` a80.

Whereas the icon fill for the erase icon remains `#ffffff` a100.

**Comment by KrzysztofBarszcz** [comment]
Hi,
I would like to work on this issue

**Comment by pocmo** [comment]
@brampitoyo Can you give us the "combined color codes" so that we do not need to have "overdraw" by using transparency?

**Comment by brampitoyo** [comment]
Yes. The background for the highlighted area is `#353852`.

I’ve specified the same colour value for highlighted areas on:

* https://github.com/mozilla-mobile/focus-android/pull/2719#pullrequestreview-127421157
* https://github.com/mozilla-mobile/focus-android/issues/2685#issuecomment-396110190

So maybe we can have this colour be a variable?

**Comment by KrzysztofBarszcz** [comment]
I think I finished this issue. How to send the code for review?

**Comment by KrzysztofBarszcz** [comment]
#2842
