### ISSUE TITLE
 Redesign menu & dialog – Main menu

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2685]
Old:

<img src="https://user-images.githubusercontent.com/51007/40755102-f20bd6b6-64d0-11e8-9177-f9fda2cc27ad.png" width="360">

New:

<img src="https://user-images.githubusercontent.com/51007/40755104-f4d9b930-64d0-11e8-9af1-d46643a135ae.png" width="360">

Spec:

<img src="https://user-images.githubusercontent.com/51007/40755195-6cf72646-64d1-11e8-9646-21fc87c3bc4f.png" width="300">

Assets:

* [Number of trackers blocked](https://cl.ly/0R3e3N1N2G0j/trackers-blocked.svg)
* [Info](https://design.firefox.com/icons/viewer/#info)
* [Share…](https://design.firefox.com/icons/viewer/#share%20macos)
* [Home screen](https://design.firefox.com/icons/viewer/#home)
* [Open in…](https://design.firefox.com/icons/viewer/#open%20in%20new)
* [Request desktop site](https://design.firefox.com/icons/viewer/#desktop)
* [Settings](https://design.firefox.com/icons/viewer/#preferences)

Just a note that the icon fill follows our default value: `#f9f9fa` a80.

**Comment by pocmo** [comment]
@brampitoyo I like all the new designs a lot. I'm only confused about the icons in the menu here. What's the rationale behind that? It looks so different compared to other app menus.

**Comment by brampitoyo** [comment]
Hi @pocmo.

Firstly, the icons are there to unify our menu design across platforms – desktop and mobile.

But why don’t Fennec have menu icons? The team hasn’t got round to it yet, but it will happen in the future. We’d be the first to launch with this design.

<img src="https://user-images.githubusercontent.com/51007/41006418-899b592c-6975-11e8-869f-ecec1fd08285.png" width="360">

Secondly, they’re there to help users parse the text quicker, so they can access the menu item even faster than before. Note: the icons are just there as visual aids. The text is still the most important element.

What do you think?

**Comment by SrChip15** [comment]
I would like to work on this issue

**Comment by SrChip15** [comment]
Hi @brampitoyo,

Where would I find ink-80 and grey-10 colors?

**Comment by brampitoyo** [comment]
@SrChip15 All of our colour values are available on the [Photon Design System](https://design.firefox.com/photon/visuals/color.html). As for the actual location of the colour variables in the code, I’m not so sure. @ekager may be able to help you here.

**Comment by brampitoyo** [comment]
@SrChip15 The background colour for the highlighted menu area is `grey-10` a10 against a `grey-80` background. The straight-up colour value is `#353852`).

**Comment by SrChip15** [comment]
@brampitoyo check this PR https://github.com/mozilla-mobile/focus-android/pull/2721. Hope that is per new spec.

**Comment by abhishekd08** [comment]
Can I work on this ?
