### ISSUE TITLE
Redesign menu & dialog – Context menu

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2686]
Old:

<img src="https://user-images.githubusercontent.com/51007/40757106-0d6309ca-64db-11e8-99da-07aef33c905f.png" width="360">

New:

<img src="https://user-images.githubusercontent.com/51007/40757112-121fc84a-64db-11e8-8a7f-827d13bd18ac.png" width="360">

Specs:

<img src="https://user-images.githubusercontent.com/51007/40757315-fdae31f2-64db-11e8-8205-29a94d4fff73.png" width="360">

**Comment by moyheen** [comment]
I would like to work on this issue.

**Comment by ekager** [comment]
Great, thanks @moyheen ! Let me know if you need any help and I'll review your PR when it's up!
