### ISSUE TITLE
Redesign page – Settings

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2687]
Old:

<img src="https://user-images.githubusercontent.com/51007/40759262-66850cc4-64e5-11e8-8fc8-65241e2bcc8d.png" width="360">

New:

<img src="https://user-images.githubusercontent.com/51007/40759285-91154198-64e5-11e8-917a-b7929170e98f.png" width="360">

Specs:

<img src="https://user-images.githubusercontent.com/51007/40759266-6d83ef86-64e5-11e8-812c-c406354d7cec.png" width="360">

Assets:

* [Language](https://cl.ly/1u413W0Y270J/Language.svg) (lacking our own, we’re using Material Icons, rounded style).
* [Privacy and Security](https://cl.ly/3P2a0V0J290X/Privacy%20Security.svg) should be the lock icon that we already show in the UI. @ekager, do we have that asset already stored somewhere? If not, the SVG is linked.
* [Search](https://cl.ly/2o2l3Q2u1Q1i/Search.svg) should also be in our repository already, but I’ve provided the SVG link, should it be required.
* [Mozilla](https://cl.ly/2N092t0q2l10/Mozilla.svg)

Just a note that the icon fill follows our default value: `#f9f9fa` a80.

**Comment by Guisanpea** [comment]
I have thought on solving this issue, I'm new around here and I don't know if I should modify primary color and secondary color so it is more modular or just solve it for this particular screen

**Comment by ekager** [comment]
Hi @Guisanpea thanks for your help! You could try to add the new primary, secondary, and accent colors to `SettingsTheme` in `styles.xml`.

**Comment by ekager** [comment]
Hey @brampitoyo this issue also includes the new icons? Could you link the language and Mozilla svgs?

**Comment by SrChip15** [comment]
I would also like to work on this. Although I am not sure if this issue is taken?

**Comment by brampitoyo** [comment]
@ekager Sorry for forgetting to include the new icons!

Here they are:

* [Language](https://cl.ly/1u413W0Y270J/Language.svg) (lacking our own, we’re using Material Icons, rounded style).
* [Privacy and Security](https://cl.ly/3P2a0V0J290X/Privacy%20Security.svg) should be the lock icon that we already show in the UI. @ekager, do we have that asset already stored somewhere? If not, the SVG is linked.
* [Search](https://cl.ly/2o2l3Q2u1Q1i/Search.svg) should also be in our repository already, but I’ve provided the SVG link, should it be required.
* [Mozilla](https://cl.ly/2N092t0q2l10/Mozilla.svg)

Just a note that the icon fill follows our default value: `f9f9fa` a80.

**Comment by Hackertronix** [comment]
Hey @bbinto @ekager , 

I wanna take this issue up but I am not sure what the protocol here is, @Guisanpea has expressed interest in fixing this one. Are issued open for anyone to pick up and PRs are accepted based on who sends them first? 😅 

Thanks!

**Comment by Hackertronix** [comment]
Looks like #2719 already fixed this 😅 ...

**Comment by ninad458** [comment]
@Hackertronix @brampitoyo So why is this issue still open? I don't understand. I'm new here.

**Comment by ekager** [comment]
Hi @ninad458 , we weren't able to merge the UX redesign issues until this week because of when we want them released, so I'm reviewing and merging them now. There is an open PR #2719 for this issue, but it may need changes which I will give the original contributor a chance to complete. If they do not respond, I'll comment here that this issue needs a new PR. In general, make sure to check the open PRs first before working on an issue. Thanks!
