### ISSUE TITLE
Horizontal scroll page issue

### ISSUE THREAD

**Issue by gdevitis** [mozilla-mobile/focus-android#2688]
Horizontal scroll does not work on some web pages.
For example, accessing this page https://www.vascorossi.net/it/home/1-0.html with Firefox Focus makes it impossible to move horizontally or pinch and zoom.
On Google Chrome instead all these features work correctly.

**Comment by bbinto** [comment]
@npark-mozilla try to reproduce

**Comment by npark-mozilla** [comment]
I was able to repro this issue.  In Focus, unlike Chrome, it opens the page in zoomed in state, and does not allow the page to be zoomed out or scroll horizontally. Chrome opens the page in fully zoomed out state.

But in Focus, if you select 'Request Desktop Site', then it behaves the same as Chrome. (you can zoom out and scroll horizontally).  I wonder whether it's the site that's sending incorrect mobile page, or we have an issue with handling mobile page.
