### ISSUE TITLE
typing market:// URL initially shows connection error

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#269]
STR:
Enter URL of market://details?id=org.mozilla.firefox&referrer=utm_source%3Dmozilla%26utm_medium%3DReferral%26utm_campaign%3Dmozilla-org

It shows the connection error page, instead of the pop that notifies that it will open an external app.

Press Try Again, then it shows the notification popup dialog.

**Comment by npark-mozilla** [comment]
It gives "The address wasn't understood" error" initially.

**Comment by pocmo** [comment]
Ah, thanks for filling. I noticed this too and forgot.

It might not be super critical, so I just flag it with "needs triage".

**Comment by npark-mozilla** [comment]
@pocmo actually, if you can fix this, that would be super awesome, since i have to restart the test many times because for some reason after a while, the uiautomator can't tap 'Try again' properly.  It will really speed up the l10n test time.
