### ISSUE TITLE
In Focus webview, on API 24 and below, clicking download link will not pop up the download dialog

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#2696]
Found this during the UI Test fix.

### STR:
Expand the attached zip file, and start a webserver to host the html.
(on mac, you can do `python -m SimpleHTTPServer 8000` inside the expanded folder
Go to the URL on the Nexus API 23 simulator (on Nexus 5) 
Click the firefox icon

### Expected behavior
Download dialog will open

### Actual behavior
Nothing happens
(On newer devices, this does not happen)
### Device information
API 23 simulator (i.e. ones without webview updates)
Older devices with system updates will not have this issue
Geckoview does not have this issue
[webserver.zip](https://github.com/mozilla-mobile/focus-android/files/2070850/webserver.zip)

If this isn't resolved, I'll enabled the download test and imagedownload test for > API 26 only.

**Comment by npark-mozilla** [comment]
If there's something wrong with the HTML, please let me know, I know that this test has been working on API 23 at least a month ago or so.

**Comment by npark-mozilla** [comment]
This also happens on device (Nexus 5) on Google Firebase, which does not have its OS update installed.

**Comment by bbinto** [comment]
Let's figure out what causes the issue and the # of current users affected.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest RC 93.1.1 build using a Xiaomi mi4i (Android 5.0.2).
