### ISSUE TITLE
Lower minSdkLevel

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#27]
Currently we build the app for Android 7.0+. Let's investigate how far we can go down with adding overhead by implementing system features ourselves. This will primarily be driven by the feature set we require from WebView.

**Comment by ahunt** [comment]
The main WebView feature we need is intercepting web requests, which seems to be API 11+:
https://developer.android.com/reference/android/webkit/WebViewClient.html#shouldInterceptRequest(android.webkit.WebView,%20java.lang.String)

I haven't actually tested on older devices, so I've got no idea if support gets worse / if other weird bugs happen.

**Comment by pocmo** [comment]
It seems I looked at targetSdkVersion when opening the issue. Our minSdkVersion is actually 21 which is Android 5.0 and it runs on my 5.1 test device without issues. With that we already support ~65% [1]. Supporting 4.4 would give us additional 22% but not having to support it might be more favorable.

[1] https://developer.android.com/about/dashboards/index.html
