### ISSUE TITLE
L10N: missing placeholders in tsz, ixl

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2706]
The string import is currently failing with an error:

```
Error: * [values-tsz/strings.xml] missing placeholder in translation, key: about_content
Error: * [values-ixl/strings.xml] missing placeholder in translation, key: preference_autocomplete_preinstalled_summary
Error: * [values-ixl/strings.xml] missing placeholder in translation, key: preference_about
```

**Comment by Delphine** [comment]
I've pinged localizers because out of the three, I'm only able to correct the last one. I'll update here once it gets done

**Comment by boek** [comment]
@Delphine 

```
Warning: * [values-pl/strings.xml] number of placeholders not matching, key: firstrun_shortcut_text
Warning: * [values-tsz/strings.xml] number of placeholders not matching, key: about_content
Error: * [values-tsz/strings.xml] missing placeholder in translation, key: about_content
Warning: * [values-tr/strings.xml] number of placeholders not matching, key: your_rights_content5
Warning: * [values-eo/strings.xml] number of placeholders not matching, key: firstrun_shortcut_text
```

Getting these errors now.

**Comment by Delphine** [comment]
Ok I've updated the locales that I could, but the Error remains until the "tsz" localizer updates his strings (probably by tomorrow).
All the other locales should be fixed now.

**Comment by Delphine** [comment]
For the record, I only realized about this later: https://github.com/mozilla-mobile/focus-android/issues/1186
So I got back to localizers about the warnings and they were able to deal however they wanted with them - and all is good on l10n front ;)

**Comment by boek** [comment]
Going to close this as there is no longer any errors in the import. Thanks Delphine!
