### ISSUE TITLE
url update callback called each time `onProgressChanged` is called

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2709]
The `WebChromeClient.onProgressChanged` method gets called frequently during page load, which calls `onURLChanged` and its session observers an unnecessary amount of times for the same URL.

This is a likely negligible performance hit at the moment but I'm concerned that future code additions may 1) increase the performance hit or 2) be non-idempotent and cause unexpected behavior. I think we should short-circuit URL updates either at the ChromeClient if possible.

https://github.com/mozilla-mobile/focus-android/blob/b5222f8f8e5d06416b4fed9e52371a6a47afb878/app/src/webview/java/org/mozilla/focus/webview/SystemWebView.java#L281-L293

From Fire TV: https://github.com/mozilla-mobile/firefox-tv/issues/926

**Comment by pocmo** [comment]
If I remember correctly the reason for that was a spoofing issue - maybe `git blame` can help.

**Comment by mcomella** [comment]
This comes from https://github.com/mozilla-mobile/focus-android/pull/390.

**Comment by pocmo** [comment]
Issue #377
