### ISSUE TITLE
Problems with web content behind status bar

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#271]
Most of the time having web content scroll behind the status bar works without problems and looks nice. However some websites use a static header and in this case the header is behind the status bar and hard to click when the toolbar is hidden. You can still fix that easily by scrolling to reveal the toolbar though.

![device-2017-03-16-20084status](https://cloud.githubusercontent.com/assets/89638/24014258/89e7ea18-0a84-11e7-92de-292411f4dcb1.png)

**Comment by antlam** [comment]
Yeah I noticed this too. It feels like a bug to me...

I noticed that static header/toolbars are fairly common on mobile, especially for commonly visited sites. 

As a quick solution, I think we might need to bring back the status bar background. What do you think? Could even keep the gradient visuals for behind there :)

**Comment by pocmo** [comment]
> I noticed that static header/toolbars are fairly common on mobile, especially for commonly visited sites.

I guess that depends. I had a hard time finding a page for this bug report. :)

> It feels like a bug to me...

Kind of. It's simple to work around this issue by scrolling, but yeah, it's not super nice (although nice looking most of the time).

**Comment by pocmo** [comment]
@antlam What do you think about this. It looks like before but instead of scrolling the whole top away we keep the background behind the status bar:

![ezgif com-optimize 1](https://cloud.githubusercontent.com/assets/89638/24098937/3298b10c-0d6d-11e7-9529-a96955a7ac66.gif)

**Comment by antlam** [comment]
ship it!

**Comment by pocmo** [comment]
Should be in beta build 688+
