### ISSUE TITLE
[l10n] New locales: quy, quc, ay

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#2710]
I just added Focus Android project for the three new locales above. They'll be needing screenshots to test, but are not shipping yet.

Since you'll need to know how they translate I imagine:
Quechua Chanka (quy) translates as "Chanka Qhichwa".
Aymara (ay) reads "Aimara" in its native language.
K'iche' (quc) reads the same, as K'iche' .

**Comment by npark-mozilla** [comment]
Only quy is imported - @Delphine that is as agreed, right?

**Comment by Delphine** [comment]
For the screenshots you ran, yes. But I see Jeff added the to locales.py for the next run of screenshots so we should be good (please correct me if I'm wrong)
