### ISSUE TITLE
Investigate App Actions and Slices

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2711]
### Why/User Benefit/User Problem

I want an instantly available, very lightweight way to look up information on the web privately, without going into a browser.

And I want to have the history of that lookup be completely gone without opening the browser.

### What / Requirements

App Actions and Slices-related feature.

Some rough examples:

* When I type “Delete”, “Erase” or “History” and Firefox Focus is running, I get the option to erase browsing history.
* When I type in potentially embarrassing search queries, I get the option to search for it privately using Firefox Focus.

### Acceptance Criteria (how do I know when I’m done?)

We’re not sure yet. Investigations will be needed to see what App Actions and Slices are capable of doing.

One thing for sure, this is something that we can potentially build up for the Andoid P release.

**Comment by brampitoyo** [comment]
![screenshot_2018-06-07 android slices build interactive results for google search google i o 18 - youtube 3](https://user-images.githubusercontent.com/51007/41071552-8553ede8-6a4c-11e8-9040-7eae3b4d4413.png)

![screenshot_2018-06-07 android slices build interactive results for google search google i o 18 - youtube](https://user-images.githubusercontent.com/51007/41071556-8b95177c-6a4c-11e8-992a-b7679d3604db.png)

![screenshot_2018-06-07 android slices build interactive results for google search google i o 18 - youtube 1](https://user-images.githubusercontent.com/51007/41071563-97771856-6a4c-11e8-9204-b8a39c819a70.png)

![screenshot_2018-06-07 android slices build interactive results for google search google i o 18 - youtube 2](https://user-images.githubusercontent.com/51007/41071564-9c315b36-6a4c-11e8-92da-ef2fb219f7db.png)

**Comment by brampitoyo** [comment]
cc @ekager

**Comment by bbinto** [comment]
@ekager to investigate what the requirements are. If Firebase integration is not required, this might be a neat feature to roll into our Android P release (/cc @lwa-moz)

**Comment by brampitoyo** [comment]
@adikul30 I think what would help the most is if you could investigate the limitations of App Actions and Slices.

Let me start with two examples:

1. While Firefox Focus is running, I can type “Delete”, “Erase” or “History” in the search box, and an app action to erase my browsing history is shown.

<img src="https://user-images.githubusercontent.com/51007/41885132-afb15dca-794a-11e8-97b3-f79b05fde7d5.png" width="360">

2. Whether Firefox Focus is running or not, I can type a website name (online shopping, banking) or a search query, and get the option of opening or searching for it privately using Firefox Focus.

<img src="https://user-images.githubusercontent.com/51007/41885152-c9ff0b00-794a-11e8-9d63-24334ac22e7f.png" width="360">

Does this give you some areas to investigate?

**Comment by adikul30** [comment]
@brampitoyo So just to be clear, by limitations, you mean you want to know if the above mentioned examples (or similar) are possible ?

**Comment by Sdaswani** [comment]
@bbinto @lwa_moz is this a must have for 7.0?

**Comment by ekager** [comment]
Looks like [app actions aren't released yet](https://developer.android.com/guide/actions/), but [slices are, and have some documentation](https://developer.android.com/guide/slices/getting-started#kotlin)

**Comment by ekager** [comment]
This is also blocked by #2909

**Comment by bbinto** [comment]
@lwa-moz and @Sdaswani - if it's not even released yet, there is no point in pushing it in, so I'm ok to wait for it but @lwa-moz probably knows best what is a MUST, so if we could get him to probe if/how much that is needed for our plans, let's regroup after again. For now, don't worry @Sdaswani.

**Comment by lwa-moz** [comment]
Including Slices in 7.0 would increase the probability of getting featured, but is not a 'must'. 

The Play Store team chooses to feature apps that highlight new OS capabilities in a way that is compelling to users. Rolling out Slices and Actions together as a fully baked feature set in a subsequent release feels more compelling, and more doable, than forcing through Slices alone. 

Getting featured will be an ongoing effort extending beyond 7.0, so we shouldn't feel that we have only one shot.

**Comment by adikul30** [comment]
Sorry I lost track of this issue ! @brampitoyo The **erase** functionality as you mentioned in the pictures could work for the Focus app. In a simple demo app, I was able to recreate this functionality with a dummy value for the number of history items available. The value of the history items in the _Slice_ also changes when the number is updated in the running app. Will try the search functionality in some time and update its status here.
