### ISSUE TITLE
Up button '^' in Find in Page is not very responsive

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2724]
### Steps to reproduce

Go to a text/image rich site like www.gizmodo.com
Search for word 'the' 
Tap down a few times, then tap up

### Expected behavior
It finds previous instances of words and highlight them

### Actual behavior
It requires several tapping to find the previous instance of words

### Device information
Pixel 2, Android 27

**Comment by boek** [comment]
@npark-mozilla I think this might be due to the tap targets being too small. Let me get a new build for you to try out
