### ISSUE TITLE
When found word is behind the Find in page text bar, it's not visible

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2725]
### Steps to reproduce
- Find a word that occurs multiple times, and the non-first occurrence is hidden behind the Find in page text bar
- tap down button to highlight the word that is hidden behind the text bar

### Expected behavior
- Page scrolls, and the word is highlighted and visible

### Actual behavior
- Page does not scroll, and the word stays covered

### Device information
- Pixel 2, API 27

**Comment by boek** [comment]
<img width="709" alt="image" src="https://user-images.githubusercontent.com/1250545/41183596-5cf3c672-6b30-11e8-96c6-e6e7749a709f.png">

Even with padding applied it looks like the WebView is drawing underneath the find in page bar.
