### ISSUE TITLE
Design a way to change theme, accent, highlight and/or gradient colours

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2726]
### Why/User Benefit/User Problem

* I want Firefox Focus to suit my personal style (hypothesis: users who take time to customise are more likely to stick – similar to users who use Firefox add-ons).
* When I use Firefox Focus in bright daylight, a light theme may be easier to read.
* If Firefox Focus can adapt its look to fit the time of the day, it may just be a nice small addition, but it also enhances the feeling that the browser suits me well.

### What / Requirements

* A way to change theme (for example: dark, ink, light)
* Potentially, a way to change accent and highlight colours (not just magenta)
* Potentially, a way to change gradient colours (although, not all gradients look good)
* Potentially, a way for themes and colours to change throughout the day (sunrise, day, sunset, night, midnight)

### Acceptance Criteria (how do I know when I’m done?)

* Not sure yet. I think that theme change is absolutely necessary to have, but accent and highlight colours may be a lot easier for engineering to implement.

**Comment by brampitoyo** [comment]
cc @bbinto in her interest.

**Comment by brampitoyo** [comment]
Some early, rough, very-alpha mocks of different gradient and accent colours:

Teal

<img src="https://user-images.githubusercontent.com/51007/41274315-0fee33fa-6e71-11e8-8b6e-3aef6b9398b2.png" width="360">

Green

<img src="https://user-images.githubusercontent.com/51007/41274316-1018fc52-6e71-11e8-9701-8b325b97cddd.png" width="360">

Orange

<img src="https://user-images.githubusercontent.com/51007/41274317-1043a268-6e71-11e8-9c40-ae38f692ae70.png" width="360">

Purple

<img src="https://user-images.githubusercontent.com/51007/41274319-106d35e2-6e71-11e8-98e0-aedfe73fdef7.png" width="360">

**Comment by bbinto** [comment]
we should get some stats from John Gruen on the Desktop Theme color picker.

I don't think this is super urgent atm.
