### ISSUE TITLE
When custom autocomplete URL added, it can save duplicates

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2730]
### Steps to reproduce
- long tap the URL bar, and select 'add custom URL' 
- long tap the URL bar again, and re-select 'add custom URL'
- Open Focus, and go to Custom URL list in settings

### Expected behavior
- There is only one custom URL entry 

### Actual behavior
- It lists duplicate URL entries

### Device information
Pixel 2, API 27

**Comment by ekager** [comment]
Is this only in a custom tab? Or anytime you add a custom URL from the URL bar?

**Comment by npark-mozilla** [comment]
@ekager just checked, it's anytime when custom URL is added.

**Comment by ekager** [comment]
Okay, thanks! Updated the description and filed a PR that should fix it
