### ISSUE TITLE
Geckoview Klar progressbar disappears when reddit is still loading

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2738]
### Steps to reproduce
- Install Geckoview Klar, and go to m.reddit.com
- wait until the site is fully loaded

### Expected behavior
- Progressbar present until all contents are loaded

### Actual behavior
- Progressbar disappears while the reddit icon is pulsing at the center, loading contents
- In webview, the progressbar is present until all contents are loaded

### Device information
- Moto G5

**Comment by bbinto** [comment]
@cpeterso will file a GeckoView issue

**Comment by cpeterso** [comment]
I filed [Firefox bug 1470988](https://bugzilla.mozilla.org/show_bug.cgi?id=1470988). If Focus+GeckoView's progress bar behaves like Chrome's and Fennec's, then this might be an issue in Focus+WebView (that we won't need to fix).

**Comment by ekager** [comment]
Closing because this doesn't seem like a bug. Someone please reopen if it is
