### ISSUE TITLE
Autocomplete "Learn more" website is missing information: does it require remote connections?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2740]
A user wanted to learn the following information from the autocomplete "Learn more" button but the page didn't have this text:
- Are autocomplete lists on device?
- If it sends data to mozilla (if send usage data is off)?
- Are self signed user certificates supported? How can they block ads?

Here's the original text from IRC ([logs](https://mozilla.logbot.info/focus/20180613#c14884893)):
> in firefox focus for android there is a Learn more for Autocomplete (default url list). the only thing I was looking for when i clicked the link is if the list is on device and if it sends some data to mozille (provided my send usage data is off) and could not learn it from learn more :)
23:24 also it looks like it does not support user signed certificate? how am i supposed to block ads?
23:24 not sure if i trust built in engine over adguard
23:25 the second issue is paramount

**Comment by bbinto** [comment]
@jonisavage, could you please check how this could be updated / better described? Thanks

**Comment by jonisavage** [comment]
Hi @bbinto and @mcomella, I'd be happy to update the article if I can get answers/details for the missing information as they're beyond my expertise.

I was going to phrase these new sections as: 

1. Are the autocomplete lists stored locally on my device?
2. If I have Firefox Focus's "Send usage data" off, will it still send information about my autocomplete list?
3. Does Firefox Focus support self-signed certificates? If not, how do I block ads?

**Comment by bbinto** [comment]
Thanks @jonisavage 
@boek could you please help answer the tech questions (if @mcomella is busy with Firefox for Fire TV).
