### ISSUE TITLE
Release 5.0 not available under releases

### ISSUE THREAD

**Issue by mziehm** [mozilla-mobile/focus-android#2750]
Latest release 5.0 (22 May 2018) according to [Play store](https://play.google.com/store/apps/details?id=org.mozilla.klar) not found under [releases](https://github.com/mozilla-mobile/focus-android/releases) or [tags](https://github.com/mozilla-mobile/focus-android/tags)

**Comment by boek** [comment]
Hey @mziehm,

Thanks for bringing this to our attention! RC4 was promoted to release. I made the appropriate change on the releases page.

@setuidroot 

We're still talking about how we're going to release nightlies, but I'll make sure they end up somewhere on Github :)

**Comment by pocmo** [comment]
See #2657 and https://github.com/mozilla-mobile/android-components/issues/208 for background. The library is no longer available under the old group id. Rebuilds of that tag will have to use the new group id: https://github.com/mozilla-mobile/focus-android/blob/master/app/build.gradle#L299

**Comment by relan** [comment]
Gotcha. Thanks for the quick reply.
