### ISSUE TITLE
Accessibility request: Scale web content according to the system font size

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2752]
### Why/User Benefit/User Problem
- No accessibility options whatsoever. Can you please add either the option  to use system fonts or to adjust the font, as now i cant use the app as i cant see it.
- We currently provide a pinch & zoom option but this is not sufficient or persistent when visiting multiple page

### What / Requirements
- Adapt web content viewed in Focus to system font size level
- Provide users with big system font size the same treatment for fonts inside web pages (not just the browser chrome)
- Either setting or used by default

### Acceptance Criteria (how do I know when I’m done?)
- Web content should adapt based on system font size

---

Via Google Play Store review: 

No accessibility options whatsoever. Can you please add either the option 
to use system fonts or to adjust the font, as now i cant use the app as i 
cant see it.

- https://play.google.com/apps/publish?account=7083182635971239206#ReviewDetailsPlace:p=org.mozilla.focus&reviewid=gp:AOqpTOHQR7DONpW4JVBpgFOS3vdXK1eHL-7BsfVdw0ahr3Cei1NjWpR3A4ynQV_i7zcBHERGgsZPz7Xgr-d9v1s
- https://play.google.com/apps/publish?account=7083182635971239206#BetaFeedbackDetailsPlace:p=org.mozilla.focus&feedbackid=gp:AOqpTOFUiiKx2NHpjwMaJnvu4-QDpayPiLLVpMB1LNTdQ1Zvbdtw4S38kKOI7wnebZomkqJCLqZnn-TuO8oRppr6GA

**Comment by bbinto** [comment]
We currently don't have accessibility settings, but we should look into using the system fonts feature - @brampitoyo to see how this effects UI. Bram, can you reach out to Eitan from the Accessibility team please.

**Comment by pocmo** [comment]
> Adapt web content viewed in Focus to system font size level

Afaik GeckoView already does that (at least in Fennec).

But we may need an API for:

> Either setting or used by default

**Comment by bbinto** [comment]
Oh, so @pocmo if we don't decide to include it as a setting, it will just work switching over to GV?

**Comment by pocmo** [comment]
> Oh, so @pocmo if we don't decide to include it as a setting, it will just work switching over to GV?

This doesn't seem to be enabled by default in GV (it's also off by default in Fennec).

File an issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1470839

Once we can enable it we can decide on whether it should be just on for everyone or whether we want to show a setting for it.

> As far as I’m aware, for UI font sizes to be scaleable by the user’s preferred text size, it needs to be specified in sp. I think we’ve done this.

Yes, that's true for our native Android UI. However web content doesn't scale accordingly currently.

**Comment by brampitoyo** [comment]
@pocmo Like #2594, this seems like a feature that we can adopt and adapt directly from Fennec without the need to reinvent the wheel.

Like that issue, the question becomes “Do we want to have accessibility settings like Fennec, or turn it on by default without a way to toggle it off?”

**Comment by pocmo** [comment]
For reference.. this is the bug where we implemented this for Fennec:
https://bugzilla.mozilla.org/show_bug.cgi?id=1328868

**Comment by bbinto** [comment]
> Like that issue, the question becomes “Do we want to have accessibility settings like Fennec, or turn it on by default without a way to toggle it off?”

Probably via setting.

@pocmo I assume dependency on GeckoView which means waiting until past 62?

**Comment by pocmo** [comment]
> @pocmo I assume dependency on GeckoView which means waiting until past 62?

Yes. Potentially this change may be small and a good candidate for uplifting.

**Comment by bbinto** [comment]
@pocmo would you mind finding/filing a bugzilla bug for this.

**Comment by pocmo** [comment]
> Filed an issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1470839

**Comment by buttercookie42** [comment]
Also realised that the font size setting in Chrome actually does both: They set the font size based on the system setting, but then also multiply it with the user provided setting value.
I wonder whether there's scope for making this part of android-components. I.e. you can call a start method and then it starts manipulating the engine's font size setting depending on the system font size, and a stop method which resets the font size back to normal again, plus the ability to set an additional user-provided factor in case the app also wants to expose a manual font size setting.

**Comment by buttercookie42** [comment]
The [GeckoView API](https://bugzilla.mozilla.org/show_bug.cgi?id=1460874) has landed.
