### ISSUE TITLE
Unregister Locale Changed BroadcastReceiver 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2767]
We register an `ACTION_LOCALE_CHANGED` `BroadcastReceiver` in `LocaleManager` but never unregister it. Is there a reason for this @pocmo ?

**Comment by pocmo** [comment]
Yeah, we want to be subscribed to that for as long as the application is alive. There's no situation where we want to not be registered anymore.

Is this causing a problem?

**Comment by ekager** [comment]
Just looking at #1544 and #1216 , but if a persistent BroadcastReceiver is never a problem, we can close this.
