### ISSUE TITLE
String import blocked on 'ay' errors

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2769]
From the import script:

```
Error: * [values-ay/strings.xml] missing placeholder in translation, key: preference_mozilla_telemetry_summary2
Error: * [values-ay/strings.xml] missing placeholder in translation, key: contextmenu_image_warning
Error: * [values-ay/strings.xml] missing placeholder in translation, key: your_rights_content3
Error: * [values-ay/strings.xml] missing placeholder in translation, key: your_rights_content3
Error: * [values-ay/strings.xml] missing placeholder in translation, key: your_rights_content2
Error: * [values-ay/strings.xml] missing placeholder in translation, key: your_rights_content4
Error: * [values-ay/strings.xml] missing placeholder in translation, key: firstrun_shortcut_text
Error: * [values-ay/strings.xml] missing placeholder in translation, key: preference_about
Error: * [values-ay/strings.xml] missing placeholder in translation, key: content_description_tab_counter
```

**Comment by pocmo** [comment]
cc: @Delphine 

Something seems to be wrong with the **ay** strings.

**Comment by Delphine** [comment]
I'll look into this now, thanks for the heads-up

**Comment by Delphine** [comment]
Just tried to radomly fix this, and flagged it to localizers so they can go back later and arrange how they should be.
Hopefully this should be clarified on their side by now. thanks!

**Comment by pocmo** [comment]
One last error is left:

> Error: * [values-ay/strings.xml] missing placeholder in translation, key: your_rights_content2

**Comment by pocmo** [comment]
Just noticed there are also some warnings:
>  [updated] app/src/main/res/values-ay/strings.xml
>             - "error_connectionfailure_message" contains invalid XHTML (Opening and ending tag mismatch: li line 1 and string, line 1, column 241 (line 1)); Falling back to loose parser.
>             - "error_hostLookup_message" contains invalid XHTML (Opening and ending tag mismatch: li line 1 and string, line 1, column 254 (line 1)); Falling back to loose parser.
>             - "error_malformedURI_message" contains invalid XHTML (Opening and ending tag mismatch: li line 1 and string, line 1, column 197 (line 1)); Falling back to loose parser.
>             - "your_rights_content5" contains invalid XHTML (Opening and ending tag mismatch: a line 1 and string, line 1, column 225 (line 1)); Falling back to loose parser.

**Comment by Delphine** [comment]
I invalidated those strings, and contacted localizers again about this. Sorry for the hassle :/

**Comment by pocmo** [comment]
> I invalidated those strings, and contacted localizers again about this. Sorry for the hassle :/

No problem. :)

Looking forward to the new strings.xml problem which will prevent those errors at input time on Pontoon :)

**Comment by pocmo** [comment]
Import works again!
