### ISSUE TITLE
Viewport issue on cnn.com

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/focus-android#2776]
### Steps to reproduce

- Install the Beta with GeckoView
- Open cnn.com

### Description

CNN displays this cookie notice now. That is not the bug though - the bug here is that the cookie notice is not properly anchored to the bottom of the screen. The *I Accept* button is therefore not visible until you start scrolling.

I have attached two screenshots that show the initial page load and what happens when i scroll the page a little bit.

Not verified with WebView Focus, but I can confirm that this works properly on Focus iOS.

### Device information

- Beta as of June 22nd.
- Moto G (2nd Generation) / Android 6.0

![device-2018-06-22-122412](https://user-images.githubusercontent.com/28052/41787757-64ac702a-7617-11e8-9c7f-f4712ba00b80.png)
![device-2018-06-22-122452](https://user-images.githubusercontent.com/28052/41787758-64b8e576-7617-11e8-94bc-f4ad231aecef.png)

**Comment by ekager** [comment]
Hey @st3fan or @npark-mozilla the banner doesn't pop up for me in the US, could one of you verify this happens with WebView Beta and if it happens with the current WebView Release? Wondering if this is a regression or a new bug with GV. Thanks :)

**Comment by st3fan** [comment]
It also happens with the current WebView release. When I try in Firefox for Android, it does show the bottom part of that message.

Maybe it is more a general Focus layout issue instead of a WebView/Gecko.

**Comment by st3fan** [comment]
I think it is definitely a more general viewport issue .. the same thing happens on maps.google.com. See these screenshots of Focus vs Firefox.

The height of the "Tap to see quick actions" bar is roughly the same as the Android toolbar at the bottom, maybe that is a good hint of what goes wrong here.

![device-2018-06-22-161328](https://user-images.githubusercontent.com/28052/41797305-8e9280f8-7637-11e8-87bb-93e12ae6f81a.png)
![device-2018-06-22-161427](https://user-images.githubusercontent.com/28052/41797306-8eb569c4-7637-11e8-89d7-bbe7eafcdd99.png)

**Comment by ekager** [comment]
Thanks @st3fan ! This problem is caused by the swipe refresh layout, which is currently disabled for all builds. Can I take it out entirely @bbinto or are we still thinking about reactivating it?

**Comment by ekager** [comment]
This was actually introduced by Swipe to Refresh but was caused specifically when the appbar_scrolling_view_behavior was moved from IWebView to SwipeRefreshLayout

**Comment by st3fan** [comment]
Reopening this because this is still happening on Focus 6.0.

**Comment by st3fan** [comment]
For comparison, try using maps.google.com in Firefox for iOS. Both apps hide the toolbar on scroll, but Firefox handles this very nicely for maps.google.com. Maybe the scrolling/hiding logic can be taken from there.

**Comment by TeNNoX** [comment]
Here are some hints:  
https://github.com/webcompat/web-bugs/issues/47995#issuecomment-584784547

**Comment by karlcow** [comment]
Yet another possible candidate. https://github.com/webcompat/web-bugs/issues/84174

**Comment by Krawei** [comment]
Is there any progress regarding this issue ? There are a lot of users complaining about broken cookie forms/websites since the last update (look at the google play store commends for firefox focus/klar (in Germany).

Kind Reagrds,

K.
