### ISSUE TITLE
Don't capitalize text in button labels

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/focus-android#278]
https://github.com/mozilla-mobile/focus-android/blob/462195f7283cc4f4f14d81efd6c2ba949437f00d/app/src/main/res/values/strings.xml#L122

```XML
<string name="firstrun_button">Ok, got it!</string>
```

Besides the fact that Ok is a typo (it should be OK), I realized this is displayed uppercase in the app.
https://people-mozilla.org/~npark/Focus_Screenshot/it-/images/phoneScreenshots/FirstUI_View_1489707954869.html

cc @delphine

**Comment by pocmo** [comment]
That's not something we do deliberately. That's the default behavior of Android's default theme (at least for some languages).

Also see: https://material.io/guidelines/components/buttons.html#buttons-style

> Button text should be capitalized in languages that have capitalization. For other languages, colored text on flat buttons distinguishes them from normal text.

CC @antlam

**Comment by pocmo** [comment]
* The English string is fixed.
* Triage decision: UX wants to keep capitalized text - following material guidelines.
