### ISSUE TITLE
Accessibility - Other Cards in First Run are "visible" when using a Screen Reader

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2780]
The other cards in the first-time-use screen carousel are "visible". Here I swiped right to the next card, and I am being read it's contents even though it is not visible on the screen.

<img alt="I am hearing about changing the default search engine, but I am still on the welcome private browsing card" src="https://user-images.githubusercontent.com/5764/39452555-721540a2-4c87-11e8-93d3-ec508574e807.png" width="256">

**Comment by pocmo** [comment]
Oh, wow. That's just Android's ViewPager. Pretty bad that it does that by default.

**Comment by rpappalax** [comment]
This seems to work well now.  Making a few further notes in #2553
