### ISSUE TITLE
Accessibility - Erase Button

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2784]
### Erase Button ###

- [ ] When being used with a screen reader the erase button should never go away. In other words, scrolling should not make it disappear.
- [ ] It would be cool if you would immediately hear "your browsing history has been erased" when tapping the erase button instead of hearing about the new focus location, and keyboard. Don't know how to pull that off.

**Comment by rpappalax** [comment]
verified that the erase button doesn't disappear when scrolling w/ TalkBack.

> It would be cool if you would immediately hear "your browsing history has been erased" when tapping the erase button instead of hearing about the new focus location, and keyboard. Don't know how to pull that off.

@ekager is this second part not part of this issue after all (aka: cool to have, but not happening)?

**Comment by sblatz** [comment]
@rpappalax It should announce "your browsing history has been erased," but I decided against removing the keyboard announcement (as it's important for the user to know the keyboard is active again).
