### ISSUE TITLE
Firefox Focus for Android (mod_rewite with 301 or 302 from http to https failure)

### ISSUE THREAD

**Issue by williamruckman** [mozilla-mobile/focus-android#2786]
Firefox Focus is not following mod_rewrite redirect with 301 or 302 from http to https URLs.

### Steps to reproduce
Go to a website using http that redirects to https using mod_rewrite of 301 or 302 code.
Example: http://ruckman.net

### Expected behavior
The browser will redirect to the secure https URL.
Example: https://ruckman.net

### Actual behavior
Browser hangs as if it is loading the page but never does. Page loads if https URL is manually entered.
All other browsers are redirecting properly.

### Device information
Android Google Pixel 2 XL (Oreo 8.1.0)
Firefox Focus version: 5.0 (Build #21342112)

**Comment by pocmo** [comment]
Only WebView version is affected.
