### ISSUE TITLE
Let the user choose where to save files

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/focus-android#2787]
### Why/User Benefit/User Problem

Instead of saving pictures in the Download folder, Focus creates a new folder called Pictures. This way WhatsApp can't find the images and I have to find it manually.

### What / Requirements

An option that let the user choose where to save the downloads with the download folder as the default location.

### Acceptance Criteria (how do I know when I’m done?)

--> when it's possible to save everything from the web anywhere.

**Comment by AyanamiSean** [comment]
Can i work on this issue?
