### ISSUE TITLE
Bug: Content moves faster than finger during drag scrolls where toolbar hides

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/focus-android#2789]
* make sure top toolbar is visible
* finger drag page content slowly upwards
* watch carefully the content where finger touches the page
* the content moves faster than the finger while the toolbar slides out of view
* after the toolbar disappears, the content moves correctly with the finger

This is quite disconcerting - the content runs away ahead of my finger :)

This problem occurs on Focus WebView and Focus GeckoView. I've replicated on a couple of my phones, one Oreo and one Nougat.

(Focus GeckoView is looking pretty nice, even on low end hardware scrolling is good. Cheers)

**Comment by pocmo** [comment]
This has been discussed for WebView in #304

**Comment by Cheap-Skate** [comment]
My issue is slightly different (but perhaps has the same cause).

I don't really care how the content moves relative to the URL bar, that seems pretty minor.

But I do care how the content moves relative to my finger

Is #304 this worth looking at again? I am surprised by the answer which seems to be "it's an Android bug". 

I have loads of apps, including browsers, which behave correctly, and only one other app (Opera Touch) which exhibits issue #304 / #2789.

I haven't seen this issue on other Android browsers:- Chrome; Edge; Samsung Internet; Opera

Or on other apps like Google Docs; Phonograph; BeyondPod

Fennec is IIUC not relevant since it generates its toolbar in a different way.

It just seems odd...

Thanks for your time

**Comment by Cheap-Skate** [comment]
Re #304 

Phonograph seems to use CoordinatorLayout and appbar_scrolling_view_behavior and the page content follows my finger correctly as the toolbar hides  i.e. it does not seem to exhibit issue #2789 or #304.

https://github.com/kabouzeid/Phonograph
https://play.google.com/store/apps/details?id=com.kabouzeid.gramophone&hl=en_GB

I  bet lots of other apps do. Most of my apps seem to behave like Phonograph (correctly) and not like Focus (incorrectly).

**Comment by domoritz** [comment]
I can confirm this issue and it's different from #304.

**Comment by vesta0** [comment]
@sv-ohorvath can you please try to reproduce this in 8.0.6?

**Comment by sv-ohorvath** [comment]
I can reproduce this on Master v 8.0.6 GV & WV.
Devices: Motorola Nexus 6 (Android 7.1.1), Pixel (Android 9)

**Comment by Guest126** [comment]
I believe this bug has been fixed in a recent update (Firefox Focus 94 or later?). Please check it.

**Comment by lobontiumira** [comment]
I did not encounter this issue lately.
Tested again today on the latest Focus Nightly build 102.0a1 from 5/11, with Oppo Find X3 Lite (Android 11), and Samsung Galaxy Note 8 (Android 9).
