### ISSUE TITLE
App freezes when typing error:<error code> in URL bar

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#279]
It was used to induce the error page in UI tests, but now when I type error:-1 in the URL bar for example, the app hangs.

**Comment by npark-mozilla** [comment]
On device (6.0) it hangs, and on sim (5.1) it exits the app

**Comment by ahunt** [comment]
I've filed a followup in #281 since I think the URL handling is all a bit messy right now.
