### ISSUE TITLE
Expose build flavor in Sentry

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2790]
When seeing a crash in Sentry it's helpful to know what build flavor this is (e.g. klarGeckoAarch64). We can get that value from BuildConfig.FLAVOR.

**Comment by RomanWuattier** [comment]
Hey, can I work on this one?
I didn't use Sentry yet. Should I record a breadcrumb in the current context and build a message containing the current flavor?

**Comment by pocmo** [comment]
Yeah, looking at crashes on Sentry a tag seems to be a good way to expose that!

**Comment by RomanWuattier** [comment]
Hey, the PR add a `BUILD_FLAVOR` tag to future events. If a lower camel case tag or another name fits better, let me know.
