### ISSUE TITLE
Initialize Sentry from FocusApplication

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2791]
Currently we initialize Sentry from MainActivity.onCreate(). A lot of other code runs before that and if this code crashes then we do not see it in Sentry.

We should initialize Sentry from FocusApplication.onCreate(). That's the earliest point where we have a `Context` object.

**Comment by agbanagba** [comment]
Hello i would like to work on this issue. Can anyone help on how to go about this as this is my first time contributing to open source. Thanks

**Comment by pocmo** [comment]
Sure!

Follow the README to get a local copy of Focus and build it in Android Studio:
https://github.com/mozilla-mobile/focus-android/blob/master/README.md

We need to move the code that initializes Sentry from MainActivity....
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/activity/MainActivity.java#L57

to FocusApplication:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/FocusApplication.kt#L28

Are you familiar with `git`? Next you will need to commit your changes, push them to GitHub and open a pull request. This guide may be helpful:
https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by agbanagba** [comment]
Thanks i would send a PR when i'm done.

**Comment by agbanagba** [comment]
Hi @pocmo I have made a pull request but i don't know why it failed the Taskcluster check.

**Comment by pocmo** [comment]
@agbanagba Thank you! I'll comment on the PR.

**Comment by ekager** [comment]
Hey @RomanWuattier , sure you can work on this, it looks like #2809 never was cleaned up and merged.
