### ISSUE TITLE
What's new link for 6.0

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#2806]
We need a what's new link for Focus 6.0

**Comment by Sdaswani** [comment]
@boek can you give a high level overview with links to tickets for all the 6.0 features here for Joni’s benefit?

**Comment by boek** [comment]
* #967 Find in page
> Adds the ability to find content within a page

* #2454 HTTP Auth support
> Adds functionality to be able to respond to websites secured with basic authentication.

* #822 Request desktop site
> Adds a button request the desktop version of a website

Am I missing anything @bbinto?

**Comment by boek** [comment]
Checked with @bbinto, looks good!

**Comment by jonisavage** [comment]
Hi all, here's the link you can use: https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/whats-new-focus-android-6

I'll have a draft ready for you to review today.

**Comment by bbinto** [comment]
thanks @jonisavage - looking forward to review it.

**Comment by boek** [comment]
Thanks @jonisavage!
