### ISSUE TITLE
Closing a custom tab closes a normal tab in Focus

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2812]
### Steps to reproduce
1. Set Focus as your default browser
2. Open a page in Focus
3. Go to an app that supports Custom Tabs and open a link
4. Close the custom tab
5. Go back to Focus

### Expected behavior
Your normal session is still there

### Actual behavior
Closing the custom tab closes the page (or one of the tabs)

### Device information
For GeckoView and WebView

**Comment by pocmo** [comment]
Seeing there is a PR... can we move this into the next milestone?
