### ISSUE TITLE
Override icon for Nightly track

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2818]
It would be helpful to override the icon for Nightly builds so that users can easily see that they are on the Nightly track.

~I do not want to add a new release type to build.gradle because this will slow down everything (more variants to build) for no reason but a different icon. We just got rid of the Beta type and want to remove the Coverage type too: #2313~

**Comment by pocmo** [comment]
While we are at it... for Sentry it would be nice to attach this to the version name too (e.g. 6.2-nightly)

**Comment by pocmo** [comment]
@brampitoyo Can you provide us with an updated icon?

Basically we would need some kind of "Nightly" version for the files in those folders (those are for local builds): https://github.com/mozilla-mobile/focus-android/tree/master/app/src/debug/res

**Comment by brampitoyo** [comment]
Hi @pocmo, what’s the difference between this Nightly version and the Dev build (which we already have the icon for)?

I’ll assign myself on this issue, so I can be reminded to design it.

**Comment by pocmo** [comment]
@brampitoyo The dev icon is used for local/debug builds whenever a developer builds and deploys the app.

**Comment by pocmo** [comment]
> I’ll assign myself on this issue, so I can be reminded to design it.

Okay! Otherwise I see myself forced to use this 😂 ..

![nightly](https://user-images.githubusercontent.com/89638/42496701-2e7a5f44-8427-11e8-9272-bd90e87a0da3.png)

**Comment by brampitoyo** [comment]
First-round mockup. Keep in mind that this is very early, so hasn’t been shown to the rest of our team!

<img width="634" alt="screen shot 2018-07-11 at 11 51 24 am" src="https://user-images.githubusercontent.com/51007/42543633-d405a444-8500-11e8-85bd-c553e5d43766.png">

**Comment by ekager** [comment]
Idk @brampitoyo I kind of like @pocmo's sketch 😜. Your mockups look awesome!!

**Comment by pocmo** [comment]
The logo looks nice! :)

Can we explicitly say "Nightly" somewhere (like in the other variants)? We need to make it as obvious as possible so that users understand that they are on the Nightly track.

![image](https://user-images.githubusercontent.com/89638/42563388-698b3676-84fe-11e8-86dc-313a10a5b7e3.png)

![image](https://user-images.githubusercontent.com/89638/42563379-6629bdb8-84fe-11e8-80fe-984c6da4b6d4.png)

**Comment by pocmo** [comment]
Okay, let's try! A different icon is already better than using the same icon. :)

**Comment by pocmo** [comment]
@brampitoyo One issue here is that Google Play always displays "Firefox Klar (Beta)" and "You are a beta tester" no matter what testing track you are actually on. And users where confused whether they are actually on the Nightly track. I'm not 100% sure if a different icon will change that (because this could be a Beta icon too?). But a different logo icon already way better than using the same logo - so we can try! :)

**Comment by pocmo** [comment]
![screenshot_20180712-105122 2](https://user-images.githubusercontent.com/89638/42623094-418c7864-85c2-11e8-938b-817934e413f9.png)

**Comment by pocmo** [comment]
> I’m not opposed to adding a “Nightly” flag in the icon should it become necessary. For now, let’s go with the new icon. 

👍

**Comment by brampitoyo** [comment]
@pocmo I expect to get this icon from Sean tomorrow.

**Comment by pocmo** [comment]
@colintheshots Maybe we should get the "Nightly" build type in already? We want Nightly builds to only use GeckoView and not be part of the A/B experiment. So we may want to have the build type before landing the A/B test, I guess?

**Comment by brampitoyo** [comment]
<img width="256" src="https://user-images.githubusercontent.com/51007/42858226-8ad088f6-8aa1-11e8-8d0f-dfd2ea0bbb11.png">

@pocmo Here are the assets, as promised:

* [Launcher icons](https://cl.ly/t0cS/Focus%20Android%20Nightly%20-%20Launcher%20Icons.zip) (circle mask)
* [Adaptive icons](https://cl.ly/t0Wx/Focus%20Android%20Nightly%20-%20Adaptive%20Icons.zip)

**Comment by colintheshots** [comment]
@pocmo I'll add a nightly build product type. It'll disallow webview variants and only support gecko variant targets. The switcher will still be there and the A/B test will effectively be a no op for nightly, since the default for gecko variants is GeckoView.
