### ISSUE TITLE
Does the Nightly track remove app data?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2819]
Some users mentioned that after subscribing to Nightly their app data was reset (e.g. saved autocomplete domains were lost). That's scary and I have no idea why that would happen. I do not care so much about that happening with Nightly... but I think we should make sure that's not just a bug in our app and will happen to all users on some update.

**Comment by pocmo** [comment]
@npark-mozilla Can you take some old actual releases and update them up to the latest 6.0 RC and see if data gets lost?

**Comment by npark-mozilla** [comment]
I tried it by building and installing debug/release build of 4.0 , and then installing debug/release builds of 6.0 by adb install -r command.  After the 'upgrade' the apps all retained the autocomplete settings / search engine selection, and custom search engine list.

**Comment by npark-mozilla** [comment]
However, we did find an intermittent possible sqlite error in google firebase, and @rpappalax will be filing a bug shortly.

**Comment by npark-mozilla** [comment]
Just updated Focus webview 4.0 to Focus geckoview 6.2  via adb install -r command, but this also retained autocomplete field and search engine data.

**Comment by pocmo** [comment]
@npark-mozilla Thank you! I think in this case we can close this. If this happens for Nightly installs then we will have to live with that.
