### ISSUE TITLE
any unsupported URL prefix hangs the app

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#282]
Initially I thought it only applies to market:// url in simulator, but it seems like it applies to any URL prefix that Focus cannot handle.  If there is a typo on URL, or if the prefix is something that Focus does not understand, it will hang the app.  For example, typing htps://www.google.com will cause the app to freeze.  Probably be fixed with #281

**Comment by ahunt** [comment]
Yup - I've tackled it all as part of that bug, but it looks like you can attach multiple bug numbers to a given commit, so hopefully we'll have this bug linked too!

**Comment by npark-mozilla** [comment]
Verified that this is fixed now
