### ISSUE TITLE
Focus/Klar + GeckoView version numbers are difficult to type

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2820]
> Focus 6.2 / #121791209 / 62.0.20180625141512

Problems:
- Typing them is error-prone
- It takes a long time
- It discourages bug filing when I have to type ^ out :)

This is especially bad if you're on nightly and the versions change frequently.

**Comment by pocmo** [comment]
Is there anything we can do about that? We can't change the version numbers ... on the device you can copy&paste them though. :)

**Comment by ekager** [comment]
Closing for now, not our top concern, sorry Mike!
