### ISSUE TITLE
Override icon for Beta track

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/focus-android#2822]
It would be helpful to override the icon for Beta builds so that users can easily see that they are on the Beta track.

(Clone of issue https://github.com/mozilla-mobile/focus-android/issues/2818)

**Comment by ekager** [comment]
From @pocmo "Beta is deliberately a release build with no modifications. Good Beta builds get promoted to release on Google Play with no rebuilding."

Closing, but leaving #2818 for a new icon for nightly
