### ISSUE TITLE
Google News loads slowly with GV 

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/focus-android#2829]
Every time I navigate to Google News, I get an unresponsive script warning. 

### Steps to reproduce

1. Navigate to: https://news.google.com/?hl=en-US&gl=US&ceid=US:en

### Expected behavior

No warnings, page loads. 

### Actual behavior

I see a warning about an unresponsive script, and I must click continue to move forward. 

![signal-attachment-2018-06-29-110809](https://user-images.githubusercontent.com/152493/42100156-7093a0b8-7b8d-11e8-8961-d84d4943e7f8.png)

### Device information

* Android device: LG-H810, Android 5.1
* Focus version: 6.2 (Build #221791209 Emoji image of 'lizard' 62.0.20180625141512)

**Comment by pocmo** [comment]
Yep, I am seeing this too. It loads for quite a while (nothing rendered) and then I get the popup. At the same time the page appears behind the popup.

**Comment by bbinto** [comment]
@pocmo - is this on a pixel?

For me, on my Pixel, it keeps loading forever.

**Comment by pocmo** [comment]
> @pocmo - is this on a pixel?

Yep, Pixel 1 XL.

**Comment by ekager** [comment]
@yoasif or @pocmo are you still seeing this issue on this site?

**Comment by yoasif** [comment]
@ekager I don't see the unresponsive script dialog. Unfortunately, loading the page is still quite slow compared to Klar 6 (installed from F-Droid) -- 35 seconds vs. 2 seconds.

**Comment by ekager** [comment]
Updated the issue description thanks for testing @yoasif ! @cpeterso is this a known slow page?

**Comment by cpeterso** [comment]
@yoasif - Is Google News still a problem on your device? On my low-end Moto G5, Google News loads in 5-6 seconds (progress bar finishes and no Unresponsive Script errors) in Focus 7.0 Nightly and Fennec 64 Nightly. It loads in just 2 seconds in Klar 6.0 with WebView.

**Comment by vesta0** [comment]
@yoasif On my Pixel 1 XL Google News loads in 5 seconds (Focus 7.0.1). Is this still a problem on your LG device?

**Comment by yoasif** [comment]
Just tried this again on the LG device -- 2 seconds with Klar, 14 seconds (loading until no progress bar appearing) with Focus GV.

**Comment by lobontiumira** [comment]
This is not an issue anymore, the news.google.com is loading pretty fast, under 3 seconds.
Tested on the Samsung Galaxy Note 8 (Android 9), and on Google Pixel (Android 10), on 8.16.0 Focus build.
