### ISSUE TITLE
Transform SUMO help page to make it mobile friendly

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#283]
See #22 for background: The SUMO help page is not really nice on mobile. If possible we would like to remove the header and footer.

* We could inject a JavaScript that makes the necessary changes.
* Or we could load the HTML manually, manipulate it and hand it to the WebView

**Comment by bbinto** [comment]
That's something that our team can't do, right? It'd be the SUMO CMS?

**Comment by pocmo** [comment]
> That's something that our team can't do, right? It'd be the SUMO CMS?

We might be able to hack something. However it looks like this has been solved with the SUMO rollback. There's now a mobile version of SUMO again.

**Comment by mcomella** [comment]
SUMO has a mobile version now so this sounds like WORKSFORME.
