### ISSUE TITLE
"Continue with Facebook" link missing text on Slickdeals deal page

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/focus-android#2830]
### Steps to reproduce

1. Navigate to https://slickdeals.net/f/11750439-new-amd-ryzen-7-2700x-8-core-3-7-ghz-socket-am4-105w-yd270xbgafbox-processor-246-ac-ebay-free-shipping-246-49
2. Scroll down to "Get more deals from Slickdeals" section

### Expected behavior

There are two styled links: "Continue with Facebook" and "Continue with Google" with text present. This is how it appears on Fennec and other browsers. 

### Actual behavior

"Continue with Facebook" link is missing link text. Icon is still present. 

![signal-attachment-2018-06-29-122246](https://user-images.githubusercontent.com/152493/42103727-eed81224-7b97-11e8-9691-25416543114a.png)

### Device information

*   Android device: LG-H810, Android 5.1
*   Focus version: 6.2 (Build #221791209 Emoji image of 'lizard' 62.0.20180625141512)

**Comment by bbinto** [comment]
@yoasif - have you tried turn on/off specific blocker settings to determine which one could cause the breakage?

**Comment by yoasif** [comment]
Oddly, turning off all blockers continues to reproduce the issue, so it seems unrelated to that feature.

**Comment by ekager** [comment]
Hi @yoasif I can reproduce, but if I turn on Cookies, I see the icon. Closing this issue.

**Comment by yoasif** [comment]
@ekager FWIW, I had Focus settings at defaults (so cookies were enabled). With the latest builds at least, what happens is that the links get filled in with the text after a few seconds - and I see this in Fennec along with the built in browser on my device. 

For whatever reason, previous builds never actually completed loading that link text, but that appears to be working now.
