### ISSUE TITLE
Two characters deleted in url bar on backspace

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2835]
### Steps to reproduce
- Click url bar on home screen
- Type "app"
- Press backspace (autocomplete removed)
- Press backspace

### Expected behavior
"ap" remains

### Actual behavior
"a" remains

### Device information

* Android device: Pixel 2
* Focus version: Klar 5.2 #21731654

**Comment by pocmo** [comment]
This looks like the same bug as: https://github.com/mozilla-mobile/android-components/issues/348

Interestingly that's even in Fennec.

**Comment by codedsun** [comment]
@mcomella Is this issue up for grab?

**Comment by pocmo** [comment]
@codedsun Yeah, but you will have to fix that in our android-components repository (ui-autocomplete module):
https://github.com/mozilla-mobile/android-components

**Comment by codedsun** [comment]
@pocmo Let me check it, and I will try to resolve it :)👍

**Comment by codedsun** [comment]
@pocmo Wanted to ask that how can I debug the android autocomplete textview? Like I have cloned the app but wanted to know how this class is working through debugger. I have never debugged a library, can you guide me.
Thanks.

**Comment by ekager** [comment]
@codedsun there should be an example app that uses the autocomplete component.

**Comment by pocmo** [comment]
Yeah, after importing the android-components project into Android Studio you should see multiple sample apps. The samples-toolbar is probably the easiest/simplest one for testing this component.

**Comment by vesta0** [comment]
I just tried to recreate this and it seems to behave as expected. @rpappalax would you please confirm?

**Comment by mcomella** [comment]
I fixed this in 0.26 components and Focus is using the latest components so it should no longer be an issue.

Components issue for this: https://github.com/mozilla-mobile/android-components/issues/911
