### ISSUE TITLE
WebRTC fingerprinting protection bug

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#2836]
I was testing Firefox Klar with the WebRTC test on browserleaks.com. The DeviceIds stay the same when the trashcan button is pressed, but the fingerprint changes when I manually close the app (flick it off the screen in the opened apps list). Ideally, the fingerprint should be reset even when only pressing the trashcan button.

**Comment by vesta0** [comment]
There is a similar issue open in our backlog #609
