### ISSUE TITLE
Send `label=browser-firefox-focus` when reporting an issue on webcompat.com

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/focus-android#2837]
Currently, if people report bugs via the "Report Site Issue" feature, we can't distinguish between Fennec and Focus GeckoView, because we send the same UA string.

However, webcompat.com supports adding additional labels to an issue via a `label` param, so we should toss `label=browser-firefox-focus` into `REPORT_SITE_ISSUE_URL`:

https://github.com/mozilla-mobile/focus-android/blob/c169cf6b186b9ddb93de970368dc112a29a621d9/app/src/main/java/org/mozilla/focus/utils/SupportUtils.java

I don't know if it's possible to know if we're building w/ GeckoView, if so, something like `browser-focus-geckoview` would be even better. Is that doable @ekager?

Server side companion bug: https://github.com/webcompat/webcompat.com/issues/2537

**Comment by ekager** [comment]
Yeah, I can add this. Thanks for looking into this @miketaylr !
