### ISSUE TITLE
Consider reducing number of clicks to share to pocket

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2838]
### Why/User Benefit/User Problem
Currently users have to go to Share -> (find it) Pocket to share to Pocket, which is the default sharing mechanism on Android. Given that focus doesn't have a temporary saving mechanism, save to pocket is one of my primary interactions – it'd be convenient if it required fewer clicks.

We could also introduce this useful feature to users ("save things from focus!") and increase the Pocket brand recognition.

### What / Requirements
- Reduce the number of clicks to share to Pocket
- Consider introducing Pocket as a way to save content from Focus

### Solution thoughts
This could be hardcoded or even be a quick share feature (didn't we already have this? Maybe I don't see it because I'm on Klar?).

**Comment by pocmo** [comment]
> This could be hardcoded or even be a quick share feature (didn't we already have this? Maybe I don't see it because I'm on Klar?).

Quick share was never implemented and is currently a P5: #687. Same for "quick open" (Can't find the issue).
