### ISSUE TITLE
Focus crashes when copying link with menu item in Slack custom tab 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2848]
### Steps to reproduce
1. Default browser focus 
2. Open link in Slack 
3. Open menu and select 'copy link'

### Expected behavior
Link is copied
### Actual behavior
App crashes
### Device information

* Android device: pixel 2
* Focus version: GV nightly

**Comment by pocmo** [comment]
Looks like #2846?

**Comment by ekager** [comment]
Yeah just commented there with maybe an idea of what's going on but can't
confirm I don't have a laptop with me

>

**Comment by boek** [comment]
Dup of #2846
