### ISSUE TITLE
GeckoView builds leave around data + cache

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2850]
### Steps to reproduce
- Open the app
- Visit a web page
- Delete data
- Go to home screen
- Get app info for the app

### Expected behavior
Data usage and cache are roughly 0

### Actual behavior
- Data is 7.46 MB and cache is 53.90 MB

### Device information

* Android device: Galaxy S5 (Android 6?)
* Focus version: 6.2 / 121791209 / 62.0.20180625141512

I'm reproducing on the device that can't load some pages, #2814, so maybe my build is not working in other ways too. :)

**Comment by Sdaswani** [comment]
@ekager to post findings and then close.

**Comment by ekager** [comment]
From the GV team, all browsing data is cleared so this is not a concern. Closing.

**Comment by 4ut0-M-4t** [comment]
> @pocmo says, Focus uses private mode, so no data is stored; therefore no need to clear it.

If Fennec is set to clear history and cache on exit, it really does so. But Focus/Klar GV does not. Keeping all that data may not be a privacy concern for some, but it definitely is wasting precious space.

**Comment by colintheshots** [comment]
We have tests we run that prove the data is cleared.

**Comment by 4ut0-M-4t** [comment]
**Device**: SGN4 ARMv7 (Android 6.0.1 and 7.0)
**Focus version**: Klar 9.0 (Build #330171230 GV 64.0.20190111134233)

Settings > Application manager > Firefox Klar > Storage > Cache is 56.30 MB -> definitely not being cleared.
I trust you test it thoroughly with emulated and real devices, but Klar still eats up space on *my* device.
