### ISSUE TITLE
Can't do searches including a domain name

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/focus-android#2854]
### Steps to reproduce

Search for "reddit.com chess"

### Expected behavior

Same as on desktop: default search engine result for those 2 keywords.

### Actual behavior

Goes to reddit.com, drops second part.

### Device information

* Android device: Pixel 2 XL
* Focus version: 5.0

**Comment by KrzysztofBarszcz** [comment]
I think I know the simple solution :)

**Comment by Daisy-pliu** [comment]
verified and fixed in https://github.com/mozilla-tw/FirefoxLite/issues/3239
