### ISSUE TITLE
Add do not track header to settings > Privacy and Security

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/focus-android#2857]
Add the do not track header support to Firefox Focus.
Why/User Benefit/User Problem
Additional tracking protection for users when a business opts in to the do not track header.
What / Requirements
Add the do not track header to Settings. No prerequisites.
Acceptance Criteria (how do I know when I’m done?)
The do not track header will be added to Settings and function properly.
Android device: Pixel XL
Android version: 9 DP 4

**Comment by pocmo** [comment]
Thank you for filing this!

Duplicate of #446.

The do not track header will be added automatically once we switch from WebView to GeckoView.

**Comment by mcl21014** [comment]
Thanks. Didn't see the other issue on mobile. Good to know it'll be included. I'll wait for it in the nightly builds.

**Comment by pocmo** [comment]
@mcl21014 The Nightly builds with GeckoView should already have the header set.
