### ISSUE TITLE
CDATA missing for 'about_content' string

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#286]
I just imported the strings from the l10n repository again and noticed that the CDATA block is missing for the 'about_content' string:

`  <string name="about_content"><p>%1$s gibt Ihnen die Kontrolle.</p>\n<p>"Verwenden Sie es als privaten Browser:\n  "<ul>"\n    "<li>Suchen und blättern Sie in der App</li>"\n    "<li>Blockieren Sie Tracker (oder aktualisieren Sie die Einstellungen, um Tracker zu erlauben)</li>"\n    "<li>Entfernen Sie Cookies, um Such- und Browserverlauf zu löschen</li>"\n  "</ul>\n</p>\n<p>%1$s wird von Mozilla entwickelt. Unsere Mission ist es, ein gesundes, offenes Internet zu fördern.<br/>\n<a href="%2$s">Erfahren Sie mehr</a></p></string>
`

Because of that we are loosing the formatting for this string.

![about_german](https://cloud.githubusercontent.com/assets/89638/24058376/2e6bf11c-0b4b-11e7-9608-ea1a64836d4a.png)

**Comment by pocmo** [comment]
@ahunt Can you take a look? I'll try to do another import tonight.

**Comment by pocmo** [comment]
Oh, wait, you are in a different timezone again. :)

**Comment by ahunt** [comment]
I'm looking at it now, but no guarantees it'll be done before you finish for the day ; ).
