### ISSUE TITLE
Nightly is only available with google account

### ISSUE THREAD

**Issue by CircleCode** [mozilla-mobile/focus-android#2864]
### Why/User Benefit/User Problem
Users willing to use focus often do this for privacy purposes.
Those testing nightly builds are often more susceptible to tweak their android for the same privacy reasons.
As a conclusion, some users willing to test nightly builds of firefox focus do not have google play installed (some use microg, or even only f-droid). For those people, nightly builds are not available

### What / Requirements
It would benefit the test program if users could download nightly builds without a google account,
either through "public" release (like firefox nightly) or through f-droid.

### Acceptance Criteria (how do I know when I’m done?)
nightly builds of focus available

- [ ] publicly on play store,
- [ ] or on f-droid

**Comment by pocmo** [comment]
The latest Nightly builds can be downloaded here:
http://bit.ly/focus-nightly-builds

**Comment by pocmo** [comment]
Added the download URLs for Nightly/Beta to our wiki page:
https://github.com/mozilla-mobile/focus-android/wiki/Release-tracks

**Comment by zekooooo** [comment]
As an F-droid-only user I would really appreciate an autoupdating Nightly version :)

**Comment by pocmo** [comment]
If someone feels like maintaining it! Unfortunately it's probably not something the Focus team can take over (We also do not maintain the f-droid Klar releases).

**Comment by MathJoDE** [comment]
> The latest Nightly builds can be downloaded here:
> http://bit.ly/focus-nightly-builds
> 
> (Of course they won't update automatically)

This link unfortunately is broken.

Where to find the non-Google Play downloads now?

**Comment by rocketsroger** [comment]
> Where to find the non-Google Play downloads now?

https://github.com/mozilla-mobile/focus-android/releases

**Comment by MathJoDE** [comment]
Thanks.
However I search for the non-Google beta downloads. Do they exist? (Sorry for expressing myself incorrectly)
