### ISSUE TITLE
Beta feedback about typing

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2866]
Via GPS
1) 
"Beim schreiben in der App passiert es häufiger, dass beim schreiben eines 
Wortes das gesamte vorherige Wort beim eintippen von jedem Buchstaben 
wiederholt wird. Bsp. Ich will Internet schreiben, dann schreibt er 
IInIntInteInterInternInterneInternet. Auch wird ab und zu die Browser 
Chronik beim aufrufen der vorherigen Seite oder einfach so gelöscht, 
wodurch die geöffnete Seite geschlossen wird."

2) 
"Browser feels really fast and smooth, but there is few things need to be 
fixed: sometimes first letter cannot be removed with keyboard's backspace 
from addressbar. Also, Would be nice to have addressbar on the bottom of 
the browser. That would help using big phones with one hand.:

**Comment by pocmo** [comment]
1. Is issue #2840 (and upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1470786)
2. sounds like #778

**Comment by bbinto** [comment]
closing this in favour of #778
