### ISSUE TITLE
AddtoHSTest.java is failing

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/focus-android#2873]
### Steps to reproduce
automated tests in AddtoHSTest.java (SearchTermShortcutTest in particular) fail frequently on all devices

### Expected behavior
Tests should successfully create and find desktop shortcuts

### Actual behavior
Each desktop shortcut links to a temporary mock server and port, i.e. http://localhost:12345.  When several tests run back-to-back, there can be more than one shortcut with different ports, but the test will only grab the first one available (which may be a zombie link to a dead port).  

Also, the test is missing a proper swipe to ensure that it lands on the correct screen with the shortcuts (and not the home screen, for example).

### Device information

* Android device: all
* Focus version: 6.2

**Comment by rpappalax** [comment]
have fixed issues on focus, but klar is failing due to first time experience launching at start of first test (despite FIRSTRUN_PREF = true), https://github.com/mozilla-mobile/focus-android/blob/6cd8fc362877c16363a3864f41f76367dced6acb/app/src/androidTest/java/org/mozilla/focus/activity/AddtoHSTest.java#L52

**Comment by pocmo** [comment]
Is this #2664?

**Comment by rpappalax** [comment]
@npark-mozilla  Have fixed issues on focus. Klar is failing in Firebase due to first time experience launching at start of first test (despite FIRSTRUN_PREF = true), https://github.com/mozilla-mobile/focus-android/blob/6cd8fc362877c16363a3864f41f76367dced6acb/app/src/androidTest/java/org/mozilla/focus/activity/AddtoHSTest.java#L52).  Tests otherwise pass on Klar (after first run).  Will submit a PR shortly.

**Comment by rpappalax** [comment]
@pocmo Yes, I believe so
