### ISSUE TITLE
Add UA string spoof to get Tier-1 Google search experience

### ISSUE THREAD

**Issue by andreasbovens** [mozilla-mobile/focus-android#2884]
### Why/User Benefit/User Problem

When switching to GeckoView, we need to make sure the search experience stays top notch. Google doesn't serve Gecko its high end version at this point, so we have to spoof the UA string on selected Google domains. 

### What / Requirements

We're currently doing an experiment on Fennec Nightly - see https://miketaylr.com/posts/2018/07/google-search-in-firefox-for-android-nightly.html for details

We'll need to do something similar (hardcoding these values in `about:config` perhaps?) in Focus/Klar.

### Acceptance Criteria (how do I know when I’m done?)

When performing a search, the Google Tier-1 experience should be shown.

**Comment by pocmo** [comment]
We do not have any GeckoView API to change the UA currently.

Also I'm not sure right now if we could change the UA before every load if we had a simple UA API.

**Comment by bbinto** [comment]
@andreasbovens do we still need to worry about this after the recent Google search experience changes?

**Comment by vesta0** [comment]
This is no longer needed.
