### ISSUE TITLE
Sentry: GeckoSession crashes, opening new session

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#2900]
https://sentry.prod.mozaws.net/operations/focus-android/issues/4423158/

```
GeckoSession crashes, opening new session
```

**Comment by pocmo** [comment]
This is not an app crash. We log this in Sentry when the `GeckoSession.onCrash()` callback gets executed and we re-open a new session:
https://github.com/mozilla-mobile/focus-android/blob/fe79a22601ceb7b1e4f6d5a158a6c5accf5b065d/app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java#L308

@cpeterso Can you verify with the GV team whether it's a problem that this onCrash() callback gets executed that often?

**Comment by ekager** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1476346

**Comment by bbinto** [comment]
Once GV team has triaged the bugzilla but, let's revisit and prioritize accordingly.

**Comment by cpeterso** [comment]
I think we can close this issue. The GV bug was closed as WORKSFORME: https://bugzilla.mozilla.org/show_bug.cgi?id=1476346#c4

The conclusion there was that these are real GV crashes being reported to Focus's onCrash handler. We can monitor this crash signature ("GeckoSession crashes") in Sentry to see if there are any GV crash spikes, even though these Sentry crash reports contain to actionable information.
