### ISSUE TITLE
Focus constantly bugs users about GDPR cookies

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/focus-android#2914]
## Steps to reproduce
Visit any site with a GDPR/EU cookie popup like https://techcrunch.com/2018/06/26/firefox-gets-speedier-tab-switching-a-new-accessibility-tool-for-developers-and-more/
You will get a GDPR notification
![screenshot_20180711-174312](https://user-images.githubusercontent.com/922368/42778985-9da0797e-8947-11e8-8923-c44347a95453.png)
Click OK at the bottom.
Close Focus.
Repeat the steps.

### Expected behavior
Either block any such notifications by default like https://addons.mozilla.org/en-US/firefox/addon/i-dont-care-about-cookies/ or have some way of persisting some cookies related to GDPR.

### Actual behavior
You will get the notification every single time.

### Device information

* Android device: LineageOS (based on Android 7.1.2)
* Focus version: Nightly with GeckoView but all of them have this issue.

**Comment by pocmo** [comment]
Related (or duplicate): #1254

**Comment by bbinto** [comment]
This doesn't have anything to do with our newly introduced cookie management feature, this also happens e.g on Desktop in PBM.

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest RC 95.1.0 build, nor on the 12/7 Focus Nightly with Samsung Galaxy Note 8 (Android 9).
