### ISSUE TITLE
Add renderer selection between GeckoView and WebView

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/focus-android#2915]
### Why/User Benefit/User Problem
As a user, I'd like to receive the latest and greatest web renderer with all new Firefox features.
As a developer or QA engineer, I'd like a means to cleanly select between GeckoView and WebView without messing up app state.

### What / Requirements
There will be a shared preference to select which web view type to use. A developer or QA engineer will have a means to toggle this setting. Also, each build flavor will have a default web view type to use in case the shared preference is unset.

### Acceptance Criteria (how do I know when I’m done?)
When a developer can toggle between GeckoView and WebView, this task will be completed. It is also in scope to restart the app after toggling so the new renderer starts up with a blank, clean slate to avoid switching state-related bugs.

**Comment by bbinto** [comment]
@colintheshots can we add a telemetry probe so I can query on the usage of the engines?

**Comment by colintheshots** [comment]
@bbinto I'll need to investigate how to do that. I just added the GeckoView flag by updating the old, incorrect logic. Was there already any telemetry tied to that?

**Comment by pocmo** [comment]
> @colintheshots can we add a telemetry probe so I can query on the usage of the engines?

Let's make sure to file a follow-up issue for that. :)

**Comment by bbinto** [comment]
@colintheshots let me know when you've created the telemetry issue and I'll confirm/comment in there - thanks.
