### ISSUE TITLE
Speed up / smooth InfoActivity

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#292]
WebView initialisation and loading for local pages (about/rights) is surprisingly slow (at least on the N5 I'm currently using). It would be nice to make that faster (I have no idea if that's feasible though).

We could also possibly add a fade-in when content appears (we used to have a jarring white->dark content flash in the past, we now show a dark screen until content loads, but fading the content in would be even nicer). We currently only make the WebView visible once content has loaded, so it shouldn't be too hard to add an appropriate transition when making it visible (most of our fades are 200ms, which is defined in configuration.xml).

This doesn't seem particularly important, since these screens aren't shown very often, but it would be a nice bit of polish.

**Comment by sabbir044** [comment]
@ahunt 
I have tried to improve the speed of the loading but it seems not possible too much. It depends on lots of things (css, reading from assets, javascript etc). 

About animation, if we add android:animateLayoutChanges="true" to the Linearlayout, it will give a simple fade-in transition with around 200ms. If thats ok, then I will create a pull request with that. Else we can add custom transition with bit of more code, but both works fine.

**Comment by ahunt** [comment]
Yeah - I had a feeling there's not much we can do about the webview.

It would be interesting to see what things look like with animateLayoutChanges. Since these screens aren't used that regularly, we probably don't want to do anything too complicated (especially since we don't want to have to maintain that), but a simple transition doesn't seem bad.

**Comment by pocmo** [comment]
I assume that this does not affect performance but I noticed that we load some resources from assets and others from res/raw.
