### ISSUE TITLE
debian.org & gnu.org open in Chinese

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2920]
## Steps to reproduce
- Visit debian.org or gnu.org

### Expected behavior
Page is in english

### Actual behavior
Page is in chinese

### Device information

* Android device: Pixel 2 Oreo
* Focus version: Klar 5.2 #21731654

I'm guessing they're doing user agent sniffing because I don't see this problem in Chrome

**Comment by bbinto** [comment]
Is this just for webview?

**Comment by mcomella** [comment]
Yes, I don't see this problem in WebView (or the emulator for that matter).

**Comment by lobontiumira** [comment]
This issue no longer reproduces on Focus Klar 8.16.0 with Samsung Galaxy Note 8 (Android 9):
![Untitled](https://user-images.githubusercontent.com/40694158/124236159-cd9c3380-db1e-11eb-8a0c-0c6961544f93.png)
