### ISSUE TITLE
Wrong locale for search engine

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2925]
<img width="764" alt="screen shot 2018-07-18 at 10 52 53 am" src="https://user-images.githubusercontent.com/122897/42889643-eec7ffa2-8a78-11e8-8ad6-a872e84f8217.png">

German
"Seit einer Weile funktioniert die Suche nicht richtig. Die Suchen wie 
Duckduckgo, Ecosia oder Bing denken immer ich wäre in den USA. Daher 
bekomme ich immer Such - Ergebnisse für und aus den USA."

**Comment by caugner** [comment]
I tried to reproduce the issue in Firefox Klar 8.0 Build 322881254.

Setting DuckDuckGo as the default search engine and searching for the term "Mozilla", opens the following URL: `https://duckduckgo.com/?q=Mozilla&t=fpas&ia=web`

The URL does not contain the `kl` parameter for selecting a locale (see https://duckduckgo.com/params), therefore no region is selected, which could explain why search results included "US results".

Furthermore, DuckDuckGo shows a user interface element to quickly restrict results to the country derived from the IP address. Therefore another explanation could be that the user was using a VPN with a US IP address or e.g. Orbot (a Tor proxy).

**Question**: Should Focus indeed append locale parameters to the search queries? This may impact privacy for users that don't use the predominant locale in their country (which can be, see above, often derived from the user's IP address).
