### ISSUE TITLE
[A11y] "ADD" button is spelled A-D-D

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2945]
## Steps to reproduce
1. Activate TalkBack.
2. Open a webpage.
3. Open the menu and select "Add to home screen".
4. Tap the "Add" button.

### Expected behavior
The button label is read correctly as one word "Add".

### Actual behavior
The button label is spelled "A-D-D".

### Device information
* Android device: 
LG Nexus 5 (Android 6.0.1)
Google Pixel (Android P beta)
* Focus version: 6.3

**Comment by abhay222** [comment]
I have fixed this issue and submitted a pull request.
