### ISSUE TITLE
[A11y] Settings menu, the title doesn't say "menu" or "list"

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2947]
## Steps to reproduce
1. Activate TalkBack.
2. Open a webpage.
3. Open the main menu.
4. Open the Settings menu.

### Expected behavior
The Settings menu title should also say that it's a "menu" or "list".

### Actual behavior
The reader says the "Settings" title only.

### Device information

* Android device: 
LG Nexus 5 (Android 6.0.1)
Google Pixel (Android P beta)
* Focus version: 6.3

**Comment by abhay222** [comment]
I would like to work on it

**Comment by ekager** [comment]
Go for it, @Gyanesha !

**Comment by Gyanesha** [comment]
I am enable to interpret this. The reader should say  "Setting menu" or is it something else?
In the description is the main menu  settings menu ?

**Comment by sv-ohorvath** [comment]
Hi Gyanesha,
When you open the Settings menu (shown in the screenshot), TalkBack should read "Settings menu" (or what you think it's best). Currently, it only says "Settings".
![screenshot_20180730-103054](https://user-images.githubusercontent.com/4037709/43383570-15634d00-93e4-11e8-9de5-2badaa8accbf.png)

**Comment by levimatheri** [comment]
Is it really necessary to change it to Settings menu?

**Comment by nish-d** [comment]
Hey, I'd like to work on this.

**Comment by ilayaraja97** [comment]
Hello!
I tried looking into how to add the extra description. What I found out was by labeling UI elements with a content-description (https://developer.android.com/guide/topics/ui/accessibility/apps).
But this property isn't there for activities, it's there for MenuItems (https://developer.android.com/reference/android/view/View#setContentDescription%28java.lang.CharSequence%29).
According to me, there are 2 possible fixes:
1. Change the "Settings" tilte
2. Add the content-description property in the context menu before going to Settings Activity.
Besides I think the context menu lacks more description in terms of TalkBack. I will file an issue and try to fix it as well.

**Comment by vvengers** [comment]
Hey, I just looked what I could do. I created this result:

![screenshot aug 17 2018 18_11_01](https://user-images.githubusercontent.com/18068208/44276895-3fb5ee00-a249-11e8-8449-4bc1b0c96456.jpg)

**Comment by ilayaraja97** [comment]
@vvengers Please no, "Settings menu" is a poor workaround for "Settings" imo. Can't we do something which doesn't change the experience of all the other users?

It is still debatable if "Settings menu" is okay for the majority of users. Sometimes we need to help the ones in need huh?

**Comment by levimatheri** [comment]
@ilayaraja97 I agree. I don't see the need to change the label to Settings menu. Maybe there's an option to try AccessibilityAction because contentDescription won't fix it

**Comment by vvengers** [comment]
@ilayaraja97 Sure, what do you suggest?

**Comment by ilayaraja97** [comment]
@vvengers As I said it is not an easy question to answer. But I think what you did is correct. It's okay to let everyone see "Settings Menu" which is a very small inconvenience to most so that the people who really need UX are greatly benefited by this move. Till an `AccessibilityAction` type fix would be done.

**Comment by colintheshots** [comment]
Should we consider a subtitle instead possibly? It seems like the best compromise here.

**Comment by vesta0** [comment]
@eeejay could you please take a look at this issue and advise?

**Comment by Chinmay-KB** [comment]
I would like to work on this. I think I have found a workaround.
What if I type in Settings Menu, but just selectively change the color of "menu" to same as that of background color? I've done that in a TextView before, i'll try it if it's possible here. That way Talkback still reads it as "Settings menu"

**Comment by eeejay** [comment]
I don't think this is a bug. The settings UI is a full screen section, not a "menu". TalkBack has some counter-intuitive ideas of when to present semantic/role information to users. In full screen UIs, it will simply announce the title of the pane.

A dropdown menu in Android (for example, when you press the "more options" meatball button), is announces as "popup window". This is done correctly in Focus.

The best way to check if these kinds of issues are bugs or not is to open a Google app and see what it says[1]. In this case, I opened Chrome, and they have a very similar STR to get to a "Settings" screen. It was announced in the same way that it is currently done in Focus.

1. There are plenty of accessibility issues with Google apps, so I would still take anything you learn from their apps with a grain of salt. But in this instance, I think not giving semantic information is correct.

**Comment by ekager** [comment]
Thanks @eeejay for your comment and investigation! :)
Closing this issue.
