### ISSUE TITLE
UI tests for "Gecko X86" builds fail with missing APK error

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2953]
Gecko X86:

> Uploading [app/build/outputs/apk/klarGeckoX86/debug/app-klar-gecko-x86-debug.apk] to Firebase Test Lab...
ERROR: (gcloud.firebase.test.android.run) [app/build/outputs/apk/klarGeckoX86/debug/app-klar-gecko-x86-debug.apk] not found or not accessible

https://tools.taskcluster.net/groups/T6TLRUMYQUGPS91KoXow0g/tasks/UIv3jHO9Te64aAIqCsyxIA/runs/0/logs/public%2Flogs%2Flive.log

**Comment by pocmo** [comment]
@npark-mozilla @colintheshots

**Comment by kfontecilla** [comment]
@npark-mozilla Could you please double-check and close if fixed?
