### ISSUE TITLE
URL bar retains formatting of pasted text

### ISSUE THREAD

**Issue by callahad** [mozilla-mobile/focus-android#2954]
## Steps to reproduce

1. In Chrome, visit https://example.com
2. Copy the text on the page, including the header
3. Open Focus
4. Paste into the URL bar

### Expected behavior

* Text is entered as plain text

### Actual behavior

* Pasted text retains most styling, or at least text sizing, italics, weight, underlines, etc.

### Device information

* Android device: Pixel
* Focus version: At least 4.2 through 6.3.

### Other Notes

* The same thing happens with copying and pasting a URLs. The pasted URL is colored purple and underlined even within the URL bar.

### Screenshots

![screenshot_20180723-115940](https://user-images.githubusercontent.com/24193/43074112-0e31eee4-8e74-11e8-9e03-2d31bc57a7cd.png)
![screenshot_20180723-121611](https://user-images.githubusercontent.com/24193/43074113-0e5060ae-8e74-11e8-9ab3-da21aa4110e0.png)

**Comment by pocmo** [comment]
This looks like a duplicate of #1346.

**Comment by callahad** [comment]
Agreed, closing
