### ISSUE TITLE
Context Menu rounded edge regression

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2961]
Introduced by #2686. The rounded edges of the context menu look strange with the download warning underneath. @brampitoyo what would you like to happen here?
![screenshot_20180723-151249](https://user-images.githubusercontent.com/25442310/43105810-18f8a374-8e8b-11e8-9a53-35882e2ed02f.png)

**Comment by KrzysztofBarszcz** [comment]
Hi, I would like to work on it :)

**Comment by ekager** [comment]
Go for it @KrzysztofBarszcz !

**Comment by ekager** [comment]
Hey @KrzysztofBarszcz can you tell us if you're planning on working on this, so we can reassign it otherwise? 
Thanks!

**Comment by KrzysztofBarszcz** [comment]
@ekager I should finish it in less than two hours :)
