### ISSUE TITLE
Just-in time information – Tracking Protection

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2964]
Per https://github.com/mozilla-mobile/focus-android/issues/2816#issuecomment-407289032

![tracking-protection 2x](https://user-images.githubusercontent.com/51007/43119884-4f6defea-8f6c-11e8-8e53-a874702ec45b.png)

**Comment by bbinto** [comment]
@brampitoyo UX finalized? Ready for eng breakdown?

**Comment by sblatz** [comment]
@BrianNJones @brampitoyo Am I okay to move forward with the string "Turn off to fix some sites"?

**Comment by BrianNJones** [comment]
An issue here is that we're trying to provide a general message for a specific instance of a site hiccup. Let's go with:
Turning off may fix some site problems.

(Too long?)

**Comment by brampitoyo** [comment]
@BrianNJones @sblatz I don’t mind using a longer string, because the text can wrap to the next line.

**Comment by BrianNJones** [comment]
@brampitoyo @sblatz , let's go with:
Turning this off may fix some site problems

**Comment by BrianNJones** [comment]
@brampitoyo @sblatz , let's go with:
Turning this off may fix sites that are behaving unexpectedly

**Comment by sblatz** [comment]
@brampitoyo could I get the full spec on this? Namely: it appears that the Trackers Blocked menu item is larger in height than its current size of 64. What size would you like it to be? Also, should the "378" be centered vertically in the image above (if not, what should the padding be?)

**Comment by brampitoyo** [comment]
<img width="320" src="https://user-images.githubusercontent.com/51007/45125557-20184280-b1c3-11e8-8ecd-c526a88984d2.png">

@sblatz 

> It appears that the Trackers Blocked menu item is larger in height than its current size of 64. What size would you like it to be?

The height should be 88dp

As far as paddings go, it’s specced out in the image, but I follow Material Design’s specs for [three-line item](https://material.io/design/components/lists.html#specs).

I would prefer not to stretch the description to 3 lines, if possible (cc @BrianNJones). After all, this is for a menu item that generally doesn’t have any subtitle underneath.

But if it can’t be avoided, perhaps we can increase the width of the menu instead, to accommodate the text?


> What text size should the subtitle be (I have it at 12 right now)?
> What color should the subtitle be?

The subtitle text should have a size of 14dp, and have a color of `grey-10` 60%.

If you prefer a flat colour value, it’s `#aaabb6`.

**Comment by sblatz** [comment]
@BrianNJones, @brampitoyo here's a look at what we're able to get with a slightly shorter string. Let me know if this string (or something similarly short) would be acceptable!

<img width="300" alt="screen shot 2018-09-06 at 5 47 14 pm" src="https://user-images.githubusercontent.com/4400286/45186894-05fb5600-b1fd-11e8-8de3-6373eccf5406.png">

**Comment by BrianNJones** [comment]
Works for me, @sblatz @brampitoyo .

**Comment by brampitoyo** [comment]
Thanks for going over the issue with me last week, @sblatz. And thanks for your confirmation, @BrianNJones!
