### ISSUE TITLE
One-tap action – Open Link in New Tab

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2965]
Per https://github.com/mozilla-mobile/focus-android/issues/2816#issuecomment-407289032

![open-link-in-new-tab 2x](https://user-images.githubusercontent.com/51007/43119926-7ce5a076-8f6c-11e8-8fac-20cf3701e284.png)

**Comment by ekager** [comment]
I think the "Just Once" and "Always" are a bit confusing it makes it seem like this is changing a setting to always open links in a new tab. It's not right?

**Comment by pocmo** [comment]
I wonder if we can intercept link clicks. Usually the engine handles those.

**Comment by brampitoyo** [comment]
@pocmo Yes. The idea with this is to ‘hijack’ the link-tap action and present a context menu, but I’m aware that it’s a totally non-standard behaviour (although it exposes a potentially useful feature).


@ekager I was thinking that we would make it possible for users to always open links in a new tab by default. Maybe some people would find it useful? So, yes, this gives users a hint on how to access the feature, but it also allows them to change the browser behaviour if they like to.

As a consequence, we’ll need a settings menu item to control it (maybe something like “Always open links in new tabs”?).

And when this is your default, how do you open links in the current tab? Long-press a link, and we’ll show a menu item called “Open link”.

Maybe I’m going overkill here, though?

**Comment by ekager** [comment]
We know roughly when a link is clicked because we have a user triggered flag when the URL changes. 

As for the second question, I'm not sure this is really a desired feature to have every link you click open in a new tab?

**Comment by jashgala** [comment]
@brampitoyo 
Does this also come with the capability to change this behavior at a later point in time? 
For example, if I select Always at the beginning and decide to change it to the original setting, what will be the user flow for that?

**Comment by brampitoyo** [comment]
@jashgala 

> For example, if I select Always at the beginning and decide to change it to the original setting, what will be the user flow for that?

I was planning on having a new setting menu item. Something along this line:

> **Open links in**
> [ ] Current tab
> [ ] New tabs
> [x] Always ask

We would default to “Always ask”. This way, all users would get this dialogue the first time they tap on a link, and get to choose a default behaviour that would fit their workflow best.

In this dialogue:
* If you choose “Open link in new tab” and tap “Always”, then the setting would flip to “New tabs”.
* If you choose “Open link” and tap “Always”, then setting would flip to “Current tab”.
* Whatever your choice, if you tap “Just once”, then the setting would remain “Always ask”.

But @ekager was absolutely right. It seems like invoking this dialogue would require us to intercept URL change, and that sounds really hacky and prone to bugs! Furthermore, no other browser does this, so we have no precedent to draw from.
