### ISSUE TITLE
One-tap action – Add Custom URL

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2966]
Per https://github.com/mozilla-mobile/focus-android/issues/2816#issuecomment-407289032

![add-custom-url 2x](https://user-images.githubusercontent.com/51007/43119952-94534e98-8f6c-11e8-8bf7-5e95e6fced4a.png)

**Comment by bbinto** [comment]
Is this the finalized breakdown of 7.0 in-app tips, @brampitoyo?

**Comment by brampitoyo** [comment]
Yes. This is the finalised breakdown for the Add Custom URL one-tap action – which is not a tip, but still achieves the same objective: expose less common features.

**Comment by boek** [comment]
@brampitoyo I finished this and @ekager brought up a couple of good points.

To someone who isn't sure what autocomplete is the wording here isn't totally clear what will happen if I tap this button. Also now that we added the link glyph to search suggestions the glyph here seems a little out of place.

Maybe using the add glyph with the string `Add Autocomplete: ...`?

**Comment by brampitoyo** [comment]
@boek @ekager Good points!

> …the wording here isn't totally clear what will happen if I tap this button.
> …the glyph here seems a little out of place.

Autocomplete was a feature that we designed because bookmarking is too visible and not private enough. But it was always meant as another means to access bookmarks.

So why don’t we reinforce the close relationship between adding custom URL and bookmarking?

First, we can use the bookmark outline glyph. Then, we can reword the string slightly – `Add link to autocomplete` – without repeating the link the second time.

<img width="360" src="https://user-images.githubusercontent.com/51007/45793100-9ac57f80-bce4-11e8-9adc-2fb1040ffc18.png">

This changes the analogy from “add a link to a list” to “add a favorite link that you want to be autocompleted”.

Asset: [bookmark-outline-24.svg](https://cl.ly/76c6a34964c5/bookmark-outline-24.svg)

**Comment by vesta0** [comment]
@brampitoyo I like your proposed changes and I think calling it "My URLs" is much more clear for the user. A couple of thoughts if we are to update the settings page:

-Instead of "Default" URL list would it be more accurate to call it something like "Common/Popular/Frequent" URLs? The top URL list is not enabled by default.
-Would it be more clear to change the "My URL List" heading to "Enable My URL List"? In a quick glance, the difference between "My URL List" and "My URLs" may not be obvious to the user.

Let me know what you think.

**Comment by boek** [comment]
@vesta0 I agree with both of your points. I will pull this out into another issue 👍

**Comment by brampitoyo** [comment]
Good points, @vesta0! @boek I’ve filed #3467 to rename the list items. Please put your thoughts there.
