### ISSUE TITLE
With the new Build Variant naming, UI tests in AndroidTestWebview is no longer detected

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2973]
In android studio, only the tests inside the AndroidTest folder is detected.  with the Webview naming gone, those tests that are specific to Webview variant is not selected.

@colintheshots , what would be the best way to handle this?

**Comment by npark-mozilla** [comment]
one option would be to move everything inside AndroidTest and somehow check the renderer inside each UI test script, wondering whether there are any other convenient ways to do this.

**Comment by colintheshots** [comment]
You can check the current renderer with AppConstants.isGeckoBuild().

**Comment by npark-mozilla** [comment]
I think moving everything to AndroidTest is a good idea. but here is the problem that we need to solve.  We need to run test suite against Focus Geckoview and Webviews build separately. Currently, this is done by submitting different build variant ( __Gecko___ vs __WebVIew___ ) apk to Google Firebase, and runs same ui test set.  Gecko apk will run tests only in AndroidTest, and Webview apk will run tests in AndroidTest and AndroidTestWebview folder.  

With that distinction gone, I need a new way of differentiating Geckoview test run vs. webview test run.  I guess one of the option is to upload klar, and in ui test, if it is klar, I can set the renderer to geckoview with shared pref, and put a check for renderer type on every script. 

The other way would be to duplicate the tests for geckoview, make sure to change the renderer type to geckoview on those tests, and run everything in one apk, but I wouldn't prefer this because it'll make individual test run twice as long, and makes debugging via video recording that much difficult. Then there's that problem of breaking the test when the renderer is changed as you mention.

@colintheshots what do you think?
