### ISSUE TITLE
Task 'assembleKlarArmNightlyAndroidTest' and 'assembleKlarX86NightlyAndroidTest' not found in root project 'focus-android'.

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2974]
UI Test submission to Google Testcloud fails, because above two build variants do not exist.

Currently, available compilation for AndroidTest are:
connectedKlarAarch64DebugAndroidTest
connectedKlarArmDebugAndroidTest
connectedKlarX86DebugAndroidTest

Since they are only available in debug mode.  Since Debug build has webview by default, we won't be able to test Geckoview it seems.  

@colintheshots need your help on this one as well.

**Comment by colintheshots** [comment]
There's two options. We can either create tests that set the rendering engine shared preference before starting the app or I can set a build property to alter the testBuildType.

**Comment by npark-mozilla** [comment]
Okay, I think the cleaner way is to check/set build variant on each test.  when #2973 is fixed, this will be fixed.

**Comment by kfontecilla** [comment]
#2973 is fixed. closing.
