### ISSUE TITLE
Nimbledroid upload is failing due to apk name change

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2976]
Currently klar geckoview upload to nimbledroid is failing because the apk name have been changed.

Just to double check, @colintheshots is FocusArmRelease in WV and KlarArmRelease in GV?  For nimbledroid, we need to submit apks with webview/geckoview set by default.

**Comment by npark-mozilla** [comment]
Parent bug: #2952

**Comment by colintheshots** [comment]
Nightly defaults to GeckoView, Debug to WebView, and Release to WebView. If you want release with GeckoView, you'll need to set a shared preference.

**Comment by npark-mozilla** [comment]
Is there a way to set the renderer with a compile flag?  The way nimbledroid takes api is that we upload the release apk, and the tests are run by treating the app as a black box.  (We have a separate test app that is set to interact with org.mozilla.klar / org.mozilla.focus app) So I don't think we can use shared pref, since the test does not belong to this repo. 

Other option may be that we can switch the build to Nightly instead of Release.

**Comment by npark-mozilla** [comment]
@bbinto Question here - so when the time comes, and Debug/Release is using GV by default, there wouldn't be a way for us to build Focus with WV as default (@colintheshots, am I understanding it correctly?) .  I guess when everything is set to GV, would there be still a need to do WV/GV comparison?  (because way it's setup now, that won't be possible)
