### ISSUE TITLE
Forward and Backward arrows problem in RTL on the Tablet

### ISSUE THREAD

**Issue by 5y** [mozilla-mobile/focus-android#298]
@arashm  @Mozillafa
@Delphine
Forward and Backward arrows problem in RTL on the Tablet [1] : 

Right arrow = > change icon to " >"
Left arrow =>  change icon to  " < "
result : " < " " > "

1- Nexus 7 , Android 6.01, Focus Persian:
![image](https://cloud.githubusercontent.com/assets/1941933/24070640/b1cb6f20-0bd6-11e7-805d-0982e2ac8e18.png)

Correct layout in Firefox for Android RTL in Persian language:

![image](https://cloud.githubusercontent.com/assets/1941933/24070921/8ef41c0e-0bdb-11e7-96a3-09fbe72acac9.png)

**Comment by pocmo** [comment]
Thanks for filing this! :)

We are trying to address all RTL issues in #31. Since you posted this to #31 too I'm going to close this issue here.
