### ISSUE TITLE
Taskcluster: Nightly: Create browsable index

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2980]
We have a taskcluster index that always points to the last Nightly build:
https://tools.taskcluster.net/index/project.mobile.focus.release/latest

Sometimes it would be nice (regression testing!) to get back to an old Nightly version. We keep those tasks around for a year but unfortunately it's impossible to find them.

We should follow what we do for mozilla-central. There's a **latest** index but also one that is browsable by date:
https://tools.taskcluster.net/index/gecko.v2.mozilla-central.nightly.2018

**Comment by kfontecilla** [comment]
@pocmo Is this for releng to do or developers?

**Comment by pocmo** [comment]
Potentially both. But no high priority.

**Comment by Rikk** [comment]
I think a difference in version number would be very welcome to differentiate nightly from stable/betas. The way it is now, Play Store and apk sites will overwrite release with nightly and vice-versa because versionCode only increments and version number stay the same.

**Comment by JohanLorenzo** [comment]
From https://github.com/mozilla-mobile/focus-android/issues/3175#issue-352481070: 

> While looking for the root cause of [bug 1484950](https://bugzilla.mozilla.org/show_bug.cgi?id=1484950),  I realized there is no easy way to look back at the graphs of the past nightlies. I worked around it by accessing the logs of the worker.
> 
> It would be great if we had more entries under: https://tools.taskcluster.net/index/project.mobile.focus.nightly . For instance Fennec nightlies have the following folders: https://tools.taskcluster.net/index/gecko.v2.mozilla-central.nightly.2018.08.20.revision (see nightly.2018.08.20.revision.$rev). 
> 
> A way to add these is to enhance the decision task with a new scope like: `queue:route:index.project.mobile.focus.nightly.2018.08.20.revision.$rev`. This is something that should happen on the hook https://tools.taskcluster.net/hooks/project-mobile/focus-nightly. This can be configured thanks to JSON-e and their time operator: https://taskcluster.github.io/json-e/#Language/time

**Comment by pocmo** [comment]
See #3175 for some hints from @JohanLorenzo about how to do that.

**Comment by mitchhentges** [comment]
@pocmo I'd like to resolve this if you don't mind assigning me

**Comment by mitchhentges** [comment]
Fixed by #4129
