### ISSUE TITLE
Add a URL shortner, would be helpfull

### ISSUE THREAD

**Issue by shikhart98** [mozilla-mobile/focus-android#2985]
### Why?
Helps when you want to share some URL with others too! 

### Where?
In option menu, inside URL bar.

**Comment by ekager** [comment]
Do you mean like #2127 ?

**Comment by pocmo** [comment]
Components issue: https://github.com/mozilla-mobile/android-components/issues/509

#2127 may be different.. that one is just about using the canonical URL for sharing. @shikhart98 Are you suggesting to use something like bit.ly here?

**Comment by pocmo** [comment]
@shikhart98 Are there specific use cases where a short URL is better?

This a third-party URL shortening service we'd share the URL with that service and that service would be able to see all visits. I'm not sure this fits Focus except there's some killer use case.

**Comment by shikhart98** [comment]
Yes, I saw that we are giving user an option to share the URL.   

![whatsapp image 2018-07-30 at 8 22 21 pm](https://user-images.githubusercontent.com/29306481/43405046-92b72284-9436-11e8-88f0-8f4dcadc4724.jpeg)  

Now if we just shorten the URL at that point! and allow user to share short and sweet URL rather than including all this crap, would be better.  

![whatsapp image 2018-07-30 at 8 22 21 pm 1](https://user-images.githubusercontent.com/29306481/43405062-9e796c6c-9436-11e8-83da-1a15f09d4ae7.jpeg)

**Comment by shikhart98** [comment]
Can I start working on it? or do some P1 issues.

**Comment by mathu97** [comment]
Can I work on this if nobody has started yet?
