### ISSUE TITLE
App Shortcut and Notification contains the same action

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2989]
Currently, Firefox Focus shows a very useful app shortcut on API level >25: Erase. This shortcut allows users to erase their browsing history in the background, without needing to open Firefox Focus.

<img width="360" src="https://user-images.githubusercontent.com/51007/43241169-14acb78c-90ee-11e8-8fde-87788d80f7cb.png">

Additionally, Focus also shows a permanent notification. When the notification itself is tapped, it performs an erase. This notification also contains two additional actions: Open, and Erase and Open.

<img width="360" src="https://user-images.githubusercontent.com/51007/43241153-fa3c3d1e-90ed-11e8-81dc-ff51290b5647.png">

But some versions of Android (I’m running 8.1) shows notifications _on the bottom_ of app shortcuts. As a result, we get an awkward doubling of functionality: two shortcuts that do the same thing, but are located in two different places and shown differently:

<img width="360" src="https://user-images.githubusercontent.com/51007/43241031-7da1b50e-90ed-11e8-8372-99b00877c95d.png">

I think we can do a few things to solve this doubling problem:

1. On API level >25, don’t show permanent notification at all. If the user wants to erase, they can use the app shortcut
2. On API level >25, when the app shortcut menu is invoked, our notification should be prevented from being displayed

I favour solution 2, as this gives users multiple ways to Erase from outside the app.

**Comment by sblatz** [comment]
I will investigate if this is possible. If it is, it will likely be a quick fix.

**Comment by sblatz** [comment]
After some research, it doesn't appear it's possible for us to monitor whether or not the long press menu is revealed or not on the launcher. We may have to move forward with option 1 if this doubling is an annoyance. 

cc: @colintheshots to confirm that this is the case.

**Comment by SubhrajyotiSen** [comment]
Is the app shortcut really necessary? In most apps/cases it is used to open the app to directly perform a certain action. 
On a normal usage scenario, I would have to find the Focus icon, long press on it and then click on the "Erase" app shortcut. It is much easier to do the same thing for the notification.

Could one possible way of dealing with this be removing the app shortcut and keeping the notification across all Android versions since the "Erase from notification" kind of behavior seems to be uniform across browsers?

**Comment by brampitoyo** [comment]
@SubhrajyotiSen If I recall correctly, we implemented “Erase from notification” because Android didn’t support app actions.

Furthermore, notifications are supposed to be highly contextual (ie. they should appear after a certain conditions have been met and can easily be dismissed), rather than appearing permanently. So our original use of the notification seems hacky.

**Comment by colintheshots** [comment]
When we say "some versions of Android," do they perfectly overlap all versions API 25 and up? If so, the app shortcut is always extraneous and never useful. It seems the app shortcut never should've been a static shortcut and we may need to even suppress creating it in certain cases.

Removing the notification is a non-starter. If we remove the notification then the Android OS creates its own notification saying "Firefox Focus is consuming battery." This clearly upsets users more than even having duplicate icons.

Removing the action from the notification also seems silly. Consider that most typical Android users still don't know that app shortcuts even exist. They're basically a power user feature today that is designed to shortcut things that might require browsing menus in the app. With the foreground notification on screen, I'm not sure there's ever an instance when the app shortcut is really valuable.

**Comment by SubhrajyotiSen** [comment]
I absolutely agree with @colintheshots

**Comment by brampitoyo** [comment]
@colintheshots @SubhrajyotiSen I agree that removing the notification would be overkill.

The main issue is that we have two “Erase” actions that appear in the Quick Launch menu: one is an action, and the other is a notification:

<img width="360" src="https://user-images.githubusercontent.com/51007/44320865-b98fe680-a498-11e8-8b17-89e2d29a9771.png">

Chrome Canary seems to be able to simultaneously show an Erase notification in the drawer (when you pull down), and suppress that notification in the app’s quick launch menu (when you long-press):

<img width="360" src="https://user-images.githubusercontent.com/51007/44320939-2905d600-a499-11e8-8953-3a612371c812.png">

I wonder if it’s worth it to try doing the same? Otherwise, is the right move to take out the Erase action – and when the user long-press, they will still see the Erase notification anyway?

(I should note that the Erase app action shows an “App isn’t installed” error, like @SubhrajyotiSen reported. Maybe getting app action right isn’t easy, that we should save it for future versions?)

**Comment by sblatz** [comment]
Sounds like @SubhrajyotiSen has more knowledge on this than I do. I'm going to un-assign, but feel free to loop me back in if you're having trouble!

**Comment by cgomezmendez** [comment]
Something you may want to consider, I'm not able access the shortcut option, only the notification one don't know if it is because I'm using a custom (popular) launcher (Nova Launcher).
