### ISSUE TITLE
Show (X) in URLInputFragment immediately after tapping on the URL bar

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#299]
STR:
1. Visit a page
2. Tap the URL bar
Expected: URL Input fragment, with an (X) button.
Actual: No (X) button, (X) only appears when you type and/or backspace.

Also, the padding needs fixing (@antlam has mocks)

**Comment by antlam** [comment]
![screen shot 2017-03-20 at 12 51 35 pm](https://cloud.githubusercontent.com/assets/1994820/24119060/2f6e6c7e-0d6d-11e7-97b5-48aaf5b95098.png)
![url active - mdpi](https://cloud.githubusercontent.com/assets/1994820/24119059/2f6859c4-0d6d-11e7-83a9-21672fdcaa16.png)

**Comment by ahunt** [comment]
Antlam also wanted to remove the fading for the (left-side of the) highlight from the following case:
![long3](https://cloud.githubusercontent.com/assets/1546915/24124737/66e731bc-0d82-11e7-9b8f-650289a19638.png)

Doing this would probably need us to reimplement our own fading, AFAICS Android fades the edge of the entire view (so we'd instead need to draw text and highlight ourselves, and fade only the text) - so probably won't be part of this bug.

**Comment by pocmo** [comment]
> Doing this would probably need us to reimplement our own fading, AFAICS Android fades the edge of the entire view (so we'd instead need to draw text and highlight ourselves, and fade only the text) - so probably won't be part of this bug.

Yeah, let's not start to fight the Android system/implementation in the last days.

**Comment by pocmo** [comment]
I landed the patches from #299 to work on the animation.
