### ISSUE TITLE
Add new app shortcut icon – Erase & Open

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2991]
Would it be helpful to add a new app shortcut icon that can complement “Erase”, and allow users to erase their browsing history and then open Focus?

We already have “Erase & Open” as one of the actions in our notification shade.

**Comment by Hackertronix** [comment]
Hi @brampitoyo an app shortcut would be a great addition, if this is approved I would like to work on it :)

**Comment by brampitoyo** [comment]
Thanks, @Hackertronix! If you think that you can fix this issue easily (we already have an app shortcut for “Erase”), it feels as if you can get started on this already. But just to be safe, let’s wait for the issue to get triaged.

**Comment by Hackertronix** [comment]
Thanks @brampitoyo is that build live in production because my latest installation does not show any app shortcuts currently (except for the default "Uninstall" and "App Info")

**Comment by brampitoyo** [comment]
@Hackertronix It appears in my build (nightly). But I do recall that this action also appears in the release (production) build:

<img width="360" src="https://user-images.githubusercontent.com/51007/43429045-7a005d4e-94b5-11e8-8c24-c39ca479146c.png">

**Comment by Hackertronix** [comment]
I am on v6.0 and it's definitely not there 

![screenshot_20180731-095929](https://user-images.githubusercontent.com/5685314/43437900-f4d83922-94a8-11e8-8cc7-456b3dd38cf7.png)

**Comment by SubhrajyotiSen** [comment]
@Hackertronix You need to update to 6.3 nightly
