### ISSUE TITLE
Home screen shortcut does not use site favicon

### ISSUE THREAD

**Issue by nkestrel** [mozilla-mobile/focus-android#2992]
Blocks #833

The Home screen shortcut icon always uses the initial letter of the site and not the site favicon. 

![focus-homescreen-icon](https://user-images.githubusercontent.com/9861435/43259286-1f241c88-90c5-11e8-851f-5d939042a537.jpg)

https://github.com/mozilla-mobile/focus-android/issues/833#issuecomment-317910664 appears to show it working back in July 2017.

Affected:
Focus 6.3 Build #222061208 on Android 8.0.0
Focus 6.3 Build #121961205 on Android 5.1.1

**Comment by bbinto** [comment]
@brampitoyo to comment

**Comment by ekager** [comment]
@bbinto , not a regression, we took out the favicon for either discretion or consistent icon quality, I can't quite remember. Maybe @pocmo remembers. Closing for now, reopen if we want to readdress this.

**Comment by brampitoyo** [comment]
Adding a home screen shortcut is a risky move. It means that anybody who has access to the phone can tap on the shortcut and find out where the link leads to.

By obscuring the favicon and letting users rename the shortcut, we give them the ability to have a discreet way to open their favourite sites.

**Comment by yoasif** [comment]
>Adding a home screen shortcut is a risky move. It means that anybody who has access to the phone can tap on the shortcut and find out where the link leads to.

Could this not be mitigated by  #2712? That is, if a user clicks on a shortcut, they are prompted with a bio metric prompt to open it. 

> By obscuring the favicon and letting users rename the shortcut, we give them the ability to have a discreet way to open their favourite sites.

You could also add a checkbox (checked by default) to the add shortcut dialog that allows the user to use the discovered favicon, or if unchecked, to use a generic icon. 

For what it is worth, for the obscuring shortcut use case, Focus today automatically uses the first letter of the site, so it's not even as obscured as it would be -- I could shortcut Google News and name the shortcut "Slickdeals", but the icon will not show an "S". If this is a use case that you are thinking of in this way, perhaps Focus could use the first letter of the shortcut name in the icon?

**Comment by nkestrel** [comment]
Putting a shortcut on the home screen is already sacrificing privacy for convenience. If the user is concerned by the icons they can put them in a more discrete location, relying on obfuscation is not going to be very effective. On Android 8.0 they are clearly marked as app shortcuts for a privacy-focused browser, have a suspicious lack of icon and a name that may not correspond with the first letter of the domain in the icon.

Shortcuts are meant to be convenient and accessible but without icons they are much less useful, making it harder to find what you want and easy to open the wrong one by mistake which is especially bad in a privacy-minded context. The icon could be made optional if obfuscation is considered an important feature.

**Comment by brampitoyo** [comment]
> Could this not be mitigated by #2712? That is, if a user clicks on a shortcut, they are prompted with a bio metric prompt to open it.

This is a really interesting idea.

Combined with:

> […] perhaps Focus could use the first letter of the shortcut name in the icon?

It would give our users the ability to have shortcuts that are obscured in two ways:

1. Visually. The shortcut icon doesn’t give you any hint of the website, as long as you choose your name wisely.
2. Functionally. If you try and open a shortcut, Firefox Focus will prompt for a biometric verification, as long as you have set it up.

@nkestrel I’m curious about what you think of this idea? Does it address some of the problems you’ve raised?

**Comment by tobz1000** [comment]
Just to say I also much prefer the favicon to the first-character icon. In my use case, I'm not concerned about people finding out about my bookmarked home pages.

Having the option to choose between character and favicon would be best.

**Comment by huuhaa** [comment]
As silly as it sounds, this is actually one of reasons I use Brave for that purpose, Sure other would be ability to remember selected theme (I use night theme at twitter) & login information.. But those are offtopic in this case and also security risk if you think it that way (unless combined with that opened when biometric sensor is used).
