### ISSUE TITLE
Can't copy the URL address of the current search.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/focus-android#2994]
A long tap just gives the option to add a custom url. And a short tap doesn't show the URL for copying.

**Comment by ekager** [comment]
This is a feature we added to be able to quickly change your search in the URL bar. What is your reasoning for needing to copy a search URL? You could also select "Share" from the menu to share the search URL.

**Comment by boek** [comment]
@bbinto this could be fixed with #2885 as well
