### ISSUE TITLE
Firefox Focus 6.3 is not using Gboard Private Mode for the find in page feature.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/focus-android#2995]
![screenshot_20180726-124511_firefox focus](https://user-images.githubusercontent.com/32398857/43273272-6c075f26-90d2-11e8-901f-032b1f7ea9ed.jpg)

**Comment by KwanEsq** [comment]
Possibly just adding [`android:imeOptions="flagNoPersonalizedLearning"`](https://developer.android.com/reference/android/widget/TextView#attr_android:imeOptions) to:
https://github.com/mozilla-mobile/focus-android/blob/4db78eb93364637087a10c72737107677b7ab75d/app/src/main/res/layout/find_in_page.xml#L16-L31
would be enough to fix this.
