### ISSUE TITLE
Custom Tab UX When Trashing the Session Is Confusing

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/focus-android#2996]
## Steps to reproduce
Open Firefox Focus normally.
Open some tabs.
Click on a link in another app to open a custom tab.
Press Back to return to your previous app.

### Expected behavior
The custom tab should clean up the custom tab silently and return to your previous app.

### Actual behavior
The screen flashes to the pink, empty browser background briefly and the Toast says "Your browsing history has been erased." Then it return to the previous app. The UX seems to imply that it lost all your other tabs that had been open. However, the previous session is still open in recent tasks.

**Comment by ekager** [comment]
@brampitoyo while this isn't a "bug" and probably isn't highest priority right now, feel free to take a look and offer some suggestions for improvement :)

**Comment by brampitoyo** [comment]
@colintheshots @ekager While the erase confirmation message is important to assure users that Focus doesn’t retain data (that’s the whole point of setting Focus as a default browser), the message is also somewhat inaccurate, because it implies that “your browsing history” means _both_ the history of the custom tab, and the history of the app.

Instead, what we may want to say is something along these lines:

> This tab’s browsing history has been erased

This clarifies that only the custom tab’s browsing history was erased, and imply that the app’s browsing history remains intact and open.

Thoughts?

**Comment by colintheshots** [comment]
Showing the pink background is part of the problem, since it visually implies everything was trashed.

The fundamental issue is the confusion, so a better message might help. Of course, it appears as a Toast, so it won't appear for long. It won't appear at all if the user disabled notifications from our app, which is better than suggesting that both sessions were trashed.

**Comment by colintheshots** [comment]
I would go with #1. Android won't really let us hijack back presses for very long. In Android P, anything that freezes the UI thread also crashes. I'm not sure how we'd stop Android from continuing back if it was even desirable behavior.

**Comment by ekager** [comment]
I was able to remove the pink flash and updating the snackbar string is simple, but the provided string above, "This tab’s browsing history has been erased" doesn't quite fit in 1 line and looks a bit strange. I suppose other languages would have length issues as well, but I tried "Tab's browsing history has been erased." and it works for English in 1 line. @brampitoyo and @BrianNJones for string feedback

<img width="432" alt="screen shot 2018-09-14 at 1 02 50 pm" src="https://user-images.githubusercontent.com/25442310/45572599-871aa480-b81e-11e8-8271-b2ae47e36ea6.png">
<img width="430" alt="screen shot 2018-09-14 at 1 03 00 pm" src="https://user-images.githubusercontent.com/25442310/45572600-87b33b00-b81e-11e8-80e1-2176b0481374.png">
