### ISSUE TITLE
Add "Search for ***" hint when entering text

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#30]

**Comment by antlam** [comment]
<img width="394" alt="screen shot 2017-02-16 at 4 36 39 pm" src="https://cloud.githubusercontent.com/assets/1994820/23047670/1e0b0868-f466-11e6-8b23-1a16b31f7113.png">

Still thinking about issue #39 so I've left out that part of the UI for the time being.

**Comment by antlam** [comment]
Font size is Roboto 14sp and the bold part is just bold :)
