### ISSUE TITLE
Add to Home screen doesn't work on Chrome OS

### ISSUE THREAD

**Issue by g-van-vreckem** [mozilla-mobile/focus-android#3001]
## Steps to reproduce
Visit any Site with Firefox focus, In the menu click on "Add to Home screen", click Add
### Expected behavior
See an "App shortcut" added to the Launcher, optionally pinned to the shelf (same as chrome create shortcut).
### Actual behavior
Nothing happen.
### Device information

* Android device:
Acer Chromebook 14 (CB3-431) (Nougat 7.1.1)
* Focus version:
6.0 (build #21861909)

**Comment by lobontiumira** [comment]
@g-van-vreckem tahnks for the report!
Is this issue still reproducing on your device?
