### ISSUE TITLE
 URL spoofing on location change/stop

### ISSUE THREAD

**Issue by thebnich** [mozilla-mobile/focus-android#301]
https://people-mozilla.org/~bnicholson/test/ios-security-test.html

[See here](https://github.com/mozilla-mobile/focus/commit/ed7c9a8) for the iOS fix.

**Comment by ahunt** [comment]
I've got a provisional patch which seems to do a similar thing. I'm going to spend a bit more time to figure out if there are any possible workarounds for my fix, but it seems like it's a robust fix.
