### ISSUE TITLE
GV Find in Page Highlight does not clear when exit find in page

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3012]
## Steps to reproduce
1. Open Find in Page
2. Search for word
3. Close find in page

### Expected behavior
Highlight disappears 

### Actual behavior
Highlight remains

### Device information

* Android device: Pixel 2
* Focus version: Nightly - GV beta 11

**Comment by ekager** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1479536
Not a RB IMO

**Comment by bbinto** [comment]
@rpappalax to confirm it's fixed
