### ISSUE TITLE
Find in page: does not open keyboard automatically

### ISSUE THREAD

**Issue by dennisguse** [mozilla-mobile/focus-android#3013]
## Steps to reproduce
1. Load a web page
2. Select find in page in menu
3. Find in page opens

### Expected behavior
The find in page text field opens and the keyboard opens as well.

### Actual behavior
Only the find in page text field opens.
Cursor focuses the text field, but the keyboard does not open.
Need to manually give focus to the text field.

### Device information

* Android device: XT1039 LineageOS 7.1.2
* Focus version: 6.0 BUILD #21842054 (from GITHUB)

* Android device: Google Pixel 2
* Focus version: (KLAR) 6.0 BUILD 21861909

**Comment by Hackertronix** [comment]
Hey @dennisguse , I would like to give it a shot
