### ISSUE TITLE
Missing placeholders in pa-IN

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#3014]
https://tools.taskcluster.net/groups/VT_hP3DDQuOuZ9xy4RMB8w/tasks/VT_hP3DDQuOuZ9xy4RMB8w/runs/0/logs/public%2Flogs%2Flive.log

```
Error: * [values-pa-rIN/strings.xml] missing placeholder in translation, key: about_content
Error: * [values-pa-rIN/strings.xml] missing placeholder in translation, key: about_content
```

CC @Delphine

**Comment by Delphine** [comment]
I've invalidated the string in Pontoon so hopefully this should be ok. Gonna contact localizers again to fix this

**Comment by Delphine** [comment]
this has been fixed by localizers, so I hope it's good on your side too now :)

**Comment by pocmo** [comment]
Yes, this seems to work again!
