### ISSUE TITLE
Find in page next/previous arrows are hard to tap

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3019]
## Steps to reproduce
- Open find in page
- Search for something with multiple results
- Try to hit up and down arrows

### Expected behavior
Work pretty well

### Actual behavior
Hard to hit arrows. I think the hit boxes don't extend *below* the views (so clicking between the arrow and the system navigation bar, back forward etc., is no-op).

### Device information

* Android device: Pixel 2, Android 8.1
* Focus version: 6.0 Klar, no gecko

**Comment by ekager** [comment]
Hey @boek do you want to take another look at these buttons?

**Comment by bbinto** [comment]
Is this a @boek issue or @bram issue? Either way, please confirm t-shirt size if possible and move to backlog, I could see this as a P2 - P3

**Comment by boek** [comment]
@ekager I'll take it

**Comment by brampitoyo** [comment]
@boek If it helps, I can regenerate the up and down arrow icons so that they occupy a 24x24dp space. This might make them an easier tap target. What do you think?

**Comment by ekager** [comment]
That'd be great @brampitoyo , could we try that?

**Comment by mcomella** [comment]
Touch target size guidelines from Google (
https://support.google.com/accessibility/android/answer/7101858?hl=en):

> Touch targets include the area that responds to user input. Touch targets
> extend beyond the visual bounds of an element: An element like an icon may
> appear to be 24x24dp but the padding surrounding it comprises the full
> 48x48dp touch target.


*Consider making touch targets at least 48x48dp,* separated by 8dp of space
> or more, to ensure balanced information density and usability. A touch
> target of 48x48dp results in a physical size of about 9mm, regardless of
> screen size. *The recommended target size for touchscreen objects is
> 7-10mm.*
>

24x24dp seems small but keep in mind we can make larger touch targets
around it.

**Comment by brampitoyo** [comment]
Here are the frame-fitted icons:

* [arrowhead-down.svg](http://f.cl.ly/items/0w0U051Z3X0Y1D2x2T1s/Arrowhead%20Down.svg)
* [arrowhead-up.svg](http://f.cl.ly/items/3j0l0u3x0j3R2y3P1g3E/Arrowhead%20Up.svg)

**Comment by ekager** [comment]
Hey @brampitoyo following what Mike posted above, would you be opposed to making the icons slightly larger and further apart in the design for find in page? So the new icons imported and set the image buttons to 48x48dp

**Comment by ekager** [comment]
Image Buttons set to 48x48 with 8dp end margin.
 ![screenshot_20180813-164958](https://user-images.githubusercontent.com/25442310/44064282-11e37e4e-9f19-11e8-9294-4c2a776dfb6c.png)

**Comment by brampitoyo** [comment]
> Image Buttons set to 48x48 with 8dp end margin.

I agree with this idea. It will ensure that our tap targets matches the recommended touch targets of 48x48 dp.

The only thing left to spec the margin between the icon and the number of results, which should be 16dp on both sides. (Having a left margin would ensure that any long search query won’t run into the number of results – although it’s unlikely that the user would want to search for a very long query in the first place).

<img width="360" src="https://user-images.githubusercontent.com/51007/44071205-dfce33f4-9fdb-11e8-808b-b282d019cf14.png">
