### ISSUE TITLE
Context menu for links

### ISSUE THREAD

**Issue by thebnich** [mozilla-mobile/focus-android#303]
Didn't see this filed anywhere, so apologies if it's a dupe.

We should show a context menu when long-pressing a link. For reference, Focus iOS has Open/Add to Reading List/Copy/Share.

**Comment by pocmo** [comment]
In triage we decided to show a share sheet when long pressing links (v1). With that we do not need new strings now.

**Comment by ahunt** [comment]
We can actually detect when we're long-pressing emails, images, phone numbers:
https://developer.android.com/reference/android/webkit/WebView.HitTestResult.html

I'm guessing we only really care about links for now (which is what I've done in the initial patch)?

**Comment by pocmo** [comment]
> I'm guessing we only really care about links for now (which is what I've done in the initial patch)?

Yeah, but let's file separate issues for the other types. I guess we could hook them up to launch Intents too. But for that we might need a confirmation dialog and strings again.

**Comment by ahunt** [comment]
> Yeah, but let's file separate issues for the other types. I guess we could hook them up to launch Intents too. But for that we might need a confirmation dialog and strings again.

Filed #330 for that.
