### ISSUE TITLE
Redesign menu & dialog – Add to Home screen

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3035]
#### Old

<img width="360" src="https://user-images.githubusercontent.com/51007/43493063-19bffc02-9580-11e8-9c5c-5c69d565409a.png">

#### New

<img width="360" src="https://user-images.githubusercontent.com/51007/43754724-5f0005ca-9a60-11e8-889b-98f99c430611.png">

#### Spec

<img width="360" src="https://user-images.githubusercontent.com/51007/43754696-40f95c0c-9a60-11e8-97d5-82381e809b39.png">

<img width="360" src="https://user-images.githubusercontent.com/51007/43754629-ecf3da42-9a5f-11e8-99ce-6e06a45fd371.png">

**Comment by brampitoyo** [comment]
For the most part, the measurement of this dialogue (and dialogues in general) are the same. Colour values are what’s mostly changed.

**Comment by KrzysztofBarszcz** [comment]
Hi,
Can I work on it? Could you provide background color and gray-10 60% flat value? I guess background is `photonInk80`

**Comment by ekager** [comment]
Hi @KrzysztofBarszcz , you can work on this. I would suggest trying to change the dialog style for accent, primary, etc colors for the project in general to match this mock to not repeat work for every dialog! And @brampitoyo can get you the flat values this afternoon. Thanks!

**Comment by brampitoyo** [comment]
@KrzysztofBarszcz Will it be possible for us to use the same transparent colour value as `contextMenuTitleTextColor`, which is `#99f9f9fa`?

Source:
https://github.com/moyheen/focus-android/commit/06fc1b21e16fabaf88dec2f15b0e11a14da310dd#diff-b90dd5bd8f8d84662b2f78ce4110a07aR70

This will make our appearance consistent with #2686.

If that’s not possible, use the flat colour value of: `#aaabb6`.

**Comment by KrzysztofBarszcz** [comment]
@brampitoyo  yes, it was possible to use the first value provided by you
I finished the first approach, now the dialog looks like this:
![screenshot from 2018-08-03 20-06-48](https://user-images.githubusercontent.com/9646592/43658447-36e502fc-9759-11e8-8606-f3d9b89db4fe.png)
![screenshot from 2018-08-03 20-07-08](https://user-images.githubusercontent.com/9646592/43658448-38cc21ae-9759-11e8-9254-d6f82e9c366d.png)
I have a problem with the corners. It seems that now we have two layers: ink80 with rounded corners and gray without (it is more visible when you increase the corner radius)
![screenshot from 2018-08-03 20-16-09](https://user-images.githubusercontent.com/9646592/43658781-20de9814-975a-11e8-8fd4-76db426596f7.png)

**Comment by brampitoyo** [comment]
@KrzysztofBarszcz This looks really good! I have a couple of comments:

* For this and other dialogues, modals and menus, can you confirm that the corner radius is 4dp?
* It seems as if the grey background – lurking in the background – is a holdover from the old design. Is it something that you’d be able to remove?
* The button spacing and dimension (“Cancel” and “Add”) on your screenshots seem to look different from mine. Are these values that we get to control and customise, or do we say “We want two buttons here” and then rely on each OS variant to implement their own spacing and dimension?

**Comment by KrzysztofBarszcz** [comment]
@brampitoyo 

- It should not be very difficult (at least for dialogs) as now we would have new dialog style declared, It should be sufficient to set it for all dialogs. We could do the analogical thing for menus. Maybe we should have a separate task for it?
- yes, I think, I could remove at least the ones from the dialogs, calling this: `dialog.getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));` on them
- One difference was too big right padding which is corrected now. We can control these values. If you write me all other differences, I will correct them. How big should be the spacing between buttons? Now it looks like this:
![screenshot from 2018-08-06 09-51-16](https://user-images.githubusercontent.com/9646592/43703838-4ce0ffaa-995e-11e8-9c13-0c89de1de193.png)

**Comment by brampitoyo** [comment]
> If you write me all other differences, I will correct them. How big should be the spacing between buttons?

@KrzysztofBarszcz we follow Android Material Design’s dialog specs very closely, in terms of font sizes and spacings.

> https://material.io/design/components/dialogs.html#specs
> https://material.io/design/components/buttons.html#specs

Applied to our design, the measurements look like this:

<img width="360" src="https://user-images.githubusercontent.com/51007/43754629-ecf3da42-9a5f-11e8-99ce-6e06a45fd371.png">

I’ve also updated the specs above with the correct measurements.

**Comment by brampitoyo** [comment]
@KrzysztofBarszcz I’d consider these changes nice-to-haves. If there’s no time or resource to work on it, feel free to mark this issue as resolved.

**Comment by colintheshots** [comment]
This should be resolved in 7.0.
