### ISSUE TITLE
Convert pre-existing code to Kotlin

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3038]
### Why/User Benefit/User Problem
Huge quality of life improvement for devs moving forward: Kotlin is less verbose, cleaner, and provides a lot of nice optimizations that Java doesn't.

### What / Requirements
Use "convert to kotlin" function built into Android Studio and fix errors as they arise.

### Acceptance Criteria (how do I know when I’m done?)
The entire codebase is in Kotlin.

💡 Note: This may not be a priority right now, but I feel it would be a "nice to have" moving forward!

**Comment by Hackertronix** [comment]
@sblatz isn't this too broad ended? I mean between 2 PRs, there can be one focusing on one single file while the other converts an entire package to Kotlin, wouldn't converting the entire codebase to Kotlin in one PR would make it tough to review? Some sort guideline/constraint on this moving forward would help I guess

**Comment by sblatz** [comment]
I agree with @Hackertronix in that the scope on this is too large. I've also been told this is not a high priority as all new files are written in Kotlin, and converting old ones would likely be more work than it was worth. 

If you are still interested in contributing, be sure to check out our issues with the ["needs help" label](https://github.com/mozilla-mobile/focus-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22).
