### ISSUE TITLE
Hiding URL bar scrolls at different speed from page

### ISSUE THREAD

**Issue by thebnich** [mozilla-mobile/focus-android#304]
Go to google.com and slowly scroll down to hide the URL bar. Rather than moving up evenly with the URL bar as it disappears, the page moves faster and scrolls underneath the URL bar.

**Comment by sabbir044** [comment]
I can reproduce it in my 5.1 device. I like to start working on this project by fixing this issue.

**Comment by pocmo** [comment]
GIF for triage:

![GIF](https://cloud.githubusercontent.com/assets/89638/24188557/1578e404-0ee2-11e7-9f48-51f200c04327.gif)

**Comment by pocmo** [comment]
We are relying on CoordinatorLayout and "appbar_scrolling_view_behavior" from the support library.

**Comment by pocmo** [comment]
FWIW the same can be observed in Chrome (although not always):

![Chrome](https://cloud.githubusercontent.com/assets/89638/24188975/9322c388-0ee3-11e7-8994-43c5f2fc24db.gif)


And Fennec:

![Fennec](https://cloud.githubusercontent.com/assets/89638/24188966/8a5ff77a-0ee3-11e7-9f19-1bc77f2685b7.gif)

**Comment by bbinto** [comment]
@pocmo still valid?

**Comment by pocmo** [comment]
This is still the case. However I wonder whether this is something we actually need/want to fix. The current code relies on functionality in the support libraries and implementing another scroll behavior is not necessarily a trivial task. @lime124 What do you think?

**Comment by bbinto** [comment]
We can punt this to a P5 then.

**Comment by Cheap-Skate** [comment]
Phonograph seems to use CoordinatorLayout and appbar_scrolling_view_behavior and the page content follows my finger correctly as the toolbar hides i.e. it does not seem to exhibit issue #2789 or #304.

https://github.com/kabouzeid/Phonograph
https://play.google.com/store/apps/details?id=com.kabouzeid.gramophone&hl=en_GB

I bet lots of other apps do. Most of my apps seem to behave like Phonograph (correctly) and not like Focus (incorrectly).

**Comment by pocmo** [comment]
They all scroll native UI and not web content though.

**Comment by Cheap-Skate** [comment]
OK fair enough. Perhaps explains why some WebView browsers don't hide the toolbar on a drag scroll, only on a fling. Pretty crappy Android bug. Thanks for your time.

**Comment by Guest126** [comment]
I believe this bug has been fixed in a recent update (Firefox Focus 94 or later?). Please check it.

**Comment by Guest126** [comment]
I have confirmed that:
- Focus v8.17.1 (GeckoView v90.0) reproduce this issue
- Focus v91.1.0 (GeckoView v91.0) does not reproduce this issue

**Comment by pocmo** [comment]
Thank you for testing! 👍
