### ISSUE TITLE
Website incorrectly detects phone to be in landscape mode

### ISSUE THREAD

**Issue by SubhrajyotiSen** [mozilla-mobile/focus-android#3042]
## Steps to reproduce
Visit https://oyorooms.com

### Expected behavior
Website should display a list of hotels

### Actual behavior
A message is displayed asking the user to keep the device in portrait mode even though it is already in portrait mode.

### Device information

* Android device: Redmi Note 5 Pro running AOSP 8.1.0
* Focus version: 6.3(Build #222131205)

**Comment by buttercookie42** [comment]
With any luck this might be because of [bug 1475875](https://bugzilla.mozilla.org/show_bug.cgi?id=1475875) and [bug 1476106](https://bugzilla.mozilla.org/show_bug.cgi?id=1476106).

**Comment by cpeterso** [comment]
This does sound like GeckoView bug 1476106. I added a comment in that bug pointing back to this Focus issue so we don't forget to test this bug's steps to reproduce.

**Comment by bbinto** [comment]
@SubhrajyotiSen can you try and see if that's fixed in Nightly?

**Comment by SubhrajyotiSen** [comment]
@bbinto This seems to be resolved now on Nightly. I am closing the issue

**Comment by cpeterso** [comment]
Awesome! Thanks for reporting this bug and testing the fix, @SubhrajyotiSen!

**Comment by SubhrajyotiSen** [comment]
That was the least I could do to help :smile:
