### ISSUE TITLE
Url in the url bar out of sync with the currently displayed website

### ISSUE THREAD

**Issue by marcin-kozinski** [mozilla-mobile/focus-android#3044]
## Steps to reproduce
The steps definitely aren't deterministic, they are pretty generic and it happened only once, but the issue felt critical enough, so here's what happened to me:

1. Set Focus as the default browser.
1. Opened something from search results in Google Search app.
1. Closed it using system back button.
1. Put my device down for about 15 minutes (which is I guess to say that the next step didn't happen immediately after the previous, the exact length is probably not meaningful).
1. Open another result from Google Search app.

### Expected behavior

The new result loads in Focus and the url bar displays url for the current page.

### Actual behavior

Focus shows the new page, but the url for the previously opened search result.

Here's a screenshot:
![screenshot_20180801-200940](https://user-images.githubusercontent.com/2088582/43576096-c5946fc2-9648-11e8-86e3-6b134cd65a33.png)
I know it's hard to tell if you're not Polish, but the url in the toolbar (`euroobuwie`) is a footwear website, while the rendered website is for a real estate developer called "Apartamenty Jagiellońskie".

### Device information

* Android device: Pixel 2, Android 8.1
* Focus version: I'm on Nightly, today it shows 6.3 (Build #222131205 🦎 62.0.20180730180407), but the issue happened yesterday and it updated overnight.

**Comment by sblatz** [comment]
This is potentially linked to the underlying issue mentioned in #3046.

**Comment by ekager** [comment]
Should be closed by #3251
