### ISSUE TITLE
URL Bar freeze

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3046]
Probably a regression from URL Bar UI (and animation) changes 

## Steps to reproduce
Unclear. I've saw this once yesterday and someone contacted me on Twitter to report the same, but no reliable STR that I know of.

1. Be browsing and press erase button

### Expected behavior
URL Bar clears and you're able to enter a new address.

### Actual behavior
URL Bar freezes with last address you visited and you can't interact with it. Have to remove Focus from recent apps for this to be fixed. 
![38242773_10155955539714865_8613791000730533888_n](https://user-images.githubusercontent.com/25442310/43595035-8b341d36-9630-11e8-9592-0900fea8c47b.png)

### Device information

* Android device: pixel 2
* Focus version: Nightly

**Comment by ekager** [comment]
Possible regression point? Recent update to animation of URL Bar. Not sure why it would capture the URL there as well though
https://github.com/mozilla-mobile/focus-android/pull/2935

**Comment by sblatz** [comment]
The issue appears to be with our custom animation.

Inside MainActivity, the showUrlInputScreen method is called after erasing, which triggers the following transaction:

```transaction
                .replace(R.id.container, UrlInputFragment.createWithoutSession(), UrlInputFragment.FRAGMENT_TAG)
                .commit();```

Unfortunately, if this transaction is interrupted by pressing the home button quickly, the previous browserFragment does not get fully removed (though it does _not_ appear when trying to find it by its tag).

**Comment by sblatz** [comment]
It appears that adding ``` .addToBackStack(null) ``` to the transaction fixes this bug. This solution is obviously not desirable as it would result in a user being able to press back to get to their previous session. This will require further investigation.

**Comment by sblatz** [comment]
As mentioned in #3090, this points to a deeper issue in which a previous session may not be fully cleared due to the user pressing erase and home quickly.

**Comment by ekager** [comment]
Apparently this bug has been around for a while, see #2006

**Comment by ekager** [comment]
This is fixed by removing the custom animation of the erase fragment transaction.  https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/activity/MainActivity.java#L238

It seems like the transaction animation is being cancelled at a bad time when the app is quickly backgrounded and leaves the screen in a weird state. Wondering if we could substitute something else for this way of animating (it doesn't work for GV anyway see #2250.

**Comment by colintheshots** [comment]
The action of trashing the session shouldn't depend upon the animation completing.

**Comment by ekager** [comment]
I believe the session has been trashed, the animation is just left in some halfway completed state as a "ghost"
