### ISSUE TITLE
New delete icon uses evenOdd vector fillType 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3050]
evenOdd fillType is not supported by older versions of Android. @brampitoyo I don't know much about SVGs is it possible to get an icon without this fillType?

**Comment by ekager** [comment]
Maybe this could help - https://medium.com/thoughts-overflow/the-mystery-of-the-disappearing-holes-a-gripping-tale-of-using-svg-in-android-442f6035a452

**Comment by ekager** [comment]
It looks like a few of the new icons optimized for mobile include the even-odd fillType we'll need new icons for those as well

**Comment by brampitoyo** [comment]
@ekager I will see if reversing the path order and changing the fill type to nonzero will fix our problem. Thanks for investigating!

**Comment by brampitoyo** [comment]
[focus-android-icons-nonzero.zip](http://f.cl.ly/items/2y1M033a2x032d1L2623/focus-android-icons-nonzero.zip)

I was able to fix all the affected icons:

* delete
* device-desktop
* internet
* language
* lock
* settings
* tracking-protection
* tracking-protection-disabled

The fixed SVGs don’t contain any `fillType` property (not even `nonzero`). This should minimise our problems going forward.
