### ISSUE TITLE
Drop an Event When the Renderer Switches

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#3052]
### Why/User Benefit/User Problem
We want to track switches of the renderer due to A/B tests

### What / Requirements
In response to a direction from our A/B testing server, drop an event when the client has switched a renderer.

### Acceptance Criteria (how do I know when I’m done?)
- In response to a direction from our A/B testing server, the client drops an event when the client has switched a renderer.
- We can find this data on redash.

cc @mmccorks

**Comment by Sdaswani** [comment]
Related to #3045

**Comment by colintheshots** [comment]
This is resolved in GeckoWebViewProvider.kt in commit hash 5305b1d46c83ff98b786e68e8b850711328e83a7
