### ISSUE TITLE
[BUG] Crash of latest Klar Nightly

### ISSUE THREAD

**Issue by 4ut0-M-4t** [mozilla-mobile/focus-android#3061]
**OS/version**: Android 6.0.1
**App/version**: Firefox Klar Nightly 6.3

Latest version of Klar GV crashes if there's no fingerprint data. 

`08-04 22:35:40.563 E/AndroidRuntime(927): java.lang.RuntimeException: Unable to resume activity {org.mozilla.klar/org.mozilla.focus.activity.MainActivity}: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use` 

Access is limited to `Settings`. Switching `Stealth` `ON/OFF` has no effect.

**Comment by 4ut0-M-4t** [comment]
Sorry, I haven't checked closed issues before submitting this one. 
You may close it if the bug has already been fixed.

**Comment by nthomas-mozilla** [comment]
I'm seeing this with Focus too and found issue https://github.com/mozilla-mobile/focus-android/issues/3049 with a likely fix.

**Comment by sblatz** [comment]
Closed by #3049.
