### ISSUE TITLE
quora.com issues

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#3063]
<img width="791" alt="screen shot 2018-08-06 at 10 22 24 am" src="https://user-images.githubusercontent.com/122897/43722168-b0a29cca-9962-11e8-8fdf-0c6a01216923.png">

**Comment by SubhrajyotiSen** [comment]
I tried out quora.com on the latest nightly and I was able to browse it without any issues. I was able to log in and reads articles too

**Comment by lobontiumira** [comment]
Not reproducible on the latest 8.16.0 Focus build.
Tested on a Xiaomi mi4i (Android 5.0.2) device.
I will close this issue.
