### ISSUE TITLE
Example for "+ Add another search engine" is misleading

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/focus-android#3064]
## Steps to reproduce
1. Tap 3-dot menu > Settings > Search > "Google" default
2. Tap "+ Add another search engine"

### Expected behavior
3. Example: <example URL here> should provide a working example and/or link to: https://support.mozilla.org/en-US/kb/add-search-engine-firefox-focus-android

### Actual behavior
3. The text provided: "Example: example.com/search/?q=%s" is misleading / not helpful in 2 ways

(a). The user might think that the path suffix to add to the domain would be the same for any other search engine, which it isn't (see: https://support.mozilla.org/en-US/kb/add-search-engine-firefox-focus-android)
(b). I assume the assumption with the example is that the user is given a dummy example "example.com" and would know to replace that with a real search engine. However, even if you knew that the search string for youtube is:  youtube.com/results?search_query=%s, if you leave off the https:// (as in the example), the "Add a search engine" fails.

![server_not_found](https://user-images.githubusercontent.com/3699494/43727965-6412cc90-9958-11e8-8ca1-f2ee1bd2b83c.jpg)

### Device information

* Android device: ?
* Focus version: ?

**Comment by Tiago11** [comment]
Hi!

I'd like to start contributing to this project. This would be my first contribution.

For this specific issue, I was thinking something like the picture below, a couple working examples (to show that different search engines can have different search strings) and a link to: https://support.mozilla.org/en-US/kb/add-search-engine-firefox-focus-android

Any suggestions are welcome.

![add_search_engine](https://user-images.githubusercontent.com/4053245/43872771-baa02046-9b59-11e8-89a7-6726c8463545.png)
