### ISSUE TITLE
Telemetry can't be enabled (Firefox Klar Nightly)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#3068]
## Steps to reproduce

1. Go to Settings > Privacy & Security
2. Enable "Send usage data"
3. close settings
4. repeat step 1 and check the telemetry setting

### Expected behavior

Telemetry is enabled

### Actual behavior

Telemetry is still disabled

### Device information

* Android device: HTC U11 with Android 8.0
* Focus version: 6.3 Build 222181211

**Comment by pocmo** [comment]
I think that's #3037.
