### ISSUE TITLE
"Trackers blocked" re-enable only re-enables social trackers blocked

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/focus-android#3069]
## Summary
Possibly a cache issue?  Only social trackers are blocked when re-enabling "Trackers blocked".  
After app restart, however, all trackers show as being blocked. User shouldn't have to restart the app to fully re-enable "Trackers blocked" toggle.

## Steps to reproduce
1. Open fmarier's tracking protection (TP) test page URL:  https://mozilla.github.io/tracking-test/disconnect.html 
2. Verify that orange (TP enabled) fox is visible with STOP sign and status listed as:
   Ads: correctly blocked
   Analytics: correctly blocked
   Social: correctly blocked
3. Click on 3-dot menu > Disable "Trackers blocked"
4.  Verify that  (TP disabled) black cat is visible and status listed as:
   Ads: incorrectly loaded
   Analytics: incorrectly loaded
   Social: incorrectly loaded
5. Click on 3-dot menu > re-enable "Trackers blocked"

### Expected behavior
6. Verify that all categories of TP are re-enabled aka:

orange (TP enabled) fox is visible again with STOP sign and status listed as:
   Ads: correctly blocked
   Analytics: correctly blocked
   Social: correctly blocked

### Actual behavior
6.  Observe that _only_ social category is re-enabled aka:

 (TP disabled) black cat is visible and status listed as:
   Ads: incorrectly loaded
   Analytics: incorrectly loaded
   Social: correctly blocked

7. Re-start Focus app
Verify that all categories of TP are re-enabled aka:

orange (TP enabled) fox is visible again with STOP sign and status listed as:
   Ads: correctly blocked
   Analytics: correctly blocked
   Social: correctly blocked

### Screenshots
**Trackers blocked** - ENABLED
![image](https://user-images.githubusercontent.com/3699494/43736917-4d34ea64-9974-11e8-9540-9de5174b3068.png)

**Trackers blocked** - DISABLED
![image](https://user-images.githubusercontent.com/3699494/43737089-e12b041a-9974-11e8-9df9-99b988eb5524.png)

**Trackers blocked** - RE-ENABLED
![image](https://user-images.githubusercontent.com/3699494/43737315-c2e8b71c-9975-11e8-964f-5895983a1fbd.png)

### Device information

* Android device: Nexus 6P, ver. 8.0.0, API 26
* Focus version: 6.3

**Comment by bbinto** [comment]
Is this in the debug build or release build?

**Comment by sblatz** [comment]
This occurs on release build as well. I will investigate / own this ticket :)

**Comment by sblatz** [comment]
This is actually only an issue in WebView and does not exist in GeckoView. 

cc: @bbinto, @Sdaswani to determine if this is still a priority.

**Comment by Sdaswani** [comment]
@sblatz I would think so since Webview will be our most used engine for at least a few months.
