### ISSUE TITLE
<Send usage data> 'learn more' link goes back to (Settings) menu, not to website

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/focus-android#3071]
## Steps to reproduce
1. Open 3-dot menu > Settings > Privacy & Security 
2. In "Data Choices" section, click on "learn more" link

### Expected behavior
3. "learn more" link should (probably) open a website explaining usage data.

### Actual behavior
3. "learn more" link only returns you to the previous (Settings) menu.

### Device information

* Android device: Nexus 6P
* Focus version: 6.3

**Comment by SubhrajyotiSen** [comment]
Duplicate of #3043 and a PR is open on #3066
