### ISSUE TITLE
Add Telemetry for search suggestions

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3075]
- [ ] User enables/disables search suggestion (w/ data `from_urlbar_prompt: [true|false]`)
- [ ] User searches using a suggestion

@bbinto should we have any more?

**Comment by bbinto** [comment]
Looks good to me, overall it's important that we can distinguish how/what a user enters (in) the address bar
- type URL and hit enter
- type search term and hit enter
- type search term, select suggestion, hit enter

**Comment by boek** [comment]
PR w/ data review open #3107
