### ISSUE TITLE
Sumo links for 7.0

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3077]
- [x] Whats new
- [x] Search Suggestions
- [ ] Homescreen tips

**Comment by jonisavage** [comment]
Here are the links you can use:

-What's New page: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/whats-new-focus-android-7

-Search suggestions:  https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/search-suggestions-focus-android

-Homescreen tips: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/homescreen-tips-focus-android

**Comment by boek** [comment]
Thank you @jonisavage!
