### ISSUE TITLE
Android tablet have an oversized search engine icon

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3084]
### Steps to reproduce

Enter any keyword. Search suggestion doesn’t need to be turned on.

### Expected behavior

The search engine icon should appear in the correct size.

### Actual behavior

The search engine icon appears grossly oversized.

![screenshot_1533689135](https://user-images.githubusercontent.com/51007/43818326-293ed0e2-9b32-11e8-8fbf-a80dea7e3053.png)

**Comment by SubhrajyotiSen** [comment]
This can be closed too
