### ISSUE TITLE
The first search suggestion box on Android tablet covers over all the other suggestions

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3085]
### Steps to reproduce

* Turn search suggestions on
* Enter any keyword
* Scroll down

### Expected behavior

All search suggestions should appear on top of each other.

### Actual behavior

The first search suggestion box covers all the other suggestions.

![screenshot_1533689189](https://user-images.githubusercontent.com/51007/43818388-850243d2-9b32-11e8-88f3-7f1826646101.png)

**Comment by bbinto** [comment]
@boek is this fixed?

**Comment by boek** [comment]
@bbinto not yet, I almost have a fix but I don't think it will be ready for the first beta.
