### ISSUE TITLE
Redesign Custom URLs Fragment

### ISSUE THREAD

**Issue by SubhrajyotiSen** [mozilla-mobile/focus-android#3092]
### Why/User Benefit/User Problem
The current UI follows old Android design practices. Since we are following the Material Design specs closely, we can redesign it a bit
### What / Requirements

1. Use a FloatingActionButton to add new custom URLs
2. Use a InputDialog instead of a new Fragment to take input from the user

I can start working on this if someone can provide me the specs to be followed

**Comment by ekager** [comment]
@brampitoyo would you like to take a look at this?

**Comment by brampitoyo** [comment]
@SubhrajyotiSen Can you explain your proposal further and link to the page in the Material Design System?

If I understood correctly, this was how I interpreted it:

1. Eliminate the “Add Custom URL” context menu that appears when you long-press the URL bar, and replace it with a Floating Action Button.
2. When tapped, this button will spawn a modal dialogue containing a text input field. This field is already pre-populated with the URL.
3. To add the URL to the autocomplete list, simply tap the “Add” button.

Or is your proposal something different?

**Comment by SubhrajyotiSen** [comment]
I was referring to Settings > Search > URL Autocomplete > Custom URLs 

According to https://material.io/design/components/buttons-floating-action-button.html#, the FloatingActionButton represents the primary action of a screen. In this case, the primary action is adding a custom URL.

Right now, we use a new Fragment "Add custom URL" to take the URL input. I don't think we need to utilize an entire Fragment for this purpose. A modal dialog (just like you mentioned) would seem more appropriate usage of space.

**Comment by brampitoyo** [comment]
@SubhrajyotiSen Aha. You were saying that, instead of having a text link called “+ Add Custom URL”, we should instead turn it into a floating action button.

This is a really good idea! I’ll mock it up over the next few days.

**Comment by brampitoyo** [comment]
@SubhrajyotiSen Is it also a smart idea to turn the “+ Add another search engine” into a floating action button? (I realise that this is a separate issue, but just in case you have been thinking about applying the F.A.B. to another page).

**Comment by SubhrajyotiSen** [comment]
@brampitoyo Yes. Turning the “+ Add another search engine” into a floating action button would be nice since it would lead to an uniform design across the app.

Could we also use the dialog approach there too or would 2 EditTexts in the dialog clutter it?

**Comment by brampitoyo** [comment]
@SubhrajyotiSen wrote:
> Turning the “+ Add another search engine” into a floating action button would be nice since it would lead to an uniform design across the app.

Here’s a mockup of what this looks like:

<img width="320" src="https://user-images.githubusercontent.com/51007/44132539-9062e458-a0ae-11e8-8a10-02ade0902126.png">

How does the FAB transform? The Material Design System gave us a guideline:

> The FAB can transform into a new surface that spans the entire screen. This type of transformation is typically for creating new content.

So actually, there’s no need to replace the screen with a modal dialogue. We can keep our existing “Add Custom URL” screen.

Here’s what that transition looks like:

![add-custom-url-fab-animation](https://user-images.githubusercontent.com/51007/44132600-d7b6787e-a0ae-11e8-954d-ee0757a298c5.gif)

This is only my best approximation. For the actual transition effect, refer to the [guideline, under the “Full screen” sub-heading](https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions).

**Comment by with-shrey** [comment]
I am new to this project .
Can I Take Up This Issue ?

**Comment by dougouk** [comment]
Is anyone on this issue?

**Comment by ekager** [comment]
I don't think so @dougouk feel free to take a stab at it

**Comment by sank20** [comment]
Hi @SubhrajyotiSen , @brampitoyo , is there an issue already created for a similar change for “+ Add another search engine” option? (I couldn't find it) It would be great if anyone can add its reference here. Or maybe if the issue hasn't been created yet, I would like to take it up.

**Comment by sank20** [comment]
Hi all, I've been exploring about the Extended FAB and according to the [roadmap](https://github.com/material-components/material-components/blob/develop/ROADMAP.md#previous-releases) it hasn't yet been implemented in the material components for Android. Although there have been some workarounds prevalent among many developers, I am not sure about its compliance with the Mozilla's design guidelines. Can anyone put more light on this issue? How do we decide to take this UX improvement further?

**Comment by brampitoyo** [comment]
@sank20 There’s no issue created for “+ Add another search engine” option.

Let’s create it, and let’s also make sure that the button says “+ Add search engine”.

The Extended FAB utilises the same UX metaphor that the FAB already used since 2014–15 (around version Lollipop and Marshmallow), so it should already be familiar to most Android users.

**Comment by dougouk** [comment]
Hi, just an update. I am too busy and make the time to finish this. So if anyone wants to take over, feel free to do so.

I will come back in November and if this still needs to be done by then, I will ping the group, but otherwise good luck!

**Comment by EMVignesh96** [comment]
Hi, since extended FAB is not available yet, I have used a simple FAB to achieve it.
