### ISSUE TITLE
"Make default browser" doesn't work on Android <7

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3093]
## Steps to reproduce
1. Go to the Settings menu, and turn on "Make default browser".

### Expected behavior
A SUMO page opens.

### Actual behavior
The Settings menu is dismissed, history erased and no SUMO page opened.
On the Sony Xperia Z2 device, Focus is   ##terminated.

### Device information

* Android device: 
Oneplus Two (Android 6.0.1)
Sony Xperia Z2 (Android 6.0.1)

* Focus version: 
Nightly build 7.0

**Comment by SubhrajyotiSen** [comment]
Are you sure the Expected Behavior should be a SUMO page opening?

**Comment by sv-ohorvath** [comment]
Yes, on Android 6 and lower. That's how it behaves on the release version 6.1.1 too and I couldn't find any new feature to change that, except https://github.com/mozilla-mobile/focus-android/issues/2896, which is not done yet.
The SUMO page is https://support.mozilla.org/en-US/kb/set-firefox-focus-default-browser-android

**Comment by SubhrajyotiSen** [comment]
You are right. I just checked the code. Will investigate this tonight
