### ISSUE TITLE
Erase app shortcut not working

### ISSUE THREAD

**Issue by SubhrajyotiSen** [mozilla-mobile/focus-android#3098]
## Steps to reproduce

1. Long tap on the app icon to show app shortcuts
2. Click on Erase shortcut

### Expected behavior
History gets erased

### Actual behavior
A toast is shown saying "App is not installed"
This is mostly caused by the update in gradle version

Refence: https://stackoverflow.com/a/44840413

### Device information

* Android device: Redmi Note 5 Pro running Oreo 8.1
* Focus version: 6.3 Nightly

**Comment by SubhrajyotiSen** [comment]
Once it is confirmed, I can start working on this

**Comment by bbinto** [comment]
@SubhrajyotiSen - we'd love for you to work on this, thanks
