### ISSUE TITLE
Support RTL languages properly

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#31]

**Comment by pocmo** [comment]
Screenshots for Arabic:
https://people-mozilla.org/~npark/Focus_Screenshot/ar-/images/phoneScreenshots/dirindex.html
* The browser menu looks good but is positioned a bit too far to the right
* The URL bar with LTR URL looks strange, but maybe it's correct? 'Clear' icon on the left, but URL also on the left. Would be interesting to know how it looks like with a RTL URL.

Overall not bad.

**Comment by ahunt** [comment]
It looks like the error pages will need some work. IIRC they set dir="ltr" for the page content, which I didn't really understand while doing the import - and that seems related.

**Comment by 5y** [comment]
Forward and Backward arrows problem in RTL:

The right arrows should replaced with left arrows.

Right arrow = > go to the forward

**Comment by 5y** [comment]
Forward and Backward arrows problem in RTL on the Tablet [1] : 

Right arrow = > go to the forward
Left arrow => go  to the backward 

1- Nexus 7 , Android 6.01, Focus Persian.
![image](https://cloud.githubusercontent.com/assets/1941933/24070640/b1cb6f20-0bd6-11e7-805d-0982e2ac8e18.png)

**Comment by pocmo** [comment]
We fixed all RTL issues mentioned here (changes in build 755+). Let's file separate bugs for any new issues from here on.
