### ISSUE TITLE
Disable home screen tips after showing a certain number of times

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3101]
### Why/User Benefit/User Problem
Currently, home screen tips will be displayed until a user engages with that feature in some way (i.e. makes us default browser, adds a website to homescreen, etc.). As a user who may not care to use a certain feature, but the tip would continue to show _until I use it_. This could get annoying for users, especially for the default browser tip (looks like we're begging). 

### What / Requirements
Disable a tip after it is shown a certain number of times 

OR

Allow users to press an "X" (or similar) to never see a certain tip again (rather than disabling tips altogether). 

### Acceptance Criteria (how do I know when I’m done?)
* Depends on the decision made above

Would love @brampitoyo's thoughts on this :)

**Comment by bbinto** [comment]
@brampitoyo - would you mind providing a recommendation

**Comment by brampitoyo** [comment]
@sblatz I had a whole thread typed up before I accidentally closed the tab, so I’m just going to provide a TL;DR here.

We should disable a tip after showing it around 4 times, but each time we show it, we should make sure that users read it.

How do we do this? We measure “one unit of exposure” by adding the time:

* When the tip first fade in (it takes 2 seconds until it replaces “Browse. Erase. Repeat.”)
* When the user’s eye sees and focuses on the tip (1 second)
* When the user reads the tip from start to finish (3–5 seconds – an average of 4 seconds).

2 + 1 + 4 = 7 seconds.

This means that, when the user sits on the start screen for 7 seconds without doing anything, we assume that they’ve read the tips.

If they do something (let’s say that they start typing on the URL bar straight away), they will either miss the tip showing up, or miss reading the tip. We don’t count that as “one exposure”.

After 4 complete “units of exposure”, we can stop showing that particular tip.

What do you think?

**Comment by sblatz** [comment]
@brampitoyo My concern with the proposed solution would be, as a user, I have no indication of knowing how long a "unit of exposure" is. That is to say, I could easily be shown the same tip endlessly if I sat on the home page for just 3 seconds after launching the app--something I would find frustrating. Is there a happy medium we could find between the two? Perhaps we stop showing the tip after it's shown X times, and start showing it again if they _still_ haven't engaged with the feature after a certain period of time (and keep cycling between these two). 

Again, I think adding a tip that explains how to disable tips would be beneficial as well :)

**Comment by brampitoyo** [comment]
@sblatz You make a very good point. Measuring the the “total unit of exposure” would mean that many users won’t qualify, and will keep being shown tips over and over again.

I really like your idea of us not being “too smart” or measure anything, and just stop showing the tips after x times.

Let’s try an initial value of:

1. Stop showing the tip after it’s been shown 4 times
2. Show the tip again if the user hasn’t engaged with the feature after 1 month

And, as you wrote, keep cycling between these two.

Let’s discuss adding a tip that explains how to disable tips in another issue.

**Comment by vesta0** [comment]
@sblatz we don't want to push this feature until after we are able to review home screen tips telemetry (a few weeks after 7.0 release) so I moved it out of sprint 6.
