### ISSUE TITLE
Crash during "seat selection" on https://www.amctheatres.com/

### ISSUE THREAD

**Issue by pgill1** [mozilla-mobile/focus-android#3108]
## Steps to reproduce
navigate to https://www.amctheatres.com/
select a movie (it doesn't matter which, I've tried several)
click Get Tickets
enter zip code 10003
select Village 7 theater (it doesn't matter which theater is selected)
choose a showing time
at this point the web site should display a selection of available seats.  Focus crashes.

### Expected behavior
display seat selection page
### Actual behavior
crash during page display 
### Device information
* Android device: OnePlus 3 running Lineage 15.1 (Oreo 8.1.0) nightly build 8/7/2018.  Lineage kernel
* Focus version: 6.3 build 222221206, 62.0.2018082174131

**Comment by SubhrajyotiSen** [comment]
I am unable to reproduce this on the Focus nightly build

![photo_2018-08-12_23-09-26](https://user-images.githubusercontent.com/12984845/44004733-cbe4c036-9e84-11e8-8bf0-23efe3901884.jpg)

**Comment by pgill1** [comment]
So not reproducible.  Sigh.  I'll close the issue.
