### ISSUE TITLE
Keyboard doesn't show up after address bar is selected, video was played

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#3112]
## Steps to reproduce
1. Type in keyword in address bar
2. Select video
Now, try to search again via address bar...

### Expected behavior
Keyboard pops up to type in keyword

### Actual behavior
Keyboard doesn't show up

### Device information

* Android device: ?
* Focus version: ?

<img width="736" alt="screen shot 2018-08-13 at 7 38 00 am" src="https://user-images.githubusercontent.com/122897/44029610-e4d9d3e6-9ecb-11e8-9543-ed53a77c7a7f.png">

**Comment by SubhrajyotiSen** [comment]
I tried playing a video on YouTube and I was unable to reproduce this. My keyboard showed up instantly

**Comment by sd1998** [comment]
@ekager I would like to work on this.

**Comment by ekager** [comment]
@sd1998 if you can reproduce this, go ahead!

**Comment by sd1998** [comment]
@ekager This bug is not reproducible.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest RC 93.1.1 build, nor on the debug build from main from 10/5, using a Google Pixel (Android 10).
