### ISSUE TITLE
Not able to enable send usage data

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/focus-android#3121]
I'm using the latest nightly version of firefox focus which is working fine, but as u see there seams a problem with mine as i unable to make the send usage data  enable properly. 

Steps to reproduce the issue-
1.Get to setting menu.
2.Go to privacy and security option.
3.Enable the send uage data(if not enabled). 
4.Get back to the setting menu 
5.Repeat step 2 and scroll down to the data choices and observe. 

Expected result- 
The send usage data option is enabled.

Actual result-
The send usage data option is disable. 

This is happening after updating latest nightly version, cannot check weather I'm only having the issue others are also facing this issue.
My other user in same phone is also having same issue.

**Comment by SubhrajyotiSen** [comment]
I can confirm this issue

**Comment by ekager** [comment]
I'm still seeing this in Build 322291208 and will investigate this week
