### ISSUE TITLE
Tracking Protection settings in "Settings" not working (WebView only)

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/focus-android#3124]
## Summary
Main (3-dot) menu > "Trackers blocked" now fixed via: https://github.com/mozilla-mobile/focus-android/issues/3069 however,...

the settings in Main (3-dot) menu > Settings > Privacy & Security > Tracking Protection
Have no effect at all (either with "Trackers blocked" toggled on or off).

## Steps to reproduce
**With "Trackers Blocked" enabled**
1. Go to Main (3-dot) menu > Settings > Privacy & Security > Tracking Protection
2. Use the following settings:
 ```
Block ad trackers: ENABLED
Block analytic trackers: DISABLED
Block social trackers: DISABLED
Block other content trackers: DISABLED
```
3. Exit settings
4. Open test web page:  https://rpappalax.github.io/testapp
5. Click on link: "Ads, analytics, social test (disconnect)" 

### Expected behavior
6. Page should appear with growling black cat image indicating that Ads: "correctly blocked" and all others are "incorrectly loaded"

### Actual behavior
6. Page appears with happy fox image indicating all categories are "correctly blocked"

![image](https://user-images.githubusercontent.com/3699494/44120584-ac0d4c76-9fd1-11e8-9235-3d65a3109d43.png)

### Notes
Tried enabling / disabling various combinations of the TP settings to no avail.
Only the Main (3-dot) menu > "Trackers blocked" toggle has any effect.

### Device information

* Android device: Nexus 6p API, API 26
* Focus version: 7.0

**Comment by sv-ohorvath** [comment]
This is reproducing on Beta 2 build #322341804, but NR on Nightly build #322411212.

**Comment by vesta0** [comment]
@rpappalax @npark-mozilla I think this is only an issue within WebView. On beta 7.0.2 (using WebView) I am able to reproduce the error but when I manually set the engine to GeckoView the issue seem to be fixed. Would you be able to confirm?

FYI @colintheshots

**Comment by rpappalax** [comment]
@npark-mozilla thanks for checking, @vesta0! i just tried it on GeckoView and still seeing the issue.  Can we sync up a few mins on vidyo tomorrow?  would like to see if we're using same STR to arrive at result.

**Comment by ekager** [comment]
Oh, this is because when you exit Settings, the page doesn't automatically reload. If you reload the page, you see the correct result. I can change the behavior
