### ISSUE TITLE
British English

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/focus-android#3129]
Why isn't it available? I can only find American and Canadian English.

**Comment by callahad** [comment]
Translations are on a volunteer basis, and it looks like no one has submitted British English translations for Focus, yet. Would you like to help out?

There's a guide for getting started with localization ("L10n") at https://wiki.mozilla.org/L10n:Contribute. 

The translations for Focus live at https://pontoon.mozilla.org/projects/focus-for-android/.

**Comment by ilayaraja97** [comment]
https://pontoon.mozilla.org/en-GB/focus-for-android/ got it started. Start contributing!
