### ISSUE TITLE
Code quality job (and UI tests) failing due to Out of Memory error

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/focus-android#3131]
UI tests failing w/ exception because one of dependencies is code quality job, which has been failing with out of memory error

![image](https://user-images.githubusercontent.com/3699494/44161968-aaadcc00-a073-11e8-9f36-d881234762ae.png)

**Comment by npark-mozilla** [comment]
Our automation run is blocked on this issue.

**Comment by colintheshots** [comment]
Could I get a link to the actual failures so I can investigate. I think it's doubtful that the lint flavors are the problem.

**Comment by npark-mozilla** [comment]
This is where the failures first showed up: https://tools.taskcluster.net/groups/Jyz9RdqBTDK_Tl-T77BqjQ/tasks/Fi0gDc-hQNmzTwWQQx5ZIA/runs/0/logs/public%2Flogs%2Flive.log

**Comment by npark-mozilla** [comment]
hmm, the first failure doesn't contain much, here's the latest failure: https://tools.taskcluster.net/groups/EH1klywmT5exgwBka0Ff3w/tasks/LDHnZLhxRcW1hv3sUKZUeA/runs/0/logs/public%2Flogs%2Flive.log. (this one has stack trace)

**Comment by colintheshots** [comment]
It seems unlikely the problem is the lint change. The first failure happened during an unflavored lint run. It says :app:lint on the lines before the failure. The lint change wouldn't run that target anymore.

**Comment by colintheshots** [comment]
The latter failure shows it running out of heap. The biggest change in that list is the Gradle upgrade and Gradle plugin upgrade. It's entirely possible that the Java heap is set too small on the TaskCluster server and the new Gradle version requires more memory. FWIW, the same build works great on my laptop.

**Comment by npark-mozilla** [comment]
With the limit increased, Taskcluster still reports out of memory error.  Perhaps VM is lacking additional memory?

**Comment by npark-mozilla** [comment]
4GiB did it, thanks @colintheshots !
