### ISSUE TITLE
Turn off individual tips directly, or add a tip that lets users turn of all tips

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3139]
Based on @sblatz’s suggestions on #3101:

> Allow users to press an "X" (or similar) to never see a certain tip again
> (rather than disabling tips altogether).
> […]
> I think adding a tip that explains how to disable tips would be beneficial as well

Both of these are great ideas to help prevent our users from being annoyed. However, it gets philosophical from here on out. If we arrive at the point of needing to turn some/all tips off permanently, then maybe we should look into why the tips are annoying in the first place.

*TL;DR* – if enough privacy-sensitive users are annoyed by tips that they want to turn them off, why show tips in the first place?

Is there a value in having opt-in tips? That way, we know that only those who want to read tips will get them. But then, we’re dealing with the problem of not reaching enough users to make a numerical difference in feature usage.

**Comment by sblatz** [comment]
As a quick comment on this: users currently have the ability to disable tips, but it's buried a couple menus deep (and very few users even open settings to begin with--hence why we created the tips in the first place). I think adding a tip to deep link to disabling them would be a good middle-ground here. Opt-in tips would almost never be turned on, but we need to make opting out easy for those who have no interest in them.

**Comment by brampitoyo** [comment]
@sblatz Agreed. Do you have further thoughts on how often we should show this “turn off all tips” message?

I would say that we can start showing this message after at least 2 different tips have been shown.

Let’s consult @BrianNJones for the string – when he has time – to solve this issue.

Brian, here’s our background story:

We now have all our tips – which you’ve written – ready to go. Like many other features in Firefox Focus, tips are optional and may be turned off.

Today, turning them off involves going to Settings > Privacy & Security. This may be too deep for many users to access. Like snippets on Firefox Desktop `about:home`, if we have a way to easily turn tips off, we will avoid as much exposure as possible, for users who don’t want to see them. They’re less annoyed as a result.

The question is: **what should this “tip to turn off all tips” say?**

My initial idea is to have a one-line underlined link which leads directly to the appropriate section inside Settings. No need for further explanation.

> <h3 align="center"><strong>Firefox Focus</strong></h3>
> <p align="center"><a href="">Hide product tips on the start screen</a></p>

But another idea is to have a radio button directly on the start screen tips itself:

> <h3 align="center"><strong>Firefox Focus</strong></h3>
> <p align="center">Show product tips &nbsp; &nbsp; <img width="20" src="https://png.icons8.com/ios/150/3584fc/toggle-on-filled.png"></p>

**Comment by BrianNJones** [comment]
@brampitoyo @sblatz , I prfer the link approach; there's something "upside down" about offering to turn a feature OFF on the home screen. If we went with the link, think it should be as predictive as possible about what user sees/encounters on click: 
Turn off tips on the Focus start screen

(Separate issue that I don't have a clear solve for: do we know how common "start screen" is as vernacular?)

**Comment by sblatz** [comment]
I agree with @BrianNJones here that the deep-linking is best as that's how we handle all other toggles. Deep linking also gives the user better context of where the setting is if they ever want to change it in the future.

@brampitoyo: In regards to the "start screen" text, we use "Show home screen tips" for the toggle in the settings, so we should likely use the same language here with the tip. "Home screen" was decided on for that screen name as its the same verbiage that Firefox desktop uses:

<img width="200" alt="screen shot 2018-08-20 at 5 54 04 pm" src="https://user-images.githubusercontent.com/4400286/44368791-0b893a00-a4a2-11e8-81a4-fa5457a14ed5.png">

I think the best way to move forward with the "disable" tip is the following:
1. Implement the "x" button to clear an individual tip, which would hide tips for the *rest of that session*
2. If the user presses the "x" button two or three times, we present the "disable home screen tips" deep link.

My only worry with the "x" button is that it would potentially be even more distracting than the current tips. Again, this is all just a safeguard in case users _hate_ tips, but I'd rather be safe than have user backlash.

**Comment by brampitoyo** [comment]
@sblatz wrote:
> I agree with @BrianNJones here that the deep-linking is best as that's how we handle all other toggles.

I agree with deep-linking, as well.

I would also suggest highlighting the field in question after the user is redirected to Settings, to clarify the next action that the user should take.

<img width="360" src="https://user-images.githubusercontent.com/51007/44496885-bb40f080-a6ca-11e8-910d-4d61fbedc638.gif">

Let’s file a new issue for this, though.


> I think the best way to move forward with the "disable" tip is the following:
> 
> 1. Implement the "x" button to clear an individual tip, which would hide tips for the rest of that session
> 2. If the user presses the "x" button two or three times, we present the "disable home screen tips" deep link.
> My only worry with the "x" button is that it would potentially be even more distracting than the current tips. Again, this is all just a safeguard in case users hate tips, but I'd rather be safe than have user backlash.

Designing an ‘x’ button will be tricky, unfortunately.

For an ‘x’ button to look “at home” and works as the user expects, it needs to be placed inside a container along with the tip itself, like so:

<img width="360" src="https://user-images.githubusercontent.com/51007/44497774-53d96f80-a6cf-11e8-9d6b-8a410cb57dc4.png">

Even after trying to make the container as non-distracting as possible, the tip box still looks too prominent. It defeats the point of having the tips looking immersive like “Browse. Erase. Repeat.”

And putting the “x” button anywhere else on the screen doesn’t make it visually obvious that it controls the tip.

So, instead of having the user presses the “x” button, why don’t we present the “disable home screen tips” deep link as the second tip that the user sees?

This way, we know for sure that users who don’t like to see tips will turn it off almost immediately, and users who want to see them will keep them on.

After this first showing, the “disable home screen tips” deep link will show up again from time to time, but not too often. We know that users have made that decision, and don’t need to revise it too often.

**Comment by sblatz** [comment]
> Even after trying to make the container as non-distracting as possible, the tip box still looks too prominent.

@brampitoyo Thanks for trying that idea out! I agree, though, that it would be far too distracting. I like the strategy of showing it early on, then showing it less often than a normal tip. I'll work on implementing this! :)

**Comment by lobontiumira** [comment]
I think we can close this issue, since there is the "Skip" option now, displayed from the first tip.
Tested on the 8.16.0 with Samsung Galaxy Note 8 (Android 9).

![Screenshot_1](https://user-images.githubusercontent.com/40694158/124242876-e52aea80-db25-11eb-9f73-00dd652558e5.jpg)

**Comment by cadeyrn** [comment]
@lobontiumira AFAIU this issue is not about the onboarding screens (as seen in your screenshot) but about the tips on the home screen.

**Comment by lobontiumira** [comment]
Oh, sorry, I misread the issue. I'll reopen it.
Thank you!
