### ISSUE TITLE
Crash on visiting "https://ww2.animeram.cc/"

### ISSUE THREAD

**Issue by Maxworld3** [mozilla-mobile/focus-android#3140]
Pasting the website link on focus address bar "https://ww2.animeram.cc/" crashes the firefox focus. 

Android 8.0.0 
Firefox Focus - 7.0 (Build #222271455)

**Comment by boek** [comment]
@ekager testing it now

**Comment by boek** [comment]
@Maxworld3 Yep! This will be fixed in the next beta 👍 

Fixed by #3143
