### ISSUE TITLE
No APKs in Releases page

### ISSUE THREAD

**Issue by Rikk** [mozilla-mobile/focus-android#3141]
There are no APKs in Releases page, therefore, Readme, Wiki and elsewhere that says it need to be fixed.

**Comment by boek** [comment]
Hey @Rikk, thank you for catching that! I just uploaded the APKs for the last two builds.

**Comment by Rikk** [comment]
6.3 was only nightly? Not on Releases?

**Comment by boek** [comment]
@Rikk Correct! We do want to create an index of all of the nightly builds that we're tracking here: #2980.
