### ISSUE TITLE
Swipe down to refresh page

### ISSUE THREAD

**Issue by sagar-viradiya** [mozilla-mobile/focus-android#3142]
### Why/User Benefit/User Problem
No need to go to overflow menu to refresh page.

### What / Requirements
Swipe down should refresh page just like google chrome.

**Comment by ekager** [comment]
Thanks for filing. Focus currently has swipe to refresh, it is just disabled because of issues. See #2007 and #1762 for why we disabled.

**Comment by sagar-viradiya** [comment]
@ekager My bad, will follow on these issues.
