### ISSUE TITLE
Block Cookies Option is not following Language Selection

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/focus-android#3146]
## Steps to reproduce
1. Open the settings menu.

2. Go to privacy and security.

3. Scroll down to the `Cookies and Site Data/Block Cookies` and  observe the selection. 

4. Return to the settings menu.

5. Click on the `language` and select a language other than current language.

6. Repeat the 2nd and 3rd steps, and observe the `Block Cookies`.
### Expected behavior
The option chosen in `Block Cookies` is shown in Current Language selected by User. 
### Actual behavior
The Option chosen by the user is not showing in the language selected rather in Previous Language selected by user. 
### Device information

* Android device: 8.0.0
* Focus version: 7.0 (Build #222281207 🦎 62.0.20180813190114)

**Comment by vesta0** [comment]
Looks like this was fixed. QA will verify.

**Comment by vesta0** [comment]
@ekager thanks for looking into this. Let's do it if it's a small.
