### ISSUE TITLE
Missing an important function!

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/focus-android#3148]
Hi,
1. The lack of whitelist mechanism inside hopes to be added!

2. Hope to add this function in the drawing!

![screenshot_2018-08-12-17-56-49-590_org adblockplus browser](https://user-images.githubusercontent.com/41664010/44256794-c31d1280-a23c-11e8-99e0-11976687df78.png)

**Comment by vesta0** [comment]
Adding this feature in #4058
