### ISSUE TITLE
Support for Unicode URLs

### ISSUE THREAD

**Issue by mastizada** [mozilla-mobile/focus-android#3150]
Tried to open an url in Focus with Russian letters, it shows encoding instead of letters (just like old versions of Firefox) and throws error that cannot securely connect to website. It works well in Firefox for Android and in Chrome.
URL: https://сталинбункер.рф/

**Comment by bbinto** [comment]
Thanks for reporting - could you please let us know what version of Focus you are currently using?

**Comment by mastizada** [comment]
6.0 (Build #21861909)
