### ISSUE TITLE
Home screen suggestions don't always wrap before screen edge, look too long

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3151]
## Steps to reproduce
- Open Focus

### Expected behavior
Suggestions wrap before screen edge

### Actual behavior
Wrap at screen edge

### Device information

* Android device: pixel 2
* Focus version: 7.0, local build from a few days ago

This doesn't seem to happen with all suggestions but some of them.

![screenshot_20180816-143604](https://user-images.githubusercontent.com/759372/44268477-73abf780-a1e6-11e8-80f8-70cb70f21c8e.png)

**Comment by bbinto** [comment]
@brampitoyo can you please tell us what your preferred method of handling this is?

Just increase margin or forcing a line break?

**Comment by brampitoyo** [comment]
We should use line breaks, as @BrianNJones had written [here](https://github.com/mozilla-mobile/focus-android/issues/3039#issuecomment-411858791):

Site behaving unexpectedly?
Try turning off Tracking Protection

Get one-tap access to sites you use most
Menu > Add to Home screen

Open every link in Firefox Focus
Set Focus as default browser

Autocomplete URLs for sites you use most
Long-press any URL in the address bar

Open a link in a new tab
Long-press any link on a page

Rather see the full desktop site?
Menu > Request desktop site

We can also add a 24px side margins, but following the line break should solve this line-wrapping issue.

**Comment by vesta0** [comment]
Fixed.
