### ISSUE TITLE
Youtube video/audio playback stops when screen is turned off

### ISSUE THREAD

**Issue by nkestrel** [mozilla-mobile/focus-android#3153]
## Steps to reproduce

1. Go to https://youtube.com and play a video with audio.
2. When video is playing, press the power button to turn off the screen.

### Expected behavior

The audio from the video playback should continue.

### Actual behavior

 The audio and video stops.

This used to work previously in 6.2 (eg 121941205) and earlier versions of 6.3 but not after 122221206.

**Comment by ilayaraja97** [comment]
This should be the expected behavior according to me. If I hit the power button I want every video/music to stop, improving my privacy.

**Comment by nkestrel** [comment]
That is a use case consideration but it can be mitigated with use of headphones and the volume button without breaking background playback. Doing so saves a lot of battery by not having to have the screen active all the time to listen to audio.

**Comment by bbinto** [comment]
@ekager to document current and past actual behavior.

Product decision: it should not be a functionality regression

**Comment by cpeterso** [comment]
Here is the GeckoView bug to provide a media control API that would allow the app to choose whether to pause GeckoView's audio playback when the app is backgrounded:

https://bugzilla.mozilla.org/show_bug.cgi?id=1483397

Fennec's behavior is to continue playing audio when backgrounded, which is considered a feature. :)

**Comment by nkestrel** [comment]
I just noticed youtube playback is working with the screen off in 7.0.3 (322521205). Background playback does not work but that is a separate issue.

**Comment by cpeterso** [comment]
Thanks for testing, @nkestrel. Does YouTube play in a background tab in Focus using WebView (Focus 6.0)?

We can use this bug to track the background tab issue.

**Comment by nkestrel** [comment]
Youtube background playback does not work on Focus 6.1.1 with WebView. 

Playback with the screen off was fixed by 7.0.1.
