### ISSUE TITLE
Site loads slow: uniqlo.com

### ISSUE THREAD

**Issue by initrd** [mozilla-mobile/focus-android#3157]
## Steps to reproduce
Open uniqlo.com
Wait for website to load

### Expected behavior
Site loads in a reasonable/comparable time to a webview browser - ~8s (I tested on Rocket 3.0.0)

### Actual behavior
Site loads in ~17s

### Device information

* Android device: Google Pixel
* Focus version: 7.0 (Build 322291208 Gecko 62.0.20180313190114)

**Comment by cpeterso** [comment]
Thanks for reporting this slow site, @initrd! I filed a GeckoView bug to track the work on the GeckoView side:

https://bugzilla.mozilla.org/show_bug.cgi?id=1485092

**Comment by jeanygong** [comment]
Chris, can you provide a profile on this bug for the QF team for analysis or more details..  Can you put the response in the bugzilla bug itself.

**Comment by vesta0** [comment]
@cpeterso was this fixed? I am not able to recreate this issue in 7.0.1

**Comment by cpeterso** [comment]
@initrd Do you still see this performance difference?

On my low-end Moto G5 (using Wi-Fi), Klar 6.0 (WebView) and chrome load uniqlo.com in about 4 seconds. Focus 7.0 Nightly (GeckoView) and Fennec 62 take about 6 seconds. So slower but not 2x slower.

**Comment by cpeterso** [comment]
I think we can close this bug as "works for me". Currently, Chrome and Focus+WebView load uniqlo.com in about 2 seconds on my Moto G5 (over fast Wi-Fi). Fennec, Focus+GeckoView, and the Reference Browser load uniqlo.com in about 3 seconds. While technically 50% slower, not a big difference.

@initrd Do you still see a 2x performance difference?
