### ISSUE TITLE
Erase Animation Seems to Be Slower 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3158]
Lately it seems our erase animation is slower than it used to be. No real STR, just maybe something to investigate.

**Comment by sblatz** [comment]
@brampitoyo to confirm this animation needs sped up?

**Comment by brampitoyo** [comment]
@ekager I don’t see it as slower, necessarily, but maybe more abrupt? Like the screenshot of the page isn’t taken properly before the tab disappeared.

But there’s a chance that the switch to GV might make our transition slower. If that’s the case, then we should speed it up.

**Comment by ekager** [comment]
Closing I don't think this is a real issue
