### ISSUE TITLE
Fleksy Keyboard Issue

### ISSUE THREAD

**Issue by Aditya7799** [mozilla-mobile/focus-android#3163]
## Steps to reproduce
Type in the first two letters of a URL. For Eg yo(utube.com)
Spam the backspace key to erase all the letters
### Expected behavior
A clear URL bar expected
### Actual behavior
One unerased character stays behind with the cursor on its left side.Here "o".
### Device information
Samsung Galaxy S6
By my knowledge issue persists only on the Fleksy Keyboard .

* Android device: ?
* Focus version: ?

**Comment by ekager** [comment]
Probably related: https://github.com/mozilla-mobile/focus-android/issues/778

**Comment by bbinto** [comment]
@Aditya7799 - What version of Focus are you using? We believe we've fixed the issue, but currently on applied to Nightly.

**Comment by Aditya7799** [comment]
@bbinto  version 5.2

**Comment by vesta0** [comment]
Fixed.
