### ISSUE TITLE
Pop Up Preferences Don't Match New Style

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3168]
Locale List Preference and Cookies Preference both pop up a dialog that does not match our new style.

**Comment by boek** [comment]
Hey @brampitoyo 

I applied the theme that the the menus have and this is what I got. What do you think?

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1250545/44505075-4337e380-a654-11e8-9243-665fc6d93cf5.png">

**Comment by brampitoyo** [comment]
@boek It looks really good! Let’s ship it.
