### ISSUE TITLE
Some heavy/heavy-ish sites tend to break the browser

### ISSUE THREAD

**Issue by initrd** [mozilla-mobile/focus-android#3173]
## Steps to reproduce
Open 'https://www.chubbiesshorts.com/collections/summer-sale-18'
In another tab, open 
Erase browsing history

### Expected behavior
Tabs are quickly closed, browsing history is erased

### Actual behavior
Browser hangs, takes a long time to clear history
Android shows a "Firefox Focus is not responding" dialog
Phone heats up after repeating the above steps a couple of times
Here are a couple of screenshots. One screenshot shows Focus hung, second one shows the "Not responding" dialog
![screenshot_20180820-211454](https://user-images.githubusercontent.com/1941695/44380447-413d1b80-a4c0-11e8-9fc6-b7bf4b88d20a.png)
![screenshot_20180820-212724](https://user-images.githubusercontent.com/1941695/44380448-413d1b80-a4c0-11e8-990b-e82b10fdd3d2.png)

### Device information

* Android device: Google Nexus, Android 9.0
* Focus version: 7.0 (Build 322291208 Gecko 62.0.201808131900114)

**Comment by ekager** [comment]
Thanks for filing! Probably related to #2843

**Comment by vesta0** [comment]
@sv-ohorvath can you reproduce this in 8.0.6?

**Comment by sv-ohorvath** [comment]
Tried with a Pixel (Android 9)& Motorola Nexus 6 (Android 7.1.1). Cannot reproduce on Nightly 8.0.6. GV. @initrd if you still have this issue, please let us know.

**Comment by vesta0** [comment]
Thank you @sv-ohorvath
