### ISSUE TITLE
Stop releasing aarch64 builds

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#3174]
Following what @cpeterso wrote here:
https://github.com/mozilla-mobile/focus-android/issues/3056#issuecomment-414483070

We should stop uploading aarch64 builds to Google Play.

For that we need to:
* Remove the aarch64 APKs from the release task:
  https://github.com/mozilla-mobile/focus-android/blob/master/.taskcluster.yml#L144-L149
* Remove the aarch64 APKs from the Nightly hook:
  https://tools.taskcluster.net/hooks/project-mobile/focus-nightly-public

**Comment by pocmo** [comment]
Currently signing on taskcluster is busted and @JohanLorenzo will file a netops bug. After that we can update the config and spin up a new Nightly.

**Comment by pocmo** [comment]
Signing works again. I'll remove aarch64 builds from the Nightly task and re-trigger it.

**Comment by pocmo** [comment]
That worked nicely. Aarch64 Nightly users have been downgraded to the regular arm builds.

**Comment by boek** [comment]
Nice!
