### ISSUE TITLE
Nightly: Archive past decision tasks to the index of Taskcluster

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-mobile/focus-android#3175]
While looking for the root cause of [bug 1484950](https://bugzilla.mozilla.org/show_bug.cgi?id=1484950),  I realized there is no easy way to look back at the graphs of the past nightlies. I worked around it by accessing the logs of the worker.

It would be great if we had more entries under: https://tools.taskcluster.net/index/project.mobile.focus.nightly . For instance Fennec nightlies have the following folders: https://tools.taskcluster.net/index/gecko.v2.mozilla-central.nightly.2018.08.20.revision (see nightly.2018.08.20.revision.$rev). 

A way to add these is to enhance the decision task with a new scope like: `queue:route:index.project.mobile.focus.nightly.2018.08.20.revision.$rev`. This is something that should happen on the hook https://tools.taskcluster.net/hooks/project-mobile/focus-nightly. This can be configured thanks to JSON-e and their time operator: https://taskcluster.github.io/json-e/#Language/time 

cc @pocmo

**Comment by pocmo** [comment]
I filed that some time ago:
https://github.com/mozilla-mobile/focus-android/issues/2980

**Comment by JohanLorenzo** [comment]
Awesome! Let's close this ticket then!
