### ISSUE TITLE
Unable to turn on Send Usage Data

### ISSUE THREAD

**Issue by initrd** [mozilla-mobile/focus-android#3178]
## Steps to reproduce
Install Focus beta from the Play Store
Open Focus > Settings > Privacy & Security 
Toggle the Send Usage Data button ON
Go back
Open Focus > Settings > Privacy & Security 

### Expected behavior
Send Usage Data is turned on

### Actual behavior
Send Usage Data is turned off

### Device information

* Android device: Google Nexus, Android 9.0
* Focus version: 7.0 (Build 322291208 Gecko 62.0.201808131900114)

**Comment by ekager** [comment]
Thanks for filing! Closed by #3165
