### ISSUE TITLE
Search suggestions causing crashes

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#3187]
Via GPS

<img width="760" alt="screen shot 2018-08-22 at 6 12 25 am" src="https://user-images.githubusercontent.com/122897/44465434-6457f000-a5d2-11e8-8e63-41c3c39f171b.png">

**Comment by boek** [comment]
@bbinto There is a fix going out in the next beta 👍. DDG is filtering on even partial matches of blacklisted words. related: #3127
