### ISSUE TITLE
Convert Java classes to Kotlin to make browser-session integration easier

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#3190]
This is a prerequisite for #3179 and will dramatically reduce the patch size and make the integration easier.

It would be helpful if we could convert (and clean up) the following files:

Activities:
* [x] app/src/main/java/org/mozilla/focus/activity/EraseShortcutActivity.java
* [x]  app/src/main/java/org/mozilla/focus/activity/MainActivity.java
* [x]  app/src/main/java/org/mozilla/focus/activity/TextActionActivity.java

Fragments:
* [x]  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java
* [x]  app/src/main/java/org/mozilla/focus/fragment/WebFragment.java
* [x]  app/src/main/java/org/mozilla/focus/session/ui/SessionsSheetFragment.java

WebView:
* [x]  app/src/main/java/org/mozilla/focus/webview/SystemWebView.java

Others:
* [x]  app/src/main/java/org/mozilla/focus/menu/browser/RequestDesktopCheckItemViewHolder.java
* [x]  app/src/main/java/org/mozilla/focus/menu/context/WebContextMenu.java
* [x]  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.java
* [x]  app/src/main/java/org/mozilla/focus/session/ui/EraseViewHolder.java
* [x]  app/src/main/java/org/mozilla/focus/session/ui/SessionsAdapter.java
* [x]  app/src/main/java/org/mozilla/focus/utils/SupportUtils.java

**Comment by pocmo** [comment]
CC @boek @colintheshots

**Comment by ekager** [comment]
Closing, they all look complete to me

**Comment by pocmo** [comment]
Yes, thanks! :)
