### ISSUE TITLE
Need a way to see main view tips for UI screenshot test

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3192]
Since 7.0, there are tips being displayed on the main view in random order.  This makes it difficult to capture all of them for UI Screenshot test for l10n team.  There should be a way to access all tips text to be captured, like we do for error messages.  (i.e. error:<digit> on the URL bar will show the error message corresponding to the number)

**Comment by npark-mozilla** [comment]
7.0 screenshot generation is blocked on this issue.

**Comment by npark-mozilla** [comment]
@Delphine is that okay with you timewise?  The screenshots need to wait before this fix is in.  I can try to generate a set anyways to check other stuffs

**Comment by Sdaswani** [comment]
If it needs to land sooner that's fine, @boek @ekager or @colintheshots can pick it up.

**Comment by Delphine** [comment]
Counting backwards: since I need to sign-off on locales on Fri August 31, I think if we get the screenshot on Tues Aug 28 at the latest, that would be ok.

**Comment by boek** [comment]
Picking this up so we can land it sooner than later

**Comment by boek** [comment]
@npark-mozilla 

This will swap out the tip whenever you submit an input with: `l10n:tip:1-6`.

Does this work?

**Comment by npark-mozilla** [comment]
@boek I'm assuming there are 6 tips? thanks!
