### ISSUE TITLE
Translations of "Trackers blocked" in the app menu overflows if longer than the English original

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-mobile/focus-android#3195]
## Steps to reproduce
1. Switch Focus to Czech (cs).
1. Go to some site with trackers, e.g. openoffice.cz.
1. Tap the menu icon.
1. Check the number of blocked trackers.

### Expected behavior
The "Trackers blocked" string does not overflow, but wraps or at least has ellipsis. Preferred is to be wrapped IMO. And I believe Czech is not the only language with such long translation.

### Actual behavior
If the string is long (actually just a little longer than English, it overflows ugly).

### Device information
* Android device: Xperia XZ1 Compact, Android 8.0.0
* Focus version: 7.0 (build #322291208 :lizard: 62.0.20180813190114)

![screenshot_20180819-162836](https://user-images.githubusercontent.com/3941344/44485703-b7bd5300-a651-11e8-8eb9-c847f4a29e86.png)

**Comment by MikkCZ** [comment]
CC @Delphine

**Comment by brampitoyo** [comment]
In this case, the text should wrap to the next line.

**Comment by SubhrajyotiSen** [comment]
@brampitoyo In that case, should the font size decrease while wrapping to next line or occupy more height?

**Comment by MikkCZ** [comment]
Verified it works well in 7.0 (Build #322381210 :lizard: 62.0.20180823143155).

**Comment by brampitoyo** [comment]
@SubhrajyotiSen 
> […] should the font size decrease while wrapping to next line or occupy more height?

It should occupy more height.

A height of 72dp should be used when we accommodate two lines of text:

<img width="360" src="https://user-images.githubusercontent.com/51007/44693427-fd4ba700-aabb-11e8-99ae-839aafff91ae.png">

And when there are three lines, we should use a height value of 88dp (I’ve only put two lines here – note that there’s enough space for a third line!):

<img width="360" src="https://user-images.githubusercontent.com/51007/44693435-15232b00-aabc-11e8-88e0-151c24b3396f.png">

**Comment by brampitoyo** [comment]
@SubhrajyotiSen 
> […] should the font size decrease while wrapping to next line or occupy more height?

It should occupy more height.

A height of 72dp should be used when we accommodate two lines of text:

<img width="360" src="https://user-images.githubusercontent.com/51007/44693427-fd4ba700-aabb-11e8-99ae-839aafff91ae.png">

And when there are three lines, we should use a height value of 88dp (I’ve only put two lines here – note that there’s enough space for a third line!):

<img width="360" src="https://user-images.githubusercontent.com/51007/44693435-15232b00-aabc-11e8-88e0-151c24b3396f.png">
