### ISSUE TITLE
Handle links that use third-party protocols or open external apps 

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#32]

**Comment by ahunt** [comment]
@antlam : What behaviour do we want? A user is unlikely to know that a link will redirect to an external app until they've clicked on it - do we need a notification to confirm that they are leaving focus (and do we need to ask them if they want to clear their browsing data then?).

**Comment by ahunt** [comment]
Note to whoever implements this: behaviour when opening a link from scratch (i.e. start focus, paste link) is different to behaviour when opening a link when you're already browsing.

- Opening link: shouldOverrideUrlLoading() is called, followed by shouldInterceptRequest()
- Opening from scratch: we've added notifyCurrentURL (since shouldOverrideUrlLoading() isn't called in this case), followed by shouldIntereceptRequest().

We should make sure both work acceptably.

**Comment by ahunt** [comment]
Fennec shows the following prompt when you open an external link in private browsing - I'll do the same in Focus for now:
_URL_
This link will open in Google Play Store. Are you sure you want to exit Private Browsing?
[No] [Yes]

**Comment by antlam** [comment]
@ahunt perfect! that's exactly what I was going to say 💯

**Comment by ahunt** [comment]
One more UX thing: If there are multiple apps that support a given link (e.g. email):

- Firefox normal browsing:
-- If a default app is set, the app is opened directly
-- If no default app exists:

Open With
[App 1]
[App ...N]
[Just once] [Always]

- Firefox private browsing: if more than one app is available, we always show:

Exit Private Browsing?
[App 1] [App 2]...[App3]

(We're using the OS app picker for both, but on at least Android 7 one of those is horizontal, and one is vertical. We don't show which app is the default for private browsing, but it's still possible for us to ask Android which one is the default.)

For now I've copied the firefox private browsing mode behaviour. I'm wondering if it's better to just try to use the default app if one is set (we don't offer that choice in normal browsing after all)? We could still add a "open in other app" option to the "exit focus" confirmation dialog in this scenario.

(I have screenshots, but screenshot upload is failing today...)

**Comment by ahunt** [comment]
Here's a screenshot of the current dialog (I haven't done anything related to its appearance, that's just the default dialog appearance with our current theme) - I'm not sure that using the link as a title is ideal (that's what fennec does):
![dialog_preview](https://cloud.githubusercontent.com/assets/1546915/23484969/35bb1886-fe8e-11e6-9cdb-27475dd84a26.png)

I'm also not too sure what exactly to show if we need to redirect to the play store, this is the current state of things:
![dialog_play](https://cloud.githubusercontent.com/assets/1546915/23485030/85634bec-fe8e-11e6-866d-c36a14985e42.png)

Finally, I still need to handle completely unsupported links: we can only redirect to the play store if a link contains an android app/package name (so generic random schemes won't do anything, e.g. ssh://...... is ignored). I still need to add code to handle that case, for now I'm redirecting to a non-existent about:error page.


I've also put together a quick document summarising what various browsers do when opening external links, just in case we need to revisit our behaviour decision.
https://docs.google.com/a/mozilla.com/document/d/1KZVpSpptLsfv72qLEUXooxwM2bgcW0qWT4g2h_9bMpM/edit?usp=sharing

**Comment by antlam** [comment]
@ahunt For the link/buttons, can we use the blue we're using in the Settings UI? 

For the "No app to handle link" I'll ask Michelle.

Also thanks for the doc! it's really helpful :)

**Comment by ahunt** [comment]
(Note to self: I still need to set the right colours as per https://github.com/mozilla-mobile/focus-android/issues/32#issuecomment-283767785 , before closing)

**Comment by ahunt** [comment]
How's this?
![updatedstyle](https://cloud.githubusercontent.com/assets/1546915/23916065/3eceb40c-08eb-11e7-9812-45d3b970fc85.png)

**Comment by antlam** [comment]
from Michelle:

> For the case where there is an app that can handle the link, instead of showing the link how about:
> Open link in another app
> You can leave Firefox Focus to open this link in <name of app>. 
> CANCEL | OK

> For the case where there is no app to handle this link:
> Find an app that can open link
> None of the apps on your device can open this link. You can leave Firefox Focus to search the Google Play Store for an app that can. 
> CANCEL | OK

**Comment by pocmo** [comment]
> None of the apps on your device can open this link. You can leave Firefox Focus to search the Google Play Store for an app that can.

"the" in the second sentence might be a problem. With placeholders (and without "the") the string would be:

> None of the apps on your device can open this link. You can leave %1$s to search %2$s for an app that can.

And in the case of Google Play (app name = "Play Store") on my device this results in:

> None of the apps on your device can open this link. You can leave Firefox Focus to search Play Store for an app that can.

Is this acceptable?

**Comment by mheubusch** [comment]
that is great, thanks for reviewing carefully and catching this! definitely remove the "the"

**Comment by ahunt** [comment]
(FWIW Chrome also does nothing if you have an unsupported link (e.g. ssh:......). It only opens the play store if the link specifies the exact desired app.)

**Comment by ahunt** [comment]
@antlam Do we still want the blue title now that we're showing actual text (instead of the link):
![v3_1](https://cloud.githubusercontent.com/assets/1546915/23996775/01e2ed5a-0a4f-11e7-9eab-d6b9d0e9649a.png)

**Comment by antlam** [comment]
@ahunt 

> @antlam Do we still want the blue title now that we're showing actual text (instead of the link):

Nope! Keep it white :)

**Comment by antlam** [comment]
@ahunt can you quickly comment in here when you have the chance? just to summarize what we decided for the 1% use case and the 99% use case :)

Thanks!

**Comment by ahunt** [comment]
Our link behaviour is:
- Normal web link -> open it
- External link: multiple scenarios:
-- Link handled by existing app:
--- Show confirmation dialog if only one target app exists
--- Show selector if multiple target apps exist
-- No target app exists:
--- Link includes target app (e.g. a link designed to open yelp/google play/etc): we ask to open the Play Store [This is likely for 99% of links that aren't an email address or phone number]
--- Link doesn't include target app: show error page (Note: both Chrome and Firefox do _nothing_ in this scenario) [1% scenario]
