### ISSUE TITLE
Redesign placement of Erase FAB

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#3201]
We've heard this before, surfacing it now again: people mistakenly click the trash can icon.

e.g. https://twitter.com/Balyan_Harsh/status/1032208507179806720

**Comment by colintheshots** [comment]
We can rope this issue fix into the tabs redesign. As it stands, I'm changing the FAB to load the tab switcher instead and will be putting the trash can icon on that screen.
