### ISSUE TITLE
Local storage not deleted using Erase browsing history

### ISSUE THREAD

**Issue by FocusedFox** [mozilla-mobile/focus-android#3207]
Local storage not deleted using Erase browsing history

## Steps to reproduce

- Open a website storing data in Local storage (tested with site added to Home screen)
- Send application to background (using home button)
- Tap Firefox Klar notification (Erase browsing history)
- Wait a bit (without this step, at least indexedDB is not cleared)
- Open the same website and observe data previously stored still present

### Expected behavior

Empty Local storage after erasing history

### Actual behavior

Local storage preserved after erasing history

### Device information

* Android device: Android 7.1.2 (LineageOS)
* Focus version: 6.1.1 (org.mozilla.klar from F-Droid)

### Additional information

Other ways of erasing browser history also trigger this bug, but exact behavior may differ.

**Comment by bbinto** [comment]
@colintheshots to confirm if this only happens in WebView and not GeckoView (this will help us prioritize for next triage)

**Comment by gab12** [comment]
Yes, I was very surprised to find all the history of my browsing over several months in the directory web_app / LocalStorage / leveldb
With this problem firefox focus can not claim a good protection of  our privacy.
Focus version : 8.0.5

**Comment by vesta0** [comment]
Moving to GeckoView will fix this.
