### ISSUE TITLE
unknown URI schemes are failing on focus andorid

### ISSUE THREAD

**Issue by xuyuehang** [mozilla-mobile/focus-android#3210]
## Steps to reproduce
1.enter baidu.com in url bar
2.Baidu home page is first loaded, randomly jump to baiduboxlite:// link
3.Focus can't understand this URL, which makes Baidu actually inaccessible.
![default](https://user-images.githubusercontent.com/17559985/44575960-f7a24880-a7bf-11e8-918d-6a5c7da01b5c.png)

### Expected behavior
Baidu homepage or other pages that try to call up the naive app on the page can access normally.

### Device information

* Android device: Android 8.0 Sumsang S7
* Focus version: 7.0

**Comment by bbinto** [comment]
We should check with the security/privacy engineers how to approach the solution.

**Comment by cpeterso** [comment]
I think this issue will be fixed by [GeckoView bug 1478171](https://bugzilla.mozilla.org/show_bug.cgi?id=1478171). That fix will be uplifted to the GeckoView 62 release branch.

**Comment by ekager** [comment]
There was a fix for this in the 62 Rel Branch, but the fix is being backed out for causing log in issues. See https://bugzilla.mozilla.org/show_bug.cgi?id=1478171 for history
