### ISSUE TITLE
Visited links not cleared after erase

### ISSUE THREAD

**Issue by thebnich** [mozilla-mobile/focus-android#322]
STR:
1. Do a search for "foo".
2. Tap any link.
3. Hit erase.
4. Repeat the search for "foo".

The link is purple. We should be clearing all user data after each erase.

**Comment by ahunt** [comment]
Huh, I've noticed that restarting the app does succesfully clear the link colouring data. (Maybe they're kept in memory, maybe something else is happening.)

**Comment by ahunt** [comment]
Even if I manually wipe _all_ on-disk data while focus is running (except for shared_prefs), the link colouring still happens (until I restart the app).

(adb shell, run-as org.mozilla.focus.debug, rm -rf everything except shared_prefs)

It's possible that WebView's destroy() fixes this, however we currently only do that when the WebFragment gets destroyed (and I don't know if we can force fragment destruction).

**Comment by ahunt** [comment]
destroy() doesn't help either. (It gets run if you press back to exit from the browser, instead of using the erase button.)

(Unassigning for now - I'm not too sure what other options we can try, short of force-restarting the app when erase'ing().)

**Comment by ahunt** [comment]
I've done some more digging (TL;DRL version is: no progress : / ):

The only java way in to the visited links storage seems to be via WebChromeClient.getVisitedHistory(), which is called every time a new WebView is created.

However that only adds to the visited links list, which is stored in C++ land:
https://chromium.googlesource.com/chromium/src.git/+/d0ef9df6be5983f6df7e4e050bbad4eb5030e7a2/android_webview/browser/aw_browser_context.cc#140
and actual storage:
https://github.com/adobe/chromium/blob/master/chrome/browser/visitedlink/visitedlink_master.cc

We'd somehow need to call VisitedLinkMaster::DeleteAllURLs(), and I haven't found any paths that let us trigger that from Java.

The clearHistory() call ends up somewhere completely different:
https://github.com/cvsuser-chromium/chromium/blob/master/content/browser/android/content_view_core_impl.cc#L1194
which calls into the navigation history for a given view - i.e. doesn't help with clearing the in memory visited links list.

**Comment by ahunt** [comment]
As mentioned on IRC:
- visited_links is stored in chromium in C++, it's part of the BrowserContext
- BrowserContext is a singleton, stored as a C++ only global variable
- The only way of resetting visited_links at this time is to kill the entire process (there's no way to unload native code in Android it seems, and WebView doesn't offer any unloading mechanism)

One potential but annoying solution is to run WebView in a separate process from the main app, i.e.
- Create a BrowserActivity, run in a separate process using android:process=":FooBar" in <activity> in AndroidManifest.xml
- Kill the process when the Activity is being closed using: android.os.Process.killProcess(android.os.Process.myPid());
This solution works for clearing visited links, but would require substantial modifications to the existing app (we currently use a Fragment for the browser, and we expect various pieces of data to be available, which we'd need to reinitialise for a separate process).

An alternative suggestion is:
- Short-term: inject JS to disable link colouring (I'm not sure how reliable this would be though)
- Long-term: ask chromium to fix visited link clearing (I'm filing a bug with detailed information right now, the fix should be simple), and wait for that to land.

Given the amount of rework the first option requires, I'm increasingly thinking the second suggestion is what we should try.

**Comment by ahunt** [comment]
The chromium bug that I filed:
https://bugs.chromium.org/p/chromium/issues/detail?id=709627&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

**Comment by ahunt** [comment]
FWIW deleting all css rules containing `:visited` is enough to disable link colouring. Making that robust is trickier. For testing I've been running code that removes `:visited` after onPageFinished(), which means that links show as coloured until loading finishes.

This approach doesn't work for unstyled links - the vast majority of websites seem to style everything, but that means that this approach isn't bulletproof.

There doesn't seem to be any java-side API to detect when every single stylesheet finishes loading. One basic option would be to repeatedly run the cleanup code every N ms during loading, I'm still looking into detecting loading of individual resources (and/or dynamic stylesheet changes) using JS.

**Comment by ahunt** [comment]
As discussed in triage, I think we want to land the JS version to see how reliable it is. I still need to get performance numbers, since iterating over all links every time a resource is loaded doesn't seem all that efficient.

**Comment by ahunt** [comment]
We should also add tests to make sure that we don't accidentally break this code. IIRC we can debug what's in a webview, so we can possibly check what's going on that way.

(Alternative idea: create a super simple test page with only one large link, take screenshots to ensure link colouring hasn't been performed.)

**Comment by pocmo** [comment]
A side effect of the JS workaround will be that we will not have visited links highlighted for the *current* browsing session too, right?

**Comment by ahunt** [comment]
Yes - the current solution disables all :visited css styles, so you won't have any visited link colouring.

Unfortunately the chromium bug doesn't seem to be going anywhere, beyond being triaged into a P2 list with 33k other items.
