### ISSUE TITLE
Switching tabs clears other open tabs webpage / content and reverts to about:blank

### ISSUE THREAD

**Issue by Reporter1** [mozilla-mobile/focus-android#3220]
## Steps to reproduce
Open page www.google.com, hold on a URL e.g. sign in and from menu select open in new tab, new tab will open the URL, when you click on the purple erase / switch tab bubble and select / switch to the other tabs, the page will instead load about:blank and not the original tab web page.
### Expected behavior
To go back and forth, swtich between tabs and see the webpage that was open.
### Actual behavior
Switching tabs loads about:blank page and not the website.
### Device information
Huawei P20 Pro, 
* Android device: 8.1
* Focus version: Gecko 7.0, build #322371206 62.0.20180823143155

**Comment by ekager** [comment]
Hi @Reporter1, thanks for filing! We're aware and working on this issue and #3206 will address it.
