### ISSUE TITLE
Remove language code in the 2nd "Mozilla Privacy Policy" link of the Focus Privacy Notice

### ISSUE THREAD

**Issue by Mozinet-fr** [mozilla-mobile/focus-android#3221]
## Steps to reproduce

With a French Focus go to the Settings > Mozilla > Privacy Notice. The [Firefox Focus Privacy Notice](https://www.mozilla.org/en-US/privacy/firefox-focus/) page opens. Go to bottom and tap on [Back to Mozilla Privacy Policy](https://www.mozilla.org/en-US/privacy/) link.

### Expected behavior
The [French version](https://www.mozilla.org/fr/privacy/) of the Privacy Notice must open like with the first [Mozilla Privacy Policy](https://www.mozilla.org/privacy/) link in the same page.
### Actual behavior
The second link opens the en-US version as it still have the en-US code in its URL.

### Device information
* Android device: Android 8.0.0
* Focus version: 7 (build #322341805)

**Comment by bbinto** [comment]
@ekager to describe potential solutions
