### ISSUE TITLE
Home screen tool tip has extra whitespace

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#3224]
One of the tooltips has extra whitespace on the left of the text which is clickable so it looks odd. See the screenshot below.

### Expected behavior
```
Menu > Add to Home screen
```

### Actual behavior
```
    Menu > Add to Home screen
```

### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: 7.0 (Build #322341805)

![screenshot_20180827-000835](https://user-images.githubusercontent.com/1370580/44640312-04c16200-a98f-11e8-9490-fbf706cb85af.png)

**Comment by jonalmeida** [comment]
Related to #3151?

**Comment by boek** [comment]
A fix has landed and once they get re-translated it will be fixed :)
