### ISSUE TITLE
Consider going directly to website when clicking on a URL in search suggestions

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3232]
### Why/User Benefit/User Problem
Users may type in websites and get search suggestions completing to that website (e.g. type "facebook" and "www.facebook.com" will show up in the search suggestions). However, clicking them will do a search for that website (e.g. https://duckduckgo.com/?q=http%3A%2F%2Fwww.facebook.com%2F&t=hi&ia=web). They probably wanted to go directly to the website: maybe we should do that for them?

There may be privacy/security risks here in taking that extra step though.

**Comment by bbinto** [comment]
@ekager suggested we might be able to parse the search string and handle URLs differently.

product to check reviews for any issues reported.
