### ISSUE TITLE
No more custom tabs in beta (regression)?

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#3245]
While we haven't even enabled GV in Beta, we should confirm that this is really a bug/issues/regression?

<img width="741" alt="screen shot 2018-08-29 at 7 36 35 am" src="https://user-images.githubusercontent.com/122897/44785277-5bc96180-ab5e-11e8-8e7c-d81d6def1ee4.png">

**Comment by bbinto** [comment]
@bbinto to reach out to user and confirm how to set their default browser to Focus.

**Comment by ekager** [comment]
Closing I don't think this is a bug
