### ISSUE TITLE
Focus app switcher screenshot not cleared after turning off screen

### ISSUE THREAD

**Issue by thebnich** [mozilla-mobile/focus-android#325]
STR (not 100% reproducible, but usually happens):
1. Go to any site.
2. Turn screen off and back on.
3. Open the app switcher.

The Focus screenshot should be cleared to white, but the site is still shown in the screenshot.

**Comment by pocmo** [comment]
Which build type are you using? We only hide the app content in the app switcher in beta and release builds.

**Comment by thebnich** [comment]
Beta. Worth noting that app content does correctly hide in normal cases (e.g., just pushing home or opening the app switcher without turning off the screen).

**Comment by pocmo** [comment]
@thebnich Can you try to reproduce this with the latest beta? We are not setting the window flag earlier in the activity life cycle. Unfortunately I haven't been able to reproduce this at all on my device.

**Comment by thebnich** [comment]
Yep, still reproducible:

![screenshot_20170331-135222](https://cloud.githubusercontent.com/assets/1093266/24569081/63338c7e-1619-11e7-9d73-a6426fa22e9d.png)

**Comment by pocmo** [comment]
This seems to be a bug in some Android versions. I'm not able to reproduce this on Android 7+. Related Android bug:
https://issuetracker.google.com/issues/37096132

There's no way for us to fix this on our site but we want to outline this problem on a SUMO page.
