### ISSUE TITLE
Remove search engines doesn't work

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3254]
## Steps to reproduce
1. Go to Settings>Search>Default search engine.
2. Tap the 3 dots button and select Remove.
3. Select the search engines you want to remove.

### Expected behavior
A checkbox is displayed for each engine to tap the ones you want to remove.

### Actual behavior
The checkboxes aren't displayed and can't select any of the installed engines.

### Device information
Google Pixel (Android 9)
LG Nexus 5 (Android 6.0.1)

* Focus version: 7.0

**Comment by SubhrajyotiSen** [comment]
I am taking a go at this
