### ISSUE TITLE
Switching out and back while changing the address breaks the UI

### ISSUE THREAD

**Issue by initrd** [mozilla-mobile/focus-android#3270]
## Steps to reproduce
1. Open any site, say https://duckduckgo.com/
2. After the site loads, tap on the address bar
3. Type anything, ex: mozilla.org
4. Without hitting Enter, press the Recent Apps button and switch to a different app
5. Switch back to Focus

### Expected behavior
Address bar is only populated with "mozilla.org"

### Actual behavior
"mozilla.org" is overlayed over https://duckduckgo.com/
Additionally half the address bar background is black now

![screenshot_20180831-135338](https://user-images.githubusercontent.com/1941695/44935624-51f25a80-ad26-11e8-838e-143ce272143c.png)

### Device information

* Android device: Google Pixel, Android 9.0
* Focus version: 7.0 (Build #322411212 🦎 62.0.20180823143155)

**Comment by initrd** [comment]
This bug can also be reproduced by tapping on an address in the address bar, and switching out and back to Focus.

**Comment by ekager** [comment]
Is this fixed for you in the latest Nightly from today?

**Comment by initrd** [comment]
I can no longer reproduce this bug. Thx, @ekager!
