### ISSUE TITLE
Menu changes position when rotating from portrait to landscape

### ISSUE THREAD

**Issue by BogdanSurd** [mozilla-mobile/focus-android#3287]
## Steps to reproduce
1. Open Focus and tap on the 3 dot menu
2. Rotate the device from portrait to landscape

### Expected behavior
* The menu holds it's position.

### Actual behavior
* The menu moves inward (to the left).

### Device information
* Android device: Nexus 5 (6.0.1), LG G4 (6.0.1), Nokia 6 (7.1.1)
* Focus version: Focus 7.0 Beta 2 (322341804)
* Android 8 and 9 do not seem to be affected by this, tested on a Pixel and Galaxy S8.

![screen](https://user-images.githubusercontent.com/17178945/44979028-b86cb800-af74-11e8-90b4-f4d4e54d19ae.png)

**Comment by rpappalax** [comment]
unable to repro on:

* Android device:  Nexus 6p, Android 8.0.0
* Focus version: v7.0 (Build #11)

**Comment by BogdanSurd** [comment]
@rpappalax It's more related to the Android version of the device rather than the actual device, as I've mentioned, Android 8 and Android 9 devices do not seem to be affected by this issue, only managed to reproduce it on devices with Android version < 8.
