### ISSUE TITLE
Add about:crashes to show crashes

### ISSUE THREAD

**Issue by BogdanSurd** [mozilla-mobile/focus-android#3289]
## Steps to reproduce
1. Crash Focus
2. Go to about:crashes

### Expected behavior
about:crashes is displayed in order to get the crash report.

### Actual behavior
The user is redirected to about:blank instead of the about:crashes page. 

### Device information

* Android device: Nexus 5 (6.0.1), Galaxy S8 (8.0), Pixel (9)
* Focus version: Focus 7.0 Beta 2 (322341804)

**Comment by ekager** [comment]
We don't implement about:crashes currently, changing this to a feature request

**Comment by BogdanSurd** [comment]
@ekager I would like to mention that I did manage to access the about:crashes page on some devices when there was no crash for Focus, after a crash, about:crashes always redirected to about:blank on the respective device.

**Comment by ekager** [comment]
Ah GV implements about:crashes so if you're on a GV build this will work, and on a WV build it will go to about:blank. It's possible that the real bug is after a crash, you were switched to a WV build

**Comment by colintheshots** [comment]
I believe this may happen if the user set the engine preference to GeckoView with an override and shared preferences are wiped.

**Comment by ekager** [comment]
I'm closing this because I think the main issue here was switching between GV+WV. about:crashes is in GV and not implemented by Focus
