### ISSUE TITLE
Focus crashes when restoring default search engines

### ISSUE THREAD

**Issue by BogdanSurd** [mozilla-mobile/focus-android#3290]
## Steps to reproduce
1. Add a new search engine in installed search engines (eg. bing)
2. Remove a couple of search engines
3. Select the newly added search engine (bing)
4. From the menu tap on "Restore default search engines"

### Expected behavior
Default search engines are restored

### Actual behavior
App crashes

### Device information
* Android device: Nexus 5 (6.0.1), Galaxy S8 (8.0), Pixel (9)
* Focus version: Focus 7.0 Beta 2 (322341804)

### Notes
Can't get a crash log since about:crashes takes me to about:blank logged [3289](https://github.com/mozilla-mobile/focus-android/issues/3289) for this

[Video](https://youtu.be/1fwmTFJoSK4)
[logcat](https://github.com/mozilla-mobile/focus-android/files/2345486/log.txt)

**Comment by sblatz** [comment]
This appears to be fixed by #3277
