### ISSUE TITLE
JavaScript not enabled in GeckoView

### ISSUE THREAD

**Issue by BogdanSurd** [mozilla-mobile/focus-android#3292]
## Steps to reproduce
1. Go to focus:test and turn on GeckoView
2. In Settings > Privacy&Security set Block Cookies to Yes
3. Go to [WhatIsMyBrowser](https://www.whatismybrowser.com/detect/are-cookies-enabled) 

### Expected behavior
In the Are Cookies enabled/allowed? section, "No" is displayed.

### Actual behavior
In the Are Cookies enabled/allowed? section, "JavaScrips is not enabled." is displayed

### Device information

* Android device: Samsung Galaxy S8 (Android 8)
* Focus version: Focus 7.0 Beta 2 (322341804)
* With GeckoView turned off the issue is not reproducible
* This issue does not seem to reproduce on other devices

![screen](https://user-images.githubusercontent.com/17178945/44990404-92a5da00-af99-11e8-93e4-f58171a2555e.png)

**Comment by ekager** [comment]
And "Block JavaScript" in settings is turned off?

**Comment by BogdanSurd** [comment]
Yes "Block JavaScript" is turned off in "Privacy & Security".

**Comment by ekager** [comment]
Looks like it's their site's tests, if you go to the JS specific site, it looks fine to me :) Closing, but please reopen if it's still an issue
https://www.whatismybrowser.com/detect/is-javascript-enabled
