### ISSUE TITLE
"Report site issue" no longer displayed in Beta 2 - GeckoView build

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3293]
## Steps to reproduce
1. Turn on GeckoView on focus:test.
2. Open a website.
3. Open the main menu and check "Report site issue" is displayed.

### Expected behavior
"Report site issue" is displayed on GeckoView builds.

### Actual behavior
On the 7.0 Beta 2 GeckoView build, the link is not displayed.
Not reproducing on Nightly build #322411212.

### Device information
* Android device: Pixel (Android 9), Sony Xperia Z5 Premium (Android 6.0.1)
* Focus version: 7.0, Beta 2 build#322341804

**Comment by ekager** [comment]
FYI the focus:test toggle can be finicky, I recommend checking focus:about after using the toggle to make sure you're on GV. It maybe just didn't correctly switch? If you're still seeing this, I can verify tomorrow.

**Comment by sv-ohorvath** [comment]
That is probably the problem. I'm assuming I have to see the gecko icon next to the build. How can I make the toggle work? I'm restarting the browser but it doesn't have any effect.

**Comment by sv-ohorvath** [comment]
LE: Couldn't turn on the GV build on Pixel (Android 9) and on an LG Nexus 5 (Android 6.0.1). 
But we were able to do it on the first try on 2 Samsung devices and now I can confirm this issue isn't valid. Thanks!
