### ISSUE TITLE
No popup for taking a screenshot is displayed with Stealth mode enabled

### ISSUE THREAD

**Issue by BogdanSurd** [mozilla-mobile/focus-android#3294]
## Steps to reproduce
1. Go into Settings > Privacy & Security
2. In the Switching Apps section enable Stealth
3. Go to any webpage and try to take a screenshot

### Expected behaviour
A notification is displayed informing the user that he cannot take a screenshot

### Actual behaviour
No notification is displayed to inform the user that a screenshot cannot be taken

### Device information
* Android device: Nexus 5 (6.0.1), Sony Xperia Z5 Premium (6.0.1)
* Focus version:  Focus 7.0 Beta 2 (322341804) & Nightly build (322411212)
* Galaxy S8 (8) & Pixel (9) are not affected by this

**Comment by iammangod96** [comment]
Moto G4 plus is also not affected by this.

**Comment by sblatz** [comment]
I'm unable to reproduce this on my Moto G4 play running 6.0.

@BogdanSurd are you able to confirm that the notification doesn't appear in the notification tray silently (without a popup?)

**Comment by ekager** [comment]
This sounds like a System issue; all we do when we enable Stealth/Secure Mode is get the Window and set WindowManager Flags.

**Comment by BogdanSurd** [comment]
@sblatz Yes, a silent tray notification is visible, was expecting a snackbar type of notification like I received on the S8 and Pixel. If this is the desired behaviour I shall update the test cases accordingly to match the expected results.

**Comment by sblatz** [comment]
As @ekager mentioned, this is a dialogue controlled by the system. It seems that in older versions of android, the silent tray notification is all that is served (whereas newer versions also give a snack bar notification). Because of this, I think it's safe to update the test to have this be the expected result. Thanks for confirming, @BogdanSurd!
