### ISSUE TITLE
Send usage data is enabled by default

### ISSUE THREAD

**Issue by BogdanSurd** [mozilla-mobile/focus-android#3295]
## Steps to reproduce
1. Go to Settings > Privacy & Security
2. Scroll down to the Data Choices section

### Expected behavior
Send usage data is disabled by default

### Actual behavior
Send usage data is enabled

### Device information
* Android device: Nexus 5 (6.0.1), Sony Xperia Z5 Premium (6.0.1), Galaxy S8 (8), Pixel (9)
* Focus version: Focus 7.0 Beta 2 (322341804) & Nightly build (322411212)

**Comment by ekager** [comment]
Focus has usage data enabled by default, and Klar does not. I believe you're using 2 Focus builds?

**Comment by BogdanSurd** [comment]
Thank you for the clarification, indeed I was using Focus builds since those were the ones we were testing. Closing this issue and will update the test case accordingly to match differences between Klar and Focus builds.
