### ISSUE TITLE
No return path after tapping on ℹ️ while adding a custom search engine

### ISSUE THREAD

**Issue by initrd** [mozilla-mobile/focus-android#3297]
## Steps to reproduce
1. Open Settings > Search > Installed search engines > + Add another search engine
2. Add a name "Test"
3. Optionally, type anything for the Search string
4. Tap on the ℹ️ in the top-right
5. A SUMO page opens
6. Press back

### Expected behavior
I am back to where I left off while adding a search engine

### Actual behavior
Dropped to the main page, custom search form data is lost

### Device information

* Android device: Google Pixel, Android 9.0
* Focus version: 7.0 (Build #322461206 🦎 62.0.20180829133835)

**Comment by ekager** [comment]
Now that we're launching InfoActivity intents for about and rights we could use that method for this link as well so that there could be a "back" path.
