### ISSUE TITLE
Replace WebView error pages with custom ones

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#33]

**Comment by ahunt** [comment]
@antlam : do you have any design plans for error pages? I've made a 1:1 copy of the iOS error page for now.

We'll probably need to provide our own error text, if we want to support API 21+ we only get messages like "net::ERR_NAME_NOT_RESOLVED". (API 23+ provides another callback which supplies strings such as "There was a network error.")

**Comment by antlam** [comment]
I was thinking we should just use the same error pages we currently have in Fennec.

But instead of a light grey background, just use the private browsing grey #363B40 as the background, but use white text.

Thoughts?

**Comment by ahunt** [comment]
If we use the fennec pages, we could import all the strings 1:1 from fennec (which would save localisation effort), but the search boxes and wifi buttons seem to be hardcoded into the translateable content which makes that a bit harder.

Here's a list of all the strings that fennec uses:
https://dxr.mozilla.org/mozilla-central/source/mobile/locales/en-US/overrides/netError.dtd

**Comment by ahunt** [comment]
Current status:
![focus_error](https://cloud.githubusercontent.com/assets/1546915/23612623/69088d58-027c-11e7-96e4-fc3ba911e28f.png)

**Comment by antlam** [comment]
Nice! @ahunt Can we make the button the same blue that's in our Settings?

**Comment by ahunt** [comment]
@antlam:
![focus_error2](https://cloud.githubusercontent.com/assets/1546915/23761864/8a890550-04f4-11e7-973f-67df7f4065a4.png)

**Comment by antlam** [comment]
@ahunt final nit - can we remove that / / / / / / / image but keep the same spacing? That is "Server not found" should stay in the same position.

**Comment by ahunt** [comment]
Voila:
![error3](https://cloud.githubusercontent.com/assets/1546915/23941607/b572910e-0969-11e7-8df2-f9213b8c86e9.png)

**Comment by antlam** [comment]
Ship it!
