### ISSUE TITLE
Handle long press on email or phone number

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#330]
_Added by @bbinto_

**Why/User Benefit**
- Allow users to perform additional tasks that require opening other apps
- Allow users to call a phone number quickly from Focus
- Allow users to email an email address quickly from Focus

**What**
- Long press on email/address/phone number to take action

**Acceptance Criteria (how do I know when I’m done?)**
- Long press on email allows to open mail app
- Long press on phone number allows to open phone app
- Probe to track that phone app or mail app was being opened

----
Taken from #303:
We can detect clicks and long presses on links (with differentiation for images that are links). We've added support for links in #303, but we could also add support for the following things:
- Email addresses
- Map/Geo addresses
- Images
- Phone numbers

Do we want to show anything for these types? Apart from Images, I don't think Fennec does anything special (we'd usually expect email addresses to be tagged as links, in which case we already offer opening an email client, but the other cases aren't standard I think).

List of types:
https://developer.android.com/reference/android/webkit/WebView.HitTestResult.html

(I'm guessing WebView just does some simple tests to detect whether a given piece of text is an address/phone number.)

**Comment by bbinto** [comment]
@ekager to file a bug with GeckoView API team

**Comment by ekager** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1468515

**Comment by ekager** [comment]
There is already a GV API for this - `onContextMenu` API that you can use to parse the long pressed URI for email/phone. We will have to do the parsing ourselves (WebView tells us the hit type) but shouldn't be too complicated.

**Comment by bbinto** [comment]
So is this something we *could* actually ship for 7.0? @ekager ?

**Comment by bbinto** [comment]
@mikailmikhail, are you still interested in working on this issue? We'd love to get this into the product soon and would love for you to help us with that.

**Comment by vesta0** [comment]
Current behaviour (both on 6.1.1. and beta 7.0.2 running on GW) is that tapping on phone number opens the and tapping on email links opens the a prompt to open the mail app. Will move this lower on the priority list and go back to it later if we want to explore long press options.
