### ISSUE TITLE
Make the "Open link in new tab" to just open a new tab, not also navigate to it 

### ISSUE THREAD

**Issue by BogdanSurd** [mozilla-mobile/focus-android#3300]
### Why/User Benefit/User Problem
The current implementation opens the link and takes the user directly to the newly opened tab. This can be annoying if the user wants to open multiple tabs and then navigate to each of them separately. 

The action should just open a tab and let the user say on the current page. Maybe a toggle could be implemented for the option in Setting. That way both functionalities still exist.

**Comment by bbinto** [comment]
@brampitoyo - could you please let us know your take on that?

**Comment by brampitoyo** [comment]
@BogdanSurd Somehow we overlooked this as we designed multitasking a year ago. Thanks for bringing it up.

I think that our default behaviour should avoid switching to a new tab. When we switch, we also **make you wait in an empty page while the site loads.**

Instead, when a tab has been opened, we should show a toast on the bottom of the screen that says:

> New tab opened &nbsp; &nbsp; &nbsp; [Switch]

You can switch if you like, but it’s not the default.

And, yes. We should have a toggle under settings – although I think it should be a checkbox. We can use the same strings that Firefox for Desktop uses:

> When you open link in a new tab, switch to it immediately

**Comment by SubhrajyotiSen** [comment]
@brampitoyo  The correct widget to be used would be a SnackBar instead of a Toast right? Since Toast just displays information whereas a SnackBar should be used when expecting user input

**Comment by brampitoyo** [comment]
@SubhrajyotiSen That’s correct. I made a terminology error. The notification and action should appear in a [snackbar](https://material.io/design/components/snackbars.html#), not a toast.
