### ISSUE TITLE
Crash when tapping "Listen" buttons

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3303]
## Steps to reproduce
1. Search for an artist on Google (e.g. "Frank Ocean")
2. Tap one of the following "listen" buttons that appears in the results: Spotify, Deezer, or Pandora

### Expected behavior
Focus asks if you want to open in another app

### Actual behavior
Focus crashes 
![crash 2018-09-04 10_40_25](https://user-images.githubusercontent.com/4400286/45038296-f4fcea00-b02e-11e8-9e5d-e2154d8cb6fc.gif)

### Device information
* Android device: Pixel 2XL
* Focus version: 7.0 Build 11 (WebView)

I believe this may be due to us not properly handling apps that are _not installed_ on the device, as it doesn't crash when using YouTube or Play Music.

**Comment by ekager** [comment]
I can't repro this using master + WV or GV I'm getting the popup that takes me to the Play Store for both builds. If you want to do some testing this is in `handleUnsupportedLink` in `IntentUtils`
