### ISSUE TITLE
Focus:test resets to "off" on re-compile (though toggle says it's on)

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3305]
## Steps to reproduce
1. Enable GeckoView in Focus:test
2. Re-compile Focus

### Expected behavior
Focus:test shows that GeckoView is still enabled and it actually _is_

### Actual behavior
Focus test shows that GeckoView is enabled but in actually it _is not_.

This can be really confusing as a dev when testing GeckoView specific bugs.

**Comment by sblatz** [comment]
Perhaps @colintheshots has some insight into why this is happening.

**Comment by colintheshots** [comment]
Focus:test defaults off on re-compile because that's the default setting in dev before we've been to the experiments server to retrieve experiments. I'm not sure why the toggle defaults to on though. The experiment should be off right now. I'll look into it.

**Comment by colintheshots** [comment]
In testing with the latest master, I cannot reproduce this behavior. I had seen it in the past, however. I wonder if the issue is related to the android-components version, since we're calling Fretboard.isInExperiment to set the toggle.

**Comment by sblatz** [comment]
This is what's happening on the latest master

[Demo](https://youtu.be/2u3SfEt52Hg)

**Comment by colintheshots** [comment]
Instant Run is never, ever, ever a legit use case. Not even close. It's broken even for quite a bit of development.
