### ISSUE TITLE
Reenable Safe Browsing in GV

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3309]
GV Team is still working on finishing Safe Browsing API, we will turn it off in #3236 while they finish, this bug is to remember to turn it back on when it's done.

**Comment by ekager** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1462000

**Comment by kbrosnan** [comment]
I would expect that Focus or Android Components would need to provide some nice UI. In every browser that provides this feature there is a description explaining why the page is blocked.

**Comment by cpeterso** [comment]
Good point. The Safe Browsing warnings should probably be part of the [ErrorPages Android component](https://github.com/mozilla-mobile/android-components/tree/master/components/browser/errorpages). Integrating ErrorPages is Focus issue #2471.

**Comment by cpeterso** [comment]
@snorp says GV 63 returns the correct Safe Browsing error codes to the app, but the app is responsible for showing its own error pages.

**Comment by cpeterso** [comment]
This bug can't be fixed in Sprint 6 because it depends on Safe Browsing support in GV 63, which won't be released until [October 23](https://wiki.mozilla.org/Release_Management/Calendar#Calendars).

**Comment by ekager** [comment]
Thanks Chris, moved it to the backlog

**Comment by cpeterso** [comment]
Eugen says Focus will need to:
1. Hook up the settings UI to the new GeckoRuntimeSettings blockMalware and blockPhishing.
2. Handle the ERROR_SAFEBROWSING_* codes in onLoadError to show custom error pages.

**Comment by cpeterso** [comment]
[Firefox's Safe Browsing code](https://searchfox.org/mozilla-central/rev/c9272ef398954288525e37196eada1e5a93d93bf/toolkit/components/url-classifier/SafeBrowsing.jsm#482-491) adds the following test URLs to Firefox's Safe Browsing blocklist. These URLs are not in Google's Safe Browsing blocklist.

https://itisatrap.org/firefox/its-a-trap.html
https://itisatrap.org/firefox/its-an-attack.html
https://itisatrap.org/firefox/unwanted.html
https://itisatrap.org/firefox/harmful.html
