### ISSUE TITLE
Additional default privacy categories (feature parity with desktop)

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#3319]
### Why/User Benefit/User Problem
Provide further privacy/security related features to Focus

### What / Requirements
Consider providing users the same benefits that have been recently added to Desktop (https://venturebeat.com/2018/08/30/mozilla-announces-firefox-will-block-trackers-by-default/)

**Comment by vesta0** [comment]
FYI the new privacy defaults being added to Desktop are:

-Blocking slow-loading trackers by default (third-party content that takes longer than 5 seconds to load)
-Removing cross-site tracking through third-party cookies
-Blocking trackers that fingerprint users and cryptomining scripts
