### ISSUE TITLE
Add URI count to telemetry

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#3320]
### Why/User Benefit/User Problem
- product and data scientist need URI count for future A/B testing and validation of regression (similar to Desktop)

/cc @mmccorks

**Comment by ekager** [comment]
To clarify, this is the # of URIs visited in a session? Is this high priority?

**Comment by bbinto** [comment]
Correct, @ekager - the Desktop team uses that metric for any experiments/regression in usage.

Can you provide an T-shirt estimate, and I tell you the priority :)

**Comment by ekager** [comment]
This would be a small

**Comment by bbinto** [comment]
Would the engineer who will be working on this please also check with Frank on how to get this into the datapipeline/redash.

**Comment by ekager** [comment]
Since this is a new telemetry event we also need a data review @bbinto ? https://github.com/mozilla/data-review/blob/master/request.md

**Comment by ekager** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

* Establish baselines or measure changes in product or platform quality or performance.

* Provide information essential for advancing a business objective such as supporting OKRs.

* Determine whether a product or platform change has an effect on user or browser behavior.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

4) Can current instrumentation answer these questions?

5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>


6) How long will this data be collected?  Choose one of the following:

* This is scoped to a time-limited experiment/project until date MM-DD-YYYY.

* I want this data to be collected for 6 months initially (potentially renewable).

* I want to permanently monitor this data. (put someone’s name here)

7) What populations will you measure?

* Which release channels?

* Which countries?

* Which locales?

* Any other filters?  Please describe in detail below.

8) If this data collection is default on, what is the opt-out mechanism for users?

9) Please provide a general description of how you will analyze this data.

10) Where do you intend to share the results of your analysis?

**Comment by ekager** [comment]
CC @bbinto / @vesta0 could one of you provide more information about why we're collecting this data in the form above?

**Comment by bbinto** [comment]
@ekager - we want to use this metric, like the Desktop team, to understand if any changes to the product (e.g. GV, other features) will increase/decrease the URI count = corresponding to the engagement with the app. Hope that helps.

**Comment by ekager** [comment]
Tagging @liuche for data review :)

**Comment by ekager** [comment]
@Sdaswani @bbinto @vesta0 should the TOTAL_URI_COUNT value max at 100 as well?

**Comment by bbinto** [comment]
@ekager, why should/would we need a "low" max for this? Do we know what desktop is doing?

**Comment by ekager** [comment]
I don't know what/why desktop is doing, we're just sending a number as a string so there's no technical restriction for the max. Would you like me to remove the max for Focus' version? @bbinto @Sdaswani @vesta0

**Comment by Sdaswani** [comment]
Yes, remove the max as a string can't too too big.

**Comment by bbinto** [comment]
Thanks @ekager - I was under the impression that's something stored in the core ping.
