### ISSUE TITLE
Create a telemetry dashboard for GeckoView vs WebView experiment

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#3325]
### Why/User Benefit/User Problem
We want to compare GeckoView vs WebView in a Focus 7.0 Beta test.

### What / Requirements
We want to limit the dashboard to Focus version 7.0.x (x >= 1) so we are only querying beta users with the latest GeckoView version.

Telemetry probes we would like to monitor:
* DAU
* 1-day retention
* 7-day retention
* [Page Load Time Histogram](https://github.com/mozilla-mobile/focus-android/wiki/Telemetry#page-load-time-histogram) (to see if GeckoView page load time is slower than WebView)
* Total session time (to see if GeckoView users browse less than WebView users)
* Crash pings (if they are available)

[GeckoView vs WebView experiment PHD](https://docs.google.com/document/d/1S-IBJWwVG38oCqDfqiE-xzQbLk18T7haucg7gttGDDc/edit)

### Acceptance Criteria (how do I know when I’m done?)
We will have a dashboard with graphs showing recent data comparing Focus 7.0 users running GeckoView and WebView.

CC @mmccorks and @bbinto

**Comment by bbinto** [comment]
Looks good to me, nothing to add for now, @mmccorks.

We should have that dashboard with all these graphs ready (except the new app / version number to define 7.0.1) before we enable GV to 50% of users.

**Comment by mmccorks** [comment]
In order to make these dashboards in STMO we need to add the experiments block to the focus-event ping and the core ping so that we can identify which branch the users are on (geckoview or webview). cc @frank @colintheshots

**Comment by mmccorks** [comment]
Verified we have the experiments data in the core ping, will add to the focus event ping at a later date (non blocking for these dashboards).

**Comment by mmccorks** [comment]
Here is version 1 - 
https://sql.telemetry.mozilla.org/dashboard/focus-android-beta-7-0-1---geckoview-vs-webview

We don't have crash pings and I am still working on the page load query as it is a bit more complicated. Will update as soon as possible.

**Comment by mmccorks** [comment]
Have updated with Average Page Load.

**Comment by cpeterso** [comment]
🎉 @mmccorks's [Focus Beta dashboard](https://sql.telemetry.mozilla.org/dashboard/focus-android-beta-7-0-1---geckoview-vs-webview) is live and up to date. It includes all the telemetry probes listed in the [first comment's requirements](https://github.com/mozilla-mobile/focus-android/issues/3325#issue-357381016) except for crash pings, but [@mmccorks says](https://github.com/mozilla-mobile/focus-android/issues/3325#issuecomment-419266688) the crash ping data is not available. We will have to manually monitor Focus 7.0 crash reports in the Google Play Console and Sentry.
