### ISSUE TITLE
Ignore single 'when' in methods when detekt is ran

### ISSUE THREAD

**Issue by EmmanuelMess** [mozilla-mobile/focus-android#3326]
[`ignoreSingleWhenExpression`](https://github.com/arturbosch/detekt/blob/2165019a5c7165e3c231671ae21aa6a20f51d4e1/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexMethod.kt#L24) should be set to true, so that no suppression is needed here:

https://github.com/mozilla-mobile/focus-android/blob/504f17e4a1ae55066c34f4a133a716d3d75b2f91/app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt#L355-L391

**Comment by SubhrajyotiSen** [comment]
+1
