### ISSUE TITLE
market:// url is unrecognized when typed in url textfield, and erasing history disables web access

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#333]
Entering a market:// url prompts 'unrecognized url' error page.  It used to work before https://github.com/mozilla-mobile/focus-android/commit/3f570163ecdb7d186df74d53c04d65d642900de3 . Needs input to determine whether it's a valid bug, or it's something that we can live with.  In latter case, I will update my test case accordingly.

**Comment by ahunt** [comment]
It's a very simple fix, we just try to load the URL a touch too early!

**Comment by npark-mozilla** [comment]
Actually, above fix caused an issue where after pressing erase button, no URL can be loaded- it just goes back to the main page it seems.

**Comment by ahunt** [comment]
I wonder if I broke that with this commit, since that fiddles with fragments:
https://github.com/mozilla-mobile/focus-android/commit/f0f0312bf7b1d0563d4f6bf8ed1ea25069c1b152

**Comment by ahunt** [comment]
Yeah, I've added a followup for that in:
https://github.com/mozilla-mobile/focus-android/pull/337

**Comment by npark-mozilla** [comment]
Seems like the issue is fixed now in BB
