### ISSUE TITLE
SUMO: Inform WV/GV users about safe browsing feature

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#3347]
See: https://github.com/mozilla-mobile/focus-android/issues/3236#issuecomment-418760359

### Why/User Benefit/User Problem
- Inform users that and why safe browsing is enabled for WV but not for GV

### What / Requirements
- Create SUMO article

**Comment by vesta0** [comment]
@jonisavage are you working on a SUMO article for this?

**Comment by vesta0** [comment]
@jonisavage we are looking for a brief explanation safe browsing, how it is currently enabled in WebView but not GeckoView for now (#3236). The GV team is currently working on finishing the Safe Browsing API which will be ready in a few weeks but not for this Tuesday's release.

**Comment by vesta0** [comment]
Thanks @jonisavage  :)
