### ISSUE TITLE
"preference_search_engine_default" message should be clearer

### ISSUE THREAD

**Issue by yfdyh000** [mozilla-mobile/focus-android#3362]
## Steps to reproduce
https://github.com/mozilla-mobile/focus-android/blob/6f6a313bd7f508f246d06e17898d9817c02a9933/app/src/main/res/values/strings.xml#L151
Open the focus-android - Settings - Search, see the "preference_search_engine_default" message.

### Expected behavior
It should be "Default search engine" (like `preference_search_restore`), not just the "Default", the Default may be "Software default", like the "System default" (preference_language_systemdefault).

### Actual behavior
I see the "Default" for unknown purposes, it is like a software default and allows you to change it, but the "Default" won't change after you change the setting.

### Device information

* Focus version: 7.0

**Comment by boek** [comment]
Hey @vesta0, I originally thought this was regarding changing the string description. But it appears the suggestion is to change the label under the selected search engine name.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/1250545/45389959-65c57880-b5d2-11e8-8304-c591f2f7bd95.png">

I do agree that the word "default" here seems wrong. As  it will show your currently active search engine, not the "default" one. But now this will require a bit more to fix. We will need a new string from either @brampitoyo or @BrianNJones.

I'm going to move it back into triage unless you want to push forward with it :)

**Comment by brampitoyo** [comment]
Hi @boek, I think that the string should be:

> **Search engine**
> Google

This clarifies that the selected search engine is indeed your currently active one.

What do you think, @BrianNJones?

**Comment by vesta0** [comment]
@brampitoyo I like your suggestion. Do you agree @BrianNJones ?

**Comment by BrianNJones** [comment]
@vesta0 @brampitoyo Yep. Let's go with that.
