### ISSUE TITLE
Consider Filtering Out Sentry Pings From Unsupported Devices

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3370]
When investigating #2903, it looks like this was a crash exclusive to versions lower than what Focus supports. It's possible to download our APKs on unsupported versions not through GP, and now that we're not doing Crash Reporting through GP, we're seeing these crashes that aren't prudent for us to fix. 

Maybe we should not send crash data for unsupported versions of Focus.

**Comment by colintheshots** [comment]
This is harder than it sounds. We'd need to detect API level changes from our defaults and we'd have to store the copied values elsewhere in the APK. We can't check against build.gradle, but we could maybe copy the values to the BuildConfig. Do we check if they altered other requirements besides minSdk?

**Comment by ekager** [comment]
It might not filter out clones but at least sideloaded APKs?
