### ISSUE TITLE
When website opens new tab by link, the title does not show the actual URL, but shows the link

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#3371]
## Steps to reproduce
- Open a page containing links to other pages, that possibly redirect or contain port numbers
- Open links as new tabs in background
- Go to the newly opened tab

### Expected behavior
- Tab title should be same, before and after visiting the new tab pages

### Actual behavior
- Tab title may change if the URL was a redirect, or contains port number

When the background tab is brought to foreground by selecting it, then the tab titles are changed to include the port number.

@ekager explained it to me that when tabs are opened in background, the pages are not actually accessed - only the link is used to display the tab title.  When the page is actually visited, that's when we know about the port number, and it updates the tab entry title in the list.

So it comes down to the fact that the tab title might change when it is actually opened, from when it was opened in the background.  
### Device information

* Android device: 
Pixel 2
* Focus version: 
7.0

Please close if it's not an issue.

**Comment by lobontiumira** [comment]
I was not able to reproduce this scenario on the 12/29 Focus Nightly build using a Google Pixel (Android 10).
Opening several tabs in the background, and tapping on the tabs counter displays the title of the new tabs correctly, even when those pages were not accessed yet.
