### ISSUE TITLE
Open in new tab title should have a shorter string

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3373]
Currently our "open in new tab" settings option has a really long title. It'd be better if this title was shorter and included a summary of what the toggle does. 

Here is our implementation right now:
<img width="300" alt="screen shot 2018-09-11 at 10 07 09 am" src="https://user-images.githubusercontent.com/4400286/45365582-d48edb80-b5aa-11e8-815a-0ff6b98e1657.png">

Suggestion:
* Title: Switch to new tabs immediately
* Summary: When you open a link in a new tab, switch to it automatically

Need confirmation on strings: @BrianNJones

**Comment by vesta0** [comment]
@sblatz which version of Focus is this?

**Comment by sblatz** [comment]
@vesta0 this is in our most recent master build. I don't believe it's on any user-facing releases yet.

**Comment by vesta0** [comment]
[Related to #5500 from Sprint 5](https://github.com/mozilla-mobile/focus-android/issues/3300)

**Comment by ekager** [comment]
This was discussed and decided positively upon here.
https://github.com/mozilla-mobile/focus-android/pull/3340#pullrequestreview-153621001

**Comment by sblatz** [comment]
@BrianNJones could we get a more succinct string for this that would convey the same message? According to the previous ticket we are going to keep it as a title.

**Comment by BrianNJones** [comment]
@sblatz , Switch to link in new tab immediately
