### ISSUE TITLE
Integrate Firefox account syncing.

### ISSUE THREAD

**Issue by samirm** [mozilla-mobile/focus-android#3374]
### Why/User Benefit/User Problem

Convenient and privacy oriented way to manage your online resources without having to constantly switch browsers on your phone. I wish I could keep track of the websites I visit on my mobile device with as much ease as it's done on desktop.

I'm not worried about "exposing" my history to someone else using the device, I'm worried about not being in control of my privacy while I browse the web.

### What / Requirements

Integrate the same feature that is available on most other Firefox browsers - being able to sign in to your account and sync data of your choosing between your devices.

### Acceptance Criteria (how do I know when I’m done?)

All relevant tests are passing.

**Comment by ekager** [comment]
Thanks for filing @samirm . I don't think this feature is on the Focus radar at this point. Could you use Firefox for Android in Private Browsing mode to get access to accounts, bookmarks, sync, etc?

**Comment by samirm** [comment]
@ekager I could... unfortunately FF for Android doesn't seem to be as privacy minded or performant as Focus :/
Welp, guess you can't have everything. Thanks for the feedback!

**Comment by jannisch** [comment]
+1
Focus is so much nicer and faster than Firefox on Android since it's native. I also want to have the best privacy when browsing but often I just discover an interesting site that I want to save to my Firefox bookmarks quickly.

**Comment by vesta0** [comment]
Thanks for the feedback. This is not on the Focus Roadmap at this time but we will keep this in mind.
