### ISSUE TITLE
Kotlin plugin should be enabled before 'kotlin-kapt'

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3375]
Run:
```sh
./gradlew tasks | grep jacoco
```

Output:
Kotlin plugin should be enabled before 'kotlin-kapt'

It appears it's a warning at the start of the gradle output and it pops out in stderr. :)

**Comment by ido-ran** [comment]
I got the same this when I've upgrade Adnroid Studio.

All I did was to swap the lines from
```
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android'
```

to
```
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
```

**Comment by gzodx** [comment]
all i had to do was decrease my kotlin version to

ext.kotlin_version = '1.3.41'
