### ISSUE TITLE
Desktop Mode should send actual Desktop UA string

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/focus-android#3378]
## Steps to reproduce

1. Open WebView Focus
2. navigate to echo.opera.com
3. select Request Desktop Site

### Expected behavior

Get a Desktop UA string

### Actual behavior

Get an *interesting* UA string... https://github.com/mozilla-mobile/focus-android/blob/7a141fe133818f36121969017ed6278d252d4766/app/src/main/java/org/mozilla/focus/web/ClassicWebViewProvider.java#L232 

The problem here is we're sending a uniquely identifiable UA string in our privacy-focused product(s), and re-inventing the wheel (which is risky for compat when it comes to UA strings).

We should just send a hard-coded Desktop Safari or Chrome UA string until we ship GeckoView, IMHO.

(I'm not exactly sure when we're shipping with GeckoView, which doesn't have this issue -- so maybe this is a WONTFIX.)

**Comment by ekager** [comment]
Took this idea from another WebView based browser, but agree it's not ideal! GV is rolled out at 50% to Beta this week actually and if everything goes well, will be in release soon, so maybe we won't need to fix this

**Comment by miketaylr** [comment]
> so maybe we won't need to fix this

awesome!
