### ISSUE TITLE
Firefox Focus should be able to detect installed Firefox Beta

### ISSUE THREAD

**Issue by afarsi** [mozilla-mobile/focus-android#338]
Hi there.
I'm testing Firefox Focus on Android via Buddy Builds. My main task is checking if focus working with RTL languages correctly?
I saw focus have an option in it's menu, named Open with Firefox. When i touched that option it went to Google Play to show the page of Firefox in Google Play.
But i installed Firefox Beta via Google Play before that.
I think focus should be understand if i installed Firefox beta instead of Firefox? If a version of Firefox Beta is on Android now, that option should be changed to Open With Firefox Beta or it should be add another menu option named open with Firefox Beta in addition of Open With Firefox.
It's true that i can use open with... option and see all of browsers on my Android phone, then select one of them(Included Firefox Beta). But i think if Focus be able to show Open with Firefox Beta in main menu, it will be better. Because one of missions of focus is Adverting for Firefox and should be able to show All Firefox versions in it's menu.

Thanks.
Amir Farsi.
Member of Persian L10n Team.

**Comment by sabbir044** [comment]
I think we should only show one option either open with firefox if firefox is installed or no browser is installed or open with firefox beta if firefox beta is installed.

**Comment by pocmo** [comment]
Yeah, the order would be:

* Open with Firefox (if installed)
* Open with Firefox Beta (if installed)
* Open with Aurora (if installed)
* Open with Nightly (if installed)
* Open with Firefox (Play store)

At the same time we'd need to make sure that whatever is selected doesn't show up in the menu item for "Open with [default browser]".
