### ISSUE TITLE
Focus should be able to open all of browsers in private browsing mode

### ISSUE THREAD

**Issue by afarsi** [mozilla-mobile/focus-android#339]
Hi there.
I saw some bugs saying Focus should be able to open Firefox Private Browsing. It's Because Focus mission.
I think we should develop this feature to all browsers. It means when user selected open with and then selected Google Chrome, instead of Firefox, it should be able to open the opened site/web page in incognito tab of Google Chrome, not common tabs of Google Chrome. In addition, if the user selected Opera, it should open opera browser in Private Browsing mode.

Thanks.

**Comment by pocmo** [comment]
Thanks for filing. This is already tracked in issue #195:
* Chrome technically has the ability to do this but doesn't allow third-party apps to open an incognito tab
* Firefox for Android doesn't have the functionality yet. But we want to add it: https://bugzilla.mozilla.org/show_bug.cgi?id=1347583
