### ISSUE TITLE
Privacy leak - gyroscope

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#3392]
Firefox Klar 6.1.1 exposes gyroscope to webpages. This is a major privacy leak, because:

* not all mobile devices have (functioning) gyroscopes, hence it can be used to help identify the user
* it exposes info about user's mobile phone habits (standing up, lying down, walking...), these can be used as information for marketing purposes. The gyro in my device is sensitive enough to detect my arm moving from my breathing and heartbeats.

I can't think of a legitimate use for this function, barring some silly web games that people should be smart enough to avoid when they expect privacy. As such I would recommend to fully disable gyro functionality.

**Comment by lobontiumira** [comment]
@zekooooo is this still an issue?
Thank you!
