### ISSUE TITLE
UI to add and remove custom blocklists

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3396]
Previous discussions: #998, #953.

To add a feature to add and remove custom blocklists, we first need to add a FAB to the new “Ads” subcategory inside “Privacy & Security” settings.

Tap the “Add blocklist” FAB to open a form with a text box to paste URLs:

![settings - privacy security - content blocking - ads - blocklist management 2x](https://user-images.githubusercontent.com/51007/45465929-9260c800-b76b-11e8-98c5-cafb4b6dd349.png)

Alternatively, blocklists may also be added by tapping on a link that contains a valid .txt file (caveat: this may be too complex to build!)

<img width="640" src="https://user-images.githubusercontent.com/51007/45466042-069b6b80-b76c-11e8-80ba-faeb44c6eafb.png">

**Comment by vesta0** [comment]
FYI for 8.0 we want to focus on the first set up of mockups (adding a custom filter URLs in the settings) and NOT the additional ways to add a new custom filter (tapping on the link of a valid filter).

**Comment by vesta0** [comment]
We will not build this feature as part of ad blocking in Focus.
