### ISSUE TITLE
Define sample size for GV in production 7.0 build (staged roll-out)

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#3398]
Release Criteria: 

No significant regression for the following key metrics

- DAU
- 1-day retention
- 7-day retention
- Page Load Time Histogram (to see if GeckoView page load time is slower than WebView)
- Total session time (to see if GeckoView users browse less than WebView users)

@mmccorks please provide the sample size you need to identify a regression of **10%** for the mentioned metrics for the **release population** of Focus/Klar.

**Comment by bbinto** [comment]
+ @sguha

**Comment by mmccorks** [comment]
The required sample size is 30,000 clients. We have ~400,000 DAU and factoring in the ~15% of users who do not reboot their app to get assigned to an experiment branch, I recommend we do a rollout to 10% of users.
