### ISSUE TITLE
Measure retention of Geckoview users for first website access after install 

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#3402]
## Problem Summary
Geckoview is in compressed form when it is installed.  It unpacks when it is first accessed, when user is visiting a website using Geckoview. The unpacking can take anywhere between 1 to 5 seconds.  This only happens when Focus is first installed, or updated.  When a user installs Focus Geckoview for the first time, he/she might be discouraged by the slow initial load time, which only happens once after install.

## What user problem(s) are we trying to resolve?
User being unsatisfied with the initial website load time after install, and not using the app anymore

### Assumptions (optional)
When newly installed browser is noticeably slower than others when used for first time, the user might be discouraged from using it any further

## Outcomes
If the user still uses the app after the first website visit, it can be considered as positive

## Hypothesis
If we measure the retention rate for Focus Geckoview after first website access for new install users, then we can validate above assumption, because we have observed the retention rate via data.

## Metrics

- What is the primary success metric to confirm hypothesis?
- Are there secondary success metrics which could potentially prevent this feature from rolling out?
- How will these metrics be measured? (tool, data source, visualization, etc.) Make sure to confirm that these are confirmed before releasing.

Please provide sample artifact graphs here.

## Detailed design
This is the bulk of the RFC.  Explain in enough detail to try to make it readable to someone outside of the team (other PMs, executives, etc) or for someone joining the team.
An additional goal is to reduce any doubt within the interpretation of metrics we might collect.This should get into specifics and corner-cases, and include examples of how the feature is used.

### Original Version (Present Day)
What is current situation in regards to this feature? How does it currently work? No need to go in as much detail as the suggested change but just enough to provide contrast and more context. Screenshots and user flow can often be enough.
[Add screenshots]

### Variation A
Provide details of change. If this is one of multiple variations, why do we think this change will make the better improvement. Include:
Screenshots with appropriate explanation
User flow

### Variation B (if necessary)
(Same details as variation A)

## Hypothetical Implementation Plan

Unresolved questions and risks (optional)
What parts of the design are still TBD?

## Results
- If we are developing a hypothesis and defining success metrics, we need to log them here.
- If metrics leave room to interpretation, define them. (e.g. when are they tracked, how, etc)
- Include screenshots of result graphs or data tables
- These results will likely help us develop new hypotheses.

## Conclusion
Was our hypothesis true or false and why?
Our hypothesis was true because we observed... [e.g. a 15% increase in account signup completions].

We should also address secondary metrics here:
We also observed during this test that…  [e.g. we had an increase in single device signups]

## Next Steps
There no point having a conclusion if you don’t have take-aways with next steps.

Are we releasing? Are we making changes?

**Comment by mcomella** [comment]
We're unlikely to have the resources to measure the retention difference for first run but we _could_ measure if first (and other early) runs are slower, as agi referenced:

> There is, however, some code that happens on first run that could inpact the first startup time, e.g. :jnicol mentioned to me that the first time Gecko starts we need to generate some shaders for WebRender which is quite slow.

**Comment by mcomella** [comment]
We're trying to be more nimble with our resourcing by being reactive so closing.
