### ISSUE TITLE
https://phabricator.services.mozilla.com/ is unusable in Focus

### ISSUE THREAD

**Issue by tomprince** [mozilla-mobile/focus-android#3410]
## Steps to reproduce

Visit any differential revision

### Expected behavior

View the diff, with proper styling

### Actual behavior

View some unstyled headings and no diffs.

### Device information

* Android device: ?
* Focus version: ?

**Comment by lobontiumira** [comment]
The https://phabricator.services.mozilla.com/ is now usable in Focus RC 92,1,1, with Google Pixel (Android 10), and Samsung Galaxy Tab A6 (Android 5,1,1).
