### ISSUE TITLE
Help page either opens English page, or an invalid URL

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#342]
It looks like even for popular locales, it displays mozilla support page in English, (like french) and in some locales (like 'nl'), it displays 'not found' mozilla support page as below:
![help_page_1490294415294](https://cloud.githubusercontent.com/assets/6930774/24265971/9f459160-0fdb-11e7-8078-9f1884e6757d.png)

Perhaps it's better to just display English page for all?

**Comment by pocmo** [comment]
We got the URLs from the SUMO team. However the articles are not written yet - so they should show up soon.
