### ISSUE TITLE
Split-screen with Focus sometimes shows a black screen on initial open

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#3422]
Note that it isn't able to consistently reproduce this. I've found that you need to use your phone with other apps before coming back to Focus to see the issue.

### Setup
- Have an app that works with split-screen.
- Ensure that Focus isn't running at all (force-close and/or force a gc).

### Repro steps
1. Open a secondary app.
2. Switch the app to split-screen mode.
3. Open Focus so that it shows up below the initial app.
4. Immediately start typing into the search suggestions field and hit enter.

GIF: https://gfycat.com/ClutteredNarrowKoi

---
### Expected behavior
- You're able to see the results of your search/website.

### Actual behavior
- You see a black screen where the WebView should be.

### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: 7.0.4 (Build #322591206 :lizard: 62.0.2.20180910204650)

<img src="https://user-images.githubusercontent.com/1370580/45606025-bd6b4600-ba0f-11e8-977f-8cc3828c6e62.png" data-canonical-src="https://user-images.githubusercontent.com/1370580/45606025-bd6b4600-ba0f-11e8-977f-8cc3828c6e62.png" width="200" />

**Comment by ekager** [comment]
I can reliably reproduce with GV and not with WV.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the 97.0 Focus Nightly build from 12/31 using an Oppo Find X3 Lite (Android 11).
