### ISSUE TITLE
Focus Nightly automatically downgraded to Beta

### ISSUE THREAD

**Issue by callahad** [mozilla-mobile/focus-android#3440]
Some time in the last 72 hours, my Focus downgraded from Nightly with GeckoView to Beta with WebView.

I'm in the UK, but my Google account is still American. At some point overnight, my phone (Google Pixel) automatically updated Focus to `7.0.4 (Build #322601626)`. I was on the Nightly channel previously.

**Comment by callahad** [comment]
I just checked the Play store, and my phone was offered an update to `7.0.5 (Build #322611740)`

**Comment by afarsi** [comment]
I have this problem too.
Yesterday with guide of i joined to Focus testing program again and updated it to version 8.0. Today it downgraded to version 7.0.6! It seems there is a problem. What do you think?
![photo_2018-09-25_19-53-43](https://user-images.githubusercontent.com/19834847/46028441-1f970b80-c0e0-11e8-8565-828164578185.jpg)
![photo_2018-09-25_19-54-09](https://user-images.githubusercontent.com/19834847/46028442-202fa200-c0e0-11e8-8d6d-16fab8d74110.jpg)

**Comment by afarsi** [comment]
I think like the join to beta button under every app in Google Play, they should make a system like that for testing program(alpha) too. For example, when i joined to to testing program,. Google play shows i'm part of beta program, while it should show i'm part of  testing program. I think google have two channels on google play only. Released and Beta! while it should be three channels Release, Beta and Alpha.
I think if you file a bug to their http://issuetracker.google.com system, they will fix this problem. It's their side not your side.

**Comment by colintheshots** [comment]
There isn't a good solution to this today using Google Play. The best option is to do like Fennec did and split Nightly to a new application id and Play store entry. I feel like it's okay for beta to upgrade you to release, but it's probably not okay for nightly to upgrade to beta or release.

**Comment by Sdaswani** [comment]
@vesta0 and @Sdaswani to decide if having a separate store entry for Focus Nightly is worth the cost.

**Comment by vesta0** [comment]
Creating a separate entry for Focus Nightly would be the ideal approach. Not only it will fix the issue of Nightly users currently being upgraded (downgraded) every time there is Beta package available with a higher version code, it will also help us learn more from our Nightly users.

**Comment by Sdaswani** [comment]
@pocmo any objections or challenges you see with us setting up a new app for Focus Nightly? And maybe for Focus Beta?

**Comment by pocmo** [comment]
First, I think the issue with beta overriding nightly could be fixed by triggering an automated Nightly build with every Release build, see #3493. This would push a Nightly with a higher version code before any build gets promoted to Beta.

> @pocmo any objections or challenges you see with us setting up a new app for Focus Nightly? And maybe for Focus Beta?

This definitely requires some build automation work to sign and upload different apps. It's doable but needs help from release engineering.

It will "break" our flow of promoting builds to release. Every channel will need to be filled with separate builds. And we will need a new way/rule to trigger builds: Currently a release on GitHub goes to Alpha and can get promoted from there to Beta and Release.

Finally we'd have to decide how/if we want to migrate our existing Nightly/Beta users.

Technically those are all things we can solve and change (together with release engineering) if we decide so. I'm more concerned about having more and more "Firefox" products show up on Google Play (But that's for product / marketing etc. to decide).

**Comment by Sdaswani** [comment]
Thanks for the info @pocmo . Note the impetus for the new Nightly and Beta apps is less about solving this bug and more about having different telemetry channels for @vesta0 to understand user behavior. It's ultimately up to her to decide to this work, but from what you have described it seems non-trivial and will take at least a few weeks of engineering time (let me know if you disagree with that).

Of course we should fix this bug too :) .

@pocmo I think the end goal is _is there a way to separate out beta, nightly and release populations telemetry data_?

**Comment by pocmo** [comment]
> Thanks for the info @pocmo . Note the impetus for the new Nightly and Beta apps is less about solving this bug and more about having different telemetry channels for @vesta0 to understand user behavior. 

* Nightly should/can have a separate telemetry channel already (I'm not sure whether we hooked that up correctly though; see Telemetry.setUpdateChannel()).

* For Beta: As those are release builds I'd consider them as part of the staged rollout. Those users just get them a bit earlier.

> It's ultimately up to her to decide to this work, but from what you have described it seems non-trivial and will take at least a few weeks of engineering time (let me know if you disagree with that).

Yeah, I agree. There is some back and forth between engineering, RelEng and RelMan needed.

**Comment by lobontiumira** [comment]
Closing this issue as it is not reproducible anymore.
