### ISSUE TITLE
New "view Wi-Fi connections" permission

### ISSUE THREAD

**Issue by nkestrel** [mozilla-mobile/focus-android#3441]
Upgrading from version 6.1.1 to 7.0.3 requests a new permission "view Wi-Fi connections" (`ACCESS_WIFI_STATE`) which implicitly allows location to be determined from nearby WiFi access points (Mozilla maintains such a database at https://location.services.mozilla.com). This seems to be a permission inherited from GeckoView (#2222) but is it necessary for a privacy focused browser?

**Comment by colintheshots** [comment]
We have the GeckoView team investigating if they can remove this requirement.

**Comment by cpeterso** [comment]
GV bug to remove ACCESS_WIFI_STATE permission. I will ask the GV team if we can expedite this bug for 7.0. https://bugzilla.mozilla.org/show_bug.cgi?id=1491094

**Comment by vesta0** [comment]
@cpeterso I assume GV team looking to remove the access (to allow location to be determined from WiFi access points) and not just the permission request prompt?

@npark-mozilla @rpappalax could you please test to confirm if this happens for everyone or only GV enabled?

**Comment by nkestrel** [comment]
The only other new permission asked for when updating from 6.1.1 to 7.0.7 is "control vibration" which is not a privacy issue. Maybe `VIBRATE` could be removed as well, avoiding any permission prompt.

The problem with asking for unnecessary permissions and then revoking them is that the user is not informed, so they continue to think the app is invasive.

**Comment by cpeterso** [comment]
> The only other new permission asked for when updating from 6.1.1 to 7.0.7 is "control vibration" which is not a privacy issue. Maybe VIBRATE could be removed as well, avoiding any permission prompt.

Thanks! That is very helpful information.

I filed [GeckoView bug 1494739](https://bugzilla.mozilla.org/show_bug.cgi?id=1494739) about removing the new VIBRATE permission. If a GeckoView-powered app (like Focus) would like to allow VIBRATE, they can add the permission to their app's AndroidManifest.xml. GeckoView doesn't need to force these apps to inherit this permission from GeckoView's AndroidManifest.xml.

**Comment by cpeterso** [comment]
@nkestrel This bug should be fixed in Focus 7.0.9 beta released yesterday. The Wi-Fi and VIBRATE permissions have been removed, so you shouldn't have to click through a permission prompt when upgrading from version 6.1.1 to 7.0.9.

Thanks again for reporting this issue!

**Comment by nkestrel** [comment]
Can confirm, no permission prompt updating from 6.1.1 to 7.0.9.

**Comment by cpeterso** [comment]
Unfortunately, this fix won't be included in tomorrow's Focus 7.0.10 release. There was a (presumably unrelated) crash in GV 62.0.3, so Jeff had to roll back to GV 62.0.2 for Focus 7.0.10. :|
