### ISSUE TITLE
Following an ftp link results in an error screen you can't back out of

### ISSUE THREAD

**Issue by jrhmoz** [mozilla-mobile/focus-android#3455]
## Steps to reproduce
Visit a link that points to something with ftp:// in it (or put an ftp:// URL in the bar)
### Expected behavior
Ideally you'd display the contents of the directory like on other browsers. Perhaps as a fallback say it's not supported and let you hit the back button and leave.
### Actual behavior
You get a "The address wasn't understood" page and hitting the back button just refreshes the error page.
### Device information

* Android device: Samsung Galaxy S8+
* Focus version: 6.1.1

**Comment by lobontiumira** [comment]
I was able to reproduce the "nothing happened" issue - I opened a page, loaded ftp://example.com in the same tab, the browser kept the previous page, as if I hadn't inserted the new page.
Tested on the 12/29 Focus Nightly with Google Pixel (Android 10).
