### ISSUE TITLE
 Cannot watch Facebook full screen landscape video 

### ISSUE THREAD

**Issue by chianger** [mozilla-mobile/focus-android#3457]
## Steps to reproduce
Connect to facebook.com and login
Browse and find a video to play it
Tap to fullscreen and then rotate to landscape mode
### Expected behavior
Viewing video as expected 
### Actual behavior
Video turns black
### Device information

Firefox Rocket has the same issue
https://github.com/mozilla-tw/Rocket/issues/2661

* Android device: PixelXL (and many more)
* Focus version: 6.1.1
* Webview version: 69

**Comment by rpappalax** [comment]
I'm able to watch Facebook in full screen landscape mode in both webview and Klar.  Webview does flicker to a black window a few times when switching to fullscreen, however.

Android device: Nexus 6p API 26
Focus version: 8.0
Klar version: 8.0

**Comment by vesta0** [comment]
@sv-ohorvath could you please see if you can reproduce this?

**Comment by sv-ohorvath** [comment]
Cannot reproduce on 8.0.6 GV or WV. 
Devices: Pixel (android 9), Huawei P9 Lite (Android 6.0)
