### ISSUE TITLE
 FDroid Fennec doesn't show up in "Open In..." on Klar

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/focus-android#3460]
see:
https://github.com/mozilla-mobile/focus-android/issues/3202#issuecomment-423602684

## Steps to reproduce

STR
1. Download and install: Klar and "Fennec F-Droid" using the FDroid app
2. Open Settings > Apps & Notifications > Advanced > Default apps
3. Set Klar as default browser 
4. Open a webpage: cnn.com
5. Click on main (3-dot) menu, select "Open in..."

### Expected behavior
6. Fennec F-Droid should appear as an

### Actual behavior
6. Only Chrome appears as an option

![image](https://user-images.githubusercontent.com/3699494/45894449-360d3200-bd83-11e8-8488-af388a4b60b3.png)

![image](https://user-images.githubusercontent.com/3699494/45894430-2aba0680-bd83-11e8-9a37-6cba5dda4cbe.png)

### Device information

* Android device: Nexus 6P API 26
* Klar version: 6.1.1

**Comment by ekager** [comment]
If you use Klar from master this should be fixed. #3417 fixed this issue but was only merged 7 days ago

**Comment by rpappalax** [comment]
@ekager thanks, Emily.  It's working now

![image](https://user-images.githubusercontent.com/3699494/46038630-7987d900-c0c0-11e8-9ed4-a472b1cee0ba.png)
