### ISSUE TITLE
Homepage tips links always open SUMO article in en-US

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-mobile/focus-android#3466]
STR:
1. open Focus home page
1. open a some tip link, e.g. about autocomplete settings
1. the link opens related SUMO article

But instead the article to open the correct localized version, it always opens en-US version. If the link does not include the article version locale directly (the article slug can stay in English), SUMO will always open en-US version based on Accept-language header sent by Focus.

**Comment by rpappalax** [comment]
when I use VPN and connect from another locale (i.e. Germany), I see google localizes for me but the SUMO pages all link to en-US

**Comment by vesta0** [comment]
@boek I think you had a good idea of what the issue was - let me know if we can move this into the sprint.
