### ISSUE TITLE
Rename list items under URL Autocomplete

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3467]
@vesta0’s suggestion on https://github.com/mozilla-mobile/focus-android/issues/2966#issuecomment-423287849:

> * Instead of "Default" URL list would it be more accurate to call it something like "Common/Popular/Frequent" URLs? The top URL list is not enabled by default.
> * Would it be more clear to change the "My URL List" heading to "Enable My URL List"? In a quick glance, the difference between "My URL List" and "My URLs" may not be obvious to the user.

I propose taking out the word “List” and clarifying the “View/Edit/Delete URLs” action:

* Default URL List → **Popular URLs** (alternate: **Top Sites** – more understandable, but less consistent)
* My URL List → **My URLs** (alternate: **My Sites** – may also use the word “Favorite”)
    * My URLs → **Manage URLs** (alternate: **Manage Sites**)

Mocks:

![autocomplete-settings 2x](https://user-images.githubusercontent.com/51007/45933931-93ef8300-bfea-11e8-89e0-e4c57633bd98.png)

**Comment by vesta0** [comment]
@BrianNJones  please advise re strings

**Comment by BrianNJones** [comment]
@brampitoyo @vesta0 This doesn't exactly match a previous structure, but I believe it's more helpful:

Autocomplete URLs
> For Top Sites
Enable to have Firefox Focus automatically complete over 450 popular site URLs in the address bar.
> For Other Sites You Visit
Enable to have Firefox Focus automatically complete URLs for sites you've visited before.

**Comment by brampitoyo** [comment]
@BrianNJones I like including the word “For”. It makes the toggles more actionable. Thanks for these!

I should clarify “For Other Sites You Visit”. Firefox Focus can’t autocomplete sites that you’ve visited before. Instead, it relies on you to manually add sites that you visit to an autocomplete list, so it can help you revisit it next time.

This was why I resorted to using the familiar “favorite” metaphor – for better or worse. My thinking went: you add a site to the list of “My favorite sites”. Once added, Firefox Focus can autocomplete these “favorite sites”.

I wonder if there’s a better analogy for this concept? “Bookmarks” doesn’t seem accurate.

**Comment by BrianNJones** [comment]
@brampitoyo, thanks for the memory jog...I'd forgotten the need to manually add! I'm leery of using something like "favorite," since a site may be more "something I need to access a lot" than it is "favorite." 

Autocomplete URLs
- For Top Sites
Enable to autocomplete more than 450 popular URLs in the address bar.
- For Sites You Add
Enable to autocomplete sites you add here.

(I believe we can safely remove the internal reference to "Firefox Focus.")
