### ISSUE TITLE
black screen on start-up 

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/focus-android#3470]
Opening the firefox focus provide the blank black page upon startup, this issue is happening with previous 3 app builds. 
This black screen remains upto 10-15 seconds after then the home screen appears.
As a nightly tester of firefox focus i regularly update app from playstore so I'm sure I haven't missed any update.pls look into it.
For issue to replicate -
The app should be not in background. 
### Device information  
    Android  device: 8.0.0
    Current Focus version:8.0 (Build #322661206 🦎 62.0.2.20180921002357)
![screenshot_20180924-185340](https://user-images.githubusercontent.com/42364681/45954657-1e40e280-bffd-11e8-896a-7dd79cd3977a.png)

The screenshot of Firefox focus at app startup.

**Comment by boek** [comment]
Hey @Scripterr, thanks for letting us know about this! Are you still seeing this behavior in the latest Nightly?

**Comment by Scripterr** [comment]
No i got an update from playstore and  updated, it got downgraded to version 7.0.6 (Build #322672330 🦎 62.0.2.20180921002357) and focus is again working normally.

**Comment by boek** [comment]
@Scripterr Sorry about that, we're currently in the process of shipping 7.0 which just got a new beta version, so the play store delivered you that. You should get the latest Nightly again tomorrow :)
