### ISSUE TITLE
GeckoView unable to load error page is not formatted for mobile

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3472]
## Steps to reproduce
- Have a poor connection (or none? looks like it from the screenshot)
- Load a page
- Wait for error

### Expected behavior
Error page is formatted for mobile

### Actual behavior
Not formatted for mobile.

### Device information

* Android device: Pixel 2
* Focus version: 8.0, #322661206 gecko 62.0.2.20180921002357

![screenshot_20180924-121328](https://user-images.githubusercontent.com/759372/45980953-48e46880-c008-11e8-82b0-8f5ea0fe9f29.png)

**Comment by ekager** [comment]
The Error Page API is coming in the next version of GeckoView (63) so we can actually load a page in its place without hacks.

**Comment by boek** [comment]
@vesta0 Going to move this back into triage

**Comment by ekager** [comment]
Dupe of #2471
