### ISSUE TITLE
about:blank is displaying briefly when loading web pages

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3473]
## Steps to reproduce
- Load a page

### Expected behavior
Never see about:blank

### Actual behavior
about:blank briefly appears when loading the initial page (maybe it's most pages): it looks really unpolished.

### Device information

* Android device: ?
* Focus version: ?

**Comment by rpappalax** [comment]
esp on slow connections

**Comment by sblatz** [comment]
You can follow the GV bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1447406

**Comment by ebalazs-sv** [comment]
This is reproducible on Focus 8.2.0 (Build #340992214) GV 75.0-20200403170909 with Pixel 2 (Android 9).

**Comment by Diana-Rus** [comment]
Reproducible on Focus 8.4.0 with GV 77.0.20200602142841 on Google Pixel 3 XL (Android 9).

**Comment by lobontiumira** [comment]
I did not encounter this issue lately on the Focus builds.
Tested on Beta 96.0.0-beta.5, Focus Nightly from 12/29, and RC 95.2.0 with Google Pixel (Android 10).
