### ISSUE TITLE
Quick remove from autocomplete URL 

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3478]
This is a follow-up ticket to #2966.

### Why/User Benefit/User Problem

The current implementation does not allow a user to quickly remove a URL in the same way they can add one. This is especially confusing because the "Add link to autocomplete" button still shows up even though I've added it already, and when tapped just presents an error message. Instead, we could replace this with "Remove link from autocomplete" if it's already on the autocomplete list.

### What / Requirements
* "Remove link from autocomplete" button that is the inverse of the newly added "add link to autocomplete"
* Telemetry

### Acceptance Criteria (how do I know when I’m done?)
* Remove link button appears only if the user has previously added the link to autocomplete
* Telemetry event is sent when the user clicks this button

For reference, [add link UI can be found here](https://github.com/mozilla-mobile/focus-android/issues/2966#issuecomment-423032174)

**Comment by sblatz** [comment]
Would love @brampitoyo's thoughts on this!

**Comment by brampitoyo** [comment]
Instead of having a link to remove from autocomplete, I think that we shouldn’t show any “autocomplete” button in the context menu, when the site already exists on the list.

Users can go to Settings to remove them. Just like removing bookmarks, I think that removing autocomplete is only something that the user will rarely use.

**Comment by sd1998** [comment]
@brampitoyo Is this feature required. If yes then can I work on it? Thanks.

**Comment by sblatz** [comment]
Closing this until we decide it's in the roadmap.
