### ISSUE TITLE
Quick add autocomplete URL does not enable autocomplete

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3479]
## Steps to reproduce
1. Navigate to a website
2. Click URL bar
3. "Add link to autocomplete"
4. Type in part of the website name

### Expected behavior
The URL autocompletes (i.e. the setting is enabled when I choose to add a URL to autocomplete)

### Actual behavior
The URL does not autocomplete (unless you go into the settings to manually enable it)

### Device information

* Android device: Moto G4
* Focus version: 8.0 build 11

**Comment by sblatz** [comment]
@boek suggests we should just enable the custom autocomplete URL's by default rather than waiting until a user clicking the button to enable it.

@brampitoyo thoughts on this?

**Comment by brampitoyo** [comment]
I didn’t realise that autocomplete wasn’t automatically enabled the moment you add your first URL. This meant that you always need to go deep inside Settings and activate it before getting its benefits.

Yes. This is a bug. And the expected behaviour is also correct.
