### ISSUE TITLE
Search Suggestions Sumo page needed

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#3480]
## Steps to reproduce

1 - Go to settings --> Search
2 - Click on "Learn More" under Get search suggestions

### Expected behavior

Sumo page for Search Suggestions opens

### Actual behavior

This page has not been populated.

### Device information

* Android device: ?
* Focus version: ?

**Comment by boek** [comment]
Hey @jonisavage it looks like the URL changed for this link. It previously was `search-suggestions-focus-android`. But now when I search Sumo it shows up as `search-suggestions-firefox-focus-android`.

**Comment by rpappalax** [comment]
on both webview and klar, i see the link redirect to search-suggestions-focus-android 
and missing content on the page itself.

**webview in landscape**
![image](https://user-images.githubusercontent.com/3699494/46033928-3fb0d580-c0b4-11e8-80b1-ca11272cbb29.png)

**Comment by jonisavage** [comment]
Sorry about that. The link needed to be updated on our end to show the right page. It should show up correctly now. Please let me know if it’s not.

**Comment by boek** [comment]
Thank you @jonisavage!
