### ISSUE TITLE
✅ [browser-session] GeckoView build crashes when erasing browsing history

### ISSUE THREAD

**Issue by BogdanSurd** [mozilla-mobile/focus-android#3484]
## Steps to reproduce
1. Go to any webpage;
2. Send Focus in the background;
3. Swipe down the notifications panel and tap on the "Erase browsing history notification" from Focus.

### Expected behaviour
Browsing history is erased and the notification disappears.

### Actual behaviour
Focus crashes

### Device information

* Android device: Samsung Galaxy Note 8 (Android 8), Nokia 6 (Android 7.1.1); On the same devices running WebView does not crash Focus.
* Focus version: Custom build with changes from #3367 applied.
* Huawei P9 Lite (Android 6) is not affected by this.

**Comment by pocmo** [comment]
This one is interesting.

The previous implementation using LiveData paused observing values while the app is in the background. The Observer from the component will continue observing. As the callback in Focus is doing a fragment transaction this fails while the app is in the background.

A quick fix here is to not do the transaction in the background. I'll add a patch for that to the PR.

However additionally I'll file an a-c issue. I think we do want to emulate the behavior of LiveData: While the app is in the background we may not want to observe changes (or queue them). However the app may want to decide that, so maybe that's going to be configurable?

**Comment by pocmo** [comment]
@BogdanSurd Pushed a patch to the PR. Please let me know if this fixes the issue for you. :)

**Comment by BogdanSurd** [comment]
@pocmo Focus no longer crashes after applying this patch.
