### ISSUE TITLE
✅ [browser-session] Tab counter does not display any pages/disappears when switching to a page

### ISSUE THREAD

**Issue by BogdanSurd** [mozilla-mobile/focus-android#3485]
## Steps to reproduce
1. Open multiple webpages in Focus;
2. Tap on the tab counter;
3. Tap on switch when opening a new webpage.

### Expected behavior
The tab counter should always be displayed in Focus if there is more than one page opened.

### Actual behavior
2. None of the pages are displayed when tapping on the tab counter.
![screen](https://user-images.githubusercontent.com/17178945/46090008-6fe19c80-c1b8-11e8-814a-bbc2e356779e.png)
3. Tab counter is replaced with a trash can icon.

### Device information

* Android device: Samsung Galaxy Note 8 (Android 8), Nokia 6 (Android 7.1.1), Huawei P9 Lite (Android 6);
* Focus version: Custom build with changes from #3367 applied.
* Issue reproducible for both GeckoView and WebView.

**Comment by pocmo** [comment]
Added a patch for this to the PR. Please let me know if this fixes the issue for you. :)

**Comment by BogdanSurd** [comment]
@pocmo Works without any kind of other issue after applying this!
