### ISSUE TITLE
✅ [browser-session] When sharing a link from another app, if focus is not in the background, it doesn't open the link

### ISSUE THREAD

**Issue by BogdanSurd** [mozilla-mobile/focus-android#3486]
## Prerequisits
Focus is not running in the background/the process is killed.

## Steps to reproduce
Share a link to Focus from any other app.

### Expected behaviour
The link is successfully opened in Focus.

### Actual behaviour
Focus homepage is displayed instead of the link.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 8), Nokia 6 (Android 7.1.1), Huawei P9 Lite (Android 6);
* Focus version: Custom build with changes from #3367 applied.
* Issue reproducible for both GeckoView and WebView.

**Comment by pocmo** [comment]
I added a patch for this to the PR. Please let me know if this fixes the issue for you! :)

**Comment by BogdanSurd** [comment]
@pocmo After adding this patch Focus now opens the page via sharing.
