### ISSUE TITLE
Trigger Nightly hook from successful release task

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#3493]
### Why/User Benefit/User Problem

Whenever we create a release (going to alpha/beta) it will have a higher versionCode than the latest Nightly. So for a brief moment Nightly users will get updated to this release version until the next Nightly is build and uploaded.

### What / Requirements

A successful release task should trigger the Nightly hook. With that a new Nightly build (with a higher versionCode) will be available before the release build gets promoted to Beta.

Nightly Hook:
https://tools.taskcluster.net/hooks/project-mobile/focus-nightly-public

Hook trigger API (Python):
```Python
# Sync calls
hooks.triggerHook(hookGroupId, hookId, payload) # -> result`
hooks.triggerHook(payload, hookGroupId='value', hookId='value') # -> result
# Async call
await asyncHooks.triggerHook(hookGroupId, hookId, payload) # -> result
await asyncHooks.triggerHook(payload, hookGroupId='value', hookId='value') # -> result
```

### Acceptance Criteria (how do I know when I’m done?)

* [ ] Sucessful release builds automatically trigger Nightly builds

**Comment by lobontiumira** [comment]
Hi @pocmo 
Is this still an issue?
Thank you!

**Comment by pocmo** [comment]
Nope, that's no longer needed.
