### ISSUE TITLE
Update SUMO page for autocomplete settings for 8.0

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3498]
When we release 8.0 the settings page will be a little out of date.

We will have to update

1. Add a website you're viewing
    - Instructions are different. The button now appears when you select the URLBar
    
<img width="250" alt="image" src="https://user-images.githubusercontent.com/1250545/46175446-d9b58100-c260-11e8-9539-9437ebaf3375.png">

2. 
    - Update the strings, replacing `Custom URLs` with `Manage sites`

<img width="250" alt="image" src="https://user-images.githubusercontent.com/1250545/46175395-ac68d300-c260-11e8-85e1-b62450bed057.png">

**Comment by vesta0** [comment]
@jonisavage would you please change the screenshots on the existing Sumo page?

**Comment by jonisavage** [comment]
Thanks for pinging me on Slack. We've updated the article now: https://support.mozilla.org/en-US/kb/autocomplete-settings-firefox-focus-address-bar

**Comment by vesta0** [comment]
Thank you @jonisavage
