### ISSUE TITLE
Play store links crash: IllegalArgumentException: Malformed URI supplied

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#35]
When opening a market:// URL linking to the Play store the app crashes:

    System.err  W  java.lang.IllegalArgumentException: Malformed URI supplied
                W      at org.mozilla.focus.webkit.matcher.EntityList.isWhiteListed(EntityList.java:38)
                W      at org.mozilla.focus.webkit.matcher.UrlMatcher.matches(UrlMatcher.java:85)
                W      at org.mozilla.focus.webkit.TrackingProtectionWebViewClient.shouldInterceptRequest(TrackingProtectionWebViewClient.java:30)
                W      at android.webkit.WebViewClient.shouldInterceptRequest(WebViewClient.java:185)
                W      at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:321)
                W      at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:527)
                W      at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:38)

STR:
 * Go to mozilla.org
 * Scroll down to the Firefox teaser
 * Click on the "Get it on Google Play" button

**Comment by ahunt** [comment]
I'll focus on not-crashing in this bug, #32 will take care of actually opening an external app.
