### ISSUE TITLE
Just in time default browser does not provide "always" option

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3504]
## Steps to reproduce
1. Open a link with another browser
2. Try to set Focus as default browser on Android <= 6.0 

### Expected behavior
The option to "always" open with Focus appears

### Actual behavior
User must select Focus, then once again select "always"

### Device information

* Android device: Moto G4
* Focus version: 6.0.1

**Comment by sblatz** [comment]
After some further investigation, it turns out that this dialogue box is entirely handled internally, and the Android API does not expose any of its functionality. **Because of this, we would need to use reflection** in order to [set the last chosen app](http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/com/android/internal/app/ResolverListController.java#85). I've heard this is frowned upon, but can go ahead with it if deemed necessary.

_For some more context_: When we start the intent and the user has not selected a preferred app, Android creates a ResolverActivity, ResolveListAdapter, and ResolverActivityController. The app that is displayed on top is determined by ResolverActivityController's method [getLastChosen](http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/com/android/internal/app/ResolverListController.java#78). Essentially, we're trying to override that by either swapping out our app instead of calling this ```getLastChosen``` method, or more simply by just setting Focus as the ```lastChosen```. 

@ekager, @colintheshots: thoughts?

**Comment by sblatz** [comment]
Discussion with @colintheshots confirmed that we should avoid using mirroring. 

Worked with @ekager a bit to try to resolve, but have not been able to find a working solution.

**Comment by Sdaswani** [comment]
@vesta0 to look at telemetry & default browser take rate and see if this is _potentially_ affecting it negatively. If not negative effect, we can close.

**Comment by sblatz** [comment]
I'm going to investigate how this behaves on >6.0. It *should* be pushing users to the default browser setting. If it isn't anymore we have a regression.

**Comment by vesta0** [comment]
Closing this issue based on the engineering investigating for <6.0  and the regression issue with >6.0 having been resolved.
