### ISSUE TITLE
Links sent from other apps create 2 tabs

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3507]
## Steps to reproduce
1. Go to an app: Fennec Nightly, for e.g.
2. Open a webpage and send it to Focus.
3. Check the number of tabs opened in Focus.

### Expected behavior
A new tab should be created with the page sent.

### Actual behavior
2 tabs are created with the same URL.

### Device information

* Android device: 
Samsung Galaxy Note 8 (Android 8.0)
Huawei P9 Lite (Android 6.0)
* Focus version: 8.0, both on WebView & GeckoView. Not Reproducing on 7.0.8

**Comment by ekager** [comment]
Are you still seeing this @sv-ohorvath ? I just tried to reproduce and couldn't. Are you "Sharing" from Chrome/Fennec?

**Comment by Scripterr** [comment]
I'm seeing this with firefox rocket and brave.

**Comment by ekager** [comment]
Ah the intent processor is being called twice
Once here in `MainActivity`
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt#L185

And once here in `IntentReceiverActivity`
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt#L185

@pocmo which one do you want to handle the Send intents?

**Comment by pocmo** [comment]
@ekager `MainActivity` may not need to process any Intents anymore.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the local build.
