### ISSUE TITLE
Add new built-in blocklists

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3512]
https://docs.google.com/presentation/d/1xya135uIeNtdMkjEoz-9ZpGIIeV0LMhTzhJRSoX2ahs/edit#slide=id.g4339ce6552_0_12

**Comment by vesta0** [comment]
Our objective for this sprint is to discuss next steps with GV team, determine what needs to be built in GV, and create and prioritize a GV ticket in Bugzilla.

**Comment by vesta0** [comment]
#2 is not desirable because it will require a lot of coding and manual manipulation + we don't know if GeckoView will be ready in time  so we will only be able to do it in WebView for the 9.0 release. 

#1 is a long term solution on the GeckoView side. This will be pursued but not for Focus.

#3 will be the best option for Focus in order to experiment and obtain user feedback on this feature for the 9.0 release.

**Comment by colintheshots** [comment]
Vesta and I spoke to Francois and the team. It seems Option 3 is doable with only minimal dependency upon the GeckoView team's time. They only need a list of categories to add for content blocking and a simple list of URLs to block per category. We should get started on that soon to make sure it's included in the GV version we wish to use.

**Comment by vesta0** [comment]
- [ ] @colintheshots is building a script to parse the 4 blocklists (Easylist, EasyPrivacy, Fanboy's annoyance list, AdGuard's Mobile Ad Filter) and convert them into a format that can be handled natively by Gecko's existing tracking protection stack. 
- [ ] GeckoView team will add the list of new categories and URLs to block per category. cc @cpeterso

**Comment by colintheshots** [comment]
So Eugen from the GeckoView team says they're only providing a single toggle to enable or disable ad blocking. Is this expected by the new UX?

**Comment by vesta0** [comment]
@colintheshots yes that's right #4058

**Comment by colintheshots** [comment]
Here's what's remaining to finish this:
[ ] The tracking protection team needs to merge https://github.com/mozilla-services/shavar-server-list-config/pull/23 before ckolos can bounce the prod shavar service.
[ ] ckolos must bounce the prod shavar service.
[ ] GV 65 must uplift the ad blocking categories change.
[ ] The Focus team needs to integrate the new GV 65 with the categories.
[ ] The Focus team needs to add the settings to enable ad blocking and test.
[ ] We need to branch and build 9.0.
[ ] (optional) The Tracking Protection team should merge the python script used to create the lists.

**Comment by Sdaswani** [comment]
Great checklist @colintheshots let me know if something is not moving forward.
