### ISSUE TITLE
Block 3rd party tracker cookies

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#3515]
### Why/User Benefit/User Problem

As a user I want to also have the option of only blocking the 3rd party tracker cookies so I can have a good browsing experience and still have some cookie protection. 

### What / Requirements

This cookie capability is being shipping as part of Firefox 63 and I believe it is GV dependent. 

![image](https://user-images.githubusercontent.com/42752644/46226238-a25ed700-c329-11e8-991a-732fec31990b.png)

**Comment by cpeterso** [comment]
GV bug to add API for blocking third-party tracker cookies: https://bugzilla.mozilla.org/show_bug.cgi?id=1495030

**Comment by vesta0** [comment]
Desktop team indicated that In Fx 65 desktop, the way they are blocking third party tracker cookies is
through the new storage access policy based on definitions in the Disconnect lists. This feature will block opaque third-party trackers on the Disconnect lists from storing data such as cookies and thus engaging in cross-site tracking. Considering that in Focus we have the Disconnect lists enabled by default, this will not add much value in the short term - but it could in the longer term when the API includes blocking cookies from unvisited sites, etc.

**Comment by ekager** [comment]
I added the option for GV to block 3rd party tracker cookies with our current menu UX in #3749, leaving this bug open for the new UX.

**Comment by vesta0** [comment]
Thanks @ekager! I think you can close this because the new UX and strings is also tracked here: https://github.com/mozilla-mobile/focus-android/issues/2452
