### ISSUE TITLE
Moveable trash can icon

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/focus-android#3517]
### Why/User Benefit/User Problem

Some users find that the trash can icon (Focus for Android) is in the wrong position and they accidentally tap it.

### What / Requirements

In the early build of Firefox ScreenshotGo, the GO button can be repositioned to a different edge of the screen by long pressing and dragging.  Perhaps the same approach could be taken with the trash can in Firefox Focus?

**Comment by ekager** [comment]
CC @brampitoyo , more requests for trash can changes

**Comment by brampitoyo** [comment]
As far as I’m aware, long-pressing the Floating Action Button in Android isn’t supposed to do anything, and its positioning is also supposed to be static (caveat: while a FAB can attach to top app bars or the edge of a component, on a phone layout, it’s always on the bottom of the screen).

@SeburoSUMO What are other positions that make sense for the FAB? I’m trying to determine whether it’s helpful to have certain areas where the button would “stick”, or if the button should be freely moveable at all times.

Without denying the merit of customisation, Firefox Focus’ original mission is to get you where you want to go as quickly and simply as possible. This means that we have to carefully pick our battles about being able to customise every single part of the app.

**Comment by SeburoSUMO** [comment]
The ideal would be to have the same ability as with ScreenshotGo for the user to move the FAB to wherever they wish.

If not, just moving to FAB up the screen by the same icon height would help prevent accidental use when going to use the right-hand Android button.

**Comment by brampitoyo** [comment]
@ekager @SeburoSUMO After looking again at our past user research sessions, it was clearly pointed out that our Erase icon isn’t easy to see.

Screenshot of report:
![screenshot_2018-11-01 2017 firefox focus for android](https://user-images.githubusercontent.com/51007/47830384-88188d00-ddf0-11e8-9249-57be5cb9cd08.png)

This confirms your idea, @ekager, in thinking that we should align our Android Erase icon positioning with Focus iOS.

**Comment by ekager** [comment]
That's great @brampitoyo! I think that will help users to not accidentally clear their history. With new multitasking mocks and possible content blocking changes from (#3705) I'm having a hard time visualizing all of the changes together. Could we possibly make a meta of all the UX changes we're considering and how they could fit together? CC @vesta0

**Comment by vesta0** [comment]
I definitely support solving for this as it often comes up in user reviews (and happens to me all the time too!) and as @ekager pointed out it would be good to look at the entire user journey. 

Considering the multiple tab design and how the floating erase button will be used to erase the whole session (as oppose to close a single tab) I am fine with keeping the erase button as it is and just re-positioning it to avoid accidental hits - but I'd love to see what other innovative designs @brampitoyo might come up with.

Also it would be great to rephrase the confirmation message to include that cookies have also been cleared. CC @BrianNJones

**Comment by brampitoyo** [comment]
Thanks, @ekager and @vesta0, for the suggestion. I’ve filed #3841 to track all the design changes.
