### ISSUE TITLE
GeckoView uses more background data than WebView

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3519]
I'm concerned that users may not be suspecting this and may be surprised when their data usage is higher than they expect.

## GeckoView usage
![screenshot_20180927-064151](https://user-images.githubusercontent.com/759372/46236829-924cf480-c335-11e8-82fa-2ace910484d5.png)

## WebView usage
![screenshot_20180927-064142](https://user-images.githubusercontent.com/759372/46236827-8d884080-c335-11e8-8412-0292718afdde.png)

**Comment by lobontiumira** [comment]
Closing this ticket, since it is no longer relevant.
