### ISSUE TITLE
Selecting text crashes Focus

### ISSUE THREAD

**Issue by initrd** [mozilla-mobile/focus-android#3520]
## Steps to reproduce
1. Open any website
2. Select any text

### Expected behavior
Text selects :)

### Actual behavior
Browser crashes :(

[Screencast](https://photos.app.goo.gl/sXCoqufVBFboFDqKA)

### Device information
* Android device: Google Pixel, Android 9.0
* Focus version: 8.0 (Build #322721206, Gecko 62.0.3.20180928184514)

**Comment by sv-ohorvath** [comment]
This is fixed on the latest Focus Nightly build (Build #322721206, Gecko 62.0.3.20181001191808)
