### ISSUE TITLE
Trackers blocked counter `i` icon misplaced

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/focus-android#3522]
Trackers blocked counter `i` icon got misplaced .
### STR:
1. Open firefox focus.
2. Serach down any keywords or url.
3. Select menu 3 dot menu.
### Expected Result:
The tracker counter `i` icon is intact.
### Actual Result:
The tracker counter `i` icon is not intact at his original position.

### Device Information:
Focus version:8.0 (Build #322731206 🦎 62.0.3.20180928184514)
Android version: 8.0.0 

Here is the screen shot.
![screenshot_20180930-234340 2](https://user-images.githubusercontent.com/42364681/46261128-cadc0200-c4de-11e8-8a02-05f6dd884b68.png)

**Comment by sv-ohorvath** [comment]
Verified as fixed on latest Nightly 8.0
