### ISSUE TITLE
Padlock context dialogue cannot render content

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/focus-android#3523]
### STR:
1.Open firefox focus.
2. Search down any kewords.
3. Click on the padlock icon at address bar.
### Expected Result:
On selecting the padlock icon the context dialogue appears should render content as it shows the site name and certifying service name.
### actual result:
The dialogue doesn't shows name of site and the certifying service name.
### Device Information:
Focus version:8.0 (Build #322731206 🦎 62.0.3.20180928184514)
Android version: 8.0.0

Here is the screenshot of bug 
![screenshot_20181001-002934](https://user-images.githubusercontent.com/42364681/46261437-011b8080-c4e3-11e8-8136-d69dae8e44e8.png)

**Comment by ekager** [comment]
Thanks for filing. Looks like a possible regression from the `browser-session` change recently.

**Comment by sv-ohorvath** [comment]
Verified as fixed on latest Nightly 8.0.
