### ISSUE TITLE
Podcasts are stopped and can't be replayed after switching tabs

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3527]
## Steps to reproduce
1. Go to ft.com (open the hamburger menu and tap Podcasts), or irlpodcast.org and play a podcast.
2. Long tap a link from the page, open in a new tab.
3. Switch to the new tab.
4. Switch back to the podcast and try to replay it.

### Expected behavior
Playback should be stopped while switching tabs and then should be able to be re-played.

### Actual behavior
The playback is finished (even if you listened just 10 seconds) and can't be re-played by tapping the play button, only if you reload the page.

### Device information
* Android device: Huawei P9 Lite (Android 6.0), Samsung Galaxy Note 8 (Android 8.0).
* Focus version: 8.0 & 7.0.8, GeckoView. NR on WebView.

**Comment by vesta0** [comment]
@sv-ohorvath would you mind testing this bug in Focus 8.0.5 GeckoView 64? Thanks!

**Comment by sv-ohorvath** [comment]
Re-tested and it's still reproducing on 8.0.5 GV.

**Comment by sv-ohorvath** [comment]
> @sv-ohorvath thank you! Can we confirm that this does not happen on WebView?

Nope, not reproducing on WebView.

**Comment by cpeterso** [comment]
> Confirmed that this issue only happens in GeckoVivew. @cpeterso would you please open a bug so a GV engineer can investigate?

Sure. I filed this GV bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1520116

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the Focus Nightly build from 12/7 with Samsung Galaxy Note 8 (Android 9).
I tested several sites with podcasts.
