### ISSUE TITLE
On Soundcloud, audio keeps playing if you switch tabs/ clear history

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3528]
## Steps to reproduce
1. Go to soundcloud.com and play a song.
2. Long tap a link on the page (e.g. the cookies or privacy policy links at the bottom of the page). Open it in a new tab.
3. Switch to the new tab.
4. Clear history.

### Expected behavior
Audio streaming should be stopped.

### Actual behavior
Audio keeps playing in the background until you close the browser.
Not reproducible on youtube/vimeo, audio podcast (irlpodcasts.com).

### Device information
* Android device: Huawei P9 Lite (Android 6.0), Samsung Galaxy Note 8 (Android 8.0).
* Focus version: 8.0 & 7.0.8, GeckoView. NR on WebView.

**Comment by cpeterso** [comment]
A `suspendMediaWhenInactive` setting was added in GV 62 ([bug 1483397](https://bugzilla.mozilla.org/show_bug.cgi?id=1483397)). ekager reported that it didn't work in Focus, but the suspend feature does work correctly in geckoview_example 62 ([bug 148925](https://bugzilla.mozilla.org/show_bug.cgi?id=1489245#c6)) so this appears to be a Focus bug.

**Comment by ekager** [comment]
This should be fixed by updating to 63

**Comment by ekager** [comment]
Confirmed in latest Nightly that this does not happen with GV 63 Beta. Closing.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly.
Devices: Google Pixel (Android 9), Mi 4i (Android 5.0.2).
