### ISSUE TITLE
Focus:about opens in background tab while browsing

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/focus-android#3529]
### STR:
1.Open firefox focus.
2. Search down any keywords.
3. Navigate to the settings menu.
4. Select mozilla.
5. Click on the About firefox focus.
### EXPECTED RESULT:
The focus:about page should open in switched new tab not in background.
### ACTUAL RESULT:
The focus:about page open in the background tab.
### DEVICE INFORMATION:
Focus version:8.0 (Build #322731206 🦎 62.0.3.20180928184514)
Android version: 8.0.0

**Comment by ekager** [comment]
Hi @Scripterr , if I'm understanding this issue correctly, I believe this is intended as this is new behavior for all new tabs, see #3300 for context. You are able to change this behavior in Settings -> General if you prefer to have new tabs opened automatically.

**Comment by Scripterr** [comment]
Okay. i thought this is a regression, anyway if this is intended behaviour then can you close the issue as i don't know how to close it :sweat_smile:

**Comment by Scripterr** [comment]
One more question if someone open wants to know the version of focus or build number shouldn't it display that page at instant in foreground rather than in backgroud where he thinks the page is not opening, as the about page is application software page not a webpage.
And could not se that the pages were queueing in tab counter.
I have opened 2 pages thinking it's not working.

**Comment by ekager** [comment]
Oh you're right these internal pages specifically are actually supposed to open in a new window not tabs. Let me look into this today! thanks for filing :)

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 8.0.
