### ISSUE TITLE
GeckoView: Link to install apps doesn't work

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3530]
## Steps to reproduce
1. Go to reddit.com and tap the "Use app" button.
2. If the app is not installed, install it from google play and repeat Step 1.

### Expected behavior
If the app is installed, the app should open.
If the app is not installed, you should be directed to the playstore.

### Actual behavior
On GeckoView, the redirect doesn't work. Nothing happens when you press the Use app link.

### Device information

* Android device: Samsung Galaxy Note 8 (Android 8.0)
* Focus version: 8.0, GeckoView, not Reproducing on 8.0 WebView. Not reproducing on 7.0.8 on both.

**Comment by ekager** [comment]
This bug was previously was fixed for GV (see https://bugzilla.mozilla.org/show_bug.cgi?id=1478171) but was backed out for causing https://bugzilla.mozilla.org/show_bug.cgi?id=1489257 .

**Comment by ekager** [comment]
Should be fixed with #3870

**Comment by vesta0** [comment]
This was fixed in GV64 and I believe it's been tested as well. @npark-mozilla is it possible to add the label "QA verified" so we can close it?

**Comment by npark-mozilla** [comment]
sure will do.
