### ISSUE TITLE
Url bar in purple state after stwiching tabs

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/focus-android#3531]
## Steps to reproduce 
1. Open firefox focus.
2. Search keyword or enter url.(e.g. home in duckduckgo)
3. Open another link in new tab.
4. Switch to new tab.
5. Switch back to former tab.
### Expected behavior
The tab url bar color should be Magenta after switching to previous tab or other tab which were fully loaded.
### Actual behavior
The url bar is showing in purple state and all tabs url bars are shown in purple state.
### Device information

* Android device: lenovo k8 note 8.0.0
* Focus version: 8.0 (Build #322731206 🦎 62.0.3.20180928184514)

**Comment by pocmo** [comment]
This could be a regression from `browser-session`. I can investigate.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 8.0.
