### ISSUE TITLE
KotlinNullPointerException: 

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#3542]
Focus 8.0 Nightly.

```
org.mozilla.focus.fragment.BrowserFragment in displayBiometricPromptIfNeeded at line 828
org.mozilla.focus.fragment.BrowserFragment in onResume at line 817
Called from: android.support.v4.app.Fragment in performResume
```

https://sentry.prod.mozaws.net/operations/focus-android/issues/4767772/

**Comment by ekager** [comment]
CC @sblatz looks like `displayBiometricPromptIfNeeded` can be called when `biometricController` is null from `onResume`. Want to take a look?

**Comment by sblatz** [comment]
I’ll investigate this!
