### ISSUE TITLE
The Autofill option on login forms doesn't show up on GeckoView

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3552]
## Steps to reproduce
1. Go to google.com and tap Sign in.
2. Long tap the email field.

### Expected behavior
"Paste" and "Autofill" options are displayed.

### Actual behavior
"Autofill" is not displayed using GeckoView, only on WebView.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 8.0), Huawei P9 Lite (Android 6.0)
* Focus version: 8.0, 7.0.10.

**Comment by sv-ohorvath** [comment]
The option I'm referring to (screenshot taken on Klar, 7.0.10, WebView): 
![screenshot_20181002-173348_firefox klar](https://user-images.githubusercontent.com/4037709/46355436-75802c00-c669-11e8-9d9f-8baf97604702.jpg)

**Comment by npark-mozilla** [comment]
@sv-ohorvath which password manager were you using?  (and the behavior was same for both Android 6.0 and 8.0 I assume?)

**Comment by cpeterso** [comment]
This sounds like a GeckoView bug, so I filed an issue in GeckoView's Bugzilla component: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1495822

**Comment by sv-ohorvath** [comment]
> @sv-ohorvath which password manager were you using? (and the behavior was same for both Android 6.0 and 8.0 I assume?)

@npark-mozilla I used LastPass. The behavior was the same on both devices.

**Comment by cpeterso** [comment]
I think LastPass autofill is fixed in GeckoView 63 (and WONTFIX'd for GV 62). Focus 7.0 (and 8.0 Nightly) still use GV 62. We will need to retest after Focus updates to GV 63.

https://bugzilla.mozilla.org/show_bug.cgi?id=1330257

**Comment by sv-ohorvath** [comment]
@vesta0 Yes, this is fixed on Beta 8.0.2, lastPass works the same on gecko and webView.

**Comment by vesta0** [comment]
@sv-ohorvath thank you for confirming!
