### ISSUE TITLE
WebviewdataTest.java is failing on Geckoview as well, retaining cache after page is cleared

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3556]
## Steps to reproduce
Run WebViewDataTest.java on Geckoview.  Use this PR (https://github.com/mozilla-mobile/focus-android/pull/3555) 

### Expected behavior
The test should pass

### Actual behavior
Test fails, after page is cleared, the directory contains the page cache
Also, the test shows that `service-worker.js` page is never requested by Focus when loading the test html page.

It is similar to the issue #2940 , but now happening on Geckoview as well. Perhaps it's Focus issue?

### Device information
* Android device: Nexus 5X simulator, API 27
* Focus version: commit 0747ec1f2a133a78a9cae7de732e7078924c8b8c

**Comment by npark-mozilla** [comment]
![screen shot 2018-10-02 at 4 29 42 pm](https://user-images.githubusercontent.com/6930774/46375494-947ac000-c661-11e8-90aa-660d7810c9b6.png)

**Comment by Sdaswani** [comment]
@boek please move this to the 8.0 sprint if you dont' expect to get it done today.
