### ISSUE TITLE
AMP pages do not open

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#356]
Via buddybuild feedback:

> I can't open AMP pages :( I can't remember if that's new or a common issue? I assume it's because of the block list? 

![screenshot](https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/584f67f6f3d6eb01000842d6/58d5681d064dfd0001672cc3/0d30d388-552c-4d01-9055-02233a12868a.jpg)

| Item | Value |
| --- | --- |
| Created | Wed Mar 29 2017 13:16:10 GMT+0000 (UTC) |
| App uptime | undefined |
| Build | 823 |
| Device type | Pixel |
| Device name | undefined |
| Screen size | 1080 |
| Screen size | 1080px by 1794px |
| Battery | 78% Unplugged |
| Memory free | 1273 MB / 3758 MB |
| Network IP | undefined |

 [Link to buddybuild feedback from build 823](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/feedback?fid=58dbb39ae915a40001c21dc4&bnum=823)

**Comment by pocmo** [comment]
Related feedback:
  https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/feedback?fid=58ee3306d76d400001e48adf&bnum=1064

**Comment by st3fan** [comment]
Is this related to https://bugzilla.mozilla.org/show_bug.cgi?id=1317067 ?

**Comment by ahunt** [comment]
I still can't reproduce, even with all blocking options enabled, on an N6P running Android 7.1, and N5 runnign Android 6 (i.e. both using chrome's webview, and system webview). I'm waiting for my Android 5 device to charge, I'll test that one later.

The iOS fix looks unrelated: iOS would previously match any occurence of a matched domain in a URL string (e.g. foo.com in http://bar.co.uk/something/foo.com/anotherthing/). The main Android implementation does matching only on the host (i.e. we extract the host from the URL string before doing any matching), so it wouldn't be affected.

(I'll do some more testing with my port of the iOS matching code to compare, but I haven't caught any mismatches between the iOS and Android approach recently.)
