### ISSUE TITLE
No padlock icon in secure connections

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/focus-android#3560]
## STR
1. Open firefox focus.
2. Search keyword though search engine or url which have secure connection/https.
### Expected Result
The padlock icon shows on secure connections/https sites.
### Actual Result 
The padlock icon doesn't show up but globe icon shows up instead.
### Device Information
- Focus Version - 8.0 (Build #322751212 🦎 62.0.3.20180928184514)
- Android Version - 8.0.0
### Screenshot 

![screenshot_20181003-230651 2](https://user-images.githubusercontent.com/42364681/46428804-75009780-c734-11e8-8977-3929b734c950.png)

![screenshot_20181003-230648 3](https://user-images.githubusercontent.com/42364681/46434506-5229af80-c743-11e8-88fe-6e4465796c0c.png)

**Comment by ekager** [comment]
I can reproduce this with GV

**Comment by ekager** [comment]
This happens because we update the final security in `onPageFinished`, but since the security doesn't change from the last `onSecurityChanged`, `onSecurityChanged` in `BrowserFragment` is not triggered again where we update the icon after the page is loaded.

**Comment by ekager** [comment]
@pocmo This seems to be related to AC session observers. If the values match it's not called again? This doesn't really work for our current 3 state icon with 2 versions for "insecure" -> http and no cert.

Related decision, do we want to show the globe for HTTP still?

**Comment by pocmo** [comment]
> @pocmo This seems to be related to AC session observers. If the values match it's not called again? 

Yeah, that's true

> This doesn't really work for our current 3 state icon with 2 versions for "insecure" -> http and no cert.

Mh, okay, I'll take a look :)
