### ISSUE TITLE
Move to new version of Activity.onCreateView

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3562]
i.e. https://developer.android.com/reference/android/app/Activity.html#onCreateView(android.view.View,%20java.lang.String,%20android.content.Context,%20android.util.AttributeSet)

The old implementation caused obscure crash bugs on fennec ([see bugs duped to this](https://bugzilla.mozilla.org/show_bug.cgi?id=1401779)) so we should move to the new one.

**Comment by lobontiumira** [comment]
@mcomella is this still relevant?
Thank you!

**Comment by mcomella** [comment]
Yes, we're currently overriding the 3 argument constructor:

https://github.com/mozilla-mobile/focus-android/blob/db5a7948c018b75cb148bad26280613ff7fa1d09/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt#L189

But we should override the four element constructor, i.e.:

```kotlin
override fun onCreateView(parent: View, name: String, context: Context, attrs: AttributeSet): View? {
```

**Comment by ionutbedregeanu** [comment]
Note for QA:  Just check if the app doesn't crash when is opened, take in consideration also the scenario when the app is opened with a custom tab
