### ISSUE TITLE
Creating new session (with fingerprint lock) does not delete all tabs

### ISSUE THREAD

**Issue by jharmer95** [mozilla-mobile/focus-android#3563]
## Steps to reproduce
- Enable the "Privacy & Security" -> "Use fingerprint to unlock app" setting
- Open multiple tabs in Focus
- Leave app without exiting (i.e. the home button)
- Switch back to Focus
- Select new session instead of using fingerprint

### Expected behavior
- All history deleted and all tabs closed

### Actual behavior
- Only bottom tab is actually closed, other tabs remain open
- Individuals can essentially bypass the fingerprint security and see your data if multiple tabs were open

### Device information
Motorola G4 Plus 64GB
* Android version: 7.0.1
* Focus version: 7.0.10 (Build #322741931)

**Comment by Scripterr** [comment]
Can reproduce the issue on my mobile.
- Focus version - 8.0 (Build #322751212 🦎 62.0.3.20180928184514)

**Comment by sv-ohorvath** [comment]
Verified this is fixed on the latest Focus Nightly 8.0 build.
