### ISSUE TITLE
While Help and Privacy sumo pages are opened in background tabs, show a snackbar

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3565]
## Steps to reproduce
1. Open a webpage: google.com.
2. Go to Settings>Mozilla> select Help / Privacy Notice.

### Expected behavior
If a page from the Settings menu is opened in the background, show the snackbar to switch to it.

### Actual behavior
When the Settings menu is closed, there is no notification that the page was opened in a new tab. Hard to notice that a new tab was created.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 8.0)
* Focus version: Nightly 8.0.

**Comment by bansalayush** [comment]
![focus_mozzila_feature](https://user-images.githubusercontent.com/9965653/46572514-af706b80-c9a4-11e8-8285-2d85e9e76727.gif)
What text should i add in snackbar ....
@sv-ohorvath

**Comment by bansalayush** [comment]
will make the gif smaller next time :D

**Comment by sv-ohorvath** [comment]
@brampitoyo Is it ok to add the "New tab opened - SWITCH" snackbar here? On a second thought, I should have logged this as a feature request maybe.

**Comment by brampitoyo** [comment]
This seems like an unintended behaviour, when the Help/Private Notice page open in a new tab the user should be switched to it immediately. They shouldn’t open in background tabs.

**Comment by sv-ohorvath** [comment]
Oh, my bad then, I wasn't aware of that. I'll log a new issue and close this one as it's invalid. Thank you!
