### ISSUE TITLE
[Meta] Biometrics hotfixes

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3566]
- [ ] RuntimeException on createKey when user doesn't have lockscreen enabled

**Comment by boek** [comment]
https://sentry.prod.mozaws.net/operations/focus-android/issues/4781874/
RuntimeException: Unable to resume activity {org.mozilla.focus/org.mozilla.focus.activity.CustomTabActivity}: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: Secure lock screen must be enabled to create keys requiring user authentication

**Comment by sblatz** [comment]
Likely involves #3542.
