### ISSUE TITLE
Erase browsing data when app is killed / in background

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#357]
Currently we only explicitly remove all browsing data when the erase button is pressed. Do we want to do this in other situations too?

* (1) Background: If we are in MainAcitivity.onPause() and isFinishing() is true then it might be a good time to throw everything away
* (2) New instance: Should we preventively delete all data whenever we create a new IWebView instance?
* (3) Enabling private browsing on a WebView is deprecated. However it might be worth enabling it anyways in case some implementations still respect that.

**Comment by pocmo** [comment]
We want to at least looking into (2) from the list above.

**Comment by pocmo** [comment]
I just tested (3) and unfortunately it throws an Exception:
`java.lang.IllegalArgumentException: Private browsing is not supported in WebView.`

**Comment by ahunt** [comment]
We have to be careful with (2) because we create a separate IWebView for InfoActivity, and cleaning up data there will affect the main webview (we can also start InfoActivity from the main screen too, in which case there's no BrowserFragment).

**Comment by ahunt** [comment]
I'm wondering if we should also cleanup data when the app is in the background, and killed by the OS (which I think we can detect via onDestroy). In this case I think we lose app state anyway, so keeping data isn't good. However based on what we discussed today, it seems we'd want to keep app state even when the app is killed by the OS, so this probably isn't useful.

**Comment by ahunt** [comment]
I wonder if we can use a Service to detect when the app is force-killed by the user. Seems hacky, but...

Instead of creating a webview to clear its data, we could also just wipe the app data directory - so I might still rework all the patches for this bug.

**Comment by ahunt** [comment]
I think we've now covered (1) and (2). I'm going to do some experimentation to see if we can detect force-kills (that seems unlikely, but I'd like to try anyway), and will close this bug once that's done.

**Comment by ahunt** [comment]
On my 7.1 device, on Destroy() is called even when force-killing an app. This might be different on older systems, but trying to detect this is seemingly both hacky and unreliable, so we probably shouldn't bother. (Instance state isn't saved when force-killing, so we will at least clear data on the next restart.)
