### ISSUE TITLE
LastPass Autofill shows in the search bar

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3570]
## Steps to reproduce
1. Install LastPass and allow it to auto-fill passwords.
2. Long tap the Focus search bar.

### Expected behavior
Autofill shouldn't be displayed in the search bar.

### Actual behavior
Autofill displayed in the search bar.

### Device information
*Android 8 devices:
Samsung Galaxy Note 8 (Android 8.0)
HTC 10 (Android 8.0)

Not reproducing on:
 Huawei P9 Lite (Android 6.0)
Nokia 6 (Android 7.1.1)
Sony Xperia Z5 Premium (Android 6.0.1)

* Focus version: 8.0 & 7.0.

![screenshot_20181005-144755_firefox klar](https://user-images.githubusercontent.com/4037709/46536690-ed439600-c8b7-11e8-86e0-0365d20cff72.jpg)

**Comment by ekager** [comment]
Hm interesting I can't repro on Pixel 2. Is this the Android system autofill manager? Does it automatically pop up or only when you long press and select it from the menu?

We add these tags to the URL bar layout to try to have autofill apps ignore it.
`android:importantForAutofill="no"
                    tools:targetApi="o"`

**Comment by sv-ohorvath** [comment]
It appears on long tap, next to PASTE (there should be a 3 dots button and you have to tap it).
Just found that on HTC 10 (Android 8.0), it also appears without having LastPass installed.

**Comment by Scripterr** [comment]
Yup, looks like it's manipulated by lastpass cause it appears in every browser, even in chrome.

**Comment by vesta0** [comment]
@sv-ohorvath did you confirm that this is a lastPass bug not specific to Focus?

**Comment by sv-ohorvath** [comment]
@vesta0  Yes, it appears lastPass has the same issue on Chrome too. Thanks for bringing this to my attention.
