### ISSUE TITLE
Tor/.onion addresses: Address not found

### ISSUE THREAD

**Issue by duncanturk** [mozilla-mobile/focus-android#3578]
I used orbot and firefox klar (german version of firefox focus) for a while now. I used the .onion address of duckduckgo as default search engine.
The last update (I think it's caused by using gecko) broke the .onion address support.
Neither using this address as default search, nor entering it by hand allows me to access duckduckgo under this address.
Neither the duckduckgo browser nor orfox have this issue.
Accessing other (non .onion) webpages through tor works fine.

## Steps to reproduce
1. Install firefox klar
2. Install Orbot
3. Activate tor for firefox klar in orbot and start vpn mode
4. e.g. try to open https://3g2upl4pq6kufc4m.onion
### Expected behavior
It should load the duckduckgo website
### Actual behavior
Address not found error
### Device information
* Android device: Oneplus 6 Android 9
* Focus version: Firefox Klar 7.0.11 (german version) (gecko 62.0.3)

**Comment by casketizer** [comment]
I can confirm this issue. It started somewhere between version 8.0.18 an 8.0.23. I grabbed Focus 8.0.18 from github and installed it alongside Klar and it resolves  .onion addressees fine. 8.0.23 and newer don't.  Until issue is fixed i use Focus for Tor use.

**Comment by lobontiumira** [comment]
@duncanturk is this still an issue?

**Comment by duncanturk** [comment]
Yes this is still an issue in 8.16.0
