### ISSUE TITLE
Pressing back on Server Not Found error is shown doesn't go to previous screen

### ISSUE THREAD

**Issue by namanpreetsingh** [mozilla-mobile/focus-android#3585]
## Steps to reproduce
Open up a URL which returns Server not found error. Then press back button.

### Expected behavior
Previously opened page should be displayed or welcome screen should be displayed.

![firefox-focus](https://user-images.githubusercontent.com/31390362/46583915-0ea0af80-ca7b-11e8-9b45-8b5d4aecaf52.gif)

### Actual behavior
It doesn't display previous page.
![firefox-focus-1-](https://user-images.githubusercontent.com/31390362/46584018-1dd42d00-ca7c-11e8-8eb7-a9bfc9427ccf.gif)

### Device information
Xiaomi Redmi Note 5 Pro
* Android device: Yes
* Focus version: 8.0 (Build 11)

**Comment by vesta0** [comment]
@sv-ohorvath could you please see if you can reproduce this in 8.0.6 with GeckoView?

**Comment by sv-ohorvath** [comment]
Cannot reproduce on 8.0.6 GV or WV.
Devices: Pixel (android 9), Huawei P9 Lite (Android 6.0)
