### ISSUE TITLE
Forgot to Include Adjust Key from 6.x on?

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#3586]
## Steps to reproduce
Load https://sql.telemetry.mozilla.org/queries/5494#11169

### Expected behavior
Up and to the right

### Actual behavior
Gasp!

**Comment by ekager** [comment]
I just checked the latest build logs and the Adjust Token is apparently being added. A few months ago we changed our sourceSets and I want to verify that the correct AdjustHelper file is being run with Release Builds as well.

**Comment by Sdaswani** [comment]
Seems like it was fixed - thanks @bbinto !?!?
