### ISSUE TITLE
Improve Action Counts

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#3592]
This [action count tabl](https://sql.telemetry.mozilla.org/queries/4293#8578)e is not super helpful. Can we please have it changed per the following:

1) Break this all down by day or week.

I'm also fine just getting this all in Amplitude instead.

cc @mmccorks and @vesta0

**Comment by vesta0** [comment]
This is tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1505530
