### ISSUE TITLE
Momofuku Milkbar shows SSL error

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#3597]
## Steps to reproduce
1. Go to milkbarstore.com
2. Observe the error.

### Expected behavior
- Locations for delicious cereal milk ice cream.

### Actual behavior
1. SSL error page.
2. Sadness.

### Device information

* Android device: Android 9
* Focus version: 8.0 (Build #322801206 :lizard: 62.0.3.20181001191808)

I did some debugging and found that we're hitting the [`SSL_UNTRUSTED`][0] error on WebView apps and [`ERROR_SECURITY_BAD_CERT`][1] on GV, but **Chrome (and Beta) and Fennec load the site without an issue**.

Fennec also shows that this site has mixed content so maybe it's not all connections that have this SSL issue?

[0]: https://developer.android.com/reference/android/net/http/SslError.html#SSL_UNTRUSTED
[1]: https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSession.java#2619

**Comment by sblatz** [comment]
@jonalmeida I'm unable to reproduce this on the latest beta. Are you able to confirm this is still happening and provide a screenshot of the issue?

**Comment by jonalmeida** [comment]
@sblatz this seems to be resolved now, thanks for looking into it!
