### ISSUE TITLE
Create First Run screen for new users

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#36]
Matching what we have on iOS would make the most sense here. Not sure if we 100% need the same animation with the wave graphic but I just wanted to file this first in case I forgot.

**Comment by antlam** [comment]
Idea from @bbinto 

Allow opt-out in the onboarding screen for Adjust?

**Comment by bbinto** [comment]
Let's not consider this for now (opt-out in onboarding) and replicate what we have for iOS.

**Comment by ahunt** [comment]
I've got the code in place to show the first run, which leaves just the design (I've used the focus wordmark as a placeholder).

One thing I'm wondering: if the user installs focus, and opens a link (without having run focus before that point), do we want to:
A. open the link immediately (and show the first-run experience when focus is opened normally and not via a link)
B. show the first-run experience (and open the link once "OK, GOT IT" is pressed).

Either is possible, I've implemented (B) but it's easy to change.

**Comment by antlam** [comment]
We've gone back and forth about this before on Fennec but I think for Focus, we should just show the First Run experience since it's relatively light-weight.

I vote B.

**Comment by bbinto** [comment]
+1 for B

**Comment by pocmo** [comment]
In Fennec we do (A) btw. :)

**Comment by antlam** [comment]
Haha I know, and that has caused a bunch of edge cases that we have to deal with individually. This approach also seems less fitting for Focus given how light-weight our First Run experience is right now.

**Comment by ahunt** [comment]
@antlam: do you have any mocks for the appearance?

(Here's a screenshot of what I've been using so far for testing, I just used a random background, etc.)
![firstrun2](https://cloud.githubusercontent.com/assets/1546915/23485430/3ec8d6aa-fe90-11e6-8206-9762d6ace863.png)

**Comment by antlam** [comment]
Thanks @ahunt ! here's the mock. It uses the same gradient colors and setting as the toolbar when "inactive.

![screen shot 2017-03-02 at 12 21 37 pm](https://cloud.githubusercontent.com/assets/1994820/23525311/deecb810-ff42-11e6-825b-a4aeba6140d8.png)

**Comment by antlam** [comment]
![screen shot 2017-03-02 at 12 29 44 pm](https://cloud.githubusercontent.com/assets/1994820/23525625/f57a0c62-ff43-11e6-9e51-79645e59c46c.png)

Specs!

**Comment by ahunt** [comment]
And an updated screenshot:
![device-2017-03-06-104814](https://cloud.githubusercontent.com/assets/1546915/23604835/a32e5d0e-025a-11e7-81c6-50aed66e8d97.png)

How important is the statusbar colour? It looks like the default focus settings result in a transparent statusbar - I'm guessing that's acceptable?


(Developer note: for 14sp text, I had to set android:lineSpacingExtra="5sp" to get line-height = 21, i.e. it looks like the default is 16 sp line-height for a 14 sp font. I'm not sure how that scales if you change font size.)

**Comment by pocmo** [comment]
> How important is the statusbar colour? It looks like the default focus settings result in a transparent statusbar - I'm guessing that's acceptable?

Ignore the status bar color. #78 will change this for all screens.

**Comment by ahunt** [comment]
And another screenshot, this time with the button hopefully looking the way it's supposed to:
![firstrun_button2](https://cloud.githubusercontent.com/assets/1546915/23618953/61dc8104-0292-11e7-9583-831f7c078f4e.png)

**Comment by antlam** [comment]
Looks good!

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Onboarding tour, e.g. focus on default browser & how to install search widget](https://trello.com/c/XDJwjW4M/6-onboarding-tour-e-g-focus-on-default-browser-how-to-install-search-widget)
