### ISSUE TITLE
Firefox Focus se detuvo

### ISSUE THREAD

**Issue by ajsyan** [mozilla-mobile/focus-android#3610]
@delphine
## Steps to reproduce
 download the new version of Firefox Focus on Google Play, open and set to kaqchikel language.
### Expected behavior
Firefox Focus in Kaqchikel language
### Actual behavior
Firefox Focus stopped
### Device information
* Android device: Android 5.1.1 version
* Focus version:  7.0.12 (Build # 322821522)

![1](https://user-images.githubusercontent.com/33326687/46751340-80dde380-cc77-11e8-995e-d561a9c7f880.png)
![2](https://user-images.githubusercontent.com/33326687/46751341-80dde380-cc77-11e8-92dd-990b2002460b.png)
![3](https://user-images.githubusercontent.com/33326687/46751342-80dde380-cc77-11e8-8bab-542781cf38d8.png)
![4](https://user-images.githubusercontent.com/33326687/46751343-81767a00-cc77-11e8-9ce7-ed1f9be941f4.png)
![5](https://user-images.githubusercontent.com/33326687/46751344-81767a00-cc77-11e8-83f1-8b02e73dc44a.png)
![6](https://user-images.githubusercontent.com/33326687/46751347-81767a00-cc77-11e8-8877-e1ec2316c920.png)

**Comment by Delphine** [comment]
FWIW I'm on a Pixel 2 (Android 9) on exactly the same Focus build, and it does not crash when I change to any locale (including kaqchikel).
@boek : Any idea why this might be happening? Could it have anything to do with the Android version? I just have no idea :)

**Comment by boek** [comment]
It could be! I will take a look :)

**Comment by vesta0** [comment]
@boek was this fixed?

**Comment by lobontiumira** [comment]
I was not able to reproduce the crash on the 8.16.0 build with Xiaomi mi4i (Android 5.0.2).
