### ISSUE TITLE
Focus-geckoView crashes when sending links from other apps (BaconReader, Pushbullet)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3614]
User reported a crash on webcompat:
*couldn't reproduce it myself on 8.0 or 7.0.12.

URL: https://webcompat.com/issues/new?url=https://duckduckgo.com/?q=firefox+focus&t=fpas&ia=about&label=browser-focus-geckoview

Browser / Version: Firefox Mobile 62.0
Operating System: Android 8.0.0
Tested Another Browser: Yes

Problem type: Something else
Description: Firefox Focus crashes
Steps to Reproduce:
I use Firefox Focus to open miscellaneous pages from other apps, like from BaconReader (a Reddit-browsing app) and similar apps, or Pushbullet, which lets me send a URL from one device to another.
This used to work fine (immediately open the relevant site); but ever since the switch to GeckoView, FFF has a tendency to crash instead-- and lose the URL in the process.

Opening Focus explicitly, then pasting the URL opens the page just fine. Also, some links work 50% of the time, others crash 100% of the time.

So whenever I need to open a URL from, say, a notification (which will disappear after tapping it), I now open it using the DuckDuckGo browser, since opening it using Focus carries a risk of crashing and losing the URL.

**Comment by boek** [comment]
We believe this was fixed. If it comes back up again through webcompat or crash reporting we will re-open 👍
