### ISSUE TITLE
Progress bar completes multiple seconds after page is visually complete

### ISSUE THREAD

**Issue by acreskeyMoz** [mozilla-mobile/focus-android#3622]
## Steps to reproduce
Visit the following sites (some from Alexa Top 500)
• [finance.yahoo.com/news/google-killing-google-data-breach-exposed-user-information-173122166.html](https://finance.yahoo.com/news/google-killing-google-data-breach-exposed-user-information-173122166.html)
• [m.sohu.com/?pvid=000115_3w_index&jump=front](https://m.sohu.com/?pvid=000115_3w_index&jump=front)
• [Yandex.ru](https://Yandex.ru)
• [people.com/amp-stories/royal-a-to-z](https://people.com/amp-stories/royal-a-to-z) 
(possibly due to font load)
• [yahoo.com](https://yahoo.com)
(possibly waiting for ad which sometimes fails to load)

### Expected behavior
The progress bar gives an accurate representation of the page load time.

### Actual behavior
The pages are visually complete but the progress bar has not yet completed. 
In some cases the progress bar will remain at ~80% for multiple seconds after the page appears to be loaded.

### Device information
* Android device: Moto G5, Android 7.0
* Focus version: Build #322751212, With GeckoView 62.0.3

**Comment by cpeterso** [comment]
Thanks for reporting this issue with good examples. I will link to this issue from an existing GeckoView bug we have to investigate the progress bar:

https://bugzilla.mozilla.org/show_bug.cgi?id=1454477
