### ISSUE TITLE
Crash when saving custom search engine

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3625]
## Steps to reproduce
1. Go to Settings>Search> add search engine.
2. Fill in a valid search URL and name.
3. Save.

### Expected behavior
A new search engine is added.

### Actual behavior
"Focus has stopped working" error and closes the app.

### Device information

* Android device:
HTC 10 (Android 8.0)
Mi 4i (Android 5.0.2)
* Focus version: 8.0 & 7.0.12, both WebView & GeckoView

**Comment by sblatz** [comment]
Could be related to some of these changes: #3290

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 8.0.
