### ISSUE TITLE
Add recommended pre-push hook to quicken feedback loops

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3630]
### Why/User Benefit/User Problem
Developers time is valuable; it's ideal to get the quickest feedback turn-around time as possible. One way to do that is to make sure the tests and static analysis tools run locally before it hits gitHub and has to run on slow CI. We can a recommended pre-push hook, which all the devs have to manually set up (it's one line!), so that they hit these problems locally before they hit the server.

We have this in firefox-tv for a while: https://github.com/mozilla-mobile/firefox-tv/blob/master/quality/pre-push-recommended.sh

And document it in our README: https://github.com/mozilla-mobile/firefox-tv#pre-push-hooks

It's up to your team if you want to implement it but it's been working great for us so far!

### What / Requirements
- Add pre-push hook
- Update readme saying how to use it
- Send out email asking people to use it

**Comment by Sdaswani** [comment]
Let's add this to the readme.
