### ISSUE TITLE
Add more Content Blockers 

### ISSUE THREAD

**Issue by maruthi-adithya** [mozilla-mobile/focus-android#3632]
### Why/User Benefit/User Problem
As number of Advertisement and Analytics Platforms are growing in the market, the blocking content resources need to updated from from time to time. This ensures that Users do not suffer from the wrath of latest tracking software developed in the market. 

### What / Requirements
A proper Open-Source documentation on how to update the list. The requirements needed to classify a software as a tracking software. Once this is done, new tracking software can be updated from time to time by users thereby protecting the interest of all Focus Users.

**Comment by boek** [comment]
This is a dup of #2603
