### ISSUE TITLE
Toolbar shows wrong URL when download is cancelled

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#3633]
## Steps to reproduce
1. Go to a site with a file download link on it (e.g. https://en.m.wikipedia.org/wiki/Richat_Structure)
2. Click on the link to download the file. (e.g. https://en.m.wikipedia.org/wiki/Richat_Structure#cite_note-Matton2008a-3)
3. When the download dialog shows up, hit cancel.
4. Observe the toolbar.

### Expected behavior
- The toolbar should show the original URL that we're currently on. In this example, the Wikipedia page.

### Actual behavior
- The toolbar shows the download file path. (e.g. The reference PDF: http://bibvir.uqac.ca/theses/030084214/030084214.pdf)

### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: 8.0 (Build #322871206 :lizard: 62.0.3.20181001191808)

![screenshot_20181015-010804](https://user-images.githubusercontent.com/1370580/46931032-2d70ea00-d017-11e8-9844-ee114f52c5ac.png)

**Comment by ekager** [comment]
I did a bit of investigation. `http://bibvir.uqac.ca/theses/030084214/030084214.pdf` is sent through `onPageStart` before `onExternalResponse` is called. Looks like we just shouldn't use `onPageStart` to update the URL for GV.

**Comment by jonalmeida** [comment]
@sd1998 it looks like @ekager already has a fix for this (🎉). I'm sure there are more issues that you can work on. :)

**Comment by sv-ohorvath** [comment]
Verified as fixed on the latest Focus Nightly build. Logged #3685 as a follow-up.
