### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by princekelly1** [mozilla-mobile/focus-android#3635]
Hello, I'm Kelly.
 I think having a privacy policy statement will be a good thing for your project seeing it kind of have functionalities that may lead to data collection on your end or not. It's a good end users are made aware of the safety of their privacy. I could draft a privacy policy statement if you wish. It's my way of contributing to open source projects.
And maybe a FAQ document

**Comment by ekager** [comment]
Thanks for filing this issue! 
We already have a privacy policy linked in the app under Settings -> Mozilla -> Privacy Notice. 
We also have information about what data we are collecting in [our wiki](https://github.com/mozilla-mobile/focus-android/wiki/Telemetry). 
Let us know if there are specific questions you can't find the answers to.
