### ISSUE TITLE
Use Errorpages component's Safe Browsing error pages

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#3642]
To implement Safe Browsing (meta #459), we need to wire up A-C's Errorpages component's Safe Browsing error pages and localize them. The Errorpages component only appears to have en-US strings.

https://github.com/mozilla-mobile/android-components/blob/master/components/browser/errorpages/src/main/res/values/strings.xml

**Comment by Sdaswani** [comment]
This will be closed when https://github.com/mozilla-mobile/focus-android/issues/2471 is closed.

**Comment by cpeterso** [comment]
The Errorpages component is currently en-US only 😢 but @jonalmeida is working L10n in mozilla-mobile/android-components#1057. We can probably just copy the existing localized strings from Fennec in the Errorpages component.

**Comment by Sdaswani** [comment]
Yes let's copy the existing localized strings!

**Comment by cpeterso** [comment]
@colintheshots I think your  6331ffe commit inadvertently closed this unrelated issue. If so, can you please reopen this issue? (I don't have GitHub permission to reopen bugs in the focus-android repo.)

**Comment by colintheshots** [comment]
@npark-mozilla Could we get some special testing of this case with the fix in place? Specifically, I want to test all entry points of the app to be sure we only get a single task. I'm not exactly sure how custom tabs should behave, but Search Privately should create a new tab in the same task and external URL clicks should do the same.
