### ISSUE TITLE
Add settings UI to enable/disable Safe Browsing

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#3643]
To implement Safe Browsing (meta #459), we should add a settings UI to enable/disable Safe Browsing.

**Comment by Sdaswani** [comment]
Default it on.

**Comment by brampitoyo** [comment]
@ekager @cpeterso While turning Safe Browsing on by default is a great idea, would it also be possible to not expose any settings UI?

It would be preferable for users to get Safe Browsing protection by default and not be able to opt out. While this eliminates choice, Focus also has a strong product point of view for blocking things that it deems unsafe. Plus, adding yet another checkbox would make our Settings bigger and longer.

**Comment by cpeterso** [comment]
> While turning Safe Browsing on by default is a great idea, would it also be possible to not expose any settings UI? It would be preferable for users to get Safe Browsing protection by default and not be able to opt out.

I mostly agree, but Firefox desktop has settings to disable Safe Browsing. Also, until Focus's error pages (Safe Browsing and certificate errors) have a button to ignore/bypass the error, disabling Safe Browsing globally is the only way for a Focus user to access a blocked site.

Some users want to disable Safe Browsing because they think it can leak their browsing history to Google, so giving them choice seems nice. Fortunately, Safe Browsing is designed to not leak browsing history. Firefox compares URLs to a local database (of URL hashes) and, in the rare case of a local hash match, Firefox double-checks the suspicious hash with Google's Safe Browsing service.

https://support.mozilla.org/en-US/kb/how-does-phishing-and-malware-protection-work?as=u&utm_source=inproduct

**Comment by brampitoyo** [comment]
@cpeterso wrote:
> […] disabling Safe Browsing globally is the only way for a Focus user to access a blocked site.

If that’s our only way out of blocked site today, then we will need a Setting.

In the current “Privacy & Security” page, we can have a new section called “Deceptive Content Protection”. This section is located below “Switching Apps”.

Under this section, we can have a menu item + description with a toggle next to it:

> **Block dangerous and deceptive content**
> Check webpages for phishing, unwanted software and malware.
> Learn more ← link to [this SUMO article](https://support.mozilla.org/en-US/kb/how-does-phishing-and-malware-protection-work)

How does this sound?

**Comment by ekager** [comment]
Sounds great! Thanks!
