### ISSUE TITLE
Replace checkbox with switch for "Request desktop site"

### ISSUE THREAD

**Issue by KazaHesto** [mozilla-mobile/focus-android#3652]
### Why/User Benefit/User Problem
The "Request desktop site" option should be a switch, you aren't selecting options from a list, you are toggling an option.
### What / Requirements
Replace checkbox with switch for "Request desktop site".
### Acceptance Criteria (how do I know when I’m done?)
The "Request desktop site" option toggles a switch instead of checking a checkbox

**Comment by ekager** [comment]
@brampitoyo to decide

**Comment by Sdaswani** [comment]
@brampitoyo putting this in the backlog until you are ready to act on it.

**Comment by lobontiumira** [comment]
This is now implemented, the "Desktop site" has now a toggle on the latest versions of Focus: RC 95.2.0, Beta 96.0.0-beta.5, and Nightly 97.0.
