### ISSUE TITLE
Focus as Default Browser is Unset

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#3655]
## Steps to reproduce
@jonalmeida is setting Focus as default browser, and without any beta or nightly release, he is seeing it unset.

@jonalmeida any other STRs than that?

### Expected behavior
Focus stays as default.

### Actual behavior
Focus is unset.
### Device information

* Android device: ?
* Focus version: ?

**Comment by Sdaswani** [comment]
@jonalmeida is there any way some other app on your phone is unsetting Focus? Is something else becuase default app? Did you do any OS upgrades?

**Comment by jonalmeida** [comment]
I'll try to re-run my regular usage and see if I can find out if another app is causing this.

> Did you do any OS upgrades?

None.

**Comment by colintheshots** [comment]
We definitely need STR, if we can identify any. My browser default has been steady. Is this a dev build, nightly, beta, or production? I wonder if switching between nightly and beta is causing it somehow.

**Comment by jonalmeida** [comment]
@colintheshots We were talking about this on Slack. I'm using Nightly, so we believe that might be the problem. It hasn't happened in a while (~1 week) so I haven't be able to see if there was something I did to trigger it.

**Comment by boek** [comment]
@jonalmeida We're most likely going to be doing another release this week. Lets coordinate you checking before / after the release to see if that is the cause.

**Comment by rpappalax** [comment]
unable to repro either

**Comment by jonalmeida** [comment]
I haven't seen this happen any more, so I'm not sure what changed, but I'm happy have this closed.

**Comment by Sdaswani** [comment]
OK let's close for now, do keep an eye out if it happens again, thanks @jonalmeida

**Comment by jonalmeida** [comment]
With this in mind, I wonder if the nightly or nightly -> beta updates are registering as new browser installs and that's what is unsetting the default browser. 🤔

**Comment by Sdaswani** [comment]
Thanks @jonalmeida ! Does step 2 include _updates_, or only fresh installs? If only the latter it's a smaller problem than if it's the former!
