### ISSUE TITLE
Update to support library 25.3.1

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#366]
Do we want to update? (I only noticed because lint was complaining.)

The release notes of 25.2/25.3.0/25.3.1 don't seem to contain anything that would be of relevance to focus. Since we've got quite a bit of time until release, upgrading doesn't seem too risky (or am I being too naive ;) ? ).

**Comment by ahunt** [comment]
FWIW this still doesn't stop the annoying appcompat inconsistent layout warning from:
https://code.google.com/p/android/issues/detail?id=227098

**Comment by pocmo** [comment]
Yeah, let's do it!
