### ISSUE TITLE
Croxyproxy.com proxy service not working in geckoview

### ISSUE THREAD

**Issue by PurpleCodingWizard** [mozilla-mobile/focus-android#3661]
## Steps to reproduce
Enable geckoview if not enabled from focus:test
1. Visit crozyproxy.com
2. Enter a website like duckduckgo.com in the input box and click go.
### Expected behavior
Expected to visit the site i entered in input through proxy service
### Actual behavior
Says browser is unsupported install latest version of chrome, firefox,...
### Device information
* Android device: 5.1
* Focus version: 7.0.12 (geckoview)

Disabling tracking protection & 3rd-party cookies has no effect. But switching to webview from focus:test, the proxy service loads fine. firefox 62.0.3 for android also loads it without any issue.

![focus(geckoview) with tracking-protection disabled](https://user-images.githubusercontent.com/34276732/47063126-6d77ce80-d1c9-11e8-9cdb-9a4f39dd2438.jpg)

**Comment by rpappalax** [comment]
Filed an issue w/ webcompat:  https://github.com/webcompat/web-bugs/issues/20266
