### ISSUE TITLE
Pixel - make default browser doesn't work

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3698]
## Steps to reproduce
Only reproducing on a Pixel device, with Android P.
1. Make sure no browser is set as the default app.
2. In Focus, go to Settings>General, switch Make default browser ON.

### Expected behavior
The toggle switches ON.

### Actual behavior
The toggle doesn't work.
*If a browser is already set, it works ok.

### Device information

* Android device: Pixel, Android P.
* Focus version: 8.0

**Comment by colintheshots** [comment]
The STR isn't complete. Are you selecting Just Once, Always, ignoring the bottom sheet, or is nothing popping up at the bottom of the screen?

If you don't select Focus as default browser, the toggle switching ON would be incorrect behavior.

**Comment by colintheshots** [comment]
I thought this was fixed with a change made on Friday. When did you reproduce?

**Comment by sv-ohorvath** [comment]
@colintheshots Yes, sorry, should've mentioned that the list of apps doesn't pop-up to choose the default. The toggle doesn't trigger anything, the screen does just a kind of refresh. It was reproduced on Monday, on the 2018-10-21 build.

**Comment by sv-ohorvath** [comment]
Ok, double-checked and installed today's build. This doesn't reproduce anymore. Sorry for the inconvenience.
