### ISSUE TITLE
Update Settings iconography on Main view to match 

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#37]
We used a placeholder from the Android Lib (I think?) in Kona, we should update that to match ours to help with cross-product consistency here.

**Comment by antlam** [comment]
<img width="386" alt="screen shot 2017-02-16 at 6 52 59 pm" src="https://cloud.githubusercontent.com/assets/1994820/23050768/2dd73196-f479-11e6-8b2f-2ab051702a47.png">

@pocmo what do you think about this? Using the overflow would allow us to offer options like these:

- Settings
- About
- Help
- Your Rights

... in the typical UI of an overflow menu.

**Comment by pocmo** [comment]
This is great!

**Comment by pocmo** [comment]
![](https://cloud.githubusercontent.com/assets/89638/23062421/eded2eb8-f505-11e6-8253-cef901a504b5.gif)

This is how the current version looks like.
