### ISSUE TITLE
Document how to run with GeckoView locally

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3709]
It starts up with WebView by default and I couldn't find any documentation on how to switch to GeckoView. This could go in the readme.

Workaround: change the code in `WebViewProvider.determineEngine` to use the GeckoWebViewProvider.

**Comment by mcomella** [comment]
From Emily:

> focus:test and then switch the toggle to enabled

**Comment by bansalayush** [comment]
@mcomella  tried replacing `WebViewProvider` with `GeckoWebViewProvider` but `GeckoWebViewProvider` class does not have `determineEngine` function

**Comment by boek** [comment]
Started a new wiki page to document GeckoView specific things.

https://github.com/mozilla-mobile/focus-android/wiki/GeckoView-(In-Progress)
