### ISSUE TITLE
Clicking Facebook messenger has a different behavior between WebView and GeckoView

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3710]
## Steps to reproduce
- Go to m.facebook.com
- Log in
- Click messenger icon

### Expected behavior
? 

### Actual behavior
- WebView: messenger web page opens
- GeckoView: messenger web page opens but it is obscured by a dialog: "Find an app that can open link. None of the apps on your device are able to open this link. You can leave Firefox Focus to search (null) for an app that can."

I reproduced this on the emulator which is maybe why "null" is shown.

Note that this behavior is handled Android Intent URLs. I filed https://github.com/mozilla-mobile/android-components/issues/1132 to figure out who is currently handling this, if any one, and who should be. Note that I didn't find `fallback_browser_url` in the code base for GeckoView so GeckoView may be unable to open external apps at all via Intent URLs.

### Device information
* Android device: Pixel 2 XL API 26 emulator
* Focus version: master

**Comment by ekager** [comment]
Hey Mike - I think this is the issue you're referring to - https://bugzilla.mozilla.org/show_bug.cgi?id=1478171

This was fixed briefly but was backed out, and is not currently high priority. Maybe we should reprioritize since these use cases seem to be common.

**Comment by vesta0** [comment]
Fixed in GV 64
