### ISSUE TITLE
Pasting into GeckoView briefly displays text content in password field

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3711]
## Steps to reproduce
With GeckoView:
- Go to m.facebook.com
- Paste text into the password field

### Expected behavior
Password is obscured

### Actual behavior
Password is momentarily not obscured.

N.B.: I reproduced this on the emulator but I have not tried to do so on device.

### Device information

* Android device: Pixel 2 XL API 26 emulator
* Focus version: master

**Comment by ekager** [comment]
I can reproduce on Nightly. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1501376

**Comment by cpeterso** [comment]
The GV fix landed in GV 65 Nightly. I've asked if we can uplift to GV 64 Beta.

This bug isn't a serious problem, but it is a behavior regression when Focus switches from WebView to GeckoView. Focus users are privacy sensitive, so they would be surprised if their password was revealed on screen.

https://bugzilla.mozilla.org/show_bug.cgi?id=1501376#c7

**Comment by cpeterso** [comment]
> The GV fix landed in GV 65 Nightly. I've asked if we can uplift to GV 64 Beta.

Unfortunately, the GV engineer recommends that we do not uplift this fix to GV 64. The fix affects core Gecko code and depends on some other bug fixes. Seeing the password is bad, but it doesn't actually break any functionality, so he recommends letting this fix ride the trains in GV 65.
