### ISSUE TITLE
Security Bug [Redacted]

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#3723]
Investigate https://bugzilla.mozilla.org/show_bug.cgi?id=1493182#c7

**Comment by Sdaswani** [comment]
If you want access to the bug, let me know.

**Comment by sblatz** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1493182#c9

**Comment by sblatz** [comment]
This seems sufficiently handled on Focus as it stands. We can reopen if we find an edge case where it isn't.
