### ISSUE TITLE
Older Devices Don't Save GV History 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3738]
## Steps to reproduce
1. Use older device
2. click through multiple websites, background focus
3. Reopen Focus

### Expected behavior
Can click back in history

### Actual behavior
History not restored

### Device information

* Android device: ?
* Focus version: ?

**Comment by sv-ohorvath** [comment]
Tried to reproduce this on an unpatched build and failed, on Huawei MediaPad M2 (Android 5.1.1), Mi 4i (Android 5.0.2) - the oldest devices I have here. @emily what kind of device did you use?
