### ISSUE TITLE
Regression GeckoSessions not closed when all sessions removed

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3744]
Possible source of some session leakage in Nightly from #3367, this code was removed and I don't think it was added back in. When multiple tabs are open and all cleared, sessions will be left open: 
https://github.com/mozilla-mobile/focus-android/pull/3367/files#diff-0dc0ec4838f44e70af7c119fb92b53e3L384

cc @pocmo where do you think a good place to clean up the geckosessions is now? I can't use the SessionObserver because I need to access the saved session bundles and by the time the callbacks are invoked, the sessions are destroyed.

**Comment by pocmo** [comment]
Ah, that's a great question. The components take care of that when using the  `browser-engine-gecko*` components but we do not do that here yet. And that's a bigger task - so not a quick fix we could do here.

For now our only option may be to add some wrapper methods that take care of first closing `GeckoSession` and then calling the remove methods on the `SessionManager`. Maybe those could even be extension methods on the `SessionManager`?

```Kotlin
fun SessionManager.removeAndCloseSession(session: Session) {
  // .. close gecko session
 
 remove(session)
}

fun SessionManager.removeAndCloseAllSessions(..) {
  sessions.forEach { session ->
    // close gecko session
  }
  removeSessions()
}
```

.. and then we would need to make sure to use those new methods in the code base. Does this make sense? Is that feasible?

The long term solution would be to get Focus to use the engine component too. We have a OKR this quarter to look into that and see if there are missing pieces. However that doesn't mean that this will land.

**Comment by ekager** [comment]
Makes sense and seems to work fine! :)
