### ISSUE TITLE
Enable remote debugging for Firefox focus

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#3745]
### Why/User Benefit/User Problem

@webcompat team is receiving more and more issues for Firefox Focus including GeckoView. The issue is that it is not currently possible to activate the remote debugging mode without a special build.
Activating the remote debugging at least through USB would help us diagnose issues on GeckoView/Focus.

### What / Requirements

`about:config` is not accessible on Firefox Focus. 
To activate GeckoView, we need to manually type `focus:test` in the address bar and hitting Go (or Enter). Maybe it could be good to add an option here to also set the remote debugging.

### Acceptance Criteria (how do I know when I’m done?)

When devtools on Firefox Desktop can see the device through USB remote debugging either with
* WebIDE window
* about:debugging tab

cc: @miketaylr

**Comment by makotokato** [comment]
```about:config``` issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1500541

**Comment by pocmo** [comment]
Closing. Remote debugging is available in settings nowadays.
