### ISSUE TITLE
Add new level of Cookie blocking (new GV API)

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3749]
GV 63 has a new level of cookie blocking that we can add now.

**Comment by sv-ohorvath** [comment]
@ekager, @colintheshots Is there a way to manually test this? 
So far, I was thinking about checking in a web console, but I'm not sure if Focus can be connected to Firefox webIDE like Fennec (for me it didn't work).

**Comment by npark-mozilla** [comment]
as Oana says, if there is a way to run Focus on a debugger and check certain values after connecting to a website for the presence of tracker received, it would also be great, but not sure whether gv allows this.
