### ISSUE TITLE
Opening link in new tab in custom tab is confusing and opens about:blank in normal browsing

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3753]
## Steps to reproduce
1. open link in custom tab
2. long press on a link and open in a new tab

### Expected behavior
?? We don't support multitasking in custom tabs so why do we have this option?
I think we should maybe take away the option to open in a new tab if in a custom tab and instead maybe "send to focus"? 

### Actual behavior
New tab is sent to normal browsing Focus, currently opens about:blank

**Comment by ekager** [comment]
What do we think about possibly adding two differentiated actions to the context menu while in a custom tab - something like "Open now in Focus", and "Send link to Focus in background". I originally went with the "Open now in Focus" approach so send the link and intent to open Focus to view the new link immediately, but I'm realizing maybe that's not desired behavior for every situation. @brampitoyo for feedback

**Comment by brampitoyo** [comment]
@ekager This is something I’ve overlooked!

While long-pressing a link inside a custom tab, the menu item “Open in a new tab” shouldn’t appear at all.

It should be replaced by “Open in browser”. And when tapped, it should immediately switch to Focus.

This should resolve the issue without introducing a new “Send link to open in background” action. What do you think?

**Comment by ekager** [comment]
Sounds good to me! That's what I originally thought too. Should we use the string "Open in Focus/Klar" that also appears in the browser menu in a custom tab?

**Comment by brampitoyo** [comment]
> Should we use the string "Open in Focus/Klar" that also appears in the browser menu in a custom tab?

Yes. This sounds good. Let’s use the same string rather than come up with yet another new one. Thanks, @ekager!
