### ISSUE TITLE
Clearing normal history then shows custom tab 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3754]
## Steps to reproduce
1. Open a link in a custom tab and leave it open
2. Open Focus and open a link, and then erase

### Expected behavior
Normal browsing tab is erased, custom tab remains

### Actual behavior
Normal browsing tab is erased then custom tab is displayed (with custom tab UI) in Focus

### Device information

* Android device: Pixel 2
* Focus version: Nightly

**Comment by pocmo** [comment]
Needs fix in a-c.

**Comment by pocmo** [comment]
A fix for this landed in a-c and will be released with 0.30.0.

**Comment by pocmo** [comment]
Removing a-c label: The fix was released with 0.30.0.

Please verify after updating. :)

**Comment by sv-ohorvath** [comment]
Cannot reproduce on Nightly.
