### ISSUE TITLE
Feature Request: Add icons for websites

### ISSUE THREAD

**Issue by git998a** [mozilla-mobile/focus-android#3764]
Why/User Benefit/User Problem:
Websites does not have icons
![d](https://user-images.githubusercontent.com/44486581/47542148-b2f57380-d90e-11e8-96f0-4560ab9fad03.jpg)

What / Requirements:
Add icons for websites

Acceptance Criteria (how do I know when I’m done?):

**Comment by vesta0** [comment]
This is the intended behaviour to protect user privacy: no identifiable site icon and the label can also be customized by user.
