### ISSUE TITLE
When a shortcut is added to homescreen - show where it's placed

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3767]
## Steps to reproduce
On Android 8 and 9 devices:
1. Go to a webpage.
2. Add it to the homescreen.
### Expected behavior
It should show you where the shortcut is added.
### Actual behavior
No indication that the shortcut was added and where.
(On Samsung Galaxy S8, there is a notification at the bottom of the screen.)

### Device information

* Android device: Devices running Android 8 & 9: 
Huawei Nexus 6P (Android 8.1.0)
HTC 10 (Android 8.0)
Google Pixel (Android 9)
* Focus version: 8.0 & 7.012

**Comment by ekager** [comment]
We totally pass this part of adding the shortcut to the system when the user presses "Add Automatically" we don't even know if they've interacted with this system dialog or not. I think we should close because there's nothing we can control in this situation.

**Comment by sv-ohorvath** [comment]
Closing as won't fix. Thanks!
