### ISSUE TITLE
Latest master does not open URL, goes to about:blank instead

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3769]
## Steps to reproduce
Go to any URL
### Expected behavior
Webpage opens
### Actual behavior
shows about:blank and that's it

### Device information
Any device, commit https://github.com/mozilla-mobile/focus-android/commit/e37d9c780f7701beff4be7ac9c0569ccd95c1554

On latest nightly, the app crashes

**Comment by boek** [comment]
Fixed with #3761
