### ISSUE TITLE
Crash on launching the app 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3773]
STR:
Install Focus Nightly latest: 2018-10-26.
Launch the app.

Expected result:
App is opened.

Actual results:
App closes immediately.

Devices:
Pixel(android 9)
HTC10 ( android 8.1.1)

**Comment by colintheshots** [comment]
This crash is likely the same one: https://sentry.prod.mozaws.net/operations/focus-android/issues/4483249/

Error loading sqlite libraries in GeckoLoader.

**Comment by cpeterso** [comment]
Exception
Error loading sqlite libraries

    org.mozilla.gecko.mozglue.GeckoLoader in loadSQLiteLibsNative
    org.mozilla.gecko.mozglue.GeckoLoader in loadSQLiteLibs at line 166
    org.mozilla.gecko.GeckoThread in loadGeckoLibs at line 279
    org.mozilla.gecko.GeckoThread in initGeckoEnvironment at line 321
    org.mozilla.gecko.GeckoThread in run at line 448

**Comment by ekager** [comment]
We backed out the upgrade tho 64, and are back on 63 Beta 14 on Nightly so that we can continue to test nightly while this is being investigated and fixed in 64.

**Comment by boek** [comment]
Fixed!
