### ISSUE TITLE
URL bar: Make clickable area bigger

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#378]
Only the actual TextView is clickable in the URL bar. Especially on tablets this is a tiny area (See red box). But also on phones I sometimes tap and nothing happens because I didn't hit the text.

<img width="400" alt="clickable" src="https://cloud.githubusercontent.com/assets/89638/24515227/32c734ac-1577-11e7-886f-ed9306afe335.png">

**Comment by sabbir044** [comment]
Why we only set the clicklistener to textview, not the layout which contains the textview + lock. Though it seems setting the clicklistener is bit of tricky for small devices as layout contains the menu also. I am just asking that was there any reason to add clicklistener to the textview only?

**Comment by pocmo** [comment]
Mostly historic reasons. The layout changed a bit since we started. Back then the TextView was spanning the whole width/height and adding the click listener to it made sense.
