### ISSUE TITLE
The cookies consent area is scrolling with the content.

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#3785]
This is a spin-off of https://github.com/webcompat/web-bugs/issues/20226

## Steps to reproduce

1. Go to https://www.kent.edu/csi/prizes
2. Scroll down and up

### Expected behavior

Cookies statement should stay at the bottom. 

### Actual behavior

Cookie statement is partially hidden and scrolls

### Device information

* Android device: Pixel 2
* Focus version: 7.0.12

**Comment by rpappalax** [comment]
I'm able to repro this on Android, but have also seen this another site using iOS as well so wondering if it's actually a bug?  
![3785](https://user-images.githubusercontent.com/3699494/50314772-0c88a300-0465-11e9-9d30-b315d32ed2d7.GIF)
