### ISSUE TITLE
No redirection to Google Play

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#3786]
This is a spin off of https://github.com/webcompat/web-bugs/issues/20286

## Steps to reproduce
1. with Firefox Focus GeckoView
2. Go to https://97ll.adj.st/?adjust_t=46b478_oywsfi

### Expected behavior
Redirect to Google Play
### Actual behavior
No Redirect to Google Play
### Device information

reproduce the issue with Firefox Focus 7.0.12 (Build #322821522 Gecko 62.0.3.20180922023437).
Note: The issue is not reproducible on Firefox Focus 7.0.12 (Build #322821522), Firefox Nightly 65.0a1 (2018-10-23), Chrome 69.0.3497.100, where redirect to "Google Play > PayBack app" is performed.

**Comment by vesta0** [comment]
This is dependent on existing GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1478171

@cpeterso let's discuss priority at our next meeting, in relation to other high priority items.

**Comment by ekager** [comment]
This should be fixed by newer versions of GV.

**Comment by ekager** [comment]
This is fixed in Nightly.

**Comment by sv-ohorvath** [comment]
Verified it's fixed in Nightly too.
