### ISSUE TITLE
App name not displayed in the Switching apps setting

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3787]
## Steps to reproduce
1. Go to settings>Privacy
2. Verify the description of the "Use fingerprint to unlock app" toggle.

### Expected behavior
App's name is displayed.

### Actual behavior
The app's name isn't displayed.
![screenshot_20181029-105845](https://user-images.githubusercontent.com/4037709/47639612-68703300-db6a-11e8-85df-2a94a46f166a.png)
### Device information

* Android device: ?
* Focus version: 8.0 (2018-10-28 build).

**Comment by ekager** [comment]
Was this in an emulator? I can't reproduce on my devices

**Comment by sv-ohorvath** [comment]
Verified on Master.
