### ISSUE TITLE
New Onboarding card for the allowlist feature

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#3800]
### Why/User Benefit/User Problem

As a user (new/existing) I would like to know that I can add a frequently visited site to my exceptions list so it doesn't break.

### What / Requirements

Existing onboarding feature:
-For existing users who have updated to the new version, show a card with content on how to add a site to exceptions list.
-For new users, add a new card with content on how to add a site to exceptions list.

### Acceptance Criteria (how do I know when I’m done?)

-Existing user will see a new card informing them on how to use the exception list
-New user will see a card (along with other cards) informing them on how to use the exceptions list

**Comment by brampitoyo** [comment]
Because one of our tips is:

> Site behaving unexpectedly?
> Try turning off Tracking Protection

We hope that the user already knows how to do this.

As long we haven’t shipped ad blocking, we don’t need any onboarding. What we can do is tweak or add to the home screen tips, so they would say something like:

> Site behaving unexpectedly?
> Try turning off Tracking Protection
> It will remain off for the site, until you turn it back on.

**Comment by vesta0** [comment]
@brampitoyo my intention was more around letting users know about the exception list once it's released: not only they can turn off tracking protection (as before) but turning off tracking protection will add that site to their allowlist, which they can also manage (remove sites) later on. What do you think?

**Comment by vesta0** [comment]
Closing this issue as we will address user education with an in-app message.
