### ISSUE TITLE
Consider search shortcuts in the URL bar

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3808]
### Why/User Benefit/User Problem

There are many kinds/types/categories of things that I search on the web: recipes, movies, song lyrics, products I want to buy, etc. When I am looking for products, for example, I like to use Amazon’s search function. It gives me a better search result than Google can, and I can then buy the product right from the website.

This applies to other topics. For research, I prefer Wikipedia. For lyrics, I prefer Genius. For movies, I prefer IMDb.

I still prefer Google for my everyday searches, but I also want a faster way to quickly search on these specific websites if I have specific queries

### What / Requirements

The ability to specify _where_ I want to search, without changing my default search engine.

### Acceptance Criteria (how do I know when I’m done?)

The user can get to their answers faster than if they’re using Google, Yahoo or Bing.

### Resources

DuckDuckGo has [!Bangs](https://duckduckgo.com/bang)

Firefox has [search shortcuts](https://venturebeat.com/wp-content/uploads/2018/10/firefox-63-search-shortcut.jpg?resize=1024%2C512&strip=all), and we can probably follow our own approach of using the `@` character. The metaphor is obvious: just as you `@` somebody to mention them in a conversation, you `@` a site to mention them in a search. It’s like saying “@amazon, I want to search for Harry Potter”.

**Comment by brampitoyo** [comment]
CC @vesta0

**Comment by mathu97** [comment]
Can I work on this, please?

**Comment by brampitoyo** [comment]
@mathu97 While Firefox Preview doesn’t have support for `@`, we do already show you a list of search engine immediately after you tap on the URL bar – which already solves this problem.

Since search shortcuts is longer an problem, I’m going to close this issue.

**Comment by mathu97** [comment]
@brampitoyo which build of focus is this? I don't seem to notice this feature that shows a list of search engines immediately on tapping the URL bar. Currently, I see that you can go into settings and change your search engine, but that seems to be about it.

**Comment by brampitoyo** [comment]
@mathu97 Oh, sorry! I thought this product was Firefox Preview, not Firefox Focus.

My mistake. Let’s reopen this issue.
