### ISSUE TITLE
Consider exposing access to Focus features in the URL bar

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3809]
### Why/User Benefit/User Problem

Sometimes, when I use Focus, I want the app to do certain things. For example, I want to change the search engine I usually search with. Another example: I want Focus not to show the image of any website I have opened, when I switch between apps.

I would probably know how to do this if I do a Google search and look around for answers on a few sites on the web. But this is slow, and I would probably forget or get distracted.

### What / Requirements

When I type “change search engine”, Focus should know what I mean by that. Instead of giving me a link to Google, it should offer me a way to switch search engines _right there_ in the address bar.

When I type “hide app when switch”, Focus should know what I mean by that. Instead of giving me a link to Google, it should offer me a way to activate Stealth Mode _right there_ in the address bar. (I don’t know that it’s called “Stealth Mode” – nor do I care what it’s called. I just want to get things done.

### Acceptance Criteria (how do I know when I’m done?)

The user can search and modify Focus settings to suit them, faster than customising another browser.

### Considerations

Keyword disambiguation is one of the hardest problem to solve. We have to make sure that we’re not being too literal, and be able to understand what the user _means_ when they type something that matches our Settings.

We also have to make sure that we’re not being too aggressive in offering our own suggestions ahead of the search engine’s keyword suggestions.

If we believe that there’s a positive correlation between Settings tweaking/usage and app usage/user retention, then this feature can help surface features that today takes a lot of taps to access.

**Comment by boek** [comment]
@MinionAttack I think the intention behind this feature is to allow people to quickly access settings by using the URL bar to search :)

**Comment by MinionAttack** [comment]
I see, I misunderstood his comment. Sorry for my confusion!
