### ISSUE TITLE
Focus is using excessive mobile data

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3811]
Reported by a user on Twitter: https://twitter.com/arcaneabhay/status/1054604022991118336
" @arcaneabhay
@firefox Firefox Focus consumed 5GB mobile data on background overnight while it was not in use. It also drained my entire battery. "

**Comment by jonalmeida** [comment]
In my usages with Nightly and GV:
- July - 130MB
- August - 225MB
- September - 213MB
- **October - 650MB**

My current build as of today: 8.0 (Build #323021211 :lizard: 63.0.20181011200118)

**Comment by colintheshots** [comment]
The Twitter reporter responded saying he had switched to GV with "focus:test". I'm not sure how he heard about it.  So far, there's been at least three reports from users with GV who have used excessive data. One stated that he had been using YouTube and erased the session. The Twitter user said he'd also erased after using any sites. I didn't ask which method they used to erase, but that would be useful info.

**Comment by jonalmeida** [comment]
I filed this issue, but I think it might be related: https://github.com/mozilla-mobile/focus-android/issues/3821

**Comment by cpeterso** [comment]
This GV issue might be related: "GeckoView CPU usage while Focus is in the background".

https://bugzilla.mozilla.org/show_bug.cgi?id=1482185

**Comment by vesta0** [comment]
May also be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1506957

**Comment by vesta0** [comment]
Here's another user feedback about excessive data use: https://play.google.com/apps/publish?account=7083182635971239206#ReviewDetailsPlace:p=org.mozilla.focus&reviewid=gp:AOqpTOHKuSjtLAqxH_RmAt4uN3gvhXQhsj0Bx62a4UrHqKftUR20FZmEO8JyFbPuM2oLSMMJl5Bp0fZ87gmyHC8
