### ISSUE TITLE
Old Homescreen Shortcuts Will Break On Update

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3813]
In #3541 we moved all of the intent receiver logic to IntentReceiverActivity instead of MainActivity.

With #3774 we changed where the new homescreen shortcut intents should be sent to IntentReceiverActivity, but any user who had old shortcuts before updating will be stranded with shortcuts that send to MainActivity. 

We should revert these changes and allow MainActivity to continue to handle only the shortcut intents.

**Comment by sv-ohorvath** [comment]
Verified on latest Nightly (2018-10-31).
