### ISSUE TITLE
Consider double-tapping anywhere on the page as a shortcut to access the URL bar

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3816]
File under “Why didn’t we think of this shortcut before”?

### Why/User Benefit/User Problem

I am currently browsing a webpage one-handed, using a phone with a large screen size. Now, I want to type a new URL. Because I’m currently holding a large phone one-handed, tapping on the URL bar itself is tricky. I either have to extend my thumb all the way to the top of the screen, or I have to use the other hand (which is still easy to do). The quickest way to start typing is by tapping the “Erase” button. 

### What / Requirements

A one-step way to access the URL bar, that can be used single-handed.

In this issue, I’m proposing that the user should be able to double-tap any area on a website which doesn’t contain images or links to access the URL bar and open the keyboard.

This proposal doesn’t shut away the opportunity for Focus to have a search button on the bottom bar, like what Chrome or Firefox Rocket are doing. Having this button will be just as effective as a measure. It’s just that Focus aims to also be a minimal browser, so we try to strip away as much UI as possible. As a result, we don’t have a bottom navigation bar.

### Acceptance Criteria (how do I know when I’m done?)

A way to access the URL bar which is faster than tapping on the URL bar, and can easily be discovered by most users.

### Explanation

When you’re browsing a website, there are a lot of areas which aren’t tappable – areas that contain neither images nor links.

When you tap on this area, it does nothing. This is totally expected. Tap-then-scroll is a common gesture to scroll up and down the page (as is just scrolling without pausing to tap first).

When you long press on this area, it will select it (if it’s a text) and pop open a Copy/Paste context menu. This is also expected.

When you double tap on this area, it does nothing, but is there an opportunity to do something here that can make browsing even faster?

There are four reasons why using double-tap as a shortcut is a good idea:

1. It implies an intent to do something, but isn’t currently used for anything.
2. It’s already used by many Android devices to wake up from sleep.
3. It’s relatively low-effort to perform – doesn’t take much more effort than a single tap – and can be done while using the phone one-handed.
4. There’s a chance of users bumping into this gesture and observing its results, either naturally or by accident, during the normal course of using Focus (e.g. when they idly tap around the screen). This helps the feature be discovered. Of course, we’ll need just-in-time help when the action is first performed, to make it clear.

There’s a fairly big risk to this feature. Maybe our users expect double-tap to do _nothing_, and now we’ve made it do _something_. That can be annoying.

**Comment by brampitoyo** [comment]
CC @vesta0

**Comment by hackel** [comment]
Double-tap is already used to select text and zoom in/out.  Changing this behaviour would be inconsistent and extremely counter-intuitive.  Following Google's lead and adding an option to move the address bar to the bottom for people who insist upon buying absurdly large phones seems like a better solution.

**Comment by brampitoyo** [comment]
@hackel Good point. I hadn’t considered (but should have considered) double-tap to zoom in/out of the page.

So my original point:

> There are four reasons why using double-tap as a shortcut is a good idea:
> 1. It implies an intent to do something, but isn’t currently used for anything.
> […]

was totally wrong.

Double-tap was in fact already used for another gesture.

In that case, this issue loses its point. Let’s close it. Thanks a lot for the correction, @hackel.
