### ISSUE TITLE
Integrate ProtonVPN support

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/focus-android#3817]
### Why/User Benefit/User Problem
As a user, I want a privacy browser with integrated VPN support. Firefox desktop already supports ProtonVPN for premium users. However, for these users to take advantage of their subscription on mobile, they must install and use an external, 3rd-party-branded app which also requires a foreground notification that stacks with our own and fills the whole notification shade. It would improve the stickiness of our premium users if they could use a privacy browser with integrated VPN support and Firefox branding. Some users might discover the VPN and subscribe entirely through Focus Android and may not even own a desktop.

### What / Requirements
- We would have to build the SessionNotificationService into a VpnService where the VPN portion can be enabled by a preference setting plus A/B experiment.
- That service would also need to function outside of browsing sessions to protect other apps.
- There would need to be VPN onboarding to disable battery optimizations which prevent the VPN from staying connected.

### Acceptance Criteria (how do I know when I’m done?)
- User can login to ProtonVPN and disconnect at will
- Can browse the web with that VPN connection
- Can keep the VPN alive while using other apps
- Can use a safe DNS solution to protect the VPN session
- No detected data leaks
- Can connect to captive portals without getting in the way

The VPN may optionally support a kill switch to block unprotected traffic, a whitelist of trusted networks, and server switching aside from using the closest. Several of these features may depend upon collaboration with ProtonVPN.

**Comment by brampitoyo** [comment]
I agree that Focus should have a “VPN Mode”, because it ties in with our privacy stance.

To tie in with our speed and simplicity stances, we have an additional opportunity to make the VPN UX a lot simpler and faster to operate than in other apps. One press of a button to activate, no tweaking required.

**Comment by setuidroot** [comment]
I like this idea (I think I proposed a similar idea awhile back.)  But I think it'd be cool to integrate the browser with OpenVPN or IKEv2 and/or SOCKS proxies.  

For example, in the browser settings, you could click on "VPN" or "Proxy".  Under "VPN" you could import an OpenVPN config (.ovpn file) or select IKEv2 and type in the server and authentication info.  Under "Proxy" you could select to add a SOCKS5 or HTTP proxy config.  Like Telegram added feature for SOCKS/MTProto proxy as an example.

In my mind, limiting the browser's (potential) VPN to just ProtonVPN seems to be promoting their services and more importantly, excluding the ability to use any other VPN provider.  I don't know ProtonVPN, I setup my own VPN servers, but showing this level of favoritism towards them might come off as an anti-feature to some people.  This is just my opinion, I don't know the business decisions behind any of it, but I would like to see a configurable VPN feature if/when a VPN is implemented.  

This extra configuration should be optional and in advanced settings, the one click VPN is a great idea and easy to deploy with Proton (or whatever default VPN) while allowing more tech savy people to change the VPN configuration.

Another idea would be to add "DNS" to the settings and allow people to manually chose a DNS server (the idea here being the eventual addition of DNSCrypt servers.)
