### ISSUE TITLE
Feature request: Set focus as default assistant

### ISSUE THREAD

**Issue by AlEilers** [mozilla-mobile/focus-android#3818]
You can change the default assistant from Google to any other app that supports it eg. Firefox. It would be nice if also Focus would support this feature.

It should be as easy as adding this intent filter to the right activity

    <intent-filter>
        <action android:name="android.intent.action.ASSIST" />
        <category android:name="android.intent.category.DEFAULT" />
    </intent-filter>

**Comment by brampitoyo** [comment]
@AlEilers If you choose Focus as a default assistant, I’m curious as to what would happen when you invoke the assistant? Would it pop open a search menu with the keyboard up? We don’t currently have assistant capability.

**Comment by AlEilers** [comment]
You are currently not able to set Focus as default assistant (because of the missing intent-filter). However if you choose Firefox as assistant it would open the search bar with keyboard. This would also be the expected behaviour for Focus.

**Comment by colintheshots** [comment]
Fixed with #3884
