### ISSUE TITLE
GV: User logged out while switching tabs

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3819]
## Steps to reproduce
1. Login on Twitter or Facebook. 
2. Open a link in a new tab. Switch to the new tab.
3. Switch back to the tab with twitter/facebook. Refresh the page.

### Expected behavior
User shouldn't be logged out until the session history is cleared.
### Actual behavior
With any cookies blocking option set: I tried "only 3rd party cookies" blocked & none. User is logged out just by leaving the tab.
### Device information

* Android device: Samsung Galaxy S8 (Android 8.0), Huawei Honor 8 (Android 7.0)
* Focus version: 8.0 & 7.0.12 with GV.

**Comment by vesta0** [comment]
Colin will look into this along with the GV team as part of his work on multitasking.
