### ISSUE TITLE
Consider automatically erasing browser history with user consent

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3822]
### Why/User Benefit/User Problem

When I tap Erase, I deliberately tell Focus that I want my browsing history to be erased. But there are situations where I want Focus to automatically erase.

In some situations, I would leave Focus and proceed to another activity. In these situations, I gradually forget about the open page/tabs that Focus has stored. Whatever was being stored, I no longer need to see it. When I have forgotten about my browsing activities, I also want Focus to forget about my browsing history.

There are situations where I want to control my own internet consumption habit. When I would rather not get sucked into infinitely scrolling, endlessly refreshing websites, I want Focus to time my browsing session and automatically erase it.

There are situations when I want to prevent my browsing from being compromised when I lose control of my phone – for example, when somebody else is accessing it. When I want to feel extra safe and assured, I want Focus to automatically erase my browsing history.

### What / Requirements

A way for Focus to automatically erase browsing history after the user has set certain conditions.

### Acceptance Criteria (how do I know when I’m done?)

The user feels totally safe to “start from fresh” or proceed to their next task.

**Comment by sd1998** [comment]
@ekager Can I work on this.

**Comment by ekager** [comment]
Hi @sd1998 , this issue hasn't been hashed out yet and still needs UX/Product work so I wouldn't recommend trying to work on it yet
