### ISSUE TITLE
Tracking protection doesn't work

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3826]
## Steps to reproduce
1. Fresh install of Focus, with default settings.
2. Go to lynda.com and pick a cnn.com or.
3. Verity the number of Trackers blocked.
### Expected behavior
On cnn's homepage, there are ~30 trackers blocked, and 4 on lynda, on Focus v7.0.13. 
### Actual behavior
0 trackers blocked on v8.0.
### Device information

* Android device: 
Samsung Galaxy S8 (Android 8.0), Mi 4i (Android 5.0.2)
* Focus version: 8.0 (2018-10-31).

**Comment by vesta0** [comment]
GeckoView team is aware and working on it.

**Comment by cpeterso** [comment]
The GeckoView bug: "Tracker blocking rarely working". https://bugzilla.mozilla.org/show_bug.cgi?id=1503560

**Comment by ekager** [comment]
Working for me in latest Nightly. Closing.

**Comment by sv-ohorvath** [comment]
Verified this is fixed on Nightly too.
