### ISSUE TITLE
Incorrect behavior for setting default browser in Android >6.0

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3829]
Seems like #3437 caused a regression where versions on Android > 6.0 are now using the [just in time default browser](https://github.com/mozilla-mobile/focus-android/issues/2896) open with method instead of being pushed to the settings.

This is almost certainly due to [this line](https://github.com/mozilla-mobile/focus-android/pull/3437/files#diff-a8232faf95c057b7dbb5e7e69e2bdee2L73)

**Comment by sv-ohorvath** [comment]
@sblatz To make sure I understand, this feature was supposed to work only on Android 6 and lower, when there is no default set? When there is a default, open the SUMO page.
On higher android versions, it should just open the settings menu in any of cases.

**Comment by sblatz** [comment]
@sv-ohorvath That is correct.

Android >6.0:
* always open default settings menu

Android <= 6.0 and NO default set:
* "open with" prompt

Android <= 6.0 default set:
* redirect to SUMO
