### ISSUE TITLE
after clearing history, links from previous session flicker "visited" color sometimes

### ISSUE THREAD

**Issue by anotak** [mozilla-mobile/focus-android#3839]
## Steps to reproduce
1. google search for the phrase "google" from the location bar.
2. click the first link to google.com.
3. clear history
4. google search for the phrase "google" again.
the first link to google.com flickers from the purple visited color to blue for a moment.

### Expected behavior
no flickering.

### Actual behavior
flickering.
this implies that state is being preserved across the "clear history" somehow, which i find disturbing.
i don't know what exactly is going on, but it sure seems like this could leak information somehow.

### Device information

* Android device: LG Stylo+, Android 7.0
* Focus version: 7.0.12. has been happening for many versions though, before the UI changes. so it's not a recent regression.

**Comment by vesta0** [comment]
Duplicate issue https://github.com/mozilla-mobile/focus-android/issues/1600
