### ISSUE TITLE
Surface erase and content blocking icons

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3841]
### Why/User Benefit/User Problem

1. In the past, most test participants did not notice the trash icon until they were asked to look for it and interact with it. Source: [2017 Firefox Focus for Android user research](https://docs.google.com/presentation/d/1AG4J_pF5CUf_e6x8-o6S_FJNfgtb_uY3ImIsAfa-NN8/edit#slide=id.g1e44033abe_3_22).
2. Some users find that the trash can icon (Focus for Android) is in the wrong position and they accidentally tap it. Source: @SeburoSUMO on #3517.
3. I just downloaded Focus, and the first site I visit is broken. I didn't scroll through all of the onboarding slides so I don't even know what content blocking options there are. I uninstall Focus because I don't understand how/where/why to "fix" sites. Source: @ekager on #3705.

### What / Requirements

Prominent position of both erase and content blocking icons, keeping in mind not only Focus for iOS, but also the upcoming changes to multitasking.

### Acceptance Criteria (how do I know when I’m done?)

1. Users know where to go to Erase their browsing history
2. At the same time, users won’t accidentally tap such a destructive action so easily and regret it afterwards
3. Users know exactly where to tap in order to fix sites that appear broken

**Comment by brampitoyo** [comment]
### Learning from pre-Photon iOS

The solution, I think, involves going _all the way back_ to Focus for iOS before the Photon alignment redesign.

<img width="220" src="https://user-images.githubusercontent.com/51007/47970922-7c7ade00-e0f0-11e8-8046-5ea977e0ab66.png"><img width="220" src="https://user-images.githubusercontent.com/51007/47970910-53f2e400-e0f0-11e8-8176-8d5422ea2bf7.png"><img width="220" src="https://user-images.githubusercontent.com/51007/47970927-8c92bd80-e0f0-11e8-8824-a41a1a7e4b03.png">

1. The shield appears on the left side of the URL, to the left of the lock icon.
    * I’m not sure if the icon has a high affordance (ie. it looks like it can be tapped), but it sure wasn’t hidden away inside any menu, like we do on Android.

2. When the shield blocks trackers, the counter increases.
    * This signals to the user that, the higher the number, the more TP blocks.
    * I’m not sure whether displaying the number without context is a good idea – see #594. Tracking Protection will be renamed Content Blocking in the future. It will block more things. Some of those things won’t be quantifiable.

3. The erase button appears on the right side.
    * This has been a feature of Focus for iOS since the day it became a browser.


-----

### Back to Android

Our current design looks like this:

<img width="240" src="https://user-images.githubusercontent.com/51007/47971117-075cd800-e0f3-11e8-8727-fea12d3b7ddc.png">

I propose to modify it to be like this:

<img width="240" src="https://user-images.githubusercontent.com/51007/47971070-57876a80-e0f2-11e8-8fac-600a0ffb031b.png"> <img width="240" src="https://user-images.githubusercontent.com/51007/47971137-4a1eb000-e0f3-11e8-96a9-981d4f55a50e.png">

We have the option of just having the shield alone, or having the shield and the number together.

1. The shield appears on the left side of the URL, as the only item there.
    * It’s no longer hidden inside the main menu
    * Unfortunately, the low affordance issue can’t be helped with such a flat visual style.
    * However, the shield replaces the lock as _the only icon on the left_. When using browser apps, users are used to seeing the lock on the left. If there’s something other than a lock, it may be more likely that users will tap it because they would find it out of the ordinary.

2. Optionally, when the shield blocks trackers, the counter can increase.
    * If we decide that numbers are important, and that we want to show it, then it will increase the affordance of the shield icon even more. When the user sees the icon changing, they will wonder what’s there, and they’re more likely to tap it.

3. The erase button appears on the right side, after the URL and before the menu icon.
    * The erase icon isn’t so easy to trigger, addressing our user complaints.
    * Why not make it the right-most icon on the URL bar, so it’s easier to tap? Because then, when you want to open the menu, you might accidentally erase. That’s even worse.
    * The user research session we’ve conducted suggested that we should consider aligning the Android and iOS trash icon design. This totally aligns the two. (Of course then we lose the FAB which is unique to Android. It’s a compromise).

4. Moving the shield and erase icons won’t interrupt the upcoming multitasking redesign.
    * We assume that the upcoming multitasking design won’t use the traditional “Number of tabs” button, that will put yet another button in the URL bar and interfere with the Erase action.

Do you think this solves our problems, @ekager @vesta0?

**Comment by ekager** [comment]
Thanks @brampitoyo ! I love the shield with the number of trackers blocked, I think that's really great for informing our users of tracker blocking and keeping them engaged. I know @Sdaswani will love that part too :)

Would clicking the shield icon open the tracker blocking/content blocking toggle then?

And we will remove the lock icon entirely for now?

**Comment by Sdaswani** [comment]
I'm a huge fan of having the shield surface the # of trackers, as we do on iOS. It's a simple way too remind our users about the product value. I also vote to add the # of trackers blocked tip that users can share out.

**Comment by SeburoSUMO** [comment]
I like the concepts and think that they solve the problem whilst reinforcing and maintaining product features.  I also like the idea of joining up the interfaces for Android and iOS, makes a lot of sense.

**Comment by lobontiumira** [comment]
@brampitoyo, @vesta0 can I close this issue as the elements are not as described [here](https://github.com/mozilla-mobile/focus-android/issues/3841#issuecomment-435719101)?

![Untitled](https://user-images.githubusercontent.com/40694158/120764611-ff6eaa00-c520-11eb-9109-86241d5e80d7.png)

**Comment by doivosevic** [comment]
Can we please revisit this? At least make the trash button toggleable in settings or make it disappear on long press. I can't click on things on websites
