### ISSUE TITLE
Consider activating Do Not Disturb while browsing

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3842]
### Why/User Benefit/User Problem

Often, I don’t browse just to pass the time. Instead, I’m trying to get somewhere. I have a task that I want to complete. But when my phone is active, it also shows me notifications, sounds and alerts for all sorts of things.

At best, these notifications steal my attention for a bit. My flow is broken, but I am able to recover it, though it still takes time and energy to context switch.

At worse, these notifications led me down a rabbit hole to other tasks and activities that are unrelated to my current task. I emerge many minutes/hours later totally forgotten of the task I wanted to accomplish.

My phone already understands that, when I’m driving, disruption can mean the difference between life and death – so it turns Do Not Disturb on. I want Do Not Disturb to be activated when I browse and need to focus on a task, and turned off when I’ve “reached my destination” (finished listening, watching, reading or browsing).

### What / Requirements

The ability to activate Do Not Disturb while you browse.

### Acceptance Criteria (how do I know when I’m done?)

Users feel like they’re more able to focus on getting things done and get less distracted when using Focus, as compared to other browsers.

**Comment by hackel** [comment]
This is not the responsibility of a browser.  You can either turn DND on manually (press volume, click DND button), or use an automation app like Tasker to do so whenever you open Focus or any other browser.  This is an extremely niche use-case.
