### ISSUE TITLE
Can't Play Comedy Central Videos in Focus with GV

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#3843]
## Steps to reproduce
1) Search for Daily Show
2) Go to Daily Show website
3) Try to play a video

### Expected behavior
Video plays

### Actual behavior
Message appears saying our bad - android 4.4.4 and chrome required to play video

### Device information

* Android device: Galaxy S8 with Android Oreo
* Focus version: Focus Nightly

**Comment by cpeterso** [comment]
Two hypotheses: Comedy Central might be sniffing the UA or using EME DRM.

Does the site work in Fennec?

Assuming the site works in Firefox desktop, if requesting the desktop site in Focus+GV:
* works, then the site is sniffing the UA and the Evangelism team needs to reach out to Comedy Central and ask them to stop sniffing.
* doesn't work, then there is some Gecko incompatibility that the GV team will need to debug.

**Comment by Sdaswani** [comment]
confirmed the video plays just fine on Fennec with desktop site requested. will file a web compat bug.

**Comment by Sdaswani** [comment]
https://github.com/webcompat/web-bugs/issues/20966

**Comment by Sdaswani** [comment]
This was found a year back but still not fixed: https://github.com/webcompat/web-bugs/issues/4735

**Comment by rpappalax** [comment]
I'm able to play some cc.com videos but there is a 5-10 second delay before they start.  

A few videos (like South Park) play on Fennec & Chrome but on Geckoview (and Webview), warn:  "This video is currently not available in the browser on your device."

device: Nexus 6P, Android 8.0.0

**Comment by cpeterso** [comment]
> I'm able to play some cc.com videos but there is a 5-10 second delay before they start.

@rpappalax Do you see the 5-10 second delay in GeckoView, Fennec, and Chrome?

> A few videos (like South Park) play on Fennec & Chrome but on Geckoview (and Webview), warn: "This video is currently not available in the browser on your device."

That sounds like an EME DRM issue in GeckoView and WebView. The site might be sniffing for desktop UA, but I doubt that's the issue because that would not explain why only some Comedy Central videos are affected.

Can you share a link to an example of South Park video (or whatever) that reproduces the "currently not available" error?

Both of the above issues sound like bugs we should probably investigate in GeckoView.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the Focus Nightly 97.0 (build 360031026 GV 97.0a1-20220101231829) with Oppo Find X3 (Android 11).
