### ISSUE TITLE
Don't clear cache when using GeckoView

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/focus-android#3853]
Currently, Focus clears the cache directory when cleaning up a session, even when using GeckoView. This results in a 3s startup time penalty on the Pixel 2 because Gecko has to unpack libraries again. I recommend we not do this :)

**Comment by cpeterso** [comment]
You can see performance difference in the "Cold Startup" graph on the [Android health dashboard](https://health.graphics/android). On that startup test (on which device??), Chrome takes 0.8 seconds, geckoview_example takes 0.9 seconds, and Klar+GV takes 1.2 seconds:

![canvas](https://user-images.githubusercontent.com/629193/48165748-62313380-e29b-11e8-8208-f1891bb3dbe5.png)

**Comment by Cheap-Skate** [comment]
This issue makes Focus awful to use on a slow device. It's supposed to be for "quick looks" at urls etc. But it can take tens of seconds from cold start until it starts loading the url.
I am very dubious about the Focus "cold start" timings on nimbledroid, I think they show when Focus presents its UI, which is fast. But from that point it is many seconds before it is ready to load a url. Over 10 seconds a slow device. You should perhaps time from cold start to when it is actually ready to load a page. A much, much longer time.
