### ISSUE TITLE
Some homescreen tips are not linked to a SUMO page or have a deep link to a setting

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/focus-android#3855]
## Steps to reproduce

1. Open Focus and observe the homescreen tips
2. Go to any page and tap on the trash can icon

### Expected behaviour
All of the homescreen tips have either a deeplink or a link to a SUMO page

### Actual behaviour
Some homescreen tips do not have a deeplink or a link to a SUMO page (eg. Try turning off Tracking Protection or Allowlist disables Tracking Protection for sites you know and trust)

### Device information

* Android device: Samsung Galaxy S8 (Android 8.0)
* Focus version: 8.0 GV

**Comment by vesta0** [comment]
"Turning off tracking protection" tip doesn't have a Sumo page currently, it can link to the new Sumo page for allowlist once it's available #3830
