### ISSUE TITLE
Open in Firefox Focus from custom tab keeps crashing/stopping

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/focus-android#3856]
## Steps to reproduce

1. Set Focus as the default browser
2. From Gmail open any link in a Custom Tab
3. Tap on the 3 dot menu and select "Open in Firefox Focus"

### Expected behavior
The page is opened in a Focus

### Actual behavior
Firefox Focus keeps stopping message appears - [video](https://drive.google.com/file/d/1auQ4nzEj5uwyWiQtDzluyWXlX78HvP3s/view?usp=sharing)

### Device information

* Android device: Samsung Galaxy S8 (Android 8.0)
* Focus version: 8.0 GV

**Comment by bsurd** [comment]
Closing this as it is not reproducible in build 323151211

**Comment by ekager** [comment]
This is a release blocker for GV. Looking into it this week
