### ISSUE TITLE
YouTube videos do not automatically play when opened from a link

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/focus-android#3857]
## Steps to reproduce

1. Go to https://rpappalax.github.io/testapp
2. In the "Misc Link Types" section tap on "Link to youtube, make sure it plays"

### Expected behaviour
YouTube opens and the video starts playing muted
### Actual behaviour
YouTube opens but the video does not play
### Device information

- Android device: Samsung Galaxy S8 (Android 8.0)
- Focus version: 8.0 GV

**Comment by vesta0** [comment]
Let's make sure "do not autoplay" flag is working as intended.

**Comment by sblatz** [comment]
From some initial investigation, it seems that external links to YouTube are not playing, but if a user is on YouTube and selects a video it is playing.

**Comment by sblatz** [comment]
[GV team investigation](https://bugzilla.mozilla.org/show_bug.cgi?id=1508733)

**Comment by Sdaswani** [comment]
Thanks @vesta0 - in GV builds, could we disable autoplay for all videos that autoplay with sound? That is what Firefox 66 is going to be doing so there is a desire for all of our products to support the same UX.
