### ISSUE TITLE
Add Telemetry Event for When User Removes Item From Allowlist

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3858]
As part of #3510 let's add a new telemetry event for when the user removes a site from their exception list to inform us on whether users switch off the toggle without intending to add that site to their allowlist (or change their minds) and how often that happens. 
Maybe we should also add a probe for the user opening the Exceptions List page in Settings? That way we can compare the users that add sites to the allowlist.
cc @vesta0

**Comment by vesta0** [comment]
Yes let's do that and also add one for clicks on "remove all sites"

Probes:

- Trackers blocked toggle activities (existing)
- Removing a site from allowlist
- User opening exceptions list page in Settings
- Removing all sites from allowlist
