### ISSUE TITLE
focus:test switch is always set to Geckoview enabled

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3860]
## Steps to reproduce
- Go to focus:test, disable geckoview
- after the app restarts, go to focus:test again

### Expected behavior
- switch is set to off
### Actual behavior
- switch is still set to on

### Device information

* Android device: Moto G5
* Focus version: master branch

**Comment by ekager** [comment]
Currently, the Nightly config overrides the switch and will always be on GV. Closing for now, but we may want to change this in the future.
