### ISSUE TITLE
Geolocation permission prompt not displayed

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/focus-android#3861]
## Steps to reproduce

1. Go to https://rpappalax.github.io/testapp
2. In the "Location Menu" section tap on "Get Location"

### Expected behaviour
A permission pop-up should be displayed letting the user allow or deny location access.

### Actual behaviour
No permission pop-up is displayed

### Device information

- Android device: Samsung Galaxy S8 (Android 8.0)
- Focus version: 8.0 GV

**Comment by npark-mozilla** [comment]
Geolocation isn't supported in Focus, as a conscious product decision - so closing this issue.
