### ISSUE TITLE
Completing onboarding in Custom Tabs doesn't show your tab at the end

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#3862]
## Steps to reproduce
1. Freshly install Focus.
2. Set Focus as default browser from Settings.
3. Go to a third party app and click a link to open Focus in a custom tab.
4. Observe Focus' onboarding showing up; continue or skip.

### Expected behaviour
After ending the onboarding, you should see the link loading in my custom tab.

### Actual behaviour
Onboarding completes and you see the main Focus screen.

Related? #263

### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: 8.0 (Build #323121216 🦎 64.0.20181022150107)

**Comment by ekager** [comment]
Did you send a link to Focus or open a custom tab? First run should not show for custom tab mode at all

**Comment by jonalmeida** [comment]
Whoops, I tried to reproduce it again and realized I didn't have a clean env when I was running into this.

Closing as works for me. 👌
