### ISSUE TITLE
On tablet simulator, cached webpage with trackers never completes loading

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3863]
## Steps to reproduce
Run ToggleBlockTest.java on Nexus 9 x86 simulator in Webview (debug build)
### Expected behavior
Test passes

### Actual behavior
Test fails, when the 'Trackers blocked' switch is turned off and the page is reloading.  adb log says onSessionLoadIdlingResource is not being set to idle, and the progressbar does not complete.
This doesn't happen on phone devices, will also try out on nexus 9 device next week, and determine whether this is a new test framework issue or app issue.

### Device information

* Android device: Nexus 9 API 25 Android simulator
* Focus version: master

**Comment by rpappalax** [comment]
per @npark-mozilla  this was a sim issue, hence closing
