### ISSUE TITLE
Sumo links for 8.0

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3865]
- [x] What's New
- [x] [Allowlist](https://github.com/mozilla-mobile/focus-android/issues/3830)

**Comment by jonisavage** [comment]
What's New page: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/whats-new-focus-android-8

Allow list: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/focus-android-allowlist
