### ISSUE TITLE
Custom Tab Disallows WSJ Login

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#3866]
## Steps to reproduce
1) Sign up for WSJ (may repro for other paywall sites too)
2) Open WSJ App
3) Ask to Login
4) [Focus Custom Tab opens asking for login]
5) Try to Login

### Expected behavior
Login is successful and WSJ app is logged in.

### Actual behavior
WSJ login button in Focus Custom tab spins forever

### Device information

* Android device: Galaxy S8 8.0
* Focus version: Nightly

**Comment by Sdaswani** [comment]
The login works fine with Fennec. Turning off TP in Focus didn't help either.

**Comment by vesta0** [comment]
Let's try to verify with the next nightly build.

**Comment by Sdaswani** [comment]
@rpappalax could you sign in with fennec (that worked for me)? I didn't try signing up with fennec.

**Comment by ekager** [comment]
Dialog now appears in newer GV builds allowing user to access the WSJ app. Closing.
