### ISSUE TITLE
Disable X86 UI test 

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3868]
### Why/User Benefit/User Problem
Saves costs
Sim testing doesn't offer significant benefits that device testing cannot
Tablet sim on Firebase is finicky

### What / Requirements
Stop sending the x86 test job to firebase

### Acceptance Criteria (how do I know when I’m done?)
When UI test report only contains ARM test results

**Comment by rpappalax** [comment]
dupe of #3987
