### ISSUE TITLE
Consider implementing side-bar pie controls 

### ISSUE THREAD

**Issue by ofirnk** [mozilla-mobile/focus-android#3873]
### Why/User Benefit/User Problem
Users want fast & intuitive control of their apps. 
A customizable pie control will allow the user to quickly open new pages, navigate between the opened tabs, move back & forward in history, etc'. 
Short video of ChromePie:
https://www.youtube.com/watch?v=Btn4qGeJp-c

### What / Requirements
Swiping from left/right side of the screen would open pie control screen with pre-defined actions 

### Acceptance Criteria (how do I know when I’m done?)
Interaction looks similar to that recorded in this video:
https://www.youtube.com/watch?v=Btn4qGeJp-c

![IMG](https://cdn57.androidauthority.net/wp-content/uploads/2014/09/chromepie-1.png)

**Comment by ofirnk** [comment]
See the stickiness of this feature:
https://forum.xda-developers.com/xposed/modules/mod-chromepie-add-pie-controls-to-t2869531
Users still want support for it and make crazy work around to make it support latest chrome.

**Comment by AyanamiSean** [comment]
can i work on this pls?

**Comment by DeltaSingh** [comment]
Pretty sure this is never going to be implemented at this point lol

It's completely dead on the newest Android 11 for Chrome as well. Dev simply stopped updating it.

**Comment by ofirnk** [comment]
It wtill works on my Android 9 with latest Chrome.

Idea is not to re-hook current implementation but to take current solution and migrate/re-implement it for Firefox.

The navigation concept of ChromePie is what this issue is about
