### ISSUE TITLE
Google Maps touch gesture also scrolls the page

### ISSUE THREAD

**Issue by rickydam** [mozilla-mobile/focus-android#3874]
## Steps to reproduce
1. Build `focus-android` in Android Studio or install `Firefox Focus` from the Play Store
2. Open https://google.com/maps
3. Move the map around with touch gesture

### Expected behavior
The touch gesture should only move the map.

### Actual behavior
The Google Maps touch gesture is not handled properly by `focus-android` and the page is also scrolled when trying to move the map.

### Device information
* Android device: OnePlus5T, Oreo 8.1.0
* Focus version: 7.0.13 (Latest Play Store version as of Nov 11, 2018)

### Extra information
The video first shows that the issue is not reproducible in `Firefox v63.0.2` downloaded from the Play Store. Then proceeds with showing the issue in `Firefox Focus v7.0.13` downloaded from the Play Store and ends with showing the issue still relevant in the version built from `focus-android` with the last commit being https://github.com/mozilla-mobile/focus-android/commit/c84135febe1b53ed93fa5731b1da216970434ddd or in other words, v8.0 build#11.

Video: https://drive.google.com/file/d/1BTsl3PuBiFuTKSx5ArQTaiXlybi-RC1K/view?usp=sharing

**Comment by ekager** [comment]
Related to #3815

**Comment by vesta0** [comment]
Same issue as being investigated in #3815
