### ISSUE TITLE
Video fullscreen option freezes the page in the About Mozilla section

### ISSUE THREAD

**Issue by rickydam** [mozilla-mobile/focus-android#3875]
## Steps to reproduce
1. Tap the triple dot menu on the top right
2. Tap on 'Settings'
3. Tap on 'Mozilla'
4. Tap on 'Your Rights'
5. Tap on 'Mozilla Public License'
6. Tap on the triple line menu on the top right
7. Tap on 'Firefox'
8. Tap on 'New Features'
9. Play any video
10. Tap on the fullscreen option

### Expected behavior
The video should be fullscreen.

### Actual behavior
The video fullscreen option freezes the page and the only thing that can be done is pressing the back button on the top navigation bar.

### Device information
* Android device: OnePlus5T, Oreo 8.1.0
* Focus version: 7.0.13 (Latest Play Store version as of Nov 11, 2018) and v8.0 build#11

### Extra information
The secret gist linked below contains the logcat output of this issue. I cleared the logcat right after completing step 8 and kept it going for approximately 10 seconds after the page froze.
https://gist.github.com/rickydam/ee67895c2652722253ed7c083b02f352

**Comment by ekager** [comment]
Thanks for filing!

This is happening because we launch a basic InfoActivity that just has a fragment with an IWebView with these links in Settings that does not handle fullscreen calls.

**Comment by devanand** [comment]
> Thanks for filing!
> 
> This is happening because we launch a basic InfoActivity that just has a fragment with an IWebView with these links in Settings that does not handle fullscreen calls.

Hi
May I take a look into this issue?

**Comment by lobontiumira** [comment]
I will close this issue because the videos are no longer available, and cannot test the described scenario.
Feel free to open a new issue, if you encounter it.
Thank you!
