### ISSUE TITLE
When in stealth mode the application window is not blacked out

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/focus-android#3876]
## Steps to reproduce
Go into settings and enable Stealth in the Switching Apps section
Tap on the Overview button and tap back into the app
Go to any webpage and tap the Overview button again

### Expected behavior
The application window should be blacked out

### Actual behavior
The application window shows the settings menu when in overview

### Notes
When not entering in overview after closing and restarting the app the screen is white instead of black

### Device information

* Android device: Nexus 5 (Android 6.0.1)
* Focus version: 8.0 WebView

[Video](https://drive.google.com/file/d/1kI6TLS8zA_wNAS3X5BRM_ith_zsxWrmA/view)

**Comment by ekager** [comment]
It looks like webview shielding is working but it won't black out the settings menu?

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly.
