### ISSUE TITLE
Crash reports are rejected by Socorro

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/focus-android#3878]
## Steps to reproduce
Induce a crash by navigating to `about:crashcontent`. Submit crash report by closing the crash dialog with the appropriate checkbox enabled.

### Expected behavior
Crash is submitted to Mozilla's crash-stats service. 

### Actual behavior
Crash not accepted by crash service. The following log line appears:
> I GeckoCrashReporter: Server rejected crash report

### Device information

* Android device: Pixel 2 / Pie
* Focus version: Nightly

**Comment by pocmo** [comment]
Looks like we are using "Firefox Focus" instead of "Focus" as the Socorro product name:
https://github.com/mozilla-mobile/focus-android/blob/c84135febe1b53ed93fa5731b1da216970434ddd/app/src/main/java/org/mozilla/focus/telemetry/CrashReporterWrapper.kt#L60

**Comment by boek** [comment]
Fixed with #3879
