### ISSUE TITLE
trash icon impact the site layout

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#3889]
This is a spin off of https://github.com/webcompat/web-bugs/issues/21230

**URL**: https://zinc.io/

**Browser / Version**: Firefox Focus
**Operating System**: Android 8.0.0
**Tested Another Browser**: Yes

**Problem type**: Something else
**Description**: The hamburger menu should be fixed. but it moves when you scroll the page.
**Steps to Reproduce**:

<details>
<summary>Browser Configuration</summary>
<ul>
  <li>None</li>
</ul>

</details>

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by vesta0** [comment]
We are working on optimizing the trash icon placement in #3841
