### ISSUE TITLE
Home Screen Link or Shared link unlocks session

### ISSUE THREAD

**Issue by m-j-r** [mozilla-mobile/focus-android#3890]
Edit: Using Version 7.0.13 (Build #323021954)
## Prerequisite
Press hamburger button > Settings > Privacy & Security > Switching Apps
Enable "Use fingerprint to unlock app"

### Steps to reproduce
- Start new Firefox Focus session
- visit any website (https://bing.com)
- press home key 
- Reopen focus 

`Unlock Firefox Focus` screen is displayed, allowing the user to unlock or create a new session

At this point, the session is 'locked'

Then, either
    Press home key, select previously created shortcut on the home screen
or
    Open another browser, and select share, and choose Focus as the destination

-------
At this point, the link is opened in Firefox Focus. 
***The trash/tabs button can be pressed to view other tabs from the otherwise locked session.***

I think rather Firefox Focus should open, with option for user to open the link in a new session, or to unlock the session and open the link.

**Comment by m-j-r** [comment]
This would be my desired UX, yes.

I'm not sure if it's the same path, or if I should open another issue, but the same thing occurs when opening a url previously added to home screen (from the hamburger menu).

**Comment by sv-ohorvath** [comment]
Verified on latest Nightly. Logged 2 new issues related to it: #3939, #3940
