### ISSUE TITLE
When custom autocomplete site is added, the site is not shown immediately

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3899]
## Steps to reproduce
Go to Settings -> Search URL Autocomplete-> Manage sites
click Add custom URL
add an URL, press save
### Expected behavior
Manage sites view shows the newly added URL

### Actual behavior
Manage sites view does not show the newly added URL, the user need to exit and come back (this is a regression)
### Device information

* Android device: ? API 25
* Focus version: ? master build

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly.
