### ISSUE TITLE
Add "Settings" icon above keyboard in Awesomescreen

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#39]
Once we get the icon in, we should leave a shortcut to the Settings above the keyboard when the user is typing. Again, mostly for iOS parity.

**Comment by antlam** [comment]
Note: we should probably keep this the same icon as issue #37 or not have this button above the keyboard.

Thoughts? @pocmo

**Comment by pocmo** [comment]
As an overlay menu that shows up above the keyboard - or should we try to move it to the toolbar? Not sure how this looks like but having the overflow menu in the toolbar would be more consistent. However I'm not sure whether we actually need access to the settings from the 'URL entering' screen? To change the search engine?

**Comment by antlam** [comment]
I agree. Let's hold off for now then.

Maybe we can also look at the usage on iOS to see if we need to prioritize this later? Even though that's a different platform, it could still help to see some numbers.

**Comment by pocmo** [comment]
Okay, I removed the v1.0 label and we can look at this later again.

**Comment by antlam** [comment]
Closing issue for now. It doesn't seem like we're heading in this direction anymore
