### ISSUE TITLE
Search suggestion does not work

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3904]
## Steps to reproduce
Enter word 'mozilla' on URL bar, press 'Yes' to enable search suggestion

### Expected behavior
Search suggestions appear

### Actual behavior
Search suggestions do not appear. See UI Test failure video here: https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6510499129904914545/executions/bs.da8991e503418a18/test-cases

### Device information
Pixel 2, API 26
* Focus version: on master

**Comment by npark-mozilla** [comment]
Yes, the first failure is found in this commit: https://github.com/mozilla-mobile/focus-android/commit/04be898b5b6169750367a656e6c2ca6a2bc6a5bd

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly.
