### ISSUE TITLE
In Focus, when TP switch is toggled when about:blank is shown during opening of an URL, gv crashes

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3911]
## Steps to reproduce
STR:
Open Focus, enter URL
When the page is loading, the URL bar briefly shows "about:blank" for a split second.  
Toggle the TP switch in the main menu 
### Expected behavior
Webpage is loaded normally

### Actual behavior
GV crashes 
### Device information

* Android device: moto g5
* Focus version: master
GV version: geckoview-beta-armeabi-v7a-64.0.20181112164519.aar

Bugzilla Link: https://bugzilla.mozilla.org/show_bug.cgi?id=1507319

**Comment by cpeterso** [comment]
@ekager Did your #3911 commit fix this TP toggle crash? Or is there an underlying GV crash that still needs to be fixed?

**Comment by sv-ohorvath** [comment]
Verified on Nightly.
