### ISSUE TITLE
Run A/B experiment (GV/WV) for 8.0 beta

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#3915]
## Problem Summary
Now that we have validated the experiment data based on the A/A test (#3489) we want to again run the A/B experiment to compare WebView and GeckoView in 8.0 beta

## What user problem(s) are we trying to resolve?
As a user, I want to have a good browsing experience on GeckoView powered Focus and not experience a negative difference in performance/feature availability between GeckoView and WebView.

## Outcomes
Set up the experiment (@colintheshots)
Create release dashboard (@mmccorks)

## Metrics
DAU, 1-day retention, 7-day retention, median session time, 95% percentile session time, avg page load
Need a dashboard similar to the previous A/B experiment:
https://sql.telemetry.mozilla.org/dashboard/focus-android-beta-7-0-1---geckoview-vs-webview

### Variations
50/50
A: WebView
B: GeckoView

## Conclusion
Considered successful if less than 10% regression on key metrics.

## Next Steps
If successful, roll out GeckoView to 8.0 release population (percentage to be determined by data scientist)

**Comment by dkanada** [comment]
Do you plan on leaving WebView in for debugging with a settings key or do you plan on removing WebView completely at some point?

**Comment by vesta0** [comment]
@dkanada we plan on eventually removing WebView once GeckoView satisfies our performance criteria.
