### ISSUE TITLE
Nimbledroid pageload test is crashing on Nexus 5

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3918]
## Steps to reproduce
Pageload tests on nimbledroid is crashing, where the scenario is:
- Load abcnews.go.com
- Open menu, turn off TP
- Clear history, and reload abcnews.go.com (fails at this point)

### Expected behavior
Page is loaded properly

### Actual behavior
crashes with 
'''
I/Gecko   ( 1586): NeckoParent::AllocPHttpChannelParent: FATAL error: App does not have permission: KILLING CHILD PROCESS
I/Gecko   ( 1586): 
I/Gecko   ( 1586): ###!!! [Parent][DispatchAsyncMessage] Error: PNecko::Msg_PHttpChannelConstructor Value error: message was deserialized, but contained an illegal value
'''

I cannot repro this with the devices I have (Moto G5, Pixel 2)
### Device information
[klar.txt](https://github.com/mozilla-mobile/focus-android/files/2587180/klar.txt)

* Android device: Nexus 5
* Focus version: 21

**Comment by cpeterso** [comment]
@npark-mozilla Is this a new crash on Nimbledroid? Is Nimbledroid hitting this crash frequently?

We have a two-year-old Gecko bug for this crash signature, so this is a known issue but not something we've been able to reproduce consistently. It's some sort of networking layer crash in Gecko. If we can reliably reproduce it on Nimbledroid, then we have a chance of fixing it. :)

Crash in IPCError-browser | PNecko::Msg_PHttpChannelConstructor Value error: message was deserialized, but contained an illegal value
https://bugzilla.mozilla.org/show_bug.cgi?id=1346368

**Comment by npark-mozilla** [comment]
@cpeterso For some reason, they're consistently hitting it on every submission since about 2 weeks ago.  I talked to their rep, and he was able to locally repro it on his nexus 5 twice in a row.

**Comment by cpeterso** [comment]
I wonder what changed 2 weeks ago (around November 1). According to my Focus+GV meeting notes, we updated Focus Nightly from GV 62 to 64 around that time. I don't know the exact date.

**Comment by cpeterso** [comment]
@npark-mozilla If Nimbledroid is hitting this crash consistently on every submission, how do we still have up-to-date test results from Nimbledroid? 🤔 

https://health.graphics/android/graph?site=https://people.com/amp-stories/royal-a-to-z

**Comment by npark-mozilla** [comment]
@cpeterso ah, not all scenarios fail - for a given run, aobut dozen or more scenarios fail with this crash.  So it is consistent per run, but doesn't happen on every scenario.

**Comment by npark-mozilla** [comment]
Another log from Nimbledroid - he reported that out of 3 times ran locally, failed twice.  I think this log is largely similar to the first one.

[klar13.txt](https://github.com/mozilla-mobile/focus-android/files/2589934/klar13.txt)

**Comment by npark-mozilla** [comment]
This crash is no longer showing up since Nov 26th build, after the GV update according to @boek . closing for now.
