### ISSUE TITLE
Set cookies blocking default setting to "Block 3rd party tracking cookies only"

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#3920]
### Why/User Benefit/User Problem

-As a user, I want to be protected from cross-site cookie tracking. 

-Feature parity: Desktop will start blocking 3rd party tracking cookies by default.

### What / Requirements

Change the cookies blocking default setting from "None" to "Block 3rd party tracking cookies only"

### Acceptance Criteria (how do I know when I’m done?)

-For new users or existing users who have not changed their cookie blocking setting from default: Default setting will be "Block 3rd party tracking cookies only"
-No changes for users who have changed their original cookie blocking setting from "None"

For existing users

**Comment by ekager** [comment]
Done in #3931

**Comment by sv-ohorvath** [comment]
Verified the new default on Nightly.
