### ISSUE TITLE
After deleting allowedlist, back arrow does not return to main settings menu

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3922]
## Steps to reproduce
- Open URL, and turn off tracking protection
- Go to settings, privacy & security, exceptions
- Press button to delete all allowlist
- Now the screen is in Privacy & Security page
- Press back arrow
### Expected behavior
- Goes to main settings menu

### Actual behavior
- Flashes the same screen briefly, and remains in privacy & security

### Device information
- Pixel 2, API 28
* Focus version: master

This is currently failing the l10n screenshot test

**Comment by sv-ohorvath** [comment]
Verified on latest Nightly.
