### ISSUE TITLE
SessionLoadedIdlingResource does not return idle in certain scenario

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3923]
## Steps to reproduce
In a scenario where the UI test script enters URL, then goes to settings and enter submenu, the UI script fails with the reason the SessionLoadedIdlingResource is timed out waiting for idle. If I don't open an URL, and go to settings and try to open submenu, it works fine.

for example, UI script below will fail at the very end:

       onView(withId(R.id.urlView))
                .check(matches(isDisplayed()))
                .check(matches(hasFocus()))
                .perform(click(), replaceText("www.google.com");
        onView(withId(R.id.urlView))
                .perform(pressImeActionButton());

        device.findObject(new UiSelector()
                .resourceId(TestHelper.getAppName() + ":id/webview")
                .enabled(true))
                .waitForExists(waitingTime);

        // Open setting
        onView(withId(R.id.menuView))
                .check(matches(isDisplayed()))
                .perform(click());
        onView(withId(R.id.settings))
                .check(matches(isDisplayed()))
                .perform(click());
        onView(withText(R.string.preference_privacy_and_security_header)).perform(click());

* Android device: Pixel 2
* Focus version: Api 28

**Comment by rpappalax** [comment]
per @npark-mozilla, fixed w/ workaround
