### ISSUE TITLE
App crashes when deleting custom autocomplete site

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3924]
## Steps to reproduce
- Add custom autocomplete site
- Exit, open the custom autocomplete site
- Go back to settings, and try to delete the custom autocomplete site

### Expected behavior
- Site is deleted 

### Actual behavior
- App either crashes, or goes back to the main view and shows the popup "history is deleted"
Check out stacktrace and video here:
https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7287091011619425506/executions/bs.fd77e27aed2024e4/videos
https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8455091469028993357/executions/bs.926c390c47433a67

`java.lang.RuntimeException: Unable to pause activity {org.mozilla.focus.debug/org.mozilla.focus.activity.SettingsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property job has not been initialized
`
### Device information

* Android device: Pixel 2, Nexus 6
* Focus version: master

**Comment by sv-ohorvath** [comment]
Verified on latest Nightly.
