### ISSUE TITLE
Focus crashes when user clicks on settings menu options listed

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#3932]
## Steps to reproduce

-open Focus and go to settings
-app crashes if user clicks on the following menu options:

search => search engine 
search => URL autocomplete => manage sites
privacy & security => exceptions

### Device information

* Android device: Pixel 
* Focus version: 8.0 (Beta)

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly.
