### ISSUE TITLE
Unable to send crash report

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#3933]
## Steps to reproduce
-open Focus and go to settings => search => search engine
-app crashes and the crash report prompt comes up

### Expected behavior
-user should be able to select "close" or "restart Firefox Focus"

### Actual behavior
-clicking on either "close" or "restart Firefox Focus" does not work as long as "Send crash report to Mozilla" is selected. Once the selection is unchecked, user can choose an action.

### Device information
* Android device: Pixel
* Focus version: 8.0 (beta)

![screenshot_20181117-003959](https://user-images.githubusercontent.com/42752644/48657935-359dba00-ea07-11e8-814c-160e3720f422.png)

**Comment by boek** [comment]
Fixed with #3974

**Comment by sv-ohorvath** [comment]
Verified as fixed.
