### ISSUE TITLE
Cannot scroll input into view on ddg

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/focus-android#394]
* Open focus
* Visit https://duckduckgo.com
* Type a few characters
* Try to scroll to reveal the input

Android One Spice running Android 6.0

Video of behavior https://www.youtube.com/watch?v=TssW7JLPmXc

**Comment by ahunt** [comment]
I can reproduce: it doesn't happen the first time I open the page, but if I open the menu, and close it - I get the same non-scrolling site.

**Comment by ahunt** [comment]
Using fitSystemWindows on fragment_browser, and enabling windowSoftInputMode=adjustResize results in better scroll behaviour (and the FAB also remains visible when the keyboard opens), but it pushes us out of the status bar.

Fortunately there's a more clever workaround:
https://github.com/mikepenz/MaterialDrawer/blob/fed00a199196efbc63296a081723e603647b5bc4/library/src/main/java/com/mikepenz/materialdrawer/util/KeyboardUtil.java

**Comment by ahunt** [comment]
I still don't have a 100% consistent reproduction recipe, but opening/closing the menu and entering/clearing text a few times usually results in the extra stuff at the bottom disappearing.

It's easier to just watch the FAB: if the FAB is visible, it should remain visible. And/or the FAB should reappear when scrolling up, regardless of keyboard visibility.
