### ISSUE TITLE
When adding a homescreen shortcut, the fingerprint auth appears

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3940]
## Steps to reproduce
1. Enable fingerprint auth in Privacy&security settings.
2. Go to a website and add it as a home screen shortcut.
### Expected behavior
Page is added on the homescreen.
### Actual behavior
Page is added on the homescreen and the fingerprint unlock prompt is displayed. Frustrating for such a small thing, the user doesn't think about it as leaving the app.
### Device information

* Android device: 
Google Pixel (Android 9)
Samsung Galaxy S8 (Android 8.0)
* Focus version: 8.0 (2018-11-18) build.

**Comment by sblatz** [comment]
Currently, any time the app is put "onPause" and resumed, the biometric authentication is required. Adding a link to the home screen is the same (to the system) as us pressing home and opening the app again. Making an edge case for this would likely require setting yet another boolean flag before exiting (something like: ```isAddingLinkToHomeScreen```) that biometricHandler would check before setting needsAuth onPause.

**Comment by lobontiumira** [comment]
I am able to reproduce this behavior on 92.1.1 RC build with OnePlus 5T (Android 10).
Is this behavior considered expected or is it a bug?
@amedyne could you please review and advise?

**Comment by lobontiumira** [comment]
Reproducible on Focus Nightly 97.0 (build 360031026 GV 97.0a1-20220101231829) with Oppo Find X3 (Android 11).

**Comment by amedyne** [comment]
@lobontiumira Verified that this is expected behavior.
Closing the ticket.
