### ISSUE TITLE
Shortcut to Incognito mode or permanent Incognito mode

### ISSUE THREAD

**Issue by sultanahamer** [mozilla-mobile/focus-android#395]
Hi There,

I am a user of Firefox android and I want to have a shortcut either in form of widget or something that launches Firefox in incognito. I have to every single time open Firefox click on tabs and then Incognito.
A permanent incognito option in settings might also suffice. Which means, I open Firefox and it opens a blank incognito page rather than a normal page.

**Comment by pocmo** [comment]
If you want to report a bug / or suggest a feature for Firefox for Android then please use Bugzilla:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android

This bug tracker here is only for "Focus" which is not released yet.

**Comment by sultanahamer** [comment]
Thanks for pointing me to the right place.
