### ISSUE TITLE
Tab crash reporter shows about:blank instead of "Tab crashed"

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3958]
## Steps to reproduce
1. Go to about:crashcontent.
2. Check the URL bar.
### Expected behavior
"Tab crashed" displayed in the URL bar.
### Actual behavior
about:blank  displayed in the URL bar.
### Device information

* Android device: Android 6 and lower.
Not reproducing on Android 7 and higher.
* Focus version: Nightly 8.0 GV (2018-20-11)

**Comment by boek** [comment]
@sv-ohorvath Is this still an issue? I'm not able to reproduce in a 5.1 sim.

Unless, do you mean the second it says `about:blank` before the Crash reporter comes up?

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly GV.
