### ISSUE TITLE
QR code reader

### ISSUE THREAD

**Issue by sultanahamer** [mozilla-mobile/focus-android#396]
Hi All, I am a everyday user of Firefox Android and I would like to see my browser capable of reading QR codes by itself rather than depending on a 3 party app. Also, lets handle the type of data present in QR if its link, open it, if its content just show the content rather than saying not a url. This is a nice to have feature I would say.

**Comment by pocmo** [comment]
This sounds like a bug report for Firefox for Android? If so then please open a bug here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android

This bug tracker here is for "Focus" an Android app that is not released yet. I'll keep this bug report though - we might want to add such a feature to Focus in a future version too.

**Comment by sultanahamer** [comment]
Thanks for pointing me to the right place.
