### ISSUE TITLE
Duplicated text when typing in a website's textbox (yes, again)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#3965]
I already mentioned it in #2807 but I guess it's besser to create a new issue report. I don't use Focus every day so I can't tell you the day when its regressed, but it has to be a recent regression.

### Steps to reproduce

1. install Firefox Klar Nightly with GeckoView
2. open google.com
3. try to enter "wiki" in the search field

### Expected behavior

- after 1. character: "w" in the search field
- after 2. character: "wi" in the search field
- after 3. character: "wik" in the search field
- after 4. character: "wiki" in the search field

### Actual behavior

- after 1. character: "w" in the search field
- after 2. character: "wwi" in the search field
- after 3. character: "wwiwik" in the search field
- after 4. character: "wwiwikwki" in the search field

### Device information

* Focus version: Firefox Klar 8.0.1 Build #323262357
* Gecko version: 64.0.20181119162153
* Android version: 8.0
* Device: HTC U11

(By the way, the Nightly Build also crashes a lot since a few days)

**Comment by cadeyrn** [comment]
I tested local builds of Focus with old revisions and found the regression. The bug has been re-introduced by the update from GV 64 Beta 7 to GV 64 Beta 9 in 7f30c2902a8aaf9f31a41eebad62bfdeb956216d. WebView builds are not affected.

**Comment by cadeyrn** [comment]
It's fixed by the latest GeckoView update / in the latest Nightly build.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly, with an HTC 10 (Android 8.0) device.
