### ISSUE TITLE
Tracker/ads is not blocking

### ISSUE THREAD

**Issue by SubhamTyagi** [mozilla-mobile/focus-android#3975]
**Focus Version:** 7.0.13

**Android version:** 7.1.2

**Description:** Firefox focus is not blocking some of ads on some website even if  trackers is blocked.
![](https://i.imgur.com/Gp7iDQA.png)

**Comment by SubhamTyagi** [comment]
more screenshot 

![](https://i.imgur.com/WcVAVlC.png)

**Comment by sblatz** [comment]
I believe this is a duplicate of #1253 and currently expected behavior:we do not currently try to block every ad.

That being said, I think this would be addressed with #3416 which will allow users to block more ads/trackers with custom lists.

**Comment by vesta0** [comment]
As noted by @sblatz we do not currently block every ad, we only block ads that track the user, so this is expected behaviour.

**Comment by vesta0** [comment]
Thanks for clarifying @SubhamTyagi. 

We have just shipped a new beta for Focus which I believe has fixed this issue. Feel free to give it a try (or wait for the new release) and let us know if the issue persists.

**Comment by SubhamTyagi** [comment]
@vesta0 

Firefox beta 8.0.2 (Build #323401829)
Problem persist 
![](https://i.imgur.com/5x1xCM1.png)

**Comment by vesta0** [comment]
@npark-mozilla can I ask QA to try and reproduce this?

**Comment by npark-mozilla** [comment]
@sv-ohorvath Oana, could you look into this please? Thanks!

**Comment by sv-ohorvath** [comment]
I can see the ads reported on this site, which are blocked with ublock on Fennec. @SubhamTyagi you said that the ads will follow you in other apps as well. Could you give me an example of an app?

**Comment by SubhamTyagi** [comment]
@sv-ohorvath 
i got the same suggestion on Amazon Shopping app.

**Comment by sv-ohorvath** [comment]
I can't reproduce this: using Focus 8.0.5 (with webView, as I see from the screenshot) and the Amazon shopping app (set to the India market). I don't get the same suggestions on the amazon app.
