### ISSUE TITLE
Erasing Custom Tab Focus Session from Notification shows home 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3976]
## Steps to reproduce
1. Open a custom tab
2. Click the notification to erase

### Expected behavior
Custom tab closes and goes back to calling app

### Actual behavior
Shows Focus homescreen in custom tab shell which we never want to show in a custom tab.

### Device information

* Android device: Pixel 2
* Focus version: Nightly

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on Focus Nightly 97.0 (build 360031026 GV 97.0a1-20220101231829) with Oppo Find X3 (Android 11).
