### ISSUE TITLE
Navigating to weird URL crashes Focus if not on Internet (or weak signal)

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3979]
## Steps to reproduce
1. Enter airplane mode (or have a *very* weak connection)
2. Open a garbage url, something like: "data:text/html;charset=64.com"

### Expected behavior
The normal "unable to connect" page is displayed

### Actual behavior
The app crashes

### Device information
* Android device: N/A
* Focus version: 8.0 

### Crash:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/4400286/49228041-8377d200-f3b8-11e8-9c76-81e577b18219.png">

**Note: this bug is likely very low priority, but it points to an issue with fretboard seen below**

**Comment by vesta0** [comment]
Related to #3938

**Comment by sblatz** [comment]
#4070 seems to have fixed this as well.

**Comment by sv-ohorvath** [comment]
Doesn't crash on latest Nightly (8.0.4 + GV).
