### ISSUE TITLE
Text selection toolbar displayed too far from the selection

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3981]
## Steps to reproduce
Go to a webpage.
Select text and watch the text selection toolbar.
### Expected behavior
The toolbar is displayed above the selected text.
### Actual behavior
The toolbar is displayed far above the selected text.
![screenshot_20181129-170317_firefox klar](https://user-images.githubusercontent.com/4037709/49231274-459b9d80-f3fa-11e8-9818-47c76160a518.jpg)

### Device information

* Android device: 
Samsung Galaxy S8 (Android 8.0)
Huawei P9 Lite (Android 6.0)
* Focus version: 8.0.1 Beta GV. Not reproducing on webView.

**Comment by ekager** [comment]
This was fixed as of today but is currently targeting 66. What is the next version of GV we will update to and should we ask for this to be uplifted?
CC @cpeterso

**Comment by cpeterso** [comment]
I asked Emily and Kats in [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1509271) if they think the fix is safe to uplift to GV 65 Beta. Or we could wait until after 65 release and create a GeckoView 65 relbranch for this fix.

**Comment by sv-ohorvath** [comment]
Verified on Master 9.0, with GV 65 that this is fixed.
devices: HTC Desire 820 (Android 6.0.1), Samsung Galaxy S8 (Android 8.0)
