### ISSUE TITLE
Black screen on opening Focus

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/focus-android#3982]
## Steps to reproduce
1. Open Firefox Focus.
### Expected behavior
The app should be open immediately without any delay.
### Actual behavior
The app presents a black screen on opening with some dealy of 3-4 sec after that the Firefox Focus home screen opens.
### Device information

* Android device: 8.0.0
* Focus version: 8.0.1 (Build #323311210 🦎 64.0.20181122182000)
### Additional information
The app should not be in background otherwise it will not replicate.

**Comment by colintheshots** [comment]
Was this on the first run or right after reboot? It seems likely this is the same issue where we're trying to grab A/B experiments from the Kinto server on initial install or after reboot.

**Comment by Scripterr** [comment]
> Was this on the first run or right after reboot? 

No this issue was around 4-5 days, thought it may be some glitch which will go away.
Every time you open the app it shows balck screen, while it will not reproduce if you load the focus and background it.
I tried to clear the data but it still shows the black screen every time.

**Comment by Scripterr** [comment]
If this information helps, the app launches immediately if not connected to any network.

**Comment by boek** [comment]
Dup of #3938
