### ISSUE TITLE
Unable/difficult to enter search criteria on hotels.com

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#3984]
## Steps to reproduce
-open hotels.com
-tap on the check-in or check-out field to enter a date

### Expected behavior
-user should be able to select a date before the date picker closes

### Actual behavior
-date picker closes before user gets a chance to select a date (I was able to do it on the 3rd try) or picks a random date and closes (I think depending on where the user tapped to open the date picker.

This bug was reported as part of the GeckoView/WebView perceived performance study and reproduced in the latest nighty. 

### Device information

* Device: Pixel
* Android device: 9
* Focus version: 8.0.1 (Build #323311210 GV 64.0.20181122182000)

**Comment by cpeterso** [comment]
This is likely a GV bug since it affects Focus+GV but not Focus+WebView. I filed a GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1511154

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly build from 2/25 with Oppo Find X3 Lite (Android 11).
