### ISSUE TITLE
Input fields on forms are covered by keyboard 

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#3985]
## Steps to reproduce
-Open USPS.com
-Tap on 'change my address' and then 'get started'
-Tap on any input fields

### Expected behavior
-As the keyboard opens, the input field should move up so the user can see what they are typing.

### Actual behavior
-Input field is covered by the keyboard.

-----
This bug was reported as part of the GeckoView/WebView perceived performance study and reproduced in the latest nighty.

### Device information

* Device: Pixel
* Android device: 9
* Focus version: 8.0.1 (Build #323311210 GV 64.0.20181122182000)

**Comment by cpeterso** [comment]
This is probably a GV bug, so I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1511174.

**Comment by makotokato** [comment]
@vesta0, I cannot reproduce this now using 8.0.6 (GV: 64.0.20190111134233).  Could you still reproduce using it?

**Comment by vesta0** [comment]
@makotokato you are right, it looks like this issue has been fixed.
