### ISSUE TITLE
All Firefox Apps Into F-Driod

### ISSUE THREAD

**Issue by trymeouteh** [mozilla-mobile/focus-android#3992]
Please add all the firefox apps on F-Driod. including Firefox, Firefox Nightly, Firefox Reality, etc.

This way we can enjoy Firefox without Google Play Store!

**Comment by vesta0** [comment]
Future consideration by @bbinto :)

**Comment by ionutbedregeanu** [comment]
@kbrosnan Do you have any information about this?

**Comment by cpeterso** [comment]
Closing this issue as a duplicate of https://github.com/mozilla-mobile/focus-android/issues/4182.
