### ISSUE TITLE
New homescreen tip to Focus survey

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#3994]
Meta: #3925 

### Why/User Benefit/User Problem
Users will be reached directly from within the app and have the opportunity to participate in a survey about Firefox Focus.

### What / Requirements
-New homescreen tip asking user to click on the link to participate in the survey
-Link to the survey
-Will show for a short time period (TBD)

### Acceptance Criteria (how do I know when I’m done?)
-New homescreen tip containing the provided string and link to the survey.
-Ability to hide tip once the survey window closes.

**Comment by raygervais** [comment]
Hey @vesta0, I'd be interested in working on this. May require some guidance since this is my first time diving into Firefox Focus for Android's community, but I'd be happy to learn along the way!

**Comment by vesta0** [comment]
@raygervais thanks for offering to work on this! This issue is not ready to be picked up yet - but feel free to look at other issues in this repo, especially ones with a "help wanted" or "good first issue" label. And here is a handy [getting started guide for Mozilla's Android projects](https://github.com/mozilla-mobile/shared-docs/blob/master/android/CONTRIBUTING_code.md) :)

**Comment by sblatz** [comment]
Setting this as "blocked" until we have strings so we know when it can be worked on!

**Comment by vesta0** [comment]
Strings (in English, French, and Spanish) will be provided on Monday Jan 21. This will launch as part of 6.0.7 on Jan 24.

**Comment by vesta0** [comment]
*Please note that all the survey invites currently default to English and localization is pending. 
cc @boek @sblatz 

Ideally, user should be able to click on the link only one time. Once clicked, they should not see the tip again.

_Target to locale EN (all geos)_
Please help us by taking a short survey. Click here.
https://qsurvey.mozilla.com/s3/Focus-2019-User-Survey

_Target to locale FR (all geos)_
Aidez-nous à améliorer en remplissant ce court questionnaire. Remplir le questionnaire.
https://qsurvey.mozilla.com/s3/d028b4c4d560

_Target to locale ES (all geos)_
Por favor ayúdanos haciendo una breve encuesta. Haz clic aquí.
https://qsurvey.mozilla.com/s3/8bbcb0edc4ff

**Comment by vesta0** [comment]
@sblatz yes exactly, thank you for clarifying :)

**Comment by sblatz** [comment]
This tip will now be the first tip to be display in the above locales, after which random tips will be shown.

**Comment by vesta0** [comment]
Thanks @sblatz. We can ship 8.1 once all the survey pages have been localized, hopefully by Friday.
