### ISSUE TITLE
Accent colour isn’t accessible against background colour

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#3995]
This is directly related to mozilla-mobile/focus-ios/issues/1385:

@sblatz wrote:

> I've had several people mention to me that they find the Done button in settings (as well as the "Learn more" text) difficult to read. This could present accessibility concerns.

@yzen wrote:

> It looks like the color contrast is 2.69:1 where for normal text you would want it to be at least 4.5:1.

To remedy this problem, we’d like to change the colour value of our links, buttons and form elements from `magenta-70` or `#b5007f` to `#e452B9`.

### Current

<img width="220" src="https://user-images.githubusercontent.com/51007/49354404-a6dbad80-f727-11e8-9be7-30e1cd19c726.png"><img width="220" src="https://user-images.githubusercontent.com/51007/49354409-a93e0780-f727-11e8-8cb4-ba5880090651.png"><img width="220" src="https://user-images.githubusercontent.com/51007/49354414-aba06180-f727-11e8-88df-c305b0a9ced0.png">
<img width="512" src="https://user-images.githubusercontent.com/51007/49354483-ffab4600-f727-11e8-8331-6bfa6aed0975.png">

### Proposed

<img width="220" src="https://user-images.githubusercontent.com/51007/49354333-51070580-f727-11e8-9d71-0c93a45b91de.png"><img width="220" src="https://user-images.githubusercontent.com/51007/49354336-53695f80-f727-11e8-8243-b974ebb382c2.png"><img width="220" src="https://user-images.githubusercontent.com/51007/49354341-55cbb980-f727-11e8-93bd-83a058192d47.png">
<img width="512" src="https://user-images.githubusercontent.com/51007/49354494-0934ae00-f728-11e8-8f73-f90e273c8277.png">

### Note

We’re not changing the value of our FAB or our “Erase Browsing History” menu item on the tab list.

The current FAB and tab list are due for redesign and may not exist in the future. But until then, we can keep the colour `magenta-70` or `#b5007f`

<img width="220" src="https://user-images.githubusercontent.com/51007/49354570-69c3eb00-f728-11e8-8ac4-9b4038ab0081.png"><img width="220" src="https://user-images.githubusercontent.com/51007/49354593-7ea07e80-f728-11e8-9888-4a72b3053dce.png">

**Comment by sv-ohorvath** [comment]
Verified as fixed on 8.0.3. 
device: Nokia 6 (Android 7.1.1), Huawei P9 Lite (Android 6.0)
