### ISSUE TITLE
Focus fails to launch if connected to WiFi that doesn't have Internet access

### ISSUE THREAD

**Issue by justdave** [mozilla-mobile/focus-android#3996]
## Steps to reproduce
1) Connect to a closed wifi network, for example on an airplane or in a hotel when you haven't purchased their Internet access package yet.
2) Launch Focus.

### Expected behavior
1) Focus launches.

### Actual behavior
1) Black screen (don't even get the purple) and it just hangs.
2) Turning off Wifi causes it to finish loading.

### Device information

* Android device: Samsung Galaxy S8, Android 8, Oct 2018 security patch
* Focus version: 8.0 (Build 323202344)

**Comment by daivat15** [comment]
Reproduced issue.
It occurs not only if I am on a closed WiFi network but also when my internet speed is extremely slow.

Android Device: Redmi Note 4, Android 8.1
Focus Version: 8.0 (Build 323202344)

**Comment by boek** [comment]
Dup of #3938
