### ISSUE TITLE
Add title attribute in image context menu

### ISSUE THREAD

**Issue by pgonzalezalv** [mozilla-mobile/focus-android#3997]
### Why/User Benefit/User Problem

It is not possible to see the title attribute of an image, for example when going on the following website with Firefox Focus:

https://xkcd.com/262/

In this case, the title contains "Hey, at least I ran out of staples." (see line 52 in the source code of the above web page). For now the image context menu shows the following:

![screenshot_title](https://user-images.githubusercontent.com/7594547/49468733-090ae000-f806-11e8-8442-4e01f8798036.jpeg)

### What / Requirements

Make the image title attribute available somewhere.

### Acceptance Criteria (how do I know when I’m done?)

If you long click on the image, it shows the content of the title attribute.

### Ideas

* In the current menu you could add an additional line to show the image title, e.g. Show image title;
* Or do something like in the Firefox app; when you long click on the image, it shows the title directly in the heading of the menu (but it is concatenated to two lines of the width of the menu, so for long titles it is not ideal).

I would like to work on this feature.

It is the first time I do that so I am not sure where to start exactly. Can I work on the code directly and just do a PR when I have something that is working? Or is there someone I should contact first?

**Comment by boek** [comment]
Hey @pgonzalezalv, this is a great idea! We would love a contribution.

You got it! Go ahead and fork the repo and open a PR when you have something that is working and we will review / give any feedback we have. If you have any questions feel free to reach out to me on here or on IRC 👍

**Comment by lobontiumira** [comment]
This is no longer an issue on the latest Firefox Nightly 97.0 (build 360041433 GV 97.0a1-20220103092929) with Oppo Find X3 Lite (Android 11):

![Screenshot_2022-01-04-14-43-01-92_11753d9bf2a67eec1c984b8ccb4d0671](https://user-images.githubusercontent.com/40694158/148061164-9af68f92-0a05-49d7-8648-b2a3b450fdf9.jpg)
