### ISSUE TITLE
Consider making homescreen tips more visible

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3998]
### Why/User Benefit/User Problem
Tips can be hard to read for users interested in seeing / interacting with them. 

### What / Requirements
We should consider making them easier to read by increasing the contrast, changing the font weight, or something to that effect.

### Acceptance Criteria (how do I know when I’m done?)
Tips are easier to read than they currently are.

**Comment by vesta0** [comment]
@brampitoyo any suggestions?

**Comment by brampitoyo** [comment]
Hi @sblatz. The tip text currently has good enough contrast against the background to pass the WCAG 2.0 standard.

* The background gradient contrast ratio was between 7.0–10.3 : 1
* On the gradient near the tips text, the ratio was between 7.3–9.0 : 1
* The recommended ratio for AA level small text is 4.5:1. For AAA level, it’s 7:1.

If we want to make them even easier to read, we can add a text shadow under the text.

Home screen icons on both Android and iOS has text shadow under them. Can we use that value and apply it to our tips? (I don’t know the exact value, but am able to research it if you like).

**Comment by sblatz** [comment]
@brampitoyo to clarify: I didn't mean that the contrast was inaccessible, rather that we discussed at All Hands wanting to make them bolder/stand out in some way. Shadows would be a great option for doing this!

**Comment by sblatz** [comment]
New text color per [Bram's comment](https://github.com/mozilla-mobile/focus-android/issues/4018#issuecomment-446797144):

<img width="317" alt="image" src="https://user-images.githubusercontent.com/4400286/49950029-0161d000-fec5-11e8-935c-b8454a320f11.png">

This seems a lot more visible to me, and I think it's sufficient. Do we think this fulfills this ticket, @vesta0?

**Comment by vesta0** [comment]
Yes I think this is more visible, thanks @sblatz and @brampitoyo

**Comment by sv-ohorvath** [comment]
Verified the change on Nightly (2018-01-07).
Devices: Samsung Galaxy S8 (Android 8.0), Sony Xperia Z5 Premium (Android 7.1.1)
