### ISSUE TITLE
Crash on miniprix.ro 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4005]
## Steps to reproduce
1. Go to miniprix.ro, select a category.
2. Open a few items in new tabs.
3. Scroll the product images on one of the pages opened.
### Expected behavior
Website works fine.
### Actual behavior
Website crashes: on the homepage (just scrolling the homepage), or on one of the tabs opened while scrolling through images.
[logcat](https://github.com/mozilla-mobile/focus-android/files/2653977/miniprix-logcat.txt)

### Device information

* Android device: Motorola Nexus 6 (Android 7.1.1)
Cannot reproduce on other devices, e.g,: HTC 10 (Android 8.0), Huawei P9 Lite (Android 6.0).
* Focus version: 8.0.1 Nightly GV 64.0.20181122182000 & 8.0.2 Beta GV. Doesn't crash on webView.

**Comment by vesta0** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1513402

**Comment by cpeterso** [comment]
@sv-ohorvath Can you still reproduce this crash? @snorp tried today but wasn't able to reproduce it.

**Comment by vesta0** [comment]
I am no longer able to reproduce this - but I could initially.

**Comment by sv-ohorvath** [comment]
Yes, I can't reproduce it either. Closing it.
