### ISSUE TITLE
Secure Connection Failed on Focus, and not on Nightly.

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4009]
## Steps to reproduce
Steps to reproduce are available at https://github.com/webcompat/web-bugs/issues/22173

The issue is not happening in Firefox Android for the same site. Focus displays a Secure Connection Failed.

**Comment by rpappalax** [comment]
i'm able to repro

**Comment by rpappalax** [comment]
I'm still able to repro this issue on:
Focus 8.0.4 (both WV and Klar)
Focus 7.0.13 (both WV and Klar) - same version on which reported in webcompat/web-bugs#22173
Android 8.0.0, Nexus 6P

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the latest Focus Nightly 99.0a1 (build 360630511 with GV 99.0a1-20220303094735) with Samsung Galaxy Note 8 (Android 9).
