### ISSUE TITLE
Tracking protection test page shows same results no matter the settings

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4014]
## Steps to reproduce
1. Go to https://mozilla.github.io/tracking-test/full.html
2. In Privacy settings, turn On all Tracking protection individual blockers: ads, analytic, social, other content.
3. Return to the webpage from step 1.
4. Switch off all blockers from Privacy settings. Re-check.
### Expected behavior
With all blockers on: page shows a fox with a sign with the message: "You have successfully enabled tracking protection. Please continue!"
With all blockers off, there is a black cat "Your browser is not set up for tracking protection. Please check your setup and try again."
### Actual behavior
On GV: with blockers on/off, the result is the same: displaying the black cat.
On WV: blockers both on/off, displays the success message (the fox).
### Device information
* Android device:
Motorola Nexus 6 (Android 7.1.1), Huawei P9 Lite (Android 6.0)
* Focus version: 8.0.2

**Comment by npark-mozilla** [comment]
The page shows cat if it loads the favicon from gravatar.com, but even on desktop strict mode, we don't block the tracker. (as seen below, detected by 3rd party tool)  I suspect for some reason, it's not in our blocker list anymore. 

![screen shot 2018-12-12 at 2 48 31 pm](https://user-images.githubusercontent.com/6930774/49895005-6235cd80-fe1d-11e8-9c5a-99209556f412.png)

**Comment by npark-mozilla** [comment]
in the blocklist.json, “gravatar.com” is listed in this manner:
```
 {
                "Automattic": {
                    "http://automattic.com/": [
                        "automattic.com",
                        "gravatar.com",
                        "intensedebate.com"
                    ]
                }
            },
```

**Comment by npark-mozilla** [comment]
@sv-ohorvath in the meantime, let's use a different site for the tracking protection check, since we can't do much about the blocklist itself

**Comment by sv-ohorvath** [comment]
Thanks for looking into this No-Jun!
