### ISSUE TITLE
[l10n] Add new locales for v8: bo, sn and co

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#4015]
Here are some new locales ready to ship on v8:
* Tibetan (bo)  -> supported in Android natively, shouldn't need to input name
* Shona (sn)  -> ChiShona in local language
* Corsican (co) -> Corsu in local language

Please also add in l10n.toml file in your repo. thanks!
(CC @boek)

**Comment by sv-ohorvath** [comment]
Verified the new languages are added on Nightly and work as expected.
