### ISSUE TITLE
Add adblock toggle to onboarding card

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#4016]
Breakout of #3616 

<img width="360" src="https://user-images.githubusercontent.com/51007/49708813-11479d00-fc96-11e8-80a1-f644b5f5e645.png">

**Comment by vesta0** [comment]
@brampitoyo could you add your latest mock-up for onboarding (new user) here please? Want to make sure it's the latest version :)

**Comment by brampitoyo** [comment]
@vesta0 The mockup I’ve posted a month ago is still the latest version. We can go ahead and implement it.
