### ISSUE TITLE
Show adblock intro card on first run after updating to 9.0

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#4017]
Breakout of #3616.

<img width="360" src="https://user-images.githubusercontent.com/51007/49708826-1b699b80-fc96-11e8-9fea-71d06d5ca392.png">

**Comment by vesta0** [comment]
@brampitoyo please add your most recent mock-up for adblock intro card for existing user :)

**Comment by brampitoyo** [comment]
@vesta0 For existing users, we are again changing the label of the toggle to match the label used in Settings:

Ad blocking → Block ads

<img width="360" src="https://user-images.githubusercontent.com/51007/50937332-03c14500-14d8-11e9-8f3e-609a6e47e80a.png">

**Comment by lobontiumira** [comment]
I'll close this issue, due to the fact that on the latest Focus Nightly 12/7, RC 95.1.0, the adblock intro card is displayed on the first run:

![Screenshot_2](https://user-images.githubusercontent.com/40694158/145054624-33fe3bf4-17cd-45da-9215-5c124d9d89ee.jpg)
