### ISSUE TITLE
Add adblock tip with toggle

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#4018]
Breakout of #3616.

<img width="320" src="https://user-images.githubusercontent.com/51007/49708838-30462f00-fc96-11e8-9e00-9124e5ecf20b.png"> <img width="320" src="https://user-images.githubusercontent.com/51007/49708842-36d4a680-fc96-11e8-8bfe-010a69a7634c.png">

**Comment by sblatz** [comment]
@brampitoyo what should the left/right margins be on the tip text? Currently the margins are both at 0dp so long tips go up against the edge of the screen. Here's what they look like at 60dp on each side (the closest I could get to your mock-up by eyeballing it):


## 0DP (before change)
<img width="250" alt="image" src="https://user-images.githubusercontent.com/4400286/49893459-6f50bd80-fe19-11e8-85e6-c1ff28be6314.png">

## 60DP (after change)
<img width="250" alt="image" src="https://user-images.githubusercontent.com/4400286/49893366-39133e00-fe19-11e8-9677-8d8be6cacabd.png">


Also, are you wanting us to change the tip text color? Currently it's set to ```#eeeeee```, but the image you posted looks pure white.

**Comment by brampitoyo** [comment]
@sblatz, the new margin looks great! The original spec calls for a 40dp margin.

Maybe what we need to do is see how all the tips appear on a big screen (like your simulator) and a smaller screen? As long as tips fit and reads well, that’s all that matters.

I originally set the tip text colour to grey-10 `#f9f9fa`. If we fix this, maybe it will also help fix issue #3998?

**Comment by sblatz** [comment]
I think following the original spec makes sense--here's what it looks like:

## 40DP

<img width=300 src=https://user-images.githubusercontent.com/4400286/49950635-2d318580-fec6-11e8-8d51-310037b2c244.png>

<img width=300 src=https://user-images.githubusercontent.com/4400286/49950840-95806700-fec6-11e8-846b-e4144fe05a01.png>

<img width=300 src=https://user-images.githubusercontent.com/4400286/49950844-96b19400-fec6-11e8-9643-2a13091d1cf7.png>

**Comment by brampitoyo** [comment]
@vesta0 The latest mock should say “Block ads” rather than “Ad blocking”. All other design specs (margin, colour, etc.) remain the same as what @sblatz has implemented.

![tip - users who haven't turned it on 2x](https://user-images.githubusercontent.com/51007/50937558-1f791b00-14d9-11e9-93f7-febca4518da7.png)
