### ISSUE TITLE
WV: Webpage still displayed on erase&open if the settings menu is opened

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4022]
## Steps to reproduce
1. Load a webpage.
2. Open the settings menu and leave it open.
3. Minimize the app.
4. Tap erase&open from the notification tray.
### Expected behavior
A new session is launched.
### Actual behavior
Only the settings menu is closed. The webpage from step 1 is displayed.
### Device information

* Android device: 
Huawei P9 Lite (Android 6.0), Motorola Nexus 6 (Android 7.1.1)
* Focus version: 8.0.2 Beta, webView. Also reproducing on Master.

**Comment by SubhamTyagi** [comment]
Focus :8.0.2 (Build #323401829 🦎 64.0.20181205213707)

Gecko view

Crashing while repeating above steps

**Comment by sblatz** [comment]
Here's the crash on GV:

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/4400286/50238321-1a6af500-038d-11e9-826b-d4d7c1d28818.png">

**Comment by sblatz** [comment]
This seems directly related to the underlying issue mentioned in the meta, #4034. I believe that fixing that meta would fix both this GV crash and the WV issue. [onStartCommand](https://github.com/mozilla-mobile/focus-android/blob/4ae8f297351302bb62f103918f0ee68dde49d7f8/app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt#L32) is never getting called anymore when the notification is pressed on, which is leading to erroneous behavior.

**Comment by sblatz** [comment]
Related to: #4021.

**Comment by sblatz** [comment]
### Demo

![webview](https://user-images.githubusercontent.com/4400286/50842233-42b69580-1334-11e9-88b9-305af0cff2a6.gif)
