### ISSUE TITLE
Add settings for ad blocking

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#4030]
![image](https://user-images.githubusercontent.com/1250545/49973081-94603180-fee8-11e8-9b80-b6e6992130a8.png)

**Comment by vesta0** [comment]
![android proposed 3 settings - privacy security 2x](https://user-images.githubusercontent.com/42752644/49973305-92a36780-ff02-11e8-8c44-27a15b78811e.png)

**Comment by vesta0** [comment]
@BrianNJones please review and approve the string for the new ad blocking toggle. The new design (based on feedback from the team + legal) includes one mega toggle. Thank you!

Lists that we need to reference:
-Easylist
-EasyPrivacy
-Fanboy's Annoyance List
-AdGuard Mobile Ad Filter

**Comment by BrianNJones** [comment]
My reco: 

Ad Blocking
Block ads and other annoyances
Stops ads and other annoyances using block lists from Easylist, EasyPrivacy, Fanboy's Annoyance, and AdGuard Mobile Ad Filter
*(note: this assumes we can combine all references to ads into the idea of "block ads")*

Tracking Protection
Block ad trackers
Removes ads designed to track site visits even if you don't tap them

Block analytic trackers
Blocks trackers that analyze and measure interactions like tapping and scrolling

Block social trackers
Stops social media-related trackers embedded on websites, including social share buttons

Block other content trackers
Blocks tracking activity, but may cause some sites and pages to behave unexpectedly

**Comment by vesta0** [comment]
cc @brampitoyo 

@BrianNJones thank you for the strings. So you recommend that we update the strings for tracking protection as well? I only have one suggestion to change "using blocklists from Easylist" to "based on Easylist, etc". What do you think? 

One more thing: For Easylist, EasyPrivacy, and Fanboy we want to credit Creative Commons License so we should note somewhere that the lists are under CC BY-SA and include credit to the people listed on this page: https://easylist.to/pages/about.html. AdGuard is also CC BY-SA but it doesn't specifically say who to credit, so we can just credit AdGuard. This can be done as a link to a Sumo page or less ideally as a section within settings. Would love your thoughts on this.

**Comment by brampitoyo** [comment]
Hi @BrianNJones, I’ve put your strings in our Settings UI, and they look good!

<img width="360" src="https://user-images.githubusercontent.com/51007/50127240-42971d00-02d5-11e9-866e-df859c7df1de.png">

@vesta0 We have a space under Settings > Mozilla to offer all the explanation we need about ad blocking (copyrights, credits, webpages, etc.)

![settings - privacy security - about ad blocking 2x](https://user-images.githubusercontent.com/51007/50127320-8ee25d00-02d5-11e9-9d0a-5ba1c5dae34a.png)

If we want to link to SUMO, we can either add a “Learn more” link under the “Block ads and annoyances” menu item itself, or alternatively under Settings > Mozilla.
