### ISSUE TITLE
[meta] Issues with Notifications

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#4034]
See:
1. #4021 
2. #4022 
3. #3821 
4. #3976 

I did a bit of investigation today, and at least #4021 and #4022 seem tied to launchmode changes (see #3624 / PR #3660 and subsequent PRs adding flags to intents to work with the new mode). I'm wondering if we can revert those changes and think of another way to open the Settings on pause/resume (#3624), otherwise something in the SessionNotificationService needs to change, but I can't quite figure out what will fix it.

**Comment by sblatz** [comment]
Would love @vesta0's thoughts on this

**Comment by colintheshots** [comment]
Launchmode changes are always impactful, but reverting everything will just go back to the old set of edge cases where singleTask clobbers the current task. We should fix the root cause.

**Comment by vesta0** [comment]
@colintheshots @ekager I need to know much effort it is to find/fix the root cause before prioritizing. We can discuss at sprint planning.
