### ISSUE TITLE
The summary string for enabling personal suggestion is copied from top sites

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-mobile/focus-android#4036]
## Steps to reproduce
1. Open Focus settings.
1. Go to Search.
1. Go to URL Autocomplete.
1. Compare thu summaries of the first two switches/preferences for enabling autocomplete.

### Expected behavior
The first switch enables autocompletion from some bundled list of URLs, and the summary corresponds to it - `Enable to autocomplete more than 450 popular URLs in the address bar.`.
The seconds switch enables autocompletion from some personal list, but the summary is copied and pasted from the previous switch, which is completely irrelevant for this option.

### Actual behavior
The string `preference_autocomplete_user_list_summary` should be replaced with a new one stating `Enable to add URLs to your personal list and autocomplete them in the address bar.`.

### Device information
* Focus version: 8.0.3 (build # 323491219 :lizard: 64.0.20181214004633)

CC @Delphine

**Comment by MikkCZ** [comment]
Or it can be `Enable to have %@ autocomplete your favorite URLs.` like in Focus for iOS.

**Comment by sblatz** [comment]
Use strings from: #3467.

**Comment by sv-ohorvath** [comment]
Fixed in Nightly (2018-12-20).
