### ISSUE TITLE
Extra characters in "Erase and open" in the app shortcut

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4041]
## Steps to reproduce
1. Long tap the Focus homescreen icon.
### Expected behavior
"Erase and open" & "Erase browsing history" options are displayed.
### Actual behavior
There are some extra characters in "Erase and open".
![screenshot_20181218-154037](https://user-images.githubusercontent.com/4037709/50158052-bd633680-02db-11e9-8877-82aa6ecc38cd.jpg)
### Device information

* Android device: 
OnePlus 5T (Android 8.0), Nokia 6 (Android 7.1.1)
* Focus version: 8.0.3 Beta & Nightly.

**Comment by vesta0** [comment]
This is a minor bug around the long shortcut label

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly GV & WV.
