### ISSUE TITLE
What's New Entry for 9.0

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/focus-android#4050]
Why

    Inform users about the latest update & changes

What

    SUMO page link explaining any new features/improvements of the version the user has just installed.

Acceptance Criteria (how do I know when I’m done?)

    User can access and exit the SUMO What's New Page

**Comment by vesta0** [comment]
I emailed @jonisavage with more details.

**Comment by jonisavage** [comment]
Here's the link you can use in product: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/whats-new-focus-android-9

The link above will redirect to this article: https://support.mozilla.org/en-US/kb/whats-new-firefox-focus-android-version-9

The article is hidden from search until the Focus/Klar v. 9 release date is finalized.
