### ISSUE TITLE
Crash reporter not working on Klar GV

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4052]
## Steps to reproduce
1. Load a website.
2. Go to about:crashcontent.
### Expected behavior
The tab-crashed reporter should be displayed.
### Actual behavior
Just a blank page.
### Device information

* Android device: Samsung Galaxy Note 8 (Android 8.0)
* Focus version: Klar 8.0.4 GV (build#323512256 GV 64.0.20181214004633) : https://drive.google.com/file/d/1MFIwsTRBD1NX9IDLEPWA85kZjspLPiar/view?usp=sharing

**Comment by sblatz** [comment]
Potentially related to https://github.com/mozilla-mobile/focus-android/issues/3958

**Comment by vesta0** [comment]
@sv-ohorvath would you please verify if this bug is fixed?

**Comment by sv-ohorvath** [comment]
Not fixed yet on Klar Nightly 8.0.4 GV.

**Comment by sblatz** [comment]
Seems to also not be working on Focus 8.0.5 GV? (https://github.com/mozilla-mobile/focus-android/issues/4006#issuecomment-451188337)

**Comment by lobontiumira** [comment]
I am still able to reproduce this issue on Klar 8.16.0 with Samsung Galaxy Note 8 (Android 9).
Not reproducible on Focus 8.16.0 with the same device.
