### ISSUE TITLE
Status bar and address bar doesn't have the same background when Focus is opened in-app

### ISSUE THREAD

**Issue by cosmic-echo** [mozilla-mobile/focus-android#4056]
## Steps to reproduce
Set Firefox Focus as the default browser and open a link by an app that supports in-app browser.

### Expected behavior
The address bar the the status bar sharing the same gradient background.

### Actual behavior
https://imgur.com/a/fNQtnn8

The address bar and the status bar doesn't share the same gradient background anymore like in older versions.

### Device information

* Android device: Moto G4 Play - Android 7.1.1
* Focus version: 8.0.4

**Comment by lobontiumira** [comment]
@cosmic-echo thank you for the report!
On the latest Focus Nightly 97.0 (build 360041451 GV 97.0a1-20220103092929), with Sony Xperia Z5 Premium (Android 7.1.1), the custom tab respects the status bar as Focus:

![Screenshot_20220104-145632](https://user-images.githubusercontent.com/40694158/148062790-e7f2f993-c409-4265-835c-244df1d5a9b7.png)

Feel free to file a new issue if you encounter the above mentioned behavior.
