### ISSUE TITLE
New strings for ad blocking and tracking protection settings

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#4058]
### Why/User Benefit/User Problem
-Clearly communicate what each setting means to the user now with the addition of ad blocking toggle.
-Underneath Ad blocking section, add a link to a Sumo page (to explain ad blocking + credit the blocklists we are using)

### What / Requirements
-New strings for ad blocking and tracking protection settings
-Localization
-New Sumo page to explain ad blocking + credit blocklists)

### Acceptance Criteria (how do I know when I’m done?)

![android proposed settings - privacy security - ad blocking mega list 2x](https://user-images.githubusercontent.com/42752644/50309053-48bf0200-046b-11e9-9f44-ded6268b2224.png)

**Comment by vesta0** [comment]
@Delphine FYI there are new strings on this page that will need localization. Just waiting for one final mock-up/approval.

**Comment by sblatz** [comment]
Note that the tracking protection strings are different here, too.

**Comment by vesta0** [comment]
@brampitoyo please upload the updated mock-up that also includes the link to Sumo page underneath the ad blocking section. Thanks!

**Comment by brampitoyo** [comment]
@vesta0 Sorry for the overdue reply! Your earlier comment arrived after I’ve left for holiday.

Here’s the updated mock that includes the link to SUMO:

<img width="360" src="https://user-images.githubusercontent.com/51007/50749379-6e3d6f80-12a3-11e9-9890-ed9adf12aac3.png">

**Comment by sv-ohorvath** [comment]
Partially verified the new strings under Tracking Protection. Cannot verify yet the hidden Ad blocking section.
