### ISSUE TITLE
Add telemetry event ping for enabling/disabling ad blocking

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#4059]
### Why/User Benefit/User Problem
-To measure the success of this feature with users (How many active users enable ad blocking)
-Ability to measure impact of ad blocking on user engagement
-Ability to measure impact of ad blocking on page load performance

### What / Requirements
-Probe for enabling ad blocking
-Probe for disabling ad blocking
(so we can measure how many users tried it and didn't like it + how long they had ad blocking enabled each time)

### Acceptance Criteria (how do I know when I’m done?)
-Add probes
-Update Focus telemetry documentation

**Comment by sblatz** [comment]
Currently blocked on adblock being merged in. Will handle this as soon as that's ready!

**Comment by lobontiumira** [comment]
This is now fixed - please see https://github.com/mozilla-mobile/focus-android/issues/5653#issuecomment-999426337.
