### ISSUE TITLE
truncated text in German version

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#4068]
## Steps to reproduce

1. open a website in a German version of Firefox Klar
2. press the menu button

### Expected behavior

No truncated text.

### Actual behavior

Truncated text: "Wenn Sie diese Option deaktivieren, werden möglicherweise einige Probleme mit der Website"

![screenshot_20181224-224321](https://user-images.githubusercontent.com/1100614/50491077-b68d9f80-0a10-11e9-88d8-ea8d4c4a2b45.png)

### Device information

* Android device: HTC U11 / Android 8.0.0
* Focus version: 8.0.4 Build #323601226

**Comment by sblatz** [comment]
Looks like the true text should read:

Tracking protection: "Wenn Sie diese Option deaktivieren, werden möglicherweise einige Probleme mit der Website behoben"

Add to home screen: "Zum Startbildschirm hinzufügen"

Request desktop site: "Desktop-Seite anfordern"

**Comment by sv-ohorvath** [comment]
Verified as fixed on Master (both GV & WV) 8.0.6.
