### ISSUE TITLE
There should be some padding for contextual hints on start screen

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#4069]
## Steps to reproduce

1. see the contexual hints on the start screen in the German version of Firefox Klar

### Expected behavior

The text should not stick to the edge of the window.

### Actual behavior

Looks bad:

![screenshot_20181226-000839](https://user-images.githubusercontent.com/1100614/50491514-ffdeee80-0a12-11e9-9219-e3e9c643c22c.png)

### Device information

* Android device: HTC U11 / Android 8.0.0
* Focus version: 8.0.4 Build #323601226

**Comment by BinduVerma123** [comment]
@cadeyrn can i work on this issue?

**Comment by cadeyrn** [comment]
@BinduVerma123 I don't work for Mozilla. I can't answer the question whether you can work in this issue or not.

**Comment by BinduVerma123** [comment]
@cadeyrn ok sorry

**Comment by cadeyrn** [comment]
This is also an issue with the new carousel implementation.

![Screenshot_20210830-212521](https://user-images.githubusercontent.com/1100614/131394715-68b22fd5-e66e-4314-9dd3-c7efb0928f04.jpg)

**Comment by cadeyrn** [comment]
Fixed by #5281.
