### ISSUE TITLE
Downloads show dialog, but never start downloading

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/focus-android#4072]
## Steps to reproduce
1. Try to download a file at an insecure HTTP link, such as http://www.ovh.net/files/1Mio.dat
2. The download may work. If one keeps retrying or switches renderers, at some point downloads will show the dialog to start the download, but the download manager will never actually begin the download.
3. LogCat shows, "W/DownloadManager: [1137] Stop requested with status HTTP_DATA_ERROR: Cleartext HTTP traffic to www.ovh.net not permitted"

### Expected behavior
Pressing DOWNLOAD will cause the download manager open a notification and download the file.

### Actual behavior
Pressing DOWNLOAD does not always begin the download or show a notification. A notification may appear after awhile showing the Download Failed.

### Device information

* Android device: Pixel 3XL, Android 9, Dec 5, 2018 patch level
* Focus version: 8.0.4

**Comment by colintheshots** [comment]
This appears to be caused by a known bug in the Android Pie release. The cleartextPermitted flag works great for the browser itself and it works initially in the DownloadManager, but something causes the DownloadManager to forget the flag and fail future downloads. Even though the download can never succeed, it retries until you eventually get a "download failed" notification.

https://issuetracker.google.com/issues/114143692

No workaround or fix is confirmed yet, but someone should investigate further.

**Comment by npark-mozilla** [comment]
any chance this is also result of #2696?  That issue hasn't been fixed for a while because it was a webview issue.

**Comment by runboy93** [comment]
It does show download box, to choose save file or cancel, for any files so far tested. When I went to check file location, it has Android logo over it and says: "In queue", after while it does change "Failed", so something wrong with Focus 8.0.4+ builds. I think build 8.0.3 worked fine, if I remember right.

Works on every other browser (tested Chrome, Firefox, Opera)

**Comment by lobontiumira** [comment]
This is no longer reproducible on Firefox Nightly 97.0 (build 360041433 GV 97.0a1-20220103092929) with Oppo Find X3 Lite (Android 11).
