### ISSUE TITLE
Disable on exit toast

### ISSUE THREAD

**Issue by Sparow199** [mozilla-mobile/focus-android#4074]
## Steps to reproduce
Firefox Focus is the default browser on my device. When i open an url from Twitter, it's displayed on Firefox Focus but when the back button is pressed it's always display the toast "Your browsing history has been cleaned". It's very unpleasant

### Expected behavior
Not show the toast message on exit or add setting to disable it.
### Actual behavior
Always show the toast when Firefox Focus is closed.
### Device information

* Android device: OnePlus 6T
* Focus version: 7.0.13

**Comment by vesta0** [comment]
Expected behaviour
