### ISSUE TITLE
Convert Java classes to Kotlin

### ISSUE THREAD

**Issue by nikit19** [mozilla-mobile/focus-android#4075]
## Steps to reproduce
There are several classes in the repository written in Java, I would like to convert them to Kotlin. I would like to start by converting the util classes.
### Expected behavior
All the Java classes should be converted to Kotlin

I would like to work on this issue.

**Comment by devanand** [comment]
I would like to work on this issue. Could I take it?

**Comment by Aman199825** [comment]
I would like to work on this issue.May I ?

**Comment by kamaleshpati** [comment]
i would like to work on it..can i?

**Comment by shangeethsivan** [comment]
@colintheshots @vesta0 I have raised a PR for this can you please check it out. ?

**Comment by prajwalgowdahg** [comment]
i would like to work on this

**Comment by losdc** [comment]
I would like to work on this.Can I?

**Comment by bhushan-borole** [comment]
Hello @nikit19 
Is this issue still available to be worked upon?
I would like to go for it.
Thank you

**Comment by luisgrcia** [comment]
Hi :)
I think you know my question.
Is this issue still available to work on it?
Have a nice day 😄

**Comment by luisgrcia** [comment]
> Hi :)
> I think you know my question.
> Is this issue still available to work on it?
> Have a nice day 😄

#4632

**Comment by kanika-narang** [comment]
Hi, 

I am interested in contributing, is this task still open. 

Thanks and have a nice day.

**Comment by gurleennsidhuu** [comment]
Hi. Can I work on this issue?

**Comment by yashj6294** [comment]
Hi,
I would like to work on this issue
