### ISSUE TITLE
Klar no certificates at entry AndroidManifest.xml 

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/focus-android#4082]
## Steps to reproduce
Download Klar from the releases
`adb install -r Klar-arm.apk`

### Expected behavior
App installs

### Actual behavior
`adb: failed to install Klar-arm.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl189313165.tmp/base.apk has no certificates at entry AndroidManifest.xml]`

### Device information

* Android device: N/A
* Focus version: Klar - v8.0 - RC10

**Comment by MinIsMin** [comment]
Looks like it's the same for Focus. RC11-arm is also not working.

**Comment by colintheshots** [comment]
It looks like the TaskCluster build doesn't show signed artifacts very
quickly in its web interface even after reloading, so it's natural to grab
the wrong, unsigned artifact by mistake. This was a release engineering
mistake caused by a bug in TaskCluster.

**Comment by MinIsMin** [comment]
Is working again with 8.0.8
