### ISSUE TITLE
Re-enable AA Test for all Focus Versions

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#4085]
## Steps to reproduce
This graph is getting hammered: https://sql.telemetry.mozilla.org/dashboard/focus-aa-test

### Expected behavior
We still see the AA test results

### Actual behavior
We aren't seeing the AA test results for 8.x

### Device information

* Android device: ?
* Focus version: 8.x

**Comment by Sdaswani** [comment]
@colintheshots @boek is this risky to do for 8.0.6?

**Comment by colintheshots** [comment]
I'm virtually certain this is another dashboard filtering issue.

**Comment by Sdaswani** [comment]
So @colintheshots the AA test is enabled for master / 8.0.x?

**Comment by colintheshots** [comment]
Oh, it's still enabled. However, looking at the current version regex, it'll need to be updated. This is what we get for asking for a very specific version minimum using regexes to match only.

Current regex: (^[7-9]\.[1-9][0-9]*(\.[0-9]+)?$)|(^[7-9]\.[0-9]+\.[1-9][3-9]+$)|((^[7-9]\.[0-9]+\.[2-9][0-9]+$))

**Comment by Sdaswani** [comment]
Awesome @colintheshots I will close this after the AA test comes around!
