### ISSUE TITLE
Fingerprint lock causes browser to crash.

### ISSUE THREAD

**Issue by XXXTentacion** [mozilla-mobile/focus-android#4086]
## Steps to reproduce

1. Enable fingerprint locking of the Focus app.
2. Exit from the menu and try to go to any website or enter any search query.

### Expected behavior

The browser will go to any link or search query entered.

### Actual behavior

The app crashes whenever the query is submitted by the enter key or by the search recommendation.
It can be fixed by disabling the fingerprint lock.

### Device information

* Android device: Galaxy S6
* Focus version: 8.0.5 (Build #323630407)

**Comment by Bhavnaharitsa** [comment]
Hello,there! Could I work on this ?

**Comment by colintheshots** [comment]
I'll test on my S6 test device.

**Comment by sv-ohorvath** [comment]
I couldn't reproduce on Galaxy S8 & Galaxy Note 8.
