### ISSUE TITLE
Master branch fails to build (string import issue)

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#4087]
Since Dec. 31, master branch build is failing.

https://tools.taskcluster.net/groups/Tw10GcvkTf2IJcmX2Uj4eA/tasks/G6WKIlPZQ46CePiIC9FHuQ/runs/0/logs/public%2Flogs%2Flive.log

It may be the we need to reimport strings, according to @colintheshots

**Comment by boek** [comment]
To fully fix this we will have to remove the string, export and re-import. This is quite the process as it also involves l10n. I've moved the string to a deprecated section until we can coordinate this effort.
