### ISSUE TITLE
about:crashes with GV shows no text such as "Submitted Crash Reports" label

### ISSUE THREAD

**Issue by makotokato** [mozilla-mobile/focus-android#4089]
## Steps to reproduce
When any crash issue occurs on Firefox Focus, about:crashes can show crash id like Fennec.  Crash id is shown via about:crashes, but no text (such as "Submitted Crash Reports" text label, "View" label button and etc) in about:crashes.  (Maybe GV bug, or this depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1496190)

![screenshot_20190104-161811](https://user-images.githubusercontent.com/965338/50677353-c292e600-103c-11e9-884a-2ee132e372bc.png)

### Expected behavior
Show localized text such as "Submitted Crash Reports" and "View" label into button

### Actual behavior
No text into localized text

### Device information
* Android device: Xperia X Compact
* Focus version: 8.0.5 (GV 64.0.20181214004633)

**Comment by lobontiumira** [comment]
This is the current behavior of the about:crashes page on the Focus Nightly 97.0 (build 360031026 GV 97.0a1-20220101231829) on Oppo Find X3 Lite (Android 11):

![Screenshot_2022-01-03-16-36-00-29_11753d9bf2a67eec1c984b8ccb4d0671](https://user-images.githubusercontent.com/40694158/147950994-5646134c-8e5e-4a1d-b942-dda69c9ce245.jpg)
