### ISSUE TITLE
With multiple tabs opened, after a crash they have to be forced closed

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4090]
## Steps to reproduce
1. Load 2 web pages in 2 tabs (or more).
2. In the <b>first</b> tab, go to about:crashcontent
3. When the crash reporter appears, close the tab.
4. Try to close all remaining tabs by pressing the trashcan icon.
### Expected behavior
All tabs are closed. The browser is functional again.
### Actual behavior
On Focus GV latest release v.8.0.5 (Build #323630407 GV 64.0.20181214004633):
- If the FIRST tab crashes, you can't close the remaining (blank) tabs. The browser has to be restarted.
- If the 2nd (or other than the first) tab crashes, tabs are blank but you can delete them and continue using the browser (issue #4006).

Note:
on Nightly v.8.0.4 ( Build #330041213 GV 64.0.20181214004633):
- no matter which tab crashes, pressing close tab in the crash reporter closes all automatically, the browser is still functional.

### Device information
* Android device: Pixel (Android 9), Huawei P9 Lite (Android 6.0)

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the latest RC 92.1.1 build, using a Google Pixel (Android 10), and a Samsung Galaxy Note 8 (Android 9).
