### ISSUE TITLE
Why no bing search engine? 

### ISSUE THREAD

**Issue by NCC1701M** [mozilla-mobile/focus-android#4093]
In several issues #1263 #1264 it's mentioned, that bing is removed from the search engine list on purpose.

Why?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802021

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
