### ISSUE TITLE
Crash when opening the tab counter after accessing a link from one of the tabs

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/focus-android#4114]
## Steps to reproduce

1. Open 4-5 tabs in Focus
2. Open a couple of other links inside one of the tabs
3. Tap on the tab counter quickly after opening a link

### Expected behavior

Link and tab counter open up correctly

### Actual behavior

Focus crashes

### Device information

* Android device: Samsung S9, Android 8.0.0
* Focus version: 8.0.5 - Gecko and Webview

https://youtu.be/vh9hF-D4He0

[logcat.txt](https://github.com/mozilla-mobile/focus-android/files/2746036/logcat.txt)

**Comment by lobontiumira** [comment]
This issue no longer reproduces.
Tested on 8.16.0 Focus build using a Google Pixel (Android 10), and a Samsung Galaxy Note 8 (Android 9).
