### ISSUE TITLE
Add a Learn More link to the Tracking Protection settings

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#4116]
### Why/User Benefit/User Problem
-As a user, I'd like to know more about tracking protection and how it's done in Focus. 
-We want to credit the tracking protection list providers.

### What / Requirements
-Add a "Learn more" link to a new Sumo page underneath the Tracking Protection settings.

### Acceptance Criteria (how do I know when I’m done?)
-Tap on Learn more takes me to the new Sumo page.

![screenshot_2019-01-10 50749393-857c5d00-12a3-11e9-8d96-2413e9d89b55 png png image 720 x 2600 pixels - scaled 30](https://user-images.githubusercontent.com/42752644/50987886-daed7f80-14d8-11e9-9b92-d1bcf6964869.png)

**Comment by jonisavage** [comment]
Here's a link you can use for the Learn More page: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/ad-blocking-focus

It will redirect to the SUMO page.

**Comment by lobontiumira** [comment]
This is not implemented yet on the Focus Nightly build 360031026 GV 97.a01-20220101231829 with Oppo Find X3 Lite (Android 11):

![Screenshot_2022-01-03-17-52-48-39_11753d9bf2a67eec1c984b8ccb4d0671](https://user-images.githubusercontent.com/40694158/147951462-7509a9ba-7695-40a2-b14c-5261afad20be.jpg)
