### ISSUE TITLE
Homescreen tips never shown on Beta

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4119]
## Steps to reproduce
1. Install the Beta version from the playstore.
2. Launch Focus.
3. Clear data/reinstall the app. Launch Focus again. Repeat.
### Expected behavior
Homescreen tips should be displayed. 
### Actual behavior
As far as I remember they are displayed based on an A/B test, but they never appear.
### Device information

* Android device: Samsung Galaxy S8 (Android 8.0)
* Focus version: Beta 8.0.5 GV & WV. Works on Nightly 8.0.5.

**Comment by vesta0** [comment]
Already fixed.

**Comment by sv-ohorvath** [comment]
Verified on Release 8.0.6 and home screen tips are displayed.
