### ISSUE TITLE
Application upgrade doesn't retain tabs

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4120]
## Steps to reproduce
1. Install an older version of Focus.
2. Open a few tabs, leave the app open.
3. Go to Gplay and update the app.
4. Return to Focus and check the tabs.
### Expected behavior
Tabs are saved after the upgrade.
### Actual behavior
Tabs are lost.
### Device information

* Android device: Samsung Galaxy Note 8 (Android 8.0)
* Focus version: 8.0.5 GV & WV.

**Comment by zznidar** [comment]
I suppose this is the expected behaviour, as updating an app kills it and installs the new version – it's like closing Firefox Focus copletely and re-opening it. This does indeed clear the tabs.
