### ISSUE TITLE
A11y - The tabs manager/erase tabs icon doesn't remain visible while scrolling

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4122]
## Steps to reproduce
1. Turn Talkback On.
2. Load a scrollable page in Focus.
3. Scroll the page down using two fingers.
### Expected behavior
The tabs manager(on Nightly)/erase history (on Beta) icon is visible while scrolling. #2784
### Actual behavior
The tabs manager(on Nightly)/erase history (on Beta) icon hides while scrolling.
### Device information

* Android device: ?
* Focus version: ?

**Comment by lobontiumira** [comment]
This is still reproducible on the 8.16.0 Focus build.
Tested with Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
This issue is no longer relevant, because of the moving of the trashcan icon and tabs counter near the toolbar.
