### ISSUE TITLE
Keyboard overlaps "Find in Page" textbox

### ISSUE THREAD

**Issue by zznidar** [mozilla-mobile/focus-android#4127]
## Steps to reproduce
1. Open a website
2. Select ⋮ -> Find in Page

### Expected behavior
The textbox should be positioned just above the keyboard.

### Actual behavior
The textbox is overlapped by the keyboard, see screenshot.
![screenshot_2019-01-11-20-27-12-942_org mozilla focus](https://user-images.githubusercontent.com/20877556/51055819-56d2ef00-15e1-11e9-9a9b-bb5d243e7705.png)
### Device information

* Android device: pocophone f1, Android 8.1
* Focus version: 8.0.5
* Keyboard: Gboard

* Android device: Samsung Galaxy S8+, Android 8.0
* Focus version: 8.0.5
* Keyboard: Gboard, Samsung Keyboard, SwiftKey

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the 8.16.0 Build, using a Google Pixel (Android 10), and a Samsung Galaxy Note 8 (Android 9).
