### ISSUE TITLE
Override activity thumbnail on pause (application switcher)

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/focus-android#413]
I think akin to iOS (https://github.com/mozilla-mobile/focus/commit/6be7f3f5ee08b9d364f82868e2bc70d464db2a1c), we should override the activity thumbnail on pause (in the application switcher) just for better privacy reasoning.

**Comment by pocmo** [comment]
* In debug builds this feature is disabled (So that we can easily run tests, take screenshots etc.)
* There's an edge case where this protection can fail: #325
* Unfortunately there's no API to replace the image in recent apps with something else (it will always be just blank)
