### ISSUE TITLE
Google Play version is still 7.0 although version 8.0.6 is already available

### ISSUE THREAD

**Issue by zerdo90** [mozilla-mobile/focus-android#4131]
When downloading Focus app from Google Play it downloads version 7 and always informs that there are no available updates, but you can already manually download Focus version 8.0.6. It is a bit annoying as manual downloads do not update themselves automatically.

Androd version: 6.0.1

**Comment by vesta0** [comment]
Hi @zerdo90, we are doing a slow roll out of 8.0.6 so you should receive the update in the next 2 weeks. Thanks for your feedback!
