### ISSUE TITLE
Error:  * [values-anp/strings.xml] placeholder missing in source, key: preference_autocomplete_topsite_summary

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#4135]
We have an error that is preventing importing new strings

```
Error:  * [values-anp/strings.xml] placeholder missing in source, key: preference_autocomplete_topsite_summary
```

**Comment by Delphine** [comment]
Looking at the existing translation, I don't see a placeholder missing here, so not sure what's wrong: https://pontoon.mozilla.org/anp/focus-for-android/app.po/?search=preference_autocomplete_topsite_summary&string=192176

I still updated string and removed the extra "%1$s" in it, so maybe that was the issue and will fix it?

**Comment by boek** [comment]
Fixed! Thanks @Delphine!
