### ISSUE TITLE
Logged out of facebook when trying to play a video

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4141]
## Steps to reproduce
1. Log in to Facebook.com
2. Tap to play a video from the news feed.
### Expected behavior
Video plays.
### Actual behavior
On both devices, on geckoView: User is logged out, asked to "log in first". After logging back in, the video is already in fullscreen and can be played.
[Recording](https://drive.google.com/file/d/13jwnvXVjXoFgL_q11C5tE9EsDNEZMXnU/view?usp=sharing)
*On P9 Lite, with webView: Can't login at all.  Getting the "You must log in first" error.

**On Pixel, with webView: no issue, user logged in, video plays.
### Device information

* Android device: Huawei P9 Lite (Android 6.0), Google Pixel (Android 9)
* Focus version: 8.0.6 geckoView & webView.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the 8.16.0 Focus build with Samsung Galaxy Note 8 (Android 9).
