### ISSUE TITLE
SwitchLocaleTest.java#EnglishSystemLocaleTest is failing

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/focus-android#4145]
Test fails because it's looking for a static message in French on the home page but instead finds one of many messages.  For some reason, only some of the messages are localized and not others.

## Steps to reproduce
Run automated test: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/androidTest/java/org/mozilla/focus/activity/SwitchLocaleTest.java#L168

### Expected behavior

tests expects to find....
"Navigation privée automatique.
Naviguez. Effacez. Recommencez."

### Actual behavior

instead it finds one of:

[1]
"Site behaving unexpected?
Try turning off Tracking Protection"
[2]
"Ouvrir un lient dans un nouvel onglet 
Effectuez un appui long sur un lien dans une page"

[3]
"Open a link in a new tab 
Long-press any link on a page"

[4]
"Un site de confiance?
Allowlist desactive la protection contre le pistage pour les sites que vous connaisaez et auxquel vous faites confiance"

### Device information

* Android device: all
* Focus version: 9.0, build #11

**Comment by levimatheri** [comment]
Seems like the teaser should only show if tip is null as in the `updateSubtitle` of [this class](https://github.com/mozilla-mobile/focus-android/blob/c8c886d8620c27c1a626044f8efe7e635affe6b9/app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt). Maybe we could set the show tips to false in SharedPreferences to disable it for this test?
