### ISSUE TITLE
Inconsistency in strings

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#4152]
Seems like there is an inconsistency between 3 strings, specifically: firstrun_defaultbrowser_text_new, tip_block_ads, and block_ads_card_description
(2 are identical, the last one is "almost")

Should these be "Browse faster by stopping ads and code that [follows] you around the web." or "follow"?

**Comment by lobontiumira** [comment]
I'll close this issue, since it is no longer the case on the 8.16.0 Focus build.
