### ISSUE TITLE
[BUG] 'Try Again' button malfunctions

### ISSUE THREAD

**Issue by 4ut0-M-4t** [mozilla-mobile/focus-android#4158]
## Steps to reproduce

1. Launch Firefox Klar by tapping the app's icon.
2. Enter any valid URL into the address bar while experiencing temporary connection issues.
3. Upon receiving a connection error message, press '**Try Again**' button.
### Expected behavior

Browser should attempt to establish connection to the server.
### Actual behavior

Nothing happens.
### Device information

* Android device: SGN4 Android 6.0.1
* Focus version: Firefox Klar Nightly 8.0.5 (Build #330111231 GV 64.0.20181214004633)
### Additional information

Refreshing the page by pressing '**Reload website**' button in the Options Menu works fine.
This issue seems to exist since vv6.0-6.3 IIRC.

**Comment by 4ut0-M-4t** [comment]
**Device**: SGN4 ARMv7 (Android 6.0.1) 
**Firefox Klar 9.0** (Build #330171230 GV 64.0.20190111134233)

Pressing '**Try Again**' button produces no results.
P.S. I've never experienced such issues with Gecko-based browsers for Android OS (like Fennec).

**Comment by lobontiumira** [comment]
I was not able to reproduce this on the 8.16.0 Focus Klar with Samsung Galaxy Note 8 (Android 9).
