### ISSUE TITLE
Tracking Protection count is inaccurate when switching tabs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4161]
## Steps to reproduce
1. Open a website that has trackers blocked (e.g. huffingtonpost.com; ~20+ trackers)
2. Observe the tracker count.
3. Click on a different link to open in Focus (e.g. reddit.com; ~2 trackers)
2. Observe the tracker count.
4. Using the tab switcher, switch back to the first tab.
5. Observe the tracker count.

### Expected behavior
1. The first tab should show the original +20 trackers that are blocked.

### Actual behavior
1. It shows 0 trackers are being blocked.

### Device information

* Android device: Android 9 (Pixel 2)
* Focus version: 9.0 (Build #330191217 :lizard: 65.0.20190114172331)

**Comment by vesta0** [comment]
I can't reproduce this in 8.0.8.
