### ISSUE TITLE
Build and ship 64-bit (ARM64 and x86_64) Focus builds

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#4164]
We need to publish 64-bit builds to the Google Play Store before Google's August 1 deadline requiring 64-bit support (for apps that include native code).

https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html?m=1

Fennec Nightly started shipping ARM64 builds on 2019-01-15. The Reference Browser already started shipping ARM64 Nightly builds in this issue: mozilla-mobile/reference-browser#367

GeckoView supports ARM64 builds:

https://maven.mozilla.org/?prefix=maven2/org/mozilla/geckoview/geckoview-nightly-arm64-v8a/

_But_ Gecko itself is missing some ARM64 optimizations (SpiderMonkey's Ion JIT) so ARM64 performance might be subpar. I think the current ARM64 GeckoView builds would be adequate for Focus Nightly testers, but we *should not* ship to Focus Beta or Prod tracks until Gecko's Ion JIT supports ARM64: [Firefox bug 1520261](https://bugzilla.mozilla.org/show_bug.cgi?id=1520261) and these blocker bugs listed on this [Mobile ARM64 wiki](https://wiki.mozilla.org/Mobile/ARM64#M3:_ARM64_Ion_Beta). ETA is 2019-05-13 for GeckoView and Fennec 68 Beta.

We will also need to publish x86_64 Focus builds or take down the 32-bit x86 Focus builds (#2122). We have x86_64 builds of GeckoView and Fennec, but they have had very little testing!

https://maven.mozilla.org/?prefix=maven2/org/mozilla/geckoview/geckoview-nightly-x86_64/

**Comment by cpeterso** [comment]
@sarentz - What are the next steps to ship ARM64 and x86_64 builds of Focus? PR #4164 has been closed (though the PR says: "This pull request is closed, but the st3fan/Bug4164BuildAarch64 branch has unmerged commits.").

**Comment by sarentz** [comment]
I think we have a build that is good to ship now - just figuring out the logistics of that.

**Comment by cpeterso** [comment]
I see Focus 8.0.11 APKs for armeabi-v7a and arm64-v8a in the Google Play Console (and none for x86 or x86_64), so I think we can close this bug as fixed! 🎉
