### ISSUE TITLE
testpilot.firefox.com - content doesn't show up

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4165]
## Steps to reproduce

0. Activate GeckoView
1. Go to https://testpilot.firefox.com/

### Expected behavior

Content is displayed.
### Actual behavior

Most of the content is not displayed.

### Device information

* Android device: Pixel 2
* Focus version: 8.0.6

See also 
https://github.com/webcompat/web-bugs/issues/21906

**Comment by sv-ohorvath** [comment]
Duplicate of #2883.
