### ISSUE TITLE
Firefox Klar is outdated in F-Droid

### ISSUE THREAD

**Issue by Yky** [mozilla-mobile/focus-android#4182]
## Steps to reproduce
Download latest Firefox Klar in F-Droid. 
### Expected behavior
Focus / Klar - v8.0.6 is available in F-Droid
### Actual behavior
The latest version that is available is Version 6.1.1 (22) - Added on 2018-08-20

**Comment by armentarius** [comment]
F-Droid's Klar is the only version that I can install, Google Play version is not available in my geographic zone, Firefox Focus is offered instead.

**Comment by 4ut0-M-4t** [comment]
@armentarius, you can always grab Focus/Klar v8.0.6 from [here](https://github.com/mozilla-mobile/focus-android/releases/tag/v8.0.6) or [Mozilla Archive](https://archive.mozilla.org/pub/android/focus/) till F-Droid team is finally [able to build GeckoView](https://gitlab.com/fdroid/fdroiddata/issues/1390).

**Comment by armentarius** [comment]
@4ut0-M-4t, Thank you for your comment, I tried it before but it didn't work, I can't update F-Droid's version from sources other than F-Droid, the image shows a few minutes ago update results,

![captura de pantalla_2019-01-26-10-16-36](https://user-images.githubusercontent.com/19825151/51787882-e33eef00-2155-11e9-98a5-baf6270543b7.png)

**Comment by armentarius** [comment]
@4ut0-M-4t, It worked. Thank you.

**Comment by rugk** [comment]
Should not this issue be raised at F-Droid actually? If something prevents/breaks build there…

**Comment by rugk** [comment]
Oh, actually, they already seem to be aware of it, but nothing has happened: https://github.com/mozilla-mobile/focus-android/issues/1528

I guess you can close this one here as a dupe of https://github.com/mozilla-mobile/focus-android/issues/1528.

**Comment by hman2** [comment]
Version 8.4.0 is now available on F-Droid.

But only as ARM64... Please add ARM or ARMv7, thanks... (using a Fairphone that runs an SD801).

**Comment by J0WI** [comment]
_bump_

**Comment by eighthave** [comment]
Mozilla Klar was removed from F-Droid because it added a proprietary library and no one has found time to make a build that removes that proprietary library.  Here's the reference:
https://hg.mozilla.org/releases/mozilla-release/file/0f814a8ab240bb6df6bbc5a88865f979e03f0f68/mobile/android/geckoview/build.gradle#l214

We're tracking it here:
https://gitlab.com/fdroid/rfp/-/issues/235

**Comment by cpeterso** [comment]
Closing this issue as a duplicate of https://github.com/mozilla-mobile/focus-android/issues/1405.
