### ISSUE TITLE
Unable to run Focus on Emulators

### ISSUE THREAD

**Issue by RotBolt** [mozilla-mobile/focus-android#4184]
Whenever I try to build and run app on emulator, I get this

`[INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]`

INSTALL_FAILED_NO_MATCHING_ABIS is when you are trying to install an app that has native libraries and it doesn't have a native library for your cpu architecture.

Also Focus is an browser application, it doesn't have any hardware related functionality, so it should run on emulator.

**Comment by lobontiumira** [comment]
I was able to run the Focus 8.13.1 (build 1191.0a1-20210624093849) on an emulator.
@RotBolt could you, please, retry?
