### ISSUE TITLE
Incorrect context menu links on Wikipedia's homepage

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4186]
## Steps to reproduce
1. Go to wikipedia.com.
2. Long press a link from the homepage (e.g. the link to go to the English articles, under the search bar) and observe the URL displayed at the top of the context menu.
3. Open the link in a new tab.
### Expected behavior
https://en.wikipedia.org/
### Actual behavior
https://wikipedia.org//en.wikipedia.org/
The same applies to the rest of the homepage links.
### Device information

* Android device: Samsung Galaxy Note 8 (Android 8.0)
* Focus version: Nightly 9.0 GV 65. Not reproducible on webView.

**Comment by Diana-Rus** [comment]
Hi, the issue is not reproducible on Google Pixel 3a (Android 9) with Firefox Focus 8.0.26. 
Please check [screenshot](https://drive.google.com/open?id=1DNKqFhxZywqMODFbmct4gUawvprgHD6k).
