### ISSUE TITLE
Miner site problem

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/focus-android#4194]
Some site use browser and phone to mine crypto currency please add Miner Block .

**Comment by apex39** [comment]
Please, provide an example of a site.

**Comment by jahmadiiiii** [comment]
www.downloadly.ir

**Comment by lobontiumira** [comment]
@minutesinch is this still an issue?
Thanks!

**Comment by lobontiumira** [comment]
I will close this issue since the user is inactive, and no other feedback has been given.
