### ISSUE TITLE
Reported load time when using Webview not accurate in this case (redirects?)

### ISSUE THREAD

**Issue by acreskeyMoz** [mozilla-mobile/focus-android#4195]
It appears that at least redirects are not being calculated into the page load time reported to Telemetry when using the WebView renderer.

## Steps to reproduce
Load https://www.tripadvisor.com from a non-US based IP.
Verify loadtime with a stopwatch.
Compare against and examine the Android logs (look for `LoadTimeObserver`)

### Expected behavior
Reported load time is approximately equal to stopwatch value.

### Actual behavior
It looks like the URL redirects are being processed as separate page loads.

In this example I calculated a difference of 3182ms between the full page load (with redirects) and the reported page load (which was just for the final url, https://www.tripadvisor.com)

`01-24 14:56:45.196  8005  8005 I LoadTimeObserver: zerdatime 36702523 - url changed to https://www.tripadvisor.com/, new page load start
01-24 14:56:45.206  8005  8005 I LoadTimeObserver: zerdatime 36702533 - url changed to https://www.tripadvisor.com, new page load start
01-24 14:56:45.537  8005  8005 I LoadTimeObserver: zerdatime 36702864 - url changed to https://www.tripadvisor.ca/LangRedirect?auto=1&origin=null&pool=C&returnTo=/, new page load start
01-24 14:56:46.968  8005  8005 I LoadTimeObserver: zerdatime 36704295 - url changed to https://www.tripadvisor.ca/, new page load start
01-24 14:56:47.974  8005  8005 I LoadTimeObserver: zerdatime 36705301 - url changed to https://www.tripadvisor.com/, new page load start
01-24 14:56:48.378  8005  8005 I LoadTimeObserver: zerdatime 36705705 - url changed to https://www.tripadvisor.ca/, new page load start
01-24 14:56:52.407  8005  8005 I LoadTimeObserver: Loaded page at Session(991430c7-7a38-45c0-9ce6-57d335511086, https://www.tripadvisor.ca/).url.value
01-24 14:56:52.407  8005  8005 I LoadTimeObserver: zerdatime 36709734 - page load stop
01-24 14:56:52.407  8005  8005 I LoadTimeObserver: 4029 - elapsed load
01-24 14:56:52.407  8005  8005 I LoadTimeObserver: Sent load to histogram`

### Device information
Moto G5
* Android device: 7
* Focus version: 9.0, Build #11

**Comment by lobontiumira** [comment]
I am closing this ticket, since it is no longer relevant on the latest Focus builds with GeckoView.
