### ISSUE TITLE
Polish "Erase" button animation

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#42]

**Comment by pocmo** [comment]
@antlam: I added the following animation:
* Normal speed: https://youtu.be/3iSCizMoMuk
* Slowed down (2 seconds, for review): https://youtu.be/_w9gz2bBkHI

The final animation is composed from three animations:
* Translate/Move: From current position to 100% (200ms)
* Scale: From current size to 50% of it's size (x/y), pivot at the center of the view (200ms)
* Alpha: From 100% to 0% (200ms)

Is there anything you want to change/polish?

**Comment by pocmo** [comment]
Landed polished version 545ae78a0502c72a1745ea2e2987f500aab8d354.

**Comment by antlam** [comment]
@pocmo I think the snackbar is still coming in too quick. I.e. we should be able to see the snackbar starting to fade in immediately after the screen is erased, but not before.

Also, can we add a 50-100ms delay just before the screen slides down? just after it's done scaling and before it begins translating.

**Comment by pocmo** [comment]
Okay, I have a patch (in review) with the following changes:

Total animation: 250ms
* scale animation: 0..100ms
* translate: 150..250ms (-> 50ms after scale)
* alpha: 0..250ms
* snackbar delay: 250ms
