### ISSUE TITLE
Intent to start search from third-party app

### ISSUE THREAD

**Issue by nyancrimew** [mozilla-mobile/focus-android#4200]
### Why/User Benefit/User Problem

As the Lead Developer of [Lawnchair Launcher](https://lawnchair.app) I'm trying to add as many possible search providers to our app as users request them. A lot of people would like to use their browser built in search to search the web.

### What / Requirements

Focus should provide an intent for third party apps to start search (similar to the erase & open shortcut, but without erasing?)

### Acceptance Criteria (how do I know when I’m done?)

- [ ] Exported third party intent to launch search exists
- [ ] Preferrably implemented using the [Intent.ACTION_SEARCH](https://developer.android.com/reference/android/content/Intent.html#ACTION_SEARCH) action 
- [ ] Intent works with and without provided query
- [ ] Keyboard is focused on starting of the intent

**Comment by baarkerlounger** [comment]
Is this currently possible on the regular Firefox Mobile for android? Or is that the same codebase/also not implemented?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802022

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
