### ISSUE TITLE
Klar crash when webview not present

### ISSUE THREAD

**Issue by sefernet** [mozilla-mobile/focus-android#4207]
## Steps to reproduce
Remove native Android Webview
Install Klar apk (from github/releases)

### Expected behavior
Run normally

### Actual behavior
Crash on launch

### Device information
Rooted
Native Webview removed

* Android device: Moto G3
* Focus version: Klar v8.0.8

----
I understood that with the addition of geckoview, then there will be no need for native android Webview , right?

Thanks  !

**Comment by lobontiumira** [comment]
I did not encounter the crash on the latest Klar 8.16.0 build.
Closing this issue.
