### ISSUE TITLE
Firefox Focus is draining my battery

### ISSUE THREAD

**Issue by rahulthewall** [mozilla-mobile/focus-android#4208]
See the [battery drain](https://i.imgur.com/wp15FQq.png) yesterday. The battery went from 100% to 13% in a little under 7 hours. That's not normal. 

The top applications as reported by Android: https://imgur.com/a/l60iPw3

The detailed report for firefox focus: https://imgur.com/a/mUlnCAW

I don't recall using the browser for over an hour. I think the browser continues to use battery even when the screen is locked. 

Can someone tell me how I can fix this? Or provide more information that may help in debugging? 

### Device information

* Android device: Sony Xperia XZs | Android 8.0.0 (Security patch level: 1 February 2019)
* Focus version: 8.0.8 (Build #330452036 65.0.20190125143011)

**Comment by vesta0** [comment]
@bbinto let me know if you'd like me to look into this.

**Comment by bbinto** [comment]
I'd think it would make sense, please let Stuart and No-Jun know about this. I know they've been setting up a battery testing platform and it'd be good to get Focus + GV tested based on this complain.

**Comment by ikanakova** [comment]
Same here - Extreme battery drain. Battery report by Android: ![Screenshot.jpeg](http://ikanakova.xf.cz/files/Screenshot.jpeg)
* Android device: Nokia 6.1 (Android 10)
* Focus version: 8.3.0 (Build #341281936 🦎 76.0-20200429185419)
