### ISSUE TITLE
Rapid tapping floating button crashes Focus

### ISSUE THREAD

**Issue by zznidar** [mozilla-mobile/focus-android#4213]
## Steps to reproduce
1. Open at least two tabs.
2. Rapidly keep tapping the _Erase browsing history_ floating button.

### Expected behavior
Tabs should be closed (history erased) without a crash.

### Actual behavior
Firefox Focus crashes after closing tabs.

### Device information

* Android device: pocophone f1, Android 8.1.0, and Samsung Galaxy S8+, Android 8.0
* Focus version: 8.0.8 (Build #330452036) and 8.0.8 (Build #330452036 :lizard: 65.0.20190125143011)

**Comment by SubhrajyotiSen** [comment]
I am picking this up

**Comment by lobontiumira** [comment]
I did not reproduce this issue on the 8.16.0 Focus build using a Google Pixel (Android 10).
