### ISSUE TITLE
Lack of GV65 crash reports -- possible incorrect version reported?

### ISSUE THREAD

**Issue by droeh** [mozilla-mobile/focus-android#4214]
Opening an issue for this based on Slack conversation -- we're not seeing any crash reports for GV 65 despite 8.0.8 using it; we're still seeing significant crash reports for GV 64. It's possible that we're misreporting the GV version number, or (worse) that we're not reporting GV 65 crashes at all. It's not clear yet if this is a Focus problem or a GV CrashReporter problem.

**Comment by lobontiumira** [comment]
I will close this issue, since it is no longer up to date.
