### ISSUE TITLE
Disable auto-upload apk to Nimbledroid 

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/focus-android#4215]
### Why/User Benefit/User Problem
We don't need automatic APK uploads to Nimbledroid anymore for the Focus Android project.
### What / Requirements
Comment out the lines of code in Taskcluster that trigger the upload
### Acceptance Criteria (how do I know when I’m done?)
Taskcluster trigger won't result in auto-upload apk to Nimbledroid

**Comment by AaronMT** [comment]
At this point we just want to remove it: #4652
