### ISSUE TITLE
Add to home screen : ask to use the favicon or not 

### ISSUE THREAD

**Issue by g-normand** [mozilla-mobile/focus-android#4218]
### Why/User Benefit/User Problem

Hello Firefox Focus team !
I'm a great fan of your app and I would like to know if it is possible to add a small feature : 
When adding to home screen, the favicon is not used. 
I read the issue about that : https://github.com/mozilla-mobile/focus-android/issues/2992

I understand that  some people does not want the favicon for privacy purpose.

As tobz1000 said (https://github.com/mozilla-mobile/focus-android/issues/2992#issuecomment-423742811) : Having the option to choose between character and favicon would be best.

### What / Requirements
So I would like to ask if it is possible to ask the user if he prefers the favicon or the "letter icon".

For example, I use Focus for privacy, but I like to have my bookmarks. And the "letter icon" is not really helpful. :)

Thanks for reading
Guillaume.

**Comment by lobontiumira** [comment]
@g-normand thank you for the report!
The Focus favicon is used when adding a page to the homescreen on the 8.17.0 Focus build.
