### ISSUE TITLE
App Shortcuts of Firefox Focus is wrongly named

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#4219]
[Note: This issue was originally reported [on bugzilla here](https://bugzilla.mozilla.org/show_bug.cgi?id=1530922) (and wrongly attributed at first to Focus iOS) for Korean locale, but this seems to affect other locales as well, such as Traditional Chinese]

**Steps to reproduce:**

Long tapping the Firefox Focus icon on home screen (launcher)
The App Shortcut's name is not correct (contains technical characters)

**Actual results:**

It shows up as "**%1$s** 지우고 열기".

(This also happens to Traditional Chinese translation, but not sure if European languages have this issue because the words are too long and have been shrunk.)

**Expected results:**

지우고 열기 but without the placeholder

The string in question [is this one](https://github.com/mozilla-mobile/focus-android/blob/29a48d4f6f368d283fda1cb81e62e5dbd9b491c7/app/src/main/res/values-zh-rTW/strings.xml#L29).

![img_20190227_145719_379](https://user-images.githubusercontent.com/399020/53532301-3a184b00-3aab-11e9-9603-3234db617e68.jpg)
![img_20190227_145715_671](https://user-images.githubusercontent.com/399020/53532302-3a184b00-3aab-11e9-9aca-d0270a693d44.jpg)
![screenshot_20190227-131247](https://user-images.githubusercontent.com/399020/53532303-3ab0e180-3aab-11e9-9216-dde113ed5bac.jpg)

(@boek Not sure who to ping about this, feel free to assign accordingly :) )

**Comment by aqeelparpia** [comment]
Hi there, I would like to work on this issue? hope to fix this problem as soon as possible. As per my undersatnding the words are shrinking on translation and not presenting the appropriate name of the shortcut file right?

**Comment by Delphine** [comment]
I think the main issue called out here is that some languages display a placeholder in the string (in this case %1$s), although there is [none in the source](https://github.com/mozilla-mobile/focus-android/blob/29a48d4f6f368d283fda1cb81e62e5dbd9b491c7/app/src/main/res/values-zh-rTW/strings.xml#L29) . 
What's more, this issue is hard to see if it reproduces in other languages, because some of those strings (like in English, for example) are truncated.

**Comment by mpas97** [comment]
Hi @Delphine and @aqeelparpia 
I just wanted to point out that I use this Firefox app for many years now and as far as I can remember, I always saw this %1$s placeholder there. And I'm even using English as system language. So not a Korean / Chinese problem only.
![IMAGE 2020-01-10 11:46:27](https://user-images.githubusercontent.com/9994218/72147454-d6370200-339e-11ea-84f6-637de83b30d2.jpg)

**Comment by mpas97** [comment]
And what I directly found with two clicks:
- we use shortcut_erase_and_open_long_label as shortcut label: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/focusRelease/res/xml-v25/shortcuts.xml#L24
- the %1$s is there, at least for the en lang: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/res/values-en-rCA/strings.xml#L33

**Comment by mpas97** [comment]
And a quick search give me the result of 74 affected files (the %1 is also often separated from the $s, eg in the first two matches): 
<img width="600" alt="grafik" src="https://user-images.githubusercontent.com/9994218/72149390-55c6d000-33a3-11ea-870b-35abecab0ccb.png">

**Comment by mpas97** [comment]
Most probably the error occurs when the launcher displays the android:shortcutLongLabel (that is probably defined faulty in each lang) instead of the short one.
<img width="867" alt="grafik" src="https://user-images.githubusercontent.com/9994218/72149803-3d0aea00-33a4-11ea-9e72-4b7dea7b9dde.png">

**Comment by mpas97** [comment]
My proposal would be to just remove the android:shortcutLongLabel incl. all "unused" translations. Because there will never be some text after "Erase & open".

Apart of the unused %1$s in the long string, I think there is also the difference of "Erase & open" to "Erase and open" (& changed to "and") because of the 10 chars limit of shortLabel. So we could also leave the longLabel for a written out symbol but then we have to update all translations.

**Comment by mpas97** [comment]
@colintheshots Can you please have a look on this issue?

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the 8.16.0 build using a Google Pixel (Android 10) build.
