### ISSUE TITLE
Upgrade Focus to GeckoView 67 Beta

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#4222]
GV 67 beta will be available on on March 18.

This build will also require some engineering work to **remove survey homescreen tip**.

- [ ] GV team update Focus 8.0 to GV 67 Beta
- [ ] Fenix team review/approve pull request and create a new build
- [ ] Release notes (Vesta)
- [ ] Release management promotes the build to 99% of release channel. Fretboard at 50/50.
- [ ] Check whether there are new crashes (Vesta)
- [ ] After 4 days release management sets the roll out to 100%
- [ ] Roll out GeckoView to 90%
- [ ] Tag the last and released RC version additionally with the tag of the release (v1.0-RC2 -> v1.0)
- [ ] Upload signed APKs to the release page
- [ ] Upload the APK to http://archive.mozilla.org/pub/android/focus/ (S3 bucket) into a folder named like a release (e.g. /android/focus/2.2). Builds from the "latest" folder are linked from the mozilla.org website.

CC @cpeterso @st3fan

**Comment by cpeterso** [comment]
GV reminder to update Focus to GV 67 Beta after it rides to the Beta channel on March 18: [bug 1531858](https://bugzilla.mozilla.org/show_bug.cgi?id=1531858). New GV Beta builds are produced once a week. We'll probably want to update Focus's GV 67 Beta snapshot weekly.

GV reminder to update Focus to GV 67 Release after it is released on May 14: [bug 1531862](https://bugzilla.mozilla.org/show_bug.cgi?id=1531862)

**Comment by vesta0** [comment]
Focus now runs on GV 68.
