### ISSUE TITLE
server load reduction most email, QR integration browser/email client for mobile copy and paste reduction

### ISSUE THREAD

**Issue by c4pt000** [mozilla-mobile/focus-android#4224]
server load reduction most email, QR integration browser/email client for mobile copy and paste reduction

https://i.redd.it/ym0vwrtt5mk21.png

https://imgur.com/gallery/jm62rSe

**Comment by lobontiumira** [comment]
@c4pt000 is this still an issue on the latest Firefox Focus build?

**Comment by lobontiumira** [comment]
Closing as obsolete.
