### ISSUE TITLE
Upgrade Focus to GeckoView 68 Beta

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#4225]
GV 68 Beta will be available on May 14.

This build will also require engineering work to add a new homescreen tip.

- [ ] GV team update Focus 8.0 to GV 68 Beta
- [ ] Fenix team review/approve pull request and create a new build
- [ ] Release notes (Vesta)
- [ ] Release management promotes the build to 99% of release channel.
- [ ] Check whether there are new crashes (Vesta)
- [ ] After 4 days release management sets the roll out to 100%
- [ ] Tag the last and released RC version additionally with the tag of the release (v1.0-RC2 -> v1.0)
- [ ] Upload signed APKs to the release page
- [ ] Upload the APK to http://archive.mozilla.org/pub/android/focus/ (S3 bucket) into a folder named like a release (e.g. /android/focus/2.2). Builds from the "latest" folder are linked from the mozilla.org website.

CC @cpeterso @st3fan

**Comment by iadeelzafar** [comment]
Hello @vesta0 I'm getting this error when trying to run this app on the emulator. I'm a new contributor to this project. Any help from the contributors of this project will be really appreciated. I apologize for posting this comment here as this is irrelevant to the issue created.
![image](https://user-images.githubusercontent.com/36811908/54048221-f637eb00-41fa-11e9-839d-5f4d8b0ebecf.png)
**I have tried uninstalling and also completely wiped the emulator's data but still I keep getting this error.**

**Comment by cpeterso** [comment]
@iadeelzafar Your error message suggests you are trying to run an ARM build of Focus in an x86 emulator (or vice versa). I recommend asking your question in the #mobile channel on Mozilla's IRC server: https://wiki.mozilla.org/IRC

**Comment by lobontiumira** [comment]
I think this ticket can be closed, as it is complete.
