### ISSUE TITLE
www.pornhub.com - Blank page displayed when opening link in a new tab on Firefox Focus with Geckoview

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4227]
Description: New tab in Firefox focus not working
Steps to Reproduce:
Opening videos in new tab resulted in about:blank tabs.

on Firefox Focus with Geckoview. 
![image](https://user-images.githubusercontent.com/12184325/53636452-f8151380-3c28-11e9-8028-3554798fd1bb.png)

Note: Not reproducible on Firefox Focus 8.0.8 (Build #330452036)

**Tested with:**
Browser / Version: Firefox Focus 8.0.8 (Build #330452036 🦎 65.0.20190125143011)
Operating System: LG G5 (Android 7.0) - 1440 x 2560 pixels (~554 ppi pixel density), Samsung Galaxy S7 Edge (Android 8.0.0) - Resolution 1440 x 2560 pixels (~534 ppi pixel density)

Spin off of https://github.com/webcompat/web-bugs/issues/26485

**Comment by karlcow** [comment]
Something similar seems to be happening with relative links. Open in new tabs fails to associate the domain name.

**Comment by lobontiumira** [comment]
Not reproducible on the latest Focus 8.16.0 build using a Google Pixel (Android 10).
