### ISSUE TITLE
Hard crash on launch

### ISSUE THREAD

**Issue by anto-1** [mozilla-mobile/focus-android#4229]
## Steps to reproduce
Build focus-android-master from source with build variant FocusAarch64Debug
### Expected behavior
run
### Actual behavior
crash
### Device information
Oreo 8.0.0 Security patch Frebruary 1, 2019
* Android device: Samsung Galaxy S7 Edge hero2lte
* Focus version: latest

It works on the same phone and on an emulator running Nougat.

But I get this error from the LogCat when trying to launch the app from an Oreo physical phone.

` I/WebViewFactory: Loading com.google.android.webview version 70.0.3538.110 (code 353811000)
 E/linker: normalize_path - invalid input: "null", the input path should be absolute
 W/linker: Warning: unable to normalize "null"
 A/zygote64: java_vm_ext.cc:504] JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received NULL jstring
 A/zygote64: java_vm_ext.cc:504]     in call to GetStringUTFChars
 A/zygote64: java_vm_ext.cc:504]     from int android.webkit.WebViewFactory.nativeLoadWithRelroFile(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.ClassLoader)
 A/zygote64: java_vm_ext.cc:504] "main" prio=5 tid=1 Runnable
 A/zygote64: java_vm_ext.cc:504]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x736dab58 self=0x745fcc0a00
 A/zygote64: java_vm_ext.cc:504]   | sysTid=15802 nice=-10 cgrp=default sched=0/0 handle=0x7464f279c8
 A/zygote64: java_vm_ext.cc:504]   | state=R schedstat=( 1095976405 1921691 277 ) utm=96 stm=13 core=5 HZ=100
 A/zygote64: java_vm_ext.cc:504]   | stack=0x7ff7ca9000-0x7ff7cab000 stackSize=8MB
 A/zygote64: java_vm_ext.cc:504]   | held mutexes= "mutator lock"(shared held)
 A/zygote64: java_vm_ext.cc:504]   native: #00 pc 0000000000397614  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+212)
 A/zygote64: java_vm_ext.cc:504]   native: #01 pc 000000000045dde8  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+348)
 A/zygote64: java_vm_ext.cc:504]   native: #02 pc 00000000002d59e0  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1040)
 A/zygote64: java_vm_ext.cc:504]   native: #03 pc 00000000002d5e60  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+116)
 A/zygote64: java_vm_ext.cc:504]   native: #04 pc 0000000000108ab0  /system/lib64/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+148)
 A/zygote64: java_vm_ext.cc:504]   native: #05 pc 00000000001080e8  /system/lib64/libart.so (_ZN3art11ScopedCheck13CheckInstanceERNS_18ScopedObjectAccessENS0_12InstanceKindEP8_jobjectb+832)
 A/zygote64: java_vm_ext.cc:504]   native: #06 pc 0000000000106a78  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+856)
 A/zygote64: java_vm_ext.cc:504]   native: #07 pc 000000000010fc9c  /system/lib64/libart.so (_ZN3art8CheckJNI22GetStringCharsInternalEPKcP7_JNIEnvP8_jstringPhbb+656)
 A/zygote64: java_vm_ext.cc:504]   native: #08 pc 000000000000100c  /system/lib64/libwebviewchromium_loader.so (???)
 A/zygote64: java_vm_ext.cc:504]   native: #09 pc 0000000000f7abec  /system/framework/arm64/boot-framework.oat (Java_android_webkit_WebViewFactory_nativeLoadWithRelroFile__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_ClassLoader_2+284)
 A/zygote64: java_vm_ext.cc:504]   at android.webkit.WebViewFactory.nativeLoadWithRelroFile(Native method)
 A/zygote64: java_vm_ext.cc:504]   at android.webkit.WebViewFactory.loadNativeLibrary(WebViewFactory.java:705)
 A/zygote64: java_vm_ext.cc:504]   at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:412)
 A/zygote64: java_vm_ext.cc:504]   at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:211)
 A/zygote64: java_vm_ext.cc:504]   - locked <0x04b53ec9> (a java.lang.Object)
 A/zygote64: java_vm_ext.cc:504]   at android.webkit.CookieManager.getInstance(CookieManager.java:39)
 A/zygote64: java_vm_ext.cc:504]   at org.mozilla.focus.web.ClassicWebViewProvider.performNewBrowserSessionCleanup(ClassicWebViewProvider.java:54)
 A/zygote64: java_vm_ext.cc:504]   at org.mozilla.focus.web.WebViewProvider.performNewBrowserSessionCleanup(WebViewProvider.kt:47)
 A/zygote64: java_vm_ext.cc:504]   at org.mozilla.focus.activity.MainActivity.registerSessionObserver(MainActivity.kt:128)
 A/zygote64: java_vm_ext.cc:504]   at org.mozilla.focus.activity.MainActivity.onCreate(MainActivity.kt:78)
 A/zygote64: java_vm_ext.cc:504]   at android.app.Activity.performCreate(Activity.java:7183)
 A/zygote64: java_vm_ext.cc:504]   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
 A/zygote64: java_vm_ext.cc:504]   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
 A/zygote64: java_vm_ext.cc:504]   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
 A/zygote64: java_vm_ext.cc:504]   at android.app.ActivityThread.-wrap11(ActivityThread.java:-1)
 A/zygote64: java_vm_ext.cc:504]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
 A/zygote64: java_vm_ext.cc:504]   at android.os.Handler.dispatchMessage(Handler.java:105)
 A/zygote64: java_vm_ext.cc:504]   at android.os.Looper.loop(Looper.java:164)
 A/zygote64: java_vm_ext.cc:504]   at android.app.ActivityThread.main(ActivityThread.java:6944)
 A/zygote64: java_vm_ext.cc:504]   at java.lang.reflect.Method.invoke(Native method)
 A/zygote64: java_vm_ext.cc:504]   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
 A/zygote64: java_vm_ext.cc:504]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
 A/zygote64: java_vm_ext.cc:504] 
 A/zygote64: runtime.cc:508] Runtime aborting...
 A/zygote64: runtime.cc:508] 
 A/zygote64: runtime.cc:516] JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received NULL jstring
 A/zygote64: runtime.cc:516]     in call to GetStringUTFChars
 A/zygote64: runtime.cc:516]     from int android.webkit.WebViewFactory.nativeLoadWithRelroFile(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.ClassLoader)
 A/zygote64: runtime.cc:516] "main" prio=5 tid=1 Runnable
 A/zygote64: runtime.cc:516]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x736dab58 self=0x745fcc0a00
 A/zygote64: runtime.cc:516]   | sysTid=15802 nice=-10 cgrp=default sched=0/0 handle=0x7464f279c8
 A/zygote64: runtime.cc:516]   | state=R schedstat=( 1095976405 1921691 277 ) utm=96 stm=13 core=5 HZ=100
 A/zygote64: runtime.cc:516]   | stack=0x7ff7ca9000-0x7ff7cab000 stackSize=8MB
 A/zygote64: runtime.cc:516]   | held mutexes= "mutator lock"(shared held)
 A/zygote64: runtime.cc:516]   native: #00 pc 0000000000397614  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+212)
 A/zygote64: runtime.cc:516]   native: #01 pc 000000000045dde8  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+348)
 A/zygote64: runtime.cc:516]   native: #02 pc 00000000002d59e0  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1040)
 A/zygote64: runtime.cc:516]   native: #03 pc 00000000002d5e60  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+116)
 A/zygote64: runtime.cc:516]   native: #04 pc 0000000000108ab0  /system/lib64/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+148)
 A/zygote64: runtime.cc:516]   native: #05 pc 00000000001080e8  /system/lib64/libart.so (_ZN3art11ScopedCheck13CheckInstanceERNS_18ScopedObjectAccessENS0_12InstanceKindEP8_jobjectb+832)
 A/zygote64: runtime.cc:516]   native: #06 pc 0000000000106a78  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+856)
 A/zygote64: runtime.cc:516]   native: #07 pc 000000000010fc9c  /system/lib64/libart.so (_ZN3art8CheckJNI22GetStringCharsInternalEPKcP7_JNIEnvP8_jstringPhbb+656)
 A/zygote64: runtime.cc:516]   native: #08 pc 000000000000100c  /system/lib64/libwebviewchromium_loader.so (???)
 A/zygote64: runtime.cc:516]   native: #09 pc 0000000000f7abec  /system/framework/arm64/boot-framework.oat (Java_android_webkit_WebViewFactory_nativeLoadWithRelroFile__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_ClassLoader_2+284)
 A/zygote64: runtime.cc:516]   at android.webkit.WebViewFactory.nativeLoadWithRelroFile(Native method)
 A/zygote64: runtime.cc:516]   at android.webkit.WebViewFactory.loadNativeLibrary(WebViewFactory.java:705)
 A/zygote64: runtime.cc:516]   at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:412)
 A/zygote64: runtime.cc:516]   at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:211)
 A/zygote64: runtime.cc:516]   - locked <0x04b53ec9> (a java.lang.Object)
 A/zygote64: runtime.cc:516]   at android.webkit.CookieManager.getInstance(CookieManager.java:39)
 A/zygote64: runtime.cc:516]   at org.mozilla.focus.web.ClassicWebViewProvider.performNewBrowserSessionCleanup(ClassicWebViewProvider.java:54)
 A/zygote64: runtime.cc:516]   at org.mozilla.focus.web.WebViewProvider.performNewBrowserSessionCleanup(WebViewProvider.kt:47)
 A/zygote64: runtime.cc:516]   at org.mozilla.focus.activity.MainActivity.registerSessionObserver(MainActivity.kt:128)
 A/zygote64: runtime.cc:516]   at org.mozilla.focus.activity.MainActivity.onCreate(MainActivity.kt:78)
 A/zygote64: runtime.cc:516]   at android.app.Activity.performCreate(Activity.java:7183)
 A/zygote64: runtime.cc:516]   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
 A/zygote64: runtime.cc:516]   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
 A/zygote64: runtime.cc:516]   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
 A/zygote64: runtime.cc:516]   at android.app.ActivityThread.-wrap11(ActivityThread.java:-1)
 A/zygote64: runtime.cc:516]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
 A/zygote64: runtime.cc:516]   at android.os.Handler.dispatchMessage(Handler.java:105)
 A/zygote64: runtime.cc:516]   at android.os.Looper.loop(Looper.java:164)
 A/zygote64: runtime.cc:516]   at android.app.ActivityThread.main(ActivityThread.java:6944)
 A/zygote64: runtime.cc:516]   at java.lang.reflect.Method.invoke(Native method)
 A/zygote64: runtime.cc:516]   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
 A/zygote64: runtime.cc:516]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
 A/zygote64: runtime.cc:516] 
)`

**Comment by lobontiumira** [comment]
@anto-1 is this still an issue?
Thank you!

**Comment by lobontiumira** [comment]
I will close this issue since the user did not provide any other feedback.
Feel free to open a new issue if this behavior re-occurs.
