### ISSUE TITLE
Latest build on archive.mozilla.org points to older one

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/focus-android#4236]
The alias at `https://archive.mozilla.org/pub/android/focus/` points to an older build. Let's remove the `latest` folder or update it if it is not too much work.

**Comment by Ryuno-Ki** [comment]
Thanks, @st3fan,
I originally filled https://bugzilla.mozilla.org/show_bug.cgi?id=1539978 but was told to open it here instead.

**Comment by Krawei** [comment]
Hello everyone,

 there a status update availabe regarding this issue?

Kind regards,
Krawei

**Comment by lobontiumira** [comment]
Is this ticket still relevant?
Thank you!

**Comment by J0WI** [comment]
Yes, the 'latest' release published on `archive.mozilla.org` is 8.0.26 from 2020.
