### ISSUE TITLE
Unable to download pdf files

### ISSUE THREAD

**Issue by andreasglueck** [mozilla-mobile/focus-android#4237]
## Steps to reproduce
A button is clicked to get a pdf file. The file download dialog doesn't pop up.
The pdf is created on a server and it's sent to the browser. In the browsers Firefox, Chrome, Internet Explorer it works correctly.

### Expected behavior
The file download dialog must appear.

### Actual behavior
I have found, that the dialog is opened by GET-Reguests not by POST-Requests.

### Device information
Any Mobile Devices

* Android device: yes
* Focus version: firefox klar 8.0.8

The log data from the server:
Request:
 host = ...;
 cache-control = max-age=0;
 origin = ...;
 upgrade-insecure-requests = 1;
 content-type = application/x-www-form-urlencoded;
 user-agent = Mozilla/5.0 (Linux; Android 6.0.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/8.0.8 Chrome/72.0.3626.105 Mobile Safari/537.36;
 accept = text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8;
 referer = ...;
 accept-encoding = gzip, deflate;
 accept-language = de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7;
 cookie = JSESSIONID=...; ...; tempcache=476892;
 x-requested-with = org.mozilla.klar;
 via = 1.1 ...;
 x-forwarded-for = ...;
 x-forwarded-host = ...;
 x-forwarded-server = ...;
 connection = Keep-Alive;
 content-length = 275 || 
Response:
 Content-Disposition = attachment; filename="download.pdf"

**Comment by test2a** [comment]
eh. i am on android 7 and the latest focus but download has NEVER worked for me. Never. clicking on download, does nothing. then half an hour later get a notification that download failed. Instead i copy the link to firefox and download from there. Much better although that one has a massive bug on that one too but yeah

**Comment by test2a** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1296895

see.... the bug is only three years old now.

**Comment by sijanr** [comment]
I used to face the problem in Firefox Focus, but haven't had the issue for a while now. Have you tried Firefox Focus global yet?

**Comment by andreasglueck** [comment]
I tried with firefox klar 8.0..0 and 8.0.8. I thought it's the same engine. I can test with firefox focus. Should I take the version 9.0.0?

**Comment by andreasglueck** [comment]
In the play store i see only the app firefox klar.

**Comment by sijanr** [comment]
https://github.com/mozilla-mobile/focus-android/releases
Use the above link and try installing the 'Focus' apk for your device.

**Comment by 4ut0-M-4t** [comment]
> Should I take the version 9.0.0?

Klar Nightly 9.0 downloads PDF files just fine. Give it a try.

**Comment by andreasglueck** [comment]
Failed:
Firefox Focus 9.0.0, Android Klar 8.00 and 8.0.8
Passed:
Firefox, Firefox Nightly

**Comment by lobontiumira** [comment]
This is no longer an issue.
Tested on the 8.16.0 Focus build, and on 8.16.0 Klar build with Google Pixel (Android 10).
