### ISSUE TITLE
Cleaning out memory space after erasing

### ISSUE THREAD

**Issue by smcode123** [mozilla-mobile/focus-android#4241]
Hi,
Steps to reproduce:
1. Visit any website.
2. Erase.
3. Take RAM dump

The html contents and other images are still present in the memory (RAM) dump of the App taken via LiME [1]. The memory dump can be inspected to identify the website visited.

I am not sure if this should be filed under a bug or a feature request. Is it possible to blank out the occupied memory pages while erasing the on disk browser cache?
Please correct if I am wrong.

1. https://github.com/504ensicsLabs/LiME

**Comment by Poopooracoocoo** [comment]
this is defs a bug

**Comment by Poopooracoocoo** [comment]
#4421

**Comment by lobontiumira** [comment]
@smcode123 is this still an issue?
Thank you!

**Comment by iorgamgabriel** [comment]
https://github.com/mozilla-mobile/focus-android/issues/4421 is closed . I think this one should be closed
