### ISSUE TITLE
how can I change the search engines and the default search engine?

### ISSUE THREAD

**Issue by Bianconiglio** [mozilla-mobile/focus-android#4242]
hi,
I can't find how I can modify the search engine list and the default search engine. can someone help me or explain how?

**Comment by mblaster75** [comment]
I'm interested in how to add a search engine or change the default via source code and not as a normal user.

**Comment by gahujipo** [comment]
Click the three dots, Settings, Search, Search Engine. There you can select your search engine or add another one.

**Comment by mblaster75** [comment]
Hello in last release of onion browser in Google market there is a onion search engine you can select and put like default

Regards,

Onion Search Engine

http://www.onionsearchengine.com

-------- Messaggio originale --------
On 17 apr 2019, 11:15, gahujipo ha scritto:

**Comment by lobontiumira** [comment]
I think I can close this issue, since the reporter found a way to change the default engine.
