### ISSUE TITLE
Click "Copy Link" please indicate to user that the link was successfully copied - in the UI

### ISSUE THREAD

**Issue by naeohmi** [mozilla-mobile/focus-android#4244]
### Why/User Benefit/User Problem
Using the Firefox Focus browser on my modern android device - I open a new page, then click the top right 3 dots icon, and the drop down menu is displayed. I click "Copy link" menu item to copy the current link.

As a user, I expect the UI to indicate in some way that the link was successfully copied, by displaying a popover message, flash message, or any kind of visual cue - to confirm successful link copy. Currently nothing is displayed and I am left unsure as to whether the link copy was successful or not.

### Acceptance Criteria (how do I know when I’m done?)
This feature request will be complete when the UI indicates in some way that a link was successfully copied, by displaying a popover message, flash message, or any kind of visual cue - to confirm success.

Relates to: https://bugzilla.mozilla.org/show_bug.cgi?id=1543488

**Comment by lobontiumira** [comment]
The 91.1.0 focus build indicates the user that a link was copied:
![copy link](https://user-images.githubusercontent.com/40694158/128470392-f395ef88-f41c-4d86-8943-7432d3443573.jpg)

Tested with Google Pixel (Android 10).
