### ISSUE TITLE
can't find the id "recycler_view"

### ISSUE THREAD

**Issue by Hatem1235** [mozilla-mobile/focus-android#4245]
## Steps to reproduce
how to fix it ? should I replace it with something else ?
### Expected behavior
build and run
### Actual behavior
no build
### Device information

* Android device: 6.0.1
* Focus version: latest

**Comment by lobontiumira** [comment]
@Hatem1235 is this still an issue for you on the latest 8.17.0 Focus build?
Thank you!

**Comment by lobontiumira** [comment]
Closing this ticket as obsolete.
