### ISSUE TITLE
Refactor code in MainActivity.kt

### ISSUE THREAD

**Issue by iadeelzafar** [mozilla-mobile/focus-android#4246]
## Steps to reproduce
1. Go to ```MainActivity.kt```
2. There is code in ```onCreate``` and ```onPause()``` that can be added in a separate function.

### Expected behavior
This code should be added in separate functions.

### Actual behavior
A few lines of code is present in ```onCreate()``` and ```onPause()``` that is not that very much readable.

**Comment by iadeelzafar** [comment]
Working on this.

**Comment by unicorn-io** [comment]
can I contribute to this?

**Comment by iadeelzafar** [comment]
Hi @unicorn-io I actually created a PR specifically to this refactoring. If you feel there's any other place where code refactoring is required, go for it.

**Comment by unicorn-io** [comment]
Thank you for the response
