### ISSUE TITLE
URL auto complete list modifies URL wrong (lower/upper case)

### ISSUE THREAD

**Issue by gahujipo** [mozilla-mobile/focus-android#4248]
## Steps to reproduce
Click the three dots, Settings, Search, URL Autocomplete, Manage sites, + Add custom URL. In the appearing textfield, enter an URL with a capital letter after the /, e.g. www.website.com/Forum/index.php. Click Save. 

### Expected behavior

The entered URL should be 
```
www.website.com/Forum/index.php
```
### Actual behavior

The url becomes: 

<span>www.website.com/**f**orum/index.php</span>

The "f" in Forum became lower case. There is actual no way to enter the URL correctly with an upper case "F".

### Device information

* Android device: Xiaomi Mi 6 Miui Global 10.2 (Android 8.0.0 OPR1.170623.027)
* Focus version: 8.0.8 (Build #330452036)

**Comment by lobontiumira** [comment]
This is no longer reproducible on 8.16.0 Focus build, using a Google Pixel (Android 10).

**Comment by gahujipo** [comment]
But it is still reproducible on 8.16.0 Focus build, using Miui Global 11 (Android 9)

**Comment by gahujipo** [comment]
Still reproducible in v102.2.0

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 106.0a1 from 8/29 with Samsung Galaxy Note 8 (Android 9):

![4248](https://user-images.githubusercontent.com/40694158/187215075-ffc8139a-800f-496c-a6b7-f18f79338da7.png)

**Comment by lobontiumira** [comment]
Verified as implemented also on Beta 106.0b1.
