### ISSUE TITLE
 www.honorbuy.it - "Secure connection failed" displayed when accessing the site

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4250]
## Steps to reproduce
1. Go to  https://www.honorbuy.it/

### Expected behavior
site is readable.

### Actual behavior
SSL error.
Note: Not reproducible on Firefox Nightly and Chrome.

### Device information

Tested with:
Browser / Version: Firefox Focus 8.0.8 (Build #330452036 🦎 65.0.20190125143011), Fenix 1.0.1.1915 (Build #11051220 🦎 68.0a1-20190408104625)
Operating System: LG G5 (Android 8.0.0) - 1440 x 2560 pixels (~554 ppi pixel density), Samsung Galaxy S7 Edge (Android 8.0.0) - Resolution 1440 x 2560 pixels (~534 ppi pixel density)

Originally reported on https://github.com/webcompat/web-bugs/issues/29306

**Comment by lobontiumira** [comment]
This is no longer reproducible on 8.16.0 build, using a Google Pixel (Android 10).
