### ISSUE TITLE
Page reloads when connecting/disconnecting charger

### ISSUE THREAD

**Issue by hackel** [mozilla-mobile/focus-android#4251]
## Steps to reproduce
1. Open a page.
2. Connect or disconnect charger.

### Expected behavior
Nothing happens, page state and scroll position is retained.

### Actual behavior
Page reloads and scrolls to the top losing scroll position, any saved state, wasting bandwidth, etc.

### Device information

* Android device: Pixel 1
* Focus version: 8.0.8 (Build #330452036)

This issue is not new.  It has been a problem for quite a long time, I just haven't gotten around to reporting it until now.  The same behaviour occurs when the Night Light feature engages, which is likely a separate issue but thought it was worth mentioning.

Also, I appear to still be on Chrome WebView.  I observe this same reload behaviour on another WebView-based browser (Bromite), however it remembers the scroll position.  I do not observe it in Chrome itself.

**Comment by lobontiumira** [comment]
This is no longer reproducible on the 8.16.0 Focus build using a Google Pixel (Android 10).
