### ISSUE TITLE
Firefox focus : Can't add an attachment in gmail

### ISSUE THREAD

**Issue by Nemmoo** [mozilla-mobile/focus-android#4253]
### Device information
I have just bought a Nokia 1 and I have installed Firefox focus (8.0.8 version). Gmail is my webmail, but I prefer to use a browser rather than the Gmail app. I have even desactivated the Google apps exept for Google Play services.

### Actual behavior
I wanted to send an email with an attachment thanks to Firefox focus, but nothing happened when I touched the attachment logo. But, I can send an email without attachment or with a drawing as an attachment. Nothing changes when I reactivate the Google apps.

### Expected behavior
I have tried to send an email with an attachment with another browser (Firefox, Cliqz) : there is no problem. When I touch the attachment logo, a window pops to ask me if I allow the browser to access my files or photos. I click on yes and then, I can choose the document I want to send.
I have checked in Nokia's settings the autorisations of those apps, but Firefox focus like the others browsers can access my smartphone storage.

**Comment by karlcow** [comment]
We got a very similar issue with yandex. 
https://github.com/webcompat/web-bugs/issues/35953

So let's pre-emptively link these two.

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the 8.16.0 Focus build using a Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
Still reproducible on RC 92.1.1 build with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
This is no longer reproducible on the latest RC 96.1.0 build, and on the latest Focus Nightly from 1/6, with Oppo Find X3 Lite (Android 11), and Sony Xperia Z5 Premium (Android 7.1.1).
