### ISSUE TITLE
Open link in new tab opens blank tabs (about:blank)

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/focus-android#4254]
## Steps to reproduce
1. Go to Wikipedia/Bilibili.com/Imdb.com/amazon.com;
2. Long tap a link and select "open in new tab" ;
3. Switch to the new tab. 

### Expected behavior
The webpage loads.

### Actual behavior
about:blank page opened in all new tabs opened with "open link in new tab". Doesn't reproduce with links sent from other apps.

### Device information

* Android device: Samsung Note9 (Android 8.1.0);
* Focus version: Focus 8.0.9 with GeckoView 68

Notes: Successfully opened links in new tabs using Microsoft.com/yahoo.com

**Comment by cpeterso** [comment]
Can you reproduce this bug in Focus 8.0.9 using WebView (using WebView/GeckoView setting in `focus:test`)?

**Comment by cpeterso** [comment]
I can't reproduce this problem in Fenix, so this is a Focus-specific bug. No further investigation is needed at this time.

**Comment by lobontiumira** [comment]
No longer reproducible on the 8.16.0 Focus build with GV89, using a Google Pixel (Android 10).
