### ISSUE TITLE
The handler jumps out of the view when you move it a little up or down

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/focus-android#4255]
## Steps to reproduce
1. Go to any page with text(en.m.wikipedia.org/wiki/Main_Page);
2. Zoom in;
3. Double tap on a word;
4. Move a handler a little up or down;
 
### Expected behavior
The Handler move where you go with the finger.

### Actual behavior
The Handler jumps out of the view and selects everything behind the first selected word.

### Device information
* Android device: OnePlus 5T (Android 9);
* Focus version: Focus 8.0.9 with GeckoView 68

Notes: 
- The issue is not reproducible if you move the handler left or right.
- Doesn't work for the first page;
- [video](https://drive.google.com/file/d/0B-OVCGyglYi_SU1kaHhkZ3BwMlB4TUlGd3h0RmRaS24yRE1z/view?usp=sharing)

**Comment by levimatheri** [comment]
If you want to select the word and then the words **below** it, then you use the right pointer of the handler and move down with your finger. For words **above**, use the left pointer and move up with your finger. From the video you posted it seems you did the opposite.

**Comment by sv-sdeiac** [comment]
This information doesn't change the actual results. Both pointers should work as normal from any direction you move them. This is a known issue on Fennec and it was fixed(bug [1540545](https://bugzilla.mozilla.org/show_bug.cgi?id=1540545 )).

**Comment by cpeterso** [comment]
Thanks for testing, @sv-sdeiac! The fix for bug 1540545 won't be available in a new Focus build (probably a future 8.0.10) for a couple weeks.

**Comment by lobontiumira** [comment]
No longer reproducible on the 8.16.0 Focus build with GV89, using a Google Pixel (Android 10).
