### ISSUE TITLE
Floating action bar isn't dismissed after pasting a word

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/focus-android#4256]
## Steps to reproduce
1. Copy any word 
2. Paste the word in the google.com search bar

### Expected behavior
Action bar should be dismissed

### Actual behavior
Action bar isn't dismissed 

### Device information

* Android device: Samsung Note9 (Android 8.1.0), OnePlus 5T(Android 9);
* Focus version: Focus 8.0.9 with GeckoView 68;

Notes:
- Action bar is dismissed when pasting a word in the Bing search bar with a minor glitch
- Photo: 
![picturemessage_ihmcshte bub](https://user-images.githubusercontent.com/40264165/56667318-4c32f600-66b6-11e9-9e95-0b3a671eb03e.png)

**Comment by cpeterso** [comment]
I can reproduce this bug in Focus 8.0.8 with GeckoView 65 and Fenix (GeckoView 68). I'll file a new GeckoView bug:
