### ISSUE TITLE
Autocomplete does not work in recent update

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#4259]
## Steps to reproduce
-Open Focus and make sure Autocomplete is enabled in settings
-Start typing in the URL bar

### Expected behavior
-See URL autocomplete suggestions for top sites.

### Actual behavior
-Autocomplete seems to be broken

### Device information
* Android device: Pixel 3 (also affecting a variety of devices such as Galaxy S9, Huawei, etc based on user reviews)
* Focus version: 8.0.9

**Comment by pm-pm** [comment]
A VERY soon coming service release would be great, so we can use this key feature again.

**Comment by sv-ohorvath** [comment]
New issues found: 
https://github.com/mozilla-mobile/focus-android/issues/4273
https://github.com/mozilla-mobile/focus-android/issues/4272
https://github.com/mozilla-mobile/focus-android/issues/4271
https://github.com/mozilla-mobile/focus-android/issues/4274

**Comment by lobontiumira** [comment]
This issue no longer reproduces on 8.16.0 Focus build using a Google Pixel (Android 10) device. I'll close it.
