### ISSUE TITLE
Input with <datalist> elements don't autocomplete

### ISSUE THREAD

**Issue by briankung** [mozilla-mobile/focus-android#4266]
## Steps to reproduce

1. Using Firefox Focus, visit https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist#Examples (the example section of the `<datalist>` element's MDN page)
1. Try to enter some of the datalist options (i.e. "Chrome" or "internet explorer")

### Expected behavior

The input should show available matching options in the datalist. Other mobile browsers (Firefox, Chrome) display this as something looking like a dropdown.

### Actual behavior

No options are shown

### Device information

* Android device: Moto G5 Plus
* Android version: 8.1.0
* Focus version: 8.0.8 (Build #330452036 :lizard: 65.0.20190125143011)

**Comment by lobontiumira** [comment]
This is still reproducible on both Focus 8.16.0, and Firefox Nightly 91.0a1 from 7/5 using a Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
This issue still reproduces on the latest Focus Nightly build 99.0a1 from 2/25, with Oppo Find X3 Lite (Android 11).

**Comment by ionutbedregeanu** [comment]
This is also reproducible in GeckoView Example app

https://user-images.githubusercontent.com/11731652/183349168-0aeb6650-25dc-46e2-a873-2c7b584b439c.mp4

**Comment by ionutbedregeanu** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1783594

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
