### ISSUE TITLE
Version 9.0 reset settings after starting browser

### ISSUE THREAD

**Issue by runboy93** [mozilla-mobile/focus-android#4267]
## Steps to reproduce

Change settings as you like, I'm not really sure what cause this, happens very randomly.

After you restarted browser x-xx times, after using it for while, browser show welcome intro again like after installation.

### Expected behavior

Settings should be kept, and not reset after while.

### Actual behavior

Settings are not kept, and settings get reset after while.

### Device information

* Android device: OnePlus 3T, Android 9.0
* Focus version: 9.0

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on 8.16.0 Focus. 
@runboy93 did you encounter this lately?
Thank you!

**Comment by lobontiumira** [comment]
I'll close this ticket as obsolete.
