### ISSUE TITLE
Crash adding an unknown protocol to Home Screen

### ISSUE THREAD

**Issue by zznidar** [mozilla-mobile/focus-android#4269]
Trying to add a site with an unknown protocol to Home Screen results in a crash. Only happens when using WebView (i. e. not with GeckoView).

## Steps to reproduce
1. Visit `test://test` (or similar)
2. Tap ⁝ -> Add to Home Screen

### Expected behavior
Firefox Focus should not crash. 

### Actual behavior
Firefox Focus crashes.

### Device information

* Android device: pocophone f1, Android 8.1, and Samsung Galaxy S8+, Android 9
* Focus version: 8.0.8 (Build #330452036)

User agent: 
Mozilla/5.0 (Linux; Android 8.1.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/8.0.8 Chrome/74.0.3729.136 Mobile Safari/537.36

**Comment by shubhamkumar1739** [comment]
I have noticed that the app crashes even on adding a valid URL to home screen

**Comment by shubhamkumar1739** [comment]
Can I work on fixing this issue?

**Comment by lobontiumira** [comment]
I was able to reproduce the crash on the 8.16.0 build using Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
I was not able to trigger the crash anymore on the Focus Nightly 97.0 (build 360101001 GV 97.0a1-20220108220226), nor on RC 96.1.1, with Samsung Galaxy Note 8 (Android 9), nor on Oppo Find X3 Lite (Android 11).
