### ISSUE TITLE
Search suggestions only pick up the first word

### ISSUE THREAD

**Issue by kef71** [mozilla-mobile/focus-android#4271]
## Steps to reproduce

type in 'bank italy' in the url bar

### Expected behavior

Showing 'bank italy' in the suggestions

### Actual behavior

Not showing 'bank italy' in the suggestions. In fact as soon as a space is used you get no more suggestions. Tested with google and duckduckgo.

### Device information

* Android device: Oneplus 3t (Android 7.1.2)
* Focus version: 8.0.9 (Geckoview)

**Comment by sv-ohorvath** [comment]
Still reproducing on 8.0.10.

**Comment by kef71** [comment]
Sill reproducing on 8.0.11.

**Comment by Diana-Rus** [comment]
Hi, this issue does not reproduce anymore, verified as fixed with Samsung Galaxy S9 (Android 8) with Focus 8.1.1 (Build #340941926) GV:74.0.1-20200403064753.
