### ISSUE TITLE
Search suggestions and search edit mode can't be dismissed

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4273]
## Steps to reproduce
1. On the homescreen, start typing in the search bar.
2. Tap the clear "x" button. Tap the back button.
### Expected behavior
Clears the typed text and closes the search bar edit mode.
### Actual behavior
Clears text but the search mode is still on, the search suggestions are still displayed.
Pressing back minimizes the app. Can't exit this mode unless you kill the app.
### Device information

* Android device: HTC 10 (Android 8.0), Note 8 (Android 9), Pixel (Android Q)
* Focus version: Beta 8.0.10 (GV 68)

**Comment by arjav2002** [comment]
This issue should be closed

**Comment by Diana-Rus** [comment]
Hi, issues does not reproduce with Samsung Galaxy S9 (Android 8) on Focus 8.1.1 (Build #340941926) GV: 74.0.1.
