### ISSUE TITLE
Custom URL autocomplete doesn't work as long Top sites suggestions is on

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4274]
## Steps to reproduce
1. Add a custom URL.
2. Make sure Top sites suggestions is On.
3. Type the custom url in the search bar.
4. Turn off top site suggestions. Type in the url again.
### Expected behavior
Custom URLs are autocompleted in both cases.
### Actual behavior
Custom URLs autocomplete doesn't work if top sites are on.
### Device information

* Android device: HTC 10 (Android 8.0)
* Focus version: Beta 8.0.10 (GV 68)

**Comment by test2a** [comment]
Yes. I updated to latest version and saved addresses are not showing

**Comment by sv-ohorvath** [comment]
@test2a This is fixed on the latest Beta/Release 8.0.13. Check for updates and try again, please.
