### ISSUE TITLE
[A11y] Skip button from first run has incorrect description

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4276]
## Steps to reproduce
1. With TalkBack on, open a freshly installed Focus app.
2.On the first slide of the tour, listen the Skip button's description
### Expected behavior
Skip button has a correct description.
### Actual behavior
The search bar description is read.
### Device information

* Android device: HTC 10 (Android 8)
* Focus version: 8.0.11

**Comment by lobontiumira** [comment]
On the RC 96.1.1, the Talkback announces the "Skip" button, then announces the first card, even if only the "Skip" button is selected.
Teste with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the latest Beta 100.0.0-beta.3 build, nor on RC 99.2.0 build.
Tested with Oppo Find X3 Lite (Android 11), Lenovo Tab M10 (Android 10), and Samsung Galaxy Note 8 (Android 9).
