### ISSUE TITLE
Firefox Focus recognised as outdated Chrome

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla-mobile/focus-android#4282]
I originally reported this to GitHub where I first noticed it.

They told me, that the User Agent is wrong.
On CodePen you get more idea on what it looks like to them:
![Screenshot_20190518-120824](https://user-images.githubusercontent.com/3097194/58200730-be0d5800-7cd3-11e9-9ae3-aed491d2690a.png)

URL: https://codepen.io/jcoulterdesign/full/xeoRZW (yes, a 404).

Firefox Focus 8.0.8 (Build #330452036).
Downloaded from https://archive.mozilla.org/pub/android/focus/

User Agent Mozilla/5.0 (Android 6.0.1; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0

**Comment by lobontiumira** [comment]
Loading URL: https://codepen.io/jcoulterdesign/full/xeoRZW only opens a 404 page.
Closing as invalid.
