### ISSUE TITLE
Request to add this feature: DNS DOT / DOH

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/focus-android#4283]
### Why/User Benefit/User Problem
These two features are strongly requested.

### What / Requirements
DNS DOT / DOH.

### Acceptance Criteria (how do I know when I’m done?)
version 9.0

thanks!

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802023

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
