### ISSUE TITLE
Fix AndroidX migration fallout to reenable URL autocomplete tests

### ISSUE THREAD

**Issue by droeh** [mozilla-mobile/focus-android#4285]
In #4284 I had to disable a few URL autocomplete tests due to breakage in UI automation from the AndroidX migration; things appear to be alright in manual testing, but it would be good to get the tests up and running again as soon as we can.

* Android device: All
* Focus version: 8.0.12

**Comment by ionutbedregeanu** [comment]
This ticket was addressed meanwhile
