### ISSUE TITLE
[Not a bug] Replace deprecated `SearchEngineManager.load()` with `loadAsync()`.

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/focus-android#4286]
`SearchEngineManager.load()` is [deprecated now](https://github.com/mozilla-mobile/android-components/blob/77d384c/components/browser/search/src/main/java/mozilla/components/browser/search/SearchEngineManager.kt#L58). `SearchEngineManager.loadAsync()` should be used instead.

Occurrences:
  - [SearchEngineListPreference](https://github.com/mozilla-mobile/focus-android/blob/b21ee8c3d83a971f3510788ffbc33894bfabf8ed/app/src/main/java/org/mozilla/focus/search/SearchEngineListPreference.kt#L67).
  - [FocusApplication](https://github.com/mozilla-mobile/focus-android/blob/9827c021f0f0bacc3e1c68d007f6e15fac1e8467/app/src/main/java/org/mozilla/focus/FocusApplication.kt#L69).

**Comment by Patil2099** [comment]
@dector  Can I work on this? I just have to replace SearchEngineManager.load() with SearchEngineManager.loadAsync() throughout the program ?

**Comment by dector** [comment]
@Patil2099 Yes, this is just a renaming. :)

**Comment by lobontiumira** [comment]
@dector is this issue fixed?
Thank you!

**Comment by dector** [comment]
@lobontiumira Don't think that it's fixed. But I can't find `SearchEngineManager` usages in this repo anymore.

**Comment by ionutbedregeanu** [comment]
SearchEngineManager is not used anymore, so I will close this ticket
