### ISSUE TITLE
APK file

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/focus-android#4288]
## Steps to reproduce
Only source code.

### Expected behavior
I hope you can upload all the apk files, thank you.

### Actual behavior
https://github.com/mozilla-mobile/focus-android/releases

### Device information
* Android device: 8.0
* Focus version: 8.0.7-8.0.12

**Comment by runboy93** [comment]
Play store latest version is from april 25th.

Github releases page latest version is 8.0.8.

Latest version is now 8.0.13, but I cannot manage to find Armv8 build for it :(

**Comment by lobontiumira** [comment]
This is fixed now.
I'll close the issue.
