### ISSUE TITLE
Unblocking trackers doesn't work

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4290]
Steps to reproduce:
1. Go to Settings > Privacy & Security
2. In "Tracking Protection" disable "Block ad trackers", exit settings and open test web page:
https://mozilla.github.io/tracking-test/ads.html or https://mozilla.github.io/tracking-test/disconnect.html

Expected behavior
Verify page shows a black cat and a message with analytics not blocked.

Actual behavior
Unblocking trackers doesn't work.

Device information
Android device: OnePlus 5T (Android 9); Motorola Nexus 6 (Android 7.1.1)
Focus version: 8.0.12 GeckoView 68.0

Notes:
This is reproducible for analytic trackers and social trackers.
This is also reproducible on panopticlick.org
Switching the "Trackers blocked" off from the Menu works as expected.

**Comment by vesta0** [comment]
@npark-mozilla @rpappalax  I believe in the past you had flagged that maybe those sites are not good ones to test with, am I remembering that right?

**Comment by sv-ohorvath** [comment]
Note that "This is also reproducible on panopticlick.org" - it shows that ads trackers are blocked.
On these test pages, I was able to get the expected results on a first try, then it didn't work after I restarted my browser. For Eliza it didn't work at all.

**Comment by ebalazs-sv** [comment]
Hi! This is verified as fixed on Focus 8.0.13 GeckoView 68.0 with Nexus 6P (Android 8.1.0).
Thanks!
