### ISSUE TITLE
Erase history does not

### ISSUE THREAD

**Issue by test2a** [mozilla-mobile/focus-android#4292]
https://ibb.co/DKqrrmL

Just saw this bug.

I am on ff 8.06 android 7 lenovo z2 plus. No customisation..

The phone has a front button for app switching and this bug is keeping the first page opened on app start when I close the page and switch apps. Even if I open another page and close that, it reverts to the first page.

**Comment by goforbg** [comment]
Hello, is this bug still present? Unable to reproduce with my Pocofone f1.

**Comment by test2a** [comment]
nah. i am unable to replicate it with the current app version. It probably was fixed sometime inbetwen

**Comment by lobontiumira** [comment]
Closing as per the comment above.
