### ISSUE TITLE
Update FAB button

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#43]
Currently, we went with a + icon from the Android lib., we should update that

Also we should match functionality here with
- Forward, 
- refresh/stop 
- share

**Comment by antlam** [comment]
Talked about this more on Vidyo. 

We're exploring making this the Erase button instead to feel more Android-y. Meanwhile, the menu buttons would fit in a typical Android Overflow button.

**Comment by pocmo** [comment]
@antlam The latest builds have an "erase" FAB button. I'm using the 'delete forever' icon from the material icons: https://material.io/icons/#ic_delete_forever
Let me know if we want to use a different icon and I'll create a follow-up patch.

**Comment by antlam** [comment]
I think we should use the 'delete' one instead... 

I feel like it's more common place and gets the idea across without creating as many questions

<img width="385" alt="screen shot 2017-02-16 at 2 25 56 pm" src="https://cloud.githubusercontent.com/assets/1994820/23044155/e06dbe2c-f453-11e6-98aa-b48706749d77.png">

Thoughts
