### ISSUE TITLE
my-free-mp3s.com audio does not play

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#4303]
## Steps to reproduce

1. Load https://my-free-mp3s.com/mp3juice
2. Search for some string.
3. Click a song's ▶️ play button.

### Expected behavior

Audio should play in Focus, like it does in Chrome, Fennec, Fenix, and Reference Browser.

### Actual behavior

Audio does not play in Focus.

### Device information

* Android device: 7.0 and 8.1.0
* Focus version: 8.0.15

**Comment by cpeterso** [comment]
This bug was originally reported in https://github.com/webcompat/web-bugs/issues/33646.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Focus Nightly from 1/10, nor on RC 96.1.1 build, using a HTC 10 (Android 8.1), and a Sony Xperia Z5 Premium (Android 7.1.1).
