### ISSUE TITLE
Can't easily open links in Fenix

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/focus-android#4305]
https://www.reddit.com/r/firefox/comments/c8b1ty/firefox_preview_not_showing_up_in_firefox_focus/

**Comment by snorp** [comment]
@ekager says we should just add Fenix here: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/utils/Browsers.java#L25

**Comment by vesta0** [comment]
@colintheshots can we close this? I believe you fixed this before the last release.

**Comment by lobontiumira** [comment]
I will close this issue, since I am not able to reproduce it on the later builds.
Tested on RC 96.1.1, and Focus Nightly 97.0 from 1/10 with Lenovo Tab M10 (Android 10), Sony Xperia Z5 Premium (Android 7.1.1).
