### ISSUE TITLE
Some tables are cropped on websites

### ISSUE THREAD

**Issue by Maccer1** [mozilla-mobile/focus-android#4307]
## Steps to reproduce
If you open this [link](https://web.archive.org/web/20150520021436/http://www.thermoanalytics.com/support/publications/batterytypesdoc.html) the battery types table will appear cropped on Firefox Focus. Both on desktop mode and mobile mode.
It will appear cropped on portrait and landscape mode as well. 

The problem also exists on Firefox Nightly.
### Expected behavior
You should be able to swipe to see the full table but it just doesn't let me.

### Actual behavior
The table appears cropped and I can't read it.

### Device information
Samsung J530F

* Android device: Android 8.1.0
* Focus version: 8.0.15

**Comment by lobontiumira** [comment]
No longer reproducible on the latest RC 96.1.1 build with HTC 10 (Android 8.1.0), nor on Lenovo Tab M10 (Android 10).
