### ISSUE TITLE
Support Browser.EXTRA_HEADERS parameters

### ISSUE THREAD

**Issue by BugsBunnyBR** [mozilla-mobile/focus-android#4311]
### Why/User Benefit/User Problem
- Developers can use standard Android parameters to open the browser and deliver a better experience when Firefox is the default browser app keeping users session while in the native app and in the browser.
### What / Requirements
- When opening the app, there is a need to check for the headers in the intent and forward it together with the url.

### Acceptance Criteria (how do I know when I’m done?)

When there is no other browser app installed/enabled in the phone and a request to `https://www.cylog.org/headers/` shows the custom headers.

**Comment by lobontiumira** [comment]
@BugsBunnyBR is this ticket still relevant?
Thank you!

**Comment by BugsBunnyBR** [comment]
If not implement yet, it still is relevant as this would allow Firefox to be behave as expected by the OS and Android developers that trust that the default browser will handle that properly.
