### ISSUE TITLE
Better bookmark/autocomplete management

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/focus-android#4314]
### Why/User Benefit/User Problem
bookmarks/autocomplete could be a long term storage for the ephemeral browser so you don't have to open it in another browser
### What / Requirements
Searching
Folders
Viewing titles
Opening in a new tab
Rename autocomplete to books
Select multiple
## Acceptance Criteria (how do I know when I’m done?)
when the above is completed.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802024

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
