### ISSUE TITLE
keep tabs when Focus goes out of memory

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/focus-android#4315]
### Why/User Benefit/User Problem
someone might open a resource intensive app or many apps and then go to firefox focus to discover that their browsing has been wiped
### What / Requirements
Don't wipe browsing when Focus is out of memory
### Acceptance Criteria (how do I know when I’m done?)
When the above is implemented

**Comment by Poopooracoocoo** [comment]
And this is so important because it should be **up to the user** if tabs and tab navigation history is deleted. 

This has happened too many times to me and I'm considering just uninstalling Focus.

**Comment by Poopooracoocoo** [comment]
@colintheshots sorry to bother you. just out of curiosity, is focus on the project so minimal because of work on Fenix?

**Comment by lobontiumira** [comment]
Hi @Poopooracoocoo 
Have you encountered this issue lately?
Thank you!

**Comment by Poopooracoocoo** [comment]
@lobontiumira Yes, Focus still deletes browsing history when it gets out of memory. But this is a feature request which is separate from the bug. I would appreciate it if both this were implemented and the bug were fixed.

**Comment by Poopooracoocoo** [comment]
omg its so easy to accidentally close

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802025

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
