### ISSUE TITLE
Enable use of about:config

### ISSUE THREAD

**Issue by Bunnicula2** [mozilla-mobile/focus-android#4317]
### Why/User Benefit/User Problem
There are many settings that can be tweaked on about:config in order to improve user privacy, sometimes at the sacrifice of security. For example, I think it would be unrealistic to expect an option to turn off Safe Browsing in the Privacy & Security menu, but I'd nevertheless love to be able to turn it off.

### What / Requirements / Acceptance Criteria (how do I know when I’m done?)
Expose an about:config page similar to those on other Firefox/Gecko Android releases. I think it will be less of an effort now that we've kicked WebView.

**Comment by 4ut0-M-4t** [comment]
@Bunnicula2, you'd better use Prefs.js.

**Comment by Bunnicula2** [comment]
How do I edit prefs.js on Android? Is this possible without root and adb? If not, that doesn't solve my problem unfortunately.
