### ISSUE TITLE
www.trenitalia.com - search results are redirected to the previous page entered.

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4318]
## Steps to reproduce

1. Go to https://mozilla.org/
2. Enter https://www.lefrecce.it/msite/?lang=it#search?noOfAdults=1&ynFlexibleDates=off&arrivalStation=Roma%20(%20Tutte%20Le%20Stazioni%20)&selectedTrainClassification=&tripType=on&selectedTrainType=tutti&departureStation=Venezia%20S.%20Lucia&departureTime=07&departureDate=29-07-2019&noOfChildren=0

### Expected behavior

Get the search results.

### Actual behavior

We are in the end redirected to https://mozilla.org/

### Device information

* Android device: Pixel 2
* Focus version: version 8

**Comment by karlcow** [comment]
Previously reported on https://github.com/webcompat/web-bugs/issues/36301

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly build from 2/25 using an Oppo Find X3 Lite (Android 11) device.
