### ISSUE TITLE
Disable Google SafeBrowsing

### ISSUE THREAD

**Issue by Bunnicula2** [mozilla-mobile/focus-android#4320]
Using Firefox Klar 8.0.15 from F-Droid on Android 7.1. Apologies if there's a newer version where this can be mitigated by the user.

### Why/User Benefit/User Problem
Google SafeBrowsing makes browsing more secure from malware. Though, Firefox Focus is a privacy-focused browser. Therefore if there's a tradeoff between privacy and security, users should be allowed to choose the side of privacy.

I haven't investigated how Firefox Focus gets safe browsing data from Google, but according to [this link](https://superuser.com/questions/832608/what-is-being-send-to-received-from-safebrowsing-google-com-when-i-open-firefo) browsers request the data immediately on opening and thereafter periodically.

Letting Google know whenever I open my web browser is a substantial privacy leak for a rather small security gain.

### What / Requirements
Offer a switch in the settings to disable SafeBrowsing, or just disable it altogether. Or just implement about:config

**Comment by cadeyrn** [comment]
@Bunnicula2 The toggle to disable SafeBrowsing was implemented in Firefox Focus / Klar 91.
