### ISSUE TITLE
Upgrade Focus to GeckoView 69 Beta 

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#4322]
Fenix Nightly updated from GV 68 Beta to GV 69 Beta. We should also update Focus because it has more users than Fenix, atm.

I will ask Dylan if he is still responsible for updating GV in Focus.

I copied this task checklist from Focus's GV 68 Beta issue #4225:

- [ ] GV team update Focus 8.0 to GV 69 Beta
- [ ] Fenix team review/approve pull request and create a new build
- [ ] Release notes (Vesta)
- [ ] Release management promotes the build to 99% of release channel.
- [ ] Check whether there are new crashes (Vesta)
- [ ] After 4 days release management sets the roll out to 100%
- [ ] Tag the last and released RC version additionally with the tag of the release (v1.0-RC2 -> v1.0)
- [ ] Upload signed APKs to the release page
- [ ] Upload the APK to http://archive.mozilla.org/pub/android/focus/ (S3 bucket) into a folder named like a release (e.g. /android/focus/2.2). Builds from the "latest" folder are linked from the mozilla.org website.

CC @vesta0

**Comment by vesta0** [comment]
I think we should do this as soon as possible but I've been told that Dylan is no longer working on this. @cpeterso would you be able to find out who can help us with this?

**Comment by cpeterso** [comment]
I am told that @colintheshots is now responsible for updating Focus's GV versions and that Dylan is available to help with any GV integration issues.

**Comment by vesta0** [comment]
Done
