### ISSUE TITLE
viewport is moving when interacting with the screen.

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4326]
Initially reported on https://github.com/webcompat/web-bugs/issues/36736

1. Go to https://wizardsuniteworld.com/spell-caster/
2. Try to draw a shape

Expected:
draw the shape leaving a blue trail without the screen moving.

Actual:
The screen is moving.

This is not happening in Firefox Fennec and in Firefox Fenix (Preview)

**Comment by amanbora** [comment]
I would like to contribute to this issue, I'm new to android so any other specification about the problem would be highly beneficial. Thanks!

**Comment by lobontiumira** [comment]
The link from step 1 is no longer available.
I'll close this ticket as obsolete.
