### ISSUE TITLE
Create a tip in Focus for launch in private mode

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#4329]
@sblatz commented on [Thu Aug 08 2019](https://github.com/mozilla-mobile/fenix/issues/4623)

We should utilize [homescreen tips](https://github.com/mozilla-mobile/focus-android/wiki/Homescreen-Tips) to create a tip in Focus that will tell users about our private mode in Fenix. 

We just need copy for what this string should say.

@mheubusch to provide that?

---

@sblatz commented on [Thu Aug 08 2019](https://github.com/mozilla-mobile/fenix/issues/4623#issuecomment-519640150)

Related to https://github.com/mozilla-mobile/fenix/issues/419

---

@sblatz commented on [Thu Aug 08 2019](https://github.com/mozilla-mobile/fenix/issues/4623#issuecomment-519640304)

@vesta0 to determine the priority of this messaging :)

---

@AmyYLee commented on [Thu Aug 08 2019](https://github.com/mozilla-mobile/fenix/issues/4623#issuecomment-519641842)

@mheubusch We will need copy for this "tip"

**Comment by mheubusch** [comment]
Proposed copy: Stay focused. The new Firefox Preview is a full-fledged mobile browser you can customize for always-on private browsing.

**Comment by vesta0** [comment]
@colintheshots can we pull this into the next release please?

**Comment by lobontiumira** [comment]
I will close this ticket as obsolete.
