### ISSUE TITLE
System-wide accessibility settings for font size not honored

### ISSUE THREAD

**Issue by emacksnotes** [mozilla-mobile/focus-android#4332]
## Steps to reproduce

`Settings` -> `Accessibility` -> `Font Size` -> {Set it to `Largest` possible setting}

### Expected behavior

Firefox Focus _used to_  honor that setting.  The font size _used to be_ larger and I could read the webpages without any strain.  Lately--i.e., in the last 3 months or so--the release builds failed honoring my phone-wide settings.  As a user who 40+ and wears reading glasses, this makes reading very difficult for me. 

### Workaround (?)

[/u/rob849 had a suggestion for me on /r/firefox, and it worked wonderfully for me](https://old.reddit.com/r/firefox/comments/crnuq4/40_user_here_any_way_i_can_get_firefox_focus_on/ex90gkk/?context=3)

> You've been opted into GeckoView, which replaces the System WebView provider. Unlike Firefox Preview, Focus (when using GeckoView) has neither the option for automatic font sizing, nor the ability to set a custom font size (so it just defaults to 100%). However you can **_opt-out of GeckoView by typing `focus:test` in the address bar and toggling it off._** This will revert to using the System WebView provider, which follows your system-wide preference as you had previously.

> Hopefully someone at Mozilla is reading this and will do something to avoid GeckoView testing affecting users with accessibility preferences. Or otherwise quickly implement automatic font sizing. Definitely a lapse in foresight on someone's part here.

### Device information

* Android device: Nokia 1, Android v9, Patched to Jul 5, 2019 levels
* Focus version:  8.0.15 (Build #331622103)

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly build 99.0a1 from 2/25 using an Oppo Find X3 Lite (Android 11) device.
