### ISSUE TITLE
Navigating to Settings=>Mozilla=>About Firefox Focus returns a blank page

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#4335]
## Steps to reproduce
-Open Focus on GeckoView
-Go to Settings=>Mozilla=>About Firefox Focus

### Expected behavior
-See the about page

### Actual behavior
-Returns a blank page

**This is a [GV bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1556540) but we can address it with a workaround **

**Comment by cadeyrn** [comment]
Duplicate of #4299.

**Comment by vesta0** [comment]
This is also fixed. @colintheshots can we close this?

**Comment by colintheshots** [comment]
Yes, this was fixed. Closing.
