### ISSUE TITLE
focus-android-8.0.16.zip and "Trojan.Script.Generic1"

### ISSUE THREAD

**Issue by runboy93** [mozilla-mobile/focus-android#4339]
Results for focus-android-8.0.16.zip, it doesn't show exactly where it was found, and only one detection engine found it:

https://www.virustotal.com/gui/file/220e5db9f3a57d9ddc1bf8f503e1be01b7ffbfda4b86477054b4978bc80a0788/detection

Earlier focus-android-8.0.15.zip for example doesn't have this as seen on this report, same detection engine "Jiangmin" shows nothing:

https://www.virustotal.com/gui/file/f0515de16b8888ae537d3fb01f38603b912625eb3e2551891715f5301fdce283/detection

**Comment by lobontiumira** [comment]
I'll close this ticket as obsolete.
