### ISSUE TITLE
"REMOVE ALL WEBSITES" button from Exceptions section flickers 

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4340]
## Steps to reproduce
1. Switch off the TP toggle for one or more websites;
2. Go to Settings -> Privacy & Security -> Exceptions; 
3. Tap the 3 dots button in the top-right corner. Select "Remove"
### Expected behavior
"Remove" option is displayed. After selecting it, the list of websites shows checkboxes for each item.
### Actual behavior
"REMOVE ALL WEBSITES" button flickers.

### Notes
[Video](https://drive.google.com/file/d/12EJxyfsc-XyHUYR0R8dSM40ZzfzDbG0G/view)
### Device information

* Android device: Samsung Galaxy S8 (Android 9)
* Focus version: Beta 8.0.16 (GV 69)

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Focus Nightly build from 2/22 with Oppo Find X3 Lite (Android 11), or Samsung Galaxy Note 8 (Android 9).
