### ISSUE TITLE
Default option from Block cookies pop-up is not selected

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4341]
## Steps to reproduce
1. Go to Settings > Privacy & Security;
2. Tap the "Block cookies" option;
3. Observe the default selection;
### Expected behavior
"Block 3rd-party Tracker cookies only" is set by default on GeckoView.
### Actual behavior
"Block 3rd-party Tracker cookies only" is not selected in the Block cookies pop-up.

### Device information

* Android device: Samsung Galaxy S8 (Android 9)
* Focus version: Beta 8.0.16 (GV 69)

###Notes:
[Screenshot](https://drive.google.com/file/d/1vWW1MCLqyJwTmWd6jg182dvuPXrNJtix/view?usp=sharing)
This is also reproducible on WebView.

**Comment by ebalazs-sv** [comment]
This is still reproducible on Focus 8.0.20 GV 71 with Pixel 2 (Android 9).

**Comment by ebalazs-sv** [comment]
This is reproducible on Focus 8.1.1 Build 340941925 GV 74.0.2 with Pixel 2 (Android 9).

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Focus 8.3.0 (Build #341281936) GV 76.0.20200429185419 with Pixel 2 (Android 9).

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Focus 8.7.2 GV 80, from 8 /28, with Pixel 2 (Android 9).

**Comment by lobontiumira** [comment]
This is still reproducible on 8.13.1 build #1186.0.1-20210310152336 with Google Pixel (Android 10).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Focus 8.15.3 GV 88 with Huawei P9 Lite (Android 7).
