### ISSUE TITLE
Focus crashes when accessing bloomberg.com

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [mozilla-mobile/focus-android#4343]
**Browser / Version**
Firefox Focus 9.0

**Operating System**
OnePlus 6 (Android 9) - 1080 x 2280 pixels, 19:9 ratio (~402 ppi pixel density)

**Prerequisites:**
- None

**Steps to reproduce:**
1. Navigate to: https://www.bloomberg.com/

**Expected Behavior:**
The page is opened.

**Actual Behavior:**
The tab is crashing

**Notes:**
1. The issue is not reproducible on Chrome.
2. The issue is not reproducible on Fenix.
3. Screenshot attached.

**Watchers:**
@softvision-oana-arbuzov
@softvision-sergiulogigan
@cipriansv

![Screen capture](https://user-images.githubusercontent.com/16573771/64606810-c814ad00-d3cf-11e9-84e6-c204293f5e49.gif)

**Comment by softvision-sergiulogigan** [comment]
https://giphy.com/ also.

**Comment by colintheshots** [comment]
Focus 9.0 is not real. It will die a horrible death in Mordor, in the fires of Mount Doom.
