### ISSUE TITLE
Firefox Focus v8.0.17 aarch64 crashes during start

### ISSUE THREAD

**Issue by runboy93** [mozilla-mobile/focus-android#4357]
## Steps to reproduce

Install "app-focus-aarch64-release-unsigned.apk" from taskcluster builds.

Start app, it flashes and crashes, error report option shows.

### Expected behavior

It shouldn't crash at all, atleast v8.0.16 version doesn't do that or earlier ones.

### Actual behavior

v8.0.17 (aarch64) flash and crash after starting it up.

### Device information

* Android device: OnePlus 3T (Android 9)
* Focus version: v8.0.17 (aarch64)

**Comment by ldavison** [comment]
- Android device: Pixel 3 (Android 10)
- Focus version: v8.0.17 (Play Store Beta channel release)

Crashes on launch

**Comment by ikanakova** [comment]
Android device: Nokia 6.1 (Android 9)
Focus version: v8.0.17 (Play Store Beta channel release)

**Comment by allanf181** [comment]
Android device: Moto X4 (Android 9)
Focus version: v8.0.17 (Play Store Beta channel release)

**Comment by colintheshots** [comment]
The crash was fixed in 8.0.18, but there will be an 8.0.19 for a blank page issue on certain devices as well soon.

**Comment by ldavison** [comment]
Confirmed, fixed in 8.0.18. Thanks!
