### ISSUE TITLE
Blank pages appear in Focus 8.0.18 on Pixel devices

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/focus-android#4360]
## Steps to reproduce
1. Open Focus 8.0.18 on a recent Pixel or Nexus device.
2. Search for "cats" or anything.

### Expected behavior
Google page loads and is visible.

### Actual behavior
Page appears to be an empty white page.

### Device information

* Android device: Pixel 3 XL running Android 10
* Focus version: 8.0.18

**Comment by colintheshots** [comment]
This will be fixed by upgrading GeckoView to the latest 71 in 8.0.19.

**Comment by colintheshots** [comment]
8.0.19 is out for testing in beta now.

**Comment by colintheshots** [comment]
It seems the fix didn't work. I'll keep investigating on Monday.

**Comment by guimspace** [comment]
Not only Pixel devices. Mine is a ZenFone 3. Same Focus version.

**Comment by weedy** [comment]
LG G6, also white not loading

**Comment by ikanakova** [comment]
Same here.
Android device: Nokia 6.1 (Android 9)
Focus version: v8.0.19 (Play Store Beta channel release)

**Comment by ckempo** [comment]
Same here too.

The previous beta did nothing but crash the app. The most recent update has resolved that, but won't load any page content.

Android device: Nokia 7 Plus (Android 9)
Focus version: 8.0.19 (Build #332631851 🦎 71.0a1-20190920094918 - Play Store Beta channel release)

**Comment by Poopooracoocoo** [comment]
Is #4362 the same? It didn't look like the same thing as my pages have an insecure connection.

**Comment by ckempo** [comment]
Yeah, to my eyes #4362 is a dupe.

**Comment by Poopooracoocoo** [comment]
I wasn't sure if it was actually a dupe as no one else had mentioned the insecure connection thing

**Comment by colintheshots** [comment]
I have a proposed fix PR posted.

**Comment by ckempo** [comment]
Just received 8.0.20 (Build #332661411) via the Play Store and can confirm all now seems well. Thanks @colintheshots!

**Comment by pm-pm** [comment]
Here in Play Store only 8.0.16 is available. (Firefox Klar)
Could someone please check this.

**Comment by lobontiumira** [comment]
I'll close this ticket as obsolete.
