### ISSUE TITLE
Make option to use WebView user facing

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/focus-android#4364]
### Why/User Benefit/User Problem
GeckoView doesn't have the best performance has has a possible video player, and frankly, Android WebView/Chrome is better
### What / Requirements
Option in settings to use webview
### Acceptance Criteria (how do I know when I’m done?)
When user can switch between geckoview and webview

**Comment by cadeyrn** [comment]
There is already an option. On focus:test you can switch between WebView and GeckoView.

**Comment by Poopooracoocoo** [comment]
@cadeyrn oh cool! Thanks! I wish it were a user facing setting.

**Comment by colintheshots** [comment]
WebView is causing problems with a 0-day on Friday. It won't be a user facing setting.
