### ISSUE TITLE
Crashes once something is downloaded

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/focus-android#4366]
## Steps to reproduce
Open Focus
Navigate to APK Mirror 
Download an APK
### Expected behavior
It would download and let me continue browsing 
### Actual behavior
Focus crashes after APK has finished downloading 
### Device information

* Android device: Galaxy S5
* Focus version: 8.0.19 system webview

**Comment by ahjolinna** [comment]
Same on Sony Xperia XZ3,
Focus version: 8.0.20 (Build #332661411 🦎 71.0a1-20190920094918)

**Comment by ebalazs-sv** [comment]
I can reproduce this on Focus 8.0.20 GV 71 with Pixel 2 (Android 9).

**Comment by colintheshots** [comment]
I should have a fix quickly. It looks like I assumed there would still be a FileProvider in the manifest merger from the A-C upgrade and there wasn't.

**Comment by colintheshots** [comment]
Fixed in 8.0.22.
