### ISSUE TITLE
JavaScript alert does not pop up on GV 71

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4368]
## Steps to reproduce
1. Install and launch Focus 8.0.20 GV 71
2. Go to Settings > Privacy & Security 
3. Disable "Block JavaScript" setting
4. Go to: https://rpappalax.github.io/testapp and tap "Click here for JS alert" button

### Expected behavior
The alert does pop up.
### Actual behavior
The alert does not pop up.
### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: 8.0.20 GV 71
### Notes:
* The pop ups for Dropdown Menu, Location Menu, Date Picker Menu, Color Picker Menu are not displayed as well.
* After switching the device in landscape mode and tapping the "Click here for JS alert" button,  the button becomes blank.
* This is not reproducible on WebView.

**Comment by zznidar** [comment]
Authorisation dialogs are not shown either. That makes it harder to, for example, change router settings (instead of visiting 192.168.x.y and entering credentials when prompted, the user must navigate manually to user:pass@192.168.x.y) or login to any other auth-required site.

**Comment by Poopooracoocoo** [comment]
This is so irritating. I often just go to Chrome and make an incognito tab. Issues like these are why I made #4372 and #4364

**Comment by ebalazs-sv** [comment]
This is not reproducible on Focus 8.1.0 GV 74 .0.2 with Pixel 2 (Android 9), Pixel 3 XL (Android 9).
