### ISSUE TITLE
About Firefox Focus/Your Rights page flashes when tapped

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4369]
## Steps to reproduce
1. Launch Firefox Focus;
2. Tap on 3-dots button> Settings menu> Mozilla About Firefox Focus;
3. Tap "About Firefox";

### Expected behavior
Focus description shows up in focus:about.
### Actual behavior
A white flash is visible before the focus:about description is displayed.
### Device information

* Android device: Pixel 2 (Android 9), Pixel 3 (Android 9)
* Focus version: Focus 8.0.20 GV 71
### Notes
* This is also reproducible for 'Your Rights' page.
* Not reproducible on Webview
* [Video](https://drive.google.com/file/d/1GYLB0UDUobqUyPviltSoy9YUCHDnc9oZ/view)

**Comment by ebalazs-sv** [comment]
This is reproducible on Focus 8.1.1 Build 340941925 GV 74.0.2 with Pixel 2 (Android 9).

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Focus 8.3.0 (Build #341281936) GV 76.0.20200429185419 with Pixel 2 (Android 9).

**Comment by Diana-Rus** [comment]
Reproducible with Sony Xperia Z5 (Android 7) on Focus: 8.5.0, Build ID: 341821555 and GV 78.0-20200625152958

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Focus 8.7.2 GV 80.0.20200827204751, from 8/28, with Pixel 2 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on 8.15.1 build with Samsung Galaxy Note 8 (Android 9).

**Comment by Mugurell** [comment]
This looks similar to [Fenix-#6313](https://github.com/mozilla-mobile/fenix/issues/6313), [BZ-1663732](https://bugzilla.mozilla.org/show_bug.cgi?id=1663732) which was resolved with waiting for `firstContentfulPaint`.

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly build 99.0 from 2/22, with Samsung Galaxy Note 8 (Android 9), nor with Oppo Find X3 Lite (Android 11).
