### ISSUE TITLE
The floating text toolbar is in the wrong place on GV 71

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4371]
## Steps to reproduce
1. Go to a website (i.e. cnn.com) and select some plain text;
2. Observe the floating text selection toolbar.

### Expected behavior
The floating text selection toolbar appears above the selected text.
### Actual behavior
The floating text selection toolbar is placed in the top left side of the page.
### Device information

* Android device: Pixel 2 (Android 9);
* Focus version: 8.0.20 GV 71
### Notes
* Not reproducible on Webview.
* This is also reproducible for input box, if long pressed, the 'Paste' option from tool bar, is away from the input box.
[Screenshot1](https://drive.google.com/file/d/1x3Qh4VqbfGPSq6pYpgQtaTPmmrzQecnR/view?usp=sharing)
[Screenshot2](https://drive.google.com/file/d/1OTR2JVGLV-Lb_AtjgQT8kSQzqBJGcM_P/view?usp=sharing)

**Comment by vesta0** [comment]
I believe this has been fixed.

**Comment by ebalazs-sv** [comment]
This is reproducible on Focus 8.0.23 GV 71 with Pixel 2 (Android 9).

**Comment by Diana-Rus** [comment]
Hi, the issue does not reproduce on Firefox Focus 8.0.26 - GV: 73.0.1 with Google Pixel 3a (Android 9).
Please check [screenshot](https://drive.google.com/open?id=1CID0egPmzD7FYVINyfoZQNY_gnvikMyg).
