### ISSUE TITLE
focus:test disabling has no effect

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/focus-android#4372]
## Steps to reproduce
Navigate to focus:test
Tap on the slider
Let Focus restart 
Go to focus:test to see what it's using
### Expected behavior
It would turn off
### Actual behavior
It stays on
### Device information

* Android device: Galaxy S5
* Focus version: 8.0.20 (Build #332681235 🦎 71.0a1-20190920094918)

**Comment by guimspace** [comment]
Try clearing the data or reinstalling the app to fix it.

**Comment by Poopooracoocoo** [comment]
@guimspace Just reinstalled. No effect. :/

**Comment by colintheshots** [comment]
This was always intended primarily for QA to test different rendering engines. It's not a user-facing feature.

**Comment by Poopooracoocoo** [comment]
😢

I still prefer the system webview

**Comment by Poopooracoocoo** [comment]
@colintheshots 
😢
I still prefer the system webview
