### ISSUE TITLE
when top bar is shown the website should resize

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/focus-android#4373]
### Why/User Benefit/User Problem
This makes bottom navigation much less of a pain
### What / Requirements
The title?
### Acceptance Criteria (how do I know when I’m done?)
The title?

**Comment by lobontiumira** [comment]
@Poopooracoocoo thank you for the report!
Could you please, provide more details?
I was not able to reproduce this issue on the latest Focus builds.

**Comment by iorgamgabriel** [comment]
I can't reproduce it .
