### ISSUE TITLE
move erase to top

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/focus-android#4374]
### Why/User Benefit/User Problem
Fewer accidental erases
### What / Requirements
Move erase button to the top beside menu icon
### Acceptance Criteria (how do I know when I’m done?)
When the FAB is gone and the erase button is beside the menu button

**Comment by adityaoberai** [comment]
I want to try and fix this issue

**Comment by seydouba95** [comment]
i would like to work on this bug

**Comment by seydouba95** [comment]
i'm ready to contribute  on this bug

**Comment by Poopooracoocoo** [comment]
@lobontiumira 
I would've expected an option though, and frankly I must've done this as a half hearted feature request because I know that Focus is meant to be an ephemeral browser. :/

Also, do you know if there will be any improvements to how Focus keeps its tabs? I only ever want it to be cleared when I clear it, and seeing the snackbar after it erases jt that tells me that my browsing history was erased is like Focus is mocking me.
