### ISSUE TITLE
APK for v8.0.20

### ISSUE THREAD

**Issue by pihug12** [mozilla-mobile/focus-android#4375]
I have the "blank pages" bug with v8.0.19. Can you please provide the APK files for v8.0.20 (https://github.com/mozilla-mobile/focus-android/releases/tag/v8.0.20)?

Thanks!

**Comment by pm-pm** [comment]
I also need a working 8.0.20 apk.
Could someone please compile it. :-)
Thanks.

**Comment by weedy** [comment]
https://www.apkmirror.com/apk/mozilla/firefox-focus-private-browser/firefox-focus-private-browser-8-0-20-release/

**Comment by pm-pm** [comment]
Thanks. :-)
But this is "Firefox Focus 8.0.20",
I need "Firefox Klar 8.0.20" to preserver my setting.
 [Note: Firefox Klar is the Version for DE, AT, CH)

**Comment by pm-pm** [comment]
Or the new Version 8.0.22.

I have installed the bug version "Firefox Klar 8.0.19" and have no chance to update to error free version.

**Comment by weedy** [comment]
I can barely find any Klar apks on google. I think they aren't building it by default since updates seem to be so spread out https://archive.mozilla.org/pub/android/focus/

**Comment by colintheshots** [comment]
8.0.22 is posted. We wanted something which could go to production and which didn't regress in a number of ways.

**Comment by pm-pm** [comment]
It works! It works again! :-)
Thanks very much.
