### ISSUE TITLE
magiquiz.com crashes firefox focus

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4378]
This is a copy of the report on https://github.com/webcompat/web-bugs/issues/38333

**URL**: https://www.magiquiz.com/quiz/what-percentage-of-your-brain-do-you-use/2/?no_intro_page

**Browser / Version**: Firefox Mobile 68.0 (Focus)
**Operating System**: Android 8.0.0
**Tested Another Browser**: No

**Problem type**: Something else
**Description**: images did not display
**Steps to Reproduce**:
Clicked link and even tried reloading 

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by colintheshots** [comment]
This looks fixed in 8.0.22.

**Comment by lobontiumira** [comment]
Verified as fixed on the 8.16.0 Focus build with Google Pixel (Android 10).
