### ISSUE TITLE
Focus Crashes on Adding to Home Screen

### ISSUE THREAD

**Issue by shubhamkumar1739** [mozilla-mobile/focus-android#4387]
![Screenshot_2019-10-07-12-15-24-448_com miui bugreport](https://user-images.githubusercontent.com/40279181/66307628-7428b580-e8f4-11e9-8063-3e6bf39cc9c2.png)
## Steps to reproduce
Open What's new -> Before the page opens and as soon as possible (otherwise add to home screen gets disabled), Click Add to Home Screen -> Click ADD

### Expected behavior
Should not crash
### Actual behavior
Application crashes
### Device information

* Android device: Redmi Note 4
* Focus version: 8.0.22

**Comment by shubhamkumar1739** [comment]
Can I work on this?

**Comment by goforbg** [comment]
Understood the bug, basically when the menu is generated when URL is "about:blank", it tries to disable it. But when you open a URL and hit the menu twice, the "Add to homescreen" button is enabled in menu prompting the title to be "null". I looked at what chrome was doing, and they essentially just set the title as "About:blank" for that special case. Send a pull request now.

**Comment by lobontiumira** [comment]
This issue no longer reproduces.
I'll close the ticket.
