### ISSUE TITLE
Find in page : The number of results doesn't get cleared when search field is cleared

### ISSUE THREAD

**Issue by shubhamkumar1739** [mozilla-mobile/focus-android#4388]
## Steps to reproduce
Search for some text in "Find in page" -> Clear search text

### Expected behavior
The number of matches being zero for blank text, the text field indicating number of matches must be zero
### Actual behavior
It indicates the previous number of matches
### Device information

* Android device: Redmi Note 4
* Focus version: 8.0.22
![Screenshot_2019-10-07-16-41-54-957_org mozilla focus debug](https://user-images.githubusercontent.com/40279181/66307472-109e8800-e8f4-11e9-885a-c10339b2a357.png)

**Comment by shubhamkumar1739** [comment]
I wish to work on this

**Comment by lobontiumira** [comment]
I was able to reproduce this issue by following these STR:
1. Open a page with a lot of text.
2. From the three-dot menu, select the "Find in page" option.
3. Without enterring any characters, tap the up/down arrows from the "Find in page" search field.

Tested with Lenovo tab M10 (Android 10), on RC 91.2.2 build 352310216.

**Comment by lobontiumira** [comment]
Reproducible also on 93.0.2 (build 352522329 - GV 93.0a1-20210906031657) with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on RC 93.1.0 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 100.0.0-beta.1 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 101.0.0-beta.1 with Oppo Reno 6 (Android 12).

**Comment by lobontiumira** [comment]
Reproducible on Beta 102.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 104.0b1 with Lenovo tablet M10 (Android 10).

**Comment by ionutbedregeanu** [comment]
Note: This is also reproducible in Fenix

**Comment by Mugurell** [comment]
> Note: This is also reproducible in Fenix

Would the fix then be in GeckoView / A-C?

**Comment by ionutbedregeanu** [comment]
yes, probably in A-C

**Comment by delia-pop** [comment]
Verified as fixed on Focus Nightly 106.0a1 from 08/26 with Xiaomi 12 Pro (Android 12). 

https://user-images.githubusercontent.com/89388888/186909805-528acffe-a7e9-413e-883f-f397c5029cef.mp4

**Comment by lobontiumira** [comment]
Verified as fixed also on Beta 106.0b1 with Oppo Reno 6 (Android 12).
