### ISSUE TITLE
Considering supporting Fenix-style font inflation.

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/focus-android#4391]
Sites appear to have tiny fonts on Focus (like Fennec), but unlike Fenix as of https://github.com/mozilla-mobile/fenix/issues/4458

Users are reporting this as a difference with how Chrome renders pages, as per https://webcompat.com/issues/41531

This will apparently be a GeckoView option Focus may get for free, or may have to opt into, based on the discussion above. It might be worth aligning with Fenix here.

**Comment by wisniewskit** [comment]
Another case reported here: https://webcompat.com/issues/41083

**Comment by lobontiumira** [comment]
This issue still reproduces on the Focus Nightly build 99.0a1 (build 360630511 with GV 99.0a1-20220303094735) with Oppo Find X3 Lite (Android 11):
* verified on the https://history.nasa.gov/afj/ap11fj/01launch.html, and on
* http://diamondgeezer.blogspot.com/ pages

![tiny](https://user-images.githubusercontent.com/40694158/156738147-1879b025-a3e8-492a-a6e8-e131ceab4dd8.png)

**Comment by lobontiumira** [comment]
This issue still reproduces on the Focus Nightly build 104.0a1 with Oppo Reno 6 (Android 12). Tested on the following pages:
* https://history.nasa.gov/afj/ap11fj/01launch.html, and on
* http://diamondgeezer.blogspot.com/

![4391](https://user-images.githubusercontent.com/40694158/178670312-f88d5412-3e0b-41a1-bcfb-3a9fa13284e8.png)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802026

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
