### ISSUE TITLE
Black "about:" pages when browser is put in foreground

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4393]
## Steps to reproduce
1. Open Focus browser.
2. Insert into URL about:support.
3. Tap the device's Home button.
4. Open recent apps list.
5. Choose Focus app.
### Expected behavior
The information from about:support page is displayed.
### Actual behavior
The about:support page is black.

Notes:
*By refreshing the page or searching after "about:support" page again will display the information again
*It seems that all "about:" pages are affected, like: about:about, about:webrtc, about:buildconfig, about:memory
*[Screenshot](https://user-images.githubusercontent.com/49859863/66480121-9104ea80-eaa6-11e9-8657-06b6c7afc2d6.png)
 
### Device information

* Android device: Google Pixel 2 (Android 9)
* Focus version: Focus / Klar - v8.0.22

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Focus build with Oppo Find X3 Lite (Android 11), nor with Samsung Galaxy Note 8 (Android 9).
