### ISSUE TITLE
The newly added engine is present in "Search Engine" list only after re-opening the app

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4394]
## Steps to reproduce
1. Open Firefox Focus and navigate to "Settings"/"Search"/"Search Engine".
2. Tap on "+ Add another search engine".
3. Insert a name for the search engine and the patch with the correct fromat as per example.
4. Tap on "Save".
### Expected behavior
The newly saved engine in present in the list.
### Actual behavior
The newly saved engine in present in the list only after closing and reopening the app.
### Device information

* Android device: Google Pixel 2 (Android 9)
* Focus version: Focus / Klar - v8.0.22

**Comment by levimatheri** [comment]
Seems to be working fine in Klar. I can reproduce the issue in Focus though.

**Comment by Diana-Rus** [comment]
Hi, the issue is still reproducible with Samsung Galaxy S9 (Android 8) on Focus 8.1.1 (Build #340941926) GV:74.0.1-20200403064753

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Focus 8.3.0 (Build #341281936) GV 76.0.20200429185419 with Pixel 2 (Android 9).
cc @zhuperman @daniel88li

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly 99.0 (build 360540512 GV 99.0a1-20220222113841) with Google Pixel (Android 10).
