### ISSUE TITLE
URL Autocomplete - The "back" action does not redirect the user correctly

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4395]
## Steps to reproduce
1. Open Firefox Focus and navigate to "Settings"/"Search"/"URL Autocomplete".
2. Tap on the "Learn More" SUMO link.
3. Tap on the "Back" of the device.
### Expected behavior
The user is sent back to "URL Autocomplete" section.
### Actual behavior
The user is sent to the first page.
### Device information

* Android device: Google Pixel 2 (Android 9)
* Focus version: Focus / Klar - v8.0.22

Note:
It should be the same implementation as for "i" icon for "Add search engine" option.

**Comment by Jahnavi00** [comment]
Hi @Diana-Rus , I want to work on this issue. Can you please help?

**Comment by arvinth10** [comment]
Could I take this issue?

**Comment by delia-pop** [comment]
This issue was reproduced again on RC 92.1.0 (Build 352442046 ; 92.0-20210901142158) with Huawei P9 Lite (Android 8). 
The user is still redirected to the main page after tapping the back button from the "Learn more" links, instead of being sent back to "URL Autocomplete" section.

**Comment by lobontiumira** [comment]
Reproducible on the latest Focus Nightly 99.0 build from 2/23 with Google Pixel (Android 10).

**Comment by ionutbedregeanu** [comment]
@amedyne @jeffreygee I made a pr for this following the same approach as [here](https://github.com/mozilla-mobile/focus-android/issues/5316#issuecomment-936220336), but I'm not sure that's what we want. In Fenix the current behaviour, to open a normal tab and go back to home screen is considered expected, so maybe should keep the same flow in Focus.
What do you think?

**Comment by jeffreygee** [comment]
@ionutbedregeanu - IMO, the proper UX should be that the back button should follow the breadcrumb and return to the last spot. I did notice we don't follow this on Firefox. Let me take this back to the team and see if there's a reasoning for this.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802253

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
