### ISSUE TITLE
select not working on Firefox Focus

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4396]
## Steps to reproduce

    Navigate to https://www.hardlopen.nl/evenementen?naam=
    Dismiss the ads popups and accept cookies.
    Tap "Filter" button.
    Tap "Afstand" drop-down.

### Expected behavior
drop-down opens

### Actual behavior
drop-down does nothing

### Device information

* Android device: Pixel 2 Android 10
* Focus version:  Firefox Focus 8.0.20 (🦎 71.0a1-20191003093956)

Working in Nightly Fenix.

Reported initially at https://github.com/webcompat/web-bugs/issues/41780

**Comment by wisniewskit** [comment]
Even a ridiculously minimal test-case shows that selects are just not opening their "drop down" in Focus:
```
<!DOCTYPE html>
<html><body>
<select>
  <option>1</option>
  <option>2</option>
</select>                                   
</body></html>
```

**Comment by denschub** [comment]
Note that this also affects date pickers.

**Comment by rahulthewall** [comment]
I have the same issue and eat about to create a bug, thanks for reporting it. The issue does not persist in Firefox preview so using that for now.

**Comment by dom1n1k** [comment]
I have same problem with [ProDirectSelect](https://www.prodirectselect.com/products/Nike-Air-Max-200-WTR-Sepia-Stone-Reflect-Silver-Mens-Shoes-209752.aspx) shop (try to tap the "please select a size" box).
It dosn't work in the Firefox Focus. However, it works normally in the regular Firefox for Android.
In both cases the latest stable versions on the same device.
Weird.

**Comment by joaoportela** [comment]
Hi! I'm trying to understand why this hasn't been fixed yet.
It is really messing with my workflow. I've been going back to chrome more and more in the last few weeks because of this. 😔

Is there anything I can do to help fix this?

**Comment by cadeyrn** [comment]
There is already a fix, but it's not yet distributed via Google Play Store. You can test a pre release version with a fix: https://github.com/mozilla-mobile/focus-android/releases/tag/v8.0.24

**Comment by joaoportela** [comment]
thank you for the reply.

**Comment by jonalmeida** [comment]
> There is already a fix, but it's not yet distributed via Google Play Store. You can test a pre release version with a fix: https://github.com/mozilla-mobile/focus-android/releases/tag/v8.0.24

Right, 8.0.24 is now deployed to release, so we can close this bug now. If there are new bugs reports, those should be new issues.
