### ISSUE TITLE
"Safe browsing" section is missing from "Settings"/"Privacy & Security"

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4397]
## Steps to reproduce
1. Open Firefox Focus browser.
2. Go to  3 dots from top right corner "Menu"/"Settings"/"Privacy & Security"
### Expected behavior
Section "Safe browsing" is present.
### Actual behavior
There is no "Safe browsing" section displayed in "Privacy & Security".
### Device information

* Android device: Google Pixel 2 (Android 9)
* Focus version: Focus / Klar - v8.0.22

Note: 
1. There should be a toggle for this option with possibility of enable/disable.
2. Partially affected test case: https://testrail.stage.mozaws.net/index.php?/tests/view/1458964 (Step 2 and Step 3)

**Comment by lobontiumira** [comment]
The "Safe browsing" option is now available in the 8.18.0-rc.1 build.
I'm closing this issue.
