### ISSUE TITLE
The link from "Your Rights" section does not redirected based on chosen browse language

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4399]
Prerequisites:
* Change browser language from English to a different one.
### Steps to reproduce
1. Open Firefox Focus and navigate to "Menu"/"Settings"/"Mozilla"/"Your Rights".
2. Tap on one of the available links.
### Expected behavior
All links redirect to pages translated in the chosen language.
### Actual behavior
All links are redirected to the English version of the pages.
### Device information

* Android device: Google Pixel 2 (Android 9)
* Focus version: Focus / Klar - v8.0.22

Note:
1. All the link from "Your Rights" page/module are affected:
- "Mozilla Public License" link
- "Here" link for additional information
- "Licenses" link
- "GNU General Public License v3" link
- "Here" link for the blocklists/blacklist
2. Tested Languages: Czech language, German language, French language, Romanian, Spanish.
* The probability of the this outcome to be present for all, is high.

**Comment by bartonstanley** [comment]
I am an open source first-timer and I believe I can fix this issue.  Is there anything I need to know or do before I proceed?

**Comment by levimatheri** [comment]
What are the corresponding links for say Espanol? Does a link https://www.mozilla.org/[locale]/MPL/ exist or do all redirect to en-US?

**Comment by Diana-Rus** [comment]
Hi, yes you may be right.
Can someone help with the info if is there any way that this will be translated at some point? Or will remain only the english version?

**Comment by lobontiumira** [comment]
This issue has a duplicate with more details - #5398 
I'll close it.
