### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentManager android.support.v4.app.FragmentActivity.getSupportFragmentManager()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#440]
```
0	org​.mozilla​.focus​.fragment	UrlInputFragment.java ​Line ​355
UrlInputFragment.dismiss
	
1	org​.mozilla​.focus​.fragment	UrlInputFragment.java ​Line ​35
UrlInputFragment.access$300
	
2	org​.mozilla​.focus​.fragment	UrlInputFragment.java ​Line ​265
UrlInputFragment$3.onAnimationEnd
	
3	android​.view	
ViewPropertyAnimator.java ​ Line 1114
ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd
	
4	android​.animation	
ValueAnimator.java ​ Line 1239
ValueAnimator.endAnimation
```

`app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.java` line `355`

```java

                .setDuration(200)
                .alpha(reverse ? 0 : 1);
    }

    private void dismiss() {
        getActivity().getSupportFragmentManager() <-- CRASHED
                .beginTransaction()
                .remove(this)
                .commit();
    }

```

[View File](https://github.com/mozilla-mobile/focus-android/blob/1230d32cc6aa04ff67942a5f71f069d3233ccc37/app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.java#L355) | [View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/73dc56012a08a60406231476b68640d2)

**Comment by ahunt** [comment]
This is the same as the user-reported crash from #442:

I can reproduce this by doing the following:
1. Open the UrlInputFragment press on the URL input field)
2. Double-tap outside of UrlInputFragment
