### ISSUE TITLE
"Find in page" through Custom tab does not work correctly

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4401]
Prerequisites:
*Set Firefox Focus as default browser.

## Steps to reproduce
1. Open external browsing app (i.e. Gmail).
2. Open a website.
3. Tap the 3 dots icon.
4. Choose "Find in Page" option.
### Expected behavior
The elements for using the "Find in page" are correctly displayed and functional.
### Actual behavior
The section from above the soft keyboard does not display:
- the text field
- the number of words found
- the "previous word" arrow
- the "next word" arrow
- the "x" - cancel functionality icon
### Device information

* Android device: Google Pixel 2
* Focus version: Focus / Klar - v8.0.22

Note;
[Screenshot Expected](https://user-images.githubusercontent.com/49859863/66565455-371a2880-eb6b-11e9-9c83-e6ea1765a629.png)

[Screenshot Actual](https://user-images.githubusercontent.com/49859863/66565438-249fef00-eb6b-11e9-9701-819765161351.png)

**Comment by Diana-Rus** [comment]
Hi, issue is still reproducible with Firefox Focus 8.0.25 GV 71 with Google Pixel 3a (Android9).

**Comment by Diana-Rus** [comment]
Hi, could no verify this issue on Focus 8.1.0 GV-74.0-20200309095159 as it is impacted by ticket https://github.com/mozilla-mobile/focus-android/issues/4480 .

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Focus 8.8.0 Build ID: 342620305 GV 81.0.20200917005511 with Pixel 2 (Android 9).

**Comment by lobontiumira** [comment]
This issue reproduces on the 8.16.0 Focus build with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
Reproduces on the 8.17.0 Focus build with OnePlus 5T (Android 10).

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the 8.18.0-rc.1 build.
I'll close this issue.
