### ISSUE TITLE
Video does not play in fullscreen correctly.

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4402]
## Steps to reproduce
1. Open Firefox Focus.
2. Navigate to youtube.com.
3. Tap on the fullscreen icon.
### Expected behavior
The video is displayed correctly.
### Actual behavior
The video is not displayed in landscape mode. The video remains in portrait mode.
### Device information

* Android device: Google Pixel 2
* Focus version: Focus / Klar - v8.0.22

**Comment by Poopooracoocoo** [comment]
But the video is fullscreen. It's full screen and portrait.

To make it go landscape, rotate the device while auto rotate is on.

You should make a feature request. I've made a similar suggestion for a custom video player, JW Player.
https://github.com/jwplayer/jwplayer/issues/3488

**Comment by Poopooracoocoo** [comment]
Related: https://github.com/jwplayer/jwplayer/issues/3488

**Comment by Poopooracoocoo** [comment]
Just to be clear, when this issue was created, the mobile YouTube site used the native browser player. It now has a custom player.

Please take a look at my JW Player issue as I've linked a relevant Chromium issue where they discussed this and came to the conclusion that it would act like the YouTube app. JW Player said that what Firefox and most custom players do now is technically "correct". 

this would get a lot more action in the Fenix repo, ngl

**Comment by Diana-Rus** [comment]
Hi, thank you for providing the info, and the last update being in https://github.com/jwplayer/jwplayer/issues/3488#issuecomment-549865307 , based on the latest discussions from the mentioned ticket it seems that it is going to be implemented at some point that the video to be displayed in landscape when set in full screen. 
I will leave the ticket open until further notice as it still reproduces.

**Comment by Poopooracoocoo** [comment]
@Diana-Rus to me it sounds like JW Player doesn't want to implement it and just getting a response from them was difficult.  :(

Well anyway, is there another issue for Fenix? Fenix issues get a lot more eyeballs and therefore action.

**Comment by Diana-Rus** [comment]
Hi @Poopooracoocoo, found this ticket through which I think that it can be proposed to be taken into consideration to be given another look on how it should work: https://github.com/mozilla-mobile/fenix/issues/7602

**Comment by ebalazs-sv** [comment]
This is reproducible on Focus 8.1.1 (Build #340941925) GV:74.0.1-20200403064753 with Pixel 2 (Android 9).

**Comment by lobontiumira** [comment]
Still reproducible on Focus Nightly 99.0 from 2/23 with Google Pixel (Android 10).
Not reproducible with Oppo Find X3 Lite (Android 11).

**Comment by ionutbedregeanu** [comment]
@lobontiumira Is still reproducible?

**Comment by lobontiumira** [comment]
@ionutbedregeanu this issue no longer reproduces on the latest Focus Nightly 103.0a1 from 6/21.
Tested with Google Pixel (Android 10).
