### ISSUE TITLE
There is no password manager prompts to auto-fill credentials

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4403]
Prerequisites:
- Have a password manager application installed: Lockwise or LastPass and set it to autofill in browser
- Have login entries saved - in my case for twitter or facebook.

## Steps to reproduce
1. Open Firefox Focus app.
2. Navigate to twitter.com/facebook.com.
3. Tap on the "Username" field.
### Expected behavior
Password manager prompts to auto-fill credentials.
### Actual behavior
There is no password manager prompts to auto-fill credentials.
### Device information

* Android device: Google Pixel 2 (Android 9), Google Pixel XL (Android 10)
* Focus version: Firefox Focus 8.0.22

Note: For Google Pixel XL (Android 10) in case of using Google for auto fill service there is a prompt displayed, but with Lockwise there isn't.

**Comment by sflorean** [comment]
Reproducible on Focus: 8.3.0, Build ID: 341281936, with Lockwise. Device: Samsung Galaxy Note10 (Android 10).

**Comment by keunes** [comment]
Firefox Focus 8.12.0
Android 10
Keepass2Android 1.08

Does show prompt to fill password.

Since it works for me and OP also notes that some autofill services work, I would think it's the password app that should ensure implementation, rather than the Firefox Focus team.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Focus Nightly 99.0 (build 360540512 GV 99.0a1-20220222113841) with Oppo Find X3 Lite (Android 11).
