### ISSUE TITLE
Authorisation via URL not working

### ISSUE THREAD

**Issue by zznidar** [mozilla-mobile/focus-android#4406]
As per #4368, dialogs are not shown on GeckoView. That includes authorisation prompts, for example when changing the router settings. 
Usually, it is possible to log in via URL directly: http://username:password@192.168.x.y, however this results in about:blank in Firefox Focus (GeckoView).

## Steps to reproduce
1. Visit user:pass@192.168.x.y (with correct credentials)

### Expected behavior
User is authorised.

### Actual behavior
User sees the about:blank page.

### Device information

* Android device: pocophone f1, Android 9
* Focus version: 8.0.22 (Build #332812056 🦎 71.0a1-20191003093956)

**Comment by lobontiumira** [comment]
@zznidar is this still reproducible for you on the latest Focus builds?
Thank you!

**Comment by zznidar** [comment]
The issue appears to no longer exist (97.2.0). I'll close it, thanks!
