### ISSUE TITLE
Crash at startup 

### ISSUE THREAD

**Issue by guiled** [mozilla-mobile/focus-android#4407]
## Steps to reproduce
Just launch the app

### Expected behavior
Run properly

### Actual behavior
Crash after 3 seconds.

### Device information
* Android device: Zenfone 2 (intel cpu) Android 5
* Focus version: 8.0.23

**Comment by lobontiumira** [comment]
I was not able to reproduce this crash on Android 5 devices on the latest Focus builds.
I'll close this ticket.
