### ISSUE TITLE
IllegalStateException: Fragment UrlInputFragment{2f687bc} not attached to Activity

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#441]
```
0	android​.support​.v4​.app	
Fragment.java ​ Line 646
Fragment.getResources
	
1	android​.support​.v4​.app	
Fragment.java ​ Line 681
Fragment.getString
	
2	org​.mozilla​.focus​.fragment	UrlInputFragment.java ​Line ​423
UrlInputFragment.onFilter
	
3	org​.mozilla​.focus​.widget	InlineAutocompleteEditText.java ​Line ​555
InlineAutocompleteEditText$TextChangeListener.afterTextChanged
	
4	android​.widget	
TextView.java ​ Line 9435
TextView.sendAfterTextChanged
	
5	android​.widget	
TextView.java ​ Line 12351
TextView$ChangeWatcher.afterTextChanged
```

`app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.java` line `423`

```java

            clearView.setVisibility(View.GONE);
            searchViewContainer.setVisibility(View.GONE);
        } else {
            clearView.setVisibility(View.VISIBLE);

            final String hint = getString(R.string.search_hint, searchText); <-- CRASHED

            final SpannableString content = new SpannableString(hint);
            content.setSpan(new StyleSpan(Typeface.BOLD), hint.length() - searchText.length(), hint.length(), 0);

            searchView.setText(content);
```

[View File](https://github.com/mozilla-mobile/focus-android/blob/1230d32cc6aa04ff67942a5f71f069d3233ccc37/app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.java#L423) | [View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/9c7376bc1bc6262864dcfa5671e5cb25)

**Comment by ahunt** [comment]
It looks like this could happen if the fragment is hidden (via onCommit()) before onFilter() has been called. IInputConnectionWrapper dispatches various text edit events via the UI event loop, so onFilter() might only be called some arbitrary amount of time after text was entered. onCommit() is called immediately after the ENTER button was pressed (it hides the fragment immediately), so it's possible for onFilter() to be called with the fragment already being hidden.

The indirection happens in:
http://androidxref.com/7.1.1_r6/xref/frameworks/base/core/java/com/android/internal/view/IInputConnectionWrapper.java
We call onCommit immediately from:
https://github.com/mozilla-mobile/focus-android/blob/ecd439c01bd35e266766377920dcc0d84a0261ff/app/src/main/java/org/mozilla/focus/widget/InlineAutocompleteEditText.java#L584
