### ISSUE TITLE
opening Focus leads to Android rebooting

### ISSUE THREAD

**Issue by asquartz** [mozilla-mobile/focus-android#4412]
Steps to reproduce
Open Firefox Focus 8.0.23 and wait a few seconds, or alternatively click on any web link in another app (Focus is set to handle web links)

Expected behavior
Firefox Focus opens and displays webpage

Actual behavior
Focus opens briefly, then Android immediately reboots.

Device information
    Android device: Nexus 7 2013, Android 9 (unofficial LineageOS 16)
    Fenix version: 8.0.23 from Play Store

I can't get any info from about:crashes, since the browser doesn't stay open.
This occurred directly after I updated my app to the latest version in the Play Store, and did not happen beforehand. I have tried deleting and re-installing Focus, and clearing data and cache.

**Comment by ajhbh** [comment]
I get the same behaviour on my HTC One M8 Android 9 (LineageOS 16) with Firefox Focus 8.0.24

**Comment by asquartz** [comment]
I just updated to 8.0.24, disappointingly no change.  
There has been no acknowledgement for nearly a month, I wonder if anyone is reading these reports?

**Comment by gobater** [comment]
I can confirm the above mentioned issues. however, I am not sure I had them before updating my Lineage OS to 15.1 (December 2019). July version was working fine as fas as I can remember

**Comment by lobontiumira** [comment]
This is no longer reproducible on the latest Focus builds.
I'll close this ticket.
