### ISSUE TITLE
Tablet reboots 

### ISSUE THREAD

**Issue by roensholt** [mozilla-mobile/focus-android#4416]
## Steps to reproduce
Open FF - wait 4 - 5 seconds and the tablet reboots
### Expected behavior
Show web page
### Actual behavior
Tablet reboots
### Device information
Sony Xperia Tablet Z LTE. LineageOS 15.1 (8.1)

* Focus version: 8.0.23

**Comment by lobontiumira** [comment]
I did not encounter this issue on a Samsung Galaxy Tab A6 (Android 5.1.1), nor on Lenovo Tab M10 (Android 10) tablets on the latest builds of Focus.
I'll close this ticket.
