### ISSUE TITLE
Application crashes after tapping multiple times on the search field (Home screen)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#442]
From feedback:

> Application crashes after tapping multiple times on the search field. Steps to reproduce: 1. Open app. 2. Tap multiple times on the "Search" field. 3. After "Search" field is becomes hidden, tap the screen. Expected result: "Search" field remains displayed. Actual result: Application crashes.

It's likely that this is one of the new crashes we got via buddybuild (#439, #440, #441)

**Comment by ahunt** [comment]
This is #440, I've posted simpler repro steps there!
