### ISSUE TITLE
Website page is abnormal

### ISSUE THREAD

**Issue by liugan-github** [mozilla-mobile/focus-android#4420]
## Steps to reproduce
1、Open the app,
2、enter the website address: https://www.douyu.com
3、press Enter to start loading the page

### Expected behavior
Website page is displayed normally

### Actual behavior
Page layout is abnormal

### Device information

* Android device: Galaxy A7 SM-A7100,Android 5.1.1
* Focus version: Focus-arm - v8.0.23

**Comment by Poopooracoocoo** [comment]
Is this a web-compat issue?

**Comment by lobontiumira** [comment]
This issue is oboslete.
I was not able to reproduce it on the latest Focus Nightly build with Xiaomi mi4i (Android 5.0.2).
