### ISSUE TITLE
Firefox Focus is draining your battery

### ISSUE THREAD

**Issue by StuartHaire** [mozilla-mobile/focus-android#4421]
## Steps to reproduce

1. Open application and use as desired
2. Close application and erase browsing history

### Expected behavior

The application should close

### Actual behavior

The application closes and after a few minutes android notifies "Firefox Focus is draining your battery" and allows me to force stop. Happens every time.

### Device information

* Android device: OnePlus 6
* Focus version: 8.0.23
Have noticed on other devices however

**Comment by Poopooracoocoo** [comment]
What version of Android are you on? I haven't experienced battery drain like that before on Samsung's Marshmallow (which is notorious for having memory management issues lol)

**Comment by StuartHaire** [comment]
Android 9. Android 10 is to be released very soon for my device so I'll be upgrading to that as soon as available.

**Comment by sanojsubran** [comment]
I also observe similar issue. I got the the same error message.

Steps to reproduce:

1. Open firefox focus and browse as desired. Delete the history.
2. Minimize the app by going to the homescreen.

After a while, I am getting a notification that Firefox Focus is draining your battery and I have to forcefully kill the app.

Firefox focus version: 8.0.23  Build: 332871437
Device: Oneplus 6
OS: Android 9
Kernel version: 4.9.106-perf+

**Comment by this-is-rafa** [comment]
Same problem here. Only started happening after the latest update from the Play store. The Oneplus battery manager is known to be aggressive, but the battery percentages show that FF is using more than before.

Firefox Focus: 8.0.23 Build: 332871437
Device: Oneplus 5t
OS: Android 9 / Oxygen OS 9.0.8
Kernel: 4.4.153-perf+

**Comment by Gogo-ZvC** [comment]
I've been experiencing this as well. Same steps as @sanojsubran.

Firefox Focus: 8.0.23
Device: OnePlus 7 Pro
OS: Android 10 / Oxygen OS 10.0.1
Kernel version: 4.14.117-perf+

**Comment by StuartHaire** [comment]
Issue resolved for me when updating to;
Firefox Focus: 8.0.23
Device: OnePlus 6
OS: Android 10 / Oxygen OS 10.0
Kernel: 4.9.179-perf+

**Comment by waleedsamy** [comment]
Issues still here 
Firefox Focus: 8.0.24
Device: OnePlus 5t
OS: Android 9
Kernel: 4.4.153-perf+
