### ISSUE TITLE
[Bug] Previous opened tab displays about:blank

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4427]
## Steps to reproduce
1. Go to Settings -> Mozilla -> Help;
2. Go to Settings -> Mozilla -> Privacy Notice;
3. Tap the opened tabs and choose to open the Help page;
### Expected behavior
Help page opens.
### Actual behavior
The page is displayed as about:blank.

### Notes
[Video](https://drive.google.com/file/d/1X5LftXJnRz0_2tY7dfUC8VAvzU-i4OLn/view)
This is also reproducible after about:crashcontent, the remaining tabs are displayed as about:blank.

### Device information

* Android device: Google Pixel 2 (Android 9)
* Focus version: 8.0.24 GV 71

**Comment by ebalazs-sv** [comment]
This is not reproducible on Focus 8.1.0 GV 74 .0.2 with Pixel 2 (Android 9), Pixel 3 XL (Android 9).

**Comment by Diana-Rus** [comment]
Hi, I wll reopen this as with Samsung Galaxy S9 (Android 8) i reproduce this issue on Focus 8.1.1 (Build #340941926) GV:74.0.1-20200403064753.

**Comment by sflorean** [comment]
Reproducible on Focus: 8.3.0 (Build ID: 341281936) with Samsung Galaxy Note10 (Android 10).

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the latest builds: beta 95.0.0-beta.1, RC 94.1.1.
