### ISSUE TITLE
[Bug] Page cannot be reloaded or edited after changing the Tracking Protection setting

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4428]
## Steps to reproduce
1. Go to https://mozilla.github.io/tracking-test/analytics.html;
2. Go to Settings > Privacy & Security;
3. Disable analytic trackers from Tracking Protection;
4. Exit Settings and reload page from Step 1.

### Expected behavior
The page is reloaded and the change from Step 3 is visible.
### Actual behavior
The page cannot be reloaded or edited.
### Notes
Long tapping the URL bar and choosing Open, opens a new tab where the setting from Step 3 is visible and also the page can be reloaded. The previous opened tab is available as about:blank (https://github.com/mozilla-mobile/focus-android/issues/4427).
This is also reproducible for Block ad trackers and Block social trackers.

### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: 8.0.24 GV 71

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus builds.
I'll close it.
