### ISSUE TITLE
Dropdown menu is not working after opening a downloaded file

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4430]
## Steps to reproduce
1. Go to https://rpappalax.github.io/testapp;
2. Tap on "Download this icon";
3. From the Download File pop-up, choose Download;
4. Open the downloaded file from the notification tray;
5. Go back on the webpage and tap on any dropdown menu;
### Expected behavior
Dropdown menu opens.
### Actual behavior
Downdown menu is not working.

### Notes
This is also reproducible on https://www.hardlopen.nl/evenementen?naam=;
[Video](https://drive.google.com/file/d/1TWFRVtYp6ySnkzicy_5YFd1Xwq2eaZC2/view)
### Device information

* Android device: Pixel 2 (Android 9);
* Focus version: 8.0.24 GV 71

**Comment by jonalmeida** [comment]
Thanks @ebalazs-sv ! I've followed your steps to reproduce, but I'm unable to reproduce the bug on a Pixel 2.

**Comment by ebalazs-sv** [comment]
This is not reproducible on Focus 8.1.0 GV 74 .0.2 with Pixel 2 (Android 9), Pixel 3 XL (Android 9).
