### ISSUE TITLE
Downloading a file with the same name as an existing one, overwrites the previous file

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4431]
## Steps to reproduce
1. Download a file with name, say filename.png.
2. Observe the date created for the file in a file manager.
3. Download the file again.
2. Observe the date created for the file in a file manager.

### Expected behavior
- There should be two files (probably with the names `filename.png` and `filename (1).png`).

### Actual behavior
- There is only one file, the latest downloaded one.

### Device information

* Android device: Pixel 2 (Android 10)
* Focus version: v8.0.24

**Comment by refactor-droidyy** [comment]
@jonalmeida can I work on this issue

**Comment by Jahnavi00** [comment]
@jonalmeida  Can I work on this bug issue ,please ?

**Comment by jonalmeida** [comment]
Hello, I don't believe we're accepting contributor pull requests for Focus at the moment. If you're looking for another project to contribute to, have a look at [Android Components](https://github.com/mozilla-mobile/android-components/) and [Fenix](https://github.com/mozilla-mobile/fenix/)! 🙂

**Comment by lobontiumira** [comment]
This is no longer reproducible on the latest Focus Nightly from 2/23.
The image is saved as many times as the user saves it, adding the (1) to the image's name.
