### ISSUE TITLE
Firefox Focus needs an updated logo

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#4435]
The current logo of Firefox Focus still uses the old Firefox shape. Since Firefox for Desktop and Firefox Lite already use an updated logo it's time for Firefox Focus to get an updated logo, too.

**Comment by cadeyrn** [comment]
@jonalmeida: I ask you because you are the one who is still active here: Do you know who is responsible for branding these days and could you forward this request to the right people? Firefox Focus still uses the old Firefox shape as logo and I guess it should be updated for branding reasons.

**Comment by jonalmeida** [comment]
@cadeyrn thanks! I'll look into it. :)

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/focus-android/issues/4650
