### ISSUE TITLE
Firefox Focus 8.0.24 uses a wrong user agent string as desktop

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/focus-android#4441]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1599334

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.9) Goanna/4.4 PaleMoon/28.7.2

Steps to reproduce:

1. Visit a website that show the web browser's user agent string, like these ones:
https://httpinfo.net/?sort=lastseen
https://duckduckgo.com/?q=what+is+my+user+agent&t=palemoon&ia=answer
2. Set Firefox Focus to show the desktop version of that website, i.e., to reload that webpage and use the Firefox desktop UA string instead.

Actual results:

Firefox Focus 8.0.24 uses this user agent string:
Mozilla/5.0 (X11; Linux x86_64:71.0) Gecko/20100101 Firefox/71.0

Expected results:

It should use this one instead:
Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0

**Comment by lobontiumira** [comment]
This issue is now obsolete.
Closing.
