### ISSUE TITLE
Unable to sign in with Google account on https://member-m.daraz.pk/user/login

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/focus-android#4444]
Originally reported @ https://github.com/webcompat/web-bugs/issues/45970

STR:

1. go to https://member-m.daraz.pk/user/login
2. attempt to sign in w/ Google credentials

Expected: login works
Actual: end up with a blank page

See the screenshots in the linked image. Note this still reproduces with trackers enabled.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Focus Nightly build with Oppo Find X3 Lite (Android 11).
