### ISSUE TITLE
Javascript whitelist / blacklist

### ISSUE THREAD

**Issue by Harteex** [mozilla-mobile/focus-android#4446]
### Why/User Benefit/User Problem
Some sites run a lot faster with no annoying popup dialogs when Javascript is off. At the same time, many other sites do not work at all when Javascript is turned off.
This means that while the user might want to turn off Javascript, they will have to turn it on for other sites, leading to the user having to enter the menu a lot to toggle the Javascript setting.

### What / Requirements
It would be great to be able to add domains / sites to a whitelist or blacklist, or why not support both. I suggest having a button below or near the javascript settings toggle in the menu, where sites could be added / removed. It could also suggest the currently visited page to reduce the required user input.

### Acceptance Criteria (how do I know when I’m done?)
When a whitelist and/or blacklist is available to control Javascript per site, regardless of the global Javascript setting.

**Comment by Poopooracoocoo** [comment]
I think that the per website setting could be in the protection popup and you could manage the whole setting in settings. Like Chrome for desktop (surprisingly Firefox for desktop is a bit annoying in terms of permission management)

**Comment by cutephoton** [comment]
+1 x 1000000 I have been toggling js on and off for months through the settings. There needs to be an easier way. I'd like just a toggle button like the tracker.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802027

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
