### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by CDGDVD** [mozilla-mobile/focus-android#4448]
## Steps to reproduce
I don't how to reproduce it :/
### Expected behavior
opening the app and installing addons
### Actual behavior
Crash on startup with no error whatsoever
### Device information
lineageos 14.1 with gapps (pico)
* Android device: Galaxy Tab E
* Fenix/firefox version: Normal, beta, nightly

**Comment by Diana-Rus** [comment]
Hi, this doesn't seem to be a Firefox Focus issue. Firefox Focus doesn't have the addons functionality. I will close the ticket as it isn't valid.
In case you encounter issues on Firefox Preview browser please create an issue here: https://github.com/mozilla-mobile/fenix/issues
