### ISSUE TITLE
falk.de -  map is not visible

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4449]
## Steps to reproduce
With Firefox Focus on Android
1. head to https://www.falk.de/

### Expected behavior
See the map

### Actual behavior
The map is not visible.
### Device information

* Android device: Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
* Focus version: Firefox Focus 8.0.24 (🦎 71.0a1-20191003093956)

This is https://github.com/webcompat/web-bugs/issues/46899

**Comment by Diana-Rus** [comment]
Hi, I can reproduce the issue with Google Pixel 3a  (Android 9) on Firefox Focus 8.0.26 with GV: 73.0.1

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the RC 98.1.0 build.
