### ISSUE TITLE
Custom tab - Option "Request Desktop Site" does not work.

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4452]
Prerequisites:
- Make "Firefox Focus" as default browser.
## Steps to reproduce
1. Open gmail app.
2. Open a website through gmail.
3. Tap on the 3 dot menu.
4. Enable the "Request desktop site" option by checking the provided checkbox for the option.
### Expected behavior
The desktop version of the site is displayed.
### Actual behavior
The mobile version of the site is displayed.
### Device information

* Android device: Google Pixel 3a (Android 9)
* Focus version: Firefox Focus 8.0.25 with GV 71

Note:
- A [video](https://drive.google.com/file/d/1SgDjjjrtfCpdarZaRGt6Iduv6dD0B6Ad/view?usp=sharing) with outcome is present. I verified the issue with site "wikipedia.org".

**Comment by Diana-Rus** [comment]
Hi, verified the issue with Google Pixel 3 XL (Android 9) on Firefox Focus 8.1.0 GV: 74.0-20200309095159
Verified sites:
- wikipedia.org
- thinkbroadband.com/download
- m.9gag.com
- amazon.com

Note:
- For baidu.com it seems that is a different version than the the Desktop Version from Chrome.
- As a side note is what I observe that somehow it takes much more longer than before for the pages to be rendered through Custom Tab -> 
![20200311-154214](https://user-images.githubusercontent.com/49859863/76424137-82519500-63b0-11ea-899d-8b8cb80e6f0f.gif)

Please check GIF:
![20200311-154023](https://user-images.githubusercontent.com/49859863/76423873-15d69600-63b0-11ea-91fb-b7f81ec95328.gif)

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Focus Nightly 99.0 build from 2/23, using an Oppo Find X3 Lite (Android 11), and a Samsung Galaxy Note 8 (Android 9).
