### ISSUE TITLE
Reddit - Link to install apps doesn't work

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4453]
## Steps to reproduce
1. Go to reddit.com and tap the "Use app" button.
2. If the app is not installed, install it from google play and repeat Step 1.
### Expected behavior
If the app is installed, the app should open.
If the app is not installed, you should be directed to the playstore.
### Actual behavior
The redirect does not work.
### Device information

* Android device: Google Pixel 3a (Android 9)
* Focus version: Firefox Focus 8.0.25 GV 71

Note:
- Related to ticket: https://github.com/mozilla-mobile/focus-android/issues/3530
- In case of using:  https://rpappalax.github.io/testapp, scroll down to "Misc Link Types" and click on "External app (play store)" that link works correctly with the same device and Focus version.

**Comment by NastyaGrifon** [comment]
The issue persists on Android 10, January Security Patch

Google Pixel 3a  (QQ1A.200105.002)
Firefox Klar 8.0.25 (Build #340092236 🦎 71.0.1-20200108003105)

**Comment by Diana-Rus** [comment]
Hi, issue is still reproducible with Google Pixel 3 XL (Android 9) on Firefox Focus 8.1.0 GV: 74.0-20200309095159 .

**Comment by Diana-Rus** [comment]
Hi, issue is still reproducing with 8.1.1 with Samsung Galaxy S9 (Android 8) on Focus 8.1.1 (Build #340941926) GV:74.0.1-20200403064753

**Comment by ebalazs-sv** [comment]
This is reproducible on Focus 8.1.1 (Build #340941925) GV:74.0.1-20200403064753 with Pixel 2 (Android 9).

**Comment by Diana-Rus** [comment]
Hi, issue does not seem to reproduce on Focus: 8.2.0 Build ID: 340992214 and GV 75.0-20200403170909 with:
- Sony Xperia Z5 (Android 7)
- Google Pixel 3 XL (Android 9)
Are you @NastyaGrifon still reproducing the issue?

**Comment by Diana-Rus** [comment]
Still not reproducing the issue, ticket will be closed.
