### ISSUE TITLE
8.0.25 requesting the READ_PHONE_STATE permission

### ISSUE THREAD

**Issue by STPR** [mozilla-mobile/focus-android#4456]
8.0.25 requesting the **READ_PHONE_STATE** permission :

> **READ_PHONE_STATE**
> **Allows read only access to phone state, including the phone number of the device, current cellular network information, the status of any ongoing calls, and a list of any PhoneAccounts registered on the device.**

**Comment by colintheshots** [comment]
It appears upgrading Google's Install Referrer library to the latest caused this. I believe we can safely downgrade in the next release.

**Comment by STPR** [comment]
Why can't you just keep the latest version and add the following line into the manifest ?
`<uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />`

**Comment by STPR** [comment]
Strangly, Firefox Klar 8.0.25, the "german" version of Firefox Focus, doesn't need this permission !

Quite frankly :

I really doubt you're discovering this just now.
So, either you need it for some obscure reasons, or you shall correct this immediatly.
That's a MAJOR issue for a browser promoting itself as a "privacy browser".

Looking at all the comments inside the play store, you really shall not wait the next release to correct this.

**Comment by STPR** [comment]
We are now at the 8.026 version and the permission is still there.
So, what do you believe now ?
Why is it so hard to put the following line in the manifest ?
`<uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />`

**Comment by STPR** [comment]
We are now at the 8.1.0 version and the permission is still there.
Do you still believe something ?

**Comment by STPR** [comment]
You don't have to believe something anymore.
Just update the Google's Install Referrer library to version 1.1.2.
(since you didn't want to use the previous fix in the manifest file)

**Comment by ionutbedregeanu** [comment]
From what I see this ticket was fixed meanwhile, so I will close it

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 100.0a1 from 3/14 with Samsung Galaxy Note 8 (Android 9), and Lenovo Tab M10 (Android 10).
