### ISSUE TITLE
Bookmarks in autocomplete default to HTTP

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#4460]
Bookmarks in my own autocomplete list default to HTTP even if the site supports HTTPS. This is a possible security risk.

I'm using Klar 8.0.15 (last F-Droid version) on Android 7.

**What the app should do**

To avoid downgrade attacks, Focus should either connect by HTTPS and let the user edit the address bar to change to http:// if the connection fails. Or alternatively remember when adding the autocomplete address whether the connection is via HTTP or HTTPS.

**Comment by arvinth10** [comment]
Could I take this issue?

**Comment by lobontiumira** [comment]
On the latest Focus Nightly 99.0 from 3/4, the behavior is:
* the user saves a http page, like http://permission.site,
* the page saves as permission.site, not displaying the http, or the https,
* the page is opened as https://permission.site.

However, I'm not sure this is a bug.
@jonalmeida could you take a look? Thank you!

https://user-images.githubusercontent.com/40694158/156740005-6b9dd142-d84b-4bf8-b911-bae6081aa9dc.mp4

**Comment by jonalmeida** [comment]
@lobontiumira This should be expected now since we've enabled HTTPS-only mode.

**Comment by lobontiumira** [comment]
Thank you!
I'll close this issue.
