### ISSUE TITLE
Update Firefox Klar on F-Droid to patch this month's 0day

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#4461]
Firefox Focus (Klar) on F-Droid is six months out of date. At the moment I'm only using it with JS disabled. It needs to be patched against the vulnerability patched in FF 72 and/or any other security problem discovered in the last 6 months.

**Comment by cadeyrn** [comment]
The latest official version from Mozilla already has a fix. Mozilla is not responsible for F-Droid...

**Comment by zekooooo** [comment]
I don't know if this is related. F-Droid just recommended me to uninstall Klar because of a known vulnerability.

**Comment by cadeyrn** [comment]
I don't know the state of F-Droid but in the meantime you can install the latest version from https://github.com/mozilla-mobile/focus-android/releases - version 8.0.25 contains the security fix. It's probably better than waiting since there was no update on F-Droid for a few months.

**Comment by NastyaGrifon** [comment]
> I don't know if this is related. F-Droid just recommended me to uninstall Klar because of a known vulnerability.

Same

**Comment by nyoxi** [comment]
@colintheshots, who is responsible for F-Droid releases? Could we get a new version there?

**Comment by vbrandl** [comment]
Any news on this issue? I'm also waiting for a new version on F-Droid

**Comment by akierig** [comment]
Any update on the status of updating it at F-Droid would be appreciated, please.

**Comment by J0WI** [comment]
Duplicate of https://github.com/mozilla-mobile/focus-android/issues/1528
