### ISSUE TITLE
tab switching

### ISSUE THREAD

**Issue by tmdwns7809** [mozilla-mobile/focus-android#4462]
Other browsers implement tab switching very smoothly like the tabs have been always existing
Even with firefox
But firefox focus has a little blinking time apparently when it's switching tabs
I wanna know this can be fixed and what's the reason this is happening 
And I really appreciate to all you guys for doing hard works every day for people thank you

**Comment by Poopooracoocoo** [comment]
And even when just switching apps, some content gets re-rendered

**Comment by lobontiumira** [comment]
This issue is no longer reproducible.
The latest Focus builds provides smooth tab switching.
