### ISSUE TITLE
medium.com - Zooming ends up scrolling the site very fast

### ISSUE THREAD

**Issue by SeriousM** [mozilla-mobile/focus-android#4464]
Issue from https://github.com/webcompat/web-bugs/issues/47680

**URL**: https://medium.com/tenable-techblog/lets-reverse-engineer-discord-1976773f4626

**Browser / Version**: Firefox Mobile 71.0
**Operating System**: Android
**Tested Another Browser**: No 

**Problem type**: Something else
**Description**: Zooming ends up scrolling the site very fast
**Steps to Reproduce**:
Zoom the page with pinch gesture diagonal or vertical.
At the end of the gesture the page is scrolling very fast in either up or down in zoomed state.

The problem existed till a few months after the initial release of Firefox klar/focus and was fixed. 
Since the last version the bad behaviour returns.

To be clear, this issue happens on many sites.

<details>
<summary>Browser Configuration</summary>
<ul>
  <li>None</li>
</ul>
</details>

_From [webcompat.com](https://webcompat.com/) with ❤️_

-------------------------------------------

Thanks for the report!
I'm able to reproduce the issue when pinching out relatively quickly. If a pinch out gesture is performed at a low speed, the issue is not reproducible. It's takes a little bit of luck to reproduce this one.

**Tested with:**
Browser / Version: Firefox Focus 8.0.25 (🦎 71.0a1-20200108003105)
Operating System: Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

Moving to Needsdiagnosis.

![Screen capture](https://user-images.githubusercontent.com/16573771/72330710-a732d000-36bf-11ea-9c28-bb393cf7b632.gif)

**Comment by Poopooracoocoo** [comment]
Happens on any site. It doesnt just happen when zooming. 

I think this is a GeckoView bug. I can repr in Fenix but not in Fennec

**Comment by zekooooo** [comment]
Yes this also happens on all sites to me on 8.0.15 pretty often.

**Comment by Poopooracoocoo** [comment]
@zekooooo I recently "downgraded" to 8.0.16 and was also able to repro. I got back to the system webview from about:test and I finally feel like I'm not walking on eggshells with Focus any more. It's like taking off your shoes after a long day.

**Comment by Diana-Rus** [comment]
Hi, I can reproduce this with Google Pixel 3a (Android 9) with Firefox Focus 8.0.26 (Build #340521549) and GV: 73.0.1-20200211134023.

**Comment by Diana-Rus** [comment]
Hi, I can reproduce this issue on Firefox Preview Nightly 200225 (Build #20560606) GV: 75.0a1-20200223093951 with onePlus 6T (Android 9).

I marked the ticket as GV issue.

**Comment by this-is-rafa** [comment]
I've had this issue in various versions of Firefox for Android, and currently am experiencing it in:

Firefox Focus 8.0.26 (Build #340521550) GV 73.0.1-20200211134023.

One way to avoid it is to lift up one finger at a time when pinching.

**Comment by Diana-Rus** [comment]
Hi, issue is reproducible on Focus 8.1.0 GV: 74.0-20200309095159 with Google Pixel 3 XL (Android 9).

**Comment by Diana-Rus** [comment]
Hi, the issue is still reproducible with Samsung Galaxy S9 (Android 8) on Focus: 8.1.1(Build #340941925) GV: 74.0.20200403064753

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Focus Nightly 100.0a1 from 3/18 with Samsung Galaxy Note 8 (Android 9).
I've tested with several pages.
