### ISSUE TITLE
Some fingerprint protection bugs

### ISSUE THREAD

**Issue by TomekS2** [mozilla-mobile/focus-android#4466]
1. When I try open link I can skip fingerprint check

This isn't occure when I open by share, only by link. When I click share everything is ok.

    1. browser must be fingerprint protected
    2. open any web site(eg. github.com)
    3. minimalize browser
    4. check if fingerprint protection exist
    5. open LINK eg. click on link in contact app
    6. now browser skip fingerprint protection

demonstrated here: https://mega.nz/#!23xRiYQI !snHur0ZYX5k0SxXijKHQblTIWVn2ntlZ0fa8rGow3JY

2.  some popups is visible from under fingerprint protection layer layer

I found 2 popups visible from under fingerprint protection layer and resend information  popup don't disappear after click new sesion:

resend information and download poup

![obraz](https://user-images.githubusercontent.com/33488334/74113316-c2500d00-4ba3-11ea-91c5-958f5d470fe5.png)
![obraz](https://user-images.githubusercontent.com/33488334/74113390-0e02b680-4ba4-11ea-9cb3-8b2cdb2b0767.png)

and after new sesion

![obraz](https://user-images.githubusercontent.com/33488334/74113414-40acaf00-4ba4-11ea-8bcd-eec4774a5af6.png)

3. settins screen is not protected properly

when I am on settings screen fingerprint protection doesn't occure after minimalization, but after return to browser view appear, but from settings I can disable fingerprint protection

https://mega.nz/#!ZGgGQAyL !rWzyb1wSzsNZd_4bOSGAW6G7tLzKhbqR6ndSKL-E5UI

4. sound is playing when fingerprint protection is present

when i listening music and i minimalize browser and i return to browser i can hear sound from under protection

https://mega.nz/#!cChCWACK !2mlwpZGuwfE-mummAkBgbbiCHzjaflPnOjdgrC8-mmk

All tested on lastest f-droid firefox-klar relase (8.0.15)
on android emulator version Q

**Comment by lobontiumira** [comment]
I can confirm some behaviors from this issue on the latest Focus Nightly build 99.0a1 (360630511 with GV 99.0a1-20220303094735) with Oppo Find X3 Lite (Android 11):
* The fingerprint protection can be skipped if a page is shared from a different app.
* The sound is still on after exiting the app.
* Closing Focus, then switching back to Focus, the active web page will be briefly displayed for a split second (see #5068).

**Comment by lobontiumira** [comment]
Reproducible with Samsung Galaxy Note 8 (Android 9) on Beta 99.0.0-beta.1.

**Comment by lobontiumira** [comment]
I was able to reproduce the following on the Focus Beta 100.0.0-beta.1 with Samsung Galaxy Note 8 (Android 9):
* the sound is still on after exiting the app,
* closing Focus, then switching back to Focus, the active web page will be briefly displayed for a split second (see https://github.com/mozilla-mobile/focus-android/issues/5068).

**Comment by iorgamgabriel** [comment]
@lobontiumira this should be retested FingerPrint behaviour was changes , now we have biometrics

**Comment by lobontiumira** [comment]
Tested on the latest Focus Nightly build 104.0a1 from 7/22 with Oppo Reno 6 (Android 12), and Samsung Galaxy Note 8 (Android 9). Indeed, the fingerprint behavior has been changed.
The fingerprint protection cannot be skipped even when a page is shared from a different app.
However, closing Focus, then opening Focus again, displays briefly the homepage - but #5068 is opened for this issue.

I'll close this ticket.
