### ISSUE TITLE
Autocompleted sites force HTTP

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#4468]
This happens to sites which I've manually added to autocomplete, that allow both HTTP and HTTPS connections. Using Klar 8.0.25.

When I start typing "https://" and enter the link w/o triggering autocomplete, HTTPS version loads. This is what I'd want to happen with autocomplete in all cases where the website supports HTTPS no matter if it also supports HTTP (duh).

When I start typing the domain name and the autocomplete finishes, I get the HTTPS version only if the site disallows HTTP. Klar always connects via HTTP if possible.

Moreover if I start typing the domain name, autocomplete finishes, and I go back and prepend "https://", it **still** loads the HTTP version! It seems it's now impossible to make an autocompleted URL load as HTTPS short of cutting and pasting it from outside the application.

**Comment by zekooooo** [comment]
This security issue is still present as of v8.4.0

**Comment by lobontiumira** [comment]
This is no longer reproducible.
On the latest Focus builds, the HTTP pages are opened as HTTPS.


https://user-images.githubusercontent.com/40694158/156741252-f324e61d-ecc4-43c2-933f-a4600b3024a6.mp4
