### ISSUE TITLE
'blocking remote fonts option' blocks also fonts that exist on the same place

### ISSUE THREAD

**Issue by make-it-really-easy** [mozilla-mobile/focus-android#4469]
When you have turned on 'blocking remote fonts option' it blocks also fonts that exist on the same place with webpage.

Example:

Webpage really caring about your privacy 'startpage.com' has all fonts on the same place 

(
for example :

<link as="font" crossorigin="" href="/assets/fonts/afterall-serif-regular-woff2.woff2?v=86f65f36" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="/assets/fonts/afterall-serif-medium-woff2.woff2?v=f67a64c7" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="/assets/fonts/proximanova-regular-woff2.woff2?v=8bcad4b1" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="/assets/fonts/proximanova-semibold-woff2.woff2?v=5babd914" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="/assets/fonts/proximanova-regularitalic-woff2.woff2?v=c48fa3c3" rel="preload" type="font/woff2"/>
)

but uBlockOrigin blocks them all .

Blocking remote fonts is good for privacy but since it does not working well it spoils webpages that really care about privacy.

Could you fix it?

**Comment by caugner** [comment]
@make-it-really-easy I only find a "Block Web fonts" option in the latest version, which I expect to block all Web fonts, no matter if remote of local. Maybe the old title of this option was just misleading?

**Comment by lobontiumira** [comment]
I'll close this ticket as obsolete.
