### ISSUE TITLE
Many UI Tests are flaky

### ISSUE THREAD

**Issue by yxliang01** [mozilla-mobile/focus-android#4470]
In the latest master, there are many ui tests in https://github.com/mozilla-mobile/focus-android/tree/master/app/src/androidTest/java/org/mozilla/focus are flaky. One source of flakiness identified is the use of `waitFor`* family of method on the uiautomator objects with a relatively small timeout(4 seconds). On a machine(e.g. CI) that is not dedicated to only run the ui tests, these tests can occasionally failed as I've already observed due to the required processing is not done within timeout. The current behavior of timing out during waiting is to continue the execution as usual. This causes the test failure message might not directly show the latency of processing being the cause of failure, making debugging difficult.

I think these tests should either 1) be labelled as flaky via adding `@FlakyTest` annotation to document this behavior in a standard way and put an assert on the `waitFor`* method calls to capture the failure ASAP or 2) wait for events indefinitely, instead of a fixed timeout. I'm happy to file a PR for this if any of these solutions sounds good.

* Android device: any
* Focus version: master

**Comment by sv-ohorvath** [comment]
Some refactoring has been done since this was opened, the 4 seconds waiting time was increased to 15 and we are seeing a lot less flakiness (but still some). I think we can close this and address each issue individually, as we log issues for every failure. Thanks!
