### ISSUE TITLE
multi-touch zoom gesture fails on the map

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4476]
## Steps to reproduce
1. go to https://capap.gugik.gov.pl/mapa/cppc/CPPC-internet/
2. try to zoom in with two fingers. 

### Expected behavior
zoom in the page

### Actual behavior
try to scroll to hide or show the url bar.
(double tap is working)

### Device information

* Android device: pixel 2 android 10
* Focus version: 8.0.25 / 71.0.1-20200108003105

initially reported at https://github.com/webcompat/web-bugs/issues/48781

**Comment by Diana-Rus** [comment]
Hi, I reproduced the issue, but only with the map of the provided site, from step 1, with OnePlus 6T (Android 9) with Firefox Focus 8.0.26 (Build #340521549) GV: 73.0.1 - 20200211134023.

Note:
The issue does not reproduce with:
- https://maps.google.com/
- mapquest.com

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Focus Nightly build from 4/3 using an Oppo Find X3 Lite (Android 11) device.
