### ISSUE TITLE
Make the button movable

### ISSUE THREAD

**Issue by vivalite** [mozilla-mobile/focus-android#4477]
### Why/User Benefit/User Problem
Sometimes the button blocks the content of the website.
Sometimes exit the website accidentally.

### What / Requirements
User able to move the button by hold and drag the button.

### Acceptance Criteria (how do I know when I’m done?)
Drag the button everywhere on the screen. The functionality of the button remains.

**Comment by yuewenma** [comment]
Can I work on this feature, please?

**Comment by lobontiumira** [comment]
I will close this issue as obsolete.
The trash button is on the toolbar on all Focus builds.
Thank you!
