### ISSUE TITLE
[webcompat] menus are not working.

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4479]
## Steps to reproduce
1. with the latest version of Firefox focus
2. go to https://mobile.etam.com/accueil
3. tap on the top left menu
see https://github.com/webcompat/web-bugs/issues/48335

### Expected behavior
menu opens like in Firefox nightly preview

### Actual behavior
menu is not responsive

### Device information

* Android device: 10.0 Pixel 2
* Focus version: Firefox Focus 8.0.25 (🦎 71.0a1-20200108003105)

**Comment by jonalmeida** [comment]
Interestingly, in Preview Nightly it doesn't work in private browsing, only works in regular browsing.

I'm guessing that's relevant since Focus sessions are always private.

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus nightly 99.0a1 (build 360670512 with GV 99.0a1-20220307093830) with Lenovo Tab M10 (Android 10).
