### ISSUE TITLE
[Bug]Find in page-The search bar is not visible in portrait mode only in landscape mode

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4480]
## Steps to reproduce
1. Go to a site with text.
2. Tap on the app's menu.
3. Choose "Find in page" option.
### Expected behavior
The search bar is displayed.
### Actual behavior
The search bar is being overlapped by the virtual keyboard.
### Device information

* Android device: Google Pixel 3XL(Android 9), Samsung Galaxy S8+(Android 8), Sony Xperia Z5 (Android 7)
* Focus version: Firefox Focus 8.1.0 GV: 74.0-20200309095159

Please check GIF:
- Google Pixel 3XL (Android 9):
![20200311-102059](https://user-images.githubusercontent.com/49859863/76397207-5966db00-6383-11ea-9424-3324763ad3e9.gif)
- Samsung Galaxy S8+ (Android 8)
![20200311-103725](https://user-images.githubusercontent.com/49859863/76398296-510f9f80-6385-11ea-92c9-d23ded8ac428.gif)

Note: Seems to be a device specific issue as with Samsung Galaxy S8+(Android 8) and Sony Xperia Z5 (Android 7) it does not reproduce.
- In video i used as testing site wikipedia.com but the same outcome is present for other ones, imdb.com,, planet.mozilla.org.
- On Firefox Preview Nightly 200311 (Build #20710604) GV: 75.0a1-20200309091841 the issue does not reproduce with Google Pixel 3 XL (Android 9)

**Comment by Diana-Rus** [comment]
Hi, issue still reproduces with Google Pixel 3XL(Android 9) on Focus: 8.2.0 with GV 75.0-20200403170909.

**Comment by goforbg** [comment]
This bug is driving me insane, anyone else working on this?

**Comment by Diana-Rus** [comment]
Hi, i can still reproduce the issue with Focus 8.4.0 and GV: GV 77.0.20200602142841 with Google pixel 3 XL (Android 9).
@goforbg , i'm going to relate this ticket to #4531 as I think after it's worked on the related ticket, this one should be solved.

**Comment by goforbg** [comment]
@Diana-Rus Yeah hoping so!

**Comment by partha2000** [comment]
This issue is reproducible on my device as well.
Device: Xiaomi Redmi Note 7 Pro (Android 9)

**Comment by partha2000** [comment]
@Diana-Rus This problem was common with devices of screen size around 6.2 inches.
So I made this PR #4560 which solves the issue.

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Focus 8.12.0 with Motorola Moto G6 (Android 8).

**Comment by lobontiumira** [comment]
This is reproducible on Xiaomi Mi 8 Lite (Android 9), on 8.17.1 build.

**Comment by lobontiumira** [comment]
This issue no longer reproduces in the 8.18.0-rc.1 build.
I'll close this issue.
