### ISSUE TITLE
some media contents and GIF pictures aren't played automatically

### ISSUE THREAD

**Issue by tmdwns7809** [mozilla-mobile/focus-android#4484]
## Steps to reproduce
Open these sites
https://www.fmkorea.com/best/2825628999

https://gall.dcinside.com/board/view/?id=football_new6&no=6808084&s_type=search_all&s_keyword=gif&page=1

### Expected behavior
the media contents in those sites are automatically played in other browsers and 
it was played automatically even in firefox focus old version

### Actual behavior
at some point it doesn't get autoplayed anymore, and in the 2nd web site the gif picture is just dark before i long press the picture.

### Device information
Samsung Galaxy Note 9 SM-N960

* Android device: SM-N960
* Focus version: 8.1.0 focus

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly build from 3/8 with Samsung Galaxy Note 8 (Android 9), nor with Google Pixel (Android 10).
Thank you for the report!
