### ISSUE TITLE
Single Tab Sharing Not possible

### ISSUE THREAD

**Issue by khunsha965** [mozilla-mobile/focus-android#4493]
## Steps to reproduce
1- Open multiple tabs 
2-Try sharing the tabs with someone.

Note:Happens both with Collections as well as Open Tabs

### Expected behavior
User gets the option to select tab he/she wants to share.

### Actual behavior
No option to select desired tab rather shares the oldest tab opened.

### Device information
Phone: Xiamo Android Phone

* Android device: Yes
* Focus version: 4.1.0

**Comment by cadeyrn** [comment]
You're in the wrong issues tracker. Fenix has a version 4.1.0, the current Focus version is 8.1.0. And there is no collections feauture in Focus.

Fenix issues tracker:
https://github.com/mozilla-mobile/fenix/issues

**Comment by lobontiumira** [comment]
Closing as invalid.
Thank you!
