### ISSUE TITLE
Logo  Size

### ISSUE THREAD

**Issue by khunsha965** [mozilla-mobile/focus-android#4494]
### Why/User Benefit/User Problem
As a user,the minute i opened the app i felt slightly discomforted by how much area the logo was occupying on the screen and how the space can utilized for far better use.

### What / Requirements
I would recommend reducing the size of the logo as well as moving it to the top which can create space for adding more valuable tabs or maybe sharing latest new or other important stuff.

### Acceptance Criteria (how do I know when I’m done?)
When the size of logo feels proportional to other visual elements on the screen

**Comment by cadeyrn** [comment]
The logo on the Focus start screen is not really big so I guess you are - as with your other issue - in the wrong issues tracker and this was meant to be a Fenix issue.

Fenix issues tracker:
https://github.com/mozilla-mobile/fenix/issues

There is already an issue filed for this request:
https://github.com/mozilla-mobile/fenix/issues/8275

**Comment by Diana-Rus** [comment]
Hi, yes it seems like the ticket is related to Fenix, please monitor the issue mentioned by @cadeyrn .
Note:  I think that on the latest firefox nightly the logo and writing have been resized, saw it Firefox Preview Nightly 4/8 .
Ticket will be closed.
