### ISSUE TITLE
USB debugging stops working when returning to web content

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4497]
## Steps to reproduce
1. Open Focus and plug into computer.
1. Open web content.
1. Go to `about:debugging` on desktop. Verify that no device is there.
2. Go into app settings and turn USB debugging on.
2. Observe desktop.
2. Inspect a web page.
2. Press the system back buttons to go back to the web content.
3. Observe desktop.

### Expected behavior
- At 5, you should see Focus show up there for debugging.
- At 8, you should continue to see Focus show up there for debugging.

### Actual behavior
- At 5, you see Focus show up there for debugging.
- At 8, you **no longer** see Focus show up there for debugging.

### Device information

* Android device: Android 10, Pixel 4
* Focus version: 8.1.0 and 8.1.1

**Comment by repkam09** [comment]
I believe I'm having the same issue, running Firefox 79.0 (64-bit) on Ubuntu 20.04, attempting to debug a webpage on my OnePlus 7 Pro running Firefox Focus version 8.5.1 (Build #341921932 🦎 78.0.2-20200708170202) on Android 10.

The Firefox debugger shows a USB connection to my device, but only when my phone is actually displaying the Advanced Developer Tools settings menu, with the Remote Debugging toggle on. As soon as I press 'back' to return to the main web content to view my webpage, the debugger disconnects. 

I am able to debug the same webpage from the normal Firefox Mobile browser v 68.11.0, but the issue I am trying to debug seems to only happen on Firefox Focus.

**Comment by jonalmeida** [comment]
Closing in place of https://github.com/mozilla-mobile/focus-android/issues/5875 because the settings page was re-written.
