### ISSUE TITLE
Fallback Web Share links on youtube no longer work

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4498]
## Steps to reproduce
1. Open youtube.com
2. Go to a video and click the share button.

### Expected behavior
 - You should see the YouTube fallback 'share' dialog (since Focus does not implement the Share API on GV). See screenshot below.

### Actual behavior
 - No changes take place.

Expected fallback dialog.
<img width="521" alt="Screen Shot 2020-04-03 at 4 43 00 PM" src="https://user-images.githubusercontent.com/1370580/78403388-46ce7300-75ca-11ea-8ed0-8295342928be.png">

### Device information

* Android device: Android 10, Pixel 4
* Focus version: 8.1.0 and 8.1.1

**Comment by jonalmeida** [comment]
I suspect this regressed because we have native support for handling share requests, but the [GV default share handler](https://searchfox.org/mozilla-central/rev/064b0f9501ad76802853b43f18e33d8713fd54d3/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSession.java#4917-4921) drops the share request.

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly build from 3/8.
I'll close it.
Thank you!
