### ISSUE TITLE
Unable to change the language to English from Arabic

### ISSUE THREAD

**Issue by BMUZAMMIL** [mozilla-mobile/focus-android#4499]
I am uninstalling it, I'll be using Firefox.
I hope this is fixed soon as possible. 
I turned off all options in settings, all blockers etc and still language didn't change.
Device: Galaxy Note 8
Location: Karachi, Pakistan. 
Common languages in Pakistan: Urdu, but mainly English. 

![Screenshot_20200404-141240_Firefox Focus](https://user-images.githubusercontent.com/7937231/78423296-d5043100-767e-11ea-8939-0080f03315d9.jpg)

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus builds.
I'll close this ticket.
Thank you!
