### ISSUE TITLE
Custom Tabs - The site does not always open in custom mode it opens in browser app

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4500]
## Steps to reproduce
1. Set Focus as default browser.
2. Go to Gmail, tap a link from an email.

### Expected behavior
The custom tab should open with the link.
### Actual behavior
The site opens through browser app.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Focus version: Focus 8.1.1 (Build #340941926) GV:74.0.1-20200403064753

**Comment by Diana-Rus** [comment]
Hi this issue seems related to:
- https://github.com/mozilla-mobile/fenix/issues/1767

**Comment by ebalazs-sv** [comment]
This is reproducible on Focus 8.2.0 (Build #340992215) GV 75.0.20200403170909 with Pixel 2 (Android 9).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Focus 8.3.0 (Build #341281936) GV 76.0.20200429185419 with Pixel 2 (Android 9).

**Comment by Diana-Rus** [comment]
Reproducible with Sony Xperia Z5 (Android 7) on Firefox Focus version 8.5.0 GV 78.

**Comment by Diana-Rus** [comment]
Reproducible with Samsung Galaxy S9 (Android 8) on Firefox Focus version 8.6.0 GV: 79

**Comment by lobontiumira** [comment]
I did not encounter this issue on the recently builds.
Verified again on the latest Focus nightly 99.0 from 2/23 with multiple websites, with Samsung Galaxy Note 8 (Android 9), Google Pixel (Android 10), and Oppo Find X3 Lite (Android 11).
