### ISSUE TITLE
connector.eidas.swedenconnect.se - site is not usable

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [mozilla-mobile/focus-android#4501]
First reported here: https://github.com/webcompat/web-bugs/issues/47731

URL: https://connector.eidas.swedenconnect.se/idp/extauth/saml2/post

Browser / Version: Firefox Mobile 71.0
Operating System: Android 8.0.0
Tested Another Browser: Yes

Problem type: Site is not usable
Description: Authentificaton with e-id is lost
Steps to Reproduce:
Open skatteverket.se > Log in > Foreign e-id > Germany > page with instructions > open link with AusweisApp2 > successfull authentification in AusweisApp2 > redirect to Firefox Klar > error massage occurs. Checked in Firefox, there it works fine. Checked also with different cookie settings, but the problem still occurs in Firefox Klar. (Firefox Klar is the same as Firefox Focus.)

**Comment by lobontiumira** [comment]
This issue cannot be tested due to the lack of valid credentials.
I will close this ticket as obsolete.
