### ISSUE TITLE
some media contents and GIF pictures aren't played automatically

### ISSUE THREAD

**Issue by tmdwns7809** [mozilla-mobile/focus-android#4504]
Open these sites
https://www.fmkorea.com/best/2825628999

https://gall.dcinside.com/board/view/?id=football_new6&no=6808084&s_type=search_all&s_keyword=gif&page=1

Expected behavior
the media contents in those sites are automatically played in other browsers and
it was played automatically even in firefox focus old version

Actual behavior
at some point it doesn't get autoplayed anymore, and in the 2nd web site the gif picture is just dark before i long press the picture.

Device information
Samsung Galaxy Note 9 SM-N960

Android device: SM-N960
Focus version: 8.1.0 focus

**Comment by Diana-Rus** [comment]
Hi, I can reproduce the issue described with Sony Xperia Z5 (Android 7) on Firefox Focus 8.2.0 (Build ID: 340992214) and GV: GV 75.0-20200403170909.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Focus 8.15.3 GV 88 with Huawei P9 Lite (Android 7).

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly build from 3/8 using a Google Pixel (Android 10), nor with Samsung Galaxy Note 8 (Android 9).
