### ISSUE TITLE
The "Erase browsing history" button is not visible in landscape mode when more than 3 tabs are open

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4507]
## Steps to reproduce
1. Launch Firefox Focus;
2. Open 4 tabs;
3. Tap the opened tabs;
4. Rotate the device in landscape mode;
### Expected behavior
The "Erase browsing history" button is visible in landscape mode.
### Actual behavior
The "Erase browsing history" button is not visible in landscape mode.
### Notes
[Video](https://drive.google.com/open?id=1I1srqoWnRrnDoPcTxEtpOkvP5AO5gAQH)
This is also reproducible when tapping the opened tabs from landscape mode.
Not reproducible with 1, 2 or 3 opened tabs.

### Device information

* Android device: Pixel 2 (Android 9); Sony Xperia Z5 (Android 7)
* Focus version: Focus: 8.2.0 Build ID: 340992215 GV 75.0.20200403170909

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Focus 8.3.0 (Build #341281936) GV 76.0.20200429185419 with Pixel 2 (Android 9).

**Comment by partha2000** [comment]
@ebalazs-sv This issue is not reproducible in my device using Firefox-Focus 8.3.0 (build #11 76.0-20200429185419)
I guess if you scroll down on the tabs menu then the "Erase browsing history" button will be visible in landscape mode as well.

- Android Device: Xiaomi Redmi Note 7 Pro (Android 9)

**Comment by ebalazs-sv** [comment]
Scrolling down the tabs menu will make the "Erase browsing history" button visible in portrait and landscape mode.

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on Focus latest builds.
I'll close this issue.
