### ISSUE TITLE
FF Klar has "Send usage data" enabled by default

### ISSUE THREAD

**Issue by KevCui** [mozilla-mobile/focus-android#4510]
## Steps to reproduce

- Fresh install FF Klar (Klar not Focus) OR Clear storage of installed FF Klar app
- Open FF Klar -> Top right menu -> Settings -> Privacy & Security
- Scroll down to bottom, the option "Send usage data" is enabled

### Expected behavior

As far as I know, "Send usage data" should be disabled for FF Klar by default.

### Actual behavior

 "Send usage data" is enabled for FF Klar by default.

### Version information

Android app downloaded from Play Store, FF Klar version 8.1.1

**Comment by Meenohara** [comment]
Hi can I take this up?

P.S. I am still new to open source code so do not know what "Successfully merging a pull request may close this issue" means

**Comment by licaon-kter** [comment]
Seeing this in 8.4.0 F-Droid too :(

**Comment by licaon-kter** [comment]
@KevCui Where din you install Klar from?

**Comment by KevCui** [comment]
@licaon-kter from Google Play Store

**Comment by licaon-kter** [comment]
@jonalmeida Ping?

**Comment by jonalmeida** [comment]
Thanks for filing this! I think I found the cause of the problem, a fix should be in for the next release.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Focus Klar 8.7.1 GV 80.0 from 8/21 with Pixel 2 (Android 9).
The "Send usage data" is disabled by default.
I will close this issue.
