### ISSUE TITLE
A Flaky Test in org.mozilla.focus.activity.SwitchLocaleTest due to configuration issue

### ISSUE THREAD

**Issue by mig40000** [mozilla-mobile/focus-android#4514]
FrenchLocaleTest in the SwitchLocaleTest (org.mozilla.focus.activity) is a flaky test. The reason for this is that if the Language of the Firefox Debug app is set to anything other than “System Default” (The very first option in the Language selection list), changeLocale(String locale) method fails to change the input locale. This phenomenon is 100% reproducible, i.e., it fails all the time. It can be made to pass in the following two circumstances:

1. Run after the EnglishSystemLocaleTest. In the EnglishSystemLocaleTest, A UIObject to select “System default” language is created. Once this test is completed, the @After method tries to change the locale to “en” by invoking changeLocale("en”). However, as the “System default” option is previously checked, it does not select the English (United States) option. Please note that “System Default” is a separate item, the very first element in the Language selection list. There is a separate item, English (United States). I am attaching these two options' screenshot to avoid any confusion. 

2. Change the app language manually to “System Default” and run the test. The test will pass. However, you would need to change this every time you run the test. The reason is this time when the After method tries to change the locale to “en” by invoking changeLocale("en”), it changes to English (United States) as the previous language was set to French.

* Android emulator: Pixel 2, API 28
* Focus version: master Branch
![Screenshot_1588851281](https://user-images.githubusercontent.com/19606918/81291239-fef4ad00-909b-11ea-9d1d-4d44d33573d8.png)
![Screenshot_1588851291](https://user-images.githubusercontent.com/19606918/81291245-00be7080-909c-11ea-9bce-794645864393.png)

**Comment by lobontiumira** [comment]
Thank you for the report @mig40000 
Could you retest, and comment if this issue is reproducible on the latest Focus?

**Comment by lobontiumira** [comment]
I will close this ticket, since there is no response from the reporter.
