### ISSUE TITLE
Whe i click on dropdown it's open previous link

### ISSUE THREAD

**Issue by jigs1996** [mozilla-mobile/focus-android#4519]
## Steps to reproduce
1) open https://vave.io
2) open menu from top right burger icon
3) click on "EXPLORE VAVE"

### Expected behavior
 - It's redirect to "START A REAL ESTATE CAREER".
### Actual behavior
 - it suppose to open sub menu.

![photo_2020-05-20_13-15-52](https://user-images.githubusercontent.com/28808327/82419451-12d8df80-9a9c-11ea-9800-60d9aac5eb44.jpg)

### Device information

* Android device: Nokia  6.1
* Focus version: 8.3.0

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest builds.
I'll close this ticket.
