### ISSUE TITLE
Audio keeps playing in background on ndr.de

### ISSUE THREAD

**Issue by pohuing** [mozilla-mobile/focus-android#4522]
## Steps to reproduce
Open a radio stream on ndr.de
Open a second tab by long pressing on the play button
Clear history
Demo(Audio Warning): https://drive.google.com/file/d/1x7PMzlgc6A8olJp7qRlFqO67UIBRsA2m/view
### Expected behavior
Audio should stop
### Actual behavior
Audio continues playing until FF Focus is closed via the task switcher
### Device information
OnePlus 2 using LineageOS 16.0-20200426-NIGHTLY-oneplus2
Android 9
* Android device: Yes
* Focus version: 8.3.0 Build #341281936
### Additional notes:
This looks similar to #3528

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly build 99.0a1 (360670512 with GV 99.0a1-20220307093830).
Tested with Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9).
