### ISSUE TITLE
Make sure Focus uses GeckoViewFetchClient

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#4528]
If we use client implementations anywhere then it should be GeckoViewFetchClient.

**Comment by jonalmeida** [comment]
[`SearchSuggestionsFetcher`](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsFetcher.kt#L34) is the only usage of OkHttpClient.

HttpUrlConnection is used in a few places:
 - [`TelemetryWrapper`](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt#L267) is using it when constructing a `TelemetryClient`.
 - [`ManualAddSearchEngineSettingsFragment`](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt#L190) is used to validate new search engines when added.
 - [`HostScreencapScreenshotStrategy`](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/androidTest/java/org/mozilla/focus/helpers/HostScreencapScreenshotStrategy.java) is an unused test.
