### ISSUE TITLE
Integrate browser-toolbar component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#4530]
Using `browser-toolbar` component to share toolbar implementation with Fenix.

- [x] Display Toolbar Look&Feel
- [x] Edit Toolbar Look & Feel
- [x] Custom Tabs Look & Feel
- [x] Fullscreen behavior
- [x] Remove legacy views & code
- [x] Tablet toolbar
- [x] Menu button
- [x] UI tests
- [x] Lock icon click

**Comment by jonalmeida** [comment]
Based on current usage of the selected session in the BrowserFragment, we may need to fix this: to use the toolbar: https://github.com/mozilla-mobile/android-components/issues/7087

**Comment by pocmo** [comment]
I almost think we should skip doing this: In RB I want soon start some Jetpack Compose prototyping. Eventually we may have a toolbar component using Jetpack Compose - and Focus would be a good target for that. So I am wondering if it's even worth to migrate to `browser-toolbar` here. I'd only do it if this unlocks something that is otherwise too hard to do.

**Comment by jonalmeida** [comment]
Do you think it would be useful for addons that use page actions?

Alternatively, we could re-think where those page actions go in Focus (maybe keep them in the menu)?

**Comment by pocmo** [comment]
> Do you think it would be useful for addons that use page actions?

Good point. If we want add-ons soonish then that could be worth it.

> Alternatively, we could re-think where those page actions go in Focus (maybe keep them in the menu)?

Yeah, that may be worth investigating once the time comes.

**Comment by pocmo** [comment]
This seems worthwhile now that we need to share more toolbar functionality with Fenix. Started working on this in #4951
