### ISSUE TITLE
Integrate Glean engine telemetry

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4545]
The deprecated telemetry API in GV will be removed in GV 79. We should switch over to using the GleanAdapter and connect those pieces together before that.

See for the entry point: https://github.com/mozilla-mobile/reference-browser/blob/d1792daf0c2cb554b400495d3ebe1b218b56de05/app/src/main/java/org/mozilla/reference/browser/EngineProvider.kt#L34

**Comment by Dexterp37** [comment]
@jonalmeida I'd recommend doing the full Glean integration here, if possible.

**Comment by jonalmeida** [comment]
Note for self: identify how to test that our telemetry is reporting as it currently does.

**Comment by jonalmeida** [comment]
I spent some time today looking into what the effort would be like and what the most minimal changes would be, and I don't see any easy way around upgrading without the updating to use the AC engine from the integration branch.

**Comment by jonalmeida** [comment]
> the service-telemetry component will be removed from Android Components on Friday September 11th, 2020.

This will not affect us since we have disabled telemetry until we migrate to Glean.
