### ISSUE TITLE
Make sure custom tabs are still behaving as intended

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#4547]
URLs opening in custom tabs, styling getting applied, ..

**Comment by jonalmeida** [comment]
I checked all the different types of supported Custom Tab configs and everything seems to be working fine. The only bug I ran into was a top crasher that we needed to get fixed either way (unrelated to this AC integration): https://github.com/mozilla-mobile/focus-android/pull/4575
