### ISSUE TITLE
8.4.0 no APKs

### ISSUE THREAD

**Issue by rfc2822** [mozilla-mobile/focus-android#4548]
On https://github.com/mozilla-mobile/focus-android, there's a download link "Download APKs" which leads to the Releases page: https://github.com/mozilla-mobile/focus-android/releases

There, 8.4.0 has no APKs (but other versions have).

Have the APKs moved? Where can one get them?

**Comment by cadeyrn** [comment]
The APKs get usually released once the rollout via Google Play Store reached 100 percent. And since I didn't receive the update yet 100 percent are not yet reached.

**Comment by rfc2822** [comment]
I see, thanks!
