### ISSUE TITLE
Desktop version not available for news.google.com

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4554]
## Steps to reproduce
1. Open app and go to news.google.com
2. Tap on the 3 dot menu and tap on the "Request desktop site".
### Expected behavior
The desktop mode for the site is displayed.
### Actual behavior
The site remains in mobile mode.
### Device information

* Android device: Google Pixel 3 XL (Android 9)
* Focus version: Focus: 8.4.0 with GV: 77.0.20200602142841

Note: 
- In case of adding to home screen news.google.com, after having for it enabled and disabled desktop mode, when opened from the homescreen about:blank page is present. 
- In case you make a refresh of the page(news.google.com) after enabling the  request desktop site option, the desktop mode of the site is present.
- This situation i only encounter it with news.google.com with you tube this does not happen

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the latest Focus builds.
Closing as obsolete.
