### ISSUE TITLE
A11y-The entire information from the active panel is read after tapping on the next button

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4556]
## Prerequisites:
- Have a clean profile
- Have talk back enabled
### Steps to reproduce
1. Open app.
2. Tap on the "Next" button from "Power up your privacy" panel.
### Expected behavior
The "Next" text is read.
### Actual behavior
After the next text is read the entire information from the panel will be read.
### Device information

* Android device: Google Pixel 3 XL (Android 9)
* Focus version: Focus 8.3.0 GV: 77 .0.20200602142841

Note:
- This happens for all panels

**Comment by Diana-Rus** [comment]
Closing for: https://github.com/mozilla-mobile/focus-android/issues/4277

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the Focus nightly build from 2/23.
After tapping on the "Nezt" option, the next board was read as "Next. 2 of 4.".
