### ISSUE TITLE
[A11y] Extra information when user is present on the "Search or enter address"

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4557]
## Prerequisites:
- Have a clean profile for the app
- Have talkback enabled.
### Steps to reproduce
1. Open app and skip through all the panels.
### Expected behavior
The talk back reads "Search or enter address" but adds "showing italian italy qwerty keyboard".
### Actual behavior
The talk back reads only text: "Search or enter address"
### Device information

* Android device: Google Pixel 3 XL (Android 9)
* Focus version: Focus 8.4.0 GV: 77.0.20200602142841

**Comment by lobontiumira** [comment]
This issue is still reproducible on Focus Nightly build 99 from 2/23 with Oppo Find X3 Lite (Android 11).

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the latest Focus Nightly 101.0a1 build from 4/14.
Tested with Samsung Galaxy Note 8 (Android 9), Lenovo Tab M10 (Android 10), and Oppo Find X3 Lite (Android 11).
