### ISSUE TITLE
Crash when re-entering Firefox Focus

### ISSUE THREAD

**Issue by sincostandx** [mozilla-mobile/focus-android#4559]
## Steps to reproduce

- In a newly installed Firefox Focus, open a random webpage.
- After the page is loaded, scroll the page by a random amount.
- Press the Home button
- Re-enter Firefox Focus by the icon on the home screen

### Expected behavior

Firefox Focus can continue respond to touch events.

### Actual behavior

Not responding to any touch event and crashes in about 5 seconds.

### Device information

* Android device: Huawei Mate 9 MHA-AL00 (Android 9, EMUI 9.1.0)
* Focus version: 8.4.0 from Google Play 

(This issue is not new in 8.4.0, but I did not take a note on the first version I encounter this issue. It is probably the previous release on Google Play)

**Comment by lobontiumira** [comment]
I am not able to reproduce this issue on the latest Focus Nightly from 3/8.
Tested with several devices: Oppo Find X3 Lite (Android 11), Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9).
