### ISSUE TITLE
Insecure connection bypass depends on Javascript

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#4567]
When loading a page which has HTTPS errors I'm given the usual Insecure Connection screen. If Javascript is disabled, the screen is a dead end. However if Javascript is enabled there's an extra "Advanced" button and I'm given the option to "Accept risk and continue".

If one is accessing a site that throws a security red flag it makes no sense to force the user to expose oneself to danger by turning on Javascript. If anything the options should be the other way around.

To make it clear: the accept risk and continue dialog should be accessible with Javascript turned off. 

Using Klar 8.4.0 on Android 7

**Comment by Nickoriginal** [comment]
Still reproducible in Focus/Klar 8.16.0. To resolve it, Focus developers can always keep JavaScript enabled for those prompt and notification pages (like [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1673237)), not exposing user data for page content. But, if it possible, it's better to remake these pages to work without JavaScript.

**Comment by Nickoriginal** [comment]
Fenix issue: https://github.com/mozilla-mobile/fenix/issues/20213

**Comment by Nickoriginal** [comment]
Still is the problem on Focus
