### ISSUE TITLE
Add Quick Toggle for turning off/on JavaScript to the main menu

### ISSUE THREAD

**Issue by moocow1452** [mozilla-mobile/focus-android#4574]
### Why/User Benefit/User Problem
Going into the menus to turn off and on JavaScript as needed is a common toggle, and is rather tedious to go through as of now.

### What / Requirements
Make turning off and on JavaScript an option directly under the three circle menu, as opposed to buried under three levels of settings.

### Acceptance Criteria (how do I know when I’m done?)
When the quick toggle option is available.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802030

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
