### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void android.widget.Editor$SelectionStartHandleView.showAtLocation(int)' on a null object reference

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#458]
```
0	android​.widget	
Editor.java ​ Line 4882
Editor$SelectionModifierCursorController.onTouchEvent
	
1	android​.widget	
Editor.java ​ Line 1224
Editor.onTouchEvent
	
2	android​.widget	
TextView.java ​ Line 8305
TextView.onTouchEvent
	
3	android​.view	
View.java ​ Line 9297
View.dispatchTouchEvent
	
4	android​.view	
ViewGroup.java ​ Line 2555
ViewGroup.dispatchTransformedTouchEvent
	
5	android​.view	
ViewGroup.java ​ Line 2254
ViewGroup.dispatchTouchEvent
	
6	android​.view	
ViewGroup.java ​ Line 2555
ViewGroup.dispatchTransformedTouchEvent
	
7	android​.view	
ViewGroup.java ​ Line 2254
ViewGroup.dispatchTouchEvent
	
8	android​.view	
ViewGroup.java ​ Line 2555
ViewGroup.dispatchTransformedTouchEvent
	
9	android​.view	
ViewGroup.java ​ Line 2254
ViewGroup.dispatchTouchEvent
	
10	android​.view	
ViewGroup.java ​ Line 2555
ViewGroup.dispatchTransformedTouchEvent
```

[View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/9cff5d974d5852b07892f90d24487f7b)

**Comment by ahunt** [comment]
The entire crash stack is Android code : /.

**Comment by ahunt** [comment]
Looks like something that can happen on Android 6, only but that code doesn't seem to exist on Android 5 or 7:
http://androidxref.com/6.0.1_r10/xref/frameworks/base/core/java/android/widget/Editor.java#4866

**Comment by ahunt** [comment]
Similar issue in signal:
https://github.com/WhisperSystems/Signal-Android/issues/6170

And a google issue with nothing beyond crash reports:
https://code.google.com/p/android/issues/detail?id=201921

And of course there's plenty of those in Fennec:
https://crash-stats.mozilla.com/signature/?signature=java.lang.NullPointerException%3A%20Attempt%20to%20invoke%20virtual%20method%20%27%27void%20android.widget.Editor%24SelectionStartHandleView.showAtLocation%28int%29%27%27%20on%20a%20null%20object%20reference%20at%20android.widget.Editor%24SelectionModifierCursorController.onTouchEvent%28Editor.java%29&date=%3E%3D2017-04-06T21%3A51%3A00.000Z&date=%3C2017-04-13T21%3A51%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_sort=-date&page=1#reports

**Comment by ahunt** [comment]
I filed a Fennec bug too. It's far away from the top-crash page, so I'm guessing this is unlikely to happen much - but we can still add a workaround:
https://bugzilla.mozilla.org/show_bug.cgi?id=1356418
