### ISSUE TITLE
Can quick add custom autocomplete URL even when autocomplete is off

### ISSUE THREAD

**Issue by dovej** [mozilla-mobile/focus-android#4580]
## Steps to reproduce

Disable URL autocomplete in settings. Navigate to a site. Click URL bar. "Add link to autocomplete" is displayed. Click "Add link to autocomplete". Custom URL is saved. URL appears in "Manage sites" list (which is only accessible after enabling autocomplete).

### Expected behavior

When autocomplete is turned off in settings, "Add link to autocomplete" should not appear.

* Focus version: 8.4.0

**Comment by JenniferJohnson89** [comment]
I noticed that there is a similar problem at https://github.com/MozillaReality/FirefoxReality. Perhaps we can refer to https://github.com/MozillaReality/FirefoxReality/issues/1857 to find more context about the bug. 
Or maybe this can help us find the faulty lines and we can also refer to the https://github.com/MozillaReality/FirefoxReality/pull/3551 for the bug?

**Comment by lobontiumira** [comment]
This ticket is obsolete since the "Add link to autocomplete" option is no longer available in the current Focus builds.
Closing.
