### ISSUE TITLE
Tabs changing to about:blank after minimizing app

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#4584]
After updating to 8.4.0 recently I started seeing this problem with Klar.

When I have more than a few tabs opened (say 3-4), I can change to another app for a couple minutes or more, and when I change back many tabs remain listed, but when I switch to them, they change to about:blank, and clicking Back closes the tab - there is no way to get the original page that was opened in that tab. The old title of this tab in the list of tabs is also often replaced by "about:blank" when I switch to this tab.

The more tabs I have open, the more often this issue occurs and the more tabs are affected.

Using Klar v8.4.0, build #341610025 77.0-20200602142841 on Android 7.0

**Comment by zekooooo** [comment]
It seems this happens more often when I turn on wifi/network and open up Klar and let the page try to load before the phone has finished connecting to the Internet.

**Comment by zekooooo** [comment]
On 8.5.1 now, pretty sure now this happens if and only if Klar is minimized with internet on and then opened with internet off.

**Comment by infinitewaveparticle** [comment]
I also have noticed this exact same issue with both Klar and Focus for months. It has gotten a little better in that now it doesn't happen as often... but it still does occur. I notice it most the more tabs are open or the longer I go without the app in the foreground. Disabling Android's battery optimization for the browsers doesn't help. I will also add that sometimes the correct address is shown in the address bar, but the website is displayed as just a black screen. Attempting to navigate results in the address switching to a white about:blank page.

**Comment by infinitewaveparticle** [comment]
#4439 & #4463 - earlier reports of this same bug

**Comment by infinitewaveparticle** [comment]
Out of curiosity how many developers are actually working on fixing Firefox Focus bugs? This has been a bug for a very long time without anyone even acknowledging it. Perhaps Mozilla needs to either hire more people or just kill several apps because it seems ridiculous to have to wait for 6-12 months for a critical bug fix from a company as large as Mozilla.

**Comment by cadeyrn** [comment]
> Perhaps Mozilla needs to either hire more people

This will probably not happen in the near term:
https://blog.mozilla.org/blog/2020/08/11/changing-world-changing-mozilla/

**Comment by zekooooo** [comment]
I can confirm the black screen version too. Sometimes the empty screen is black, sometimes white. Usually it initially displays the original URL in the address bar, but occasionally it already just shows about:blank. Anyway once it happens the whole session is gone irretrievably, nothing to do other than erase and start over.

One workaround that seems to never fail is to never disconnect while browsing multitabbed on Focus/Klar. It seems disconnections/reconnections and/or reopening Klar while offline causes this.

**Comment by lobontiumira** [comment]
I did not encounter this issue on the latest Focus builds.
I'll close this ticket.

@zekooooo thank you for the report!
Feel free to file a new ticket if you see meet this behavior again.

**Comment by cadeyrn** [comment]
>  instead of following some idiot at the top of your organization who has no idea what people actually want

And how exactly does it help to offend other people?
