### ISSUE TITLE
add WebAuthn (FIDO2) support to Firefox Klar / Focus

### ISSUE THREAD

**Issue by h1618** [mozilla-mobile/focus-android#4585]
## Steps to reproduce
visit webauthn.io and find: Oh no! This Browser doesn't currently support WebAuthn!

### Expected behavior
WebAuthn just works (note that Fennec already supports webauthn - since 68.0)

### Actual behavior
it throws an error (see above)

### Device information

* Android device: Xiaomi Redmi Note 3 Pro, crDroid 6.1 (Android 10)
* Focus version: 8.5.0 (78.0.20200625152958)

**Comment by lobontiumira** [comment]
This is no longer reproducible on the latest Focus Nightly build 100.0a1 from 3/18 with Lenovo tablet M10 (Android 10), nor with Samsung Galaxy Note 8 (Android 9).
Thank you for the report!
