### ISSUE TITLE
Search bar won't accept an URL containing a colon

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#4587]
When I input an URL that contains a colon, but omit the protocol ("https://"), for example: `en.wikipedia.org/wiki/Dracula:_Dead_and_Loving_It`, pressing Enter doesn't do anything.

If the URL doesn't contain a : outside the protocol and/or I've input the protocol, the page is normally loaded.

Using Klar 8.4.0 on Android 7.

**Comment by lobontiumira** [comment]
I can confirm this issue, with a minor difference.
After tapping enter for the en.wikipedia.org/wiki/Dracula:_Dead_and_Loving_It page, the "Open in app" prompt is displayed.
Tapping on Cancel, or Open just dismisses the prompt, and turns the page blank.

![colon](https://user-images.githubusercontent.com/40694158/158985007-777cbd83-5859-4026-9ded-524feca48e05.png)

Tested on the latest Focus Nightly 100.0a1 from 3/18 with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
This issue still reproduces on the latest Focus Nightly 104.0a1 from 7/13 with Oppo Reno 6 (Android 12).
After loading en.wikipedia.org/wiki/Dracula:_Dead_and_Loving_It page, the "Open in app" prompt is displayed.
Tapping on Cancel, or Open just dismisses the prompt, and turns the page blank.

**Comment by ionutbedregeanu** [comment]
Both apps(Fenix and Focus) add a new tab with url = en.wikipedia.org/wiki/Dracula:_Dead_and_Loving_It but the request interceptor receives a diferent value. Fenix receives the url formatted with "https" while Focus receives the url without any changes.Maybe someone else, which has more context, can also take a look.

**Comment by ionutbedregeanu** [comment]
`override fun interceptsAppInitiatedRequests()` - Thats the difference between Focus and Fenix and that cause this behaviour from Focus
In Focus is true and in Fenix is false(default value), but I'm reading the documentation and I'm a bit confuse. Shouldn't be also true in Fenix?
@jonalmeida Can you help me with this? Do you have more details?

**Comment by mcarare** [comment]
This should be rechecked after https://github.com/mozilla-mobile/focus-android/issues/7777 is fixed, looking at the last [STR](https://github.com/mozilla-mobile/focus-android/issues/4587#issuecomment-1182972323) it seems to be the same as in #7777.

**Comment by Mugurell** [comment]
> Looks like this requires some changes from the GeckoView side. I'll take this issue and work on the GeckoView change.

Maybe you saw already, the difference between Fenix and Focus, why this works on Fenix and not on Focus is again [interceptsAppInitiatedRequests() = true ](https://github.com/mozilla-mobile/focus-android/blob/2407357cfaf3b5f2f21861d9953a6b2b6cb29342/app/src/main/java/org/mozilla/focus/engine/AppContentInterceptor.kt#L89) - on Fenix it is by default `false`.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802666

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
