### ISSUE TITLE
Figure out how to get the app translated

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#46]
We need to somehow get the app translated by our translators. Figure out how.

**Comment by pocmo** [comment]
@flodolo, @Delphine: Do you or the community have any preferences here? Do we need to support any specific tools or file formats? To be honest I have been quite ignorant because with Fennec everything happens magically in the background. :)

**Comment by flodolo** [comment]
Definitely need to support Pontoon, possibly Pootle
https://pontoon.mozilla.org/
https://mozilla.locamotion.org/

That also means file format constraints. 

What were you thinking about? Personally I have no experience with Android apps other than Fennec.

I have the feeling you'll need to convert from one format supported by tools to the format using by Android (XML)?)

**Comment by pocmo** [comment]
> What were you thinking about? Personally I have no experience with Android apps other than Fennec.

Not sure. I have no experience with our translation processes. :)

> I have the feeling you'll need to convert from one format supported by tools to the format using by Android (XML)?

Yeah, at the end of the day we need Android XML files [[1]](https://developer.android.com/guide/topics/resources/string-resource.html).

- What file format are those tools using?
- If I take care of writing import/export scripts for "Android <-> Tools" then does this get us started or do we need more?

**Comment by flodolo** [comment]
Supported file formats in Pontoon
https://mozilla-pontoon.readthedocs.io/en/latest/

We can use the same strategy we use for Focus for iOS, which is a GitHub repository for strings that you can pull from. 

As for the format, in mozilla-central we use .properties and convert them, that might be a strategy, noting that we have some pain points with the XML (need to escape straight quotes or double quotes for example).

**Comment by pocmo** [comment]
I looked around and a promising tool seems to be android2po [[1]](https://github.com/miracle2k/android2po). It can convert between Android XML files and Gettext PO, which is supported by Pontoon.

Without any tweaking it generates files like this:
https://pastebin.mozilla.org/8979993

Would this be useful?

**Comment by flodolo** [comment]
I think so, yes, unless we find roadblocks along the way.

@Delphine Definitely your call though :-)

**Comment by Delphine** [comment]
Yes this looks good, thank you! :)

**Comment by pocmo** [comment]
Okay, cool! I'll have a look how we can add localization comments that survive import/export and then I can create an actual export.

Can you create a repository where the files will live? It looks like we keep them separate? Are there any languages we want to start with or is adding languages something you do in Pontoon anyways?

**Comment by flodolo** [comment]
I can take care of creating the repository tomorrow. New locales can be added directly in Pontoon, but it would be good to figure out if you want to start with some.

Note that there are some conventions to follow in terms of structure
https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website

**Comment by flodolo** [comment]
Repository created, invite sent. Let me know if other devs need access to it
https://github.com/mozilla-l10n/focus-android-l10n/

**Comment by flodolo** [comment]
Turns out I had to rename the file to .pot (didn't realize Pontoon expects that for templates).

You can find the Italian file here if you want to try building an apk
https://github.com/mozilla-l10n/focus-android-l10n/tree/master/locales/it

**Comment by pocmo** [comment]
![focus-it](https://cloud.githubusercontent.com/assets/89638/23266246/40a87992-f9b5-11e6-963f-abf38253da9f.png)

This is working nicely!

**Comment by flodolo** [comment]
Great.

@Delphine 
The project is basically ready. You need to set up the project on Pontoon's prod (you can copy it from stage, just add a description), and communication.

Before you send anything out, I'll need to enable write access for localizers.

We also need to figure out if we want to preselect a list of languages.

**Comment by Delphine** [comment]
Will do! thanks to the both of you!

**Comment by pocmo** [comment]
Note that some of the strings might change soon or might even disappear as we polish the UI. Not sure if this kind of churn is okay for the translators?

**Comment by Delphine** [comment]
If these are minor changes and since the project is still small, I think we should be ok. Let me know if you expect major changes though. In that case, we should work on defining an l10n cycle within the general Focus release cycle.

**Comment by Delphine** [comment]
@pocmo : Do you know if anything has changed in regards to the list of "priority" languages we should start enabling right away? I know Barbara mentioned "same as Focus iOS" last week, so want to make sure this still holds true. If so, I'll start by adding these and we can make the project opt-in for other locales from there.

**Comment by pocmo** [comment]
> If these are minor changes and since the project is still small, I think we should be ok. Let me know if you expect major changes though.

I was thinking about the menu that we need to update and with that some strings will change too (#52). But apart from that it should be stable. And yeah, we have not many strings so far anyways.

> Do you know if anything has changed in regards to the list of "priority" languages we should start enabling right away?

I haven't heard from any changes. From my point of view we should take whatever we can get. :) We will need to make sure we support RTL correctly in our layouts (#31).

**Comment by Delphine** [comment]
@flodolo: Do we have dashboards set up for this project so we can track l10n status?

**Comment by Delphine** [comment]
Hey guys - this is live on Pontoon now \o/
https://pontoon.mozilla.org/projects/focus-for-android/

I started with the same subset of locales as for Focus on iOS, and already more are asking to join :) 

I think that it remains important for us to get a deadline though for this project - and to set up some kind of l10n cycle that includes testing time. 

Exactly the same goes for Play Store content and deadline. As long as this isn't urgent yet, we can discuss these during the next Focus for Android meeting I guess. 

In the meantime, thanks flod and Sebastian for all your help here 👍

**Comment by flodolo** [comment]
> @flodolo: Do we have dashboards set up for this project so we can track l10n status?

We do now :-)
https://l10n.mozilla-community.org/webstatus/?product=focus-android

**Comment by pocmo** [comment]
> I think that it remains important for us to get a deadline though for this project - and to set up some kind of l10n cycle that includes testing time.

We have about 6-8 weeks for developing v1. In your experience how much time should we give translators with the final set of strings? I can look through our filed issues and see which ones will require strings additions/changes. We can then try to give them a higher priority so that we finish those tasks earlier.

**Comment by pocmo** [comment]
I added the "needs strings" label to all issues that are likely to add or change strings. Note that not all of those issues are marked with "v1.0" though!
https://github.com/mozilla-mobile/focus-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22needs+strings%22

**Comment by Delphine** [comment]
@pocmo: thanks that's very helpful!
I think 1-2 weeks for l10n + l10n testing should be enough since this is a small project. Same thing if Play Store content needs localization.

Side note: as I was adding languages to the project, flod realized that we probably aren't using a language switcher for Focus on Android. We're going to depend on what languages are supported by Android, correct? Issue is that we have never been able to find one single reliable source of truth telling us what are all the supported languages by Android at this point... :/ I have a few documents & devices that can guide our decision, but won't be reliable at 100% unfortunately.

**Comment by mastizada** [comment]
@Delphine That also will not help as it depends on companies, for example: Android doesn't support Azerbaijani language as OS language but latest Android phones by Asus and mostly all by Samsung has Azerbaijani option. So I don't think it will be possible to find list of all supported languages as different manufactures has different Android modifications. In my opinion having a language selection as in Firefox for Android can be better option.

**Comment by ahunt** [comment]
@mastizada Implementing our own language selection is complicated, I filed #122 for that - however I suspect that probably won't be part of focus v1.

**Comment by pocmo** [comment]
> So I don't think it will be possible to find list of all supported languages as different manufactures has different Android modifications.

Yeah, that's right. This varies from device to device. It might be driven by where the device is sold.

(I'm closing this issue as we have figured out how to translate the app.)
