### ISSUE TITLE
Build version is not updated to 8.6.1 in About Focus 

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4604]
## Steps to reproduce
1. Launch Focus 8.6.1;
2. Click on 3-dots button> Settings menu> Mozilla;
3. Tap "About Firefox Focus";
### Expected behavior
The About Focus page contains all the details and the version is 8.6.1.
### Actual behavior
The build version is 8.6.0 instead of 8.6.1.
### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: Focus: 8.6.1, Build ID: 342261855, GV 79.0.20200720193547

**Comment by jonalmeida** [comment]
This should be fixed now. We made a new release for 8.6.2 to avoid deleting the current 8.6.1 release.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Focus 8.6.2 Build #342271411 GV 79.0.2 with Pixel 2 (Android 9).
I will close this issue.
