### ISSUE TITLE
Wrong label for custom auto complete

### ISSUE THREAD

**Issue by PhoenixIV** [mozilla-mobile/focus-android#4608]
## Error description

In the German version (see screenshot) the labels for most-visited and custom websites are the same. Right now it claims custom websites would enable the 450 most-visited websites.

![Screenshot_20200816-114549_Firefox_Focus](https://user-images.githubusercontent.com/2091755/90331910-9aa98980-dfb8-11ea-85b7-c42eaea7c8c5.png)

### Device information

* Focus version: 8.5.1

**Comment by lobontiumira** [comment]
Thank you for the report.
This is now fixed on the latest Focus builds.
