### ISSUE TITLE
Horizontal scrolling on blog.fefe.de

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#461]
From feedback:

> This website has a viewport size that shouldnt allow horizontal scrolling. Bug?

![fefe](https://cloud.githubusercontent.com/assets/89638/24999648/ac68d302-203e-11e7-8868-8742dcfe4e93.jpg)

**Comment by pocmo** [comment]
It doesn't happen in Chrome. You can actually zoom the page a little and the horizontal scrolling is gone. WebView has a bunch of methods for controlling zoom - maybe we want something else than the default.

**Comment by ahunt** [comment]
I've noticed there's still a difference between Firefox and Chrome: chrome zooms out until the entire page is visible on screen (which results in a white margin on the side). We can enable the same behaviour with:
```
        settings.setLoadWithOverviewMode(true);
        settings.setUseWideViewPort(true);
```

Firefox and Chrome Dev additionally increase text size to use the full width - i.e. the margins on either side are the same size. It's possible to get this behaviour in WebView by adding `settings.setLayoutAlgorithm(WebSettings.LayoutAlgorithm.TEXT_AUTOSIZING)`. However that only works on my Android 7 device (Chrome WebView), and doesn't work on Android 6 (System WebView).

My draft patches do both.

**Comment by ahunt** [comment]
Keeping this open to reevaluate once we get user feedback!

**Comment by ahunt** [comment]
This seems to have broken error pages (they're hugely magnified, and you can't zoom out). More work needed : )
