### ISSUE TITLE
Disable capturing screenshots.

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/focus-android#4613]
### Why/User Benefit/User Problem
Disabling capturing screenshot is a good practice from a security viewpoint. If this feature isn't built in, at least consider adding it under the settings menu.
### What / Requirements
Disabling screenshot such that pressing screenshot keys or any third party apps couldn't capture screenshots.

**Comment by jonalmeida** [comment]
As @cadeyrn mentioned, this feature is already implemented. You can enable it in Settings -> Privacy & Security -> Stealth.

**Comment by samiuljoy** [comment]
My bad.
