### ISSUE TITLE
The GV version is different on the 8/28 builds

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4616]
## Steps to reproduce
1. Install Focus 8.7.2 with GV 80.0.20200827204751;
2. Launch Focus and go to Settings - About Firefox Focus;
3. Observe the GV version;
### Expected behavior
The GV version is 80.0.20200827204751.
### Actual behavior
The GV version is 80.0.1-20200827204751.
### Notes
![rsz_screenshot_20200828-154345](https://user-images.githubusercontent.com/48799384/91562204-7a2ce800-e945-11ea-9491-12c0de741eb4.png)

### Device information

* Android device: Pixel 2 (Android 9), Samsung Galaxy Tab S6 (Android 9), Nexus 5 (Android 5.1).
* Focus version: Focus 8.7.2 Build ID: 342410345 GV 80.0.20200827204751
This is also reproducible on Fenix 80.1.1 RC1 from 8/28.

**Comment by jonalmeida** [comment]
Based on RyanVM's comment, we can close this!
