### ISSUE TITLE
Tab viewer

### ISSUE THREAD

**Issue by holde4** [mozilla-mobile/focus-android#4618]
### Why/User Benefit
The old tab viewer was easier to organize and see

### What / Requirements
Maybe there should be an option to customize how tabs are viewed

Well, this is the first time I've done this, forgive my ignorance, but this was important to me

**Comment by cadeyrn** [comment]
You are obviously in the wrong issue tracker. There is no old or new tab viewer in Focus.

**Comment by kbrosnan** [comment]
Closing as invalid
