### ISSUE TITLE
support text reflow on zoom

### ISSUE THREAD

**Issue by jtnord** [mozilla-mobile/focus-android#4619]
### Why/User Benefit/User Problem

many sites layouts do not scale when zoomed due to small fonts or other usability issues.
FFF allows you to zoom in like other browsers (Chrome Firefox) however unlike those browsers the text does not reflow to fit the screen.
this means reading text you have to constantly scroll left/right to read sentences.

### What / Requirements

when zooming text should reflow.

### Acceptance Criteria (how do I know when I’m done?)

as a user visiting a text heavy site (BBC.co.uk/news) when I zoom in text is both enlarged and reflowed so that text wraps to fit on the screen and you can read an article by only scrolling up and down and you do not have to scroll up/down and left/right

**Comment by kbrosnan** [comment]
This is tracked at bz-1547181
