### ISSUE TITLE
Use default search from Firefox?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#462]
We got feedback from two users that didn't like the default search engine and were expecting us to use the one configured in Firefox or get it via Sync.

> Didn't pick up my Firefox default search. No other issues so far though 😁 thanks for not forgetting 🤖 android.
https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/feedback

> I don't want yahoo as the default search, can we add firefox sync to this?
https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/feedback

**Comment by bbinto** [comment]
Kinda neat but might be not that important anymore considering we are giving users the choice to add their default search engine.

**Comment by pocmo** [comment]
Agree! Let's just close? :)
