### ISSUE TITLE
Adding "https by default" and "encrypted sni + DoH" as built in features.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/focus-android#4620]
From about:config on the nightly and beta versions, if **dom.security.https_only_mode** is set to ***true***, all websites use https by default.
**network.trr.mode**, **bootstrap.address.url(optional)** and **esni.enabled** rulesets allows users to use esni + DoH(dns over https). A few refferer header rulesets are needed to be set to false/disabled for esni + DoH to work at its best.

If these features were built into settings under privacy sub-menu, it'd be great!

Users can turn them on or off as per desire.

**Comment by lobontiumira** [comment]
This is now implemented in RC and Nightly Focus builds.
Closing as obsolete.
