### ISSUE TITLE
Focus doesn't download password protected .pdf files

### ISSUE THREAD

**Issue by Keyikedalube** [mozilla-mobile/focus-android#4626]
## Steps to reproduce

1. Go to this link: https://nagalanduniversity.ac.in/English/ug2020onlineexam
2. Click on BCA DCN-601 (or any pdf provided) link

### Expected behavior

3. Download password protected pdf

### Actual behavior

4. Focus tries to open

![20200923_100537](https://user-images.githubusercontent.com/24214509/93970158-25855d00-fd8b-11ea-8bd0-b3a12b7c9e1d.jpg)

### Device information

* Android device: Samsung Galaxy M30s
* Focus version:
![Screenshot_20200923-103502_Firefox Focus](https://user-images.githubusercontent.com/24214509/93969761-47321480-fd8a-11ea-8627-5b6c80f35d09.jpg)

**Comment by rahulgupta1999** [comment]
Hey can you please elaborate the issue

**Comment by Keyikedalube** [comment]
Firefox Focus doesn't support opening password protected pdf files. So, I'm getting that error page when I click a pdf link on the website provided above. I briefly described only the expected output if Focus is intended to be minimal with no fancy features like those we see on full-featured web browser eg: Firefox browser

Since I'm not presented with a password prompt to unlock the document and also there's no download option when tapping & holding the pdf link, I'm not able to access the pdf document at all. Focus should let the user download password-protected pdfs and let other third-party apps open 'em later... if that feauture isn't going to be implement/supported in the browser.

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the latest Focus Nightly build 100.0a1 from 318 with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the latest Focus Nightly 104.0a1 build from 7/13.
Tested with Samsung Galaxy Note 8 (Android 9), and Oppo Reno 6 (Android 12).

I'll close this ticket.
