### ISSUE TITLE
Images on remotestash.co broken

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#463]
From feedback:

> The images on this site are broken, but work (mostly) in regular Firefox

![remotestash](https://cloud.githubusercontent.com/assets/89638/24999841/61167db8-203f-11e7-9c0b-ea09c667d509.jpg)

**Comment by ahunt** [comment]
I can reproduce on e.g.:
http://remotestash.co/jobs?category=job_board

I don't see any missing images when I disable all tracking protection settings - that suggests this is just a side-effect of tracking protection - we block e.g. the "github jobs" image which is hosted on twimg.com ( https://pbs.twimg.com/profile_images/616309728688238592/pBeeJQDQ.png ). The same images are blocked in Firefox Private browsing (i.e. with tracking protection enabled), so this looks like tracking protection working as intended.

**Comment by ahunt** [comment]
Maybe we should change this bug to be something like "Make sure Users are aware that tracking protection could break images/websites in general" (even beyond the "Block other content trackers setting").

**Comment by pocmo** [comment]
Setting [needs triage] to discuss whether we want to add an explanation (See comment above).

**Comment by ahunt** [comment]
This will be explained during onboarding (and we have the override switch and "open in browser" menu items), hence no action needed for now.
