### ISSUE TITLE
crash on clicking open in chrome

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/focus-android#4633]
## Steps to reproduce
Set default browser to none by uninstalling the default browser app
In focus, click on open in chrome in three dot menu
### Expected behavior
Opens in chrome/the option is not displayed
### Actual behavior
Crash
### Device information

* Android device: Asus Zenfone
* Focus version: 8.8.0 (Build #342620305 🦎 81.0-20200917005511)

**Comment by s-ankur** [comment]
Could you tell me how to attach crash info? About:crashes seems empty

**Comment by kbrosnan** [comment]
Then a logcat would be needed. Same steps as https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information

**Comment by s-ankur** [comment]
Is this helpful? https://gist.github.com/s-ankur/714cd5165e6b9bbb3b3cdf6f195659c7

**Comment by lobontiumira** [comment]
I was not able to reproduce this crash on the latest Focus builds.
@s-ankur please file a new issue if you encounter any crash, and please provide the logcat or additional information from about:crashes.
Thank you!
