### ISSUE TITLE
Focus appears in share menu

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/focus-android#4635]
## Steps to reproduce
On a website, click on share.. option in 3 dot menu
### Expected behavior
Focus is an option in sharesheet
IMO focus should detect and remove that entry since noone would want to share the url with the same app

### Actual behavior
It is shown in the sharesheet as an option
### Device information

* Android device: Asus Zenfone
* Focus version: ?

**Comment by lobontiumira** [comment]
This issue was fixed - see #5881 
Thank you!
