### ISSUE TITLE
Date picker issues when switching from landscape to portrait mode

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4637]
## Steps to reproduce
1. Launch Focus and go to https://rpappalax.github.io/testapp;
2. Scroll down to "Date Picker Menu";
3. Rotate the device in landscape mode;
4. Click on Date Picker Menu control and verify that a date picker object appears;
5. Rotate the device in portrait mode;
6. Tap on the ">" to change the month;
### Expected behavior
When switching from landscape to portrait mode, the date picker object is displayed as in portrait mode.
### Actual behavior
The date picker object is displayed as in landscape mode and when changing the month, there are visual issues.

![20201001_122550](https://user-images.githubusercontent.com/48799384/94792426-a1158880-03e1-11eb-98d6-834f142ca389.gif)

### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: Focus: 8.8.1, Build ID: 342742322, GV 81.0.20200930150533

**Comment by ionutbedregeanu** [comment]
Can't be reproduced anymore

#### Pixel 2 API 28

https://user-images.githubusercontent.com/11731652/121881437-f5fef200-cd17-11eb-86ed-dbc4db433e31.mp4

#### Pixel 3 API 30

https://user-images.githubusercontent.com/11731652/121881446-f9927900-cd17-11eb-9ae1-443ce2ab1da0.mp4

**Comment by lobontiumira** [comment]
I am still able to reproduce partially this issue, on the month/year elements, switching from landscape to protrait mode.
Tested on the OnePlus 5T (Android 10) with Focus 8.16.0:

![Screenshot_1](https://user-images.githubusercontent.com/40694158/121889030-5e060600-cd21-11eb-8cd5-ea47d21decbc.jpg)

https://user-images.githubusercontent.com/40694158/121888900-36af3900-cd21-11eb-847d-08af180967fc.mp4

**Comment by ionutbedregeanu** [comment]
Oh, ok, I will take a look again. Thanks, @lobontiumira!

**Comment by Mugurell** [comment]
@lobontiumira is the same issue also reproducing in other browsers (Fenix/Chrome) while testing on the same device?

**Comment by lobontiumira** [comment]
Yes! Reproducible on 6/14 Nightly Fenix build, and on Chrome 91.0.4472.88.

**Comment by ionutbedregeanu** [comment]
Hmm, then  seems to be an OS problem

**Comment by lobontiumira** [comment]
I've reproduced this with Samsung Galaxy Note 8 (Android 9), as well.
On 8.16.0 Focus, 6/14 Nightly Fenix build, and on Chrome 91.0.4472.88.

**Comment by ionutbedregeanu** [comment]
@pocmo Seems to be a problem caused by the native android dialog component. Should we implement our own date picker?

**Comment by lobontiumira** [comment]
Reproducible on Beta 99.0.0-beta.1 with Xiaomi mi4i (Android 5.0.2).

**Comment by Mugurell** [comment]
As a quick solution to this we could just close these prompts when the screen rotates.

**Comment by ionutbedregeanu** [comment]
> As a quick solution to this we could just close these prompts when the screen rotates. Otherwise, supporting the transition from portrait to landscape and reverse on our own, with it being broken in the platform seems like a heavy task with high maintenance costs.

@jeffreygee Any thoughts about "As a quick solution to this we could just close these prompts when the screen rotates"?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802252

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
