### ISSUE TITLE
No DNS resolution for .onion addresses with orbot VPN (again)

### ISSUE THREAD

**Issue by casketizer** [mozilla-mobile/focus-android#4639]
IMPORTANT:
An identical problem existed in 2018 and is still listed here on github. Not to be confused.

## Steps to reproduce
Install orbot.
Activate its VPN mode. Add Focus to it.
Open Focus and open check.torproject.org to make sure Focus goes through Tor.
If confirmed try to open any .onion address.
For example DuckDuckGo
https://3g2upl4pq6kufc4m.onion/

### Expected behavior
Focus loads the address you try to access. 
## Actual behavior
Address not found error.
### Device information
Any Android device. I tried several covering Android versions 6 to 10

* Focus version: ? 
Any Focus >= 8.0.23 doesn't work

All Versions <= 8.0.18 work fine

**Comment by hudak** [comment]
Reproduced with Brave Browser and DuckDuckGo app

**Comment by lobontiumira** [comment]
@casketizer is this issue still reproducible on your side?
Thank you!

**Comment by casketizer** [comment]
Yes, still no dns resolution for .onion.

Mira ***@***.***> schrieb am Fr., 18. März 2022, 15:54:

**Comment by iorgamgabriel** [comment]
Set this as a "feature-request" since it's not clear if we want to support this or not

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802007

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
