### ISSUE TITLE
Initially all the options in block cookies settings menu are unchecked

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/focus-android#4645]
## Steps to reproduce
Open block cookies option from settings
On a clean install btw
### Expected behavior
One of the options is checked, since it is a radiobutton 
### actual behaviour
![Screenshot_2020-10-27-23-41-08-703_org mozilla focus](https://user-images.githubusercontent.com/33252312/97344098-50912e00-18ae-11eb-8fbe-2772f93af3ee.jpg)

### Device information

* Android device: Redmi Note 4
* Focus version: 8.8.3 (Build #342872056 🦎 81.0.2-20201012085804)

**Comment by lobontiumira** [comment]
This is no longer an issue.
Closing as obsolete.
