### ISSUE TITLE
FF Klar on F-Droid outdated

### ISSUE THREAD

**Issue by hman2** [mozilla-mobile/focus-android#4656]
F-Droid offers only 8.0.15 from 2018 (in the app). On the F-Droid website, version 8.4.0 is listed. When I transfer that to the phone, F-Droid says it would be incompatible. This is a Fairphone 2 with Nougat (in the form of AOSP 7.1.2, named Fairphone Open OS 19.2). F-Droid claims "Android 5 or newer" as prerequisite, which is clearly the case. Searching for Firefox Klar and installing installs 8.0.15 again....

And even stranger, the Google Playstore (which I can only access through Aurora) has version 8.8.4.343140144...

Oh, btw, there is a bug in Firefox Klar 8.0.15: The about-screen is just a blank white page with no content

**Comment by kbrosnan** [comment]
F-droid is independent of this project. They have some requirements of building Geckoview themselves.
