### ISSUE TITLE
Code Quality task failing: unable to find pmd

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/focus-android#4665]
I'm not sure how long this has been a problem, but I am trying to find out why UI tests are not being ran on Firebase currently (with whatever currently pass, that's another problem), but the Code Quality task is a dependency for the scheduled UI test task. 

Code Quality Failure: https://firefox-ci-tc.services.mozilla.com/tasks/OohJuDmMT-iQ9rYdBo99NA/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FOohJuDmMT-iQ9rYdBo99NA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

```Log
<======-------> 50% CONFIGURING [37s]> :app<=============> 100% CONFIGURING [37s]
FAILURE: Build failed with an exception.
* What went wrong:
Task 'pmd' not found in root project 'focus-android'.
```

(@pocmo ?)

**Comment by pocmo** [comment]
pmd was for Java code and I think is no longer part of our Gradle setup. Let's get rid of it.

**Comment by pocmo** [comment]
Same for probably for `checkstyle` and `spotbugs`:
https://github.com/mozilla-mobile/focus-android/blob/7e4034cd7fbc008b65f2c6cfb9befd5469a7329b/tools/taskcluster/schedule-master-build.py#L48
