### ISSUE TITLE
UI Test Failures in waitForWebContent

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/focus-android#4666]
Running master (02ccad3e)  (Focus x86 WebView Debug) tests on a Pixel 4 API 30 Emulator

The following tests all fail with:

```Java
junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at org.mozilla.focus.helpers.TestHelper.waitForWebContent(TestHelper.java:61)
```

* org.mozilla.focus.activity.AddToHomescreenTest#SearchTermShortcutTest
* org.mozilla.focus.activity.EraseAllUserDataTest#TrashTest
* org.mozilla.focus.activity.EraseAllUserDataTest#systemBarHomeViewTest
* org.mozilla.focus.activity.EraseAllUserDataTest#systemBarTest
* org.mozilla.focus.activity.OpenInExternalBrowserDialogueTest#OpenInExternalBrowserDialogueTest
* org.mozilla.focus.activity.SettingsBlockToggleTest#SettingsToggleTest
* org.mozilla.focus.activity.ToggleBlockTest#SimpleToggleTest
* org.mozilla.focus.activity.URLExceptionTest#removeAllExceptionsTest
* org.mozilla.focus.activity.URLExceptionTest#AddAndRemoveExceptionTest

This [wait](https://github.com/mozilla-mobile/focus-android/blob/fe45eb8242f7b7db0499f008eac987dd3abc5ef2/app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.java#L59) is not good.

```Java
    public static final long waitingTime = DateUtils.SECOND_IN_MILLIS * 4;
```

**Comment by sv-ohorvath** [comment]
This method won't be sued anymore, tests still using it are disabled for now. I'll close the issue.
