### ISSUE TITLE
Adding web pages to home screen appears to break expected cookie/privacy behavior

### ISSUE THREAD

**Issue by cm2** [mozilla-mobile/focus-android#4671]
Adding web pages to home screen appears to break expected cookie/privacy behavior

## Steps to reproduce
1. Log into an account on a site (Site A)
2. Create an icon on home screen for the site (Site A)
3. Log into another site (Site B)
4. tap Trash button
5. Return to Site B

### Expected behavior
Expect that trash button will clear cookies for at least Site B, but ideally both Site B + Site A (suppose a usability/privacy trade-off would be made for pages that the user specifically chose to retain on their home screen). 

### Actual behavior
- Cookies are retained for sites going forward (Site A and Site B remain logged in).
- There does not be appear to be a user accessible way of clearing all cookies from within the app once this occurs
- Changing cookie behavior to block all cookies causes the user to be logged out but only for the duration the setting is in effect (putting back to default block 3rd party tracker cookies leads to the user being logged in again)

### Device information

* Android device: Google Pixel 3, Android 11
* Focus version: 8.8.4 Build 343140145

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue. 
Tested on Google Pixel 9Android 10) with the latest Focus Nightly build 100.0a1 from 4/4.
After step 5, I was signed out from site B. Tapping on the homescreen icon opened site A where I was also signed out of.
