### ISSUE TITLE
Extra colon within URL breaks the Autocomplete functionality

### ISSUE THREAD

**Issue by disposableone** [mozilla-mobile/focus-android#4672]
## Steps to reproduce
Open Google News at https://news.google.com
It resolves to https://news.google.com/topstories?hl=en-US&gl=US&ceid=US:en
Click on address input field. Click add to autocomplete. Close tab. In the address field start typing news...and if you don't have other links saved, news.google.com/blah blah should auto complete. Click enter.  Nothing happens, the page doesn't load. It looks like what breaks the functionality is the second colon in the link. Without a colon, everything works as expected.

### Expected behavior
See above. Autocomplete link for Google news should load the page just fine. 
### Device information

* Android device: Android 6.0.1, Samsung Note 4
* Focus version: 8.8.4

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the latest Focus nightly 100.0a1 (build 360940510 with GV 100.0a1-20220403090644) with Google Pixel (Android 10).
STR are:
1. Open Google News at https://news.google.com/.
2. The page loads as https://news.google.com/topstories?hl=en-US&gl=US&ceid=US:en.
3. Long tap on the search field and copy the link.
4. Go to Settings - Search - URL Autocomplete - Manage sites - +Add custom URL, and paste the link from step 2.
5. Save it.
6. Exit Settings, tap on the trashcan icon. 
7. Type "news" on the search field.
8. The link auto completes, but nothing is loading, the page is blank.

**Comment by lobontiumira** [comment]
This issue still reproduces on Focus Nightly 107.0a1 from 10/3 with Lenovo tablet M10 (Android 10), and Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802665

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
