### ISSUE TITLE
The Language list flashes when tapping the Recent Apps device button

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4686]
## Steps to reproduce
1. Launch Focus;
2. Go to the three-dot menu -> Settings -> General -> Language;
3. Tap the Recent Apps device button;
4. Observe the behavior;
### Expected behavior
The Language list is displayed in Recent Apps without flashing.
### Actual behavior
The Language list flashes when tapping the Recent Apps device button. The General page is displayed briefly.
![20210106_120605](https://user-images.githubusercontent.com/48799384/103756195-b40aab00-5017-11eb-8ccc-1152fa875ff2.gif)

### Device information

* Android device: Pixel 2 (Android 9);
* Focus version: Focus 8.11.3 GV 84 from 1/5; Focus 8.11.2 GV 84 from 12/24;

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the latest Focus nightly build 99.0, nor on RC 97.2.0.
Tested with Samsung Galaxy Note 8 (Android 9), and Oppo Find X3 Lite (Android 11).
