### ISSUE TITLE
Can't delete installed search engines

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/focus-android#4697]
## Steps to reproduce

Settings -> Search -> Search engine -> select DuckDuckGo -> three dots -> remove -> select Amazon.co.uk, Google and Wikipedia -> click bin icon, top right

### Expected behavior

Amazon, Google and Wikipedia to be removed from search engine selection page

### Actual behavior

All three (Amazon, Google and Wikipedia) are still there.

### Device information

* Android device: Fairphone 3, Android 10
* Focus version: 8.12.0

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly build 100.0a1 from 3/18.
