### ISSUE TITLE
Turning Tracking Protection toggle off doesn't add the page to the exceptions list

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#4729]
## Steps to reproduce
1. Open a website. Switch Tracking Protection toggle off on this page.
2. Go to Settings>Privacy&Security>Cookies and site data.
3. Tap the Exceptions list menu.

### Expected behavior
A list of websites where Content blocking was turned off is displayed.

### Actual behavior
"Exceptions" option is greyed out and the list can't be opened (page wasn't added to the list).

### Device information
* Android device: Samsung Note 10(Android 11), LG G7 Fit (Android 8.1)
* Focus version: dev build # 1186.0.1- 20210310152336

**Comment by pocmo** [comment]
This is a known issue currently and we are waiting for a fix in GeckoView.

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the latest versions of Focus.
Closing as obsolete.
