### ISSUE TITLE
Buddybuild crash report on build #1136

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#473]
Buddybuild detected a crash from a.polivanchuk@outlook.com

[View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/26ceb41da71d2f8521e498a2eb84d90b)

**Comment by ahunt** [comment]
All of these crashes (java.lang.NoSuchMethodError: org.mozilla.focus.web.c$a.setWebContentsDebuggingEnabled) are on a 4.1 emulator - we only support Android 5+, hence not an actual bug we should care about.

(setWebContentsDebugginEnabled doesn't exist on Android 4, hence the crash)

**Comment by pocmo** [comment]
I wonder how the APK could be installed on such an emulator? minSdkVersion should prevent that.
