### ISSUE TITLE
"Find in Page" search box is still displayed after new links are opened

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#4731]
## Steps to reproduce
1. Open a url containing text -> open menu, and tap 'Find in Page'.
2. Enter a word to search (that exists in more than one place).
3. Open another link/links.

### Expected behavior
"Find in Page" search box is not visible after the new links are opened.

### Actual behavior
"Find in Page" search box is still displayed.

### Notes
* The searchbox color is white.
* Not reproducible on Focus - Play Store.

### Device information
* Android device: Samsung Note 10(Android 11), LG G7 Fit (Android 8.1)
* Focus version: dev build # 1186.0.1- 20210310152336

**Comment by pocmo** [comment]
The same seems to happen in Reference Browser and it looks like we do not have any specific code handling this in the feature. I am not really sure yet why it works that way in Fenix. That may be a side effect of something else.

**Comment by gouri-panda** [comment]
@pocmo Maybe in-migration from `SessionManger` to `BrowserStore`, they forgot to add the feature. I'm interested in working on this issue. Can I work on it?

**Comment by pocmo** [comment]
@gouri-panda Yes, you can work on this. But let's discuss some options here, before writing code. :)

My first thought is whether `EngineObserver` should remove `findResults` for the current page on navigation and then the presenter should detect that and notify the app to do whatever it needs to do (e.g. hide the bar).

* https://github.com/mozilla-mobile/android-components/blob/master/components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt#L63
* https://github.com/mozilla-mobile/android-components/blob/master/components/feature/findinpage/src/main/java/mozilla/components/feature/findinpage/internal/FindInPagePresenter.kt#L33-L40
* https://github.com/mozilla-mobile/android-components/blob/master/components/feature/findinpage/src/main/java/mozilla/components/feature/findinpage/FindInPageFeature.kt#L68

**Comment by pocmo** [comment]
I noticed that we already clear the results when the loading state changes:
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt#L135

Would we want to close the bar in that case? 🤔

**Comment by gouri-panda** [comment]
@pocmo I'm not so familiar with the `BrowserState` code base. How things work before `BrowserStore` i mean how `SessionManager` handles if the URL changed in session? Thanks!

**Comment by mcarare** [comment]
Question for UX: 
Currently, the behavior in Fenix is that we dismiss the find in the page bar on navigating away from the page. But as @pocmo pointed out, this is not the behavior in Firefox desktop where the bar stays open until it is explicitly dismissed. 
Should we align the Focus behavior with the Fenix one or should we follow desktop? (Following desktop would imply we should also change current Fenix behavior?)

**Comment by pocmo** [comment]
> (Following desktop would imply we should also change current Fenix behavior?)

I tried to look up how that works in Fenix and I couldn't really figure out in the short time whether that was actually done intentionally in Fenix?

**Comment by mcarare** [comment]
> 
> I tried to look up how that works in Fenix and I couldn't really figure out in the short time whether that was actually done intentionally in Fenix?

https://github.com/mozilla-mobile/fenix/blob/75fc116043d782f70f430dad4af22cdd61064055/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L732-L745

**Comment by amedyne** [comment]
Tagging @brampitoyo for UX feedback.

**Comment by brampitoyo** [comment]
@amedyne Sorry I missed this issue! The right behaviour is indeed to not show the “Find in page” UI on the new link pages that are opened.

**Comment by amedyne** [comment]
@jeffreygee Can you have another look before I add this to the backlog for the team to work on?

**Comment by jeffreygee** [comment]
@amedyne Agreed with the previous decision that the correct flow is to not show the “Find in page” UI on the new link pages that are opened.

**Comment by ionutbedregeanu** [comment]
I didn't succeed to reproduce it. @lobontiumira Can you also try to reproduce it?

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Focus Nightly 101.0a1 build from 4/28.
Tested with Samsung Galaxy Note 8 (Android 9), and Oppo Reno 6 (Android 12).
