### ISSUE TITLE
The newly added search engine is set as default

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4736]
## Steps to reproduce
1. Launch Focus and go to Settings - Search - Search engine;
2. Tap  "Add another search engine" and add a valid search engine;
3. Tap "Save";
4. Observe the default search engine;
### Expected behavior
The newly added search engine is not set as default.
### Actual behavior
The newly added search engine is set as default.
### Device information

* Android device: Pixel 2 (Android 9);
* Focus version: Focus 8.13.1 GV 86 and 8.14.0 GV 87 from 3/18;

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Focus 8.15.3 GV 88 with Huawei P9 Lite (Android 7).

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the latest Focus builds.
