### ISSUE TITLE
Enabling the "Block JS" doesn't work

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#4737]
## Steps to reproduce
1. Go to Settings - Privacy & Security - Web Content and enable "Block JavaScript".
2. Open https://rpappalax.github.io/testapp and tap on  "Click here for JS alert" button.

### Expected behavior
A JS alert pops up.

### Actual behavior
Nothing happens.

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: build from master (#1186.0.1- 20210310152336)
* Not reproducible on Foxus 8.14.0 with Google Pixel 2 (Android 9)

**Comment by pocmo** [comment]
@lobontiumira Is the actual and expected behavior mixed up? If JavaScript is blocked then no alert popping up seems right?

**Comment by lobontiumira** [comment]
Hi Sebastian,
Closing this bug, as I mixed up.
Sorry!
