### ISSUE TITLE
New search engines can't be added

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#4738]
## Steps to reproduce
1. Launch Focus and go to Settings - Search - Search engine;
2. Tap "Add another search engine" and add a valid search engine (ecosia);
3. Tap "Save";
4.Observe the search engine list;

### Expected behavior
The new added search engine is displayed in the list.

### Actual behavior
The new added search engine is NOT displayed in the list.

### Device information
* Android device: Samsung Note 10 (Android 11), Google Pixel (Android 10)
* Focus version: dev build from master - #1186.0.1- 20210310152336

**Comment by pocmo** [comment]
Will be fixed with the changes in https://github.com/mozilla-mobile/focus-android/issues/4761
