### ISSUE TITLE
Search engines can't be removed

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#4739]
## Steps to reproduce
1. Go to Settings>Search>SearchEngine;
2. In 'Installed search engines' dialog, click more options button and select Remove.
3. Select search engines to remove. -> click "Remove".

### Expected behavior
The search engine selected is removed from the list.

### Actual behavior
Selected search engines can't be removed.

### Device information
* Android device: Samsung Note 10 (Android 11), Google Pixel (Android 10)
* Focus version: dev build from master - #1186.0.1- 20210310152336

**Comment by pocmo** [comment]
Will be fixed with the changes in https://github.com/mozilla-mobile/focus-android/issues/4761
