### ISSUE TITLE
The downloaded files cannot be seen

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#4743]
## Steps to reproduce
1. Go to https://rpappalax.github.io/testapp or https://daleharvey.github.io/testapp/.
2. Scroll down to the File download section.
3. Tap on the "download this icon". When the download finishes, tap on "Open".

### Expected behavior
The image is opened.

### Actual behavior
The image is not opened.

### Device information
* Android device: Google Pixel (Android 10), Samsung Note 10 (Android 11)
* Focus version: build from master (#1186.0.1- 20210310152336)
* Not reproducible on Focus 8.14.0 with Google Pixel 2 (Android 9)

**Comment by pocmo** [comment]
@Amejia481 Do you know from the top of your head what is needed for that? We integrated `feature-downloads`, but maybe there's more needed?

**Comment by Amejia481** [comment]
Nothing that I could think of, as we delegate to the Android OS via intents to opening files. I'm not that busy today if you like I could take a look today?

**Comment by Amejia481** [comment]
The same issue is reproducible in Fenix too, I'm still researching so far this is what I have found:

The issue is only reproducible on Android 10 only. Android 11, 9 and below it works. I noticed that if I add `android:requestLegacyExternalStorage="true"` on the manifest the issue gets resolve.

I'm still researching, I will keep posting updates

**Comment by Amejia481** [comment]
I think the problem could have to do with the app that is trying to open the file not getting access to the URI that we are passing. 

I'm not sure why as we are passing the `Intent.FLAG_GRANT_READ_URI_PERMISSION` on AC when creating the intent
https://github.com/mozilla-mobile/android-components/blob/72d73704127ac174ed356452d80c23c2e3a626c0/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L978

**Comment by Amejia481** [comment]
@lobontiumira when you have some available time, we can re-test this ticket on master. Thanks in advance.

**Comment by lobontiumira** [comment]
Verified as fixed on the 8.13.1 build #1190.0a1-20210426094327 from master, with Google Pixel (Android 10), and HTC 10 (Android 8).
