### ISSUE TITLE
Report Site Issue is not working in custom tab

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4745]
## Steps to reproduce
1. Launch Focus and set it as default browser;
2. Go to Gmail and tap on a link;
3. Tap the three dot menu and choose "Report Site Issue";
4. Observe the opened page;
### Expected behavior
"Report Site Issue" is working in custom tab.
### Actual behavior
"Report Site Issue" is not working in custom tab.
### Device information

* Android device: Pixel 2 (Android 9), Samsung Note 10 (Android 11), Google Pixel (Android 10)
* Focus version: dev build from master - #1186.0.1- 20210310152336 and Focus 8.13.1 GV 86 and 8.14.0 GV 87

**Comment by lobontiumira** [comment]
Reproducible on 8.15.1 build with Xiaomi Mi 8 Lite (Android 9).

**Comment by lobontiumira** [comment]
This issue reproduces on 8.15.2 Focus build with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Focus 8.15.3 GV 88 with Huawei P9 Lite (Android 7).

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the 8.16.0 build with Google Pixel (Android 10), nor with Samsung Galaxy Note 8 (Android 9).

**Comment by Mugurell** [comment]
@lobontiumira If the bug cannot be reproduced anymore can this issue be closed?
