### ISSUE TITLE
Permissions pop-up not displayed/camera & location not working

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#4747]
## Steps to reproduce
1. Go to https://permission.site/ and enable HTTPS. (or webrtc pages)
2. Tap on Camera, Location, Microphone.

### Expected behavior
A pop-up is displayed asking for permission for location/camera.

### Actual behavior
The permission pop-up is not displayed.
Location is not available nor camera.

### Device information
* Android device: Samsung Note 10 (Android 11), Google Pixel (Android 10)
* Focus version: dev build from master - #1186.0.1- 20210310152336

**Comment by ebalazs-sv** [comment]
This issue is also reproducible on Focus 8.14.0 from 3/18 with Pixel 2 (Android 9).

**Comment by pocmo** [comment]
Afaik we never implemented this for Focus and Focus as app never had the related app permissions.

**Comment by sv-ohorvath** [comment]
> Afaik we never implemented this for Focus and Focus as app never had the related app permissions.

@pocmo That's how I remember it too. I think there was a confusion :) @sflorean

**Comment by pocmo** [comment]
Let's close it since it is linked from different reports.

There's this old issue that covers this feature request (it mentions "microphone" explicitly, but the same API is also used for camera etc.):
https://github.com/mozilla-mobile/focus-android/issues/805
