### ISSUE TITLE
Crash system dialog not displayed

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#4748]
## Steps to reproduce
1. Open focus and trigger the app to crash using this URL about:crashparent.

### Expected behavior
App crashed and a dialog is displayed.

### Actual behavior
The dialog is not displayed.

### Device information
* Android device: Samsung Note 10 (Android 11), Google Pixel (Android 10)
* Focus version: dev build from master - 1186.0.1- 20210310152336

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on  Focus build with Google Pixel (Android 10).
The system dialog isn't displayed until the user opens the notification - please see the short video below:

https://user-images.githubusercontent.com/40694158/120199667-292b8680-c22c-11eb-931c-60fd917a298f.mp4

**Comment by pocmo** [comment]
Is this a build from `main` or Focus 8.x?

**Comment by pocmo** [comment]
> The system dialog isn't displayed until the user opens the notification

Ah, yes, that is intentional on Android 10+ since https://github.com/mozilla-mobile/android-components/issues/3097. Since that Android version we are no longer allowed to launch a UI screen from the background and therefore show the notification instead.

**Comment by lobontiumira** [comment]
I forgot to mention the 8.16.0 Focus build.

**Comment by lobontiumira** [comment]
Based on Sebastian's [comment](https://github.com/mozilla-mobile/focus-android/issues/4748#issuecomment-851501267), I'll close this issue.
