### ISSUE TITLE
Add support for links that open third-party apps (feature-applinks)

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#4749]
## Steps to reproduce
1. With a fresh profile, open reddit.com.
2. When asked to "See Reddit in..." select to open Reddit app.

### Expected behavior
The user is redirected to the Reddit app, if installed, or to Play Store if not installed.

### Actual behavior
I had the Reddit app installed, but selecting to open in Reddit did nothing. Also, tapping on "Use app" does nothing.
Workaround: from the three-dot menu, tapping on "Open in Reddit" opened the Reddit app.

### Device information
* Android device: Google Pixel (Android 10), Samsung Note 10 (Android 11)
* Focus version: build from master (1186.0.1- 20210310152336)
* Not reproducible on Focus 8.14.0 with Google Pixel 2 (Android 9)

https://user-images.githubusercontent.com/40694158/111792496-fcbeca00-88cc-11eb-86a7-e16bdb542172.mp4

**Comment by pocmo** [comment]
Does this work in the play store version?

This may need `feature-applinks` integration.

**Comment by gouri-panda** [comment]
@pocmo I want to work on this issue. AFAIK `focus-android` doesn't have launch in external app functanlity. What should I do with `lauchInApp`  parameter of `AppLInksFeature` ? Should I change true to default?

https://github.com/mozilla-mobile/android-components/blob/0f11c790f6d0b7fe8fb0ac2d610f732555526b61/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt#L52

**Comment by pocmo** [comment]
I'll move this out of the bug column and will turn this into a feature request, since this is something we haven't implemented in Focus. This may need UX involvement to figure out how/if we want to leave the app - since that may have privacy implications.

**Comment by lobontiumira** [comment]
This is no longer the case.
Closing.
