### ISSUE TITLE
Revert URLs from Lithium's structure back to Original for the Kitsune Rollback

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/focus-android#475]
The SUMO team is doing a rollback to their old CMS. This means that the new style URLs that are currently implemented for Focus & Klar will not work.

This change may not be needed if they finalize their migration to Lithium before Focus & Klar for Android ship.

**Comment by npark-mozilla** [comment]
We should make sure this does not block Focus release timeline - should we talk to SUMO people?

**Comment by pocmo** [comment]
For "default browser" the new URL format is:
`https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/focus-default-android`
