### ISSUE TITLE
Opening a custom tab does not show the private notification 

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4763]
## Steps to reproduce
1. Set Focus as the default browser.
2. Open a custom tab.
3. Observe your notifications.

### Expected behavior
- The persistent notification that allows you to erase the open sessions.

### Actual behavior
- No notification is available.

### Device information

* Android device: Android 11, Pixel 3
* Focus version: dev build of master @ 364eea96

**Comment by pocmo** [comment]
Is this a bug? Do we do this in the currently shipped version? Since the notification doesn't clear custom tabs I think it would be confusing if it showed up for custom tabs?

**Comment by jonalmeida** [comment]
In the current version, the notification shows Up for a custom tab and it does clear the opened custom tabs as well. When you go back to the custom tab, it used to show the third party app (now it shows Focus home screen because of an unrelated patch).

I agree that it can be confusing because the notification does not tell you that it's for a custom tab specifically. 

We can always revisit this later

**Comment by lobontiumira** [comment]
This issue still reproduces on the latest Focus Nightly 104.0a1 from 7/12 with Oppo Reno 6 (Android 12).

**Comment by iorgamgabriel** [comment]
Set this as a "feature-request" since it's not clear if we want to support this or not

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802008

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
