### ISSUE TITLE
Save backup login keys for 2FA in password manager

### ISSUE THREAD

**Issue by Tasty213** [mozilla-mobile/focus-android#4768]
### Why/User Benefit/User Problem
Currently, users can only add usernames and passwords to firefoxes, inbuilt password manager. With the increasing rise of 2FA it would be very useful to keep to backup tokens in the same secure locations as the passwords.
### What / Requirements
An optional text entry box in the password manager to add additional information

### Acceptance Criteria (how do I know when I’m done?)

You can add 2FA backup tokens to the password manager

**Comment by cadeyrn** [comment]
Wrong issue tracker? There is no "password manager" in Focus.

**Comment by Tasty213** [comment]
Hi,

Oh sorry i didn't realise must be the wrong one. Where can i submit a
feature request for the password manager that's used across firefox
android and the desktop version?

**Comment by cadeyrn** [comment]
Firefox for desktop: https://bugzilla.mozilla.org/home
Firefox for Android: https://github.com/mozilla-mobile/fenix/issues
