### ISSUE TITLE
Placeholder Text Issue in App Shourtcut

### ISSUE THREAD

**Issue by VishnuSanal** [mozilla-mobile/focus-android#4771]
## Steps to reproduce

 - Long click on the app icon
 - See the error (Please check the attached screenshot)

![SS](https://user-images.githubusercontent.com/50027064/112748968-f8856180-8fdc-11eb-8844-41559bfd0899.jpg)

### Expected behaviour

 - The App name is displayed correctly

### Actual behaviour

 - The App name is not displayed. The placeholder text is displayed instead

### Device information

* Android device: Realme Narzo 20A
* Focus version: v8.14.0 (Can also be reproduced on v8.13.1)

### Additional information

 - A bit of searching in the codebase leads to [this](https://github.com/mozilla-mobile/focus-android/blob/09ea191d0e409e83aa3bab678decfbc2c16efe80/app/src/main/res/values/strings.xml#L114) line. Here it is said that the app name should be displayed instead of the placeholder.
 - I would like to work on this issue :)

**Comment by gouri-panda** [comment]
@VishnuSanal If you aren't working on this issue. Can I take this one? Thanks!

**Comment by VishnuSanal** [comment]
No one confirmed it from the organisation's side. So, I haven't started working on it! I'd love to work on it, but since you asked, you can take it up if you wish! :)
