### ISSUE TITLE
Clicking the "Delete browsing history" notification closes the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4788]
## Steps to reproduce
1. Open a web page.
2. Press the device home key.
3. Pull down the notification bar, tap the notification text (not the 2 buttons: Open/Erase and open)
4. Press the device recent apps button, check if the app is still running in the background.
### Expected behavior
Not sure about the expected behavior, I've found this test which needs to re-launch the activity after pressing the notification, indicating that it used to behave like this and probably was expected(?) or just assumed it was:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.kt#L121

To me it makes sense that the app should still be in the background, with browsing data deleted.
### Actual behavior
The app is killed, no longer running in the background.
### Device information

* Android device: Pixel 4
* Focus version: 8.14.0

**Comment by gouri-panda** [comment]
@sv-ohorvath What's the Expected behaviour? Shouldn't it killed the app and clear the browsing section like if we click the delete trash icon? Thanks!

**Comment by sv-ohorvath** [comment]
@gouri-panda Sorry, I somehow missed your comment. I'm not sure what is the real expectation here, but my guess is that it shouldn't kill the app, just delete browsing data.

**Comment by amedyne** [comment]
@brampitoyo any thoughts here on what we should expect?

**Comment by brampitoyo** [comment]
@amedyne @sv-ohorvath @gouri-panda This action is working as expected.

- If Focus is in the background (e.g. on the phone homescreen)
    - If the notification is tapped, the app will quit and will not come into the foreground **← This issue**
    - If “Erase and open” is tapped, the app will come into the foreground with browsing history deleted
-  If Focus is in the foreground
    - If the notification is tapped, the app stays in the foreground and browsing history is deleted
    - If “Erase and open” is tapped, the app stays in the foreground and browsing history is deleted (identical as above)

**Comment by amedyne** [comment]
Thank you @brampitoyo. Closing this issue.
