### ISSUE TITLE
Consider clearing cache when changing blocking settings

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#479]
This is similar to what we already discussed when talking about image blocking.

STR:
1. Start a new session
2. Enable all blockers
3. Open website with blocked images, e.g. winecountry.com -> no images should load
4. Disable all blockers (menu->settings)
5. Refresh -> images load
6. Reenable all blockers

Maybe Expected: images aren't visible, same appearance as in (3)
Actual: images load (because they're cached)

I think this is mostly a UX/product decision - from a technical side we can clear the cache if needed. (Images aren't a huge issue here, but we could have cached tracking scripts which will continue to run after changing blocking settings.)

**Comment by pocmo** [comment]
* Image blocking is hidden again
* We will need to fix this as part of #443 -> Users will be able to disable blocking for the current session. Whenever turning blocking on/off we will need to clear the cache.
