### ISSUE TITLE
Setup crash reporting for Beta builds

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#4793]
We should make sure that crash reporting is working as we expect it:

* Socorro: The assumption is that it will filter based on version and no change is needed.
* Sentry: For Fenix we currently use separate products for Beta/Release. Do we want the same for Focus? Should we try using a single one since Sentry can already group by channel?

**Comment by jonalmeida** [comment]
> Sentry: For Fenix we currently use separate products for Beta/Release. Do we want the same for Focus? Should we try using a single one since Sentry can already group by channel?

We have a separate project for Sentry: [focus-android-beta](https://sentry.prod.mozaws.net/operations/focus-android-beta/).
