### ISSUE TITLE
Separate beta build in telemetry

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#4794]
Once we ship a Beta build, we need to be able to distinguish between Beta and Release builds in telemetry.

Is this even something we would want to do in the old telemetry system or is integrating Glean a requirement for this (probably?) (See #4545).

(This estimate does not include Glean integration)

**Comment by ionutbedregeanu** [comment]
@travis79 Do you know if we already do that in base ping?

**Comment by travis79** [comment]
Glean does this automatically, and it looks like the pipeline is already set up to ingest data from release/beta/nightly versions of Focus Andriod.  Legacy telemetry also has a `channel` included with the core ping and can be split by it, but I don't know for certain if Focus Android sets this or not (I would assume it does)

**Comment by ionutbedregeanu** [comment]
I noticed that we are using the `channel` in the upload patch, but we don't send the `channel` in pings.
This is how core pings looks

`{
  "searches": {}, 
  "tz": 120, 
  "seq": 24, 
  "created": "2022-01-20", 
  "locale": "en-US", 
  "arch": "x86", 
  "durations": 2, 
  "sessions": 1, 
  "clientId": "3576df1a-c67b-427c-afde-7737090fd4f1", 
  "profileDate": 19009, 
  "experiments": [], 
  "defaultSearch": "Google", 
  "v": 7, 
  "device": "Google-Android SDK built f", 
  "osversion": "27", 
  "os": "Android"
}
`

Does this offer the data needed? Are there any changes needed?

**Comment by travis79** [comment]
Based on what I can see [here](https://sql.telemetry.mozilla.org/queries/84022#208141), we do collect channel information via legacy telemetry so I'm certain we can filter by channel for analysis in either the legacy or the Glean data.

**Comment by ionutbedregeanu** [comment]
Thanks, Travis! Then I think we can close this ticket since we can filter the data
