### ISSUE TITLE
Crashes on erasing browser data

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4796]
### Firebase Test Run:
trashButtonTest
https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7583673953021975845/executions/bs.8212bea0fae12636/testcases/1/logs

changeSearchEngineTest 
https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5982841671663786387/executions/bs.696538f8ebaa5a42/testcases/4

testLocalAndSessionStorageIsWrittenAndRemoved 
https://console.firebase.google.com/u/1/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8807568340833473108/executions/bs.4c4dc961ddd5721f/testcases/3/logs

### Build: debug 4/8

The test instrumentation also crashed after closing a tab by pressing the back button (this test was removed for flakiness):
https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7561477158669147356/executions/bs.bab610f85d913bf2/testcases/1/logs

I couldn't reproduce the crashes manually and I can't determine from the logs if it's caused by the tests or a bug.

Same crash when I ran the tests on API 28: [link](https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7342105127195498081/executions/bs.39f91d78e3e13fb/testcases/1/logs)

**Comment by sv-ohorvath** [comment]
bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1704067

**Comment by sv-ohorvath** [comment]
From the logs, it seems to be this crash:
`04-08 02:29:57.969: W/Binder(9459): Caught a RuntimeException from the binder stub implementation.
04-08 02:29:57.969: W/Binder(9459): java.lang.SecurityException: Calling from not trusted UID!
04-08 02:29:57.969: W/Binder(9459): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:520)
04-08 02:29:57.969: W/Binder(9459): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:424)
04-08 02:29:57.969: W/Binder(9459): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
04-08 02:29:57.969: W/Binder(9459): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
04-08 02:29:57.969: W/Binder(9459): 	at android.os.Binder.execTransact(Binder.java:994)
04-08 02:29:57.999: I/MemoryTrimmer(3008): Trimming objects from memory, since app is in the background.
04-08 02:29:58.013: W/Binder(1535): Outgoing transactions from this process must be FLAG_ONEWAY
04-08 02:29:58.013: W/Binder(1535): java.lang.Throwable
04-08 02:29:58.013: W/Binder(1535): 	at android.os.BinderProxy.transact(BinderProxy.java:480)
04-08 02:29:58.013: W/Binder(1535): 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
04-08 02:29:58.013: W/Binder(1535): 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)`

**Comment by sv-ohorvath** [comment]
Or:
` E/GeckoConsole(10848): [JavaScript Error: "NS_ERROR_NOT_IMPLEMENTED: " {file: "resource://gre/modules/storage-geckoview.js" line: 83}]
05-12 05:40:48.412: E/GeckoConsole(10848): getAllLogins@resource://gre/modules/storage-geckoview.js:83:22
05-12 05:40:48.412: E/GeckoConsole(10848): getAllLogins@resource://gre/modules/LoginManager.jsm:426:26
05-12 05:40:48.412: E/GeckoConsole(10848): _deleteInternal/<@resource://gre/modules/ClearDataService.jsm:296:38
05-12 05:40:48.412: E/GeckoConsole(10848): _deleteInternal@resource://gre/modules/ClearDataService.jsm:294:12
05-12 05:40:48.412: E/GeckoConsole(10848): deleteAll@resource://gre/modules/ClearDataService.jsm:290:17
05-12 05:40:48.412: E/GeckoConsole(10848): deleteData/<@resource://gre/modules/ClearDataService.jsm:1187:23
05-12 05:40:48.412: E/GeckoConsole(10848): _deleteInternal/promises</<@resource://gre/modules/ClearDataService.jsm:1250:18
05-12 05:40:48.412: E/GeckoConsole(10848): _deleteInternal/promises<@resource://gre/modules/ClearDataService.jsm:1249:20
05-12 05:40:48.412: E/GeckoConsole(10848): _deleteInternal@resource://gre/modules/ClearDataService.jsm:1247:59
05-12 05:40:48.412: E/GeckoConsole(10848): deleteData@resource://gre/modules/ClearDataService.jsm:1186:17
05-12 05:40:48.412: E/GeckoConsole(10848): clearData/<@resource://gre/modules/GeckoViewStorageController.jsm:170:26
05-12 05:40:48.412: E/GeckoConsole(10848): clearData@resource://gre/modules/GeckoViewStorageController.jsm:169:5`

**Comment by AndiAJ** [comment]
`changeSearchEngineTest` crashed 1x on Master 6/23 : [Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8497299209711004446/executions/bs.829ecbef098a4c5d/testcases/1/logs)

**The problem occurred in the second loop.**
✔️ Properly selected "Google" as the default engine
✔️ Performed the search,
✔️ Verified that the "mozilla" keyword was indeed searched using Google
💥  Crashed after after pressing the erase browsing history button

**Comment by sv-ohorvath** [comment]
> `changeSearchEngineTest` crashed 1x on Master 6/23 : [Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8497299209711004446/executions/bs.829ecbef098a4c5d/testcases/1/logs)
> 
> **The problem occurred in the second loop.**
> ✔️ Properly selected "Google" as the default engine
> ✔️ Performed the search,
> ✔️ Verified that the "mozilla" keyword was indeed searched using Google
> 💥 Crashed after after pressing the erase browsing history button

This belongs to https://github.com/mozilla-mobile/focus-android/issues/4964.
The crash in this issue seems to have stopped for now, I'll close this and we can reopen if it appears again.
