### ISSUE TITLE
Intermittent UI test failure - SearchTest.enableSearchSuggestionOnFirstRunTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4825]
### Firebase Test Run:
Flaky, failed 1/2 tries:
https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6531532247145267636/executions/bs.73e9548bd2f36d9f/testcases/3/logs
### Stacktrace:
`androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=org.mozilla.focus.debug:id/suggestionList]
at androidx.test.uiautomator.UiObject.getChildCount(UiObject.java:174)
at org.mozilla.focus.activity.robots.SearchRobot.verifySearchSuggestionsAreShown(SearchRobot.kt:43)`
### Build: 
4/22 debug

**Comment by sv-ohorvath** [comment]
Fixed in https://github.com/mozilla-mobile/focus-android/pull/4826. Closing for now.

**Comment by sv-ohorvath** [comment]
Still failing: https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5130917663311863408/executions/bs.3a4632c108b34960/testcases/5/test-cases

The issue is not related to the test, it is that I omitted to re-enable the network connection after the noNetworkConnectionErrorPageTest :(

**Comment by sv-ohorvath** [comment]
Still failing :( the previous patch didn't fix it entirely, probably needs idling resources for the network connection. Will get a new fix ASAP

**Comment by AndiAJ** [comment]
Failed on Master 5/27
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6660132872341551126/executions/bs.8d8338c846ef0ac6/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6660132872341551126/executions/bs.509df0108bab0a96/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7894687683469504211/executions/bs.87f5c20f8721d28f/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7894687683469504211/executions/bs.b2dd0604b25309cb/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8733949586231754912/executions/bs.780e9a00ebdeb84d/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8733949586231754912/executions/bs.68c018bad400b0be/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8784875839007734081/executions/bs.273eb2c0580f4844/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8784875839007734081/executions/bs.ebca235ed93ae313/testcases/1)

**Comment by sv-ohorvath** [comment]
Opened https://github.com/mozilla-mobile/focus-android/issues/4909 for the bug causing the test failure.

**Comment by AaronMT** [comment]
Thanks for filing. Yeah, ran into this in my Flank update PR.

https://console.firebase.google.com/u/1/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7935727720943183869/executions/bs.849410ee18d4cbf5/testcases/1

**Comment by AndiAJ** [comment]
Failed on Master 5/28:
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5712191011528580200/executions/bs.c82f1d7b49cb2953/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5712191011528580200/executions/bs.2f1dbae3e854e38a/testcases/1)

**Comment by AndiAJ** [comment]
Failed on Master 6/3:
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5728308063820437526/executions/bs.79db273781b0b07f/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5728308063820437526/executions/bs.709928061f177f5f/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7206144152064050335/executions/bs.b693621fd756a39a/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7206144152064050335/executions/bs.9da1291a95492d57/testcases/1)

**Comment by AndiAJ** [comment]
Failed on Master 6/10:
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5410123517458823603/executions/bs.df21d61c4e0d01d4/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5410123517458823603/executions/bs.9cdd7e030c758cb0/testcases/1)
