### ISSUE TITLE
Implement the Glean Crash Ping

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/focus-android#4847]
Implement the Glean Crash Ping in Focus so that we can create a crash metrics dashboard like we do for Fenix. This will allow us to set a baseline and track a crash ratio across Focus versions and even compare it to our other Android products that use the same telemetry.

Unclear if this requires an upgrade of the Crash Reporting component in Focus. This will require a Data Collection Review as it is a new metric type we will include.

**Comment by amedyne** [comment]
@jonalmeida Marking this as closed since we have completed the work on this.
