### ISSUE TITLE
One back press goes 2 steps from Manage sites in URL autocomplete settings 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4858]
## Steps to reproduce
1. Go to Settings>Search>URL autocomplete>Manage Sites
2. Press back (either the top navigation back button or the device button)
3. Observe the view it takes you to.
### Expected behavior
Should be in URL autocomplete settings.
### Actual behavior
Goes back 2 steps to the Search menu.

Related automation test failing #4859
### Device information

* Android device: Pixel 2, API 29
* Focus version: Debug 8.13.1 (#1190.0a1-20210426094327)

**Comment by lobontiumira** [comment]
Verified as fixed on the 8.13.1, build #1190.0a1-20210525093431, with Google Pixel (Android 10).
