### ISSUE TITLE
Remove xmlns attributes from localizable strings.xml files

### ISSUE THREAD

**Issue by mathjazz** [mozilla-mobile/focus-android#4868]
CDATA strings in the localizable strings.xml files contain `xmlns` attributes, which aren't present in the source files.

Such discrepancy will be confusing for localizers and may result in translation errors.

For example, see: https://github.com/mozilla-mobile/focus-android/blob/50d34542feb20ebb79973e930aa0cf39482418ee/app/src/main/res/values-it/strings.xml#L35

And the corresponding source string: https://github.com/mozilla-mobile/focus-android/blob/50d34542feb20ebb79973e930aa0cf39482418ee/app/src/main/res/values/strings.xml#L124

Can we get rid of these attributes?

**Comment by Delphine** [comment]
Hello Sebastian, friendly reminder about this PR - I think it's the only it left so we can enable Focus Android on our side :) thanks!

**Comment by pocmo** [comment]
I was on PTO last week. This and other changes should come in today via the quarantine PR :)
