### ISSUE TITLE
About Focus and Your Rights are opened in a new tab

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4873]
## Steps to reproduce
1. Go to Settings -> Mozilla -> "About Firefox Focus";
2. Observe the opened "About Firefox Focus" page;
### Expected behavior
A custom tab opens with "About" title and a back button.
### Actual behavior
A Insecure Connection new tab opens with the URL 
data:text/html;base64,PCFkb2N0eXBlIGh0bWw+PCEtLSBUaGlzIFNvdXJjZSBDb2RlIEZvcm0gaXMgc3ViamVjdCB0byB0aGUgdGVybXMgb2YgdGhlIE1vemlsbGEgUHVibGljICAgLSBMaWNlbnNlLCB2LiAyLjAuIElmIGEgY29weSBvZiB0aGUgTVBMIHdhcyBub3QgZGlzdHJpYnV0ZWQgd2l0aCB0aGlzIGZpbGUsICAgLSBZb3UgY2FuIG9idGFpbiBvbmUgYXQgaHR0cDovL21vemlsbGEub3JnL01QTC8yLjAvLiAgLS0+PGhlYWQ+PG1ldGEgbmFtZT0idmlld3BvcnQiIGNoYXJzZXQ9InV0Zi04IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MSI+PHN0eWxlPiAgICBib2R5LCBodG1sIHsgICAgYmFja2dyb3VuZDogIzIyMUYxRjsgICAgY29sb3I6ICNGRkZGRkY7ICAgIGZvbnQtZmFtaWx5OiBzYW5zLXNlcmlmOyAgICBsaW5lLWhlaWdodDogMjRweDsgICAgZm9udC1zaXplOiAxNHB4OyAgICB9ICAgIGJvZHl7ICAgIHBhZGRpbmctbGVmdDogMjRweDsgICAgcGFkZGluZy1yaWdodDogMjRweDsgICAgbWFyZ2luLWxlZnQ6IDBweDsgICAgbWFyZ2luLXJpZ2h0OiAwcHg7ICAgIH0gICAgYSB7ICAgIGNvbG9yOiAjMEE5QUY0OyAgICB9ICAgIC8qIE1ha2Ugb25seSBhYm91dCBwYWdlIGxpbmtzICgibGVhcm4gbW9yZSIpIHdoaXRlICovICAgIC5hYm91dCBhIHsgICAgY29sb3I6ICNGRkZGRkY7ICAgIH0gICAgcC5zdWJ0aXRsZSB7ICAgIHRleHQtYWxpZ246IGNlbnRlcjsgICAgb3BhY2l0eTogLjc7ICAgIG1hcmdpbjogMDsgICAgfSAgICBpbWcjd29yZG1hcmsgeyAgICAvKiBXZSBuZWVkIHRvIHNldCB0aGUgZHAgc2l6ZSBoZXJlLCBiZWNhdXNlIGJ5IGRlZmF1bHQgd2VidmlldyBhc3N1bWVzIHRoZSBpbWFnZSBpcyBub3QgICAgZGVuc2l0eSBzcGVjaWZpYyAoYnV0IHNpbmNlIGl0J3MgYW4gYW5kcm9pZCByZXNvdXJjZSwgd2UgZ2V0IGEgZGVuc2l0eSBzcGVjaWZpYyB2ZXJzaW9uKS4gKi8gICAgd2lkdGg6IDE4MHB4OyAgICBkaXNwbGF5OiBibG9jazsgICAgbWFyZ2luLWxlZnQ6IGF1dG87ICAgIG1hcmdpbi1yaWdodDogYXV0bzsgICAgcGFkZGluZy10b3A6IDI0cHg7ICAgIH08L3N0eWxlPjwvaGVhZD48aHRtbD48Ym9keSBjbGFzcz0iYWJvdXQiIGRpcj0ibHRyIj48aW1nIHNyYz0iZGF0YTppbWFnZS9wbmc7YmFzZTY0LGlWQk9SdzBLR2dvQUFBQU5TVWhFVWdBQUFod0FBQUJzQ0FNQUFBQVduWnVtQUFBREFGQk1WRVVBQUFELy8vLy8vLy8vLy8vLy8vLy8KLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLwovLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vCi8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8KLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLwovLy8vLy8vLy8vLy8vLy8vLy8vLwovLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vCi8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8KLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLwovLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vCi8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8KLy8vLy8vLy8vLy8vLy8vLy8vLy8KLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLwovLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vCi8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8KLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy84SFBRc0lBQUFCQUhSU1RsTUFCUVFtVG5HSwpsSmlQZ0dSQ0hSYTUxOWkvZXlBcGdzMzEvKy9FZnk5UzN1aGlHUEw0czBZSFdmcHRRZHYrWVNFajdUTk55Z29WSlNRUkNlRkVrcWd3CjdsT0w5bFRaQzl6cXlNUDg0QXczClpmMUxrZU1QQVVBSTBjdU9iM1NWdkFLK292cys2WmZtUlh3RzBnMkc5R05YaDdDdk5oUGRMTFhrMWhrMEdyY1FEaXEyK2FxRk81a3gKSWh6d0Z4czFYbWhuVVQydVB6bEpXbHQ0U25CNXROKzZQTnE0RkZERzVlelVxMjR0V0lpOUh5N1BIaytoc3BOc0E1K3B5U3ZNbW9uQgpZSDJsODBkbTR0T25YMnZDckRKMmc4ZU5tNHllc1ZXdGM4QW94ZFYxME90NjkrY25URGpPcElTY25mR0JkMzZnRXBaZGNseWpWanFRCmFidHFRMGltTVJiVVFRQUFFdmhKUkVGVWVBSHMwZ04ySkdFWUJkQVgyL3hpMjdadDJ6Ykh0cjNpaWFwTzg0Ui9SKyt1NFlLSWlJaUkKaUlpSWlJaUlpSWlJaUlqdUFqczdxR2Z2NE9qazdPTHE1dTdoNlFXNkhieWRmSHo5L0FNQ29WUlFjRWlvYU1MQ0l5Sng4MUZVdEJ5SgppWVU2Y1M3eFlpd2hNU2taZExPbApwSW9tRGFxa1o0aTV6SFJjQTdLUHlqcFZiRFlPNU9TS0xqUVBhdVRIaXdVRmhiQ2RvdUtTMHhTWDRsNG9LNWZUVmVCQXBSaW9naExWCk5XSkpMV3lvcmo3ME5QVU45eVJIbzV3cU5BZEFVN01ZYVBHR0FtV3RZa21iUFd5b1VrN1ZIc2tjbW81T0FNVUpZaUN6Q3dwMGl5VTkKdmJDbFBqbFYvd0J6YU5vR0FVUzJpNkVoWEwzaEVURXdPalkrTVRuYUxqSTFmZE55ekVEREhMTTRrQjBxQnVhcWNmWG1NMFcza0dLUApBL1pkaTB2THVHazUrcGhEdDRJRHEydGlJSG9kVjI5RGRKdEQwTVJOMzdnY1c4eWgyOGFoQURHd0F3V21SRmNIeFU3UHNiQnJ6VjRRCmMrajJjZWlCbitnYXZYSDFtaDZLSnVIUjllZDRqSHZQTUVkOC94TkxuajdEa2YwbE9WSCtIQXE4cUJHTmIvTDE1M2dKQTh3eDlzcWkKMTRNNDl1WnRqeHg0OXo0SEtwUWsKaUdZS3pISERjbnpBYVQ0R2ZGcDArZ3lvenJISEhEY3R4d1lVWUE2Vm1JTTVtT05MUFhNd2h4VmZ2ekVIYzFqeGZZRTVibitPc3BJZgpNTkg1c3dnNjcvbGZ2Ly84TFptR3NVS3Z5SDlEOC8rcHU4K0FLSzY5aitOL01EMkJOTGp5dzY0b2tzc2FlNWRMSkxHQnlRcXNwSzlpCmVVQ0NGYnZTbEVpeGdTMng5MTRTSy9iZWUrOHAySlgwbnR3MDkrek1PYk16V3g1MkxtNCtiMnl6aFozdjdwUnpacTM3WWhwcGF4VUYKeVFSeUpLWFJxeE03VGtxdm1rZ09tVXMxRG5PcjJOZzRlc0M4Y3ZwTjdqVWx2M21GcWw2bEg0ZXA0ZEFQZWxkL051QkR4VjM4WjF4WQphK09iMGlKVFIxVEdmZFdtRVdjZU9uMUdhTFY0QUpISk0yYzlNVHVSbEZKOGZIeGVuQVBKM0J3ZkxvOEU4K2EzV0xBd3dnQWdjOUhpCkpVc3JtRWhMMnJMbEsxYU84Q2FsCldCOXVsZVVabFBtb2dSNXhOSjd5NXNDUFE1dEZQZE4yUlBuSmVlU0MxV3ZLcjEwM2NPQ0k5UnRteDVKSzRlZ3VTeHM1V0dlMU5mL1IKdCtiR0hya0czQmRmcDhlbWgxOXRVSXB4ZlBUMjJzMWRqYmhQanFQcGxscHJCNGNBd0tBbWRGK0Y0WkRNNXc4eXRsMDhSSWF0NDlKSQp0QzB3TURDY0x4TVNIaWpMM1U2eUNvL0dRQ0Z6Ujg5WVVrZ2EwS3ZsckNqTFU5cHAwOFptNFU1WHRpS3F2Zkc5WGJzZmNqZU9KcSt0CjNBTkI1YkRKaGVSUSt5bkRjeUdyMUcyU292Ny9lN2p6MW5CZ0wya29YRFZ4WC9UVGM1STdrNHAvOUVJb0daK0o3bEpZV25GRWd4SGkKTUhVT2dzVHlLbGNKaEdSL0xGbnRmUU5xQjE0bXdVSFkxNFdzY3JvRlFHM3dJVFBKZkFaV3lvUWtxaUdKeW9PTDcwaVUxTGZpVzI4Tgo3VFBKclRpQ0Q4K0J5cEdwWko5cApTZzhvaFJ3OVJyTGpmR3FtbWw4YldLeFY5WFlpRnhvTUo2dTBMNTA0VHFuam9DY2dlOXptOVQ5TlROeVpTR2c2MjRSa3UySFh4NG5FCnZOUU0yczc1a2NSTFVka1pFbVNIZ3p0RlJPZEhOcnh3Y2VTcjc3c1R4MGVYb01WdzFwZnM4TGtBdFQxUHhKSFY4NDdpcUoycEhjZmwKSzdEbmFyOEhGa2VXRVpKTGNpck1WTEpJbVFGN05qZDJKWTdwWkdFcWI0UTlVUk5KNHRzYVhQSXk0azZERzV4S1JKOThrUExwcFlLcQptOXlJSS84ejJMSDRHR25xMGgrYTNtMUV6T2NPNHlqU2pPTllNOWhWcmRFRGl5UGxHaVQ5YVR3RXpkTFlBcDFnMzV6THp1TUl1RTczCm1hUGhRTzVVa3R5SUJIZk9SSkpSUlpERld6Ym9ML2R1ZVBSMHdVUTNQamxxQmNHdXlnV2tZVTB1N05qdlUrSTRhZ3R0Wk1ZTXZocTYKeUFqWmRucGdjWmphUVJJekpRQ0MKYmV6d2RDNGN1VnJWYVJ4ejJmb2RDWWR5dTVEa01YQ0dHeVJaQXU0eHRwM3V1M3p2a0JmTzNTeHhIUE16SVNtNmRmdk8yd25kMmdWQwoxbVlNcWR3SUFGZFVMZGtBMmQzZ2tzWVJkd2xXaGxrOXQ2UUdCN2VxV3JmbjJrcXdXT1R6NE9LZ2U1QVU1VUkwbWE4cHJsclhZaWowCkxTU0xvN0JuTE4xM0NBcEJkZG9rUXlGcUZWbWxQQVB1VmxOaXNrSWc2OStRTFB6ZTMzNWlZd2NxYVJ4YlBvUFZvSDh0OHlhTFZZY1gKUTlJNmgyeE00dTE4K3E4YWwvMXFqeG5iZVJFc0xqV2drc1l4RFZiUFRpVXV0c1B1WEFBcjZBSEdrUUExdmxYWkNjRXJYeFNzOHZVcAo2TDFRdmU1cC9xNkVoRWVLSUJtVUlQblNzdGZxWHdkYzh1M3ova1B5L0RxZUNJV2d1amRaMVlnSGQ1Z3NURE1nTTFRa1NYWjZISlUwCmpyaDJzT28yakxpa3I0ckVweVFhCkZpcXZ4cHJ5NC9xZGlnRFE3RVVxYVJ6ekJvRzU1V083OUJQN3czUDBpdU9MRXNTeEU3YU1VU2ZidGNiWGxoKzhLMlNSSTFPSldSMEcKcm5VcVNiNEpoS1F0S1JSbWdGdFFWNzdCSXdad1ZUUXZTNHBoaHcwVEl5RzdyYzhaMG9mQlpJNG5wWHJoc0ZMK2kza0VyRWI0a2lDcgpMQ0tlb2hMSE1RNU1IWDlTeWNzaXZlSW8rNjJ0eDc1ekZzY05LQzA2ODJvYVVmdUo2VVJFWHd0dDdDTlo0VFp3NDdRRzN1cVRRa1Z3Ck81b1E5NVpRUjFRS1dhVWVnSXg5cnBvR1FqWm90R3R4WkpCRFZhK0IrWjVzUFJRa1BWUWVDV3JDYW5jaUtUUzV2WlJLSElkcEZwZ1QKcFQ3QitMYXpPQXFnMExjUmNVTXo3VXduYjNBU3N2cGVUdU5JM0F4WjVXd1N2USt0Si9YdlRNaUt5eEJSeDBqSWZpRFg0bmh1dFpaNQpaUFVWbUZsbVVybWo5VmtjT3dkTQoyU1JTS1hrY3ZtMWdVZVJmNm5HY2RSWkhYU01FcHdwSjhEVmtvYkVrbWgwQ1NYeGRwM0YwQUhlUkZQSVdRdFkvaVNSbndFZ3Y1QXpJCkpwaGRqQ015V1l1MFdtS2pyRXM5UldxeC9jSEVmRU95RjhCdm9XTWNyeHBnTVRqWTgrTHdqd2YzbzRrRU9ZR1FUU09sNFpBOTd6U08KdnBCMVR5R2xKOEQ5UkpLa1c1QUY5YU9mZVl0dHN0MjdxR2tFTWIzQWJDNGtEY2RoZFlpLzBGZjVzYm1lY2VTREtVZWVIVWVsZVNRYQpEMW54YWxLYUF0a3NaM0dzTGxhZGsrZktCRUJyb0QrckNMSjF0RW5jeFhFdmprM0VYQUJ6bkxUNFZWUHR1RXlHVlVYU05ZNmEvNUE0Ck5wQkNkY2d1a1EyZllrZ1dObkVTUnhWdytTUlJuNFhEWjNra0d3bFovQ2Y4d2VaNjZ4UEh2TXA4bytqbzRyM3dZV1MxRWN5Z0p2K2IKT0o3MTdNMUttNm9rK3FhN2czTzQKNXZxUVJJNXlFa2NZWkh2OGlGTlZnSG9rYTdVWk1pTWtnZjZrVHh3MXdGUnFSWm9TYk9jdEpNM2tkNkJySEZQQlpGYnc2RGcrTnBQbwpaeU5rTzhuV2Jjak9PNDZqUVd2SUZpZVNyWWVnM1dDL0FLaGRKSGZqNktzOFZobE8ydmJ5STJubXBoSE1CcDNqR0JBQzVxN25IY3FLCmNSVGEyK1ZBRGJMVkc3SXZIY2VSbmdsWmRWTHhEMUx2dm9qclQzUWsyUFU0Y0cyVGhpWFR5S0lQbUY5SVcrMWtNSE9KV1FyR2tLVnoKSEsxYTh6TkovOHM0ZXF4VmViTGtjUWlMR3lxUXJiY2dlOVJ4SFBuZzNpR1ZKdDBobTltZXVMaHlzSkY4VEs4THFiME9nSG1ZdExXUApBaFBhbEN6TzhwMFFmZU9nYmJBeVJxOG10UWQ0K3R4QkhCT0VPS2FNc1RHMEpXUkhIY2R4SEZ3Q3FYaTlEbGx5TmdsRzdZSFNWN3BOCk1NNzdERXhOMG1iZURDWjN0WEsvCmVYQ2kzbkg4SEFsSjVjYzZEREdWd3V4ejkrTm9CODVneTJpQWJLWGpPTjRCOXl1cGRZTE04RE9KUG9UQ0d3MTBpOE0vQk14ZXNtTWcKR09NeDlrblNIOHk3cEhjY3BxTVFMRHJacmVmUUpwNGVoL2RpdUdpenlXRWNSK0g0MVBjRTFlR0tKTGdUQk1sWnBGc2NXZUw4VmsyZApvY2huU0NDWTNickhRWTJ2UWNrWTg5djJpcXM5T1k1V2xlQ2lBMTRPNDNnWDNFK09Wb1A2cUdoQU1yak9wRjhjSGNBWWJwSWRMWlJmCmkrUmZCQ1phL3pob2FnVFVBbjhiTjh4ajQ0aHRCaGM5RSt3d2pyYmdPcEJhTjNEL0pZVWZRc0RGWk9zWFI3NXdqa2JiZHVWTWdqRkcKTUUvb0Z3ZVhIdzR0MTFiNC9PUGplQ1hPWVJ4YjRYb2NuNUNvY1J1SXFoZnFGc2NIWUl4anlJNnZZTFdVN1RYQzZxS09jWEJqMmtMVApvRnIvOURqMnQzY1lSMWx3OVp6RQpjWndFM2hsUStsWDNPRkJBZGlUQTZpMjY3M2RZSGRZekRxN0I5NVdnNmR1NGYzWWMxeHpIY1JMY2NsTDdGdHdHMWR4S1VaMHllbTlXCjhMdUxjVFNIVlMxOTQrQlNxc3pLaFlhMTNoNFlSL0FjeUNJSHYyNWZqNmNidUx4RCtoMnAzUU5YaTdnS3ViQ1Y0YTN6RGlubU80MWoKZy9Md3BvcnVjWEIrTDIvL0xTWVNOcVo3WUJ5bU55QUw5UE4yaEZ3K2xEMU1hcHZBemRlWS95czZyRk1jczJIVjArayt4eUcrUTZwLwpIR3FweDNhdUwxY0hndVJsbmhjSFphaW5jemptd2ttd0JGSjdHakxEYkpLVmg0WTYvdnJFa1I3Q1p5cHBld1JXK2NvUm9CZjBqME50CjlFdExJaURiNklGeFBBWlpwcjhiY1h3Q2JqMnBGSmFGTEtJeFNiSWlvT1ZkTDEzaXFMb0lURGV5b3h1c3N0aEpzSEF4Yi8zalVEbTIKRHBJNlF6d3ZqcmZBWmJrUlJ6NjQKdnFTU3RsOTVzUXlUOWlsa2JjcUJlMWlYT0JJSDgwRlhiVWZCQkRUbVk2ZjZud1J6d053YmtwYzhMNDdmNGVxTWI5ZUg3RzhWa3ExRwpFWkE5UjVMSHdkM0pyZ1paN2dBOTRxQVpZSjZOSTAybUsxS3ZTV1J4Qk15RjBvcER1QUQwUGMrTFkwZ2R5RTY1RVVlRDFxcUpnS0twCjBIaVlQK0loNno2RVZvRHJsS2hISE8rcHg0RzFQODlXMmx6ai83RjNxY1d4SlFCTW1PZkZZZW9FV1Zzek9lYmlORUZEQWRrcXJ6SEQKdEdFb3VPK0o1a1dCZTF1UE9OYncwM0thS29UWVhLOHpEa3h1VHFuRlFjK0JHZTU1Y2RDWGtBVXRjeU9PS280TzJrM1BRYjNuZFJiYwo0dlkyZDFGdGxBNXhqQTRVVjc3YU9OdDRSc1dEdWVGT0hINy9yemgrQVRQWEErTklMM0oxdStMNnBRbnR6QTR1VFRoSHpFOEdjQzliCmRpRExnU3NYNTNZYy9DTEVXOTZrCnBhL3RmNVFZTnhqTU95N0dVWU0wL0dCd1BRNCtuNlc2QjhaaGVocXk4TWFrSmM1RW5Dc1hOV1VlSTZVbjFDZlhmUWFCbTh1ZVZNZDQKY0orN0h3ZjlDaVprS0drWUhRNW1oR29YdVZtcWEzR2NKN1dVVUxnZUJ6OFJkOWNENDZDS3pvWkVsMTNKZHlXT3FlQTZPN2dja2gzSQptaStBS3hwS3pGcHdlNDY1SDBkT09KaHZIVjd4dG9Za04rUEI5SFR0N1g2UjFCNkQxUVZ5eFQxK1Y1NFhSM0I5Y05FbXNtRjZzZzFlCitjYUZPQkxiUXBaWmcwU25vWnJGL2hvRWo1SlZkaDF3VjVxNkhRZmRCVk44blZUeVlzQXNia0NTd2gxZ25vMGxsYVIrcXIyVkgwbGwKbndGV25jZ0ZYajFnWVpqb2lYSFFEUU80cnh1U3dzOFpBTkRDaFRqb0lYQlJBNGg3R0Z3bDF0bDFzWUx1dzhTUGErNEo5K1A0S0FKTQpoaGZaK2hGVys3UStSeDhuVzRtNwppMi9hSGdmRnBKS05seU1BalduS2VhbWtyWGtrTEdZbWVXUWNwakFJNWh6T0kwbEsvcm9RM0pmWjBZVTR6SDNBTlZ0RFZrMWFHbFRmCkVlVDFtNTJCdHFTcjRDSnV1aDBIUDBGK09waVV2b0RWclFiRWVWOENZM3lObEZMRGdKbTFwZWppN1F6YlZJblFIcXk2TUhpNXQrYWEKWGNBUEJqd3hEc3FKZ3VqYWhPbm5mLys1UnMyditneUM1TlAyenVPZ3hsM0JHV2FORzdOcWRIYkhmNzBDd1lWQzFVZ01Oc2NSVjFFcwo2WTFXYnNjeGJEK2tKYStUSUswRnJFSitKMUZXcHZUM2I1dEpVTERWOGlPbldDT09rZ0wraVFUZlJFTzBodDlyQ0hCbGVYdXk1WFVYClRMVXlIaG9IL1I0QVo5NHpPNCtEemtkQ1pDaXVzd2NLYzlnR3BLNzQxL0ZQa2NBOEE0SVRic2RCTHhsaFZXZEZ1cHpHbEU4aFdVRksKS3lBWm1HVWlxLys4SHdTTGRXazIKMjZTUWxqbGtsWFRvR1NqOFNhVDRzck5ueWxjb0pGR2pQdnhaZUdvYzlGMDhuQmdjNjBJY05CME90V0ZISlEzYVFyQ1JGQ29rZ3l2NgoyZTA0YUNSa0FUdFcvRkJqNGtNYnZ1NFBXZlZnVW1yd0hDU1JSNzU2cU4rV29UZWU3eFJrTzdYK2R3TWtYYi8rcnE3ZjZzdjF6cndpCjVUNUJlcnhqeFB3ZUNTYXovdlkxalpKWWM2bXpmMWtFcTYxcG5oc0hIWXFBUXlzYmtTdHgwQWs0VUhraVdkeFJCTE9LbEZwQ2NDdkoKN1RnSzM0Y0RLNzhoV3ptTElUQ0VHQ0U0WTIycGNBWUV4ajNGUVpCOWxWY01aZ0Y3UzhYdGdDQmladHZxWVFlWDdOZ1AyY0l0NU1GeAowTjRvMkxkblZ4eTVGZ2R0c0YvWmdWRmtNVEVJZ3FWa28yRVVCTnZkam9POEg0ZGQ1NzRodGV6NnNDUHpiWktVdVFZN3pwam9BcXd1CmVCTVJyWm9EaC9aUElvK09nMVp0CmdoMkdQcU9JWEkyRE9uNEtUWWFOdm1TUnVoaUNCY0ZrYXljRW1SUGRpb01aWHdlYWd1NGtrcFo1dDZFcGRDcHh6UU9oSmVSRDRjdDIKNDE4enNUdE0yQS83cnZpVFczSE1kUDVlRWw0MTFXRldPbVNMQzhtT05RdWdJWFBHN3lUeWllQ2RrWmJZaE81UWE5ZUJHUE0yQ0RKLwpKaFh2VGhBOGswSmExb041bWx3eDRJSUJhcGNLeUo2YVY2R1MzQ0tQUkIwclFlM3FIOEpiMVBBclNYeVh2bUdBcHZBdldwRmJna2RzCmJtdFYvMWR5NkszNjhwSmpTZUozUmJyOTVoL05aSS9YNUQrN1FpSCs5ZDdIU01uM1hmbXVOcEsyWVJlM3hrTVVmclNlTjFrdE85bVcKcTcrTE5BeGx6NVlwTzVhMG5MalcvYjVydThrMVQ0VUZRaUY1eG54dnNpK3Q1NDRJaUdMV0x5TWJQbmVMb05Rc29RbFpOQjJvbW5mZwoxZVhOeGZHd3RmRHhNdVEyRS8rTgpXMHVheUtHOGVyMHpybll0TGlyYXM2aDF1N3UvSGdzbU5aUHp1L0txTyszUHJZTnlJLzYrbXptZG9uL3lJYzdiN1B6WmlIOXY4aVl0CnJlYWwzRGN2alZ6MVlwVWZYNjhUQWdDUmdWYzMvZmN5T2JObC9Oa3IvVDhyTHM3dCtzeXNsdlZTU01PeDZGQWpKRjJyMTJwSWt0VGgKd0Zka0k2N3VodHNmTDRxVSt4ejhZMDFmK21jSlRsbDEyZjlGMzFia0huTnF6blgvN0x3RzVEbThxaTZidlhkeXdhaWNZSEpSKzRhcgpWL3VreEpGZHJjYjBISGx2U2RqcDk4Wk56Q05SVXRncDB1SmQ5ZGpVUTI5ZHZMajBnMy9YanZ1clBUZ1FBQUNBZ1NEMGt2TlhHY2hWCmErSUd0QUFBQUFBQUFBQUFQRXZsTzhqMS9XTTVBQUFBQUVsRlRrU3VRbUNDCiIgaWQ9IndvcmRtYXJrIi8+PHAgY2xhc3M9InN1YnRpdGxlIj44LjEzLjEgKEJ1aWxkICMxMTkwLjBhMS0yMDIxMDUwNDA5MjAyNCk8L3A+PHA+RmlyZWZveCBGb2N1cyBwdXRzIHlvdSBpbiBjb250cm9sLjwvcD4gPHA+VXNlIGl0IGFzIGEgcHJpdmF0ZSBicm93c2VyOiA8dWw+IDxsaT5TZWFyY2ggYW5kIGJyb3dzZSByaWdodCBpbiB0aGUgYXBwPC9saT4gPGxpPkJsb2NrIHRyYWNrZXJzIChvciB1cGRhdGUgc2V0dGluZ3MgdG8gYWxsb3cgdHJhY2tlcnMpPC9saT4gPGxpPkVyYXNlIHRvIGRlbGV0ZSBjb29raWVzIGFzIHdlbGwgYXMgc2VhcmNoIGFuZCBicm93c2luZyBoaXN0b3J5PC9saT4gPC91bD4gPC9wPiA8cD5GaXJlZm94IEZvY3VzIGlzIHByb2R1Y2VkIGJ5IE1vemlsbGEuIE91ciBtaXNzaW9uIGlzIHRvIGZvc3RlciBhIGhlYWx0aHksIG9wZW4gSW50ZXJuZXQuPGJyLz4gPGEgaHJlZj1odHRwczovL3d3dy5tb3ppbGxhLm9yZy9lbi1VUy9hYm91dC9tYW5pZmVzdG8vPkxlYXJuIG1vcmU8L2E+PC9wPjwvYm9keT48L2h0bWw+

### Notes
This is also reproducible for the "Your Rights" page.
### Device information

* Android device: Pixel 2 (Android 9);
* Focus version: #1190 dev build from main
* Not reproducible on Focus 8.15.4

**Comment by lobontiumira** [comment]
I'll close this issue as it does not reproduce anymore on the latest Focus builds.
