### ISSUE TITLE
Three dot menu and lock icon are not visible in custom tab

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4877]
## Steps to reproduce
1. Set Focus as default browser;
2. Open another external browsing app (i.e. Gmail). Open a different website (i.e. cnn.com);
3. Observe the 3 dots button and the lock icon;
### Expected behavior
Three dot menu and lock icon are visible in custom tab.
### Actual behavior
Three dot menu and lock icon are not visible in custom tab, but they are actionable.
![20210511_101831](https://user-images.githubusercontent.com/48799384/117774882-97d77e80-b242-11eb-9a2c-288721a78151.gif)

### Device information

* Android device: Pixel 2 (Android 9);
* Focus version: #1190 dev build from main;
* Not reproducible on Focus 8.15.4;

**Comment by ionutbedregeanu** [comment]
I would like to work on this ticket

**Comment by lobontiumira** [comment]
Verified as fixed on the 8.13.1, build #1190.0a1-20210525093431, with Google Pixel (Android 10).
