### ISSUE TITLE
Long tap context menu is different

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4880]
## Steps to reproduce
1. Launch Focus and visit i.e. wikipedia.org;
2. Long tap a link;
3. Observe the context menu;
### Expected behavior
The context menu is:
![rsz_2screenshot_20210511-152018](https://user-images.githubusercontent.com/48799384/117814268-c10d0480-b26c-11eb-8290-7f682160191e.png)

### Actual behavior
The context menu is:
![rsz_screenshot_20210511-152007](https://user-images.githubusercontent.com/48799384/117814273-c2d6c800-b26c-11eb-9051-74ab1c5e20c9.png)
### Notes
This is also reproducible for long tap on cnn.com, list variations.

* Android device: Pixel 2 (Android 9);
* Focus version: #1190 dev build from main;
* Not reproducible on Focus 8.15.4;

**Comment by gouri-panda** [comment]
@pocmo I want to work on this issue ;)

**Comment by gouri-panda** [comment]
In `ContextMenuFragment` we should add a method to change the background. Should I create a PR In `AC`?

**Comment by pocmo** [comment]
I think we should be able to control this through the app theme?

**Comment by ionutbedregeanu** [comment]
I would like to work on this issue
