### ISSUE TITLE
Add a search engine- support page is not opened, instead the browser is closed

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#4881]
## Steps to reproduce
1. Go to the three-dot menu -> Settings -> Search -> Search engine.
2. Tap on "+ Add another search engine" to add a new search engine.
3. Tap on **"i"** option.

### Expected behavior
"Add search engine" support page is opened.

### Actual behavior
Focus is closed.

### Device information
* Android device: Pixel 2 (Android 9.0), Samsung Note 10 (Android 11).
* Focus version: Focus dev build (from main).

<video src="https://user-images.githubusercontent.com/58466444/117823263-f407c600-b275-11eb-95c4-77fb9ef4c7c8.mp4" width="300" height="550" />

**Comment by sv-ohorvath** [comment]
@pocmo this also happens on devices with Android <=6, when you click the set default browser setting to turn it off.

**Comment by pocmo** [comment]
@sv-ohorvath Thanks! Will take a look at this too.

**Comment by lobontiumira** [comment]
Verified as fixed on the 8.16.0 Focus build with Google Pixel (Android 10).
