### ISSUE TITLE
Intermittent UI test failure -privacy.LocalSessionStorageTest.testLocalAndSessionStorageIsWrittenAndRemoved

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4895]
### Firebase Test Run:
Flaky, failed 1/2 tries:
`Test instrumentation process crashed`
https://console.firebase.google.com/u/1/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8807568340833473108/executions/bs.4c4dc961ddd5721f/testcases/3/logs
#### Stacktrace:
From the logs, it seems to be this crash:
`04-08 02:29:57.969: W/Binder(9459): Caught a RuntimeException from the binder stub implementation.
04-08 02:29:57.969: W/Binder(9459): java.lang.SecurityException: Calling from not trusted UID!
04-08 02:29:57.969: W/Binder(9459): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:520)
04-08 02:29:57.969: W/Binder(9459): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:424)
04-08 02:29:57.969: W/Binder(9459): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
04-08 02:29:57.969: W/Binder(9459): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
04-08 02:29:57.969: W/Binder(9459): 	at android.os.Binder.execTransact(Binder.java:994)
04-08 02:29:57.999: I/MemoryTrimmer(3008): Trimming objects from memory, since app is in the background.
04-08 02:29:58.013: W/Binder(1535): Outgoing transactions from this process must be FLAG_ONEWAY
04-08 02:29:58.013: W/Binder(1535): java.lang.Throwable
04-08 02:29:58.013: W/Binder(1535): 	at android.os.BinderProxy.transact(BinderProxy.java:480)
04-08 02:29:58.013: W/Binder(1535): 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
04-08 02:29:58.013: W/Binder(1535): 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)`

### Build: 5/12 Debug

Same crash on other tests: https://github.com/mozilla-mobile/focus-android/issues/4796

Same crash running the tests on API 28.

**Comment by AndiAJ** [comment]
Flaky 1x on Master 5/27 : [Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8733949586231754912/executions/bs.83bbc103b33c71f0/testcases/1)

Stack trace:
`Test instrumentation process crashed. Check org.mozilla.focus.privacy.LocalSessionStorageTest#testLocalAndSessionStorageIsWrittenAndRemoved.txt for details
`

**Comment by sv-ohorvath** [comment]
` E/GeckoConsole(10848): [JavaScript Error: "NS_ERROR_NOT_IMPLEMENTED: " {file: "resource://gre/modules/storage-geckoview.js" line: 83}]
05-12 05:40:48.412: E/GeckoConsole(10848): getAllLogins@resource://gre/modules/storage-geckoview.js:83:22
05-12 05:40:48.412: E/GeckoConsole(10848): getAllLogins@resource://gre/modules/LoginManager.jsm:426:26
05-12 05:40:48.412: E/GeckoConsole(10848): _deleteInternal/<@resource://gre/modules/ClearDataService.jsm:296:38
05-12 05:40:48.412: E/GeckoConsole(10848): _deleteInternal@resource://gre/modules/ClearDataService.jsm:294:12
05-12 05:40:48.412: E/GeckoConsole(10848): deleteAll@resource://gre/modules/ClearDataService.jsm:290:17
05-12 05:40:48.412: E/GeckoConsole(10848): deleteData/<@resource://gre/modules/ClearDataService.jsm:1187:23
05-12 05:40:48.412: E/GeckoConsole(10848): _deleteInternal/promises</<@resource://gre/modules/ClearDataService.jsm:1250:18
05-12 05:40:48.412: E/GeckoConsole(10848): _deleteInternal/promises<@resource://gre/modules/ClearDataService.jsm:1249:20
05-12 05:40:48.412: E/GeckoConsole(10848): _deleteInternal@resource://gre/modules/ClearDataService.jsm:1247:59
05-12 05:40:48.412: E/GeckoConsole(10848): deleteData@resource://gre/modules/ClearDataService.jsm:1186:17
05-12 05:40:48.412: E/GeckoConsole(10848): clearData/<@resource://gre/modules/GeckoViewStorageController.jsm:170:26
05-12 05:40:48.412: E/GeckoConsole(10848): clearData@resource://gre/modules/GeckoViewStorageController.jsm:169:5`

**Comment by AndiAJ** [comment]
**• AssertionError**
Failed on 8/8 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6066125213718826339/executions/bs.df05a2b44821b9ad/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6066125213718826339/executions/bs.b4d8259f8dd11da/testcases/1)

**Comment by sv-ohorvath** [comment]
> **• AssertionError**
> Failed on 8/8 Main
> [Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6066125213718826339/executions/bs.df05a2b44821b9ad/testcases/1)
> [Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6066125213718826339/executions/bs.b4d8259f8dd11da/testcases/1)

Logged issue for failure caused by real bug: https://github.com/mozilla-mobile/focus-android/issues/5082

**Comment by sv-ohorvath** [comment]
It looks like there's a fix on master and this hasn't failed in the last days. Closing the issue.
