### ISSUE TITLE
Enable Total Cookie Protection (dFPI) by default

### ISSUE THREAD

**Issue by arthuredelstein** [mozilla-mobile/focus-android#4897]
### Why/User Benefit/User Problem

Prevents cross-site cookie-based tracking by giving every website its own cookie jar. Already enabled in Desktop in Strict Mode. See https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/

**Comment by ionutbedregeanu** [comment]
Implemented by https://github.com/mozilla-mobile/focus-android/issues/5938
