### ISSUE TITLE
Focus on Android legacy data MUST support user self-service data deletion requests

### ISSUE THREAD

**Issue by shell1** [mozilla-mobile/focus-android#4898]
### As a user, I must be able to request deleting all my data ([project shredder](https://mana.mozilla.org/wiki/display/DATA/Shredder#Shredder-HowDoesTelemetrySelf-ServeDataDeletionWork?)). 

In addition to Glean data - there is legacy telemetry being sent for Focus Android.  

The legacy client ID needs to be added to the glean deletion request.  

### Acceptance Criteria (how do I know when I’m done?)
When the user opts out of telemetry collection, the users glean data and any data associated with the legacy client ID are deleted.

**Comment by chutten** [comment]
This has been done in the mentioned PR! https://github.com/mozilla-mobile/focus-android/blob/main/app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt#L67
