### ISSUE TITLE
Horizontal mode UI/UX

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#49]

**Comment by pocmo** [comment]
This is going to be the same as the tablet version (#44). So I'll close this one here.

**Comment by pocmo** [comment]
Reopening: The UX is the same but technically it's a bit more challenging to support two different layouts on the same device (portrait vs. landscape) with our current configuration. So that's not part of #44.

**Comment by lobontiumira** [comment]
Can this ticket be closed?

**Comment by pocmo** [comment]
👍
