### ISSUE TITLE
[Bug] Search hint and suggestions are broken

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4909]
## Steps to reproduce
1. Enable search suggestions
2. Type in the search bar and check the search hint and the search suggestions.
### Expected behavior
Search hint and suggestions are displayed.
### Actual behavior
No search hint or suggestions displayed.
The automation test `enableSearchSuggestionOnFirstRunTest` started failing with this commit: https://github.com/mozilla-mobile/focus-android/commit/5f86cbfcbae2ce2f60b826b521abe09f4fd3804d
### Device information

* Android device: Pixel 2, Android 10
* Focus version: Debug 5/26

cc: @jonalmeida

**Comment by jonalmeida** [comment]
Interesting.. I'm guessing something internal to the gradle plugin. In the commit referenced, we were upgrading the latest version that is also [used in Fenix](https://github.com/mozilla-mobile/fenix/blob/master/buildSrc/src/main/java/Dependencies.kt#L11).

I also don't have permissions to see the Firebase runs in the linked PR (will get that fixed soon).

**Comment by sv-ohorvath** [comment]
This was fixed already. Closing.
