### ISSUE TITLE
Cannot add Ecosia as search engine

### ISSUE THREAD

**Issue by caugner** [mozilla-mobile/focus-android#4914]
## Steps to reproduce

1. Open settings and go to "Search" settings.
2. Add search engine and set name to "Ecosia". 
3. Use `https://www.ecosia.org/search?q=%s` as "Search string to use". 

### Expected behavior

Focus should allow adding Ecosia with those parameters.

### Actual behavior

Focus rejects the input: `Server not found`

![Screenshot_20210531-225522](https://user-images.githubusercontent.com/495429/120241885-f7cead00-c263-11eb-9b51-b961fe9a0e0d.png)

### Device information

* Android device: Fairphone FP3
* Focus version: `8.15.3 (Build #351242344 🦎 88.0.1-20210504152106)`

PS: Disconnecting from my VPN didn't solve the issue either. 
PPS: Removing the protocol, as the example suggests, didn't solve the issue either.

**Comment by cadeyrn** [comment]
Dupicate of #4738 and #4817, it is already fixed in the main branch by #4761, but it's not yet fixed in the 8.x branch.

**Comment by kbrosnan** [comment]
Closing as a duplicate

**Comment by caugner** [comment]
Oops, so sorry about that, I thought I was using Focus Nightly (which I obviously don't) and thus neglected the duplicate check (plus GitHub didn't suggest them to me on mobile, ouch).

Glad to hear the issue is already fixed! 🚀
