### ISSUE TITLE
Manage sites page in autocomplete settings has wrong background colours

### ISSUE THREAD

**Issue by edaigle** [mozilla-mobile/focus-android#4916]
## Steps to reproduce
1. Launch Focus and go to Settings -> Search -> URL Autocomplete -> Manage Sites
2. Observe the background and toolbar colours

### Expected behavior
The background and toolbar colours match those in the other the settings pages (photonInk).

### Actual behavior
The background and toolbar are grey. The problem continues on navigating to the "add custom URL" page.

![Screenshot](https://user-images.githubusercontent.com/8319652/120520531-e5f32400-c3a1-11eb-956c-04f68715d0a7.png)

### Device information
* Android device: Pixel 3 running Android 11
* Focus version: #1190 from main

**Comment by ionutbedregeanu** [comment]
Can't reproduced anymore
