### ISSUE TITLE
Add Noodle Shape as Focus background

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4923]
Designs refer to here: https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/MVP---iOS%2FAndroid---Product-UI

**Comment by ionutbedregeanu** [comment]
I want to work on this

**Comment by ionutbedregeanu** [comment]
New design: https://www.figma.com/file/jgsM2hWimZbPmtUJn7IGIB/Focus-Landing-Page-Design-(Kate)?node-id=1648%3A87291

**Comment by lobontiumira** [comment]
Verified on the 93.0 (build 11 GV 92.0a1-20210730093652) with Google Pixel (Android 10):

![noodle](https://user-images.githubusercontent.com/40694158/128199246-43e24775-c54b-4473-b3c4-ccf4adaa5b63.png)
