### ISSUE TITLE
Splash: Update Splash screen design

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4924]
- Add the shield icon (Tracking Protection) to the left of the URL bar 
- Update Focus Icon
- Keyboard

Implement Dark Mode. 

https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/MVP---iOS%2FAndroid---Product-UI?node-id=804%3A11

**Comment by ionutbedregeanu** [comment]
All ticket changes are implemented behind a feature flag(FeatureFlags.isMvp).
FeatureFlags.isMvp = true -> mvp changes are visible
FeatureFlags.isMvp = false -> mvp changes are hidden

**Comment by lobontiumira** [comment]
Hi all!
I've verified with Google Pixel (Android 10), on the latest Debug build 8.13.1 (1191.0a1-20210705095222) that contains the latest modifications, and here are my findings:
* the search field has no ETP icon when there is no page loaded,
* the ETP icon is not as in Figma,
* there is no space between the search field and the three-dot menu, as in Figma,
* there is no dark mode by default,
* the "What's new" option is not moved to "Settings":

![Untitled](https://user-images.githubusercontent.com/40694158/126646956-5a6e18cd-d40d-4018-806a-20f5dfebf5f8.png)

@pocmo I understood you can help us with more details regarding the search bar design, as it will be like it is now in Fenix.
I'll move the issue back to "In Development" until further notice.
Thank you!

**Comment by ionutbedregeanu** [comment]
Dark mode background its implemented by [4923](https://github.com/mozilla-mobile/focus-android/issues/4923)

**Comment by ionutbedregeanu** [comment]
Meanwhile almost all changes mentioned by @lobontiumira were made, except the logo update.
I will make  a new pr for that

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main 8/24 with Lenovo Tab M10 (Android 10), and the TP icon has the new UI, as in Figma. Tapping on it, displays the tracking protection panel:

![TP icon](https://user-images.githubusercontent.com/40694158/130610750-47a2613e-1620-4081-a66a-377d82821227.png)

@amedyne in Settings -> Privacy & Security the section is "Tracking Protection", but in the tracking protection panel is displayed as "Enhanced Tracking Protection". Should I address this in #4931 ?
Thank you!

**Comment by amedyne** [comment]
Let's clarify this with @brampitoyo or @channingcarter . Please clarify if we want the string on the Settings -> Privacy & Security changed from current "Tracking Protection" to "Enhanced Tracking Protection".

**Comment by mcarare** [comment]
As a note: the copy for the tracking protection tip also mentions "tracking protection" not "enhanced tracking protection".

**Comment by brampitoyo** [comment]
@lobontiumira  Thanks for your observation! Yes. We should definitely change that Settings heading into “Enhanced Tracking Protection. The Pro Tip, also.

**Comment by lobontiumira** [comment]
Taking into consideration that #5210 was opened to address the change of the name, I'll close this issue as verified as fixed.
Thank you!

**Comment by lobontiumira** [comment]
Verified as fixed also on RC 93.1.0 with Lenovo Tab M10 (Android 10).
