### ISSUE TITLE
Browser: Implement Settings Menu and Settings sub menus

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4927]
Design: https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=804%3A961

This includes sub menus for:
- Block Cookies
- Choose Search Engine
- Manage Sites
- Language

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main from 9/1 with Samsung Galaxy Note 8 (Android 9) that:
- the "What's new" moved to the top-right corner inside Settings,
- the default search engine is highlighted,
- the "Block cookies" has the new "yes"/"no" texts,
- the "Manage sites" page has the new UI,
- the "Language" page has the new UI, but it is slightly different than in the design - I've filed #5293 for this.

![4927](https://user-images.githubusercontent.com/40694158/131625935-cbbeef17-6c16-4210-b52f-bb6df46152f5.png)

**Comment by lobontiumira** [comment]
Verified also on the latest RC 93.1.0 build with Lenovo Tab M10 (Android 10):
* the "What's new" moved to the top-right corner inside Settings,
* the default search engine is highlighted,
* the "Block cookies" has the new "yes"/"no" texts,
* the "Manage sites" page has the new UI,
* the "Language" page has the new UI.
