### ISSUE TITLE
Splash: Implement Splash screen Alerts

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4928]
https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/MVP---iOS%2FAndroid---Product-UI?node-id=903%3A4136

**Comment by ionutbedregeanu** [comment]
QA note:
All ticket changes are implemented behind a feature flag(FeatureFlags.isMvp).
FeatureFlags.isMvp = true -> mvp changes are visible
FeatureFlags.isMvp = false -> mvp changes are hidden

**Comment by lobontiumira** [comment]
Hi all,
I've verified with Google Pixel (Android 10), on the latest Debug build 8.13.1 (1191.0a1-20210705095222) that contains the latest modifications, and the "Browsing history cleared" snackbar is displayed after the user closes the opened tab/tabs by tapping the "Delete icon".

<img src="https://user-images.githubusercontent.com/40694158/126648986-ddf40688-54eb-4484-8e4b-479044b3d25d.png" width="300" height="550" />
