### ISSUE TITLE
Browser: Update Loading/Progress bar 

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4930]
### Acceptance Criteria (how do I know when I’m done?)
Conform to new design and colors.

**Comment by ionutbedregeanu** [comment]
QA note:
All ticket changes are implemented behind a feature flag(FeatureFlags.isMvp).
FeatureFlags.isMvp = true -> mvp changes are visible
FeatureFlags.isMvp = false -> mvp changes are hidden

**Comment by lobontiumira** [comment]
Verified on the debug build8.13.1 (1191.0a1-20210705095222) with Google Pixel (Android 10):

![Untitled](https://user-images.githubusercontent.com/40694158/126650226-ab9a9495-ce76-4725-9955-ea87909379a3.png)
