### ISSUE TITLE
Browser: Implement Toolbar to follow design changes

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4933]

**Comment by jonalmeida** [comment]
We should be following [this configuration](https://github.com/mozilla-mobile/fenix/blob/f198e110d7c0eabff455a028e7739bcb6f1abf3b/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt#L125) according to Arturo for combining the TP and secure icon together.

**Comment by ionutbedregeanu** [comment]
This wasn't implemented by [4530](https://github.com/mozilla-mobile/focus-android/issues/4530)?

**Comment by jonalmeida** [comment]
I think you're right that the BrowserToolbar integration gave us most of the stuff for free, but there might be some smaller differences that we could address in this ticket, if any. Otherwise, we can close. :slightly_smiling_face:

**Comment by ionutbedregeanu** [comment]
Focus toolbar seems up to date so I will close this ticket
