### ISSUE TITLE
Browser: Implement updates and changes for Find in Page, Add to HomeScreen and Context Menu screens

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4937]
### Figma
https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2133%3A282824

**Comment by ionutbedregeanu** [comment]
#### In order to not create a too large pr with mixed changes I created a [new ticket](https://github.com/mozilla-mobile/focus-android/issues/5098) for context menus updates

**Comment by lobontiumira** [comment]
Verified on the latest Debug build from main 8/24 with Lenovo Tab M10 (Android 10).
The "Find in page" option is displayed as in Figma design:
![find in page](https://user-images.githubusercontent.com/40694158/130625776-eba6b1e8-14cd-4c57-bea8-31448cf924e2.png)


The "Add to homescreen" panel is displayed as in Figma design:
![add to homescreen](https://user-images.githubusercontent.com/40694158/130625889-cf4529f0-0056-425f-bd69-dee9cff12c4a.png)

**Comment by lobontiumira** [comment]
Verified as implemented also on the RC 93.1.0 with Lenovo Tab M10 (Android 10).
The "Find in page", and "Add to Homescreen" are as in the Figma design:

![4937](https://user-images.githubusercontent.com/40694158/135231495-fc8b4aa1-ffe4-4d07-bb2a-9fd297de3af4.png)
