### ISSUE TITLE
LightMode: Splash Screen Alerts

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4941]
Implement light mode for Alerts.

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main from 10/11 version 95.0 (build 11 GV 95.0a1-20211005094529) with Google Pixel (Android 10):

![alerts](https://user-images.githubusercontent.com/40694158/136769815-6550d338-1f31-4fa3-be75-395eea053bd6.png)

It appears that:
* the "Saved and shared images will not be deleted when you erase Firefox Focus history" message from the context menu, and
* the "Powered by Firefox Focus" from the custom tab's menu 

don't match the Figma design.

![figma](https://user-images.githubusercontent.com/40694158/136770172-c37051a0-c972-4b2e-a969-f97f04c1519e.jpg)

@jonalmeida should I file a new issue for the discrepancies?
