### ISSUE TITLE
Light Mode: Menus

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4942]
This task should cover Light mode updates for color scheme, icons:
- 3dot Home/Splash screen Menu
- Browser 3dotMenu
- Settings Menu and sub-menu settings

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main from 10/8, build 95.0 (build 11 GV 95.0a1-20211005094529), with Google Pixel (Android 10):
* main menu - settings - there is some discrepancy between the homescreen's background color, and the submenus background color:
![main menu - settings](https://user-images.githubusercontent.com/40694158/136552772-69397f2c-6c44-41d6-a045-b6269468368d.png)

* General page:
![general](https://user-images.githubusercontent.com/40694158/136552979-1106338c-7307-4bf9-a871-6054ce65b898.png)

* Privacy & security page:
![privacy and security](https://user-images.githubusercontent.com/40694158/136553042-f7a2a2a7-efcd-484e-8813-d0af095895a7.png)

* Search page - search engines:
![search engine](https://user-images.githubusercontent.com/40694158/136553120-2ed2ed80-d9b6-4963-a78a-687c0e5dcf03.png)

* URL Autocomplete page:
![customisez URL](https://user-images.githubusercontent.com/40694158/136553227-06fe99de-f5ab-410e-84ec-a2073103e5d1.png)

* Advanced page:
![advanced page](https://user-images.githubusercontent.com/40694158/136553347-24633c4a-8ea8-42c5-aff4-1542cce82428.png)

* Mozilla page:
![mozilla page](https://user-images.githubusercontent.com/40694158/136553373-47a9d1e3-b4ee-4af8-be40-c2616a416620.png)
