### ISSUE TITLE
Browser URL bar hidden, can't be triggered back on non-scrollable pages

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4946]
## Steps to reproduce
1. Search "senglehardt test pages" on google 
2. Scroll down a bit to hide the navbar.
3. Click the first link from the google results (should be https://senglehardt.com/test/trackingprotection/test_pages/)
4. Observe the nav bar.
### Expected behavior
The navbar is shown when the page is not scrollable.
### Actual behavior
Going from a scrollable page to a non-scrollable page, the navbar is hidden and can't be triggered back by scrolling the page.
### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: debug 8.13.1 (1191.0a1-20210608091819), from 6/15

**Comment by budhirajamadhav** [comment]
Hi @pocmo, I would like to work on this issue, Can I have this one assigned on my name?
