### ISSUE TITLE
Failing to log out of websites on close/clear

### ISSUE THREAD

**Issue by WD40andTape** [mozilla-mobile/focus-android#4947]
## Steps to reproduce

Log in to any website. Completely close the browser or press the erase button. Return to the website.

### Expected behavior

The user should be logged out of the website.

### Actual behavior

The user remains logged in to the website.

### Device information

* Android device: Galaxy S7, Android 8.0.0, Samsung Experience version 9.0
* Focus version: 8.16.0

![1](https://user-images.githubusercontent.com/19304774/122066027-4e062900-cdea-11eb-871b-d98ea030fb13.jpg)
![2](https://user-images.githubusercontent.com/19304774/122066030-4e9ebf80-cdea-11eb-9f7d-628406822737.jpg)
![3](https://user-images.githubusercontent.com/19304774/122066034-4f375600-cdea-11eb-9cd9-f7901599d187.jpg)
![4](https://user-images.githubusercontent.com/19304774/122066037-4f375600-cdea-11eb-8f81-6c7a68e566dc.jpg)
![5](https://user-images.githubusercontent.com/19304774/122066039-4fcfec80-cdea-11eb-9c36-e995c02ce290.jpg)
![6](https://user-images.githubusercontent.com/19304774/122066041-50688300-cdea-11eb-8457-0089e52904f3.jpg)

**Comment by WD40andTape** [comment]
Hi @pocmo, any way to escalate this? Seems like a critical bug. It essentially undermines the main feature of Firefox Focus if cookies are kept between sessions.

**Comment by mcarare** [comment]
@WD40andTape This should be already fixed on the latest main branch.
