### ISSUE TITLE
First start page is missing subject

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-mobile/focus-android#495]
Hi.

When testing our localization the beta builds, I have noticed the app first start page looks a bit confusing, as there is no mention of the app name. I suggest to add the app logo above the texts, or update the first string to have a subject in the first sentence.
> Automatically block online trackers while you browse. Then tap to erase visited pages, searches, cookies and passwords from your device.

https://people-mozilla.org/~npark/Focus_Screenshot/en-US/images/phoneScreenshots/FirstUI_View_1492724135887.html

**Comment by pocmo** [comment]
@antlam ?

**Comment by antlam** [comment]
Thanks MikkCz! 

@pocmo I don't think it's confusing. Given that the user downloaded this app themselves, and just pressed the App icon, and probably has some context around what it is before they went to go look for it on the App store, I think it doesn't need any more branding :)

**Comment by pocmo** [comment]
Okay, I'm going to close this one. However note that we might implement a new onboarding tour for v1: #497
