### ISSUE TITLE
Secure connection failed on a secure website (works on Android Firefox Release/Nightly and Firefox Desktop)

### ISSUE THREAD

**Issue by quaqo** [mozilla-mobile/focus-android#4954]
## Steps to reproduce
1. Visit the official website of the Italian Lazio Regional Health System: [https://www.salutelazio.it](https://www.salutelazio.it)
2. A "Secure Connection Failed" page is showed (this doesn't happen on Firefox Release, nor Nightly on the same device)
3. If "Accept the Risk and Continue" is clicked the connection is shown as secure (as it is on Desktop, Android Release and Android Nightly), but this might be related to #4921 

### Expected behavior
Firefox Focus should show that the connection is secure, as it is shown on Firefox Release and Nightly.

### Actual behavior
A "Secure Connection Failed" page is showed.

### Device information

* Android device: Samsung A52 (Android 11)
* Focus version: 8.16.0 (Build #351481538 / 89.0-20210527174632)

### Additional information

This doesn't happen on Focus 8.16.0 (same version) on an old Huawei Oreo device I have available.

I tried to enable USB/WiFi debug but I couldn't connect to Focus on the Samsung device, only to Nightly.

**Comment by quaqo** [comment]
I changed the title as I tested the same behaviour (showing https://www.salutelazio.it as insecure) on the device below. So it seems that the behaviour on the Huawei Oreo device is the exception, and not vice-versa.

### Device information

* Android device: Xiaomi Mi A1 (LineageOS 17.1 / Android 10)
* Focus version: 8.16.0 (Build #351481538 / 89.0-20210527174632)

**Comment by Nickoriginal** [comment]
It seems to be issue in Firefox Beta, Firefox Nightly and Firefox Focus. Firefox Stable and Google Chrome working  with this site normally.
![Screenshot_20210629-211200_Firefox Nightly](https://user-images.githubusercontent.com/85299944/123847587-6e240500-d91f-11eb-8410-f7b753503fa1.jpg)
![Screenshot_20210629-211300_Firefox Focus](https://user-images.githubusercontent.com/85299944/123847615-767c4000-d91f-11eb-901f-12c3d3ec0135.jpg)
Tested in Nightly 2021-06-28T17:31:51.595
Beta 90.0.0-beta.6
Focus 8.16.0 (Build #351481538 🦎 89.0-20210527174632)

**Comment by Nickoriginal** [comment]
Device: Samsung Galaxy A20s, ARM64

**Comment by quaqo** [comment]
Thanks for the feedback! For me it does work on Nightly 2021-06-28T17:31:51.595 though. On both aforementioned devices. I didn't try Beta. It still doesn't work on Focus.

**Comment by Nickoriginal** [comment]
Failed secure connection in a Firefox Stable at the Samsung Galaxy J2 Prime
![Screenshot_20210629-213035](https://user-images.githubusercontent.com/85299944/123851069-7716d580-d923-11eb-86af-809000eb70d3.png)
89.1.1 (Build #2015812945)

**Comment by Nickoriginal** [comment]
I think it is a web compatibility bug.

**Comment by quaqo** [comment]
> I think it is a web compatibility bug.

I can't debug it. For me it only fails on Focus... But it seems strange, I mean what's not working is at the certificate verification stage, isn't it?

Do you maybe have any hints on how could debug Focus?

**Comment by Nickoriginal** [comment]
You can debug Nightly successfully?

**Comment by quaqo** [comment]
> You can debug Nightly successfully on your Samsung?

Correct. But that doesn't give me any useful info as that website does work for me on Nightly.

Still, I'm open to suggestions!

Thanks!

**Comment by Nickoriginal** [comment]
I'll try to debug Focus on my device tomorrow.

**Comment by quaqo** [comment]
> I'll try to debug Focus on my device tomorrow.

Thank you!

**Comment by Nickoriginal** [comment]
#3745

**Comment by Nickoriginal** [comment]
Hello! I successfully debugged Focus on my device using desktop Firefox, but I don't know what info do you need. How I can provide it?

**Comment by quaqo** [comment]
Ideally I'd expect to see some kind of evaluation in the debug info during the SSL handshake/certificate validation... Are you able to isolate that section?

**Comment by Nickoriginal** [comment]
No, I have some info, but it is not useful.

**Comment by Nickoriginal** [comment]
I'm sorry about that.

**Comment by quaqo** [comment]
Thanks anyways! I guess I'll wait for somebody on the team to have more instructions. It is a very important website in Italy, especially right now with the COVID pandemic, it serves the whole Rome area (capital city), with COVID testing, vaccine info and booking, etc.

**Comment by Nickoriginal** [comment]
I can open the same bug in the Fenix repository, because I too experiencing connection issues in the Firefox

**Comment by quaqo** [comment]
> I can open the same bug in the Fenix repository, because I too experiencing connection issues in the Firefox

That makes sense. Thanks!

**Comment by mcarare** [comment]
Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1718744

**Comment by Nickoriginal** [comment]
Previously I've checked only Firefox 89.0.2, Chrome 91 and didn't confirmed this issue on desktop browsers, but now explored that ESR 78.11.0 is affected.
![2021-06-30 173957](https://user-images.githubusercontent.com/85299944/123982696-eba54f00-d9cb-11eb-9c45-590b6eb384bd.png)
![2021-06-30 174202](https://user-images.githubusercontent.com/85299944/123982806-01b30f80-d9cc-11eb-9d75-18fd6c36da5b.png)
Windows 10 20H2, x86

**Comment by Nickoriginal** [comment]
@mcarare, do you can provide a new info about this issue in the bugzilla?

**Comment by Nickoriginal** [comment]
Thanks!

**Comment by quaqo** [comment]
Wait, @Nickoriginal and @mcarare. What @Nickoriginal wrote about ESR got me thinking.

I installed a fresh copy of Firefox ESR 78, no "GlobalSign RSA OV SSL CA 2018" intermediate in about:certificate.

I visited _https://salutelazio.it/_ and got SEC_ERROR_UNKNOWN_ISSUER.

I visit another website with full intermediate chain for "GlobalSign RSA OV SSL CA 2018" such as:

_https://www.telenet.be/_

In about:certificate I got "GlobalSign RSA OV SSL CA 2018" and https://salutelazio.it/ was secure.

So I downloaded the PEM chain via curl of https://salutelazio.it/ and **is missing the intermediate certificate** so, @Nickoriginal, you were right. It's a server configuration issue: not all browser can trust the certificate without the intermediate being present in the chain!

Thanks. I'll try to contact the webmaster.

**Comment by Nickoriginal** [comment]
Preloading the intermediate certificates as described in bug 1520297 would also resolve this one automatically.

**Comment by Nickoriginal** [comment]
> I'll try to contact the webmaster.

You did it?

**Comment by quaqo** [comment]
> > I'll try to contact the webmaster.
> 
> You did it?

I did via multiple channels. No reply. It is managed by a govt contractor from what I understand, so it could take a while to have the email routed to the people able to act on it (there's no direct way to contact the tech dept).
