### ISSUE TITLE
Replace deprecated Fragment.onActivityCreated()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#4958]
* https://github.com/mozilla-mobile/focus-android/blob/main/app/src/main/java/org/mozilla/focus/fragment/AddToHomescreenDialogFragment.kt#L96
* tUrhttps://github.com/mozilla-mobile/focus-android/blob/main/app/src/main/java/org/mozilla/focus/fragment/AddToHomescreenDialogFragment.kt#L96
* tUrhttps://github.com/mozilla-mobile/focus-android/blob/main/app/src/main/java/org/mozilla/focus/fragment/AddToHomescreenDialogFragment.kt#L96tS

**Comment by sanchi0204** [comment]
Can I work on this?

**Comment by pocmo** [comment]
@sanchi0204 Yes, absolutely. Let me know if you need any help. :)
