### ISSUE TITLE
DNT (Do Not Track) header need to be disabled + WebRTC leaks need to be stopped

### ISSUE THREAD

**Issue by runboy93** [mozilla-mobile/focus-android#4962]
Years ago it was recommended to use DNT (Do Not Track) header, but as years gone pretty much none websites are respecting DNT header, more likely users are being fingerprinted instead which is privacy issue!

You have to stay up to date with security trends (for privacy specialized browser), for example you could find way to disable WebRTC leaks on Firefox Focus instead (even worse privacy issue with user fingerprinting!):
https://browserleaks.com/webrtc

My results for Firefox Focus v8.16.0

```
WebRTC Support Detection:

RTCPeerConnection | ✔ True
RTCDataChannel | ✔ True

WebRTC IP Address Detection:

Local IP Address |  leaked IP
Public IP Address |  leaked IP
IPv6 Address | leaked IP

WebRTC Media Devices:

Device Enumeration | ✔ True
Has Microphone | ✔ True
Has Camera | ✔ True
```

You can easily check here, if DNT header is enabled (1) or disabled:
https://browserleaks.com/donottrack

My results for Firefox Focus v8.16.0

```
Your Web Browser
--
Mozilla/5.0 (Android 11; Mobile; rv:89.0) Gecko/89.0 Firefox/89.0

HTTP Header method to detect Do Not Track:
DNT | 1

JavaScript ways to detect Do Not Track:
navigator.doNotTrack | 1
window.doNotTrack | undefined
navigator.msDoNotTrack | undefined
```

**Comment by pocmo** [comment]
> for example you could find way to disable WebRTC leaks on Firefox Focus instead

@agi This has come up a couple of times in the past. I do not remember what the latest take is. Is this possible with GeckoView?

> Years ago it was recommended to use DNT (Do Not Track) header, but as years gone pretty much none websites are respecting DNT header, more likely users are being fingerprinted instead which is privacy issue!

This is the default behavior for all Firefox browsers in private browsing afaik. @Amejia481 Do you know someone from the tracking protection teams to comment on this or link to any public opinion?

**Comment by Amejia481** [comment]
> > for example you could find way to disable WebRTC leaks on Firefox Focus instead
> 
> @agi This has come up a couple of times in the past. I do not remember what the latest take is. Is this possible with GeckoView?
> 
> > Years ago it was recommended to use DNT (Do Not Track) header, but as years gone pretty much none websites are respecting DNT header, more likely users are being fingerprinted instead which is privacy issue!
> 
> This is the default behavior for all Firefox browsers in private browsing afaik. @Amejia481 Do you know someone from the tracking protection teams to comment on this or link to any public opinion?

I will bring the topic to the privacy team.

**Comment by agi** [comment]
> > for example you could find way to disable WebRTC leaks on Firefox Focus instead
> 
> @agi This has come up a couple of times in the past. I do not remember what the latest take is. Is this possible with GeckoView?
> 

Not currently, but we can easily add a GeckoRuntimeSetting for it. I wouldn't be opposed if you want to do this.
