### ISSUE TITLE
java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 668 ("DefaultDispatcher-worker-1")

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#4964]
## Steps to reproduce
Start-up crashed 1x when `duplicateCustomUrlNotAllowedTest` ran

### Device information

* Android device:  Pixel 2, Virtual, API Level 29 - Cuttlefish x86 
* Focus version: Debug 6/23

### Log
06-23 11:27:15.370: I/Choreographer(9151): --------- beginning of crash
06-23 11:27:15.419: E/AndroidRuntime(9151): FATAL EXCEPTION: DefaultDispatcher-worker-2
06-23 11:27:15.419: E/AndroidRuntime(9151): Process: org.mozilla.focus.debug, PID: 9151
06-23 11:27:15.419: E/AndroidRuntime(9151): java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 668 ("DefaultDispatcher-worker-1")
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.gecko.util.ThreadUtils.assertOnThreadComparison(ThreadUtils.java:110)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.gecko.util.ThreadUtils.assertOnThread(ThreadUtils.java:86)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.gecko.util.ThreadUtils.assertOnUiThread(ThreadUtils.java:77)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.geckoview.GeckoRuntime.setDelegate(GeckoRuntime.java:553)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at mozilla.components.browser.engine.gecko.GeckoEngine.<init>(GeckoEngine.kt:104)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at mozilla.components.browser.engine.gecko.GeckoEngine.<init>(GeckoEngine.kt:75)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.focus.components.EngineProvider.createEngine(EngineProvider.kt:37)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.focus.Components$engine$2.invoke(Components.kt:81)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.focus.Components$engine$2.invoke(Components.kt:57)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.focus.Components.getEngine(Unknown Source:2)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.focus.Components$store$2.invoke(Components.kt:117)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.focus.Components$store$2.invoke(Components.kt:57)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.focus.Components.getStore(Unknown Source:2)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at org.mozilla.focus.telemetry.GleanMetricsService$collectPrefMetrics$1.invokeSuspend(GleanMetricsService.kt:84)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
06-23 11:27:15.419: E/AndroidRuntime(9151): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
06-23 11:27:15.440: I/libglean_ffi(9151): glean_core::upload: No more pings to upload! You are done.
06-23 11:27:15.450: I/WM-WorkerWrapper(9151): Worker result SUCCESS for Work [ id=9a687c21-dbdb-4064-91c0-8bb2ee287ad9, tags={ mozilla.telemetry.glean.scheduler.PingUploadWorker, mozac_service_glean_ping_upload_worker } ]
06-23 11:27:15.453: I/Process(9151): Sending signal. PID: 9151 SIG: 9
06-23 11:27:15.462: I/DropBoxManagerService(1530): add tag=data_app_crash isTagEnabled=true flags=0x2
06-23 11:27:15.473: W/BroadcastQueue(1530): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-23 11:27:15.473: W/BroadcastQueue(1530): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-23 11:27:15.522: I/RoleUserState(1530): Wrote roles.xml successfully
06-23 11:27:15.532: I/Zygote(1322): Process 9151 exited due to signal 9 (Killed)
06-23 11:27:15.541: D/NuPlayerDriver(1431): NuPlayerDriver(0xeb32a180) created, clientPid(1699)
06-23 11:27:15.544: I/Codec2Client(1431): Creating a Codec2 client to service "software"
06-23 11:27:15.545: I/Codec2Client(1431): Client to Codec2 service "software" created
06-23 11:27:15.603: D/GenericSource(1431): FileSource remote
06-23 11:27:15.614: I/ActivityTaskManager(1530): Displayed org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity: +1s262ms
06-23 11:27:15.625: I/MediaFocusControl(1530): requestAudioFocus() from uid/pid 10089/1699 clientId=android.media.AudioManager@82fc804 callingPack=com.android.systemui req=3 flags=0x0 sdk=29
06-23 11:27:15.712: V/AvrcpMediaPlayerList(1682): mPackageChangedBroadcastReceiver: action: android.intent.action.PACKAGE_CHANGED
06-23 11:27:15.712: D/AvrcpMediaPlayerList(1682): Name of package changed: org.mozilla.focus.debug
06-23 11:27:15.716: I/RoleManagerService(1530): Granting default permissions...
06-23 11:27:15.733: W/SmsApplication(1910): Package com.google.android.talk lacks required manifest declarations to be a default sms app:  mPackageName: com.google.android.talk mSmsReceiverClass: com.google.android.apps.hangouts.sms.SmsDeliverReceiver mMmsReceiverClass: com.google.android.apps.hangouts.sms.MmsWapPushDeliverReceiver mRespondViaMessageClass: null mSendToClass: com.google.android.apps.hangouts.phone.BabelHomeActivity mSmsAppChangedClass: null mProviderChangedReceiverClass: null mSimFullReceiverClass: null mUid: 10068
06-23 11:27:15.744: D/ConnectivityService(1530): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=52, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10133] ], android.os.BinderProxy@556b160)
06-23 11:27:15.746: W/WindowManager(1530): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@b4fa0bd
06-23 11:27:15.748: I/WindowManager(1530): WIN DEATH: Window{fdb64a0 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity}
06-23 11:27:15.751: I/ActivityManager(1530): Process org.mozilla.focus.debug (pid 9151) has died: fore TOP 
06-23 11:27:15.752: I/VSoCGrallocRegionRegistry(1385): Unmapped gralloc-1342.67 hnd=0xe6bcdf40 fd=62 base=0xe32cb000
06-23 11:27:15.752: I/VSoCGrallocRegionRegistry(1385): Unmapped gralloc-1342.66 hnd=0xe6bcdf80 fd=61 base=0xe42bf000
06-23 11:27:15.752: I/libprocessgroup(1530): Successfully killed process cgroup uid 10133 pid 9151 in 0ms
06-23 11:27:15.752: D/ConnectivityService(1530): releasing NetworkRequest [ TRACK_DEFAULT id=52, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10133] ] (release request)
06-23 11:27:15.766: D/CarrierSvcBindHelper(1910): No carrier app for: 0
06-23 11:27:15.769: W/InputDispatcher(1530): channel 'fdb64a0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-23 11:27:15.769: E/InputDispatcher(1530): channel 'fdb64a0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-23 11:27:15.769: W/InputDispatcher(1530): Attempted to unregister already unregistered input channel 'fdb64a0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)'
06-23 11:27:15.776: W/ActivityManager(1530): Scheduling restart of crashed service

**Comment by sv-ohorvath** [comment]
2 other automated UI tests failed with this crash:
org.mozilla.focus.activity.SafeBrowsingTest.unblockSafeBrowsingTest
org.mozilla.focus.activity.CustomTabTest.testCustomTabUI
[Firebase log](https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5048718455637267608/executions/bs.7dd6269801380449/testcases/1/logs)

[Text logs](https://github.com/mozilla-mobile/focus-android/files/6791875/focus-crash.txt)

**Comment by AndiAJ** [comment]
Flaky 1x `openCustomTabInFocusTest` [Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7043519714839398539/executions/bs.c9bbcdf9d1426c1b/testcases/1/logs)

**Comment by AndiAJ** [comment]
Flaky 1x `openYourRightsPageTest` on Main 8/8 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6066125213718826339/executions/bs.4e24193445257f9d/testcases/1/logs)

**Comment by sv-ohorvath** [comment]
The last occurrence was on Oct 2021, I'll close this as not reproducible and can be reopened if it appears again.
