### ISSUE TITLE
String "Erase and open %1$s" is incorrectly showed in the menu after long tapping on the Focus icon

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/focus-android#4973]
## Steps to reproduce
1. Long tap on the Focus app icon in the app menu.
2. Look at the string "Erase and open %1$s" in the opened menu.
### Expected behavior
String "Erase and open %1$s" should be correctly handled, like "Erase and open" and "Стереть и открыть".
### Actual behavior
String "Erase and Open %1$s" is not correctly handled, shows "Erase and Open %1$s" and "Стереть и открыть %1$s" for Russian locale.
<img src = https://user-images.githubusercontent.com/85299944/124819895-7dd1c800-df75-11eb-8b9c-1207c524b0ee.jpg width = 45%> <img src = https://user-images.githubusercontent.com/85299944/124819818-698dcb00-df75-11eb-8531-be776f0b3b82.jpg width = 45%>
### Device information
* Android device: Samsung Galaxy A20s, Android 10, One UI 2.0
* Focus version: 8.17.1 (Build #351931837 🦎 90.0-20210705185941)

**Comment by Nickoriginal** [comment]
More locales can be affected, so feel free to complement my list in comments (better with screenshots)

**Comment by Nickoriginal** [comment]
More locales can be affected, so feel free to complement my list in comments.

**Comment by Nickoriginal** [comment]
As I can see here https://pontoon.mozilla.org/en-CA/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?string=209886, %1$s is a parameter in strings, what should be replaced by the adjustable word during application processing (usually). It fails to do so in this menu.

**Comment by Nickoriginal** [comment]
Reproducible in Focus 8.18.0-rc.1 on Samsung Galaxy A20s (Android 11).

**Comment by mcarare** [comment]
@brampitoyo The simpler solution is to change the long label that contains a placeholder with the app name. The shortcut is implemented statically so we cannot insert the app name in the string. Is this acceptable from  UX point of view?

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest debug build from main 8/30 and 93.0.0.
### Devices used:
- Oppo Find X3 Neo (Android 11)
- OnePlus 6T (Android 9)
