### ISSUE TITLE
8.17.0 version missing APKs?

### ISSUE THREAD

**Issue by runboy93** [mozilla-mobile/focus-android#4979]
8.17.0 doesn't have .apk files on releases?

**Comment by Nickoriginal** [comment]
I think they will be available later.

**Comment by runboy93** [comment]
NVM found unsigned

**Comment by Nickoriginal** [comment]
Thanks! I thought it was about APKs provided here, on Github (in addition, they are signed there), because it is important source for me and some other users, who didn't know about this site. However, I'll track their availability here.

**Comment by Nickoriginal** [comment]
I realized what it was about GitHub APKs.

**Comment by Nickoriginal** [comment]
Resolved for 8.17.0 and 8.17.1
<img src = https://user-images.githubusercontent.com/85299944/125398733-5c7b3c80-e3b8-11eb-9e27-d3968d195bfe.jpg width = 35%>
