### ISSUE TITLE
Implement Beta Channel Dark Mode

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4992]
Implement Beta channel Landing screen design for Light and Dark Mode

- [ ] Logo 
- [ ] Landing page

**Comment by amedyne** [comment]
latest designs: https://www.figma.com/file/jgsM2hWimZbPmtUJn7IGIB/Landing-Page?node-id=1941%3A61459

**Comment by lobontiumira** [comment]
Verified on the latest beta build 93.0 (GV 93.0a1-20210831093704) with Google Pixel (Android 10):

![Beta Dark](https://user-images.githubusercontent.com/40694158/131858760-56e0310e-99cc-4197-b45a-314d32b24393.png)
