### ISSUE TITLE
Show lock icon for secure https sites

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#5]
Currently we show the lock icon whenever we are displaying a https URL. That's not ideal. The code should look at the certificate to determine whether this is a secure connection. Basically the same we do for displaying a "green lock" in Fennec.

It probably makes sense to wait until we switch to GeckoView before implementing this.

**Comment by ahunt** [comment]
For the webview it looks like we can use:
https://developer.android.com/reference/android/webkit/WebView.html#getCertificate()

We'll also want to handle SSL errors somehow:
https://developer.android.com/reference/android/webkit/WebViewClient.html#onReceivedSslError(android.webkit.WebView,%20android.webkit.SslErrorHandler,%20android.net.http.SslError)

**Comment by pocmo** [comment]
That's what we already do. I think we can close this. :)

(It's not implemented for the Gecko build yet, but so are a lot of other things)
