### ISSUE TITLE
Shortcuts: Implement workflow to Remove/Delete shortcuts

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#5003]
Implement workflow to Remove/Delete shortcuts.
https://www.figma.com/file/KggJlo8pg2T2Q8nn0Ec5c3/Shortcuts?node-id=1830%3A46874

**Comment by jonalmeida** [comment]
E3 because there are two delete options. One as a BrowserMenu overlay when you long-press a shortcut on the homescreen, and another in the three-dot menu.

**Comment by gabrielluong** [comment]
Fixed #5001
