### ISSUE TITLE
Update feature flag "isMvp"

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#5004]
### Why/User Benefit/User Problem
It helps QA team to see the mvp changes without manually updating the flag
### What / Requirements
Update const val isMvp = false/true to var isMvp = BuildConfig.BUILD_TYPE.contains("debug")

**Comment by ionutbedregeanu** [comment]
Note for QA: After this patch you should be able to see all mvp changes on DEBUG build

**Comment by lobontiumira** [comment]
Verified on the debug build 8.13.1 (1192.0a1-20210721092353) with Google Pixel (Android 10).
