### ISSUE TITLE
Build and target SDK 30+ (11.0+)

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#5009]
Similar to https://github.com/mozilla-mobile/focus-android/issues/2909 we should update to 30 (or eventually 31)..

### Why/User Benefit/User Problem

* It will be a requirement for using new OS features
* The longer we stay behind the harder it gets to update

### What / Requirements

* [ ] Update build.gradle files
* [ ] Build and run tests to see if there are issues that need to be fixed

**Comment by pocmo** [comment]
I did update to SDK 30 with Jetpack Compose (was needed):
https://github.com/mozilla-mobile/focus-android/commit/6caa9468a4906675378a4bef9f9ad12bbb7c6bca

**Comment by jonalmeida** [comment]
Thanks!
