### ISSUE TITLE
The GV icon is missing in the "About" page

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5011]
## Steps to reproduce
1. Install Focus 8.18.0-rc.1.
2. Go to Settings - Mozilla - About Firefox Focus, and observe the GV version.

### Expected behavior
The GV version is displayed with an icon.

### Actual behavior
The GV version is following the build version, hard to read them separately - please see the screenshot below.

### Device information
* Android device: all
* Focus version: 8.18.0-rc.1

![gv](https://user-images.githubusercontent.com/40694158/127100014-84125277-81f5-404e-bb73-6d6ac0780a8c.jpg)

**Comment by Nickoriginal** [comment]
Reproducible in 8.18.0-rc.1 on Samsung Galaxy A20s, Android 11.

**Comment by Nickoriginal** [comment]
Comparison with 8.17.1:
<img src = https://user-images.githubusercontent.com/85299944/127203037-5d58f8c3-14a6-411f-959f-9b152b7466ff.png width = 45%>

**Comment by cadeyrn** [comment]
The icon was removed as part of the refactoring in be56599d04385a506c24684db705dd9b80122a10. I don't know if it was removed on purpose, but Fenix no longer uses the icon either.

**Comment by Nickoriginal** [comment]
> The GV version is following the build version, hard to read them separately

This icon was something like pointer, simplifying separation, viewing and analysis of "About Firefox Focus" internal info.

**Comment by Nickoriginal** [comment]
In Fenix GV version is listed in a separate line, but in Focus it is mixed with rest.

**Comment by cadeyrn** [comment]
I am aware of that. I mentioned what was done in Fenix because it raises the question of whether the desired solution is to reintroduce the icon or to format the information in a similar way to Fenix.

**Comment by lobontiumira** [comment]
Verified as fixed on the 91.1.0 Firefox Focus build, with Google Pixel (Android 10).
