### ISSUE TITLE
The tracking protection of a page cannot be enabled back until deleted from Exceptions

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5012]
## Steps to reproduce
1. Open a page.
2. From the three-dot menu, disable the tracking protection - the page reloads with the tracking protection icon cut.
3. From the three-dot menu, enable the tracking protection.

### Expected behavior
The page reloads with the tracking protection icon uncut, and the tracking protection toggle ON.

### Actual behavior
The page reloads with the tracking protection icon still cut, and the tracking protection toggle is still OFF.

### Device information
* Android device: HTC 10 (Android 8), Google Pixel (Android 10)
* Focus version: 8.18.0-rc.1

https://user-images.githubusercontent.com/40694158/127102374-e0f28055-f4c9-4e5d-a026-ae6202de3bdd.mp4

**Comment by mcarare** [comment]
@amedyne This looks like something we want to fix before we ship #4931 because it affects the same functionality we agreed to implement for the ETP toggle.

**Comment by Amejia481** [comment]
I'm taking a look I'll keep the issue posted

**Comment by mcarare** [comment]
@Amejia481 I fixed this issue for the etp panel in this commit: https://github.com/mozilla-mobile/focus-android/pull/5019/commits/3f1cf8f820bd818b80eca5572f081360048fd1be.
It also fixes the list persistence between app runs.  Let me know if there is a better approach.

**Comment by pocmo** [comment]
@mcarare Can you move this to a separate PR, so that we can review it independently? :)

**Comment by pocmo** [comment]
Opened PR #5061 to update A-C, which should come with a fix for this.

**Comment by lobontiumira** [comment]
Verified as fixed on the 91.1.0 build with Google Pixel (Android 10), and OnePlus 5T (Android 10).
