### ISSUE TITLE
The search bar is not active, and the keyboard is not triggered when leaving the search field empty and tap "Go"

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5013]
## Steps to reproduce
1. Tap on the search field, in order to trigger the keyboard.
2. Tap on "Go".

### Expected behavior
Nothing happens, the keyboard is still trigerred, the search field is empty and the focus is on it.

### Actual behavior
The keyboard is dismissed, the focus is not in the search field anymore.

### Device information
* Android device: HTC 10 (Android 8), Google Pixel (Android 10)
* Focus version: 8.18.0-rc.1
* Not reproducible on 8.17.1 build

https://user-images.githubusercontent.com/40694158/127109884-46c4cd46-8d31-474d-942b-cfde7b12efce.mp4

**Comment by Nickoriginal** [comment]
Reproducible in 8.18.0-rc.1 on Samsung Galaxy A20s (Android 11) with Samsung Keyboard 5.2.60.0.

**Comment by lobontiumira** [comment]
Verified as fixed on the 91.1.0 Firefox Focus build, with Google Pixel (Android 10).
