### ISSUE TITLE
The "Open this PDF File" link from rpappalax.github.io/testapp doesn't open anymore

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5014]
## Steps to reproduce
1. Go to test web page: https://rpappalax.github.io/testapp.
2. Scroll the page to "Open PDF File" section and tap on the "Open this PDF File" link.

### Expected behavior
The https://github.com/rpappalax/testapp/blob/master/lorem_ipsum2.pdf page opens.

### Actual behavior
Nothing happens.

### Device information
* Android device: HTC 10 (Android 8), Google Pixel (Android 10)
* Focus version: 8.18.0-rc.1
* Not reproducible on 8.17.1 build

**Comment by lobontiumira** [comment]
This issue still reproduces on 91.1.0 build with Google Pixel (Android 10).

**Comment by rpappalax** [comment]
@lobontiumira Mira, I've moved the page into the mozilla-mobile github org and fixed this error.  If you run into further issues with the page, just post an issue directly against the test page repo:
https://mozilla-mobile.github.io/testapp/
https://github.com/mozilla-mobile/testapp
