### ISSUE TITLE
Fix deprecated systemUiVisibility and flags

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#5016]
I am updating Focus to the latest SDK (for using Jetpack Compose) and the build is showing warning about deprecated `systemUiVisibility` and `View.SYSTEM_UI_FLAG_*` in:

* `CustomTabActivity`
* `FullscreenIntegration`
* `MainActivity`

**Comment by pocmo** [comment]
I'm going to deprecate the warnings on my branch.

@jonalmeida Did we already fix this for Fenix?

**Comment by pocmo** [comment]
The issue is closed:
* https://github.com/mozilla-mobile/fenix/issues/17804

But the `@Suppress` calls are still there:
* https://github.com/mozilla-mobile/fenix/blob/4dd4e3598227a346fd7013b1aef6eee1caf08a2c/app/src/main/java/org/mozilla/fenix/ext/Activity.kt#L40

**Comment by jonalmeida** [comment]
> But the `@Suppress` calls are still there:
> 
>     * https://github.com/mozilla-mobile/fenix/blob/4dd4e3598227a346fd7013b1aef6eee1caf08a2c/app/src/main/java/org/mozilla/fenix/ext/Activity.kt#L40

Ah yes, it came back in because some of the Android 11 targetting changes had been backed out and we were seeing weird bugs without it. It looks we updated to Android 11 again but we didn't land the removal of this code and use the AC extensions.
