### ISSUE TITLE
Can't select/delete/edit the URL link after searching on Google/other search engines

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#5020]
## Steps to reproduce
1. Search something random on Google. 
2. Tap on URL bar to enter in edit mode.

### Expected behavior
The URL is selected and the link can be deleted.

### Actual behavior
The link can't be selected and the page is reloading.

### Device information
* Android device: Huawei P40 Lite (Android 11). 
* Focus version: Focus version: 8.18.0-rc.1.
* Not reproducible using direct URL (e.g. cnn.com).

https://user-images.githubusercontent.com/58466444/127169731-073d4290-cf0a-4a79-965a-fd72f6cfda90.mp4

**Comment by Nickoriginal** [comment]
Not reproducible in 8.18.0-rc.1 (build #35207182591.0a1-20210705095222) on Samsung Galaxy A20s (Android 11). Other search engines working fine to me.

**Comment by pocmo** [comment]
I just ended up in this state once while testing something else. Clicking on the "erase" icon, causes the same: A reload of the current page. 🤔 I wonder if this somehow is caused by our navigation state and the fragments getting out of sync...

**Comment by pocmo** [comment]
Okay, can reproduce this reliably now. Will investigate it now.

**Comment by sflorean** [comment]
Tested with Huawei P40 Lite (Android 11) and made some exploratory testing, on Focus 91.1.1 and I didn't see the issue again.
