### ISSUE TITLE
(regression) keyboard keeps open if you close Firefox Focus

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#5023]
### Steps to reproduce

1. open Firefox Focus
2. press the Android home button

### Expected behavior

Firefox Focus closes, you see your Android home screen and the keyboard is closed.

### Actual behavior

Firefox Focus closes, you see your Android home screen but the keyboard is still open. This is a regression in Firefox Focus 8.18.0. The issue is not present in Firefox Focus 8.17.1.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 11 (Android 11)
* Focus version: self compiled from tag v8.18.0

**Comment by cadeyrn** [comment]
@pocmo It's a regression from c20a52c95914e74cf5f46d1cec9428b896721cc2 - "Integrate browser-toolbar component"

**Comment by mcarare** [comment]
@cadeyrn Can you still reproduce this on main? Thank you!

**Comment by cadeyrn** [comment]
@mcarare Yes, it's still an issue with the latest code from the main branch. But applying PR #5038 fixes the issue.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the 91.1.0 Focus build using Google Pixel (Android 10), and OnePlus 5T (Android 10).
