### ISSUE TITLE
Understand why focus app updates are so small compared to fenix

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#5031]
On the GPlay dashboard, the release version of Focus has very small app update downloads:
![image](https://user-images.githubusercontent.com/759372/127576149-f6a9d9a7-7a80-4939-86d0-f5faf0ea4cbf.png)

Compared to fenix:
![image](https://user-images.githubusercontent.com/759372/127576181-27ece230-d053-4c16-b911-c18b51d41397.png)

Focus updates are in the 1's of MB compared to 10's in fenix. We should figure out why. That being said, _the dashboard does not indicate how it calculates this difference_ so we may not find anything actionable. Theories:
- (actionable) Focus GV is packaged in a different way from fenix GV and packaging fenix the same way could save tremendously on app update download size
- (unactionable) The aggregation method used by Google looks at downloads over all time. On average, updates have been smaller in fenix hence the visualization
- (unactionable) The aggregation only looks at recent app versions and recent app updates to fenix may not have changed GV (or only a small part of GV changed) so the app updates are small

**Comment by mcomella** [comment]
@jonalmeida @pocmo Do you have ideas why this might be? I'm particularly curious if you've changed anything with the recent updates that might change this.

**Comment by jonalmeida** [comment]
What data range is used to plot these graphs? I suspect that it may be based on the last release of Focus, which was a patch release instead of a GV upgrade.

Another consideration is that in Focus, we haven't yet (until 8.18) published a build that used app services' before, so maybe Google's magical (to me at least) tools can't diff and serve up a binary blob like that one?

**Comment by MarcLeclair** [comment]
Triage: We'll wait for the next GV release to see if the app size difference is still there.

**Comment by mcomella** [comment]
We checked again and Focus has a large download size:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/759372/132583560-a3de06a3-180c-4cd7-a79a-8f783779652e.png">

So this was a fluke – it appears the GPlay data might just be pulling from the last release. Closing.
