### ISSUE TITLE
ETP icon in Firefox Focus 8.18.0-rc.1 doesn't match Proton UI

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/focus-android#5040]
In the Firefox Focus 8.18.0-rc.1 an ETP icon was added into the address bar.

It has been used in Firefox 88 and below, doesn't match Proton UI design for Firefox.

ETP icon looks inconsistent compared with new updated secure lock icon, located nearby.

It should be replaced with current fresh ETP icon or entirely hidden (to match Firefox Focus 8.17.1 and below) because it doesn't contain any useful info.

| Expected behaviour | Actual behaviour |
| - | - |
| Focus 8.17.1 | Focus 8.18.0-rc.1 |
| <img src = https://user-images.githubusercontent.com/85299944/127690759-6fc35aac-e0a0-49a1-8b26-7bb02d391e53.png width = 100%> | <img src = https://user-images.githubusercontent.com/85299944/127691100-7b915cc0-66f8-4480-979f-55cf7355c6a3.png width = 100%> |

**Comment by pocmo** [comment]
This is kind of expected from the integration of the `browser-toolbar` component from A-C, by default it shows a TP and security icon. We could hide the TP icon, but showing the state of TP (on/off) may make sense for now: The old UI showed an overlay over the menu button, that we are not able to support with the component.

This is not the new UI yet - merely an intermittent state in 91/92, until the new UI gets released in 93.

CC @brampitoyo

**Comment by Nickoriginal** [comment]
Resolved in the Focus Nightly 93.0a1 and further builds.
<img src = https://user-images.githubusercontent.com/85299944/133878561-38e5816c-85c9-4308-ba0f-a5b0585d1dd5.jpg width=45%>
