### ISSUE TITLE
Hide icons in the Focus "Settings" menu

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/focus-android#5041]
### Why
In the Firefox 89 icons in the "Settings" app menu were hidden to simplify the settings view. Firefox Focus doesn't match this behaviour. Bringing additional fenix-parity by hiding these icons will improve user experience on both browsers.
### Requirements
Hide in-app icons near parameters in "Settings" menu.
<img src = https://user-images.githubusercontent.com/85299944/127744081-aa8f717f-c9fe-4052-9755-2ff9dbd4ec25.png width = 45%> <img src = https://user-images.githubusercontent.com/85299944/127744074-c0624406-0f78-44bb-bbfe-26cf7f32e2a5.png width = 45%>

**Comment by sanchi0204** [comment]
Can I work on this?

**Comment by cadeyrn** [comment]
This was already done in #5090.

**Comment by Nickoriginal** [comment]
@cadeyrn, thanks, I hope it will be closed very soon!

**Comment by cadeyrn** [comment]
@Nickoriginal AFAIK the new design is planned for Firefox Focus 93.

**Comment by Nickoriginal** [comment]
Resolved in the Firefox Focus nightly build 93.0a1, as mentioned @cadeyrn and further builds.
