### ISSUE TITLE
Create a smoke tests suite/class

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5052]
Have a test class / annotate tests that are set as Smoke & Sanity type in the Full functional suite in [TestRail](https://testrail.stage.mozaws.net/index.php?/suites/view/1028&group_by=cases:section_id&group_order=asc&group_id=51560).

Then we can run the tests locally on release builds.

**Comment by sv-ohorvath** [comment]
The solution I've found is to create a custom annotation class ([source:]( https://evanfang.medium.com/run-specific-android-espresso-tests-by-creating-custom-annotations-using-kotlin-and-command-line-6a90e8728e3b)) and annotate the tests I want to include.
Then we can run locally the smoke tests only, using this terminal command:

For release: `gradlew app:connectedAndroidTest -PtestBuildType=release -PdisableOptimization -Pandroid.testInstrumentationRunnerArguments.annotation=org.mozilla.focus.testAnnotations.SmokeTest
`

For debug: `gradlew app:connectedAndroidTest -PtestBuildType=debug -PdisableOptimization -Pandroid.testInstrumentationRunnerArguments.annotation=org.mozilla.focus.testAnnotations.SmokeTest
`

**Comment by AaronMT** [comment]
Flank supports annotations too (doc @ https://flank.github.io/flank/ )


### Test Targets
  ## A list of one or more test target filters to apply (default: run all test targets).
  ## Each target filter must be fully qualified with the package name, class name, or test annotation desired.
  ## Supported test filters by am instrument -e … include:
  ## class, notClass, size, annotation, notAnnotation, package, notPackage, testFile, notTestFile
  ## See https://developer.android.com/reference/android/support/test/runner/AndroidJUnitRunner for more information.
  # test-targets:
  #  - class com.example.app.ExampleUiTest#testPasses

**Comment by sv-ohorvath** [comment]
> Flank supports annotations too (doc @ https://flank.github.io/flank/ )

Great! We could make an annotation for release tests (we don't want all the smoke tests to run on beta/release builds in CI).
