### ISSUE TITLE
FADPV2-2804: Capture Telemetry for Focus "Shortcuts" / Quick Access Sites

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#5056]
https://mozilla-hub.atlassian.net/browse/FADPV2-2804

**Description**

As a Product Manager, I want to see how effective the new feature of Top Sites is on Focus so that I know if it is useful for our users. 

**Acceptance Criteria**

    Collect telemetry data for the following: 

        Do users add shortcuts to their home page? What’s the percentage of users that are adding shortcuts?

        How often are users clicking on the shortcuts?

        Are users adding one, two, three or four shortcuts to their home page? What’s the average?

        How often are users deleting a shortcut?

        How often are users adding a shortcut?

**Comment by mcarare** [comment]
waiting on #5001, #5002, #5003.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on a nightly build created from main using a Google Pixel 3a (Android 11)

STR
• Added 4 Shortcuts
• Opened each of them 2x 
• Removed 2 Shortcuts 
• The other 2 Shortcuts remained displayed on the home screen

Metrics Ping 2e293c58-4cca-4f02-bcb3-77df0c392549
✅   `"shortcuts.shortcut_added_counter": 4`
✅   `"shortcuts.shortcut_opened_counter": 8`
✅   ```"shortcuts.shortcut_removed_counter": {
            "removed_from_home_screen": 2
          }```
❌   ```"quantity": {
          "shortcuts.shortcuts_on_home_number": 0
        }```

[Logcat](https://github.com/mozilla-mobile/focus-android/files/7104466/Shortcuts.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-0903001)

Just to be 100% sure regarding the counting inconsistency for `"shortcuts.shortcuts_on_home_number"` I've made a separate run in which, added 1 shortcut, generated the metrics ping and the count remained set to 0.
Afterwards, added another shortcut, generated the metrics ping and again the count remained set to 0.

@mcarare , please review and share your thoughts ☺️ 
Thanks!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on a nightly build created from latest main using the same STR as mentioned above on a Google Pixel 3a (Android 11)

Metrics Ping b1d643b9-b90c-4431-a3c3-6b9edbd041a4
✅   `"shortcuts.shortcut_added_counter": 4`
✅   `"shortcuts.shortcut_opened_counter": 8`
✅   ```"shortcuts.shortcut_removed_counter": {
            "removed_from_home_screen": 2
          }```
✅   ```"quantity": {
          "shortcuts.shortcuts_on_home_number": 2
        }```

[Logcat](https://github.com/mozilla-mobile/focus-android/files/7105162/Srct.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-090310)
