### ISSUE TITLE
FADPV2-2806: Capture Telemetry for "What's New"

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#5058]
https://mozilla-hub.atlassian.net/browse/FADPV2-2806

**Description**

As a Product Manager, I want to understand if the repositioning of What’s New from the three dot menu to Settings causes users to click on it more or less frequently 

**Acceptance Criteria**

Capture Telemetry for:

    How many users click What’s New from the Settings menu bar?

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 93.0 (GV 93.0a1-20210831093704) with Google Pixel (Android 10).
Glean ping to URL: /submit/org-mozilla-focus/metrics/1/c61c25b9-954e-4e1c-adc9-403894e82d81

`"counter": {
          "glean.validation.foreground_count": 4,
          "settings_screen.whats_new_tapped": 1
        }`

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2109020003)
