### ISSUE TITLE
Stealth (fingerprint enable) mode issue, switch back to Focus, there is 0.2s appearing of the web-page view.

### ISSUE THREAD

**Issue by stevenleeS0ht** [mozilla-mobile/focus-android#5068]
## Steps to reproduce

Just as what it is described in fingerprint setting entry, when switching back to Focus via "Recent Apps", the web-page will appear for about 0.2s and then the fingerprint prompt will occupy the screen.

However, for extremely confidential content, such period of time can make user leak privacy information.

### Expected behavior

After leave Focus (When fingerprint stealth mode is enabled), the active web page should not show up until fingerprint is successfully validated.

### Actual behavior

When switching back to Focus, when the app windows zoom-in, the active web page will show off for about 0.2s. And then Focus become blank and fingerprint prompt will pop out.

### Device information

* Android device: Issue appears on multiple device (Smartphone, Tablet) Android 11.
* Focus version: 91.1.0

**Comment by stevenleeS0ht** [comment]
Due to the stealth mode feature, screenshot or screen recording are unable to be captured.

**Comment by stevenleeS0ht** [comment]
@pocmo and @ahunt , do you think this problem is due to Focus itself or Android OS?

**Comment by lobontiumira** [comment]
I was able to reproduce this on the 99 Focus Nightly (build 360630511 with GV 99.0a1-20220303094735) with Oppo Find X3 Lite (Android 11).

**Comment by lobontiumira** [comment]
Reproducible with Samsung Galaxy Note 8 (Android 9) on Beta 99.0.0-beta.1.

**Comment by lobontiumira** [comment]
This issue reproduces on the Focus Nightly build 104.0a1 from 7/22 on Samsung Galaxy Note 8 (Android 9).
Not reproducible on Oppo Reno 6 (Android 12).

**Comment by lobontiumira** [comment]
Reproducible on Beta 104.0b1 with Samsung Galaxy Note 8 (Android 9).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802664

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
