### ISSUE TITLE
Firefox Focus problems after last update (yesterday)

### ISSUE THREAD

**Issue by Moses4188** [mozilla-mobile/focus-android#5070]
After last update Firefox Focus:
*doesn't offer saved passwords for websites, 
*on some websites it hides the adress bar and prevents to write into it,
*sometimes it just reloads the webpage when I want to fill another web's adress and it also makes the same thing when I press the delete browsing history button at the right bottom,
*on some webpages I can see advertisements which I haven't seen before,
*on some webpages it prevents me to open buttons,
*in the adress bar it doesn't offer saved webpage suggestions
*browser crashed few times

* Android device: BlackBerry KEY2 LE
* Focus version: 91.1.0 (Build #352172102 🦎 91.0-20210804193234)

**Comment by sv-ohorvath** [comment]
@Moses4188 thank you for the report. Could you please open individual bugs for each issue with detailed steps to reproduce the problem?

**Comment by sv-ohorvath** [comment]
I started logging some of the issues I've encountered so far:
