### ISSUE TITLE
Intermittent UI test failure - <CustomTabTest.testCustomTabUI>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5076]
### Firebase Test Run: 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6066125213718826339/executions/bs.69a99e7bd1ad43d4/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6066125213718826339/executions/bs.98f96fbc96992aef/testcases/1/logs)
### Stacktrace:
08-07 23:24:51.686: D/AndroidRuntime(7465): --------- beginning of crash
08-07 23:24:51.687: E/AndroidRuntime(7465): FATAL EXCEPTION: main
08-07 23:24:51.687: E/AndroidRuntime(7465): Process: org.mozilla.focus.debug, PID: 7465
08-07 23:24:51.687: E/AndroidRuntime(7465): android.content.res.Resources$NotFoundException: Resource ID #0x7f060105
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.content.res.Resources.getColor(Resources.java:961)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.content.Context.getColor(Context.java:610)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.core.content.ContextCompat.getColor(ContextCompat.java:517)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at org.mozilla.focus.menu.browser.CustomTabMenu$menuItems$2.invoke(CustomTabMenu.kt:120)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at org.mozilla.focus.menu.browser.CustomTabMenu$menuItems$2.invoke(CustomTabMenu.kt:90)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at org.mozilla.focus.menu.browser.CustomTabMenu.getMenuItems(CustomTabMenu.kt:90)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at org.mozilla.focus.menu.browser.CustomTabMenu.access$getMenuItems(CustomTabMenu.kt:23)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at org.mozilla.focus.menu.browser.CustomTabMenu$menuBuilder$2.invoke(CustomTabMenu.kt:35)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at org.mozilla.focus.menu.browser.CustomTabMenu$menuBuilder$2.invoke(CustomTabMenu.kt:33)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at org.mozilla.focus.menu.browser.CustomTabMenu.getMenuBuilder(CustomTabMenu.kt:33)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at org.mozilla.focus.browser.integration.BrowserToolbarIntegration.<init>(BrowserToolbarIntegration.kt:81)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at org.mozilla.focus.fragment.BrowserFragment.customizeToolbar(BrowserFragment.kt:271)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at org.mozilla.focus.fragment.BrowserFragment.onViewCreated(BrowserFragment.kt:233)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:714)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.app.Activity.performStart(Activity.java:7157)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.os.Looper.loop(Looper.java:193)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at java.lang.reflect.Method.invoke(Native Method)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-07 23:24:51.687: E/AndroidRuntime(7465): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-07 23:24:51.690: E/InstrumentationResultPrinter(7465): Failed to mark test No Tests as finished after process crash
08-07 23:24:51.692: E/MonitoringInstr(7465): Exception encountered by: Thread[main,5,main]. Dumping thread state to outputs and pining for the fjords.
08-07 23:24:51.692: E/MonitoringInstr(7465): android.content.res.Resources$NotFoundException: Resource ID #0x7f060105
### Notes
❗ Seems to be a start-up crash

**Comment by sv-ohorvath** [comment]
cc @jonalmeida this started failing with [this commit](https://github.com/mozilla-mobile/focus-android/commit/7d086c0da10371aa012208ccca23c8c737ebed6b) and it's not clear to me what I need to fix it, could you please help?
