### ISSUE TITLE
Search autocomplete broken when you have a page already open

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5080]
## Steps to reproduce
1. Go to a webpage (e.g. twitter.com)
2. Tap the URL bar, start typing another URL (e.g. google)
3. Check if the browser autocompletes the URL.
### Expected behavior
The suggested URL should be filled in.
### Actual behavior
Autocomplete doesn't work.
### Device information

* Android device: Pixel 2, Android 9
* Focus version: latest 93.0 debug build from `main`

**Comment by mcarare** [comment]
This should also be fixed by https://github.com/mozilla-mobile/focus-android/pull/5085.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Focus 93.0 Debug build from main using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

►Video
![20210813-164554](https://user-images.githubusercontent.com/51314259/129366937-5c5ebebf-d67f-485b-83fc-62b81019c1af.gif)
