### ISSUE TITLE
Buggy typing when replacing an URL

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5081]
## Steps to reproduce
1. Open a webpage.
2. Tap the URL bar and type one or 2 characters.
3. Observe the typed chars.
### Expected behavior
Can type in the search bar
### Actual behavior
The first chars are getting deleted.
### Device information

* Android device: Pixel 2, Android 9
* Focus version: latest 93.0 debug build from main

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Focus 93.0 Debug build from main using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

►Video
![20210813-164125](https://user-images.githubusercontent.com/51314259/129366433-ca5006b5-95a1-414b-9223-867344ba7809.gif)
