### ISSUE TITLE
Browser page content doesn't get refreshed with a new page

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5082]
## Steps to reproduce
1. Go to a website (e.g. Facebook)
2. Tap the URL bar and type in another URL (twitter.com). Press go
3. Observe the page content after loading.
### Expected behavior
The Twitter webpage should be displayed
### Actual behavior
Still showing the initial webpage (Facebook)
### Device information

* Android device: Pixel 2, Android 9
* Focus version: latest 93.0 debug build from main
* https://github.com/mozilla-mobile/focus-android/issues/4895 started failing with [this commit](https://github.com/mozilla-mobile/focus-android/commit/7d086c0da10371aa012208ccca23c8c737ebed6b)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Focus 93.0 Debug build from main using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

►Video
![20210813-163559](https://user-images.githubusercontent.com/51314259/129366132-ee82f9a1-a222-4a12-9004-e049a6148d7b.gif)
