### ISSUE TITLE
connectedFocusDebugAndroidTest - No tests found

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/focus-android#5086]
`./gradlew connected[flavor]DebugAndroidTest` yields `No Tests Found`

Example:

```Gradle
./gradlew connectedFocusDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=org.mozilla.focus.activity.ThreeDotMainMenuTest#browserMenuItemsTest
```

> com.android.build.gradle.internal.testing.ConnectedDevice > No tests found.[Pixel_2_API_28(AVD) - 9] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).

It's possible this started happening with https://github.com/mozilla-mobile/focus-android/commit/4832f93fbc0b28ffb134ec9474d3d4b8393a03ed and `ANDROIDX_TEST_ORCHESTRATOR` and or https://github.com/mozilla-mobile/focus-android/commit/6caa9468a4906675378a4bef9f9ad12bbb7c6bca (updates). 

```Gradle
  testImplementation 'androidx.test:core:1.2.0'
  testImplementation 'androidx.test:runner:1.2.0'
  testImplementation 'androidx.test:rules:1.2.0'
```

Maybe Core deps need a big update too? I tried Googling around and there was no straight answer.

(This is the reason for the failing Github Action too: `disabled` for now)

**Comment by AaronMT** [comment]
There's also https://github.com/android/android-test/issues/986 (@pocmo) (re: https://github.com/mozilla-mobile/focus-android/commit/6caa9468a4906675378a4bef9f9ad12bbb7c6bca)

**Comment by AaronMT** [comment]
Maybe Orchestrator needs updating too? `androidTestUtil 'androidx.test:orchestrator:1.4.0` (https://stackoverflow.com/questions/62395286/no-tests-found-when-using-androidx-test-orchestrator) 
Although that yields 
```Log
e: warnings found and -Werror specified
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt: (15, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt: (41, 28): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt: (10, 43): 'IntentsTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt: (12, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt: (29, 5): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt: (59, 5): 'IntentsTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/screenshots/FirstRunScreenshots.kt: (7, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/screenshots/FirstRunScreenshots.kt: (19, 28): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
```

**Comment by sv-ohorvath** [comment]
It is weird, but, Andi and I ran the tests with the gradle terminal command on debug and release and it worked fine on our Pixels, both on API 28 and 30.
Andi had some similar issues initially on his Android 11 device, but yesterday it worked well with the latest changes.

**Comment by AndiAJ** [comment]
Hi @AaronMT , indeed I couldn't run the test on a Google Pixel 3a (Android 11) a week or so.

Not sure if I bumped into the same error, but [this trick proved to be helpful](https://github.com/android/android-test/issues/743#issuecomment-712306451) 

Yesterday I've managed to run all the Smoke tests without making the above mentioned change.

Just ran your cmd `gradlew connectedFocusDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=org.mozilla.focus.activity.ThreeDotMainMenuTest#browserMenuItemsTest` and it worked properly.

**Comment by AaronMT** [comment]
I'm concerned because the workflow https://github.com/mozilla-mobile/focus-android/runs/3282458545?check_suite_focus=true (last ran here before I disabled it) ran into this and then I did, so it's two different environments reproducing the issue.

**Comment by pocmo** [comment]
Reading through all the device logs I found this:

> F  runtime.cc:566] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn’t find class “androidx.test.services.shellexecutor.ShellMain” on path: DexPathList[[directory “.”]
                            ,nativeLibraryDirectories=[/system/lib, /system/lib]]


And finally ended up with this state that seems to run tests:
https://github.com/mozilla-mobile/focus-android/commit/92e0d853a14b19412d524d729071cc2979551708

There are more changes in this commit. The important one seems to be the addition of the orchestrator dependency. So maybe we can also just isolate that one.

**Comment by AaronMT** [comment]
Was looking at Fenix differences, there's missing an explicit declaring of the dependency
(e.,g https://github.com/mozilla-mobile/fenix/blob/main/app/build.gradle#L560) (and https://github.com/mozilla-mobile/fenix/blob/main/buildSrc/src/main/java/Dependencies.kt#L222)

(https://github.com/android/android-test/issues/220)

**Comment by AaronMT** [comment]
I am able to successfully run instrumented tests on API 30 (Pixel 3). I am not sure what changed or if this is an API 28 issue.

**Comment by sv-ohorvath** [comment]
@AaronMT the problem seems to be back with API 30 too, the CI is failing on all PRs: https://github.com/mozilla-mobile/focus-android/pull/5176/checks?check_run_id=3369309363

**Comment by AaronMT** [comment]
> @AaronMT the problem seems to be back with API 30 too, the CI is failing on all PRs: https://github.com/mozilla-mobile/focus-android/pull/5176/checks?check_run_id=3369309363

Redisabled while this is investigated.

**Comment by sv-ohorvath** [comment]
> Was looking at Fenix differences, there's missing an explicit declaring of the dependency
> (e.,g https://github.com/mozilla-mobile/fenix/blob/main/app/build.gradle#L560) (and https://github.com/mozilla-mobile/fenix/blob/main/buildSrc/src/main/java/Dependencies.kt#L222)
> 
> ([android/android-test#220](https://github.com/android/android-test/issues/220))

@AaronMT you were right. I added the missing dependencies https://github.com/mozilla-mobile/focus-android/pull/5187

**Comment by ionutbedregeanu** [comment]
Still reproducible: https://github.com/mozilla-mobile/focus-android/pull/5175/checks?check_run_id=3407798357

**Comment by AaronMT** [comment]
Disabled
