### ISSUE TITLE
Add Metropolis and Inter fonts.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5091]
https://github.com/rsms/inter/

@brampitoyo I see. https://github.com/chrismsimpson/Metropolis is no longer available. Should we use the files from Fenix?

Also, thoughts about this: https://github.com/mozilla-mobile/fenix/issues/8089#issuecomment-893667598?

**Comment by brampitoyo** [comment]
@mcarare The designer of Metropolis had decided to take the repo private, so we have to rely on fonts used by Fenix.

As for Inter, Fenix wasn’t able to include this font in product. I think there were some language issues?

So, for Focus, I wonder whether we should just use the default system font. This would be Roboto, or whatever system default font the phone manufacturer specifies (Samsung uses their own one, for example).

**Comment by mcarare** [comment]
@brampitoyo I agree. So we should add just Metropolis where designs use it or keep only default system fonts altogether for now in Focus?

**Comment by brampitoyo** [comment]
@mcarare Since Fenix doesn’t look like they will change their font any time soon, I would prefer for Focus to use Metropolis where the spec calls for it (titles, headings, buttons), and use the default system font for the rest of the UI.

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/focus-android/pull/5127.
