### ISSUE TITLE
Cannot follow a link by pressing it if its target is not _self

### ISSUE THREAD

**Issue by zznidar** [mozilla-mobile/focus-android#5101]
## Steps to reproduce
1. Open https://ismyinternetworking.com/
2. Touch any of the links after the first paragraph (e. g. "Is it Down or Just Me?")

### Expected behavior
The browser follows that link and opens a new website.

### Actual behavior
The text changes colour, but nothing more happens. Browser stays on the same website.

It is possible to hold on the link and open it in a new tab, but impossible to navigate to it in the current tab.

### Device information

* Android device: Pocophone f1, Android 10
* Focus version: 91.1.1 (Build #352212035 🦎 91.0-20210804193234)

Video: 

https://user-images.githubusercontent.com/20877556/129068806-72456796-f76b-46e7-948e-1d5e02b84d85.mp4

**Comment by zznidar** [comment]
This also affects buttons which are not links but open a new URL with, for example, JavaScript's `window.open()` function.
These links, however, cannot be opened by holding and opening them in a new tab, because they are not `<a href>` elements.

Demo/Repro steps:
1. Open https://zznidar.github.io/bugreports/Firefox%20Focus/Cannot%20follow%20links/
2. Tap on the paragraph text. 

Expected result: example.com website should be opened
Actual result: nothing happens

**Comment by zznidar** [comment]
After further testing, it seems only links that should open in a new tab/window (e. g. where target != _self) cause problems. I have updated the [demo](https://zznidar.github.io/bugreports/Firefox%20Focus/Cannot%20follow%20links/) to illustrate that.

**Comment by amedyne** [comment]
@zznidar thank you for providing more details into this. This will really help with us providing a fix.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Focus 91.2.2 and the issues no longer occurs.

### Devices used:
- OnePlus 6T (Android 9)
- Lenovo tab M10 (Android 10)
