### ISSUE TITLE
Ensure we are stripping debug symbols in native libraries to minimize APK size

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#5104]
When compiling nightly locally with `./gradlew installFocusNightly`, I see:

>\> Task :app:stripFocusNightlyDebugSymbols
Unable to strip the following libraries, packaging them as they are: libfreebl3.so, libglean_ffi.so, libjnidispatch.so, liblgpllibs.so, libmozavcodec.so, libmozavutil.so, libmozglue.so, libnss3.so, libnssckbi.so, libplugin-container.so, libsoftokn3.so, libxul.so.

I wonder if we're shipping native debug symbols and if that's increasing the size of our shipped APK. Perhaps we're not supposed to strip nightly builds though.

**Comment by mcomella** [comment]
Triage: not P1 because APK size isn't a focus.

**Comment by jonalmeida** [comment]
We don't have this warning showing up anymore so I think upstream fixed it already. Closing for now since this isn't a priority - we can open it again if needed.
