### ISSUE TITLE
Search box moves around when highlighted, causing delay to keyboard up

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5105]
## Steps to reproduce
- The app opens with keyboard up by default
- Minimise the keyboard
- Select the search box again

Alternatively, put the phone to sleep, then wake it up again to automatically select the search box

### Expected behavior
- The text and cursor doesn’t move
- The keyboard is instantly up
- Transition is smooth and instantaneous

![screen-20210812-133259](https://user-images.githubusercontent.com/51007/129124644-79d686f1-0cf9-491d-bf02-963493172d04.gif)

### Actual behavior
- The text and cursor move
- There’s a slight delay to keyboard up
- Transition is neither smooth nor instantaneous

![screen-20210812-133023](https://user-images.githubusercontent.com/51007/129124527-6ad1dfa3-2835-460b-831d-9da2d39a5401.gif)

**Comment by mcarare** [comment]
This would need AC work for the hint position fix, because `mozac_browser_toolbar_origin_view` and `mozac_browser_toolbar_edit_url_view` have different start margins
