### ISSUE TITLE
Match Settings visual style to spec

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5107]
## Steps to reproduce
- Go to Settings

### Expected behavior

- Top app bar
    - [ ] Uses new iconset for Back
    - [ ] Background colour matches page content and URL bar (for both, use `Ink 60` `#271948`)
    - [ ] Heading font family: Metropolis
- Page content
    - [x] Does not have icons
    - [x] Captions use a different colour value from body texts
    - [x] No horizontal line divider
    - [ ] Match font size of small texts to Fenix (Focus uses 12dp, but Fenix uses 14dp?)

<img width="360" alt="Android - Settings - Dark@2x" src="https://user-images.githubusercontent.com/51007/132267238-0e5709d7-1980-4a2d-94a8-3deeea10526c.png">

https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2140%3A71629

### Actual behavior

- Top app bar
    - Uses old iconset for Back
    - Background colour does not match page content
    - Heading font family: Roboto
- Page content
    - Size of small texts are smaller compared to Fenix

| Focus | Fenix |
| --- | --- |
| Small text: 12dp | Small text: 14dp |
| ![Screenshot_20210907-121146_Firefox_Focus](https://user-images.githubusercontent.com/51007/132267293-bd6282aa-4be1-4cc4-a8e6-067161c60531.png) | ![Screenshot_20210907-120843_Firefox_Nightly](https://user-images.githubusercontent.com/51007/132267320-6a6335f6-19f6-4b6d-96e0-2583c1245e71.png) |

**Comment by mcarare** [comment]
@brampitoyo This issue should be revised after the changes landed in the main branch.

**Comment by brampitoyo** [comment]
Thanks @mcarare. I’ve updated this Settings visual style issue to reflect design elements that have already been corrected (thanks heaps for fixing those issues!), and those that are not yet fixed.

You can see comment 0 for the change. In summary, they are:

Top app bar
- [ ] Uses new iconset for Back
- [ ] Background colour matches page content and URL bar (for both, use `Ink 60` `#271948`)
- [ ] Heading font family: Metropolis

Page content
- [ ] Match font size of small texts to Fenix (Focus uses 12dp, but Fenix uses 14dp?)

**Comment by mcarare** [comment]
@brampitoyo Preferences headers already have Metropolis font.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 9/9 with GV 93.0a1-20210901091701, with Lenovo tab M10 (Android 10), and OnePlus 5T (Android 9).

![Screenshot_20210909-153919](https://user-images.githubusercontent.com/40694158/132687468-6b4652d5-289e-4891-a4a5-6dfb6abe52c7.jpg)
