### ISSUE TITLE
Update search suggestions strings and typography

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5108]
## Steps to reproduce
- Start typing in the search box
- Observe “Search suggestions” box show up

### Expected behavior
- Header
    - Font family: Metropolis
    - Text: Show search suggestions?
- Body text: To get suggestions, Firefox Focus needs to send what you type in the address bar to the search engine.
<img width="360" alt="Android - No Shortcuts - Keyboard Up@2x" src="https://user-images.githubusercontent.com/51007/129492988-5f59e16a-7780-47cf-9cbf-d7b24551cd1f.png">

https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2133%3A91391

### Actual behavior
- Header
    - Font family: Roboto
    - Text: Would you like to turn on search suggestion?
- Body text: To get search suggestions, Firefox Focus needs to send what you type in the address bar to the search engine you’ve chosen. [Learn more]().
<img width="360" src="https://user-images.githubusercontent.com/51007/129128651-218203ea-45bf-45b2-b2ca-33c9c0fa5986.png">

**Comment by mcarare** [comment]
@brampitoyo does this mean the part with the search icon and typed text below the “Search suggestions” box should also be removed, or is it omitted from the designs? Thank you!

**Comment by brampitoyo** [comment]
@mcarare Sorry. That part was accidentally omitted. We should keep showing the verbatim search keyword underneath the “Search suggestions” box, as we already do today.

I will update the screenshot above to match (the Figma file was also updated). Thanks.

**Comment by lobontiumira** [comment]
Verified as fixed on the 91.2.2 build 352310216 - GV 91.0.1-20210816143654 with Lenovo Tab M10 (Android 10):

![focus](https://user-images.githubusercontent.com/40694158/130040267-df30c080-377e-46d1-b796-98be719a0c65.jpg)

**Comment by lobontiumira** [comment]
Verified also on the 93.1.0 RC build with Lenovo Tab M10 (Android 10):
![Screenshot_2021-09-29-11-27-56-561](https://user-images.githubusercontent.com/40694158/135232174-b8ef7704-63fe-4245-a4bf-bd710a4b901a.jpeg)
