### ISSUE TITLE
After adding a shortcut, it does not appear in the selected search box

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5110]
## Steps to reproduce
- Navigate to a webpage
- Add it as a shortcut (tap ⋮ Main Application Menu → Add to Shortcuts)
- Tap the search box again to select it again

### Expected behavior
- The shortcut tile that you’ve just added appears underneath the search box
- “Add to Autocomplete” does not appear
- Note that “Add to Autocomplete” should never appear, even if you have not added any site as a shortcut
<img width="360" alt="Android - Browser - Search Zero Screen@2x" src="https://user-images.githubusercontent.com/51007/129130180-6ae59441-3a9b-4d7b-b3eb-5f8086e2dfc6.png">
https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2133%3A91391

### Actual behavior
- Your just-added shortcut does not appear under the search box
- Instead, “Add to Autocomplete” appears
<img width="360" src="https://user-images.githubusercontent.com/51007/129130395-2a5b6d76-3d97-490f-bd18-22a847c0d09a.png">

**Comment by ionutbedregeanu** [comment]
Can't be reproduced anymore
