### ISSUE TITLE
After adding a shortcut, show a confirmation message

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5112]
## Steps to reproduce
- Navigate to a site
- Add it to shortcut

### Expected behavior

We currently don’t have this in the spec, but it would be great to have a snackbar that says:
> Added to Shortcuts

Note that the example below comes from Firefox for Android, and the style of our snackbar should be different from theirs.

<img width="360" src="https://user-images.githubusercontent.com/51007/129132116-f95185f2-d7e2-4915-acf6-e7b0c8e19a19.png">

### Actual behavior

No snackbar is shown.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802010

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
