### ISSUE TITLE
The Shortcuts context menu should be styled like Firefox for Android

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5113]
## Steps to reproduce
- Add a site to Shortcut
- Go back to the New Tab Page
- Long-press a Shortcut to open its context menu

### Expected behavior

We currently don’t have this in the MVP spec, but it would be great to have a menu layout that matches Firefox for Android in terms of height, typography and icon usage (no icon) – but with a text and background colour styles that matches our own menu.

Our Shortcuts context menu only contain two items:
- Rename
- Remove

| Proposed Focus Shortcuts context menu | Compared to Fenix Shortcuts context menu |
| --- | --- |
| <img width="360" alt="Android - 1 to 4 Shortcuts - Shortcut Tile Menu@2x" src="https://user-images.githubusercontent.com/51007/129133011-3014760e-23ed-42e3-8586-2309564d05d5.png"> | <img width="360" src="https://user-images.githubusercontent.com/51007/129133250-84233896-cfba-47ae-bb06-910560989f38.png"> |

I’ve put this mockup in the Post-MVP Figma page:
https://www.figma.com/file/KggJlo8pg2T2Q8nn0Ec5c3/Shortcuts?node-id=1875%3A63694

### Actual behavior

Our menu is taller, only contains one item, and has an icon.

| Current Focus Shortcuts context menu |
| --- |
| <img width="360" alt="Android - 1 to 4 Shortcuts - Shortcut Tile Menu@2x" src="https://user-images.githubusercontent.com/51007/129133354-b593c8d8-24d2-451c-bea9-7c96d7874a6d.png"> |

**Comment by ionutbedregeanu** [comment]
I will close this ticket since it was addressed by other tickets
