### ISSUE TITLE
Add ability to rename Shortcuts

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5114]
## Steps to reproduce
- Add a site to Shortcut
- Go back to the New Tab Page
- Long-press a Shortcut to open its context menu

### Expected behavior

We currently don’t have this in the MVP spec, but it would be great to be able to rename Shortcuts. This is a feature that already exists in Firefox for Android, so we could take their implementation and apply our own visual style.

To access the Rename Shortcuts dialog:
- Long-press a Shortcut to open its context menu
- Tap “Rename”

| Proposed Focus Shortcuts context menu | Fenix Rename Shortcuts dialog (note that we should apply our own visual style on this dialog) |
| --- | --- |
| <img width="360" alt="Android - 1 to 4 Shortcuts - Shortcut Tile Menu@2x" src="https://user-images.githubusercontent.com/51007/129133011-3014760e-23ed-42e3-8586-2309564d05d5.png"> | <img width="360" src="https://user-images.githubusercontent.com/51007/129133585-296ed042-8fce-45ad-a555-9e974317f552.png"> |

### Actual behavior

This feature does not exist today.

**Comment by ionutbedregeanu** [comment]
Implemented by https://github.com/mozilla-mobile/focus-android/issues/5740
