### ISSUE TITLE
"Custom Tabs" Don't Support Navigating Back

### ISSUE THREAD

**Issue by mackncheesiest** [mozilla-mobile/focus-android#5115]
Sometime over the last week or so (?), the back button has stopped navigating "back" for me specifically when I'm viewing sites from an embedded "Custom Tabs" view (i.e. [this feature](https://developer.chrome.com/docs/android/custom-tabs/overview/)). Instead, the Android back button (or gesture) closes the entire view and punts me back to whatever context I'd launched that browser pane from. Given that there isn't a back button in the overflow menu either, this means that I don't believe I can currently navigate back when browsing sites in these kinds of panes.

It's worth noting that, in the standalone/proper `Firefox Focus` app, the Android back button _does_ still serve as a means of navigating back, so this seems to exclusively impact Custom Tabs views. Namely, if I open a page as a Custom Tab, choose to `Open in Firefox Focus`, navigate via the same link on that page, and then tap the back button, everything works as expected.

## Steps to reproduce

1. Open a link in a Custom Tabs version of Firefox Focus (i.e. the active app in the app switcher is still shown as your messenger, news reader, etc, and the top right overflow menu has `Powered by Firefox Focus` at the bottom)
2. Tap to navigate to another page within that view
3. Perform your Android phone's back gesture (tap the back button, swipe in from left, etc)

### Expected behavior

The page should navigate backwards to the previous page

### Actual behavior

The entire web view closes and kicks me out back to the messenger/news reader/etc

### Device information

* Android device: Pixel 4a 5G, Android 11
* Focus version: 91.1.1 (Build #352212035, Gecko 91.0-20210804193234)

**Comment by mackncheesiest** [comment]
No evidence that this is actually the case (and digging into this just seems to be taking me into Gecko View 😰), but maybe it could be related to this merge?

https://github.com/mozilla-mobile/focus-android/commit/f4c4f90e838beeff43c2ebd302fdb6f8c93b2a78

There are some updates to `onBackPressed` handlers and such in that PR (although those seem to be handling presses for a button in the overflow menu?), and temporally, that would line up with when I seem to remember this issue starting. Again no evidence, but could it have something to do with this new logic that seems to switch on whether we're in a Custom Tab.

**Comment by lobontiumira** [comment]
Verified as fixed on the 8/30 debug build from main, using a Lenovo Tab M10 (Android 10), and Samsung Galaxy Note 8 (Android 9).

Still able to reproduce it on the latest RC build 91.4.0, with the same devices.
