### ISSUE TITLE
On the search results interface, the top toolbar has a different background

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5116]
## Steps to reproduce
- Tap the address box to select it
- Enter a keyword

### Expected behavior
- The background of the top toolbar should be the same as the rest of the search results
- The search box has a different background colour from the rest of the toolbar
<img width="360" alt="Android - Browser - Search Zero Screen@2x" src="https://user-images.githubusercontent.com/51007/129140821-b37654ae-3c42-422f-9068-13dc7a574cc9.png">

### Actual behavior
- The background of the top toolbar is dark magenta
- The search box is not differentiated from the rest of the toolbar
<img width="360" src="https://user-images.githubusercontent.com/51007/129140666-26f4f094-25cc-4e4e-8d73-e425b007d0e5.png">

**Comment by sanchi0204** [comment]
Can I work on this issue?

**Comment by brampitoyo** [comment]
Hi @ionutbedregeanu, we’d like to follow the toolbar design on Figma and have the background colour of the address/search box be different from the toolbar itself.

When the address box is coloured differently, it will be possible to make the toolbar and search results background identical.

Do you think this is possible to do in time for release? Thanks!

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main 93.0 (build 11 GV 93.0a1-20210901091701), with LEnovo Tab M10 (Android 10), and Samsung Galaxy Tab A6 (Android 5.1.1).
