### ISSUE TITLE
Crash in [@ java.lang.IllegalThreadStateException: at org.mozilla.gecko.util.ThreadUtils.assertOnThread(ThreadUtils.java)]

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#5120]
Crash report: https://crash-stats.mozilla.org/report/index/18886596-21e1-44b8-866c-0b6a50210810

Java stack trace:

```
java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 972 ("DefaultDispatcher-worker-1")
	at org.mozilla.gecko.util.ThreadUtils.assertOnThread(ThreadUtils.java:7)
	at org.mozilla.gecko.util.ThreadUtils.assertOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoRuntime.setDelegate(GeckoRuntime.java:1)
	at mozilla.components.browser.engine.gecko.GeckoEngine.<init>(GeckoEngine.kt:9)
	at org.mozilla.focus.Components$engine$2.invoke(Components.kt:6)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
	at org.mozilla.focus.Components.getEngine(Unknown Source:2)
	at org.mozilla.focus.Components$store$2.invoke(Components.kt:14)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
	at org.mozilla.focus.Components.getStore(Unknown Source:2)
	at org.mozilla.focus.telemetry.GleanMetricsService$collectPrefMetrics$1.invokeSuspend(GleanMetricsService.kt:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:13)
```

**Comment by eliserichards** [comment]
Happening here @jonalmeida : https://github.com/mozilla-mobile/focus-android/blob/3483f844045a231e111165d1837ee853df53ddf7/app/src/main/java/org/mozilla/focus/components/EngineProvider.kt#L29

**Comment by jonalmeida** [comment]
The problem here is that we're initializing Glean as soon as possible in the [`Application#onCreate`](https://github.com/mozilla-mobile/focus-android/blob/releases_v91.0/app/src/main/java/org/mozilla/focus/FocusApplication.kt#L49) and our metrics collection, which [**switches over to an IO dispatcher**](https://github.com/mozilla-mobile/focus-android/blob/releases_v91.0/app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt#L61-L77) for reading user prefs. That [metrics collection](https://github.com/mozilla-mobile/focus-android/blob/releases_v91.0/app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt#L85) pulls locale data from BrowserStore, which hasn't been initialized yet either and in order to init, as you may guess, also [initializes the GeckoEngine](https://github.com/mozilla-mobile/focus-android/blob/releases_v91.0/app/src/main/java/org/mozilla/focus/Components.kt#L119). Since we are no longer on the main thread during this call, Gecko assertions kick in.

**Comment by kbrosnan** [comment]
* Sentry issue: [FOCUS-ANDROID-AM9](https://sentry.prod.mozaws.net/operations/focus-android/issues/12091689/?referrer=github_plugin)
* https://crash-stats.mozilla.org/signature/?product=Focus&signature=java.lang.IllegalThreadStateException%3A%20at%20org.mozilla.gecko.util.ThreadUtils.assertOnThread%28ThreadUtils.java%29

**Comment by jonalmeida** [comment]
> The problem here is that we're initializing Glean as soon as possible in the [`Application#onCreate`](https://github.com/mozilla-mobile/focus-android/blob/releases_v91.0/app/src/main/java/org/mozilla/focus/FocusApplication.kt#L49) and our metrics collection, which [**switches over to an IO dispatcher**](https://github.com/mozilla-mobile/focus-android/blob/releases_v91.0/app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt#L61-L77) for reading user prefs. That [metrics collection](https://github.com/mozilla-mobile/focus-android/blob/releases_v91.0/app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt#L85) pulls locale data from BrowserStore, which hasn't been initialized yet either and in order to init, as you may guess, also [initializes the GeckoEngine](https://github.com/mozilla-mobile/focus-android/blob/releases_v91.0/app/src/main/java/org/mozilla/focus/Components.kt#L119). Since we are no longer on the main thread during this call, Gecko assertions kick in.

Comparing what we do [in Fenix](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L174), I think we have an obvious solution which is to warm up the engine first (on the main thread) before initialize metrics.
