### ISSUE TITLE
Update Focus notification icon 

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/focus-android#5128]
## Steps to reproduce

Have a notification arrive in Fenix
Open webpage in Focus for Android 

### Expected behavior

The two notification icons are the same.

### Actual behavior

The Fenix icon is the current branding, the Focus icon is the previous branding (see attached image, Focus on the left, Fenix on the right).

![Focus Fenix notifications](https://user-images.githubusercontent.com/31939113/129344704-89899f3a-fdc2-46fd-a353-fba44bc27f9a.png)

### Device information

* Android device: Motorola Moto E5, Android 8
* Focus version: 91.1.1

**Comment by mcarare** [comment]
@brampitoyo do we have resources for the new icon?

**Comment by SeburoSUMO** [comment]
Could we not use the same notification icon as Fenix?

**Comment by brampitoyo** [comment]
@mcarare I agree with @SeburoSUMO. The original intention is for Focus to use the same status logo as Fenix.

Fenix’s asset can be found here: https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/res/drawable/ic_status_logo.xml

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 9/9 (GV 93.0a1-20210901091701) with Lenovo Tab M10 (Android 10).

![notifications icons](https://user-images.githubusercontent.com/40694158/132689684-4088fefb-5b07-4c6f-9b5a-c4dec624190a.png)
![icons](https://user-images.githubusercontent.com/40694158/132689696-ffbb1d6a-78e4-4f00-8fc3-840314b48a01.jpg)
