### ISSUE TITLE
Intermittent UI test failure - <CustomTabTest.testCustomTabUI>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5130]
### Firebase Test Run: 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/9142254862940283030/executions/bs.875192e085ebe0b2/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/9142254862940283030/executions/bs.d97989a0c391b816/testcases/1)

### Stacktrace:
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Open in Firefox Focus"

View Hierarchy:
+>PopupDecorView{id=-1, visibility=VISIBLE, width=741, height=1026, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(981,77)(wrapxwrap) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged} ty=APPLICATION_PANEL fmt=TRANSPARENT wanim=0x7f130101 surfaceInsets=Rect(45, 45 - 45, 45) (manual)
fl=SPLIT_TOUCH HARDWARE_ACCELERATED FLAG_LAYOUT_ATTACHED_IN_DECOR
pfl=WILL_NOT_REPLACE_ON_RELAUNCH LAYOUT_CHILD_WINDOW_IN_PARENT_FRAME}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+->PopupBackgroundView{id=-1, visibility=VISIBLE, width=741, height=1026, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@edd9905, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+-->CardView{id=2131362134, res-name=mozac_browser_menu_menuView, visibility=VISIBLE, width=741, height=1026, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@7d7dd5a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+--->DynamicWidthRecyclerView{id=2131362135, res-name=mozac_browser_menu_recyclerView, visibility=VISIBLE, width=689, height=952, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@9f6db8b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=26.0, y=37.0, child-count=9}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=154, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@d820468, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}
|
+----->AppCompatImageButton{id=-1, desc=Navigate back, visibility=VISIBLE, width=229, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=false, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@e23c081, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+----->AppCompatImageButton{id=-1, desc=Navigate forward, visibility=VISIBLE, width=230, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=false, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@ea67526, tag=null, root-is-layout-requested=false, has-input-connection=false, x=229.0, y=0.0}
|
+----->AppCompatImageButton{id=-1, desc=Reload website, visibility=VISIBLE, width=230, height=154, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@5f5a567, tag=null, root-is-layout-requested=false, has-input-connection=false, x=459.0, y=0.0}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@6a6ff14, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=154.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@2c6feb9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=157.0, child-count=4}
|
+----->AppCompatImageView{id=2131362079, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@c6d02fe, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362349, res-name=text, visibility=VISIBLE, width=351, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@fc7da5f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Find in Page, input-type=0, ime-target=false, has-links=false}
|
+----->View{id=-1, visibility=VISIBLE, width=184, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@11b1cac, tag=null, root-is-layout-requested=false, has-input-connection=false, x=461.0, y=64.0}
|
+----->AppCompatImageView{id=2131362206, res-name=overflowImage, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@44fcd75, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->SwitchCompat{id=2131362329, res-name=switch_widget, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@412510a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=289.0, text=Desktop site, input-type=0, ime-target=false, has-links=false, is-checked=false}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@839bd7b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=421.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@4125544, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=424.0, child-count=4}
|
+----->AppCompatImageView{id=2131362079, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@861362d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362349, res-name=text, visibility=VISIBLE, width=510, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@3b3f762, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Add to Home screen, input-type=0, ime-target=false, has-links=false}
|
+----->View{id=-1, visibility=VISIBLE, width=25, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@cc60f3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=620.0, y=64.0}
|
+----->AppCompatImageView{id=2131362206, res-name=overflowImage, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@b8181b0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@7affde5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=556.0, child-count=4}
|
+----->AppCompatImageView{id=2131362079, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@96910ba, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362349, res-name=text, visibility=VISIBLE, width=287, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@eb0fb6b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Open in…, input-type=0, ime-target=false, has-links=false}
|
+----->View{id=-1, visibility=VISIBLE, width=248, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@db7d6c8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=397.0, y=64.0}
|
+----->AppCompatImageView{id=2131362206, res-name=overflowImage, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@1679361, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->AppCompatTextView{id=2131362290, res-name=simple_text, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@6077e86, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=688.0, text=TestItem4223, input-type=0, ime-target=false, has-links=false}
|
+---->AppCompatTextView{id=2131362290, res-name=simple_text, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@b61e347, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=820.0, text=Powered by Firefox Focus, input-type=0, ime-target=false, has-links=false}
|
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
at org.mozilla.focus.activity.robots.CustomTabRobot.verifyTheStandardMenuItems(CustomTabRobot.kt:44)
at org.mozilla.focus.activity.CustomTabTest$testCustomTabUI$2.invoke(CustomTabTest.kt:77)
at org.mozilla.focus.activity.CustomTabTest$testCustomTabUI$2.invoke(CustomTabTest.kt:73)
at org.mozilla.focus.activity.robots.CustomTabRobotKt.customTab(CustomTabRobot.kt:66)
at org.mozilla.focus.activity.CustomTabTest.testCustomTabUI(CustomTabTest.kt:73)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

### Notes
✔️ The crash from #5076 is fixed 
Once #5095 lands this should be fixed

**Comment by AndiAJ** [comment]
Total of 6 fails on 8/13 Main, all of them caused by 
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Open in Firefox Focus"`

**Comment by AndiAJ** [comment]
Failed again on 8/13 Main
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Open in Firefox Focus"`
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7427725193328934865/executions/bs.4034bbfc6ea10dcf/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7427725193328934865/executions/bs.1d15428eab4e4021/testcases/1)

Failed with a different stack trace after [#5095](https://github.com/mozilla-mobile/focus-android/pull/5095) landed
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Report site issue"`
Will be fixed in [#10791](https://github.com/mozilla-mobile/android-components/issues/10791)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/4991136182251413973/executions/bs.574f9935f45beae2/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/4991136182251413973/executions/bs.c0db9371107cbb31/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5813088404962409092/executions/bs.b15d9ab137d2a7cf/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5813088404962409092/executions/bs.177e2e969459e20/testcases/1)

**Comment by AndiAJ** [comment]
Failed 1x on 8/14 Main
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Report site issue"`

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7694380479782453280/executions/bs.8a48fa0142d2c7b5/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7694380479782453280/executions/bs.889fddc4e079cdf0/testcases/1)

**Comment by AndiAJ** [comment]
Failed 1x on 8/16 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8337792199024522170/executions/bs.51234e9899842911/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8337792199024522170/executions/bs.6e4dd9d91887cbd4/testcases/1)

**Comment by sv-ohorvath** [comment]
Waiting for https://github.com/mozilla-mobile/android-components/issues/10791
