### ISSUE TITLE
Replace Focus icons with AC icons

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#5152]
### Why/User Benefit/User Problem
Remove all icons from Focus which are available in AC
Import AC icons in order to restore the current design

**Comment by ionutbedregeanu** [comment]
Blocked by [10621](https://github.com/mozilla-mobile/android-components/issues/10621)

**Comment by ionutbedregeanu** [comment]
Note for QA: To test this ticket you need to check if the browser menu have the same icons as in [Figma](https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2133%3A282824) for both scenarios(normal tab, custom tab)

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main from 8/25, with Lenovo Tab M10 (Android 10):

![AC icons](https://user-images.githubusercontent.com/40694158/130756981-0ebdc05e-19d4-439f-8f8e-75e92e206a3b.png)

**Note: I've filed #5212 for the extra space in custom tab's toolbar.

**Comment by lobontiumira** [comment]
Verified as fixed also on RC 93.1.0 with Lenovo Tab M10 (Android 10).
