### ISSUE TITLE
What's New link takes you to an unmaintained page

### ISSUE THREAD

**Issue by jtnord** [mozilla-mobile/focus-android#5161]
## Steps to reproduce

In the menu select what's new

### Expected behavior

You are told what's new in each release 

### Actual behavior

You are told the page has not been maintained since 2018

The link takes you to what ends up after a redirect to https://support.mozilla.org/en-US/kb/whats-new-firefox-focus-android-version-8?as=u&utm_source=inproduct

> This article is no longer maintained, so its content might be out of date.

> Version: 8
Release date: December 20, 2018
Here are the changes you’ll see in this version of Firefox Focus for Android. 
### Device information

* Android device: one plus 6t android 10
* Focus version: 91.2.0

**Comment by jonalmeida** [comment]
Thanks, we've removed the link for now until we have a new link from our SUMO team.
