### ISSUE TITLE
Correct default tracking protection blocking resources

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#5166]
Our categories for Tracking Protection had changed with the new [AC Engine](https://github.com/mozilla-mobile/android-components/blob/2fb230cc7c11afa942171245060ce3ee275acb21/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L269) integration, and we need to update our default settings accordingly.

### Steps to reproduce
1. Have Focus 8.17.3 or earlier installed.
2. Browse to rottentomatoes.com and wait for the ad banner to load.
3. Open Settings -> Privacy & Security and observe the 'Block other content trackers' preference.
4. Install Focus 91.2.0.
5. Browse to rottentomatoes.com and wait for the ad banner to load.
6. Open Settings -> Privacy & Security and observe the 'Block other content trackers' preference.

### Expected results
- At 2, the ad banner never shows.
- At 5, the ad banner never shows.

### Actual results
- At 2, the ad banner never shows.
- At 5, the ad banner always shows.

### Additional notes
- With versions greater than 91.2.0, the default preference should be **enabled**.

**Comment by lobontiumira** [comment]
Hi @jonalmeida 
Following the steps, here are my findings:
* after step 5, the ad banner never shows;
* the "Block other consent trackers" is disabled by default on the 91.2.0 Focus build.

However, **on 91.2.2 Focus build**, this "Block other consent trackers" TP option is enabled by default, and the banner is displayed again.

<img src="https://user-images.githubusercontent.com/40694158/130079794-f6a040b0-c148-4fe9-a0c1-3fada96b4db6.jpg" width="300" height="550" />

* Note: I do hope the marked area in the screenshot is the banner you are reffering to.

**Comment by amedyne** [comment]
@Amejia481 FYI.

**Comment by Amejia481** [comment]
@lobontiumira 
I think the ad banner that @jonalmeida was referring was the top one (Maker in yellow).
![image](https://user-images.githubusercontent.com/773158/130101087-dd5ad908-ea7f-4503-bef8-f312e7343b9f.png)

**Comment by Amejia481** [comment]
On your screenshot is not visible, the one in pink is just a popup dialog from the website adding the users to enable ads (as their are not showing).

![image](https://user-images.githubusercontent.com/773158/130101667-99e1e3a7-fe4c-41eb-b3dd-3243967f8212.png)

**Comment by lobontiumira** [comment]
Thank you, Arturo!
I've retested on the Lenovo Tab M10 (Android 10), and after step2, and step 5, the ad banner never shows.
I'll close this issue as verified as fixed.

**Comment by Amejia481** [comment]
Thanks @ lobontiumira  for double checking :)
