### ISSUE TITLE
Web content with nested scrolling in Focus hides the toolbar permanently

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#5173]
### Steps to reproduce
1. Visit a site with nested scrolling elements like maps.google.com or reddit.com when it has it's (terrible) app banner.
2. Try to scroll vertically.

### Expected results
- The toolbar shows and hides or is permanently visible when scrolling vertically.

### Actual results
- The scroll bar is hidden entirely and the toolbar cannot be accessed until the page is removed.

In the Google Maps example below, you lose access to the toolbar and tab counter if it's scrolled away.
In the Reddit example, you lose the toolbar and tab counter too, but you can access it if you dismiss the (terrible) app banner.

https://user-images.githubusercontent.com/1370580/129980956-5f4bdc56-bd98-4a3e-a6a6-6f6f9cb21000.mp4

https://user-images.githubusercontent.com/1370580/129980968-a68a4020-e111-432a-980e-2efd21302486.mp4

**Comment by Mugurell** [comment]
The current AppBarLayout based implementation has many issues stemming mainly from the fact that it does not differentiate on whether GV/the website handled the touch and it does not differentiate between zoom/panning gestures.
Fenix migrated to a more direct approach first with the bottom toolbar then with the top toolbar in https://github.com/mozilla-mobile/fenix/issues/10686.

Focus should probably switch to a similar approach.

**Comment by sv-ohorvath** [comment]
Hello, there was this issue too, a while ago: https://github.com/mozilla-mobile/focus-android/issues/4946
