### ISSUE TITLE
Option to always show toolbar

### ISSUE THREAD

**Issue by E0697** [mozilla-mobile/focus-android#5177]
### Why/User Benefit/User Problem
Consider adding an option to always show the toolbar, similar to the one in Firefox "scroll to hide toolbar"

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802011

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
