### ISSUE TITLE
Firefox Klar logo has wrong colors

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#5180]
### Steps to reproduce

1. compile Focus from the main branch with Klar branding

### Expected behavior

The logo has the same colors as with the Focus branding.

### Actual behavior

Wrong colored Firefox logo. A purple foreground on purple background does, obviously, not work very well.

The Klar logo is also noticeable larger than the Focus logo which seems wrong to me.

![klar-logo](https://user-images.githubusercontent.com/1100614/130062746-feee4c1d-c951-4d53-992f-76064b46b04a.png)

### Device information

* Android device: OnePlus 7T Pro McLaren, Oxygen OS 11 (Android 11)
* Focus version: main branch revision baa92c122369515b8c1696c4d995c998a338a8b9

**Comment by ionutbedregeanu** [comment]
Because both logos suffered some changes I will update Focus logo as well in this ticket

Focus logo resource: https://drive.google.com/drive/folders/1ZUwG06Bq4YrTGHQal18sdsJrlYCbUz-r
Klar logo resource: https://drive.google.com/drive/folders/1-Kb3ejWKjw1GTmPEiDXGr_Mfuys1CDu4

**Comment by cadeyrn** [comment]
> QAReady

The logo is still purple on a purple background and the logo of Firefox Klar is still noticeable larger than the logo of Firefox Focus: The fox logo is larger as well as the font size of the word mark:

<img width="1433" alt="Bildschirmfoto 2021-08-25 um 11 39 55" src="https://user-images.githubusercontent.com/1100614/130767658-8755c208-e53a-4453-87a0-230e88d9a3a9.png">

**Comment by ionutbedregeanu** [comment]
@cadeyrn Thank you! You are right, is a minor difference in size

@brampitoyo From what I see Focus logo has 384 width and 80 height while the Klar logo has 338 width and 80 height
Can you help me with another resource in order to have the same dimensions for both? Not sure which are the intended ones?

**Comment by mcarare** [comment]
@cadeyrn These are the color from the design team, not sure what ales are to do about it, except for them reconsidering.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 8/30, with Lenovo Tab M10 (Android 10)

![Untitled](https://user-images.githubusercontent.com/40694158/131352881-697a6d56-7727-4754-88d9-b3454928f49f.png)
