### ISSUE TITLE
The Add to Home screen confirmation prompt is blank for a website

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5182]
## Steps to reproduce
1. Go to https://senglehardt.com/test/trackingprotection/test_pages/;
2. Tap the 3 dot menu;
3. Select "Add to Home screen".
### Expected behavior
The "Add to Home screen" confirmation prompt should show the name of the website.
### Actual behavior
The "Add to Home screen" confirmation prompt is blank.
### Device information

* Android device: OnePlus 6T (Android 9), Lenovo Tab M10 (Android 10)
* Focus version: 91.2.2
![blank](https://user-images.githubusercontent.com/50983519/130068865-86a5c38a-26a0-4931-8311-5d85dfbd2da5.jpg)

**Comment by jonalmeida** [comment]
We could use the (base) url for the immediate fix if needed.

If the URL is `https://www.mozilla.org/en-GB/` we then use `mozilla.org`.

**Comment by brampitoyo** [comment]
@jonalmeida @mcarare I like the `Second-Level Domain` + `Top-Level Domain` default name suggestion.

The only issue is the fact that homescreen icons have limited character space. To solve this problem, I would recommend using only the SLD.

So, in the examples above, our string would be `senglehardt` and `mozilla`.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest debug build from main 8/25.
### Devices used:
- Oppo Find X3 Neo (Android 11)
- OnePlus 6T (Android 9)

**Comment by lobontiumira** [comment]
Reproducible also on RC 92.1.1 with Lenovo Tab M10 (Android 10).

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Focus 93.1.0.

### Device used:
- Huawei MediaPad M3 (Android 9)
- Oppe Find X3 (Android 11)
