### ISSUE TITLE
add back "open in app" context menu item on links

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/focus-android#5192]

**Comment by Poopooracoocoo** [comment]
Yikes. Stale bot??!

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802012

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
