### ISSUE TITLE
Excessive "Open in app?..." prompts with UntrackMe installed

### ISSUE THREAD

**Issue by jigglysackles** [mozilla-mobile/focus-android#5194]
## Steps to reproduce
Follow any link or search from browser address bar. 

### Expected behavior
Search completes or link follows without prompting. 

### Actual behavior
Persistently getting a prompt to "Open in app? Your activity may no longer be private." This happens regardless of an app being available for the site on link or search involved. 

### Device information

* Android device: Nokia 8.3 5g Android 11 Build 00WW_2_270_SP01
* Focus version: 91.3.0 Build 352320240 🦎 91.0.2-20210819103104

**Comment by worg** [comment]
A video with the behavior

https://user-images.githubusercontent.com/675355/130373372-1d92b17c-d457-467b-98fa-5bbbb8af05cc.mp4

Device: Xiaomi Mi A1 Android 9

**Comment by amedyne** [comment]
@Amejia481 Can you validate if this is expected?

**Comment by Amejia481** [comment]
Let me take look!

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest debug build from main 8/30.

### Devices used:
- Oppo Find X3 Neo (Android 11)
- OnePlus 6T (Android 9)
