### ISSUE TITLE
Custom Tabs context menu not working 

### ISSUE THREAD

**Issue by worg** [mozilla-mobile/focus-android#5195]
## Steps to reproduce
- Open a custom app tab with focus being the default browser
- long press on a link

### Expected behavior
- A popup appears to open the link in another app, share or copy the link

### Actual behavior
- no popup is shown
- #5183 and #5115 also apply

https://user-images.githubusercontent.com/675355/130373529-c58b2f47-c272-490f-bc24-b4da430827c5.mp4

### Device information

* Android device: Xiaomi Mi A1 - Android 9
* Focus version: 91.3.0 Build 352320240 🦎 91.0.2-20210819103104

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main 8/30 with Lenovo Tab M10 (Android 10).
The only issue is that the context menu options are in black text (already filed #5235 ).

![custom tab context menus](https://user-images.githubusercontent.com/40694158/131357456-1fc45fef-b08e-4319-aa7c-19dd8d420252.png)

**Comment by worg** [comment]
@lobontiumira Your screenshots don't correspond to the custom tabs context, the context menu works well in the browser view, but not in the custom tabs (even on the latest 0.91.4) 
You can get a custom tab by setting Focus as default browser and using an application that needs/uses custom tabs for browser activities.
Can this be reopened?
