### ISSUE TITLE
Google search is wierd

### ISSUE THREAD

**Issue by Ashwin-Raj18** [mozilla-mobile/focus-android#5196]
Google search looks like a lite version.. No modern ui.. I have attached pics for comparision with other browser
![onFirefox](https://user-images.githubusercontent.com/63547678/130384548-a4df4933-7b62-4ecd-8d77-6c002433e5ab.jpg)
![OnOtherBrowser](https://user-images.githubusercontent.com/63547678/130384559-ee118bf4-fc38-48cb-92c4-36836ec65542.jpg)

**Comment by amedyne** [comment]
@Ashwin-Raj18 What browser did you use for the comparison here?

**Comment by Ashwin-Raj18** [comment]
Google chrome

**Comment by kbrosnan** [comment]
Firefox and Chrome get different versions of the search page.
