### ISSUE TITLE
Forces https on site where not supported

### ISSUE THREAD

**Issue by Leonov65** [mozilla-mobile/focus-android#5199]
## Steps to reproduce
Visit any page within Aus Govt Bureau of Meteorology website:
http://bom.gov.au/

### Expected behavior
Before installation of recent FF Focus updates all pages at this site would load normally.

### Actual behavior
FF-F hangs while attempting to reload pages at this site. Redirection notice is displayed. FF-F attempts to reload but repeatedly returns to redirection notice. Desired pages do not load.

BOM's redirection notice states that its website currently does not support connections via HTTPS. Prior to recent updates FF-F did not have any problems loading pages from this website.

Site loads normally in FF-Android (91.3.0) with HTTPS Everywhere extension installed.

### Device information

* Android device: Samsung Galaxy S6 Edge (SM-G925I), Android 7.0
* Focus version: 91.3.0
![20210824-FF-Focus-https-prob-scnsht](https://user-images.githubusercontent.com/68941417/130584462-49a939d8-70c8-4188-9fec-7b552bc6772e.png)
[](url)

**Comment by amedyne** [comment]
@Amejia481 @jonalmeida is this a result a any recent security/privacy settings changes?

**Comment by Amejia481** [comment]
Let me take look and I'll report back.

**Comment by Amejia481** [comment]
@Leonov65 which version did you have before ?

**Comment by Amejia481** [comment]
I'm able to reproduce the same issue on Focus `8.13.1` released this on **Feb 22, 2021**. I'm seeing some logs on the browser console, it's very likely that there is a preference that we have turn ON Focus that it's not on Fenix.
```
HTTPS-First Mode: Upgrading insecure request “http://bom.gov.au/” to use “https”.
HTTPS-First Mode: Upgrading insecure request “https://bom.gov.au/” failed. Downgrading to “http” again.
HTTPS-First Mode: Upgrading insecure request “http://www.bom.gov.au/” to use “https”.
```

I will continue investigating.

**Comment by Amejia481** [comment]
The same issue is reproducible in Fenix in Private mode looks like this pref `dom.security.https_first_pbm` could be the source.

**Comment by Amejia481** [comment]
The same issue is reproducible on Firefox desktop in private mode.

**Comment by Amejia481** [comment]
I filed this ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1727419 for the privacy team on gecko to help us.

**Comment by Leonov65** [comment]
@Amejia481 I have three FF-F links to pages within bom.gov.au website saved to my home screen. I access them regularly; not daily but a few times a month. I was able to access them without issue earlier in August 2021. As I recall, FF-F was updated twice within the last week or so. Problem manifested after that.
