### ISSUE TITLE
Use overflow button to show menu of navigational options

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#52]
If we make the FAB erase, lets default back to the overflow button in the action bar for the following:

- Back (?)
- Forward
- Refresh
- Share
- Open with
- Settings

**Comment by pocmo** [comment]
After refactoring the FAB button (#43) I created an overflow menu with the options mentioned above. This is just using the default plain text menu style. As soon as we have some mocks ready I'll update the menu accordingly.

**Comment by antlam** [comment]
<img width="842" alt="screen shot 2017-02-16 at 2 27 56 pm" src="https://cloud.githubusercontent.com/assets/1994820/23044232/28086c00-f454-11e6-973e-d604d306baa4.png">

Attaching visual of "overflow button" here. Will post the menu contents next.

**Comment by antlam** [comment]
<img width="390" alt="screen shot 2017-02-16 at 3 57 07 pm" src="https://cloud.githubusercontent.com/assets/1994820/23046794/9b911fbc-f460-11e6-8647-f1c3a42e9219.png">

Pressed list item color #E0E0E0

**Comment by antlam** [comment]
Something to think about @bbinto ... are we OK with Firefox, Chrome, etc being tucked under the "Open with..." menu item with the rest of the other apps that could handle links?

or, we could special case ourselves and pull out "Firefox (Private browsing)" into an additional menu list item.

**Comment by pocmo** [comment]
> Something to think about @bbinto ... are we OK with Firefox, Chrome, etc being tucked under the "Open with..." menu item with the rest of the other apps that could handle links?

For roughly two weeks after Kona I used the prototype as my default browser. And every additional click I had to do in order to get to my real browser (when needing cookies or passwords) was super annoying. This was ultimately the reason why I switched back to Nightly. It would be nice if the "Open with.." at least shows the last/most used browser as an icon (like our Quick share in Fennec!) for direct access.

**Comment by antlam** [comment]
If it's not an immense amount of Engineering, I think adding a "last used" icon on the right of the Share and Open with.. option sounds like a great idea. But as a user, I would have concerns around privacy seeing this type of "smart"/"adaptive" behavior.

**Comment by antlam** [comment]
<img width="379" alt="screen shot 2017-02-17 at 10 52 47 am" src="https://cloud.githubusercontent.com/assets/1994820/23078862/40b65a18-f4ff-11e6-90db-88f4233535a2.png">

@pocmo I forget, why did we need an "Open with..." button again?

Maybe we could do something like this?

**Comment by pocmo** [comment]
@antlam Are you happy with the current version of the menu or are there things we need to tweak?

**Comment by antlam** [comment]
@pocmo I see an "Open with Open" option right now under "Open with Firefox". Pressing it crashes the app.

Is that a known issue? or should we try to address that bug here?

**Comment by pocmo** [comment]
> Is that a known issue? or should we try to address that bug here?

That's #162!

**Comment by pocmo** [comment]
Closing this one. Let's open new issues if we decide to change/polish some things.
