### ISSUE TITLE
The Website name is cut off in the site security section

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5201]
## Steps to reproduce
1. Visit a website with a long name;
2. Tap the Shield Icon to the left of the URL bar;
3. Tap the Connection is secure/not secure;
### Expected behavior
The site's name should be displayed without issues
### Actual behavior
The site name is cut of.
### Device information

* Android device: Oppo Find X3 Neo (Android 11), OnePlus 6T (Android 9)
* Focus version: Latest debug build from main 8/24
![cut_off](https://user-images.githubusercontent.com/50983519/130622610-38e170b8-28e6-4f6b-9ee6-10d934f554a7.png)

**Comment by mcarare** [comment]
Handled in #5202.

**Comment by mcarare** [comment]
Reopened for QA.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest debug build from main 8/25.

### Devices used:
- Oppo Find X3 Neo (Android 11)
- OnePlus 6T (Android 9)
