### ISSUE TITLE
[debug build] "Add to shortcut"/"Remove from Shortcut" options are still available after adding/removing the shortcut

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5203]
## Steps to reproduce
1. Open a page and add it as a shortcut.
2. Re-open the three-dot menu and observe the "Add to shortcut".
3. Clear the browsing history.
4. From the app's homescreen, tap on one of the added shortcuts.
5. Open the three-dot menu and tap on "Remove from Shortcuts".
6. Open again the three-dot menu, and observe.

### Expected behavior
After adding or removing a page from shortcuts, the options should interchange.
If a page is added already, there should only be "Remove from Shortcuts" option available, and viceversa.

### Actual behavior
The user can add a page multiple times (I added a page 10 times, the option is still available, but there are only 4 shortcuts on the app's homescreen).
The user has the option "Remove from Shortcuts" even after all the shortcuts have been removed, even after refreshing the page.

### Device information
* Android device: Lenovo Tab M10 (Android 10)
* Focus version: debug build from 8/24 main

**Comment by lobontiumira** [comment]
Verified as fixed on the 93.0.1 pre-release build, with Lenovo Tab M10 (Android 10).

**Comment by delia-pop** [comment]
Verified as fixed as well on 93.1.0 RC build with Huawei P9 Lite (Android 8).
