### ISSUE TITLE
Display Shortcuts in the AwesomeBar

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/focus-android#5216]

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main from 9/1 with Samsung Galaxy Note 8 (Android 9), by following these STR:
1. Add a page as a shortcut.
2. Go to the homescreen.
3. Load a different page.
4. Tap on the URL bar to edit the page from step 3.

The added shortcuts are displayed below the awesomebar, and the "Show search suggestions?" banner:

![Screenshot_20210901-105844_Firefox Focus](https://user-images.githubusercontent.com/40694158/131635183-225723af-db3e-4f26-9c78-bd173a155a48.jpg)

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest debug build from main 8/25.

### Devices used:
- Oppo Find X3 Neo (Android 11)
- OnePlus 6T (Android 9)
