### ISSUE TITLE
 "Switch to link in new tab immediately" doesn't work

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5217]
## Steps to reproduce
1. Open Firefox Focus, and enable the  "Switch to link in new tab immediately" from Settings - General.
2. Open a page with multiple links, like bbc.co.uk, or cnn.com.
3. Tap on a linked text, and observe.

### Expected behavior
The tapped link is opened in a new tab.

### Actual behavior
Tapping on a linked text redirects the user to that link, but in the same tab, does not open a new tab. 

### Device information
* Android device:  Oppo Find X3 Neo (Android 11), OnePlus 6T (Android 9), Samsung Galaxy Note 8 (Android 9), and Lenovo Tab M10 (Android 10)
* Focus version: 91.3.0 RC build, and debug build from 8/25 main

**Comment by mcarare** [comment]
I think the setting is related to automatically switching to links opened in new tabs (as opposed to showing the snackbar to switch to it), not for opening every tapped link in a new tab.

Having said that, that behavior is not working as expected either. :)

**Comment by lobontiumira** [comment]
Reproducible on  version too, with Lenovo Tab M (Android ).

**Comment by pocmo** [comment]
Does Fenix have that (I don't think so?). Is there anything in Focus that makes this more needed? (cc @brampitoyo)

**Comment by mcarare** [comment]
@pocmo, Fenix does not have this, that is why AC use cases to not include a scenario where we do not show the snackbar but switch to tab immediately.

**Comment by brampitoyo** [comment]
@lobontiumira @mcarare @pocmo I don’t recall Fenix having this feature. For Focus, since we are planning to gradually let the multi-tasking feature take a backseat, I don’t see a reason why we need this feature.

If my proposal is to take this feature out, would that be feasible?

**Comment by mcarare** [comment]
Yes, I can just remove the preference from the screen, as it is not used anywhere in the app.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main (GV 93.0a1-20210824094724), with Samsung Galaxy Note 8 (Android 9).
The option is no longer displayed in the General page:

![Screenshot_20210831-153950_Firefox Focus](https://user-images.githubusercontent.com/40694158/131504262-c369246f-1774-4037-95fb-bed80efa595a.jpg)

**Comment by delia-pop** [comment]
Verified as fixed as well on 93.1.0 RC build with Huawei P9 Lite (Android 8).
