### ISSUE TITLE
[bug] The refresh/cancel button from the toolbar is black

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5222]
## Steps to reproduce
1. Install the latest debug build from main from 8/26.
2. Open a page, and observe the toolbar.

### Expected behavior
All the buttons are white (back/forward arrows, refresh/cancel, ETP icon).

### Actual behavior
The refresh/cancel button is black.

### Device information
* Android device: Lenovo Tab M10 (Android 10)
* Focus version: the latest debug build from main from 8/26

![1212](https://user-images.githubusercontent.com/40694158/130961392-c2f2f0f2-6abe-4391-90d0-3149be3bce25.jpg)

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Focus 93.1.0.

### Device used:
- Huawei MediaPad M3 (Android 9)
