### ISSUE TITLE
[bug] The "Android system: Couldn't capture screenshot" pop-up isn't displayed when "Steatlh" toggle is enabled on certain devices

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5223]
## Steps to reproduce
1. Open a page.
2. Go to Settings - Privacy & Security - Switching Apps, and enable the Stealth toggle.
3. Exit Settings, And try taking a screenshot of the page.

### Expected behavior
The pop-up "Android system: Couldn't capture screenshot" is displayed.

### Actual behavior
No pop-up "Android system: Couldn't capture screenshot" is displayed. 

### Device information
* Android device: Lenovo Tab M10 (Android 10)
* Not reproducible on Samsung Galaxy Note 8 (Android 9)
* Focus version: the latest debug build from main from 8/26, and RC 91.3.0

**Comment by pocmo** [comment]
Does it still prevent screenshots?

**Comment by lobontiumira** [comment]
@pocmo yes, the screenshot cannot be taken.

**Comment by mcarare** [comment]
@lobontiumira Can you test if that happens on Fenix also on the same device? It might not be something we can fix, but device/OS-specific. 
Thank you!

**Comment by pocmo** [comment]
I somehow think this has come up before and some devices or Android versions just do not show this message. It's definitely a system feature to show this popup. I am so sure that this exact discussion happened on this issue tracker before, but I can;t find it.

**Comment by pocmo** [comment]
Finally found it: https://github.com/mozilla-mobile/focus-android/issues/775

**Comment by lobontiumira** [comment]
You are right! The device is not displaying the pop-up for Fenix either.
It is device specific. 
I'll close the issue.
Thanks!
