### ISSUE TITLE
[custom tab] Some elements from the three-dot menu have black texts

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5235]
## Steps to reproduce
1. Set Firefox Focus as your default browser.
2. From Gmail, open a custom tab.
3. Tap the three-dot menu and observe the options.

### Expected behavior
The menu's options have the same white color.

### Actual behavior
Some options are black texts.

### Device information
* Android device: Lenovo Tab M10 (Android 10), Samsung Galaxy Note 8 (Android 9)
* Focus version: debug build from main from 8/27, Focus build version 93.0.0

![Screenshot_1](https://user-images.githubusercontent.com/40694158/131089299-f9cb1dcb-f047-41a8-b13b-ed901088baad.jpg)

**Comment by lobontiumira** [comment]
This is not fixed yet entirely. The "Powered by Firefox Focus" text is still black when opening the first custom tab. Opening another custom tab, fixes this.

Tested on the 93.0.1 build (GV 93.0a1-20210831093704) with Lenovo Tab M10 (Android 10).

![custom tab](https://user-images.githubusercontent.com/40694158/131981095-438a12bd-f7dc-40c6-af4a-6f0adefbb946.png)

**Comment by mcarare** [comment]
@lobontiumira I think the remaining issue can be tracked here: https://github.com/mozilla-mobile/focus-android/issues/5325
