### ISSUE TITLE
[bug] Disabling the trackers from ETP section doesn't work

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5236]
## Steps to reproduce
1. Open https://senglehardt.com/test/trackingprotection/test_pages.html, and tap on Trackers & Cookies.
2. Go to Settings - Privacy & Security - Enhanced Tracking Protection section.
3. Disable ad trackers, or analytic trackers, or social trackers, or other content trackers.
4. Go back to the page opened in step 1 and reload it.
5. Observe if the trackers are now not blocked.

### Expected behavior
The page shows that analytics trackers, or ad trackers, or social trackers are not blocked.

### Actual behavior
The page shows that analytics trackers, or ad trackers, or social trackers are still blocked.
Force closing the app, and re-opening the page doesn't fix the issue.

### Device information
* Android device: all
* Focus version: 93.0.0
* NOT reproducible on the debug build from 8/27 from main

https://user-images.githubusercontent.com/40694158/131110796-8a356f03-d3cc-4fef-a50c-5c90cd0a73c7.mp4

**Comment by Amejia481** [comment]
Thanks for reporting, this was addressed with https://github.com/mozilla-mobile/focus-android/pull/5264, it should be already fixed  on `main`.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from 9/1 from main, with Samsung Galaxy Note 8 (Android 9).
