### ISSUE TITLE
[bug] The Web Content features don't work on https://mozilla-mobile.github.io/testapp/

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5238]
## Steps to reproduce
1. Go to https://mozilla-mobile.github.io/testapp/ to Custom Font Test.
2. Go to Settings -> Privacy & Security -> "Web Content" section.
3. Enable "Block Web fonts" setting, exit Settings and go back to https://mozilla-mobile.github.io/testapp/.
or
4. Enable "Block JavaScript", exit Settings, go to https://mozilla-mobile.github.io/testapp/, and tap on the "Click here for JS alert" button.

### Expected behavior
The "This is some crazy font text!" has now the same font style as all other texts.
or 
The alert does not pop up.

### Actual behavior
The red web font "This is some crazy font text!" is still in a non-standard font.
or 
The alert does pop up.

### Device information
* Android device: Lenovo Tab M10 (Android 10), Samsung Galaxy Note 8 (Android 9)
* Focus version: 93.0.0
* Not reproducible on the latest debug build from 8/27 from main

**Comment by mcarare** [comment]
I cannot reproduce this on main either.

**Comment by lobontiumira** [comment]
Verified that is not reproducible on the latest debug build from main from 9/17 with Lenovo Tab M10 (Android 10), Samsung Galaxy Note 8 (Android 9), and OnePlus 5T (Android 10).

However **it still reproduces on 93.0.2 build.**
