### ISSUE TITLE
Disabling the "Safe browsing" option does not allow visiting unsafe web pages

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5239]
## Steps to reproduce
1. Go to Setting->Privacy & Security;
2. Set Safe browsing to off;
3. Visit several unsafe pages such as:
https://itisatrap.org/firefox/its-a-trap.html
https://itisatrap.org/firefox/its-an-attack.html
https://itisatrap.org/firefox/unwanted.html
https://itisatrap.org/firefox/harmful.html
### Expected behavior
The webpages should load without warnings.
### Actual behavior
A warning message and "Try again" button is displayed.
### Device information
* Android device: Oppo Find X3 (Android 11), OnePlus 6T (Android 9)
* Focus version: 93.0.0
* Not reproducible on the latest debug build from 8/27 from main

**Comment by mcarare** [comment]
I cannot reproduce this on latest main.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue either on the latest debug build from main 93.0 (build 11 GV 93.0a1-20210901091701), nor on 92.1.1, with Lenovo Tab M10 (Android 10), Google Pixel (Android 10), and OnePlus 5T (Android 9).

**Comment by LaurentiuApahideanSV** [comment]
The issue still occurs on Focus 93.0.2, it does not occur on the latest debug build from main 9/13.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by sv-ohorvath** [comment]
Still occurs on Focus RC 93.1.0.

**Comment by mcarare** [comment]
@lobontiumira Can you test the behaviour on another test site? some of the links do not work as expected, neither on Focus, Fenix or other browsers with safe browsing.

https://testsafebrowsing.appspot.com/ for example.

Thank you!

**Comment by lobontiumira** [comment]
I tested on the pages mentioned by you, Mihai, and on the pages from comment 0, and everything works as expected on the Beta 95.0.0-beta.3, on RC 94.1.1 and on the latest debug build from main from 11/5, with Sony Xperia Z5 (Android 7.1.1), OnePlus 5T (Android 10), Samsung Galaxy Tab a6 (Android 5.1.1), and Samsung Galaxy Note 8 (Android 9).
