### ISSUE TITLE
[bug] "Manage sites" option should be inactive when URL Autocomplete is disable "For sites you add"

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5243]
## Steps to reproduce
1. Go to Settings - Search - URL Autocomplete, and disable the "For Sites You Add" toggle.
2. Tap on "Manage sites".

### Expected behavior
The "Manage sites" cannot be accessed. The option is inactive.

### Actual behavior
The "Manage sites" is enabled but doesn't work. The user may not know that, by disabling the URL Autocomplete "For sites you add", this area is not available anymore.

### Device information
* Android device: all
* Focus version: 93.0.0, the latest debug from main 8/27

![Screenshot_3](https://user-images.githubusercontent.com/40694158/131138776-a007a8be-ad26-4de7-946f-b50900533c1f.jpg)

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 8/31 with Samsung Galaxy Note 8 (Android 9).

**Comment by delia-pop** [comment]
Verified as fixed as well on 93.1.0 RC build with Huawei P9 Lite (Android 8).
