### ISSUE TITLE
Switch places between the Refresh and Share button in the main menu

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5244]
## Steps to reproduce
1. Visit a website
2. Open the main menu
3. Observe the position of the Refresh button.
### Expected behavior
The refresh button should be the last one in the row, as it is in most apps, and users are used to that.
### Actual behavior
Accidentally tapping the share button instead of refresh, because of muscle memory.
### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: Pre-release 93.0.0

**Comment by brampitoyo** [comment]
@sv-ohorvath @amedyne Agreed. Thanks for the suggestion, and good call!

I should’ve been aware that Fenix already had the positioning you suggested: Back, Forward, Share, Refresh. Focus should be identical to that.

Let’s swap the positioning of the Share and the Refresh icons.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Klar & Focus build from main from 8/31, with GV 93.0a1-20210824094724, with Samsung Galaxy Note 8 (Android 9).

**Comment by delia-pop** [comment]
Verified as fixed as well on 93.1.0 RC build with Huawei P9 Lite (Android 8).
