### ISSUE TITLE
The Find in Page search field appears behind the keyboard

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5247]
## Steps to reproduce
1. Open any website that contains text;
2. From the 3 dot menu select Find in Page
### Expected behavior
The search field should appear above the keyboard.
### Actual behavior
The search field appears behind the keyboard
### Device information

* Android device: Oppo Find X3 (Android 11), OnePlus 6T (Android 9)
* Focus version: 93.0.0

https://user-images.githubusercontent.com/50983519/131150207-5c65c114-8134-4d51-b801-9bd4d43b64e1.mp4

**Comment by ionutbedregeanu** [comment]
Please read this comment before testing: https://github.com/mozilla-mobile/focus-android/pull/5099#discussion_r689168165

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from 9/9 from main, and on RC 92.1.1.
The both mentioned builds use the top-aligned “Find in page” UI.

![Screenshot_20210909-161015](https://user-images.githubusercontent.com/40694158/132692167-4408c408-ef6d-4c52-9d5e-a86caa512b50.jpg)
