### ISSUE TITLE
Open in app popup on every click

### ISSUE THREAD

**Issue by pepperminth** [mozilla-mobile/focus-android#5252]
## Steps to reproduce
1. Open link of website that has an app on phone
2. Click cancel on "Open in app" popup

### Expected behavior
Open links without "Open in app" popup

### Actual behavior
Repeated "Open in app" popup for every click on website

### Device information

* Android device: OnePlus 5T
* Focus version: v91.2.1 onwards

Bug introduced with commit 348d858

https://user-images.githubusercontent.com/89726223/131244541-4c4135ff-70d2-4b80-a73a-4d33177d57de.mp4

**Comment by Poopooracoocoo** [comment]
An option to _enable_ this would be awesome :)

I'm very rarely going to open a website in its app from Focus. 

If I am, I'm going to want to set to automatically open the app for just that website. Or I'm going to do it explicitly and will want to open the context menu and open it in its app from there.

**Comment by Wicked0ne** [comment]
This really needs to be a option to turn off. I almost never ever want to open a link in another app. If I do, I can use the "open in" menu option.

Some sites even trigger 2 open in popups. For example www.YouTube.com opens a prompt and I hit cancel, YouTube then redirects me to m.youtube.com which opens another her prompt.

**Comment by ionutbedregeanu** [comment]
@pocmo I made some debug to find the source of this problem and it seems that are situations when [here](https://github.com/mozilla-mobile/android-components/blob/44bc568df8d9f0d6ca76d32536ad3b7341fff138/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt#L148) we are comparing the main website domain with a short url(a redirecting url) which results in a false response from this function.

As example, if we are replacing that short url with its extended version, 'isSameDomain' function would recognise both urls as having the same domain, which is the right behaviour and fix the bug.

My question is: Is something we can do about that?
To expand every short url and verify it doesn't seem like a solution

**Comment by pocmo** [comment]
CC @rocketsroger (who worked on `feature-app-links`) and @brampitoyo (to look at this from UX point of view)

I wonder if we need two different behaviors based on the URL:
* For app specific schemes, let's say "amazon://" we should offer to open them in the app if the user wants to, after all that's the only way to open this URL.
* For http(s), in Focus, I think the most sensible approach is to never offer to open them in an app via the popup. For this Focus has "Open in .." as a menu item that offers to switch to full-featured browsers, as well as matching apps.

@brampitoyo What do you think?

**Comment by brampitoyo** [comment]
@pocmo I think that sounds sensible, but I’d like to check what Fenix’s behaviour is.

I recall that Fenix has a toggle, but defaults the value to OFF.

Is that a sensible policy that we can apply to Focus? So then, people who want it can manually turn it ON. Or, will it add yet another toggle to Focus and make it more complex?

Would love to hear your feedback and advice. Thanks!

**Comment by Wicked0ne** [comment]
Just me 2 cents: @pocmo's solution sounds great. Adding a toggle in focus's options menu would also be great, the current options menu doesn't have a lot of options so I don't think adding a few toggle would pollute it.

**Comment by Amejia481** [comment]
Related https://github.com/mozilla-mobile/focus-android/issues/5225

**Comment by ionutbedregeanu** [comment]
I will close this ticket since is addressed by #5225
