### ISSUE TITLE
"Add link to autocomplete" feature is missing in v.93

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5255]
## Steps to reproduce
1. Visit a website.
2. Tap the URL bar and observe if "Add link to autocomplete" is displayed under the selected URL.
### Expected behavior
In version 91 the feature still works.
See screenshot:
![Screenshot_20210830-115002](https://user-images.githubusercontent.com/4037709/131313969-7775b0c7-5f37-4759-ad88-b40984acc681.png)
### Actual behavior
Missing feature since the nav bar has changed.
### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: Pre-release 93.0.0

**Comment by cadeyrn** [comment]
This was removed in favour of the new shortcuts feature, see https://github.com/mozilla-mobile/focus-android/pull/5154#issuecomment-900281326.

**Comment by sv-ohorvath** [comment]
oh, thanks, that's true.
