### ISSUE TITLE
[bug] Can't add shortcuts on (Device)homescreen with Huawei MediaPad M2 (Android 5.1.1)

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#5257]
## Steps to reproduce
1.Open an webpage.
2. Select "Add to Home screen" from the menu.

### Expected behavior
Add to Home screen dialog pops up and the page is added to the homescreen. 

### Actual behavior
The dialog might not be displayed (1/3) at all.
The dialog is displayed, and after the "Add" button is taped, the shortcut is not available on the device's screen. 

### Device information
* Android device: Huawei MediaPad M2 (Android 5.1.1)
* Focus version: 93.0.0, 91.3.0.
** Not reproducible on: Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by mcarare** [comment]
@sflorean Can you add any other shortcuts (from any other app, maybe try Fenix) on that device?
We might need to hide that menu item on devices that have a launcher that does not support pinning.

**Comment by mcarare** [comment]
For QA: The option should not show up in the menu for devices that do not allow shortcuts to be added.

**Comment by sflorean** [comment]
> @sflorean Can you add any other shortcuts (from any other app, maybe try Fenix) on that device?
> We might need to hide that menu item on devices that have a launcher that does not support pinning.

@mcarare sorry for late reply here.
Tested on Focus 93.0.2 and the issue is still reproducible:
- the menu option is still displayed
- on Fenix, the shortcuts are added to the device home screen without issues

**Comment by sflorean** [comment]
Tested again on the main and here is a log: [focusHomescsreenOption.txt](https://github.com/mozilla-mobile/focus-android/files/7178490/focusHomescsreenOption.txt).

**Comment by mcarare** [comment]
This part is relevant:
` I/HwLauncher: InstallShortcutReceiver Do not install shortcut ,because has the ComponentName activity with launcher caterory. component=ComponentInfo{org.mozilla.focus/org.mozilla.focus.activity.MainActivity}`

**Comment by mcarare** [comment]
This can be retested on the main branch.

**Comment by sflorean** [comment]
Verified as fixed with Huawei MediaPad M2 (Android 5.1.1), shortcuts can be added to the homescreen. 

But when tapping on the shortcut, the following message is displayed "App is not installed". 
@mcarare ^
