### ISSUE TITLE
Audit the Falcon dependency

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/focus-android#5267]
> I changed the title of this issue to "Audit the Falcon dependency". There were some questions about the impact on security of this dependency. Maybe someone can scan through the code (400 lines) and make sure this doesn't do anything dangerous.

Focus includes https://github.com/jraska/Falcon as a dependency but it doesn't actually seem to be used. I could not find any invocations of the Falcon code. Let's remove this dependency.

**Comment by mcarare** [comment]
I think it is needed by `tools.fastlane:screengrab` : https://github.com/mozilla-mobile/focus-android/pull/5144/files#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R271.

We also have this in Fenix.

**Comment by st3fan** [comment]
Yeah I think you are right.
