### ISSUE TITLE
tips on start screen are truncated to a maximum of two lines

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#5271]
### Steps to reproduce

0. use a language with longer translations, like German
1. start Focus

### Expected behavior

You can read all tips.

### Actual behavior

Tips can be truncated (second tip):

![Screenshot_20210830-212506](https://user-images.githubusercontent.com/1100614/131395083-e41fed80-9c90-4ed5-8dae-06c1fb4e59ac.jpg)

The full string is "Erstellen Sie Verknüpfungen zu den meistbesuchten Websites:\n
Wählen Sie aus dem %1$s-Menü die Option „Zu Verknüpfungen hinzufügen“"

As you can see the `hinzufügen“` part is missing.

And on the third tip you can also see only two lines but you can scroll to see the third line (does not work for tthe second tip).

### Device information

* Android device: OnePlus 7T Pro McLaren, Oxygen OS 11 (Android 11)
* Focus version: main branch revision 56ab7b8a872f19f4397553b516837b80b750c6f1

**Comment by lobontiumira** [comment]
Verified as fixed on both Focus, and Klar, the latest debug builds from main from 9/3.
Tested with Google Pixel (Android 10).

![deutsch](https://user-images.githubusercontent.com/40694158/131990033-b6990a50-e002-4084-9b00-b136d0f59bf5.png)

**Comment by brampitoyo** [comment]
@lobontiumira @mcarare Good call here. I agree that we should extend to three lines, but align the paragraph itself to the bottom (rather than top).

This way, there’s always the same amount of empty space between the carousel dots (• • • • •) and the last line of the tips.
