### ISSUE TITLE
link is missing for first tip in carousel

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#5272]
### Steps to reproduce

1. open Focus

### Expected behavior

I don't know if there is a link planned for the first tip in the carousel on the start screen because all your documents are access restricted but from reading the first tip ("read more") I would expect that there is a link:

![Screenshot_20210830-212716](https://user-images.githubusercontent.com/1100614/131396781-386de361-ae4a-406f-87a2-1cf251da08b3.jpg)

### Actual behavior

There is no link.

### Device information

* Android device: OnePlus 7T Pro McLaren, Oxygen OS 11 (Android 11)
* Focus version: main branch revision 56ab7b8a872f19f4397553b516837b80b750c6f1

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest Focus build from main 09/14.
### Devices used:
- Oppo find X3 (Android 11)
- OnePlus 6T (Android 9)
