### ISSUE TITLE
Add whats new link for Klar build.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5276]
Following the discussion offline with @fabiLpz we should direct Klar users to a separate Klar whats new page.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Klar & Focus build from main, with GV 93.0a1-20210824094724, with Samsung Galaxy Note 8 (Android 9).
The What's new link for Focus is https://support.mozilla.org/en-US/kb/whats-new-firefox-focus-android?as=u&utm_source=inproduct, and for Klar is https://support.mozilla.org/en-US/kb/whats-new-firefox-klar-android?as=u&utm_source=inproduct.

![whats new](https://user-images.githubusercontent.com/40694158/131509792-17f2ebe5-536e-4853-95e7-6e12ecb4fa57.png)
