### ISSUE TITLE
[Bug] Tips on the landing screen don't swipe/scroll consistently

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/focus-android#5287]
The tips on the landing page aren't responding to swipes in a consistent way. 

Steps to reproduce: 
1. Open Nightly or debug (I saw this on `main`)
2. See the dot carousel for the tips, try to swipe. Not able to swipe.
3. Close keyboard, try to swipe again: it works!

Closing and opening the keyboard seems to make it work, but does not seem consistent to me: sometimes it works with the keyboard open, sometimes it works when the keyboard is closed. 

Device: Pixel 3, Android 10
(will attach gif to the jira issue)

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main from 9/3 with LEnovo Tab M10 (Android 10), and with Samsung Galaxy Tab A6 (Android 5.1.1), and the tips from the carousel can be swiped right/left, without issues.
