### ISSUE TITLE
Toolbar hint text moves when keyboard is raised and lowered

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#5290]
### STR
- On the homescreen, click toolbar to raise keyboard
- Lower keyboard

### Expected
Hint text stays in the same location

### Actual
Hint text moves slightly, looking a little unpolished

![gif](https://user-images.githubusercontent.com/759372/131589948-f14f98f7-c8f7-47cc-b44b-880749f9a808.gif)

This is a local branch built off 56ab7b8a872f19f4397553b516837b80b750c6f1 on a Moto G5

**Comment by mcarare** [comment]
This is because `mozac_browser_toolbar_displaytoolbar` and `mozac_browser_toolbar_edittoolbar` have a different value for `layout_goneMarginStart` for the view that displays the url/hint :  `mozac_browser_toolbar_origin_view` and `mozac_browser_toolbar_edit_url_view`.

**Comment by mcarare** [comment]
AC issue: https://github.com/mozilla-mobile/android-components/issues/10916

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main 93.0 (build 11 GV 93.0a1-20210901091701), with Lenovo Tab M10 (Android 10), Google Pixel (Android 10), Samsung Galaxy Tab A6 (Android 5.1.1), and OnePlus 5T (Android 9).

@mcarare on the Lenovo device, there is a slightly move, the "Search or enter address" characters have less space between them:

https://user-images.githubusercontent.com/40694158/132329472-0265d81e-823f-4e52-ab0d-d8bb824994d7.mp4

**Comment by mcarare** [comment]
Lenovo is a tablet, I think? This looks like an issue, but a different one, the font size looks different. If you would open a separate issue with a tablet tag I will investigate it also. Thank you!

**Comment by lobontiumira** [comment]
I've filed #5349 for the tablet issue mentioned. I'll close this issue as fixed.
