### ISSUE TITLE
The "Language" page has extra elements

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5293]
## Steps to reproduce
1. Install the latest debug build from main from 9/1.
2. Go to Settings - General - Language, and observe the page.

### Expected behavior
The design is like in Figma https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2140%3A71629.
The page has a back arrow, and no "Cancel" button.

### Actual behavior
The "Language" page has a "Cancel" button in the bottom-right corner, no back arrow, and scrolling through it, displays some borders - please see the attached screenshot.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9).
* Focus version: latest debug build from main from 9/1

![language - debug](https://user-images.githubusercontent.com/40694158/131624288-ae03cb11-74a6-4c6e-a3b6-47ce0961a586.jpg)

**Comment by mcarare** [comment]
The refactoring of language and block cookies preferences has been postponed after 93.

**Comment by lobontiumira** [comment]
Tested on Focus Nightly 95.0 (build 353060511 GV 95.0a1-20211101084651) with Samsung Galaxy Note 8 (Android 9), and the design in Figma is different:

![language](https://user-images.githubusercontent.com/40694158/139812968-7d9ed80c-c632-44d7-bb3a-b9f82f4cb6ba.png)

**Comment by iorgamgabriel** [comment]
I'm working on this

**Comment by lobontiumira** [comment]
Verified on 1/6 Focus Nightly (build 360061030 GV 97.0a1-20220105093353) with several devices:
* Oppo Find X3 Lite (Android 11),
* Samsung Galaxy Tab A6 (Android 5.1.1),
* Lenovo tab M10 (Android 10), and
* Xiaomi mi4i (Android 5.0.2).

Found some regressions, and filed #6170, and #6171.
I'll remove the QAReady label, and leave this ticket opened until the two new tickets are fixed.

Thank you!

**Comment by delia-pop** [comment]
Verified as fixed also on Beta 97.0.0-beta.1 with Google Pixel 6 (Android 12). 
We'll close this ticket, and the above mentioned issues will be treated separately.

**Comment by delia-pop** [comment]
Reproducible on RC 96.3.0 with Google Pixel 6 (Android 12).
