### ISSUE TITLE
Mozilla products telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5295]
https://mozilla-hub.atlassian.net/browse/FADPV2-2926

**Comment by AndiAJ** [comment]
Hi verified as fixed on a nightly build created from latest master using a OnePlus A3 (Android 6.0.1)

✅   Fenix Nightly installed and set as default browser - Ping bede6514-a48c-4dad-9259-a38c21cc677c
```
"metrics": {
        "boolean": {
          "browser.is_default": false,
          "mozilla_products.has_fenix_installed": true,
          "mozilla_products.is_fenix_default_browser": true
```
✅   Fenix Nightly installed and Focus set as default browser - Ping d5b377df-999c-4ad9-b6cb-23418c11ebc4
```
"metrics": {
        "boolean": {
          "browser.is_default": true,
          "mozilla_products.has_fenix_installed": true,
          "mozilla_products.is_fenix_default_browser": false
```
✅   Fenix Beta installed and set as default browser - Ping 854552f9-62b3-4a85-993d-08d12e62534b
```
metrics": {
        "boolean": {
          "browser.is_default": false,
          "mozilla_products.has_fenix_installed": true,
          "mozilla_products.is_fenix_default_browser": true
```
✅   Fenix Beta installed and Focus set as default browser - Ping c2a0f1eb-51cd-4594-b0f9-783293337f89
```
metrics": {
        "boolean": {
          "browser.is_default": true,
          "mozilla_products.has_fenix_installed": true,
          "mozilla_products.is_fenix_default_browser": false
```
✅   Fenix RC installed and set as default browser - Ping 98764852-d94d-411d-82cd-ae4b04a5c469
```
"metrics": {
        "boolean": {
          "browser.is_default": false,
          "mozilla_products.has_fenix_installed": true,
          "mozilla_products.is_fenix_default_browser": true
```
✅   Fenix RC installed and Focus set as default browser - Ping ae1a143f-9c67-41cf-bed7-032a3ee1df52
```
"metrics": {
        "boolean": {
          "browser.is_default": true,
          "mozilla_products.has_fenix_installed": true,
          "mozilla_products.is_fenix_default_browser": false
```
[Logcat](https://github.com/mozilla-mobile/focus-android/files/7107043/defaFoc.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-0903103)
