### ISSUE TITLE
Most menu items truncate in priority languages

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#5305]
## Steps to reproduce
Go to a website
Open the menu

### Expected behavior
Strings are not truncated

### Actual behavior
Strings are truncated and incomprehensible

### Device information
Pixel 2

* Android device: v 11
* Focus version: Nightly (Focus crashes when I try to see the Nightly version)

Note: this has initially been reproduced by @flodolo who has another device, and I confirm I see all the same issues. This is really concerning because most menu items are incomprehensible at this point
Also reproducible in Italian, French, German, and other "priority" locales. See screenshot in Italian below
CC @amedyne for visibility.
![menu](https://user-images.githubusercontent.com/399020/131731984-df8894a9-a4a5-4728-9252-7af312407254.jpg)

**Comment by amedyne** [comment]
Tagging @brampitoyo for input from UX.

**Comment by mcarare** [comment]
The way we handle this in Fenix is to allow the menu to stretch to a maximum width (set in Fenix ) while also allowing a minimum of 48dp (constraint in AC) space to allow the menu to be dismissed on taping outside of it. 
@Bram, I implemented this with the same sizes we use in Fenix here: https://github.com/mozilla-mobile/focus-android/pull/5315.

**Comment by brampitoyo** [comment]
@mcarare Excellent suggestion. I was going to say “Let’s follow Fenix’s implementation”, so I agree completely.

**Comment by lobontiumira** [comment]
Verified on the 93.0 (build 11 GV 93.0a1-20210906031657), and on 93.0.2 pre-release with OnePlus 5T (Android 9).
The page's menu is wider, but some options in some languages are still truncated:

![languages](https://user-images.githubusercontent.com/40694158/132862734-4433d812-93da-4193-890f-91cfb470897b.png)

@Delphine please review and advise.
Thank you!

**Comment by Delphine** [comment]
@brampitoyo @mcarare: Is it technically impossible to have the text wrap to a second line (we do that in other areas)? That would be preferable given this is the main menu and affects top tier locales

**Comment by brampitoyo** [comment]
@Delphine @mcarare I am happy to have the text wrap to the second line.

Follow this specs for two-line list items:
https://material.io/components/lists#specs

Except in our case, the second line does not contain secondary text. It’s simply the item title that spills over.

**Comment by mcarare** [comment]
@Delphine We do not wrap menu items to the next line anywhere. I am not sure I know any Android app to do that. IMO it would not look good. We also have this behaviour on Fenix where list items are truncated on some languages, and other browsers have that too.

**Comment by Delphine** [comment]
@mcarare I tend to disagree: if we can avoid truncation and having a poor experience for users, I believe we should wrap text (even in Fenix and other browsers)
We do this on iOS, for example.
My concern is that the meaning of the string is lost here in certain languages - which might impact how the users interact with this menu item.

**Comment by flodolo** [comment]
@mcarare 
I don't understand. QA [reported issues](https://github.com/mozilla-mobile/focus-android/issues/5305#issuecomment-916916082) for several top locales. Why would you need more reports?

> IMO it would not look good.

Having a menu that is not understandable is worse than having a menu that might potentially look worse.

**Comment by cadeyrn** [comment]
It was not considered as a problem in Fenix. Why is it a problem in Focus? 🤔

Since one of the screenshots show a German menu: In the largest German speaking Firefox support forum there was not one user who didn't understand a menu item or complained about a few truncated characters, neither for Fenix nor for Focus. And in Fenix more menu items are truncated than in Focus.

**Comment by flodolo** [comment]
> It was not considered as a problem in Fenix. Why is it a problem in Focus? 🤔

If there is a technical way to avoid truncation, why shouldn't we take advantage of it? BTW, according to internal feedback, iOS does wrap menu items.

It's great if the issue doesn't affect you, but there are other languages out there. The first screenshot (which I'm aware doesn't match the current version, where the panel is larger), cannot be understood at all in Italian.

**Comment by mcarare** [comment]
> @mcarare I don't understand. QA [reported issues](https://github.com/mozilla-mobile/focus-android/issues/5305#issuecomment-916916082) for several top locales. Why would you need more reports?

I meant reports from users. Like was already mentioned, I am not aware of any compliant from a Fenix user.

**Comment by st3fan** [comment]
> > @mcarare I don't understand. QA [reported issues](https://github.com/mozilla-mobile/focus-android/issues/5305#issuecomment-916916082) for several top locales. Why would you need more reports?
> 
> I meant reports from users. Like was already mentioned, I am not aware of any complaint from a Fenix user.

We don't need complaints before we change something. We can simply decide that something is not meeting our quality standards and then make it better.

**Comment by lobontiumira** [comment]
As per discussion we had, the decision was to leave the menus truncated for now.
I will close this issue.

**Comment by amedyne** [comment]
@flodolo The discussion was in a meeting on Tuesday 11/09 with the Product Manager @channingcarter and the development team. The decision was to keep the current behavior for now as the requirements for wrapping or expanding width for the strings on the settings menu are being re-evaluated.

**Comment by Delphine** [comment]
Thanks for confirming Amedyne. Looking forwards to the re-evaluation!
