### ISSUE TITLE
Snippet at the bottom of home page truncated on priority locales

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#5306]
## Steps to reproduce
Go to home page
Look at the different strings changing at the bottom of the screen (I think this can be forced by quitting and relaunching Focus)

### Expected behavior
Snippet is not truncated

### Actual behavior
Snippet is truncated and incomprehensible in many priority locales

### Device information
Pixel 2
Android device: v 11
Focus version: Nightly (Focus crashes when I try to see the Nightly version)

Note: this has initially been reproduced by @flodolo who has another device, and I confirm I see all the same issues. This is really concerning because this snippet is on the home page becomes incomprehensible
Also reproducible in Italian, French, German, and other "priority" locales. See screenshot in Italian below
CC @amedyne for visibility, and CC @brampitoyo 
![home](https://user-images.githubusercontent.com/399020/131732709-274ec0f1-4f45-49d7-9159-0ec3abbc9699.jpg)

**Comment by mcarare** [comment]
cc @ionutbedregeanu

**Comment by mcarare** [comment]
This looks the same as https://github.com/mozilla-mobile/focus-android/issues/5271

**Comment by mcarare** [comment]
Closing this and tracking issue in #5271.
