### ISSUE TITLE
App fails to search when launched from external search context menu

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/focus-android#5307]
## Steps to reproduce
* Launch Fenix
* Visit a website ex: https://en.wikipedia.org/wiki/Main_Page
* Long press on non link text to select it
* In the context menu tap 3 dot
* Select Search Privately 
* Focus should launch with a search of the selected text  

### Expected behavior
Focus searches on the text shared from the other app

### Actual behavior
Focus does not search the text. Tries to load `https://$SEARCH/`

### Device information

* Android device: ?
* Focus version: 91.4.0

**Comment by kbrosnan** [comment]
Video of behavior https://www.youtube.com/watch?v=jaM6GofMGWY

**Comment by mcarare** [comment]
On the main branch, this works a expected.

**Comment by kbrosnan** [comment]
This still reproduces on 93.

**Comment by ionutbedregeanu** [comment]
From what I see this can be reproduced when Focus app is not already in the background. I will work on this

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 9/27 with Lenovo Tab M10 (Android 10), and Samsung Galaxy Note 8 (Android 9).
