### ISSUE TITLE
Enable StrictMode penalty death

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#5309]
We're currently StrictMode penalty log which we found to be ineffective In fenix for preventing regressions. Let's enable StrictMode penalty death. Options:
- only enable on start up, like fenix (smaller scope)
- add lint check or runtime check for suppressing StrictMode like we do on fenix

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802662

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
