### ISSUE TITLE
1.3 MB APK size regression in v91.1.2 on 8/16

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#5311]
On the Google Play console, we see a regression in the release channel of Focus of 1.3 MB from v91.1.1 to v91.1.2 on August 16th. This is especially surprising because it's a dot release.

**Comment by ionutbedregeanu** [comment]
@mcomella Since the current release version is 102 should we keep open this ticket?

**Comment by mcomella** [comment]
@ionutbedregeanu This is up for the focus team to decide: e.g. do we think APK size is an important issue to tackle and, if so, would it be useful to keep open old tickets indicating prior APK size regressions?

**Comment by mcarare** [comment]
This is the difference between the 2 releases https://github.com/mozilla-mobile/focus-android/compare/v91.1.1...v91.1.2.
It does not seem that the increase is determined by code or added assets.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802661

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
