### ISSUE TITLE
Regression: Multiple search engines with the same name/string to use can be added

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5317]
## Steps to reproduce
1. Go to the three-dot menu -> Settings -> Search -> Search engine.
2. Tap on "+ Add another search engine".
3. Enter a name for the engine (e.g. test) and the string to use (e.g. test.com/search/?q=%s).
4. Tap on "SAVE". 
5. Repeat Steps 1-4 and create another search engine with the same name from Step 3 (e.g. test) and a different string to use.
6. Repeat Steps 1-4 and create another search engine with a different name and the same string to use from Step 3 (e.g. test.com/search/?q=%s).

### Expected behavior
5. A message error stating "An installed search engine is already using that name." should be displayed, preventing the user to save a new search engine with an already used name.
6. A message error stating "An installed search engine is already using the same string." should be displayed, preventing the user to save a new search engine with the same string to use.

### Actual behavior
5. No error message is displayed, the user can save the new search engine.
6. The User is be able to create another search engine with the same string to use already registered, however, sometimes the "Server not found" error might be displayed. 

Regression after issue https://github.com/mozilla-mobile/focus-android/issues/1880

### Device information
*Android device: Huawei P9 Lite (Android 8)
*Focus version: RC 92.1.0 (Build 352442046 ; 92.0-20210901142158)

https://user-images.githubusercontent.com/89388888/131824853-3e98a3f4-4077-432d-8cb9-336dcde7fbae.mp4

https://user-images.githubusercontent.com/89388888/131831683-54a5eaa8-3646-4b31-9ede-2bd4a83b6513.mp4

**Comment by mcarare** [comment]
This is something we should fix and we already have the string for this.

**Comment by lobontiumira** [comment]
Reproducible also on RC 92.1.1 with Lenovo Tab M10 (Android 10).

**Comment by mcarare** [comment]
This issue is for tracking the name error message. For the same search string the issue is: https://github.com/mozilla-mobile/focus-android/issues/5318

**Comment by delia-pop** [comment]
Verified as fixed on the 93.0 (Build 352522329 93.0a1-20210906031657) with Huawei P9 Lite (Android 10).  The "An installed search engine is already using that name." message is correctly displayed. 

As per comments in issue https://github.com/mozilla-mobile/focus-android/issues/5318,  search engines with the same search engine but different names can be added.
