### ISSUE TITLE
[bug] The GV icon is displayed as a grey square on Android 5 devices

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5319]
## Steps to reproduce
1. Install 92.1.0 Focus.
2. Go to Settings - Mozilla - About Firefox Focus, and observe the GV icon.

### Expected behavior
The green gecko is displayed.

### Actual behavior
A grey square is displayed instead of the green gecko.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), Xiaomi Mi4i (Android 5.0.2)
* Focus version: 92.1.0

![gv icon](https://user-images.githubusercontent.com/40694158/131850652-ab6666a9-bef3-4547-809b-6842218fde43.jpg)

**Comment by lobontiumira** [comment]
This is how it is displayed on the debug build from main:
![Screenshot_2](https://user-images.githubusercontent.com/40694158/131856417-1d2dfbbc-4867-4dbc-9a2f-83eada7fe969.jpg)

**Comment by mcarare** [comment]
Seems like Android 5 & 6 only support Unicode from versions 6.3 / 7 ([source](https://developer.android.com/guide/topics/resources/internationalization)).

The lizard symbol was added in version 9.0 (June 2016).

The best we can do, other than adding a drawable resource for it, is not show it or replace it with text for Android 5&6.

**Comment by mcarare** [comment]
cc @brampitoyo

**Comment by brampitoyo** [comment]
I am happy not to show the Gecko. This screen is quite hidden and mostly useful for engineers + technical audience, anyway.

See how the build information is displayed on Firefox Desktop. We should do the same on Focus, too.

<img width="240" alt="Screen Shot 2021-09-07 at 11 38 04 AM" src="https://user-images.githubusercontent.com/51007/132265887-0793f3bb-615b-4527-b70d-6f75692a29d3.png">

**Comment by mcarare** [comment]
For QA: On Android 5 & 6 devices the icon should be replaced by "GV:" text.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main, (build 11 with GV 93.0a1-20210901091701), with Samsung Galaxy Tab A6 (Android 5.1.1).
Not fixed in the 92.1.1 RC build yet.

![gv icon](https://user-images.githubusercontent.com/40694158/132302151-17c7c297-8df4-4a19-83cf-5076d146539f.png)
