### ISSUE TITLE
Wrong text color for Powered by...

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#5325]
## Steps to reproduce
1.Open a custom tab
2.Open the browser menu
### Expected behavior
Powered by... should have the same text color as the rest of menu items
### Actual behavior
Powered by... it has a different text color by the rest of menu items
### Device information

* Android device: Pixel 3 
* Focus version: 93.0.1

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main 93.0 (build 11 GV 93.0a1-20210901091701), with Lenovo Tab M10 (Android 10), Google Pixel (Android 10), and OnePlus 5T (Android 9).
