### ISSUE TITLE
Intermittent UI test failure - < ThreeDotMainMenuTest. browserMenuItemsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5328]
### Stacktrace:
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Report Site Issue…"

View Hierarchy:
+>PopupDecorView{id=-1, visibility=VISIBLE, width=741, height=1032, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(981,77)(wrapxwrap) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged} ty=APPLICATION_PANEL fmt=TRANSPARENT wanim=0x7f130105 surfaceInsets=Rect(45, 45 - 45, 45) (manual)
fl=SPLIT_TOUCH HARDWARE_ACCELERATED FLAG_LAYOUT_ATTACHED_IN_DECOR
pfl=WILL_NOT_REPLACE_ON_RELAUNCH LAYOUT_CHILD_WINDOW_IN_PARENT_FRAME}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+->PopupBackgroundView{id=-1, visibility=VISIBLE, width=741, height=1032, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@51a9001, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+-->CardView{id=2131362142, res-name=mozac_browser_menu_menuView, visibility=VISIBLE, width=741, height=1032, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@5f5cea6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+--->DynamicWidthRecyclerView{id=2131362143, res-name=mozac_browser_menu_recyclerView, visibility=VISIBLE, width=689, height=958, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@903c0e7, tag=null, root-is-layout-requested=false, has-input-connection=false, x=26.0, y=37.0, child-count=11}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=154, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@509b494, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=4}
|
+----->AppCompatImageButton{id=-1, desc=Navigate back, visibility=VISIBLE, width=172, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=false, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@89f2b3d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+----->AppCompatImageButton{id=-1, desc=Navigate forward, visibility=VISIBLE, width=172, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=false, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@9202f32, tag=null, root-is-layout-requested=false, has-input-connection=false, x=172.0, y=0.0}
|
+----->AppCompatImageButton{id=-1, desc=Share…, visibility=VISIBLE, width=172, height=154, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@3c18483, tag=null, root-is-layout-requested=false, has-input-connection=false, x=344.0, y=0.0}
|
+----->AppCompatImageButton{id=-1, desc=Reload website, visibility=VISIBLE, width=173, height=154, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@178600, tag=null, root-is-layout-requested=false, has-input-connection=false, x=516.0, y=0.0}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@8d83e39, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=154.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@c0de5df, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=157.0, child-count=4}
|
+----->AppCompatImageView{id=2131362086, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@76f022c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362361, res-name=text, visibility=VISIBLE, width=439, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@6f584f5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Add to Shortcuts, input-type=0, ime-target=false, has-links=false}
|
+----->View{id=-1, visibility=VISIBLE, width=96, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@f8a728a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=549.0, y=64.0}
|
+----->AppCompatImageView{id=2131362214, res-name=overflowImage, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d9500fb, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@be01518, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=289.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@8a52d56, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=292.0, child-count=4}
|
+----->AppCompatImageView{id=2131362086, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@8a8b1d7, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362361, res-name=text, visibility=VISIBLE, width=351, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@94d6ac4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Find in Page, input-type=0, ime-target=false, has-links=false}
|
+----->View{id=-1, visibility=VISIBLE, width=184, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@4165dad, tag=null, root-is-layout-requested=false, has-input-connection=false, x=461.0, y=64.0}
|
+----->AppCompatImageView{id=2131362214, res-name=overflowImage, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@edec8e2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->SwitchCompat{id=2131362341, res-name=switch_widget, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@6dc9473, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=424.0, text=Desktop site, input-type=0, ime-target=false, has-links=false, is-checked=false}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@5186f30, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=556.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@a24912e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=559.0, child-count=4}
|
+----->AppCompatImageView{id=2131362086, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d6204cf, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362361, res-name=text, visibility=VISIBLE, width=510, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@74d4e5c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Add to Home screen, input-type=0, ime-target=false, has-links=false}
|
+----->View{id=-1, visibility=VISIBLE, width=25, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@f29565, tag=null, root-is-layout-requested=false, has-input-connection=false, x=620.0, y=64.0}
|
+----->AppCompatImageView{id=2131362214, res-name=overflowImage, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@1ec923a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@a8ef448, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=691.0, child-count=4}
|
+----->AppCompatImageView{id=2131362086, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@4fc22e1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362361, res-name=text, visibility=VISIBLE, width=287, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d019806, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Open in…, input-type=0, ime-target=false, has-links=false}
|
+----->View{id=-1, visibility=VISIBLE, width=248, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@a3bec7, tag=null, root-is-layout-requested=false, has-input-connection=false, x=397.0, y=64.0}
|
+----->AppCompatImageView{id=2131362214, res-name=overflowImage, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@ec30cf4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@fb70c1d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=823.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@7938063, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=826.0, child-count=4}
|
+----->AppCompatImageView{id=2131362086, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@a7e0460, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362361, res-name=text, visibility=VISIBLE, width=270, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@f3d4d19, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Settings, input-type=0, ime-target=false, has-links=false}
|
+----->View{id=-1, visibility=VISIBLE, width=265, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@4eda1de, tag=null, root-is-layout-requested=false, has-input-connection=false, x=380.0, y=64.0}
|
+----->AppCompatImageView{id=2131362214, res-name=overflowImage, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@33bfbf, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
at org.mozilla.focus.activity.robots.ThreeDotMainMenuRobot.verifyReportSiteIssueButtonExists(ThreeDotMainMenuRobot.kt:35)
at org.mozilla.focus.activity.ThreeDotMainMenuTest$browserMenuItemsTest$3.invoke(ThreeDotMainMenuTest.kt:63)
at org.mozilla.focus.activity.ThreeDotMainMenuTest$browserMenuItemsTest$3.invoke(ThreeDotMainMenuTest.kt:56)
at org.mozilla.focus.activity.robots.BrowserRobot$Transition.openMainMenu(BrowserRobot.kt:188)
at org.mozilla.focus.activity.ThreeDotMainMenuTest.browserMenuItemsTest(ThreeDotMainMenuTest.kt:56)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by sv-ohorvath** [comment]
Flaky on 10/5: [logs](https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6975546913703465163/executions/bs.2465f5f96aa3cc2d/testcases/1)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for a couple of months
