### ISSUE TITLE
Carousel tips fail to be translated after changing the language without restarting the application

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5331]
## Steps to reproduce
1. Go to Settings -> General -> Language, and change to a different language than the default/the one selected.
2. Exit settings and observe that the carousel tips are not translated.

### Expected behavior
 Focus displays every UI text in the new language, including the carousel tips, immediately after changing the language.

### Actual behavior
The carousel tips remain displayed in the default/previously set language and are only updated after restarting the application. 

### Device information
* Android device: Huawei P9 Lite (Android 8), Huawei P20 (Android 10).
* Focus version: 93.0 (Build 352452037 ; 93.0a1-20210831093704).

https://user-images.githubusercontent.com/89388888/131998676-d132e6d4-76ef-4ab4-8c2d-2aa5ba2ca68c.mp4

**Comment by mcarare** [comment]
For QA: Please test multiple scenarios involving tips, scrolling through all of them, not just the first after locale change. Thank you!

**Comment by delia-pop** [comment]
Verified as fixed on the 93.0 (Build 352522329 93.0a1-20210906031657) with Huawei P9 Lite (Android 10). All tips are translated immediately as per the language changes.
