### ISSUE TITLE
 The tracking protection data panel is cutoff in landscape mode and cannot be scrolled 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5333]
## Steps to reproduce
1. Using the landscape mode, open a page.
2. Tap on the ETP icon displayed in front of the URL.
3. Notice that the tracking protection data panel is cutoff under the "Analytics" text and toggle and the user cannot scroll on the panel.

### Expected behavior
The tracking protection data panel is correctly displayed, all the trackers names/ toggles and the number of trackers blocked on the page are visible when scrolling on the panel.

### Actual behavior
The tracking protection data panel is cutoff, the items under the "Analytics" text and toggle are not visible and the user cannot scroll on the panel.

### Device information
* Android device: Huawei P9 Lite (Android 8), Huawei P20 (Android 10), Google Pixel (Android 10).
* Focus version: 93.0 (Build 352452037 ; 93.0a1-20210831093704).
Please note that this issue is not encountered when using Tablets.

https://user-images.githubusercontent.com/89388888/132010891-328daebb-05ed-428d-bd0f-69ca4badf888.mp4

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug from main from 9/9, using a Google Pixel (Android 10), and OnePlus 5T (Android 9).
