### ISSUE TITLE
The "Open in..." option does not work on Android 11 devices

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5334]
## Steps to reproduce
1. Open a webpage for which you have a corresponding application installed on the device (eg. Amazon, Reddit)
2. Tap the 3 dot menu an select "Open in..."
### Expected behavior
A list of application that can open the link should be displayed.
### Actual behavior
Only the option to download Firefox is available even though Firefox, Amazon and Reddit are also installed on the device.
### Device information

* Android device: Oppo Find X3 Neo (Android 11), OnePlus Nord N10 (Android 11)
* Focus version: 93.0.1 (Build #352452037
![1630675782292](https://user-images.githubusercontent.com/50983519/132014235-e6aea2a2-2e1b-46c0-ba07-0eb4c1cc9f3f.JPEG)

**Comment by mcarare** [comment]
@lobontiumira What version of Firefox do you have installed on the test device? I tried with firefox from the play store and I cannot reproduce this.

**Comment by mcarare** [comment]
As a note, this is not the same feature as Fenix's "open in app" where you can open a link in the corresponding app.
 This is "open in..." and it is expected to open in **another browser** (ora apps that handle links like browsers, for example, Instagram.)

**Comment by mcarare** [comment]
This also looks like this issue: https://github.com/mozilla-mobile/android-components/issues/7827

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest debug build from main 9/7.

### Devices used:
- Oppo Find X3 Neo (Android 11)
- OnePlus Nord N10 (Android 11)
