### ISSUE TITLE
Losing bottom of screen.

### ISSUE THREAD

**Issue by phil99** [mozilla-mobile/focus-android#5339]
In some sites, the bottom approx 5% of the page is not rendered. I cannot scroll down to see the missing part of the page.
The last version that I've tried that renders correctly on my device was 8.17.1
Android 7.1.1

**Comment by cadeyrn** [comment]
What is your Focus version number? Which websites are affected? What is the vendor / model name of your device?

**Comment by phil99** [comment]
Thank you cadeyrn
Version numbers affected that I have tested are versions 91.3.0, 92.1.0 (8.17.1 displays entire page correctly).
One website that causes this is: https://magicseaweed.com/North-Atlantic-Surf-Chart/2/?type=pressure
This is the case with Lenovo Tab8 (Android 7.1), and with Sony Xperia L1 ( Android 7.0)

**Comment by phil99** [comment]
The same issue occurs with Nokia 3.4 running Android 10.
Tested Focus versions 91.3.0 & 91.4.0 build #352421903

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 9/27 (build 11 GV 93.0-20210921185902) with Lenovo Tab M10 (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1), on the provided website.
