### ISSUE TITLE
Link/image/etc context menu

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#534]
Do we want a context menu for things like:
- Long press on a link: copy link / share link?
- Long press on an image: copy image URL / share image URL?

(Note: images can be in a link, in which case we'd probably want both options in one menu.)

We'll need some form of menu to add "save image" in #502.

Currently we just show the share screen when long pressing on a link, see #303.

**Comment by pocmo** [comment]
* Share URL
* Copy URL
* Share Image URL
* Copy Image URL
* (Save Image #502)

**Comment by ahunt** [comment]
I'm guessing this will want some UX ❤️ :
![v1](https://cloud.githubusercontent.com/assets/1546915/25689037/ed87f9bc-3038-11e7-92f6-436135cf4b0e.png)

**Comment by antlam** [comment]
@ahunt can we make the padding below the link (in the title) the same as the padding above it?

(looking at the space between "market" and the top of the context menu, and the space between "&referrer" and the bottom of the light grey box)

**Comment by ahunt** [comment]
![v2](https://cloud.githubusercontent.com/assets/1546915/25720305/4583395a-30c1-11e7-9a5f-f5a04e6e8fa8.png)
