### ISSUE TITLE
The video is paused after switching from portrait to landscape

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#5343]
## Steps to reproduce
1. Open Youtube and play a video.
2. Switch the device orientation from portrait to landscape.

### Expected behavior
The video is still playing.

### Actual behavior
The video is paused.

### Device information
* Android device: Lenovo Tab M10 (Android 10), Huawei MediaPad M2 (Android 5.1.1).
* Focus version: 93.0.1, 92.1.1.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug from main from 9/9 using a OnePlus 5T (Android 9), Google Pixel (Android 10), and Lenovo Tab M10 (Android 10).

**Comment by delia-pop** [comment]
Verified as fixed as well on the 93.0.3 build with Huawei P9 Lite (Android 8).
