### ISSUE TITLE
[custom tabs] The "Report site issue" option isn't available when opening link from custom tabs

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5345]
## Steps to reproduce
1. Make Focus 93.0.1 your default browser.
2. From Gmail, open a link in custom tab.
3. From the three-dot menu of the custom tab, select to open the link in Focus.
4. In Focus, from the three-dot menu, select the "Report site issue" option.

### Expected behavior
The "Report site issue" option is available.

### Actual behavior
The "Report site issue" option isn't available. 
Workaround: Opening the same link in a new tab, displays the "Report site issue" option back in the page's menu.

### Device information
* Android device: all
* Focus version: 93.0.1 pre-release (build 352452037 GV 93.0a1-20210831093704)
* Not reproducible on RC 92.1.1

**Comment by amedyne** [comment]
@brampitoyo Thoughts on this one?

**Comment by mcarare** [comment]
This also happens in Fenix, and it's due to the way we build the menu, report site issue being an extension that is moved from the extension menu for increased visibility.

**Comment by brampitoyo** [comment]
@amedyne @mcarare I must admit: I never accounted for this corner case!

@mcarare you wrote that “Report site issue” was moved from this menu for increased visibility. I’m also unfamiliar with this behavious. Is there another place in the app where this action is being moved to?

Ideally, we’d have “Report site issue” in our main application menu, no matter the link origin (whether it’s from in-app browser, or opened directly in Focus). And Fenix should also follow this behaviour.

**Comment by mcarare** [comment]
@brampitoyo The report site menu item is actually an extension. By default, it is automatically placed in the add-ons menu. Following this: https://github.com/mozilla-mobile/fenix/issues/11631 we have implemented a workaround in AC to move it to the main menu. The same is used in Focus.

**Comment by jonalmeida** [comment]
I had filed this issue and dropped the ball on it. Will work on it next: https://github.com/mozilla-mobile/android-components/issues/10791

**Comment by lobontiumira** [comment]
Reproducible on 93.0.2 build (352522329 GV 93.0a1-20210906031657) with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on RC 93.1.0 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 97.0.0-beta.1 with Oppo Find X3 Lite (Android 11).

**Comment by lobontiumira** [comment]
Reproducible on RC 97.2.0 with Lenovo Tab M10 (Android 10).

**Comment by jonalmeida** [comment]
I think I'm going to close this as "wontfix" unless product have a strong desire for this.
