### ISSUE TITLE
The list of browsers to open site in is hard to read. 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5351]
Noticed while investigating https://github.com/mozilla-mobile/focus-android/issues/5334.

The `OpenWithFragment` dialog fragment has a weird design and the browser lists are hard to read. 

<img src = https://user-images.githubusercontent.com/48995920/132349087-0375af5e-d667-4253-a718-6eac750fc73c.png width =60%>

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug from main from 9/9 using a OnePlus 5T (Android 9): the first screenshot is from the app, the second is from the custom tab.

![open in](https://user-images.githubusercontent.com/40694158/132693852-36322a11-578b-4a88-ac89-b89088e5b170.png)
