### ISSUE TITLE
Update landing page background(nightly/production) and launch icons(production)

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#5355]
## Steps to reproduce
Open a release build
### Expected behavior
The app should have different backgrounds for nightly and production
Production launch icons should be updated
 [Figma design](https://www.figma.com/file/jgsM2hWimZbPmtUJn7IGIB/Landing-Page?node-id=1941%3A61457)
### Actual behavior
Wrong [nightly background](https://www.figma.com/file/jgsM2hWimZbPmtUJn7IGIB/Landing-Page?node-id=1941%3A61458) is displayed for nightly and production
### Device information

* Android device: any
* Focus version: 93.0.1

**Comment by lobontiumira** [comment]
Verified on the latest Release, and Nightly builds from main from 9/15, with OnePlus 5T (Android 10). The first row of screenshots is from Release, the second is from Nightly:

![release vs nightly](https://user-images.githubusercontent.com/40694158/133408863-3b2217ec-1476-40fc-bc79-665d29d0ec4e.png)

![icons](https://user-images.githubusercontent.com/40694158/133408925-b9b7e859-cc66-43a8-b318-022dec6aadcc.jpg)
