### ISSUE TITLE
Migrate HomeMenu to use BrowserMenuItem

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5357]
It seems this menu has not been migrated yet.

**Comment by lobontiumira** [comment]
Verified the three-dot menu from the homescreen is dynamic, depending on the language selected.
Tested with Google Pixel (Android 10), Lenovo Tab M10 (Android 10), OnePlus 5T (Android 10), and Samsung Galaxy Note 8 (Android 9), on the latest debug build from main from 9/21 (build 11 with GV 93.0a1-20210906031657).

![three-dot menu](https://user-images.githubusercontent.com/40694158/134181676-2b39b1db-5e73-42fe-9206-88a183240f07.png)
