### ISSUE TITLE
[bug] Rotating the device from portrait to landscape, or viceversa opens new tabs

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5361]
## Steps to reproduce
1. Load a page.
2. In the same tab, type a different URL.
3. Rotate the device from portrait to landscape, or viceversa. Observe.
4. Clear history.
5. Rotate again the device from portrait to landscape, or viceversa. Observe

### Expected behavior
After step 3, the page loaded at step 2 is displayed without issues.
After step 5, the homescreen is still displayed.

### Actual behavior
After step 3, the page from step 1 is loading in a new tab, so now the app has 3 opened tabs.
After step 5, the first loaded page (from step 1) is loading in a new tab.
Please see the short video below, and the attached logcat.

### Device information
* Android device: Lenovo Tab M10 (Android 10), OnePlus 5T (Android 9)
* Focus version: 91.4.0, 92.1.1
* Not reproducible on the latest debug build from main from 9/9 (GV 93.0a1-20210901091701)

https://user-images.githubusercontent.com/40694158/132684575-9ef416bf-4df0-4aee-b81b-45412e64c33d.mp4

[logcat.txt](https://github.com/mozilla-mobile/focus-android/files/7136440/logcat.txt)

**Comment by mcarare** [comment]
This is fixed on main by https://github.com/mozilla-mobile/focus-android/commit/9496e1e5113f28991629baa163315245dbfcc0e0.
