### ISSUE TITLE
Add support for HTTPS-Only Mode

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/focus-android#5365]
## User Story
- As a user, I want  be able to opt in to use the [HTTPS-Only Mode](https://blog.mozilla.org/security/2020/11/17/firefox-83-introduces-https-only-mode/) 

## Dependencies
- GeckoView [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1697866).

### Acceptance Criteria
- When I navigate to any site, the HTTPS version should be always served

**Comment by Amejia481** [comment]
👋🏽  @brampitoyo 
From UX we will need mockups for the error page I'm not sure if we to use the same page as desktop?

![image](https://user-images.githubusercontent.com/773158/132762740-2f1c3d40-26c4-4382-bf92-a822adfb9677.png)

**Comment by brampitoyo** [comment]
@Amejia481 It seems as if the desktop error page was already designed to be responsive:

<img width="360" src="https://user-images.githubusercontent.com/51007/133191453-f0ae163b-d1c3-4713-8255-19c70ec122fc.png">

Let’s try using it on mobile. I think it should work OK.

**Comment by Amejia481** [comment]
> @Amejia481 It seems as if the desktop error page was already designed to be responsive:
> 
> <img alt="" width="360" src="https://user-images.githubusercontent.com/51007/133191453-f0ae163b-d1c3-4713-8255-19c70ec122fc.png">
> 
> Let’s try using it on mobile. I think it should work OK.

Perfect!

**Comment by agi** [comment]
FYI the GeckoView bug landed so this is ready to be implemented!

**Comment by Amejia481** [comment]
Engineering tasks 

- [ ] https://github.com/mozilla-mobile/focus-android/issues/5935
- [ ] https://github.com/mozilla-mobile/android-components/issues/11305
- [ ] https://github.com/mozilla-mobile/android-components/issues/11306
