### ISSUE TITLE
Carousel tips are improperly displayed in landscape mode when the keyboard is invoked/dismissed

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5366]
## Steps to reproduce
1. Launch FF and rotate the device from portrait to landscape mode.
2. Observe the minimized tip while the keyboard is invoked.
3. Dismiss the keyboard and observe the carousel tips.

### Expected behavior
The carousel tips should be completely visible when the keyboard is invoked/dismissed in landscape mode.

### Actual behavior
Carousel tips are improperly displayed as cutoff in landscape mode when the keyboard is invoked/dismissed.

The issue occurs whenever the user returns to homescreen and the keyboard is invoked automatically.

### Device information

* Android device: Huawei P9 Lite (Android 8); Huawei P20 (Android 10).
* Focus version:  93.0.2 (Build 352522329 93.0a1-20210906031657).

Please note that the issue could not be reproduced on other devices.

https://user-images.githubusercontent.com/89388888/132832235-7b3184e1-e41d-4c41-8850-438a994ba189.mp4

https://user-images.githubusercontent.com/89388888/132832243-cae3f5a6-a448-4629-9c93-4fe5975f306c.mp4

**Comment by ionutbedregeanu** [comment]
@amedyne @brampitoyo I tried to fix this but most of the times, for landscape, we don't have enough space between keyboard and  toolbar to show cleanly tips, logo and shortcuts

<image src="https://user-images.githubusercontent.com/11731652/133088833-d0050ad9-3759-4f97-b521-0d1c35977d69.png" width="40%"/>

Even on portrait it happens sometimes 

<image src="https://user-images.githubusercontent.com/11731652/133089649-0b324022-e1f2-4d93-8647-9171891f1058.png" width="40%"/>

So maybe we should avoid resizing everything above the keyboard and just like on Fenix allow for the keyboard to be shown on top of anything that may be on screen at the time

What do you think?

**Comment by brampitoyo** [comment]
@ionutbedregeanu Wow. Thanks for posting those screenshots. I didn’t expect the keyboard to take up so much vertical space on landscape mode!

Have a look on this Figma, on the right-side of the page under `Specs`: https://www.figma.com/file/KggJlo8pg2T2Q8nn0Ec5c3/Shortcuts?node-id=1836%3A46849

You’ll see that I’ve hidden the logo on some landscape layout devices.

And in case this is still not enough space when the keyboard is up, I’d be OK with hiding the Shortcut tiles too.

So, the only way to show Shortcut tiles will be to minimise the keyboard (using the ▼ soft key).

Does this help you come up with a solution?

Let me know if there are more layout edge cases, and we’ll work together to resolve them!

**Comment by ionutbedregeanu** [comment]
If I understand correctly tips section should be always visible when the keyboard is displayed and we should hide the logo and shortcuts if tips overlaps them. Am I right?
This implies a pretty complex custom behaviour, fact which makes me suggest again to follow Fenix approach, were the keyboard opens over anything that it's on screen at that time
@jonalmeida What is your opinion?

**Comment by jonalmeida** [comment]
> This implies a pretty complex custom behaviour, fact which makes me suggest again to follow Fenix approach, were the keyboard opens over anything that it's on screen at that time

I'd recommend this solution too. It should let you peek at your shortcuts at the top if you decided to use them instead of typing.

**Comment by ionutbedregeanu** [comment]
> that

@brampitoyo Can you confirm if  you are ok with this?

**Comment by ionutbedregeanu** [comment]
> If I understand correctly tips section should be always visible when the keyboard is displayed and we should hide the logo and shortcuts if tips overlaps them. Am I right?
> This implies a pretty complex custom behaviour, fact which makes me suggest again to follow Fenix approach, were the keyboard opens over anything that it's on screen at that time
> @jonalmeida What is your opinion?

 @brampitoyo Could you please confirm that you are ok with this?

**Comment by brampitoyo** [comment]
@ionutbedregeanu Yes. I confirm that the behaviour that @jonalmeida suggests sounds ok. It will also align us with Fenix.

**Comment by delia-pop** [comment]
Verified as fixed on the latest debug build from main 09/21 with Huawei P9 Lite (Android 8). 
When the keyboard is invoked, it overlaps any asset on the screen and the carousel tips are no longer displayed.
When the keyboard is dismissed, the tips are correctly displayed at the bottom of the screen.
