### ISSUE TITLE
Incorrect linked text for carousel tip in Czech language

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5373]
## Steps to reproduce
1. Go to Settings -> General -> Language, and change the language to Czech.
2. Exit settings and observe that the 3rd carousel tip.

### Expected behavior
Only the "Add it to the Allowlist in Settings(translated)" string is linked text.

### Actual behavior
The entire tip appears as linked text.

### Device information

* Android device: Huawei P9 Lite (Android 8), Huawei P20 (Android 10).
* Focus version: 93.0.2 (Build #352522329 93.0a1-20210906031657).

![Incorrect linked text for carousel tip in Czech language_Landscape](https://user-images.githubusercontent.com/89388888/133053441-ea438823-3664-4d68-b5f3-31faedc131cc.jpg)
![Incorrect linked text for carousel tip in Czech language_Portrait](https://user-images.githubusercontent.com/89388888/133058565-cefb5daf-eb6c-4ef2-b762-ebb7d8703b67.jpg)

**Comment by ionutbedregeanu** [comment]
@Delphine can you please update this string also with a "\n" before "Přidejte" ?

**Comment by Delphine** [comment]
Done, thanks for flagging!

**Comment by mcarare** [comment]
The string was updated in https://github.com/mozilla-mobile/focus-android/pull/5379/files.

**Comment by delia-pop** [comment]
Verified as fixed on the latest Focus build from main 09/15 with Huawei P9 Lite (Android 8).
