### ISSUE TITLE
Tab icon is displayed briefly when sharing tabs from other apps

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#5374]
## Steps to reproduce
1. Open 2-3 pages in Focus.
2. Open Firefox and share a page to Focus.

### Expected behavior
The page is displayed without issues/visual effects/ other menu or options.

### Actual behavior
The tab icon is displayed briefly for 1-2 seconds. 

### Device information
* Android device: Huawei MediaPad M2 (Android 5.1.1).
* Focus version: 93.0.2.

**Comment by channingcarter** [comment]
Not something we need to fix for MVP

**Comment by ionutbedregeanu** [comment]
Can't be reproduced anymore after https://github.com/mozilla-mobile/focus-android/issues/5829
