### ISSUE TITLE
Custom keyboard is displayed for a split second 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5375]
## Steps to reproduce
1. Launch the application.
2. Observe the keyboard. 

### Expected behavior
The default incognito keyboard is invoked when the application is launched. 

### Actual behavior
The custom keyboard is displayed for a split second before the incognito keyboard loads.

### Device information
* Android device: Huawei P9 Lite (Android 8), Huawei P20 (Android 10), Lenovo Tab M10 (Android 10).
* Focus version: 93.0.2 (Build #352522329 93.0a1-20210906031657), RC build 92.1.1.

https://user-images.githubusercontent.com/89388888/133093441-c38f45c9-c9dd-49dd-9ab7-bf477c3cbfff.mp4

**Comment by mcarare** [comment]
I cannot reproduce this on a Huawei P10 with a SwiftKey keyboard, but I can try a speculative fix. It might be a problem with the keyboard, not in our code, but we could try to help determine the incognito mode earlier.

**Comment by channingcarter** [comment]
This is low priority to fix for the MVP release. If we have time to fix we should.

**Comment by mcarare** [comment]
I see this also happens in Fenix private mode with SwiftKey keyboard.
