### ISSUE TITLE
Reddit choose browser panel cannot be scrolled into view

### ISSUE THREAD

**Issue by chutten** [mozilla-mobile/focus-android#5377]
**Describe the bug**

When you load reddit.com in Focus you must tell it you really want to open it in the browser, not in an app, via a panel at the bottom of the screen. I cannot scroll that panel into view.

**To Reproduce**

1. Go to reddit.com
2. Attempt to scroll up so I can more easily select See Reddit in... Firefox

**Expected behavior**

The screen to scroll as I asked

**Actual behavior**

No scrolling

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A5
 - OS: Android 8
 - Focus Version: Foxfooding APK

**Additional context**
Might have been happening in stock Focus as well

**Comment by jonalmeida** [comment]
There are a couple of duplicates of this bug. Petru gave us some hints on what we can do next to fix this: https://github.com/mozilla-mobile/focus-android/issues/5173#issuecomment-901835330

**Comment by chutten** [comment]
Looks like it's being handled. Thanks!
