### ISSUE TITLE
9gag.com's banner to "Open in..." is not displayed entirely; the page is unusable

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5380]
## Steps to reproduce
1. Open 9gag.com.
2. From the "Open 9GAG in..." banner, select the "Continue" option, to continue visiting the site in Focus.

### Expected behavior
The "Continue" option is displayed, the user can continue visiting the page, without issues.

### Actual behavior
The banner is not displayed fully, the "Continue" option is not displayed at all. The user cannot visit the page, scroll through it.
Disabling the ETP doesn't fix the issue.

### Device information
* Android device: Huawei MiPad M2 (Android 5.1.1), Lenovo Tab M10 (Android 10), and OnePlus 5T (Android 9)
* No reproducible on Samsung Galaxy Note 8 (Android 9)
* Focus version: the latest debug build from main from 9/14, RC 92.1.1, pre-release build 93.0.2

https://user-images.githubusercontent.com/40694158/133206372-41782e1d-b06d-4597-a7ab-4ae2f7bf9fcd.mp4

**Comment by channingcarter** [comment]
Not required to fix for MVP

**Comment by lobontiumira** [comment]
Reproducible on 93.0.3 build as well, with Lenovo Tab M10 (Android 10), and OnePlus 5T (Android 10).

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main from 9/27 (build 11 GV 93.0-20210921185902) with Lenovo Tab M10 (Android 10), and OnePlus 5T (Android 10), and the banner is visible, but the "Continue" option is covered by the trashcan, so the user can accidentally tap on the trashcan, instead of the desired option:

![9gag](https://user-images.githubusercontent.com/40694158/134906217-8e6bd147-1895-458a-90cc-b6221e23fcb5.png)

*Note: should we have the Firefox logo, instead of the Chrome one?

@mcarare please review, thank you!

**Comment by mcarare** [comment]
@lobontiumira The icon is shown by the website, and it is the same for any browser. There is not much we can do, the website has to change the icon it displays (my best guess is they do not check the user agent).

The issue with the trashcan is not necessarily related to the initial issue here, it pertains to a bigger issue that has to be evaluated by UX, as using the FAB is expected to overlap web page content.

**Comment by lobontiumira** [comment]
Thanks, Mihai!
I'll mark this issue as verified, and close it, based on your feedback.
