### ISSUE TITLE
Cutoff options in the yahoo.com consent page 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5381]
## Steps to reproduce
1. Access yahoo.com. 
2. Observe the consent page.

### Expected behavior
The "Accept all" and "Manage Settings" options should be properly displayed in Portrait and Landscape mode.

### Actual behavior
In Portrait mode, de "Manage Settings" option is barely visible.
In Landscape mode, both "Accept all" and "Manage Settings" options appear cutoff.

### Device information
* Android device: Huawei P9 Lite (Android 8), Huawei P20 (Android 10),  OnePus 5T (Android 10).
* Focus version:  93.0.2 (Build #352522329 93.0a1-20210906031657) and RC 92.1.1.

The issue could not be reproduced on Tablets. 

https://user-images.githubusercontent.com/89388888/133219564-9792ec43-1441-49e2-aaa6-03758b55bb18.mp4

**Comment by channingcarter** [comment]
We should fix for MVP

**Comment by delia-pop** [comment]
The issue is partially fixed on the latest debug build from main 09/22 with Huawei P9 Lite (Android 8) and Huawei P20 (Android 10).
Both options are now visible on Portrait mode, however, in Landscape mode, the "Accept all" and "Manage Settings" options are not displayed anymore. 

@mcarare please see the attached file.

https://user-images.githubusercontent.com/89388888/134295463-6a8fc69e-7445-44aa-8293-12b2c761c481.mp4

**Comment by mcarare** [comment]
@delia-pop Please open a separate issue for the landscape issue. Note that this also happens in Fenix.

**Comment by delia-pop** [comment]
A separate issues was opened: https://github.com/mozilla-mobile/focus-android/issues/5477.
