### ISSUE TITLE
Dismissing the keyboard clears the address bar

### ISSUE THREAD

**Issue by Vinnl** [mozilla-mobile/focus-android#5382]
**Describe the bug**

If I type in the address bar, then dismiss the keyboard (e.g. to be able to see more search suggestions), everything I typed into the address bar is removed.

**To Reproduce**

1. Type something in the address bar.
2. Press the Android down button.
3. (Optional) Press outside the search suggestions.

**Expected behavior**

I can press in the address bar again to complete the URL I was typing.

**Actual behavior**

I have to retype the full URL and make sure not to dismiss the keyboard.

**Smartphone (please complete the following information):**

- Device: Fairphone 2
 - OS: Android 9
 - Focus Version: the one built for the Sep 13- Sep 17, 2021 Foxfooding

**Comment by mcarare** [comment]
@brampitoyo What should be the behavior here? In Fenix, I think we also hide the search suggestions when we dismiss the keyboard.
Note that more search suggestions can be viewed by scrolling the suggestions list, not by dismissing the keyboard.

**Comment by Vinnl** [comment]
@mcarare 

>  Note that more search suggestions can be viewed by scrolling the suggestions list, not by dismissing the keyboard.

Maybe that's where I went wrong: if I scroll through the suggestions in Fenix, the keyboard is dismissed so that I can see more suggestions at the same time (without clearing the address bar). In Focus, the keyboard remains open, obscuring the view of a couple of search suggestions.

**Comment by mcarare** [comment]
@Vinnl You are right, that behavior was implemented in Fenix, but I know there were some UX discussions around it, so I think @brampitoyo can add more insight to what we should try to do in order to provide the best experience for the users.

**Comment by brampitoyo** [comment]
@mcarare @Vinnl I think the right behaviour here should be:

- If you scroll through search suggestions, the keyboard will be dismissed but your search query remains
- If, on the other hand, you dismiss the keyboard by pressing the down arrow or swiping, we count it as a “Back” action. In this case, the keyboard will be dismissed _and_ the address bar will be un-selected. Since the address bar is no longer active, your search query will reset as well

**Comment by Vinnl** [comment]
@brampitoyo For that second bullet, one thing that also confused me was that search suggestions remained visible, even though the query they were based on was removed. Possibly they should be cleared as well?

**Comment by mcarare** [comment]
Yes, in Fenix the suggestions are cleared when the keyboard is closed and the search field cleared. We should do the same here.

**Comment by brampitoyo** [comment]
@Vinnl I agree with @mcarare here. When you exit the search screen, this should both close the keyboard _and_ clear the address bar keyword.

Note that _exiting_ search is different from _scrolling down_ the search screen. In the latter case, the keyboard is closed, but the address bar keyword is not cleared.

**Comment by Vinnl** [comment]
Yeah that sounds good. Though note:

> Note that exiting search is different from scrolling down the search screen. In the latter case, the keyboard is closed, but the address bar keyword is not cleared.

When I scroll down the search screen, the keyboard is _not_ closed. (Whereas in regular Fenix it is.)

**Comment by mcarare** [comment]
This can be tested by QA:

1. When pressing back with the suggestion list showing (including the keyboard) the keyboard should hide, the suggestion list should disappear and the text typed in the toolbar should be cleared.
2.  On scrolling through the suggestion list the keyboard should hide.

This is also the current behavior in Fenix.

**Comment by delia-pop** [comment]
Verified as fixed on the latest Focus build from main 09/17 (build 11 - GV 93.0a1-20210906031657) with Huawei P9 Lite (Android 8). 
The behavior described in the comment above applies: 
1. when tapping "back" while the suggestions are displayed, the keyboard is dismissed and the toolbar is cleared;
2. when scrolling through the suggestions, the keyboard is dismissed and the toolbar keeps its content.

**Comment by mcarare** [comment]
Closing as per above comment.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Focus 93.0.3.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
