### ISSUE TITLE
Toggling a single type of tracker/script doesn't reload the page

### ISSUE THREAD

**Issue by Vinnl** [mozilla-mobile/focus-android#5383]
**Describe the bug**

Supposedly, tapping the shield symbol in the top-left corner and then disabling either Advertising, Analytics or Social trackers/scripts should reload the page. This does not happen.

**To Reproduce**

1. Go to an arbitrary website.
2. Tap the shield icon in the top left-hand corner.
3. Turn off one of the toggles next to Advertising, Analytics or Social.

**Expected behavior**

The Site Info panel disappears, and the page reloads, with the untoggled type of tracker/script no longer blocked.

**Actual behavior**

The Site Info panel stays active, and nothing happens other than the toggle now being off.

**Smartphone (please complete the following information):**

 - Device: Fairphone 2
 - OS: Android 9
 - Focus Version: the one built for the Sep 13- Sep 17, 2021 Foxfooding

**Comment by mcarare** [comment]
@brampitoyo & @channingcarter for a decision here.

The initial design does not specify reloading the page for tracker state change, only for ETP change. This is also consistent with the behaviour of changing a tracker state from settings (the opened page does not reload). Do we want to change this? 

IMO the behaviour should be consistent, so if we decide to reload the page when changing trackers from the panel we should also try to reload it when changing trackers from settings.

**Comment by brampitoyo** [comment]
@mcarare I agree with @Vinnl here (good catch – thank you!), that toggling individual trackers on and off should reload the page. And the panel should close, too.

This will allow people to instantly see the change they’re making, and whether it will fix any issue with the site.

**Comment by mcarare** [comment]
I think closing the panel each time would make it frustrating for people that want to turn on or off multiple tracker categories.

**Comment by brampitoyo** [comment]
@channingcarter @mcarare Sounds good. I have also checked iOS’ behaviour, and they’re also keeping the panel open. Let’s keep it open here, too.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 9/16 (build 11 - GV 93.0a1-20210906031657) with Samsung Galaxy Note 8 (Android 9), and OnePlus 5T (Android 10).
After disabling one of the trackers toggle, the page reloads, and the panel is still displayed, so the user can enable/disable other options.

**Comment by lobontiumira** [comment]
Verified as fixed also on 93.0.3 build with Lenovo Tab M10 (Android 10).
