### ISSUE TITLE
Shortcuts opened from the address bar open a new tab

### ISSUE THREAD

**Issue by Vinnl** [mozilla-mobile/focus-android#5384]
**Describe the bug**

Shortcuts opened from the address bar open in a new tab.

**To Reproduce**

1. Add a shortcut.
2. Visit a website.
3. Tap the address bar.
4. Tap the shortcut.

**Expected behavior**

The current page is replaced by the shortcut target.

**Actual behavior**

A new tab opens with the shortcut target, keeping the existing page open in the background.

**Smartphone (please complete the following information):**

 - Device: Fairphone 2
 - OS: Android 9
 - Focus Version: the one built for the Sep 13- Sep 17, 2021 Foxfooding

**Additional context**

I'm not sure if this is desired behaviour, but the foxfooding screencast seemed to not open a new tab, hence the report.

**Comment by mcarare** [comment]
@brampitoyo, @gabrielluong I am not aware of the design for the awesomebar shortcuts. Should they open in the current tab or a new tab? It would make sense to me to open in the same tab, as opposed to the shortcuts from the home screen that opens in a new tab.

**Comment by brampitoyo** [comment]
@mcarare All shortcuts should open in the current tab, including ones that appear underneath the selected address bar while you’re visiting a website

This means that shortcuts that appear on the New Tab Page should open in the current tab, too. This is true when I checked the dev build, but just checking if this is still true today?

**Comment by mcarare** [comment]
I think there is the same misunderstanding as it is for Fenix. The home tab is not a browser tab, but a screen. The shortcuts from the home screen open in a new tab, as there is none when you just open the app.

**Comment by brampitoyo** [comment]
@mcarare I see! Sorry, I didn’t know that the Homescreen (or New Tab Page) exists in a “tab zero” state.

Then yes. You are correct. Shortcuts should be opened in a new tab.

**Comment by mcarare** [comment]
@brampitoyo even when opened from an existing tab? ( now shortcuts show up even when you click on the URL in an existing tab) This is the case reported here, clicking on those shortcuts opens a new tab when we could assume the intention of the user would be to not keep the first tab but open the shortcut URL instead of the first URL.

**Comment by Vinnl** [comment]
This behaviour still exists in current nightly, and I think the last question asked is still relevant?

**Comment by ionutbedregeanu** [comment]
> @brampitoyo even when opened from an existing tab? ( now shortcuts show up even when you click on the URL in an existing tab) This is the case reported here, clicking on those shortcuts opens a new tab when we could assume the intention of the user would be to not keep the first tab but open the shortcut URL instead of the first URL.

@jeffreygee Any thoughts about this?

**Comment by jeffreygee** [comment]
@ionutbedregeanu - I agree with the above.

All shortcuts should open in the current tab, including ones that appear underneath the selected address bar while you’re visiting a website, so basically:
- If the user clicks on a shortcut while on a website, clicking on the shortcut should replace the current website and not open a new tab. 
- If the user is on the homepage view (tab zero), then open in a new tab. 

We can chat in the meeting tomorrow AM if you have any questions. Thanks!

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 106.0a1 from 9/8 that tapping on the shortcut opens it on the same tab, does not open a new one.
Tested with the following devices:
* Samsung Galaxy Note 8 (Android 9),
* Samsung Galaxy Tab A6 (Android 5.1.1),
* Sony Xperia Z5 Premium (Android 7.1.1), and
* Lenovo tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Not yet fixed on RC 105.1.0 build 2.
