### ISSUE TITLE
[v93][L10N] Truncated context menu when long tapping a linked image

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5387]
## Steps to reproduce
1. Set the device language to Spanish/Spanish Mexican/Italian.
2. Open an article from Wikipedia.
3. Long click on a linked image.
4. Observe the context menu.

### Expected behavior
The context menu is correctly displayed both in Portrait and Landscape mode.

### Actual behavior
In Portrait mode, the last paragraph appears truncated excluding the "Firefox Focus" text.
In Landscape mode, the last paragraph is not displayed at all.

### Device information
* Android device: Huawei P9 Lite (Android 8), Huawei P20 (Android 10).
* Focus version: 93.0.2 (Build #352522329 93.0a1-20210906031657).

Note that on Huawei P20 (Android 10) only the behavior described for the Landscape mode applies.

![Truncated context menu when long tapping a linked image_Portrait](https://user-images.githubusercontent.com/89388888/133252401-24bb28d2-a8fc-4c27-ad49-dce9de6f674c.jpg)
![Truncated context menu when long tapping a linked image_Landscape](https://user-images.githubusercontent.com/89388888/133252409-89d51ee4-0f80-4e9c-a457-bf968c3889c7.jpg)

**Comment by mcarare** [comment]
I cannot reproduce the first issue (truncating in portrait) for Spanish or Italian.

**Comment by Delphine** [comment]
Confirming that I can not reproduce the truncating in portrait either.
However, I've noticed this happens in all locales - even source locale en-US
(so this isn't an l10n specific bug)

**Comment by mcarare** [comment]
cc @ionutbedregeanu for the landscape issue.

**Comment by delia-pop** [comment]
The issue is still reproducible on the 93.0.3 build (352601845 - GV 93.0a1-20210906031657) and debug build 09/20 from Main with Huawei P9 Lite (Android 8) and Huawei P20 (Android 10).

**Comment by delia-pop** [comment]
Verified as fixed on the Debug build from Main 09/24 with Huawei P9 Lite (Android 8).
