### ISSUE TITLE
[L10N] "Report site issue" option from the three-dot menu is not translated

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5388]
## Steps to reproduce
1. Change your device language to Dutch, Japanese, Korean, or any other language.
2. Open Focus, open a page, and tap on the three-dot menu.
3. Observe the page's menu.

### Expected behavior
All the options are translated.

### Actual behavior
The "Report site issue" option is not translated in Nederlands, Japanese, Korean, Spanish, Spanish-Mexico, Croatian.
Because this option is not translated, the options from the page's menu are missaligned.

### Device information
* Android device: all
* Focus version: 93.0.2

![japanese report site issue](https://user-images.githubusercontent.com/40694158/133258134-6242ff9d-73d9-4096-8a1f-e67d6330fdaa.jpg)

![missaligned Nederlands](https://user-images.githubusercontent.com/40694158/133259686-435bb2ee-4a7b-4bb7-94a2-01a26feb262a.jpg)

**Comment by mcarare** [comment]
Report site issue is not translated in Fenix either, because it is a web extension.

**Comment by Delphine** [comment]
Agreed, I think we can close this ([Fenix similar issue](https://github.com/mozilla-mobile/fenix/issues/12886#issuecomment-663411672) for reference)

**Comment by Delphine** [comment]
I don't see that these have ever been localized. I think we can close this (I can't close the issue myself) - unless anyone has any other thoughts

**Comment by mcarare** [comment]
Closing as per comment above.
