### ISSUE TITLE
[L10N] The Privacy Notice page is not translated.

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5389]
## Steps to reproduce
1. Change your device language to French, Spanish, Chinese, or any other language;
2. Go to Settings->Mozilla->Privacy Notice;
### Expected behavior
The Privacy Notice page should be translated in the language of the device.
### Actual behavior
The Privacy Notice page is displayed in English.
### Device information

* Android device: all
* Focus version: 93.0.2

**Comment by mcarare** [comment]
@ fabiLpz is the link for the focus privacy notice still good? (https://www.mozilla.org/privacy/firefox-focus/ )
I do not see any localized versions for it.

**Comment by fabiLpz** [comment]
I'm not sure I can help with this, since it's not a SUMO page. But @flod, on Slack, may be able to help.

**Comment by delia-pop** [comment]
This is reproducible on Beta 96.0.0-beta.1 with LG G7 fit (Android 8.1.0) with Hungarian language.

**Comment by Delphine** [comment]
From my firefox desktop, I get redirected to this page: https://www.mozilla.org/fr/privacy/firefox-focus/
I also see it translated in italian, for example: https://www.mozilla.org/it/privacy/firefox-focus/
Seems like there is an issue with the redirect perhaps?

**Comment by kelimuttu** [comment]
The privacy notice is hosted on mozilla.org, so this is not part of SUMO.

**Comment by lobontiumira** [comment]
Reproducible on RC 97.1.0 with Punjabi (Indian) with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 98.0.0-beta.2 with Samsung Galaxy Note 8 (Android 9) with the following languages:
* Swedish
* Occitan
*
