### ISSUE TITLE
When opened from an intent, Focus re-opens original intent when selected from recents

### ISSUE THREAD

**Issue by mbrubeck** [mozilla-mobile/focus-android#539]
This describes a case where Focus appears (at least from the user's point of view) to remember browsing history even after it was explicitly cleared.

Steps to reproduce (tested with Focus for Android beta build 1136, Moto X 2nd Gen, Android 6.0):

1. Make Focus the default browser.

2. Make sure Focus is not running (force kill it, or swipe to close it in the recent apps switcher).

3. Open Focus by clicking a link in another app.

4. Press the trash can icon or back button to close the page and erase browsing history.  (Focus now shows its welcome screen.)

5. *Important:* Press the back button to exit Focus.

6. Open the Recents (app switcher) screen and select Focus.

Expected behavior: Focus still shows its welcome screen.

Actual behavior: Focus re-opens the link from step 3.

cc #105

**Comment by mbrubeck** [comment]
Note: If you open and close any number of links in Focus before continuing to steps 5 and 6, they will still make Focus re-open whatever link was in the *original* intent that it launched with in step 3.

**Comment by pocmo** [comment]
Thank you for this very detailed bug report!

Are you using the beta builds from buddybuild? There are a couple of bug fixes we haven't deployed to our beta group yet.

**Comment by pocmo** [comment]
I can reproduce this with the state on `master`.

**Comment by mbrubeck** [comment]
Yes, I'm using a beta build from buddybuild.
