### ISSUE TITLE
[L10N] The "What's New in Firefox Focus.." page is partially translated

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5391]
## Steps to reproduce
1. Change your device language to any language.
2. Go to Settings->Tap on the gift pictogram in the right upper corner.

### Expected behavior
The SUMO page should be fully translated in the language of the device.

### Actual behavior
The SUMO page is partially translated.

### Device information
* Android device: all
* Focus version: 93.0.2 (Build #352522329 93.0a1-20210906031657).

![What's New in Firefox Focus not translated](https://user-images.githubusercontent.com/89388888/133261470-9808cafd-b979-416a-b61d-572c1a94fa67.jpg)

**Comment by mcarare** [comment]
@fabiLpz do we have these pages translated?

**Comment by fabiLpz** [comment]
Yes. Contributors help us localize into other languages. If you want to prioritize a language in particular, we share the article with the contributors two weeks before release.

**Comment by lobontiumira** [comment]
Reproducible in Spanish (Mexico) on RC 95.1.0, where, also, the parenthesis after "Version 93" is missing:

![Screenshot_2](https://user-images.githubusercontent.com/40694158/144858697-aba4a3f3-352e-495b-819d-c8d502e4b2cf.jpg)

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on Beta 96.0.0-beta.1 with Chinese Simplified language set as default:
![aaa](https://user-images.githubusercontent.com/40694158/145586233-e0e9df13-6256-45fc-bd28-551e7e718206.jpg)

**Comment by lobontiumira** [comment]
Reproducible on Beta 96.0.0-beta.1 with Slovenčina language.
