### ISSUE TITLE
[L10N] The "Remote debugging via USB/Wi-Fi" option is not translated in Dutch

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5392]
## Steps to reproduce
1. Change your device language to Dutch.
2. Open Focus, and go to Settings - Advanced.
3. Observe if the page is translated.

### Expected behavior
The "Remote debugging via USB/Wi-Fi" option is translated in Dutch.

### Actual behavior
The "Remote debugging via USB/Wi-Fi" option is not translated in Dutch.

### Device information
* Android device: Lenovo Tab M10 (Android 10)
* Focus version: 93.0.2
* 
![nederlands remote debugging](https://user-images.githubusercontent.com/40694158/133261464-001cfc0c-9015-42a1-825a-41ad85c36df7.jpg)

**Comment by mcarare** [comment]
This is strictly a translation issue, not a coding one.
cc @Delphine The string `preference_remote_debugging`: https://pontoon.mozilla.org/nl/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?search=preference_remote_debugging&string=223926.

**Comment by Delphine** [comment]
Some Dutch strings remain in English. Since this is more of a developer option, the localizer has decided to keep this string in English.
Closing for now, thanks
