### ISSUE TITLE
[L10N] The Safe Browsing section heading is not translated in Italian

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5394]
## Steps to reproduce
1. Change your device language to Italian.
2. Go to Settings->Privacy & Security.
3. Notice the Safe Browsing section.

### Expected behavior
The Safe Browsing section heading should be translated in Italian language.

### Actual behavior
The Safe Browsing section heading is displayed in English.

### Device information
* Android device: all
* Focus version: 93.0.2 (Build #352522329 93.0a1-20210906031657).

![The Safe Browsing section heading is not translated in Italian](https://user-images.githubusercontent.com/89388888/133264257-e699c50b-478b-4dc8-8374-55ffee7ef17d.jpg)

**Comment by mcarare** [comment]
This is strictly a translation issue, not a coding one.
cc @Delphine The string `preference_category_safe_browsing`: https://pontoon.mozilla.org/it/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?search=preference_category_safe_browsing&string=224067.

**Comment by Delphine** [comment]
Thanks for flagging!
Apparently, this depends if Google translates the term or not. In this case, it seems they don't - so this isn't an issue for Italian (see for example in French here: https://france.googleblog.com/2015/03/google-safe-browsing-nous-protegeons.html)
Some locales have decided to translate it, though (like Arabic) - I will check in if that should be updated or not

**Comment by Delphine** [comment]
Just got confirmation it should not be an issue for the locales who have decided to translate that (it's what happens on Firefox Desktop too).
In fact, some languages would just not be able to read/understand what the term means otherwise

**Comment by mcarare** [comment]
Closing as per above comment.
