### ISSUE TITLE
Force RTL is not applied to context menus

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#5395]
## Steps to reproduce
1. Go to developer Options and enable "Force RTL layout direction".
2. Open Focus and go to cnn.com.
3. Long tap on a link.
4. Check the text and layout of the Context Menu.

### Expected behavior
The layout of the Context menu is Right to left.

### Actual behavior
The layout of the device is Left to Right.

### Device information
* Android device: Pixel 3 (Android 12).
* Focus version: 93.0.2.

**Comment by mcarare** [comment]
Does this also happen with RTL languages? Or only when using Force RTL layout direction?

**Comment by sflorean** [comment]
> Does this also happen with RTL languages? Or only when using Force RTL layout direction?

This is not reproducible with RTL languages, only with Force RTL.

**Comment by lobontiumira** [comment]
I will re-open this issue because I was able to reproduce it on the latest Focus Nightly build 101.0a1 from 4/28 with Oppo Reno 6 (Android 12), and Samsung Galaxy Note 8 (Android 9).

**Comment by AyushUnleashed** [comment]
can I work on this issue, I am a beginner at Opensource with Android Dev experience in Kotlin.

**Comment by Mugurell** [comment]
> can I work on this issue, I am a beginner at Opensource with Android Dev experience in Kotlin.

Would be great to! Thank you!

**Comment by AyushUnleashed** [comment]
Sorry for not responding timely, I was not able to set it up locally, today, I'll try my best to do so & reply back.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802660

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
@AyushUnleashed Sorry to complicate your work on this bug, but the Focus team is moving the Focus Android code from this GitHub repo to https://github.com/mozilla-mobile/firefox-android and moving the Focus bug tracking to Bugzilla. This GitHub bug is now tracked in Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1802660. You will need to clone and build Focus from the new repo and create a Bugzilla account.
