### ISSUE TITLE
[L10N] RTL options are not applied on the Privacy & Security page entirely

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5397]
## Steps to reproduce
1. Go to the device's settings - Developer pptions, and enable "Force RTL layout direction".
2. Open Focus, and go to Settings - Privacy & Security, or Advanced.

### Expected behavior
The titles of the Privacy & Security areas are aligned from right to left.

### Actual behavior
The titles of the Privacy & Security areas are aligned from left to right.

### Device information
* Android device: all
* Focus version: 93.0.2

![RTL](https://user-images.githubusercontent.com/40694158/133266675-f5855add-4c0e-446f-a2d9-95d07c370b1b.png)

**Comment by lobontiumira** [comment]
@mcarare no, this is not reproducible on RTL languages:

<img src="https://user-images.githubusercontent.com/40694158/133384161-bbaa4822-20a1-4ea8-9e06-18c174f4cc6e.jpeg" width="300" height="550" />

**Comment by mcarare** [comment]
@lobontiumira Thanks for confirming. I have a PR ready to fix this, I will add the label when it's ready for QA.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 9/16 (build 11 - GV 93.0a1-20210906031657) with Samsung Galaxy Note 8 (Android 9):

![force RTL](https://user-images.githubusercontent.com/40694158/133567689-51ba1802-804d-4c4c-bf9a-894c51ea1d87.png)

**Comment by lobontiumira** [comment]
Verified also on the 93.0.3 build, with Lenovo Tab M10 (Android 10).
