### ISSUE TITLE
[L10N] The SUMO links from Your Rights page are not translated.

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5398]
## Steps to reproduce
1. Change your device language to any language.
2. Go to Settings->Mozilla->Your Rights.
3. Open every link from the page.

### Expected behavior
The SUMO links from Your Rights page should be translated in the language of the device.

### Actual behavior
The SUMO links from Your Rights page are displayed in English.

### Device information
* Android device: all
* Focus version: 93.0.2 (Build #352522329 93.0a1-20210906031657).

**Comment by mcarare** [comment]
Not sure we have localized versions of those pages. We should check before adding language tag for those links.

**Comment by amedyne** [comment]
On v92 of Focus, this is not fully translated either. 
![Screenshot_20210915-121657](https://user-images.githubusercontent.com/68711330/133471044-ff33ae0b-3b71-48de-b51b-a45244212718.png)

**Comment by amedyne** [comment]
Tagging @jr-johnson-support and @channingcarter .
Need final call on what to route to for this page.

**Comment by jr-johnson-support** [comment]
On Fenix, this is the link that opens when you select Your Rights: https://support.mozilla.org/en-US/kb/firefox-android-your-rights?as=u&utm_source=inproduct. Checking the SUMO translations, that page is translated to en-US, bn, cs, de, es, fr, it, pt-BR, pt-PT, ru, vi, and ZH-CN. if the system language is set to one of these when they hit the Knowledge base article, then it should show the translated copy.

**Comment by jr-johnson-support** [comment]
To clarify, are we talking about the links from this page
![Screenshot_20210915-103333_Firefox](https://user-images.githubusercontent.com/58608126/133482429-adae3f9a-42af-4cd5-8626-7f9a0490bd9b.jpg)

Or the links within the SUMO article here from clicking 'Know your Rights' 
![Screenshot_20210915-103453_Firefox](https://user-images.githubusercontent.com/58608126/133482498-6344d520-e980-479c-af11-67ada6df3d62.jpg)

The later only has one additional Link to a SUMO kb article for the provide feedback section: https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-browsers?redirectslug=send-usage-data-firefox-mobile-devices&redirectlocale=en-US

**Comment by jr-johnson-support** [comment]
> Tagging @jr-johnson-support and @channingcarter .
> Need final call on what to route to for this page.

Re:Amadyne - FX for Android 'Know your Rights' Links to SUMO. Meanwhile 'Know your Rights' On iOS links to https://www.mozilla.org/en-US/about/legal/terms/firefox/ and Focus has the copy right there on the page instead of linking out. 

So first I think we need to figure out what we want to do for these 3 different experiences. If the Policy is different for each product then we should create support KB articles for each and link out to them from the products. Then we can fix any missing translations or issues with it catching system language. 

If the Policy is not different between them, then we should link out to https://www.mozilla.org/en-US/about/legal/terms/firefox/ for all three I would assume and the translations handled by the appropriate team.

**Comment by Delphine** [comment]
Has there been any decision made about this? Thanks!

**Comment by amedyne** [comment]
Per discussions and clarification with @channingcarter , On Focus Settings->Mozilla->Your Rights should route the user to the following: https://www.mozilla.org/en-US/about/legal/terms/firefox/

**Comment by lobontiumira** [comment]
Reproducible on the following languages with Google Pixel (Android 10), on Beta 96.0.0-beta.1:
* Slovenčina 
* Chinese zh-TW
* Chinese zh-CN
* Dolnoserbski (Lower Sorbian - dsb)
* Hornjoserbšćina (Upper Sorbian - hsb)

**Comment by Delphine** [comment]
There are localized versions of this page, which users should be redirected to. For example:
French - https://www.mozilla.org/fr/about/legal/terms/firefox/
Italian - https://www.mozilla.org/it/about/legal/terms/firefox/
Are redirects not working properly perhaps?

**Comment by ionutbedregeanu** [comment]
Since is not something we should do locally in the app I will remove ticket from Android Focus Backlog

**Comment by lobontiumira** [comment]
Reproducible on RC 97.1.0 with Punjabi (Indian) with Lenovo Tab M10 (Android 10).
