### ISSUE TITLE
[a11y] "System default" option not working 2/3 times on Pixel 3

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#5399]
## Steps to reproduce
1. Go to Settings - General -  Language.
2. Change the language.
3. Perform some browsing.
4. Perform again step 1 and change to System default.

### Expected behavior
The language is changed.

### Actual behavior
The language is not changes, but the system default setting is enabled.
Reproducible 2/3 times.
Not reproducible after a clear data. 

### Device information
* Android device: Pixel 3 (Android 12)
* Focus version: 93.0.2.

**Comment by mcarare** [comment]
When: "The language is not changes, but the system default setting is enabled." this means 100% still in the previous language or just some parts of the app? 
This happens only on Android 12?

**Comment by lobontiumira** [comment]
I was not able to reproduce the issue on Google Pixel (Android 10) on RC 95.2.0, nor on Focus Nightly from 12/29.

**Comment by sflorean** [comment]
The issue is not reproducible anymore on 95.2.0 with Pixel 3 (Android 12). I will close it.
