### ISSUE TITLE
Rotating device does not use the landscape background 

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#5401]
## Steps to reproduce
1. Open up a build of Focus with the new splash screen.
2. Observe the gradient direction.
3. Rotate the device.
4. Observe the gradient direction again.
5. Open settings, then close it to return to the homescreen.
6. Observe the gradient direction one more time

### Expected behavior
- At 4 and 6, the direction should be similar to the [landscape designs](https://www.figma.com/file/jgsM2hWimZbPmtUJn7IGIB/Landing-Page?node-id=2030%3A68481).

### Actual behavior
- Only at 6, the direction is similar to the landscape designs.

### Device information

* Android device: All devices
* Focus version: Happens on all varients, but the nightly gradient is easiest to notice.

**Comment by jonalmeida** [comment]
This might be because we're handling [rotation now](https://github.com/mozilla-mobile/focus-android/blob/main/app/src/main/AndroidManifest.xml#L75), so we need to re-draw our background drawable.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Nightly build from main from 9/16, and on the last debug build from main from 9/16, with OnePlus 5T (Android 10), and Samsung Galaxy Note 8 (Android 9).

![Nightly](https://user-images.githubusercontent.com/40694158/133605501-6ff81e6a-c4b3-44cd-9935-7c2966878bb0.png)

**Comment by lobontiumira** [comment]
Verified as fixed also on 93.0.3 build with Lenovo Tab M10 (Android 10).

**Comment by delia-pop** [comment]
Verified as fixed as well on the 93.0.3 build with Huawei P9 Lite (Android 8).
