### ISSUE TITLE
Remove string "Tabs" Under Settings->General

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#5416]
from: https://github.com/mozilla/focus_foxfooding_campaign/issues/53
**Firefox Version:** Mozilla/5.0 (Android 7.0; Mobile; rv:93.0) Gecko/93.0 Firefox/93.0
**Window Size (inner width and height):** 360x232
**GitHub Username:** @gioisco
## Steps to Reproduce
1) 3 dots
2) Settings
3) General (description): Defaut browser, tabs, language

## Expected Behavior
After tapping General settings, I expected tabs settings. 

## Actual Behavior
In general section there are only 2 settings:
- default
- language 

## Screenshot 
![Problem Screenshot](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/151ed8da-7126-440e-8ff8-6b6879025ba0.png)

**Comment by amedyne** [comment]
Should also address this: https://github.com/mozilla/focus_foxfooding_campaign/issues/42

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Focus 93.0.3.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
