### ISSUE TITLE
 While pressing and hold in options in "open in..." menu, the focusing color is too deep notice #41 

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#5417]
From: https://github.com/mozilla/focus_foxfooding_campaign/issues/41
**Firefox Version:** Mozilla/5.0 (Android 10; Mobile; rv:93.0) Gecko/93.0 Firefox/93.0
**Window Size (inner width and height):** 396x813
**GitHub Username:** @mMARUF
## Steps to Reproduce
1) Open Firefox Focus
2) Open the three dot menu
3) Press open in... Option
4) Press and hold any option in the menu

## Expected Behavior
After press and hold any option, the focusing color should not be deep violet, it should be of light color for better visibility

## Actual Behavior
We see that after press and hold in any opinion, the focusing for that option is not that much clear. The focusing color is deep violet, which is is not easy to see

## Screenshot 
![Problem Screenshot](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/deeee5cd-dad7-4749-b59d-96f1a70b1eda.jpg)

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main from 9/21 with GV 93.0a1-20210906031657 with OnePlus 5T (Android 10), Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9).

![Screenshot_20210921-155146](https://user-images.githubusercontent.com/40694158/134174436-59e5d74d-59b0-4998-8341-9cec37f62a99.jpg)
