### ISSUE TITLE
The "Language" page doesn't fit the screen

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5451]
## Steps to reproduce
1. Go to Settings - General - Language, and observe the "Language" page.

### Expected behavior
The "Language" page fits the screen, as per design here: https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2140%3A71629

![figma](https://user-images.githubusercontent.com/40694158/134337158-53696bc6-adde-4434-8e66-9683435c448f.jpg)

### Actual behavior
The "Language" page doesn't fit the screen - it is mostly visible on tablets.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), OnePlus 5T (Android 10), and Lenovo Tab M10 (Android 10)
* Focus version: RC 92.1.1, debug build from main from 9/22

![language](https://user-images.githubusercontent.com/40694158/134336860-d540d2a0-2b02-4928-a506-8c707ba9d475.png)

**Comment by lobontiumira** [comment]
@eliserichards this is how it is displayed on Focus Nightly on a Samsung Galaxy Note 8 (Android 9) phone:

![Screenshot_1](https://user-images.githubusercontent.com/40694158/139829816-82ad604c-07af-4dce-b86f-98056670f49f.jpg)

So, I don't think it is a tablet issue. I am not sure if this is intended or not.

**Comment by mcarare** [comment]
This will no longer be an issue when a fix for https://github.com/mozilla-mobile/focus-android/issues/5293 lands. So I am inclined to close this and keep the other issue for follow-ups on this component.
