### ISSUE TITLE
Unresponsive screen after taping on the search bar while in Landscape mode on Google.com/ Youtube.com.

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5454]
## Steps to reproduce
1. Go to Google.com/ Youtube.com/Tmall.com.
2. Rotate the device in Landscape mode.
3. Tap on the search bar.
4. Observe the screen.

### Expected behavior
The search bar is displayed without issues and the user can type in.

### Actual behavior
The entire space above the keyboard (search bar and URL) is grayed out and the keyboard is unresponsive.

### Device information
* Android device: Huawei P20 (Android 10).
* Focus version:  Debug build from main 09/22 (93.0.3 GV - 93.0a1-20210906031657).

https://user-images.githubusercontent.com/89388888/134343830-fd7057de-a301-4250-ba82-c3c2c7fefe25.mp4

**Comment by ionutbedregeanu** [comment]
I didn't succeed to reproduce it anymore
