### ISSUE TITLE
Trashcan icon overlaps option "I Agree" and "Terms" link in the YouTube consent page.

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5455]
## Steps to reproduce
1. Go to Youtube.com.
2. Rotate the device from Portrait mode to Landscape mode and vice versa.
3. Scroll at the end of the consent prompt.
4. Notice the trashcan icon.

### Expected behavior
The "I Agree" option and "Terms" link should be properly displayed on both Portrait and Landscape modes.

### Actual behavior
In Portrait mode, the Trashcan icon overlaps the "Terms" link in the YouTube consent page.
In Landscape mode, the Trashcan icon overlaps option "I Agree" and "Terms" link in the YouTube consent page.

### Device information
* Android device: Huawei P20 (Android 10).
* Focus version:  Debug build from main 09/22 (93.0.3 GV - 93.0a1-20210906031657).

https://user-images.githubusercontent.com/89388888/134345570-6adf50a5-55cc-4706-8cf5-770807130b10.mp4

**Comment by ionutbedregeanu** [comment]
Fixed by https://github.com/mozilla-mobile/focus-android/issues/5829
