### ISSUE TITLE
Heise.de does not serve a mobile version of the website

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#546]
I noticed that heise.de does serve the desktop version to Focus while Firefox/Chrome do get the mobile version. Not sure if they are just using a bad user agent sniffer or whether we might need to tweak something.

**Comment by st3fan** [comment]
Looks like bad UA sniffing. Same thing happens for Focus/Klar for iOS. If we talk to them, can we also ask them to fix the detection for iOS?

**Comment by pocmo** [comment]
@bbinto You have a contact there, right?

**Comment by pocmo** [comment]
Removing v1 flag as this is not something we can fix on our side and therefore doesn't need to track a specific release.

**Comment by pocmo** [comment]
This is fixed now.

@st3fan Does it work on iOS now too?
