### ISSUE TITLE
Lighten Shortcut Tile background color

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5463]
Following the fix for #5442, we should also change the colour of our Shortcut Tile background, from `Ink 30` `#2e255c` to `Ink 05` `#393473`:

<img width="360" alt="Android - 1 to 4 Shortcuts - Keyboard Up@2x" src="https://user-images.githubusercontent.com/51007/134446879-10c612c9-3070-42ff-93d4-5e579351f308.png">

**Comment by mcarare** [comment]
@brampitoyo Do we have designs in Figma for shortcuts in LIght theme?

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 9/30 (build 11 GV 94.0a1-20210927093458):

![Screenshot_1](https://user-images.githubusercontent.com/40694158/135443431-7ddc562c-b732-4bf7-b4b0-04ab8f9616f7.jpg)

**Comment by lobontiumira** [comment]
Re-opening for Bram's input.

**Comment by brampitoyo** [comment]
Sure. We haven’t officially designed all the light theme components, but the tile background should be coloured white `#ffffff`. Let’s make sure that we use a colour token that already exist, rather than specifying a new one.

As soon as it’s designed, I’ll post the Figma link here.

**Comment by brampitoyo** [comment]
@lobontiumira @mcarare reference image:

<img width="360" alt="Android - 1 to 4 Shortcuts - Keyboard Up@2x" src="https://user-images.githubusercontent.com/51007/135916285-ef76cee7-375e-47e3-98d6-6e4545471079.png">

Figma: https://www.figma.com/file/KggJlo8pg2T2Q8nn0Ec5c3/Shortcuts?node-id=1836%3A46849

**Comment by mcarare** [comment]
@brampitoyo EDE7FF is not a Photon color. Shouldn't it be?

**Comment by brampitoyo** [comment]
@mcarare Sorry for the late reply on this. There seems to be a mixup!

The colour token `violet 05` should have the value of `#e7dfff` as specified by the existing Firefox Colour library, rather than `#ede7ff`. I mixed up the placement of `e7` and `ed`. Sorry about that!
