### ISSUE TITLE
Lighten URL bar / address box background color

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5464]
Following the fix for #5442, we should also change the colour of our URL bar / address box background, from `Ink 30` `#2e255c` to `Ink 05` `#393473`:

| Current | Proposed |
| --- | --- |
| <img width="360" alt="Android - 1 to 4 Shortcuts - Keyboard Up@2x" src="https://user-images.githubusercontent.com/51007/134447119-365bed7f-0fec-42d4-9fd9-2776e1630b56.png"> | <img width="360" alt="Android - 1 to 4 Shortcuts - Keyboard Up@2x" src="https://user-images.githubusercontent.com/51007/134447147-9c6e0d72-9662-4fe1-b412-b0da866ccbca.png"> |
 
This will make the design fit according to the Figma specs that @Kate-Galetski had created: https://www.figma.com/file/jgsM2hWimZbPmtUJn7IGIB/Landing-Page?node-id=2578%3A70617

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 9/30 (build 11 GV 94.0a1-20210927093458):

![Screenshot_20210930-135512](https://user-images.githubusercontent.com/40694158/135443198-7c633922-d821-485f-9517-e7ae9015b9bd.png)
