### ISSUE TITLE
The toolbar remains displayed when scrolling down on different pages on tmall.com

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5466]
## Steps to reproduce
1. Go to tmall.com/taobao.com
2. Scroll down and up on the main page, "Cost-effective" or "Classification" pages, reviews section (taobao.com).
3. Notice the trashcan icon.

### Expected behavior
The trashcan icon should be dismissed when scrolling down on the pages.

### Actual behavior
The trashcan icon remains displayed when scrolling down on different pages (e.g. main page, "Cost-effective" or "Classification" pages.

### Device information
* Android device: Huawei P20 (Android 10).
* Focus version:  Debug build from main 09/23 (93.0.3 GV - 93.0a1-20210906031657).

https://user-images.githubusercontent.com/89388888/134488505-6eb55f96-3453-4b8b-a648-575cfa40903d.mp4

**Comment by jonalmeida** [comment]
While trying to reproduce https://github.com/mozilla-mobile/focus-android/issues/5487 I was able to reproduce this too on a Pixel 3.

That might help confirm that it's not hardware (Huawei) specific.

<img width="762" alt="Screen Shot 2021-09-27 at 11 12 20 PM" src="https://user-images.githubusercontent.com/1370580/135016708-09009f41-fa7f-47ac-b0df-7fad0b3ce86a.png">

**Comment by jonalmeida** [comment]
I'm beginning to think #5487 and this are related. They seem to have the same effects: tapping the icon shows the tab switcher (with one tab).

**Comment by ionutbedregeanu** [comment]
Erase button should be hidden when the toolbar is also hidden. I will take a look to see why both of them doesn't change their state at scroll

**Comment by ionutbedregeanu** [comment]
It's not an obvious scenario but in this case it's an intended behaviour.
Focus toolbar, floating buttons shouldn't change their state when we are scrolling on a specific item, in our case a nested scrollable item

**Comment by ionutbedregeanu** [comment]
My bad, seems to be GeckoView issue. I will log a ticket on Bugzilla for that

**Comment by ionutbedregeanu** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1733572

**Comment by lobontiumira** [comment]
I was not able to reproduce this on tmall, com, or taobao.com anymore, due to the fact that the trash icon is moved.
Tested on the latest Focus Nightly from 11/24 with Google Pixel (Android 10).
I'll leave this ticket opened for the displayed toolbar when scrolling:


https://user-images.githubusercontent.com/40694158/143222099-c7294dd6-c768-45ae-ba5b-99f47da69ed3.mp4
