### ISSUE TITLE
First run experiance suggests that there is an ad-blocker in Focus

### ISSUE THREAD

**Issue by plwt** [mozilla-mobile/focus-android#5478]
## Steps to reproduce

Open Firefox Focus for Android from a first-run state

### Expected behavior

Wording on panels that are displayed reflects the product features.

### Actual behavior

The first panel states "Block ads and other content that can track you across sites and bog down page load times.".  This suggests that there is an ad-blocker, when in reality Focus blocks ad _tracking_, rather than the ads themselves.

### Device information

* Android device: Motorola Moto E5
* Focus version:  92.1.1 and 93.0

![Screenshot_20210923-094627](https://user-images.githubusercontent.com/31939113/134725917-5f74cbac-5af6-44c0-88cc-6996536caed2.png)

**Comment by amedyne** [comment]
@channingcarter FYI.

**Comment by amedyne** [comment]
@SeburoSUMO There is a planned redesign of onboarding so this is noted that we have to re-evaluate and update wording.

**Comment by mcarare** [comment]
An additional note: this first run fragment also needs designs for the light theme.

**Comment by amedyne** [comment]
Closing this issue since there will be new Focus onboarding screens. See https://github.com/mozilla-mobile/focus-android/issues/6297
