### ISSUE TITLE
A grey bar is visible when watching a video in fullscreen mode

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#5486]
## Steps to reproduce
1. Play a video.
2. Make the video full screen.

### Expected behaviour
- The video is taken the full area.

### Actual behaviour
- There is a grey bar at the bottom (landscape or portrait).
<img width="426" alt="Screen Shot 2021-09-27 at 9 50 30 PM" src="https://user-images.githubusercontent.com/1370580/135009288-18d7aa01-f649-47d5-a9a3-95e85e122a57.png">

### Device information

* Android device: All devices
* Focus version: main @ e595eda1

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 9/30 with Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
