### ISSUE TITLE
Migrate old telemetry to Glean

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#5488]
This task will cover the change needed to migrate old telemetry to Glean.
Refer to this spreadsheet for details: https://docs.google.com/spreadsheets/d/16hDajzs4ICWsNQP7lhCfD5e8bezh78CQZ1aQ_IK4Jx0/edit#gid=0

**Comment by mcarare** [comment]
Starting a list with migration issues splitting.

- [ ] Migrate telemetry related to pro tips on home screen - issue https://github.com/mozilla-mobile/focus-android/issues/5541.
