### ISSUE TITLE
More foreground events than background events

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#549]
We seem to be sending more foreground events than background events. And I saw at least one ping that had two foreground events at time 0 in it.

**Comment by ahunt** [comment]
The difference is small - that could just be the app crashing? (I'm not sure how long we've been getting telemetry, but we've definitely had more than 11 crash reports via buddybuild.)

**Comment by ahunt** [comment]
I found one ping with 5 foreground events with timestamp == 0:
[[10508589,"action","foreground","app",null,null],[10552610,"action","background","app",null,null],[0,"action","foreground","app",null,null],[0,"action","foreground","app",null,null],[1,"action","foreground","app",null,null],[0,"action","foreground","app",null,null],[0,"action","foreground","app",null,null],[0,"action","foreground","app",null,null],[22433,"action","background","app",null,null]]

This looks like they didn't do much on the two successful runs, and focus crashed every other time.

There's another ping with 3 foregrounds with timestamp == 0, where it looks like the app kept crashing again (although it's not clear why there's a foreground at 72, without a preceeding background)
[[0,"action","foreground","app",null,null],[540,"action","background","app",null,null],[0,"action","foreground","app",null,null],[1,"action","intent_url","app",null,null],[0,"action","foreground","app",null,null],[1,"action","intent_url","app",null,null],[88,"action","foreground","app",null,null],[0,"action","intent_url","app",null,null],[72,"action","foreground","app",null,null],[0,"action","click","notification","erase",null],[588,"action","foreground","app",null,null],[719,"action","background","app",null,null]]

There are a lot more pings with two foregrounds at time == 0 - this just looks like normal usage: AFAICS we don't send a ping until there are enough events to send, so if we don't generate many events during one session, then exit normally (and then wait long enough for Android to kill the app), and restart, we'll get two foregrounds with time==0 in the same ping.

**Comment by pocmo** [comment]
Thanks for investigating this! This looks good to me. So I'm going to close this.

However I filed a new bug in the telemetry repository to investigate whether we should have a timestamp that works across multiple sessions instead of always starting at 0.
