### ISSUE TITLE
Rotating device opens new tab when Focus was started through site shortcut

### ISSUE THREAD

**Issue by youri--** [mozilla-mobile/focus-android#5495]
## Steps to reproduce

1. Open any site in Focus
2. Menu > Add to home screen
3. Kill focus (remove from recent apps)
4. Open focus using the site shortcut you just added to your home screen
5. Rotate your device 90 degrees

### Expected behavior

Currently open site to stay active, only rotated.

### Actual behavior

A new tab opens with the site you started Focus with, the one added to the home screen. In fact, every rotation a new tab is opened.

### Device information

* Android device: OnePlus 6 (A6003)
* Focus version: 92.1.1

My user agent: Mozilla/5.0 (Android 11; Mobile; rv:92.0) Gecko/92.0 Firefox/92.0
Other HTTP headers
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,nl-NL;q=0.5
Host: duckduckgo.com
Referer: https://duckduckgo.com/
TE: trailers
User-Agent: Mozilla/5.0 (Android 11; Mobile; rv:92.0) Gecko/92.0 Firefox/92.0
DNT: 1
SEC-FETCH-DEST: document
SEC-FETCH-MODE: navigate
SEC-FETCH-SITE: same-origin
SEC-FETCH-USER: ?1
UPGRADE-INSECURE-REQUESTS: 1

**Comment by mcarare** [comment]
This seems the same issue as https://github.com/mozilla-mobile/focus-android/issues/5361. 
This should no longer be a problem in 93.

**Comment by youri--** [comment]
@mcarare my apologies, I had searched for it, but only in open issues. This one can be closed then. Thanks!

**Comment by mcarare** [comment]
@youri-- No worries, thank you for your report!
