### ISSUE TITLE
Set user agent

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#55]
**Firefox for Android**

    Mozilla/5.0 (Android 7.1.1; Mobile; rv:54.0) Gecko/54.0 Firefox/54.0

**Firefox for iOS**

    Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) FxiOS/1.0 Mobile/12F69 Safari/600.1.4

**Focus for iOS**

    Mozilla/5.0 (iPhone; CPU Iphone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Focus/3.1 Mobile/14C89

**Default Android WebView**

    Mozilla/5.0 (Linux; Android 7.1.1; Pixel XL Build/NOF26V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36

**Comment by ahunt** [comment]
Firefox for Android replaces Mobile with Tablet for tablets - I wonder if we'd want to do something similar (it uses Configuration.SCREENLAYOUT_SIZE_LARGE and larger to set tablet mode).

**Comment by pocmo** [comment]
Related: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox

@st3fan @thebnich Is there anything we should take care of (especially in regards to tracking)? It looks like the iOS user agent has the same structure like Firefox for iOS?

**Comment by ahunt** [comment]
(AFAICT only firefox on Android uses the Tablet/Mobile strings within the platform part of the UA. Everyone else uses Mobile only for mobile devices, later in the UA. I don't know which route we'd want to go here...)

**Comment by st3fan** [comment]
@ahunt Can we look at some other Android WebKit based browsers to compare? How about UC Browser, Chrome, etc. Is there a common pattern there?

**Comment by miketaylr** [comment]
Here's [Chrome's format](https://developer.chrome.com/multidevice/user-agent):

`Mozilla/5.0 (Linux; <Android Version>; <Build Tag etc.>) AppleWebKit/<WebKit Rev> (KHTML, like Gecko) Chrome/<Chrome Rev> Mobile Safari/<WebKit Rev>`

`Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19`

Here's [Samsung](http://developer.samsung.com/technical-doc/view.do?v=T000000203) (in the most confusing format ever):

`Mozilla/$(MOZILA_VER) ($(DEVICE_TYPE); $(OS); $(PLATFORM) $(PLATFORM_VER);
SAMSUNG $(MODEL_NAME) Build/$(BUILD_TAG)) AppleWebKit/$(APPLEWEBKIT_VER)
(KHTML, like Gecko) $(APP_NAME)/$(APP_VER) (Chrome/$(CHROME_VER))
$(UX RECOMMEND) Safari/$(SAFARI_VER)`

`Mozilla/5.0 (Linux; Android 5.0.2; SAMSUNG SM-G925F Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36`


[UC](http://www.ucweb.com/download/UCBrowser_User_Agent_en.pdf) (maybe there's a generic format in that 23 page PDF, i dunno):

`Mozilla/5.0 (Linux; U; Android 2.3; en-US; MI-ONEPlus) AppleWebKit/534.13 (KHTML, like Gecko) UCBrowser/8.6.0.199 U3/0.8.0 Mobile Safari/534.13`

<hr>

Seems like following Samsung's lead here and sticking in $(APP_NAME)/$(APP_VER) before the Chrome tokens would be good. So based on the default WebView (removing the `;wv` token):

`Mozilla/5.0 (Linux; Android 7.1.1; Pixel XL Build/NOF26V;) AppleWebKit/537.36 (KHTML, like Gecko) Focus/1.0 Chrome/56.0.2924.87 Mobile Safari/537.36`

**Comment by miketaylr** [comment]
Whatever y'all decide, I would recommend we don't include the string `Firefox` anywhere. Otherwise the odds are pretty good you get sent Gecko-specific code.

**Comment by bbinto** [comment]
Talked to Elvin, he doesn't see any concerns but wants us to check with the sec team re: fingerprinting etc. (Selena's team). I'll send an email to Selena to review this bug.

**Comment by ahunt** [comment]
FWIW I'm keen to _not_ include the device name as part of the UA: most webkit based browsers on Android seem to include both the device name and build number in the UA, e.g. "SAMSUNG SM-G925F Build/LRX22G". I don't actually know what this is used for (and we might need to revise this if it turns our websites break), but it doesn't seem right to broadcast the device name (firefox for Android doesn't do so).

**Comment by miketaylr** [comment]
> I don't actually know what this is used for

We've seen sites use this in Japan to tie in specific operator/site promotions. But it doesn't seem to be common in the West, from my experience.

**Comment by miketaylr** [comment]
Ah, relevant info popped up in a Facebook-Mozilla mailing list:

> After investigating this it seems like the issue is that unlike Chrome or Samsung browser the user agent for Firefox for Android does not give us any device information. Since we don’t know what the current device is we are unable to look up the pixel ratio for the device and must fallback to lower quality images :/

So, at least for Facebook, they use device name to determine DPI (which sucks, IMO).
