### ISSUE TITLE
Scrolling up to the top, the URL bar and the trashcan icon are hidden

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5504]
## Steps to reproduce
1. Go to wikipedia.com
2. Scroll up & down a bit, just enough to hide the URL bar 
3. While scrolling back up with the URL bar hidden, observe the trash icon.
### Expected behavior
The URL bar and trash icon are visible while scrolling up. (if the specs haven't changed)
### Actual behavior
The URL bar stays hidden, even when you reached the top, it needs another short swipe to show it.
The trash icon is also hidden until the URL bar is displayed.
If you reach the bottom of the page and start to scroll up, then they are both displayed.
### Device information

* Android device: Pixel 2(Android 9)
* Focus version: RC 93.1.0

**Comment by ionutbedregeanu** [comment]
I put some logs to see why some scroll events are not treated and seems that offset changed listener from displayT
oolbar class misfire sometimes, onOffsetChanged method is not called.
I don't see a way to improve this to have 100% accuracy. 
@jonalmeida Any thoughts about that?

**Comment by jonalmeida** [comment]
I think we should revisit this after we land https://github.com/mozilla-mobile/focus-android/pull/5476. I think this probably relate to scroll behaviours that we can hook into with a listener on `BrowserToolbarBehavior`.
