### ISSUE TITLE
The Focus icon is not properly displayed on Android 7 and lower

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5508]
## Steps to reproduce
1. Install Focus on a device with Android 7 or lower.
2. Observe the icon.
### Expected behavior
The icon on the home screen should be the Focus icon.
### Actual behavior
The icon on the home screen is not the Focus icon.
### Note
The issue only occurs on devices with Android 7 or lower.
### Device information

* Android device: Huawei MediaPad M3 (Android 7), Sony Xperia Z5 (Android 7), Samsung Galaxy Tab A6 (Android 5.1.1), HTC Desire 530 (Android 6.0.1)
* Focus version: 93.1.0
![icon](https://user-images.githubusercontent.com/50983519/135276741-043f4936-4802-48b6-ad73-daf8d6391898.png)

**Comment by mcarare** [comment]
cc @ionutbedregeanu

**Comment by lobontiumira** [comment]
Verified as fixed on the RC 93.1.1 build with Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), and Xiaomi mi4i (Android 5.0.2).
![Screenshot_1](https://user-images.githubusercontent.com/40694158/135576106-926d4bbd-1289-493d-aa14-f913829aab67.jpg)
