### ISSUE TITLE
Don't animate the toolbar if a11y services are enabled

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5509]
## Steps to reproduce
1. Enable Talkback on your device.
2. Launch Firefox Focus.
3. Open 2 or more web pages, load one with content that must be scrolled (i.e. cnn.com).
4. Scroll down page using talkback gestures.
5. Observe the tab manager icon.

### Expected behavior
The tab manager icon remains present at all times when Talkback is enabled.

### Actual behavior
The tab manager icon disappears when scrolling down using the talkback gestures.

### Device information
* Android device: Huawei P9 Lite (Android 8).
* Focus version: RC 93.1.0 ( Build 352720228 GV - 93.0.20210927210923).

https://user-images.githubusercontent.com/89388888/135280216-f0f7d02d-319e-4a01-a3d3-7f77b6a6ef7e.mp4

**Comment by Mugurell** [comment]
There's a bigger issue here: the toolbar should not be animated if there's an a11y service enabled.
If we're to fix this the FABs would stay on the screen also.
Fenix for reference:
- https://github.com/mozilla-mobile/fenix/issues/17676
- https://github.com/mozilla-mobile/fenix/issues/18027
- https://github.com/mozilla-mobile/fenix/blob/2b363b98683a92d8f51af3757b899294908d9308/app/src/main/java/org/mozilla/fenix/utils/Settings.kt#L605-L615

**Comment by Mugurell** [comment]
Will also update the title.
