### ISSUE TITLE
The "Remove" option from a shortcut is overlapping the shortcut when the keyboard is triggered

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5514]
## Steps to reproduce
1. Install Focus v93.
2. Add a shortcut to the homescreen.
3. Go to the homescreen, and activate the keyboard.
4. Long-tap on the shortcut, and observe the position of the "Remove" option.

### Expected behavior
The "Remove" option is below the shortcut even when the keyboard is triggered.

### Actual behavior
The "Remove" option from a shortcut is overlapping the shortcut when the keyboard is triggered.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Huawei P9 Lite (Android 8)
* Focus version: 93.1.0 RC build, and on the latest debug build from main from 9/30
* Not reproducible on Samsung Galaxy Note 8 (Android 9), on Samsung Galaxy Tab A6 (Android 5.1.1), nor on Xiaomi mi4i (Android 5.0.2)

https://user-images.githubusercontent.com/40694158/135421375-d74ffe28-0c4d-4557-bc73-6765a8dbd08f.mp4

**Comment by lobontiumira** [comment]
This is still reproducible on RC 93.1.1 with the same devices: Sony Xperia Z5 Premium (Android 7.1.1), Huawei P9 Lite (Android 8).

**Comment by lobontiumira** [comment]
Still reproducible on Sony Xperia Z5 Premium (Android 7.1.1) on the latest Focus Nightly 95.0 (build 353061431 GV 95.0a1-20211101084651).

**Comment by delia-pop** [comment]
Reproducible on Beta 97.0.0-beta.5 with LG G7 fit (Android 8.1.0). The "Rename/Remove" option menu is displayed for a split second above the shortcut when tapped from the awesome bar. 

https://user-images.githubusercontent.com/89388888/151154922-de20cca3-9e89-481d-bc39-f31b5d07cfc7.mp4

**Comment by lobontiumira** [comment]
This issue still reproduces on all Focus builds (Nightly 102.0a1 from 5/26, Beta 101.0.0-beta.6, and RC 101.1.0) with Sony Xperia Z5 Premium (Android 7.1.1).
Not reproducible on Oppo Reno 6 (Android 12).

**Comment by ionutbedregeanu** [comment]
@lobontiumira Can you please check if you can reproduce it? I didn't succeed on my side

**Comment by lobontiumira** [comment]
@ionutbedregeanu this issue still reproduces on the latest Focus nightly 105.0a1 from 8/11 with Sony Xperia Z5 Premium (Android 7.1.1):

![Untitled](https://user-images.githubusercontent.com/40694158/184086423-c7d27e77-c643-4608-a8fb-90174d0ef2d2.png)

**Comment by ionutbedregeanu** [comment]
I succeed to reproduce it on my side on small devices, but compose `DropdownMenu` behaves by default like this when it doesn't have space to be extended, so I don't see how can I improve this. Maybe the UX team(@jeffreygee ) can help us with a solution

**Comment by lobontiumira** [comment]
This issue still reproduces on the latest Focus nightly 107.0a1 from 10/6, and Beta 106.0b4, with Sony Xperia Z5 Premium (Android 7.1.1):

![Untitled](https://user-images.githubusercontent.com/40694158/194244003-ea5b5dc3-d7f6-4581-bd78-ad7c0d2a4301.png)

**Comment by jeffreygee** [comment]
@lobontiumira I noticed this happens on Fenix too. The only suggestion I'd have to get around this is that we add an 'Open Shortcut' option to the menu.

cc: @rtestard any thoughts on this?

**Comment by rtestard** [comment]
> 

On the screenshots it seems to have space to be extended though?
I cannot reproduce on my pixel 4a and it's unclear under which circumstances it reproduces - certain screen sizes?

**Comment by lobontiumira** [comment]
@rtestard we were able to reproduce this only on:
* Sony Xperia Z5 Premium (Android 7.1.1) that has these characteristics: 2160 x 3840 pixels, 16:9 ratio (~806 ppi density), and
* Huawei P9 Lite (Android 7): 1080 x 1920 pixels (~432 ppi pixel density).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802250

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
