### ISSUE TITLE
Consider uploading findbugs reports *somewhere*

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#552]
If a findbugs failure happens, you need to build locally to view the actual failures - an html report is generated in the buddybuild VM, but it isn't accessible.

It's possible to manually upload files during the postbuild stage: findbugs reports currently land at the following location, so we just need to upload them somewhere (note: buddybuild automatically detects lint artifacts, but it isn't aware of findbugs):
file:///tmp/sandbox/workspace/app/build/reports/findbugs/findbugs.html

It isn't that hard to run findbugs locally, but it's hard to debug buddybuild specific failure (e.g. if you cause a findbugs failure in the UI tests, which you usually don't run locally, only the buddybuild build will fail, until you remember to build the UI tests locally - we've sidestepped that issue for now by ignoring tests in findbugs...). Therefore seeing the actual errors as encountered in a buddybuild build is helpful.

As mentioned above: we ignore any class with a name ending in Test, but that means we might accidentally ignore non-test files. Filtering by source location doesn't seem to work, so to be extra safe I'd like to eventually fix the findbugs issues in test files, and remove that *Test exclude. Which makes it more important to actually be able to access buddybuild's findbugs output.

**Comment by npark-mozilla** [comment]
I was thinking, maybe we can put some kind of slackbot that tells when findbug check has failed? I suppose we'd still need to copy the report somewhere and link its location though, (I wonder whether attaching files is possible with slackbot message, if so, then not) but we'd be informed immediately

**Comment by pocmo** [comment]
I enabled Sputnik on Friday. It's running findbugs, checkstyle and PMD - and posts violations right into the PR.
