### ISSUE TITLE
Focus drains phone battery

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#5520]
This bug is to investigate further reports from users that when Focus is in the background, the app uses a lot of battery.

See #5269, #4684

**Comment by kacnje** [comment]
I don't have any additional information. Just want to inform you that I noticed a huge battery drain tonight. 
Some days ago I bought a new phone and (like on the previous one) installed Firefox Focus (the latest version from Google Play). 
The phone is a new "Samsung Galaxy S21 FE" (debloated) with Android 12 and One UI 4. I was really surprised this morning when I saw a big fall in the battery capacity. I checked which app drinks so much juice while the phone was in Airplane mode overnight. It was a Firefox focus. I don't know how, I had just installed it and checked if it worked. Then it went to the background. 
Now I will be more careful about it.

**Comment by ionutbedregeanu** [comment]
I will monitor my current device(Pixel 3a Android 11) for a few days with https://developer.android.com/topic/performance/power/setup-battery-historian, to see if I catch something

**Comment by kacnje** [comment]
Tnx. Maybe you will find something. 
My "investigation": I noticed that Focus had a high battery drain while I had a shortcut to URL from Focus on Android's home screen. Yesterday I remove the shortcut and it looks that now everything is ok. It is interesting because the shortcut shows to my website which doesn't refresh by itself. Can shortcut (even if I didn't use it) be the reason for high battery consumption?

**Comment by ionutbedregeanu** [comment]
After some tests I didn't find anything weird, but I will let this ticket open to keep an eye on it
I also took a look on Network informations, Process info, Scheduled jobs, Services and I didn't notice something wrong

#### Day 1
First I tested with the debug version of Focus, I just let it open over night 

<img src="https://user-images.githubusercontent.com/11731652/164029472-c1b17b6c-9fa6-4d00-aa22-eab21cbead64.png"/>

#### Day 2
Debug version of Focus, open over night with an wikipedia shortcut and airplane mode on

![App Stats Day 2](https://user-images.githubusercontent.com/11731652/164030083-fafde9bc-19fe-42ae-ad4b-3581b8ba2936.png)

#### Day 3
Release version of Focus, open over night with an wikipedia shortcut and airplane mode on

![App Stats Day 3](https://user-images.githubusercontent.com/11731652/164030055-0d4eab14-1394-4a91-b09a-b4e30d8ab14b.png)

**Comment by kacnje** [comment]
After a few days, I can confirm that there is no Focus battery drain anymore while I remove a shortcut. A shortcut points to my weather station page: https://izo.amebis.si/belchertown
Maybe you can create a shortcut to it for a test.
I attacheched a screenshot I made when I noticed the problem. Commendation to your job. 
![Screenshot_20220412-033903_Device care](https://user-images.githubusercontent.com/54092707/164148963-1a9852d3-fbef-4fea-80ed-941454e05909.jpg)

**Comment by ionutbedregeanu** [comment]
Update: Still can't reproduce the bug
I will let this ticket open to be under observation
I tried the following scenario on debug and prod builds:
1. Open Focus debug/prod build
2. Navigate to https://izo.amebis.si/belchertown
3. Add  https://izo.amebis.si/belchertown as shortcut and as top site
4. Put the Focus app in background
5. Put the device on airplane mode
6. Let the device overnight in this state
### Battery stats after those tests
#### Debug build
![debug_weather_shortcut_battery_app_stats](https://user-images.githubusercontent.com/11731652/166629933-1e02f7f7-a60f-492e-ad28-975ebaa77537.png)
![debug_weather_shortcut_device_battery_stats](https://user-images.githubusercontent.com/11731652/166629940-ece8506d-82a1-4a99-8eab-6ee780480a3a.png)
#### Production build
![prod_weather_shortcut_device_battery_stats](https://user-images.githubusercontent.com/11731652/166629990-dc37135b-dbed-4c89-aff5-4a88c505c88d.png)
![prod_weather_shortcut_battery_app_stats](https://user-images.githubusercontent.com/11731652/166629992-61724a24-9fc4-408c-b467-25880c420015.png)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802659

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
