### ISSUE TITLE
Tabs are not restored after closing the crash report

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5524]
## Steps to reproduce
1. Open a few tabs and go to about:crashparent.
2. On the crash dialog tap "Close".
3. Re-open the app, observe that the tabs are not restored.

### Expected behavior
The tabs previously opened are restored.

### Actual behavior
The tabs previously opened are not restored.

### Device information
* Android device: RC 93.1.1 ( Build 352731721 GV - 93.0.20210927210923).
* Focus version: Huawei P9 Lite (Android 8), Oppo Find X3 Neo (Android 11).

https://user-images.githubusercontent.com/89388888/135611462-2e320ed4-2bd9-46b4-9c44-6ad184c75a95.mp4

**Comment by ionutbedregeanu** [comment]
Seems an intended behaviour. ^^ @amedyne @brampitoyo

**Comment by jonalmeida** [comment]
Yes, this is intended behaviour. Thanks for filing though. 🙂
