### ISSUE TITLE
The share button is black after coming from a custom tab

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5527]
## Steps to reproduce
1. Set focus as default browser;
2. Open a link from an external application (e.g. gmail);
3. Tap the 3 dot menu and select "Open in Firefox Focus";
4. Tap the 3 dot menu and observe the share icon.
### Expected behavior
The share icon should be white;
### Actual behavior
The share icon is black;
### Device information

* Android device: Oppo Find X3 (Android 11), OnePlus 6T (Android 9), OnePlus 5T (Android 9)
* Focus version: 93.1.1
![black](https://user-images.githubusercontent.com/50983519/135620212-b46b9b70-8f27-4d88-9149-d1d789d0fa5a.JPEG)

**Comment by mcarare** [comment]
This should be fixed after the PR for light theme is merged.

**Comment by delia-pop** [comment]
Verified as fixed on the latest debug build from main from 10/11 (build 11 GV 95.0a1-20211005094529), with Huawei P9 Lite (Android 8). The share icon is white when the Dark theme is selected, respectively black when the Light theme is selected.

**Comment by LaurentiuApahideanSV** [comment]
The issue still occurs on Focus 94.0.0-Beta.1.

**Comment by delia-pop** [comment]
The issue could also be reproduced on Beta 95.0.0-beta.3 with Huawei P9 Lite (Android 8).

![Screenshot_20211105-130224](https://user-images.githubusercontent.com/89388888/140509888-5dd919df-4db2-4935-b44d-5853a68fc98d.jpg)

**Comment by lobontiumira** [comment]
Verified as fixed on Beta 96.0.0-beta.1, and 12/7 Focus Nightly builds with Sony Xperia Z5 Premium (Android 7.1.1), and Lenovo Tab M10 (Android 10).
