### ISSUE TITLE
Migrate Pro tips telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5541]
Breakout from https://github.com/mozilla-mobile/focus-android/issues/5488.

> Question being answered by the data:

 How many users engage with protips?

**Comment by lobontiumira** [comment]
Verified on the latest debug Nightly from 10/14, with Google Pixel (Android 10), and here are my findings:
I've encountered these events:
* tip_displayed - fresh look tip:
```
          "timestamp": 195,
          "category": "pro_tips",
          "name": "tip_displayed",
          "extra": {
            "tip_id": "fresh_look_tip"
          }
```
* tip_displayed - link in tip clicked
```
          "timestamp": 17603,
          "category": "pro_tips",
          "name": "link_in_tip_clicked",
          "extra": {
            "tip_id": "fresh_look_tip"
          }
```
* tip_displayed - shortcuts tip
```
          "timestamp": 25652,
          "category": "pro_tips",
          "name": "tip_displayed",
          "extra": {
            "tip_id": "shortcuts_tip"
          }
```
* tip_displayed - allow list tip
```
          "timestamp": 26406,
          "category": "pro_tips",
          "name": "tip_displayed",
          "extra": {
            "tip_id": "allow_list_tip"
          }
```
* link_in_tip_clicked - allow list tip 
```
          "timestamp": 27368,
          "category": "pro_tips",
          "name": "link_in_tip_clicked",
          "extra": {
            "tip_id": "allow_list_tip"
          }
```

However, @mcarare  I did not encounter:
* etp_tip
* request_destop_tp

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2110140004)
