### ISSUE TITLE
Migrate open from external intents telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5547]
Breakout from https://github.com/mozilla-mobile/focus-android/issues/5488.

> Question being answered by the data:

 How often do users open the app from external intents.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 95.0 (build 353221030 with GV 96.0a1-20211117094929) with Google Pixel (Android 10).
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2111180002)

* open through the launcher site shortcut:
```
{
          "timestamp": 0,
          "category": "app_opened",
          "name": "from_launcher_site_shortcut"
        }
```
* open through app's icon:
```
{
          "timestamp": 0,
          "category": "app_opened",
          "name": "from_icons",
          "extra": {
            "open_type": "Resume"
          }
        }
```
* open app throught share from a different app:
```
{
          "timestamp": 0,
          "category": "app_opened",
          "name": "share_intent",
          "extra": {
            "is_search": "false"
          }
        }
```
* open app through text search privately
```
{
          "timestamp": 0,
          "category": "app_opened",
          "name": "text_selection_intent"
        }
```
