### ISSUE TITLE
Light Theme: background colour of Settings should match background colour of menu surfaces

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5554]
## Steps to reproduce
- Select ⋮ Main menu → ⚙️ Settings
- Observe background colour

### Expected behavior

Background colour matches value used by Light Theme menu surfaces: `Light Grey 05` `#FBFBFE`

<img width="360" alt="Android - Settings - Light@2x" src="https://user-images.githubusercontent.com/51007/136485798-0301e405-b51b-4bae-810c-c0f5e8df4de9.png">

Figma: https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2140%3A71629

### Actual behavior

Background colour is `Violet 05` `#E7DFFF`.

<img width="360" src="https://user-images.githubusercontent.com/51007/136485859-11f96e84-e31f-4100-a5ca-b4d403934b63.png">

**Comment by mcarare** [comment]
@brampitoyo In the Figma link you added the color is #FAFAFA. As that is not a photon color, I temporarily used a similar color -  Violet 05.
So Light Grey 05 is the final decision?

**Comment by mcarare** [comment]
@bram, thanks for the clarification and the follow-up!
