### ISSUE TITLE
Light Theme: text colour of pro tips should match text colour of secondary texts

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5556]
## Steps to reproduce
Observe the text colour of pro tips on the home screen.

### Expected behavior

The text colour of pro tips should be `On-Light 02` `Dark Grey 05` `#5b5b66` – the same colour value used on Shortcut tile titles and Settings secondary text.

<img width="360" alt="Android - Splash@2x" src="https://user-images.githubusercontent.com/51007/136488646-0b35ebe0-0c7b-482b-94a2-158342c4ce1b.png">

### Actual behavior

The text colour seems to be `On-Light Inactive` and set at 40% opacity?

<img width="360" src="https://user-images.githubusercontent.com/51007/136489085-d0abc886-bba7-4b3e-a0a3-759a98fd57f0.png">

**Comment by mcarare** [comment]
@brampitoyo Thanks for the review. I actually could not select the individual lines of text on Figma in order to see the text color.

**Comment by delia-pop** [comment]
Verified as fixed on Beta 94.0.0-beta.2 (build 352922038 GV 94.0-20211017185800) with Huawei P9 Lite (Android 8).
