### ISSUE TITLE
The list of available languages is invisible in light theme

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5561]
## Steps to reproduce
1. Build and install the latest debug build from main.
2. Set the device's theme to light, or from Settings - General select Light theme.
3. Tap on Language.

### Expected behavior
The list of available languages is displayed.

### Actual behavior
The list isn't visible at all.

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: 95.0 (build 11 GV 95.0a1-20211005094529)

![Screenshot_20211023-001528language](https://user-images.githubusercontent.com/40694158/136531481-22de34dd-6778-4077-b5cb-5e8d6a90e076.png)

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest debug build from main from 10/14 (build 11 GV 95.0a1-20211007091917) with Oppo Find X3 (Android 11). Not fixed yet in Beta 94.0.0 (build 352862025 GV 94.0-20211005185813).
