### ISSUE TITLE
Update colors for sessions list

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5569]
@brampitoyo any thoughts on this?

I did not find any designs for this. Sorry if they exist, it's sometimes difficult to find things in Figma.

I made these changes for the moment: https://github.com/mozilla-mobile/focus-android/pull/5562/commits/37898d107414283e48ca991beec73db814e24623

Let me know what you think. Thank you!

**Comment by brampitoyo** [comment]
Hi @mcarare, I assume that sessions list is the multi-tasking menu sheet?

If that’s the case, then we should use the same value as all other menu sheets, plus just a few additions (like the colour of action and action text):

| | Light Theme | Dark Theme |
| --- | --- | --- |
| | <img width="360" alt="Android - Browser - Context menu - image@2x-1" src="https://user-images.githubusercontent.com/51007/136856142-0016fcd3-6679-4652-b05f-48e313b98760.png"> | <img width="360" alt="Android - Browser - Context menu - image@2x" src="https://user-images.githubusercontent.com/51007/136856173-489c1ced-b857-4bf2-9b14-b5e40cfadc39.png"> |
| | <img width="280" alt="Light@2x" src="https://user-images.githubusercontent.com/51007/136858194-2266e9c3-eb21-42f0-9e2f-005340d1cc1d.png"> | <img width="280" alt="Dark@2x" src="https://user-images.githubusercontent.com/51007/136858212-4f8a5190-a834-4ee0-ad5e-29a1c72c79f6.png"> |
| colorSession | `photonLightGrey05` | `photonInk05` |
| colorActiveSession | `photonViolet05` | `photonInk60` |
| textColor | `photonInk50` | `photonLightGrey05` |
| colorAction | `photonPink70` | `photonPink70` |
| actionTextColor | `photonLightGrey05` | `photonLightGrey05` |

Note: action background and text color is identical across both Light and Dark Themes. This ensures AA contrast ratio.
