### ISSUE TITLE
Update snackbars colors for light theme.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5571]
TBD.

@brampitoyo The colors for the light theme are the same used for the dark theme snackbars.
There is however a question if we should also update the colors for the dark ones.

Currently, the colors are:

```
    <!-- Snackbar-->
    <color name="snackbarBackground">@color/photonDarkGrey05</color>
    <color name="snackbarTextColor">@color/photonWhite</color>
    <color name="snackbarActionText">@color/photonBlue50</color>
```
With the mention that snackbars shown from AC (related to actions from the context menu) have the action button as a pink color. (the correct one for controls / radio buttons, etc)

**Comment by brampitoyo** [comment]
Hi @mcarare, in the Nightly build I’m running, the Dark Theme snackbar already seems to have the correct colour values.

Here are what the values supposed to be, for both themes:

| | Light Theme | Dark Theme |
| --- | --- | --- |
| | <img width="356" alt="Snackbars@2x" src="https://user-images.githubusercontent.com/51007/136855233-fc208bf3-d0cd-4719-980c-a787c0651737.png"> | <img width="356" alt="Snackbars@2x" src="https://user-images.githubusercontent.com/51007/136855169-b0767785-4b92-46b7-8695-3457f6cbdd93.png"> |
| snackbarBackground | `photonLightGrey05` | `photonInk05` |
| snackbarTextColor | `photonInk50` | `photonLightGrey05` |
| snackbarActionText | `photonPink70` | `photonPink40` |

You’ll note that snackbarBackground uses identical value to backgrounds for menu elements.

TextColor is identical to all other texts within the app.

And Focus snackbars don’t have any ActionText (unlike Firefox, which has them). But if there is one, we use the same ActionText colour value as other accents already used in the app.

**Comment by brampitoyo** [comment]
@mcarare I forgot about those. Thanks for pointing them out!

I wonder whether we can convert them to a snackbar which is similar to the one above (and the one we have in Fenix) where they are offset by 8dp from the FAB ([behaviour guidelines](https://material.io/components/snackbars#behavior)) and side of the screen ?

Here’s a mockup for “New private tab opened”. Can we do the same for “Download finished”?

| Light Theme | Dark Theme |
| --- | --- |
| <img width="360" alt="Android - Browser - Multi Tasking Snackbar@2x-1" src="https://user-images.githubusercontent.com/51007/137068048-d145c107-0462-4c86-a4e6-36c123d0b6ee.png"> | <img width="360" alt="Android - Browser - Multi Tasking Snackbar@2x" src="https://user-images.githubusercontent.com/51007/137068086-8cdc6ecf-5ed9-4c25-9fc5-200cc72d1557.png"> |

**Comment by mcarare** [comment]
@brampitoyo I already did that. I will also add a commit [here](https://github.com/mozilla-mobile/focus-android/pull/5562)  to adjust snackbar bottom padding when the FAB is visible.

**Comment by brampitoyo** [comment]
@mcarare Thank you!

**Comment by brampitoyo** [comment]
@mcarare Just leaving a note to say that all the snackbars look great!

The only thing remaining to fix would be the 8dp padding against the left and right sides of the screen.

| Browsing history cleared | New private tab opened | Download finished |
| --- | --- | --- |
| <img width="360" src="https://user-images.githubusercontent.com/51007/137235519-993eedff-735e-4a60-a5fa-36e88af9b313.png"> | <img width="360" src="https://user-images.githubusercontent.com/51007/137235498-63f3bdbc-8594-47e7-9a71-9327394bf1df.png"> | <img width="360" src="https://user-images.githubusercontent.com/51007/137235504-9fe8e0ed-a124-4624-967b-b3ddc627f21c.png"> |
