### ISSUE TITLE
User is not warned that opening PDFs in app violates privacy when reclicking a .pdf link

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#5575]
## Steps to reproduce
- Have PDF reader app installed (I think I'm using the Google one)
- Visit http://shawnodonnells.com
- Click "Lunch/Dinner menu" (may need to scroll down)
- On "Open in app? Your activity may no longer be private" dialog, hit cancel. **This dialog is meant to protect me from doing something that loses my privacy**
- Click "Lunch/Dinner menu" again
- A different dialog appears. Hit "download"
- Hit "Open" in snackbar after download completes. **This flow has the same outcome as clicking "Open in app" in the previous dialog, but it didn't rewarn me that this violates my privacy.**

### Expected behavior
Any time we open in app, we warn the user about a loss of privacy

### Actual behavior
The second flow allowed me to open in app without the privacy violation warning.

There are two facets I see to this:
1. We probably shouldn't provide an alternative flow for clicking on .pdf links if the user cancels the action
2. The "Open" snackbar after a download completes should probably warn about privacy violations

### Device information
* Android device: Moto G5
* Focus version: 93.0-20210927210923

### Screenshots
Here's a screenshot of the first dialog:
![image](https://user-images.githubusercontent.com/759372/136635915-bb1826de-ddb3-420d-9517-4964fb409094.png)

And the second alternative flow:
![image](https://user-images.githubusercontent.com/759372/136635934-ba2c21ac-2061-44b0-b93c-33809a091f5d.png)

**Comment by mcarare** [comment]
cc @brampitoyo
