### ISSUE TITLE
Blocking JavaScript in Settings doesn't actually work.

### ISSUE THREAD

**Issue by blordpluto** [mozilla-mobile/focus-android#5577]
## Steps to reproduce

1) Navigate to Settings >Privacy and Security> Block JavaScript and turn blocking on

2) Reload the page. It can be any page requiring JS. Try https://play2048.co if you need some inspiration.

### Expected behavior

JavaScript shouldn't run.

### Actual behavior

JavaScript does run.

### Device information
I don't think this matters. Please correct me if I'm wrong.

* Focus version: At Settings> Mozilla > About Firefox Focus > I see two version strings. This is incredibly confusing. 😞  I don't see how both of these can be true.
93.1.1 (Build #352731722)
93.0-20210927210923

I've used Focus with JS disabled for years and it's always worked until a recent autoupdate. Breaking this functionality, unannounced, in a security-oriented product is just wildly unacceptable. I hope you can put this at the very top of your bug priority list. In the meantime, I am switching to another browser. _This is how you lose users._

**Comment by cadeyrn** [comment]
@mcarare This issue is #5577. Did you mean another issue? I can't find another recent and open issue for a non-working JavaScript option.

**Comment by mcarare** [comment]
@blordpluto Does the setting work if you clear app data (or reinstall)?

**Comment by mcarare** [comment]
@blordpluto Thanks for checking!

Can you try another scenario: 
 - Toggle the JS setting to block JS.
 - Close the app completely (from task manager / recents screen)
 - Open the app and check if JS is blocked.
 
Thank you!
