### ISSUE TITLE
Add to home screen default icon background color

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5585]
@brampitoyo said:
> The only thing that still needs to change in this dialog, is the default colour of the tile background colour. Let’s use the same accent colour on Light Theme (even on Dark Theme – I know that we can’t have two different values for this tile), which is `pink 70`.

@brampitoyo That color is not something we set from Focus, but, just like Fenix, that is a color chosen in AC depending on the website snippet to match as best it can the website predominant color. 
 The colors we choose from are:

    <array name="mozac_browser_icons_photon_palette">
        <item>#9A4C00</item>
        <item>#AB008D</item>
        <item>#4C009C</item>
        <item>#002E9C</item>
        <item>#009EC2</item>
        <item>#009D02</item>
        <item>#51AB00</item>
        <item>#36385A</item>
    </array>

IMO this feature is important to be kept as such, as it helps differentiate between different launcher shortcuts that we add for multiple sites, when the site icon is not accessible. We can change the colors in that list as they do not seem to actually be photon colors (maybe they are old values).

_Originally posted by @mcarare in https://github.com/mozilla-mobile/focus-android/issues/5560#issuecomment-940756139_

**Comment by mcarare** [comment]
I have opened this follow-up for #5560 to discuss track any required change.

**Comment by brampitoyo** [comment]
@mcarare I didn’t know that the colour comes from A-C, and is matched to the site’s predominant colour! Let’s keep that approach, then.
