### ISSUE TITLE
No-internet-connection-screen doesn't work

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/focus-android#5587]
This bug has persisted for many months. I think it's time to finally fix an issue as ugly as this one.

## Steps to reproduce
1. Disable your internet-access (turn off that wifi-switch, for example)
2. Open FF-Klar
3. Search for anything

### Expected behavior
Some helpful site that tells you about the  connection-problem and has a reload-button.

### Actual behavior
No text, a blank button (i think it's supposed to be a button?) that does absolutely nothing onclick.

<img src = https://user-images.githubusercontent.com/59611881/136953757-239d42ec-bb77-4874-96d6-036b5fc679ce.jpg width = 40%>

### Device information

* Android device: Samsung Galaxy S9
* Focus version: 93.1.1

**Comment by mcarare** [comment]
At this moment the error pages use JS to display the message and button. If you do not have JS blocked this page will show up as intended.

**Comment by Glitchy-Tozier** [comment]
Thank you for the explnation!

However, isn't this a pretty big flaw of design for a browser whose selling point (among other things) is being able to easily block trackers and/or JS?
