### ISSUE TITLE
Block cookies options cannot be seen with light theme

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5588]
## Steps to reproduce
1. Install the latest debug build from main.
2. Go to Settings - Privacy & security - Block cookies and observe the available options.

### Expected behavior
The 4 options are visible.

### Actual behavior
The 4 options have white font, and cannot be seen. The user can select them, and they work as expected.

### Device information
* Android device: Google Pixel
* Focus version: 95.0 debug (build 11 GV 95.a01-20211007091917)

![Screenshot_20211012-153101](https://user-images.githubusercontent.com/40694158/136956922-147d7c18-0068-4e43-ab7e-4709e6d10782.png)

**Comment by mcarare** [comment]
This will be fixed in a9029dd54fccab0e424038b9bac22bdaf105038a, as it has the same root issue as https://github.com/mozilla-mobile/focus-android/issues/5561.

Still keeping this opened for later QA check.

**Comment by delia-pop** [comment]
Verified as fixed on Beta 94.0.0 -beta.2 (build 352922038 GV 94.0-20211017185800). with Huawei P9 Lite (Android 8).
