### ISSUE TITLE
Additional note colors need adjustments

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5589]
@amedyne – @lobontiumira is correct. Those screens need to match the Figma design.

Of particular interest are these values:

| | Light Theme | Dark Theme |
| --- | --- | --- |
| **textColor (primary)** <br> Text in all menus and panels should have the same colour value. Today, texts are coloured `#202021`, `#20123a`, `#52525e`, or `#000000`. | `photonInk50` | `photonLightGrey05` |
| **textColor (secondary)** <br> Used for captions and additional information, e.g. “Saved and shared images will not be deleted…” | `photonDarkGrey05` | `photonLightGrey50` |
| **menu background (primary)** <br> This is already correct | `photonLightGrey05` | `photonInk05` |
| **menu background (secondary)** <br> Used for captions and additional information, e.g. “Saved and shared images will not be deleted…” | `photonViolet05` | `photonInk60` |

_Originally posted by @brampitoyo in https://github.com/mozilla-mobile/focus-android/issues/4941#issuecomment-940586617_

**Comment by jonalmeida** [comment]
Let's file the 'Powered by Firefox Focus' as a separate issue. That's a bug in the existing theme as well and a separate fix (that needs AC work).
