### ISSUE TITLE
Intermittent UI test failure - SearchTest.changeSearchEngineTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5590]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8042151971263754580/executions/bs.77e475b387d67a4c/testcases/1/logs
### Stacktrace:
`10-12 01:49:53.855: W/InputDispatcher(2070): Attempted to unregister already unregistered input channel '9c96c2a org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)'
10-12 01:49:53.858: W/BinderNative(2070): Uncaught exception from death notification
10-12 01:49:53.858: W/BinderNative(2070): java.lang.NullPointerException: Attempt to read from field 'android.accessibilityservice.IAccessibilityServiceClient com.android.server.accessibility.AbstractAccessibilityServiceConnection.mServiceInterface' on a null object reference
10-12 01:49:53.858: W/BinderNative(2070): 	at com.android.server.accessibility.UiAutomationManager.destroyUiAutomationService(UiAutomationManager.java:179)
10-12 01:49:53.858: W/BinderNative(2070): 	at com.android.server.accessibility.UiAutomationManager.access$200(UiAutomationManager.java:41)
10-12 01:49:53.858: W/BinderNative(2070): 	at com.android.server.accessibility.UiAutomationManager$UiAutomationService.binderDied(UiAutomationManager.java:230)
10-12 01:49:53.858: W/BinderNative(2070): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:1193)
10-12 01:49:53.858: W/SurfaceFlinger(1924): Attempting to destroy on removed layer: AppWindowToken{110f6be token=Token{df76979 ActivityRecord{3575640 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t4}}}#0
10-12 01:49:53.860: W/ActivityManager(2070): Crash of app org.mozilla.focus.debug running instrumentation ComponentInfo{org.mozilla.focus.debug.test/androidx.test.runner.AndroidJUnitRunner}
10-12 01:49:53.860: I/ActivityManager(2070): Force stopping org.mozilla.focus.debug appid=10095 user=0: finished inst
10-12 01:49:53.860: I/ActivityManager(2070): Killing 7688:org.mozilla.focus.debug:tab3/u0a95 (adj 0): stop org.mozilla.focus.debug`
### Build:
10/12, started crashing with https://github.com/mozilla-mobile/focus-android/pull/5584

**Comment by mcarare** [comment]
This test passes for me locally, and that PR has nothing to do with search engines. Do you have a video with the moment it craashes?

**Comment by AndiAJ** [comment]
Crashed again on 11/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5278022112031714428/executions/bs.d828fd8c97058e9/testcases/1/logs)

**Comment by sv-ohorvath** [comment]
Logged a bug for investigation: https://github.com/mozilla-mobile/focus-android/issues/5794

**Comment by AndiAJ** [comment]
Crashed 1x on 11/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5145668493185678677/executions/bs.3f9fd2d84812e8b9/testcases/1/logs)

**Comment by sv-ohorvath** [comment]
Might be fixed with https://github.com/mozilla-mobile/focus-android/pull/5798. We'll wait for a while to see if it appears again and close this if not.

**Comment by AndiAJ** [comment]
`changeSearchEngineTest` crashed on 1/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7802761907098604153/executions/bs.ece542b11fda6abb/testcases/1/logs)

It crashed after performing the search using Wikipedia:
`Matched selector: UiSelector[CONTAINS_TEXT=Wikipedia]`

**Comment by AndiAJ** [comment]
Closing as it didn't fail for a couple of months
