### ISSUE TITLE
[RTL] "Block cookies" arrow in the settings is pointing the wrong direction

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-mobile/focus-android#5595]
## Steps to reproduce

1. Use Focus in an RTL language
2. Open settings
3. Security & Privacy
4. See the "block cookies" arrow

### Expected behavior

It should be pointing to the left.

### Actual behavior

It's pointing to the right.

### Device information

* Android device: Samsung Galaxy S10e
* Focus version: 93.1.1

**Comment by ItielMaN** [comment]
Still an issue.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 104.0a1 (build 361950510) with Oppo Reno 6 (Android 12):

![Screenshot_2](https://user-images.githubusercontent.com/40694158/178924245-7663b2f0-8b27-4aff-b1f1-6287ee94c947.jpg)
