### ISSUE TITLE
[RTL] "Secure connection" arrow in the site identity panel is pointing the wrong direction

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-mobile/focus-android#5596]
## Steps to reproduce

1. Use Focus in an RTL language
2. Open a secure website (not sure if this is a requirement)
3. Click the shield icon in the urlbar
4. See the "connection secure" arrow

### Expected behavior

It should be pointing to the left.

### Actual behavior

It's pointing to the right.

### Device information

* Android device: Samsung Galaxy S10e
* Focus version: 93.1.1

![Screenshot_20211013-130837_Firefox Focus](https://user-images.githubusercontent.com/18016656/137113951-ef385b7d-efb9-4935-9a0f-322f9e2cd0f8.jpg)

**Comment by ItielMaN** [comment]
Still an issue.

**Comment by lobontiumira** [comment]
Reproducible on Beta 102.0.0-beta.2 with Samsung Galaxy Tab A6 (Android 5.1.1) for the back arrow from the Languages page,

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 104.0a1 (build 361950510) with Oppo Reno 6 (Android 12):

![Screenshot_1](https://user-images.githubusercontent.com/40694158/178924160-7594dce4-a8b9-49d2-a234-999ca40388e0.jpg)
