### ISSUE TITLE
[RTL] Engines names and icons in the search engine selection setting should be aligned to the right

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-mobile/focus-android#5597]
## Steps to reproduce

1. Use Focus in an RTL language
2. Open settings
3. Search
4. Search engine

### Expected behavior

The list of engines should be aligned to the right. Both icons and text.

### Actual behavior

They're aligned to the left.

### Device information

* Android device: Samsung Galaxy S10e
* Focus version: 93.1.1

![Screenshot_20211013-131317_Firefox Focus](https://user-images.githubusercontent.com/18016656/137114793-864e9888-7883-4dcb-9dac-93153aae159a.jpg)

**Comment by lobontiumira** [comment]
Still reproducible on RC 95.1.0.

**Comment by lobontiumira** [comment]
Reproducible on Beta 97.0.0-beta.2 in Persian, with Samsung galaxy Note 8 (Android 9):

![Screenshot_۲۰۲۲۰۱۲۴-۰۴۴۳۵۲_Firefox Focus Beta](https://user-images.githubusercontent.com/40694158/150103096-c65d24a1-980f-4248-b591-3882a9e4f0dd.jpg)

**Comment by lobontiumira** [comment]
Reproducible on Beta 98.0.0-beta.1 with Samsung Galaxy Note 8 (Android 9):

![Screenshot_1](https://user-images.githubusercontent.com/40694158/153902864-7e1d821b-3e24-490c-84ad-74133a9dae1a.jpg)

**Comment by Mugurell** [comment]
Prepending the RTL mark - `\u200F` will force the LTR text to be displayed from as RTL.

**Comment by ItielMaN** [comment]
> Prepending the RTL mark - `\u200F` will force the LTR text to be displayed as RTL.

That't not just the text- the icons should also be on the right, so RLM wouldn't suffice here.

**Comment by lobontiumira** [comment]
Verified as fixed on the Focus Nightly 99.0a1 (build 360550514 with GV 99.0a1-20220223093800) with Oppo Find X3 Lite (Android 11), and Lenovo Tab M10 (Android 10):

![Screenshot_۲۰۲۲-۰۲-۲۴-۱۷-۲۴-۱۷-329](https://user-images.githubusercontent.com/40694158/155554626-f19fca86-ca4c-41b5-b694-6a9837c6ea77.jpeg)
![Screenshot_2022-02-24-17-26-41-82_11753d9bf2a67eec1c984b8ccb4d0671](https://user-images.githubusercontent.com/40694158/155554630-2fe12ea8-7a1c-4f65-b0d3-4975c453f9c3.jpg)
