### ISSUE TITLE
Implement a Nimbus Settings Screen in Focus Android

### ISSUE THREAD

**Issue by channingcarter** [mozilla-mobile/focus-android#5601]
The minimal requirement for settings to ship Nimbus (and start doing experiments) is to allow the user to globally opt-out of all experiments.

(follow designs based on Fenix https://www.figma.com/file/bZyKtDQECrnkiW6uhGxlwG/Nimbus?node-id=104%3A17984 ) 

This issue asks for a Nimbus SUMO page at the location:

https://support.mozilla.org/1/mobile/\(AppInfo.appVersion)/iOS/\(languageIdentifier)/studies

Notes for QA:

- Test if Studies state is updated properly 
- Tapping on Learn more text a SUMO page is open
- At this moment the list of studies is not loaded

**Comment by ionutbedregeanu** [comment]
> @brampitoyo Where should we place "Data collection" option?

https://github.com/mozilla-mobile/focus-android/pull/5661#issuecomment-946647470

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main from 11/5 with OnePlus 5T (Android 10):
* the Studies option is displayed in Data Choices section, below "Send usage data",
* the Studies are set to OFF by default,
* tapping on the toggle triggers the "Studies The application will quit to apply changes" prompt, with the CANCEL, and OK options,
* enabling/disabling the toggle, closes the app,
* tapping on the "Learn more" link, opens the https://support.mozilla.org/1/mobile/95.0/Android/en-US/studies in Portuguese?! - please see the last screenshot:

![studies](https://user-images.githubusercontent.com/40694158/140520790-ebafe45b-0d91-4650-bfee-a7410fe0de45.png)

@ionutbedregeanu please review and advise regarding the SUMO opened page.
Thanks!

**Comment by ionutbedregeanu** [comment]
@amedyne @channingcarter Seems that https://support.mozilla.org/1/mobile/\(AppInfo.appVersion)/Android/\(languageIdentifier)/studies doesn't exist. 
We are using the correct url? 
I noticed that in Fenix  is used https://support.mozilla.org/en-US/kb/how-opt-out-studies-firefox-android which is working.

**Comment by Amejia481** [comment]
@ionutbedregeanu  we recently got a patch on Fenix for fixing the link issue, you can take a look at https://github.com/mozilla-mobile/fenix/commit/1809bea49d8d1de61107de8f2273378b9ff779d1

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build from main with Samsung Galaxy Note 8 (Android 9) - the SUMO page from the "Studies" page is https://support.mozilla.org/en-US/kb/how-opt-out-studies-firefox-android:

![Screenshot_20211116-152921_Firefox Focus Nightly](https://user-images.githubusercontent.com/40694158/141995323-03824694-8e29-4090-9322-0db1a97c3e81.jpg)
