### ISSUE TITLE
Find in page search bar buttons not visible

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5618]
## Steps to reproduce
1. Switch to light-theme
2. Open a webpage
3. Open main menu>Find in page
4. Observe the buttons on the right: next/prev/close
5. Switch to the dark theme. Repeat the same steps.
### Expected behavior
next/prev/close buttons are visible.
### Actual behavior
next/prev/close buttons are not visible.
### Device information

* Android device: Pixel 2, Android 9
* Focus version: Nightly 10/14, v94 Beta-1

**Comment by channingcarter** [comment]
@Kate-Galetski Is this something you can work on?
