### ISSUE TITLE
The settings selected in Cookies and Site Data are not applied instantly

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5622]
## Steps to reproduce

1. With the default cookie setting (Block 3rd-party tracker cookies only) go to https://mozilla-mobile.github.io/testapp/ and tap on "Are cookies enabled? and "Are 3rd Party cookies enabled? from the Blocked Cookies Test area and observe the result.
2. Go to Settings -> Privacy & Security -> Block cookies and switch to "Yes please";
3. Go to https://mozilla-mobile.github.io/testapp/ and tap on "Are cookies enabled? from the Blocked Cookies Test area.
4. Go to Settings -> Privacy & Security -> Block cookies and switch to "Block 3rd-party cookies only";
5. Go to https://mozilla-mobile.github.io/testapp/ and tap on "Are 3rd Party cookies enabled? from the Blocked Cookies Test area.
### Expected behavior
After step 2 the whatismybrowser.com response should be "No".
After step 4 the whatismybrowser.com response should be "No".
### Actual behavior
The whatismybrowser.com response is "Yes" in both cases and several restarts of Focus are required in order for the newly applied setting to take effect.
### Device information

* Android device: Oppo Find X3 (Android 11)
* Focus version: 94.0.0-Beta.1

**Comment by mcarare** [comment]
Still reproducible in 94.0.0-beta.2: https://github.com/mozilla-mobile/focus-android/issues/5335#issuecomment-947405418.

I am going to take a look also, maybe it's still a preference update problem, not a GV-related one.

**Comment by mcarare** [comment]
Added a fix: https://github.com/mozilla-mobile/focus-android/pull/5669.
