### ISSUE TITLE
[RTL] The urlbar background shifts when focused

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-mobile/focus-android#5627]
## Steps to reproduce

1.Use an RTL locale
2. Erase the session
3. Focus the urlbar
4. Observe the difference in the background

### Expected behavior
The background stays fixed, with a bit of padding in the right side of the placeholder (both when focused or not).

### Actual behavior

The background shifts a little to the right.

### Device information

* Android device: Samsung Galaxy S10e
* Focus version: 93.1.1

<img src = https://user-images.githubusercontent.com/18016656/137356876-8ea1c8fd-178d-4d3b-bb6c-4d5e7600b603.jpg width = 45%> <img src = https://user-images.githubusercontent.com/18016656/137356873-55dd6854-b0e9-437c-8e61-e64778f1fff7.jpg width = 45%>

**Comment by ItielMaN** [comment]
Still an issue.

**Comment by lobontiumira** [comment]
Reproducible on Beta 102.0.0-beta.2 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 103.0.0-beta.1 with Lenovo tablet (Android 10).

**Comment by lobontiumira** [comment]
Verified as fixed on the 105.0a1 Focus Nightly build 362191708, with GV 105.0a1-20220807070028, with the following devices:
* Lenovo Tab M10 (Android 10), 
* Samsung Galaxy Tab A6 (Android 5.1.1), and
* Oppo Reno 6 (Android 12):

https://user-images.githubusercontent.com/40694158/183439582-1dee28dd-4e74-4a11-b200-5c96abaf5e53.mp4
