### ISSUE TITLE
[A11y] Talkback reads content from other onboarding pages when swiping on the current page

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5631]
## Steps to reproduce
1. Install Firefox Focus and activate TalkBack.
2. Launch Firefox Focus.
3. Swipe right several times on the "Power up your privacy" tip page.
4. Notice that content from the next tip "Your search, your way" is announced.
5. Double tap "Next" button.
6. Swipe right or left several times on the "Your search, your way" tip page.
7. Notice that content from both the previous tip "Power up your privacy" and next tip "Add shortcuts to your home screen" is announced.

### Expected behavior
The Talkback announces only the content from the current page when swiping.

### Actual behavior
The Talkback jumps to previous and next pages and proceeds to announce the content after reading the content from the current page when swiping multiple times.

### Device information
* Android device: Huawei P9 Lite (Android 8).
* Focus version: Beta 94.0.0 (build 352862025 GV 94.0-20211005185813), latest Focus Nightly from 10/15 95.0 (Build #352880510) 95.0a1-20211007091917).

https://user-images.githubusercontent.com/89388888/137459297-939b50f7-0a98-4018-b135-6f610d74bf79.mp4

**Comment by lobontiumira** [comment]
Reproducible on Beta 96.0.0-beta.5 with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on the latest Focus Nightly 104.0a1 from 7/18 with Oppo Find X3 Lite (Android 11).

**Comment by lobontiumira** [comment]
Reproducible on the latest Focus Nightly 108.0a1 from 11/2 with Oppo Find X3 Lite (Android 11).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802585

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
