### ISSUE TITLE
Multiple search engines with the same string can be added

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5634]
## Steps to reproduce
1. Go to the three-dot menu -> Settings -> Search -> Search engine.
2. Tap on "+ Add another search engine".
3. Enter a name for the engine, and the string to use.
4. Tap on "SAVE".
5. Repeat steps 3 & 4 and create another search engine with a different name, but the same string to use from step 3.

### Expected behavior
The "An installed search engine is already using the same string" message should be displayed.

### Actual behavior
The search engine is added again.

### Device information
* Android device: all
* Focus version: Beta 94.0.0-beta.1, and the latest debug build from main from 10/15
* Please see #5317

**Comment by mcarare** [comment]
@lobontiumira This was the desired behaviour as decided following the discussions here: https://github.com/mozilla-mobile/focus-android/issues/5318#issuecomment-915724307.

**Comment by lobontiumira** [comment]
Oh, ok, thanks!
I'll close this ticket.
