### ISSUE TITLE
Migrate first run page telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5635]
Breakout from #5488.

> Question being answered by the data:

Is the onboarding of interest to the users?

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build from 11/26 (build 353301620 GV 96.0a1-20211125095031) with Google Pixel (Android 10):

* page_displayed:
```
{
          "timestamp": 4726,
          "category": "onboarding",
          "name": "page_displayed",
          "extra": {
            "current_item": "0"
          }
        }
```
* next_button_tapped:
```
 {
          "timestamp": 4729,
          "category": "onboarding",
          "name": "next_button_tapped",
          "extra": {
            "current_item": "2"
          }
        }
```
* finish_button_tapped:
```
{
          "timestamp": 6957,
          "category": "onboarding",
          "name": "finish_button_tapped",
          "extra": {
            "current_item": "3"
          }
        }
```
* skip_button_tapped:
```
{
          "timestamp": 1812,
          "category": "onboarding",
          "name": "skip_button_tapped",
          "extra": {
            "current_item": "0"
          }
        }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2111260001) for the first three events
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2111260002) for the last event
