### ISSUE TITLE
Migrate crash reporter telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5652]
Breakout from #5488.

> Question being answered by the data:

How are users interacting with the crash reporter?

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 95.0 (build 353091620 - GV 96.0a1-20211104094642) with OnePlus 5T (Android 10):
Glean ping to URL: /submit/org-mozilla-focus-nightly/events/1/7551a74b-7943-45a3-a778-8ac114c22b1c
```
 {
          "timestamp": 17067,
          "category": "crash_reporter",
          "name": "displayed"
        }
```
```
 {
          "timestamp": 24279,
          "category": "crash_reporter",
          "name": "close_report",
          "extra": {
            "submit_report": "true"
          }
        }
```

Glean dashboard
