### ISSUE TITLE
Migrate open with... telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5654]
Breakout from #5488.

> Question being answered by the data:

How often are users opening websites in other browsers?

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 95.0 (build 353050927 with GV 95.0a1-20211026090355) with Google Pixel (Android 10).
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-211101001)

I was able to trigger 2 events:
* open_with list_displayed:
```
{
          "timestamp": 3359,
          "category": "open_with",
          "name": "list_displayed",
          "extra": {
            "list_size": "3"
          }
        },
```
* open_with list_item_tapped:
```
   {
          "timestamp": 8219,
          "category": "open_with",
          "name": "list_item_tapped",
          "extra": {
            "package_name": "true"
          }
```

@mcarare I cannot trigger the "install_firefox" event. Could you please provide me some more details?
Thank you!
