### ISSUE TITLE
Implement awesomebar telemetry.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5662]
We should implement telemetry similar to the one in Fenix for awesomebar events:
https://github.com/mozilla-mobile/fenix/blob/7e12bd32387451f3eba8380df488ce4f0b0ffae4/app/metrics.yaml#L4828

Note that we do not have all suggestion providers in Focus (history/ bookmarks, etc.)

**Comment by lobontiumira** [comment]
Verified on the 11/29 Focus Nightly build with Google Pixel (Android 10), and these events were generated successfully:
* suggestion_tapped:
```
{
          "timestamp": 9437,
          "category": "search_suggestions",
          "name": "suggestion_tapped",
          "extra": {
            "engine_name": "Google"
          }
        }
```
* autocomplete_arrow_tapped:
```
{
          "timestamp": 17580,
          "category": "search_suggestions",
          "name": "autocomplete_arrow_tapped"
        }
```
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2111290001)

However, I was not able to trigger "search_tapped".
@mcarare please help with some more details.

**Comment by mcarare** [comment]
@lobontiumira "search_tapped" should be triggered when you tap the suggestion that is the same as the typed text (usually the first suggestion in list)
