### ISSUE TITLE
Fetch the list of active and completed studies

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#5668]
### Why/User Benefit/User Problem
Show the list of active studies

#### Notes for QA:
Active studies is always empty because we don't have active experiments 
Completed studies can't be displayed at this moment https://mozilla-hub.atlassian.net/browse/FNXV2-17071?focusedCommentId=447662

### What / Requirements
Follow designs based on Fenix https://www.figma.com/file/bZyKtDQECrnkiW6uhGxlwG/Nimbus?node-id=104%3A17984

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on the latest debug build from main 2021-11-05. The Studies section is present in Focus, but empty. I'll leave this issue open until the issues regarding the displaying of Studies are fixed at which point the issue will be retested.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9
![1636125484219](https://user-images.githubusercontent.com/50983519/140535192-6e44b01c-2014-40ee-b9b2-41c77684413e.JPEG)
![1636125484121](https://user-images.githubusercontent.com/50983519/140535197-7ddb5d3b-bf88-4e43-b19b-6f5cf63b9a28.JPEG)
)

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build from main )build 353221044 GV 96.0a1-20211117094929) with Sony Xperia Z5 Premium (Android 7.1.1).

![completed](https://user-images.githubusercontent.com/40694158/142385617-96f466c2-b3eb-43a9-ab38-ee6bb24d57bd.png)
