### ISSUE TITLE
NPE in "new URI(....)".

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#567]
Buddybuild detected a crash from XXX@XXX.com
`app/src/main/java/org/mozilla/focus/utils/UrlUtils.java` line `57`

```java

        return searchEngine.buildSearchUrl(searchTerm);
    }

    public static String stripUserInfo(String url) {
        try {
            URI uri = new URI(url); <-- CRASHED

            final String userInfo = uri.getUserInfo();
            if (userInfo == null) {
                return url;
            }
```

[View File](https://github.com/mozilla-mobile/focus-android/blob/661f69ef67548b9e51596226d5a30bc9c451fef4/app/src/main/java/org/mozilla/focus/utils/UrlUtils.java#L57) | [View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/eaa5036be8129494caeff75b3f315c63)

**Comment by ahunt** [comment]
We've got two variants of this (which I think is different java versions crashing in different parts of new URI, both being called from stipUserInfo).
