### ISSUE TITLE
The selected search engine cannot be removed

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5673]
## Steps to reproduce
1. Go to setting -> Search ->Search Engine;
2. Tap the 3 dot menu and try to remove the preferred search engine.
### Expected behavior
The preferred search engine should be selectable.
### Actual behavior
The preferred search engine cannot be selected and cannot be deleted.
### Device information

* Android device: Huawei MediaPad M3 (Android 7), Oppo Find X3 (Android 11)
* Focus version: 94.0.0-beta.2

https://user-images.githubusercontent.com/50983519/138119635-702f0764-9377-4110-b193-20ebd3918a02.mp4

**Comment by mcarare** [comment]
Looking at the code, this is the intended behavior, and in IMO it's fine as it is as it prevents accidentally deleting the engine you actually use. 
You can delete the default engine in Fenix, but it leads to us choosing another default, and that looks somewhat random for a user. 

Adding @brampitoyo for an evaluation here.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802017

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
