### ISSUE TITLE
Firefox focus cosmetic filtering

### ISSUE THREAD

**Issue by chris122380** [mozilla-mobile/focus-android#5674]
Already searched using different phrases and could not find this as being reported. 

### What is the user problem or growth opportunity you want to see solved? 
Ad blocking with Firefox focus does not do cosmetic filtering, leaving large amounts of white space.

### How do you know that this problem exists today? 
- https://github.com/webcompat/web-bugs/issues/90695
### Why is this important? 
- Important for visuality reasons and to make web pages easier to read.

### Who will benefit from it?
All users who use ad blocking

**Comment by pocmo** [comment]
CC @Amejia481 Was this ever discussed in tracking protection meetings / for desktop? I almost assume this is not really something that is being worked on since "visually blocking ads" is not really the goal of tracking protection, but maybe?

**Comment by Amejia481** [comment]
> CC @Amejia481 Was this ever discussed in tracking protection meetings / for desktop? I almost assume this is not really something that is being worked on since "visually blocking ads" is not really the goal of tracking protection, but maybe?

No that I'm aware of, I will further investigate with them.

**Comment by pocmo** [comment]
@amedyne We may want to move this out of the backlog. It's not actionable by the mobile team.

**Comment by Amejia481** [comment]
From the privacy team: 

> Changing the structure of the web page after blocking tracking scripts from loading will be more in the  "ad blocker" territory and this is not the intention, ad blocking is a side effect in some cases from using tracking protection no the goal.
