### ISSUE TITLE
Import SafeIntent (android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.facebook.*)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#569]
Buddybuild detected a crash from ????

[View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/c1081dc1669867e3428803e5b6331bfe)

**Comment by ahunt** [comment]
Another similar one:
https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/5481140ea4049128bcf8c9694f91baa8

**Comment by ahunt** [comment]
It looks like both of these need something like Fennec's SafeIntent, see e.g.:
https://bugzilla.mozilla.org/show_bug.cgi?id=1299939

**Comment by ahunt** [comment]
I filed this to look at writing a lint check to make sure we don't accidentally access Intents in an unsafe way anywhere:
https://bugzilla.mozilla.org/show_bug.cgi?id=1362561
