### ISSUE TITLE
The page menu bar does not stay stuck to the footer of the page if scrolling is performed at aliexpress.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#5701]
## Steps to reproduce
1. Access :https://mbest.aliexpress.com/m/promote.htm?tracelog=wwwhome2mobilesitehome&af=149794&cn=6814&cv=14000&dp=10250029fabdc1ecac64f83add408f&aff_fcid=88f1911029cd46fd9043ec513331ca39-1635213826814-09111-_ATQOXo&tt=CPS_NORMAL&aff_fsk=_ATQOXo&aff_platform=portals-tool&sk=_ATQOXo&aff_trace_key=88f1911029cd46fd9043ec513331ca39-1635213826814-09111-_ATQOXo&terminal_id=c0917bc71f624f1d88ad03009f41610d
2. Scroll the page
3. Observe the bottom menu navigation bar

### Expected behavior
The menu has a fixed position

### Actual behavior
The menu changes the position

### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
* Focus version: Firefox Focus 93.1.1(352731722 🦎93.0-202109027210923🦎)

**Notes:**

1. Attaching relevant screenshots:
![Screenshot_73](https://user-images.githubusercontent.com/75027050/138835692-7ce68ec2-8daa-4c64-848e-fab0e71cbc1b.png)
2. Might be related to : https://github.com/mozilla-mobile/focus-android/issues/5603

**Comment by leithouse** [comment]
This has been an issue for about a month now. What happens is that when Focus opens a page there is a location bar at the top of the screen, and then statically positioned content is rendered at the bottom of the page. However, when you start scrolling down, the location bar at the top goes away and the statically positioned content at the bottom of the page moves up the same number of pixels that were the height of the location bar. You can observe this on virtually any website.

**Comment by softvision-raul-bucata** [comment]
@LaurentiuApahideanSV Is it safe to mark duplicate issues that display the same behavior observed in https://github.com/mozilla-mobile/focus-android/issues/5705 for different domains? We have received a number of similar issues for different domains

**Comment by LaurentiuApahideanSV** [comment]
@softvision-raul-bucata Yes it is safe, but please mention all domains that display this behavior in https://github.com/mozilla-mobile/focus-android/issues/5705, once the issue is fixed we will test all domains for which this issue was encountered.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802658

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
