### ISSUE TITLE
Trashcan icon overlaps cookies preferences prompts on TikTok/Soundcloud websites

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5704]
## Steps to reproduce
1. Go to tiktok.com or soundcloud.com.
2. Notice the prompt regarding cookies preferences.

### Expected behavior
The options in the consent prompts are properly displayed.

### Actual behavior
The trash icon overlaps the prompts, which become un-scrollable and the options are not completely displayed.

Regression after #5452.

### Device information
* Android device: Huawei P9 Lite (Android 8).
* Focus version: Debug build from main 10/26 (95.0 build 11 GV - 95.0a1-20211023211445).

https://user-images.githubusercontent.com/89388888/138880554-ecee6e79-5315-408f-b983-e986840c75ce.mp4

https://user-images.githubusercontent.com/89388888/138880570-8776e371-4ba0-440a-9708-0939f87583b5.mp4

**Comment by lobontiumira** [comment]
This issue no longer reproduces due to the #5829 being fixed.
Verified on the latest Focus Nightly build from 11/24 with Google Pixel (Android 10).

![Untitled](https://user-images.githubusercontent.com/40694158/143223910-da2928cb-c136-4022-b6be-dedb45226cf3.png)
