### ISSUE TITLE
Bottom bar should remain displayed at all times when scrolling on different websites

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5705]
## Steps to reproduce
1. Go to soundcloud.com (or other websites e.g. youtube.com/tmall.com)
2. Play a soundtrack and scroll down on the page. (on youtube.com/tmall.com scroll the pages).
3. Notice the bottom bar.

### Expected behavior
The bottom bar should always remain displayed on the screen when scrolling, as it does on Fenix/Chrome.

### Actual behavior
On soundcloud.com, the bottom bar is partially dismissed when the dynamic toolbar and trash icon are displayed. (On Fenix/Chrome the bottom bar remains displayed at all times).

On youtube.com/tmall.com, the bottom bar is dismissed when the dynamic toolbar and trash icon are displayed. (The same behavior is present on Fenix. On Chrome, the bottom bar remains displayed at all times).

Regression after #5452.
Relates to issue https://github.com/mozilla-mobile/focus-android/issues/5456 which was updated and closed. This ticket was opened to follow up on the comment from the mentioned issue #5456.

### Device information
* Android device: Huawei P9 Lite  (Android 8).
* Focus version: Debug build from main 10/26 (95.0 build 11 GV - 95.0a1-20211023211445).

https://user-images.githubusercontent.com/89388888/138881289-827cc46e-fe7c-407a-ba81-1346ffd93197.mp4

https://user-images.githubusercontent.com/89388888/138892343-e01b15f5-1004-4d16-b4c9-790b478fcd4d.mp4

**Comment by delia-pop** [comment]
Tested with the latest debug build from main 11/29 and geckoview_example.apk with Huawei P9 Lite. The following were observed:
- On Focus, the bottom bar displays a flicker when scrolling on different websites (soundcloud.com/youtube.com/tmall.com) when the dynamic toolbar is animated. 

- On Chrome, the bottom bar remains displayed at all times.

- The improper flicker of the bottom bar when the dynamic toolbar is animated could also be reproduced with GVE, therefore this could be a browser issue.


https://user-images.githubusercontent.com/89388888/143857050-3f7aff24-ef6c-4664-8e5d-75cb740ca35b.mp4

https://user-images.githubusercontent.com/89388888/143857061-f236f500-8f84-4d98-9540-dfca8b62130c.mp4


https://user-images.githubusercontent.com/89388888/143857175-021a00cf-6ec5-47d1-9cc2-88c1123f2531.mp4

https://user-images.githubusercontent.com/89388888/143857185-105dba2b-4be2-45cb-a84d-5c30099f07af.mp4

**Comment by ionutbedregeanu** [comment]
Bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1654336
