### ISSUE TITLE
 Trashcan icon overlaps various prompts on soundcloud.com

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5706]
## Steps to reproduce
1. Go to soundcloud.com.
2. Tap on a soundtrack.
3. With the dynamic toolbar dismissed, tap on the icons displayed under the song details (Like icon, Comments icon, Repost icon).
4. Notice the prompt displayed.
5. Tap on the prompt.
6. Repeat step 3 with the dynamic toolbar displayed.
7. Notice the prompt displayed.

### Expected behavior
The prompts and and the "Download the SoundCloud App" option should be properly displayed when the trashcan icon is displayed.

### Actual behavior
After step 3, although the prompt is properly displayed initially, once tapped, the trash icon overlaps the prompt, which becomes un-scrollable and the "Download the SoundCloud App" option is cut off.
After step 6, since the trashcan icon is already invoked, it overlaps the prompt, which becomes un-scrollable and the "Download the SoundCloud App" option is cut off.

Regression after #5452.

### Device information
* Android device: Huawei P9 Lite  (Android 8).
* Focus version: Debug build from main 10/26 (95.0 build 11 GV - 95.0a1-20211023211445).

https://user-images.githubusercontent.com/89388888/138882102-6baf275e-7fac-4a0e-b96b-fbc8aebf6ce2.mp4

https://user-images.githubusercontent.com/89388888/138884617-07ce578d-ff5b-4959-b567-d8395e8094c8.mp4

**Comment by lobontiumira** [comment]
This is now fixed by #5829.
Verified on the latest Focus Nightly from 11/24 with Google Pixel (Android 10).
