### ISSUE TITLE
 Trashcan icon overlaps warning prompt on tiktok.com

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5707]
## Steps to reproduce
1. Go to tiktok.com.
2. Accept all cookies when the prompt is displayed.
3. When the "Get the full experience on the app" prompt is displayed, tap on "Log in".
4. Select "Continue with Instagram".
5. Notice the warning prompt.

### Expected behavior
The warning prompt and "Open TikTok" option should be properly displayed.

### Actual behavior
The trash icon overlaps the prompt, which becomes un-scrollable and the "Open TikTok" option is cut off.

Regression after #5452. 

### Device information
* Android device: Huawei P9 Lite  (Android 8).
* Focus version: Debug build from main 10/26 (95.0 build 11 GV  95.0a1-20211023211445).

https://user-images.githubusercontent.com/89388888/138890530-eaea7aee-2d70-43c5-86f2-d79f0beef7cb.mp4

**Comment by lobontiumira** [comment]
This is now fixed by #5829.
Verified on the latest Focus Nightly from 11/24 with Google Pixel (Android 10).
