### ISSUE TITLE
Consider avoiding string copy on substring for ~20% url matching performance improvement

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#571]
It turns out that Android Java does create a new String copy for String.substring():
http://androidxref.com/6.0.1_r10/xref/art/runtime/mirror/string-inl.h#188

I'd naively assumed that wasn't the case, and our UrlMatcher calls substring() a lot. We already wrap Java's String in FocusString to avoid copies when reversing Strings - we could consider avoiding String.substring() by storing our own String offsets in FocusString. (Note: Java 6 used offsets, Java 7 switched during a point release, based on reading https://dzone.com/articles/changes-stringsubstring-java-7 ).

Doing that leads to a ~20% performance improvement in UrlMatcher.matches(), based on my testing on an N6P with Android 7.1.2 (default blocklist settings, ie. ad/analytic/social trackers blocked).

Average time for matcher.matches:
before (copy on substring) = 1.19ms
after (offsets in FocusString) = 0.96ms

Note: I already have a local patch doing this, I just need to write some more tests to make sure FocusString really is bulletproof.

I don't think this is super important (we already are quite a bit faster than focus-iOS's matching algorithm), but the changes are fairly simple.

**Comment by ahunt** [comment]
I've pushed a copy of my branch which contains a (non-landable) measurement patch to ahunt/matcherperf-measurements.

**Comment by ahunt** [comment]
I noticed that the performance numbers were a lot worse than 1 month ago: it turns out we now use `testCoverageEnabled` true for our debug builds. If I remove that and enable proguard, the numbers are:
before (copy on substring) = 0.42ms
after (offsets in FocusString) = 0.26ms

**Comment by pocmo** [comment]
It's a bit strange that testCoverageEnabled does anything when we are not running tests but the app itself. I wonder if it's worth to create a separate flavor for this - but this is probably more annoying.
