### ISSUE TITLE
Lateral tapping outside the menu does not return to web page

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5720]
## Steps to reproduce
1. Open a webpage with links/linked images (i.e. https://en.wikipedia.org).
2. Long click on a link or a linked image.
3. Tap outside the menu.
4. Observe if the menu is dismissed.

### Expected behavior
Tapping anywhere outside the menu will dismiss it, the user is returned to web page.

### Actual behavior
Tapping outside the menu on the lateral left/right sides will not dismiss the menu. Please note that tapping above/below the menu works as expected, dismissing the menu.

### Device information
* Android device: Huawei P9 Lite (Android 8), Sony Xperia Z5 (Android 7). 
This issue was not reproduced on tablets.
* Focus version: RC 94.1.0 ( Build 352991926 GV 94.0-20211025220926)/Beta 94.0.0-beta.2.

https://user-images.githubusercontent.com/89388888/139081193-782434b3-ac43-4296-9901-fac5699e727d.mp4

**Comment by brampitoyo** [comment]
@mcarare @delia-pop I agree. Tapping on the horizontal sides of a context menu should dismiss it.

I also agree with Mihai. We should file a separate issue to limit the height of the context menu.

What are the top and bottom margin/padding values that we should use? According to [Material Design 3](https://m3.material.io/components/dialogs/guidelines):
> On small screens, dialogs scale vertically until reaching 48dp from the screen’s top and bottom edge

**Comment by delia-pop** [comment]
Tested on Beta 95.0.0-beta.1 build and latest debug build from main 11/04 with Huawei P9 Lite (Android 8)/Sony Xperia Z5 (Android 7)/OnePlus 6T (Android 9).

The issue is verified fixed on the debug build with OnePlus 6T (Android 9) on both Portrait and Landscape modes.
However, on Huawei P9 Lite (Android 8), horizontal typing is still not dismissing the context menus on Portrait mode. This might be device related, since on Sony Xperia Z5 (Android 7) the issue is not encountered.

Note that it is still present on the Beta 95.0.0-beta.1 build.

https://user-images.githubusercontent.com/89388888/140304179-1361f55c-3a82-4668-84ef-c6ebb688c728.mp4

https://user-images.githubusercontent.com/89388888/140304170-8e6a7867-0398-478a-be74-c40e013b5012.mp4

https://user-images.githubusercontent.com/89388888/140318591-84b5eda4-2983-45e7-9423-815e7f224f80.mp4

**Comment by delia-pop** [comment]
Please note that horizontal typing is still not dismissing the context menus on Portrait mode on the Beta 95.0.0-beta.5 (build 353202152 GV 95.0-20211114185943) with LG G7 fit (Android 8.1.0)/Huawei P9 Lite (Android 8).

**Comment by ionutbedregeanu** [comment]
@delia-pop Seems that the space between menu and screen margins is too small for some devices.

@jeffreygee To display a context menu Focus and Fenix are using the same component from android components project, fact which makes me put myself the next questions:

Should I update this component and some extra margins? But after that the dialog will not respect the figma design anymore. At this moment in Fenix this menu is not dismissible if we are tapping on left, right sides.

If I am adding an extra margin, this change should be reflected in both apps(Focus, Fenix)?
What's your suggestion?

**Comment by jeffreygee** [comment]
@ionutbedregeanu - let me check in quickly with our design systems team to see if they're addressing this in their new designs

**Comment by jeffreygee** [comment]
@ionutbedregeanu - I checked in with some folks on the design systems teams and they weren't aware of this either, so I put it on their radar as well. This should definitely be reflected in both apps (Focus, Fenix) so that it's a consistent experience throughout. So, as of right now, is the side dismissing fixed across everything except the portrait on Android 8? If that's the case, I think we should pause on updating for now and continue to sync up with the other teams before updating the component and make sure we keep it consistent with breakpoints/margins/etc across both apps so that we're not doubling the work. Happy to hear your thoughts as well though.

**Comment by ionutbedregeanu** [comment]
Sounds good to me. I will put this ticket on pause until further updates

**Comment by delia-pop** [comment]
This issue is no longer occurring on the 96.0.0-beta.1 (Build 353412232 GV 96.0-20211206194555) with Xiaomi Redmi Note 8T (Android 9).
Please note that the issue is Still Present on the RC 95.1.0 build.

**Comment by ionutbedregeanu** [comment]
@delia-pop still reproducible?

**Comment by delia-pop** [comment]
Tested with Google Pixel 6 (Android 12) on the latest RC 101.1.1 and Beta 102. Beta 1. I cannot reproduce this issue anymore.
