### ISSUE TITLE
[L10N] Some options are not translated in Russian

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5726]
## Steps to reproduce
1. Set the device's language to Russian.
2. Observe the pro tips from the homescreen.
3. Go Settings - General, and observe the Theme section.
4. Go to Settings - Advanced, and observe the "Open links in apps".

### Expected behavior
The pro tips, the theme section, and the "Open links in apps" option are translated in Russian.

### Actual behavior
The pro tips, the theme section, and the "Open links in apps" option are not translated in Russian.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1)
* Focus version: 94.1.0, Beta 94.0.0-beta.2
![russian](https://user-images.githubusercontent.com/40694158/139248001-c511c0e2-3778-4f90-a0af-72f49a547216.png)

**Comment by Delphine** [comment]
I think we're blocked on import because of an error at this time: #5836
Once I can fix it, and the l10n import happens, this should be fixed.
Thanks!

**Comment by lobontiumira** [comment]
Hi @Delphine!
The translations are imported: the pro tips, themes, and Advanced options are translated.
Tested on RC 95.2.0, with Sony Xperia Z5 Premium (Android 7.1.1)
However, "Developer tools" title is spaced a bit too much:

![Screenshot_1](https://user-images.githubusercontent.com/40694158/147664646-ccf2140d-da4a-400d-bad7-40731ecdccc3.jpg)

* Not reproducible on Google Pixel (Android 10)
