### ISSUE TITLE
Enable and enforce pmd

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#573]
pmd is another static analysis tool:

- [x] Enable pmd in local gradle builds
- [ ] Decide which rulesets are good to use
- [ ] Fix existing issues
- [x] Fail builds when pmd failures are found, and enable in buddybuild

It seems pmd is less immediately useful than findbugs and infer, but it can help enforce a consistent coding style.

PMD rules that we should look at to decide what's worth enabling:
http://pmd.sourceforge.net/pmd-4.3.0/rules/index.html

**Comment by pocmo** [comment]
PMD is running on taskcluster and via sputnik. Closing this.
