### ISSUE TITLE
Add option to close tabs selectively.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5741]
### Why/User Benefit/User Problem

Users do not have the option to close just one or more, not all opened tabs.

### What / Requirements

Add a close button to items in the session list.

### Acceptance Criteria (how do I know when I’m done?)

Users have the option to close tabs selectively.

P.S.: This request was also encountered in play store reviews.

**Comment by OysterP** [comment]
Already raised under #5445

**Comment by kelimuttu** [comment]
We've seen a request to have this feature from the [Google Play Store](https://play.google.com/store/apps/details?id=org.mozilla.focus&reviewId=gp:AOqpTOF8Wl5M-rLQ1uCttb8G0E79btdR0BvyDbWbYv72dJJDarqJNMWOSyrSl6Lm3HLHYVagclUnr_t3qNROtFU).

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build from 12/8, and on Beta 96.0.0-beta.1 with multiple devices:
* Sony Xperia Z5 Premium (Android 7.1.1),
* Samsung Galaxy Tab A6 (Android 5.1.1),
* Xiaomi mi4i (Android 5.0.2),
* Google Pixel (Android 10),
* Lenovo tablet M10 (Android 10).

The tabs can be closed in any order. If the user selects to close the active tab, the next teb under it is loading and displayed.
Switching from portrait to landscape and viceversa while the tabs list is displayed, keeps the tabs list displayed, does not dismiss it.

![5741 landscape](https://user-images.githubusercontent.com/40694158/145197339-6bcbb8ba-e87b-457b-abdf-5f2e621edecd.png)

![5741 portrait](https://user-images.githubusercontent.com/40694158/145197384-60673545-b206-443a-812e-169268d7daec.png)
