### ISSUE TITLE
Revisit Focus notification

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5742]
Coming from using private browsing on Fenix, I would have expected to have the option to close the browser using the notification. The current notification does not offer this, and it is also un-removable.

Maybe we should revisit this behavior, as it has also been reported by some users on play store reviews.

**Comment by brampitoyo** [comment]
@mcarare Correct me if I’m wrong, but Focus currently shows a notification that allows you to “Erase browsing history” just by tapping the notification.

In fact, Focus gives you two additional action:
- Open the browser (without erasing history)
- Erase browsing history, then open the browser afterwards

Do users report wanting more functionality from our notification?

**Comment by mcarare** [comment]
The fact that tapping on the notification closes the browser or erases the history is not obvious to users. The users only see the action buttons. Add to that the fact that the behavior depends on the current active window, it seems pretty confusing.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802018

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
