### ISSUE TITLE
Consider adding setting for fixed toolbar.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5745]
Some reviews from play store are indicating users find toolbar hiding a not very desirable behavior. (Not sure why AFAIK previous Focus versions had this behavior)

We should consider adding a setting for having a fixed toolbar. 
This might be synchronized with other changes related to the FAB.

**Comment by jonalmeida** [comment]
> cc @channingcarter , @brampitoyo

The behaviour for the toolbar doesn't match that of Fenix for example. On Focus using reddit, I get stuck with the bottom end of the content hidden.

This is on nightly.

<img width="451" alt="Screen Shot 2021-11-01 at 11 22 03 AM" src="https://user-images.githubusercontent.com/1370580/139723428-463a63c5-db70-4690-aa08-a5684c9f303e.png">

**Comment by brampitoyo** [comment]
@mcarare @jonalmeida There are three separate issues here:

- FAB is blocking content
    - Solution: We’re planning to relocate the FAB into the sidebar, solving this issue.
- Bottom-end of the content is hidden
    - This seems to be a bug that occurs on other sites (e.g. Twitter) and unique to Focus. We should fix it.
- Toolbar hides when scrolling down, and cannot be fixed
    - Every other browser hides their toolbar when scrolling down; there’s no reason to us not to follow this behaviour.

**Comment by mcarare** [comment]
This issue was not meant to address the problems above. It was a question if we should add a setting for a fixed toolbar as Fenix has. (Customize -> Gestures -> Scroll to hide toolbar toogle)

**Comment by jonalmeida** [comment]
I'll file a separate issue for this dynamic toolbar bug because I don't see one already filed for it.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802019

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
