### ISSUE TITLE
Migrate etp exceptions telemetry 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5753]
Breakout from #5653

> Question being answered by the data:

How often are people customizing their privacy security settings?

**Comment by lobontiumira** [comment]
Verified as fixed on the Focus Nightly build 95.0 (build 353151018 GV 96.0a1-20211110092453) with Google Pixel (Android 10):
* opening the exception list:
```
{
          "timestamp": 21270,
          "category": "tracking_protection_exceptions",
          "name": "allow_list_opened"
        }
```
* removing an exception through the menu:
```
{
          "timestamp": 36625,
          "category": "tracking_protection_exceptions",
          "name": "selected_items_removed",
          "extra": {
            "list_size": "1"
          }

```
* removing an exceptions with "Remove all websites" button:
```
{
          "timestamp": 10465,
          "category": "tracking_protection_exceptions",
          "name": "allow_list_cleared",
          "extra": {
            "list_size": "1"
          }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2111110004)
