### ISSUE TITLE
 "Trash" icon overlaps the "Send" button

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#5757]
## Steps to reproduce

1. Navigate to :https://pjp-povo-webfront.s3.ap-northeast-1.amazonaws.com/povoChat.html
2. Observe the "Send form" button

### Expected behavior
The button is visible

### Actual behavior
The button is overlapped by the "Trash" icon

### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
* Focus version: Firefox Focus 94.1.1(353012322 🦎94.0-20211028161635🦎)

**Notes:**
1. This is an issue specific to Firefox Focus
2. See also : https://github.com/mozilla-mobile/focus-android/issues/5452
3. As reported here : https://github.com/webcompat/web-bugs/issues/92057

**Comment by lobontiumira** [comment]
Tested today on the latest Focus Nightly build 95.0 (353271124 with GV 96.0a1-20211122093912) with Google Pixel (Android 10) with the new implementation of the trashcan, and the "Next" button from the bottom of the page isn't displayed at all on Focus:

![1a1a](https://user-images.githubusercontent.com/40694158/143031936-add640ff-95b8-43f2-8e9e-97a08d501f79.png)

**Comment by ionutbedregeanu** [comment]
This can't be reproduced anymore since the 'trash' button was relocated

**Comment by Guest126** [comment]
@lobontiumira This should be opened as a new issue. Could you please?

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the 12/29 Focus Nightly, nor on Beta 96.0.0-beta.5.
Tested with Google Pixel (Android 10).

@Guest126 the relocated trashcan will be soon in the RC Focus build.

**Comment by Guest126** [comment]
@lobontiumira Thank you for your check.
