### ISSUE TITLE
Crash in [@ android.content.res.Resources$NotFoundException: at android.content.res.Resources.loadDrawableForCookie(Resources.java)]

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5762]
## Steps to reproduce

Open Focus. Rotate screen. Crashes

### Device information

* Android device:  < 24
* Focus version:  94.1.1

Crash report: https://crash-stats.mozilla.org/report/index/d8338d68-24de-4830-9fdc-781670211103

**Comment by lobontiumira** [comment]
I was able to reproduce it with Beta 95.0.0-beta.1 build with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by mcarare** [comment]
The crash is caused by the invalid <gradient> tag in the vector drawable.

**Comment by mcarare** [comment]
This can be tested on latest main. The fix will be uplifted to 95 after the QA check (Will be in Beta 95.0.0-beta.2 probably)

**Comment by pocmo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1739037

**Comment by mcarare** [comment]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1739037

Yes, That is where I opened this from. I will add a comment there once QA tests this.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 11/3 (build 11 GV 96.0a1-20211102094141) with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by rvandermeulen** [comment]
Please backport to the v94 branch as well so we can get it in a dot release.

**Comment by lobontiumira** [comment]
Verified as fixed on Beta 95.0.0-beta.3 with Samsung Galaxy Tab A6 (Android 5.1.1), and Xiaomi mi4i (Android 5.0.2).

**Comment by lobontiumira** [comment]
Verified as fixed on RC 94.1.2 too, with Samsung Galaxy Tab A6 (Android 5.1.1), and Xiaomi mi4i (Android 5.0.2).
