### ISSUE TITLE
Update the screenshot from the Help SUMO page

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5763]
## Steps to reproduce
1. Install any version of Focus (Nightly, Beta 95.0.0-beta.1, or RC 94.1.1).
2. From the homescreen's three-dot menu, select Help and observe the screenshot of the Focus homescreen.

### Expected behavior
The screenshot of the homescreen is updated with the new UI.

### Actual behavior
The screenshot is not updated.

### Device information
* Android device: all
* Focus version: 11/2 Focus Nightly, RC 94.1.1, Beta 95.0.0-beta.1

![Screenshot_2](https://user-images.githubusercontent.com/40694158/140027209-c7d91f6b-2316-478d-b23f-9421fbcd0f29.jpg)

**Comment by SeburoSUMO** [comment]
Please can you assign this to me?  I can rectify this issue myself in Kitsune.

**Comment by SeburoSUMO** [comment]
An edit has been made and is awaiting review.

**Comment by SeburoSUMO** [comment]
Edit has been reviewed and is now live.

**Comment by amedyne** [comment]
Closing per @SeburoSUMO 's confirmation.

**Comment by lobontiumira** [comment]
Verified as fixed on the 95.0 Focus Nightly build with Lenovo Tab M10 (Android 10).
