### ISSUE TITLE
Migrate the deprecated Kotlin Android Extensions compiler plugin

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5767]
Since Kotlin 1.4.20 `android-kotlin-extensions` is deprecated and it is to be removed ( [timeline](https://android-developers.googleblog.com/2020/11/the-future-of-kotlin-android-extensions.html) is after September 2021 Kotlin release).

Migration guide: https://developer.android.com/topic/libraries/view-binding/migration.

Note for QA:  A smoke test through the entire app is required to test this ticket, to check if all the screen are loaded properly, if all the buttons are working and the behaviour wasn't altered

**Comment by lobontiumira** [comment]
I have encountered this [crash](https://github.com/mozilla-mobile/focus-android/issues/6094) while accessing the Cookies options.
I'll remove the QAReady label for now.

**Comment by ionutbedregeanu** [comment]
> I have encountered this [crash](https://github.com/mozilla-mobile/focus-android/issues/6094) while accessing the Cookies options. I'll remove the QAReady label for now.

Fixed

**Comment by lobontiumira** [comment]
I'll close this ticket as verified as fixed on the 97.0 Focus Nightly (build 353551145 GV 97.0a1-20211220094500) with Xiaomi Mi8 Lite (Android 10), and Samsung Galaxy Note 8 (Android 9).
