### ISSUE TITLE
"Trash" icon overlaps "Next" button in "Report user" page on YouTube

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/focus-android#5774]
## Prerequisites
Signed into YouTube.

## Steps to reproduce
1. Navigate to https://m.youtube.com/channel/UCIZ_Rkmnzdu7Ow7dGK-go4g/about?openChannelReportingDialog=1#menu
2. Observe the bottom right side of the page.

### Expected behavior
No elements are overlapped.

### Actual behavior
The "Trash" icon overlaps "Next" button.

### Device information

* Android device: Google Pixel 5 (Android 11) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
* Focus version: Firefox Focus 94.1.1 (🦎 94.0-20211028161635)

## Notes
1. Regression after #5452.
2. The issue was previously reported here: https://github.com/webcompat/web-bugs/issues/92326
3. Screenshot attached.
![image](https://user-images.githubusercontent.com/12184325/140300558-873ff142-d333-4ee3-b041-292e93fcd716.png)

**Comment by lobontiumira** [comment]
Tested today on the latest Focus Nightly build 95.0 (353271124 with GV 96.0a1-20211122093912) with Google Pixel (Android 10) with the new implementation of the trashcan, and the "Next button from the bottom of the page isn't desplayed at all:

![yt](https://user-images.githubusercontent.com/40694158/143027151-87a17c52-1f07-4b56-bf20-064dc839d2dc.png)

**Comment by Mugurell** [comment]
This should be rechecked after the patch for https://github.com/mozilla-mobile/focus-android/issues/5884 lands.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly from 11/24 (build 353281028 GV 96.0a1-20211123094249) with Google Pixel (Android 10):

![Screenshot_20211124-171712](https://user-images.githubusercontent.com/40694158/143265224-69b81004-accb-4d87-833e-ddff340a3ba5.png)
