### ISSUE TITLE
Unsafe pages load with a white lock icon, on light theme on Android 5 devices

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5775]
## Steps to reproduce
1. Install Focus on an Android 5 device.
2. Load an unsafe page, like 
* https://itisatrap.org/firefox/its-a-trap.html
* https://itisatrap.org/firefox/its-an-attack.html
* https://itisatrap.org/firefox/unwanted.html
* https://itisatrap.org/firefox/harmful.html
3. Observe the lock icon from the URL bar.

### Expected behavior
The lock icon is black, and visible.

### Actual behavior
The lock icon is white and barely visible. 

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), Xiaomi mi4i (Android 5.0.2)
* Focus version: 95.0.0-beta.1
* Not reproducible on the debug build 11 with GV 96.0a1-20211102094141

![Screenshot_2](https://user-images.githubusercontent.com/40694158/140312815-b38b529c-f96d-4c65-902d-cf94017c5336.jpg)

**Comment by ionutbedregeanu** [comment]
Close this ticket since is a duplication of https://github.com/mozilla-mobile/focus-android/issues/6022
