### ISSUE TITLE
about:crashcontent doesn't work on the "child" page

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5778]
## Steps to reproduce
1. Open cnn.com in a tab.
2. Long-tap on a link, select to open in a new tab.
3. Switch to the new tab.
4. Insert about:crashcontent in the URL field.

### Expected behavior
The "Sorry. We're having problems with this tab.As a private browser, we never save and cannot restore this tab." messages are displayed."Send crash report to Mozilla" checkbox (checked by default)."Close tab" button. page is displayed.

![Screenshot_3](https://user-images.githubusercontent.com/40694158/140319954-d570205f-c1da-429a-993a-6bb142340ef2.jpg)
 
### Actual behavior
"Cannot complete request" page is displayed.
Focus doesn't crash. Tapping back, the page from step 2 reloads without issues.

If the second tab is opened from a different source, like Gmail, or from the "What's New" gift icon from settings, the issue doesn't reproduce anymore.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), Lenovo Tab M10 (Android 10)
* Focus version: 95.0.0-beta.1, RC 94.1.1, debug build 11 with GV 96.0a1-20211102094141

https://user-images.githubusercontent.com/40694158/140320391-519ca662-ddcd-41f8-82dc-65bd8416ece9.mp4

**Comment by lobontiumira** [comment]
Reproducible on RC 94.1.2 also, with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 96.0.0-beta.2 with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
Reproducible also on RC 95.2.0 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 96.0.0-beta.4 with Xiaomi Mi8 Lite (Android 10).

**Comment by iorgamgabriel** [comment]
I investigated the issue and I think it's a bug in GeckoView , I put there a ticket.
https://bugzilla.mozilla.org/show_bug.cgi?id=1747979

**Comment by delia-pop** [comment]
Reproducible on Beta 97.0.0-beta.1 with Google Pixel 6 (Android 12).

**Comment by delia-pop** [comment]
Reproducible on Beta 97.0.0-beta.2 with Google Pixel 6 (Android 12).

**Comment by delia-pop** [comment]
Reproducible in RC 96.2.0 with LG G7 fit (Android 8.1.0).

**Comment by delia-pop** [comment]
Reproducible on RC 96.3.0 with Google Pixel 6 (Android 12).

**Comment by lobontiumira** [comment]
Reproducible on Beta 98.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 99.0.0-beta.1 with Xiaomi mi4i (Android 5.0.2).

**Comment by lobontiumira** [comment]
Reproducible on Beta 100.0.0-beta.5 with HTC 10 (Android 8).

**Comment by delia-pop** [comment]
Reproducible on Focus RC 100.3.0 with Motorola Moto G30 (Android 11).

**Comment by lobontiumira** [comment]
Reproducible on RC 102.1.0, and Beta 102.0.0-beta.5 with all devices.

**Comment by lobontiumira** [comment]
Reproducible also on RC 103.2.0.

**Comment by delia-pop** [comment]
Also reproducible on RC 104.1.0.

**Comment by lobontiumira** [comment]
Reproducible on Beta 106.0b3 build, as well.

**Comment by lobontiumira** [comment]
Reproducible on Beta 107.0b3.
Reproducible with about:crashparent as well.

**Comment by lobontiumira** [comment]
I'll close this ticket, as is being tracked in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1747979.
