### ISSUE TITLE
Visual defect observed when opening the Tabs Manager 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5779]
## Steps to reproduce
1. Open several pages on Firefox Focus.
2. Tap on the Tabs manager.
3. Notice the shadow flicker displayed as the tabs manager opens.

### Expected behavior
The tab manager should open without any visual effects.

### Actual behavior
A shadow flicker can be observed as the tab manager opens, on both Light/Dark Theme.

Might relate #4878.
### Device information
* Android device: Huawei P9 Lite (Android 8), Samsung Galaxy Tab A6 (Android 5.1.1).
* Focus version: 95.0.0-beta.1, debug build from main 11/04 with GV 96.0a1-20211102094141

https://user-images.githubusercontent.com/89388888/140325381-e18c61fb-dc91-45d9-9492-ce43bd26681b.mp4

**Comment by ionutbedregeanu** [comment]
This can't be reproduced anymore since the button was relocated and the animation was removed
