### ISSUE TITLE
Execution failed for task ':app:buildBlocklists'. > Process 'command 'python'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by AnkS4** [mozilla-mobile/focus-android#578]
https://gist.github.com/AnkS4/8641b300ed525b7c671a115ab3e9fbe3

**Comment by Calfredop** [comment]
Hello,
Had the same issue, you need to use Python 2.

**Comment by ahunt** [comment]
Closing as duplicate of #215, I'm hopefully fixing that today by removing our python dependency for generating blocklists.

**Comment by ahunt** [comment]
And #215 just landed, so you should no longer need python for the main build
