### ISSUE TITLE
Telemetry: Tab count when app goes to the background

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#5785]
This ticket is to collect/record the number of tabs open when the app goes to the background.

**Comment by lobontiumira** [comment]
Verified as fixed on the Focus Nightly 95.0 (build 353201008 GV 96.0a1-20211115093917) with Google Pixel (Android 10):
Glean Ping to URL: /submit/org-mozilla-focus-nightly/events/1/930d235e-6cae-4341-9de9-6c123a85cdb9

```
{
          "timestamp": 0,
          "category": "tab_count",
          "name": "session_button_tapped",
          "extra": {
            "opened_tabs": "3"
          }
        },
        {
          "timestamp": 797,
          "category": "tab_count",
          "name": "session_list_item_tapped",
          "extra": {
            "opened_tabs": "3"
          }
        }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2111160002)
