### ISSUE TITLE
[Android 5] "Erase browsing history" option from the notification does nothing

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5796]
## Steps to reproduce
1. Install the latest debug build from main from 11/5 on an Android 5 tablet.
2. Open the app, open a page.
3. Scroll the notification, and tap on the Erase browsing history.

### Expected behavior
The app is closed, the notification is dismissed.

### Actual behavior
The app is closed, but the notification is still displayed.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1)
* Focus version: latest debug build from main from 11/5
* Not reproducible on Xiaomi mi4i (Android 5.0.2)

[logcat.txt](https://github.com/mozilla-mobile/focus-android/files/7486316/logcat.txt)

https://user-images.githubusercontent.com/40694158/140519093-69e512fe-28bf-4731-a27f-a5943cca635a.mp4

**Comment by pocmo** [comment]
Removing the app should have triggered `SessionNotificationService.onTaskRemoved()` which should stop the notification 🤔

**Comment by lobontiumira** [comment]
Reproducible also on RC 94.1.2.

**Comment by lobontiumira** [comment]
Reproducible on Beta 96.0.0-beta.1, and Nightly from 12/8 with the same tablet Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 97.0.0-beta.1, with the same tablet Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 100.0.0-beta.2 with Samsung Galaxy Tab A6 (Android 5.1.1).
Tapping on the "Erase browsing history" from the notification does nothing.

**Comment by lobontiumira** [comment]
Reproducible on Beta 100.0.0-beta.3 with Samsung Galaxy Tab A6 (Android 5.1.1).
Tapping on the "Erase browsing history" from the notification does nothing.
Tapping on "Erase and open" works as expected.

**Comment by lobontiumira** [comment]
Reproducible on Beta 102.0.0-beta.3 with Samsung Galaxy Tab A6 (Android 5.1.1).
Tapping on the "Erase browsing history" from the notification does nothing.
Tapping on "Erase and open" works as expected.

**Comment by Mugurell** [comment]
This seems related to https://github.com/mozilla-mobile/focus-android/issues/2951 and https://bugzilla.mozilla.org/show_bug.cgi?id=1773288

**Comment by lobontiumira** [comment]
This issue is reproducible on RC 103.2.0 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
This issue is reproducible on Beta 104.0b4 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Still reproducible on the latest Focus Nightly 107.0a1 from 10/6, and Beta 106.0b4 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Still reproducible on the latest Focus Nightly 108.0a1, and Beta 107.0b5 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802657

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
