### ISSUE TITLE
[L10N] Firefox Focus crashes when reaching the last carousel tip on Russian

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5813]
## Steps to reproduce
1. Change your device language to Russian.
2. Open Focus, scroll through the carousel tips, until the last one.
3. Observe that the application will crash after the 4th scroll without displaying the last tip.

### Expected behavior
The application should remain stable at all times.

### Actual behavior
The application crashes when reaching the last carousel tip. 

### Device information
* Android device: Huawei P8 Lite (Android 8), Huawei P20 (Android 10), Lenovo Tab M10 (Android 10).
* Focus version: 95.0.0-beta.3 (Build 353082029 GV 95.0-20211101163752)/latest Debug build from main 11/08.

[Crash log.txt](https://github.com/mozilla-mobile/focus-android/files/7497854/Crash.log.txt)

https://user-images.githubusercontent.com/89388888/140760512-46ca68c5-f84f-4603-b7b8-e3c7fee46623.mp4

**Comment by jonalmeida** [comment]
Sentry link: https://sentry.prod.mozaws.net/operations/focus-android-beta/issues/14710034/?query=is%3Aunresolved

**Comment by mcarare** [comment]
Added correction on Pontoon: https://pontoon.mozilla.org/ru/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?search=tip_request_desktop2&string=230886
cc: @Delphine

**Comment by pocmo** [comment]
I am not sure if we have setup the string uplift automation here. Maybe we should just nuke this string from the beta branch.

**Comment by jgtoriginal** [comment]
the error is on the translation file missing an `s` on it's dynamic content.

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/1785392/140936794-30a36738-7855-4389-a550-8d0d6f25a42e.png">

**Comment by Delphine** [comment]
I've approved the string in Pontoon (thanks mcarare!)
This should be fixed with latest Pontoon sync (so, within next 10min).

@pocmo: can you confirm if there are multiple betas for Focus Android, and that l10n udpates get in with each beta (like in Fenix?). I thought that was the case, but want to make sure I understand your comment, thanks!

**Comment by delia-pop** [comment]
Please note that the crash is also present on the Beta 95.0.0-beta.4 (Build 353140212 GV 95.0-20211109194756).

**Comment by jgtoriginal** [comment]
the crash will be present on any other instance of the app the consumes the same translation resources.
so as soon as we move away from the broken translation file, they should be all fixed by that Pontoon fix.

**Comment by pocmo** [comment]
> @pocmo: can you confirm if there are multiple betas for Focus Android, and that l10n udpates get in with each beta (like in Fenix?). I thought that was the case, but want to make sure I understand your comment, thanks!

There are Nightly, Beta and Release builds (and according branches). Currently translations only make it to those branches via the train model. We do not have an automated string uplift mechanism here yet - like we do for Fenix.

I'll file an issue for that now. But in the meantime we should manually uplift this String to unbreak the app.

**Comment by pocmo** [comment]
A patch is now available on the Beta branch.

**Comment by lobontiumira** [comment]
Verified as fixed on the Focus Nightly 95.0 (build 353260949 GV 96.0a1-20211120215911) with Samsung Galaxy Note 8 (Android 9), and Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
Verified as fixed also on RC 95.1.0 with Lenovo Tab M10 (Android 10), and LG G7 fit Android 8.1).
