### ISSUE TITLE
[android 5] The default search engine isn't greyed out when removing search engines

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5821]
## Steps to reproduce
1. On an Android 5 device, install Focus.
2. Go to Settings - Search - three dot menu - select Remove.
3. Select a search engine to remove, and observe the other search engine, especially the default one.

### Expected behavior
The default search engine is greyed out, and cannot be selected.

### Actual behavior
The default search engine is not greyed out.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), Xiaomi mi4i (Android 5.0.2)
* Focus version: RC 94.1.2, Beta 95.0.0-beta.3
* Not reproducible on LEnovo M10 (Android 10), Oppo Find X3 Neo (Android 11), nor Huawei P9 Lite (Android 8).

![Screenshot_2](https://user-images.githubusercontent.com/40694158/140895298-2b6e49b9-b076-475a-a80d-0a04e5de2f15.jpg)

**Comment by lobontiumira** [comment]
Reproducible on Beta 95.0.0-beta 5 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 96.0.0-beta 1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 98.0.0-beta 1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 98.0.0-beta 1 with Xiomi mi4i (Android 5.0.2).

**Comment by lobontiumira** [comment]
Reproducible on the latest builds (Nightly 102.0a1 from 5/25, RC 101.1.0, and Beta 101.0.0-beta.6) with Xiaomi mi4i (Android 5.0.2).

**Comment by lobontiumira** [comment]
The issue is still reproducible on the latest Focus Nightly 107.0a1 from 10/6, and Beta 106.0b4 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
The issue is still reproducible on the latest Focus Beta 108.0b3 with Xiaomi mi4i (Android 5.0.2).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802656

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
