### ISSUE TITLE
A desktop mode page shortcut on the app's homescreen, doesn't open in desktop mode

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5822]
## Steps to reproduce
1. Open a page.
2. From the three-dot menu, enable the Desktop site toggle.
3. Add the page as a shortcut.
4. Add the page to the homescreen.
5. Clear the history.
6. Tap on the shortcut, and observe if the page is still displayed in desktop mode.
7. Exit the app, and open the shortcut from the device's homescreen and observe if the page is still displayed in desktop mode.

### Expected behavior
After steps 6 & 7, the page is still displayed in desktop mode.

### Actual behavior
After step 6, the page is displayed in normal mode, and the Desktop site toggle is disabled.
After step 7, the page is displayed in desktop mode, and the Desktop site toggle is enabled.

### Device information
* Android device: all
* Focus version: RC 94.1.2, Beta 95.0.0-beta.3

**Comment by mcarare** [comment]
@lobontiumira I tested some websites(wikipedia, hotnews.ro) on the latest main and it works as expected. Can you retest this, and maybe mention the page you have tested this? Thank you!

**Comment by lobontiumira** [comment]
@mcarare I've tested again on the latest debug build from main (GV 96.0a1-20211115093917) with Sony Xperia Z5 Premium (Android 7.1.1), and I was able to reproduce the bug.
The page was the SUMO page, from the first pro tip - please see the short video below:


https://user-images.githubusercontent.com/40694158/141962255-84c8d94c-50b8-46c8-a89a-5bf39abe5b39.mp4

**Comment by mcarare** [comment]
Sorry, I did not notice you are referring to home screen shortcuts. Thank you for the video!
AFAIK those are not intended to be opened in desktop mode, just as the top sites in Fenix do not open in desktop mode. 
IMO this works as expected.

**Comment by mcarare** [comment]
Leaving this open for UX to weigh in. IMO we should keep the same behavior as Fenix has. 

cc: @jeffreygee

**Comment by jeffreygee** [comment]
> Leaving this open for UX to weigh in. IMO we should keep the same behavior as Fenix has.
> 
> cc: @jeffreygee

Sorry, this ticket got buried in my inbox. I agree with @mcarare - let's keep this behavior consistent with Fenix and leave as is.

**Comment by mcarare** [comment]
Thank you for your input @jeffreygee!

Closing this as per the comment above.
