### ISSUE TITLE
The current debug build is displayed in the "Open in..."/Share list

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5824]
## Prerequisites
Make sure you have at least two Firefox Focus builds installed, from which one of the must be a debug build.

## Steps to reproduce
1. Install the latest debug build from main
2. Open a page, and from the three-dot menu select the "Open in..." option/Share.
3. Or tap on a link and select "Share link"
3. Observe the installed apps displayed in the "Open in..."/Share/"Share link" dialogue.

### Expected behavior
As per discussed in https://github.com/mozilla-mobile/focus-android/issues/5632, the "Open in..." dialogue should display the installed browsers, without the current build.

### Actual behavior
On both browser page and custom tab opened from de debug build, the "Open in..." dialogue displays the debug build itself. This issue is not encountered on other builds (verified with Beta 95.0.0-beta.1, Beta 95.0.0-beta.3, RC 94.1.2) where the current build is not listed.

Both debug build and RC build display the current build in the Share/"Share link" dialogue.

### Device information
* Android device: all
* Focus version: Latest debug build from main 11/09./RC 94.1.2.

![Screenshot_20211109-115234](https://user-images.githubusercontent.com/89388888/140929312-72c87335-7acf-41b3-9df5-86684f97b35f.jpg)

**Comment by lobontiumira** [comment]
Reproducible with Samsung Galaxy Tab A6 (Android 5.1.1) on RC 94.1.2 too.

**Comment by lobontiumira** [comment]
Reproducible on RC 94.1.2 also, with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
This is partially fixed on the latest debug build from main (GV 96.0a1-20211115093917).
Tested with Google Pixel (Android 10), Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
Using the "Open in..." option doesn't display the current build, but sharing the page displays it:

![5824](https://user-images.githubusercontent.com/40694158/141960827-6771f206-7be7-4910-9f2d-2f519250b5ce.png)

@mcarare I'll remove the QAReady label for now, and leave this ticket opened.

**Comment by mcarare** [comment]
@lobontiumira I did not notice the adding of the share issue to this thread. I will add a fix for that too. In the future, it might be best to open new issues for different parts of the app. Thank you!

**Comment by mcarare** [comment]
Closing this. The issue with the share dialogue will be tracked in https://github.com/mozilla-mobile/focus-android/issues/5881.
