### ISSUE TITLE
Implement new design for Trash Icon and Tabs

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#5829]
This ticket is to implement the design changes for the Trash Icon location and the number of tabs indicator.

Figma designs here: https://www.figma.com/file/8Xyk89M3lk8n2c5aP79AHh/Delete-Action?node-id=2522%3A7249

This should help address and answer the following: 
https://github.com/mozilla-mobile/focus-android/issues/5774
https://github.com/mozilla-mobile/focus-android/issues/5757
https://github.com/mozilla-mobile/focus-android/issues/5707
https://github.com/mozilla-mobile/focus-android/issues/5706
https://github.com/mozilla-mobile/focus-android/issues/5704
https://github.com/mozilla-mobile/focus-android/issues/5466

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 95.0 (353271124 with GV 96.0a1-20211122093912), withthe following devices:
* Samsung Galaxy Tab A6 (Android 5.1.1),
* Samsung Galaxy Note 8 (Android 9),
* Google Pixel (Android 10), and
* Sony Xperia Z5 Premium (Android 7.1.1).

The trashcan, and the tabs counter are separated, both moved to the left/right of the search field:
![5829](https://user-images.githubusercontent.com/40694158/143006329-3bceb603-0d61-4b75-8502-d5d93df8e477.jpg)


I'll start verifying the above mentioned issues as well.

**Comment by lobontiumira** [comment]
Verified as implemented successfully on Beta 96.0.0-beta.1 as well.
Tested with:
* Sony Xperia Z5 Premium (Android 7.1.1),
* Google Pixel (Android 10),
* Samsung Galaxy Tab a6 (Android 5.1.1).
