### ISSUE TITLE
Add Autoplay in site permissions settings

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#5837]
### Why/User Benefit/User Problem
At this moment Focus blocks only audible videos without user interaction
### What / Requirements
Provide Autoplay  site permission settings for end users on Focus.

#### Figma resource(Fenix):
[[<image src="https://user-images.githubusercontent.com/1370580/141004458-838eccd7-c194-4463-bd79-33e59f87899f.png"](https://www.figma.com/file/RyIADLmC3B0BIS9jSiAti3/Settings?node-id=0%3A2687)](https://www.figma.com/file/RyIADLmC3B0BIS9jSiAti3/Settings?node-id=0%3A2687)

**Comment by lobontiumira** [comment]
Verified that the new options are in: Settings - Privacy & Security - Cookies and Site Data - Site permissions - Autoplay:
- Allow audio and video
- Block audio only (selected by default)
Recommended
- Block audio and video

![site permissions](https://user-images.githubusercontent.com/40694158/146789214-7ea79bb7-d5ad-40d0-84a0-c2b52a82d401.png)

However, selecting different options from Autoplay, and going to a site that contains media, crashes the app.
* https://crash-stats.mozilla.org/report/index/0f93f4a8-26c3-46da-8566-43e6c0211220
* https://crash-stats.mozilla.org/report/index/9370cec0-b50e-43f6-8032-d2e020211220


The crash has the same signature as the crash filed in ticket #6094.

**Comment by ionutbedregeanu** [comment]
https://github.com/mozilla-mobile/focus-android/issues/6094 fixed

**Comment by lobontiumira** [comment]
Verified on the Focus Nightly 97.0 (build 353560954 GV 97.0a1-20211220094500) with Xiaomi Mi8 Lite (Android 10), and Google Pixel (Android 10), that the app does not crash while switching from one option to another on Site Permissions settings page.
