### ISSUE TITLE
"Restore default search engines" option should be renamed to avoid confusion

### ISSUE THREAD

**Issue by kelimuttu** [mozilla-mobile/focus-android#5838]
## Steps to reproduce
* Go to Settings -> Search -> Search engine
* Chage your search engine to something else than the default
* Click the three dots menu
* Choose Restore default search engines

### Expected behavior
Default search engine changed to default

### Actual behavior
Nothing changed

### Device information

* Android device: Huawei P30 Pro, Android 10
* Focus version: 94.1.2

**Comment by mcarare** [comment]
AFAIK the option is supposed to restore the default search engine list. That is, removing any added custom engines and adding deleted search engines. It has nothing to do with changing the user-selected search engine. 

Maybe the option text adds to the confusion.

**Comment by kelimuttu** [comment]
That makes sense. I definitely didn't expect that. In that case, just a minor fix on the text should be sufficient.

**Comment by amedyne** [comment]
@jeffreygee Can you check if we need a new string for this?

**Comment by jeffreygee** [comment]
@amedyne - I'll ping the content team, thanks!

**Comment by jeffreygee** [comment]
@amedyne I discussed this with the UX team/content and this is going to be part of a larger UI/UX rework so let's pause on this for now.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802020

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
