### ISSUE TITLE
Migrate telemetry related to enabling/ disabling search suggestions. 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5840]
Migrate / Add telemetry for users enabling / disabling search suggestions.
The source of the change can be the prompt or the settings option in the "search" group.

**Comment by lobontiumira** [comment]
Verified on the 11/29 Focus Nightly build with Google Pixel (Android 10), and the following events were generated:
* disabled_from_panel:
```
{
          "timestamp": 3963,
          "category": "show_search_suggestions",
          "name": "disabled_from_panel"
        }
```
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2111290002)

* enabled_from_panel:
```
{
          "timestamp": 4400,
          "category": "show_search_suggestions",
          "name": "enabled_from_panel"
        }
```
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2111290003)


@mcarare the event "changed_from_settings" is not generating at all.

**Comment by mcarare** [comment]
@lobontiumira the event "changed_from_settings"  is generated when the setting is changed from settings -> search -> "get search suggestion" option.

**Comment by lobontiumira** [comment]
@mcarare I've retried today with Google Pixel (Android 10) on Focus Nightly 95.0 (build 353361543 GV 96.0a1-20211201050507), and again, the event was not generated after swithcing the toggle of "Get search suggestions" from Settings - Search.

**Comment by mcarare** [comment]
@lobontiumira Thanks for re-testing, I will put a patch for this soon.

**Comment by mcarare** [comment]
@lobontiumira This can be now tested on the latest main or on the next Nightly.

**Comment by lobontiumira** [comment]
Verified as fixed on the 12/3 Focus Nightly with Google Pixel (Android 10):
* disabling the search suggestions:
```
{
          "timestamp": 3964,
          "category": "show_search_suggestions",
          "name": "changed_from_settings",
          "extra": {
            "is_enabled": "false"
          }
```
* enabling the search suggestions:
```
{
          "timestamp": 5318,
          "category": "show_search_suggestions",
          "name": "changed_from_settings",
          "extra": {
            "is_enabled": "true"
          }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2112030001)
