### ISSUE TITLE
[Regression] 'Open in' no longer includes native third party apps

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#5847]
## Steps to reproduce
1. Have the Github app installed.
2. Set Focus as your default browser.
2. Open a GitHub link from Gmail.
3. Observe it open a custom tab.
4. Click the three for menu and select 'Open In'.
5. Observe the list of apps available

### Expected behavior
- One of those apps should be the GitHub app.
- Same behaviour as 92 and prior.

### Actual behavior
- Only browser apps are seen.

### Device information

* Android device: All devices
* Focus version: Focus Nightly 96 and Beta 95

**Comment by jonalmeida** [comment]
This is probably a regression from when we switched to the AC browsers list, we need to see what custom property Focus had to include supported third party apps in the list.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 95.0 build 353201117 with GV 96.0a1-20211115093917 with Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Note 8 (Android 9).
