### ISSUE TITLE
Support fullscreen videos

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#586]
STR:
1) Open vimeo.com
2) Start playing a video
3) Tap the fullscreen button

Expected: A fullscreen video
Actual: Nothing happens

I've seen this on other sites too.

**Comment by ahunt** [comment]
This would probably need support for WebChromeClient.onShowCustomView():
https://developer.android.com/reference/android/webkit/WebChromeClient.html#onShowCustomView(android.view.View,%20android.webkit.WebChromeClient.CustomViewCallback)

**Comment by ahunt** [comment]
TODO: investigate whether this affects all videos on the web.

**Comment by mcomella** [comment]
fwiw, YouTube goes fullscreen but I have seen this on other sites as well.

Also, some videos don't provide fullscreen controls (e.g. http://html5demos.com/video). Normally, you'd long-tap & select fullscreen to fullscreen but I don't remember seeing that option in focus.

**Comment by ahunt** [comment]
I don't see any fullscreen controls on youtube on my test devices (N6P/7.1.2 and N5/6.???),  I wonder what the difference there is.

**Comment by mcomella** [comment]
> I don't see any fullscreen button on youtube on my test devices

Actually, I don't see a fullscreen button any more either.

**Comment by pocmo** [comment]
> Full screen support
> 
> In order to support full screen — for video or other HTML content — you need to set a WebChromeClient and implement both onShowCustomView(View, WebChromeClient.CustomViewCallback) and onHideCustomView(). If the implementation of either of these two methods is missing then the web contents will not be allowed to enter full screen. Optionally you can implement getVideoLoadingProgressView() to customize the View displayed whilst a video is loading.

**Comment by pocmo** [comment]
@bbinto Do we need telemetry for this?

**Comment by bbinto** [comment]
You mean when somebody opens a video in fullscreen as supposed to in-page? Not necessarily

**Comment by brampitoyo** [comment]
I assume that we’ll use Android’s video player UI, which would already have a button you can tap to go fullscreen? (Firefox for Android seems to style its video player differently).

**Comment by pocmo** [comment]
> You mean when somebody opens a video in fullscreen as supposed to in-page? Not necessarily

Yeah, exactly."Enter full screen" and "Exit full screen" would be two possible probes.

> I assume that we’ll use Android’s video player UI, which would already have a button you can tap to go fullscreen? (Firefox for Android seems to style its video player differently).

Yeah, the video player UI is completely handled by the WebView. The "only" thing we need to add code-wise is the transition to "immersive mode" and hiding our browser chrome:
https://developer.android.com/training/system-ui/immersive.html

**Comment by pocmo** [comment]
This is implemented in the last beta builds. It works great with all sites except YouTube. When using YouTube after "enter full screen" immediatelly "exit full screen" is called. This isn't limited to Focus - I tried a separate app that uses WebView and has full screen implemented - it has the same issue. I'll file a bug against WebView and see if they know more. There are no issues when using Chrome directly.

**Comment by pocmo** [comment]
I'll close this one (the feature is implemented and in our Nightly builds) and open a new issue for YouTube.

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Video fullscreen issue](https://trello.com/c/IorItbq8/53-fix-video-fullscreen-issue)
