### ISSUE TITLE
42ms regression to cold start (MAIN & VIEW; Nimbus?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#5876]
In our dashboards, we see ~42ms regression to cold start in both MAIN and VIEW:

![image](https://user-images.githubusercontent.com/759372/141833317-c5168af7-17a3-44b7-9b58-e19b21d06124.png)

The regression starts around 11/3 and continues upward on 11/4 and 11/5. It peaks just afterwards, stabilizing to the 11/4 measurements.

**Comment by mcomella** [comment]
@mcarare @jonalmeida Do you know what might have caused this performance regression? Looking through the git log, it seems like it could be ac too.

**Comment by mcarare** [comment]
@mcomella Maybe adding Glean? 
https://github.com/mozilla-mobile/focus-android/blob/96812489c3687e97a0bfcf1016f9555b7cf4f252/app/src/main/java/org/mozilla/focus/Components.kt#L174
https://github.com/mozilla-mobile/focus-android/blob/5a990f5d90110be0d24710e216e82139a87430a2/app/src/main/java/org/mozilla/focus/FocusApplication.kt#L102

**Comment by jonalmeida** [comment]
Yes, Nimbus is my guess too. Previously, we were not initializing Nimbus with an HttpClient which it needed to fetch experiments. This was added in https://github.com/mozilla-mobile/focus-android/commit/5a990f5d90110be0d24710e216e82139a87430a2 which is what enabled that code path to start working.

**Comment by jonalmeida** [comment]
This seems to tie into the PR when we connected Nimbus to a UI that uses SharedPreferences: https://github.com/mozilla-mobile/focus-android/pull/5688

The PR landed on 11/3 as well.

**Comment by mcomella** [comment]
> This seems to tie into the PR when we connected Nimbus to a UI that uses SharedPreferences: #5688

Here's [the specific SharedPreferences read we suspect as part of the cause during triage](https://searchfox.org/mozilla-mobile/rev/cef4f8b426132c2298ff9466af09591a0440a12a/fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt ).

If the SharedPreferences read is the root cause, maybe we can pre-fetch SharedPreferences on a background thread as early as possible during start up and block for that read to complete when we need it for Nimbus?

@jhugman Is there anything we can do here to prevent the regression?

Triage: P1, especially since any improvements we make here can carry back into fenix.

**Comment by jhugman** [comment]
Looking at the linked PR, it seems that the `pref_key_studies` is only being read and connected to Nimbus startup. 

The source of truth of whether or not studies are enabled is stored by Nimbus as `nimbus.globalUserParticipation`. The `pref_key_studies` should _only_ be used as a convenient proxy.

I _think_ it should be safe to remove the `isExperimentationEnabled` read at startup without changing the meaning of the code. I _was_ worried that you weren't setting `globalUserParticipation` at all, but that seems to be ok.

The Focus team should change their studies screen to read `globalUserParticipation`. If concerned about reading `SharedPreferences` on the main thread for the studies screen, you might also be about reading `globalUserParticipation` from the main thread. It is safe to write from any thread.

**Comment by jonalmeida** [comment]
> The Focus team should change their studies screen to read `globalUserParticipation`. If concerned about reading `SharedPreferences` on the main thread for the studies screen, you might also be about reading `globalUserParticipation` from the main thread. It is safe to write from any thread.

Interesting! So for the UI, we can use `globalUserParticipation` instead of a separate pref from what I understand. 

Briefly looking into the A-S code, I see the [default participation is true](https://searchfox.org/mozilla-mobile/source/application-services/components/nimbus/src/enrollment.rs#19). This [differs](https://github.com/mozilla-mobile/focus-android/blob/main/app/src/main/java/org/mozilla/focus/utils/Settings.kt#L111) for Focus, so we would still need to use a pref to update the default unless we can change the default setting for Nimbus on startup separately from the `globalUserParticipation`, I think.

**Comment by jhugman** [comment]
So it looks like the Nimbus' idea of whether the user is taking part in studies already differs from the `SharedPreferences` version.

In that case, you'd need to do a one time synchronization to make sure that the two were the same, which is what the that first read at start up is doing. Hmm.

Given the timings we're worried about (SharedPrefs and Nimbus reading/writing to disk; Nimbus fetching from network; experiments only applied on next run), I don't think I'd be worried about doing all this reading from prefs and writing to nimbus off the main thread, perhaps on the same thread that the you've just constructed Nimbus with.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802655

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
