### ISSUE TITLE
Current app shows up in share via list app 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5881]
Breakout from https://github.com/mozilla-mobile/focus-android/issues/5824.

## Steps to reproduce
1. Install the latest debug build from main
2. Open a page, and from the three-dot menu select the Share option

3. Observe the installed apps displayed in the dialogue.

### Expected behavior
The current app should not be in the list,

### Actual behavior
The current app is in the list.

**Comment by lobontiumira** [comment]
Reproducible on Beta 96.0.0-beta.1 with Samsung Galaxy A6 (Android 5.1.1).

**Comment by delia-pop** [comment]
Reproducible on RC 96.1.0 with Google Pixel 6 (Android 12).

**Comment by delia-pop** [comment]
Verified as fixed on Firefox Focus Nightly 98.0 (Build 360330514 🦎 98.0a1-20220201093942) with Google Pixel 6 (Android 12).
The current app is no longer displayed in the share list. 
![Screenshot_20220202-154211](https://user-images.githubusercontent.com/89388888/152165112-181966fb-68f0-4049-b917-2341db9b4e24.png)
