### ISSUE TITLE
Support more shortcuts

### ISSUE THREAD

**Issue by kelimuttu** [mozilla-mobile/focus-android#5887]
### Why/User Benefit/User Problem
We've seen a few number of request to add more shortcuts after the 94 update: 
- [A Google user](https://play.google.com/store/apps/details?id=org.mozilla.focus&reviewId=gp:AOqpTOHetKrTp5AIAVZfK9nk_U8_FFJY11BOHlAcN_aSdyMnUfIaW87eiV9477lCaDZnVJUaNuONezID2SHCj1U): "Ridiculous we can only save 4 shortcuts. Can't close individual tabs. No quick access home button."
- [Aleksandar Skoco](https://play.google.com/store/apps/details?id=org.mozilla.focus&reviewId=gp:AOqpTOG7y3StBJcxTomPmPMEgL03LBdCktwTqeqeyRg2qlMcX-JsoM-q1GGqdw4Hu_33ibk6q5Ha01KpI9ebOTQ): "Browser is very good. My suggestion is to allow for 2 or more rows of shortcut sites because now we only can have 4 shortcuts, and there is really space for more"

### What / Requirements
Ability to add more than 4 shortcuts

### Acceptance Criteria (how do I know when I’m done?)
When I can add more than 4 shortcuts in the homepage

**Comment by iorgamgabriel** [comment]
@channingcarter @jeffreygee  should we support more that four shortcuts ? How many more ? How should look like ?

**Comment by channingcarter** [comment]
@iorgamgabriel no we should not support more than four shortcuts.

**Comment by ljader** [comment]
Hello Focus team ( CC @iorgamgabriel ) ,

I've just spend half hour searching and chasing why I can't add more than 4 shotcuts - so 2 questions:
1. Is this limit visible somewhere in the help/documentation? (to help others if they are also stuck)
2. What is the reasoning behing not adding more than 4 shortcuts?
In the above answer, IMHO no "actual" arguments were provided besides the general statement.
If it's the "design/look" decision, could you describe what is desired look and how i.e. 8 icons would impact it?
(especially on 6+ inch phones)

Thanks in advance for any response
Lukasz

**Comment by kelimuttu** [comment]
Thanks for your feedback, @ljader I just made a new revision to [this article](https://support.mozilla.org/en-US/kb/add-web-page-shortcuts-your-home-screen/discuss/10619#post-23390).

**Comment by ljader** [comment]
@kelimuttu thank you for taking the time and improving the docs.

FYI article you linked describes only the "Android homepage shortcuts" and not the "Focus homepage shortcuts" - mentioned here:
https://support.mozilla.org/en-US/kb/firefox-focus-main-menu

(IMO I get the impression the Firefox Focus is currently on the same path as Google Inbox once was for Gmail
- to be a source of ideas and eventually the bigger tool will win.
So I'm switching to main Firefox - thanks for all your effort.
Lukasz

**Comment by kelimuttu** [comment]
Ah, thanks for correcting. Didn't realized they're distinct functions.
