### ISSUE TITLE
Migrate report site issue telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5897]
Breakout from https://github.com/mozilla-mobile/focus-android/issues/5488.

> Question being answered by the data:

Are users frequently encountering bugs? On average how often are users reporting site issues?

**Comment by lobontiumira** [comment]
Verified as fixed on the 11/29 Focus Nightly (build 353331041 GV 96.0a1-20211125095031) with Google Pixel (Android 10):

```
"counter": {
          "power.total_cpu_time_ms": 49390,
          "browser.total_uri_count": 8,
          "tracking_protection.toolbar_shield_clicked": 1,
          "glean.validation.foreground_count": 2,
          "browser.report_site_issue_counter": 2
        }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2111290007)
