### ISSUE TITLE
The page menu bar does not stay stuck to the footer of the page if scrolling is performed at linkedin.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#5899]
## Preconditions
Test account created
The user is logged in

## Steps to reproduce

1. Navigate to: https://www.linkedin.com/feed/?trk=homepage-basic_signin-form_submit
2. Scroll the page
3. Observe the bottom menu navigation bar

### Expected behavior

The menu bar stays in a fixed position

### Actual behavior

The menu bar changes the position

### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
* Focus version: Firefox Focus 94.1.2 (353121860 🦎94.0-20211028161635🦎)

**Notes:**
1. The issue is not reproducible on the latest build of Firefox Nightly
2. The issue is not reproducible whilst browsing in "Private mode" using Firefox Nightly
3. Attaching relevant screenrecording:
![sroll focus linkd](https://user-images.githubusercontent.com/75027050/142215912-a2345974-4f50-4904-9e41-b2a06b5d1deb.gif)

**Comment by ionutbedregeanu** [comment]
@softvision-raul-bucata You can still reproduce it? Because I tried with the current version but I didn't succeed

**Comment by softvision-raul-bucata** [comment]
@ionutbedregeanu With the current version of Firefox Focus, the issue is still reproducible:
![repro focus](https://user-images.githubusercontent.com/75027050/143438602-9d1b2e7b-aedb-4461-ae5b-5d821e82f841.gif)


Tested with:
Browser / Version:  Firefox Focus 94.1.2 (353121860 🦎94.0-20211028161635🦎)/Firefox Nightly 96.0a1 (2015847723 -🦎96.0a1-20211123094249🦎)
Operating System: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)

**Comment by softvision-raul-bucata** [comment]
See also: https://github.com/mozilla-mobile/focus-android/issues/5823

**Comment by softvision-raul-bucata** [comment]
See also: https://github.com/mozilla-mobile/focus-android/issues/5705
