### ISSUE TITLE
Figure out what kind of Telemetry to use, and how

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#59]
In order to measure the success of this new product, we will need to understand how and when our users pickup the app.

High-level KPIs
---
To track our overall mobile core browser goals for 2017, success will be measured by

- Installs/downloads
- DAU/WAUS/MAU
- Engagement ratio (DAU/MAU)
- Retention 1D/7D/28D
- Store rating & reviews (Google Play Store)
- Compare existing KPIs of iOS version with Android

Event Telemetry
----

We believe by measuring interactions of our users with this new app, we will understand what features, settings and UI elements work best for users, and where we might be able to improve the product, to better help get the user where they want to browse to.

- Tun on/off settings (including turning off telemetry): Knowing what blocklists or settings the user turns on/off helps us understand if we might want to add or remove specific blocklists or settings, or that need further explanation or breakdown.
- Search engine selection: It’s good to understand if our users prefer/dislike a specific search engine, and this will allow us to potentially improve the integration with the specific search engine further
- Erase button:  we want to understand how often, and how many users hit the erase button and at what point of their journey, e.g. every time right before they close the app? 
- Pop-out / Intent actions: we want to understand how often and how many users want/need to pop-out to different apps or browsers, so it would be great to know how often the intent/sharing systems are being triggered (and potentially which apps).

All events should be available on a per unique user / total number of times basis.

We can then create cohort analysis and retention curves depending on what specific features or UI journeys users have taken. 

Mozilla always wants to give user choices and wants to understand how we can improve the product for _our_ users.

Read more about our data privacy and collection [here](https://support.mozilla.org/t5/Protect-your-privacy/Send-anonymous-usage-data-from-Firefox-on-mobile-devices/ta-p/37739).

**Comment by pocmo** [comment]
Closing this one. The actual implementation will be in #18 and #198.
