### ISSUE TITLE
Add version information in About page

### ISSUE THREAD

**Issue by lexcyn** [mozilla-mobile/focus-android#590]
I'm not sure if this fits with the type of project, but it would be beneficial to have a type of versioning information in the **_Help -> About_** screen to track progress and any new commits.

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add version number to product](https://trello.com/c/Cjao0VLj/43-add-version-number-to-product)

**Comment by brampitoyo** [comment]
This one can be simple. Show the version information below the logo, at the same text size as the rest of the body copy, at 30% opacity.

<img src="https://user-images.githubusercontent.com/51007/27161101-d466ec42-51c4-11e7-8ab0-4e18c6817726.png" width="360">

**Comment by liuche** [comment]
I'll take this one and work out any kinks in my Focus workflow!

**Comment by liuche** [comment]
<img width="323" alt="screenshot 2017-06-23 16 33 02" src="https://user-images.githubusercontent.com/1082253/27503643-b8568868-5832-11e7-97ff-9945ba6edb13.png">

**Comment by liuche** [comment]
@pocmo btw, unrelatedly, why did we decide to make the info pages in HTML rather than as android layouts? Is it to avoid having to maintain activity state in switching layouts, or having another Fragment? Or so that we could control the link color?

(@mcomella was also curious)

**Comment by pocmo** [comment]
@liuche Good question. I actually wanted to push for making them Android views in the next iteration - the HTML is clunky. The only reason why they are HTML is that we re-used them from the iOS version.
