### ISSUE TITLE
Intermittent UI test failure - blockOtherContentTrackersTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5900]
### Firebase Test Run:
Crashed 1x:
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8896965711582016141/executions/bs.869bd88519f671a/testcases/1
### Stacktrace:
[test logcat.txt](https://github.com/mozilla-mobile/focus-android/files/7555214/test.logcat.txt)
### Build:
Main 11/17

Looks similar to https://github.com/mozilla-mobile/focus-android/issues/5871

**Comment by AndiAJ** [comment]
Flaky 1x on 3/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6810144359267907816/executions/bs.681519c03e2ef99c/testcases/2)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a month
