### ISSUE TITLE
Migrate telemetry related to back button navigation

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5914]
Breakout from https://github.com/mozilla-mobile/focus-android/issues/5488.

> Question being answered by the data:

How are users navigating within / away from focus?

**Comment by lobontiumira** [comment]
Verified as fixed on the 11/29 Focus Nightly (build 353331041 GV 96.a01-20211125095031) with Google Pixel (Android 10):

```
{
          "timestamp": 399680,
          "category": "browser_menu",
          "name": "navigation_toolbar_action",
          "extra": {
            "item": "back"
          }
        }
```
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2111290007)
