### ISSUE TITLE
HTTPS turns into HTTP upon clicking a picture in Google search. (According to lock in the top-left corner)

### ISSUE THREAD

**Issue by Light2027** [mozilla-mobile/focus-android#5920]
## Steps to reproduce
Search for "Certificate test".
Open the same picture as in the Video.
HTTPS is now gone, according to the lock in the top-left corner.
This is not limited to that single image, this search term was just the quickest to replicate it.
I tried to look into it with Wireshark whether the secure connection was truly gone or not, but there was too much noise...

### Expected behavior
The HTTPS connection should remain and not switch to HTTP.

### Actual behavior
The HTTPS connection is gone and does not come back until the page is reloaded one way or another. (According to the lock in the top-left corner)

#### Videos
Watch out for the lock in the top-left corner.

##### Mobile
https://user-images.githubusercontent.com/43041394/142661138-e834bcc3-8fe3-4bfb-afc8-9243bdb18a19.mp4

##### Desktop (Regular Firefox)
https://user-images.githubusercontent.com/43041394/142661151-863bc528-3678-4e3b-b0c8-d476b37e51a8.mp4

### Device information

* Android device: Moto g 100
* Focus version: 94.1.2 (Build #353121859 (Gecko?) 94.0-20211028161635)
**Also happens in the Desktop version of the regular Firefox.**
* Device: Lenovo Legion Y720
* Mozilla Version: 94.0.1 (64-Bit)

That's it. I hope it will be helpful.

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus Nightly build with Xiaomi mi8 Lite (Android 10).

Closing.
