### ISSUE TITLE
Page content does not load on m.imgur.com 

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/focus-android#5929]
## Steps to reproduce
1. Navigate to https://m.imgur.com/
2. Observe the page.

### Expected behavior
Page content loads.

### Actual behavior
Page content does not load.

### Device information

* Android device: Google Pixel 5 (Android 11) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
* Focus version: Firefox Focus 94.1.2 (🦎 94.0-20211028161635)

### Notes:
1. The issue is not reproducible on Firefox Nightly.
2. The issue is still reproducible on Firefox Focus with ETP disabled.
3. This was previously reported here: https://github.com/webcompat/web-bugs/issues/94239
4. Screenshot attached.
![image](https://user-images.githubusercontent.com/12184325/142886852-a1e90ccb-4414-4332-bff1-157f9bde1fc4.png)

**Comment by ionutbedregeanu** [comment]
This issue can be reproduced also in Fenix and GeckoView Example but private mode
In Firefox Focus all tabs are open in private by default
I logged a bug in Bugzilla for that https://bugzilla.mozilla.org/show_bug.cgi?id=1743123

**Comment by softvision-raul-bucata** [comment]
@ionutbedregeanu After investigating more when the bug was reported, we've discovered that the issue is reproducible when browsing in private mode. We've filled https://bugzilla.mozilla.org/show_bug.cgi?id=1742344. I've closed your submitted report as a duplicate in favor of the above-mentioned report.
