### ISSUE TITLE
Add a UI setting for controlling Total cookie protection

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/focus-android#5938]
In desktop, we have this setting that activates the total cookie protection functionality
![image](https://user-images.githubusercontent.com/773158/143098050-fd4155f8-3ed5-45cd-a32d-2612868bb621.png)

In focus we can to do the same, and add a new entry to our cookie blocking UI
<img width="462" alt="image" src="https://user-images.githubusercontent.com/773158/143098308-a818e676-fc2d-426c-8a8e-bc489037c1bf.png">

When the new setting is selected we need to pass `ACCEPT_FIRST_PARTY_AND_ISOLATE_OTHERS` [here](https://github.com/mozilla-mobile/focus-android/blob/03a63e958d570640fb80d838a93c634b0ebd52c8/app/src/main/java/org/mozilla/focus/utils/Settings.kt#L68). This new setting should be our new default.

**Comment by ionutbedregeanu** [comment]
@Amejia481 @jeffreygee Should we display the same Heads up message as in desktop when this cookie option is selected?

**Comment by Amejia481** [comment]
I think the Heads up message is not related to the new cookie setting we could ignore it

**Comment by Amejia481** [comment]
In my opinion, we could use the same string as desktop and we could iterate later if we would like change it to something shorter.

**Comment by lobontiumira** [comment]
Verified that the "Block cross-site cookies" is displayed in the Settings - Privacy & Security - Cookies and Site Data, and is set by default.
Tested on the latest Focus Nightly build 95.0 (353361543 GV 96.0a1-20211201050507) with Google Pixel (Android 10).


![Screenshot_20211202-155446](https://user-images.githubusercontent.com/40694158/144442414-26d3d72e-5078-470f-9345-6be2f98fb511.png)
