### ISSUE TITLE
Black flicker displayed when changing the theme or language

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5970]
## Steps to reproduce
1. Go to Settings -> General.
2. Change the theme and observe the black flicker.
3. Change the language and observe the black flicker.

### Expected behavior
The transition is done smoothly, with no glitches. Fenix shows no flickering for the above scenario.

### Actual behavior
After selecting a different theme or language, a black flicker is displayed during the transition.

### Device information

* Android device: LG G7 fit (Android 8.1).
* Focus version: RC 95.1.0, latest debug build from main 12/02, 95.0.0-beta.5.

https://user-images.githubusercontent.com/89388888/144394150-341d7523-3e2b-461c-98b7-08ad5c6748cb.mp4

**Comment by delia-pop** [comment]
This issue also occurs on the 96.0.0-beta.1 (Build 353412232 GV 96.0-20211206194555) build with Xiaomi Redmi Note 8T (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on RC 96.1.0 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 97.0.0-beta.2 with Lenovo Tab M10 (Android 10).

**Comment by delia-pop** [comment]
Reproducible in RC 96.2.0 with LG G7 fit (Android 8.1.0).

**Comment by delia-pop** [comment]
Reproducible on Beta 97.0.0-beta.5 with LG G7 fit (Android 8.1.0).

**Comment by delia-pop** [comment]
Reproducible on RC 97.1.0 with Samsung Galaxy Note10 (Android 11).

**Comment by lobontiumira** [comment]
Reproducible on Beta 98.0.0-beta.1 with Samsung Galaxy Note 8 (Android 9), and Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on RC 97.1.1, and Beta 98.0.0-beta.2 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 100.0.0-beta.1 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 102.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 103.0.0-beta.1 with Lenovo tablet M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 104.0b1 with Lenovo tablet M10 (Android 10).

**Comment by lobontiumira** [comment]
@ionutbedregeanu this issue is not fixed yet.
Tested on the 106.0a1 Focus Nightly (build 362440511) with Lenovo tablet M10 (Android 10), and Samsung Galaxy Note 8 (Android 9):

https://user-images.githubusercontent.com/40694158/187851160-790b8aef-8cfa-4340-bc77-e88d8204b94a.mp4
