### ISSUE TITLE
The Homescreen background changes to system default after rotating the device, when other language than system default is selected.

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5971]
## Steps to reproduce
1. Go to Settings -> General.
2. From "Theme" change the theme to Dark.
3. From "Language" select any language other that the "System default".
3. Return to the homescreen.
4. Rotate the device to Landscape mode.
5. Observe that the theme changes.

### Expected behavior
The transition is done smoothly, the Dark theme is still displayed.

### Actual behavior
Rotating the device to Landscape mode when any language other than the "System default" is selected, causes the theme to incorrectly change from Dark to "Light" - like theme, with the white text color. 
The incorrect theme will continue to be displayed on both Landscape and Portrait mode until the user will navigate to another page/menu.

### Device information

*Android device: LG G7 fit (Android 8.1), Lenovo Tab M10 (Android 10), Sony Xperia Z5 Premium (Android 7.1.1).
*Focus version: RC 95.1.0, latest debug build from main 12/02.

https://user-images.githubusercontent.com/89388888/144399891-2f7ad36a-74d0-44e8-91a6-de79d897cf0d.mp4

**Comment by mcarare** [comment]
For QA: Please also test scenarios with successive locale changes after testing the main issue here. Thank you!

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Nightly build 95.0 (353401017 GV 96.0a1-20211203094816) with:
- Google Pixel (Android 10),
- Lenovo Tab M10 (Android 10),
- Samsung Galaxy Note 8 (Android 9),
- Xiaomi mi4i (Android 5.0.2).
