### ISSUE TITLE
Cannot load a different page on an already loaded tab on a Xiaomi device with Android 5

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5984]
## Steps to reproduce
1. Load wikipedia.org, or any other page.
2. Tap the toolbar, and type a different address, like cnn.com.

### Expected behavior
The page from step 2 loads replacing the page from step 1.

### Actual behavior
The page from step 1 is still displayed, on the top of the screen, leaving the bottom of the screen blank.

### Device information
* Android device: Xiaomi mi4i (Android 5.0.2)
* Focus version: 12/3 Focus Nightly
* Also reproducible on 12/3 Fenix Nightly
* Not reproducible on the GeckoView Example from 12/3
* Not reproducible on Samsung Galaxy Tab A6 (Android 5.1.1), or any other device

https://user-images.githubusercontent.com/40694158/144615489-900d9ced-b8e2-4ffa-8bf6-26b15b5d7d42.mp4

[logcat.txt](https://github.com/mozilla-mobile/focus-android/files/7650136/logcat.txt)

**Comment by Mugurell** [comment]
@delia-pop Can you please also add a logcat for accessing `about:crashparent` and then getting that ANR message?

**Comment by delia-pop** [comment]
@Mugurell I reproduced the issue on Focus Beta 99.0.0-beta.5 with Huawei MediaPad M2 (Android 5.1.1).
[Logcat_ANR_TabA5.txt](https://github.com/mozilla-mobile/focus-android/files/8351403/Logcat_ANR_TabA5.txt)

**Comment by delia-pop** [comment]
I can still reproduce this issue as described above with Huawei MediaPad M2 (Android 5.1.1) on Focus Beta 104.0b2.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802654

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
