### ISSUE TITLE
Implement Scrolling Screenshots For Android 12

### ISSUE THREAD

**Issue by Ep0chalypse** [mozilla-mobile/focus-android#5994]
Android 12 added a new api to enable apps to have scrolling screenshots. For example when viewing a webpage and you take a screenshot, there is a option that allows you to screenshot more of the webpage then what fits in the screen.

More info can be found here: 
[Announcement with images of what it looks like](https://android-developers.googleblog.com/2021/07/android-12-beta-3.html?m=1)
Api docs 
https://developer.android.com/reference/android/view/ScrollCaptureCallback

**Comment by Mugurell** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/20905

**Comment by seventhpaw** [comment]
Commenting to show support for the feature request.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802005

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
