### ISSUE TITLE
The "Help" button is not translated in Nederlands and Frysk

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5999]
## Steps to reproduce
1. Set the Focus language to Nederlands and Frysk
2. Go to Settings -> Mozilla;
### Expected behavior
The "Help" button should be translated to Nederlands and Frysk
### Actual behavior
The "Help" button is not translated for Nederlands and Frysk
### Device information

* Android device: all devices
* Focus version: RC 95.1.0
![Nederlands - Dutch](https://user-images.githubusercontent.com/50983519/144854633-4cdef060-165d-4239-a5f8-a611a60725d1.JPEG)

**Comment by lobontiumira** [comment]
Reproducible on RC 95.2.0 with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
This is still reproducible on RC 96.1.1 with HTC 10 (Android 8):

![help](https://user-images.githubusercontent.com/40694158/149087325-704df32d-def9-476e-bff5-6d1075854253.png)

**Comment by delia-pop** [comment]
This is reproducible in Beta 97.0.0-beta.2 with Google Pixel 6 (Android 12).
However, this is in accordance with https://pontoon.mozilla.org/nl/focus-for-android/all-resources/?search=help&string=223894.

**Comment by lobontiumira** [comment]
The "Help" option is not yet translated in Frisian in Pontoon:

![Screenshot_1](https://user-images.githubusercontent.com/40694158/180193295-df5d9b70-0dcb-4b1b-980c-ef378eb78d8d.jpg)

@flodolo please review.
Thank you!

**Comment by flodolo** [comment]
> @flodolo please review.

For the future, @bcolsson is the point of contact for mobile questions ;-)

This is INVALID, some language are similar to English (that's the case here), or can decide to use the English term.

**Comment by lobontiumira** [comment]
Thank you!
I'll close this ticket as invalid.
