### ISSUE TITLE
Ship beta via google play beta?

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#600]
- Some sites and forums are distributing beta or debug builds
-- Those builds don't provide updates
-- Those builds don't provide crash reports
-- Debug builds don't have telemetry

It looks like we might as well provide builds via the google play beta program:
https://android-developers.googleblog.com/2015/07/iterate-faster-on-google-play-with.html

Note: for closed betas you can add emails from a csv file, but we could also just go for an open beta?

**Comment by lexcyn** [comment]
This would be great. I am building every day over on XDA but this would be great to have auto updates.

**Comment by TruboXL** [comment]
I oppose the idea of opt-in beta.
Google Play only allows a limited number of testers to sign up for beta testing.
If you want to do beta, do it like the current Firefox Nightly or Firefox Beta for Android as a separate app/ID.

**Comment by pocmo** [comment]
We are doing this already. :)
