### ISSUE TITLE
Incorrect focus area for "Accept All Cookies" button

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/focus-android#6006]
## Steps to reproduce
1. Navigate to https://www.nature.com/articles/s41598-021-91992-9
2. After "Your Privacy" popup is displayed, scroll down the page.
3. Tap "Accept All Cookies" button.
4. Observe behavior.

### Expected behavior
The "Cookies" are accepted and the popup is dismissed.

### Actual behavior
The tapped area is above the button and the "Cookies" can't be accepted.

### Device information

* Android device: Google Pixel 5 (Android 11) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
* Focus version: Firefox Focus 95.1.0 (🦎 95.0-20211129150630)

### Notes
1. The issue is not reproducible on Firefox Nightly.
2. Gif attached.
![FocusAreaNotOnBtn](https://user-images.githubusercontent.com/12184325/145030429-f0f01a01-4c9f-4345-9623-8b92a132c587.gif)

### Workaround: 
Tapping bellow the button.

**Comment by iorgamgabriel** [comment]
https://user-images.githubusercontent.com/8118371/148051877-2b922835-f53d-46f1-a32c-47e50b72870f.mp4

**Comment by iorgamgabriel** [comment]
I can't reproduce this bug . 
Device information
Android device:Pixel 3XL , OnePlus 7t 
Focus version: Firefox Focus 97.0
@softvision-oana-arbuzov Please retest this bug with the latest app version .

**Comment by softvision-oana-arbuzov** [comment]
The issue no longer occurs, I can accept cookies (by tapping the "Accept All Cookies" button) now and proceed to the site.
 
**Tested with:**
Browser / Version: Firefox Focus Release 95.2.0 (🦎 95.0-20211215221728), Firefox Focus Nightly 97.0 (🦎 97.0a1-20220103092929) 
Operating System: Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
 
Closing the issue as Fixed.
