### ISSUE TITLE
Add "Learn more" link for HTTPS-Only mode setting

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#6008]
Currently the "Learn more" link for the "HTTPS-Only Mode" setting links to https://support.mozilla.org/en-US/kb/https-only-prefs - but this page is specifically about the desktop version of Firefox. We will need a Focus specific link, I guess.

**Comment by ionutbedregeanu** [comment]
@Kelimutu Do you know if already exists a link for this?

**Comment by kelimuttu** [comment]
I don't think we have one for Focus. But I'll ask our content manager to double-check.

**Comment by amedyne** [comment]
@abbyparise FYI. We need the "Learn More" link for this. Thanks!

**Comment by kelimuttu** [comment]
@abbyparise just confirmed that we don't have one for Focus. @amedyne can you create an article request for this one through Bugzilla? You can use [this link](https://bugzilla.mozilla.org/enter_bug.cgi?product=support.mozilla.org&component=Knowledge+Base+Content) to request

**Comment by amedyne** [comment]
Submitted Bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1749353 for this request.

**Comment by abbyparise** [comment]
SUMO link: https://support.mozilla.org/kb/https-only-prefs-focus
I'll get content updated and published by Wed Jan 19th.

**Comment by channingcarter** [comment]
@amedyne @ionutbedregeanu Here is the link provided by Abby. She will get the content up in the next few days so that it can be released in v97. 

https://support.mozilla.org/en-US/kb/https-only-prefs-focus

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug Nightly 98.0 (build 360261349 GV 98.0a1-20220125100058) with Lenovo tablet M10 (Android 10): the link is https://support.mozilla.org/en-US/kb/https-only-prefs-focus

![Screenshot_2022-01-26-13-49-08-856](https://user-images.githubusercontent.com/40694158/151158448-06e14141-bb2c-4770-bc57-718775f25db1.jpeg)
