### ISSUE TITLE
Figure out content for "HTTPS-Only mode" error page

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#6009]
We can't show all the text the desktop version has (See https://github.com/mozilla-mobile/android-components/issues/11306). And we want to enable the feature by default, which means we may want to use different text.

![](https://user-images.githubusercontent.com/89638/144647507-c83dca1e-11a8-46c4-b73c-259ff9584d17.png)

**Comment by pocmo** [comment]
Updated strings from Jeff, from #5988

> **[Settings screen]**
Header: HTTPS-only mode
Subheader: Automatically attempts to connect to sites using HTTPS for increased security. HTTPS connections provide a secure, encrypted connection to websites you visit. 
CTA: Learn more

> **[Error Page]**
Title: The site you requested does not support HTTPS
Body: By default, Firefox Focus attempts to connect using HTTPS for increased security. To change this setting or to learn more, go to Settings > Privacy & Security > Security. 
CTA: Continue to HTTP Site

**Comment by channingcarter** [comment]
@amedyne fyi
