### ISSUE TITLE
Investigate deep-linking from error page to settings

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#6010]
We would like to link from the "HTTPS-Only Mode" error page to our settings. Is this feasible? Does this require code in A-C?

**Comment by Mugurell** [comment]
We could create a new `DeeplinkIntentProcessor` and send a link from js.
Documentation for the structure of such intents used in js - https://developer.chrome.com/docs/multidevice/android/intents/

**Comment by iorgamgabriel** [comment]
Based on @jeffreygee input we will not add a button that will redirect the user to Settings Screen. The screen should remain the same . https://github.com/mozilla-mobile/focus-android/pull/6423
