### ISSUE TITLE
The ETP shield icon doesn't preserve its state after closing the app

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6020]
## Steps to reproduce
1. Open google.com, or instagram.com.
2. Sign in with valid credentials.
3. Turn the ETP off.
4. Close Focus.
5. Open focus, and open the same page from step 1.
6. Sign in with the same valid credentials.
7. Observe the ETP state.

### Expected behavior
The ETP shield is cut off. Tapping on the shield, displays the ETP panel with the ETP toggle disabled.

### Actual behavior
The ETP shield isn't cut off. Tapping on the shield, displays the ETP panel with the ETP toggle disabled.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1)
* Focus version: Beta 96.0.0-beta.1
* Not reproducible on 12/9 Nightly build, nor on RC 95.1.0

![etp off](https://user-images.githubusercontent.com/40694158/145371619-730dc756-be71-4cbb-9d97-a018e3f9770e.jpg)

**Comment by jonalmeida** [comment]
I recommend uplift this fix to beta if it's a small patch because it's unclear if your current session may have tracking protection enabled/disabled.

**Comment by lobontiumira** [comment]
This issue is still reproducible on all builds, with Lenovo Tab M10 (Android 10), and Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
I could no longer reproduce this issue on the latest Beta 100.0.0-beta.3 with Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Note 8 (Android 9).
