### ISSUE TITLE
The fingerprint verification window prevents the 3-dot menu to stay open on restore

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6023]
## Steps to reproduce
1. Create and enable fingerprint ID on your device.
2. Go to Settings -> Privacy & Security -> Switching Apps.
3. Switch the "Use fingerprint to unlock app" toggle ON.
4. Exit Settings menu and open a webpage.
5. Tap on the 3-dot menu to invoke menu contents.
6.  Minimize and restore the app.
7. Touch fingerprint sensor.
8. Observe if the 3-dot menu remains displayed.

### Expected behavior
After dismissing the fingerprint verification window with the fingerprint, the 3-dot menu stays open on restore.

### Actual behavior
After restoring the app, the webpage and the 3-dot menu can be seen for a slip second before the fingerprint verification window is invoked. Upon dismissing the window, the 3-dot menu is no longer displayed. 

### Device information
* Android device: Xiaomi Redmi Note 8T (Android 9).
* Focus version: 96.0.0-beta.1 (Build 353412232 GV 96.0-20211206194555), RC 95.1.0, latest debug build from main 12/09.

https://user-images.githubusercontent.com/89388888/145383997-d66aa272-5c7d-439e-b6a2-8389d8693530.mp4

**Comment by lobontiumira** [comment]
Reproducible on Beta 96.0.0-beta.2 with Google Pixel (Android 10).

**Comment by ionutbedregeanu** [comment]
In my opinion this is not necessarily a bug, is not something we really should restore. @jeffreygee What do you think?

**Comment by jeffreygee** [comment]
> In my opinion this is not necessarily a bug, is not something we really should restore. @jeffreygee What do you think?

I agree. It's not the smoothest transition, but it looks like it's just opening the last state/cached state of the app before switching but then triggering the fingerprint as expected. After you use the fingerprint, the menu goes away, right?

**Comment by ionutbedregeanu** [comment]
yep. I will close this ticket because  the 3-dot menu is not something we should necessarily restore
