### ISSUE TITLE
Tapping the trashcan, empties the toolbar, then closes the tab

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6024]
## Steps to reproduce
1. Open any page.
2. Tap on the trashcan, and observe the behaviour.

### Expected behavior
The tab closes immediately.

### Actual behavior
The URL address is deleted, the toolbar is empty, then the tab closes.
It is more visible on low-end devices.

### Device information
* Android device: Xiaomi mi4i (Android 5.0.2), Samsung Galaxy Tab A6 (Android 5.1.1), Lenovo Tab M10 (Android 10), Sony Xperia Z5 Premium (Android 7.1.1)
* Focus version: Beta 96.0.0-beta.1, Focus Nightly 95.0 (build 353421248 GV 96.0a1-20211204095400)

[logcat (2).txt](https://github.com/mozilla-mobile/focus-android/files/7684496/logcat.2.txt)

https://user-images.githubusercontent.com/40694158/145384482-8195516f-33d2-4cdc-b4a0-bd6254180647.mp4

**Comment by delia-pop** [comment]
Reproducible on Beta 97.0.0-beta.6 with Huawei MediaPad M2 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 102.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by ionutbedregeanu** [comment]
I made a pr for this, but the trackers icon still disappear before erase.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 106.0a1 from 9/12 with the following devices:
* Lenovo tab M10 (Android 10),
* HTC 10 (Android 8), and
* Google Pixel (Android 10).

https://user-images.githubusercontent.com/40694158/189612691-d784dbd0-e329-4658-be76-751ffb90c62b.mp4

**Comment by lobontiumira** [comment]
Verified as implemented also on Beta 106.0b1 build.
