### ISSUE TITLE
The biometric prompt description is barely visible

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6025]
## Steps to reproduce
1. Create and enable fingerprint ID on your device.
2. Go to Settings -> Privacy & Security -> Switching Apps.
3. Switch the "Use fingerprint to unlock app" toggle ON.
4. Exit Settings menu and open a webpage.
5. Minimize and restore the app.
6. Touch the fingerprint sensor.
7. Observe the fingerprint verification window.

### Expected behavior
The "Unlock Firefox Focus Beta - Touch the fingerprint sensor to continue" text description is properly displayed and visible.

### Actual behavior
The "Unlock Firefox Focus Beta - Touch the fingerprint sensor to continue" text description is barely visible.

### Device information
* Android device: all
* Focus version: 96.0.0-beta.1 (Build 353412232 GV 96.0-20211206194555), RC 95.1.0, latest debug build from main 12/09.

![21BB52EC-327A-479B-809C-CA6E943C1D1A](https://user-images.githubusercontent.com/89388888/145386578-bdade713-fbb8-44f2-9e9f-04528bd591cb.jpg)

**Comment by lobontiumira** [comment]
Verified as fixed on the 97.0 Focus Nightly 97.0 (build 353441046 GV 97.0a1-20211208095339) with Samsung Galaxy Note 8 (Android 9):

![Screenshot_3](https://user-images.githubusercontent.com/40694158/145548203-0c06639b-9c28-4c87-a6d2-b9ff639304d1.jpg)

**Comment by lobontiumira** [comment]
Verified as fixed on Beta 96.0.0-beta.2 with Google Pixel (Android 10).
