### ISSUE TITLE
Implement Storage Access API prompt

### ISSUE THREAD

**Issue by artines1** [mozilla-mobile/focus-android#6027]
### Why/User Benefit/User Problem

As Focus is going to support Total Cookie Protection (#5938), we should implement the Storage Access API prompt which allows users to make decisions regarding the storage access when websites use Storage Access API. Following is an example in the Firefox desktop.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/6202423/145404966-0e27f022-a68b-446d-a04a-918af3d45901.png">

This is important to Total Cookie Protection in terms of breakage mitigation because websites can use Storage Access API to get unpartitioned storage. But, Storage Access API rejects in Focus because the Storage Access API prompt is not currently implemented.

Note that Gecko has implemented a mechanism called `Auto Grant` which will automatically grant storage access under certain conditions. In this case, Focus can still get storage access even without the storage access prompt. However, `Auto Grant` doesn't always kick in and hence should not eliminate the need of implementing Storage Access API prompt.

### What / Requirements

Implement the Storage Access API prompt. 

### Acceptance Criteria (how do I know when I’m done?)

The Storage Access API prompt will be shown to users if the websites use Storage Access API to request storage access. And users should be able to use the prompt to decide if they want to grant the storage access or not.

**Comment by Amejia481** [comment]
Thanks for filing the ticket we are tracking the progress on https://github.com/mozilla-mobile/android-components/issues/10739 as the implementation should be done on the Android Components repository for the behavior be shared between Focus and Fenix.

**Comment by Amejia481** [comment]
@artines1 is there any website that you recommend for testing the prompt? I've tried https://senglehardt.com/test/dfpi/storage_access_api.html and I'm not able to see the prompt, I have clicked the `requestStorageAccess()` on all tabs
and all sections display "access granted" but none show the dialog.

**Comment by artines1** [comment]
Yeah, I think that's the best website we can use to test this. The reason why you didn't see the prompt is that the `Auto Grant` is working. You can disable `Auto Grant` by turning the pref `dom.storage_access.auto_grants` to false.

**Comment by Amejia481** [comment]
Unfortunately, I still see the same behavior after disabling  `dom.storage_access.auto_grants`. Additionally, I disabled  `dom.storage_access.auto_grants.delayed` without luck :( .

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/773158/145416317-5ee34f7a-6ef1-4066-9a33-72093fbec58e.png">

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/773158/145416600-df584290-946f-4e2a-9b62-97854adba6cf.png">

**Comment by artines1** [comment]
Did you clear the `Cross-site cookies` permission before you did the test? You can clear the permission by using the permission icon on the URL bar.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/6202423/145417737-7fe84ad0-a110-44e7-8c15-360b889775b9.png">

**Comment by Amejia481** [comment]
🎉  awesome now it's working. I didn't know that permission was persistent, I was thinking it will prompt every time the permission was requested. 

<img width="415" alt="image" src="https://user-images.githubusercontent.com/773158/145418487-1ef00a9f-477c-4e1d-bd20-5a5d098ed649.png">
