### ISSUE TITLE
Buttons are not functional on "Twitter is better on the app" popup

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/focus-android#6029]
## Steps to reproduce
1. Navigate to https://mobile.twitter.com/SciGuySpace/with_replies
2. After "Twitter is better on the app" popup is displayed, scroll down to reveal the available options.
3. Tap "Not now" button.
4. Observe behavior.

### Expected behavior
The popup is dismiss and the site can be browsed.

### Actual behavior
Nothing happens, the popup remains displayed.

### Device information

* Android device: Google Pixel 5 (Android 11) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
* Focus version: Firefox Focus 95.1.0 (🦎 95.0-20211129150630) 

### Note:
1. The same behavior is encountered for "Switch to the app" button.
2. The issue is not reproducible on Firefox Nightly.
3. The issue is still reproducible on Firefox Focus regardless of the ETP status.
4. This was previously reported here: https://github.com/webcompat/web-bugs/issues/96132
5. Gif attached.

![BtnNotFUnctional](https://user-images.githubusercontent.com/12184325/145430490-2c93b081-c7dd-4b5c-8d74-587aff1aadd3.gif)

**Comment by iorgamgabriel** [comment]
I can't reproduce this bug .
Device information
Android device:Pixel 3XL , OnePlus 7t
Focus version: Firefox Focus 97.0
@softvision-oana-arbuzov Please retest this bug with the latest app version .

**Comment by iorgamgabriel** [comment]
https://user-images.githubusercontent.com/8118371/148238787-3a235d1d-f3cb-4c58-932d-16b517002636.mp4

**Comment by softvision-oana-arbuzov** [comment]
The issue no longer occurs on my side either.

**Tested with:**
Browser / Version: Firefox Focus Release 95.2.0 (🦎 95.0-20211215221728), Firefox Focus Nightly 97.0 (🦎 97.0a1-20220104034109) 
Operating System: Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
