### ISSUE TITLE
Investigate custom tabs support

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#603]
This is a reminder bug to test that various apps can successfully open Focus Custom Tabs. Google's library tries to default to chrome except in very specific circumstances, so we need to make sure we fulfil those requirements if at all possible:
https://github.com/GoogleChrome/custom-tabs-client/blob/master/shared/src/main/java/org/chromium/customtabsclient/shared/CustomTabsHelper.java

**Comment by ahunt** [comment]
All tests performed with Focus set as the default browser:
- It looks like Google properties are correctly opening Focus custom tabs.
- Twitter does open Focus when "in app browser" is enabled, but not in custom tabs mode.

(Note: IIRC we're testing for the SESSION flag to determine whether we're opening a custom tab, that's not a hard spec but it's what the google custom tabs library does to denote a custom tab. Perhaps we have to test additional conditions?)

**Comment by pocmo** [comment]
> (Note: IIRC we're testing for the SESSION flag to determine whether we're opening a custom tab, that's not a hard spec but it's what the google custom tabs library does to denote a custom tab. Perhaps we have to test additional conditions?)

In this case it's actually twitter's fault. They are assuming only Chrome implements Custom Tabs and therefore other apps just get a normal VIEW intent. :(

**Comment by ahunt** [comment]
Closing since it looks like we support CT properly (and I'm happily using it for everything except twitter)!
