### ISSUE TITLE
Losing bottom of screen - #5339 is back

### ISSUE THREAD

**Issue by phil99** [mozilla-mobile/focus-android#6035]
The issue reported in #5339 has reappeared in Focus v.95.1.0
On some site pages the bottom of the screen is not displayed, and is not readable by scrolling.

Example site: 
https://magicseaweed.com/UK-Ireland-Surf-Chart/1/?type=pressure
Wind

Issue is replicable.

**Comment by Mugurell** [comment]
@phil99 Can you post a video of the issue you're seeing?

**Comment by phil99** [comment]
Hi Muggurell
I'm not sure I can do that (video), but there is nothing to see if I was able.

It is not possible to scroll down to see missing bottom of the page. The behaviour exhibited is exactly as in #5339.

**Comment by OysterP** [comment]
I'm experiencing something similar with pages that have bottom heavy overlays such as cookie concent, where either you can't get to the buttons at the bottom or if they are visible, any attempt to click button triggers  links further up (10-20mm).
Example below:
https://amp.theguardian.com/world/2021/dec/10/travellers-to-ireland-from-great-britain-must-take-covid-tests-for-five-days

**Comment by phil99** [comment]
Hi OysterP
Yes, now I've looked at your example I get the same result - I can't click on the Accept Cookies, Focus ignores it.

Can you see the scrolling scale (to move through the coming days) at the bottom of this weather page? I can just see the very top of it, but can't get to it.
https://magicseaweed.com/UK-Ireland-Surf-Chart/1/?type=pressure

**Comment by phil99** [comment]
Here (I hope) is a screenshot of the above weather page,
Focus will not scroll down to show the bar at the bottom:

![Screenshot_2021-12-14-10-07-21](https://user-images.githubusercontent.com/4710379/145977960-8ae2023f-d445-4bfe-b517-2f4aae88fb7b.jpeg)

**Comment by phil99** [comment]
I have now reinstalled Focus v94.1.2 which works fine.
See same weather page - here you can see (and use) the date/time scroller at the bottom of the page.
![Screenshot_2021-12-15-11-54-10](https://user-images.githubusercontent.com/4710379/146182776-54d54003-f495-4809-a3b1-28ac7a75d197.jpeg)

**Comment by phil99** [comment]
v95.2.0 has fixed the issue with non-displaying & non-functional overlays and cookie banners.
Closing issue.
