### ISSUE TITLE
[L10N] The "Cancel" button from menus is not translated in some languages

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6036]
## Steps to reproduce
1. Set Focus in Welsh language (Cymraeg).
2. Observe the "Cancel" button from Language page (Settings - General).
3. Observe the "Cancel" button from Cookies (Settings - Privacy & Security - Cookies and Site Data).

### Expected behavior
The "Cancel" button is translated in Welsh.

### Actual behavior
The "Cancel" button is not translated in Welsh.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9), Lenovo Tab M10 (Android 10), Google Pixel (Android 10)
* Focus version: Beta 96.0.0-beta.1
* I was not able to set any device to Cymraeg, because none of them support Cymraeg language
* Also reproducible with Hornjoserbšćina (Upper Sorbian - hsb), also a language not available on the devices language

![6036](https://user-images.githubusercontent.com/40694158/145773440-6b400c1f-43be-452a-969e-17d1f799cf17.png)

**Comment by Delphine** [comment]
Welsh is at 100% completion on both Focus strings and android-components.
But I still do see this issue

**Comment by delia-pop** [comment]
The "Cancel" button is still not translated in RC 96.1.1 with Google Pixel 6 (Android 12) in the Settings - General - Language and 
Settings - Privacy & Security - Cookies and Site Data menus.

**Comment by Delphine** [comment]
I'm still wondering how come this happens in locales where I see 100% coverage (and I don't see this for French, for example. So the string is localized).
Looking at l10n imports form Focus Android and Android-components, I see that exports are happening regularly.
Is there an issue perhaps on that end (so, between pulling in latest changes from Focus and a-c to bring them together?)
CC @channingcarter if you can help someone look into this. Thank you!

**Comment by delia-pop** [comment]
Reproducible in Beta 97.0.0-beta.2 with Google Pixel 6 (Android 12). Within the Settings - Privacy & Security - Cookies and Site Data menu, the "Cancel" button is still not translated in the Interlingua - (ia) language.

**Comment by lobontiumira** [comment]
This is still reproducible on Beta 98.0.0-beta.2, and on Nightly 99.0 (build 360420514 with GV 99.0a1-20220210065747), although in Pontoon the string is translated - https://pontoon.mozilla.org/fy-NL/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?search=Cancel&string=223950:

![Screenshot_3](https://user-images.githubusercontent.com/40694158/154263458-661c1d07-71f8-4f25-9ed1-ee7170fe9638.jpg)

**Comment by lobontiumira** [comment]
Still reproducible for Settings - Privacy & Security - Cookies and Site Data menu, the "Cancel" button is still not translated in the Frysk - Western Frisian (Netherlands) - (fy-NL) on the Beta 99.0.0-beta.1 build.

**Comment by Mugurell** [comment]
@lobontiumira Is this issue happening in all cases where we show this kind of dialog with rows of items and then an untranslated cancel button?
At a quick glance it looks like we're using a platform dialog with the cancel button not set to use a custom string.

**Comment by lobontiumira** [comment]
@Mugurell the "Cancel" option is now only displayed on Settings - Privacy & Security - Cookies and Site Data menu - Block cookies (the option is not available anymore in Languages).
And, so far, I've encountered it on Frysk - Western Frisian (Netherlands) - (fy-NL), and Occitan.

**Comment by Mugurell** [comment]
For romanian I get "Anulați" although all translations for "Cancel" on focus say "Renunță" - https://pontoon.mozilla.org/ro/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?search=cancel&string=223930 
so it looks like we're using a platform translation and not something the app sets.

<img src="https://user-images.githubusercontent.com/11428869/158209155-5e054dbf-306a-4fcc-b07c-b9bc579ba4dd.png" width="33%" />

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 100.0a1 (build 360750514 with GV 100.0a1-20220315091352) with Oppo Find X3 Lite (Android 11) on the following languages:
* Cymraeg
* Hornjoserbšćina
* Interlingua
* Frysk
* Occitan

![Untitled](https://user-images.githubusercontent.com/40694158/158597914-3de52bc0-b411-4b30-8884-bd5ca91ff3b4.png)
