### ISSUE TITLE
[L10N] "Add a search engine" SUMO page is not translated in some languages

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6045]
## Steps to reproduce
1. Set the Focus app in Cymraeg (Welsh), or Hornjoserbšćina (Upper Sorbian), or Nynorsk (Norwegian), or Taqbaylit.
2. Go to Settings - Search - Search engine - Add another search engine, and tap on the "i" option from the top right corner.

### Expected behavior
A custom tab with the https://support.mozilla.org/hsb/kb/add-search-engine-firefox-focus-android?as=u&utm_source=inproduct SUMO page is opened, translated in the app's language.

### Actual behavior
A custom tab with the https://support.mozilla.org/hsb/kb/add-search-engine-firefox-focus-android?as=u&utm_source=inproduct SUMO page is opened, partially translated in the app's language.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9)
* Focus version: Beta 96.0.0-beta.1

![Screenshot_20211213-095707_Firefox Focus Beta](https://user-images.githubusercontent.com/40694158/145775041-0f747299-6ca3-40d0-9b1e-3ba7634f4ef7.jpg)

**Comment by ionutbedregeanu** [comment]
@amedyne It seems the same scenario as in https://github.com/mozilla-mobile/focus-android/issues/6061#issuecomment-995272035

**Comment by ionutbedregeanu** [comment]
Since l10n team doesn't consider it a bug I will close this ticket, but feel free to reopen it if I'm wrong
