### ISSUE TITLE
Firefox android Nightly tab switch 

### ISSUE THREAD

**Issue by Reporter1** [mozilla-mobile/focus-android#6048]
Firefox Nightly android latest version from play store 
Android 11/ lineage 18
Pixel 5 redfin

Screen shots attached, the tab switcher overflows / flows into the notification bar area. When trying to select tabs 1 or 2 from the list, notification bar attempts to slide down. 
Suggest to adjust the position of the tab switch lower, do notification bar does not show or try to pull down. 

![Screenshot_20211212-123338_Firefox_Focus_Nightly_1](https://user-images.githubusercontent.com/34857551/145712539-dc0efe47-60bf-42b6-84b0-e97e08f27055.png)
![Screenshot_20211212-123320_Firefox_Focus_Nightly](https://user-images.githubusercontent.com/34857551/145712545-6318b043-1293-402c-bd49-dba61ff08304.png)

**Comment by ionutbedregeanu** [comment]
@jeffreygee Should we still follow the [figma design](https://www.figma.com/file/8Xyk89M3lk8n2c5aP79AHh/Delete-Action?node-id=2522%3A7249), should we place it under the toolbar?
Any thoughts?

**Comment by jeffreygee** [comment]
@ionutbedregeanu - Let's anchor it so that the dropdown menu is positioned below the menu button.

Reference:
<img width="360" alt="Tabs-NewAnchor" src="https://user-images.githubusercontent.com/93741573/146088134-fde9d3ad-119e-4be6-bc26-36fdb8ad29db.png">

**Comment by lobontiumira** [comment]
Verified as fixed on the Focus Nightly 97.0 (build 353560954 GV 97.0a1-20211220094500) with Google Pixel (Android 10).

![Screenshot_20211222-111817](https://user-images.githubusercontent.com/40694158/147068883-a0e26192-2447-48c4-8370-9becbdfa5af7.png)
