### ISSUE TITLE
Address code warnings

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6049]
Remove unused imports, classes, methods etc
Address those code warnings which doesn't imply a major refactoring

Note for QA: Theoretically this ticket shouldn't add regressions because just remove unused code, but maybe a smoke testing should be done just to be sure

**Comment by lobontiumira** [comment]
I finished a smoke & sanity testing run on the latest Focus Nightly from 1/20 with Oppo Find X3 Lite (Android 11), and there seems to be no regressions from removing unused code.
