### ISSUE TITLE
[L10N] Text's context menu is not translated in multiple languages

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6050]
## Steps to reproduce
1. Set Focus to Dolnoserbski or Hornjoserbšćina (Upper or Lower Sorbian), or Nynorsk (Norwegian), or Taqbaylit.
2. Open a page with non-linked text.
3. Long-tap on a non-linked text.
4. Select to "copy" the text.
5. Long-tap on the URL bar and "paste" the text.

### Expected behavior
Both options ("copy", and "paste") are translated in Dolnoserbski or Hornjoserbšćina (Upper or Lower Sorbian).

### Actual behavior
The options ("copy", and "paste") are not translated in Dolnoserbski or Hornjoserbšćina (Upper or Lower Sorbian).

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: Beta 96.0.0-beta.1

![HSB DSB languages](https://user-images.githubusercontent.com/40694158/145811183-0ec0c5fc-2854-4b22-ba21-b90406e69255.png)

**Comment by Delphine** [comment]
I have a feeling this text comes from android-components since I can't find it under Focus specific strings.
I wouldn't know in which file to look specifically though, to check if it's been translated though (my instinct tells me they didn't)

**Comment by ionutbedregeanu** [comment]
I will close this ticket since those dialogs are system related, so the text is translated using your device language
