### ISSUE TITLE
[L10N] The positive feedback isn't translated in some languages

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6051]
## Steps to reproduce
1. Set Focus to Slovenčina (Slovak).
2. Open any SUMO page.
3. Scroll to the end of the SUMO page and give the thumbs up feedback.

### Expected behavior
The "Great to hear - thanks for the feedback!" message is translated.

### Actual behavior
The "Great to hear - thanks for the feedback!" message is not translated.
The negative feedback is translated though.

### Device information
* Android device: any
* Focus version: Beta 96.0.0-beta.1
* Reproducible also with: Spanish (Mexico, Chile, Argentina), Nynorsk (Norwegian)

![feedback translation](https://user-images.githubusercontent.com/40694158/145815188-f98ba5d8-1c57-4bd7-af70-96de553f9ba4.png)

**Comment by delia-pop** [comment]
Another issue regarding the feedback prompt was encountered on RC 96.1.1 with Google Pixel (Android 12). 
The "Great to hear - thanks for the feedback" prompt displays incorrect characters/debug text in Chinese Simplified language.

link: https://support.mozilla.org/zh-CN/kb/firefox-focus-android-93?as=u&utm_source=inproduct

![Screenshot_2022-01-11-14-28-08-121_org mozilla focus](https://user-images.githubusercontent.com/89388888/148943270-cb7aab83-6034-4095-b8bb-77e8089d1ed3.jpg)

**Comment by lobontiumira** [comment]
Reproducible on Beta 97.0.0-beta.2 with Spanish, with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on Beta 98.0.0-beta.1: the "Great to hear - thanks for the feedback" prompt is not translated in Spanish.
