### ISSUE TITLE
[L10N] Some SUMO pages display "Page not found" when accessed in some languages

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6054]
## Steps to reproduce
1. Set Focus to Interlingua or Basa Sunda or Corsican.
2. Go to Settings - What's New gift icon from the top right corner.

### Expected behavior
1. The "What's New" SUMO page is opened in a new tab.

### Actual behavior
A "Page not found" is opened in a new tab, with this address: https://support.mozilla.org/en-US/ia/kb/whats-new-firefox-focus-android?as=u&utm_source=inproduct

When accessed via Pro Tips, the following SUMO page is opened: https://support.mozilla.org/en-US/kb/whats-new-firefox-focus-android?as=u&utm_source=inproduct

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: 96.0.0-beta.1

![Screenshot_20211213-155646](https://user-images.githubusercontent.com/40694158/145825644-99657244-5f83-40e0-9e52-194364a43164.png)

**Comment by lobontiumira** [comment]
The same situation with "Add a search engine" SUMO page. When the "i" is tapped from Settings - Search - Search engine - "+Add a search engine", a new tab is opened with this link: https://support.mozilla.org/en-US/ia/kb/add-search-engine-firefox-focus-android?as=u&utm_source=inproduct

**Comment by kelimuttu** [comment]
Hi @lobontiumira 

Both links have additional strange characters (ia) in between the URL that caused the link to be broken. 

* The first link: https://support.mozilla.org/en-US/ia/kb/whats-new-firefox-focus-android?as=u&utm_source=inproduct should've been → https://support.mozilla.org/kb/whats-new-firefox-focus-android?as=u&utm_source=inproduct
* The second link: https://support.mozilla.org/en-US/ia/kb/add-search-engine-firefox-focus-android?as=u&utm_source=inproduct should've been → https://support.mozilla.org/kb/add-search-engine-firefox-focus-android?as=u&utm_source=inproduct

Notice how I also omit the locale string, so users would be directed based on their locale instead of automatically presented the English version. See https://support.mozilla.org/en-US/kb/a-guide-to-linking-to-support-articles for more about linking a support article from SUMO.

**Comment by delia-pop** [comment]
Please note that on RC 96.1.1 some SUMO pages still display "Page not found" when accessed in Interlingua language and the user is not directed to the proper page based on their locale.

e.g. Add a search engine SUMO page:  https://support.mozilla.org/en-US/ia-001/kb/add-search-engine-firefox-focus-android?as=u&utm_source=inproduct

**Comment by kelimuttu** [comment]
@delia-pop the link you have above is wrong. The in-product link shouldn't include locale code. It should be → https://support.mozilla.org/kb/add-search-engine-firefox-focus-android?as=u&utm_source=inproduct

**Comment by lobontiumira** [comment]
The issue still reproduces on the latest Focus Nightly 107.0a1 from 10/6 with Google Pixel (Android 10).
Setting the app to Basa Sunda or Corsican language, and tapping on:
* "What's new" button,
* the "i" from Settings - Search - Search engine - "+Add a search engine", 
* the Safe browsing "Learn more" link,
* the HTTPs-Only mode "Learn more" link,
* the Data choices "Learn more" link, or 
* the Get search suggestions "Learn more" link,

takes the user to a "Page not found" page.

**Comment by kelimuttu** [comment]
It's highly possible if this is related to the problem with locales with legacy codes.

Our team recently resolved this issue for Hebrew https://github.com/mozilla/sumo/issues/1106. @escattone would you please take a look and check if this is the same issue?

**Comment by escattone** [comment]
This occurs under the following conditions:
- Focus uses a SUMO-provided "inproduct" link to a SUMO article or page, for example something like https://support.mozilla.org/1/mobile/{version}/{platform}/{locale}/whats-new-firefox-focus-android, where Focus fills in the `{version}`, `{platform}`, and `{locale}` depending upon the user's context
- Focus fills-in the locale with a locale that SUMO doesn't recognize, like `ia`, `co`, or `su`
- SUMO receives the "inproduct" request and redirects to the configured SUMO page using the locale provided from Focus
- When the redirect request is received, SUMO doesn't recognize the locale, so it assumes the locale is missing and prepends `en-US` as the locale

What we (the SUMO engineering team) should do is gracefully handle unsupported locales by falling back to the default locale (`en-US`), which would be easy for us to do. I created https://github.com/mozilla/sumo/issues/1110 for us to do that. Thanks for the heads up @kelimuttu!

**Comment by kelimuttu** [comment]
Thanks for taking a look at this and for the swift fix for this @escattone 

Totally makes sense to redirect this case to English instead, since we don't have the presence of those 3 locales in SUMO.

**Comment by escattone** [comment]
This should be fixed now. For example, all of the following "inproduct" links now gracefully redirect to the default locale:

https://support.mozilla.org/1/mobile/105/Android/ia/whats-new-firefox-focus-android
https://support.mozilla.org/1/mobile/105/Android/co/whats-new-firefox-focus-android
https://support.mozilla.org/1/mobile/105/Android/su/whats-new-firefox-focus-android

**Comment by kelimuttu** [comment]
@lobontiumira Mira, would you please confirm this and close the issue?

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 107.0a1 from 10/13 with Google Pixel (Android 10).
Verified with Basa Sunda, and Corsican. All the SUMO links were opened in the default en-US locale.
I'll close this issue as complete.

**Comment by lobontiumira** [comment]
Verified as fixed also on Beta 107.0b1 build.
