### ISSUE TITLE
[L10N] Some elements are not translated in Vietnamese

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6061]
## Steps to reproduce
1. Set you device to Vietnamese (Tieng Viet).
2. Go to the homescreen, and tap on the third pro tip hyper-link, with this SUMO page https://support.mozilla.org/vi/kb/them-cac-trang-web-dang-tin-cay-vao-danh-sach-cho-phep-cua-ban?as=u&utm_source=inproduct&redirectslug=add-trusted-websites-your-allow-list&redirectlocale=en-US 
3. Go to Settings - Privacy & Security - Cookies and Site Data, and tap on Cookies.
4. Observe the default "Block cross-site cookies".
5. Go to Settings - Privacy & Security - Safe Browsing, and tap on the "Learn more" hyper-link.
6. The https://support.mozilla.org/vi/kb/how-does-phishing-and-malware-protection-work  SUMO page is opened.

### Expected behavior
All the elements are translated in Vietnamese.

### Actual behavior
After step 2, the SUMO page displays the "Add trusted websites to your allo list" hyper-link, not translated.
After step 3, the "Block cross-site cookies" is not translated.
After step 6, the SUMO page is not translated.

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: Beta 96.0.0-beta.2

![vietnamese](https://user-images.githubusercontent.com/40694158/146015583-ee27f8dd-a802-4358-8661-fa3644ab9483.png)

**Comment by Delphine** [comment]
This is SUMO content, so would add SUMO label (this is not something we can fix with Pontoon).

**Comment by delia-pop** [comment]
Please note that the "Add trusted websites to your allow list" hyper-link from the third Pro tip SUMO page is not translated in Japanese, Ukrainian, Nederlands (Dutch) as well.

![Screenshot_2021-12-15-12-02-55-621_org mozilla focus beta](https://user-images.githubusercontent.com/89388888/146170256-23247147-ec5b-4c69-8ca2-44346fb38e82.jpg)

**Comment by delia-pop** [comment]
Please note that the "What's new in Firefox Focus for Android (verison95)" hyper-link from the first Pro tip SUMO page is not translated in Japanese.

![Screenshot_2021-12-15-12-25-45-792_org mozilla focus beta](https://user-images.githubusercontent.com/89388888/146175039-dd8046b3-bd5a-4891-8dd1-d4ac77fd87e6.jpg)

**Comment by Delphine** [comment]
I think the fact SUMO pages are not entirely translated is something that can happen, as it depends on volunteers. I don't think these cases should be bugs. The things I see as bugs are more when a link in the app doesn't link correctly to a SUMO page.
@jr-johnson-support for clarification :)

**Comment by kelimuttu** [comment]
I agree with @Delphine

This shouldn't be considered a bug as we also have a banner on the article explaining that the article hasn't been translated. 

What I think will be useful is, perhaps we can identify all the SUMO articles that are linked from the product and set up priority for the locales that are considered priority for the team so we can rally the community effort around it.

**Comment by jr-johnson-support** [comment]
I also agree here with @Delphine this does not seem like a bug. 

Thanks @kelimuttu your response. That could be a path forward to help reduce instances like this in the future.

**Comment by lobontiumira** [comment]
Based on Delphine's, and Kelimutu's comments above, I will close this ticket.
