### ISSUE TITLE
[L10N] Wrong Privacy Notice SUMO page in Swedish

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6062]
## Steps to reproduce
1. Set the device to Swedish.
2. Go to Settings - Mozilla - Privacy Notice, and tap on it.
3. The Privacy Notice SUMO page opens translated in Swedish.

### Expected behavior
The SUMO page openes in a new tab, translated in Swedish.

### Actual behavior
The https://www.mozilla.org/vi/privacy/firefox-focus/ is opened in a new tab, the SUMO page is translated in Vietnamese.

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: Beta 96.0.0-beta.2

![asas](https://user-images.githubusercontent.com/40694158/146022595-e1063f14-6435-40bb-bc32-cff72a7c9ce5.png)

**Comment by Delphine** [comment]
Scrolling to the the bottom of that page, I don't see Swedish available as a translation in the drop down.
But in any case, it shouldn't send to Vietnamese - it should default to English.

**Comment by Delphine** [comment]
I think we should add the SUMO label here too

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue anymore on the Beta 98.0.0-beta.2 with Samsung Galaxy Note 8 (Android 9).
The Privacy Notice SUMO page is opened in en-US:
![Screenshot_4](https://user-images.githubusercontent.com/40694158/154283448-81eca644-7daa-44ca-b912-08c6ec496073.jpg)

I'll close this ticket.
