### ISSUE TITLE
Enable experimentation on Focus

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6064]
This ticket is to enable experimentation on all builds for Focus.
Ensure that we uplift the change for Focus Beta 96.

**Comment by lobontiumira** [comment]
Verified that the Studies is enabled by default, and is displayed in Settings - Privacy & Security in Focus Beta 96.0.0-beta.3.
Verified with Sony Xperia Z5 Premium (Android 7.1.1).
