### ISSUE TITLE
[L10N] SUMO pages need some adjustments in some languages

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6065]
## Steps to reproduce
1. Set the device to Swedish.
2. Tap on the hyper-link from the third pro tip.
3. Go to Settings - Mozilla - Help, and tap on it.

### Expected behavior
Both SUMO pages are translated in Swedish.

### Actual behavior
The SUMO pages need adjustments:
* the "Help" page https://support.mozilla.org/sv/kb/vad-firefox-focus-android needs new screenshots, with the new design,
* the "Allow list" page https://support.mozilla.org/1/mobile/96.0.0-beta.2/Android/sv-SE/focus-android-allowlist also needs new screenshots, and displays the "Add trusted websites to your allow list" hyper-link, not translated.

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: Beta 96.0.0-beta.2
Help page:
![sw2](https://user-images.githubusercontent.com/40694158/146028552-2a805262-8e66-4e64-90f7-8eb27de26550.png)

Allow list page:
![allowlist](https://user-images.githubusercontent.com/40694158/146028742-7afba94a-2f12-42f6-88c6-d0be42062e28.png)

**Comment by delia-pop** [comment]
Please note that the "Help" page needs screenshot with the new design on the Japanese language as well.

![Screenshot_2021-12-15-12-38-45-328_org mozilla focus beta](https://user-images.githubusercontent.com/89388888/146172952-0bd42c54-5707-4174-88e2-6783b9b3cbc0.jpg)

**Comment by delia-pop** [comment]
Please note that the "Help" page needs screenshot with the new design to be added on the Slovenčina - Slovak - (sk) language as well. 

link: https://support.mozilla.org/sk/kb/co-je-firefox-focus-pre-android
![Screenshot (11  1](https://user-images.githubusercontent.com/89388888/148944627-a54c2dc8-12f1-4fe0-8f25-1b702004f6ef.png)

**Comment by marsf** [comment]
> Please note that the "Help" page needs screenshot with the new design on the Japanese language as well.

I have updated for Japanese help page. Thanks.
https://support.mozilla.org/ja/kb/what-firefox-focus-android/revision/240089

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802591

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
