### ISSUE TITLE
Skip button in onboarding does nothing.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#6067]
## Steps to reproduce

Have a fresh install.
Press button "SKIP" in the onboarding screens.

### Expected behavior

Onboarding is finished.

### Actual behavior

Nothing happens.

### Device information

* Android device:  All.
* Focus version:  from latest main.

**Comment by mcarare** [comment]
Possible regression from https://github.com/mozilla-mobile/focus-android/pull/5997.

**Comment by lobontiumira** [comment]
Verified as fixed on the 97.0 Nightly (build 353540510 GV 97.0a1-20211219092930) with Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
