### ISSUE TITLE
[L10N] Pro tips SUMO pages aren't translated in some languages

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6071]
## Steps to reproduce
1. Set Focus to Basa Sunda.
2. Go to the homescreen, and observe the pro tips with hyper-links - they are translated.
3. Tap on each one of them.

### Expected behavior
The SUMO pages from Pro Tips are translated.

### Actual behavior
None of the Pro Tips SUMO pages are translated in Basa Sunda.

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: Beta 96.0.0-beta.2
* Reproducible also with Hungarian, Occitan, and Turkish

**Comment by delia-pop** [comment]
The pro tips SUMO pages are also partially translated on Japanese language on  Beta 96.0.0-beta.2.
The "The fine people helped write this article:" text from the bottom of the page is not localized. (Note that the text is localized in Ukrainian, Dutch).

![Screenshot_2021-12-15-12-03-07-979_org mozilla focus beta](https://user-images.githubusercontent.com/89388888/146167798-266e837f-60f5-4d39-bf34-74d24119a9b4.jpg)

**Comment by delia-pop** [comment]
The first pro tip SUMO page is also partially translated on Ukrainian language on Beta 96.0.0-beta.2.

![Screenshot_20211215-130613_Firefox Focus Beta](https://user-images.githubusercontent.com/89388888/146175890-627bd471-c864-4cda-9759-7fbca7b082b9.jpg)

**Comment by kelimuttu** [comment]
Hi both, 

SUMO is not available in Sundanese (su), see: https://support.mozilla.org/en-US/locales

As for @delia-pop 's point about the Japanese translation for the pro-tips sumo page, I did find the strings in [Pontoon](https://pontoon.mozilla.org/ja/sumo/LC_MESSAGES/django.po/?search=these+fine&string=209637), so it's a matter of localizing the string from there. 

As for the Ukrainian translation, I'm not sure if it's part of the article or part of the platform. Can you share the full link so I can check?

**Comment by lobontiumira** [comment]
Hi @kelimuttu 
This is the link for the Ukrainian translation: https://support.mozilla.org/uk/kb/sho-novogo-u-firefox-focus-dlya-android-versiya-95?as=u&utm_source=inproduct

**Comment by kelimuttu** [comment]
@lobontiumira Thanks! I've nudged our Ukrainian contributor to help with that one.

**Comment by lobontiumira** [comment]
I encountered this issue on Beta 98.0.0-beta.2 on Occitan, for all three pro tips SUMO pages:
* first pro tip: https://support.mozilla.org/en-US/kb/whats-new-firefox-focus-android?as=u&utm_source=inproduct
* the third pro tip: https://support.mozilla.org/en-US/kb/add-trusted-websites-your-allow-list-firefox-focus?as=u&utm_source=inproduct&redirectslug=add-trusted-websites-your-allow-list&redirectlocale=en-US
* the fifth pro tip: https://support.mozilla.org/en-US/kb/switch-desktop-view-firefox-focus-android

**Comment by kelimuttu** [comment]
Hi @lobontiumira. As I mentioned before, I don't think that this should be a bug. We can't have every article translated to every language. I think it's better for us to identify articles that are linked from the product and agree on priority locales, so we can work with the community for each release to prioritize those articles as necessary. Otherwise, we'll keep having this kind of issue every time there's a new release.

**Comment by lobontiumira** [comment]
Thanks, @kelimuttu 
Based on your comment, I'll close this ticket.
