### ISSUE TITLE
[L10N] Incorrect Focus version number in first Pro Tip in some languages

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6072]
## Steps to reproduce
1. Set Focus to Japanese.
2. Go to the homescreen, tap on the first pro tip hyper-link.
3. Observe the incorrect version number.

### Expected behavior
The correct version (95) should be displayed.

### Actual behavior
The incorrect version (94) is displayed.

### Device information

* Android device: all
* Focus version: Beta 96.0.0-beta.2

![Screenshot_2021-12-15-12-25-45-792_org mozilla focus beta](https://user-images.githubusercontent.com/89388888/146173602-64c6ee23-aac1-4fce-8bab-9b0c77798193.jpg)

**Comment by kelimuttu** [comment]
Hi @delia-pop can you mention the URL of the article? Thanks!

**Comment by lobontiumira** [comment]
@kelimuttu this is the link: https://support.mozilla.org/ja/kb/whats-new-firefox-focus-android?as=u&utm_source=inproduct

**Comment by kelimuttu** [comment]
@lobontiumira Thanks for the link, Mira. This can happen when the localized version hasn't been updated. I wouldn't consider this as a  bug. I've pinged our contributor to see if we can prioritize translating this article.

Feel free to ping our team (#sumo_community on Slack) or me directly (rkelimutu on Slack) when something like this happen next time.

**Comment by lobontiumira** [comment]
I encountered this on Beta 98.0.0-beta.2 when setting the device to Russian> The first pro tip https://support.mozilla.org/ru/kb/chto-novogo-v-firefox-focus-dlya-android-versiya-9?as=u&utm_source=inproduct displays "version 93" instead of "version 97":
![russian](https://user-images.githubusercontent.com/40694158/154271044-336bc9e6-339d-4be8-bdc8-d050c838d854.jpg)

**Comment by kelimuttu** [comment]
I've pinged our contributor to help with the Russian and Japanese localization for the 97 version.

**Comment by lobontiumira** [comment]
This issue is reproducible also on Turkish on the latest Beta 99.0.0-beta.1, with Samsung Galaxy Note 8 (Android 9):

![Screenshot_3](https://user-images.githubusercontent.com/40694158/158129814-ba0e492d-ce9a-432f-a198-94b4f450f395.jpg)

**Comment by lobontiumira** [comment]
This is fixed on the latest Focus Beta 100.0.0-beta.3.
