### ISSUE TITLE
Unable to save credentials for website with auth_basic

### ISSUE THREAD

**Issue by asarubbo** [mozilla-mobile/focus-android#6079]
## Steps to reproduce
Go to a website that uses auth_basic authentication, like "https://USER:PASS@WEBSITE" and save it on the home

### Expected behavior
Access to the website without insert again the password

### Actual behavior
The user/password needs to be typed again

### Device information

"Mozilla/5.0 (Android 9; Mobile; rv:95.0) Gecko/95.0 Firefox/95.0" "-"

Just ftr, I'm able to to that with chrome on android.

**Comment by ionutbedregeanu** [comment]
Hi, @asarubbo!  Firefox Focus is a browser oriented to privacy and doesn't store data, so this is an expected behaviour.
If you want a complex browser you can use Firefox Fenix https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en&gl=US
