### ISSUE TITLE
[Beta] Focus clients are not unenrolled from experiments after the recipe is disabled

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6084]
From: https://mozilla-hub.atlassian.net/browse/QA-1321
and
https://mozilla-hub.atlassian.net/browse/SDK-462
## Steps to reproduce

1. Navigate to the experiment's Nimbus page and disable it.
2. Wait for the nimbus-mobile-experiments/records collection to update with the change.
3. Restart the Focus application several times to fetch the changes.
4. Filter the Logcat pings using the "nimbus" keyword and observe the events.

### Expected behavior
    The client is unenrolled from the experiment and an event stating this is displayed.
### Actual behavior
    The client remains enrolled in the experiment and the status remains "Enrolled".

Affected Platforms:

    Android 8

 
Affected Versions:

    Focus 96.0.0-beta.2, Build #353491703.

 
Prerequisites:

    Have the latest Firefox Focus 96 Beta build APK generated and installed on an Android device.

    Have the nimbus.remote-settings.url = https://settings-cdn.stage.mozaws.net and debuggable = true lines added to the local.properties file.

    Have a .nimbus file created with the https://settings-cdn.stage.mozaws.net line.

    Have the Android Studio Logcat console open.

    Have the Focus client enrolled in a Live Nimbus experiment.

Notes:

    I've verified that the experiment is correctly removed from the Remote Settings collection after it is disabled (https://settings.stage.mozaws.net/v1/buckets/main/collections/nimbus-mobile-experiments/records)

    The disabled experiment is also displayed as active in the client's Studies menu.

    The following status is displayed for the disabled experiment: 17104-17141/org.mozilla.focus.beta D/nimbus::enrollment: Have enrollment: ExperimentEnrollment { slug: "ppop-focus-android-ab-v96-beta-experiment-stage-clone", status: Enrolled { enrollment_id: 27db97a6-597f-40b0-a117-c855dec06d80, reason: Qualified, branch: "treatment-a" } }

**Comment by Mugurell** [comment]
Seems like this is happening because of Nimbus' caching/backoff/retry logic in the SDK - https://mozilla-hub.atlassian.net/browse/SDK-462.

So the issue described here should probably not block the launch of the experiment.

But for the future @jhugman suggested that we could have a button that the users could press to force refresh the data.

**Comment by amedyne** [comment]
@channingcarter @jeffreygee see suggestion ^ for this.

**Comment by ionutbedregeanu** [comment]
I will close this ticket since it was marked as resolved in Jira.
For the above suggestion we should create a separate ticket
