### ISSUE TITLE
WebRTC IP Leak Switch

### ISSUE THREAD

**Issue by mikeV02** [mozilla-mobile/focus-android#609]
I noticed that the browser leaks the true IP through WebRTC when using a VPN. It does not have about:config menu as Firefox, so I thought it would be nice to have a switch in the settings to enable or disable WebRTC.

**Comment by pocmo** [comment]
As long as our builds are based on WebView we can't really prevent that. This was one of the reasons why Tor's browser is based on Firefox and not using WebView anymore.

**Comment by eolme** [comment]
I think you can try *webview.evaluateJavascript* or inject script tag before other scripts in page and set *RTCPeerConnection* and/or *webkitRTCPeerConnection* to *undefined*

**Comment by lfxc** [comment]
what about replacing webview with https://crosswalk-project.org/ ?

**Comment by pocmo** [comment]
Crosswalk is no longer in development. It's more likely that we are going to switch to GeckoView in case we are deciding to abandon the WebView based build.

**Comment by lfxc** [comment]
if google hasn't allowed the ability to turn off webrtc by now, I would guess they won't for whatever data collection reasons they may have...

**Comment by lfxc** [comment]
there's also the option of using Chromium webkit in addition to GeckoView.

I do think an IP leak is a big problem.   Is there any workaround on the mean time that would work?

thanks

**Comment by pocmo** [comment]
Unfortunately there's no workaround for Focus currently. For this you'd have to either use regular Firefox (and flip the preferences for this) or OrFox.

**Comment by rancidfrog** [comment]
How can you label project 

>  Firefox Focus: The privacy browser - Browse like no one’s watching. 

When IP is being leaked. Kind of pathetic false information.
Can't you be sued?

**Comment by lfxc** [comment]
I really think you guys need to figure this one out if you want to be a privacy-focused browser.

**Comment by RootUp** [comment]
Indeed, I believe this is more of a privacy issue here is the live demo for same,  
1. Navigate to `www.ch3114.com/getip.html`
2. You would be able to private IP address of user.

**Comment by Sdaswani** [comment]
Thanks for your input folks - we will re-triage this soon.

**Comment by pocmo** [comment]
Focus has replaced WebView with GeckoView a long time ago. Closing.
