### ISSUE TITLE
[crash] Changing the cookies option crashes the Focus Nightly app

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6094]
## Steps to reproduce
1. Install the latest Nightly, from 12/20.
2. Open Settings - Privacy & Security - Cookies and Site Data, and change the default option to any other options.

### Expected behavior
The new option is displayed as selected. The user remains in the Privacy & Security page.

### Actual behavior
Focus crashes.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9)
* Focus version: 12/20 Focus Nightly
[logcat.txt](https://github.com/mozilla-mobile/focus-android/files/7745559/logcat.txt)

https://user-images.githubusercontent.com/40694158/146773266-6758db6b-28d2-452c-9f0a-cd79fd836982.mp4

**Comment by ionutbedregeanu** [comment]
Seems that is a regression of this https://github.com/mozilla-mobile/focus-android/pull/5940 . I'm working on it

**Comment by lobontiumira** [comment]
Verified as fixed on the 97.0 Focus Nightly (build 353551145 GV 97.0a1-20211220094500) with Xiaoi Mi8 Lite (Android 10), and Samsung Galaxy Note 8 (Android 9).
