### ISSUE TITLE
CustomTab followups

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#610]
We're adding initial custom tabs support in #500 (which is v1). We're not adding complete support there, I'm putting remaining features here:

- [ ] Bottom toolbar support (not use much IRL?)
- [ ] URL copying (the urlbar doesn't allow editing, FF and chrome let you long-press to copy the current URL)
- [ ] Consider showing page title in the urlbar (similar to firefox CT)
- [ ] In/out animations
- [ ] Pre-warming (that might not be possible given we're using webview?)
- [ ] Show page title (EXTRA_TITLE_VISIBILITY_STATE)
- [ ] Action button tint

We might not want and/or be able to support all of these, but at least we can track what features we don't support here.

**Comment by bbinto** [comment]
moved ahunt's text into #1870
