### ISSUE TITLE
Make the build options of Focus and Klar the same.

### ISSUE THREAD

**Issue by carbongreat13** [mozilla-mobile/focus-android#6101]
### Why/User Benefit/User Problem
Currently, Focus requires more permissions than Klar. This is undesirable from a privacy perspective, and should be identical to Klar.
You should stop discriminating against users based on the country they live in.

**Comment by carbongreat13** [comment]
Please do not close this issue.

**Comment by lobontiumira** [comment]
@carbongreat13 thank you for the report!
Could you please elaborate this issue?

**Comment by Mugurell** [comment]
I think permissions should be the same with the only difference being whether telemetry is enabled by default or not.
Marking this as a `feature-request` for this.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802004

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
