### ISSUE TITLE
"Learn More" link for Studies in Focus needs to be updated

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6104]
## Steps to reproduce
Go to **Settings**-> **Privacy & Security**
Under **Data Choices** click on **Studies**
Click on **Learn More** link

### Expected behavior
User should be taken to correct Focus Android Studies support page

### Actual behavior
User goes to the Firefox Android Studies support page

* Android device: Pixel 6Pro
* Focus version: Focus Nightly 97

See equivalent link: https://bugzilla.mozilla.org/show_bug.cgi?id=1746399

**Comment by lobontiumira** [comment]
Verified as fixed on the Focus Nightly 97.0 (build 360101001 GV 97.0a1-20220108220226) with Lenovo tab M10 (Android 10), Samsung Galaxy Note 8 (Android 9), and Oppo Find X3 Lite (Android 11).
Tapping on "Learn more" opens a new tab with the following SUMO page: https://support.mozilla.org/en-US/kb/how-opt-out-studies-firefox-focus-android:
![aaaa](https://user-images.githubusercontent.com/40694158/148734385-a6a89d42-689a-4d8e-b4fe-b55df2699b32.jpg)

**Comment by lobontiumira** [comment]
Verified also on Beta 97.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).
