### ISSUE TITLE
[Android 5] "Open links in apps" prompt is not triggered when the setting is enabled

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6122]
## Steps to reproduce
1. From Settings - Advanced - enable the "Open links in apps".
2. Exit Settings, open youtube.com.

### Expected behavior
The "Open in app" prompt is displayed.

### Actual behavior
The prompt is not displayed.

### Device information
* Android device: Xiaomi mi4i (Android 5.0.2), Samsung Galaxy Tab A6 (Android 5.1.1)
* Focus version: Beta 96.0.0-beta.5
* Reproducible also on Focus Nightly 95.0 (353421248 GV 96.0a1-20211204095400), and Focus Nightly 97.0 (353581052 GV 97.0a1-20211223093436)
* Not reproducible on Google Pixel (Android 10)

[logcat.txt](https://github.com/mozilla-mobile/focus-android/files/7773581/logcat.txt)

**Comment by mcarare** [comment]
Does this feature work on Fenix on those devices? Thank you!

**Comment by lobontiumira** [comment]
@mcarare no, the "Open links in apps" does not work as expected in Fenix either.
Tested on the Fenix Nightly 97.0a1 (build 2015853099, GV 97.0a1-20211221093038).

**Comment by lobontiumira** [comment]
@mcarare I'll close this ticket because I retested today, and everything works as expected.
Apparently I have to close Focus after I enable the "Open links in apps" in order for it to work.
Re-tested on both devices, with Beta 96.0.0-beta.5, and Focus Nightly from 12/27.
