### ISSUE TITLE
[a11y] The unchecked radio buttons from Block cookies prompt aren't read as "unchecked"

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6134]
## Steps to reproduce
1. Turn the device's talkback/screen reader on.
2. In Focus, fo to Settings - Privacy & Security - Block cookies, and scroll through options using TB gestures.

### Expected behavior
The unchecked radio buttons are announced as "unchecked".

### Actual behavior
The unchecked radio buttons are announced only by the name, but not if they are checked or not.
The default one that is checked is announced as checked.

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: Focus Nightly from 12/27, Beta 96.0.0-beta.5

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the latest Focus Nightly 101.0a1 from 4/8 with Google Pixel (Android 10).
The unchecked options are read as:
* "Yes please, 1 of 5 in list, five items, double-tap to toggle"
* "Checked Block cross-site cookies, 4 of 5, double-tap to toggle"

**Comment by ionutbedregeanu** [comment]
@lobontiumira I tested on pixel 3a and it seems expected behaviour to me.
The selected option is announced as checked and for the rest of them it says "Double tap to toggle", which means are unchecked and we can can check one of them by double tap
