### ISSUE TITLE
Add the ability to disable Autocomplete in Search Engines

### ISSUE THREAD

**Issue by tunjos** [mozilla-mobile/focus-android#6145]
### Why/User Benefit/User Problem
Search is one of the activities people engage in the most on the internet. Some search engines like [DuckDuckGo](https://duckduckgo.com/), [Bing](https://www.bing.com/), etc. provide the possibility to completely disable autocomplete. Others like **Google**, **Yahoo! Search**, etc. don’t currently allow this option and thus make autocomplete a **forced feature**.

There are several **cons** to **Autocomplete**. Some of them are highlighted in this article: [Autocomplete in Search Engines can be evil. Find out why!
](https://tunjos.co/blog/autocomplete-search-engine-can-be-evil/)

Summary of the **The effects of autocomplete** in the article:
1. Your search intentions are controlled or at least shaped by Autocomplete
2. It can corrupt one’s mindset subconsciously by reinforcing many false beliefs
3. It causes anxiety
4. It leads to laziness
5. You become really bad at spelling

**Firefox Focus**, as the name implies, should allow one to **Focus** while browsing the internet.

[Mindful Google™](https://chrome.google.com/webstore/detail/mindful-google/majeighpkbfmjamjiegocmiemagfanle) is Google Chrome extension that helps to disable autocomplete on the Google Search Engine. The JavaScript code can be seen here [Mindful-Google](https://github.com/tunjos/Mindful-Google)

### What / Requirements
- Add ability to disable Autocomplete in Search Engines that force this feature
- Add an option in the settings that enables or disables automcomplete  in Search Engines that force this feature

### Acceptance Criteria (how do I know when I’m done?)
- Firefox Focus Automatically disables Autocomplete in Search Engines that force this feature.
- Users have the option enable or disable Autocomplete in Search Engines that force this feature.

**Comment by mcarare** [comment]
@tunjos Thank you for your suggestions and info. However, Focus already has the option to autocomplete websites or not. It also has the option to show search suggestions or not.

**Comment by tunjos** [comment]
@mcarare You welcome. I think you misunderstood the suggestion though. I was referring to the autocomplete that occurs in the actual webpages of search engines, and not the one that occurs in the URL/address bar. Thanks!

**Comment by mcarare** [comment]
I am reopening this. However, for the moment Focus does not have extension support so this feature request should be raised against the Gecko View component, maybe on https://bugzilla.mozilla.org/home.

**Comment by tunjos** [comment]
@mcarare Ok great! Thanks for the hint.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802003

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
