### ISSUE TITLE
Investigate a different method of obscuring thumbnail on the list of Recent Apps

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#615]
I’ve learnt something neat from [Courier](https://guardianproject.info/apps/courier/) app from The Guardian Project. It’s got a setting called “Block Screenshots”:

> **Block Screenshots**
> Stop other apps and the Android system from taking screenshots of this app

Turning the blocker on doesn’t stop you from taking a screenshot of the Settings page itself (which isn’t incriminating). But it will stop you from taking screenshot of _the rest of the app_ (which may contain pictures/videos that can be incriminating).

Cleverly, because the app’s Settings Page is always allowed to take screenshots from, when you open Recent Apps ( ⃞ button), the app seems to tell the system to “Take a screenshot of the Settings page and use it as a thumbnail”.

The logic goes like this:

* If you access any page in app without having accessed the Settings page first, the thumbnail will be a blank white box.
* If you access any page after accessing the Settings page, the thumbnail is that of the Settings page.

It seems like, instead of hiding Firefox Focus entirely on Recent Apps, we can just show a screenshot of our Settings page but still show our app on the list.

What are the pros and cons of adopting an approach like Courier’s? Should we consider it, or stick to our original approach?

**Comment by pocmo** [comment]
Removing the "nice to have" label because we are using this for items with P2 priority for the v1 release.

Our settings screen is currently a separate activity and we do not set the secure flag for it - so this should already show up in recent apps :)

**Comment by brampitoyo** [comment]
Thanks for relabelling :)

I think showing the screenshot of Settings in Recent Apps vs. total stealth has one advantage: it makes the app easier to access. If we want to provide more security, we can then implement a passphrase that unlocks the app.

**Comment by brampitoyo** [comment]
We already do this. Closing this issue.
