### ISSUE TITLE
Custom Tabs and View intent clearing

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#616]
For a normal View intent:
- Back button returns to previous app, data is not cleared (browsing session notification remains on screen)
- Erase button goes to focus home screen, data is cleared

For Custom Tabs:
- Back button returns to previous app, data is not cleared (same as View intent)
- Close button (top-left) used to erase data (returns to previous app), but I've changed that in #611 to return to the previous app without clearing data.
- The erase button isn't shown in Custom Tabs

My questions:
1) Should the erase button return to the previous app if opened via VIEW intent?
2) Should we be erase()'ing when you use the (top-left) close button in Custom Tabs? Do we want the FAB?

**Comment by ahunt** [comment]
For 2: yes, we do want to erase, so I'm dropping that commit from #616.

**Comment by pocmo** [comment]
It looks like everything is working as intended here.
