### ISSUE TITLE
Fingerprint auth does not protect the home screen (shortcuts)

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#6166]
## Steps to reproduce
1. Add a few shortcuts to Focus.
2. Enable fingerprint auth.
3. Swipe away Focus and re-open the app.

### Expected behaviour
- The user sees the fingerprint auth. (UX, is this a correct expectation?)

### Actual behaviour
- There is no auth needed to see your shortcuts.

### Device information

* Android device: All devices
* Focus version: All nightly versions.

**Comment by amedyne** [comment]
@jeffreygee Thoughts on this?

**Comment by jonalmeida** [comment]
Clarification: the reason this is a new issue, is because previously we never had any personal or identifiable data on the Focus home screen. With the addition of Shortcuts,  a user can have information on the home screen that they might not want to be accessible when they have the security auth feature turned on.

**Comment by jeffreygee** [comment]
@amedyne @jonalmeida I'm thinking if we're going to be more privacy/security-focused, this tool should be more flexible. If I was turning this feature on as a user, I would expect that any entry points (either opening the app for the first time or returning to the app) would trigger this. That way it's not page or shortcut based - it's more of a general security feature. Thoughts on this? Happy to discuss

**Comment by jonalmeida** [comment]
That's the direction I was headed towards as well. 👍 

i.e. if the feature is enabled, any visit to the app should require auth.

**Comment by iorgamgabriel** [comment]
So I made the changes . If the user has at least one Shortcut , the lockscreen will appear every time the user enters in the app , doesn't matter the last visited screen .

**Comment by iorgamgabriel** [comment]
<img src="https://user-images.githubusercontent.com/8118371/162430818-46307f9c-eaca-4786-aaf7-35e7559c4076.jpg" width="300" height="600" />

**Comment by iorgamgabriel** [comment]
I think the text "Your fingerprint can unlock Focus  if a URL is already opened in the app. Stealth will be turned on." should be changed . @amedyne @jeffreygee

**Comment by lobontiumira** [comment]
This issue is not fixed yet. Tested on the latest Focus Nightly build from 4/13 with Oppo Find X3 Lite (Android 11), and Samsung Galaxy Note 8 (Android 9).
The STR are:
1. Set a fingerprint auth on the device.
2. Enable the "Use fingerprint to unlock app" on Focus.
3. Open a page, and set is as a shortcut.
4. Close Focus, by swiping away from the recent apps.
5. Re-open Focus.

The user can easily see the shortcuts, and open them. If Focus is minimized, then re-opened, then the fingerprint authentication is required.
Please see the short video below:

https://user-images.githubusercontent.com/40694158/163135375-e2e31bd3-bc19-4ec8-9202-c5689e1575dd.mp4

**Comment by jeffreygee** [comment]
> I think the text "Your fingerprint can unlock Focus if a URL is already opened in the app. Stealth will be turned on." should be changed . @amedyne @jeffreygee

I can work with the content team for a new string, Thanks!

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 101.0a1 (build 361170511 with GV 101.0a1-20220423065829) with the following devices:
* Oppo Reno 6 (Android 12), and
* Samsung Galaxy Note 8 (Android 9).

After Focus is swiped away, re-opening it, asks the user for the fingerprint without displaying any information.

**Comment by jeffreygee** [comment]
Still working on getting a new string (Content person was OOO this past week) - thanks!

**Comment by iorgamgabriel** [comment]
I created a new ticket for the text change https://github.com/mozilla-mobile/focus-android/issues/7057 . I will close this one because the bug is fixed and verified by the QA. @jeffreygee @amedyne
