### ISSUE TITLE
Fingerprint auth prompt cuts off 'New session' on some screens.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#6167]
## Steps to reproduce
1. Enable finger print auth.
2. Open a site and leave app.
3. Return to the app.

### Expected behavior
- The fingerprint auth prompt has the 'New Session' text fully visible.

### Actual behavior
- It is not. See screenshot:
<img src='https://user-images.githubusercontent.com/1370580/148270884-21ee0a1d-2a08-411b-b2b7-5270fea92e55.png' width=320 />

### Device information

* Android device: Pixel 3, Android 12
* Focus version: Nightly 97

**Comment by jonalmeida** [comment]
Maybe we should just rely on the native fingerprint prompt? When this was added, the API was still new. The OS now has been biometric prompt support that we use in Fenix as well.

See `BiometricPromptFeature`.

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on Beta 97.0.0-beta.1 with Oppo Find X3 Lite (Android 11).

**Comment by lobontiumira** [comment]
We were able to reproduce on Oppo Find X3 Lite (Android 11), and Google Pixel 6 (Android 12), on the latest Focus Nightly from 1/20.
Not on Google Pixel (Android 10).

**Comment by iorgamgabriel** [comment]
Now Focus is using FingerprintManagerCompat , this is deprecated now . To fix this bug and refactor all the FingerprintManagerCompat part we need to use , like @jonalmeida  suggested : BiometricPromptFeature. This is how will look like . @jeffreygee  It's this ok for you ?

**Comment by iorgamgabriel** [comment]
<img src="https://user-images.githubusercontent.com/8118371/163823700-e76362de-f732-42eb-ba35-dae9668c8202.jpg" width="300" height="600" />

**Comment by jonalmeida** [comment]
> Now Focus is using FingerprintManagerCompat , this is deprecated now . To fix this bug and refactor all the FingerprintManagerCompat part we need to use , like @jonalmeida suggested : BiometricPromptFeature. This is how will look like . @jeffreygee It's this ok for you ?

@iorgamgabriel please upstream the BiometricPromptFeature to android components instead of copying the code over. 🙂

**Comment by jeffreygee** [comment]
@iorgamgabriel Is all of the content customizable on this popup - more specifically the CTA text of 'New Session'?

**Comment by jeffreygee** [comment]
Question about the current flow too - so the way this currently works is that if a users taps 'New Session' it technically restarts the session. But doesn't this also mean that an outside user can technically come in and hit that and see the user's saved shortcuts without the fingerprint?

**Comment by iorgamgabriel** [comment]
Yes all the texts can be custom . "But doesn't this also mean that an outside user can technically come in and hit that and see the user's saved shortcuts without the fingerprint? " for these I made a fix https://github.com/mozilla-mobile/focus-android/issues/6166 . @jeffreygee

**Comment by iorgamgabriel** [comment]
I think this is how it should like and behave with the refactoring from FingerPrint to Biometric .

Acceptance Criteria : 

1.As a user if I have  a browsing session open or at least one  shortcut on the home screen and I close the app the lockscreen with Biometric will appear.   

<img src="https://user-images.githubusercontent.com/8118371/166637192-3c6b03f5-315f-4c7d-a271-8be312e510bb.png" width="300" height="600" />

2.If the user enters corre

**Comment by jeffreygee** [comment]
@iorgamgabriel I think this flow makes sense to me. With scenario 4, if the user closes the app and reopens it again, will it trigger step 1 all over again?

**Comment by iorgamgabriel** [comment]
It will not trigger again  step 1 . The app will be in the initial state without FingerPrint

**Comment by jeffreygee** [comment]
@iorgamgabriel If (before the user clears cache data), the user fails fingerprint and passcode and just hard closes the app, but then reopens the app again, it'll start from Step 1 though right?

**Comment by iorgamgabriel** [comment]
@jeffreygee Yes , if the user doesn't clean cache data .

**Comment by jeffreygee** [comment]
@iorgamgabriel what's your rationale on #2 (As a user if I click onside the biometric Prompt (the grey pop-up with the fingerprint icon) this will appear)?

I was thinking that the natural reaction to getting the prompt for the fingerprint would be either closing the app via hitting home/back button, or putting in a PIN. This hitting outside the prompt seems unnecessary and I think we should limit the flow a bit here. But if this is a necessary fallback, we can proceed.

**Comment by iorgamgabriel** [comment]
This is the behaviour of BiometricPrompt . I can't force it to stay on the screen if the user clicks outside . @jeffreygee

**Comment by jeffreygee** [comment]
@iorgamgabriel I mocked up the similar flow (on dark mode) [here](https://www.figma.com/file/dPV9Rn2rzrRsvwQ6SI8EzO/Fingerprint-Auth-Flow?node-id=0%3A1)

**Comment by iorgamgabriel** [comment]
So when BiometricPrompt is visible will be the Logo and "Firefox Focus" and when it's not will be only the logo? This is correct ? Will not be the two buttons one for Login and the oder for Cancel?  @jeffreygee

**Comment by jeffreygee** [comment]
Adding a note here that updates to the flow have been discussed with @iorgamgabriel and updated on the [Figma](https://www.figma.com/file/dPV9Rn2rzrRsvwQ6SI8EzO/Fingerprint-Auth-Flow?node-id=3%3A3998)

**Comment by lobontiumira** [comment]
Hi all!
I've verified on the latest Focus Nightly 104.0a1 (build 361811708 with GV 104.0a1-20220630095519) with Oppo Reno 6 (Android 12), and Oppo Find X3 Lite (Android 11), and here are the results:
* after the user returns to the Focus Nightly app, only the logo, the name of the app, and the "Unlock" button are displayed like in screenshot 1,
* tapping the "Unlock" button triggers the prompt from screenshot 2,
* if the user taps on "Cancel" from the prompt, the "Authentication canceled" is displayed like in screenshot 3:

![fingerprint](https://user-images.githubusercontent.com/40694158/176843445-13d9c000-5cca-4206-b258-8813b284f80a.png)

* if the user's fingerprint isn't recognized, then the option for the Password/PIN is available - see the screenshot below:

![Screenshot_5](https://user-images.githubusercontent.com/40694158/176843857-2f0d7be4-5831-4682-9dc1-05e12435f59c.jpg)

@jeffreygee @iorgamgabriel I do have a concern. In [Figma designs](https://www.figma.com/file/dPV9Rn2rzrRsvwQ6SI8EzO/Fingerprint-Auth-Flow?node-id=3%3A3998) the "Use PIN" option is available to the user from the moment the app is accessed. I did not see this option until the device did not recognized the fingerprint.

![Screenshot_4](https://user-images.githubusercontent.com/40694158/176844372-16a3ee3a-d13b-4ea0-a36e-541c0714fdee.jpg)

**Comment by iorgamgabriel** [comment]
From what I saw in fenix they have another flow if the user doesn't have a fingerprint enrolled in the app . 
If the user have a pin or a password he can see the credit cards with that . 
In focus in the old implementation and I kept the same flow in the new one , the user can't unlock the app if he doesn't have a fingerprint enrolled. 
Should we support this ? I think this should be another feature. @amedyne @jeffreygee @jonalmeida

**Comment by iorgamgabriel** [comment]
"@jeffreygee @iorgamgabriel I do have a concern. In [Figma designs](https://www.figma.com/file/dPV9Rn2rzrRsvwQ6SI8EzO/Fingerprint-Auth-Flow?node-id=3%3A3998) the "Use PIN" option is available to the user from the moment the app is accessed. I did not see this option until the device did not recognized the fingerprint." 
This depends on Biometric implementation from android . It is different from a phone to another.

**Comment by lobontiumira** [comment]
Thank you for the clarification.
Closing this ticket as complete and verified.

**Comment by lobontiumira** [comment]
This is now implemented in Beta 104.0b1 also.
Tested with Samsung Galaxy Note 8 (Android 9).
