### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [mozilla-mobile/focus-android#617]
Can you please fix [these issues](https://gitlab.com/fdroid/rfp/issues/171#note_30410376) in order to include Firefox Focus to [F-Droid](https://f-droid.org/) app store? 
Thanks.

**Comment by IzzySoft** [comment]
Or at least add an `.apk` to the `releases/` page (with releases, that is – otherwise, in the repo itself would still be better than nowhere)?

**Comment by pocmo** [comment]
There hasn't been a release yet. So there's nothing to upload. :)

**Comment by IzzySoft** [comment]
Oh. That might explain things. Any estimates on when to expect something, if I might ask? "Orders of magnitude" accepted (within the next few weeks / after the summer vacations / end of year / …) :wink:

**Comment by pocmo** [comment]
It's not too far away. In fact I just uploaded the first RC build for v1:
https://github.com/mozilla-mobile/focus-android/releases

**Comment by IzzySoft** [comment]
Any objections that I take it into my F-Droid compatible [App-Repo](https://android.izzysoft.de/repo)? Or shall I rather wait for the final release? Btw: doesn't "clash" with the official repo, if you aim for the latter (which I recommend in addition) – but if you want me to "remove" it from mine once it's listed in the official one, no bad feelings :innocent: Difference is of course the signing: in my repo, it's your signature (as I don't "rebuild" the APK), so cross-updates are possible with e.g. Playstore or manual download from here – while in the official repo, it will be F-Droid's signature. Oh, and usually updates appear much sooner in my repo, as F-Droid seems to have issues with their build server quite frequently (as currently: no updates within the last 5 days).

**Comment by IzzySoft** [comment]
@pocmo is there a reason you've stopped attaching the `.apk` files to their corresponding releases? Remember that some of the privacy-focused (oops) people for that very reason do not use Google Play, and AFAIR you're not on the official F-Droid repo (yet). Could you please attach at least the latest one (RC4), and then continue attaching the APK for future releases? Thanks!

**Comment by andreicristianpetcu** [comment]
[RSS feed](https://github.com/mozilla-mobile/focus-android/releases.atom) for who wants to follow the releases outside the Google Play Store.

**Comment by IzzySoft** [comment]
@andreicristianpetcu nice, but no APKs there.

**Comment by rugk** [comment]
So {it has been released officially](https://blog.mozilla.org/blog/2017/06/20/firefox-focus-new-to-android-blocks-annoying-ads-and-protects-your-privacy/) (on Google Play), but still not available on F-Droid.

So please get rid of these closed-source telemetry libs and remove the gecko AAR and provide the source code instead of binary blobs (at least when you'll switch to Gecko…, currently you could ignore it at all.)

**Comment by pocmo** [comment]
> @pocmo is there a reason you've stopped attaching the .apk files to their corresponding releases? 

No, I was just on PTO while the other builds where made / distributed. I'm planning to upload them too.

> So please get rid of these closed-source telemetry libs and remove the gecko AAR and provide the source code instead of binary blobs (at least when you'll switch to Gecko…, currently you could ignore it at all.)

The telemetry library is not closed-source (Nothing referenced from this repository is, even though we do drop the AARs in here until we can publish them to a public maven repository):
https://github.com/mozilla-mobile/telemetry-android

**Comment by rugk** [comment]
> until we can publish them to a public maven repository

Then do so…

**Comment by IzzySoft** [comment]
@pocmo thanks! Looking forward to that (both: your uploading, and the auto-processing via Maven) – so us Google-less folks can at least have the updates at about the same time the Playstore folks receive them :innocent:

@rugk I read the "until we can" as "we're already working on it". Guess unless they can hire someone from Hogwards, that means some work to be done so everything turns out right :wink:

**Comment by pocmo** [comment]
The APKs are now available here (The same ones that are available via Google Play):

Additionally I created a PR for replacing the telemetry AAR with a public dependency that gets pulled in from jcenter.

FWIW the klarWebkitRelease flavor should fulfill the F-Droid requirements.

**Comment by IzzySoft** [comment]
Thanks a lot, @pocmo – I just triggered a manual update for my repo, and they are now there as well :wink:

And yes, IMHO you're correct for Klar to meet F-Droid criteria. Why not file a request with them in their [RFP repo](https://gitlab.com/fdroid/rfp) at GitLab? Focus wouldn't make it (GMS, Adjust) – but Klar should be fine. Maybe telemetry could be an issue, but they should let you know then.

**Comment by IzzySoft** [comment]
@pocmo As you explicitly showed interest, I've [created an issue with RFP](https://gitlab.com/fdroid/rfp/issues/235) to have *Klar* included with the official repo. If one of your team has an account on GitLab, be welcome to "chime in" and confirm you support inclusion. I've just verified with your documentation: as telemetry should be off by default with *Klar,* all criteria should be met (as I pointed out in the linked issue).

**Comment by andreicristianpetcu** [comment]
Does Klar have an English version or only German?

**Comment by dimqua** [comment]
@andreicristianpetcu Yes.

**Comment by IzzySoft** [comment]
Never ask a Vorlon a question with an "or" in it, right @dimqua ? :stuck_out_tongue_winking_eye: To which part of @andreicristianpetcu's question does your "yes" belong?

**Comment by dimqua** [comment]
@IzzySoft Klar have an English translation as well as many others (at least Russian).

**Comment by IzzySoft** [comment]
@dimqua cool, thanks! Could well have been that *Klar* was "German only", as it targets D-A-CH (Germany, Austria, Switzerland), and *Focus* is declared the international version. So good to know!

**Comment by IzzySoft** [comment]
OK, seems we succeeded: *Klar* [was taken into the officially repo](https://gitlab.com/fdroid/fdroiddata/merge_requests/2363) half an hour ago.

:tada: **Congratulations!** :tada:

If you don't mind, I'll keep it in mine as well (with your signature, so folks who want to leave the Google world can easily cross-update). If you don't want that, just let me know (here in this issue, which I still monitor).

**Comment by pocmo** [comment]
Great! Thank you for your help with that. I'm going to close this issue here.

> If you don't mind, I'll keep it in mine as well (with your signature, so folks who want to leave the Google world can easily cross-update). If you don't want that, just let me know (here in this issue, which I still monitor).

Yeah, that's fine!

**Comment by andreicristianpetcu** [comment]
For the people in this thread who do not refresh the F-Droid repo daily I can tell you that you can install Firefox Klar now. Just refresh it and search for it.

**Comment by IzzySoft** [comment]
@pocmo As the app is now well established in the "official repo", I'll "unlist" *Firefox Klar* in mine. If need arises, contact me anytime to have it re-listed. With *Firefox Focus* not being in the official repo, I'll keep it in mine unless you want me to "unlist" it as well (in that case, just let me know).
