### ISSUE TITLE
Intermittent UI test failure - EraseBrowsingDataTest.trashButtonTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#6175]
### Firebase Test Run:
Flaky, crashed 1/2 runs
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8590276559719654942/executions/bs.92acd47a9a36406b/testcases/1/logs
### Stacktrace:
Test crashed:
[logcat.txt](https://github.com/mozilla-mobile/focus-android/files/7822953/logcat.txt)

### Build:
1/6/22

**Comment by AndiAJ** [comment]
Closing as it didn't fail for a couple of months
