### ISSUE TITLE
Not Locking the Browser

### ISSUE THREAD

**Issue by Aarav-USA** [mozilla-mobile/focus-android#6188]
When you lock the browser with touch/face ID and you go to the open applications menu (iOS) I can still see the content in the app regardless of the lock or not.

**Comment by cadeyrn** [comment]
That's the issues tracker for Focus on iOS:
https://github.com/mozilla-mobile/focus-ios/issues

**Comment by jonalmeida** [comment]
Closing. Please file in the iOS project (linked above).
