### ISSUE TITLE
Implement Material You theming

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#6190]
https://developer.android.com/jetpack/androidx/releases/compose-material3

Material You is available on Android 12: https://developer.android.com/about/versions/12

More info: https://material.io/blog/announcing-material-you

Note: This is could be first implemented for composable components: https://developer.android.com/jetpack/compose/themes/material#material3

**Comment by mcarare** [comment]
Depends on https://github.com/mozilla-mobile/focus-android/issues/4760.

**Comment by mcarare** [comment]
This is unblocked now. Will re-evaluate the priority.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802001

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
