### ISSUE TITLE
Modify Onboarding Card: New Users

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6205]
Update Focus Onboarding card to comply with the new design.

Figma file for reference is [here](https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding-2022?node-id=2647%3A11565).

Ensure that text corresponds to latest content.

**Comment by amedyne** [comment]
Tagging @jeffreygee if in case new designs come up.

**Comment by ionutbedregeanu** [comment]
I will move this ticket back to backlog because now I need to work on https://github.com/mozilla-mobile/focus-android/issues/6223

**Comment by ionutbedregeanu** [comment]
@jeffreygee The logo used in the onboarding card should be the same for all builds(Beta, Nightly, etc)?

**Comment by jeffreygee** [comment]
@ionutbedregeanu - let's keep using the individual logos and name of the app in the cards to avoid confusion between versions

Current design is for both themes, but I'm currently working with the accessibility team to confirm we can use the same components across both.

**Comment by ionutbedregeanu** [comment]
> @ionutbedregeanu - let's keep using the individual logos and name of the app in the cards to avoid confusion between versions
> 
> Current design is for both themes, but I'm currently working with the accessibility team to confirm we can use the same components across both.

@jeffreygee Can you help me with a Figma link where I can find all the logos(Focus and Klar, all builds)?

**Comment by ionutbedregeanu** [comment]
In the drive folder they have a background and I need only the logo. Should I let as it is(the same logo for all builds) and make a ticket to update this logo in the future?

**Comment by jeffreygee** [comment]
![Beta](https://user-images.githubusercontent.com/93741573/152284163-40a9249c-650c-499e-a0f1-928d3fb4af56.svg)
![Focus](https://user-images.githubusercontent.com/93741573/152284164-bbdb40e9-9aa5-4db7-b2cd-d2f35ab3aa6a.svg)
![Nightly](https://user-images.githubusercontent.com/93741573/152284165-1b4ad369-423e-4f16-af00-f3fbaa9c7f81.svg)

**Comment by ionutbedregeanu** [comment]
@jeffreygee The last one(Nightly) can't be imported
Error: The image may be incomplete:Error@line109 <symbol> is not supported

**Comment by jeffreygee** [comment]
@ionutbedregeanu not sure why that's the only one erroring - is there another format I can provide?

**Comment by ionutbedregeanu** [comment]
We prefer SVG because one single resource can be used for all screen ratios. For png, jpg we need to import a resource for every density(mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi) which is not memory friendly

**Comment by jeffreygee** [comment]
@ionutbedregeanu can we try this version?
![Nightly](https://user-images.githubusercontent.com/93741573/152882520-bf98fecc-4197-47b7-92b6-0cedac92caff.svg)

**Comment by ionutbedregeanu** [comment]
> @ionutbedregeanu can we try this version? ![Nightly](https://user-images.githubusercontent.com/93741573/152882520-bf98fecc-4197-47b7-92b6-0cedac92caff.svg)

This one Is ok. Thanks!

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 99.0a1 (build 360260510 with GV 99.0a1-20220302065857) with several devices:
* Samsung Galaxy Note 8 (Android 9),
* Lenovo Tab M10 (Android 10),
* Oppo Find X3 Lite (Android 11),
* Sony Xperia Z5 Premium (Android 7.1.1).

I've filed #6561 for the discrepancies on dark mode.
