### ISSUE TITLE
Switching between Onboarding tour tips should be smoother 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6206]
## Steps to reproduce
1. Have a fresh install.
2. Launch Firefox Focus.
3. Rotate the device in Landscape mode.
4. Switch between the onboarding tour tips and observe the transition.

### Expected behavior
The transition should be smooth.
### Actual behavior
The transition is not done smoothly, the previous tip is partially displayed on the left side of the screen when switching tips.
The issue is more visible in Landscape mode, but it is also noticeable in Portrait mode.
### Device information

* Android device: Google Pixel 6 (Android 12).
* Focus version: 97.0.0-beta.1, RC 96.1.1.

https://user-images.githubusercontent.com/89388888/149170242-57b3b482-871b-4131-8668-11ae2e599133.mp4

**Comment by amedyne** [comment]
There are plans of updating the onboarding behavior. Will close this once the new one is implemented.
