### ISSUE TITLE
CFR for Shield Icon

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6208]
This is part of the onboarding updates.
Display CFR(Contextual Feature Recommender)/Tool tip to lead users to browser tracking/privacy information, settings and data. 

<img width="329" alt="Screen Shot 2022-01-12 at 11 56 34 AM" src="https://user-images.githubusercontent.com/68711330/149186141-44e21f50-d281-4b24-863b-5e6959b96651.png">

Figma design [here](https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding-2022?node-id=2647%3A11565).

@jeffreygee please add comment or update once behavior on the following is finalized:

- [ ] condition/trigger when the CFR appears
- [ ] behavior to dismiss the CFR (click on X or click anywhere on the screen)

**Comment by jeffreygee** [comment]
**Trigger logic**: for any new user, CFR will pop up on the first site where a tracker is logged. 
**Behavior to dismiss**: CFR can be dismissed by tapping a ‘close’ icon in the opposite corner of the pointer, or anywhere outside of the CFR. Once dismissed, will not be shown again.

**Comment by iorgamgabriel** [comment]
Hi @jeffreygee ,
The ratio between text color and background color of the CFR isn't very good . I get a warning from Accessibility Scanner App . I think  this contrast should be improve . 
Thank you very much
@amedyne

**Comment by jeffreygee** [comment]
> Hi @jeffreygee , The contrast ratio between text color and background color of the CFR isn't very good . I get a warning from Accessibility Scanner App . I think this contrast should be improve . Thank you very much @amedyne

Designs are with the accessibility team for recommendations on that - definitely something that's being looked into. thank you!

**Comment by delia-pop** [comment]
Tested on Firefox Focus Nightly 98.0 (Build 360330514 🦎 98.0a1-20220201093942) with several devices.

The following were observed and several issues were reported as follows:
- The CFR pops up when accessing a webpage, but is not correctly placed: #6332
- The CFR is not properly displayed on tablets: https://github.com/mozilla-mobile/focus-android/issues/6333
- The CFR can be dismissed by tapping its "X" icon or by tapping outside the prompt, except on Android 5 tablet, where tapping outside the prompt will not dismiss it: https://github.com/mozilla-mobile/focus-android/issues/6334
- The CFR for Shield may cause the "Your Rights" page to be incorrectly displayed on a specific tablet: https://github.com/mozilla-mobile/focus-android/issues/6335
