### ISSUE TITLE
Add "Stealth mode" info to First Run

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#621]
From @brampitoyo in Issue #501 

Having looked at all the app examples above, I had to revert to a very simple solution: make Secure Mode a part of onboarding along with a few tweaks.

![first run 4 - mdpi](https://cloud.githubusercontent.com/assets/51007/26291926/b91b92dc-3efd-11e7-8988-461abfc0a4c7.png)

* Make it a checkbox
* Rename it to “Stealth: block screenshots and hide on Recent Apps”
  * Explanation copy: “Be very stealthy. You won’t be able to take screenshots, and Firefox Focus will hide itself on the list of Recent Apps.”
* Make it clear that you can revert easily: “To change this, go to Settings.”
* The copy on the Settings page should be the same as the onboarding step.

Visually, my mockup doesn’t look the best. We’ll have to think of a good layout for it.

Thoughts, @antlam and @pocmo?

**Comment by antlam** [comment]
Since this won't make V1, let's make sure we get eyes from @mheubusch and Sean on this earlier rather than later :)

**Comment by antlam** [comment]
^Adding needs triage tag for deadline and prioritization (cc @bbinto @brampitoyo )

**Comment by brampitoyo** [comment]
Let’s revise the mock slightly to incorporate new string from @mheubusch and add a clear call-to-action.

![first run stealth - mdpi](https://cloud.githubusercontent.com/assets/51007/26379575/9aed58d6-4065-11e7-8aa0-74222e15df0e.png)

I feel conflicted about this. On one hand, it’s great that we explain why the user might not be able to take screenshots in Firefox Focus. On the other hand, we run the risk of making stealth too easy to turn off (which may compromise user privacy at the end of the day).

Thoughts?

**Comment by mheubusch** [comment]
In the other tour panels we indicate how to do something but don't provide the control itself. We could take that approach here. Turn off stealth mode in settings . .

**Comment by brampitoyo** [comment]
Thanks, @mheubusch. Removing the control does make the page look better.

![first run stealth - mdpi](https://cloud.githubusercontent.com/assets/51007/26380018/c8a4b286-4067-11e7-8d6e-6084ca390978.png)

**Comment by mheubusch** [comment]
I added writing a headline and adding the illustration to the UX content trellis board and will revisit closer to the deadline for this. Thanks Bram!

**Comment by pocmo** [comment]
One minor nit: ".. and see Firefox Focus in your Recent Apps list". To me (But I'm not a native speaker!) it sounds like Focus does not show up in "recent apps" at all - although it does and we only hide the content (For some screens the content actually shows up because it's not privacy relevant - like the settings screen). Technically it's also possible to hide the app in "recent apps" completely (but we don't do that because it would make switching between Focus and other apps a painful experience) and therefore I wonder whether we should be more explicit about hiding content inside the app?

**Comment by mheubusch** [comment]
Thanks for the clarification, Sebastian.  is it accurate to say:  “and see sites you’ve visited using Focus in your Recent Apps list"

**Comment by ekager** [comment]
Another intern told me she was frustrated that Focus for Android didn't let her take screenshots, I definitely think this should be included soon!

**Comment by antlam** [comment]
<img width="402" alt="screen shot 2017-08-09 at 2 52 52 pm" src="https://user-images.githubusercontent.com/1994820/29108642-747370a2-7d12-11e7-9fff-3e5aef3a4a85.png">

Got the illustration from Martell, copy TBD. 

CC/ @mheubusch

**Comment by bbinto** [comment]
#835 will have the strings posted by @mheubusch

**Comment by antlam** [comment]
All the content is in #835 so I'm closing this to track it all together easier.
