### ISSUE TITLE
about:config is blocked on Firefox Focus Beta for Android

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/focus-android#6210]
## Steps to reproduce
Install Firefox Focus Beta through early access on the Play Store. In this case it's version 96.0.0-beta5.
### Expected behavior
Access to about:config is unrestricted as in Firefox Beta for Android.
### Actual behavior
User gets a grey screen with no access to about:config.
### Device information

* Android device: Pixel 6 Pro with Android 12 and December 2021 updates
* Focus version: 96.0.0-beta5

<img width=340 src=https://user-images.githubusercontent.com/3611312/149190724-c070791b-fdf5-4a65-b38c-4332a19232fd.png />

**Comment by jonalmeida** [comment]
I believe we should be enabling this for beta and nightly but the current configuration has it for nightly only.

**Comment by lobontiumira** [comment]
This is not working yet: on Beta 97.0.0-beta.6 the about:config is displaying a blank page.
Tested with Lenovo Tablet M10 (Android 10):

![6210](https://user-images.githubusercontent.com/40694158/152941590-34729d52-2403-4bb3-84d4-312615624b3f.png)

**Comment by lobontiumira** [comment]
The about:config page is blank in RC 97.1.1.

On Beta 98.0.0-beta.2, the about:config is loading, and is functional. Tested with Lenovo tab M10 (Android 10), and Samsung Galaxy Note 8 (Android 9):

![Screenshot_2](https://user-images.githubusercontent.com/40694158/154022463-323c05df-ed8f-4a1f-afd2-43bf39fb582a.jpg)
