### ISSUE TITLE
Tool Tip for: Privacy and Security Settings page

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6211]
Display Inline tool tip on the Privacy and Security Settings page.
<img width="318" alt="Screen Shot 2022-01-12 at 1 35 39 PM" src="https://user-images.githubusercontent.com/68711330/149201389-e6b5d804-af41-4464-a465-7620e1de24cb.png">

Figma design [here](https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding-2022?node-id=2522%3A7249).
Content/Strings is still being finalized.

@jeffreygee please add comment or update once behavior on the following is finalized:

- [ ] condition/trigger when the CFR/tool tip appears
- [ ] behavior to dismiss the CFR/tool tip (click on X or click anywhere on the screen)

**Comment by jeffreygee** [comment]
**Trigger logic**: This will be an inline CFR that is triggered by a new updated version. The user will see it within the Privacy & Security window above the configurable settings. 
**Behavior to dismiss**: CFR can be dismissed by tapping a ‘close’ icon in the opposite corner of the pointer, or anywhere outside of the CFR. Once dismissed, will not be shown again.
