### ISSUE TITLE
Firefox crash notification is not displayed on devices with Android 11/Android 12

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6215]
## Steps to reproduce
1. Open several tabs.
2. Insert  about:crashparent in the URL field.
### Expected behavior
The app is closed, and the crash dialog notification is displayed in the notification bar.
### Actual behavior
The app is closed, but the crash dialog notification is not displayed in the notification bar.
### Device information

* Android device: Google Pixel 6 (Android 12), Oppo Find X3 Lite (Android 11)
* Not reproducible on Google Pixel (Android 10)
* Focus version: Focus Beta 97.0.0-beta.1, Fenix Nightly 97

https://user-images.githubusercontent.com/89388888/149341206-eac8ee41-9458-478c-97c6-64d08d68ddba.mp4

**Comment by delia-pop** [comment]
Reproducible in Beta 97.0.0-beta.2 with Google Pixel (Android 12).

**Comment by delia-pop** [comment]
Reproducible on Beta 97.0.0-beta.4 with Motorola Moto G30 (Android 11).  The crash notification is only displayed in the notification bar for a short period of time, until the crash report is sent to Mozilla.

https://user-images.githubusercontent.com/89388888/150969295-6004db09-2cf0-44da-9785-1f47b14e889f.mp4

**Comment by delia-pop** [comment]
Reproducible on RC 96.3.0 with Google Pixel 6 (Android 12).

**Comment by delia-pop** [comment]
This is still reproducible on Firefox Focus Nightly 98.0 (Build 360310515 🦎 98.0a1-20220130093554) with Google Pixel 6 (Android 12) and Motorola Moto G30 (Android 11).

Google Pixel 6 (Android 12): The crash dialog notification is not displayed in the notification bar at all.

https://user-images.githubusercontent.com/89388888/151775025-b2e182fe-c76f-416a-9912-8c0afe7a1cc2.mp4

Motorola Moto G30 (Android 11): The crash notification is only displayed in the notification bar for a short period of time, until the crash report is sent to Mozilla.

https://user-images.githubusercontent.com/89388888/151775029-d7e2719d-fc07-4eca-9ea7-5384b7918e62.mp4

**Comment by Mugurell** [comment]
The issues seen on Android 12 might be because of https://github.com/mozilla-mobile/android-components/issues/11666
The PendingIntent mutability rules should not affect Android 11 though so maybe there's another bug there in which case the logs for around that period will be helpful.

**Comment by delia-pop** [comment]
Tested on Focus Nightly 98.0 from 02/04 with Motorola Moto G30 (Android 11) to provide the log.

I could no longer reproduce this, as the crash notification remained displayed permanently in the notification bar.
[MotoG30.txt](https://github.com/mozilla-mobile/focus-android/files/8004539/MotoG30.txt)

https://user-images.githubusercontent.com/89388888/152562954-a26edb7c-f36e-459d-8275-aa05b3792156.mp4

**Comment by delia-pop** [comment]
Verified as fixed on Firefox Focus Nightly 98.0 (Build 360390514 🦎 98.0a1-20220207065816) with Google Pixel 6 (Android 12) and Motorola Moto G30 (Android 11).
The Firefox crash notification remains displayed in the device's notification bar and can be accessed.
