### ISSUE TITLE
Add a counter for searches

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6229]
After migrating to Glean there is no one probe to report the total number of searches irrespective of the source.

As a requirement from DS and to bring Focus' telemetry in line with the one from other mobile clients we should add a new `search_count` counter similar to the one of Fenix - https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/metrics_search_count

**Comment by lobontiumira** [comment]
Verified on the latest RC 96.2.0 with Samsung Galaxy Note 8 (Android 9):

```
"labeled_counter": {
          "browser.search.search_count": {
            "action": 4
          },
          "browser.search.in_content": {
            "duckduck
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2201190004)
Glean ping to URL: /submit/org-mozilla-focus/metrics/1/60d0959f-ec9c-4988-850c-6ba3a255e63d [Part 1 of 2]
Glean ping to URL: /submit/org-mozilla-focus/metrics/1/60d0959f-ec9c-4988-850c-6ba3a255e63d [Part 2 of 2]

**Comment by mcarare** [comment]
Reopening for QA testing after the fix in https://github.com/mozilla-mobile/focus-android/pull/7538

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 106.0a1 from 8/30 with Samsung Galaxy Note 8 (Android 9):
 ```
"browser.search.search_count": {
            "duckduckgo.action": 3,
            "duckduckgo.suggestion": 1,
            "google.action": 1,
            "google.suggestion": 1
          }
```


```
"string": {
          "preferences.user_theme": "Follow device",
          "browser.install_source": "com.google.android.packageinstaller",
          "browser.locale_override": "none",
          "browser.default_search_engine": "DuckDuckGo"
        }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-0005)
