### ISSUE TITLE
Language Selection Español

### ISSUE THREAD

**Issue by mikevelasquez02** [mozilla-mobile/focus-android#623]
When selecting Español in the Language Selection Setting, the app is set to English. If I select a region related Español, for example Español (Argentina), it is set correctly.

**Comment by pocmo** [comment]
This seems to work correctly for me.

To help us debug this: What device and Android version are you using? And what build of Focus?

**Comment by ahunt** [comment]
I can repro:
1. I'd assumed values-es means we need to list es as a locale (we also have es-ES, es-MX, etc)
2. values-es actually only contains urls.xml which is our sumo URLs.

**Comment by ahunt** [comment]
Thanks for spotting this, we've removed the general Español, and you should only see the region specific versions in future!

**Comment by ahunt** [comment]
It turns out we have the same for pt vs pt-BR (although pt-BR is the only portugese variant we offer), and hi vs hi-IN. Both of those will be fixed when the build-time locale detection in #122 lands.
