### ISSUE TITLE
Investigate ways to reduce APK size

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#624]
Our APK is already pretty small (Focus: 2.6M, Klar: 2.3M) - It might grow a little as soon as we add more languages and the onboarding images. However there seems to be an opportunity for marketing if we end up with an APK that is smaller than other "mini" Android browsers. So let's see if there are any quick wins.

- [x] Proguard: Shrinking - This should noticeable reduce the size by removing unused code. However we need to make sure to not break the app because of missing dependencies
- [x] Proguard: Optimiziation - I guess this won't affect the size but might be worth doing when running proguard anyways
- [x] Proguard: Obfuscation - It's unlikely that we are going to do that (it makes debugging harder) but it would be interesting to measure if it affects size (the shorter labels should/could).
- [x] Proguard: Use proguard-android-optimize.txt (~37 kB)
- [x] Run ImageOptim on all images - if we haven't already
- [x] ~Disable pngcruncher, we already know that it might make optimized images bigger again, let's avoid that~ (No advantage for us, no need to disable with aapt2)
- [ ] Run lint or similar tools to identify unused resources/strings etc. and actually remove them
- [x] Watch I/O 17 talk about reducing APK size and see if there's more we can do: https://www.youtube.com/watch?v=AdfKNgyT438
- [ ] Replace some PNGs with vector images if possible (onboarding images perhabs?)
- [ ] Use lossless WEBP where we can't use vector drawables
- [ ] APK splits (via gradle "splits" configuration)? It's cumbersome to handle all those APKs - but it would be interesting to measure at least.
- [x] Set resConfig to the languages we want to add (and remove unwanted or not completely translated languages - especially translations in libraries that we do not need) - However this would require that we somehow dynamically determine which languages we actually want at build time. Or keep a list of languages somewhere. (-137 KB)
- [x] Minify blocklists (in APK). They are formatted nicely for humans but we could strip a lot of whitespaces etc. from them. They are ~470kB (uncompressed) - So we might not save many bytes (after compressing) (Can be minified to < 200 KB, but in the compressed APK we only save about 5 KB)
- [ ] Try using aapt2 (resource version collapsing [remove resources from libraries etc. that are not needed for the minSdkVersion], resource deduplication [e.g. same strings in es-ES and es-MX will be merged into "es" only], better cruncher [no need to disable anymore])
- [x] Run the APK analyzer from Android Studio (there's an improved version in 3.0) and identify big chunks that make sense to reduce (No real advantage from trying to shrink a block that's only 10kB in size anyways)
- [ ] Consider adding resources in only one density (xhdpi?) and let Android do the resizing [except for the launcher icon]
- [ ] Minimize search plugins (688 kB) - avoid duplicate icons? compress icons?

**Comment by pocmo** [comment]
Minify / Proguard is already enabled for release builds. For builds including onboarding the difference is: 4.1 MB -> 2.9M

**Comment by pocmo** [comment]
ImageOptim can save a bunch of kB - but overall it's less than 100kB (It was quite useful for the onboarding images - but they never landed uncompressed).

**Comment by pocmo** [comment]
Enabling "resourceShrinking" doesn't help much here - but I'll do it anyways in hope it might help in later versions.

**Comment by pocmo** [comment]
Letting gradle split the APK by densities saves us about 200kB (2.5 MB -> 2.3 MB)

**Comment by pocmo** [comment]
I can't see any advantages when disabling the PNG cruncher. The APK is actually a tiny bit larger (2591317 -> 2591365).

**Comment by pocmo** [comment]
I can't get aapt2 working. It's complaining about the meta-data tags in our manifest (unknown element). However even removing them temporarily doesn't help because google play services will add one too via the manifest merge.

**Comment by pocmo** [comment]
@ahunt If you have any additional ideas then go ahead and add them to the list :)

**Comment by pocmo** [comment]
Using `proguard-android-optimize.txt` makes the build noticeable slower (but it's disabled for debug builds anyways), but we end up with a smaller APK!

* Focus Release 2.9M -> 2.8M (3024466 -> 2986314) [-37kB]
* Klar Release 2.6M -> 2.6M (2765131 -> 2732215) [-32kB]

**Comment by pocmo** [comment]
@antlam Currently the following drawables are PNGs and could theoretically be replaced with vector images - do we have vector images for them?

* Lock icon
* Notification icon (Not sure if Android supports vectors here)
* Erase shortcut icon (Not sure if Android supports vectors here)
* Onboarding Image 1
* Onboarding Image 1

**Comment by pocmo** [comment]
Looking at the APK analyzer from AS 3.0 (raw size - download size):
* assets: 714.8 KB - 714.8 KB (33.8%)
* res: 642.9 KB - 625.4 KB (29.6%)
* classes.dex 557.3 KB - 557.3 KB (26.4%)
* resources.arsc 866.5 KB - 212.5 KB (10.1%)
* Manifest 2 KB - 2 KB
* Everything else < 1 KB

**Comment by pocmo** [comment]
If I copy the values from LocaleList and use them in resConfigs in build.gradle:
`
        resConfigs "ar","ast","az","bg","bn-rBD","bn-rIN","ca","cs","cy","de","dsb","el","eo","es-rAR","es-rCL","es-rES","es-rMX","fa","fr","fy-rNL","ga-rIE","hi-rIN","hsb","hu","hy-rAM","in","it","iw","ja","kab","kk","ko","lo","my","nb-rNO","nl","nn-rNO","pl","pt-rBR","ro","ru","sk","sl","sq","sr","sv-rSE","ta","th","tr","uk","ur","zh-rCN","zh-rTW","en"
`
.. then I end up with a smaller APK:

* Focus 2.9M -> 2.8M (3024466 -> 2883886) [- 137 KB]
* Klar 2.6M -> 2.6M (2765131 -> 2696475) [- 67 KB]

However if we want to do that then we'd need to make the value of resConfig dynamic (like we did with LocaleList.java).

**Comment by antlam** [comment]
> @antlam Currently the following drawables are PNGs and could theoretically be replaced with vector images - do we have vector images for them?
> 
>     Lock icon
>     Notification icon (Not sure if Android supports vectors here)
>     Erase shortcut icon (Not sure if Android supports vectors here)
>     Onboarding Image 1
>     Onboarding Image 2
>     Onboarding Image 3
>     Wordmark

Yes, there are vector versions of these. But Ill need to take some time to prep/locate them.

**Comment by pocmo** [comment]
Running [json-minify ](https://www.npmjs.com/package/json-minify) over our blocklists reduces the size of them significantly. However in the compressed APK the win is much smaller:

* Focus: 2.9M -> 2.9M (3024554 -> 3019262) [- 5 KB]
* Klar: 2.6M -> 2.6M (2765187 -> 2759903) [- 5 KB]

**Comment by pocmo** [comment]
> Running json-minify over our blocklists reduces the size of them significantly. However in the compressed APK the win is much smaller

We only save about 5 KB of APK size. But parsing those lists might be faster too (Only < 200 KB of data instead of 400+ KB)

**Comment by pocmo** [comment]
Right now our APK size is good enough (and we have a build time check for that) - so I'm going to remove the v1 label. But I'm keeping this bug open so that we can still get back to it when needed.

**Comment by regalstreak** [comment]
Why not download some locale on the go on first start

**Comment by daivat15** [comment]
@pocmo I think now the app is running with aapt2 enabled right?

**Comment by pocmo** [comment]
> @pocmo I think now the app is running with aapt2 enabled right?

Good question. I don't think we enabled it manually. Is aap2 the default now?

**Comment by daivat15** [comment]
Yes. By default aapt2 is used for projects using Gradle 3.+.

**Comment by pocmo** [comment]
Great! Overall I think we can close this issue. There's no work planned.
