### ISSUE TITLE
[L10N] Floating menu option is truncated in Landscape mode in Russian 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6249]
## Steps to reproduce
1. Set Focus in Russian.
2. Go to Settings - Search - Search engine.
3. Tap on the 3-dot menu.
4. Rotate the device in Landscape mode.
5. Observe the floating menu options.

### Expected behavior
The second string "Restore default search engines" should be fully displayed in Landscape mode. 

### Actual behavior
The second string "Restore default search engines" is truncated in Landscape mode.
### Device information

* Android device: Google Pixel 6 (Android 12).
* Focus version: Beta 97.0.0-beta.2.

![1642513214120](https://user-images.githubusercontent.com/89388888/149954111-df66cddd-119b-4f8e-ba0c-71b27023547b.JPEG)

**Comment by lobontiumira** [comment]
Reproducible on Beta 98.0.0-beta.2 with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on Beta 99.0.0-beta.1 with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on Beta 100.0.0-beta.3 with Oppo Find X3 Lite (Android 11).

**Comment by Delphine** [comment]
I have asked the localizer if they can shorten the string, I'll update here once I hear back

**Comment by lobontiumira** [comment]
This is not fixed yet in the latest Focus Nightly build 104.0a1 from 7/22 on the Oppo Reno 6 (Android 12) device.
On the Lenovo tablet, the menu is entirely visible.

![Oppo](https://user-images.githubusercontent.com/40694158/180428381-5934f8f3-88fc-4b09-9f32-4276789321f3.png)
![Lenovo](https://user-images.githubusercontent.com/40694158/180428393-fd46a1cd-cb7c-4f7b-a6a5-8f6a9df43b8b.png)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802652

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
