### ISSUE TITLE
Firefox Focus Debug mode

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6263]
Add ability to enable Debug mode to Firefox Focus.

1.  Go  to **Settings**->**Mozilla**->**About Firefox Focus** 
2. Tap on Focus Logo 5 times (Debug menu is enabled)
3. Press (back) **←** to **Settings**
4. Select **Advanced**
5. Select “**Secret Settings**”
6. Turn on Use Nimbus Preview Collection

Tagging @jeffreygee for UX design and if you agree where the Secret settings will appear on the Settings menu.
@channingcarter any additional requirements from product?

**Comment by channingcarter** [comment]
No additional requirements and the position of the Secret settings is fine. @amedyne

**Comment by delia-pop** [comment]
Tested on Firefox Focus Nightly 98.0 (Build 360330514 🦎 98.0a1-20220201093942) with Google Pixel 6 (Android 12).

The Secret Settings menu is displayed in Advanced and the "Use Nimbus Preview Collection" toggle can be switched to ON/enabled, as per the steps above. 
After Focus is restarted, steps 1-5 have to be performed again, and on step 6 the "Use Nimbus Preview Collection" toggle is enabled.

https://user-images.githubusercontent.com/89388888/152116167-d554f0d6-b373-4dcd-af55-b425786038a5.mp4
