### ISSUE TITLE
Page design is broken on coolmod.com

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/focus-android#6280]
## Steps to reproduce
1. Navigate to https://www.coolmod.com/
2. Observe the page.

### Expected behavior
Page design is displayed correctly.

### Actual behavior
Page design is broken (CSS, images).

### Device information

* Android device: Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
* Focus version: Firefox Focus Nightly 98.0 (🦎 98.0a1-20220124093541)

### Notes
1. The issue is not reproducible on Firefox Nightly 98.0a1 (🦎 98.0a1-20220124093541) and Firefox Focus Release 96.2.0 (🦎 96.0-20220117150835). 
2. The issue is reproducible on Firefox Focus Nightly even if I disable ETP.
3. Screenshot attached.
![image](https://user-images.githubusercontent.com/12184325/150945406-c39c571d-574d-4531-9382-2a6fab236e87.png)

**Comment by ionutbedregeanu** [comment]
This is also reproducible in Fenix and GeckoView Example app. 
@softvision-oana-arbuzov Can you please fill a GV ticket in Bugzilla for this?

**Comment by ionutbedregeanu** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1778937

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
