### ISSUE TITLE
Deleting Slightly Slower

### ISSUE THREAD

**Issue by detherminal** [mozilla-mobile/focus-android#6288]
### Why/User Benefit/User Problem

It is deleted cery quick when we try to delete something from the search section by holding delete button. It would be nice if it deleted slightly slower.

### What / Requirements

Should delete a little bit slower.

### Acceptance Criteria (how do I know when I’m done?)

If it deletes slowly.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802000

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
