### ISSUE TITLE
Status bar is overlapped by website details in Landscape mode

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6292]
## Steps to reproduce
1. Open a webpage.
2. Rotate the device in Landscape mode.
3. Tap the ETP shield icon.
4. Observe the status bar.
### Expected behavior
In Landscape mode, the menu opened after tapping the ETP shield icon is properly displayed under the status bar.
### Actual behavior
After tapping the ETP shield icon in Landscape mode, the webpage name and icon overlaps the status bar.
### Device information

* Android device: LG G7 fit (Android 8.1.0)
* Focus version: Beta 97.0.0-beta.5. 
The issue is not present in the latest Nightly build from 01/26.

![Screenshot (Jan 26, 2022 13 48 05)](https://user-images.githubusercontent.com/89388888/151159355-b4d0335b-ab5e-4d35-9fcf-aac93f95b6bd.png)

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?

**Comment by indurs** [comment]
@Mugurell , can't reproduce this issue.

![Screenshot_20220311-105545(1)](https://user-images.githubusercontent.com/12825812/157807987-117612f1-b629-43a4-8257-c3f9343d3571.png)

**Comment by Mugurell** [comment]
So this would come to validate Delia's report.
If the issue was reported for v97 and it doesn't reproduce anymore it seems like the ticket can be closed.

**Comment by indurs** [comment]
yes. @delia-pop has also mentioned  that the issue is not present in the latest Nightly build from 01/26
