### ISSUE TITLE
Remove Homepage Tips (Pro Tips) from Homepage

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6296]
Since we are implementing CFRs, we can now remove the Homepage Tips.
This ticket is for implementing this change. 
![Screenshot_20220112-134314](https://user-images.githubusercontent.com/68711330/151217339-1350e7dc-3fa6-40d5-8cba-98b5d8615a59.png)

**Comment by amedyne** [comment]
@iorgamgabriel Note that this should be under the same feature and nimbus flags as the CFRs. Meaning this should be disabled once CFRs are enabled for support.

**Comment by ionutbedregeanu** [comment]
Meanwhile homepage tips were put under the same feature flags as the CFRs, so I will close this ticket

**Comment by delia-pop** [comment]
Verified as fixed on Focus Nightly 106.0a1 from 08/26 with Xiaomi 12 Pro (Android 12). The Pro Tips are no longer displayed on homepage and the toggle option was removed from Settings > Mozilla. 

<img src="https://user-images.githubusercontent.com/89388888/186908631-a8ff1aac-8626-40b0-8277-e730938dcd5b.jpg" width="50%" />

**Comment by lobontiumira** [comment]
Verified as implemented also on Beta 106.0b1.
