### ISSUE TITLE
CFRs, tooltips and Onboarding card update under a Feature Flag

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6297]
Set all changes for the following:

- [x] #6205 
- [x] #6208 
- [x] #6209 
- [x] #6211 
- [x] #6296

To be enabled/disabled with a feature flag.

**Comment by ionutbedregeanu** [comment]
Onboarding card flag addressed here https://github.com/mozilla-mobile/focus-android/pull/6302

**Comment by ionutbedregeanu** [comment]
All cfrs and onboarding screen are under feature flags, so we can move this ticket in Done
