### ISSUE TITLE
Renew telemetry for is_fenix_default_browser in Focus (and it's variants)

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#6299]
```
Each metric in the following list from firefox-focus-android, firefox-focus-android-beta, firefox-focus-android-nightly, and firefox-klar-android will expire in the next 14 days or has already expired.

- mozilla_products.is_fenix_default_browser on 2022-02-01

What to do about this:

1. If the metric is no longer needed, remove it from its `metrics.yaml` [1] file.
2. If the metric is still required, resubmit a data review [2] and extend its expiration date.

If you have any problems, please ask for help on the #glean Matrix channel[3]. We'll give you a hand.

What happens if you don't fix this:

The metrics listed above will stop collecting data from builds built after this expiration date,
and you will continue to get this e-mail as a reminder.

Your Friendly, Neighborhood Glean Team

[1] The correct metrics.yaml is in this list:
https://github.com/mozilla-mobile/focus-android/tree/HEAD/app/metrics.yaml
[2] https://wiki.mozilla.org/Firefox/Data_Collection
[3] https://chat.mozilla.org/#/room/#glean:mozilla.org
```

cc: @amedyne

**Comment by amedyne** [comment]
@channingcarter do we need to renew this metric?

**Comment by channingcarter** [comment]
Yes @amedyne

**Comment by AndiAJ** [comment]
Hi, I've checked if the probe is renewed in the [Glean dictionary](https://dictionary.telemetry.mozilla.org/apps/focus_android/metrics/mozilla_products_is_fenix_default_browser) and it looks like it's expired.

On the other hand, I've manually generated the metrics ping (set the date to 2/1 and time to 04:00 AM) and the probe was successfully generated. [Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ0102000)

I'll remove the QAReady label until further notice.

**Comment by ionutbedregeanu** [comment]
I will move this ticket to done until further notice

**Comment by lobontiumira** [comment]
The telemetry was renewed for is_fenix_default_browser in the [Glean dictionary](https://dictionary.telemetry.mozilla.org/apps/focus_android/metrics/mozilla_products_is_fenix_default_browser).
I will close this ticket.
