### ISSUE TITLE
Create a base fragment browser and browser fragments for custom and normal tabs.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#6305]
Currently, `CustomTabActivity` uses the same `BrowserFragment` as a normal tab.

This will help separate logic in customizing the toolbar for each use case.
It will also avoid duplicating functionality from the browser fragment in the `CustomTabActivity`.

**Comment by iorgamgabriel** [comment]
Fenix already supports this so we'll get this for free after the migration
