### ISSUE TITLE
Investigate how to add Focus/Klar variants to one Sentry project

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#6318]
We're moving to a new instance of Sentry that supports beta/nightly/release style of variants, but we need to see if we can group Klar builds in a similar way instead of making them separate projects.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801999

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
