### ISSUE TITLE
Investigate feature-media integration

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6325]
### How this help us?
Find out what which components should/can be integrated from `feature-media` in Focus at this moment

### What / Requirements
Get  documented about all the available `feature-media` components from AC and see which fits to Focus and if their implementation depends on another components which aren't integrated at this moment

### Acceptance Criteria (how do I know when I’m done?)
All the integrations should be approved by product team

**Comment by Mugurell** [comment]
One important thing regarding the updated media support: drm protected videos don't seem to currently be supported on Focus. Tested on Netflix.
Maybe it has something to do with the EME permission (`mediaKeySystemAccess`) and the updated media support would address this.

**Comment by jonalmeida** [comment]
Reference Browser might be an easier sample code base to follow on how to add the media feature. You can find some hints [here](https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/java/org/mozilla/reference/browser/components/Core.kt#L112) with `MediaSessionFeature` and `RecordingDevicesMiddleware`.

> Tested on Netflix.

Netflix isn't a great test site for DRM. They actively stop mobile browsers (even with desktop mode) from playing content even if EME support is there. There is a an [example site](https://shaka-player-demo.appspot.com/demo/) here from Google with EME content.

On Fenix, the permissions prompt asks you if you want to play DRM content first. On Focus, it just accepts that permission for you. 😅 

The permissions part ties into another story about site permissions, so I think it's fair to ignore that problem while work on feature-media integration.

**Comment by ionutbedregeanu** [comment]
Media features which can be integrated in Focus:
- MediaSessionFullscreenFeature -> Feature that will auto-rotate the device to the correct orientation for the media aspect ratio.
- MediaSessionFeature -> Feature that handles MediaSession state changes
Ticket for MediaSessionFullscreenFeature, MediaSessionFeature https://github.com/mozilla-mobile/focus-android/issues/6330

- AbstractMediaSessionService -> Keep the process alive while we are playing media (with the app possibly in the background) and shows an ongoing notification
@channingcarter Do we consider to integrate AbstractMediaSessionService in Focus in order to display a media notification while the app is in the backround?

-  DRM site permission -> To support encrypted media
We already started a discussion for [site permissions integration](https://github.com/mozilla-mobile/focus-android/discussions/5830) and we should treat this subject there
- Picture in Picture https://github.com/mozilla-mobile/focus-android/issues/820

**Comment by amedyne** [comment]
@channingcarter For your review

**Comment by channingcarter** [comment]
Just for clarification, if we add this enhancement what benefit will it provide Focus users? I am unable to tell. @ionutbedregeanu @amedyne

**Comment by jonalmeida** [comment]
This gives Android OS media control to the playing media. It will be identical to how we support media notifications in Fenix when in private browsing, i.e. **you can control the media from the UI or headset, but there is no metadata about the audio/video shared**.

I highly recommend we add this because it can be awkward when web content is playing media on a page and you have to find the web controls to start/stop it.

**Comment by channingcarter** [comment]
Thank you for the explanation. Let's go ahead and implement @jonalmeida

**Comment by ionutbedregeanu** [comment]
Thanks. I created a new ticket for that https://github.com/mozilla-mobile/focus-android/issues/6384

**Comment by ionutbedregeanu** [comment]
Since all the subjects were discussed I will move this ticket in Done
