### ISSUE TITLE
locales 'dsb' and 'hsb' are not accepted by Android

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#633]
Normally, three-letter locale codes are not accepted by Android, but the l10n repo (https://github.com/mozilla-l10n/focus-android-l10n/tree/master/locales) has 'dsb' and 'hsb' which is not being imported to focus-android.

Also, it's odd that 'ast' locale does get imported into focus-android

**Comment by ahunt** [comment]
I can't reproduce, running "gradlew stringsImport" results in the following files being created:

app/src/main/res/values-dsb/strings.xml
app/src/main/res/values-hsb/strings.xml

These locales aren't in the tree yet, I'll add a PR adding them. They also won't appear in the language selector until PR #642 lands (which ensures that all available locales are added to the list).

**Comment by ahunt** [comment]
I've added some gradle code to check that we've imported all locales correctly in PR #642, and I'll import the missing locales in PR #646!
