### ISSUE TITLE
Integrate MediaSessionFullscreenFeature and MediaSessionFeature from AC

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6330]
### Why/User Benefit/User Problem
Improve the user experience
### What / Requirements
MediaSessionFullscreenFeature -> Feature that will auto-rotate the device to the correct orientation for the media aspect ratio.
MediaSessionFeature -> Feature that handles MediaSession state changes
Integrate MediaSessionFullscreenFeature and MediaSessionFeature from` feature-media` component
### Acceptance Criteria (how do I know when I’m done?)
The device will be auto-rotated to correct the orientation for the media aspect ratio.
A media notification will be displayed if we are playing audio/video content

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 99 (build 360420514 GV 99.0a1-20220210065747) with the following devices:
* Samsung Galaxy Note 8 (Android 9),
* Xiaomi mi4i (Android 5.0.2),
* Lenovo Tab M10 (Android 10),
* Xiaomi Mi 8 Lite (Android 10),
* Samsung Galaxy Tab A6 (Android 5.1.1).

When a media starts playing, the media notification is displayed continaing the "A site is playing media" text, and the pause/play button. Verified on several sites: vimeo.com, soundclaoud.com, cnn.com, bbc.co.uk, rockfm.ro.

![Untitled](https://user-images.githubusercontent.com/40694158/153562845-27a1ba6d-a3d5-4a84-b20d-e22ea35e13ec.png)
