### ISSUE TITLE
Focus crashes when accessing the "Add a search engine" SUMO page

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6331]
## Steps to reproduce
1. Go to Settings - Search - Search engine - Add another search engine.
2. Tap on the "i" option from the top right corner.
3. Observe the crash.
### Expected behavior
The application remains stable at all times.
### Actual behavior
The application crashes every time when tapping the "i" option. 
### Device information

* Android device: Google Pixel 6 (Android 12), Motorola Moto G30 (Android 11).

* Focus version: Firefox Focus Nightly 98.0 (Build 360330514 🦎 98.0a1-20220201093942).

https://user-images.githubusercontent.com/89388888/152130187-685954ed-e28a-4585-9d8e-05c4be305586.mp4

**Comment by ionutbedregeanu** [comment]
Seems a regression after https://github.com/mozilla-mobile/focus-android/issues/6208
![Screenshot 2022-02-02 at 15 13 58](https://user-images.githubusercontent.com/11731652/152160662-f0b6d611-c75e-427b-b4ef-dc568c8ee1e3.png)

@iorgamgabriel I will assign you on this

**Comment by delia-pop** [comment]
Verified as fixed on Firefox Focus Nightly 98.0 (Build 360390514 🦎 98.0a1-20220207065816) with Google Pixel 6 (Android 12) and Motorola Moto G30 (Android 11).
The application remains stable when accessing the "Add a search engine" SUMO page.
