### ISSUE TITLE
The CFR for Shield Icon is incorrectly placed

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6332]
## Steps to reproduce
1. Install Firefox Focus Nightly.
2. Open a webpage and observe the CFR prompt.
3. Clear data.
4. Go to Settings - Mozilla  - Your Rights and observe the CFR prompt.
### Expected behavior
After step 2, the CFR prompt is displayed under the shield icon.
After step 4, the CFR prompt is displayed under the shield icon.

### Actual behavior
After step 2, the CFR prompt is firstly incorrectly placed in the left upper corner above the trash icon, and then jumps under the shield icon.
After step 4, the CFR prompt is incorrectly placed and remains displayed in the left upper corner above the trash icon.
### Device information

* Android device: Google Pixel 6 (Android 12), Motorola Moto G30 (Android 11), Samsung Galaxy Tab S3 (Android 9), Huawei MediaPad M2 (Android 5.1.1).

* Focus version: Focus Nightly 98.0 (Build 360330514 🦎 98.0a1-20220201093942).

https://user-images.githubusercontent.com/89388888/152144873-7fc6dd06-35e9-4fec-990f-06d8a85a7fc8.mp4

https://user-images.githubusercontent.com/89388888/152145100-f64144e9-2832-4848-aaff-999c9a87ebdf.mp4

https://user-images.githubusercontent.com/89388888/152145386-58186e25-b20b-4f8d-904d-b92b919feddf.mp4

**Comment by lobontiumira** [comment]
This issue is not fixed yet.
The CFR is positioned incorrectly on Samsung Galaxy Tab A6 (Android 5.1.1), and on Xiaomi mi4i (Android 5.0.2).
Tested with the latest Focus Nightly build 98.0 (360390513 with GV 98.0a1-20220207065816) from 2/8.

![Screenshot_1](https://user-images.githubusercontent.com/40694158/152959893-34067e5c-47b1-4307-91e2-deb8241f66d0.jpg)

I'll remove the QAReady label for now.

**Comment by Mugurell** [comment]
@iorgamgabriel @ionutbedregeanu On Android <= 23 we might have to use `showAtAnchorLocation` instead of `showAsDropdown` when showing the PopupWindow. The solution needs to be validated for when rotating the screen.

**Comment by Mugurell** [comment]
@ QA: This should be addressed by https://github.com/mozilla-mobile/focus-android/pull/6411
Please recheck.

**Comment by lobontiumira** [comment]
Verified as fixed on:
* the Samsung Galaxy Tab A6 (Android 5.1.1) on Focus Nightly 99.0a1 (build 360550513 GV 99.0a1-20220223093800), and
* the Lenovo Tab M10 (Android 10) on Focus Nightly 99.0a1 (build 360550514 GV 99.0a1-20220223093800).

![Screenshot_1](https://user-images.githubusercontent.com/40694158/155487904-61ba6518-f315-4208-bbc3-c5b0a8b087ba.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/40694158/155487921-c74e4b98-a6e0-4404-927b-98ffaa69592d.jpg)
