### ISSUE TITLE
The CFR for Shield Icon is incorrectly displayed on tablets

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6333]
## Steps to reproduce
1. Install Firefox Focus Nightly.
2. Open a webpage and observe the CFR prompt.
### Expected behavior
The CFR prompt is properly displayed, with rounded corners and fully visible text, as in [Figma ](https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding-2022?node-id=2647%3A11565 )design.
### Actual behavior
On Android 5 tablet, the CFR prompt appears cutoff at the bottom and the text is not completely displayed on both Portrait and Landscape modes.
On Android 5 tablet, the CFR prompt appears cutoff at the bottom, but the text is completely displayed.
### Device information

* Android device: Samsung Galaxy Tab S3 (Android 9), Huawei MediaPad M2 (Android 5.1.1).
* Focus version: Focus Nightly 98.0 (Build 360330514 🦎 98.0a1-20220201093942).

![Untitled](https://user-images.githubusercontent.com/89388888/152147684-2c06fc5f-b1bc-48a3-a1e6-4dfa662e4d16.png)

**Comment by Mugurell** [comment]
@ QA: This should be addressed by https://github.com/mozilla-mobile/focus-android/pull/6411
Please recheck.

**Comment by lobontiumira** [comment]
Verified as fixed on:
* the Samsung Galaxy Tab A6 (Android 5.1.1) on Focus Nightly 99.0a1 (build 360550513 GV 99.0a1-20220223093800), and 
* the Lenovo Tab M10 (Android 10) on Focus Nightly 99.0a1 (build 360550514 GV 99.0a1-20220223093800).

![Screenshot_1](https://user-images.githubusercontent.com/40694158/155486133-fce37169-dfe4-4f0f-b744-52b9e5b628e3.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/40694158/155486158-e7c974c9-10fb-4d60-848e-c2f834af6c94.jpg)
