### ISSUE TITLE
The CFR for Shield Icon cannot be dismissed by tapping outside the prompt on Android 5 tablet

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6334]
## Steps to reproduce
1. Install Firefox Focus Nightly.
2. Open a webpage and observe the CFR prompt.
3. Tap outside the CFR prompt.
### Expected behavior
The CFR prompt is dismissed when tapping outside the prompt.
### Actual behavior
The CFR prompt is not dismissed when tapping outside the prompt, only them tapping on the "X" icon.
### Device information

* Android device: Huawei MediaPad M2 (Android 5.1.1).
* Focus version: Focus Nightly 98.0 (Build 360330514 🦎 98.0a1-20220201093942).

https://user-images.githubusercontent.com/89388888/152148910-67b99b7b-db74-452b-a128-8e7d6100f1f4.mp4

**Comment by lobontiumira** [comment]
The issue is no longer reproducible on the debug build 104.0 (build 11, GV 104.0a1-20220720095935, AC 104.0.20220720190100) with Samsung Galaxy Tab A6 (Android 5.1.1).
