### ISSUE TITLE
 CFR for Shield may cause the "Your Rights" page to be incorrectly displayed on tablet

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6335]
## Steps to reproduce
1. Install Firefox Focus Nightly.
2. Go to Settings - Mozilla - Your Rights.
3. Observe the page.
### Expected behavior
The "Your Rights" page is properly displayed, on the entire screen when the CFR prompt pops up.
### Actual behavior
The "Your Rights" page is not displayed on full screen when the CFR prompt pops up, white margins can be observed.
Note that this is not 100% reproducible, on several occasions the page was correctly displayed.
### Device information

* Android device: Samsung Galaxy Tab S3 (Android 9).
* Focus version: Focus Nightly 98.0 (Build 360330514 🦎 98.0a1-20220201093942).

![A9 Tab Your Rights](https://user-images.githubusercontent.com/89388888/152150529-51f2a129-7ce4-4706-b74c-9a177928f87d.jpg)

**Comment by Mugurell** [comment]
The issue with how the webpage renders seems rather like a GeckoView issue that should not depend on the CFR.

**Comment by Mugurell** [comment]
@delia-pop Not sure how often does this reproduce and it may be a device specific issue.
Can you please test loading the "Your rights" page url on the latest GeckoView example apk? - https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile
(copy - paste the entire url)
I think the issue should also be reproduceable there and if so we'd know the next steps for investigating this.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 100.0a1 (build 360730510 with GV 100.0a1-20220313093807) with Lenovo tablet M10 (Android 10):

![Screenshot_2022-03-14-07-20-45-499](https://user-images.githubusercontent.com/40694158/158123739-428f0bb3-ec22-4cc2-b1a3-ce1e6cf13148.jpeg)
