### ISSUE TITLE
Add a static_strings.xml for strings that don't need to be translated

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/focus-android#6341]
@ionutbedregeanu @iorgamgabriel This came up about how we deal with strings related to Secret Settings / Debug/Dev only fragments that are not expected to be seen by the general audience. In Fenix, we add a `static_strings.xml` to differentiate from the list of strings (`strings.xml`) that does get parsed by Pontoon for localization. See https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/res/values/static_strings.xml we used this to put strings that don't need to be translated and are generally use for debug purposes. We will probably want to introduce this immediately to address https://github.com/mozilla-l10n/android-l10n/pull/421.

**Comment by ionutbedregeanu** [comment]
Since is nothing to test here by QA I will move this ticket to Done
