### ISSUE TITLE
[L10N] "Light" theme text is missing in Settings - Theme in Punjabi

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6363]
## Steps to reproduce
1. Change the device's language to Punjabi (Indian).
2. Open Focus with a fresh profile.
3. Go to Settings - Theme, and observe the "Light" theme option.

### Expected behavior
The "Light" theme option is displayed correctly.

### Actual behavior
The "Light" theme option has no text.

### Device information
* Android device: Lenovo Tab M10 (Android 10)
* Focus version: RC 97.1.0

![punjabi](https://user-images.githubusercontent.com/40694158/152801688-104b6dd0-b6ab-4742-80d1-ef9d52fe15e8.png)

**Comment by lobontiumira** [comment]
Reproducible on Beta 98.0.0-beta.2 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 99.0.0-beta.1 with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Still reproducible on Beta 100.0.0-beta.3 with Oppo Find X3 Lite (Android 11).

**Comment by Delphine** [comment]
I updated the string on Pontoon using the 100% translation memory. This should be fixed at the next l10n string import that happens

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Beta build 101.0.0-beta.2 on Samsung Galaxy Note 8 (Android 9).

![punjabi](https://user-images.githubusercontent.com/40694158/167091498-a68e3207-8785-4c54-b806-6a5f5ea8181b.jpg)
