### ISSUE TITLE
CFRs RTL issues

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6364]
Saw while reviewing the new CFR for the erase button that we need to have special care around these CFRs - https://github.com/mozilla-mobile/focus-android/pull/6352/files#r800679968

The currently proposed CFR for the erase button
![image](https://user-images.githubusercontent.com/11428869/152804951-253b3278-b911-4961-b972-79044e188361.png)
and the one for the security indicator show issues with RTL
![image](https://user-images.githubusercontent.com/11428869/152805515-a898bbe3-d2f9-47dd-a865-48a2dfbe3292.png)

We'll need to verify all CFRs and ensure proper support for RTL.
cc @giorga @ionutbedregeanu

**Comment by amedyne** [comment]
Thanks for logging this @Mugurell

**Comment by Mugurell** [comment]
@ QA: This should be addressed by https://github.com/mozilla-mobile/focus-android/pull/6411
Please recheck.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 99.0a1 build from 2/24 with:
* Samsung Galaxy Tab A6 (Android 5.1.1), 
* Xiaomi mi4i (Android 5.0.2), 
* Oppo Find X3 Lite (Android 11), and
* Sony Xperia Z5 Premium (Android 7.1.1)

![Screenshot_۲۰۲۲-۰۲-۲۴-۱۱-۲۳-۵۲-۰۸۵_org mozilla focus nightly](https://user-images.githubusercontent.com/40694158/155498698-c1010f83-4185-4abe-a4db-0280efd8cb72.png)
