### ISSUE TITLE
[L10N] The "Site permissions" options are not translated in some languages

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6371]
## Steps to reproduce
1. Set the device to Persian.
2. Open Focus Beta 97.0.0-beta.6.
3. Go to Settings, and observe the Site permissions option.
4. Tap on it, and observe all the menus in Site permissions.

### Expected behavior
All the options are translated in Persian.

### Actual behavior
The Site permissions and its options are not translated in Persian.

### Device information
* Android device: Lenovo Tab M10 (Android 10)
* Focus version: Beta 97.0.0-beta.6

![site permission - persian](https://user-images.githubusercontent.com/40694158/153002127-dab52bc8-4368-4ae7-801f-34a69c1861fe.png)

**Comment by Mugurell** [comment]
"Site permissions" and "Autoplay" are not translated into persian
https://pontoon.mozilla.org/fa/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?search=preference_site_permissions&string=237249
https://pontoon.mozilla.org/fa/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?search=preference_autoplay&string=237252

"Site permissions" has been translated for french 22 days ago so this translation should only be available starting with v98 - https://github.com/mozilla-mobile/focus-android/pull/6243/files 

Based on https://github.com/mozilla-mobile/focus-android/issues/5679#issuecomment-994069998 I think this is safe to close.

**Comment by lobontiumira** [comment]
Verified as translated into French on the Beta 98.0.0-beta.1.
