### ISSUE TITLE
Integrate AbstractMediaSessionService from AC

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6384]
### Why/User Benefit/User Problem
Keep the process alive while we are playing media (with the app possibly in the background) and shows an ongoing notification
### What / Requirements
Integrate AbstractMediaSessionService in Focus as in Fenix
### Acceptance Criteria (how do I know when I’m done?)
A media notification should be displayed when we play video/audio content and put the app in background

**Comment by jonalmeida** [comment]
You've already added this in https://github.com/mozilla-mobile/focus-android/pull/6336, just needs one middleware piece in that PR to complete it. 🙂

**Comment by ionutbedregeanu** [comment]
> You've already added this in #6336, just needs one middleware piece in that PR to complete it. 🙂

Oh, it seems that i didn't understand completely the MediaSessionFeature. Thanks, @jonalmeida 
I will close this ticket since is already addressed
