### ISSUE TITLE
[android 5] Pages are zoomed when changing from portrait to landscape and viceversa

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6385]
## Steps to reproduce
1. Open a page, like wikipedia.org.
2. Turn the device to landscape.
3. Turn it to portrait.
4. Repeat steps 2 & 3 and observe the page.

### Expected behavior
The page is displayed without issues.

### Actual behavior
The page is zoomed.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), Xiaomi mi4i (Android 5.0.2)
* Not reproducible on Samsung Galaxy Note 8 (Android 9), nor Lenovo Tab M10 (Android 10)
* Focus version: Focus Nightly from 2/8, Beta 98.0.0-beta.1
* Please see the similar issue filed on Fenix: [17856](https://github.com/mozilla-mobile/fenix/issues/17856)

https://user-images.githubusercontent.com/40694158/153171524-d9b7b4d0-6f5c-4b09-9ba8-bba1478d4e9f.mp4

**Comment by Mugurell** [comment]
@lobontiumira This is always reproduceable on those Android 5 devices?
If so can you please also test on latest GVE - https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-arm-debug ?

**Comment by lobontiumira** [comment]
Hi @Mugurell!
Yes, it is reproducible always.
I've tested with both devices on the geckoview apk, and it is reproducible.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1754487

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
