### ISSUE TITLE
Synchronize CFRs to prevent overlapping

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6386]
We need to ensure a way for different CFRs to not overlap
Maybe a queue?

![image](https://user-images.githubusercontent.com/11428869/153173598-8baff23b-4d99-41ce-aa45-80eec4982459.png)

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly build 101.0a1 from 4/13 with Oppo Find X3 Lite (Android 11).
First, the CFR for delete icon is displayed. Dismissing that CFR, and reloading the page, or opening a new secure page, displays the CFR for tracking protection.
