### ISSUE TITLE
Have a common approach for CFRs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6388]
Talked with Ionut and Gabriel about how to find a common implementation for all CFRs that would have us treat all issues related to anchoring and layout in one place and also simplify the logic for deciding when to show the CFRs (which would also help with https://github.com/mozilla-mobile/focus-android/issues/6386).

The general agreed direction would be:
- One `CFRPopup` class responsible for creating any CFR and displaying it, with proper anchoring and support for all visual details
(This could use xml now but converted to compose later)
- One `CFRsMiddleware` (better name pending) observing `BrowserStore` and containing all necessary business logic to decide when as a side effect of various actions the CFRs will be shown. 
This one component controlling all CFRs could also sync them to not appear at the same time.
- The Middleware will emit an action for a new `BrowserScreenStore` which will modify a boolean to show or not a specific CFR. This also preparing the compose refactoring where observing and reacting to such state would be needed.

@csadilek @Amejia481 @jonalmeida Thoughts?

**Comment by jonalmeida** [comment]
This looks good! r+ in advance!

> * One `CFRPopup` class responsible for creating any CFR and displaying it, with proper anchoring and support for all visual details

Yes! What I learnt from some of of the Fenix code, is that we try to find elements on the screen by ID with [`View#getLocationOnScreen`](https://developer.android.com/reference/android/view/View#getLocationOnScreen(int[])) and then draw the popup on a transparent overlay view. It would be nice if we had a nice API to give you this and the popup could draw itself in the right way depending on how close it is to the edges of the screen.

> * The Middleware will emit an action for a new `BrowserScreenStore` which will modify a boolean to show or not a specific CFR. This also preparing the compose refactoring where observing and reacting to such state would be needed.

Do we need a new store or can we put this in the [`AppState`](https://github.com/mozilla-mobile/focus-android/blob/main/app/src/main/java/org/mozilla/focus/state/AppState.kt)? Optionally, within a nested data class if that helps.

**Comment by jonalmeida** [comment]
You mentioned it in https://github.com/mozilla-mobile/focus-android/issues/6386 already, but just to clarify, was the store going to manage the queue of events so we wouldn't overlap them on the same screen?

**Comment by jonalmeida** [comment]
Yeah, that sounds fair.

Just throwing out this WIP idea that I was imaging from what you described, but may not necessarily work: I was thinking along the lines of having a queue of CFRs with a reference to which screen, and some observer would know when to take the next one:

```kotlin
AppState(
  val screen: Screen,
  val cfrs: listOf<CFRData> = { 
    CFRData(content: String = "Try this feature!", screen: Screen = screenForThisCfr),
  }
)
```

Then some other piece would observe the `screen` changes in the state and take the next CFR for that screen to display it:

```kotlin
override suspend fun onState(flow: Flow<AppState>) {
    flow.ifChanged { it.screen }
        .collect { state ->

            // Find and take the next CFR
            val cfrToDisplay = state.first { it == it.screen }
 
            // Send it over to the UI piece to display.
            sendToCfrPop(nextCfr)

            // Remove the displayed CFR from our queue.
            dispatch(RemoveCfrAction(cfrToDisplay))
        }
}
```

**Comment by ionutbedregeanu** [comment]
Already implemented
