### ISSUE TITLE
Handle system-locale changes better

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#641]
From #122:

> One known bug (which Firefox also exhibits), is that the locale doesn't change (until app restart) if you:
> 
>     Start with Focus using a custom locale (i.e. not system default). (Force-kill the app after setting a custom locale)
>     Set to system default -> language updates
>     Change the OS locale, return to Focus -> language doesn't change (but should reflect the new system locale)
> 
> If Focus is already set to "system default", and the OS language is changed, then we correctly update the language. This issue only occurs if Focus was started with a custom locale.

I don't think this is a V1 issue, since Firefox exhibits the same. Other apps don't update locales at all (when the system locale is changed) until you force-kill them, and we primarily care about the internal locale-switcher working (and it does work reliably), so we're not worse than any other app in this regard.

**Comment by pocmo** [comment]
> Other apps don't update locales at all (when the system locale is changed) until you force-kill them

Afaik activities of apps that do not set configChanges="locale" should get killed by the system and automatically re-created. :)

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Locale Switcher on Android](https://trello.com/c/Ig8qAH28/34-locale-switcher-on-android)

**Comment by ahunt** [comment]
Closing as dupe of #651

**Comment by pocmo** [comment]
> Closing as dupe of #651

This is related to TransactionTooLargeException? How?
