### ISSUE TITLE
Videos can not be played on sport.orf.at due to a DRM error message

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#6420]
## Preconditions
VPN set to AUSTRIA

## Steps to reproduce
1. Navigate to: https://sport.orf.at/beijing2022/stories/3091263/.
2. Allow DRM control content to be played.
3. Tap on the "Play" button located inside the video frame.
4. Observe the result.

### Expected behavior
The video is played
### Actual behavior
An error message is shown:

### Device information
Samsung A51
* Android device: A11
* Focus version: Firefox Focus Nightly 99.0 (360450513-🦎99.0a1-20220212115333🦎)

**Notes:**
1. Reproducible regardless of the status of ETP.
2. Not reproducible using the latest build of Firefox Nightly in Normal Browsing Mode and in Private Browsing Mode.
3. Reproducible on both Release and Nightly Version of Firefox Focus.
4. Screenshot attached:
![Screenshot_5](https://user-images.githubusercontent.com/75027050/153839901-f675b506-3b9a-4869-a8ec-101003ce7bf7.png)

**Comment by ionutbedregeanu** [comment]
It will be addressed by https://github.com/mozilla-mobile/focus-android/issues/6504
