### ISSUE TITLE
"Secure connection failed" when accessing the site at ausscripts.erx.com.au

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#6421]
## Steps to reproduce
1. Navigate to: [ausscripts.erx.com.au](https://ausscripts.erx.com.au/Scripts/14FYCJMQJ3BNVNJ7X4).
2. Observe the result.
### Expected behavior
A message regarding the status of the subscription is displayed.
### Actual behavior
An error message regarding the connection to the page is displayed.
### Device information
Google Pixel 3
* Android device: A12
* Focus version:  Firefox Focus Nightly 99.0 (360450513-🦎99.0a1-20220212115333🦎)

**Notes:**

1. Reproducible regardless of the status of ETP.
2. Not reproducible using the latest build of Firefox Nightly in Normal Browsing Mode and in Private Browsing Mode.
3. Reproducible on both Release and Nightly Version of Firefox Focus.
4. Screenshot attached:
![Screenshot_9](https://user-images.githubusercontent.com/75027050/153841968-14439de4-9e49-4705-af49-2a7b44abcf4a.png)
5. According to SSL Labs:
![Screenshot_11](https://user-images.githubusercontent.com/75027050/153842436-6f96f578-9940-435f-a5f4-4581a1943381.png)

**Comment by lobontiumira** [comment]
I've tested on the latest Focus Nightly 104.0a1 from 7/22 with Oppo Reno 6 (Android 12), and the page https://ausscripts.erx.com.au/Scripts/14FYCJMQJ3BNVNJ7X4 was opened without issues. The same content was displayed on Chrome as well.

![Screenshot_2022-07-22-14-29-41-82_11753d9bf2a67eec1c984b8ccb4d0671](https://user-images.githubusercontent.com/40694158/180430376-adae68f2-eb5a-42ad-ade7-80c271d45037.jpg)
