### ISSUE TITLE
Very frequent UI test failure - different shards with inconclusive results

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/focus-android#6428]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6479591213728734212
### Build:
https://github.com/mozilla-mobile/focus-android/commit/92bf0b66d24669272c3edfe28a9dc43d7fcab3dc

**Comment by Archaeopteryx** [comment]
Started by #6348

**Comment by AaronMT** [comment]
I've opened a ticket with Google for insight, not getting any replies in Firebase Community.

**Comment by AaronMT** [comment]
No replies yet in ticket. Testing if a Pixel 2 is more stable in draft PR. From Slack reply

> For [matrix-2iu96w9y1otlk](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8978338696274776020/details?stepId=), the issue is on the infrastructure. A related question, does your app have a lot log?

Do we have excessive logging enabled?

**Comment by AaronMT** [comment]
I have a promising workaround while they continue to investigate based on discussion about reducing our sharding.

> If we assume the infrastructure failure rate is the same, more sharding will increase the chance for the matrix to fail.  Further, these test executions all have overhead in terms of device scheduling, preparation, post test run result processing, these time combined might be much longer than the time running the test. So in practice, more sharding might not help you at some point.

**Comment by AaronMT** [comment]
> HI Aaron,
> 
> Thank you for your patience, After speaking with Daming this is a known issue within the Testing Infrastructure team for which there is an active ticket and ongoing investigation. The test matrix ID's you have provided have been noted and the product team has been made aware of your specific case.
> 
> At this time, there is no mitigation available, and I will continue to provide you with updates as they become available on my end. Please let me know if you have any questions in the meantime.
> 
> Best,
> 
> Desmon

**Comment by AaronMT** [comment]
> Hi Aaron, 
> 
> Thank you for your patience. I have received correspondence from the product team regarding the results you have provided: 
> 
> this is an issue with our current API level 30 virtual devices (Pixel2, Pixel3 and NexusLowRes) and our engineering team is actively working on it. We have alternate devices you can test in the meantime that are currently in private alpha. We have whitelisted you at this time for these devices to try at your discretion. 
> 
> - Pixel2Emulator 
> - NexusLowResEmulator. 
> 
> Please attempt to test with these as a workaround. 
> 
> Notes: 
> 
> - We don't keep a large pool of these at the ready, so their tests may queue if they send a lot of individual tests at once (e.g. sharding). 
> 
> - These devices are currently in alpha phase, speed and stability may be different from the Pixel2 and NexusLowRes. 
> 
> Please let me know if you experience any issues with the alternate devices and I will be sure to take your feedback into consideration. 
> 
> Best, 
> 
> Desmon

**Comment by AaronMT** [comment]
> The Engineering team has now submitted a potential fix for this issue outright. This fix is in the processed of rollout in the next few days after which extensive testing will be done to ensure the errors observed in the example matrices you provided has been mitigated. I will keep you up to date with more information as I receive it, along with a confirmation on when the API30 devices will be available for your consumption once again.

**Comment by AaronMT** [comment]
Google claims this is fixed. This should be fixed now. Re-open if we see any more, and I'll pass along the matrix ids.

> HI Aaron, 
> 
> As an update on our end: 
> 
> The fix from Engineering has been rolled out at this time, and the Engineering team will be analyzing the incidence rate of the error messages observed to ensure that this issue has been fixed. Thank you for your patience, and let me know if you have any questions in the meantime. 
> 
> Desmon

**Comment by AaronMT** [comment]
😓 
https://github.com/mozilla-mobile/focus-android/runs/5531212168

Commented in Ticket

**Comment by AaronMT** [comment]
> A potential fix has been rolled out for the inconsistencies observed in your test matrices. Can you please attempt your testing automation again at this time and tell me if you are still experiencing this issue? 

Monitoring

**Comment by AaronMT** [comment]
Resolved at this time.
