### ISSUE TITLE
Rewrite setting for enabling/disabling "secure mode"

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#643]
Based on the discussion on #621:

@pocmo wrote:
 > ".. and see Firefox Focus in your Recent Apps list". To me […] it sounds like Focus does not show up in "recent apps" at all - although it does and we only hide the content.

@mheubusch wrote:
> […] is it accurate to say: “and see sites you’ve visited using Focus in your Recent Apps list"

So we might like to clarify the text like so:

> **Stealth**
> Turn off stealth mode to take screenshots and see sites you’ve visited using Focus in your Recent Apps list.

**Comment by pocmo** [comment]
We do a last string export today and I can update the setting to this version. :)

**Comment by pocmo** [comment]
Merged! :)
