### ISSUE TITLE
Intermittent UI test failure - < EraseBrowsingDataTest. systemBarHomeViewTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6438]
### Stacktrace:
java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity } within 45000 milliseconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1644885070997 and now the last time the queue went idle was: 1644885120110. If these numbers are the same your activity might be hogging the event queue.
	at androidx.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:509)
	at androidx.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:376)
	at org.mozilla.focus.activity.EraseBrowsingDataTest$systemBarHomeViewTest$5.invoke(EraseBrowsingDataTest.kt:160)
	at org.mozilla.focus.activity.EraseBrowsingDataTest$systemBarHomeViewTest$5.invoke(EraseBrowsingDataTest.kt:151)
	at org.mozilla.focus.activity.robots.NotificationRobot$Transition.clickNotificationMessage(NotificationRobot.kt:87)
	at org.mozilla.focus.activity.EraseBrowsingDataTest.systemBarHomeViewTest(EraseBrowsingDataTest.kt:151)

**Comment by AaronMT** [comment]
This should hopefully be resolved by my clearing existing notifications PR. The error here is the runner timing out because it can't find the notification.

**Comment by AndiAJ** [comment]
Falky 1x on 2/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7124424158494818448/executions/bs.83a5f4b1894d0d00/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6057223281033602572/executions/bs.f24292b893723b02/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9067818685472264056/executions/bs.afea3d73ed8d02b5/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5855424558945730841/executions/bs.8ee149a8b3434a4c/testcases/1)

**Comment by AndiAJ** [comment]
Failed 1x on 3/4 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6646516784429019336/executions/bs.395c3568f8b90eb8/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6646516784429019336/executions/bs.2b2517ff42f033ed/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6996107237691375590/executions/bs.9becb91d50e88645/testcases/1)

**Comment by AndiAJ** [comment]
Failed 1x on 3/7 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4763911342473929757/executions/bs.fbcc63116ece46ee/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4763911342473929757/executions/bs.ac9f07e016a20783/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9144000668997431137/executions/bs.aa15471f4be4a72b/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8500066092317331268/executions/bs.eb6f062a46564e07/testcases/1)

**Comment by AndiAJ** [comment]
Failed 1x on 3/9 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7577141395612590386/executions/bs.c8385541e6ce2e86/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7577141395612590386/executions/bs.f235721943b8d241/testcases/1)

Flaky 2x on 3/9 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5187096809308075231/executions/bs.c9a9ad9ecdcd5d4b/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9045660674613542987/executions/bs.12f62db4f3e1bd93/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/13 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5451954564505545813/executions/bs.4c65f992071c26f6/testcases/1)

Flaky 2x on 3/14 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5616571615745246125/executions/bs.1783f322e90fef39/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6955969541834874878/executions/bs.c383cbdcced13c45/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 2x on 3/14 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5428566693430890806/executions/bs.bf5428ec082b5323/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8183871149504062821/executions/bs.309e6241d88eb45c/testcases/1)

**Comment by AndiAJ** [comment]
Failed 1x on 3/15 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6379957783228786887/executions/bs.3393de83b17b3d3b/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6379957783228786887/executions/bs.631488a7a0ffb393/testcases/1)

**Comment by sv-ohorvath** [comment]
Tried re-enabling the test but I hit this ANR https://github.com/mozilla-mobile/fenix/issues/24047

**Comment by AndiAJ** [comment]
Re-enabled with #7779
