### ISSUE TITLE
Intermittent UI test failure - < EnhancedTrackingProtectionSettingsTest.allowOtherContentTrackersTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6439]
### Stacktrace:
02-14 16:46:26.471: I/WindowManager(480): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 40acbb3 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5001ms for FocusEvent(hasFocus=false)
02-14 16:46:26.508: I/chatty(1826): uid=1041(audioserver) writer identical 4 lines
02-14 16:46:26.523: W/audio_hw_generic(1826): Hardware backing HAL too slow, could only write 0 of 661 frames
02-14 16:46:26.524: I/Icing(8598): Usage reports ok 1, Failed Usage reports 0, indexed 0, rejected 0
02-14 16:46:26.531: I/Icing(8598): IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=null serviceId=36
02-14 16:46:26.538: W/audio_hw_generic(1826): Hardware backing HAL too slow, could only write 0 of 661 frames
02-14 16:46:26.590: I/chatty(1826): uid=1041(audioserver) writer identical 3 lines
02-14 16:46:26.598: W/audio_hw_generic(1826): Hardware backing HAL too slow, could only write 0 of 661 frames
02-14 16:46:26.611: W/Icing(8598): No valid account for uploading user actions
02-14 16:46:26.613: W/audio_hw_generic(1826): Hardware backing HAL too slow, could only write 0 of 661 frames
02-14 16:46:26.631: I/ActivityManager(480): Force stopping org.mozilla.focus.debug appid=10153 user=0: finished inst
02-14 16:46:26.632: I/ActivityManager(480): Killing 11897:org.mozilla.focus.debug/u0a153 (adj 0): stop org.mozilla.focus.debug due to finished inst
02-14 16:46:26.628: W/audio_hw_generic(1826): Hardware backing HAL too slow, could only write 0 of 661 frames
02-14 16:46:26.638: I/ServiceChildProcess(12437): Destroying GeckoServiceChildProcess
02-14 16:46:26.638: W/Binder(11816): Caught a RuntimeException from the binder stub implementation.
02-14 16:46:26.638: W/Binder(11816): java.lang.SecurityException: Calling from not trusted UID!
02-14 16:46:26.638: W/Binder(11816): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
02-14 16:46:26.638: W/Binder(11816): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
02-14 16:46:26.638: W/Binder(11816): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
02-14 16:46:26.638: W/Binder(11816): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
02-14 16:46:26.638: W/Binder(11816): 	at android.os.Binder.execTransact(Binder.java:1123)
02-14 16:46:26.642: I/ServiceChildProcess(12540): Destroying GeckoServiceChildProcess
02-14 16:46:26.643: W/audio_hw_generic(1826): Hardware backing HAL too slow, could only write 0 of 661 frames
02-14 16:46:26.647: W/ActivityTaskManager(480): Force removing ActivityRecord{ae17cb2 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
02-14 16:46:26.649: I/ActivityManager(480): Killing 12437:org.mozilla.focus.debug:tab20/u0a153 (adj 0): stop org.mozilla.focus.debug due to finished inst
02-14 16:46:26.652: I/ActivityManager(480): Killing 12540:org.mozilla.focus.debug:gpu/u0a153 (adj 0): stop org.mozilla.focus.debug due to finished inst
02-14 16:46:26.654: D/WindowManager(480): notifyANR took 184ms

### Notes
❗ Not sure what is causing this crash
The last performed action was verifyPageContent("other content trackers not blocked") **so the UI test ran to completion**

[Logcat](https://github.com/mozilla-mobile/focus-android/files/8068179/allowOtherContentTrackersTest.txt)

Similar with #6436 and #6437

**Comment by AndiAJ** [comment]
Flaky 1x on 2/22 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5416923431159755803/executions/bs.fe2afa4b0ffbd789/testcases/2/test-cases)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail in the last months.

**Comment by sv-ohorvath** [comment]
Crashed again, once,  on 5/26:
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6663277129900157563/executions/bs.5a8af22a077545bd

**Comment by sv-ohorvath** [comment]
> Crashed again, once, on 5/26: https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6663277129900157563/executions/bs.5a8af22a077545bd
> 
> Not sure if relevant: `05-26 09:35:51.645: E/QueryController(13699): Got null root node from accessibility - Retrying... 05-26 09:35:51.841: D/CompatibilityChangeReporter(479): Compat change id reported: 135634846; UID 10152; state: DISABLED 05-26 09:35:51.847: D/CompatibilityChangeReporter(479): Compat change id reported: 143937733; UID 10152; state: ENABLED 05-26 09:35:51.850: I/ActivityManager(479): Killing 11896:com.android.providers.calendar/u0a65 (adj 985): empty #17 05-26 09:35:51.858: D/Zygote(290): Forked child process 15743 05-26 09:35:51.860: I/ActivityManager(479): Start proc 15743:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 for service {org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService} 05-26 09:35:51.883: I/sh.CrashHandle(15743): Late-enabling -Xcheck:jni 05-26 09:35:51.910: I/sh.CrashHandle(15743): Unquickening 12 vdex files! 05-26 09:35:51.911: W/sh.CrashHandle(15743): Unexpected CPU variant for X86 using defaults: x86 05-26 09:35:51.913: I/Zygote(290): Process 11896 exited due to signal 9 (Killed) 05-26 09:35:51.939: I/adbd(374): jdwp connection from 15743 05-26 09:35:51.946: I/libprocessgroup(479): Successfully killed process cgroup uid 10065 pid 11896 in 94ms 05-26 09:35:51.952: I/Gecko(14158): Exiting due to channel error. 05-26 09:35:51.972: I/ActivityManager(479): Process org.mozilla.focus.debug (pid 13699) has died: fg FGS `

From the logs it looks exactly the same with the known [ANR]( https://github.com/mozilla-mobile/fenix/issues/24047), but without the ANR reported (because the hang possibly took less than 5s which triggers the ANR).

**Comment by sv-ohorvath** [comment]
Notes: ANR reports moved to https://github.com/mozilla-mobile/focus-android/issues/7344
We will keep this issue for the [crash ](https://github.com/mozilla-mobile/focus-android/issues/6439#issuecomment-1148534537) not yet confirmed the same as the ANR
