### ISSUE TITLE
Clarify "Trackers blocked" is for the page you're currently viewing

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#644]
Filing this so we can keep track of the diff. conversations we're having. To be specific, this is about the "Trackers blocked 15" UI. Not, the switch next to it, etc.

From @bbinto:
> Because a) both things have a different lifetime/expiration which could cause confusion (at least it does it for me and I feel literally uncertain if I use the product properly), and b) we mention this turn on/off feature during onboarding as something they can do on a per site basis and not as a per session basis.

This might be a challenge with the string-freeze. But we can see what we think after triage. 

From @mheubusch:
> "Site trackers blocked" 

Thoughts? Are we maybe over thinking it at this point? Can we still get strings in?

**Comment by antlam** [comment]
![screen shot 2017-05-24 at 4 06 43 pm](https://cloud.githubusercontent.com/assets/1994820/26429328/0d77ca28-409b-11e7-9c04-c1cb638dd8e6.png)

@brampitoyo thoughts on this UX?

**Comment by bbinto** [comment]
I'm not sure about "Site trackers blocked", it makes me think too much what it means (might be me as non-English speaker) --- I'd suggest to keep the wording "Trackers blocked", and maybe just add the "i" next to it, link to our main sumo page and explain the UI there, i.e. in case people really want to know/care?

**Comment by antlam** [comment]
<img width="512" alt="image" src="https://cloud.githubusercontent.com/assets/1994820/26456822/1ae9d79a-4123-11e7-89d0-b87be43d2917.png">

In that case, maybe we can add the "more info" icon first and then measure? 

@pocmo spacing and sizing spec!

**Comment by bbinto** [comment]
I'm fine with that, yes, and link should go to the SUMO page.

@pocmo, can we please add a probe? Thanks

**Comment by brampitoyo** [comment]
@antlam Saying “Trackers Blocked” is good.

I’m more in the camp of verbose explanation, but if we want to create a new menu item under settings, we’ll need more time to finalise the string, which we don’t have. Maybe for the next version?

As a compromise, putting the info button on the side sounds like a good idea. The designs I mocked up in the past [(1)](https://d2ppvlu71ri8gs.cloudfront.net/items/1K1w2S0d1G3q000c1t2J/Menu%201%20-%20MDPI.png) [(2)](https://d2ppvlu71ri8gs.cloudfront.net/items/003V0b302y1A123U2k1p/Menu%202%20-%20MDPI.png) solves this problem similarly (pay no attention to the data visualisation).

**Comment by bbinto** [comment]
Thanks @brampitoyo, I like the wording "on this page" in your previous mocks, and since we've agreed on a string freeze, I agree that we should work on that/include that _After v1_.

**Comment by antlam** [comment]
@pocmo in the mock, I had it aligned vertically to the baseline of the trackers number. But this looks fine to me too!

**Comment by pocmo** [comment]
Removing the "needs triage" label as we agreed on only adding the "info button" to v1 and we have a patch for that in review.
