### ISSUE TITLE
Should experiments be disabled by default on Klar variants?

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#6448]
## Steps to reproduce
1. Install Klar.
1. Navigate to Studies.
1. Observe the default state.

### Expected behavior
- I think they should be disabled (similar to Telemetry).

### Actual behavior
- They are enabled.

### Device information

* Android device: All devices.
* Focus version: Any recent Klar build with Nimbus enabled.

**Comment by amedyne** [comment]
@athomasmoz Any thoughts or inputs on this?

**Comment by athomasmoz** [comment]
@amedyne if telemetry is disabled, then experiments should also be disabled.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Klar Nightly 100.01 (build 360891150 with GV 100.a01-20220329095604) with Google Pixel (Android 10).

The Studies are OFF by default.
