### ISSUE TITLE
Has anyone thought about password managers compatibility?

### ISSUE THREAD

**Issue by mikevelasquez02** [mozilla-mobile/focus-android#645]
It would be nice if the browser is compatible with password managers (LastPass, 1Password, etc). Currently, LastPass only detects debug.focus.mozilla.org as the returned URL.

**Comment by pocmo** [comment]
It heavily depends on how those password managers hook into the browser. We definitely do not want to "leak" the browsing session to third-party apps without the user agreeing to that first.

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Password manager support](https://trello.com/c/JBdgOAf1/42-password-manager-support)

**Comment by bbinto** [comment]
see #1810, closing this.
