### ISSUE TITLE
[L10N] The Pivacy Notice SUMO is in a different language when setting the device in Greek

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6453]
## Prerequisites
Focus has a fresh profile.

## Steps to reproduce
1. Set your device to Greek.
2. Open Focus - three-dot menu - Settings - Mozilla - Privacy Notice.
3. Observe the SUMO page opened.

### Expected behavior
The SUMO page is translated in Greek.

### Actual behavior
The SUMO page is in Netherlands, with the following link: https://www.mozilla.org/nl/privacy/firefox-focus/.
The SUMO page is opened in the previous language set to the device. I had tested the Netherland language before.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1)
* Focus version: Beta 98.0.0-beta.2, and on Nightly 99.0 (build 360420514 with GV 99.0a1-20220210065747)

[logcat.txt](https://github.com/mozilla-mobile/focus-android/files/8080009/logcat.txt)

![1645015868289](https://user-images.githubusercontent.com/40694158/154268705-481728f6-12ca-4199-b5e0-d5f956c39f56.jpg)

**Comment by kelimuttu** [comment]
I don't think this is on SUMO. The privacy notice page is hosted in mozilla.org and they're not translated in Greek, so maybe that's why they switch to the previously used language.

**Comment by Delphine** [comment]
@ peiying2: do you know how this is handled on mozilla.org side? Are the privacy notices supposed to be localized in just a subset of languages or is that a "requirement" for all languages? thanks!

**Comment by peiying2** [comment]
> @peiying2: do you know how this is handled on mozilla.org side? Are the privacy notices supposed to be localized in just a subset of languages or is that a "requirement" for all languages? thanks!

Correct. Greek is not one of the top 20-ish Firefox Desktop locales we support per agreements in 2021. Yes, almost all the legal docs are hosted on mozilla.org. The switch of languages to another non-English locale might be related to language setting in preferences. Normally, it would switch to English.

**Comment by kelimuttu** [comment]
@peiying2 do we have more information about why users see the page in NL instead of EN?

**Comment by peiying2** [comment]
> @peiying2 do we have more information about why users see the page in NL instead of EN?

What is the user's language setting in the browser preferences? I wonder if it had something to do with it. I commented on this. We do not have the legal doc in Greek at the moment.

**Comment by peiying2** [comment]
Here is the locale list that f Focus PN doc is localized in: https://github.com/mozilla/legal-docs/blob/dcdbab1711aa98b66b9aa8c23f06b0f219f737cb/.github/stats.json#L347

**Comment by kelimuttu** [comment]
> What is the user's language setting in the browser preferences? I wonder if it had something to do with it. I commented on this. We do not have the legal doc in Greek at the moment.

@lobontiumira should be able to answer that question.

**Comment by lobontiumira** [comment]
Hi all!
The device was set to Greek, and Focus was set to follow the device's language.
