### ISSUE TITLE
Beta builds no longer have the version of the build in About page

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6468]
## Steps to reproduce
1. Install any of the Beta 98.0.0 builds.
2. Go to Settings - Mozilla - About Firefox Focus Beta.
3. Observe the version of the build.

### Expected behavior
The full version is displayed 98.0.0-beta.1 (or 2, or 3).

### Actual behavior
Only 98.0 version is displayed.

### Device information
* Android device: All
* Focus version: Beta 98.0.0
* Beta 97.0.0-beta.6 displayed everything:

![beta](https://user-images.githubusercontent.com/40694158/154659511-52a1898f-4668-4e3b-a773-af589767f4e3.png)

**Comment by kbrosnan** [comment]
Maybe https://github.com/mozilla-mobile/focus-android/pull/6451 addresses this?

**Comment by Mugurell** [comment]
Seems to me also that https://github.com/mozilla-mobile/focus-android/pull/6399 caused the issue shown by Mira and then https://github.com/mozilla-mobile/focus-android/pull/6451 would come to address that.
Though the last patch shown the versionName parameter is not set when building test artifacts.

**Comment by lobontiumira** [comment]
Verified as fixed on the Beta 98.0.0-beta.4 build, using a Lenovo Tab M10 (Android 10):

![Screenshot_5](https://user-images.githubusercontent.com/40694158/155513682-94c361dd-127d-432a-9b9d-347b2a8292c6.jpg)
