### ISSUE TITLE
Enable about:config

### ISSUE THREAD

**Issue by uis246** [mozilla-mobile/focus-android#6474]
**Describe the bug**

about:config page is disabled. How otherwise I would change user agent and use proxy?

**To Reproduce**

1. Try to open about:config
2. See gray page

**Expected behavior**

See configs and be able to edit them.

**Actual behavior**

Can't edit configs.

**Comment by Mugurell** [comment]
Already addressed in 
https://github.com/mozilla-mobile/focus-android/issues/5831
https://github.com/mozilla-mobile/focus-android/issues/6210

**Comment by uis246** [comment]
I talking about release(Production), not about beta

**Comment by uis246** [comment]
@Mugurell

**Comment by cadeyrn** [comment]
@uis246 As you already noticed about:config was intentionally disabled for stable releases, similar to Firefox. So there is no point in this issue.
