### ISSUE TITLE
Consider changing "Search Privately" to "Search in Firefox Focus"

### ISSUE THREAD

**Issue by ksy36** [mozilla-mobile/focus-android#6478]
This issue might be too specific as it depends on the fact that certain browsers have to be installed on a device (in this case it's Opera, Firefox Focus and Firefox Focus Nightly), but it might be worth considering, to make it clear that the search will be performed in Firefox Focus.

Steps to Reproduce:
1. Navigate to any website in Firefox release or Firefox Nightly on Android.
2. Long press on any text until "Context" menu is displayed.
3. Tap the "three dots" button from the "Context" menu.
4. Observe the list of options.

Actual:
"Search Privately" is displayed 3 times and it's unknown which one is Firefox Focus.

Expected:
Able to differentiate in which browser the search will be performed.

While the first "Search privately" is coming from Opera and we have no control over that, 2 others could be potentially be changed (similarly to "Search in Edge").

![image](https://user-images.githubusercontent.com/1303908/154889305-4a163ee8-2eba-499b-9694-fd5257a1d62b.png)

**Comment by amedyne** [comment]
@jeffreygee Any thoughts on this?

**Comment by jeffreygee** [comment]
@amedyne yes, this can definitely be improved by making it more contextual for the user (i.e. Search in Focus). Do we have control over this specific string on our team? If so, I can work on a new string with our content team.

**Comment by mcarare** [comment]
@jeffreygee Yes, this string is provided by Focus, so we can change it.

**Comment by iorgamgabriel** [comment]
Set this as a "feature-request" and "UX" since we need the string from UX @jeffreygee

**Comment by jeffreygee** [comment]
@ewachowiak - I don't think Brian ever got to doing this. Not pressing, but whenever you have a moment we could use your recommendation. Happy to chat about!

**Comment by ewachowiak** [comment]
Yes I think it makes sense to change to "Search in Focus" but "Focus" needs to be coded as a variable to get the correct product name in all locales (and eng should leave a localization note for the string to say what the variable represents).

**Comment by lobontiumira** [comment]
Verified as fixed in the latest Focus Nightly 108.0a1 build from 10/28 with Oppo Reno 6 (Android 12), and Xiaomi Mi8 Lite (Android 10):

![search in](https://user-images.githubusercontent.com/40694158/198544991-5de6bf4f-f674-4c68-8dbb-d75a627d1448.jpg)

**Comment by lobontiumira** [comment]
Verified also on the latest Focus Beta build 108.0a1 with Sony Xperia Z5 Premium (Android 7.1.1), and Lenovo tablet M10 (Android 10).

![Screenshot_6](https://user-images.githubusercontent.com/40694158/201870454-e145197b-4f31-4c0e-9387-c1d978f33925.jpg)
