### ISSUE TITLE
Crash when initialising BrowserMenu because url == null

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#648]
Buddybuild detected a crash
`app/src/main/java/org/mozilla/focus/utils/Browsers.java` line `103`

```java


    private Map<String, ActivityInfo> resolveBrowsers(PackageManager packageManager, String url) {
        final Map<String, ActivityInfo> browsers = new HashMap<>();

        final Intent intent = new Intent(Intent.ACTION_VIEW);
        intent.setData(Uri.parse(url)); <-- CRASHED

        final List<ResolveInfo> infos = packageManager.queryIntentActivities(intent, 0);

        for (ResolveInfo info : infos) {
            browsers.put(info.activityInfo.packageName, info.activityInfo);
```

[View File](https://github.com/mozilla-mobile/focus-android/blob/1721b57308a090c272b7ba328f733298a6338963/app/src/main/java/org/mozilla/focus/utils/Browsers.java#L103) | [View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/9fcdd0272a15f2fdd58ed9ef2f09b61e)

**Comment by ahunt** [comment]
I've only seen this on 7.0 devices, we're getting two different traces due to NPE's in different locations in Uri.parse, either way it looks like url is null here.
