### ISSUE TITLE
Accessing a fullscreen webpage with the toolbar hidden will show a toolbar sized gap

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6481]
Additionally, because GV knows the page is fullscreen it will not allow to show/hide the toolbar so the content won't be reflown when scrolling.

https://user-images.githubusercontent.com/11428869/154947453-b5d0a417-0a23-416c-a9e5-7d5212ff0313.mp4

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Focus Nightly 104.0a1 build.
Tested with Sony Xperia Z5 Premium (Android 7.1.1), and Lenovo tablet M10 (Android 10).
