### ISSUE TITLE
Better support for PWAs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6482]
Tried using the https://airhorner.com/ PWA from https://connorjclark.github.io/pwa.rocks/ and saw that:
- there is no "Install" option in the menu but a "Add to Home screen" option - https://github.com/mozilla-mobile/focus-android/issues/6480
- the PWA icon is not correcly shown when installing it or on homescreen
- the toolbar does not behave properly:
   - before installing there is a toolbar sized gap at the bottom of the webpage - https://github.com/mozilla-mobile/focus-android/issues/6481
   - after installing Focus does not respect the "standalone" display property.

https://user-images.githubusercontent.com/11428869/154947988-dd011219-43f8-4e8a-ba2a-5f2bf2abd8e1.mp4

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801998

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
