### ISSUE TITLE
Update notificationOpenButtonTest ui test

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6486]
`notificationOpenButtonTest` was seen as failing in
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6876726315785070613 or
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6509423953918907733
or just leading to inconclusive test results like seen here https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6463908495974399455
and as such prevent new merges.

A quick fix to try and scroll the notifications didn't work so in https://github.com/mozilla-mobile/focus-android/pull/6411 this test was disabled.
@sv-ohorvath @AaronMT

**Comment by sv-ohorvath** [comment]
Thanks @Mugurell
