### ISSUE TITLE
Update compose to latest version - 1.1.0

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6487]
As a followup to https://github.com/mozilla-mobile/fenix/issues/23871 and https://github.com/mozilla-mobile/android-components/issues/11753.

Beside updating compose to `1.1.0` kotlin also needs to be updated to `1.6.10`.

**Comment by Mugurell** [comment]
https://github.com/mozilla-mobile/fenix/issues/23989 was fixed and this update was re-landed in AC.
Focus should be updated also.

**Comment by ionutbedregeanu** [comment]
Ticket already addressed
