### ISSUE TITLE
Update kotlin-coroutines to 1.6.0

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6488]
As a followup to https://github.com/mozilla-mobile/focus-android/issues/6487 which will increase the kotlin version to `1.6.10` according to https://kotlinlang.org/docs/releases.html#release-details the recommended version for `kotlin.coroutines` is `1.6.0`.

The `1.6.0` release comes with many changes
- https://blog.jetbrains.com/kotlin/2021/12/introducing-kotlinx-coroutines-1-6-0/
- https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md

which is why it was left out of https://github.com/mozilla-mobile/focus-android/issues/6487.

**Comment by ionutbedregeanu** [comment]
Can't be tested by QA, so I will move this ticket in Done

**Comment by Mugurell** [comment]
https://github.com/mozilla-mobile/fenix/issues/23989 was fixed and this update was re-landed in AC.
Focus should be updated also.

**Comment by ionutbedregeanu** [comment]
Can't be tested by QA, so I will close it
