### ISSUE TITLE
When Renaming a Shortcut the Favicon / Letter Should Reflect Updated Name

### ISSUE THREAD

**Issue by channingcarter** [mozilla-mobile/focus-android#6503]
As a user, when  rename a shortcut the first letter of the name should be updated to reflect the new name. Currently, when I update the name of the shortcut the first letter of the old name remains.

In the example below I have renamed People.com to Twitter and the P still remains instead of switching to T. This new functionality will align with the way shortcuts are handled on Focus iOS.

![image](https://user-images.githubusercontent.com/79924336/155348978-6f25ca62-0de8-4925-9746-4399f6cd6572.png)

**Comment by iorgamgabriel** [comment]
@channingcarter @amedyne Hello,
this is an enhancement not a bug . It's working like in specifications https://www.figma.com/file/KggJlo8pg2T2Q8nn0Ec5c3/Shortcuts?node-id=1836%3A46849
"Set shortcut tile graphic to first letter of web address (example: `M` for mozilla.org, `G` for google.com)" .
Thank you!

**Comment by channingcarter** [comment]
I know it's an enhancement @iorgamgabriel . I thought I added it as such.

**Comment by lobontiumira** [comment]
Verified as implemented on the latest Focus Nightly 99.0a1 (build 360600510 GV 99.0a1-20220228090129) with Oppo Find X3 Lite (Android 11), and Lenovo Tab M10 (Android 10).
