### ISSUE TITLE
TransactionTooLargeException in Android code

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#651]
Buddybuild detected a crash

[View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/953a29ee4a3aa8b79c2e09d64bb5920f)

**Comment by ahunt** [comment]
I don't know if/how we triggered this, all the threads are in Android framework code.

**Comment by ahunt** [comment]
These crashes happened on a pixel. One other pixel user has complained about the app hanging and eventually crashing, also on a Pixel, when using the menu. We're creating intents when inflating the menu, so I wonder if those reports are related to this crash.

See also:
https://developer.android.com/reference/android/os/TransactionTooLargeException.html

**Comment by pocmo** [comment]
We saw some new crashes. All happening on a single Google Pixel XL running Android 7.1.2.

**Comment by pocmo** [comment]
This happened on Joe's device and we were able to track it down. It's not actually a visible crash. This happens in the background when the app is killed by swiping it away in "recent apps".

Some further details:
* https://www.reddit.com/r/androiddev/comments/53690f/transactiontoolargeexception_crashes_on_nougat/
* http://blog.sqisland.com/2016/09/transactiontoolargeexception-crashes-nougat.html
* https://stackoverflow.com/questions/39098590/android-os-transactiontoolargeexception-on-nougat

From the postings it looks like the data saved in onSaveInstanceState might be too large. As we are not really permanently saving data and as the user is killing the app in this case (with no visible crash) we can look at this after the v1 release.

**Comment by liuche** [comment]
Looks like the other v1.1 issues are all being investigated or handled, so I'll investigate this issue and add any more information I learn.

**Comment by pocmo** [comment]
Okay, I have an idea how to fix this. :)
