### ISSUE TITLE
[gecko] XML Parsing Error: undefined entity

### ISSUE THREAD

**Issue by danilodorgam** [mozilla-mobile/focus-android#652]
When the device is in plane mode and tries to access some url

05-25 17:17:25.481 26522-26543/org.mozilla.focus.gecko.debug E/GeckoConsole: [JavaScript Error: "XML Parsing Error: undefined entity
                                                                             Location: jar:jar:file:///data/app/org.mozilla.focus.gecko.debug-1/base.apk!/assets/omni.ja!/chrome/toolkit/content/global/netError.xhtml
                                                                             Line Number 315, Column 34:" {file: "jar:jar:file:///data/app/org.mozilla.focus.gecko.debug-1/base.apk!/assets/omni.ja!/chrome/toolkit/content/global/netError.xhtml" line: 315 column: 34 source: "        <div id="ed_dnsNotFound">&dnsNotFound.longDesc;</div>"}]

**Comment by danilodorgam** [comment]
The same problem happens when you try to access internal files.
Example file: ///android_asset/rights-focus.html
Available in the app menu

**Comment by pocmo** [comment]
Builds using the gecko configuration are not feature complete and may be broken in various parts. If you build yourself then use the **focusWebkitDebug** configuration for now.

**Comment by grubdragon** [comment]
Without a working internet connection it doesn't work, so not only air plane mode

**Comment by ekager** [comment]
I don't think this is still a problem, closing.

**Comment by deepakmehra10** [comment]
The problem still persists. @ekager
