### ISSUE TITLE
when accessing language list for the first time, none are selected

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#654]
For the first time, the 'system locale' should be selected by default I think?

**Comment by npark-mozilla** [comment]
<img width="410" alt="screen shot 2017-05-25 at 5 47 01 pm" src="https://cloud.githubusercontent.com/assets/6930774/26472143/cfe8f67c-4172-11e7-9c54-0b6d3aa9339c.png">

**Comment by danilodorgam** [comment]
On the same subject:
In the configuration here comes written "system default" (in pt br) but if I check this option the app is in English.

The "default system" option should not be the default android language?

**Comment by npark-mozilla** [comment]
@danilodorgam thanks, raised a separate issue for this, as it seems pretty important.
