### ISSUE TITLE
[Experiment] Links set to open in new tabs / windows temporarily open in the background if clicked with tabs disabled

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#6542]
**[Affected Versions]:**
- Firefox Focus 97.2.0 (Build #360591303) GV: 97.0.1-20220216172458
- Firefox Focus 98.0 (Build #360591110) GV: 98.0.20220224185616

**[Affected Platforms]:**
- Android 9 (Samsung Galaxy S8)
-  Android 8 (HUAWEI P20 lite)

**[Prerequisites]:**
- Have a Focus for Android build with the following modifications:
     The following lines added to local.properties:
`nimbus.remote-settings.url = https://settings.stage.mozaws.net/`
`debuggable = true`
A new “.nimbus” file (in the same location as local.properties) containing the following line:
`https://settings.stage.mozaws.net`
- Have a Firefox Nightly for desktop profile open on “about:debugging”.
- Have  “Enable USB devices” enabled on “about:debugging”.

**[Steps to reproduce]:**
1. Open the browser from prerequisites to enroll in [Stage Copy Focus Android A/B v97 Experiment - New Users](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/stage-copy-focus-android-ab-v97-experiment-new-users) in the treatment branch (the branch you have been enrolled in can be found looking at logcat logs at startup with the "nimbus" filter set).
2. Close and open the app again (to avoid #6528).
3. Go to “Settings” > “Advanced” and enable “Remote debugging via USB/Wi-Fi”.
4. On the desktop “about:debugging” page, tap the “Connect” button of the Focus app option.
5. Tap the Focus option to view open tabs.
6. Navigate to https://www.rapidtables.com/web/html/link/html-link-new-window.html.
7. Tap the two “Open page in new window” links.
8. Observe the “Tabs” section of the “about:debugging” window.

**[Expected result]:**
-  The page opens in the current tab.
- The “Tabs” section in “about:debugging” displays only one tab.

**[Actual result]:**
-  The page does not seemingly open at all.
- The “Tabs” section in “about:debugging” displays multiple tabs.

**[Notes]:**
- The additional tabs are removed from the “Tabs” section if the user then navigates to another page.
- The issue was also reproducible for links on this page: https://www.freecodecamp.org/news/how-to-use-html-to-open-link-in-new-tab/
- Attached is a recording of the issue.

![new tabs hidden](https://user-images.githubusercontent.com/53752296/156175024-51ab4376-afa3-422a-b90e-a20e546a57c6.gif)

**Comment by heres-maria** [comment]
The issue is also reproducible for pop ups for which the user taps the "ALLOW" option when asked. Page used: https://www.webroot.com/services/popuptester1.htm.

**Comment by ionutbedregeanu** [comment]
@csadilek 
#### Short context
I started to work on this ticket and what I noticed is that we are receiving a blank("about:blank") tab when “Open page in new window” is clicked.
Since "about:blank" is not a valid url [shouldLoadInExistingTab](https://github.com/mozilla-mobile/focus-android/blob/bb63cc8cec4bbc602b663fefb74d9b63f442f797/app/src/main/java/org/mozilla/focus/tabs/MergeTabsMiddleware.kt#L97) returns false and cancel the flow, thats why “Open page in new window" doesn't a new page

#### My Question
Do you know why we are receiving that blank tab before the correct one?
Can you help with some details? I am trying to understand the flow

**Comment by csadilek** [comment]
> Do you know why we are receiving that blank tab before the correct one? Can you help with some details? I am trying to understand the flow.

@ionutbedregeanu Sure, the initial load of `about:blank` can not be avoided, unfortunately, and being worked around in various places in [A-C](https://github.com/mozilla-mobile/android-components/blob/main/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L466). For `window.open` it's also need for security reasons I can explain more separately. More details on the initial loading issue can be found in:
https://bugzilla.mozilla.org/show_bug.cgi?id=1634428
https://bugzilla.mozilla.org/show_bug.cgi?id=1447406

So, we will need to adjust the logic in Focus here for this. Can you share some more details? Why is `shouldLoadInExistingTab` needed? If tabs are not supported (in this experiment branch) shouldn't all sites open in the current page? Or in other words can we just add `about:` to the condition?

Also, happy to pair talk through in person if this helps.

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible. Links set to open in new windows / new tabs and allowed pop-ups open in the same tab. 
Users are not able to return to the initial page using the back button though, as seen in https://github.com/mozilla-mobile/focus-android/issues/6620.
Tested using Firefox Focus 100.0 (Build #360691240 GV: 100.a1-20220309094444) built as Release on Android 9 - Samsung Galaxy S8.

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible with the [New Users experiment](https://experimenter.services.mozilla.com/nimbus/focus-android-ab-v97-experiment-new-users-copy) on [Focus v98.3.0](https://github.com/mozilla-mobile/focus-android/releases/tag/v98.3.0)[](https://github.com/mozilla-mobile/focus-android/releases/latest) - Android 9 - Samsung Galaxy S8.
