### ISSUE TITLE
Focus is wrongly listed in the share list when chosing to share by long tapping a link

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/focus-android#6543]
**[Affected Versions]:**
- Firefox Focus 97.2.0 (Build #360591303) GV: 97.0.1-20220216172458
- Firefox Focus 98.0 (Build #360591110) GV: 98.0.20220224185616

**[Affected Platforms]:**
- Android 9 (Samsung Galaxy S8)
- Android 10 (Oneplus 6) 
- Android 8 (HUAWEI P20 lite)

**[Steps to reproduce]:**
1. Open the Focus browser.
2. Navigate to a page with links on it.
3. Long tap one of the links and select the "Share Link" option.
4. Observe the apps listed in the list.

**[Expected result]:**
-  Focus is not displayed in the app list.

**[Actual result]:**
-  The link can be shared with the Focus app.

**[Notes]:**
- Attached is a [recording of the issue](https://drive.google.com/file/d/1fu--hk8ppv83VbXYqnuWvtOZVqqnWEG8/view?usp=sharing).

**Comment by lobontiumira** [comment]
Reproducible on Beta 99.0.0-beta.1 with Xiaomi mi4i (Android 5.0.2).

**Comment by delia-pop** [comment]
Reproducible on Beta 99.0.0-beta.4  with Google Pixel (Android 12).

**Comment by Mugurell** [comment]
Fix should be available to test in the next Nightly.

**Comment by delia-pop** [comment]
Verified as fixed on the latest Focus Nightly 100.0a1 (Build 360830510 🦎 100.0a1-20220323094932) with Google Pixel 6 (Android 12), Xiaomi Redmi Note 8T (Android 9) and Huawei MediaPad M2 (Android 5.1.1). The current app is no longer listed in the share list.
