### ISSUE TITLE
Add unit tests for erase cfr in BrowserToolbarIntegrationTest

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6545]
At this moment only one test is written for erase cfr popup in BrowserToolbarIntegrationTest.
Since one of our goals is to improve the coverage of unit tests in Focus I added this ticket as a reminder to increase the coverage of BrowserToolbarIntegrationTest by adding another tests for erase cfr popup

**Comment by Mugurell** [comment]
Thank you for opening this Ionut!
As a drive-by I wanted to propose also adding tests for the newly added `CFRMiddleware` also to know that we have this bigger feature tested and safer from future regressions.

**Comment by ionutbedregeanu** [comment]
This ticket was merged, but can't be tested by QA, so I will close it
