### ISSUE TITLE
[Experiment] [Intermittent] The “Report Site Issue…” link either opens multiple tabs in the background or does not work if tabs are disabled

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#6546]
**[Affected Versions]:**
- Firefox Focus 97.2.0 (Build #360591303) GV: 97.0.1-20220216172458
- Firefox Focus 98.0 (Build #360591110) GV: 98.0.20220224185616 built as Release

**[Affected Platforms]:**
- Android 9 (Samsung Galaxy S8)
- Android 8 (HUAWEI P20 lite)

**[Prerequisites]:**
- Have a Focus for Android build with the following modifications:
     The following lines added to local.properties:
`nimbus.remote-settings.url = https://settings.stage.mozaws.net/`
`debuggable = true`
A new “.nimbus” file (in the same location as local.properties) containing the following line:
`https://settings.stage.mozaws.net`
- Have a Firefox Nightly for desktop profile open on “about:debugging”.
- Have  “Enable USB devices” enabled.

**[Steps to reproduce]:**
1. Open the browser from prerequisites to enroll in [Stage Copy Focus Android A/B v97 Experiment - New Users](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/stage-copy-focus-android-ab-v97-experiment-new-users) in the treatment branch (the branch you have been enrolled in can be found looking at logcat logs at startup with the `nimbus` filter set).
2. Close and open the app again (to avoid #6528).
3. Go to “Settings” > “Advanced” and enable “Remote debugging via USB/Wi-Fi”.
4. On the desktop “about:debugging” page, click the “Connect” button of the Focus app option.
5. Navigate to a page.
6. Tap “Report Site Issue…” 
7. Observe the “Tabs” section of the “about:debugging” window.
8. Repeat steps 5 - 7 a few times.

**[Expected result]:**
-  The page opens in the current tab.
- The “Tabs” section in “about:debugging” displays only one tab.

**[Actual result]:**
-  [Intermittent] The page does not open at all.
-  [Intermittent] The page opens seemingly in the same tab, but the “Tabs” section in “about:debugging” displays multiple tabs.

**[Notes]:**
- The UI of the Focus app only displays one tab.
- Restarting the app will make the page open if stuck in the case when it does not open.
- Attached is a [recording of the issue](https://drive.google.com/file/d/1Ja_KQ087WT_Dno35xNRUPyWJw_0padLd/view?usp=sharing).

**Comment by csadilek** [comment]
@ionutbedregeanu This is a bug in the `MergeTabsMiddleware` in Focus:

Currently when a new tab is added, this middleware intercepts the action, copies the old tab including its engine/gecko session, and assigns the new ID before closing the old/current tab. However, in case a new tab is being opened by a web extension (in this case the `webcompat` extension), the new tab will have its own new engine/gecko session, which will have to be used! Instead, the middleware will attempt to re-use the engine/gecko session from the old tab and simply leak the new engine/gecko session that was created for the extension tab.

This is the code path for new tabs being opened by web extensions: https://github.com/mozilla-mobile/focus-android/blob/7317cdb99050c4f96ae33b55a71b7329c9588725/app/src/main/java/org/mozilla/focus/FocusApplication.kt#L183

This new tab will have an engine session which will simply be discarded by the `MergeTabsMiddleware`. So the workaround in this middleware isn't good enough and doesn't handle the case where a new tab is created with an engine session.

/cc @Mugurell

**Comment by csadilek** [comment]
My suggestion for a fix in the middleware:
- Check if the new tab already has an engine session
- If it does, use it, instead of copying the old one
- Then close the old tab (but without unlinking it first so the old engine/gecko session is properly closed.)

**Comment by heres-maria** [comment]
The original issue is no longer reproducible. The page opens in only one tab, even if used multiple times. It does open "about:blank" first, though,  which can be seen with the device connected to "about:debugging" on desktop.  

- It seems like users are not able to return to the original page after  “Report Site Issue…” is accessed. I have filed #6620 for this.

- It also seems that the page still does not open if it was accessed from the "Your Rights" page, I have filed #6622 separately for this.

Tested using Firefox Focus 100.0 (Build #360681813 GV: 100.0a1-20220308100756) built as Release from the main branch and using Android 9 - Samsung Galaxy S8.

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible with the [New Users experiment](https://experimenter.services.mozilla.com/nimbus/focus-android-ab-v97-experiment-new-users-copy) on [Focus/Klar v98.2.0](https://github.com/mozilla-mobile/focus-android/releases/tag/v98.2.0) (98.2.0 Build #360722031 GV: 98.0.1-20220312140707) - Android 9 - Samsung Galaxy S8.
