### ISSUE TITLE
Some spelling errors in the new onboarding card

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6566]
## Steps to reproduce
1. Have a fresh profile.
2. Open Focus Nightly and observe the 
"Browse like it never happened
One tap erases your browsing history and cookies and stops ads from following you around." text from the onboarding card.

### Expected behavior
The text has no errors.

### Actual behavior
The text has 2 errors:
* an extra "--",
* an extra "r":
"Browse like it never happenede
One tap erases your browsing history and cookies--and stops ads from following your around." - please see the screenshot below.

### Device information
* Android device: all
* Focus version: Focus Nightly from 3/3 (build 360620510 GV 99.0a1-20220302065857)

![Screenshot_1](https://user-images.githubusercontent.com/40694158/156593357-295e1e34-3e2d-40c1-bee2-841011e879ce.jpg)

**Comment by indurs** [comment]
Can I work on this issue?

**Comment by indurs** [comment]
@Mugurell , Can I work on this issue?

**Comment by Mugurell** [comment]
> @Mugurell , Can I work on this issue?

Sure!
Seems like the the only change we'd need to make is removing the "r" from "following you**r** around".
We probably can just update the current string: https://github.com/mozilla-mobile/focus-android/blob/aa8ce02d30623e0fdf1c79435a48065827b60f16/app/src/main/res/values/strings.xml#L488

**Comment by indurs** [comment]
Thank You @Mugurell !
We need to also change focus-android/app/src/main/res/values-en-rGB/strings.xml
I've submitted the PR for this issue.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 100.0a1 (build 360730510 with GV 100.0a1-20220313093807):

![Screenshot_20220314-070900_Firefox Focus Nightly](https://user-images.githubusercontent.com/40694158/158122049-5795a5d7-3349-4203-89da-9b2b14aaad92.jpg)
