### ISSUE TITLE
Scrolling the page dispalys parts of the burger menu on 12newsnow.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#6573]
## Preconditions
VPN set to the US for access on the page

## Steps to reproduce
1. Navigate to: https://www.12newsnow.com/article/news/verify/joe-biden/fact-check-president-joe-biden-state-of-union-2022/536-22a16a29-d50a-486a-b99f-5e17c8c7d212.
2. Scroll the page.
3. Close the keyboard if the keyboard is triggered.
4. Observe the result
### Expected behavior
Scrolling the page presents no issues.
### Actual behavior
Upon scrolling the page, the burger menu, parts of the burger menu are displayed.
### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
* Focus version: Firefox Focus Nightly 99.0 (360630511-🦎99.0a1-202203003094735🦎)

**Notes:**
1. Reproducible regardless of the status of ETP.
2. Not reproducible using the latest build of Firefox Nightly in Normal Browsing Mode and in Private Browsing Mode.
3. Reproducible on both Release and Nightly Version of Firefox Focus.
4. Screenrecording attached:
![focus](https://user-images.githubusercontent.com/75027050/156749670-69bd9c42-88fb-4ec4-ab3b-e69aba29c76e.gif)

**Comment by Mugurell** [comment]
Seems like a browser layout issue. Moving to Bugzilla.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1758146

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
