### ISSUE TITLE
Status bar for onboarding screen should have the same color as the background of the screen 

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/focus-android#6585]
* Android device: all devices 
* Focus version: 99.0
@jeffreygee should modify Figma files to be without status bar. 
https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding-2022?node-id=2647%3A11565

Actual behavior 

![Actual behavior](https://user-images.githubusercontent.com/8118371/156990522-007ed30e-8700-4001-8a81-b6ca8e96f24c.png)

Expected behavior

![Expected behavior](https://user-images.githubusercontent.com/8118371/156997864-c8f5a381-ccde-4b5a-9df3-5f2ca8603ffc.png)

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 100.0a1 (build 360680510 with GV 100.0a1-20220308100756) with Samsung Galaxy Note 8 (Android 9), Xiaomi mi4i (Android 5.0.2), and Oppo Find X3 Lite (Android 11):

![Untitled](https://user-images.githubusercontent.com/40694158/157398448-7e6bb1d9-41e9-4ecf-8128-087ae8437ba2.png)
