### ISSUE TITLE
The bottom section of the context menu should be static in Landscape mode

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6593]
## Steps to reproduce
1. Open a webpage with linked images (i.e. https://en.wikipedia.org/).
2. Long tap on a linked image.
3. Rotate the device and landscape mode.
4. Scroll to the bottom of the context menu.
5. Scroll up and down and observe the dark purple section of the context menu.
### Expected behavior
The dark purple section of the context menu should be static when scrolling on Landscape mode.
### Actual behavior
The dark purple section of the context menu is dynamic, and can be hidden when scrolling on Landscape mode.
### Device information

* Android device: Google Pixel 6 (Android 12), LG G7 fit (Android 8.1.0), Samsung Galaxy note 8 (Android 9).
Note that the issue is not encountered on Lenovo Tab M10 (Android 10).

* Focus version:  latest Nightly from 03/07.
Reproducible on 98.1.0, 98.1.1 and 97.3.0.

https://user-images.githubusercontent.com/89388888/157066484-f529e29e-9119-4035-afd8-780ae395a413.mp4

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?

I went through these files in focus-android
1. BrowserFragment
2. ContextMenuFeature
3. ContextMenuFragment

If the hitresult is an image, we need to display the additional note below all the menu items in the context menu fragment.
The current issue is that in landscape mode the user can see the note only if they scroll down the menu items.

File to be modified - mozac_feature_contextmenu_dialog.xml in android-components

I just added the file mozac_feature_contextmenu_dialog.xml in focus-android just for preliminary testing. I made these changes to the file

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">


    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingBottom="16dp"
        android:scrollbars="vertical"
        app:layout_constraintBottom_toTopOf="@+id/additional_note"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.072" />

    <com.google.android.material.textview.MaterialTextView
        android:id="@+id/additional_note"
        style="@style/Mozac.Dialog.AdditionalNote"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="24dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>

and this is the ressult

https://user-images.githubusercontent.com/12825812/157382828-f15d6257-bd7d-43ad-9719-cc013831ee7d.mp4

**Comment by Mugurell** [comment]
@indurs Nice work on tracking down the source of the issue!
I've created https://github.com/mozilla-mobile/android-components/issues/11829 to fix this in A-C. 
If you want to work on that just leave a comment in the ticket so it can be assigned to you.

Regarding the proposed solution here it seems like you're on the right track but I still see an issue while in landscape with not all options being visible - seems like the `additional_note` covers the bottom part of the list.
Maybe is just needs `app:layout_constraintTop_toBottomOf="@id/recyclerView"`.

**Comment by indurs** [comment]
Thank You @Mugurell ! Will work on fixing this issue

**Comment by indurs** [comment]
@Mugurell , the space in landscape mode is not enough to display all the options above the additional_note.
Recyclerview is set to scroll vertically and hence the user can scroll to see all the options.

**Comment by indurs** [comment]
I see the issue which you've mentioned. The last two options are not visible even if I scroll.

**Comment by Mugurell** [comment]
Fix landed in AC - https://github.com/mozilla-mobile/android-components/pull/11830
Should be available to test in the next Nightly.

**Comment by indurs** [comment]
Thank You, @Mugurell

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 100.0a1 (build 360740511 with GV 100.0a1-20220314094248) with Samsung Galaxy Note 8 (Android 9), Xiaomi mi4i (Android 5.0.2), and Oppo Find X3 Lite (Android 11)
