### ISSUE TITLE
Support Orbot (Tor)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#66]
https://guardianproject.info/apps/orbot/
https://play.google.com/store/apps/details?id=org.torproject.android

By default Focus blocks different kinds of trackers. If we utilize Orbot (to route traffic through the Tor network) we can protected the privacy of the user in general.

This could be a setting that only shows up if Orbot is installed or we could actively promote it. Needs UX.

**Comment by pocmo** [comment]
_OrFox_ is based on Fennec. There used to be a version based on WebView called _Orweb_. This version is not developed anymore and had serious flaws.

> The problem is the behaviour of the internal browser view. It is based on the Android WebView which doesn't handle proxy settings of the internal stagefright player correctly. Therefore, the proxy (Orbot) is ignored for HTML5 video or audio elements. This could help a malicious person to get your actual ip address by inserting specific elements into your traffic.

http://xordern.net/why-you-really-shouldn%27t-use-orweb-anymore.html

>  Additionally, even though the proper API calls are made to turn off all plugins, apparently HTML5 video and audio players not considered plugins, and there is no way to disable them at an API level.

https://guardianproject.info/2013/08/21/orweb-security-advisory-possible-ip-leakage-with-html5-videoaudio/

> Orweb is built upon the bundled WebView (Webkit) browser component inside of the Android operating system. This has proven to be problematic because we cannot control the version of that component, and cannot upgrade it directly when bugs are found. In addition, Google has made it very difficult to effectively control the network proxy settings of all aspects of this component, making it difficult to guarantee that traffic will not leak on all devices and OS versions.

https://dev.guardianproject.info/projects/orfox-private-browser/wiki/Orfox_vs_Tor_Browser_FAQ

> Orweb does have an advantage which is that it less than 2MB while Orfox is in the 25-30MB range.

:)

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tor browser support](https://trello.com/c/sISoA8ZF/21-tor-browser-support)

**Comment by tomrittervg** [comment]
https://github.com/mozilla-mobile/focus-android/pull/825

**Comment by bbinto** [comment]
see also #825

**Comment by jerryn70** [comment]
We need  inbuilt download manager, then only we can use orbot connection for downloading also , otherwise when we download anything it will use our real IP because focus is using androids default download manager for downloading files.

**Comment by quakenet2** [comment]
Orfox is old. Tried Klar and it's impressive in file size but not UX.

**Comment by bbinto** [comment]
Met with team + Nathan, eng work is pretty much completed, UX needs to get their hands on the UI and see how we can message this/enable this in Focus. 

More info here: https://docs.google.com/document/d/1hA5SS9npOZCZdsSoD3LCN1d7MrYDs1C71rbAkV8Gwvc/edit

Barbara to meet with marketing regarding messaging.

**Comment by bbinto** [comment]
Chatted with Mike H. about messaging and proposed to look at the following potential comms material sources: 

- https://www.torproject.org/about/overview
- https://guardianproject.info/apps/orbot/

**Comment by bbinto** [comment]
We are currently holding this features until we consider using GeckoView for Focus.

**Comment by CaFI0** [comment]
> We are currently holding this features until we consider using GeckoView for Focus.

Are there any plans or updates on this yet?
