### ISSUE TITLE
Wired.com crashes focus

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#660]
Trying to open wired.com shuts down focus

**Comment by pocmo** [comment]
I can't reproduce this. Is this the latest beta build? Which Android version / device are you using?

@ahunt Does it crash on your device?

**Comment by ahunt** [comment]
I can repro when I disable all tracking protection options (only with a recent dev build, and not on the 2-week old beta). It looks like a strictmode violation:

05-26 11:25:46.432 4297-4306/org.mozilla.focus.debug W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.

**Comment by ahunt** [comment]
> 05-26 11:32:16.929 5085-5094/org.mozilla.focus.debug E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
>                                                                    java.lang.Throwable: Explicit termination method 'end' not called
>                                                                        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
>                                                                        at java.util.zip.Inflater.<init>(Inflater.java:104)
>                                                                        at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
>                                                                        at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
>                                                                        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:821)
>                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
>                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
>                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
>                                                                        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
>                                                                        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
>                                                                        at android.media.MediaHTTPConnection.seekTo(MediaHTTPConnection.java:205)
>                                                                        at android.media.MediaHTTPConnection.getSize(MediaHTTPConnection.java:366)
>                                                                        at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:80)
>                                                                        at android.os.Binder.execTransact(Binder.java:565)

**Comment by pocmo** [comment]
Ouch! This is in Android/WebView land? Seems like our only option is to not use `penalyDeath` on beta/release builds.
