### ISSUE TITLE
Intermittent UI test failure - < SafeBrowsingTest. unblockSafeBrowsingTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6602]
### Notes
❗ Not sure what is causing this crash
The last performed action was verifyPageContent("It’s an Attack!") so the UI test ran to completion

Similar with #6439 #6437 #6436 #6523 #6538 #6600 and #6601

[Logcat](https://github.com/mozilla-mobile/focus-android/files/8206570/unblockSafeBrowsingTest.txt)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by ionutbedregeanu** [comment]
Fails on https://github.com/mozilla-mobile/focus-android/pull/6618

**Comment by AndiAJ** [comment]
Flaky 1x on 6/17 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6462065286122160075/executions/bs.cd56cb8dd7f2e068)

06-16 22:31:23.275: I/WindowManager(477): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 4336382 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=false)
06-16 22:31:23.380: I/ActivityManager(477): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-16 22:31:23.380: I/ActivityManager(477): Killing 14933:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-16 22:31:23.364: I/chatty(1885): uid=1041(audioserver) writer identical 8 lines
06-16 22:31:23.379: W/audio_hw_generic(1885): Hardware backing HAL too slow, could only write 0 of 661 frames
06-16 22:31:23.386: D/AndroidRuntime(14831): Shutting down VM
06-16 22:31:23.391: I/ServiceChildProcess(15511): Destroying GeckoServiceChildProcess
06-16 22:31:23.392: W/ActivityTaskManager(477): Force removing ActivityRecord{b489d09 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-16 22:31:23.394: W/audio_hw_generic(1885): Hardware backing HAL too slow, could only write 0 of 661 frames
06-16 22:31:23.399: I/ServiceChildProcess(15381): Destroying GeckoServiceChildProcess
06-16 22:31:23.405: I/ActivityManager(477): Killing 15381:org.mozilla.focus.debug:tab22/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-16 22:31:23.406: I/ActivityManager(477): Killing 15511:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-16 22:31:23.408: D/WindowManager(477): notifyANR took 141ms

Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
