### ISSUE TITLE
Intermittent UI test failure - < WebControlsTest.verifyTextInputTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6603]
### Notes
❗ Not sure what is causing this crash
The last performed action was loadPage(htmlControlsPage)

Similar with #6439 #6437 #6436 #6523 #6538 #6600 #6601 and #6602

[Logcat](https://github.com/mozilla-mobile/focus-android/files/8206608/verifyTextInputTest.txt)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by AndiAJ** [comment]
Flaky 1x on 6/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5090948252601895631/executions/bs.dc118cf952d6be87)

06-19 08:48:21.942: E/QueryController(14234): Got null root node from accessibility - Retrying...
06-19 08:48:21.944: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.244: D/CompatibilityChangeReporter(481): Compat change id reported: 135634846; UID 10152; state: DISABLED
06-19 08:48:22.246: D/CompatibilityChangeReporter(481): Compat change id reported: 143937733; UID 10152; state: ENABLED
06-19 08:48:22.229: I/chatty(1850): uid=1041(audioserver) writer identical 19 lines
06-19 08:48:22.244: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.250: I/InputManager(481): Enabling motion classifier because timeout changed: feature enabled, long press timeout = 400
06-19 08:48:22.250: I/InputClassifier(481): Enabling motion classifier
06-19 08:48:22.259: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.264: I/cmd(16863): oneway function results will be dropped but finished with status OK and parcel size 4
06-19 08:48:22.318: I/binder(0): 481:16873 BC_REQUEST_DEATH_NOTIFICATION death notification already set
06-19 08:48:22.269: D/Zygote(290): Forked child process 16876
06-19 08:48:22.270: I/ActivityManager(481): Start proc 16876:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 for service {org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
06-19 08:48:22.274: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.276: I/cmd(16870): oneway function results will be dropped but finished with status OK and parcel size 4
06-19 08:48:22.289: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.297: I/sh.CrashHandle(16876): Late-enabling -Xcheck:jni
06-19 08:48:22.304: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.317: I/sh.CrashHandle(16876): Unquickening 12 vdex files!
06-19 08:48:22.319: W/sh.CrashHandle(16876): Unexpected CPU variant for X86 using defaults: x86
06-19 08:48:22.319: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.325: I/adbd(382): jdwp connection from 16876
06-19 08:48:22.332: I/Gecko(14744): Exiting due to channel error.
06-19 08:48:22.334: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.340: I/Zygote(290): Process 14234 exited cleanly (11)
06-19 08:48:22.349: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.440: I/ActivityManager(481): Process org.mozilla.focus.debug:gpu (pid 14860) has died: fg  FGS 
06-19 08:48:22.424: I/chatty(1850): uid=1041(audioserver) writer identical 5 lines
06-19 08:48:22.439: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.441: I/Zygote(290): Process 14860 exited cleanly (0)
06-19 08:48:22.441: I/libprocessgroup(481): Successfully killed process cgroup uid 10152 pid 14860 in 0ms
06-19 08:48:22.441: W/ActivityManager(481): Scheduling restart of crashed service org.mozilla.focus.debug/org.mozilla.gecko.process.GeckoChildProcessServices$gpu in 1000ms for connection
06-19 08:48:22.442: D/CompatibilityChangeReporter(481): Compat change id reported: 136219221; UID 10152; state: ENABLED
06-19 08:48:22.454: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.516: I/ActivityManager(481): Process org.mozilla.focus.debug (pid 14234) has died: fg  FGS 
06-19 08:48:22.499: I/chatty(1850): uid=1041(audioserver) writer identical 3 lines
06-19 08:48:22.514: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.520: I/libprocessgroup(481): Successfully killed process cgroup uid 10152 pid 14234 in 0ms
06-19 08:48:22.521: I/WindowManager(481): WIN DEATH: Window{904f2d4 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity}
06-19 08:48:22.521: W/InputDispatcher(481): Attempted to unregister already unregistered input channel '904f2d4 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)'
06-19 08:48:22.525: W/WindowManager(481): Cannot find window which accessibility connection is added to
06-19 08:48:22.526: W/WindowManager(481): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@4744f7c
06-19 08:48:22.529: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.544: W/ActivityManager(481): Crash of app org.mozilla.focus.debug running instrumentation ComponentInfo{org.mozilla.focus.debug.test/androidx.test.runner.AndroidJUnitRunner}
06-19 08:48:22.563: I/ActivityManager(481): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-19 08:48:22.564: I/ActivityManager(481): Killing 14744:org.mozilla.focus.debug:tab14/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-19 08:48:22.564: I/ActivityManager(481): Killing 16876:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 (adj 200): stop org.mozilla.focus.debug due to finished inst
06-19 08:48:22.565: W/ActivityManager(481): Bringing down service while still waiting for start foreground: ServiceRecord{6325bd6 u0 org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
06-19 08:48:22.544: W/audio_hw_generic(1850): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:48:22.571: I/Finsky(13291): [2] ukz.onTrimMemory(1): Memory trim requested to level 80
06-19 08:48:22.574: D/BufferPoolAccessor2.0(412): evictor expired: 1, evicted: 0
06-19 08:48:22.579: D/BufferPoolAccessor2.0(423): evictor expired: 1, evicted: 0
06-19 08:48:22.593: W/audio_hw_generic(1850): Not supplying enough data to HAL, expected position 1024848 , only wrote 806420
06-19 08:48:22.593: I/system_server(481): oneway function results will be dropped but finished with status OK and parcel size 4
06-19 08:48:22.603: I/MemoryTrimmer(10385): Trimming objects from memory, since app is in the background.
06-19 08:48:22.629: I/AppBase(2190): AppBase.onTrimMemory():615 onTrimMemory(): 5
06-19 08:48:22.629: I/GoogleInputMethodService(2190): GoogleInputMethodService.onTrimMemory():4225 onTrimMemory(): 5
06-19 08:48:22.672: D/AndroidRuntime(14144): Shutting down VM

**Comment by sv-ohorvath** [comment]
closing as dupe, in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
Some test reports that have this same error in the logs contain the ANR notification, some don't, so until we can tell if they are different issues, I will log them in one place.
