### ISSUE TITLE
[android 5] Cannot dismiss the tabs tray list

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6614]
## Steps to reproduce
1. Open multiple tabs, at least 2.
2. Tap on the counter tab.
3. Tap anywhere outside the tabs list, to dismiss it.

### Expected behavior
Tapping outside the tabs list, dismisses the list.

### Actual behavior
Nothing happens.
To dismiss it, the user has to select a different tab, or to close one tab. Then, the tabs list is dismissed.
In the short video below, I tried tapping outside the tabs list several times.

### Device information
* Android device: Xiaomi mi4i (Android 5.0.2)
* Not reproducible on Samsung Galaxy Note 8 (Android 9), Oppo Find X3 Lite (Android 11)
* Focus version: Beta 99.0.0-beta.1, and Focus Nightly 100.0a1 from 3/9

https://user-images.githubusercontent.com/40694158/157416772-63031073-0c3e-475e-9308-8139551604c8.mp4

**Comment by delia-pop** [comment]
Reproducible on RC 98.3.0 with Huawei MediaPad M2 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on RC 99.1.0 with Xiaomi mi4i (Android 5.0.2).

**Comment by lobontiumira** [comment]
Reproducible on Beta 100.0.0-beta.2 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 101.0a1 (build 361160507 GV 101.0a1-20220423065829) with Xiaomi mi4i (Android 5.0.2), and with Samsung Galaxy Tab A6 (Android 5.1.1).
