### ISSUE TITLE
[android 5] Error pages are almost blank

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6615]
## Steps to reproduce
1. Open the following error pages:
* https://itisatrap.org/firefox/its-a-trap.html
* https://itisatrap.org/firefox/its-an-attack.html
* https://itisatrap.org/firefox/unwanted.html
* https://itisatrap.org/firefox/harmful.html
* or any non-existing page, like aaaaaaaaa.ccccc
2. Observe the pages.

### Expected behavior
The deceptive pages display some details regarding the dangerous/deceptive page, and the "Try again" button.

### Actual behavior
The deceptive sites no longer display the details regarding the dangerous/deceptive page, and the "Try again" button.

### Device information
* Android device: Xiaomi mi4i (Android 5.0.2)
* Not reproducible on Samsung Galaxy Note 8 (Android 9)
* Focus version: Beta 99.0.0-beta.1
* **Not reproducible on Focus Nightly 100.0a1** (build 360680509 with GV 100.0a1-20220308100756)

![android 5](https://user-images.githubusercontent.com/40694158/157425791-d4780256-1d63-4abd-af34-fda6d34a3610.png)

**Comment by ionutbedregeanu** [comment]
@lobontiumira Please retest on the latest beta. I tried to reproduce it on Nexus 6 Android 5.1 but I didn't succeed

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the latest Beta 100.0.0-beta.5 on Xiaomi mi4i (Android 5.0.2):
![Untitled](https://user-images.githubusercontent.com/40694158/163776352-7c333d76-acd9-4f6c-b31a-de98ff5ab3ae.png)
