### ISSUE TITLE
Slow browser menu

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#662]
The browser menu is sometimes slow. I want to at least refactor `Browsers` so that we do not do the package lookups all the time.

**Comment by pocmo** [comment]
> I want to at least refactor Browsers so that we do not do the package lookups all the time.

This seems to be not that easy. Our queries depend on the current URL (to suggest default apps that only handle specific URLs - like a reddit app for a reddit URL).

Some research seams to point to loadLabel() (and loadIcon) being slow. We could try to repload / cache at least the ones for normal browsers.

**Comment by ahunt** [comment]
The same issue affects settings - DefaultBrowserPreference also uses Browsers, which is probably why.

Disabling loadLabel() calls everywhere doesn't seem to improve things for me (I've been able to reduce huge slowness in the menu since yesterday), disabling most of Browsers makes the menu fast again, so it looks like the problem is still somewhere in Browsers.

**Comment by ahunt** [comment]
packageManager.resolveActivity() is taking about 200ms (N6P, unreliable wifi connection) for any browser that isn't installed. We loop over a long list of browsers (to test whether they're installed) in findKnownBrowsers(), hence the big delay.

**Comment by ahunt** [comment]
I've got a quick and simple fix, but I wonder if we should migrate to queryIntentActivities(), we could then iterate over the list of browsers the user actually has installed (see https://groups.google.com/a/chromium.org/forum/#!topic/chromium-bugs/5AmLhXHaPUM for more).

**Comment by pocmo** [comment]
> I've got a quick and simple fix, but I wonder if we should migrate to queryIntentActivities()

The problem with queryIntentActivities is that on Android M+ it only returns the default browser (if one is set). Even if you have multiple browsers installed they won't be returned [[1]](https://medium.com/google-developer-experts/intent-resolving-in-android-m-c17d39d27048).

**Comment by pocmo** [comment]
@antlam Can you confirm that this is fixed for builds >= 1784?

**Comment by antlam** [comment]
I'm on 1784 and it looks to be a lot better now. Still a bit slow but I'd say that fixed it!

**Comment by pocmo** [comment]
Thanks!
