### ISSUE TITLE
[Experiment] Users are unable to return to the previous page after accessing “Report Site Issue…” with multiple tabs disabled

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#6620]
**[Affected Versions]:**
- Firefox Focus 100.0 (Build #360681813 GV: 100.0a1-20220308100756) built as Release

**[Affected Platforms]:**
- Android 9 (Samsung Galaxy S8)

**[Prerequisites]:**
- Have a Focus for Android build with the following modifications:
     The following lines added to local.properties:
`nimbus.remote-settings.url = https://settings.stage.mozaws.net/`
`debuggable = true`
A new “.nimbus” file (in the same location as local.properties) containing the following line:
`https://settings.stage.mozaws.net`

**[Steps to reproduce]:**
1. Open the browser from prerequisites to enroll in [Stage Copy Focus Android A/B v97 Experiment - New Users](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/stage-copy-focus-android-ab-v97-experiment-new-users) in the treatment branch (the branch you have been enrolled in can be found looking at logcat logs at startup with the `nimbus` filter set).
2. Navigate to a page.
3. Tap “Report Site Issue…”
4. Open the overflow menu and observe the Go Back One Page button.

**[Expected result]:**
-  You are able to navigate back to the page you were on before opening the “Report Site Issue…” page.

**[Actual result]:**
- You are not able to navigate back to the previous page.

**[Notes]:**
- Attached is a recording of the issue.
![cannot go back one page](https://user-images.githubusercontent.com/53752296/157487526-1eb2070e-03ad-4730-842b-78401d745de5.gif)

**Comment by Mugurell** [comment]
I think this is expected.
Also saw while testing that in the cases of opening pages from extensions (like in this case) or from `window.open` because we'd use a new `EngineSession` there will be no history.

@csadilek  to confirm.

**Comment by csadilek** [comment]
Yes, I agree. I think that's the best we can do for the scope of this experiment. These are all features relying on the fact that browsers support tabs.

**Comment by heres-maria** [comment]
This behavior is also seen for links set to open in new tabs / windows and pop-ups which the user has allowed.
