### ISSUE TITLE
[android 5] The notification bar's icon is white

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6627]
## Steps to reproduce
1. Open a page.
2. Minimise the app.
3. Drag the notification bar and observe the Focus icon near the "Open" option from the notification

### Expected behavior
The Focus icon is visible.

### Actual behavior
The Focus icon is white, and barely visible.

### Device information
* Android device: Xiaomi mi4i (Android 5.0.2)
* Focus version: Beta 99.0.0-beta.1, Focus Nightly 100.0a1
* Not reproducible on Oppo Find X3 Lite (Android 11), Samsung Galaxy Note 8 (Android 9)

![Screenshot_4](https://user-images.githubusercontent.com/40694158/157611316-2b65dd9c-67e7-4a67-add2-654ac3aa9822.jpg)

**Comment by lobontiumira** [comment]
Also, the media icon is white, on the same device:

![android 5](https://user-images.githubusercontent.com/40694158/157834276-8f6a7c42-0f15-49be-9dab-a924e5e2d8e6.png)

**Comment by lobontiumira** [comment]
Reproducible on RC 99.1.0 with Xiaomi mi4i (Android 5.0.2).

**Comment by lobontiumira** [comment]
Reproducible on Beta 100.0.0-beta.3 with Xiaomi mi4i (Android 5.0.2).

**Comment by lobontiumira** [comment]
Reproducible on the latest Focus nightly build 102.0a1 with Xiaomi mi4i (Android 5.0.2).

**Comment by lobontiumira** [comment]
Still reproducible on RC 101.1.0 with the same Xiaomi mi4i (Android 5.0.2) device.

**Comment by lobontiumira** [comment]
Reproducible with the same Xiaomi mi4i (Android 5.0.2) device on Beta 102.0.0-beta.5.

**Comment by lobontiumira** [comment]
Reproducible with the same Xiaomi mi4i (Android 5.0.2) device on RC 102.1.0.

**Comment by Mugurell** [comment]
Seems like we need `drawable-night` versions of these drawables.
@lobontiumira Does the issue with the speaker being white happens on Fenix also when testing on the Xiaomi device?

**Comment by lobontiumira** [comment]
@Mugurell it is reproducible also on the latest Fenix Nightly in private mode:

![Fenix Nightly](https://user-images.githubusercontent.com/40694158/177164608-ac521f39-791f-4b69-adb5-ad40a590b85f.png)

**Comment by lobontiumira** [comment]
Reproducible on Beta 104.0b1 with Xiaomi mi4i (Android 5.0.2).

**Comment by mcarare** [comment]
This looks like a device-specific problem to me.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802646

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
