### ISSUE TITLE
Disabling metrics setting workflow.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#6628]
In the current implementation, we might send metrics after the setting has been turned off, until the next app restart.

@lobontiumira: can QA test for this? Thank you!

**Comment by lobontiumira** [comment]
Verified as implemented on the latest Focus Nightly 100.0a1 (build 360870510 with GV 100.0a1-20220327093354) with Google Pixel (Android 10).
After the "Send usage data" is disabled, the metrics are not sent.
Enabling the "Send usage data", the metrics are being sent properly.
