### ISSUE TITLE
Feature Request: Night mode (for websites)

### ISSUE THREAD

**Issue by bdtoole** [mozilla-mobile/focus-android#663]
Please add a night mode/inverted color mode.

**Comment by pocmo** [comment]
Isn't the Focus UI already pretty dark? Or do you want a night mode for websites?

**Comment by bdtoole** [comment]
I like the UI, but I mean for websites. I know there are a fair number of mobile browsers out there that accomplish this to varying degrees of success. The closest I can think of as far as webview-based browsers go is Lightning, however that inverts the color scheme of images and videos on the pages as well. Normally images correct themselves once a page is fully loaded, but videos remain completely inverted, and that causes some really funky display issues.

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support for Nightmode](https://trello.com/c/4mxdOAB1/45-support-for-nightmode)

**Comment by huuhaa** [comment]
I see this is moved  to roadmap. Hope you will add this at main menu, under  block tracker switch new nigtmode swich so it would be quickly accessible.

**Comment by huuhaa** [comment]
@pocmo @bbinto 
Is there any ETA on ths one?

**Comment by mcomella** [comment]
@huuhaa Unfortunately, no – we prioritized this as a P5, which means it's not something we're prioritizing primary development time on but something we'd accept a patch to fix.

**Comment by autonome** [comment]
I really want this for the content area when Focus first opens.

Focus is my default browser, so it's blinding when I click on a link from an external app:

![screenshot_20181028-092920](https://user-images.githubusercontent.com/50103/47614259-e06c2980-da94-11e8-9ee0-940c75de3a94.png)

**Comment by moshpirit** [comment]
Definitely a must. It blinds my eyes during the night, this is why I use Firefox with [Dark Reader](https://github.com/darkreader/darkreader) instead when I'm in bed. How difficult would it be to implement? (I'm no dev, sorry, I have no idea)

**Comment by kelimuttu** [comment]
We received a request for this feature recently from the [GPS review](https://play.google.com/store/apps/details?id=org.mozilla.focus&reviewId=gp:AOqpTOE0T3L5mnQGb89wtERnf9JGreTtJTdEecsgjbGUQHahNl-OQvQ06lbNbC2NEU1-INdUdRo1kZA6135a6iM). 

> I'm conflicted. Focus used to be my most used browser. It's simple, quick, limited ad + tracking leak, no history log. Only downside is the lack of a dark mode for web pages. Would be great if there were a work around to integrate ""essential"" extensions, perhaps ones that meet a privacy/security standard. Definitely a dark mode! I use different browsers for different purposes but without dark mode, I see Focus less and less. Still, there is no clean solution to fill its void. #darkintegration

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801918

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
