### ISSUE TITLE
[L10N RTL] Beta build version is not displayed fully on RTL languages

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6641]
## Steps to reproduce
1. Set the device to any RTL language.
2. In Focus Beta, go to Settings - Mozilla - About, and observe the build version.

### Expected behavior
The Beta build version is displayed fully.

### Actual behavior
The Beta build version is not displayed fully.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9)
* Focus version: Beta 99.0.0-beta.1

![Screenshot_1](https://user-images.githubusercontent.com/40694158/157879443-d1348f23-dabe-4fd0-a8f3-3581554b8968.jpg)

**Comment by lobontiumira** [comment]
This issue is still reproducible on Beta 100.0.0-beta.3.

**Comment by lobontiumira** [comment]
Reproducible on Beta 101.0.0-beta.1 with Xiaomi Mi8 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 102.0.0-beta.2 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 103.0.0-beta.1 with Lenovo tablet (Android 10).

**Comment by Mugurell** [comment]
The versions header has been modified in the meantime and the offending dash disappeared.
The l10n team helped confirm in https://github.com/mozilla-mobile/focus-android/pull/7358#issuecomment-1190702461 that the current state is fine.

<image src="https://user-images.githubusercontent.com/11428869/180142504-30304d9f-cbac-4396-ba4b-c17b0f5a5ea0.png" width="33%" />

@lobontiumira Do you agree on closing this ?

**Comment by ItielMaN** [comment]
Hmm, how does this currently look like in beta? If the "beta" part still appears on the left, the whole thing should be LTR (while retaining the same text alignment.

**Comment by lobontiumira** [comment]
@ItielMaN this is how it looks now in Beta 103.0.0-beta.5:

![Untitled](https://user-images.githubusercontent.com/40694158/180194852-0ed031bf-92fa-4150-8782-385eaefeb55a.png)

**Comment by ItielMaN** [comment]
If this would look the same without the dash (as @Mugurell mentioned), i.e. if the number is on the right and the beta (which I assume is not localizable) appears on the left, it should be set to LTR whilw being aligned to the right. Injecting LRM before the version number would also work.

**Comment by Mugurell** [comment]
@ItielMaN Sorry, I cannot guarantee about the dash. The version appearing there is set in the release process.
So I guess just to be sure we do need the patch from https://github.com/mozilla-mobile/focus-android/pull/7358 ?

**Comment by ItielMaN** [comment]
The dash is not really a factor tbh. In any case if the current end result is version on the right and `beta` on the left, an marker is needed.
So yes, the patch would be still needed, but why RLM? I think LRM (`U+200E`) would be needed instead?

**Comment by Mugurell** [comment]
@ItielMaN Added now both directional marks. Please help choose the right one.

| | Focus with RLM | Focus with LRM |
| --- | --- | --- |
| English | <img src="https://user-images.githubusercontent.com/11428869/180236516-4c9fed89-1342-443e-be80-eacd5e9a2e78.png" /> | <img src="https://user-images.githubusercontent.com/11428869/180236327-3dc74e85-2862-4094-9a93-e172456aab00.png" /> |
| Arabic | <img src="https://user-images.githubusercontent.com/11428869/180239827-b1aa8fb2-77c3-400b-9887-4ef127e86742.png" /> | <img src="https://user-images.githubusercontent.com/11428869/180236211-519bef6e-d975-4e01-bc58-425981ed71b7.png" /> |

**Comment by ItielMaN** [comment]
@Mugurell `Focus with LRM (u200E)` LGTM

**Comment by Mugurell** [comment]
@ItielMaN @mcarare Proposed in yet another approach which would result in the following:

| &nbsp; | &nbsp; |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11428869/180252510-c5651cc8-9a17-40b2-9402-2c929292304a.png" /> | <img src="https://user-images.githubusercontent.com/11428869/180378785-c24c541c-2420-4fb8-8fa4-acc589478f4a.png" /> |

Can you help choose between the result from this or the ones from when using `u220E` ?

**Comment by ItielMaN** [comment]
The new approach still looks broken to me.
I don't think passing the current locale will help here, because we need it to be displayed as LTR regardless of the current locale.
A non-hacky solution could be to set the android equivalent of CSS's `direction: ltr;` and `text-align: match-parent;`.

**Comment by Mugurell** [comment]
Thank you for the support @ItielMaN!
We can indeed also enforce LTR in code without the need of the LTR mark.
Tested [this change](https://github.com/mozilla-mobile/focus-android/pull/7404/files#diff-b8abb8c8d842c3f8fe0fe2088ef8bcbbfa0bf94f06629d8e624e6801ddbf3db8R175) and saw the same results as when using the LTR mark.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 105.0a1 from 7/26 with:
* Sony Xperia Z5 Premium (Android 7.1.1), and
* Lenovo tab M10 (Android 10).
![Screenshot_20220726-100222](https://user-images.githubusercontent.com/40694158/180945028-b2852fdd-7b51-4c45-9bfd-a7d257954f6f.png)

**Comment by lobontiumira** [comment]
Verified as fixed also on Beta 104.0b1:

![Screenshot_2022-07-26-17-05-03-253_org mozilla focus beta](https://user-images.githubusercontent.com/40694158/181026066-74dbd1c5-41eb-485d-a3fe-51a9da6dc98f.png)
