### ISSUE TITLE
Intermittent UI test failure - < EnhancedTrackingProtectionSettingsTest. addURLToTPExceptionsListTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6661]
Firebase Test Run: [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5951643588451289313/executions/bs.9ba7445f3fc7d967/testcases/2)

Build: 3/11 Main

Stacktrace: 
03-11 12:02:33.938: I/WindowManager(482): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: faa9e6 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5004ms for FocusEvent(hasFocus=true)
03-11 12:02:34.071: E/Finsky(12480): [842] luj.b(5): Error getting device settings.
03-11 12:02:34.071: E/Finsky(12480): network time: 1835, HTTP status code: 404, exception com.android.volley.ClientError
03-11 12:02:34.071: E/Finsky(12480): 	at waj.hn(Unknown Source:4)
03-11 12:02:34.071: E/Finsky(12480): 	at dbq.r(PG:2)
03-11 12:02:34.071: E/Finsky(12480): 	at fam.r(PG:3)
03-11 12:02:34.071: E/Finsky(12480): 	at dbj.run(PG:3)
03-11 12:02:34.071: E/Finsky(12480): 	at android.os.Handler.handleCallback(Handler.java:938)
03-11 12:02:34.071: E/Finsky(12480): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-11 12:02:34.071: E/Finsky(12480): 	at android.os.Looper.loop(Looper.java:223)
03-11 12:02:34.071: E/Finsky(12480): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
03-11 12:02:34.071: E/Finsky(12480): 	at java.lang.reflect.Method.invoke(Native Method)
03-11 12:02:34.071: E/Finsky(12480): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-11 12:02:34.071: E/Finsky(12480): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-11 12:02:34.071: E/Finsky(12480): [842] luc.b(1): Error while refreshing device settings: network time: 1835, HTTP status code: 404, exception com.android.volley.ClientError. Retrying.
03-11 12:02:34.071: E/Finsky(12480): network time: 1835, HTTP status code: 404, exception com.android.volley.ClientError
03-11 12:02:34.071: E/Finsky(12480): 	at waj.hn(Unknown Source:4)
03-11 12:02:34.071: E/Finsky(12480): 	at dbq.r(PG:2)
03-11 12:02:34.071: E/Finsky(12480): 	at fam.r(PG:3)
03-11 12:02:34.071: E/Finsky(12480): 	at dbj.run(PG:3)
03-11 12:02:34.071: E/Finsky(12480): 	at android.os.Handler.handleCallback(Handler.java:938)
03-11 12:02:34.071: E/Finsky(12480): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-11 12:02:34.071: E/Finsky(12480): 	at android.os.Looper.loop(Looper.java:223)
03-11 12:02:34.071: E/Finsky(12480): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
03-11 12:02:34.071: E/Finsky(12480): 	at java.lang.reflect.Method.invoke(Native Method)
03-11 12:02:34.071: E/Finsky(12480): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-11 12:02:34.071: E/Finsky(12480): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-11 12:02:34.072: I/Finsky(12480): [842] abvs.n(4): SCH: jobFinished: 31-305419896. TimeElapsed: 1997ms.
03-11 12:02:34.072: I/Finsky(12480): [2] abuj.e(7): SCH: Job 31-305419896 finished. Rescheduling.
03-11 12:02:34.073: I/Finsky(12480): [2] abui.handleMessage(68): SCH: RunningQueue size: 3, PendingQueue size: 0
03-11 12:02:34.073: I/Finsky(12480): [2] abuj.p(3): SCH: Running queue: 10-3 10-33 10-82 
03-11 12:02:34.188: I/ActivityManager(482): Force stopping org.mozilla.focus.debug appid=10153 user=0: finished inst
03-11 12:02:34.188: I/ActivityManager(482): Killing 13884:org.mozilla.focus.debug/u0a153 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-11 12:02:34.192: W/Binder(13815): Caught a RuntimeException from the binder stub implementation.
03-11 12:02:34.192: W/Binder(13815): java.lang.SecurityException: Calling from not trusted UID!
03-11 12:02:34.192: W/Binder(13815): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
03-11 12:02:34.192: W/Binder(13815): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
03-11 12:02:34.192: W/Binder(13815): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
03-11 12:02:34.192: W/Binder(13815): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
03-11 12:02:34.192: W/Binder(13815): 	at android.os.Binder.execTransact(Binder.java:1123)
03-11 12:02:34.201: I/ServiceChildProcess(14414): Destroying GeckoServiceChildProcess
03-11 12:02:34.201: W/ActivityTaskManager(482): Force removing ActivityRecord{3459912 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t10 f}}: app died, no saved state
03-11 12:02:34.207: D/AndroidRuntime(13815): Shutting down VM
03-11 12:02:34.213: I/ServiceChildProcess(14278): Destroying GeckoServiceChildProcess
03-11 12:02:34.226: I/cus.debug:tab1(14278): System.exit called, status: 0
03-11 12:02:34.226: I/AndroidRuntime(14278): VM exiting with result code 0, cleanup skipped.
03-11 12:02:34.234: I/focus.debug:gp(14414): System.exit called, status: 0
03-11 12:02:34.234: I/AndroidRuntime(14414): VM exiting with result code 0, cleanup skipped.
03-11 12:02:34.236: I/ActivityManager(482): Killing 14278:org.mozilla.focus.debug:tab18/u0a153 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-11 12:02:34.237: I/ActivityManager(482): Killing 14414:org.mozilla.focus.debug:gpu/u0a153 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-11 12:02:34.249: D/WindowManager(482): notifyANR took 314ms

Notes
❗ Not sure what is causing this crash
The last performed action was verifyPageContent("Tracker Blocking")

Similar with https://github.com/mozilla-mobile/focus-android/issues/6439 https://github.com/mozilla-mobile/focus-android/issues/6437 https://github.com/mozilla-mobile/focus-android/issues/6436 https://github.com/mozilla-mobile/focus-android/issues/6523 https://github.com/mozilla-mobile/focus-android/issues/6538 https://github.com/mozilla-mobile/focus-android/issues/6600 https://github.com/mozilla-mobile/focus-android/issues/6601 https://github.com/mozilla-mobile/focus-android/issues/6602 and #6603

[Logcat](https://github.com/mozilla-mobile/focus-android/files/8245686/addURLToTPExceptionsListTest.txt)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/22 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7063070257947525440/executions/bs.db5c53d95bcf9f5e/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7805666101114109673/executions/bs.fe1289641c3ecf97/testcases/1)

**Comment by sv-ohorvath** [comment]
Possibly same ANR as https://github.com/mozilla-mobile/fenix/issues/24047

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
