### ISSUE TITLE
~46ms regression to COLD VIEW nav start (Sentry SDK?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#6664]
On 3/10, we see a regression of about ~46ms from our weekly backfill (that I don't think we see in fenix):
![image](https://user-images.githubusercontent.com/759372/158246410-32e49622-9ad6-4fd7-8b35-9541f4c5de03.png)

Let's find the cause. You can use [`backfill.py`](https://github.com/mozilla-mobile/perf-tools/blob/main/backfill.py) to bisect the commit that caused the issue – let me know if you have questions.

**Comment by mcomella** [comment]
Triage: jonalmeida suggested we landed the Sentry SDK on that day so that's probably what changed.

**Comment by mcomella** [comment]
Triage: Jonalmeida said they'd do a manual bisection.

**Comment by ionutbedregeanu** [comment]
Using [backfill.py](https://github.com/mozilla-mobile/perf-tools/blob/main/backfill.py) I measured for Focus Nightly the cold start up duration(cold_view_nav_start) before and after [this pr](https://github.com/mozilla-mobile/focus-android/pull/6610)
As you can see the median values are pretty similar(19ms)
#### Results for 03.09.2022 vs 03.08.2022
<img width="758" alt="Screenshot 2022-05-25 at 15 00 17" src="https://user-images.githubusercontent.com/11731652/170257159-df04a089-2cb8-4c00-91e0-3223fff727ce.png">

On the other hand I noticed a considerable difference after [this pr](https://github.com/mozilla-mobile/focus-android/pull/6624#issuecomment-1063419500)
I will take a look in AC to see what changes were made in that update
<img width="733" alt="Screenshot 2022-05-25 at 15 33 29" src="https://user-images.githubusercontent.com/11731652/170262893-9109657f-21e9-48d6-b79f-01c48be311a4.png">

**Comment by ionutbedregeanu** [comment]
@jonalmeida @mcomella After some investigation made with git bisect in AC I noticed a regression after [this change](https://github.com/mozilla-mobile/android-components/pull/11831)
#### Before gecko update
<img width="695" alt="Screenshot 2022-05-27 at 14 23 57" src="https://user-images.githubusercontent.com/11731652/170690507-deaa2dba-d3a0-44c6-a33e-2c38aa129058.png">

#### With gecko update
<img width="686" alt="Screenshot 2022-05-27 at 14 24 34" src="https://user-images.githubusercontent.com/11731652/170690578-62afdeee-79e9-4eb5-9254-0273d59c9426.png">

**Comment by ionutbedregeanu** [comment]
@jonalmeida I don't have the setup for going lower in geckoview and trying to find there the regression. Should I open a ticket on Bugzilla?

**Comment by mcomella** [comment]
If you wanted to continue debugging, you can take a profile before the change and after the change and compare to see what's different. Since the Firefox Profiler doesn't start profiling that early during start up, you may want to [capture the profile using the Debug API.](https://wiki.mozilla.org/Performance/Fenix/Debug_API#Usage_for_start_up) Since the change is small, however, it might be hard to spot. fwiw, if you share the profiles or identify the cause, that could make the bug more actionable for the folks working on geckoview when you file that Bugzilla ticket.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802645

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
