### ISSUE TITLE
Intermittent UI test failure - < EnhancedTrackingProtectionSettingsTest.removeAllExceptionURLTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6679]
### Notes
❗ Not sure what is causing this crash
The last performed action was `openSettings`

Similar with https://github.com/mozilla-mobile/focus-android/issues/6439 https://github.com/mozilla-mobile/focus-android/issues/6437 https://github.com/mozilla-mobile/focus-android/issues/6436 https://github.com/mozilla-mobile/focus-android/issues/6523 https://github.com/mozilla-mobile/focus-android/issues/6538 https://github.com/mozilla-mobile/focus-android/issues/6600 https://github.com/mozilla-mobile/focus-android/issues/6601 https://github.com/mozilla-mobile/focus-android/issues/6602 #6603 and #6661

[Logcat](https://00f74ba44bfec3da7b6298338ff9fc354f7b6098ef-apidata.googleusercontent.com/download/storage/v1/b/focus_android_test_artifacts/o/2022-03-15_17-02-36.423850_YhnE%2Fmatrix_0%2FPixel3-30-en-portrait-shard_72%2Flogcat?jk=AFshE3VuUBUzyannUo_IycDCEmtjLYaFNXo0s24CQlbe43IqpzzfefbNOgbRAvjKMU5u9FrmsHDkAVJKrcH76Ii5J7ict7Y2TmdsNuepZVAQKC7udDynzVY5iiaHPbtdF2uY5qJeCBWS7chXUX1BJQQCAxN3gNRLEoUxShmDUygRpweNX95t2FOlg0poRfBJ4bJKFLl9YMtoNAL13kjqdHNjfu5SEv_XI1WN4vt298BIOGKSCCf6025haJ0mJn5HQriHOrhm2LKjC9jM9ghPP_12s0KNBw1DSAleksYId8h8q7DZwDxR8T5xoB4-lQCu788Vp-ZYQAevRY_b8lMcmisS6YD9fgiT5jhaf35QFB1WEN7wEuuL1YYCHrfY9hk3HXES1EMISsjeqjTAeimh6gpfu3q2GRtk47dCa87pPM09d11x1O6pnQH5fhsTCp-eXcFqOstwxv45s3RdqnJmyVsRsxzfOw3htL2646HDWoubi2isL7BhzjA7389Z1FQRGGRGgVQYqBXGcQSk5JP3rUyGb-3zA68ezsOAoOkpSo-ZtyqTmHKkYpZKHWrN5CKS0HnRsHnz3HBe0wUZIjmdN2PitWd9cjVD_iQ1IyIJe2Hs8B1X4tSyR7huPIyTbf_sbYV3LGhsPP5BTIDqwOH-idOyhZdcfd0VNLQ6K0UqQmgm1SVd2B40CrIi7N8b0GMwIJ4Y-Nf-DaMmauGnkOn4bqUZV45p4MXebTiqL3_LvgpLTiqYt9_OzZYWXSHPVGh9GlfxwmvJSlfQOHixN3DxSWpHMIvRr8H40wv99nDlV3R-dfCcrRIG0NsAmxk0yz9rsjcs336wSWZeMxJ9Yi7aDFoih4_MpC9Mx713ujBKGZ1_xs7ZyE7m1xCVDvDwTMkJ0aaqWFH2ZMx8_aBBoA9GUo6V_0e4QkILgM-cYhTWQitiCBIc4nlbfUtgQLL4vI8Ff6BnltJmY_Hp2IEYpMIdEEnWThYgsZpuqKxUG7tMO9D3bOrkmRKH-GM_PMg6WzcNuf-U9IWjfbjAMECmV7iXl8oRpNg2GckKQ1zRx5ALpukiRFthe3ipd7OWTA&isca=1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8182925938649682224/executions/bs.df093eeca127c549/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7805666101114109673/executions/bs.df515c48f3568900/testcases/1)

**Comment by sv-ohorvath** [comment]
Crashed 1/2 tries on debug 3/25 :
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6228986710578014704/executions/bs.f9213fffedf0d02c

**Comment by sv-ohorvath** [comment]
Possibly same ANR as https://github.com/mozilla-mobile/fenix/issues/24047

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
