### ISSUE TITLE
Do not report Nimbus network errors to Sentry

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/focus-android#6684]
Just noticed https://sentry.io/organizations/mozilla/issues/3085342297/. 

These errors are not actionable. There will always be clients with connection issues. In Fenix, we decided to filter out `RequestException` and `ResponseException`: https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt#L112

We should do the same for Focus.

**Comment by jonalmeida** [comment]
Duplicate of https://github.com/mozilla-mobile/focus-android/issues/6646
