### ISSUE TITLE
[META] Dark theme does not apply to background at reddit.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#6686]
## Preconditions
Dark theme enabled from the browser's settings.
## Steps to reproduce
1. Navigate to: https://www.reddit.com/r/HFY/comments/t98ze8/first_contact_chapter_chptr_relog_73x/.
2. Observe the background.
### Expected behavior
The background follows the dark theme of the browser.
### Actual behavior
The background follows the light theme.
### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
* Focus version: Firefox Focus Nightly 100.0a1 (360760511-🦎100.0a1-20220316095231🦎)

**Notes:**
1. Reproducible regardless of the status of ETP.
2. Not reproducible using the latest build of Firefox Nightly in Normal Browsing Mode and in Private Browsing Mode.
3. Reproducible on both Release and Nightly Version of Firefox Focus.
4. Reproducible on other pages( youtube.com)
5. Screenshot attached:

Firefox Focus Nightly:
![Screenshot_2](https://user-images.githubusercontent.com/75027050/158766687-5440b089-e35d-42c0-bab1-47b9e914d160.png)

Firefox Fenix Nightly:
![Screenshot_5](https://user-images.githubusercontent.com/75027050/158766907-e39a851d-4dc3-4b00-ba5e-f3812b042912.png)

**Comment by delia-pop** [comment]
Verified as fixed on the latest Focus Nightly 105.0a1 from 08/22 with Xiaomi 12 Pro (Android 12).

<img src="https://user-images.githubusercontent.com/89388888/185955038-41545f4a-4662-4d99-9aaf-d553918468d2.JPEG" width="30%" />
