### ISSUE TITLE
Number of blocked trackers should be "-" if content blocking is disabled

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#669]

**Comment by pocmo** [comment]
![counter-disabled](https://cloud.githubusercontent.com/assets/89638/26549852/4fa306f4-447b-11e7-8cc9-a6bdee3561d0.png)

@antlam ?

**Comment by antlam** [comment]
I think this is better than 0. Because it clarifies a stronger "off" status. 

Thoughts @brampitoyo ?

**Comment by brampitoyo** [comment]
I agree.

Say “Not blocking”, “Inactive” or “—” when TP is off. This is the equivalent of a `null` state.

Say “0” when TP is on, but cannot detect any element to block on the page.
