### ISSUE TITLE
[RTL] The dots are wrongly written on the new onboarding

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6695]
## Steps to reproduce
1. Set the device to an RTL language.
2. Install the latest Focus Nightly 100.0a1, or make sure it has a clean profile.
3. Observe the dots from each sentence.

### Expected behavior
The dots are at the end of each sentence.

### Actual behavior
The dots are wrongly displayed in the middle of the sentence - please observe the screenshots below.

### Device information
* Android device: all
* Focus version: Focus Nightly 100.0a1 from 3/18
![Untitled1](https://user-images.githubusercontent.com/40694158/158961726-9e880fc8-3845-433a-88fd-ec54d04a11d0.png)

**Comment by mcarare** [comment]
I am not sure this is a real problem when using a real RTL language, including translation. It just seems weird because you keep reading it in English and LTR.
