### ISSUE TITLE
Secure connection failed when accessing aide.laposte.fr

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#6710]
## Steps to reproduce
1. Navigate to: https://aide.laposte.fr/contenu/validite-des-timbres-apres-un-changement-de-tarif.
2. Observe the result.

### Expected behavior
The page loads as expected.

### Actual behavior
A "Secure connection failed" message is displayed.
### Device information
* Operating System: Android 11
* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
* Focus version:  Firefox Focus Nightly 100.0a1 (360770507-🦎100.0a1-20220317092857🦎)

**Notes:**
1. Reproducible regardless of the status of ETP.
2. Not reproducible using the latest build of Firefox Nightly in Normal Browsing Mode and in Private Browsing Mode.
3. Reproducible on both Release and Nightly Version of Firefox Focus.
4. Screenshot attached:
![Screenshot_47](https://user-images.githubusercontent.com/75027050/159233984-e84a6939-72f7-42c5-b4dd-854597b233e7.png)

**Comment by Mugurell** [comment]
I see this reproducing on Fenix and GVE also, but interestingly not on desktop.

| Fenix 98 release | latest GVE - 100 |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11428869/159457039-028c8bda-06b3-413c-9c27-f913f4f7de4b.png" height="678" /> | <video src="https://user-images.githubusercontent.com/11428869/159457197-6b999054-5835-4ddb-804f-0a5ff0c7b375.mp4" height="400" /> |



&nbsp;

Moving the ticket to Bugzilla for more investigations.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1760770

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
