### ISSUE TITLE
Custom tab navigation actions should be updated

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6718]
## Steps to reproduce
1. Make Firefox Focus your default browser.
2. Open a link in custom tab.
3. Observe the toolbar.
### Expected behavior
Back and forward buttons shouldn't be visible
Embedded back button should remains visible but should have the color set according to the theme
### Actual behavior
Back and forward buttons are visible
Toolbar embedded back button is white in light theme
### Device information

* Android device: Nexus 10 Android 11
* Focus version: 100 Nightly

**Comment by ionutbedregeanu** [comment]
@jeffreygee I noticed that in custom tab we are having two back buttons in the toolbar, which is a bit misleading
The left one is used to go back between Focus pages and the other one is to exit from the custom tab
Should we let it as it is or should we remove back, forward buttons and let only that one which is located near to the shield icon, as in Fenix?
These Focus navigation buttons are also present in the browser menu
<img src="https://user-images.githubusercontent.com/11731652/159696010-5eea9859-301e-4e5d-a8c7-1ea5ace289e4.png" width="70%" />

**Comment by jeffreygee** [comment]
![nav](https://user-images.githubusercontent.com/93741573/161093086-5f04e4d2-028e-4987-92d2-2e891671acc9.jpg)

@ionutbedregeanu - let's remove the one next to the shield so that only the back/forward arrows exist as seen above. Let me know if you have any questions!

**Comment by ionutbedregeanu** [comment]
@jeffreygee That back button which is next to the shield is set dynamically from AC and it has the role of a close button(close the custom tab) and in my opinion it shouldn't be removed
I suggested to remove "<- ->" because:
- are also present in the browser menu
- are also removed in Fenix and maybe we want to have a consistency between those browsers

Another option which can be considered is to change the icon of close button, maybe from back arrow icon to close icon
What do you think?

#### Focus
<img src="https://user-images.githubusercontent.com/11731652/161221002-49afe539-a948-44c4-a228-fa897a63a088.png" width="70%"/>

#### Fenix
<img src="https://user-images.githubusercontent.com/11731652/161220995-6a111e1a-ed4d-4628-8d99-ce91e591ba57.png" width="70%"/>

**Comment by jeffreygee** [comment]
@ionutbedregeanu - ah sorry, I misunderstood. I'm good with your suggestion and removing the <---> and following Fenix's

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 101.0a1 (build 360970511 with GV 101.0a1-20220405094056) with Lenovo tablet M10 (Android 10):

![custom tab](https://user-images.githubusercontent.com/40694158/162141977-5adfa8a0-e1e0-4e6d-a863-8cb6ddc0a71f.png)
