### ISSUE TITLE
Intermittent UI test failure - < EnhancedTrackingProtectionSettingsTest. removeOneExceptionURLTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6735]
### Notes
❗ Not sure what is causing this crash
The last performed action was ` verifyPageContent("Tracker Blocking")`

Similar with https://github.com/mozilla-mobile/focus-android/issues/6439 https://github.com/mozilla-mobile/focus-android/issues/6437 https://github.com/mozilla-mobile/focus-android/issues/6436 https://github.com/mozilla-mobile/focus-android/issues/6523 https://github.com/mozilla-mobile/focus-android/issues/6538 https://github.com/mozilla-mobile/focus-android/issues/6600 https://github.com/mozilla-mobile/focus-android/issues/6601 https://github.com/mozilla-mobile/focus-android/issues/6602 #6603 #6661 and #6679

### Build: 3/22

[Logcat](https://github.com/mozilla-mobile/focus-android/files/8333276/removeOneExceptionURLTest.txt)

**Comment by sv-ohorvath** [comment]
A11y issue backed out from AC. Can reopen if it fails again
