### ISSUE TITLE
Intermittent UI test failure - < WebControlsTest. emailLinkTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6743]
### Notes
❗ Not sure what is causing this crash UI test seems that ran to completion

Similar with https://github.com/mozilla-mobile/focus-android/issues/6439 https://github.com/mozilla-mobile/focus-android/issues/6437 https://github.com/mozilla-mobile/focus-android/issues/6436 https://github.com/mozilla-mobile/focus-android/issues/6523 https://github.com/mozilla-mobile/focus-android/issues/6538 https://github.com/mozilla-mobile/focus-android/issues/6600 https://github.com/mozilla-mobile/focus-android/issues/6601 https://github.com/mozilla-mobile/focus-android/issues/6602 #6603 #6661 and #6679

### Build: 3/23 Main 

[Logcat](https://00f74ba44b25a86291deb7aa4745679954db8fda5f-apidata.googleusercontent.com/download/storage/v1/b/focus_android_test_artifacts/o/2022-03-23_15-19-03.537859_nUYb%2Fmatrix_0%2FPixel3-30-en-portrait-shard_8%2Flogcat?jk=AFshE3VqVFmL5Hnqav__LKlJrqdDUtGBA-LAmlIwYwXjMfTeYdqkM96R_TuHzrCWurFrr_W1p3v57pKb1cTUPj8XNZ5zAhJOFNGAnLr28mqTW9qHFI-8YRlcpcXupK6BdVLozcbYKQ3wSUizShiIpMNCORfzSRxcUCW8qSvbPDY4uNQAEUg-yZ45ZtoeWmIJhQc8hHVX1enzRuKO6DP6jf3oyEBeKGn3gr-VPi0OznM8fIJQAtrmJfLEY8NtMKc1YlhhM_kX10b6yWC3EW6fNDYrgtnYHE9bbQrzuI5BSTVF0i9B-82-jkQPfuEuJbruuISjSVv65SE6ig9ZctuP2phTG4skbHiiqEWYbfzhTvKk5Ea_WY9myndWcB5JMxukQi46vV2avOOIu2iqxK-p_cmfBLS6EvaUu88b8rgAXlrhrmH34AcJ0kR5Kdlywjt4zwV9w_yppLo0FlhzRsXMkInvuTC5gFyKJPQUNernFQ2PVimgrcqzyzzZ76MkBpV2hbFbGi3P5MIH5J4C3HTvpJayQ0YKIv0gLLqok-qZMnOcbXC7ZwMFz79RQrfo6mU4qroRv82J0nyfcrSYcmekv9G35ACrHtRWnbeY46xD3VTVK_-Pecr_uOmLknUlqcq0dopu41M59G4VduD89f8ux6q0hX079wRdC7lmAWdbTz13G2runS6XuiouJ7hQyw9Yh5m928Y1g319xoqshjoZBgCYSE4ijd_NznaMmhialSpfne_sNpmkeScwxd2HTJokQZ-LCk50ex6FrxQmlXYK4ifHj3fwtQVySE2nf5a_UjIyKXY-Gv1QIkdRvbv1qNejxUzvu2o3_EX3uzqRowH6iT7h4xegPFu9rl7fJvOjLzfgQModg_Awuajt0JX0aL_QIaVS3bwPdqHFDbR2CUqw-HeuvOST93oj6W28-G8UGoJ_WeOHXWnHPuNJBS9QjjVtCA7SGOntlripULkWVaKbDcMa8Hcdv_j7cfbV1w7AQVnGRftj2yqjL_o11C1ZDoRCNp2FsKoUxV0OpcN7HknSDkDas4RMMScEGf6QdUbZcVPDO3EYQoSJFa0Oj7uL-f851GdaOIZO_4eCo5r-76-fsY-2BPkPYNI6BhdWzH8z04Ani-q7pZJl0sGOish2KXIb7pJI&isca=1)

**Comment by sv-ohorvath** [comment]
Similar ANRs on Fenix, see https://github.com/mozilla-mobile/fenix/issues/24047

**Comment by AndiAJ** [comment]
Flaky 1x on 3/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8539602442037172345/executions/bs.ffbaf22a2b35ad33/testcases/1)

**Comment by sv-ohorvath** [comment]
Flaky on 3/29 Main: https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7521731236104233620/executions/bs.ed51414511ec4b0a

**Comment by AndiAJ** [comment]
Flaky on 3/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5653748005058624493/executions/bs.13cd92b57648f6f6/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5069556148344924969/executions/bs.3f1c6abd29d98b1/testcases/1)

**Comment by sv-ohorvath** [comment]
Flaky on 14/14: [link](https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6965280057133160039/executions/bs.e78c91bcc40b3ad4/testcases/1/logs)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8591079614157632064/executions/bs.ecbf086f895bafa5)

05-02 04:05:36.784: I/WindowManager(479): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 1b676ff org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=false)
05-02 04:05:36.852: E/MmTelFeatureConnection [0](1779): ImsRegistrationCallbackAdapter: ImsRegistration is null
05-02 04:05:36.978: I/ActivityManager(479): Force stopping org.mozilla.focus.debug appid=10151 user=0: finished inst
05-02 04:05:36.978: I/ActivityManager(479): Killing 14123:org.mozilla.focus.debug/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-02 04:05:36.980: W/ActivityTaskManager(479): Force removing ActivityRecord{2331abd u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
05-02 04:05:36.984: I/ServiceChildProcess(14657): Destroying GeckoServiceChildProcess
05-02 04:05:36.991: W/Binder(14029): Caught a RuntimeException from the binder stub implementation.
05-02 04:05:36.991: W/Binder(14029): java.lang.SecurityException: Calling from not trusted UID!
05-02 04:05:36.991: W/Binder(14029): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
05-02 04:05:36.991: W/Binder(14029): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
05-02 04:05:36.991: W/Binder(14029): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
05-02 04:05:36.991: W/Binder(14029): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-02 04:05:36.991: W/Binder(14029): 	at android.os.Binder.execTransact(Binder.java:1123)
05-02 04:05:36.994: I/cus.debug:tab2(14657): System.exit called, status: 0
05-02 04:05:36.994: I/AndroidRuntime(14657): VM exiting with result code 0, cleanup skipped.
05-02 04:05:36.997: I/ServiceChildProcess(14778): Destroying GeckoServiceChildProcess
05-02 04:05:37.015: I/ActivityManager(479): Killing 14657:org.mozilla.focus.debug:tab27/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-02 04:05:37.015: I/ActivityManager(479): Killing 14778:org.mozilla.focus.debug:gpu/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-02 04:05:37.016: D/WindowManager(479): notifyANR took 236ms

Looks like #24047

**Comment by AndiAJ** [comment]
Flaky 1x on 5/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6569641563593289795/executions/bs.dbca986344b10073/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6656350735003907423/executions/bs.5513ab943dc23d6f)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7009969343288319373/executions/bs.de2a2953cc02c515/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9162777830940611482/executions/bs.32fa97a4647ccc8e/test-cases)

06-02 10:29:09.566: I/WindowManager(481): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: c11bdb8 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5001ms for FocusEvent(hasFocus=false)
06-02 10:29:09.626: I/perfetto(385): probes_producer.cc:329  Producer stop (id=6)
06-02 10:29:09.638: I/perfetto(386): ng_service_impl.cc:1948 Tracing session 6 ended, total sessions:0
06-02 10:29:09.675: I/perfetto(385): ftrace_procfs.cc:183    disabled ftrace
06-02 10:29:09.672: W/perfetto(0): disabled ftrace
06-02 10:29:09.700: I/ActivityManager(481): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-02 10:29:09.700: I/ActivityManager(481): Killing 14683:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-02 10:29:09.702: W/ActivityTaskManager(481): Force removing ActivityRecord{17d107b u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-02 10:29:09.703: W/Binder(14656): Caught a RuntimeException from the binder stub implementation.
06-02 10:29:09.703: W/Binder(14656): java.lang.SecurityException: Calling from not trusted UID!
06-02 10:29:09.703: W/Binder(14656): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-02 10:29:09.703: W/Binder(14656): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-02 10:29:09.703: W/Binder(14656): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-02 10:29:09.703: W/Binder(14656): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-02 10:29:09.703: W/Binder(14656): 	at android.os.Binder.execTransact(Binder.java:1123)
06-02 10:29:09.705: I/ServiceChildProcess(15393): Destroying GeckoServiceChildProcess
06-02 10:29:09.706: I/ServiceChildProcess(15278): Destroying GeckoServiceChildProcess
06-02 10:29:09.715: I/ActivityManager(481): Killing 15278:org.mozilla.focus.debug:tab31/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-02 10:29:09.716: I/ActivityManager(481): Killing 15393:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-02 10:29:09.717: D/WindowManager(481): notifyANR took 156ms

Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6739652407665704267/executions/bs.b536d831069ff916/test-cases)

06-29 01:04:22.864: I/WindowManager(465): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 4ae9df3 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5001ms for FocusEvent(hasFocus=false)
06-29 01:04:23.009: E/MmTelFeatureConnection [0](1781): ImsRegistrationCallbackAdapter: ImsRegistration is null
06-29 01:04:23.230: W/system_server(465): Long monitor contention with owner InputDispatcher (1496) at void com.android.server.wm.ActivityTaskManagerService$LocalService.saveANRState(java.lang.String)(ActivityTaskManagerService.java:6971) waiters=0 in boolean com.android.server.wm.WindowProcessController.hasActivities() for 163ms
06-29 01:04:23.231: W/system_server(465): Long monitor contention with owner Binder:465_14 (2739) at int com.android.server.am.ActivityManagerService.bindIsolatedService(android.app.IApplicationThread, android.os.IBinder, android.content.Intent, java.lang.String, android.app.IServiceConnection, int, java.lang.String, java.lang.String, int)(ActivityManagerService.java:15184) waiters=0 in int com.android.server.am.ActivityManagerService.bindIsolatedService(android.app.IApplicationThread, android.os.IBinder, android.content.Intent, java.lang.String, android.app.IServiceConnection, int, java.lang.String, java.lang.String, int) for 150ms
06-29 01:04:23.282: I/ActivityManager(465): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-29 01:04:23.282: I/ActivityManager(465): Killing 14061:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 01:04:23.286: W/ActivityTaskManager(465): Force removing ActivityRecord{5cd889 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-29 01:04:23.296: W/Binder(13963): Caught a RuntimeException from the binder stub implementation.
06-29 01:04:23.296: W/Binder(13963): java.lang.SecurityException: Calling from not trusted UID!
06-29 01:04:23.296: W/Binder(13963): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-29 01:04:23.296: W/Binder(13963): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-29 01:04:23.296: W/Binder(13963): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-29 01:04:23.296: W/Binder(13963): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-29 01:04:23.296: W/Binder(13963): 	at android.os.Binder.execTransact(Binder.java:1123)
06-29 01:04:23.319: I/ServiceChildProcess(14628): Destroying GeckoServiceChildProcess
06-29 01:04:23.320: D/AndroidRuntime(13963): Shutting down VM
06-29 01:04:23.333: I/ActivityManager(465): Killing 14628:org.mozilla.focus.debug:tab21/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 01:04:23.334: I/ActivityManager(465): Killing 14778:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 01:04:23.335: D/WindowManager(465): notifyANR took 483ms

**Comment by AndiAJ** [comment]
Flaky 1x on 6/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5476546022835625057/executions/bs.3cd398c1c93bf992/test-cases)

06-29 14:55:15.162: I/WindowManager(482): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 45ab6d4 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5001ms for FocusEvent(hasFocus=false)
06-29 14:55:15.183: E/Gmail(13600): ComposeActivity:Failed to update the menu for wallet attachment.
06-29 14:55:15.183: E/Gmail(13600): dom: Failed to get universalDraft because the account is not initialized yet.
06-29 14:55:15.183: E/Gmail(13600): 	at dob.d(PG:6)
06-29 14:55:15.183: E/Gmail(13600): 	at dob.onPrepareOptionsMenu(PG:3)
06-29 14:55:15.183: E/Gmail(13600): 	at com.google.android.gm.ComposeActivityGmail.onPrepareOptionsMenu(PG:4)
06-29 14:55:15.183: E/Gmail(13600): 	at android.app.Activity.onPreparePanel(Activity.java:4224)
06-29 14:55:15.183: E/Gmail(13600): 	at fs.onPreparePanel(PG:2)
06-29 14:55:15.183: E/Gmail(13600): 	at ur.onPreparePanel(Unknown Source:2)
06-29 14:55:15.183: E/Gmail(13600): 	at sg.onPreparePanel(PG:2)
06-29 14:55:15.183: E/Gmail(13600): 	at ur.onPreparePanel(Unknown Source:2)
06-29 14:55:15.183: E/Gmail(13600): 	at ta.onPreparePanel(PG:1)
06-29 14:55:15.183: E/Gmail(13600): 	at sw.run(PG:4)
06-29 14:55:15.183: E/Gmail(13600): 	at android.os.Handler.handleCallback(Handler.java:938)
06-29 14:55:15.183: E/Gmail(13600): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-29 14:55:15.183: E/Gmail(13600): 	at android.os.Looper.loop(Looper.java:223)
06-29 14:55:15.183: E/Gmail(13600): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
06-29 14:55:15.183: E/Gmail(13600): 	at java.lang.reflect.Method.invoke(Native Method)
06-29 14:55:15.183: E/Gmail(13600): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-29 14:55:15.183: E/Gmail(13600): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-29 14:55:15.212: I/PeopleChimeraService(11099): onService. callbacks = agqu@205d8e0, request = com.google.android.gms.common.internal.GetServiceRequest@1d1c799
06-29 14:55:15.311: W/system_server(482): Long monitor contention with owner InputDispatcher (1489) at android.content.res.Configuration com.android.server.wm.ActivityTaskManagerService.getGlobalConfigurationForPid(int)(ActivityTaskManagerService.java:976) waiters=0 in void com.android.server.wm.WindowAnimator.lambda$new$1$WindowAnimator(long) for 142ms
06-29 14:55:15.354: I/ActivityManager(482): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-29 14:55:15.354: I/ActivityManager(482): Killing 15371:org.mozilla.focus.debug:tab5/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 14:55:15.356: I/ActivityManager(482): Killing 14807:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 14:55:15.362: W/ActivityTaskManager(482): Force removing ActivityRecord{dd6b426 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-29 14:55:15.364: W/Binder(14729): Caught a RuntimeException from the binder stub implementation.
06-29 14:55:15.364: W/Binder(14729): java.lang.SecurityException: Calling from not trusted UID!
06-29 14:55:15.364: W/Binder(14729): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-29 14:55:15.364: W/Binder(14729): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-29 14:55:15.364: W/Binder(14729): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-29 14:55:15.364: W/Binder(14729): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-29 14:55:15.364: W/Binder(14729): 	at android.os.Binder.execTransact(Binder.java:1123)
06-29 14:55:15.380: I/ActivityManager(482): Killing 15456:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 14:55:15.382: D/WindowManager(482): notifyANR took 266ms

**Comment by AndiAJ** [comment]
Flaky 1x on 7/6 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6739335882513839856/executions/bs.cafe6d785bc32b15)

07-05 23:13:03.396: I/WindowManager(478): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: a763407 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false)
07-05 23:13:03.533: I/ActivityManager(478): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
07-05 23:13:03.533: I/ActivityManager(478): Killing 15209:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-05 23:13:03.535: W/ActivityTaskManager(478): Force removing ActivityRecord{47367c8 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
07-05 23:13:03.537: W/Binder(15151): Caught a RuntimeException from the binder stub implementation.
07-05 23:13:03.537: W/Binder(15151): java.lang.SecurityException: Calling from not trusted UID!
07-05 23:13:03.537: W/Binder(15151): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
07-05 23:13:03.537: W/Binder(15151): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
07-05 23:13:03.537: W/Binder(15151): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
07-05 23:13:03.537: W/Binder(15151): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
07-05 23:13:03.537: W/Binder(15151): 	at android.os.Binder.execTransact(Binder.java:1123)
07-05 23:13:03.542: I/ServiceChildProcess(15910): Destroying GeckoServiceChildProcess
07-05 23:13:03.553: I/ServiceChildProcess(15773): Destroying GeckoServiceChildProcess
07-05 23:13:03.567: I/ActivityManager(478): Killing 15773:org.mozilla.focus.debug:tab25/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-05 23:13:03.580: I/ActivityManager(478): Killing 15910:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-05 23:13:03.581: D/WindowManager(478): notifyANR took 197ms

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
