### ISSUE TITLE
Intermittent UI test failure - < EnhancedTrackingProtectionSettingsTest. allowAnalyticsTrackersTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6745]
### Notes
❗ Not sure what is causing this crash UI test seems that ran to completion

Similar with https://github.com/mozilla-mobile/focus-android/issues/6439 https://github.com/mozilla-mobile/focus-android/issues/6437 https://github.com/mozilla-mobile/focus-android/issues/6436 https://github.com/mozilla-mobile/focus-android/issues/6523 https://github.com/mozilla-mobile/focus-android/issues/6538 https://github.com/mozilla-mobile/focus-android/issues/6600 https://github.com/mozilla-mobile/focus-android/issues/6601 https://github.com/mozilla-mobile/focus-android/issues/6602 #6603 #6661 #6679 and #6743

### Build: 3/23 Main 
[Logcat](https://github.com/mozilla-mobile/focus-android/files/8338795/allowAnalyticsTrackersTest.txt)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8639610908106265458/executions/bs.dc97c2f3cb87e2f2/testcases/1)

**Comment by sv-ohorvath** [comment]
Similar ANRs on Fenix, see https://github.com/mozilla-mobile/fenix/issues/24047

**Comment by AndiAJ** [comment]
Closing, as it didn't occur for more than a month.
