### ISSUE TITLE
PWAs are not added to home screen on Android 5 tablet

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6753]
## Steps to reproduce
1. Open a webpage in Focus/Open a custom tab while having Focus set as default browser.
2. Tap on the 3-dot menu and select "Add to Home screen".
3. Tap "Yes" on the the "Add to Home screen" dialog.
4. Go to home screen and observe if the shortcut was added.
### Expected behavior
The webpage shortcut is added to the home screen.
### Actual behavior
The webpage shortcut is not added to the home screen.
### Device information

* Android device: Huawei MediaPad M2 (Android 5.1.1).
* Focus version: Latest Nightly from 03/25, RC 98.3.0, Beta 99.0.0-beta.5.

https://user-images.githubusercontent.com/89388888/160132550-ea64818b-53c5-4649-b8cc-684b3336b39b.mp4

**Comment by delia-pop** [comment]
This is still reproducible on the latest Focus Nightly 104 from 07/25 with Huawei MediaPad M2 (Android 5.1.1). 
Note that PWAs are correctly added to homepage from Fenix.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802643

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
