### ISSUE TITLE
Improper flicker displayed when tapping the PiP floating window

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6756]
## Steps to reproduce
1. Open a video from YouTube in Fullscreen.
2. Tap the home button to enter the PiP mode.
3. Tap on the floating window.
4. Observe the floating window.
### Expected behavior
The transition is done smoothly, with no glitches. 
### Actual behavior
An improper flicker displayed when tapping the PiP floating window.
### Device information

* Android device: Samsung Galaxy Note10 (Android 11), Motorola Moto G30 (Android 11).
* Focus version: Latest Nightly from 03/25, Beta 99.0.0-beta.5.

https://user-images.githubusercontent.com/89388888/160137397-782643da-dae9-45f8-bca4-8b9bc437e1d5.mp4

**Comment by Mugurell** [comment]
Saw this issue on a Oneplus 7 with Android 11 with multiple apps supporting pip: Fenix also, Opera, Chrome, Google Maps, Youtube (here just the controls were flickering).
Might just be a platform issue but at a quick search I didn't find a mention of a issuetracker ticket.

**Comment by ionutbedregeanu** [comment]
Since this bug seems to be a platform issue I will close it
