### ISSUE TITLE
Different theme for system insets when coming back to the app

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6762]
Pre-requisites:
- have the system theme set to light
- have the app follow device theme / be in light theme

STRs:
- put the app in background and come back to it
(also reproduceable if going to set the app as the default browser on Android <12)

Expected result:
- Status bar icons have a good contrast
- There is no visible change between how the status bar looked before leaving the app and returning to the app

Actual result:
- Upon returning to the app the status bar icons are white and hard to distinguish especially in the settings screen.

Notes:
- Issue seems device dependent.
Can reproduce on a OnePlus7 with Android 11 but cannot reproduce on a Pixel 3 with Android 12.
- Before leaving the app the navigation bar button seem harder to distinguish but they are shown much clearer when coming back to the app. Seems like the reverse of what's happening with the status bar.

https://user-images.githubusercontent.com/11428869/160343518-51d96f2c-95ab-4e9f-91c8-81c32f67623a.mp4

**Comment by ionutbedregeanu** [comment]
Didn't succeed to reproduce it on:
Nexus 6 Android 7
Nexus 6 Android 11
Pixel 3a Android 11

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 101.0a1 (build 360970511 with GV 101.0a1-20220405094056) with:
* Lenovo Tablet M10 (Android 10), 
* Samsung Galaxy Note 8 (Android 9), 
* Oppo Find X3 Lite (Android 11), 
* Google Pixel (Android 10),and
* HTC 10 (Android 8).
