### ISSUE TITLE
Intermittent UI test failure - < ErrorPagesTest. badURLCheckTest >

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#6769]
### Firebase Test Run:
Failed 1/2 tries:
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8539602442037172345/executions/bs.acd8398c6cf9dade
### Stacktrace:
ANR [reported here](https://github.com/mozilla-mobile/fenix/issues/24047)
`Failure reporting to instrumentation watcher: comp=ComponentInfo{org.mozilla.focus.debug.test/androidx.test.runner.AndroidJUnitRunner} results=Bundle[{shortMsg=keyDispatchingTimedOut, longMsg=Input dispatching timed out (1ac1c46 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=false))}]`
### Build:
main 3/28

**Comment by AndiAJ** [comment]
Closing, as it didn't occur for more than a month.
