### ISSUE TITLE
Going to system default sets the locale to English in non-English Locale.

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#677]
As mentioned in https://github.com/mozilla-mobile/focus-android/issues/654#issuecomment-304140105, setting the locale to default causes the app to show texts in English.

STR:
Change the system locale to French, start Focus
Go to Settings, change locale to English
Check the locale is changed to English, go to Language option again

1. 'System default' is shown in English.
2. Selecting it sets locale in English, although the system locale is unchanged in French.

**Comment by pocmo** [comment]
Locale.getDefault() seems to return "und" (empty language / empty country) when switching back to the system default.

Looking at LocaleList (API 24+) I see the following order of locales on my device:
* und
* de-DE
* en-US

I'll test some other devices to see whether this only affects multi-locale devices or whether this breaks on single-locale devices too. For multi-locale devices we could skip "und" and use the next available locale. However if all devices are affected then we could determine the system default on app start and keep a reference to it.

**Comment by pocmo** [comment]
The same happens on an Android 5.1.1 device. I assume keeping a reference to the default is the best we can do.
