### ISSUE TITLE
Wrong text alignment in the onboarding screen

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6781]
## Steps to reproduce
1.Install a fresh build of Focus on a tablet
2.Notice onboarding text alignment
### Expected behavior
At this moment we don't have design for tablet onboarding screen, so I will start a discussion on this ticket about this https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding-2022?node-id=2647%3A11565
### Actual behavior
<img src="https://user-images.githubusercontent.com/11731652/160824280-7228099f-73c8-4a09-9f5e-1e73f875912a.png" width="50%"/>

### Device information

* Android device: Nexus 10 Api R
* Focus version: Focus Nightly 100.0

**Comment by ionutbedregeanu** [comment]
@jeffreygee At this moment we don't have design for tablet onboarding screen. Can you help with this?

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 101.0a1 (build 360970511 with GV 101.0a1-20220405094056) with LEnovo Tablet M10 (Android 10), Samsung Galaxy Note 8 (Android 9), and Samsung Galaxy Tablet A6 (Android 5.1.1).

![onboarding landscape](https://user-images.githubusercontent.com/40694158/162136947-97c7ff4d-e2e6-403c-994a-51c94c093978.png)
![onboarding portrait](https://user-images.githubusercontent.com/40694158/162136965-caa80a2e-f03a-41ab-b910-9213360f1de1.png)
