### ISSUE TITLE
Implement dark theme for the new onboarding screen

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6787]
### Why/User Benefit/User Problem
We should see a specific design for the new onboarding in dark theme
### What / Requirements
Implement dark theme for the new onboarding screen
### Acceptance Criteria (how do I know when I’m done?)
The new onboarding screen it should look like [this](https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding-2022?node-id=2647%3A11565) in dark mode

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 100.0a1 (build 360910510 with GV 100.0a1-20220331093541) with the following devices:
* Oppo Find X3 Lite (Android 11),
* Lenovo Tab M10 (Android 10), and
* Google Pixel (Android 10).

![Screenshot_2022-04-01-12-19-17-23_11753d9bf2a67eec1c984b8ccb4d0671](https://user-images.githubusercontent.com/40694158/161248785-59b858e9-4bf1-416c-9bc3-e64a8a8aa4ed.jpg)
