### ISSUE TITLE
Leak when navigating to settings and returning back to homescreen

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6790]
STRs:
- open Focus
- tap the 3dot menu and to settings
- press back to return to the homescreen

Result:
> ┬───
│ GC Root: Global variable in native code
│
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (InternalLeakCanary↓ is not leaking and A ClassLoader is never
│    leaking)
│    ↓ ClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (InternalLeakCanary↓ is not leaking)
│    ↓ Object[697]
├─ leakcanary.internal.InternalLeakCanary class
│    Leaking: NO (MainActivity↓ is not leaking and a class is never leaking)
│    ↓ static InternalLeakCanary.resumedActivity
├─ org.mozilla.focus.activity.MainActivity instance
│    Leaking: NO (Activity#mDestroyed is false)
│    mApplication instance of org.mozilla.focus.DebugFocusApplication
│    mBase instance of androidx.appcompat.view.ContextThemeWrapper
│    ↓ AppCompatActivity.mDelegate
│                        ~~~~~~~~~
├─ androidx.appcompat.app.AppCompatDelegateImpl instance
│    Leaking: UNKNOWN
│    Retaining 809 B in 10 objects
│    mAppCompatCallback instance of org.mozilla.focus.activity.MainActivity
│    with mDestroyed = false
│    mContext instance of org.mozilla.focus.activity.MainActivity with
│    mDestroyed = false
│    mHost instance of org.mozilla.focus.activity.MainActivity with mDestroyed
│    = false
│    ↓ AppCompatDelegateImpl.mActionBar
│                            ~~~~~~~~~~
├─ androidx.appcompat.app.ToolbarActionBar instance
│    Leaking: UNKNOWN
│    Retaining 34.4 kB in 716 objects
│    ↓ ToolbarActionBar.mDecorToolbar
│                       ~~~~~~~~~~~~~
├─ androidx.appcompat.widget.ToolbarWidgetWrapper instance
│    Leaking: UNKNOWN
│    Retaining 34.3 kB in 712 objects
│    ↓ ToolbarWidgetWrapper.mToolbar
│                           ~~~~~~~~
├─ androidx.appcompat.widget.Toolbar instance
│    Leaking: UNKNOWN
│    Retaining 33.3 kB in 686 objects
│    View not part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mID = R.id.toolbar
│    View.mWindowAttachCount = 1
│    mPopupContext instance of org.mozilla.focus.activity.MainActivity with
│    mDestroyed = false
│    mContext instance of org.mozilla.focus.activity.MainActivity with
│    mDestroyed = false
│    ↓ View.mParent
│           ~~~~~~~
╰→ android.widget.LinearLayout instance
​     Leaking: YES (ObjectWatcher was watching this because org.mozilla.focus.
​     settings.SettingsFragment received Fragment#onDestroyView() callback
​     (references to its views should be cleared to prevent leaks))
​     Retaining 17.9 kB in 404 objects
​     key = 8cdc8fec-0181-42e8-bc10-5dc1931ea8b8
​     watchDurationMillis = 14067
​     retainedDurationMillis = 9066
​     View not part of a window view hierarchy
​     View.mAttachInfo is null (view detached)
​     View.mWindowAttachCount = 1
​     mContext instance of org.mozilla.focus.activity.MainActivity with
​     mDestroyed = false

**Comment by jonalmeida** [comment]
I think I came across the same leak as well with a slightly different trace:

```
┬───
│ GC Root: Global variable in native code
│
├─ android.graphics.animation.RenderNodeAnimator instance
│    Leaking: UNKNOWN
│    Retaining 38.0 kB in 834 objects
│    mListeners[0] = android.graphics.drawable.RippleAnimationSession$3
│    ↓ RenderNodeAnimator.mTarget
│                         ~~~~~~~
├─ android.graphics.RenderNode instance
│    Leaking: UNKNOWN
│    Retaining 35.9 kB in 764 objects
│    ↓ RenderNode.mAnimationHost
│                 ~~~~~~~~~~~~~~
├─ android.view.ViewAnimationHostBridge instance
│    Leaking: UNKNOWN
│    Retaining 35.8 kB in 763 objects
│    ↓ ViewAnimationHostBridge.mView
│                              ~~~~~
├─ androidx.appcompat.widget.AppCompatImageButton instance
│    Leaking: UNKNOWN
│    Retaining 35.8 kB in 762 objects
│    View not part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 1
│    mContext instance of org.mozilla.focus.activity.MainActivity with mDestroyed = false
│    ↓ View.mParent
│           ~~~~~~~
├─ androidx.appcompat.widget.Toolbar instance
│    Leaking: UNKNOWN
│    Retaining 32.1 kB in 687 objects
│    View not part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mID = R.id.toolbar
│    View.mWindowAttachCount = 1
│    mPopupContext instance of org.mozilla.focus.activity.MainActivity with mDestroyed = false
│    mContext instance of org.mozilla.focus.activity.MainActivity with mDestroyed = false
│    ↓ View.mParent
│           ~~~~~~~
╰→ android.widget.LinearLayout instance
     Leaking: YES (ObjectWatcher was watching this because org.mozilla.focus.settings.MozillaSettingsFragment received
     Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks))
     Retaining 19.5 kB in 451 objects
     key = 7bbce6ca-9976-4a4c-a1df-9d57a7f0e030
     watchDurationMillis = 5915
     retainedDurationMillis = 914
     View not part of a window view hierarchy
     View.mAttachInfo is null (view detached)
     View.mWindowAttachCount = 1
     mContext instance of org.mozilla.focus.activity.MainActivity with mDestroyed = false

METADATA

Build.VERSION.SDK_INT: 32
Build.MANUFACTURER: Google
LeakCanary version: 2.8.1
App process name: org.mozilla.focus.debug
Count of retained yet cleared: 1 KeyedWeakReference instances
Stats: LruCache[maxSize=3000,hits=108487,misses=180484,hitRate=37%]
RandomAccess[bytes=9202385,reads=180484,travel=61049289417,range=33601989,size=41016021]
Analysis duration: 4871 ms
```

**Comment by ionutbedregeanu** [comment]
Note for QA: Please navigate through the entire app and check if the toolbar is displayed or not as before this ticket
