### ISSUE TITLE
[custom tab] Some elements from the toolbar are white

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6792]
## Steps to reproduce
1. Make Focus Nightly your default browser.
2. From Gmail open a link on a custom tab.
3. Observe the back arrow, and share icon.

### Expected behavior
All the elements have the same colour.

### Actual behavior
The back arrow, and share icon are white, no matter which theme the device is set on.

### Device information
* Android devices: Oppo Find X3 Lite (Android 11), Google Pixel (Android 10)
* Not reproducible on Lenovo tablet M10 (Android 10)
* Focus version: Focus Nightly from 3/30
* Not reproducible on RC 99.1.0
<img src = https://user-images.githubusercontent.com/40694158/160876826-ccf0ba64-6421-422f-9f9e-39d0afc9a511.jpg  width="40%" />

**Comment by ionutbedregeanu** [comment]
Should be fixed after https://github.com/mozilla-mobile/focus-android/pull/6751 merge

**Comment by lobontiumira** [comment]
Reproducible on Beta 100.0.0-beta.1 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on Beta 100.0.0-beta.2 with Oppo Find X3 Lite (Android 11):

![Screenshot_3](https://user-images.githubusercontent.com/40694158/162428707-6762acdb-5c63-4372-8ac5-716c71b2ff36.jpg)

**Comment by ionutbedregeanu** [comment]
@jeffreygee @amedyne What color should the toolbar have in custom tab?

**Comment by jeffreygee** [comment]
@ionutbedregeanu @amedyne - all icons in the toolbar on light mode should be #291D4F

**Comment by iorgamgabriel** [comment]
Focus supports any color  to the toolbar that an external app sends in the intent when it opens a Custom Tab . Now we should set the color of the icons from the toolbar to be in contrast with the toolbar background color . I think this is the bug . 
We should support something like Google Chrome https://developer.chrome.com/docs/android/custom-tabs/integration-guide/#opening-a-custom-tab .
@jeffreygee  do you agree?

**Comment by iorgamgabriel** [comment]
No , we are setting the color of the toolbar based on what the external app sends . One of the most important aspects of Custom Tabs should be  the ability for an external app to change the color of the toolbar  to be consistent with the app's theme. . We should programmatic set the color of the icons based on the toolbar background color. @jeffreygee

**Comment by jeffreygee** [comment]
@iorgamgabriel - my only worry about this route (if im understanding this) is that we'd need enough contrast between the icons and the color of the toolbar for accessibility. The only way to truly keep that accessible is if we set the color of the toolbar, right? or is there a programmatic way to change the icon color based on 'x' range of colors?

**Comment by iorgamgabriel** [comment]
Yes we can calculate the color of icons programatic base on toolbar color .

**Comment by jonalmeida** [comment]
@jeffreygee @iorgamgabriel we should be using the colour for the Custom Tab that the app is requesting when provided. Based on the colour that is provided to the toolbar, the icons are then tinted white or black to increase contrast between the two (for reference, [this is the code](https://github.com/mozilla-mobile/android-components/blob/7219f3956183781db8563c46573ee2344c41b667/components/support/utils/src/main/java/mozilla/components/support/utils/ColorUtils.kt#L16-L18=) we use to determine what colour to use).

Forcing a colour for the toolbar breaks the API contract, but also reduces the UX features that Custom Tabs are trying to provide.

Have a look at Fenix as well that uses the same [feature component](https://github.com/mozilla-mobile/android-components/blob/7219f3956183781db8563c46573ee2344c41b667/components/support/utils/src/main/java/mozilla/components/support/utils/ColorUtils.kt#L16-L18=t) so that we don't have to re-implement a standard implementation across our apps.

**Comment by iorgamgabriel** [comment]
Thank you very much @jonalmeida

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 102.0a1 (build 361320510 with GV 102.0a1-20220511094252) with Oppo Find X3 Lite (Android 11), and Google Pixel (Android 10).

![Screenshot_2022-05-12-10-42-11-76_11753d9bf2a67eec1c984b8ccb4d0671](https://user-images.githubusercontent.com/40694158/168018364-82bcc420-057d-4562-be99-57e20e1bf578.jpg)

**Comment by delia-pop** [comment]
Reproducible on Focus RC 100.2.0 with Google Pixel 6 (android 12) and Xiaomi mi4i (Android 5.0.2).

**Comment by delia-pop** [comment]
Reproducible on Focus RC 100.3.0 with Motorola Moto G30 (Android 11).

**Comment by delia-pop** [comment]
Reopening this ticket since I was able to reproduce this issue on the latest Focus Beta 105.0b1 with Google Pixel 6 (Android 13).

<img src="https://user-images.githubusercontent.com/89388888/186155085-629d2a2c-bc56-49c5-8ca0-2cc05b66160d.png" width="40%" />

**Comment by mcarare** [comment]
I cannot reproduce this on a Pixel 4 with Android 13. @delia-pop can you mention the app you opened the custom tab from? TY!

**Comment by mcarare** [comment]
This seems to only be reproducible with custom tabs opened from Focus itself.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 107.0a1 build from 10/16 with Google Pixel (Android 10), and Oppo Find X3 Lite (Android 11):

![Screenshot_20221017-095614](https://user-images.githubusercontent.com/40694158/196109901-72192639-b3ea-43a1-9290-5dad936cae5b.png)

**Comment by lobontiumira** [comment]
Verified as fixed also on Beta 107.0b1 build.
