### ISSUE TITLE
Intermittent UI test failure - WebControlsTest.telephoneLinkTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#6793]
### Firebase Test Run:
Flaky, 1/2 runs
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5168453731992422477/executions/bs.46e65b8b29641ab3
### Stacktrace:
`03-29 08:48:27.195: I/WindowManager(482): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: fd8c43d org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5001ms for FocusEvent(hasFocus=false)
03-29 08:48:27.355: I/.android.diale(13497): WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 8.113ms
03-29 08:48:27.405: I/ActivityManager(482): Force stopping org.mozilla.focus.debug appid=10151 user=0: finished inst
03-29 08:48:27.405: I/ActivityManager(482): Killing 12567:org.mozilla.focus.debug:tab8/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-29 08:48:27.406: W/Binder(11953): Caught a RuntimeException from the binder stub implementation.
03-29 08:48:27.406: W/Binder(11953): java.lang.SecurityException: Calling from not trusted UID!
03-29 08:48:27.406: W/Binder(11953): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
03-29 08:48:27.406: W/Binder(11953): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
03-29 08:48:27.406: W/Binder(11953): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
03-29 08:48:27.406: W/Binder(11953): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
03-29 08:48:27.406: W/Binder(11953): 	at android.os.Binder.execTransact(Binder.java:1123)
03-29 08:48:27.409: D/AndroidRuntime(11953): Shutting down VM
03-29 08:48:27.411: I/ActivityManager(482): Killing 12044:org.mozilla.focus.debug/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-29 08:48:27.415: I/ServiceChildProcess(12740): Destroying GeckoServiceChildProcess
03-29 08:48:27.416: W/ActivityTaskManager(482): Force removing ActivityRecord{c56b605 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
03-29 08:48:27.430: I/ActivityManager(482): Killing 12740:org.mozilla.focus.debug:gpu/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-29 08:48:27.431: D/WindowManager(482): notifyANR took 261ms`
### Build:
Debug 3/30

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
