### ISSUE TITLE
Intermittent UI test failure - < AddToHomescreenTest.noNameShortcutTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6806]
### Stacktrace:
03-30 23:51:08.433: I/WindowManager(481): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 19e9ac0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=false)
03-30 23:51:08.543: W/Role(5962): Cannot get ApplicationInfo for default holder: com.google.android.dialer
03-30 23:51:08.572: W/Binder(11611): Caught a RuntimeException from the binder stub implementation.
03-30 23:51:08.572: W/Binder(11611): java.lang.SecurityException: Calling from not trusted UID!
03-30 23:51:08.572: W/Binder(11611): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
03-30 23:51:08.572: W/Binder(11611): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
03-30 23:51:08.572: W/Binder(11611): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
03-30 23:51:08.572: W/Binder(11611): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
03-30 23:51:08.572: W/Binder(11611): 	at android.os.Binder.execTransact(Binder.java:1123)
03-30 23:51:08.572: I/ActivityManager(481): Force stopping org.mozilla.focus.debug appid=10151 user=0: finished inst
03-30 23:51:08.572: I/ActivityManager(481): Killing 12549:org.mozilla.focus.debug:tab6/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-30 23:51:08.606: I/ActivityManager(481): Killing 14587:org.mozilla.focus.debug:tab7/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-30 23:51:08.631: D/AndroidRuntime(11611): Shutting down VM
03-30 23:51:08.709: I/Zygote(290): Process 12549 exited due to signal 9 (Killed)
03-30 23:51:08.723: I/libprocessgroup(481): Successfully killed process cgroup uid 10151 pid 12549 in 139ms
03-30 23:51:08.773: I/ActivityManager(481): Killing 11732:org.mozilla.focus.debug/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-30 23:51:08.779: W/ActivityTaskManager(481): Force removing ActivityRecord{f018c83 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
03-30 23:51:08.838: I/ActivityManager(481): Killing 12710:org.mozilla.focus.debug:gpu/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst

### Notes
[Logcat](https://github.com/mozilla-mobile/focus-android/files/8388422/noNameShortcutTest.txt)
❗ Similar with the ANR reported in [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by ionutbedregeanu** [comment]
Fails on https://github.com/mozilla-mobile/focus-android/pull/6618

**Comment by sv-ohorvath** [comment]
Disabled in https://github.com/mozilla-mobile/focus-android/pull/6618
see https://github.com/mozilla-mobile/focus-android/issues/6958

**Comment by sv-ohorvath** [comment]
Closing as dupe, in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
