### ISSUE TITLE
Update search Engines and Search Engine Icons

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6811]
See Jira ticket [here](https://mozilla-hub.atlassian.net/browse/FADPV2-3513). 

[Focus](https://www.figma.com/file/epu0Sj6mCPk7K282sNpHgI/Site?node-id=3337%3A49199) search engines and their icons should match desktop with the exception that Focus does not include Bing.

Design docs for Focus.

Android Focus: 

    Update the Amazon, DuckDuckGo, and Wikipedia icons.

    Update the order of the search engines: Google, Amazon, DDG, eBay, Wikipedia

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly build from 4/13 that the update of the search engines icons, and that the order of the search engines is:
* Google
* Amazon
* DuckDuckGo
* eBay
* Wikipedia
