### ISSUE TITLE
Focus crash when user opens an CustomTab

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/focus-android#6832]
1.Make Firefox Focus your default browser.
2.Open a link in custom tab.
3.Focus will crash 

Expected behaviour :
Should open the page in a custom tab 

* Android device: Pixel 3 XL with Android 12 
* Focus version: 100

Crash Log: 2022-04-05 15:58:04.118 5642-5750/org.mozilla.focus.debug E/Web Content: [JavaScript Error: "Error: IndexedDB failed to initialise: undefined" {file: "https://aid-frontend.prod.atl-paas.net/atlassian-id/front-end/5.0.331/static/js/40.53063a58.chunk.js" line: 2}]
2022-04-05 15:58:05.061 5519-5519/org.mozilla.focus.debug E/mozac/CrashReporter: CrashHandlerService received native code crash

**Comment by iorgamgabriel** [comment]
https://user-images.githubusercontent.com/8118371/161760814-25f08696-7bd9-4a9c-b310-51a98015c767.mp4

**Comment by cpeterso** [comment]
Irene was not able to reproduce this crash in the GeckoViewExample app: https://bugzilla.mozilla.org/show_bug.cgi?id=1763147#c6

That suggests that this crash is a Focus-specific bug. She thinks it might be a bug with Focus's custom tab feature or handling of permissions. If you think this is a GeckoView bug, please reopen GeckoView bug https://bugzilla.mozilla.org/show_bug.cgi?id=1763147.

**Comment by iorgamgabriel** [comment]
https://user-images.githubusercontent.com/8118371/180416795-f9863fff-5b72-43ad-980a-1002be8c2d68.mp4

I can't reproduce this bug . I will close it .
