### ISSUE TITLE
Record telemetry event to indicate that we were unable to download experiments

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6847]
See discussion here: https://github.com/mozilla-mobile/focus-android/pull/6618#issuecomment-1091688914

Set expiry to be release version 112.

**Comment by heres-maria** [comment]
Verified as part of [QA-1485](https://mozilla-hub.atlassian.net/browse/QA-1485) on Focus Nightly 102.0a1 builds #361300946 GV: 102.0a1-20220509094710 through  #361380927 GV: 102.0a1-20220517092745 using Android 9 - Samsung Galaxy S8.
The nimbus_initial_fetch metric was sent for every startup.
