### ISSUE TITLE
Lao: "error_unsupportedprotocol_message" contains invalid XHTML (Opening and ending tag mismatch)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#685]
When importing strings our tool reports an error in the "error_unsupportedprotocol_message" for Lao (lo):

>  [unchanged] app/src/main/res/values-lo/strings.xml
>              - "error_unsupportedprotocol_message" contains invalid XHTML (Opening and ending tag mismatch: ul line 1 and string, line 2, column 76 (line 2)); Falling back to loose parser.

**Comment by flodolo** [comment]
Should land in the repo in about 10 minutes
https://pontoon.mozilla.org/lo/focus-for-android/app.po/?search=error_unsupportedprotocol_message&string=163950

**Comment by flodolo** [comment]
https://github.com/mozilla-l10n/focus-android-l10n/commit/723b6c88feb09e80b1667420bc73418e5caf4a55

**Comment by pocmo** [comment]
Thanks! I created a new import (PR #686)
