### ISSUE TITLE
Allow users change permissions for just the current session on the fly

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6851]
As a followup to https://github.com/mozilla-mobile/focus-android/issues/6504 which adds site-permissions handled per application and not per website we could add a way for users to easily check and even change permissions for just the current session without having to go to settings to check or change the default set per application.

Initially proposed here - https://github.com/mozilla-mobile/focus-android/issues/6504#issuecomment-1050612472
The dialog shown on Fenix would still apply but it probably needs some changes, I'm thinking at
- a clear indications that any change here would not change the default per app?
- showing the permissions in the same dialog as the 'Trackers and Scripts to Block" section would probably fill the entire screen.
Maybe when opening this the permissions (or both sections) could be shown as collapsed with the user then being able to expand each section to check/change settings?

| permissions on Fenix | ETP on Focus |
| --- | --- |
| <img width="323" alt="permissions on Fenix" src="https://user-images.githubusercontent.com/11428869/162391450-3a647653-6440-4d78-968c-019f1dbaf887.png"> | <img width="323" alt="ETP on Focus" src="https://user-images.githubusercontent.com/11428869/162391833-880bf6f4-445d-43e8-902a-1cc92af0caf9.png"> |

Asking @jeffreygee about a decision and design.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801997

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
