### ISSUE TITLE
Consider showing an indicator for when site permissions are in use.

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6852]
As a followup to #6504 which adds site-permissions we could show an indicator for when site permissions are in use similar to what is being shown on Fenix.

We could use the same blue dot implemented in https://github.com/mozilla-mobile/android-components/issues/9378 something that we could very easily get - https://github.com/mozilla-mobile/focus-android/issues/6504#issuecomment-1065285269 .

<img width="323" alt="blue dot" src="https://user-images.githubusercontent.com/11428869/162395435-dbe82047-c8ea-4fcd-be41-cc3e8bc2a20c.png">

Asking @jeffreygee for decision and design.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801996

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
