### ISSUE TITLE
Focus stuck in landscape mode

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6862]
## Steps to reproduce
1. Open Focus and start streaming from youtube, set to full screen.
2. Swipe up and go to home (device home) to trigger PiP.
3. Open Fenix go to google.com, share to focus
### Expected behavior
 PiP dismissed, google.com opened. Focus should be now showing in portrait orientation.
### Actual behavior
PiP dismissed, google.com opened. Focus stuck in landscape mode and doesn't matter how I rotate the device it won't switch to portrait mode.
### Device information

* Android device: Pixel 3a Android 11
* Focus version: Nightly 101

**Comment by indurs** [comment]
@ionutbedregeanu , can I work on this issue?

**Comment by ionutbedregeanu** [comment]
@indurs Sure. Thanks!

**Comment by indurs** [comment]
@ionutbedregeanu , this issue is fixed in A-C.  
https://github.com/mozilla-mobile/android-components/pull/12169

**Comment by delia-pop** [comment]
Verified as fixed on the latest Focus Nightly 103.0a1 from 06/02 (build 361540510 with GV 103.0a1-20220602231739), with Google Pixel 6 (Android 12). The website opens correctly in Portrait mode.
