### ISSUE TITLE
Removing content blocking exceptions doesn't actually work 

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/focus-android#6888]
## Steps to reproduce

Create some content blocking exceptions by visiting sites, clicking the shield icon in the address bar, and toggling off cintent blocking for those sites. 

Go to Settings, Privacy & Security, Exceptions

Either tap the "remove all exceptions" button, or go into "remove" mode via the vertical three dot menu then remove some individual sites from the exceptions list. 

See that the removed exceptions are no longer in the list. 

Kill the app via android app switcher. 

Reopen the app. Go back to the exceptions list. 

See the removed exceptions are back in the list (this may require one or more app kills) without actively toggling them back off on the sites themselves. 

### Expected behavior

Removed exceptions should stay off the exceptions list until/unless the user re-adds them. 

### Actual behavior

Removed exceptions don't seem to actually get removed. 

### Device information

* Android device: Samsung Galaxy S21, Android 12
* Focus version: 99.2.0

**Comment by KWierso** [comment]
I thought it was maybe me killing the app before Focus has a chance to write to disk, but I waited a minute or two after removing the exceptions (and then navigated to google.com) before I killed the app, and the removed exceptions all came back.

**Comment by KWierso** [comment]
This started from a reddit thread https://www.reddit.com/r/firefox/comments/u62djw/cannot_get_rid_of_site_exceptions_firefox_focus/

**Comment by lobontiumira** [comment]
We were not able to reproduce this issue on the latest Focus Nightly 101.0a1 from 4/19, nor on RC 99.2.0.
Tested with OnePus 9 (Android 12), and Oppo Find X3 Lite (Android 11).
I'll leave this ticket opened, fur more investigation.

**Comment by SoftVision-LorandJanos** [comment]
I wasn't able to reproduce this issue either using two devices with android 12:
- Google Pixel 4 (Android 12)
- Oppo Reno 6 (Android 12)

Tested on the latest Nightly 101.0a1 (20220418091627) build.
