### ISSUE TITLE
Intermittent UI test failure - < SafeBrowsingTest. blockUnwantedSoftwarePageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6889]
### Firebase Test Run: 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5844236252701674209/executions/bs.85794c90f986c5d3/testcases/1)

[Logcat](https://00f74ba44b5d487e26db65f9853e492816ab95f706-apidata.googleusercontent.com/download/storage/v1/b/focus_android_test_artifacts/o/2022-04-16_15-20-28.709196_Knhd%2Fmatrix_0%2FPixel3-30-en-portrait-shard_35%2Flogcat?jk=AFshE3V_b42PSvOkh6FiId7aOXtNHZ3OpCstJZ45Bb5ZZ0RPoGI6wtvaMhoFhp-AuJq60Kd3FRmOOmxjMFB5KLMQxAotqW2_YUWkrkoSvUTOrHi5Jy9J5ftQr8S7erNKUDdAjngWAUAcHGKhCFq9vKRM7kLl9a5Inairtrg5OFZ_hznlFQJ4bb7axsnU8GtHTdvJjo2DH6QBG5XtGltHw7ouaR6X99X-PLsYKaI3rR9o4PCDqp26XbVfsc2xC-uSHZjWMdDSd6-DHrK8vaaSXo1uz3jF2vGFBaYphoq_o7Fa1FtfMzlVLXRW6amCgfoc9EwvIknwafMXzavTfGXQzb78GQRJd67JkJiKplXUE9ZSlQrd7Qwx3QCr_duEcqmAlP6wLXTJjm96JbhWFamUAUAdKrH6jN7lWd4XL8jETI-I3sof4Y6NABGIaOxv8jpHWbZmLbOHzU1us2bzN8T_nsobT0ZlEZEa4_y9e41zp1lPXZyQWEf7gZs0I_4jX4mAWjG8ct19hhp4DRKfpu-I5oFGvk90QP3hJQf-OsKS9ZuJOsOydUVraGW_T3_MxiV50O4Z80vJaLGSjx9p_4T5B0a7TWbCdfYpsaELeUtqaJcSZ7fsLitXDTlrHzChKkE35kKr1E1SAD8ieLIiOqCMJJVxVff3ZMO13ur7mXX7zTfKw2KNDxuqKCjqyYng6nA_S4kYfUgXefhExPvLpVUEk-J-6AzG2F_--AQEv4_dekJt5YAkczgffS6HtEF2dz22MQuqHZh4GxMH5pYBQopkAO1ynYU51NAsD8E_U9df22qCCGTVBYx4_pBwVcn1QaYMWJvSoj_Qg896ziAh5k35wIANqandD5AXBEITU3P_hrFeRZq1KWjQkoSAvjgVPpDY2EkyYTqE-V18-qJPq9Kd17ans2A9pFA6zWQXd2YkF0qp9WjM2H2jP7DdrvzhXN0siCelZt5D0OwAdAQh3p-C9ZtLyAVLKuufjLxms-0vRvrLalgLfyMGYSWr_Ni2IFqT2_DY3Hy9FovupzzoJZkADRnkP41GHwmjaGFvroBDOyQU3eqJEoarkdNWx3aDoaenfDOLNeTmo_VjnTBo_h53jO71RvwIx1jPEpz9gVf4rPpUhLkrjrJl2vXB-nzQZjVvDPFVkA&isca=1)
### Stacktrace:
04-16 08:24:55.344: I/WindowManager(479): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 1e5c8e6 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5004ms for FocusEvent(hasFocus=false)
04-16 08:24:55.491: I/ActivityManager(479): Force stopping org.mozilla.focus.debug appid=10151 user=0: finished inst
04-16 08:24:55.491: I/ActivityManager(479): Killing 14133:org.mozilla.focus.debug/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
04-16 08:24:55.500: W/ActivityTaskManager(479): Force removing ActivityRecord{77718ab u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
04-16 08:24:55.477: I/chatty(1860): uid=1041(audioserver) writer identical 9 lines
04-16 08:24:55.492: W/audio_hw_generic(1860): Hardware backing HAL too slow, could only write 0 of 661 frames
04-16 08:24:55.501: I/ServiceChildProcess(14634): Destroying GeckoServiceChildProcess
04-16 08:24:55.506: I/ActivityManager(479): Killing 14634:org.mozilla.focus.debug:tab37/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
04-16 08:24:55.507: W/audio_hw_generic(1860): Hardware backing HAL too slow, could only write 0 of 661 frames
04-16 08:24:55.509: I/ActivityManager(479): Killing 14766:org.mozilla.focus.debug:gpu/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
04-16 08:24:55.512: D/AndroidRuntime(14045): Shutting down VM
04-16 08:24:55.522: W/audio_hw_generic(1860): Hardware backing HAL too slow, could only write 0 of 661 frames
04-16 08:24:55.527: D/WindowManager(479): notifyANR took 190ms
### Build: 4/16 Main 

Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for approx. a month.

**Comment by jonalmeida** [comment]
Re-opening.

Happened in https://github.com/mozilla-mobile/focus-android/pull/7101. Both runs failed here: https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6665406313744881905

```
 java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
at org.mozilla.focus.activity.SafeBrowsingTest$blockUnwantedSoftwarePageTest$2.invoke(SafeBrowsingTest.kt:83)
at org.mozilla.focus.activity.SafeBrowsingTest$blockUnwantedSoftwarePageTest$2.invoke(SafeBrowsingTest.kt:82)
at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
at org.mozilla.focus.activity.SafeBrowsingTest.blockUnwantedSoftwarePageTest(SafeBrowsingTest.kt:82) 
```

[logcat.txt](https://github.com/mozilla-mobile/focus-android/files/8766085/logcat.txt)

**Comment by AndiAJ** [comment]
Failed 1x on 5/25 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8860814377759403630/executions/bs.5b4a2b4152447db8/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8860814377759403630/executions/bs.1165df8458e850bb/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockUnwantedSoftwarePageTest$2.invoke(SafeBrowsingTest.kt:82)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockUnwantedSoftwarePageTest$2.invoke(SafeBrowsingTest.kt:81)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.SafeBrowsingTest.blockUnwantedSoftwarePageTest(SafeBrowsingTest.kt:81)

**Comment by AndiAJ** [comment]
Let's log only the ANR failures in this ticket.
The verifyPageContent issue will be tracked in #7113

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by AndiAJ** [comment]
Flaky 1x on 6/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4754503188057136843/executions/bs.c6365b28221b0ce6)

06-21 09:15:16.595: I/WindowManager(480): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 6e67136 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false)
06-21 09:15:16.720: W/ActivityManager(480): Slow operation: 83ms so far, now at getContentProviderImpl: after updateOomAdj
06-21 09:15:16.721: W/ActivityManager(480): Slow operation: 83ms so far, now at getContentProviderImpl: done!
06-21 09:15:16.810: I/ActivityManager(480): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-21 09:15:16.810: I/ActivityManager(480): Killing 14254:org.mozilla.focus.debug:tab0/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-21 09:15:16.814: I/ActivityManager(480): Killing 13704:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-21 09:15:16.801: I/chatty(1890): uid=1041(audioserver) writer identical 14 lines
06-21 09:15:16.816: W/audio_hw_generic(1890): Hardware backing HAL too slow, could only write 0 of 661 frames
06-21 09:15:16.819: I/ServiceChildProcess(14388): Destroying GeckoServiceChildProcess
06-21 09:15:16.823: W/ActivityTaskManager(480): Force removing ActivityRecord{be6b99e u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-21 09:15:16.824: D/AndroidRuntime(13632): Shutting down VM
06-21 09:15:16.830: W/audio_hw_generic(1890): Hardware backing HAL too slow, could only write 0 of 661 frames
06-21 09:15:16.839: I/Finsky(12782): [901] nmi.run(36): Stats for Executor: BlockingExecutor non@f001c0f[Running, pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 24]
06-21 09:15:16.845: W/Binder(13632): Caught a RuntimeException from the binder stub implementation.
06-21 09:15:16.845: W/Binder(13632): java.lang.SecurityException: Calling from not trusted UID!
06-21 09:15:16.845: W/Binder(13632): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-21 09:15:16.845: W/Binder(13632): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-21 09:15:16.845: W/Binder(13632): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-21 09:15:16.845: W/Binder(13632): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-21 09:15:16.845: W/Binder(13632): 	at android.os.Binder.execTransact(Binder.java:1123)
06-21 09:15:16.846: W/audio_hw_generic(1890): Hardware backing HAL too slow, could only write 0 of 661 frames
06-21 09:15:16.847: I/ActivityManager(480): Killing 14388:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-21 09:15:16.850: D/WindowManager(480): notifyANR took 299ms

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
