### ISSUE TITLE
Nimbus API usage is triggering massive amounts of exposure events

### ISSUE THREAD

**Issue by travis79** [mozilla-mobile/focus-android#6894]
Due to how [`Nimbus.isMultiTabsEnabled](https://github.com/mozilla-mobile/focus-android/search?q=isMultiTabsEnabled) is called, each invocation triggers an exposure event to be recorded. This has exposed some downstream issues (which I'm also filing issues for). 

To resolve this, Focus should change the invocation to manually trigger the exposure event: 
`.getVariables("app-menu", sendExposureEvents = false)`

And then ensure that the exposure event is only called _once_, manually, when the user is first exposed to the feature.

ref: https://experimenter.info/feature-variables-and-me#recording-exposure-events

**Comment by ionutbedregeanu** [comment]
This ticket was already addressed in https://github.com/mozilla-mobile/focus-android/pull/6897
