### ISSUE TITLE
Rename tabs experiment flag(is_multi_tab)

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6901]
### Why/User Benefit/User Problem
is_multi_tab should use kebab case to follow FML code style

### What / Requirements
is_multi_tab from tabs experiment(.experimenter.yaml file)should be refactored to is-multi-tab
### Acceptance Criteria (how do I know when I’m done?)
Tabs experiment should look like this

`tabs:
  description: Nimbus feature name intended to control the multiple tabs feature in the app.
  hasExposure: true
  exposureDescription: ""
  variables:
    is-multi-tab:
      type: boolean
      description: "Nimbus variable of [FEATURE_TABS] allowing outside control of whether the multiple tabs feature should be enabled or not."
`

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801995

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
