### ISSUE TITLE
[a11y] The selected radio button option is read as "double-tap to activate"

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6903]
## Steps to reproduce
1. Turn talkback/screen reader on.
2. Open Focus Nightly, and open the three-dot menu using talkback gestures.
3. Go to Settings - Privacy & Security - Site permissions - Autoplay, and scroll through the options,
or go to Settings - Privacy & Security - Site permissions - Camera, or Location, or Microphone,
or go to Settings - Privacy & Security - Block cookies.
5. Listen what the screen reader announces.

### Expected behavior
The selected option is read as "checked [name of the option]".

### Actual behavior
The selected option is read as "Block audio only. Recommended. Double-tap to activate." although this option is already activated.
Or "Checked block cross-site cookies. Double-tap to toggle", although this option is checked.

### Device information
* Android device: Oppo Find X3 Lite (Android 11)
* Focus version: Focus Nightly 101.0a1 from 4/20

**Comment by PalakSDarji** [comment]
Hi @lobontiumira, I can fix this bug. Let me know. Thanks. 👍

**Comment by ionutbedregeanu** [comment]
Sure, @PalakSDarji. Thanks!

**Comment by ionutbedregeanu** [comment]
Since are no updates after assignation I will assign it on me

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 102.0a1 build from 5/5 with several devices:
* Oppo Reno 6 (Android 12),
* Sony Xperia Z5 Premium (Android 7.1.1), and 
* Xiaomi Mi8 Lite (Android 10).

All the radio buttons from Settings - Privacy & Security - Site permissions are announced as checked, without the "double-tap to toggle/activate" part.
However, the options from Settings - Privacy & Security - Block cookies are still read as checked with the "double-tap to toggle/activate" part.
@ionutbedregeanu could you please take a look? Thanks!

**Comment by ionutbedregeanu** [comment]
@lobontiumira Unfortunately Block cookies dialog is build using and android component ListPreference and this is wrongly read by talkback sometimes. What we can do to fix this is to refactor the entire component, but I don't think it worth the effort and we should let it as it is
