### ISSUE TITLE
about:config doesn't do anything

### ISSUE THREAD

**Issue by JesterDoobiesmoker** [mozilla-mobile/focus-android#6906]
## Steps to reproduce
Install Firefox Klar, type "about:config" in address bar. 
### Expected behavior
Advanced config page opens

### Actual behavior
I very briefly see a purple "working" line then the previous page address comes back but this page doesnt reload or anything its like nothing was ever typed.

### Device information
Ulefone Note 11P NonEU version

* Android device: ?  11
* Focus version: ?99.2.0

**Comment by cadeyrn** [comment]
This is expected, about:config is only supported in pre-release builds.

**Comment by lobontiumira** [comment]
I'll close this ticket as wontfix.
