### ISSUE TITLE
Firefox Focus needs a Reader Mode

### ISSUE THREAD

**Issue by n8willis** [mozilla-mobile/focus-android#6916]
## Steps to reproduce
Open Firefox Focus; reader mode is unavailable.

### Expected behavior
The benefits of reader mode apply equally to users of the Focus browser; perhaps even more than they do to the regular mobile-browser user, considering that activating reader mode has the useful side-effect of stripping out pop-up and annoy-up panels, which are more prevalent when visiting sites that actively engage in user-tracking and profiling behavior — for which Focus is the preferable browser.

### Actual behavior
Users are being left without access to reader mode.

### Device information
No restrictions.

* Android device: all
* Focus version: any

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801994

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
