### ISSUE TITLE
Record multi tabs experiment exposure when the context menu is opened

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6939]
### Why/User Benefit/User Problem
We should record multi tabs experiment exposure only when the context menu is opened and not at build
### What / Requirements
Add additional validation callback for AC context menu feature where to check if multi tabs experiment is enabled and record the exposure 
### Acceptance Criteria (how do I know when I’m done?)
Multi tabs experiment exposure is recorded only when the context menu is opened

**Comment by heres-maria** [comment]
Verified as part of [QA-1485](https://mozilla-hub.atlassian.net/browse/QA-1485) on Focus Nightly 102.0a1 builds #361300946 GV: 102.0a1-20220509094710 through  #361380927 GV: 102.0a1-20220517092745 using Android 9 - Samsung Galaxy S8.
One issue found: https://github.com/mozilla-mobile/focus-android/issues/7039

**Comment by heres-maria** [comment]
The following issues were filed during bugfix verification: #7066, #7067

**Comment by Mugurell** [comment]
If this was verified with other followup tickets opened seems like it can be closed.
