### ISSUE TITLE
Fix UI tests for SitePermissions

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6958]
SwitchContextTest: switchFromSettingsToFocusTest()
SitePermissionsTest: locationPermissionsSettingsItemsTest()
SitePermissionsTest: cameraPermissionsSettingsItemsTest()
SitePermissionsTest: autoplayPermissionsSettingsItemsTest()
AddToHomeScreenTest: noNameShortcutTest()
These UI are failing after https://github.com/mozilla-mobile/focus-android/pull/6957

**Comment by sv-ohorvath** [comment]
switchFromSettingsToFocusTest & noNameShortcutTest are unrelated, already logged in https://github.com/mozilla-mobile/focus-android/issues/6678 & https://github.com/mozilla-mobile/focus-android/issues/6507
