### ISSUE TITLE
Changing the theme opens a new tab

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6959]
## Steps to reproduce
1. Have Beta 101.0.0-beta.1 installed.
2. Open a page.
3. From the three-dot menu go to Settings - General - Theme.
4. Select "Light" or "Dark".

### Expected behavior
The selected theme has the checked radio button. The user remains in the General page.

### Actual behavior
The selected theme is applied. The user is redirected to a new tab opened.
The new opened tab is similar to the tab opened in step 2.
If there is no tab opened, a new tab is opened with the previos tab opened.

### Device information
* Android device: Oppo Reno 6 (Android 12)
* Focus version: Beta 101.0.0-beta.1
* Not reproducible on Focus nightly 102.0a1 from 5/3, nor on RC 100.1.1
* After clearing the data, I was not able to reproduce the issue again.
* logcat: [logcat.txt](https://github.com/mozilla-mobile/focus-android/files/8611118/logcat.txt)

https://user-images.githubusercontent.com/40694158/166473219-df5a297c-4db6-4631-bf7d-a212bcbdc0a6.mp4

https://user-images.githubusercontent.com/40694158/166473237-fb498c5a-66f1-4f03-9dc8-1e730faef331.mp4

**Comment by ionutbedregeanu** [comment]
@lobontiumira Still reproducible?

**Comment by lobontiumira** [comment]
I haven't seen this issue on the latest Beta builds.
I'll close it.
Thank you!
