### ISSUE TITLE
[PiP] The video keeps playing when closing the PiP floating window

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6966]
## Steps to reproduce
1. Open a site with video content (I used vimeo.com).
2. Open a video in fullscreen.
3. Tap on the device's home button to activate PiP mode.
4. From the floating window (PiP) tap the close button.
5. Return to the browser and observe the site from step 1.

### Expected behavior
The user is seeing the tab with the site from step 1. The video is paused. 

### Actual behavior
The user is seeing the tab with the site from step 1. The video is still playing.

### Device information
* Android device: Oppo Reno 6 (Android 12), Lenovo tablet M10 (Android 10)
* Focus version: Beta 101.0.0-beta.1, Focus Nightly 102.0a1 from 5/4
* Not reproducible on Fenix Nightly 102.0a1 from 5/3

https://user-images.githubusercontent.com/40694158/166653134-67fe98a4-8130-4b2e-a675-b2d63b7db8de.mp4

**Comment by delia-pop** [comment]
Reproducible on Focus Beta 101.0.0-beta.5 with Google Pixel 6 (android 12) on vimeo.com.

**Comment by delia-pop** [comment]
Reproducible on Focus RC 100.3.0 with Motorola Moto G30 (Android 11) on vimeo.com.
