### ISSUE TITLE
UI tests are failing on Api 30

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#6967]
SitePermissionsTest: sitePermissionsSettingsItemsTest()
SitePermissionsTest: blockAudioVideoAutoplayPermissionTest()
SitePermissionsTest: allowAudioVideoAutoplayPermissionTest()
SitePermissionsTest: allowAudioVideoAutoplayPermissionOnMutedVideoTest()
SafeBrowsingTest: unblockSafeBrowsingTest()

**Comment by sv-ohorvath** [comment]
unblockSafeBrowsingTest was already logged in https://github.com/mozilla-mobile/focus-android/issues/6602, not sure if this was a new issue or the same. 
Please leave a test report link here when disabling tests so we can see the issues you've encountered.
