### ISSUE TITLE
Open menu with tracker count persists after history wipe

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/focus-android#697]
Tested via 772cd8f0fd29f7daab5146fe69294975a3985147

=> cnn.com
=> open menu
=> clear history via the system notification

I suppose we should close the menu

![screenshot_1496328727](https://cloud.githubusercontent.com/assets/102331/26685630/aac046ca-46b8-11e7-8d67-1e0906509b9d.png)

**Comment by npark-mozilla** [comment]
On a related note, when going to share... or open with... menu, then clearing the history on the notification bar causes the app to either crash (in case of share) or show the app selection window to remain open.

**Comment by pocmo** [comment]
Landed a patch for this - And you updated test passes now - You can merge it. :)
