### ISSUE TITLE
Intermittent UI test failure - < ErrorPagesTest.noNetworkConnectionErrorPageTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6971]
### Stacktrace:
05-04 15:28:17.165: I/WindowManager(482): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: e0ee3e0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5005ms for FocusEvent(hasFocus=false)
05-04 15:28:17.203: W/NotificationHistory(482): Attempted to add notif for locked/gone/disabled user 0
05-04 15:28:17.236: I/chatty(1743): uid=1041(audioserver) writer identical 5 lines
05-04 15:28:17.251: W/audio_hw_generic(1743): Hardware backing HAL too slow, could only write 0 of 661 frames
05-04 15:28:17.262: E/Finsky(11988): [2] alff.run(14): Error while cleaning up task
05-04 15:28:17.262: E/Finsky(11988): java.util.concurrent.ExecutionException: com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out (timeout delayed by 39 ms after scheduled time): bvj@45f6442[status=PENDING, info=[tag=[class akjm]]]
05-04 15:28:17.262: E/Finsky(11988): 	at awuc.s(PG:3)
05-04 15:28:17.262: E/Finsky(11988): 	at awuc.get(PG:2)
05-04 15:28:17.262: E/Finsky(11988): 	at awxe.a(PG:1)
05-04 15:28:17.262: E/Finsky(11988): 	at awvz.r(Unknown Source:9)
05-04 15:28:17.262: E/Finsky(11988): 	at alff.run(Unknown Source:4)
05-04 15:28:17.262: E/Finsky(11988): 	at android.os.Handler.handleCallback(Handler.java:938)
05-04 15:28:17.262: E/Finsky(11988): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-04 15:28:17.262: E/Finsky(11988): 	at android.os.Looper.loop(Looper.java:223)
05-04 15:28:17.262: E/Finsky(11988): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
05-04 15:28:17.262: E/Finsky(11988): 	at java.lang.reflect.Method.invoke(Native Method)
05-04 15:28:17.262: E/Finsky(11988): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-04 15:28:17.262: E/Finsky(11988): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-04 15:28:17.262: E/Finsky(11988): Caused by: com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out (timeout delayed by 39 ms after scheduled time): bvj@45f6442[status=PENDING, info=[tag=[class akjm]]]
05-04 15:28:17.262: I/Finsky(11988): [2] VerifyInstallTask.mC(6): Verification complete: id=12, package_name=org.mozilla.focus.debug.test
05-04 15:28:17.266: W/audio_hw_generic(1743): Hardware backing HAL too slow, could only write 0 of 661 frames
05-04 15:28:17.281: W/audio_hw_generic(1743): Hardware backing HAL too slow, could only write 0 of 661 frames
05-04 15:28:17.292: D/InterruptionStateProvider(1605): No bubble up: not allowed to bubble: 0|android|17303299|null|1000
05-04 15:28:17.293: D/InterruptionStateProvider(1605): No heads up: unimportant notification: 0|android|17303299|null|1000
05-04 15:28:17.296: W/audio_hw_generic(1743): Hardware backing HAL too slow, could only write 0 of 661 frames
05-04 15:28:17.365: I/ActivityManager(482): Killing 11691:com.google.android.calendar/u0a106 (adj 915): empty #17
05-04 15:28:17.356: I/chatty(1743): uid=1041(audioserver) writer identical 4 lines
05-04 15:28:17.371: W/audio_hw_generic(1743): Hardware backing HAL too slow, could only write 0 of 661 frames
05-04 15:28:17.376: W/Binder(12962): Caught a RuntimeException from the binder stub implementation.
05-04 15:28:17.376: W/Binder(12962): java.lang.SecurityException: Calling from not trusted UID!
05-04 15:28:17.376: W/Binder(12962): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
05-04 15:28:17.376: W/Binder(12962): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
05-04 15:28:17.376: W/Binder(12962): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
05-04 15:28:17.376: W/Binder(12962): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-04 15:28:17.376: W/Binder(12962): 	at android.os.Binder.execTransact(Binder.java:1123)
05-04 15:28:17.376: I/ActivityManager(482): Force stopping org.mozilla.focus.debug appid=10151 user=0: finished inst
05-04 15:28:17.377: I/ActivityManager(482): Killing 13037:org.mozilla.focus.debug/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-04 15:28:17.382: I/ServiceChildProcess(13622): Destroying GeckoServiceChildProcess
05-04 15:28:17.383: I/ServiceChildProcess(13751): Destroying GeckoServiceChildProcess
05-04 15:28:17.386: W/audio_hw_generic(1743): Hardware backing HAL too slow, could only write 0 of 661 frames
05-04 15:28:17.389: W/ActivityTaskManager(482): Force removing ActivityRecord{c130b9a u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
05-04 15:28:17.391: D/AndroidRuntime(12962): Shutting down VM
05-04 15:28:17.401: W/audio_hw_generic(1743): Hardware backing HAL too slow, could only write 0 of 661 frames
05-04 15:28:17.416: W/audio_hw_generic(1743): Hardware backing HAL too slow, could only write 0 of 661 frames
05-04 15:28:17.419: I/focus.debug:gp(13751): System.exit called, status: 0
05-04 15:28:17.419: I/AndroidRuntime(13751): VM exiting with result code 0, cleanup skipped.
05-04 15:28:17.422: I/Zygote(290): Process 11691 exited due to signal 9 (Killed)
05-04 15:28:17.425: I/libprocessgroup(482): Successfully killed process cgroup uid 10106 pid 11691 in 58ms
05-04 15:28:17.430: I/cus.debug:tab1(13622): System.exit called, status: 0
05-04 15:28:17.430: I/AndroidRuntime(13622): VM exiting with result code 0, cleanup skipped.
05-04 15:28:17.431: W/audio_hw_generic(1743): Hardware backing HAL too slow, could only write 0 of 661 frames
05-04 15:28:17.442: I/ActivityManager(482): Killing 13622:org.mozilla.focus.debug:tab12/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-04 15:28:17.443: I/ActivityManager(482): Killing 13751:org.mozilla.focus.debug:gpu/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-04 15:28:17.461: D/WindowManager(482): notifyANR took 303ms
### Build:5/4 Main
Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Disabled in #7047

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
