### ISSUE TITLE
[L10N] "Location" is not translated correctly in Japanese

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6974]
## Steps to reproduce
1. Set the device to Japanese.
2. Go to Focus beta 101.0.0-beta.1, or the latest Focus Nightly 102.0a1.
3. Go to Settings - Privacy & Security - Site permissions, and observe the "Location" translation.

### Expected behavior
The "Location" translation should be "位置 (Ichi)".

### Actual behavior
The current translation is "URL" 
![japanese](https://user-images.githubusercontent.com/40694158/166947913-8b02d25b-7311-4b5f-995c-a8d3962f603b.jpg)

### Device information
* Android device: Xiaomi Mi8 Lite (Android 10)
* Focus version: Beta 101.0.0-beta.1, Focus Nightly 102.0a1
![1](https://user-images.githubusercontent.com/40694158/166948233-3f656063-35ef-4b52-9075-b3eb1c4bb695.jpg)

**Comment by Mugurell** [comment]
cc @Delphine

**Comment by Delphine** [comment]
@marsf: I know Japanese sometimes uses "URL", but wanted to double check, because in this case it seems it may be something else? thanks for letting us know

**Comment by marsf** [comment]
Now fixed. I confused it with "URL" and "GPS".
And, I checked all other strings for "locations" and "URL".

FYI: In comment or entity name of the string, if it includes some term like "permissions" or "GPS", it helps to choose correct word in Japanese translation.

Thanks.

**Comment by Delphine** [comment]
Good to know, I will let people know how that can be helpful.
And thanks for fixing all this!
this should look fixed once next l10n import happens
