### ISSUE TITLE
Focus crashes when the fingerprint auth is deleted

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6979]
## Steps to reproduce
1. Have fingerprint set and enabled on your device.
2. On Focus, go to Settings - Privacy & Security - Switching Apps, and enable the use of fingerprint.
3. On Focus open a page.
4. Put Focus in background, without closing it.
5. From the device's settings, delete the fingerprint set on step 1.
6. Open Focus -> crash.

### Expected behavior
Focus opens without requesting the fingerprint auth.

### Actual behavior
Focus crashes.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9)
* Focus version: Focus Nightly 102.0a1 from 5/6
* https://crash-stats.mozilla.org/report/index/ff88f855-e2b7-4210-a4a1-c1d1e0220506
* Additional infos are [here](https://github.com/mozilla-mobile/fenix/issues/24393#issuecomment-1099146407)

**Comment by lobontiumira** [comment]
Reproducible also on Beta 101.0.0-beta.2 with Xiaomi Mi8 Lite (Android 10).

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 102.0a1 (build 361320510 with GV 102.0a1-20220511094252) with Oppo Find X3 Lite (Android 11), and Google Pixel (Android 10).

**Comment by delia-pop** [comment]
Reproducible on Focus Beta 101.0.0-beta.5 with Google Pixel 6 (Android 12).

**Comment by delia-pop** [comment]
Reproducible on Focus RC 100.3.0 with Motorola Moto G30 (Android 11).

**Comment by lobontiumira** [comment]
Still reproducible on RC 101.1.0 with Oppo Reno 6 (Android 12).

**Comment by lobontiumira** [comment]
Reproducible on RC 101.1.1.
