### ISSUE TITLE
Display Components and App Services version on the About Page

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#6993]
Similar to Fenix, we should display the AC and App Services version that is currently being used in the currently running Focus app: 

**Expected:**
<img width="478" alt="Screen Shot 2022-05-09 at 10 58 12 PM" src="https://user-images.githubusercontent.com/1370580/167534035-3f9de9ff-2a5a-40e9-809f-fa8b5d04a800.png"> 

**Actual:**
<img width="478" alt="Screen Shot 2022-05-09 at 11 00 51 PM" src="https://user-images.githubusercontent.com/1370580/167534118-8049a594-49e0-4740-bc3a-f44a356fce5b.png">

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 102.0a1 from 5/23 with Oppo Reno 6 (Android 12):

<img src="https://user-images.githubusercontent.com/40694158/169811463-b0cb53d6-55ab-4355-b3c3-7cef6529a688.jpg" width="300" height="550" />
