### ISSUE TITLE
Focus crashes at screen orientation change while the Shield Icon CFR is displayed for mixed content pages

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7001]
**[Affected Versions]**:
- Focus Nightly 102.0a1 (Build #361300946 GV: 102.0a1-20220509094710 )

**[Affected Platforms]**:
- Android 9 - Samsung Galaxy S8

**[Prerequisites]**:
- Have a Focus for Android build with the following modifications:
     - The following lines added to local.properties:
     nimbus.remote-settings.url = https://settings.stage.mozaws.net/
     debuggable = true
     - A new “.nimbus” file (in the same location as local.properties) containing the following line: https://settings.stage.mozaws.net
- Have a Focus for Android Nimbus experiment using the onboarding feature launched to Stage Live targeting your build which sets “is-cfr-enabled” to true.

**[Steps to reproduce]**:
1. Open Focus for the first time.
2. Close the app and open it again to avoid #6995.
3. Dismiss the onboarding if necessary.
4. Navigate to https://googlesamples.github.io/web-fundamentals/fundamentals/security/prevent-mixed-content/active-mixed-content.html.
5. Change the orientation of the app to landscape while the Shield Icon CFR is displayed.

**[Expected result]**:
-  The application does not crash.

**[Actual result]**:
- The application crashes.

**[Notes]**:
- The issue is also reproducible with https://www.bennish.net/mixed-content.html.
- The issue is also reproducible when changing the orientation from landscape to portrait.
- Attached is a [recording of the issue](https://drive.google.com/file/d/1nb3PNrcSQ1ne8iKP71b-UvuSMpxakwa6/view?usp=sharing).

**Comment by ionutbedregeanu** [comment]
https://user-images.githubusercontent.com/11731652/167836317-cbc5982e-ae77-43e8-9247-5e9e812fc072.mp4

I didn't succeed to reproduce it on Pixel 3a Android 11 and Pixel 4 Android 9(emulator)
On the other hand I noticed a different bug: The tracking cfr is not anchored properly every time 
I will let this ticket open and keep an eye on it

**Comment by heres-maria** [comment]
The issue is no longer reproducible. The app no longer crashes when the screen orientation is changed from landscape to portrait or the other way around on the two test pages. Tested on Focus Nightly 102.0a1 (Build #361361204 GV: 102.0a1-20220513093538) using Android 9 - Samsung Galaxy S8.
