### ISSUE TITLE
No crashes reported for Focus Beta/Release on Sentry

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#7006]
It looks like we're not getting any crash info on Sentry for Focus Beta/Release. Our dependency SDK seems to be still using an older form of the integration, so we should update it to be similar to Fenix to use `Deps.lib_crash_sentry` and `Deps.sentry`.

See Sentry dashboard: https://sentry.io/organizations/mozilla/issues/?groupStatsPeriod=auto&page=0&project=6176960&query=is%3Aunresolved&statsPeriod=14d

**Comment by Amejia481** [comment]
Looks like we have some reports now :) 
https://sentry.io/organizations/mozilla/issues/?groupStatsPeriod=auto&page=0&project=6176960
