### ISSUE TITLE
Build time check for placeholders in strings.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#701]
See #698 - Sometimes we get crashes because a placeholder is not added or wrong in a translation of a string.

It would be nice if we had a script (in tools/ folder) that loops over all strings in our source file (values/strings.xml) and makes sure that placeholders in the source string show up correctly in the translated string as well.

* Source: no placeholders -> No check -> OK
* Source: %1$s -> Translation contains %1$s too. -> Otherwise fail build.
* Source %1$s, %2$s -> Translation contains %1$s and %2$s -> Otherwise fail build.
* Source:  %1$s -> String does not exist in Translation. -> OK, might not be translated yet.

Android does support a lot of format strings, but so far we are only using %x$s:
https://developer.android.com/reference/java/util/Formatter.html

This script could run on buddybuild as a pre-build script:
http://docs.buddybuild.com/docs/custom-prebuild-and-postbuild-steps

**Comment by friedger** [comment]
Isn't the lint check  StringFormatInvalid  meant for that?

**Comment by pocmo** [comment]
> Isn't the lint check StringFormatInvalid meant for that?

This hasn't uncovered missing placeholders in some random language files though.
