### ISSUE TITLE
The Shield Icon CFR is displayed for pages with 0 trackers

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7011]
**[Affected Versions]**:
- Focus Nightly 102.0a1 (Build #361300946 GV: 102.0a1-20220509094710)

**[Affected Platforms]**:
- Android 9 - Samsung Galaxy S8

**[Prerequisites]**:
- Have a Focus for Android build with the following modifications:
     - The following lines added to local.properties:
     nimbus.remote-settings.url = https://settings.stage.mozaws.net
     debuggable = true
     - A new “.nimbus” file (in the same location as local.properties) containing the following line: https://settings.stage.mozaws.net/
- Have a Focus for Android Nimbus experiment using the onboarding feature launched to Stage Live targeting your build which sets “is-cfr-enabled” to true.

**[Steps to reproduce]**:
1. Open Focus.
2. Close the app and open it again to avoid #6995.
3. Navigate to a page with 0 trackers (e.g. https://www.google.com/).
4. Observe the page.

**[Expected result]**:
- The Shield Icon CFR is not displayed.

**[Actual result]**:
- The Shield Icon CFR is displayed.

**[Notes]**:
- Taping the Shield Icon will display 0 trackers blocked.
- Attached is a recording of the issue.
![0 trackers](https://user-images.githubusercontent.com/53752296/168091843-e02b8f9a-ccd3-437e-a2ad-d17d8e912bc3.gif)

**Comment by ionutbedregeanu** [comment]
@jeffreygee In this scenario the message of cfr seems a bit misleading since the number of trackers is 0. Should we let it as it is, should we change the message or should we display the cfr only when the number of trackers is greater than 0?

**Comment by amedyne** [comment]
@ionutbedregeanu I agree that the CFR is only displayed when trackers are greater than 0. 
@jeffreygee something to think about here is if we need a different CFR to introduce the "shield" for new users.

**Comment by jeffreygee** [comment]
@ionutbedregeanu @amedyne yeah, i agree - i thought one of the trigger criteria was when tracker > 0?

**Comment by amedyne** [comment]
@jeffreygee Can you share the new design/flow for when there are 0 trackers?

**Comment by ionutbedregeanu** [comment]
@amedyne @jeffreygee I chose to show the cfr for tracking protection when we find for the first time blocked trackers.
Please see the video from the [draft pr](https://github.com/mozilla-mobile/focus-android/pull/7086) and let me know what you think

**Comment by heres-maria** [comment]
For now I have filed issue #7136 for tracking purposes.
