### ISSUE TITLE
Newsletter pop-up does not close on the first attempt at snowpeak.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#7028]
## Steps to reproduce
1. Navigate to: https://www.snowpeak.com/.
2. Wait for the page to load.
3. Tap on the "X" button inside the newsletter pop-up.
4. Observe the result.

### Expected behavior
The pop-up is closed on the first tap.
### Actual behavior
Numerous taps are needed in order to close the pop-up.
### Device information
Samsung A51  -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
Google Pixel 3  -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)
* Android device: Android 11, Android 12
* Focus version: Firefox Focus Nightly 102.0a1 (361360510-🦎102.0a1-20220513093538🦎)

**Notes:**
1. The issue is reproducible intermittently.
2. Not reproducible on the latest build of Firefox Nightly.
3. Not reproducible when using "Private Browsing" mode.
4. Originally reported here: https://github.com/webcompat/web-bugs/issues/104432
5. Might have a dependency on FastClick JS Library.
5. Screenrecording attached:
![fastclick focus release](https://user-images.githubusercontent.com/75027050/168558013-fe92cb05-e708-419a-ad9a-4731ec6b2efb.gif)

**Comment by iorgamgabriel** [comment]
https://user-images.githubusercontent.com/8118371/179948334-802c38d4-6e14-426a-a8d3-734fbc471820.mp4

**Comment by softvision-raul-bucata** [comment]
@iorgamgabriel I can confirm that the issue is no longer reproducible.

We appreciate your report. I was not able to reproduce the issue.
 
 
 


**Tested with:**

Browser / Version:  Firefox Focus Release 103.1.0 (361992241-🦎102.0-20220718155818🦎)/ Firefox Fenix Nightly 104.0a1 (2015893131-🦎104.0a1-20220719093424🦎)
Operating System: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
Operating System: Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)




 [inv_29/2022]
