### ISSUE TITLE
Fix focus memory leaks 

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/focus-android#7035]
All memory leaks are reported by LeakCanary.  LeakCanary is a memory leak detection library for Android.

<img src="https://user-images.githubusercontent.com/8118371/168751023-25c30487-7b41-4016-ab54-26a816c46426.png" width="300" height="600" /> 
<img src="https://user-images.githubusercontent.com/8118371/168751042-71158164-d9b8-4420-9de5-f688fd62780e.png" width="300" height="600" /> 
<img src="https://user-images.githubusercontent.com/8118371/168751047-2190814e-7a58-4135-9d7a-cd20ccf80b33.png" width="300" height="600" /> 

* Android device: all versions
* Focus version: all devices

**Comment by jonalmeida** [comment]
Let's file separate issues for each of these leaks so we can track and fix the bugs independently.
