### ISSUE TITLE
Intermittent UI test failure - < EraseBrowsingDataTest.notificationEraseAndOpenButtonTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7037]
### Stacktrace:
05-16 12:25:33.795: I/WindowManager(475): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 4a22072 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=true)
05-16 12:25:33.906: I/ActivityManager(475): Force stopping org.mozilla.focus.debug appid=10151 user=0: finished inst
05-16 12:25:33.906: I/ActivityManager(475): Killing 14056:org.mozilla.focus.debug/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-16 12:25:33.911: W/Binder(13961): Caught a RuntimeException from the binder stub implementation.
05-16 12:25:33.911: W/Binder(13961): java.lang.SecurityException: Calling from not trusted UID!
05-16 12:25:33.911: W/Binder(13961): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
05-16 12:25:33.911: W/Binder(13961): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
05-16 12:25:33.911: W/Binder(13961): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
05-16 12:25:33.911: W/Binder(13961): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-16 12:25:33.911: W/Binder(13961): 	at android.os.Binder.execTransact(Binder.java:1123)
05-16 12:25:33.912: I/ServiceChildProcess(14632): Destroying GeckoServiceChildProcess
05-16 12:25:33.912: I/ServiceChildProcess(14782): Destroying GeckoServiceChildProcess
05-16 12:25:33.915: W/ActivityTaskManager(475): Force removing ActivityRecord{b330755 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
05-16 12:25:33.956: I/cus.debug:tab3(14632): System.exit called, status: 0
05-16 12:25:33.956: I/AndroidRuntime(14632): VM exiting with result code 0, cleanup skipped.
05-16 12:25:33.986: I/focus.debug:gp(14782): System.exit called, status: 0
05-16 12:25:33.986: I/AndroidRuntime(14782): VM exiting with result code 0, cleanup skipped.
05-16 12:25:33.991: D/AndroidRuntime(13961): Shutting down VM
05-16 12:25:34.020: I/Zygote(289): Process 14632 exited cleanly (0)
05-16 12:25:34.029: W/system_server(475): Long monitor contention with owner InputDispatcher (1488) at void com.android.server.wm.WindowManagerService.onAnimationFinished()(WindowManagerService.java:7999) waiters=0 in void com.android.server.wm.WindowAnimator.lambda$new$1$WindowAnimator(long) for 108ms
05-16 12:25:34.031: I/ActivityManager(475): Killing 14632:org.mozilla.focus.debug:tab36/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-16 12:25:34.031: I/ActivityManager(475): Killing 14782:org.mozilla.focus.debug:gpu/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-16 12:25:34.034: W/Looper(475): Slow dispatch took 125ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=null m=31
05-16 12:25:34.034: D/WindowManager(475): notifyANR took 248ms
### Notes: Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Disabled in #7047

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
