### ISSUE TITLE
The exposure event for the onboarding feature is recorded multiple times at every app startup for experiments with “is-enabled” false

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7046]
**[Affected Versions]**:
- Focus Nightly 102.0a1 (Build #361380927 GV: 102.0a1-20220517092745)

**[Affected Platforms]**:
- Android 9 - Samsung Galaxy S8

**[Prerequisites]**:
- Have a Focus for Android build with the following modifications:
     - The following lines added to local.properties:
     nimbus.remote-settings.url = https://settings.stage.mozaws.net
     debuggable = true
     - A new “.nimbus” file (in the same location as local.properties) containing the following line: https://settings.stage.mozaws.net/
- Have a Focus for Android Nimbus experiment using the onboarding feature which sets “is-enabled” to false launched to Stage Live (the experiment used for testing had "is-cfr-enabled" to true as well).
- Have a way to observe Logcat (the Android Studio viewer was used for testing).

**[Steps to reproduce]**:
1. Open Focus and close it to avoid #6995.
2. Reopen the app using a [telemetry command](https://mozilla.github.io/glean/book/user/debugging/android.html) (e.g. adb shell am start -n org.mozilla.focus.nightly/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es sendPing events --es debugViewTag MH-1.
3. Minimize the app, refocus it, and observe Logcat.
4. Dismiss onboarding.
5. Close the app.
6. Reopen the app using a telemetry command.
7. Minimize the app, refocus it, and observe Logcat.

**[Expected result]**:
Step 3: The exposure event is only recorded once.
Step 7:  The exposure event is only recorded once when users are exposed to onboarding.

**[Actual result]**:
Step 3: The exposure event is recorded multiple times for the onboarding.
Step 7:The exposure event is recorded multiple times for every startup for the onboarding feature.

**[Notes]**:
- The issue was not reproducible for an experiment which sets "is-enabled" to true and "is-cfr-enabled" to false.
- Attached is a [recording of the issue](https://drive.google.com/file/d/1KrQwVlqrURWKa45g7tqTM9Z9_j3Qi9Tt/view?usp=sharing).

**Comment by ionutbedregeanu** [comment]
Should be addressed by https://github.com/mozilla-mobile/focus-android/issues/7039

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible. The exposure event is no longer recorded multiple times at every startup. Tested Focus Nightly 102.0a1 (Build #361431118 GV: 102.0a1-20220522094633) AC:102.0.20220522143114, edac10adc1, AS: 93.1.0 using Android 9 -  Samsung Galaxy S8.
