### ISSUE TITLE
The splash screen is not displayed if the app is opened in landscape mode in certain conditions

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7049]
**[Affected Versions]**:
- Focus Nightly 102.0a1 (Build #361380927 GV: 102.0a1-20220517092745)

**[Prerequisites]**:
- Have the device in the landscape position, but with the menu from which you open Focus still stuck in portrait mode.

**[Steps to reproduce]**:
1. Open Focus directly in landscape mode.
2. Observe the splash screen.

**[Expected result]**:
- The splash screen is displayed for at least 2 seconds.

**[Actual result]**:
- The splash screen does not seem to be displayed if the app is opened in landscape mode from a menu still in portrait mode.

**[Notes]**:
- If I open Focus while the UI from which I do that is in landscape mode, the splash screen is displayed.
- Attached is a recording of the issue.

https://user-images.githubusercontent.com/53752296/169042835-ef023c12-ec9c-462e-a6a9-a445d9bb5173.mov

**Comment by ionutbedregeanu** [comment]
It seems related to https://github.com/mozilla-mobile/focus-android/pull/6618#discussion_r838229130 and is considered expected by Google team

**Comment by heres-maria** [comment]
Based on the previous comment, I will close this issue as won't fix.
