### ISSUE TITLE
The text for FingerPrint subtitle should be change 

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/focus-android#7057]
The text for FingerPrint subtitle from Settings -> Privacy & Security should be change .
Now the text is  "Your fingerprint can unlock Focus if a URL is already opened in the app. Stealth will be turned on."
Here it was the initial request https://github.com/mozilla-mobile/focus-android/issues/6166 

<img src="https://user-images.githubusercontent.com/8118371/162430818-46307f9c-eaca-4786-aaf7-35e7559c4076.jpg" width="300" height="600" /> 

* Android device: all devices 
* Focus version: all versions

**Comment by amedyne** [comment]
Tagging @jeffreygee for input.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 102.0a1 build from 5/26 with Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).

![Screenshot_20220715-065410](https://user-images.githubusercontent.com/40694158/170488856-069c6841-9f44-436f-9c0e-d310b210f707.png)
