### ISSUE TITLE
Regression to cold start (main = 50ms, view = 20ms; around 5/10/22)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#7060]
Our nightly results show a regression in cold main start up on 5/10 of about 50ms:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/759372/169364586-12981b5f-0568-424f-bebc-6db374b1cbc5.png">

And a smaller, gradual increase in cold start view around the same time – somewhere between 5/10 and 5/15:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/759372/169363672-f1507a7b-1602-4d72-8b4a-7410ce0bd305.png">

The period before the large jump averages out to 1.92s (eyeballed) while we see 1.944s on 5/14: about a 20ms increase.

There is a temporary spike that starts earlier, on 5/2, that may also be related to the root cause of this regression.

**Comment by ionutbedregeanu** [comment]
I talked with the team to transfer me a device with a lower android version in order to catch the differences easily, so I will postpone this ticket until then. If someone else can help feel free to take the ticket

**Comment by iorgamgabriel** [comment]
@mcomella I was that this regression had a spike only between 05/01 and 05/16 after that it came back to normal . Do you think it is worth investigating? Thank you !

**Comment by iorgamgabriel** [comment]
<img src="https://user-images.githubusercontent.com/8118371/196446680-6ce1a54d-b81f-49cf-afa8-0a77caad1d47.png" width="300" height="600" />

**Comment by MarcLeclair** [comment]
Triage: Close since it does seems inactionable with the noise. The time was ~600-605ms before the regression on first frame and afterwards was ~630-650ms. It would be very difficult to find on a profile.
