### ISSUE TITLE
The Tabs exposure event is sent twice for the context menu displayed for images

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7067]
**[Affected Versions]**:
- Focus Nightly 102.0a1 (Build #361401126 GV: 102.0a1-20220519180318) AC: 102.0.20220519222019, c773d9b96, AS: 93.1.0

**[Affected Platforms]**:
- Android 9 - Samsung Galaxy S8

**[Prerequisites]**:
- Have a Focus for Android build with the following modifications:
     - The following lines added to local.properties:
     nimbus.remote-settings.url = https://settings.stage.mozaws.net
     debuggable = true
     - A new “.nimbus” file (in the same location as local.properties) containing the following line: https://settings.stage.mozaws.net
- Have a Focus for Android Nimbus experiment using the “tabs” feature launched to Stage (Stage Preview was used).

**[Steps to reproduce]**:
1. Open Focus and close it to avoid #6995.
2. Reopen the app using a [telemetry command](https://mozilla.github.io/glean/book/user/debugging/android.html) (e.g. adb shell am start -n org.mozilla.focus.nightly/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es sendPing events --es debugViewTag MH-1).
3. Navigate to a page containing images.
4. Long press an image to display its context menu.
5. Minimize the app and observe logcat.

**[Expected result]**:
- The exposure event is sent only once.

**[Actual result]**:
- The exposure event is sent twice for image context menus.

**[Notes]**:
- The issue is reproducible for both multi and single tab branches.
- This issue is not reproducible for link context menus.
- Attached is a recording of the issue.

https://user-images.githubusercontent.com/53752296/169553479-5a41c5cf-46c5-440e-b6d7-c2521b5b92a8.mov

**Comment by Mugurell** [comment]
Thank you for the report @heres-maria .
This is the expected behavior because for an image there are two possible menu options that both evaluate the multiple tabs experiment:
- the option to open the link for that image in a new tab,
- the option to open the image in a new tab.
