### ISSUE TITLE
[Intermittent] The old onboarding is displayed after the user restarts the app while the onboarding is displayed

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7069]
**[Affected Versions]**:
- Focus Nightly 102.0a1 (Build #361401126 GV: 102.0a1-20220519180318) AC: 102.0.20220519222019, c773d9b96, AS: 93.1.0
- Focus Nightly 102.0a1 (Build #361361204 GV: 102.0a1-20220513093538)

**[Affected Platforms]**:
- Android 9 - Samsung Galaxy S8

**[Prerequisites]**:
- Have a Focus for Android build with the following modifications:
      - The following lines added to local.properties:
     nimbus.remote-settings.url = https://settings.stage.mozaws.net
     debuggable = true
      - A new “.nimbus” file (in the same location as local.properties) containing the following line: https://settings.stage.mozaws.net/
- Have a Focus for Android Nimbus experiment using the onboarding feature which sets “is-enabled” to true launched to Stage Live.

**[Steps to reproduce]**:
1. Open Focus and close it to avoid #6995.
2. Open the app.
3. Close the app.
4. Reopen the app.
5. Repeat steps 3 and 4 several times.

**[Expected result]**:
- The new onboarding is displayed when reopening the app.

**[Actual result]**:
- The old onboarding is sometimes displayed when reopening the app.

**[Notes]**:
- The issue is **not** reproducible for Focus Nightly 102.0a1 (Build #361321114 GV: 102.0a1-20220511094252).
- The old onboarding is not displayed after restart if the new onboarding was previously dismissed.
- The issue does not seem reproducible for app minimization.
- Attached is a recording of the issue.

https://user-images.githubusercontent.com/53752296/169565450-7898b5c5-802a-440d-a894-ba416c1893d0.mov

**Comment by heres-maria** [comment]
@ionutbedregeanu Yes, it was reproducible for a fresh install for an experiment with the new onboarding enabled. It was intermittently reproducible for me, about 4/10 cases (restarts).

**Comment by ionutbedregeanu** [comment]
Still didn't succeed to reproduce it. I'm not sure if it's not reproducible anymore or I'm doing something wrong

**Comment by iorgamgabriel** [comment]
I can't reproduce it . Tried  with One Plus 7t Android 11 and Pixel3 XL Android 12

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible. The onboarding displayed no longer changes after some restarts. Tested using Focus Nightly 104.0a1 (Build #3618515210 GV 104.0a1-20220630095519) AC: 104.0.20220702143150, 9b36f91939, AS: 93.5.0 and Focus Beta 103.0 (Build #361861059) GV 103.0-20220703190044) AC: 103.0.3, 6d483337fa AS: 93.5.0 on Android 9 - Samsung Galaxy S8.
