### ISSUE TITLE
[l10n] About page is not localized when opened from menu button

### ISSUE THREAD

**Issue by mastizada** [mozilla-mobile/focus-android#707]
Switch to different language, close app. Open app and go to about from menu button - it will be in English.
Go to settings and open "About Firefox Focus" there - will be in selected language.
Again go back to default page, open about from menu button, it will be in localized version.
It will continue to appear in localized version until you close application from recent apps.

Moto Z Play, Android 7.0 (3.18.31), system lang: en, focus lang: az.

**Comment by pocmo** [comment]
This is intentional and the same in Firefox Focus for iOS. Anyways, I'm going to set the [needs triage] label to discuss this in our weekly meeting.

**Comment by mastizada** [comment]
After opening same page from Settings view, it also starts to appear in localized version even from home view (opening from menu button from main view). It continues to appear in localized version until you close app from task manager (recent apps). That is the weird part.

**Comment by pocmo** [comment]
Oh, sorry. I mixed up "Your Rights" and "About". You are right, "About" should always be translated.

**Comment by pocmo** [comment]
@mastizada What language is your system set to and what language is selected in the settings screen of Focus?

**Comment by mastizada** [comment]
System Language is English (en US), Focus language is Azerbaijani (az)

**Comment by pocmo** [comment]
I landed a fix for the about page but then I realized that there are even more situations where the locale is suddenly reset to the system locale. The browsing menu often uses the system language and after erasing the browsing history the start page is suddenly in the system language again too.

**Comment by pocmo** [comment]
Okay, now this should be fixed. Please open a new bug if you see things that are not localized after performing some specific steps. Thanks! :)
