### ISSUE TITLE
The app crashes if the screen orientation is changed after the app was minimized while a CFR was displayed

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7070]
**[Affected Versions]**:
- Focus Nightly 102.0a1 (Build #361401126 GV: 102.0a1-20220519180318) AC: 102.0.20220519222019, c773d9b96, AS: 93.1.0

**[Affected Platforms]**:
- Android 9 - Samsung Galaxy S8

**[Prerequisites]**:
- Have a Focus for Android build with the following modifications:
     - The following lines added to local.properties:
     Nimbus.remote-settings.url = https://settings.stage.mozaws.net/
     debuggable = true
     - A new “.nimbus” file (in the same location as local.properties) containing the following line:   https://settings.stage.mozaws.net
- Have a Focus for Android Nimbus experiment using the onboarding feature which sets “is-cfr-enabled” to true launched to Stage Live.

**[Steps to reproduce]**:
1. Open Focus and close it to avoid #6995.
2. Open the app.
3. Navigate to a page.
4. Minimize the app.
5. Refocus the app.
6. Change the orientation of the screen to landscape.

**[Expected result]**:
- The app does not crash.

**[Actual result]**:
- The app crashes.

**[Notes]**:
- The issue is also reproducible for the trash can icon CFR.
- The issue is not reproducible for the CFR displayed in the Settings menu.
- Attached is a recording of the issue.

https://user-images.githubusercontent.com/53752296/169567338-6f34cd37-c73f-46cd-989f-f81e2cccfb46.mov

**Comment by iorgamgabriel** [comment]
Looks like a Gecko bug . I've opened a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1771142) for tracking the issue in Bugzilla.
https://bugzilla.mozilla.org/show_bug.cgi?id=1771142

**Comment by ionutbedregeanu** [comment]
Close this ticket in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1771142
