### ISSUE TITLE
Collect telemetry on how Focus was started and n which state it way

### ISSUE THREAD

**Issue by rtestard** [mozilla-mobile/focus-android#7079]
### Why/User Benefit/User Problem
- Better understand how users launch Focus in order to better the application for user workflows
- Quantify the value of being the default browser and having home screen shortcuts to help prioritize custom onboarding for set to default

### What / Requirements
- Implement a probe that is similar to the Fenix probe detailed on https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/perf_startup_startup_type

See glossay under https://wiki.mozilla.org/Performance/Fenix#Glossary for definitions of path and state

### Acceptance Criteria (how do I know when I’m done?)
- Every time a user accesses Focus, a telemetry counter is incremented under the right state_path bucket used to open Focus (cold_main, cold_unknown, cold_view, hot_main, hot_unknown, hot_view, warm_main, warn_unknown, warm_view, unknown_main, unknown_unknown, unknown_view)
- Glean is used to collect the telemetry

**Comment by iorgamgabriel** [comment]
Hello @rtestard we have some Metrics for : 
-app_opened  https://dictionary.telemetry.mozilla.org/apps/focus_android?page=1&search=app_opened 
-shortcuts https://dictionary.telemetry.mozilla.org/apps/focus_android?page=1&search=shortcuts
-default_browser https://dictionary.telemetry.mozilla.org/apps/focus_android?page=1&search=default_browser
Is this enough ? Do I need to add more ?
Thank you very much !

**Comment by Mugurell** [comment]
Based on the proposed mappings it looks like Focus would need to add the same probes as in https://github.com/mozilla-mobile/fenix/pull/19028/files.
Because of the relative high complexity it seems like we should try to borrow the same exact code with only minor alterations (Tests will have to be refactored to use `mockito` instead of `mockk`).

Just thinking on whether we can share this in all products from A-C instead of copying and maintaining the same code in multiple projects.
Seeing [here](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/perf_startup_startup_type) a mention about `Widget text search: *_unknown` and with Focus not having a widget I'm not sure about if one A-C implementation can fit all projects.
@mcomella Any suggestions?

**Comment by mcomella** [comment]
From my brief look, I don't see any code that is specific to fenix so I think it's possible to pull it into android-components. However, this code is really complex so I can't say for sure.

This is probably obvious but I just want to be explicit – if you don't need all of the state we're collecting for Focus, we'd benefit from minimizing what we collect: it's easier to implement and less likely to be incorrect.

> Seeing [here](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/perf_startup_startup_type) a mention about Widget text search: *_unknown and with Focus not having a widget I'm not sure about if one A-C implementation can fit all projects.

This shouldn't matter: I tested all of the ways to open the app to see what the telemetry collected and this is what the widget code path returned. We didn't add any code to specifically handle the widget case.

**Comment by lobontiumira** [comment]
Hi all!
I've verified on the latest Focus Nightly 103.0a1 build from 6/22 with Google Pixel (Android 10), and here are my findings.
I've opened the app in the following ways:
* by tapping the Focus nightly app,
* by sharing a page from a different app,
* by tapping on the "Open" option from the notification bar,
* by long-tapping on the Focus Nightly icon and selecting "Erase & open",
* by selecting "Open in Focus Nightly" from a custom tab from Gmail.

The metrics can be seen here - [Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/test-000001)

![startup_type](https://user-images.githubusercontent.com/40694158/175036667-a46a838e-7ecc-41b7-830d-064bf37ad771.jpg)

@iorgamgabriel please review and let me know if there is any other scenario to test.
Thank you!
