### ISSUE TITLE
The Display components, and App Services versions on the About page should be centered

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7081]
## Steps to reproduce
1. Go to Settings - About, and observe the build, AC, and AS versions.

### Expected behavior
The details are cenntered, like on Fenix.

### Actual behavior
The details are aligned to the left.

### Device information
* Android device: all
* Focus version: Focus Nightly 102.0a1 from 5/23

![Untitled](https://user-images.githubusercontent.com/40694158/169813750-46a8d2e2-696e-4c1d-a77c-eea8dd457358.png)

**Comment by ionutbedregeanu** [comment]
@lobontiumira I'm not sure if the UX wants this content aligned to center. @jeffreygee What do you think about that?

**Comment by jeffreygee** [comment]
@ionutbedregeanu @lobontiumira I think it's fine as is for now. We can discuss if we want to follow a similar template to Fenix though overall with the sections, etc.
