### ISSUE TITLE
The onboarding exposure event is sent twice at onboarding startups for “is-cfr-enabled” and “is-enabled” both set to true

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7085]
**[Affected Versions]**:
- Focus Nightly 102.0a1 (Build #361431118 GV: 102.0a1-20220522094633) AC:102.0.20220522143114, edac10adc1, AS: 93.1.0

**[Affected Platforms]**:
- Android 9 - Samsung Galaxy S8

**[Prerequisites]**:
- Have a Focus for Android build with the following modifications:
     - The following lines added to local.properties:
     nimbus.remote-settings.url = https://settings.stage.mozaws.net
     debuggable = true
     - A new “.nimbus” file (in the same location as local.properties) containing the following line: https://settings.stage.mozaws.net/
- Have a Focus for Android Nimbus experiment using the onboarding feature which sets both “is-enabled” and “is-cfr-enabled” to true.
- Have a way to observe Logcat (the Android Studio viewer was used for testing).

**[Steps to reproduce]**:
1. Open Focus and close it to avoid #6995.
2. Reopen the app using a [telemetry command](https://mozilla.github.io/glean/book/user/debugging/android.html) (e.g. adb shell am start -n org.mozilla.focus.nightly/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es sendPing events --es debugViewTag MH-1).
3. Minimize the app and observe Logcat.

**[Expected result]**:
-  The exposure event is recorded once.

**[Actual result]**:
- The exposure event is recorded once at step 2 and once at step 3.

**[Notes]**:
- The issue was not reproducible with branches with “is-cfr-enabled” true and “is-enabled” false, “is-cfr-enabled” false and “is-enabled” false or “is-cfr-enabled” false and “is-enabled” true.
- Attached is a recording of the issue.

https://user-images.githubusercontent.com/53752296/169818673-c7b3c57f-a359-4894-81a9-4b185a01adb9.mov

**Comment by ionutbedregeanu** [comment]
This should be also fixed by https://github.com/mozilla-mobile/focus-android/pull/7124

**Comment by heres-maria** [comment]
The issue is no longer reproducible. The exposure event was only sent once. Tested using Focus Nightly 103.0a1 (Build #361511109GV: 103.0a1-20220530140717) AC:103.0.20220530190102, 5888c2c465e, AS: 93.1.0.
