### ISSUE TITLE
The exposure event is not sent at app minimization for experiments with “is-enabled” set to false

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7087]
**[Affected Versions]**:
- Focus Nightly 102.0a1 (Build #361431118 GV: 102.0a1-20220522094633) AC:102.0.20220522143114, edac10adc1, AS: 93.1.0

**[Affected Platforms]**:
- Android 9 - Samsung Galaxy S8

**[Prerequisites]**:
- Have a Focus for Android build with the following modifications:
     - The following lines added to local.properties:
     nimbus.remote-settings.url = https://settings.stage.mozaws.net
     debuggable = true
     - A new “.nimbus” file (in the same location as local.properties) containing the following line: https://settings.stage.mozaws.net/
- Have a Focus for Android Nimbus experiment using the onboarding feature with “is-enabled” set to false and “is-cfr-enabled” set to true.
- Have a way to observe Logcat (the Android Studio viewer was used for testing).

**[Steps to reproduce]**:
1. Open Focus to enroll into the experiment from prerequisites. 
2. Close the app to avoid #6995.
3. Reopen the app using a [telemetry command](https://mozilla.github.io/glean/book/user/debugging/android.html) (e.g. adb shell am start -n org.mozilla.focus.nightly/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es sendPing events --es debugViewTag MH-1).
4. Minimize the app, refocus it, and observe Logcat.
5. Repeat step 4 a few times.

**[Expected result]**:
-  The exposure event is recorded when the app is minimized and refocused.

**[Actual result]**:
- The exposure event is not recorded when the app is minimized and refocused.

**[Notes]**:
- The exposure event is recorded for startups where the onboarding is displayed for this configuration.
- The issue is also reproducible for experiments with both “is-enabled” and “is-cfr-enabled” set to false (together with #7083).
- The issue is not reproducible for experiments with both “is-enabled” and “is-cfr-enabled” set to true or “is-enabled set to true” and “is-cfr-enabled” set to false.
- Attached is a recording of the issue.

https://user-images.githubusercontent.com/53752296/169822417-64e2ddeb-b183-45d4-85e5-c7392357741f.mov

**Comment by ionutbedregeanu** [comment]
This is expected behaviour. Were some inconsistencies because the exposure was recorded at browser store build, but now should be ok
