### ISSUE TITLE
Support for partner distributions

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#709]
[scope to be defined]

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support partner distributions](https://trello.com/c/iXWcNg4u/44-support-partner-distributions)

**Comment by bbinto** [comment]
Some possible asks

- Being able to set vendor as Focus/Klar default search option
- "Open With" to have partner's browser as the default option
- Partner defined search codes

**Comment by bbinto** [comment]
covered in #1422 - #1425
