### ISSUE TITLE
Intermittent UI test failure - < SafeBrowsingTest.verifyPageSecurityIconAndInfo>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7095]
### Stacktrace:
05-23 20:11:06.951: I/WindowManager(458): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: dc38b89 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5003ms for FocusEvent(hasFocus=false)
05-23 20:11:06.936: I/chatty(1914): uid=1041(audioserver) writer identical 76 lines
05-23 20:11:06.951: W/audio_hw_generic(1914): Hardware backing HAL too slow, could only write 0 of 661 frames
05-23 20:11:06.959: E/QueryController(13977): Got null root node from accessibility - Retrying...
05-23 20:11:06.966: W/audio_hw_generic(1914): Hardware backing HAL too slow, could only write 0 of 661 frames
05-23 20:11:07.046: I/ActivityManager(458): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
05-23 20:11:07.047: I/ActivityManager(458): Killing 14424:org.mozilla.focus.debug:tab0/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-23 20:11:07.047: I/ActivityManager(458): Killing 13977:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-23 20:11:07.049: W/ActivityTaskManager(458): Force removing ActivityRecord{1aaa8a0 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
05-23 20:11:07.026: I/chatty(1914): uid=1041(audioserver) writer identical 4 lines
05-23 20:11:07.041: W/audio_hw_generic(1914): Hardware backing HAL too slow, could only write 0 of 661 frames
05-23 20:11:07.055: I/ServiceChildProcess(14530): Destroying GeckoServiceChildProcess
05-23 20:11:07.056: W/audio_hw_generic(1914): Hardware backing HAL too slow, could only write 0 of 661 frames
05-23 20:11:07.057: W/Binder(13907): Caught a RuntimeException from the binder stub implementation.
05-23 20:11:07.057: W/Binder(13907): java.lang.SecurityException: Calling from not trusted UID!
05-23 20:11:07.057: W/Binder(13907): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
05-23 20:11:07.057: W/Binder(13907): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
05-23 20:11:07.057: W/Binder(13907): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
05-23 20:11:07.057: W/Binder(13907): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-23 20:11:07.057: W/Binder(13907): 	at android.os.Binder.execTransact(Binder.java:1123)
05-23 20:11:07.060: I/ActivityManager(458): Killing 14530:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-23 20:11:07.065: I/ActivityManager(458): Killing 12743:com.google.android.calendar/u0a105 (adj 985): empty #17
05-23 20:11:07.065: D/WindowManager(458): notifyANR took 121ms
### Notes: Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
