### ISSUE TITLE
[Android 5] Focus crashes when camera is allowed on Xiaomi mi4i

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7096]
## Steps to reproduce
1. Go to https://mozilla.github.io/webrtc-landing/gum_test.html.
2. Tap on Camera & microphone button.
3. The "Allow the site to use your camera and microphone?" prompt is displayed. Select "Allow".

### Expected behavior
The video starts.

### Actual behavior
Focus crashes.

### Device information
* Android device: Xiaomi mi4i (Android 5.0.2)
* NOT reproducible on Samsung Galaxy Tab A6 (Android 5.1.1), nor on Lenovo Tablet M10 (Android 10), Oppo Reno 6 (Android 12)
* Focus versions: RC 101.1.0, Beta 101.0.0-beta.6, and Focus Nightly 102.0a1 (build 361440509, GV 102.0a1-20220523095244)
* Fenix Nightly 102.0a1 (build 2015882281), AC 102.0.20220524015637
* [Logcat ](https://github.com/mozilla-mobile/focus-android/files/8762435/logcat.txt)
* Crash details: https://crash-stats.mozilla.org/report/index/afb8b7ee-c691-4991-a76c-236590220524
* Short video:

https://user-images.githubusercontent.com/40694158/170031788-48d77d44-16da-4cc5-980a-20f106bf7923.mp4

**Comment by lobontiumira** [comment]
@amedyne I don't have an iOS device to test.

**Comment by lobontiumira** [comment]
I investigated a little more on this crash, and it seems this crash is reproducing on the Xiaomi device from the implementation of the camera permissions on Focus Nightly, the build from 4/6 (build 360961708 with GV 101.0a1-20220405094056).

**Comment by lobontiumira** [comment]
I've found [#15316](https://github.com/mozilla-mobile/fenix/issues/15316) from Fenix repo.

**Comment by lobontiumira** [comment]
Reproducible on the same Xiaomi mi4i (Android 5.0.2) device on Beta 102.0.0-beta.5.

**Comment by lobontiumira** [comment]
Reproducible on the same Xiaomi mi4i (Android 5.0.2) device on Beta 103.0.0-beta.1.

**Comment by Mugurell** [comment]
Waiting for a resolution from GV - https://bugzilla.mozilla.org/show_bug.cgi?id=1770940

**Comment by lobontiumira** [comment]
Reproducible on the same Xiaomi mi4i (Android 5.0.2) device on RC 102.2.0.

**Comment by lobontiumira** [comment]
Reproducible with the Xiaomi mi4i (Android 5.0.2) device, on the Beta 104.0b1 build.

**Comment by lobontiumira** [comment]
Reproducible with the Xiaomi mi4i (Android 5.0.2) device, on the Beta 105.0b4 build.

**Comment by lobontiumira** [comment]
Reproducible with the Xiaomi mi4i (Android 5.0.2) device, on the Beta 105.0b5 build.

**Comment by lobontiumira** [comment]
Reproducible on the latest Beta 105.0b6 build, and RC 104.2.0 with the same Xiaomi mi4i (Android 5.0.2) device.

**Comment by lobontiumira** [comment]
Reproducible on the latest RC 105.1.0 build 2 with the same Xiaomi mi4i (Android 5.0.2) device.

**Comment by lobontiumira** [comment]
Verified as fixed on Focus Nightly 108.0a1 with Xiaomi mi4i (Android 5.0.2).
Still reproducible on Beta 107.0b1 with the same device.

**Comment by lobontiumira** [comment]
Verified as fixed on the Beta 107.0b2 build with Xiaomi mi4i (Android 5.0.2).
