### ISSUE TITLE
Figure out how to build 'Klar'

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#71]
We need a separate build for German stores.

- [x] Separate build configuration
- [x] Create a strings.xml overlay
- [x] Create drawable overlays
- [x] Use completely different package id (org.mozilla.klar)

**Comment by pocmo** [comment]
Google Play's "Multi APK" feature does not allow filtering based on country. This means we'd have to create and upload a completely separate app.

**Comment by pocmo** [comment]
@antlam Can you send me or attach the wordmark for "Firefox Klar" (start screen)?

**Comment by antlam** [comment]
![img_klar_wordmark 3x](https://cloud.githubusercontent.com/assets/1994820/23086210/a3c9d758-f520-11e6-8458-2ce530c0ce66.png)

Heres the asset we used for iOS. We might need to massage this for Android though.

**Comment by pocmo** [comment]
@antlam Do you have the other sizes too? For Focus we have a wordmark with heights: 75 (xxhdpi), 50 (xhdpi), 25 (mdpi).

**Comment by antlam** [comment]
@pocmo in my design file this is 36 height for MDPI. Then I centered this horizontally and the padding from the top of the URL bar is 36dp.

So I've scaled it up to XHDPI and XXHDPI. Try these!

[focus_wordmark.zip](https://github.com/mozilla-mobile/focus-android/files/805774/focus_wordmark.zip)

**Comment by antlam** [comment]
![screen shot 2017-03-02 at 11 29 24 am](https://cloud.githubusercontent.com/assets/1994820/23523531/2b8548d8-ff3c-11e6-9eb8-731d80f5089f.png)

[focus_wordmark2.zip](https://github.com/mozilla-mobile/focus-android/files/814890/focus_wordmark2.zip)

Updated!
