### ISSUE TITLE
Standardize the removal of unused strings process

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#7108]
[strings.xml](https://github.com/mozilla-mobile/focus-android/blob/4a4eaba43d61ed6413b37225d2a92c622a102a4b/app/src/main/res/values/strings.xml) currently contain some unused strings.

Focus should standardize the process of removing all strings left unused after each new release.

&nbsp;
Tasks:
- [x] Add a new wiki page similar to [the one from Fenix](https://github.com/mozilla-mobile/fenix/wiki/Removing-strings) for detailing the process 
- [x] Remove all strings marked for removal in at most `99` to serve as a baseline from here on out.

**Comment by ionutbedregeanu** [comment]
Wiki added https://github.com/mozilla-mobile/focus-android/wiki/Removing-strings
