### ISSUE TITLE
Image search via gallery when access to camera is denied does not work at bing.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#7109]
## Steps to reproduce
1. Navigate to: https://www.bing.com/camera?ptn=Homepage&rtpu=%2F%3Fscope%3Dimages%26nr%3D1%26FORM%3DNOFORM.
2. Deny camera access when prompted.
3. Tap on the "Gallery" button.
4. Observe the result.

### Expected behavior
The internal storage options of the devices are opened.
### Actual behavior
Nothing happens.
### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
                           Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)
* Focus version: Firefox Focus Nightly 102.0a1 (361450509-🦎102.0a1-202205023095244🦎)

**Notes:**
1. Reproducible on the latest build of Firefox Focus Release and Nightly.
2. Not reproducible on the latest build of Firefox Fenix Nightly.
3. Not reproducible in "Private mode" using Firefox Fenix Nightly.
4. Originally reported here:
5. The issue reproduces intermittently.

**Comment by ionutbedregeanu** [comment]
@amedyne @jeff At this moment Focus doesn't support storage site permissions. Do we consider to implement this?

**Comment by ionutbedregeanu** [comment]
Fixed by https://github.com/mozilla-mobile/focus-android/pull/7310

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 104.0a1 (build 361831708 with GV 104.0a1-20220630095519) with the following devices:
* Samsung Galaxy note 8 (Android 9), and
* Oppo Reno 6 (Android 12).
