### ISSUE TITLE
Intermittent UI test failure - < WebControlsTest.verifySelectTextTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7116]
### Stacktrace:
05-25 13:15:54.970: W/droid.apps.doc(12366): --------- beginning of crash
05-25 13:15:54.977: E/AndroidRuntime(1932): FATAL EXCEPTION: launcher-loader
05-25 13:15:54.977: E/AndroidRuntime(1932): Process: com.android.launcher3, PID: 1932
05-25 13:15:54.977: E/AndroidRuntime(1932): java.lang.RuntimeException: item: WorkspaceItemInfo(id=9 type=APP container=5 targetComponent=ComponentInfo{com.google.android.apps.maps/com.google.android.maps.MapsActivity} screen=0 cell(0,1) span(1,1) minSpan(1,1) rank=3 user=UserHandle{0} title=Maps)modelItem: WorkspaceItemInfo(id=9 type=APP container=5 targetComponent=ComponentInfo{com.google.android.apps.maps/com.google.android.maps.MapsActivity} screen=0 cell(0,1) span(1,1) minSpan(1,1) rank=3 user=UserHandle{0} title=Maps)Error: ItemInfo passed to checkItemInfo doesn't match original
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.launcher3.model.ModelWriter$UpdateItemBaseRunnable.<init>(ModelWriter.java:419)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.launcher3.model.ModelWriter$UpdateItemsRunnable.<init>(ModelWriter.java:388)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.launcher3.model.ModelWriter.moveItemsInDatabase(ModelWriter.java:187)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.launcher3.folder.Folder.updateItemLocationsInDatabaseBatch(Folder.java:1000)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.launcher3.folder.Folder.bind(Folder.java:422)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.launcher3.folder.FolderIcon.inflateFolderAndIcon(FolderIcon.java:174)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.launcher3.Launcher.bindItems(Launcher.java:2100)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.lambda$bindWorkspaceItems$5(BaseLoaderResults.java:241)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.launcher3.model.-$$Lambda$BaseLoaderResults$WorkspaceBinder$u3fVFEA_dzybIfdOdmLuq72EG4o.execute(Unknown Source:6)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.lambda$executeCallbacksTask$8$BaseLoaderResults$WorkspaceBinder(BaseLoaderResults.java:267)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.launcher3.model.-$$Lambda$BaseLoaderResults$WorkspaceBinder$DoJdszY9e4_DUwoU7ASsVyUHvxU.run(Unknown Source:4)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at android.os.Handler.handleCallback(Handler.java:938)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at android.os.Looper.loop(Looper.java:223)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at java.lang.reflect.Method.invoke(Native Method)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-25 13:15:54.977: E/AndroidRuntime(1932): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-25 13:15:54.981: W/ActivityTaskManager(482):   Not force finishing home activity com.android.launcher3/com.android.searchlauncher.SearchLauncher
05-25 13:15:54.981: I/Process(1932): Sending signal. PID: 1932 SIG: 9
05-25 13:15:54.985: I/DropBoxManagerService(482): add tag=system_app_crash isTagEnabled=true flags=0x2
05-25 13:15:54.986: W/LocationOracle(10569): No location history returned by ContextManager
05-25 13:15:54.986: W/LocationOracle(10569): No location returned by GMS core getLastLocation()
05-25 13:15:54.986: W/LocationOracle(10569): No location history returned by ContextManager
05-25 13:15:54.986: W/LocationOracle(10569): No location returned by GMS core getLastLocation()
05-25 13:15:54.988: W/earchbox:searc(10569): Long monitor contention with owner Blocking Thread #21 (11655) at void com.google.android.apps.gsa.l.d.a(com.google.android.apps.gsa.l.c)(SourceFile:20) waiters=3 in void com.google.android.apps.gsa.l.d.a(com.google.android.apps.gsa.l.c) for 1.164s
05-25 13:15:55.002: W/BroadcastQueue(482): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-25 13:15:55.002: W/BroadcastQueue(482): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-25 13:15:55.010: I/PairHttpConnection(10569): [Download] starting read
### Notes: ❗ Similar with #7103

**Comment by AndiAJ** [comment]
Flaky 1x on 6/11 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8844915779908086916/executions/bs.af1848b814d07355/testcases/1/test-cases)

06-11 08:23:38.657: I/droid.apps.doc(12527): --------- beginning of crash
06-11 08:23:38.672: E/AndroidRuntime(1961): FATAL EXCEPTION: launcher-loader
06-11 08:23:38.672: E/AndroidRuntime(1961): Process: com.android.launcher3, PID: 1961
06-11 08:23:38.672: E/AndroidRuntime(1961): java.lang.RuntimeException: item: WorkspaceItemInfo(id=9 type=APP container=5 targetComponent=ComponentInfo{com.google.android.apps.maps/com.google.android.maps.MapsActivity} screen=0 cell(0,1) span(1,1) minSpan(1,1) rank=3 user=UserHandle{0} title=Maps)modelItem: WorkspaceItemInfo(id=9 type=APP container=5 targetComponent=ComponentInfo{com.google.android.apps.maps/com.google.android.maps.MapsActivity} screen=0 cell(0,1) span(1,1) minSpan(1,1) rank=3 user=UserHandle{0} title=Maps)Error: ItemInfo passed to checkItemInfo doesn't match original
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.launcher3.model.ModelWriter$UpdateItemBaseRunnable.<init>(ModelWriter.java:419)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.launcher3.model.ModelWriter$UpdateItemsRunnable.<init>(ModelWriter.java:388)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.launcher3.model.ModelWriter.moveItemsInDatabase(ModelWriter.java:187)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.launcher3.folder.Folder.updateItemLocationsInDatabaseBatch(Folder.java:1000)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.launcher3.folder.Folder.bind(Folder.java:422)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.launcher3.folder.FolderIcon.inflateFolderAndIcon(FolderIcon.java:174)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.launcher3.Launcher.bindItems(Launcher.java:2100)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.lambda$bindWorkspaceItems$5(BaseLoaderResults.java:241)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.launcher3.model.-$$Lambda$BaseLoaderResults$WorkspaceBinder$u3fVFEA_dzybIfdOdmLuq72EG4o.execute(Unknown Source:6)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.lambda$executeCallbacksTask$8$BaseLoaderResults$WorkspaceBinder(BaseLoaderResults.java:267)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.launcher3.model.-$$Lambda$BaseLoaderResults$WorkspaceBinder$DoJdszY9e4_DUwoU7ASsVyUHvxU.run(Unknown Source:4)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at android.os.Handler.handleCallback(Handler.java:938)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at android.os.Looper.loop(Looper.java:223)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at java.lang.reflect.Method.invoke(Native Method)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-11 08:23:38.672: E/AndroidRuntime(1961): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-11 08:23:38.663: I/droid.apps.doc(12527): The ClassLoaderContext is a special shared library.
06-11 08:23:38.675: I/PeopleGalProvider(10040): Gal directories started.
06-11 08:23:38.676: I/PeopleGalProvider(10040): Gal directories started.
06-11 08:23:38.679: I/PeopleGalProvider(10040): Method 1 completed.
06-11 08:23:38.679: I/PeopleGalProvider(10040): Method 1 finished successfully.
06-11 08:23:38.682: I/ContactDirectoryManager(12377): deleted 0 stale rows which don't have any relevant directory
06-11 08:23:38.682: I/ContactDirectoryManager(12377): Discovered 0 contact directories in 705ms
06-11 08:23:38.684: I/ContactsProvider(12377): Locale has changed from [en_US] to [en]
06-11 08:23:38.686: I/ContactsDatabaseHelper(12377): Switching to locale [en] (ICU v66.1.0.0)
06-11 08:23:38.691: D/nativeloader(12527): classloader namespace configured for unbundled product apk. library_path=/product/app/Drive/lib/x86:/product/app/Drive/Drive.apk!/lib/x86:/product/lib:/system/product/lib
06-11 08:23:38.696: I/PeopleGalProvider(10040): Method 1 completed.
06-11 08:23:38.696: I/PeopleGalProvider(10040): Method 1 finished successfully.
06-11 08:23:38.704: D/NetworkSecurityConfig(12527): Using Network Security Config from resource network_security_config debugBuild: false
06-11 08:23:38.705: D/NetworkSecurityConfig(12527): Using Network Security Config from resource network_security_config debugBuild: false
06-11 08:23:38.731: W/ogle.android.g(12475): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
06-11 08:23:38.731: W/ogle.android.g(12475): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
06-11 08:23:38.754: W/ogle.android.g(12475): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
06-11 08:23:38.792: W/droid.apps.doc(12527): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
06-11 08:23:38.793: W/droid.apps.doc(12527): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
06-11 08:23:38.793: W/droid.apps.doc(12527): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
06-11 08:23:38.833: D/BluetoothPbapService(1594):  onChange on contact uri 
06-11 08:23:38.855: W/GAV2(12475): Thread[main,5,main]: Need to call initialize() and be in fallback mode to start dispatch.
06-11 08:23:38.893: D/app_process(12468): Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
06-11 08:23:38.893: D/app_process(12468): I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
06-11 08:23:38.905: W/app_process(12468): Unexpected CPU variant for X86 using defaults: x86
06-11 08:23:38.551: W/app_process(12468): type=1400 audit(0.0:307): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=7620 scontext=u:r:shell:s0 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0
06-11 08:23:39.005: I/app_process(12468): The ClassLoaderContext is a special shared library.
06-11 08:23:39.046: E/MmTelFeatureConnection [0](1783): ImsRegistrationCallbackAdapter: ImsRegistration is null
06-11 08:23:39.108: W/Gmail(12475): AccountUtils:For b/73513912, load account content://com.google.android.gm.sapi/account.-2137146394 from MailAppProvider. Is account valid result: 1.
06-11 08:23:39.124: W/Gmail(12475): AccountUtils:For b/73513912, load account content://com.google.android.gm.email.provider/account.-437561172?suppress_combined%3Dtrue from MailAppProvider. Is account valid result: 1.
06-11 08:23:39.160: I/DropBoxManagerService(486): add tag=system_app_crash isTagEnabled=true flags=0x2
06-11 08:23:39.169: W/app_process(12468): JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
06-11 08:23:39.172: W/ActivityTaskManager(486):   Not force finishing home activity com.android.launcher3/com.android.searchlauncher.SearchLauncher
06-11 08:23:39.185: I/GAv4(12527): Google Analytics 202.4.12 is starting up. To enable debug logging on a device run:
06-11 08:23:39.185: I/GAv4(12527):   adb shell setprop log.tag.GAv4 DEBUG
06-11 08:23:39.185: I/GAv4(12527):   adb logcat -s GAv4
06-11 08:23:39.201: I/Process(1961): Sending signal. PID: 1961 SIG: 9
06-11 08:23:39.215: W/BroadcastQueue(486): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-11 08:23:39.215: W/BroadcastQueue(486): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-11 08:23:39.237: D/AndroidRuntime(12468): Calling main entry com.android.commands.input.Input
06-11 08:23:39.250: I/Finsky(8842): [674] lrn.l(1): Account name null when calculating account hash
06-11 08:23:39.267: W/GAv4(12527): CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
06-11 08:23:39.279: D/BluetoothPbapUtils(1594): primaryVersionCounter = 0, secondaryVersionCounter=0
06-11 08:23:39.290: E/NotificationAccessor(12527): Cannot delete notification channel. Channel not found.
06-11 08:23:39.301: V/DisplayPowerController(486): Brightness [0.39763778] reason changing to: 'manual', previous reason: 'manual [ dim ]'.
06-11 08:23:39.290: I/chatty(12527): uid=10108(com.google.android.apps.docs) identical 1 line
06-11 08:23:39.290: E/NotificationAccessor(12527): Cannot delete notification channel. Channel not found.
06-11 08:23:39.314: D/AndroidRuntime(12468): Shutting down VM

**Comment by sv-ohorvath** [comment]
Not sure if the above stacktrace is relevant if the test still continued to run after.
The last step of the test was performed and then gecko probably stopped responding?

Logs:
06-11 08:28:56.652: I/QueryController(14417): Matched selector: UiSelector[CONTAINS_TEXT=You entered: Copy] <<==>> [android.view.accessibility.AccessibilityNodeInfo@6ae06; boundsInParent: Rect(22, 687 - 373, 739); boundsInScreen: Rect(22, 907 - 373, 959); packageName: org.mozilla.focus.debug; className: android.view.View; text: You entered: Copy; error: null; maxTextLength: -1; stateDescription: null; contentDescription: ; tooltipText: null; viewIdResName: ; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; importantForAccessibility: false; visible: true; actions: [AccessibilityAction: ACTION_NEXT_HTML_ELEMENT - null, AccessibilityAction: ACTION_PREVIOUS_HTML_ELEMENT - null, AccessibilityAction: ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY - null, AccessibilityAction: ACTION_NEXT_AT_MOVEMENT_GRANULARITY - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null]]
06-11 08:28:56.663: W/audio_hw_generic(1869): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:28:56.723: I/chatty(1869): uid=1041(audioserver) writer identical 4 lines
06-11 08:28:56.738: W/audio_hw_generic(1869): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:28:56.746: D/LifecycleMonitor(14417): Lifecycle status change: org.mozilla.focus.activity.MainActivity@92bd656 in: PAUSED
06-11 08:28:56.756: W/audio_hw_generic(1869): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:28:56.760: D/GeckoViewModule(14417): dispatch GeckoView:WebExtension:SetTabActive, data={"active":false}
06-11 08:28:56.760: D/GeckoViewTab(14417): onEvent: event=GeckoView:WebExtension:SetTabActive, data={"active":false}
06-11 08:28:56.771: W/audio_hw_generic(1869): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:28:56.777: I/BackdropActivity(12672): onResume()
06-11 08:28:56.779: D/WebExtensionsMiddleware(14417): No engine session for new active tab (null)
06-11 08:28:56.783: I/ActivityTaskManager(486): Activity requesting to dismiss Keyguard: ActivityRecord{676bd13 u0 com.google.android.apps.mtaas.backdrop/.BackdropActivity t8}
06-11 08:28:56.786: W/audio_hw_generic(1869): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:28:56.789: D/GeckoViewContent(14417): handleEvent: DOMWindowClose
06-11 08:28:56.792: D/GeckoViewNavigation(14417): onDisable
06-11 08:28:56.792: D/GeckoViewProcessHangMonitor(14417): onDisable
06-11 08:28:56.792: D/GeckoViewModule(14417): unregisterListener
06-11 08:28:56.792: D/GeckoViewProcessHangMonitor(14417): onDestroy
06-11 08:28:56.793: D/GeckoViewProgress(14417): onDisable
06-11 08:28:56.793: D/GeckoViewModule(14417): unregisterListener
06-11 08:28:56.793: D/GeckoViewSelectionAction(14417): onDisable
06-11 08:28:56.793: D/GeckoViewModule(14417): unregisterListener
06-11 08:28:56.793: D/GeckoViewModule(14417): unregisterListener
06-11 08:28:56.794: D/GeckoViewMediaControl(14417): onDisable
06-11 08:28:56.794: D/GeckoViewModule(14417): unregisterListener
06-11 08:28:56.799: D/GeckoViewSelectionActionDelegate[C](14893): handleEvent: visibilitychange
............................
06-11 08:28:57.754: V/MediaRouter(1610): Selecting route: RouteInfo{ name=‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‏‏‏‏‏‏‏‏‏‏‎‏‏‏‎‏‎‎‎‏‎‏‏‏‎‏‏‎‎‏‏‏‏‏‏‎‏‎‎‏‏‎‏‏‎‏‎‏‏‏‏‎‎‎‎‎‎‏‏‎‏‎‎‏‎Phone‎‏‎‎‏‎, description=null, status=null, category=RouteCategory{ name=‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‏‏‎‎‏‎‎‎‏‎‏‏‏‏‏‎‎‏‏‎‎‏‏‏‎‎‎‏‏‏‏‎‎‎‏‏‎‏‎‏‎‏‏‎‎‎‏‎‎‎‎‎‏‏‏‎‎‏‎‏‎‎‏‏‎System‎‏‎‎‏‎ types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
06-11 08:28:57.754: I/GenericSource(411): start
06-11 08:28:57.759: D/CCodec(411): allocate(c2.android.vorbis.decoder)
06-11 08:28:57.760: V/C2Store(423): in init
06-11 08:28:57.760: V/C2Store(423): loading dll
06-11 08:28:57.760: W/audio_hw_generic(1869): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:28:57.762: I/CCodec(411): Created component [c2.android.vorbis.decoder]
06-11 08:28:57.762: D/CCodecConfig(411): read media type: audio/vorbis
06-11 08:28:57.763: D/ReflectedParamUpdater(411): extent() != 1 for single value type: algo.buffers.max-count.values
.....................................
06-11 08:28:57.775: W/audio_hw_generic(1869): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:28:57.782: E/FMQ(423): grantorIdx must be less than 3
06-11 08:28:57.782: E/FMQ(411): grantorIdx must be less than 3
06-11 08:28:57.786: D/AudioFlinger(1866): Client defaulted notificationFrames to 12064 for frameCount 24129
06-11 08:28:57.789: D/AF::TrackHandle(1866): OpPlayAudio: track:61 usage:5 not muted
06-11 08:28:57.791: W/audio_hw_generic(1869): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:28:57.793: D/AudioTrack(411): getTimestamp_l(14): device stall time corrected using current time 17553669044406
06-11 08:28:57.794: I/system_server(486): oneway function results will be dropped but finished with status OK and parcel size 4
....................................................
06-11 08:28:58.240: I/chatty(1869): uid=1041(audioserver) writer identical 29 lines
06-11 08:28:58.255: W/audio_hw_generic(1869): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:28:58.264: I/PlayCommon(13468): [973] atno.h(22): Preparing logs for uploading
06-11 08:28:58.265: I/PlayCommon(13468): [973] atno.h(132): Connecting to server for timestamp: https://play.googleapis.com/play/log/timestamp
06-11 08:28:58.271: W/audio_hw_generic(1869): Hardware backing HAL too slow, could only write 0 of 661 frames
........................................
06-11 08:29:00.718: D/CompatibilityChangeReporter(486): Compat change id reported: 135634846; UID 10152; state: DISABLED
06-11 08:29:00.719: D/CompatibilityChangeReporter(486): Compat change id reported: 143937733; UID 10152; state: ENABLED
06-11 08:29:00.713: I/chatty(1869): uid=1041(audioserver) writer identical 47 lines
06-11 08:29:00.728: W/audio_hw_generic(1869): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:29:00.739: D/Zygote(290): Forked child process 2266
06-11 08:29:00.741: I/ActivityManager(486): Start proc 2266:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 for service {org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService

**Comment by sv-ohorvath** [comment]
The test hasn't failed in a month with this crash, I'll close the issue but it can be reopened if it appears again.
