### ISSUE TITLE
Bug 1771055

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#7117]
https://bugzilla.mozilla.org/show_bug.cgi?id=1771055

**Comment by mcarare** [comment]
For QA: Details on testing are on the linked Jira Task. Contact me with any questions.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 103.0a1 builds from 6/24 (361741705, and 361741706) with the following devices:
* Xiaomi mi4i (Android 5.0.2),
* Lenovo tablet M10 (Android 10),
* Google Pixel (Android 10),
* Xiaomi mi8 Lite (Android 10), 
* Samsung Galaxy Tab A6 (Android 5.1.1), and
* Oppo Reno 6 (Android 12).

There are some inconsistencies on page https://subdomain.preloaded-hsts.badssl.com/, between the Xiaomi mi4i device (Android 5.0.2), and all the other devices:

![Untitled](https://user-images.githubusercontent.com/40694158/175524159-c8c8532b-5d96-4a67-8491-a504e0d56a28.png)

Other than that, the cert error page has no “Accept risk and continue” button on any of the devices tested on.

@mcarare please let me know if this is considered an issue, or I can close this issue.
