### ISSUE TITLE
Intermittent UI test failure - WebControlsTest.verifyDropdownMenuTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#7126]
### Firebase Test Run:
Flaky, 1/2 tries
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5499013909798756662/executions/bs.879f30397971c38a/test-cases

The test has reached the last step `verifySelectedDropDownOption("The National")`

### Stacktrace:
`E/QueryController(13723): Got null root node from accessibility - Retrying...
05-26 15:33:19.553: W/audio_hw_generic(1862): Hardware backing HAL too slow, could only write 0 of 661 frames
05-26 15:33:19.643: D/CompatibilityChangeReporter(478): Compat change id reported: 135634846; UID 10152; state: DISABLED
05-26 15:33:19.646: D/CompatibilityChangeReporter(478): Compat change id reported: 143937733; UID 10152; state: ENABLED
05-26 15:33:19.642: I/chatty(1862): uid=1041(audioserver) writer identical 6 lines
05-26 15:33:19.657: W/audio_hw_generic(1862): Hardware backing HAL too slow, could only write 0 of 661 frames
05-26 15:33:19.669: D/Zygote(289): Forked child process 15855
05-26 15:33:19.672: W/audio_hw_generic(1862): Hardware backing HAL too slow, could only write 0 of 661 frames
05-26 15:33:19.681: I/sh.CrashHandle(15855): Late-enabling -Xcheck:jni
05-26 15:33:19.682: I/ActivityManager(478): Start proc 15855:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 for service {org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}`
### Build:
main branch 5/26

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a couple of months.
