### ISSUE TITLE
Implement Home assistant for Firefox Focus

### ISSUE THREAD

**Issue by sandoxy** [mozilla-mobile/focus-android#7131]
### Why/User Benefit/User Problem

Every time I activate the app Just Search after long pressing home, it makes a search in a new tab in Firefox. When I set Firefox as my Assist and press long home, it just opens the existing tab in Forefox. It would be great, if Firefox behaved like Just Search. Just Search is not mantained for years and I am afraid, it coild be not save to use anymore.

https://github.com/veniosg/JustSearch
"Just Search is an Assist replacement (the app that launches after long pressing
home) and cannot be launched via the launcher. To use it, navigate to the device
settings and change the default Assist app."

**Comment by lobontiumira** [comment]
Hi @sandoxy 
Did you mean Firefox Focus or Firefox fro Android? These are two distinctive apps.
Thank you!

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801993

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
