### ISSUE TITLE
Let A-C handle toolbar expanding when URL changes

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#7140]
Followup to https://github.com/mozilla-mobile/focus-android/issues/7075 and similar to Fenix - https://github.com/mozilla-mobile/fenix/issues/25455 .

https://github.com/mozilla-mobile/android-components/issues/12215 would upstream the current behavior to A-C for Focus to also automatically have the toolbar expanded when the URL changes.

We'd need to remove the now duplicated [toolbar expanding functionality from Focus](https://github.com/mozilla-mobile/focus-android/blob/55787c89d61abb966c54f5df2d3448664e05d84a/app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt#L280-L292) and rely only on the A-C functionality to expand the toolbar when the page is loading.

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?

**Comment by Mugurell** [comment]
@ QA: This ticket was about refactoring code, please ensure the app functions the same as just after https://github.com/mozilla-mobile/focus-android/issues/7075 - the toolbar is shown when the page is loading.

**Comment by delia-pop** [comment]
Verified as fixed on the latest Focus Nightly 103.0a1 from 06/02 (build 361540510 with GV 103.0a1-20220602231739), with Google Pixel 6 (Android 12). The previously hidden toolbar is displayed whenever tapping an URL. No issues were encountered.
