### ISSUE TITLE
[crash] Focus crashes when about:crashes is accessed

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7144]
## Steps to reproduce
1. Try to open about:crashes.

### Expected behavior
Focus crashes.

### Actual behavior
The about:crashes pages is displayed.

### Device information
* Android device: Lenovo Tab M10 (Android 10), and Samsung Galaxy Tab A6 (Android 5.1.1)
* Focus version: Focus Nightly 103.0a1 (build 361510512 GV 103.0a1-20220530140717, AC 103.0.20220530190102), and Beta 102.0.0-beta.1
* [Logcat](https://github.com/mozilla-mobile/focus-android/files/8805363/crash.logcat.txt)

**Comment by pascalchevrel** [comment]
Could we get this uplifted to the 102 beta branch if it affects beta? Thanks

**Comment by rvandermeulen** [comment]
@Mergifyio backport releases_v101.0 releases_v102.0

**Comment by ionutbedregeanu** [comment]
Sure

**Comment by ionutbedregeanu** [comment]
Fix uplifted to beta an release. @delia-pop please check when you have time
