### ISSUE TITLE
Intermittent UI test failure - < ErrorPagesTest. badURLCheckTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7166]
### Stacktrace:
06-02 10:29:05.951: I/WindowManager(481): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: c9193 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5001ms for FocusEvent(hasFocus=false)
06-02 10:29:05.959: W/audio_hw_generic(1710): Hardware backing HAL too slow, could only write 0 of 661 frames
06-02 10:29:06.123: I/ActivityManager(481): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-02 10:29:06.124: I/ActivityManager(481): Killing 13996:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-02 10:29:06.126: W/ActivityTaskManager(481): Force removing ActivityRecord{b9dea75 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-02 10:29:06.106: I/chatty(1710): uid=1041(audioserver) writer identical 10 lines
06-02 10:29:06.121: W/audio_hw_generic(1710): Hardware backing HAL too slow, could only write 0 of 661 frames
06-02 10:29:06.135: W/Binder(13884): Caught a RuntimeException from the binder stub implementation.
06-02 10:29:06.135: W/Binder(13884): java.lang.SecurityException: Calling from not trusted UID!
06-02 10:29:06.135: W/Binder(13884): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-02 10:29:06.135: W/Binder(13884): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-02 10:29:06.135: W/Binder(13884): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-02 10:29:06.135: W/Binder(13884): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-02 10:29:06.135: W/Binder(13884): 	at android.os.Binder.execTransact(Binder.java:1123)
06-02 10:29:06.136: W/audio_hw_generic(1710): Hardware backing HAL too slow, could only write 0 of 661 frames
06-02 10:29:06.137: I/ServiceChildProcess(14483): Destroying GeckoServiceChildProcess
06-02 10:29:06.144: D/AndroidRuntime(13884): Shutting down VM
06-02 10:29:06.151: W/audio_hw_generic(1710): Hardware backing HAL too slow, could only write 0 of 661 frames
06-02 10:29:06.153: I/ActivityManager(481): Killing 14483:org.mozilla.focus.debug:tab16/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-02 10:29:06.153: I/ActivityManager(481): Killing 14628:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-02 10:29:06.155: I/ActivityManager(481): Killing 12740:com.google.android.deskclock/u0a103 (adj 985): empty #17
06-02 10:29:06.155: D/WindowManager(481): notifyANR took 216ms

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.

**Comment by AndiAJ** [comment]
Flaky 1x on 7/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6164824543449132742/executions/bs.395876cb9b2521e3)

07-03 08:14:48.392: I/WindowManager(449): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 7c0fd20 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5004ms for FocusEvent(hasFocus=false)
07-03 08:14:48.404: W/audio_hw_generic(1907): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:14:48.412: W/e.process.gapp(13762): Unexpected CPU variant for X86 using defaults: x86
07-03 08:14:48.419: W/audio_hw_generic(1907): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:14:48.434: W/audio_hw_generic(1907): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:14:48.439: I/adbd(379): jdwp connection from 13762
07-03 08:14:48.449: W/audio_hw_generic(1907): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:14:48.509: I/chatty(1907): uid=1041(audioserver) writer identical 4 lines
07-03 08:14:48.524: W/audio_hw_generic(1907): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:14:48.529: W/system_server(449): Long monitor contention with owner Binder:449_1C (2869) at void com.android.server.am.ActivityManagerService.removeContentProvider(android.os.IBinder, boolean)(ActivityManagerService.java:7637) waiters=0 in void com.android.server.am.ActivityManagerService.dumpApplicationMemoryUsage(java.io.FileDescriptor, java.io.PrintWriter, java.lang.String, com.android.server.am.ActivityManagerService$MemoryUsageDumpOptions, java.lang.String[], boolean, java.util.ArrayList, java.io.PrintWriter) for 131ms
07-03 08:14:48.539: W/audio_hw_generic(1907): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:14:48.584: I/chatty(1907): uid=1041(audioserver) writer identical 3 lines
07-03 08:14:48.599: W/audio_hw_generic(1907): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:14:48.602: I/e.process.gapp(13762): The ClassLoaderContext is a special shared library.
07-03 08:14:48.613: I/ActivityManager(449): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
07-03 08:14:48.613: I/ActivityManager(449): Killing 12827:org.mozilla.focus.debug:tab7/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-03 08:14:48.614: W/Binder(12395): Caught a RuntimeException from the binder stub implementation.
07-03 08:14:48.614: W/Binder(12395): java.lang.SecurityException: Calling from not trusted UID!
07-03 08:14:48.614: W/Binder(12395): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
07-03 08:14:48.614: W/Binder(12395): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
07-03 08:14:48.614: W/Binder(12395): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
07-03 08:14:48.614: W/Binder(12395): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
07-03 08:14:48.614: W/Binder(12395): 	at android.os.Binder.execTransact(Binder.java:1123)
07-03 08:14:48.614: W/audio_hw_generic(1907): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:14:48.621: I/ActivityManager(449): Killing 12481:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-03 08:14:48.623: W/ActivityTaskManager(449): Force removing ActivityRecord{278359b u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
07-03 08:14:48.626: D/AndroidRuntime(12395): Shutting down VM
07-03 08:14:48.629: W/audio_hw_generic(1907): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:14:48.641: I/ActivityManager(449): Killing 12931:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-03 08:14:48.643: D/WindowManager(449): notifyANR took 259ms

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
