### ISSUE TITLE
[custom tab] Share icon is missing on Android 5 device

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#7177]
## Steps to reproduce
1. Make Focus your default browser.
2. From Gmail open a link on a custom tab.
3. Observe if the share icon is displayed. 
### Expected behavior
The share icon is displayed in the toolbar.
### Actual behavior
The share icon is not displayed in the toolbar.
### Device information

* Android device: Huawei MediaPad M2 (Android 5.1.1)
* Focus version: Beta 102.0.0-beta.2, RC 101.1.1., latest Nightly  from 06/05.

Note that the share icon is displayed on phone devices.

![image_2022_06_06T12_16_54_237Z](https://user-images.githubusercontent.com/89388888/172163799-3a27f9b5-7bd2-4c83-9a9b-185d0931146c.png)

**Comment by ionutbedregeanu** [comment]
@delia-pop noticed that this bug is not Focus specific, it can be reproduced also on Fenix. We need to do some extra research to see how it behaves on different devices with different android versions

**Comment by Mugurell** [comment]
Based on the above comment it seems like we'd want the same behavior as on other browsers.
@delia-pop Can you test if Focus / Fenix has the same behavior for showing the share button as Chrome?

**Comment by delia-pop** [comment]
Hello, @Mugurell @ionutbedregeanu, I re-tested this behavior on latest Focus/Fenix Nightly 104 and Chrome with Huawei MediaPad M2 (Android 5.1.1) tablet and Google Pixel 6 (Android 12) phone for reference and observed the following:
- the Share Icon **is** displayed in toolbar in custom tabs on **Phone** in Fenix/Focus;
- the Share Icon **is not** displayed in toolbar in custom tabs on **Tablet** in Fenix/Focus;
- the Share Icon **is displayed** in toolbar in custom tabs on **Phone and Tablet** in Chrome;

![ShareIcon](https://user-images.githubusercontent.com/89388888/180452867-d04a5444-a048-457e-8b65-a979d7ca0b21.jpg)

**Comment by Mugurell** [comment]
Thank you Delia!
So it remains for us to investigate what configuration is sent to us with `EXTRA_SHARE_STATE` and then if the app uses that as expected or not.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802641

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
