### ISSUE TITLE
Focus crashed when performing a search after being idle for a while in Settings.

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#7178]
## Steps to reproduce
1. Have a page opened.
2. Access some menus in Settings.
3. Leave the app idle a few minutes.
4. Exit the settings and tap on the search bar from the page opened in step 1.
5. Perform a search (e.g. YouTube) and observe if the app crashes. 

### Expected behavior
The application remains stable at all times.
### Actual behavior
The application crashed when performing a search after being idle for a while in Settings.
### Device information

* Android device: Google Pixel 6 (Android 12)
* Focus version: Beta 102.0.0-beta.2
Note that the crash could not be reproduced, and the STR could not be 100% reliable.

Crash report: https://crash-stats.mozilla.org/report/index/5475d427-9840-4808-aa1b-f2c6a0220606

**Comment by Mugurell** [comment]
The exception message shown on [Socorro](https://crash-stats.mozilla.org/report/index/5475d427-9840-4808-aa1b-f2c6a0220606) shows
> java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

So this is similar to the recently resolved https://github.com/mozilla-mobile/focus-android/issues/7144.
What's interesting is that this should be a perma crash.

**Comment by delia-pop** [comment]
I can no longer reproduce the issue on the latest Focus Nightly 104, Beta 103.0.0-beta.5 or RC 103.1.0 with Google Pixel 6 (Android 12).
