### ISSUE TITLE
Confusing "Stealth" setting

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#718]
Feedback from XXXXXXXXXX : I feel like this language is a bit confusing. I feel like it would be better to describe what it does while in stealth mode instead of what it would do if you turn it off. 

![screenshot](https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/584f67f6f3d6eb01000842d6/593033b2d1f5290001797bf3/70d465c8-fb2a-4cee-a349-0af5dac8458f.jpg)

| Item | Value |
| --- | --- |
| Created | Fri Jun 02 2017 15:11:10 GMT+0000 (UTC) |
| App uptime | undefined |
| Build | 1851 |
| Device type | Nexus 6P |
| Device name | undefined |
| Screen size | 1440 |
| Screen size | 1440px by 2392px |
| Battery | 98% Unplugged |
| Memory free | 530 MB / 2799 MB |
| Network IP | undefined |

 [Link to buddybuild feedback from build 1851](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/feedback?fid=5931800e5445ec0001d559a1&bnum=1851)

**Comment by mheubusch** [comment]
@antlam per our discussion:

Stealth
Hide webpages when switching apps

**Comment by antlam** [comment]
@pocmo double checking my understanding of the default pref here. Is the Stealth setting ON (screenshots disabled) or OFF (screenshots enabled) by default ?

**Comment by pocmo** [comment]
The setting is on by default.
