### ISSUE TITLE
[SUMO] Default browser article 

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#719]
Feedback from XXXXXXXXXX : The "make default browser" menu option, when toggled, opens a support article telling the user to toggle that option to set Focus as the default browser. But when they do, it opens a support article that tells the user to toggle that option etc etc. 

![screenshot](https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/584f67f6f3d6eb01000842d6/5928a2fe47e41c0001d8bc2a/565b596c-fb9f-4e42-9ce1-f3b916753f2d.jpg)

| Item | Value |
| --- | --- |
| Created | Sat May 27 2017 22:16:56 GMT+0000 (UTC) |
| App uptime | undefined |
| Build | 1769 |
| Device type | XT1021 |
| Device name | undefined |
| Screen size | 540 |
| Screen size | 540px by 888px |
| Battery | 70% Unplugged |
| Memory free | 323 MB / 914 MB |
| Network IP | undefined |

 [Link to buddybuild feedback from build 1769](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/feedback?fid=5929fad8f7b88a0001cd7706&bnum=1769)

**Comment by pocmo** [comment]
https://support.mozilla.org/en-US/kb/make-firefox-default-browser-android

**Comment by jonisavage** [comment]
We can update this article. What version(s) of Android do users need to install Firefox Focus? Should we include instructions on how to set the default for older versions of Android, or just on Android 6+?

**Comment by pocmo** [comment]
Focus supports Android 5 and higher
