### ISSUE TITLE
  Picture-in-picture to custom tab has the app blocked in landscape

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#7190]
Duplicate issue as on Fenix - https://github.com/mozilla-mobile/fenix/issues/25413

STRs:
- Have Fenix set as the default browser
- Start playing a fullscreen video in landscape
- Tap the home button to enter in picture-in-picture  mode
- Ensure the device is now held in portrait
- Tap on a link from another app to open it in a Fenix custom tab

Expected result:
- Fenix open a custom tab and shows it using device orientation (portrait).

Actual result:
- The picture-in-picture mode is still on and the player is shown over the custom tab.
- Orientation is locked to landscape making webpage interactions cumbersome.
- Even after closing the small pip window orientation is locked to landscape.

Not that testing the same scenario on Chrome I see that the video continue playing in pip mode but the app orientation when showing the custom tab will be portrait as expected.

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly from 6/14 build 103.0a1 (GV 103.0a1-20220609065921) on the following devices:
* Oppo Reno 6 (Android 12),
* Lenovo Tab M10 (Android 10).
