### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest. verify3rdPartyCookiesEnabledTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7196]
### Stacktrace:
06-07 13:52:34.633: I/WindowManager(477): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: ccd97da org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=false)
06-07 13:52:34.750: I/ActivityManager(477): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-07 13:52:34.750: I/ActivityManager(477): Killing 14119:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-07 13:52:34.731: I/chatty(1745): uid=1041(audioserver) writer identical 8 lines
06-07 13:52:34.746: W/audio_hw_generic(1745): Hardware backing HAL too slow, could only write 0 of 661 frames
06-07 13:52:34.752: W/Binder(14062): Caught a RuntimeException from the binder stub implementation.
06-07 13:52:34.752: W/Binder(14062): java.lang.SecurityException: Calling from not trusted UID!
06-07 13:52:34.752: W/Binder(14062): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-07 13:52:34.752: W/Binder(14062): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-07 13:52:34.752: W/Binder(14062): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-07 13:52:34.752: W/Binder(14062): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-07 13:52:34.752: W/Binder(14062): 	at android.os.Binder.execTransact(Binder.java:1123)
06-07 13:52:34.755: W/ActivityTaskManager(477): Force removing ActivityRecord{6e8524f u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-07 13:52:34.759: I/ActivityManager(477): Killing 14663:org.mozilla.focus.debug:tab30/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-07 13:52:34.760: I/ActivityManager(477): Killing 14745:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-07 13:52:34.761: W/audio_hw_generic(1745): Hardware backing HAL too slow, could only write 0 of 661 frames
06-07 13:52:34.771: D/WindowManager(477): notifyANR took 180ms
### Notes: Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/17 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5296091421993630801/executions/bs.714da204c3c9e35)

06-17 20:00:43.016: I/WindowManager(484): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: f879da3 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=false)
06-17 20:00:43.129: I/ActivityManager(484): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-17 20:00:43.129: I/ActivityManager(484): Killing 15679:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-17 20:00:43.115: I/chatty(1758): uid=1041(audioserver) writer identical 7 lines
06-17 20:00:43.130: W/audio_hw_generic(1758): Hardware backing HAL too slow, could only write 0 of 661 frames
06-17 20:00:43.133: W/Binder(15627): Caught a RuntimeException from the binder stub implementation.
06-17 20:00:43.133: W/Binder(15627): java.lang.SecurityException: Calling from not trusted UID!
06-17 20:00:43.133: W/Binder(15627): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-17 20:00:43.133: W/Binder(15627): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-17 20:00:43.133: W/Binder(15627): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-17 20:00:43.133: W/Binder(15627): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-17 20:00:43.133: W/Binder(15627): 	at android.os.Binder.execTransact(Binder.java:1123)
06-17 20:00:43.135: I/ServiceChildProcess(16411): Destroying GeckoServiceChildProcess
06-17 20:00:43.137: I/ServiceChildProcess(16288): Destroying GeckoServiceChildProcess
06-17 20:00:43.145: D/AndroidRuntime(15627): Shutting down VM
06-17 20:00:43.145: W/ActivityTaskManager(484): Force removing ActivityRecord{d3bfa05 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-17 20:00:43.145: W/audio_hw_generic(1758): Hardware backing HAL too slow, could only write 0 of 661 frames
06-17 20:00:43.169: I/ActivityManager(484): Killing 16288:org.mozilla.focus.debug:tab37/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-17 20:00:43.171: I/ActivityManager(484): Killing 16411:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-17 20:00:43.174: D/WindowManager(484): notifyANR took 169ms
06-17 20:00:43.310: I/chatty(1758): uid=1041(audioserver) writer

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
