### ISSUE TITLE
Intermittent UI test failure - WebControlsTest.verifyCalendarFormTest

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7219]
### Firebase Test Run:
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8844915779908086916/executions/bs.f15faa4e63664a42/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8844915779908086916/executions/bs.67e260e14234b9d1)

### Notes: Not sure why it crashed ❓ 
It happened before [asserting the selected date ](https://github.com/mozilla-mobile/focus-android/blob/main/app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt#L269)
[Logcat](https://00f74ba44b724ea954f8d53da4379c1848f745d1b1-apidata.googleusercontent.com/download/storage/v1/b/focus_android_test_artifacts/o/2022-06-11_15-20-25.980609_KbxY%2Fmatrix_0%2FPixel3-30-en-portrait-shard_7%2Ftest_cases%2F0000_logcat?jk=AFshE3XqTVChJlhtsvmbnRurTYGc_ZarmsNjelPxBTJEBSNVRv2Z_4gPFHy8wyL1Ur7MPJh7K_M9eagriK-m1H390wwCKOThvAhGodBxWtMmFafcqv0SdesDlIhakmr9wutGaB0Yj00xbMxwOzs89YgFaKXy9lKIrNeWfFGlsPbIpqOeMz3cfSV42yF6n0wH5W1_WqrPaH7-RBf-N2J74tP9-VKeGCJgtgaMDcP0b4PQNQZ1bciW5BPEiYCGoCPjDLghzy4Cro_7TZOsTft4ap78e-FQpG-icsZwXQe9pxusDNJe1R54BzjeOcOPQMgH4Z0uLgQv-cszTSiJtA5ccwhJmXWJvplZPMLeiJ0y3GfCa4_a11TsA9nHTXMCJhhrHM3qFGIaYnjdaUcEeijUB2wRj4PnzRzUXV6TwwjPFkddGNZdGsq2nxn_2VYVIJbDAkvAZAueb0s8KU204DnuvV9VLL2mle4aM-PvGgUIqL9lBO1tAiciIE3PeZ5q-5A9_EXGyCdtdoKBXfxi8cFToN_OgETvi36pv7lrVP-17nbYjmB_4Ty4Mhou6QRB-Yu7qgy9h1G96YS4A6oLxgTGHXqVBDKLdNAQexWsXT_cSSCu3CKvhzxljEqFG2fk2fOjWDDq20Qr7vYFkWPvBne567MDKfeb0a2RgzZ-xp5chxVvmIs2G4nk9Nk_ZJxbayYN4z-pKo4WHVk19KJ_GDcYAxlwr4GVk-MbUUwT2LNBnR9glNENsw23etuieGzd9jsKOqyudnUyWP8lUfTUNTCXX2wzl8zi3ozNpKTKdsTobU_FEIWHLlPZsm44qRRtONu7gUUKClRDP3i-W8qKs-hRc-j7H7M9K999Ltsl407r-_ZYPSDP01lkAI4-pWXBFWOAiyZIDlIQMV0PYDAOEUgifYODm-jXT2sCeQz6150dHOIq02UsU2YgRIU_TVhkFaxDkQuU21aInTwp2tElUDygwWsDCKchHEWn6anypDFcbm4ZGvfSczLiq2QHMf8GlNQ-kdmwXiNahHWbIt0639Wz7jqNfrKM6u4YiNDWuTP1Ivvd3tftDUyjL4x_fWDtkclYVnD-rmX80qAjru6gn4mIw12zaTbE-in9PqVe0JdeoJjjawZJLMJOf4iPX28FEYgLgZvTPzEzj-s8I8Z6ds_w20GJ&isca=1)
[Logcat](https://00f74ba44b007776e9ec9a76fafb51a9a08f3ff382-apidata.googleusercontent.com/download/storage/v1/b/focus_android_test_artifacts/o/2022-06-11_15-20-25.980609_KbxY%2Fmatrix_0%2FPixel3-30-en-portrait-shard_7-rerun_1%2Flogcat?jk=AFshE3UQmRwyveazeJufVOnP_NJDOBE1I_27E0R9nO-YQaWPYAgJQBkg7Vp3mkqgLQpCTXglFOYiVzvHO_D9rZ0kV0WKiBgc_TG78ZO8AG_XffHwJwCcuXrExqa0BHrqBeXMKBs5ONx2gsP0YbTXh3UJ5CH5xWy32OWPeB0sY_ul4vAWNgl7wZH5GnmyBwLBsUg6Sx_nccnH8VA4a4I-M1Dw84BVwjMQRlwwGSCgI4NA_secQDszB8FwLP8yDX6Nt1FczjL_dnMMgGuhMd0ka6EgxilIXa83QeOMkCgY6OEH8d9SRCXQHeBRAgbN3kGiLbV_IMN804EYVNpLzWsYHIPba_swSAzDldpwPwlcLJc2jKD_lZYCQ8oHPGJo9sz6djqoIWmFkU1A3DcD2w8FhFJMnJhPUr6pir6Nu1q82K9Zv5L9djc46eGGvky344N4DtrtKTX5clfDOwlnv7dfpG4S9PBWp-D-znGaWykgTqzAuPWjfiNxjozZHJRZwTpBGz5fqfFNCb_zTeAskwQrPpIjNqxItDPUuFf-Dx9NrdlhFhpvVrhIO82ozrRKeMNiHRnOLo-lhaCs1jVIbQ_P3xQeAF_hk_RNT1tZaxYAVN9HdQ4fcPb5hHGIaLFhRl2x9nG8x3Qn_IlcyAg2pb4phqlgOAbar8IWojuwr43IyoVv677DZRDf3Z_oRVWCI0aNGZJ9STMkXSG7xIcKa8YzTITUhBjPjnZpy9oynKsO6vwcUsiLitmGXZ511QJ--612UTlLoSOVuIngG0suyfe0S4qD3v0qjTUJW_XUNBotuHSvdUJqvPXORs50HDl_AgC1U1Te6hIkR13MnUya-l--0FbU1eFrUmOcBO6GKN4Y9-nKhYKFxfEc50tb7Qp6ZeyWFEClsYhILqwcatXcT4hSkRRkCIUCy7v19F2Ju37oz6p_Ru8IyFPnrRVI8U-PzdM1ypHIeSKIjwFmVobFdBDCZfxynM3yttodBN3JRui89NU5kOOuzpsnhQTMYF_rf-y1cNstcX7-1_DbbYs8JsOSSYI8V41lHZPFK_ney1HAp98Z5LY9BZsYlIKyaNwWUcxJZfK-oWTbbjobZinDYBgxWV399xN609fGAP-8hhdfkYyP75eDth8mUwUFrYF4XcF8IJuviMai6OQ&isca=1)

**Comment by sv-ohorvath** [comment]
`06-11 08:32:25.847: E/QueryController(12039): Got null root node from accessibility - Retrying...
06-11 08:32:25.849: W/audio_hw_generic(1831): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:32:25.987: D/CompatibilityChangeReporter(480): Compat change id reported: 135634846; UID 10152; state: DISABLED
06-11 08:32:25.987: D/CompatibilityChangeReporter(480): Compat change id reported: 143937733; UID 10152; state: ENABLED
......
06-11 08:32:26.050: D/Zygote(291): Forked child process 15434
.......
06-11 08:32:26.322: I/binder(0): undelivered transaction 978767, process died.
06-11 08:32:26.276: I/ActivityManager(480): Process org.mozilla.focus.debug (pid 12039) has died: fg  FGS 
06-11 08:32:26.277: I/WindowManager(480): WIN DEATH: Window{8c38042 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity}
06-11 08:32:26.277: W/InputDispatcher(480): Attempted to unregister already unregistered input channel '8c38042 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)'
06-11 08:32:26.284: W/audio_hw_generic(1831): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:32:26.288: I/Zygote(291): Process 12039 exited cleanly (11)
06-11 08:32:26.288: W/WindowManager(480): Cannot find window which accessibility connection is added to
06-11 08:32:26.289: W/WindowManager(480): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@975e56e
06-11 08:32:26.299: W/audio_hw_generic(1831): Hardware backing HAL too slow, could only write 0 of 661 frames
06-11 08:32:26.318: W/ActivityManager(480): Crash of app org.mozilla.focus.debug running instrumentation ComponentInfo{org.mozilla.focus.debug.test/androidx.test.runner.AndroidJUnitRunner}`

**Comment by sv-ohorvath** [comment]
Similar to other logged issues, it could be the same as the known https://github.com/mozilla-mobile/fenix/issues/24047 but without throwing an ANR

**Comment by sv-ohorvath** [comment]
closing as dupe, in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
Some test reports that have this same error in the logs contain the ANR notification, some don't, so until we can tell if they are different issues, I will log them in one place.
