### ISSUE TITLE
The download from https://www.thinkbroadband.com/download fails after it's resumed

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7224]
## Steps to reproduce
1. Go to https://www.thinkbroadband.com/download.
2. Start downloading a file, by confirming the HTTP prompt.
3. Pause the download from the Android notification bar.
4. Resume the download, and observe if the download actually continues.

### Expected behavior
The download continues without issues.

### Actual behavior
The download continues for a couple of seconds, without progressing, then fails.
If the download is not paused, then resumed, it completes without issues.

### Device information
* Android device: OnePlus 5T (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1)
* Focus version: Focus Nightly 103.0a1 from 6/15, Beta 102.0.0-beta.4
* Not reproducible on other sites.
* Not reproducible on Fenix Nightly from 6/14
* Please see the short video:

https://user-images.githubusercontent.com/40694158/173836539-7d23361e-8b30-4903-99a6-9416cda37144.mp4

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802640

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
