### ISSUE TITLE
[Fission] When Fission is active, the Media Notification Player is not displayed

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#7227]
## Steps to reproduce
1. Go to about:config.
2. Search for fission.autostart and set it to true.
3. Go to a website that can play media (e.g. rockfm.com, youtube.com, soundcloud.com).
4. Play a video.
5. Invoke the Android notification bar and observe.
6. Lock the device and observe the lock screen.
### Expected behavior
The Media Notification is active/displayed on the Android Notification bar and lock screen, and the user can play/pause/skip the playing media.
### Actual behavior
Similar to #25640 in Fenix, the Media Notification is not displayed on the Android Notification bar and lock screen when Fission is enabled.
### Device information
* Android device: Google Pixel 6 (Android 12).
* Focus version: latest Nightly 103 from 06/16.

https://user-images.githubusercontent.com/89388888/174058221-6d27be85-f5fd-40e4-8fc8-d5b5c561fcf8.mp4

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802639

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
