### ISSUE TITLE
[Fission] The tab crashes when attempting to access an unsecure page with HTTPS-Only Mode enabled

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#7231]
## Precondition: 
1. Go to about:config > Search for fission.autostart and set it to true.
2. Make sure to have the HTTPS-Only Mode enabled in Settings.
## Steps to reproduce
1. Go to any HTTP page (e.g. http://www.testingmcafeesites.com/, http://xcal1.vodafone.co.uk/, https://www.thinkbroadband.com/download and attempt to download a file).
2. When the HTTP confirmation prompt is displayed, tap on "Continue to HTTP Site".
3. Observe the result.

### Expected behavior
The unsecure page loads.
### Actual behavior
The tab crashes when attempting to access an unsecure page.
### Device information

* Android device: Google Pixel 6 (Android 12)
* Focus version: latest Nightly 103 from 06/16.

[HTTP_Crash.txt](https://github.com/mozilla-mobile/focus-android/files/8920239/HTTP_Crash.txt)

[4c269dfe-e69b-4.txt](https://github.com/mozilla-mobile/focus-android/files/8920556/4c269dfe-e69b-4.txt)

https://user-images.githubusercontent.com/89388888/174114323-8b40f13c-6973-4e45-82ba-494bb6710cac.mp4

**Comment by ionutbedregeanu** [comment]
Mozilla crash report: https://crash-stats.mozilla.org/report/index/7cacc88d-470b-4af3-b1a9-2659f0220718#tab-details
Bugzilla ticket was already created: https://bugzilla.mozilla.org/show_bug.cgi?id=1776917

**Comment by ionutbedregeanu** [comment]
@amedyne Should we close this one or should we label it with "waiting"?

**Comment by Mugurell** [comment]
> @amedyne Should we close this one or should we label it with "waiting"?

Would say that if we expect to have other work to do to fix this after the GV work this should be marked as waiting.
Otherwise based on how Agi's extension - "Move to Bugzilla" functions if there isn't anything for us to do then the ticket can be moved to Bugzilla or just linked there and closed here since it will be worked on solely on Bugzilla and can also be verified there.
