### ISSUE TITLE
Add metrics tags for all issues labels

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/focus-android#7236]
Similar to https://github.com/mozilla-mobile/fenix/issues/22956 and as a followup to https://github.com/mozilla-mobile/focus-android/pull/7186/files#diff-da7ea8df1d4843419cfa6570993d3a350d1a4bd3ecda6f17a081c119ae45a8af Focus also needs to easily use tags for metrics probes and in that remove most of the manual process/pain of defining tags in a seperate Glean annotations repository (see: https://github.com/mozilla-mobile/fenix/wiki/Add-a-Glean-Annotation-for-an-event).

To keep the list of tags up to date with the Focus issue labels:
- a similar script to Focus' [update-glean-tags.py](https://github.com/mozilla-mobile/fenix/blob/759f0bd800e9885bca2475d68f0f7de406ac8cb6/tools/setup-startup-profiling.py) should be added to the repository and 
- ran once to add the initial list of tags and then only seldomly when the labels are updated.

**Comment by Mugurell** [comment]
@iorgamgabriel It seems like only half of the work for this was done. 
I see https://github.com/mozilla-mobile/focus-android/pull/7251 added the script for syncing all labels to the project but this syncing was not done.
Do you plan to break the work and add them in a separate ticket so they can be later used?

**Comment by iorgamgabriel** [comment]
Done https://github.com/mozilla-mobile/focus-android/pull/7319
