### ISSUE TITLE
Intermittent UI test failure - < DownloadFileTest.downloadAndOpenPdfFileTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7237]
### Stacktrace:
06-16 22:31:40.959: I/WindowManager(479): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 9322c3e org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5014ms for KeyEvent(deviceId=-1, source=0x00000101, displayId=-1, action=UP, flags=0x00000000, keyCode=66, scanCode=0, metaState=0x00000000, repeatCount=0), policyFlags=0x6b000000
06-16 22:31:41.182: I/ActivityManager(479): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-16 22:31:41.182: I/ActivityManager(479): Killing 15681:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-16 22:31:41.185: W/Binder(15570): Caught a RuntimeException from the binder stub implementation.
06-16 22:31:41.185: W/Binder(15570): java.lang.SecurityException: Calling from not trusted UID!
06-16 22:31:41.185: W/Binder(15570): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-16 22:31:41.185: W/Binder(15570): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-16 22:31:41.185: W/Binder(15570): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-16 22:31:41.185: W/Binder(15570): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-16 22:31:41.185: W/Binder(15570): 	at android.os.Binder.execTransact(Binder.java:1123)
06-16 22:31:41.188: I/ServiceChildProcess(16307): Destroying GeckoServiceChildProcess
06-16 22:31:41.192: I/ServiceChildProcess(16150): Destroying GeckoServiceChildProcess
06-16 22:31:41.192: W/ActivityTaskManager(479): Force removing ActivityRecord{27f543d u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-16 22:31:41.195: D/AndroidRuntime(15570): Shutting down VM
06-16 22:31:41.242: E/JavaBinder(15570): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
06-16 22:31:41.242: E/JavaBinder(15570): java.lang.RuntimeException: Bad file descriptor
06-16 22:31:41.242: E/JavaBinder(15570): 	at android.os.BinderProxy.transactNative(Native Method)
06-16 22:31:41.242: E/JavaBinder(15570): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
06-16 22:31:41.242: E/JavaBinder(15570): 	at android.view.IWindowManager$Stub$Proxy.injectInputAfterTransactionsApplied(IWindowManager.java:5262)
06-16 22:31:41.242: E/JavaBinder(15570): 	at android.app.UiAutomationConnection.injectInputEvent(UiAutomationConnection.java:136)
06-16 22:31:41.242: E/JavaBinder(15570): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:228)
06-16 22:31:41.242: E/JavaBinder(15570): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
06-16 22:31:41.242: E/JavaBinder(15570): 	at android.os.Binder.execTransact(Binder.java:1123)
06-16 22:31:41.253: I/cus.debug:tab1(16150): System.exit called, status: 0
06-16 22:31:41.253: I/AndroidRuntime(16150): VM exiting with result code 0, cleanup skipped.
06-16 22:31:41.256: I/ActivityManager(479): Killing 16150:org.mozilla.focus.debug:tab11/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-16 22:31:41.257: I/ActivityManager(479): Killing 16307:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-16 22:31:41.272: I/BackdropActivity(13760): onResume()
06-16 22:31:41.273: I/ActivityTaskManager(479): Activity requesting to dismiss Keyguard: ActivityRecord{63fc037 u0 com.google.android.apps.mtaas.backdrop/.BackdropActivity t8}
06-16 22:31:41.277: D/WindowManager(479): notifyANR took 327ms
### Build: 6/17 Main
Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
