### ISSUE TITLE
Intermittent UI test failure - < ThreeDotMainMenuTest. browserMenuItemsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7245]
### Stacktrace:
06-19 08:47:55.397: I/WindowManager(477): Input event dispatching timed out sending to PopupWindow:11e1eef.  Reason: b6aa0d PopupWindow:11e1eef (server) is not responding. Waited 5001ms for FocusEvent(hasFocus=false)
06-19 08:47:55.507: I/ActivityManager(477): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-19 08:47:55.507: I/ActivityManager(477): Killing 13515:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-19 08:47:55.509: W/ActivityTaskManager(477): Force removing ActivityRecord{1ca15eb u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-19 08:47:55.497: I/chatty(1870): uid=1041(audioserver) writer identical 8 lines
06-19 08:47:55.512: W/audio_hw_generic(1870): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:47:55.512: I/ServiceChildProcess(13975): Destroying GeckoServiceChildProcess
06-19 08:47:55.513: W/Binder(13425): Caught a RuntimeException from the binder stub implementation.
06-19 08:47:55.513: W/Binder(13425): java.lang.SecurityException: Calling from not trusted UID!
06-19 08:47:55.513: W/Binder(13425): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-19 08:47:55.513: W/Binder(13425): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-19 08:47:55.513: W/Binder(13425): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-19 08:47:55.513: W/Binder(13425): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-19 08:47:55.513: W/Binder(13425): 	at android.os.Binder.execTransact(Binder.java:1123)
06-19 08:47:55.532: W/audio_hw_generic(1870): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:47:55.548: I/chatty(1870): uid=1041(audioserver) writer identical 1 line
06-19 08:47:55.564: W/audio_hw_generic(1870): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 08:47:55.565: I/ServiceChildProcess(14099): Destroying GeckoServiceChildProcess
06-19 08:47:55.566: I/ActivityManager(477): Killing 13975:org.mozilla.focus.debug:tab23/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-19 08:47:55.567: I/ActivityManager(477): Killing 14099:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-19 08:47:55.568: D/WindowManager(477): notifyANR took 172ms
### Notes: Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5483480119120719958/executions/bs.e994608d558e9918)

06-20 13:28:42.117: I/WindowManager(482): Input event dispatching timed out sending to PopupWindow:c995624.  Reason: 5a08841 PopupWindow:c995624 (server) is not responding. Waited 5001ms for FocusEvent(hasFocus=false)
06-20 13:28:42.124: W/audio_hw_generic(1860): Hardware backing HAL too slow, could only write 0 of 661 frames
06-20 13:28:42.177: I/ActivityManager(482): Killing 12131:com.google.android.calendar/u0a105 (adj 985): empty #17
06-20 13:28:42.198: I/chatty(1860): uid=1041(audioserver) writer identical 5 lines
06-20 13:28:42.214: W/audio_hw_generic(1860): Hardware backing HAL too slow, could only write 0 of 661 frames
06-20 13:28:42.219: I/Zygote(290): Process 12131 exited due to signal 9 (Killed)
06-20 13:28:42.222: I/libprocessgroup(482): Successfully killed process cgroup uid 10105 pid 12131 in 43ms
06-20 13:28:42.228: W/audio_hw_generic(1860): Hardware backing HAL too slow, could only write 0 of 661 frames
06-20 13:28:42.280: I/ActivityManager(482): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-20 13:28:42.280: I/ActivityManager(482): Killing 13465:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-20 13:28:42.259: I/chatty(1860): uid=1041(audioserver) writer identical 2 lines
06-20 13:28:42.273: W/audio_hw_generic(1860): Hardware backing HAL too slow, could only write 0 of 661 frames
06-20 13:28:42.283: W/Binder(13378): Caught a RuntimeException from the binder stub implementation.
06-20 13:28:42.283: W/Binder(13378): java.lang.SecurityException: Calling from not trusted UID!
06-20 13:28:42.283: W/Binder(13378): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-20 13:28:42.283: W/Binder(13378): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-20 13:28:42.283: W/Binder(13378): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-20 13:28:42.283: W/Binder(13378): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-20 13:28:42.283: W/Binder(13378): 	at android.os.Binder.execTransact(Binder.java:1123)
06-20 13:28:42.288: W/ActivityTaskManager(482): Force removing ActivityRecord{620c6d6 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-20 13:28:42.289: W/audio_hw_generic(1860): Hardware backing HAL too slow, could only write 0 of 661 frames
06-20 13:28:42.296: I/ActivityManager(482): Killing 13944:org.mozilla.focus.debug:tab22/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-20 13:28:42.299: I/ActivityManager(482): Killing 14054:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-20 13:28:42.300: D/WindowManager(482): notifyANR took 187ms

**Comment by AndiAJ** [comment]
Flaky 1x on 6/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8578281270252513802/executions/bs.170aa6b05406c9a1/test-cases)

06-29 15:41:26.071: I/WindowManager(482): Input event dispatching timed out sending to PopupWindow:708be79.  Reason: 92acc0e PopupWindow:708be79 (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=false)
06-29 15:41:26.090: I/chatty(1824): uid=1041(audioserver) writer identical 66 lines
06-29 15:41:26.105: W/audio_hw_generic(1824): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 15:41:26.113: E/QueryController(14092): Got null root node from accessibility - Retrying...
06-29 15:41:26.120: W/audio_hw_generic(1824): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 15:41:26.121: E/MmTelFeatureConnection [0](1774): ImsRegistrationCallbackAdapter: ImsRegistration is null
06-29 15:41:26.135: W/audio_hw_generic(1824): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 15:41:26.224: I/ActivityManager(482): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-29 15:41:26.224: I/ActivityManager(482): Killing 14092:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 15:41:26.210: I/chatty(1824): uid=1041(audioserver) writer identical 5 lines
06-29 15:41:26.225: W/audio_hw_generic(1824): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 15:41:26.233: D/GeckoViewProgressDelegate[C](14603): handleEvent: MozAfterPaint
06-29 15:41:26.234: W/Binder(14004): Caught a RuntimeException from the binder stub implementation.
06-29 15:41:26.234: W/Binder(14004): java.lang.SecurityException: Calling from not trusted UID!
06-29 15:41:26.234: W/Binder(14004): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-29 15:41:26.234: W/Binder(14004): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-29 15:41:26.234: W/Binder(14004): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-29 15:41:26.234: W/Binder(14004): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-29 15:41:26.234: W/Binder(14004): 	at android.os.Binder.execTransact(Binder.java:1123)
06-29 15:41:26.238: I/ServiceChildProcess(14603): Destroying GeckoServiceChildProcess
06-29 15:41:26.238: I/ServiceChildProcess(14686): Destroying GeckoServiceChildProcess
06-29 15:41:26.240: W/audio_hw_generic(1824): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 15:41:26.247: W/ActivityTaskManager(482): Force removing ActivityRecord{9a678c3 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-29 15:41:26.255: W/audio_hw_generic(1824): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 15:41:26.260: D/GeckoViewProgressDelegate[C](14603): handleEvent: MozAfterPaint
06-29 15:41:26.270: W/audio_hw_generic(1824): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 15:41:26.277: I/ActivityManager(482): Killing 14603:org.mozilla.focus.debug:tab11/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 15:41:26.278: I/ActivityManager(482): Killing 14686:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 15:41:26.279: D/WindowManager(482): notifyANR took 224ms

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
