### ISSUE TITLE
Intermittent UI test failure - <DownloadFileTest.cancelDownloadTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7246]
### Stacktrace:
06-19 23:22:56.687: E/QueryController(12069): Got null root node from accessibility - Retrying...
06-19 23:22:56.687: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:56.897: I/chatty(1864): uid=1041(audioserver) writer identical 14 lines
06-19 23:22:56.912: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:56.922: I/PeriodicStatsRunner(2177): PeriodicStatsRunner.call():180 call()
06-19 23:22:56.922: I/PeriodicStatsRunner(2177): PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
06-19 23:22:56.927: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:56.933: D/CompatibilityChangeReporter(475): Compat change id reported: 135634846; UID 10152; state: DISABLED
06-19 23:22:56.934: D/CompatibilityChangeReporter(475): Compat change id reported: 143937733; UID 10152; state: ENABLED
06-19 23:22:56.936: E/JobScheduler.Background(475): App com.google.android.gms became active but still in NEVER bucket
06-19 23:22:56.937: I/DropBoxManagerService(475): add tag=system_server_wtf isTagEnabled=true flags=0x2
06-19 23:22:56.942: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:56.948: I/cmd(14645): oneway function results will be dropped but finished with status OK and parcel size 4
06-19 23:22:56.957: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:56.959: D/Zygote(288): Forked child process 14651
06-19 23:22:56.972: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:56.975: I/sh.CrashHandle(14651): Late-enabling -Xcheck:jni
06-19 23:22:56.987: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.002: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.003: I/sh.CrashHandle(14651): Unquickening 12 vdex files!
06-19 23:22:57.006: W/sh.CrashHandle(14651): Unexpected CPU variant for X86 using defaults: x86
06-19 23:22:57.017: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.018: I/cmd(14662): oneway function results will be dropped but finished with status OK and parcel size 4
06-19 23:22:57.032: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.033: I/adbd(378): jdwp connection from 14651
06-19 23:22:57.047: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.049: W/ActivityManager(475): Slow operation: 115ms so far, now at startProcess: done updating battery stats
06-19 23:22:57.049: W/ActivityManager(475): Slow operation: 115ms so far, now at startProcess: building log message
06-19 23:22:57.049: I/ActivityManager(475): Start proc 14651:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 for service {org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
06-19 23:22:57.049: W/ActivityManager(475): Slow operation: 115ms so far, now at startProcess: starting to update pids map
06-19 23:22:57.049: W/ActivityManager(475): Slow operation: 116ms so far, now at startProcess: done updating pids map
06-19 23:22:57.050: I/InputManager(475): Enabling motion classifier because timeout changed: feature enabled, long press timeout = 400
06-19 23:22:57.050: I/InputClassifier(475): Enabling motion classifier
06-19 23:22:57.062: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.105: I/binder(0): 475:14681 BC_REQUEST_DEATH_NOTIFICATION death notification already set
06-19 23:22:57.137: I/chatty(1864): uid=1041(audioserver) writer identical 5 lines
06-19 23:22:57.152: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.153: I/Gecko(12611): Exiting due to channel error.
06-19 23:22:57.207: I/binder(0): undelivered transaction 953373, process died.
06-19 23:22:57.214: I/binder(0): undelivered transaction 953376, process died.
06-19 23:22:57.167: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.170: I/WindowManager(475): WIN DEATH: Window{1b19739 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity}
06-19 23:22:57.170: W/InputDispatcher(475): Attempted to unregister already unregistered input channel '1b19739 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)'
06-19 23:22:57.171: I/ActivityManager(475): Process org.mozilla.focus.debug (pid 12069) has died: fg  FGS 
06-19 23:22:57.176: I/Zygote(288): Process 12069 exited cleanly (11)
06-19 23:22:57.181: W/WindowManager(475): Cannot find window which accessibility connection is added to
06-19 23:22:57.182: W/WindowManager(475): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@e0f03ab
06-19 23:22:57.182: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.199: W/ActivityManager(475): Crash of app org.mozilla.focus.debug running instrumentation ComponentInfo{org.mozilla.focus.debug.test/androidx.test.runner.AndroidJUnitRunner}
06-19 23:22:57.199: I/ActivityManager(475): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-19 23:22:57.200: I/ActivityManager(475): Killing 12611:org.mozilla.focus.debug:tab6/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-19 23:22:57.200: I/ActivityManager(475): Killing 12743:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-19 23:22:57.201: I/ActivityManager(475): Killing 14651:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 (adj 200): stop org.mozilla.focus.debug due to finished inst
06-19 23:22:57.201: W/ActivityManager(475): Bringing down service while still waiting for start foreground: ServiceRecord{9cff706 u0 org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
06-19 23:22:57.202: W/ActivityManager(475): setHasOverlayUi called on unknown pid: 12069
06-19 23:22:57.197: I/chatty(1864): uid=1041(audioserver) writer identical 1 line
06-19 23:22:57.212: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.217: W/Binder(11971): Caught a RuntimeException from the binder stub implementation.
06-19 23:22:57.217: W/Binder(11971): java.lang.SecurityException: Calling from not trusted UID!
06-19 23:22:57.217: W/Binder(11971): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-19 23:22:57.217: W/Binder(11971): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-19 23:22:57.217: W/Binder(11971): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-19 23:22:57.217: W/Binder(11971): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-19 23:22:57.217: W/Binder(11971): 	at android.os.Binder.execTransact(Binder.java:1123)
06-19 23:22:57.220: I/libprocessgroup(475): Successfully killed process cgroup uid 10152 pid 12069 in 48ms
06-19 23:22:57.227: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.231: I/ActivityManager(475): Killing 10246:android.process.acore/u0a57 (adj 985): empty #17
06-19 23:22:57.257: I/chatty(1864): uid=1041(audioserver) writer identical 2 lines
06-19 23:22:57.272: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.278: D/AndroidRuntime(11971): Shutting down VM
06-19 23:22:57.287: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.294: D/CountryDetector(475): No listener is left
06-19 23:22:57.295: I/Zygote(288): Process 10246 exited due to signal 9 (Killed)
06-19 23:22:57.302: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.347: I/chatty(1864): uid=1041(audioserver) writer identical 3 lines
06-19 23:22:57.362: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.362: I/Zygote(288): Process 14651 exited due to signal 9 (Killed)
06-19 23:22:57.377: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.407: I/chatty(1864): uid=1041(audioserver) writer identical 2 lines
06-19 23:22:57.422: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.436: I/Zygote(288): Process 12743 exited cleanly (0)
06-19 23:22:57.436: I/Zygote(288): Process 12611 exited cleanly (0)
06-19 23:22:57.477: I/binder(0): undelivered transaction 953521, process died.
06-19 23:22:57.477: I/binder(0): undelivered transaction 953522, process died.
06-19 23:22:57.479: I/binder(0): undelivered transaction 953520, process died.
06-19 23:22:57.479: I/binder(0): undelivered transaction 953517, process died.
06-19 23:22:57.480: I/binder(0): undelivered transaction 953518, process died.
06-19 23:22:57.480: I/binder(0): undelivered transaction 953516, process died.
06-19 23:22:57.437: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.446: W/ProcessCpuTracker(475): Failed to stat(/proc/12611): android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
06-19 23:22:57.447: I/libprocessgroup(475): Successfully killed process cgroup uid 10152 pid 12611 in 226ms
06-19 23:22:57.447: I/libprocessgroup(475): Successfully killed process cgroup uid 10152 pid 12743 in 0ms
06-19 23:22:57.447: I/libprocessgroup(475): Successfully killed process cgroup uid 10152 pid 14651 in 0ms
06-19 23:22:57.447: I/libprocessgroup(475): Successfully killed process cgroup uid 10057 pid 10246 in 0ms
06-19 23:22:57.452: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.452: W/ProcessCpuTracker(475): Skipping unknown process pid 12611
06-19 23:22:57.452: W/ProcessCpuTracker(475): Failed to stat(/proc/12743): android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
06-19 23:22:57.452: W/ProcessCpuTracker(475): Skipping unknown process pid 12743
06-19 23:22:57.454: W/ProcessCpuTracker(475): Failed to stat(/proc/14680): android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
06-19 23:22:57.454: W/ProcessCpuTracker(475): Skipping unknown process pid 14680
06-19 23:22:57.454: W/ProcessCpuTracker(475): Failed to stat(/proc/14689): android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
06-19 23:22:57.454: W/ProcessCpuTracker(475): Skipping unknown process pid 14689
06-19 23:22:57.454: W/ProcessCpuTracker(475): Failed to stat(/proc/14694): android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
06-19 23:22:57.454: W/ProcessCpuTracker(475): Skipping unknown process pid 14694
06-19 23:22:57.454: W/ProcessCpuTracker(475): Failed to stat(/proc/14695): android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
06-19 23:22:57.454: W/ProcessCpuTracker(475): Skipping unknown process pid 14695
06-19 23:22:57.454: W/ProcessCpuTracker(475): Failed to stat(/proc/14696): android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
06-19 23:22:57.454: W/ProcessCpuTracker(475): Skipping unknown process pid 14696
06-19 23:22:57.454: W/ProcessCpuTracker(475): Failed to stat(/proc/14697): android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
06-19 23:22:57.454: W/ProcessCpuTracker(475): Skipping unknown process pid 14697
06-19 23:22:57.750: I/ActivityManager(475): Force stopping androidx.test.orchestrator appid=10145 user=0: finished inst
06-19 23:22:57.722: I/chatty(1864): uid=1041(audioserver) writer identical 18 lines
06-19 23:22:57.737: W/audio_hw_generic(1864): Hardware backing HAL too slow, could only write 0 of 661 frames
06-19 23:22:57.751: D/AndroidRuntime(11855): Shutting down VM

**Comment by sv-ohorvath** [comment]
closing as dupe, in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
Some test reports that have this same error in the logs contain the ANR notification, some don't, so until we can tell if they are different issues, I will log them in one place.
