### ISSUE TITLE
Intermittent UI test failure - < SafeBrowsingTest.blockHarmfulPageTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7254]
### Stacktrace:
06-20 13:28:38.349: I/WindowManager(485): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: ab28f4a org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5003ms for FocusEvent(hasFocus=false)
06-20 13:28:38.473: I/ActivityManager(485): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-20 13:28:38.474: I/ActivityManager(485): Killing 14199:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-20 13:28:38.460: I/chatty(1870): uid=1041(audioserver) writer identical 9 lines
06-20 13:28:38.475: W/audio_hw_generic(1870): Hardware backing HAL too slow, could only write 0 of 661 frames
06-20 13:28:38.478: W/Binder(14107): Caught a RuntimeException from the binder stub implementation.
06-20 13:28:38.478: W/Binder(14107): java.lang.SecurityException: Calling from not trusted UID!
06-20 13:28:38.478: W/Binder(14107): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-20 13:28:38.478: W/Binder(14107): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-20 13:28:38.478: W/Binder(14107): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-20 13:28:38.478: W/Binder(14107): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-20 13:28:38.478: W/Binder(14107): 	at android.os.Binder.execTransact(Binder.java:1123)
06-20 13:28:38.479: I/ServiceChildProcess(14809): Destroying GeckoServiceChildProcess
06-20 13:28:38.479: I/ServiceChildProcess(14702): Destroying GeckoServiceChildProcess
06-20 13:28:38.483: W/ActivityTaskManager(485): Force removing ActivityRecord{42c615 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-20 13:28:38.490: W/audio_hw_generic(1870): Hardware backing HAL too slow, could only write 0 of 661 frames
06-20 13:28:38.505: W/audio_hw_generic(1870): Hardware backing HAL too slow, could only write 0 of 661 frames
06-20 13:28:38.507: I/Gecko(14702): Exiting due to channel error.
06-20 13:28:38.508: I/Zygote(290): Process 14199 exited due to signal 9 (Killed)
06-20 13:28:38.513: D/AndroidRuntime(14107): Shutting down VM
06-20 13:28:38.520: W/audio_hw_generic(1870): Hardware backing HAL too slow, could only write 0 of 661 frames
06-20 13:28:38.521: I/ActivityManager(485): Killing 14702:org.mozilla.focus.debug:tab24/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-20 13:28:38.521: I/ActivityManager(485): Killing 14809:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-20 13:28:38.522: D/WindowManager(485): notifyANR took 176ms
### Notes: Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by sv-ohorvath** [comment]
Closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
