### ISSUE TITLE
Intermittent UI test failure - < EnhancedTrackingProtectionSettingsTest.allowAnalyticsTrackersTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7255]
### Stacktrace:
06-20 13:28:38.778: E/QueryController(13936): Got null root node from accessibility - Retrying...
06-20 13:28:38.860: D/BufferPoolAccessor2.0(410): evictor expired: 1, evicted: 0
06-20 13:28:38.862: D/BufferPoolAccessor2.0(424): bufferpool2 0xf5304648 : 0(0 size) total buffers - 0(0 size) used buffers - 90/97 (recycle/alloc) - 7/96 (fetch/transfer)
06-20 13:28:38.862: D/BufferPoolAccessor2.0(424): evictor expired: 1, evicted: 1
06-20 13:28:38.905: D/CompatibilityChangeReporter(481): Compat change id reported: 135634846; UID 10152; state: DISABLED
06-20 13:28:38.905: D/CompatibilityChangeReporter(481): Compat change id reported: 143937733; UID 10152; state: ENABLED
06-20 13:28:38.916: D/Zygote(290): Forked child process 16248
06-20 13:28:38.926: I/sh.CrashHandle(16248): Late-enabling -Xcheck:jni
06-20 13:28:38.939: I/cmd(16244): oneway function results will be dropped but finished with status OK and parcel size 4
06-20 13:28:38.939: I/ActivityManager(481): Start proc 16248:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 for service {org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
06-20 13:28:38.953: I/sh.CrashHandle(16248): Unquickening 12 vdex files!
06-20 13:28:38.955: W/sh.CrashHandle(16248): Unexpected CPU variant for X86 using defaults: x86
06-20 13:28:38.967: I/adbd(383): jdwp connection from 16248
06-20 13:28:39.097: I/Gecko(14357): Exiting due to channel error.
06-20 13:28:39.112: I/Zygote(290): Process 13936 exited cleanly (11)
06-20 13:28:39.151: I/binder(0): undelivered transaction 1293080, process died.
06-20 13:28:39.115: I/ActivityManager(481): Process org.mozilla.focus.debug (pid 13936) has died: fg  FGS 
06-20 13:28:39.117: I/WindowManager(481): WIN DEATH: Window{1f64332 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity}
06-20 13:28:39.117: W/InputDispatcher(481): Attempted to unregister already unregistered input channel '1f64332 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)'
06-20 13:28:39.125: I/libprocessgroup(481): Successfully killed process cgroup uid 10152 pid 13936 in 0ms
06-20 13:28:39.131: W/WindowManager(481): Cannot find window which accessibility connection is added to
06-20 13:28:39.139: W/WindowManager(481): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@da7bc3f
06-20 13:28:39.151: W/ActivityManager(481): Crash of app org.mozilla.focus.debug running instrumentation ComponentInfo{org.mozilla.focus.debug.test/androidx.test.runner.AndroidJUnitRunner}
06-20 13:28:39.151: I/ActivityManager(481): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-20 13:28:39.151: I/ActivityManager(481): Killing 14357:org.mozilla.focus.debug:tab20/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-20 13:28:39.152: I/ActivityManager(481): Killing 14483:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-20 13:28:39.152: I/ActivityManager(481): Killing 16248:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 (adj 200): stop org.mozilla.focus.debug due to finished inst
06-20 13:28:39.152: W/ActivityManager(481): Bringing down service while still waiting for start foreground: ServiceRecord{42b0ada u0 org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
06-20 13:28:39.162: I/Finsky(12985): [2] ukz.onTrimMemory(1): Memory trim requested to level 80
06-20 13:28:39.174: W/ActivityManager(481): setHasOverlayUi called on unknown pid: 13936
06-20 13:28:39.175: I/AppBase(2188): AppBase.onTrimMemory():615 onTrimMemory(): 5
06-20 13:28:39.177: W/Binder(13841): Caught a RuntimeException from the binder stub implementation.
06-20 13:28:39.177: W/Binder(13841): java.lang.SecurityException: Calling from not trusted UID!
06-20 13:28:39.177: W/Binder(13841): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-20 13:28:39.177: W/Binder(13841): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-20 13:28:39.177: W/Binder(13841): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-20 13:28:39.177: W/Binder(13841): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-20 13:28:39.177: W/Binder(13841): 	at android.os.Binder.execTransact(Binder.java:1123)
06-20 13:28:39.189: I/GoogleInputMethodService(2188): GoogleInputMethodService.onTrimMemory():4225 onTrimMemory(): 5
06-20 13:28:39.218: D/AndroidRuntime(13841): Shutting down VM
### Notes: Could be [#24047](https://github.com/mozilla-mobile/fenix/issues/24047) ❓

**Comment by AndiAJ** [comment]
Flaky 1x on 7/10 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5391892252101037820/executions/bs.1748ece423fa539f/testcases/1)

07-10 08:56:04.228: I/WindowManager(477): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 98c839d org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5001ms for FocusEvent(hasFocus=false)
07-10 08:56:04.321: I/ActivityManager(477): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
07-10 08:56:04.321: I/ActivityManager(477): Killing 14120:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-10 08:56:04.298: I/chatty(1861): uid=1041(audioserver) writer identical 6 lines
07-10 08:56:04.313: W/audio_hw_generic(1861): Hardware backing HAL too slow, could only write 0 of 661 frames
07-10 08:56:04.322: W/Binder(14026): Caught a RuntimeException from the binder stub implementation.
07-10 08:56:04.322: W/Binder(14026): java.lang.SecurityException: Calling from not trusted UID!
07-10 08:56:04.322: W/Binder(14026): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
07-10 08:56:04.322: W/Binder(14026): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
07-10 08:56:04.322: W/Binder(14026): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
07-10 08:56:04.322: W/Binder(14026): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
07-10 08:56:04.322: W/Binder(14026): 	at android.os.Binder.execTransact(Binder.java:1123)
07-10 08:56:04.323: W/ActivityTaskManager(477): Force removing ActivityRecord{87e87 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
07-10 08:56:04.327: W/audio_hw_generic(1861): Hardware backing HAL too slow, could only write 0 of 661 frames
07-10 08:56:04.338: I/ServiceChildProcess(14719): Destroying GeckoServiceChildProcess
07-10 08:56:04.343: W/audio_hw_generic(1861): Hardware backing HAL too slow, could only write 0 of 661 frames
07-10 08:56:04.353: I/ServiceChildProcess(14612): Destroying GeckoServiceChildProcess
07-10 08:56:04.356: D/AndroidRuntime(14026): Shutting down VM
07-10 08:56:04.357: I/ActivityManager(477): Killing 14612:org.mozilla.focus.debug:tab31/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-10 08:56:04.358: W/audio_hw_generic(1861): Hardware backing HAL too slow, could only write 0 of 661 frames
07-10 08:56:04.359: I/ActivityManager(477): Killing 14719:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-10 08:56:04.360: D/WindowManager(477): notifyANR took 141ms

**Comment by sv-ohorvath** [comment]
Some comments with ANR reports are hidden as dupe, in favor of https://github.com/mozilla-mobile/focus-android/issues/7344

**Comment by sv-ohorvath** [comment]
closing as dupe, in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
Some test reports that have this same error in the logs contain the ANR notification, some don't, so until we can tell if they are different issues, I will log them in one place.
