### ISSUE TITLE
28ms regression to cold main first frame start up (glean metric native library load?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#7261]
We go from 677ms (6/16 Nightly) to 705ms (6/17 Nightly):

![image](https://user-images.githubusercontent.com/759372/174899790-a926ac1b-146d-4fc7-9e2c-137106fda956.png)

There may be an additional regression into 6/18 or 6/19 (since it's higher than 6/17) but it is hard for me to determine that through the data so I only filed this bug.

_edit: the day after, 6/18, regresses another 34ms (before stabilizing at a slightly lower value for a few days:_
![image](https://user-images.githubusercontent.com/759372/177825628-0a097bda-e1d7-466d-9121-21e8bec17e5d.png)

_We should consider investigating these together. I filed https://github.com/mozilla-mobile/focus-android/issues/7336 so we don't forget to look into it._

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802636

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
