### ISSUE TITLE
Intermittent UI test failure - < LocalSessionStorageTest.eraseCookiesTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7271]
### Stacktrace:
6-23 00:53:58.191: E/QueryController(13652): Got null root node from accessibility - Retrying...
06-23 00:53:58.204: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.219: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.230: D/StrictMode(13652): StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
06-23 00:53:58.230: D/StrictMode(13652): 	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1924)
06-23 00:53:58.230: D/StrictMode(13652): 	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:303)
06-23 00:53:58.230: D/StrictMode(13652): 	at android.view.Surface.finalize(Surface.java:274)
06-23 00:53:58.230: D/StrictMode(13652): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
06-23 00:53:58.230: D/StrictMode(13652): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
06-23 00:53:58.230: D/StrictMode(13652): 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
06-23 00:53:58.230: D/StrictMode(13652): 	at java.lang.Thread.run(Thread.java:923)
06-23 00:53:58.230: D/StrictMode(13652): Caused by: java.lang.Throwable: Explicit termination method 'release' not called
06-23 00:53:58.230: D/StrictMode(13652): 	at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:259)
06-23 00:53:58.230: D/StrictMode(13652): 	at dalvik.system.CloseGuard.open(CloseGuard.java:230)
06-23 00:53:58.230: D/StrictMode(13652): 	at android.view.Surface.setNativeObjectLocked(Surface.java:682)
06-23 00:53:58.230: D/StrictMode(13652): 	at android.view.Surface.copyFrom(Surface.java:567)
06-23 00:53:58.230: D/StrictMode(13652): 	at android.view.Surface.<init>(Surface.java:232)
06-23 00:53:58.230: D/StrictMode(13652): 	at org.mozilla.gecko.gfx.SurfaceControlManager.getChildSurface(SurfaceControlManager.java:76)
06-23 00:53:58.230: D/StrictMode(13652): 	at org.mozilla.geckoview.GeckoSession$Compositor.syncResumeResizeCompositor(Native Method)
06-23 00:53:58.230: D/StrictMode(13652): 	at org.mozilla.geckoview.GeckoSession.onSurfaceChanged(GeckoSession.java:5963)
06-23 00:53:58.230: D/StrictMode(13652): 	at org.mozilla.geckoview.GeckoSession.onCompositorReady(GeckoSession.java:6141)
06-23 00:53:58.230: D/StrictMode(13652): 	at org.mozilla.geckoview.GeckoSession$$ExternalSyntheticLambda0.run(Unknown Source:2)
06-23 00:53:58.230: D/StrictMode(13652): 	at android.os.Handler.handleCallback(Handler.java:938)
06-23 00:53:58.230: D/StrictMode(13652): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-23 00:53:58.230: D/StrictMode(13652): 	at android.os.Looper.loop(Looper.java:223)
06-23 00:53:58.230: D/StrictMode(13652): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
06-23 00:53:58.230: D/StrictMode(13652): 	at java.lang.reflect.Method.invoke(Native Method)
06-23 00:53:58.230: D/StrictMode(13652): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-23 00:53:58.230: D/StrictMode(13652): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-23 00:53:58.231: D/StrictMode(13652): StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. Callsite: SurfaceControl.Builder
06-23 00:53:58.231: D/StrictMode(13652): 	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1929)
06-23 00:53:58.231: D/StrictMode(13652): 	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:305)
06-23 00:53:58.231: D/StrictMode(13652): 	at android.view.SurfaceControl.finalize(SurfaceControl.java:1104)
06-23 00:53:58.231: D/StrictMode(13652): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
06-23 00:53:58.231: D/StrictMode(13652): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
06-23 00:53:58.231: D/StrictMode(13652): 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
06-23 00:53:58.231: D/StrictMode(13652): 	at java.lang.Thread.run(Thread.java:923)
06-23 00:53:58.234: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.427: D/CompatibilityChangeReporter(477): Compat change id reported: 135634846; UID 10152; state: DISABLED
06-23 00:53:58.413: I/chatty(1802): uid=1041(audioserver) writer identical 12 lines
06-23 00:53:58.428: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.439: I/PeriodicStatsRunner(2198): PeriodicStatsRunner.call():180 call()
06-23 00:53:58.439: I/PeriodicStatsRunner(2198): PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
06-23 00:53:58.443: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.450: D/CompatibilityChangeReporter(477): Compat change id reported: 143937733; UID 10152; state: ENABLED
06-23 00:53:58.452: I/cmd(16105): oneway function results will be dropped but finished with status OK and parcel size 4
06-23 00:53:58.458: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.464: D/Zygote(290): Forked child process 16116
06-23 00:53:58.473: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.482: I/InputManager(477): Enabling motion classifier because timeout changed: feature enabled, long press timeout = 400
06-23 00:53:58.482: I/InputClassifier(477): Enabling motion classifier
06-23 00:53:58.488: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.495: I/sh.CrashHandle(16116): Late-enabling -Xcheck:jni
06-23 00:53:58.503: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.504: I/cmd(16118): oneway function results will be dropped but finished with status OK and parcel size 4
06-23 00:53:58.518: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.519: I/sh.CrashHandle(16116): Unquickening 12 vdex files!
06-23 00:53:58.520: W/sh.CrashHandle(16116): Unexpected CPU variant for X86 using defaults: x86
06-23 00:53:58.554: I/binder(0): 477:16121 BC_REQUEST_DEATH_NOTIFICATION death notification already set
06-23 00:53:58.532: I/adbd(379): jdwp connection from 16116
06-23 00:53:58.533: W/ActivityManager(477): Slow operation: 106ms so far, now at startProcess: returned from zygote!
06-23 00:53:58.535: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.566: W/ActivityManager(477): Slow operation: 139ms so far, now at startProcess: done updating battery stats
06-23 00:53:58.566: W/ActivityManager(477): Slow operation: 139ms so far, now at startProcess: building log message
06-23 00:53:58.566: I/ActivityManager(477): Start proc 16116:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 for service {org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
06-23 00:53:58.566: W/ActivityManager(477): Slow operation: 139ms so far, now at startProcess: starting to update pids map
06-23 00:53:58.566: W/ActivityManager(477): Slow operation: 139ms so far, now at startProcess: done updating pids map
06-23 00:53:58.683: I/chatty(1802): uid=1041(audioserver) writer identical 10 lines
06-23 00:53:58.698: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.704: I/Gecko(14143): Exiting due to channel error.
06-23 00:53:58.713: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.809: I/binder(0): undelivered transaction 1214485, process died.
06-23 00:53:58.768: I/WindowManager(477): WIN DEATH: Window{c4cc23f u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity}
06-23 00:53:58.743: I/chatty(1802): uid=1041(audioserver) writer identical 2 lines
06-23 00:53:58.758: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.768: W/InputDispatcher(477): Attempted to unregister already unregistered input channel 'c4cc23f org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)'
06-23 00:53:58.770: I/ActivityManager(477): Process org.mozilla.focus.debug (pid 13652) has died: fg  FGS 
06-23 00:53:58.771: W/WindowManager(477): Cannot find window which accessibility connection is added to
06-23 00:53:58.773: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.774: W/WindowManager(477): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@73c716
06-23 00:53:58.796: W/ActivityManager(477): Crash of app org.mozilla.focus.debug running instrumentation ComponentInfo{org.mozilla.focus.debug.test/androidx.test.runner.AndroidJUnitRunner}
06-23 00:53:58.796: I/ActivityManager(477): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-23 00:53:58.806: I/ActivityManager(477): Killing 14143:org.mozilla.focus.debug:tab35/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-23 00:53:58.807: I/ActivityManager(477): Killing 14294:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-23 00:53:58.808: I/ActivityManager(477): Killing 16116:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 (adj 200): stop org.mozilla.focus.debug due to finished inst
06-23 00:53:58.808: W/ActivityManager(477): Bringing down service while still waiting for start foreground: ServiceRecord{101b3ba u0 org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
06-23 00:53:58.893: I/binder(0): undelivered transaction 1214668, process died.
06-23 00:53:58.895: I/binder(0): undelivered transaction 1214669, process died.
06-23 00:53:58.899: I/binder(0): undelivered transaction 1214667, process died.
06-23 00:53:58.818: W/ActivityManager(477): setHasOverlayUi called on unknown pid: 13652
06-23 00:53:58.803: I/chatty(1802): uid=1041(audioserver) writer identical 2 lines
06-23 00:53:58.818: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.821: W/Binder(13545): Caught a RuntimeException from the binder stub implementation.
06-23 00:53:58.821: W/Binder(13545): java.lang.SecurityException: Calling from not trusted UID!
06-23 00:53:58.821: W/Binder(13545): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-23 00:53:58.821: W/Binder(13545): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-23 00:53:58.821: W/Binder(13545): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-23 00:53:58.821: W/Binder(13545): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-23 00:53:58.821: W/Binder(13545): 	at android.os.Binder.execTransact(Binder.java:1123)
06-23 00:53:58.833: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.835: I/Zygote(290): Process 13652 exited cleanly (11)
06-23 00:53:58.841: I/libprocessgroup(477): Successfully killed process cgroup uid 10152 pid 13652 in 41ms
06-23 00:53:58.849: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.853: I/Zygote(290): Process 14143 exited cleanly (0)
06-23 00:53:58.863: W/audio_hw_generic(1802): Hardware backing HAL too slow, could only write 0 of 661 frames
06-23 00:53:58.865: D/AndroidRuntime(13545): Shutting down VM
### Notes: Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8228378861382884214/executions/bs.4f90aa42939f89e7/test-cases)

07-02 08:32:35.244: E/QueryController(12184): Got null root node from accessibility - Retrying...
07-02 08:32:35.246: D/SharedPreferencesImpl(12184): Time required to fsync /data/user/0/org.mozilla.focus.debug/shared_prefs/org.mozilla.focus.debug_preferences.xml: [<1: 0, <2: 0, <4: 2, <8: 0, <16: 1, <32: 0, <64: 0, <128: 0, <256: 2, <512: 0, <1024: 0, <2048: 0, <4096: 0, <8192: 1, <16384: 0, >=16384: 0]
07-02 08:32:35.250: W/audio_hw_generic(1883): Hardware backing HAL too slow, could only write 0 of 661 frames
07-02 08:32:35.325: I/chatty(1883): uid=1041(audioserver) writer identical 5 lines
07-02 08:32:35.340: W/audio_hw_generic(1883): Hardware backing HAL too slow, could only write 0 of 661 frames
07-02 08:32:35.343: I/PeriodicStatsRunner(2190): PeriodicStatsRunner.call():180 call()
07-02 08:32:35.343: I/PeriodicStatsRunner(2190): PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
07-02 08:32:35.355: W/audio_hw_generic(1883): Hardware backing HAL too slow, could only write 0 of 661 frames
07-02 08:32:35.512: D/CompatibilityChangeReporter(475): Compat change id reported: 135634846; UID 10152; state: DISABLED
07-02 08:32:35.588: W/ActivityManager(475): Slow operation: 76ms so far, now at startProcess: done starting proc!
07-02 08:32:35.593: W/ActivityManager(475): Slow operation: 81ms so far, now at startProcess: asking zygote to start proc
07-02 08:32:35.593: D/CompatibilityChangeReporter(475): Compat change id reported: 143937733; UID 10152; state: ENABLED
07-02 08:32:35.580: I/chatty(1883): uid=1041(audioserver) writer identical 15 lines
07-02 08:32:35.595: W/audio_hw_generic(1883): Hardware backing HAL too slow, could only write 0 of 661 frames
07-02 08:32:35.599: I/cmd(15011): oneway function results will be dropped but finished with status OK and parcel size 4
07-02 08:32:35.599: E/JobScheduler.Background(475): App com.google.android.gms became active but still in NEVER bucket
07-02 08:32:35.604: I/DropBoxManagerService(475): add tag=system_server_wtf isTagEnabled=true flags=0x2
07-02 08:32:35.608: D/Zygote(290): Forked child process 15024
07-02 08:32:35.609: W/ActivityManager(475): Slow operation: 97ms so far, now at startProcess: returned from zygote!
07-02 08:32:35.609: W/ActivityManager(475): Slow operation: 97ms so far, now at startProcess: done updating battery stats
07-02 08:32:35.609: W/ActivityManager(475): Slow operation: 97ms so far, now at startProcess: building log message
07-02 08:32:35.609: I/ActivityManager(475): Start proc 15024:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 for service {org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
07-02 08:32:35.609: W/ActivityManager(475): Slow operation: 97ms so far, now at startProcess: starting to update pids map
07-02 08:32:35.609: W/ActivityManager(475): Slow operation: 97ms so far, now at startProcess: done updating pids map
07-02 08:32:35.610: W/audio_hw_generic(1883): Hardware backing HAL too slow, could only write 0 of 661 frames
07-02 08:32:35.625: W/audio_hw_generic(1883): Hardware backing HAL too slow, could only write 0 of 661 frames
07-02 08:32:35.636: I/sh.CrashHandle(15024): Late-enabling -Xcheck:jni
07-02 08:32:35.640: W/audio_hw_generic(1883): Hardware backing HAL too slow, could only write 0 of 661 frames
07-02 08:32:35.662: I/sh.CrashHandle(15024): Unquickening 12 vdex files!
07-02 08:32:35.663: W/sh.CrashHandle(15024): Unexpected CPU variant for X86 using defaults: x86
07-02 08:32:35.670: I/adbd(379): jdwp connection from 15024
07-02 08:32:35.683: W/audio_hw_generic(1883): Not supplying enough data to HAL, expected position 1145699 , only wrote 932010
07-02 08:32:35.684: I/system_server(475): oneway function results will be dropped but finished with status OK and parcel size 4
07-02 08:32:35.693: I/InputManager(475): Enabling motion classifier because timeout changed: feature enabled, long press timeout = 400
07-02 08:32:35.693: I/InputClassifier(475): Enabling motion classifier
07-02 08:32:35.765: I/binder(0): 475:15054 BC_REQUEST_DEATH_NOTIFICATION death notification already set
07-02 08:32:35.764: D/BufferPoolAccessor2.0(421): evictor expired: 1, evicted: 0
07-02 08:32:35.865: I/Gecko(12651): Exiting due to channel error.
07-02 08:32:35.909: I/binder(0): undelivered TRANSACTION_COMPLETE
07-02 08:32:35.909: I/binder(0): undelivered transaction 993960, process died.
07-02 08:32:35.910: I/binder(0): undelivered transaction 994036, process died.
07-02 08:32:35.873: I/ActivityManager(475): Process org.mozilla.focus.debug (pid 12184) has died: fg  FGS 
07-02 08:32:35.879: I/Zygote(290): Process 12184 exited cleanly (11)
07-02 08:32:35.887: I/WindowManager(475): WIN DEATH: Window{aa107d9 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity}
07-02 08:32:35.887: W/InputDispatcher(475): Attempted to unregister already unregistered input channel 'aa107d9 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)'
07-02 08:32:35.904: W/WindowManager(475): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@9ab5dd2
07-02 08:32:35.915: I/libprocessgroup(475): Successfully killed process cgroup uid 10152 pid 12184 in 42ms
07-02 08:32:35.916: W/ActivityManager(475): Crash of app org.mozilla.focus.debug running instrumentation ComponentInfo{org.mozilla.focus.debug.test/androidx.test.runner.AndroidJUnitRunner}
07-02 08:32:35.966: I/ActivityManager(475): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
07-02 08:32:35.967: I/ActivityManager(475): Killing 12651:org.mozilla.focus.debug:tab12/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-02 08:32:35.968: I/ActivityManager(475): Killing 12737:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-02 08:32:36.012: I/binder(0): undelivered transaction 994168, process died.
07-02 08:32:36.012: I/binder(0): undelivered transaction 994169, process died.
07-02 08:32:36.012: I/binder(0): undelivered transaction 994167, process died.
07-02 08:32:35.968: I/ActivityManager(475): Killing 15024:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 (adj 200): stop org.mozilla.focus.debug due to finished inst
07-02 08:32:35.969: W/ActivityManager(475): Bringing down service while still waiting for start foreground: ServiceRecord{afe81e9 u0 org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
07-02 08:32:35.972: I/Zygote(290): Process 12651 exited cleanly (0)
07-02 08:32:35.977: D/AndroidRuntime(12090): Shutting down VM

**Comment by sv-ohorvath** [comment]
closing as dupe, in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
Some test reports that have this same error in the logs contain the ANR notification, some don't, so until we can tell if they are different issues, I will log them in one place.
