### ISSUE TITLE
Intermittent UI test failure - < EnhancedTrackingProtectionSettingsTest.allowAdTrackersTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7272]
Notes: ANR report moved to #7344
We will keep this issue for the[ next fail report,](https://github.com/mozilla-mobile/focus-android/issues/7272#issuecomment-1165398906) not yet confirmed the same as the ANR

**Comment by AndiAJ** [comment]
Flaky 1x on 7/1/ Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9124776387917112329/executions/bs.95e34232f8636fc2)

07-01 03:41:22.229: I/WindowManager(482): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 63dd1d8 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=false)
07-01 03:41:22.214: I/chatty(1829): uid=1041(audioserver) writer identical 117 lines
07-01 03:41:22.229: W/audio_hw_generic(1829): Hardware backing HAL too slow, could only write 0 of 661 frames
07-01 03:41:22.241: E/QueryController(14243): Got null root node from accessibility - Retrying...
07-01 03:41:22.244: W/audio_hw_generic(1829): Hardware backing HAL too slow, could only write 0 of 661 frames
07-01 03:41:22.379: I/chatty(1829): uid=1041(audioserver) writer identical 9 lines
07-01 03:41:22.394: W/audio_hw_generic(1829): Hardware backing HAL too slow, could only write 0 of 661 frames
07-01 03:41:22.396: D/GeckoViewProgressDelegate[C](14749): handleEvent: MozAfterPaint
07-01 03:41:22.398: D/GeckoViewProgress(14243): receiveMessage: MozAfterPaint
07-01 03:41:22.406: D/GeckoViewContent(14243): handleEvent: DOMWindowClose
07-01 03:41:22.409: W/audio_hw_generic(1829): Hardware backing HAL too slow, could only write 0 of 661 frames
07-01 03:41:22.411: D/GeckoViewSelectionActionDelegate[C](14749): handleEvent: visibilitychange
07-01 03:41:22.418: D/GeckoViewNavigation(14243): onDisable
07-01 03:41:22.419: D/GeckoViewProcessHangMonitor(14243): onDisable
07-01 03:41:22.419: D/GeckoViewModule(14243): unregisterListener
07-01 03:41:22.419: D/GeckoViewProcessHangMonitor(14243): onDestroy
07-01 03:41:22.419: D/GeckoViewProgress(14243): onDisable
07-01 03:41:22.419: D/GeckoViewModule(14243): unregisterListener
07-01 03:41:22.420: D/GeckoViewSelectionAction(14243): onDisable
07-01 03:41:22.420: D/GeckoViewModule(14243): unregisterListener
07-01 03:41:22.421: D/GeckoViewModule(14243): unregisterListener
07-01 03:41:22.421: D/GeckoViewMediaControl(14243): onDisable
07-01 03:41:22.422: D/GeckoViewModule(14243): unregisterListener
07-01 03:41:22.424: W/audio_hw_generic(1829): Hardware backing HAL too slow, could only write 0 of 661 frames
07-01 03:41:22.428: D/GeckoViewSelectionActionDelegate[C](14749): handleEvent: visibilitychange
07-01 03:41:22.429: D/GeckoViewAutoFill[C](14749): handleEvent: pagehide
07-01 03:41:22.438: I/Choreographer(14243): Skipped 312 frames!  The application may be doing too much work on its main thread.
07-01 03:41:22.439: W/audio_hw_generic(1829): Hardware backing HAL too slow, could only write 0 of 661 frames
07-01 03:41:22.464: I/ActivityManager(482): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
07-01 03:41:22.464: I/ActivityManager(482): Killing 14243:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-01 03:41:22.470: W/ActivityTaskManager(482): Force removing ActivityRecord{5d8d204 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
07-01 03:41:22.454: W/audio_hw_generic(1829): Hardware backing HAL too slow, could only write 0 of 661 frames
07-01 03:41:22.471: W/Binder(14156): Caught a RuntimeException from the binder stub implementation.
07-01 03:41:22.471: W/Binder(14156): java.lang.SecurityException: Calling from not trusted UID!
07-01 03:41:22.471: W/Binder(14156): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
07-01 03:41:22.471: W/Binder(14156): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
07-01 03:41:22.471: W/Binder(14156): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
07-01 03:41:22.471: W/Binder(14156): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
07-01 03:41:22.471: W/Binder(14156): 	at android.os.Binder.execTransact(Binder.java:1123)
07-01 03:41:22.474: W/audio_hw_generic(1829): Hardware backing HAL too slow, could only write 0 of 661 frames
07-01 03:41:22.482: I/ActivityManager(482): Killing 14749:org.mozilla.focus.debug:tab26/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-01 03:41:22.499: I/chatty(1829): uid=1041(audioserver) writer identical 2 lines
07-01 03:41:22.514: W/audio_hw_generic(1829): Hardware backing HAL too slow, could only write 0 of 661 frames
07-01 03:41:22.517: D/AndroidRuntime(14156): Shutting down VM
07-01 03:41:22.518: I/ActivityManager(482): Killing 14904:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-01 03:41:22.520: D/WindowManager(482): notifyANR took 296ms

**Comment by AndiAJ** [comment]
Flaky 1x on 7/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6164824543449132742/executions/bs.a305be01410e480c)

07-03 08:11:58.265: I/WindowManager(478): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 9ecddf6 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false)
07-03 08:11:58.270: W/audio_hw_generic(1878): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:11:58.498: I/ActivityManager(478): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
07-03 08:11:58.498: I/ActivityManager(478): Killing 11839:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-03 08:11:58.480: I/chatty(1878): uid=1041(audioserver) writer identical 14 lines
07-03 08:11:58.495: W/audio_hw_generic(1878): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:11:58.502: W/Binder(11689): Caught a RuntimeException from the binder stub implementation.
07-03 08:11:58.502: W/Binder(11689): java.lang.SecurityException: Calling from not trusted UID!
07-03 08:11:58.502: W/Binder(11689): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
07-03 08:11:58.502: W/Binder(11689): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
07-03 08:11:58.502: W/Binder(11689): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
07-03 08:11:58.502: W/Binder(11689): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
07-03 08:11:58.502: W/Binder(11689): 	at android.os.Binder.execTransact(Binder.java:1123)
07-03 08:11:58.506: W/ActivityTaskManager(478): Force removing ActivityRecord{49d6117 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
07-03 08:11:58.507: I/ServiceChildProcess(12592): Destroying GeckoServiceChildProcess
07-03 08:11:58.510: W/audio_hw_generic(1878): Hardware backing HAL too slow, could only write 0 of 661 frames
07-03 08:11:58.511: I/ActivityManager(478): Killing 12592:org.mozilla.focus.debug:tab22/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-03 08:11:58.523: I/ActivityManager(478): Killing 12706:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
07-03 08:11:58.527: D/WindowManager(478): notifyANR took 272ms

**Comment by sv-ohorvath** [comment]
closing as dupe afterall, in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
Some test reports that have this same error in the logs contain the ANR notification, some don't, so until we can tell if they are different issues, I will log them in one place.
