### ISSUE TITLE
The Play/Pause button does not remain displayed on the media notification

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7289]
## Steps to reproduce
1. Go to a website with audio content, like soundcloud.com.
2. Play the audio stream.
3. Invoke the notifications bar.
4. Tap the Pause/Play button several times from the media notification.
5. Observe the media notification.

### Expected behavior
The Play/Pause button should is displayed on the media notification.

### Actual behavior
After tapping on the Play/Pause button for several times, it disappears from the media notification. 
Playing/pausing the audio stream from the application, doesn't restore the Play/Pause button on the media notification.
Playing/pausing the audio from a different app (like Fenix), restores the button on the Focus media notification until the user is using the Focus Beta Play/Pause button again.

### Device information
* Android device: Lenovo tablet M10 (aAndroid 10), Oppo Reno 6 (Android 12)
* Focus version: Beta 103.0.0-beta.1, RC 102.1.1
* NOT reproducible on Focus Nightly 104.0a1 from 6/28
* Please see #6758 

![Screenshot_2](https://user-images.githubusercontent.com/40694158/176178084-d4bd067b-6bc2-4941-91a5-3c064261ae4b.jpg)

https://user-images.githubusercontent.com/40694158/176177970-627f0f2c-0b48-4569-93d1-49e157ae146d.mp4

**Comment by lobontiumira** [comment]
Reproducible on Oppo Reno 6 (Android 12) on Beta 103.0.0-beta.2 build.

**Comment by Mugurell** [comment]
Looked at this a little with Gabriel, seems like there is a deeper issue with the `MediaSessionFeature` / `MediaSessionServiceDelegate` - a race between 
- posting a "dummy notification" from `MediaSessionFeature` when the service starts - and it [is always started](https://github.com/mozilla-mobile/android-components/blob/6c0fe91ab83614265f533b819bf406fc046b2227/components/feature/media/src/main/java/mozilla/components/feature/media/MediaSessionFeature.kt#L65-L71) when [media starts/resumes playing](https://github.com/mozilla-mobile/android-components/blob/6c0fe91ab83614265f533b819bf406fc046b2227/components/feature/media/src/main/java/mozilla/components/feature/media/MediaSessionFeature.kt#L40-L47) and 
- updating the already existent notification from `MediaSessionServiceDelegate` [for all playback changes](https://github.com/mozilla-mobile/android-components/blob/6c0fe91ab83614265f533b819bf406fc046b2227/components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt#L135-L137).

The service is also started and stopped [when playback resumes / is paused](https://github.com/mozilla-mobile/android-components/blob/6c0fe91ab83614265f533b819bf406fc046b2227/components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt#L119-L127) which causes the notification to flicker and contributes to this bug.
If we would start the service only once and keep is alive while the notification is shown then both the flicker and the missing action buttons bug would dissapear.

This issue affects Fenix also and although it is more easily reproducible in private mode it happens in normal browsing mode also.

https://user-images.githubusercontent.com/11428869/177268745-f7ffdceb-d489-4a87-b583-f079ebb4cfa5.mp4

cc @rocketsroger

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Beta 103.0.0-beta.5, RC 103.1.0, and Nightly 104.0a1 with the following devices:
* Oppo Reno 6 (Android 12),
* Lenovo tablet M10 (Android 10), and
* Samsung Galaxy Note 8 (Android 9).
