### ISSUE TITLE
"Open with Firefox Beta" shown twice in 3-dot menu

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#729]
I have Focus (Beta) installed from Buddybuild & Firefox Beta installed from the Play Store. I have no other versions of Firefox installed.

In the 3-dot menu, I see:
![screenshot_2017-06-07-12-56-40](https://user-images.githubusercontent.com/759372/26898560-454ba988-4b81-11e7-87c3-39aaedd7f382.png)

I think Sebastian mentioned this could be related to how we encourage the user to go to the Play Store to install Firefox & how we display the default app to open in.

**Comment by pocmo** [comment]
I pushed a patch for this to master. In this use case we showed two items:
* A) The most stable (installed) Firefox
* B) The default browser

We do not show the default browser item if the default browser is Firefox. I extended this to match the (new) behavior of the Firefox item: Do not show the default browser item if it is the same as the Firefox branded browser we already show (Release, Beta, Aurora, Nightly).
