### ISSUE TITLE
Intermittent UI test failure - < WebControlsTest. telephoneLinkTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7294]
### Stacktrace:
06-28 12:55:35.765: I/WindowManager(471): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: d86e837 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false)
06-28 12:55:35.857: I/Finsky(12596): [2] abwt.b(5): SCH: Jobs in database: 1-1337 2-48879 3-3 10-78 24-77777777 26-1414141414 31-305419896 
06-28 12:55:35.863: I/Finsky(12596): [2] abvf.d(37): SCH: ConstraintMapping: 24-77777777,  -> L: 0ms, D: 81104194ms, C: false, I: true, N: 0
06-28 12:55:35.863: I/Finsky(12596): [2] abvf.d(37): SCH: ConstraintMapping: 1-1337, 31-305419896,  -> L: 0ms, D: 62086847ms, C: false, I: false, N: 1
06-28 12:55:35.864: I/Finsky(12596): [2] abvf.d(37): SCH: ConstraintMapping: 10-78,  -> L: 0ms, D: 84698370ms, C: false, I: true, N: 1
06-28 12:55:35.864: I/Finsky(12596): [2] abvf.d(37): SCH: ConstraintMapping: 2-48879, 3-3,  -> L: 0ms, D: 84698301ms, C: true, I: true, N: 2
06-28 12:55:35.864: I/Finsky(12596): [2] abvf.d(37): SCH: ConstraintMapping: 26-1414141414,  -> L: 42591267ms, D: 43491267ms, C: false, I: false, N: 0
06-28 12:55:35.885: W/ActivityManager(471): Slow operation: 105ms so far, now at startProcess: done creating new process record
06-28 12:55:35.885: W/ActivityManager(471): Slow operation: 106ms so far, now at startProcess: stepping in to startProcess
06-28 12:55:35.885: D/CompatibilityChangeReporter(471): Compat change id reported: 135634846; UID 10097; state: DISABLED
06-28 12:55:35.886: W/ActivityManager(471): Slow operation: 106ms so far, now at startProcess: done starting proc!
06-28 12:55:35.888: D/CompatibilityChangeReporter(471): Compat change id reported: 143937733; UID 10097; state: ENABLED
06-28 12:55:35.907: I/ActivityManager(471): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-28 12:55:35.907: I/ActivityManager(471): Killing 13527:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-28 12:55:35.910: W/ActivityTaskManager(471): Force removing ActivityRecord{77e2938 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-28 12:55:35.914: W/Binder(13433): Caught a RuntimeException from the binder stub implementation.
06-28 12:55:35.914: W/Binder(13433): java.lang.SecurityException: Calling from not trusted UID!
06-28 12:55:35.914: W/Binder(13433): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-28 12:55:35.914: W/Binder(13433): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-28 12:55:35.914: W/Binder(13433): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-28 12:55:35.914: W/Binder(13433): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-28 12:55:35.914: W/Binder(13433): 	at android.os.Binder.execTransact(Binder.java:1123)
06-28 12:55:35.920: I/ServiceChildProcess(14141): Destroying GeckoServiceChildProcess
06-28 12:55:35.921: I/ServiceChildProcess(14023): Destroying GeckoServiceChildProcess
06-28 12:55:35.922: I/Gecko(14023): Exiting due to channel error.
06-28 12:55:35.929: D/Zygote(290): Forked child process 15081
06-28 12:55:35.932: I/ActivityManager(471): Killing 14023:org.mozilla.focus.debug:tab35/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-28 12:55:35.940: I/ActivityManager(471): Killing 14141:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-28 12:55:35.942: D/WindowManager(471): notifyANR took 290ms
### Notes: Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by sv-ohorvath** [comment]
closing as dupe, in favor if https://github.com/mozilla-mobile/focus-android/issues/7344
