### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest.verifyCookiesEnabledTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7297]
### Stacktrace:
06-29 01:04:13.052: I/WindowManager(480): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: a9c539 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5003ms for FocusEvent(hasFocus=false)
06-29 01:04:13.055: I/chatty(1863): uid=1041(audioserver) writer identical 1 line
06-29 01:04:13.070: W/audio_hw_generic(1863): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 01:04:13.076: I/Finsky:download_service(12869): [922] nmi.run(36): Stats for Executor: bgExecutor non@82def57[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
06-29 01:04:13.085: W/audio_hw_generic(1863): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 01:04:13.169: I/ActivityManager(480): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-29 01:04:13.169: I/ActivityManager(480): Killing 13711:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 01:04:13.145: I/chatty(1863): uid=1041(audioserver) writer identical 4 lines
06-29 01:04:13.160: W/audio_hw_generic(1863): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 01:04:13.174: W/Binder(13610): Caught a RuntimeException from the binder stub implementation.
06-29 01:04:13.174: W/Binder(13610): java.lang.SecurityException: Calling from not trusted UID!
06-29 01:04:13.174: W/Binder(13610): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-29 01:04:13.174: W/Binder(13610): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-29 01:04:13.174: W/Binder(13610): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-29 01:04:13.174: W/Binder(13610): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-29 01:04:13.174: W/Binder(13610): 	at android.os.Binder.execTransact(Binder.java:1123)
06-29 01:04:13.175: W/audio_hw_generic(1863): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 01:04:13.177: I/ServiceChildProcess(14129): Destroying GeckoServiceChildProcess
06-29 01:04:13.179: W/ActivityTaskManager(480): Force removing ActivityRecord{e241fe3 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-29 01:04:13.184: I/ActivityManager(480): Killing 14129:org.mozilla.focus.debug:tab35/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 01:04:13.185: I/ActivityManager(480): Killing 14247:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 01:04:13.190: W/audio_hw_generic(1863): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 01:04:13.191: D/WindowManager(480): notifyANR took 149ms

**Comment by sv-ohorvath** [comment]
closing as dupe, in favor if https://github.com/mozilla-mobile/focus-android/issues/7344
