### ISSUE TITLE
The screen is displayed for a moment before fingerprint fragment

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#7305]
## Steps to reproduce
1. Put the app in the background
2. Reopen it and notice(for a short time) the page which should be hidden
3. Fingerprint fragment is displayed
### Expected behavior
Focus should display only the fingerprint fragment
### Actual behavior
Focus displays for a moment the last screen opened
### Device information

* Android device: Samsung A50, Android 11
* Focus version:

**Comment by lobontiumira** [comment]
This issue is a dupe of #5068 
Closing.
