### ISSUE TITLE
Focus IS auto-deny storage access without showing a Storage Access prompt

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/focus-android#7309]

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 104.0a1 (build 361831708 with GV 104.0a1-20220630095519) on this test site https://senglehardt.com/test/dfpi/storage_access_api.html, and here are my findings:

- regardles of setting the `dom.storage_access.auto_grants` pref = false in Focus Nightly **the prompt is displayed** when tapping on "requestStorageAccess()" buttons in columns 3, and 4,
- once the access is granted, the prompt isn't displayed anymore if the user taps again on the "requestStorageAccess()" buttons in columns 3, and 4,
- if the access is denied, the prompt is displayed again if the user taps again on the "requestStorageAccess()" buttons in columns 3, and 4.

![7309](https://user-images.githubusercontent.com/40694158/177273594-a778ffba-522a-457c-a9d1-a1b7107f4bad.png)

Verified with the following devices:
* Oppo Reno 6 (Android 12),
* Xiaomi mi4i (Android 5.0.2), and
* Samsung Galaxy Note 8 (Android 9).

**Comment by Amejia481** [comment]
Thanks for verifying @lobontiumira :)
