### ISSUE TITLE
Check if Adjust token exists at build time (release builds)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#732]
Currently we have a runtime check to crash Focus release builds if no Adjust token is set.. So that we do not accidentally ship without a token. It might be more helpful to "crash" the build of release builds if no token is set. Otherwise we create APKs that just crash - and there's the risk that we might accidentally ship such an APK. So let's no create them in the first place.

**Comment by mcomella** [comment]
Note: this will require some gradle knowledge – check for the existence of our adjust token on the release variant and fill the build if the file does not exist or is not empty!

**Comment by bansalayush** [comment]
hey @pocmo  @mcomella  , I would like to work on this issue . Can you guys drop a few hints on what to do ?

**Comment by mcomella** [comment]
@bansalayush Unfortunately, I don't know gradle well enough to know the correct answer. I think it involves waiting for the task graph to complete, checking if "release" is present in the set of running tasks and, if so, ensuring the config has set the adjust token, failing the build if not.

**Comment by bansalayush** [comment]
@mcomella Understood the first two parts . What's an adjust token ? Can you shed some light on this ?

**Comment by mcomella** [comment]
Adjust is an SDK we use and it requires an API token. We get the token at
compile time from an optional file on desk: here's the build.gradle file
where we slurp it up:
https://github.com/mozilla-mobile/focus-android/blob/308093ecbd82f755f56b0a44f4dd27930adaa208/app/build.gradle#L317

**Comment by mcomella** [comment]
The change is happening at the build script's configure time: *all* tasks
are affected for exceptions thrown during configure. You want to do this
check at Execution time, only if the appropriate release tasks are being
executed, to avoid breaking the build for every task if this token is
missing.

See this doc (disclaimer: haven't read it yet) on the build lifecycle for
notes on configure and execution time:
https://docs.gradle.org/current/userguide/build_lifecycle.html

**Comment by bansalayush** [comment]
@mcomella Thanks again , above link helped . Narrowed the solution down to 
```
gradle.taskGraph.beforeTask {
    Task task ->
        def isRelease = task.toString().contains("assembleFocus") && task.toString().contains("Release")
        println(isRelease)
        if(isRelease){
            try {
                def token = new File("${rootDir}/.adjust_token").text.trim()
                buildConfigField 'String', 'ADJUST_TOKEN', '"' + token + '"'
                println "(Added from .adjust_token file)"
            } catch (java.io.FileNotFoundException e) {
                buildConfigField 'String', 'ADJUST_TOKEN', 'null'
                println("X_X")
                throw new GradleException('ADJUST_TOKEN not set')
            }
        }

}
```
Now facing a problem with `buildConfigField` . I think that's because this is not a build phase . There must some other function to set execution time vars . Figuring this out .... :)

**Comment by mcomella** [comment]
Perhaps you can set the token at configure time but validate it when the
task graph completes?

fwiw, instead of adding code to gradle.taskGraph calls, in a similar issue
<https://github.com/mozilla-mobile/firefox-tv/issues/1280>, I was thinking
of making a new validateReleaseTask and having the "assemble*release"
builds depend on the release task. I don't know what is better by gradle
convention though. :)

**Comment by bansalayush** [comment]
@mcomella I tried re-assigning value to `def` but I think we can't do that in gradle . Is there a way of declaring a variable and  re-assigning value to it in gradle

**Comment by bansalayush** [comment]
@pocmo @mcomella Finally came up with a solution 

```

def isFocusRelease(){
    Gradle gradle = getGradle()

    def isRelease = gradle.getStartParameter().getTaskNames().any { name ->
    println("+++++++++" + name + "++++++++++"+ name.contains("Focus"))
    println("+++++++++" + name + "++++++++++"+ name.contains("Release") )
    def containsFocus =  name.contains("Focus")
    def isRelease = name.contains("Release")
    return containsFocus && isRelease
    }
    return isRelease
}

def checkAdjustToken(isRelease = isFocusRelease()){
    println "********" + isRelease + "******"
    if(isRelease){
        try {
            def token = new File("${rootDir}/.adjust_token").text.trim()
            project.ext.adjustToken = token;
            println "@@@@@!!!@@@" + project.ext.adjustToken + "@@@@@!!!@@@"
        }
        catch(FileNotFoundException ignored){
            throw new GradleException('ADJUST_TOKEN not found')
        }
    }
}
checkAdjustToken()
```

I think it's crashing on my machine because i don't have the Adjust token file .
