### ISSUE TITLE
Intermittent UI test failure - < WebControlsTest.verifySelectTextTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7334]
### Stacktrace:
07-06 08:36:55.368: I/ActivityManager(478): Start proc 29339:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 for service {org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
07-06 08:36:55.368: W/ActivityManager(478): Slow operation: 55ms so far, now at startProcess: starting to update pids map
07-06 08:36:55.368: W/ActivityManager(478): Slow operation: 55ms so far, now at startProcess: done updating pids map
07-06 08:36:55.372: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.382: I/sh.CrashHandle(29339): Late-enabling -Xcheck:jni
07-06 08:36:55.387: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.402: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.408: I/sh.CrashHandle(29339): Unquickening 12 vdex files!
07-06 08:36:55.409: W/sh.CrashHandle(29339): Unexpected CPU variant for X86 using defaults: x86
07-06 08:36:55.417: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.418: I/adbd(383): jdwp connection from 29339
07-06 08:36:55.432: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.461: I/ActivityManager(478): Process org.mozilla.focus.debug:tab31 (pid 13704) has died: fg  BTOP
07-06 08:36:55.447: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.461: I/libprocessgroup(478): Successfully killed process cgroup uid 10152 pid 13704 in 0ms
07-06 08:36:55.462: I/Zygote(290): Process 13704 exited cleanly (0)
07-06 08:36:55.462: W/ActivityManager(478): Scheduling restart of crashed service org.mozilla.focus.debug/org.mozilla.gecko.process.GeckoChildProcessServices$tab31 in 1000ms for connection
07-06 08:36:55.462: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.464: D/CompatibilityChangeReporter(478): Compat change id reported: 136274596; UID 10152; state: ENABLED
07-06 08:36:55.492: I/WindowManager(478): WIN DEATH: Window{ade75ff u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity}
07-06 08:36:55.477: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.492: W/InputDispatcher(478): Attempted to unregister already unregistered input channel 'ade75ff org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)'
07-06 08:36:55.492: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.495: I/ActivityManager(478): Process org.mozilla.focus.debug (pid 13210) has died: fg  TOP 
07-06 08:36:55.498: I/libprocessgroup(478): Successfully killed process cgroup uid 10152 pid 13210 in 0ms
07-06 08:36:55.535: I/binder_alloc(0): 13825: binder_alloc_buf, no vma
07-06 08:36:55.536: I/binder(0): 478:2415 transaction failed 29189/-3, size 84-0 line 3317
07-06 08:36:55.500: W/WindowManager(478): Cannot find window which accessibility connection is added to
07-06 08:36:55.502: W/WindowManager(478): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@447b5b
07-06 08:36:55.507: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.513: W/ActivityManager(478): Exception when unbinding service org.mozilla.focus.debug/org.mozilla.gecko.process.GeckoChildProcessServices$gpu
07-06 08:36:55.513: W/ActivityManager(478): android.os.DeadObjectException
07-06 08:36:55.513: W/ActivityManager(478): 	at android.os.BinderProxy.transactNative(Native Method)
07-06 08:36:55.513: W/ActivityManager(478): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
07-06 08:36:55.513: W/ActivityManager(478): 	at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1646)
07-06 08:36:55.513: W/ActivityManager(478): 	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:3503)
07-06 08:36:55.513: W/ActivityManager(478): 	at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:3905)
07-06 08:36:55.513: W/ActivityManager(478): 	at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:14772)
07-06 08:36:55.513: W/ActivityManager(478): 	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:3772)
07-06 08:36:55.513: W/ActivityManager(478): 	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3926)
07-06 08:36:55.513: W/ActivityManager(478): 	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1601)
07-06 08:36:55.513: W/ActivityManager(478): 	at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:305)
07-06 08:36:55.513: W/ActivityManager(478): 	at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:654)
07-06 08:36:55.522: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.523: I/Zygote(290): Process 13825 exited cleanly (0)
07-06 08:36:55.533: W/lowmemorykiller(165): Failed to open /proc/13825/oom_score_adj; errno=2: process 13825 might have been killed
07-06 08:36:55.536: W/ActivityManager(478): Crash of app org.mozilla.focus.debug running instrumentation ComponentInfo{org.mozilla.focus.debug.test/androidx.test.runner.AndroidJUnitRunner}
07-06 08:36:55.536: I/ActivityManager(478): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
07-06 08:36:55.537: I/ActivityManager(478): Killing 13825:org.mozilla.focus.debug:gpu/u0a152 (adj 900): stop org.mozilla.focus.debug due to finished inst
07-06 08:36:55.537: I/libprocessgroup(478): Successfully killed process cgroup uid 10152 pid 13825 in 0ms
07-06 08:36:55.537: W/audio_hw_generic(1893): Hardware backing HAL too slow, could only write 0 of 661 frames
07-06 08:36:55.538: I/ActivityManager(478): Killing 29339:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashHandler/u0a152 (adj 200): stop org.mozilla.focus.debug due to finished inst
07-06 08:36:55.539: W/ActivityManager(478): Bringing down service while still waiting for start foreground: ServiceRecord{4412a95 u0 org.mozilla.focus.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
07-06 08:36:55.548: I/WindowManager(478):   Force finishing activity ActivityRecord{5c665c4 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t11}
07-06 08:36:55.549: D/AndroidRuntime(13089): Shutting down VM
07-06 08:36:55.551: I/BackdropActivity(11507): onResume()

**Comment by sv-ohorvath** [comment]
closing as dupe, in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
Some test reports that have this same error in the logs contain the ANR notification, some don't, so until we can tell if they are different issues, I will log them in one place.
