### ISSUE TITLE
34ms regression to cold main first frame start up (6/18)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#7336]
We saw a 28ms regression in https://github.com/mozilla-mobile/focus-android/issues/7261 and the next day (6/18) we see another 34ms before it stabilizes for a few days:

![image](https://user-images.githubusercontent.com/759372/177825713-a165172b-e3ab-46e3-8e03-d2cde3bcf90a.png)

These could be related regressions or independent. I filed them as independent to make sure we don't forget to look at the second regression but we should consider investigating both regressions together in https://github.com/mozilla-mobile/focus-android/issues/7261.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802637

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
