### ISSUE TITLE
[Intermittent] nimbus_initial_fetch is copied in logcat for startups other than the first one

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7350]
**[Affected Versions]:**
- Firefox Nightly 104.a1 (Build #361921026 GV: 104.0a1-20220710094429) AC: 104.0.20220710143147, 9904639da7 AS: 93.5.0

**[Affected Platforms]:**
- Android 9 -  Samsung Galaxy S8

**[Prerequisites]:**
- Have a way to observe logcat (Android Studio was used for testing).
- Have the [Glean viewer](https://debug-ping-preview.firebaseapp.com) open.

**[Steps to reproduce]:**

1. Open Focus.
2. Use a telemetry command for metrics (e.g. adb shell am start -n org.mozilla.focus.nightly/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es sendPing metrics --es debugViewTag MH-a).
3. Minimize the app and then refocus the app.
4. Close the app.
5. Repeat steps 1-4.
6. Observe logcat.
7. Open the Glean viewer on the tag chosen.

**[Expected result]:**
- The “nimbus_initial_fetch” metric is registered for the first run of the app only.

**[Actual result]:**
- The “nimbus_initial_fetch” metric value registered for the first startup is sometimes copied for subsequent startups in logcat only (the Glean viewer does not seem to register the ping for startups other than the first) .

**[Notes]:**
- The issue seems highly intermittent. As a result, I am unable to provide a recording at this time.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802635

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
