### ISSUE TITLE
Broken imported string: contextmenu_image_warning

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#736]
The script from #701 found some broken strings:

```
18:01:42  * [values-az/strings.xml] missing placeholder in translation, key: contextmenu_image_warning
18:01:42  * [values-fa/strings.xml] missing placeholder in translation, key: contextmenu_image_warning
18:01:42  * [values-ja/strings.xml] missing placeholder in translation, key: contextmenu_image_warning
18:01:42  * [values-kk/strings.xml] missing placeholder in translation, key: contextmenu_image_warning
18:01:42  * [values-ko/strings.xml] missing placeholder in translation, key: contextmenu_image_warning
18:01:42  * [values-sl/strings.xml] missing placeholder in translation, key: contextmenu_image_warning
18:01:42  * [values-ta/strings.xml] missing placeholder in translation, key: contextmenu_image_warning
18:01:42  * [values-tr/strings.xml] missing placeholder in translation, key: contextmenu_image_warning
18:01:42  * [values-zh-rCN/strings.xml] missing placeholder in translation, key: contextmenu_image_warning
18:01:42  * [values-zh-rTW/strings.xml] missing placeholder in translation, key: contextmenu_image_warning
```

It looks like we only import some part of the string and not the full string. The PO files are looking good.

**Comment by pocmo** [comment]
**Japanese**

po file:
`保存、共有された画像は %1$s の履歴を消去しても <b>削除されません</b>`

strings.xml:
`<b xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">削除されません</b>。`

**Chinese (zh-TW)**

po file:
`清除 %1$s 瀏覽紀錄時，已儲存並分享的圖片將<b>不會被刪除</b>。`

strings.xml:
`<b xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">&#19981;&#26371;&#34987;&#21034;&#38500;</b>&#12290;`

**Comment by pocmo** [comment]
In both cases the imported string contains only the block inside the `<b>` tags and not the text before that.

**Comment by piotrdrag** [comment]
In case of Polish we get only what’s inside `<b>` and what’s after it — but not what’s before it.

https://people-mozilla.org/~npark/Focus_Screenshot/pl/images/phoneScreenshots/Image_Menu_1496947179263.png

**Comment by pocmo** [comment]
Okay, I have a patch for this. Our custom "CDATA repair code" didn't see text nodes. So far our strings containing HTML started with a child node.

**Comment by pocmo** [comment]
Fixed and strings re-imported.
