### ISSUE TITLE
-22ms regression to cold view nav start (7/15)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#7383]
From Nightly 7/14 we see 1.925s to Nightly 7/15 1.947s:

![image](https://user-images.githubusercontent.com/759372/179628966-55d6417d-76bc-42a9-a21d-eb73c18cf778.png)

**Comment by Mugurell** [comment]
@mcomella Just curious, can you share a link to the query for this graphs?

**Comment by mcomella** [comment]
@Mugurell [Focus](https://earthangel-b40313e5.influxcloud.net/d/7u0o-gdnz/focus-startup-nightly-via-backfill-py?orgId=1) and [fenix](https://earthangel-b40313e5.influxcloud.net/d/s3AT6t7nk/fenix-startup-nightly-via-backfill-py?orgId=1&from=now-30d&to=now). You should be able to sign in with OAuth.

**Comment by Mugurell** [comment]
Looking at the evolution of the startup data between 7/13-7/24 and the commits merged in that period there isn't anything that would stand out to explain the 38ms increase followed immediately by a 42ms drop.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/11428869/183684900-648bdcf9-93d2-4c24-8b15-4d4f5048f8cc.png">

&nbsp;

And if we look at data for a longer period it seems like this differences are common to "cold view nav start" with the performance being generally the same.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/11428869/183686599-66c24cf3-f838-4508-b418-8a902f65251c.png">

@mcomella  Would you agree just closing this based on the small differences which which are leveling up in time?

**Comment by mcomella** [comment]
Performance triage: we want to discuss this when csadilek is around. Notes on what we discussed:
- we'll run into these kinds of questions and unactionability on any performance regression that it is small enough that the date of regression is ambiguous; bimodals make this especially hard. Generally, how should we handle issues like these?
- the fenix team mentions there are higher priorities they'd rather focus on, like larger regressions https://github.com/mozilla-mobile/focus-android/issues/7576 – should we mark non-P1 or close it because it's unrealistic we're going to get to this, especially with how unactionable it feels?
  - We've seen a major performance improvement – ~120ms – is this unactionable change worth the effort/gain ratio?
  - [mcomella] perhaps there's something about how strict the team wants to be around start up regressions. Being strict requires great tools though.

**Comment by MarcLeclair** [comment]
Triage: It would be better to talk about it as a whole group / separate session.

**Comment by MarcLeclair** [comment]
Closing: 22ms is too hard for us to be actionable at the moment with our current tooling since the start up time can vary by that much.
