### ISSUE TITLE
HTTPS only mode is working only when a pref in about:config is changed

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7384]
## Steps to reproduce
1. Go to Settings - Privacy & Security - Security - HTTPS-only mode and disable it.
2. Exit the Settings pages, and type http://permission.site in the search bar (or http://badssl.com).
3. Observe the URL after the page is loaded.

### Expected behavior
The page loads as http page, exactly how the user typed it.

### Actual behavior
The page loads as https, regardless of how the user typed the URL.
Only if the parameter `dom.security.https_first_pbm` is changed in about:config to `false`, the HTTPS-Only mode option works properly.

### Device information
* Android device: all
* Focus version: Focus Nightly 104.0a1 from 7/19, and Beta 103.0.0-beta.5
* In Fenix Nightly normal browsing the HTTPS only mode works
* In the short video below is the behavior if the pref in the about:config isn't modified:

https://user-images.githubusercontent.com/40694158/179674275-a0ad98e8-f930-443b-a5b5-4aead6f984e8.mp4

* In the short video below is the behavior when the user modifies the `dom.security.https_first_pbm` in about:config to `false`

https://user-images.githubusercontent.com/40694158/179674378-aaccd973-c10f-4547-a1bd-af8d518ab36a.mp4

**Comment by Mugurell** [comment]
The same issue reproduces in Fenix when in private mode.
Seems to be a GeckoView / Gecko issue which do not update all state to allow for http to be loaded in private mode.
`about:config` is not available for users on the release channel so they cannot (and probably don't know about the `dom.security.https_first_pbm` flag).

https://user-images.githubusercontent.com/11428869/179704372-c08033af-d376-410b-b289-c9522830c74d.mov

**Comment by lobontiumira** [comment]
After investigating more on both Firefox mobile, and desktop, enabling/disabling the option HTTPS only mode displays a warning page to the user informing about the risk to browse an insecure page.
* If the HTTPS only mode option is enabled in Settings - Privacy & Security - Security, **the user will be notified** through a warning page, and the option to continue to HTTP site:

https://user-images.githubusercontent.com/40694158/179760923-fdb30597-7d34-4e95-98cd-d66e4f25ed45.mp4

* if the option is disabled, the the user will no longer see the warning page:

https://user-images.githubusercontent.com/40694158/179760948-8dd684ac-f7ad-4754-a9a3-29dd5fd6106b.mp4


Thanks @Mugurell & @mcarare for the advices.
Closing this ticket as invalid.
