### ISSUE TITLE
RTL problem, About page

### ISSUE THREAD

**Issue by 5y** [mozilla-mobile/focus-android#740]
![help](https://user-images.githubusercontent.com/1941933/26956672-b96655da-4cd4-11e7-905e-cbcd91fdcfdc.png)

left = incorrect 
right = correct

**Comment by pocmo** [comment]
Thank you for filing this bug. One important thing to know for this and the other RTL bugs is whether your system is set to an RTL language or if you switched to this language using Focus' own language setting. And additional which system/Focus language you have set. :)

**Comment by 5y** [comment]
You are welcome.
This is a review based on the [screenshots](https://people-mozilla.org/~npark/Focus_Screenshot/fa/images/phoneScreenshots/) from last version of Focus for Android.
@Delphine

**Comment by pocmo** [comment]
Ah, thanks! I'll ask @npark-mozilla about it. :)

**Comment by pocmo** [comment]
The "good" news is that most of those issues seem to be caused by the same bug. The "bad" news is that it looks like it is our locale chooser that is not working correctly.

**Comment by pocmo** [comment]
![740](https://user-images.githubusercontent.com/89638/26985072-3a977cb6-4d42-11e7-9f96-ae070a166916.png)

^-- From my device. How does this look like?

**Comment by 5y** [comment]
Yes, I checked previous version and everything is correct. I guess our problems is related to the locale chooser.
