### ISSUE TITLE
Granular media permissions 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#7400]
On targeting SDK 33, this will require adding new permissions to the manifest file.

We currently use permission READ_EXTERNAL_STORAGE so when targeting Android 13 we should also add `READ_MEDIA_IMAGES`, `READ_MEDIA_AUDIO`, `READ_MEDIA_VIDEO` while also keeping the existing `READ_EXTERNAL_STORAGE`.

Note: Fortunately, for users that have already allowed reading files from storage, the 3 new permissions are automatically granted.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802579

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
