### ISSUE TITLE
RTL problem, Help page

### ISSUE THREAD

**Issue by 5y** [mozilla-mobile/focus-android#741]
![help2](https://user-images.githubusercontent.com/1941933/26956694-ef72e76a-4cd4-11e7-9976-07ad81c64ee2.png)
left = incorrect
right = correct

**Comment by pocmo** [comment]
![741](https://user-images.githubusercontent.com/89638/26985110-5cc2f324-4d42-11e7-8a55-37cbf5549e5a.png)
