### ISSUE TITLE
Renew telemetry expiring in 106

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/focus-android#7415]
* Android device: all devices 
* Focus version: all versions

**Comment by lobontiumira** [comment]
Verified that the following metrics are renewed:
`browser.is_default` - expires in version 119
`browser.default_search_engine` - expires in version 119
`browser.locale_override` - expires in version 119
`browser.search.with_ads` - expires in version 119
`browser.search.ad_clicks` - expires in version 119
`browser.search.in_content` - expires in version 119
`mozilla_products.has_fenix_installed` - expires in version 119
`settings_screen.whats_new_tapped` - expires in version 119
`shortcuts.shortcuts_on_home_number` - expires in version 119
`shortcuts.shortcut_opened_counter` - expires in version 119
`shortcuts.shortcut_added_counter` - expires in version 119
`shortcuts.shortcut_removed_counter` - expires in version 119
`tracking_protection.toolbar_shield_clicked` - expires in version 119
`tracking_protection.tracking_protection_changed` - expires in version 119
`tracking_protection.tracker_setting_changed` - expires in version 119
`tracking_protection.has_social_blocked` - expires in version 119
`tracking_protection.has_advertising_blocked` - expires in version 119
`tracking_protection.has_analytics_blocked` - expires in version 119
`tracking_protection.has_content_blocked` - expires in version 119
`preferences.user_theme` - expires in version 119

Closing the ticket as complete.
