### ISSUE TITLE
RTL problem, Home page menu

### ISSUE THREAD

**Issue by 5y** [mozilla-mobile/focus-android#742]
![home](https://user-images.githubusercontent.com/1941933/26956719-21b9998a-4cd5-11e7-8962-6dbbaa2219a4.png)
left = incorrect
right = correct

**Comment by pocmo** [comment]
![742](https://user-images.githubusercontent.com/89638/26985132-785cd320-4d42-11e7-950c-b43a6dcc49fc.png)
