### ISSUE TITLE
[RTL L10N] The "Languages" page's back arrow is incorrect

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7423]
## Steps to reproduce
1. Set your device to a RTL language, like Persian (fa).
2. Open Focus - Settings - General - Languages, and observe the back arrow.

### Expected behavior
The back arrow is pointing to the right, like all the other back arrows inside the app.

### Actual behavior
The back arrow is pointing to the left.

### Device information
* Android device: all
* Focus version: Focus Nightly 105.0a1, Beta 104.0b1
* Please see the short video below:

https://user-images.githubusercontent.com/40694158/181462351-aec194b4-38ea-402b-a0bc-c0f185895693.mp4

![Screenshot_3](https://user-images.githubusercontent.com/40694158/181462777-c9841bc5-aa14-4984-a0f6-6de0c838b80c.jpg)

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 105.0a1 build from 8/2 with Lenovo tablet M10 (Android 10):

<img src="https://user-images.githubusercontent.com/40694158/182320626-a84c1fdc-1410-4d1a-a562-e565a68ea169.jpg" width="300" height="550" />

**Comment by delia-pop** [comment]
Verified as fixed on Focus Beta 105.0b1 as well, with Google Pixel 6 (Android 13).
