### ISSUE TITLE
Disabling the “Send usage data” toggle doesn’t unenroll users from Focus for Android experiments

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-mobile/focus-android#7425]
**[Affected versions]:**
- Focus Nightly 105.0a1 (Build #362091408 GV: 105.0a1-20220726143051) AC: 105.0.20220726143051, deb9d3359e, AS: 93.7.0

**[Affected platforms]:**
- Samsung Galaxy S9, Android 10

**[Prerequisites]:**
- Have a Focus for Android build with the following modifications:
- The following lines added to local.properties:
`nimbus.remote-settings.url = https://settings.stage.mozaws.net/`
`debuggable = true`
`autosignReleaseWithDebugKey=true`

- A new “.nimbus” file (in the same location as local.properties) containing the following line: https://settings.stage.mozaws.net/
- You are enrolled in a Live Focus for Android Nimbus experiment launched to Stage.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Go to Settings > Privacy & Settings and disable “Send usage data”.
3. Close and reopen the app.
4. Go to Settings > Privacy & Settings > Studies and observe if you are still enrolled in any experiments.

**[Expected result]:**
- The experiment from the prerequisites is no longer listed in the Active studies section.

**[Actual result]:**
- The experiment from the prerequisites remains listed in the Active studies section.

**Comment by mcarare** [comment]
I think this was previously reported and discussed in https://github.com/mozilla-mobile/focus-android/issues/6083.

**Comment by heres-maria** [comment]
@mcarare Since then we have had https://mozilla-hub.atlassian.net/browse/EXP-2121 filed, which determined the expected behavior to be that users who disable telemetry should have experiments also be disabled. Fenix has also been modified to conform to that behavior.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802634

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
