### ISSUE TITLE
RTL problem, Language menu

### ISSUE THREAD

**Issue by 5y** [mozilla-mobile/focus-android#743]
![language](https://user-images.githubusercontent.com/1941933/26956736-4bd3aa62-4cd5-11e7-9c80-8f83604153c9.png)
left = incorrect
right = correct

**Comment by pocmo** [comment]
![743](https://user-images.githubusercontent.com/89638/26985154-942ed896-4d42-11e7-86a0-19bb3267fb48.png)

The button at the bottom seems wrong, right?

**Comment by 5y** [comment]
My example isn't correct. I checked again and the bottom should be aligned to the left ( current position).
as you can see here in this LTR example the bottom is on the right side.
![image](https://user-images.githubusercontent.com/1941933/26986669-d11029a2-4d5d-11e7-8e75-12eb75824e26.png)
