### ISSUE TITLE
Fix breaking change from AC regarding `exitImmersiveModeIfNeeded`

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#7430]
Based on the development from https://github.com/mozilla-mobile/android-components/pull/12560 AC will introduce a breaking change that needs to be handled in clients.
This ticket is to address the needed changes.

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?

**Comment by indurs** [comment]
@Mugurell , if you've started working on this issue, it's fine. Otherwise can I work on this issue?

**Comment by indurs** [comment]
Can we follow the implementation similar to Fenix for entering and exiting immersive mode in Focus while in full screen mode?

**Comment by Mugurell** [comment]
> Can we follow the implementation similar to Fenix for entering and exiting immersive mode in Focus while in full screen mode?

Yes, both Fenix and Focus would have the same bug.
Which can be fixed by your AC changes.

**Comment by indurs** [comment]
Yes indeed it will work for Focus also. But in Focus, the FullScreenIntegration handles the enter/exit immersive modes. It will be nice if we use the Activity extension methods in AC library. Shall I update that also?

**Comment by Mugurell** [comment]
> Yes indeed it will work for Focus also. But in Focus, the FullScreenIntegration handles the enter/exit immersive modes. It will be nice if we use the Activity extension methods in AC library. Shall I update that also?

Thank you for checking! Seems like a welcome refactoring indeed 👍

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 105.0a1 from 8/9 on youtube.com, and vimeo.com, with the following devices:
* Samsung Galaxy Tab A6 (Android 5.1.1),
* Oppo Reno 6 (Android 12),
* Lenovo tablet M10 (Android 10), and Samsung Galaxy Note 8 (Android 9).

After the video in fullscreen was finished / paused, the device's screens are locked based on the "screen off" set by the users (on those devices).

**Comment by delia-pop** [comment]
Verified as fixed on Focus Beta 105.0b1 as well, with Lenovo Yoga Tab 11 (Android 11).
