### ISSUE TITLE
When setting Focus as a default browser, prompt users to enable 'Open links in apps'

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#7434]
### Why/User Benefit/User Problem
When a user sets Focus as their default browser, they want it to allow them to use it as a (secure) browser's full potential.

A default browser allows other apps to open tabs in them for Oauth and then redirects the user back to the app when login is complete. If 'Open links in apps' is not enabled, this could lead to poor usability and a loss of default users.

Example (my use case):
1. Install the IKEA app.
2. Click login; the app opens a Focus custom tab to login.
3. Login to website.
4. Website responds with, "there was a problem with your browser, please login with Google Chrome instead."

If I were to retry this same flow with 'Open links in apps', Focus notifies me that we are about to leave the browser and enter the app (which is a decision a user would want to agree with). This is still privacy preserving, because the login session/cookies will be deleted when leaving so the default browser is not left signed in (which is probably desired since a user has set their default browser as Focus).

### What / Requirements
When a user clicks on "Make Focus your default browser" or when we detect the default browser has changed to us, gently prompt the user to enable 'Open links in apps' for a better default browsing experience.

### Acceptance Criteria (how do I know when I’m done?)
A non-blocking/user friendly way to prompt the user to enable 'Open links in apps'.

**Comment by jonalmeida** [comment]
This could also be applicable for Fenix as well, if we observe the default app has been set and they may have turned 'Open links in apps' off before.

A gentle prompt is a key requirement for both browsers.

**Comment by nerder** [comment]
Hey folks,

Hopefully, this goes forward, in our use-case we rely heavily on [Firebase Dynamic Links](https://firebase.google.com/docs/dynamic-links/) and we have users reporting this issue quite a lot.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801992

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
