### ISSUE TITLE
The placeholder text from search bar is zoomed in when the keyboard in invoked

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#7439]
## Steps to reproduce
1. Open Focus.
2. Tap on the search bar.
3. Observe the "Search or enter address" placeholder text.
### Expected behavior
The "Search or enter address" placeholder text from search bar remains correctly displayed when the keyboard in invoked, without visual defects.
### Actual behavior
The "Search or enter address" placeholder text from search is zoomed in when the keyboard in invoked.
### Device information
* Android device: Lenovo Yoga Tab 11 (Android 11)
* Focus version: Focus Nightly 105.0a1 from 07/31, Beta 104.0b3.

Note that this is not reproducible with phone devices, nor with Huawei MediaPad M2 (Android 5.1.1) tablet.

https://user-images.githubusercontent.com/89388888/182166844-bfb331d3-6091-4fed-a46e-63bc33da3774.mp4

**Comment by lobontiumira** [comment]
Reproducible also on the Lenovo tablet M10 (Android 10), on the latest Focus Nightly 105.0a1 build from 8/2.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802633

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
