### ISSUE TITLE
RTL problem, Open with menu

### ISSUE THREAD

**Issue by 5y** [mozilla-mobile/focus-android#744]
![menu](https://user-images.githubusercontent.com/1941933/26956770-888c10f2-4cd5-11e7-8b21-fb2216fe733e.png)
left = incorrect
right = correct

**Comment by pocmo** [comment]
![744](https://user-images.githubusercontent.com/89638/26985199-c3e2926c-4d42-11e7-934e-9e823f3b4f62.png)

The forward button should show in the opposite direction - anything else here?

**Comment by 5y** [comment]
Your RTL version is totally correct.

**Comment by pocmo** [comment]
@5y 

> Your RTL version is totally correct.

Even the "forward" button in the menu? Looking at the back button of the system - Shouldn't it point in the other direction? It does in LTR at least.
