### ISSUE TITLE
Add quick actions on long-pressing the browser toolbar

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#7446]
### Why/User Benefit/User Problem

Focus is a browser that is meant to be private and also (implicitly) fast. We should make it easier for users to access common features in Fenix that allow it to be so.

### What / Requirements
Long-pressing on the toolbar provides the user with quick actions they can perform.

### Acceptance Criteria (how do I know when I’m done?)
Having the same/similar quick actions as Fenix does when you long press on the browser toolbar.

Example:

<img width=500 src="https://user-images.githubusercontent.com/1370580/182428118-ef3113a7-9540-47be-ae1b-09133c50ea08.png" />

**Comment by Mugurell** [comment]
For a bit of context regarding Fenix this was implemented in https://github.com/mozilla-mobile/fenix/issues/4155 and https://github.com/mozilla-mobile/fenix/issues/6846.
The [`ToolbarPopupWindow`](https://github.com/mozilla-mobile/fenix/blob/49f352d52da55bed7ab1cc7dc90f75953a112c86/app/src/main/java/org/mozilla/fenix/utils/ToolbarPopupWindow.kt) that is used would probably have to be shared through A-C a refactoring which would also present the opportunity to reimplement it in Compose.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801991

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
