### ISSUE TITLE
Punjabi (pa-IN) not available in app languages

### ISSUE THREAD

**Issue by bcolsson** [mozilla-mobile/focus-android#7447]
## Steps to reproduce
1. Open Firefox Focus for Android
2. Open Settings > General > Language
3. Notice Punjabi (ਪੰਜਾਬੀ) language option unavailable

### Expected behavior
Option for Punjabi (ਪੰਜਾਬੀ) to be available, and UI to display localization when enabled.

### Actual behavior
Option for Punjabi (ਪੰਜਾਬੀ) is unavailable, and UI localization unable to be used.

### Device information

* Android device: ChromeOS
* Focus version: 103.1.0

Additional notes:
Punjabi currently sits at 100% translated for Focus for Android.
Punjabi is already enabled and available in Firefox for Android.
When cross referencing against Firefox for Android, the language switcher behavior appears to be quite different. (See example screenshots.)

Focus
![image](https://user-images.githubusercontent.com/38174554/182456385-d1bb7f96-a01a-4972-a7bc-c8f03cd46b3a.png)

Firefox
![image(1)](https://user-images.githubusercontent.com/38174554/182456437-3f42fc4b-7c02-4ef5-a8cf-d3b33f25acd9.png)

**Comment by flodolo** [comment]
I wonder if this can be somehow related to this piece of code
https://github.com/mozilla-mobile/focus-android/blob/b5834b731b7e60a66dff6d12181eb31a2b0ce815/app/src/main/java/org/mozilla/focus/locale/screen/LocaleDescriptor.kt#L106-L126

**Comment by jonalmeida** [comment]
Based on the comments in the code snippet above, if we don't have this bug in fenix, then we should be fine removing this check in Focus too. I don't see any of our other supported apps that have this workaround (probably because we're using Java 8+ now).

**Comment by flodolo** [comment]
I understand a lot of Java and Android development, but is it correct that Focus uses its own solution for the language switcher, while fenix uses an android-component? Could we use the latter for consistency, which also looks a lot clearer with both localized and non-localized names?

**Comment by Mugurell** [comment]
Looks like this ticket can remain for fixing the issue with the Punjabi language option.
For maybe updating the Language screen UI I've opened https://github.com/mozilla-mobile/focus-android/issues/7453.

**Comment by flodolo** [comment]
@ionutbedregeanu 

I'm not familiar with the release schedule for Focus. In which version (and when) is this going to ship to users?

**Comment by ionutbedregeanu** [comment]
It will be available in prod in version: 104
Current prod version: 102
Firefox trains: https://fx-trains.herokuapp.com/

**Comment by flodolo** [comment]
Thanks, I wasn't sure how code lands in Focus, and it had a beta cycle 👍🏼

**Comment by flodolo** [comment]
Correction: the current prod version is 103, so I guess it will ship with 105 (Sep 20).

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 105.0a1 from 8/9 with Oppo Reno 6 (Android 12), and Samsung Galaxy Tab A6 (Android 9):

![Screenshot_20220809-143018_Firefox Focus Nightly](https://user-images.githubusercontent.com/40694158/183637481-0091d829-7f2b-4387-ba11-0f8b6968a527.jpg)

Closing the ticket as verified. We will test on Beta 105 version, when available.

**Comment by delia-pop** [comment]
Verified as fixed on Focus Beta 105.0b1 as well, with Lenovo Yoga Tab 11 (Android 11).

<img src="https://user-images.githubusercontent.com/89388888/186351878-99c4309a-eaed-4beb-bbc5-605232a98707.jpeg" width="50%" />
