### ISSUE TITLE
Update the locale list UI 

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#7453]
From https://github.com/mozilla-mobile/focus-android/issues/7447#issuecomment-1204771945
> I understand a lot of Java and Android development, but is it correct that Focus uses its own solution for the language switcher, while fenix uses an android-component? Could we use the latter for consistency, which also looks a lot clearer with both localized and non-localized names?

| Fenix | Focus |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/11428869/182797171-913dcad6-4742-4950-b538-103b247fda17.png) | ![image](https://user-images.githubusercontent.com/11428869/182796710-176a02bb-9063-4f44-9dc7-864a9ae1e478.png) |

**Comment by ionutbedregeanu** [comment]
@jeffreygee Focus language feature should look as in Fenix in order to have consistency?

**Comment by jeffreygee** [comment]
@ionutbedregeanu Yeah, we're trying to move toward all native/android-components where we can so I'm good with this

**Comment by Mugurell** [comment]
If this work is not urgent we might wait to use the same common approach on both Fenix and Focus.

**Comment by flodolo** [comment]
> If this work is not urgent we might wait to use the same common approach on both Fenix and Focus.

@Mugurell 
Could you clarify? Do you mean that the plan is also to change the current behavior on fenix?

**Comment by Mugurell** [comment]
> > If this work is not urgent we might wait to use the same common approach on both Fenix and Focus.
> 
> @Mugurell Could you clarify? Do you mean that the plan is also to change the current behavior on fenix?

I was thinking about sharing code the with Fenix since at it's essence is the same feature.
Though if it's just for UI sharing this through A-C would probably be an exotic approach. The implementations are already different so maybe Focus can first mimic Fenix's UI and then we can look into whether Fenix can be updated to use the newer implementation and eliminate code duplication.

**Comment by amedyne** [comment]
@rtestard Any thoughts in this?

**Comment by flodolo** [comment]
In the meantime, I realized that Firefox for Android seems to build on top of that, since they have hard-coded list of locales if the language name is not available in Android.
https://github.com/mozilla-mobile/fenix/pull/26630

**Comment by rtestard** [comment]
Regarding the move to native/android-components where we can - does that imply that in these instances the UI style is different?
I see that on Fenix the language UI is represented with different style from other lists with selectors (default UI on Fenix is a circle that gets highlighted in purple whereas the android component list of languages is represented as a white check-mark). It seems that doing it will regress UI consistency in settings - can't we style the native/android components to match specific browser styles?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802632

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
