### ISSUE TITLE
RTL problem, Setting 

### ISSUE THREAD

**Issue by 5y** [mozilla-mobile/focus-android#746]
![menu3](https://user-images.githubusercontent.com/1941933/26956835-0651943a-4cd6-11e7-87da-5c9196867e2c.png)
left = incorrect
right = correct

**Comment by pocmo** [comment]
![746](https://user-images.githubusercontent.com/89638/26985282-1775c3d6-4d43-11e7-8e7f-025c86b8149a.png)
