### ISSUE TITLE
Update code quality tools

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#7467]
This should include updating ktlint and detekt, and also fixing issues and removing entries from baselines (if any).

**Comment by mcarare** [comment]
Ktlint has been updated. Detekt remains.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802631

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
