### ISSUE TITLE
RTL problem, URL/Search bar 

### ISSUE THREAD

**Issue by 5y** [mozilla-mobile/focus-android#747]
![url](https://user-images.githubusercontent.com/1941933/26956881-578fc0c4-4cd6-11e7-934e-f8e8bf74237e.png)
left = incorrect
right = correct

**Comment by pocmo** [comment]
![747](https://user-images.githubusercontent.com/89638/26985300-26bed698-4d43-11e7-95be-d678de76c66e.png)
