### ISSUE TITLE
On Tips, it is not clear how to "Add a shortcut"

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#7470]
## Steps to reproduce

1.  On the Focus Homepage, on the "Tips" section, scroll to the second tip.
2. The string on the Tip says 
"Create shortcuts to the sites you visit most: 
Select Add to Shortcuts from the Firefox Focus menu"
3. Click on the three-dot menu

### Expected behavior
Should be clearer to the user what prerequisite steps are before they can add items to SHortcuts

### Actual behavior
No "Add to shortcut" option on the Menu
![Screenshot_20220808-121211](https://user-images.githubusercontent.com/68711330/183464863-cf8c4ced-774c-4f65-8cb3-a6561a4f4092.png)

### Device information

* Android device: Pixel 6
* Focus version: Focus Nightly v105.0a1, but this is also same behavior on Focus v103.2.0

**Comment by amedyne** [comment]
Tagging @jeffreygee

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802248

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
