### ISSUE TITLE
Missleading Wiki

### ISSUE THREAD

**Issue by hi337** [mozilla-mobile/focus-android#7489]
Hey,

I'm just trying to play around with the code base in my free time, so excuse me in advance if this question has already been answered. I just noticed that, while trying to read the [content blocking](https://github.com/mozilla-mobile/focus-android/wiki/Content-blocking#the-blacklist) page in the repo's wiki, the BlocklistProcessor.java file is not available and I can't find it anywhere on my local clone of the repo neither.

So 1) I was just wondering how content blocking works and where I can access the code that intercepts blocked domains, 2) how I would go about adding my own urls to block.

Thanks

**Comment by Amejia481** [comment]
Hi there👋🏽 ,
The wiki page is outdated, sorry about that.  Focus is using the same technology as Firefox for desktop, all the content blocking is happening inside of the Gecko engine web engine. The content blocking list can be seen here https://github.com/mozilla-services/shavar-prod-lists, to add to the list you may want to create an issue on the repo to discuss.  

Another alternative you could build Focus using the [engine system ](https://github.com/mozilla-mobile/android-components/blob/main/components/browser/engine-system/README.md) t[hat ships with is own list, which you can alter in your clone repo](https://github.com/mozilla-mobile/android-components/tree/main/components/browser/engine-system/src/main/res/raw), that follows the same a similar approach that the wiki above. The only caveat is that is based on  WebView and you won't have access to all the privacy features that are built-in in Gecko.

**Comment by Amejia481** [comment]
I updated the wiki to indicated that it's outdated.
