### ISSUE TITLE
Google Play listing page uses a screenshot from Focus for iOS 

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#7499]
## Steps to reproduce
https://play.google.com/store/apps/details?id=org.mozilla.focus

### Expected behavior
All the product screenshots are sourced from Focus for Android.

### Actual behavior
The third image, captioned “Automatically block ads and other trackers”, uses a screenshot from Focus for iOS.

This is a Branding/Marketing issue, but I’m not sure where to file it?

**Comment by ionutbedregeanu** [comment]
@amedyne ^^

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802629

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
I'll forward the Bugzilla bug to the marketing person who manages the Play Store listing.
