### ISSUE TITLE
Update onboarding screen 1

### ISSUE THREAD

**Issue by rtestard** [mozilla-mobile/focus-android#7500]
### Why/User Benefit/User Problem
This first screen should be updated to align with the rest of the onboarding changes:

- We now mention history clearing on onboarding screen 2
- We don't want to steer users to settings since we now realize it may influence them to enable features that could cause webcompat issues
- The C2A on the onboarding screen 1 is not to start browsing anymore given there is now onboarding screen 2

### Acceptance Criteria (how do I know when I’m done

- Update copy and visuals per UX on https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4617%3A40516
- Selecting "Get started" will get users to onboarding screen 2
- Selecting the cross will close onboarding but CFRs will still apply
- Event telemetry informs of user engagement with the "Get started" button or the cross button
- If the first Focus launch is a result of a search widget launch (i.e the user installed the widget through OS settings prior to launching the app), onboarding is not shown.
- Tablet - Let's do the same thing we do on iOS where it's just a smaller version on the screen with the scrim over the background. I've added [screens here for reference.](https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4857%3A43257) 
- Landscape - Let's lock the first two screens in portrait, but the rest of the onboarding (with CFRs, etc) can run on landscape. That shouldn't be an issue, right? 
- Get Started - if a user closes the app, they should return to where they left off. (i.e. If a user closes the app on the 2nd screen, they should see 2nd screen on re-open, etc.) 
- Exposure of this onboarding screen can be toggled through Nimbus to facilitate experiments
The implementation will track the `onboarding.is-enabled` configuration.
A draft experiment is available at https://experimenter.services.mozilla.com/nimbus/firefox-focus-android-onboarding.

**Comment by iorgamgabriel** [comment]
@jeffreygee where is the cross that will close the onboarding in this design https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4448%3A38774 ?

**Comment by iorgamgabriel** [comment]
For dark mode is the same design like for light mode ? @rtestard

**Comment by iorgamgabriel** [comment]
The background of the screen and the colors shouldn't be like the ones from biometric screen , to be consistent in all the app ? 
https://www.figma.com/file/dPV9Rn2rzrRsvwQ6SI8EzO/Fingerprint-Auth-Flow?node-id=3%3A3998
@rtestard @amedyne @jeffreygee

**Comment by jeffreygee** [comment]
> The background of the screen and the colors shouldn't be like the ones from biometric screen , to be consistent in all the app ? https://www.figma.com/file/dPV9Rn2rzrRsvwQ6SI8EzO/Fingerprint-Auth-Flow?node-id=3%3A3998 @rtestard @amedyne @jeffreygee

I think you're looking at the old user test screens. Please use this page: https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4617%3A40516

**Comment by iorgamgabriel** [comment]
@jeffreygee  said that he will modify the background , in the meantime I will use the same background like on biometrics 
https://www.figma.com/file/dPV9Rn2rzrRsvwQ6SI8EzO/Fingerprint-Auth-Flow?node-id=3%3A3998
Do we need to support the tablet ? If we need to support tablet I need dimensions from @jeffreygee 
Do we need to support landscape mode ,the old onboarding supports ? If so I need design for landscape mode.
@amedyne @rtestard

**Comment by iorgamgabriel** [comment]
If the user presses "Get started" and the second screen appears . If he closes the app, next time when he enters in the app should appear again screen one or only screen two ? @rtestard @jeffreygee

**Comment by jeffreygee** [comment]
@iorgamgabriel - i updated the [background](https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4617%3A40516) here.

Tablet - Let's do the same thing we do on iOS where it's just a smaller version on the screen with the scrim over the background. I've added [screens here for reference.](https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4857%3A43257) 

Landscape - Let's lock the first two screens in portrait, but the rest of the onboarding (with CFRs, etc) can run on landscape. That shouldn't be an issue, right? 

Get Started - if a user closes the app, they should return to where they left off. (i.e. If a user closes the app on the 2nd screen, they should see 2nd screen on re-open, etc.)

**Comment by iorgamgabriel** [comment]
@jeffreygee at onboarding screen 2 light mode did you forget to put the same background like onboarding screen 1 or white remains ?

**Comment by iorgamgabriel** [comment]
@jeffreygee @rtestard what onboarding we keep from the old ones ? We put this onboarding under nimbus feature file ?

**Comment by iorgamgabriel** [comment]
@rtestard @jeffreygee if the user select focus as default browser I will close the onboarding ?

**Comment by iorgamgabriel** [comment]
@rtestard Do we have two separate  telemetry events for each Close button ? Each onboarding has his own close button .
Or one event for both screens ?

**Comment by iorgamgabriel** [comment]
@jeffreygee said that "Ah, yeah we are getting rid of Metropolis across products and using Roboto" So we delete Metropolis from Focus ? @rtestard 
@amedyne

**Comment by lobontiumira** [comment]
Hi all!
I've tested the new onboarding on multiple devices, on the Focus Nightly 106.0a1 from [here](https://github.com/mozilla-mobile/focus-android/issues/7500), and here are my findings:
* on Android 5 devices (Samsung Galaxy Tab A6 - android 5.1.1, and Xiaomi mi4i - android 5.0.2), the first screen of the onboarding is displayed with a slightly cut "x" close button:
![Screenshot_1](https://user-images.githubusercontent.com/40694158/188461156-9b5be3e1-2d81-4e99-9bdb-63dec45b8d98.jpg)
* on Sony Xperia, the same slightly cut "x" close button. In adittion, on this device, the second screen is scrollable (but I will add this information on the screen 2 ticket):
![sony](https://user-images.githubusercontent.com/40694158/188461211-ffa2cdba-31d9-4eb4-a418-379d42f3a277.png)

* on the Lenovo tablet M10 (Android 10), the same slightly cut "X" close button:
![lenovo](https://user-images.githubusercontent.com/40694158/188461496-443934cc-bb79-4ad2-a66b-572ebc9cd4e1.png)

* on the Oppo Reno 6 (Android 12), and Samsung Galaxy Note 8 (Android 9), everything is as in the Figma designs:
![Oppo](https://user-images.githubusercontent.com/40694158/188461641-b547d533-da11-40e6-950b-b7cb2a10e7eb.png)

Note:
*if the user exits the app when on the first screen of the onboarding, then reopens the app, the app will display the first screen of the onboarding.

@iorgamgabriel @Mugurell please review, and/or advise regarding the slightly cut "x" close button, if I should file a new issue, or not.
Thank you!

**Comment by Mugurell** [comment]
Thank you @lobontiumira for testing.
I'll try to address some of your findings:
- The "slightly cut "x" close button" - seems like an issue we should address. Based on the screenshots the paddings are also not perfectly matching [Figma](https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4617%3A40516). Please open a new ticket with the details about the devices / configuration on which you saw this issue.
- the second screen being scrollable - actually both screens are scrollable to support the scenarios in which the content cannot fit the screen. Based on the screenshots seems like the right approach. @jeffreygee to confirm.
- the app remembering the onboarding step - is part of the requirements from Jeff - https://github.com/mozilla-mobile/focus-android/issues/7500#issuecomment-1225851324. Would be nice to verify that the second screen is remembered also.

**Comment by jeffreygee** [comment]
@Mugurell @lobontiumira - the screen becoming scrollable really only affects the smallest devices right? I think that's okay. If there's a way we can set maybe the max-height or width of the image to appear smaller in these, I think that would help. I'm not sure if we do anything on Fenix to do this, but I know we have some parameters on iOS to fit the tiniest phone.  

Remembering the screens - yes that is correct. The user should be returned to the last screen they were on, regardless of step. It shouldn't restart the onboarding.

**Comment by lobontiumira** [comment]
Hello all!
I've filed #7645 for the scrollable second screen.
I'll close this ticket as complete.
Thank you!
