### ISSUE TITLE
Introduce onboarding screen 2

### ISSUE THREAD

**Issue by rtestard** [mozilla-mobile/focus-android#7502]
### Why/User Benefit/User Problem
In order to help increase new user retention we want to promote the set to default action.

### Acceptance Criteria (how do I know when I’m done?

- When users select "Get started" on onboarding screen 1(https://github.com/mozilla-mobile/focus-android/issues/7500) this new onboarding screen appears
- Copy and visuals are per UX on https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4448%3A38774
- Selecting "Set as default browser" brings the OS set to default UI where the user can select to set Focus as default browser.
- This is not displayed to users who have Firefox or Focus set as default
- Selecting the cross or "Skip" will close onboarding but CFRs will still apply
- Android 5 and 6 users don’t see this message (population is too small)Android 5 and 6 users don’t see this message (population is too small)
- Event telemetry informs of user engagement with the "Set to default" button, the "Skip" button or the cross button
- Exposure of this onboarding screen can be toggled through Nimbus to facilitate experiments.
The implementation will track the `onboarding.is-enabled` configuration.
A draft experiment is available at https://experimenter.services.mozilla.com/nimbus/firefox-focus-android-onboarding.

**Comment by Mugurell** [comment]
This should've also be implemented in https://github.com/mozilla-mobile/focus-android/pull/7566

**Comment by lobontiumira** [comment]
I've tested the new onboarding on multiple devices, on the Focus Nightly 106.0a1 from [here](https://github.com/mozilla-mobile/focus-android/issues/7500), and here are my findings:
* on Android 5 devices (Samsung Galaxy Tab A6 - android 5.1.1, and Xiaomi mi4i - android 5.0.2), **the second screen of the onboarding is not displayed at all**, the user is redirected directly to the homescreen:

https://user-images.githubusercontent.com/40694158/188462716-c3260ed7-9542-4e46-9095-e2e6b96da49c.mp4

* on Sony Xperia, the same slightly cut "x" close button, and **the second screen is scrollable**:
![sony](https://user-images.githubusercontent.com/40694158/188461211-ffa2cdba-31d9-4eb4-a418-379d42f3a277.png)

* on the Lenovo tablet M10 (Android 10), the same slightly cut "X" close button (mentioned on #7500 ticket):
![lenovo](https://user-images.githubusercontent.com/40694158/188461496-443934cc-bb79-4ad2-a66b-572ebc9cd4e1.png)

* on the Oppo Reno 6 (Android 12), and Samsung Galaxy Note 8 (Android 9), everything is as in the Figma designs:
![Oppo](https://user-images.githubusercontent.com/40694158/188461641-b547d533-da11-40e6-950b-b7cb2a10e7eb.png)

Notes:
* if the user exits the app when on the second screen of the onboarding, then reopens the app, the app will display the second screen of the onboarding, exactly where the user left the app;
* the apps with the onboarding screens are not available on the regular channels, being behind the Nimbus experiment.

Thank you!
