### ISSUE TITLE
Update the tracking protection tooltip

### ISSUE THREAD

**Issue by rtestard** [mozilla-mobile/focus-android#7504]
### Why/User Benefit/User Problem
Introduce a more user friendly message to inform users that trackers were blocked on the tracking protection CFR
### Acceptance Criteria (how do I know when I’m done?)
Update CFR string per copy on UX:https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4448%3A38774

**Comment by lobontiumira** [comment]
Verified on a local Focus Nightly build with the following devices:
* Lenovo tablet M10 (Android 10),
* Samsung Galaxy Note 8 (Android 9),
* Sony Xperia Z5 Premium (Android 7.1.1),
* Google Pixel (Android 10),
* Xiaomi Mi8 Lite (Android 10),
* Oppo Reno 6 (Android 12), and 
* Samsung Galaxy Tab A6 (Android 5.1.1).

And the behavior is:
* the tracking protection CFR is displayed on the first page were trackers are being blocked,
* the tracking protection CFR is dismissed when the devices is turned into landscape/or viceversa,
* the tracking protection CFR is always displayed before the trashcan CFR,
* while the tracking protection CFR is displayed, after tapping anywhere on the screen, the tracking protection CFR is dismissed, then the trashcan CFR is displayed.

![Screenshot_2022-09-12-16-07-08-528_org mozilla focus nightly](https://user-images.githubusercontent.com/40694158/189667153-699bc0b9-0c3d-4205-8048-742b15663bb9.jpg)
