### ISSUE TITLE
Update the trash can CFR

### ISSUE THREAD

**Issue by rtestard** [mozilla-mobile/focus-android#7505]
### Why/User Benefit/User Problem
Introduce a more user friendly message to inform users that they can use the trash button

### Acceptance Criteria (how do I know when I’m done?)

- Update CFR string per copy on UX:https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4448%3A38774
- Trigger: dismissal of tracking protection CFR

**Comment by ionutbedregeanu** [comment]
Note for QA: Don't test it yet because cfrs visibility is under experiment and we don't know at this moment if the experiment will be kept or not

**Comment by lobontiumira** [comment]
Verified on a local Focus Nightly build with the following devices:
* Lenovo tablet M10 (Android 10),
* Samsung Galaxy Note 8 (Android 9),
* Sony Xperia Z5 Premium (Android 7.1.1),
* Google Pixel (Android 10),
* Xiaomi Mi8 Lite (Android 10),
* Oppo Reno 6 (Android 12), and
* Samsung Galaxy Tab A6 (Android 5.1.1).

And the behavior is:
* the trashcan CFR is dismissed when the devices is turned into landscape/or viceversa,
* the tracking protection CFR is always displayed **before the trashcan CFR**,
* while the tracking protection CFR is displayed, after tapping anywhere on the screen, the tracking protection CFR is dismissed, then the trashcan CFR is displayed,
* if the tracking protection CFR is NOT displayed on a first opened page (for example if the user opens wikipedia.org), the trashcan CFR is no longer displayed, at all,
* while the tracking protection is displayed, if the user turns the devices into landscape/portrait, the CFR is dismissed, and the trashcan CFR is no longer displayed, at all.

@rtestard @amedyne please review and advise regarding the last 2 behaviors of the trashcan CFR described above.
Thank you!

![Screenshot_2](https://user-images.githubusercontent.com/40694158/189671076-6f34c13e-a4c8-497e-ae19-68ca07919319.jpg)
