### ISSUE TITLE
Introduce an onboarding step to promote widget addition

### ISSUE THREAD

**Issue by rtestard** [mozilla-mobile/focus-android#7506]
### Why/User Benefit/User Problem
Discovering widgets is hard, telling users about the widget availability should drive adoption.

### Acceptance Criteria (how do I know when I’m done?)

- After using the trash icon for the first time, display a "Browsing history cleared" UI per UX https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4448%3A38774
- Selecting the cross will get users to the home screen
- Selecting "Add Widget to home screen" button the user to the browser UI and displays a notification informing the user that a Widget was added to their homescreen
- Telemetry helps identify if a user saw the “Add widget” tooltip, engaged with the “Add to homescreen” button and succeeded in the widget addition
- Exposure of the search widget tooltip can be toggled through Nimbus to facilitate experiments
- Android 5, 6 and 7 users don’t see this message (the population is too small)
- If the widget was not added before, display the widget promo again on next data clearing action after 5th Focus session

**Comment by ionutbedregeanu** [comment]
@jeffreygee The current figma design will be used for both, dark and light themes?
The snackbar "Browsing history cleared" should be displayed while this popup is displayed, should be removed at all or should we show it only when the popup is not displayed?

**Comment by jeffreygee** [comment]
@ionutbedregeanu - I added a dark version [here](https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4617%3A40516) 

The latter is correct - The snackbar should show how it normally does already, except for when this popup is displayed.

**Comment by iorgamgabriel** [comment]
@jeffreygee @amedyne @rtestard 
What it is the final design that I need to implement ?
First 
![image](https://user-images.githubusercontent.com/8118371/189637095-196c1337-b429-4bb5-977d-8e1cd1f3a373.png)

**Comment by amedyne** [comment]
Per discussion today, it's the second design.

**Comment by iorgamgabriel** [comment]
The search widget picture from dialog is different in light mode and dark mode . Please update the design. @jeffreygee @rtestard @amedyne

**Comment by iorgamgabriel** [comment]
@rtestard Suggested that we will not keep the snackBar with "Browsing history cleared" since the widget promo modal mentioned browsing history cleared inside the modal  @jeffreygee. This is how I implemented it .

**Comment by lobontiumira** [comment]
Verified as implemented on the latest debug build Focus Nightly 107.0a1 with the following devices:
* Oppo Reno 6 (Android 12),
* Lenovo tablet M10 (Android 10),
* Sony Xperia Z5 Premium (Android 7.1.1),
* Samsung Galaxy A6 (Android 5.1.1)

![widget prompt](https://user-images.githubusercontent.com/40694158/191744401-9e93c237-6089-4e4e-a81a-b8b94188c76b.png)


** The widget prompt is displayed after tapping the trashcan option (when closing a page).
** Tapping the "Add widget to home screen" button, redirects the user to the "Add to home screen" prompt (not working on all the devices - see #7711). Tapping on "Add" adds the widget to the homescreen without issues. The widget works properly.
** Tapping the "X" close button from the top-right corner of the prompt dismisses the prompt.
** The widget follows the device's theme.
