### ISSUE TITLE
Custom set to default onboarding page for Huawei users

### ISSUE THREAD

**Issue by rtestard** [mozilla-mobile/focus-android#7511]
### Why/User Benefit/User Problem
Huawei users don't have access to set to default OS settings the way other Android users do. We need custom handling of this case so they are informed   about what to do in order to set Focus as default browser.

### Acceptance Criteria (how do I know when I’m done?)
- For HuaWei phone users, onboarding scre2 (https://github.com/mozilla-mobile/focus-android/issues/7502) is replaced with a different screen that points users to an informational page detailing how users can change their default browser.

**Comment by rtestard** [comment]
@jeffreyge Can you please help with UX for this?

**Comment by jeffreygee** [comment]
@rtestard - UX for review: https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4996%3A41824

**Comment by rtestard** [comment]
This looks good to me, thanks!

**Comment by iorgamgabriel** [comment]
@rtestard @jeffreygee This is the page that i should open if the phone is Huawei https://support.mozilla.org/en-US/kb/make-firefox-default-browser-android ?

**Comment by rtestard** [comment]
Yes, I raised https://bugzilla.mozilla.org/show_bug.cgi?id=1791564 to get the content updated on that page to cover Huawei users.

**Comment by iorgamgabriel** [comment]
@rtestard @jeffreygee What should happen after the user closes the page ? This is how I implemented it : Onboarding get close and the pop-up with promote search dialog will appear because it is the first enter in browsing . Is it okay?

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on a Focus local build 106.0 (Build #11). After taping the "Set as default browser" button from the second onboarding screen the user is redirected to the following page: https://support.mozilla.org/en-US/kb/set-firefox-focus-default-browser-android.
### Device used:
- Huawei MediaPad M3 (Android 7)

**Comment by rtestard** [comment]
> @rtestard @jeffreygee What should happen after the user closes the page ? This is how I implemented it : Onboarding get close and the pop-up with promote search dialog will appear because it is the first enter in browsing . Is it okay?

Yes, this aligns with https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4996%3A41824, looks all good to me
