### ISSUE TITLE
Missing locale names for skr locales

### ISSUE THREAD

**Issue by bcolsson** [mozilla-mobile/focus-android#7521]
### Steps to reproduce
1. Open settings in Nightly
2. Select Language
3. Observe Saraiki and Toki Pona being displayed with just their locale codes (skr / tok)

### Expected behaviour
Language settings should display the language name in its native language and English:
skr
سرائیکی
Saraiki

### Actual behavior
Locale code displayed with initial caps:
Skr

### Device information

* Android device: ?
* Focus version: focusDebug

**Comment by delia-pop** [comment]
Verified as fixed on Focus Nightly 106.0a1 from 08/24 with Google Pixel 6 (Android 13). The "سرائیکی" name is displayed for Saraiki.
<img src="https://user-images.githubusercontent.com/89388888/186605876-245e3f13-1b7b-4e31-90da-b3e7e378d031.JPEG" width="40%" />
