### ISSUE TITLE
I'm having issues where I can enter fullscreen, but I can't exit. Any ideas for help?

### ISSUE THREAD

**Issue by sgebr01** [mozilla-mobile/focus-android#7532]
## Steps to reproduce
Use a simple basic Geckoview app.
Load YouTube Mobile site("https://m.youtube.com")
Select any video
Go into fullscreen
Try to exit fullscreen
### Expected behavior
Should exit fullscreen on fullscreen button click
### Actual behavior
Just stays in fullscreen

### Device information

* Android device: Pixel XL
* Focus version: N/A, Geckoview Version - 97

**Comment by kbrosnan** [comment]
dupe bz-1786171
