### ISSUE TITLE
Private session is closed after denying permissions 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#7536]
## Steps to reproduce
1. Go to https://mozilla.github.io/webrtc-landing/gum_test.html. 
2. Select "Camera".
3. Tap "Allow".
4. Send the app in background.
5. Go to the device's settings, to Apps - Focus - Permissions, and turn the Camera custom setting toggle off.
6. Access Focus and observe if the page is step 1 is still open.

### Expected behavior
The browsing session should remain opened.
### Actual behavior
The browsing session is automatically ended after denying the permission.
### Device information

* Android device: Google Pixel 6 (Android 13)
* Focus version: Latest Nightly 106.0a1, Beta 105.0b1, also reproducible on Fenix in Private Mode.
Note that on Fenix Normal Browsing, the session is not closed, only restarted.

https://user-images.githubusercontent.com/89388888/186182226-96c408d0-3eec-4f32-8f89-4e631aed2c46.mp4

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802628

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
