### ISSUE TITLE
Microphone icon is incorrectly placed on the 2x1 size widget 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#7547]
## Steps to reproduce
1. Long tap on the home screen of the device.
2. Set a widget for Focus Nightly.
3. Resize the widget to 2x1.
4. Observe the microphone icon placement.
### Expected behavior
The microphone icon is placed on the right end of the widget.
### Actual behavior
The microphone icon is incorrectly placed on towards the Firefox Focus logo.
On tablet, this issue only occurs in landscape mode.
### Device information

* Android device: Google Pixel 6 (Android 13), Lenovo Yoga Tab 11 (Android 11).
* Focus version: latest Focus Nightly 106.0a1 from 08/24.

<img src="https://user-images.githubusercontent.com/89388888/186596521-2198689b-5227-48d2-b40a-4c6a0adf07f5.JPG" width="40%" />

https://user-images.githubusercontent.com/89388888/186596639-41482492-a1c3-48db-b758-e77f44440a32.mp4

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802627

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
