### ISSUE TITLE
The text overlaps the microphone icon on the 1x2 widget

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7565]
## Steps to reproduce
1. Have Focus Beta installed.
2. Long-tap on the homescreen of the device, in order to acces the Widgets.
3. Set Focus Beta as widget.
4. Resize the widget to the 1x2 size, and observe.

### Expected behavior
The widget only displays the Focus logo, and the microphone icon.
The screenshot below is from the [Figma design](https://www.figma.com/file/nCvlz8wsL1w7dLPag32Syz/Widget?node-id=2%3A277):
![Screenshot_2](https://user-images.githubusercontent.com/40694158/187197034-8367797b-858f-416b-8716-30ac6cdeafff.jpg)

### Actual behavior
The "Search the web" text overlaps the microphone icon.
After resizing several times, the text is no longer displayed on the 1x2 widget.
The Fenix Beta 1x2 widget has no microphone icon displayed (issue filed on Fenix repo [9323](https://github.com/mozilla-mobile/fenix/issues/9323)).

### Device information
* Android device: Lenovo tablet M10 (Android 10)
* Focus version: Beta 105.0b3
* Not reproducible on Fenix Beta 105.0b3

![Screenshot_3](https://user-images.githubusercontent.com/40694158/187198274-ac125286-4485-4dd5-8e13-bb09b50632ca.jpg)

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.
