### ISSUE TITLE
Finalize list of languages

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#757]
So far we just imported everything from the L10N repository. Now we need to decide which languages we want to ship and whether we should (temporarily, for the release) remove any translations.

**Comment by pocmo** [comment]
I removed all languages that are not at 100% from the repository:

 * Albanian (sq) - 85%
 * Asturian (ast) - 53%
 * Bengali (bn-BD) - 71%
 * Bengali (bn-IN) - 71%
 * Hindi (hi-IN) - 71%

**Comment by Delphine** [comment]
I've just checked all the other pending languages one last time. For Albanian, Bengali (bn-BD), Bengali (bn-IN) and Hindi, all the most important parts of the UI are translated and look good. 
The only main thing missing is the Onboarding section for those locales, which appears in English.
However, I would still add them as most of the UI is complete and the app is totally usable in those languages - and I've seen our competitors use partial localizations on some of their browsers too.
I wouldn't add Asturian though as there are still too many missing strings.

**Comment by Delphine** [comment]
All the other languages that are at 100% are also good to go and can be added.

**Comment by pocmo** [comment]
Thanks! Re-added everything but "ast".
