### ISSUE TITLE
Blank widgets on Google Pixel

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7570]
## Steps to reproduce
1. Have the latest Focus Nightly 106.0a1, and Beta 105.0b3 installed.
2. Add widgets from these two apps mentioned at step 1.
3. Observe them.

### Expected behavior
The widgets have all the elements displayed.

### Actual behavior
The widgets are blank. 
Also, the behaviour is strange, but I'll file a new issue for that.

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: Focus Nightly 106.0a1 from 8/30, and Beta 105.0b3
* On Fenix Nightly only the microphone icon is displayed

https://user-images.githubusercontent.com/40694158/187369429-7e61a7a7-a4cb-4ce3-9c3c-bc2313013cb2.mp4

**Comment by Mugurell** [comment]
Are other widgets affected also? Like those of Chrome / Google Search / other apps?

**Comment by lobontiumira** [comment]
@Mugurell I am not able to reproduce the issue anymore. 
I will test for a couple of days, to observe if the issue still occurs, and, if not, I'll close it as invalid.
Thank you!

**Comment by lobontiumira** [comment]
I was able to reproduce this again today on the RC 105.1.0 build, twice, than the search widget displayed properly.
I managed to get a logcat, maybe it helps: [logcat (2).txt](https://github.com/mozilla-mobile/focus-android/files/9644534/logcat.2.txt)

![Screenshot_20220926-113924](https://user-images.githubusercontent.com/40694158/192232755-8b1f2cdb-ce10-4eba-a706-a5faa256c5fb.png)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802593

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
