### ISSUE TITLE
Searching through the widget doesn't open a new tab for each search

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7571]
## Steps to reproduce
1. Have the latest Focus Nightly 106.0a1 installed, or the latest Beta 105.0b3.
2. Add the widget of any of the apps mentioned at step 1.
3. Although the widgets are blank (see #7570), tap on the search field in order to perform a search.
4. Exit the app, and tap again on the search field.

### Expected behavior
Every search via the widget is performed in a new tab.

### Actual behavior
Every time the user is tapping the widget's search filed the previous opened tab is displayed.
Voice search doesn't work at all, since the microphone icon isn't displayed.

### Device information
* Android device: Google Pixel (Android 10)
* Not reproducible on Samsung Galaxy Note 8 (Android 9), Lenovo tablet M10 (Android 10), nor Xiaomi mi4i (Android 5.0.2)
* Focus version: Focus Nightly 106.0a1, Beta 105.0b3
* Fenix Nightly 106.0a1 from 8/30

https://user-images.githubusercontent.com/40694158/187372573-264d5bf4-5b86-487b-847b-8f0ec8f8155f.mp4

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the latest Focus Nightly build 109.0a1 from 11/21 with Google Pixel (Android 10).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802626

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
