### ISSUE TITLE
Incorrect widget logo displayed in preview for Focus Nightly and Beta

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#7574]
## Steps to reproduce
1. Long tap on the home screen of the device.
2. Search for the widget for Focus Nightly and Focus Beta.
3. Observe the logo displayed on the widget previews.
### Expected behavior
The Focus Nightly logo is displayed on the Focus Nightly widget.
The Focus Beta logo is displayed on the Focus Beta widget.
### Actual behavior
The Firefox  Focus logo is displayed on the Focus Nightly and Focus Beta widgets.
### Device information
* Android device: Google Pixel 6 (Android 13), Lenovo Yoga Tab 11 (Android 11)
* Focus version: latest Nightly 106, Beta 105.0b3

Also reproducible on other devices.
Similar ticket reported on Fenix: https://github.com/mozilla-mobile/fenix/issues/26708

<img src="https://user-images.githubusercontent.com/89388888/187494670-7cc1700c-a9f3-4d5d-a542-440569eb5900.jpeg" width="40%" />

**Comment by Mugurell** [comment]
Currently we have one set of previews used for all flavors - https://searchfox.org/mozilla-mobile/search?q=focus_search_widget.png&path=&case=false&regexp=false
We would need new resources to use as previews for the other flavors.
This issue would also affect Klar which currently uses the same previews as Focus.
@jeffreygee

**Comment by mcarare** [comment]
Starting with Android 12 you can show a widget [preview](https://developer.android.com/develop/ui/views/appwidgets/enhance#improve-widget-picker-experience) from an XML layout.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802246

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
