### ISSUE TITLE
Update UI tests - <FirstRunTest>,<CustomTabTest>

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/focus-android#7580]
Update the ui tests to support new OnBoarding flow

**Comment by AndiAJ** [comment]
Disabled UI tests in #7566
`openCustomTabInFocusTest`
`firstRunOnboardingTest`
`skipFirstRunOnboardingTest`

**Comment by AndiAJ** [comment]
Re-enabled `openCustomTabInFocusTest` in #7792

**Comment by AndiAJ** [comment]
`firstRunOnboardingTest` and `skipFirstRunOnboardingTest` re-enabled in #7791
