### ISSUE TITLE
Download prompts do not work in custom tabs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#7591]
## Steps to reproduce
1. Open a custom tab to a page that has a download link.
2. Try and click the link to download a link.

### Expected behavior
- You are prompted to download said file.

### Actual behavior
- Nothing appears to happen.

### Device information

* Android device: Android 12
* Focus version: Nightly (latest as of filing)

**Comment by jonalmeida** [comment]
A quick peak at the code showed that we are not passing in a tabId to the `DownloadsFeature` in the `BrowserFragment` , so I suspect that might be the only change required to fix this bug.

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.

**Comment by lobontiumira** [comment]
I am able to reproduce this on Beta 105.0b5 with Lenovo tablet M10 (Android 10).

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 106,0a1 from 7/9 with the following devices:
* Sony Xperia Z5 Premium (Android 7.1.1),
* Samsung Galaxy Note 8 (Android 9), and
* Oppo reno 6 (Android 12).

![Screenshot_2](https://user-images.githubusercontent.com/40694158/188835155-2e377a8a-ebd6-4301-818b-a636eb4ac955.jpg)

**Comment by lobontiumira** [comment]
Verified as fixed also on Beta 105.0b6 with Lenovo tablet M10 (Android 10), Xiaomi mi4i (Android 5.0.2), and Oppo Reno 6 (Android 12).
