### ISSUE TITLE
[Android 5] The second screen of the onboarding is not displayed at all

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7599]
## Steps to reproduce
1. Install Focus Nightly, making sure the new onboarding is available, on an Android 5 device.
2. Tap on the "Get started" button, in order to reach the second screen.

### Expected behavior
The second screen of the onboarding is displayed.

### Actual behavior
The user is redirected to the homepage.
Might be because, on these devices, setting the default browser is a little bit more tricky.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), and Xiaomi mi4i (Android 5.0.2)
* Focus version: Focus Nightly 106.0a1 
* Short video:

https://user-images.githubusercontent.com/40694158/188464138-fe40627f-1369-4f22-839e-5e2cab95d293.mp4

### Figma design
https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding?node-id=4617%3A40516

**Comment by ionutbedregeanu** [comment]
"Android 5 and 6 users don’t see this message (population is too small)Android 5 and 6 users don’t see this message (population is too small)" https://github.com/mozilla-mobile/focus-android/issues/7502
This seems expected, so I will close this ticket
