### ISSUE TITLE
Don't load blocklists on the UI thread

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#76]
We currently load the blocklists on the UI thread. That's bad.

We only ever access the lists (i.e. do URL matching) on a background thread, i.e. webkit calls shouldInterceptRequest() off the UI thread. There's no need at all to have this data be available for UI thread calls. We could easily load the data the first time shouldInterceptRequest() is called.

I think it would be even better to try to preload the data as early as possible, e.g. during app startup - that means once we try to load a URL we already have all data available and loaded. (I have local patches which do this. We are still able to load during shouldInterceptRequest() as a backup, but we try to load at startup.)

**Comment by pocmo** [comment]
> I think it would be even better to try to preload the data as early as possible, e.g. during app startup - that means once we try to load a URL we already have all data available and loaded.

I agree! There's a high chance that the user just visits a specific URL and then leaves Focus again. So we shouldn't make the actual load of this website slower but instead load the lists while the user might still be typing etc.
