### ISSUE TITLE
"Secure Connection Failed" when accessing the page at balikesirulasim.com.tr

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#7608]
## Steps to reproduce
1. Navigate to: https://www.balikesirulasim.com.tr/.
2. Observe the result.

### Expected behavior
The page loads.
### Actual behavior
"Secure connection failed" message is displayed:

![Screenshot_48](https://user-images.githubusercontent.com/75027050/188572232-c4814cf1-d668-4186-bfcd-ababcedf5357.jpg)

### Device information

* Android device: Samsung A51 (A11), Google Pixel 3 (A12)
* Focus version: Firefox Fenix Nightly 106.0a1 (2015902251-🦎106.0a1-20220904093956🦎)

**Notes:**

1. Reproducible regardless of the status of ETP.
2. Reproducible on the latest build of Firefox Focus Nightly and Release.
3. Works as expected using Firefox Fenix Nightly, both normal and private mode.
4. According to SSL Labs:
![Screenshot_49](https://user-images.githubusercontent.com/75027050/188572170-40ee9bdd-96c4-43ca-ba3f-7c2546dc9dd4.jpg)

**Comment by Mugurell** [comment]
This is happening for me also on Fenix and on GVE no matter the private mode status.
It's interesting that there is no issue on Desktop.

https://user-images.githubusercontent.com/11428869/188625473-58b389c8-9c04-41fb-8d13-96d9c9a4cfed.mp4

Moving the ticket to Bugzilla.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1789395

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
