### ISSUE TITLE
java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#761]
Buddybuild detected a crash
`app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java` line `394`

```java


        final String cookie = CookieManager.getInstance().getCookie(download.getUrl());
        final String fileName = URLUtil.guessFileName(
                download.getUrl(), download.getContentDisposition(), download.getMimeType());

        final DownloadManager.Request request = new DownloadManager.Request(Uri.parse(download.getUrl())) <-- CRASHED
                .addRequestHeader("User-Agent", download.getUserAgent())
                .addRequestHeader("Cookie", cookie)
                .addRequestHeader("Referer", getUrl())
                .setDestinationInExternalPublicDir(download.getDestinationDirectory(), fileName)
                .setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED)
```

[View File](https://github.com/mozilla-mobile/focus-android/blob/5a0c0da5d84133918d8a8a9e9707d81858fdcced/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java#L394) | [View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/379e63793197857ba2d66aae243cb8b3)

**Comment by Sohaib-Aslam** [comment]
I just had the same problem. For some reason, my URL had one kind of white space before the "https". Using trim() on the URL String solved the problem.

**Comment by mukeshverma4000** [comment]
> I just had the same problem. For some reason, my URL had one kind of white space before the "https". Using trim() on the URL String solved the problem.

i cant understand please help
