### ISSUE TITLE
Remove multiTabsFeature experiment branch from code

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#7616]
When running the `multiTabsFeature` experiment, we have these checks around the codebase. Now that we're done with the experiment, do we still need them? Can we remove them if product is okay with it?

Why remove? It simplifies the tab logic that we had to put in place for this experiment.

cc @rtestard

**Comment by rtestard** [comment]
That sounds good to me, no tab experiment are being considered

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 106.0a1 from 9/8 that there are no regressions, that the user can open multiple tabs, close them, without issues.
Tested with the following devices:
* Samsung Galaxy Note 8 (Android 9),
* Samsung Galaxy Tab A6 (Android 5.1.1),
* Sony Xperia Z5 Premium (Android 7.1.1), and
* Lenovo tab M10 (Android 10).
