### ISSUE TITLE
Nimbus support for A/B testing the new onboarding

### ISSUE THREAD

**Issue by rtestard** [mozilla-mobile/focus-android#7620]
### Why/User Benefit/User Problem
We want to validate our assumptions regarding the new user onboarding through an A/B test:
- Improve 7 days new user retention
- Improve CDoU per new profile

### What / Requirements
Nimbus can remote controle enablement of all changes under https://github.com/mozilla-mobile/focus-android/issues/7501

**Comment by Amejia481** [comment]
Requires https://mozilla-hub.atlassian.net/browse/EXP-2697

**Comment by iorgamgabriel** [comment]
Nimbus documentation can be found in https://github.com/mozilla-mobile/focus-android/blob/main/.experimenter.yaml .

Locally for testing purpose we can control the onboarding , all Cfrs and the dialog for promote search widget from here https://github.com/mozilla-mobile/focus-android/blob/main/nimbus.fml.yaml .If the default value is changed to true, the feature will appear. By default all of them are active in debug mode. 

The implementation was done in this pull request:  https://github.com/mozilla-mobile/focus-android/pull/7657 , https://github.com/mozilla-mobile/focus-android/pull/6618

**Comment by iorgamgabriel** [comment]
Thank you @Amejia481

**Comment by lobontiumira** [comment]
I've verified that the onboarding feature configuration is present in the experimenter.yaml file from the focus-android repo. Also the feature config is displayed on the Experimenter console and can be configured.
@rtestard  To test an actual A/B experiment a new JIRA ticket is required for the Ecosystem QA team to validate it.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802592

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
