### ISSUE TITLE
"Secure connection failed" when accessing versowood.fi

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#7633]
## Steps to reproduce
1. Navigate to: https://www.versowood.fi/fi/tuotteet
### Expected behavior
The page loads as expected.
### Actual behavior
"Secure connection failed" message is displayed
### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)/ Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)
* Focus version: Firefox Focus Nightly 106.0a1 (362520510-🦎106.0a1-20220908190311🦎)

1. Reproducible regardless of the status of ETP.
2. Not reproducible using the latest build of Firefox Nightly in Normal Browsing Mode and in Private Browsing Mode.
3. Reproducible on both Release and Nightly Version of Firefox Focus.
4. Screenshot attached:
![Screenshot_26](https://user-images.githubusercontent.com/75027050/189366014-3106cb45-b9c3-470c-a364-7138c0755733.jpg)

**Comment by Mugurell** [comment]
Reproduces in Fenix also for me and also on GVE.
Seems similar to the other scenarios which would benefit from https://bugzilla.mozilla.org/show_bug.cgi?id=1520297, closing as duplicate.

https://user-images.githubusercontent.com/11428869/189376484-d9e5e435-ccc5-4326-b58f-2c54b5b4338a.mp4
