### ISSUE TITLE
Cursor in search box teleports on m.youtube.com if you type as soon as the page loads

### ISSUE THREAD

**Issue by IgorTrp** [mozilla-mobile/focus-android#7635]
## Steps to reproduce
Go on https://m.youtube.com
As soon as the page loads click the search button(magnifying glass) and start typing
### Expected behavior
It should type normally and cursor line shouldn't move by itself.
### Actual behavior
After a second of two the cursor line moves a couple of characters back by itself
### Device information

* Android device: ?
* Focus version: 104.2.0

https://user-images.githubusercontent.com/72347790/189434256-00487a12-5414-40ac-b89f-36e71b2c1d0c.mp4

**Comment by mcarare** [comment]
@IgorTrp Thank you for your report! Can you please specify what Android device you are using and what keyboard?

**Comment by IgorTrp** [comment]
Im using Huawei P10 lite with Android version 8.0.0. Keyboard im using is Microsoft SwiftKey.
Also i should note that this bug does not occur in google chrome browser on Android, i tried it.

**Comment by IgorTrp** [comment]
> @IgorTrp Thank you for your report! Can you please specify what Android device you are using and what keyboard?

Im using Huawei P10 lite with Android version 8.0.0. Keyboard im using is Microsoft SwiftKey.
Also i should note that this bug does not occur in google chrome browser on Android, i tried it.

**Comment by mcarare** [comment]
@IgorTrp Does it occur with other keyboards? (Gboard for example)

**Comment by IgorTrp** [comment]
No, but a different glitch occurs. 
It doesn't write out the first letter, as if the page loads visually but it needs half a second more to start accepting keyboard input.
This occurs when i use Gboard or Grammarly keyboard. It doesn't happen on google chrome.

**Comment by mcarare** [comment]
@IgorTrp Does it also happen in Firefox?

**Comment by IgorTrp** [comment]
No just focus. I tested it with Swiftkey and Grammarly keyboards

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802615

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
