### ISSUE TITLE
The second screen of the new onboarding is scrollable on some devices

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7645]
## Steps to reproduce
1. Install the latest Focus Nightly local build.
2. Tap on "Get started" button, in order to get to the second onboarding screen.
3. Observe the second screen.

### Expected behavior
The second onboarding screen isn't scrollable.

### Actual behavior
The second onboarding screen is scrollable.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1 - 2160 x 3840 pixels, 16:9 ratio (~806 ppi density)), Google Pixel (Android 10 - 1080 x 1920 pixels (~441 ppi pixel density)), and HTC 10(Android 8 - 1440 x 2560 pixels (~565 ppi pixel density))
* Focus version: local build of Focus Nightly from 9/9
* Not reproducible on Samsung Galaxy Note 8 (Android 9), Oppo Reno 6 (Android 12)
* The short videos are below.

**Comment by lobontiumira** [comment]
https://user-images.githubusercontent.com/40694158/189929031-22f56a6a-276a-4982-89fe-c17fdffc7e21.mp4

**Comment by lobontiumira** [comment]
https://user-images.githubusercontent.com/40694158/189929204-0df9ba11-bfa7-42d4-8cb9-894e0c82d7ab.mp4

**Comment by iorgamgabriel** [comment]
Based on @jeffreygee comment both screens from OnBoarding must support only  portrait mode.

**Comment by Mugurell** [comment]
> Based on @jeffreygee comment both screens from OnBoarding must support only portrait mode.

Even with blocking the screen to only portrait the issue still remains. Should the screen be scrollable or should the image allow for dynamic resizing to ensure everything fit on the screen?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802245

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
