### ISSUE TITLE
Update Core Splashscreen to stable version

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#7647]
We currently use `1.0.0-beta01`. We should move to a stable 1.0.0

**Comment by mcarare** [comment]
For QA: Tagged just for QA to check that the splash screen works the same as before the upgrade. TY!

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 107.0a1 from 9/22 that the splash screen works the same as before.
Tested on Lenovo tablet M10 (Android 10), Sony Xperia Z5 Premium (Android 7.1.1), and Oppo Reno 6 (Android 12).
