### ISSUE TITLE
Search widget unlocks fingerprint lock

### ISSUE THREAD

**Issue by GeorgeRNG** [mozilla-mobile/focus-android#7678]
## Steps to reproduce
Enable fingerprint to unlock app
On the android home screen, add the widget to Search the web
Use it and enter a link

### Expected behavior
You are stopped from accessing previous open links with the fingerprint

### Actual behavior
You can access the links

### Device information

* Android device: Samsung S8 (Android 9), Samsung S10 (Android 12)
* Focus version: 105.0.7

**Comment by amedyne** [comment]
@jeffreygee Any guidance for this one?

**Comment by iorgamgabriel** [comment]
If the lockScreen is active doesn't matter from where the user enters in the app the lockScreen should appear.

If a browsing page is open and the users closes the app but doesn't removed it from background , when he opens again the app he should be redirected to that page (if the lockScreen is active it should appear first and after that the browsing page ).

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 107.0a1 from 10/11 with:
* Oppo Reno 6 (Android 12), and
* Samsung Galaxy Note 8 (Android 9).
