### ISSUE TITLE
Add option to position the search bar at the bottom of the screen

### ISSUE THREAD

**Issue by Hexb0y** [mozilla-mobile/focus-android#7692]
### Why/User Benefit/User Problem

- Smartphone screens are getting larger, placing the search engine at the top of the screen makes accessibility for one-handed users and people with motor function disabilities or hand injuries more difficult to reach an integral function of the app.

- More consistent design language with the Firefox Android app.

### What / Requirements

- Include a menu or toggle option in the settings menu to move the search bar to the bottom of the screen instead of the top.

### Acceptance Criteria (how do I know when I’m done?)
- The search bar is moved to the bottom of the screen and functions normally similar to the Firefox app, as seen in the screenshot below.

**Firefox Search Bar**
![image](https://user-images.githubusercontent.com/92604980/191198202-b01b8eef-1907-475b-a906-8ef07b936710.jpeg)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801990

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
