### ISSUE TITLE
Change progress bar color to gradient

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#77]
![gradient_bar](https://cloud.githubusercontent.com/assets/89638/23059136/4b13cb0a-f4f8-11e6-8161-d426f227bcf5.png)

**Comment by antlam** [comment]
I'm ok with kicking this can down the line depending on how hard it is to implement. 

It was spec'd out for iOS but it turned out to be harder to do so this is lower priority for me ATM

**Comment by pocmo** [comment]
@antlam I created a patch with the following gradient. Let's polish the colors etc. once you are back. :)

![gradient_progress](https://cloud.githubusercontent.com/assets/89638/24657919/6833e700-1948-11e7-9a7f-8fa9ef9099b6.png)

**Comment by antlam** [comment]
@pocmo for the record, what colors did you use in the screenshot above?

**Comment by pocmo** [comment]
I used the colors from the (active) toolbar in reverse, and made them a little bit brighter for contrast:
* Start: #495aa3
* Center: #9c4296
* End: #b5445a
