### ISSUE TITLE
CustomTab clobbers existing Focus session

### ISSUE THREAD

**Issue by callahad** [mozilla-mobile/focus-android#770]
Steps to Reproduce (Focus build 1979 (RC1) on Android 7.1.2):

1. Set Focus as the default browser
2. Open the Focus app, navigate to http://example.com
3. Open the GMail app, click on a link in an email
4. Press Home
5. Open the Focus app

What should happen:

- My previous Focus session opens, displaying http://example.com

What actually happens:

- The custom tab from Gmail opens, neither Focus nor http://example.com are visible / accessible.
- Clicking the "back" arrow in the Custom tab returns to the Focus home screen

This means that opening a CustomTab in Focus permanently kills my separate Focus session.

**Comment by pocmo** [comment]
That's kind of expected: For a bunch of reasons we decided to always have only one session open at a time. This is something we might reconsider in a future version though.

**Comment by pocmo** [comment]
I agree that launching Focus should probably not resume the custom tab session.

**Comment by mystor** [comment]
I also noticed this and filed it in bugzilla (as I didn't realize that focus for android issues were tracked on github :-S) https://bugzilla.mozilla.org/show_bug.cgi?id=1376065

I don't personally care much about it killing my previous session, but I really don't want to end up inside of a gmail custom tab after clicking on the focus icon in the launcher.

**Comment by npark-mozilla** [comment]
Verified that now the previous Focus session is gone, and the user will see the initial Focus screen when resuming the Focus app after opening Custom Tab

**Comment by npark-mozilla** [comment]
Hmm, @pocmo a question - when custom tab is opened and then user returns to the main Focus app, and open a webpage, now that is retained when the user switches back and forth between the custom tab and the Focus app session. Since only one session is allowed, shouldn't Focus app clear its session each time it is opened?

**Comment by pocmo** [comment]
@npark-mozilla I'm not sure I fully understand the question. Focus itself should behave as it did before. Custom Tabs are now "owned" by the app opening them and should not affect Focus itself.

**Comment by brampitoyo** [comment]
@npark-mozilla Correct. There is an explicit separation between Custom Tabs (which are owned by and are considered a part of the app opening them) and Focus Browser Tabs (which are owned by Focus), whatever you do in one shouldn’t impact the other.
