### ISSUE TITLE
The "Add widget to home screen" button from the widget prompt doesn't work on all devices

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7711]
## Steps to reproduce
1. Install a debug Focus Nightly build 107.0a1, that has the widget prompt implemented.
2. Open a page.
3. Tap on the trashcan.
4. When the widget prompt is displayed, tap on the "Add widget to home screen" button.

### Expected behavior
The second prompt is displayed that asks the user to add the widget to the home screen.

### Actual behavior
The widget prompt is dismissed without other actions from the user. The widget is not added.
The widget can be added by the user without issues, via the long-tap on the home screen - select "Widgets" - select and drag manually the Focus Nightly widget.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), **Xiaomi mi8 Lite (Android 10)**
* Focus version: Focus Nightly 107.0a1 debug build
* In [7506](https://github.com/mozilla-mobile/focus-android/issues/7506#issue-1340257236), was mentioned that "Android 5, 6 and 7 users **don’t see this message** (the population is too small)", but the widget prompt is displayed!
* The logcat: [logcat.txt](https://github.com/mozilla-mobile/focus-android/files/9625584/logcat.txt)

https://user-images.githubusercontent.com/40694158/191742546-5131f3ec-d8d9-40b8-a0fc-d6feb7eb515a.mp4

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802611

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
