### ISSUE TITLE
Intermittent UI test failure - SwitchLocaleTest.FrenchLocaleTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#7718]
Was disabled on https://github.com/mozilla-mobile/focus-android/pull/7699
because of compose scrolling issue: https://github.com/mozilla-mobile/focus-android/issues/7282

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802610

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
