### ISSUE TITLE
(Crash) java.lang.NullPointerException (org.mozilla.geckoview.GeckoResult$UncaughtException: at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java))

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#7732]
### Steps to reproduce

Unfortunately no reliable steps to reproduce. :( But it suddenly happened two times after bringing back Firefox Focus from the background to the foreground. I am not sure if Firefox Focus already crashed before pressing the "Unlock" button or after that. It doesn't always reproduce so I can't check that.

### Expected behavior

No crash. :) 

### Actual behavior

Crash report: https://crash-stats.mozilla.org/report/index/4b611361-8354-4bae-8f77-57f210220925

### Device information

* Android device: OnePlus 10 Pro, Android 12
* Focus version: Firefox Klar 105.1.0

**Comment by mcarare** [comment]
STR:
0. Have at least one tab opened and fingerprint unlock enabled.
1. Open Exceptions list.
2. Turn the screen off / background the app.
3. Turn the screen on / go back to the app.
4. Crash.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 107.0a1 from 10/7 with Google Pixel (Android 10), and Oppo Reno 6 (Android 12).
