### ISSUE TITLE
expose crash reports somewhere in the settings UI

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#7733]
### Why/User Benefit/User Problem

Crash reports are important for finding the cause of stability issues. At the moment you have to know as user that about:crashes exists to share crash reports with Mozilla. Firefox has a link to about:crashes on the "About Firefox" screen. I suggest to do something similar in Focus as well.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1801989

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
