### ISSUE TITLE
unexpected button colors on exeption list with light theme

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#7734]
### Steps to reproduce

0. use the light theme
1. open a website
2. press the shield button
3. disable the enhanced tracking protection
4. press the menu button > Settings > Privacy & Security > Exceptions (in the "Cookies and Site Data" section)

### Expected behavior

Other colors with better color contrast for the "Remove all websites" button.

### Actual behavior

The button has a black font color on a purple/dark pink? background which results in a bad color constrast. Maybe it's even an a11y issue due to bad readability but at least it doesn't fit the design of Firefox Focus.

![Screenshot_2022-09-25-16-06-33-49_80c65855c2fd87fe33c18da258042f3e](https://user-images.githubusercontent.com/1100614/192147947-0199ce0d-9b09-471e-b6b8-09639da14cff.jpg)

I am not sure about the dark theme. With the dark theme there are no readability issues. But compared with the "Unlock" button on the home screen after starting Firefox Focus it's a different color scheme. So it's less of a problem but could still be considered as design issue due to the inconsistency.

### Device information

* Android device: OnePlus 10 Pro, Android 12
* Focus version: 105.1.0 and Nightly

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802244

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
