### ISSUE TITLE
color constrast issue with autofill selection color on address bar

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#7735]
### Steps to reproduce

0. use the light theme
1. enter a character into the address bar

### Expected behavior

Good readability for the autofilled characters.

### Actual behavior

The autofilled characters have a black font color on a purple/dark pink? background which results in a bad color constrast.

![Screenshot_2022-09-25-16-07-07-28_80c65855c2fd87fe33c18da258042f3e](https://user-images.githubusercontent.com/1100614/192147922-33f6d259-eeea-478a-9fd1-dc5b0ba28664.jpg)

### Device information

* Android device: OnePlus 10 Pro, Android 12
* Focus version: 105.1.0 and Nightly

**Comment by mcarare** [comment]
UX should provide feedback on this (if we should keep the current behavior or specify new colors to be used).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802582

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
