### ISSUE TITLE
Focus app unexpectedly closes if history is cleared twice from the notification tray

### ISSUE THREAD

**Issue by MihaiNinu** [mozilla-mobile/focus-android#774]
MihaiNinu commented 29 minutes ago
Device: Android only

STR:

Tap a site address (e.g. qq.com since it takes a long time to load )
while site is loading, drag to open android bar
Tap on Erase focus history
Actual: Focus Crashes
Note: Please take in consideration that you might need to repeat the STR to trigger the crash

For further details please check : https://pastebin.mozilla.org/9024585

**Comment by AaronMT** [comment]
Log is set to expire after a day 
[9024585.txt](https://github.com/mozilla-mobile/focus-android/files/1075141/9024585.txt)

**Comment by pocmo** [comment]
Opened a PR with a fix for this. Can't test this thoroughly while in transit. :)

**Comment by mcomella** [comment]
After looking at the code, I discovered a simpler STR:
1. Start focus
1. load website
1. use notification to clear data
1. load a new website
1. use notification to clear data

Expected: data is clear, on homepage
Actual: app is closed

**Comment by mcomella** [comment]
I filed a related issue (#779) which is **not** fixed by Sebastian's patch.
