### ISSUE TITLE
Screenshot block notification not present on tablet devices

### ISSUE THREAD

**Issue by MihaiNinu** [mozilla-mobile/focus-android#775]
Device: Nexus 9
Android: 6.0 

STR:
1. Make sure the Stealth option is checked as active
2. Go to any site
3. Try to take a screenshot
Actual: Screenshot not taken but no toast informing "Can't take screenshot due to security policy" is present

Note: This issue could not be reproduced on a Samsung Galaxy S6 EDGE (Android 7.0) 
For further details please check https://pastebin.mozilla.org/9024589

**Comment by mcomella** [comment]
I discovered in #787 that the notification for blocked screenshots is specific to the device. Unless we add our own layer or improve the stealth mode UX, I don't think this is actionable.

**Comment by mcomella** [comment]
@bbinto to evaluate usage stats.

**Comment by pocmo** [comment]
Yep. This notification is shown by the Android system. As we are not aware that the user tried to take a screenshot there's no way for us to show our own UI in this situation.

Nexus 9 users are 0.2% of our current user base according to Google Play.
