### ISSUE TITLE
Refrain blank searches

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/focus-android#776]
Currently we let you do a blank search via no input in the address bar but by hitting the Go/Arrow on the keyboard.

=> Tap the address bar 
=> Hit Go

We should decide wether we grey out the keyboard button until a character exists in the field.

**Comment by npark-mozilla** [comment]
Actually, the fix recognizes empty spaces as valid input, instead of ignoring it. The behavior in Chrome (and in Firefox for Android) is that it ignores the input unless there is a non-space char.  Can we add a fix for it?

**Comment by ekager** [comment]
@npark-mozilla Thanks! I think I fixed this by adding a trim.

**Comment by pocmo** [comment]
Merged. :)
