### ISSUE TITLE
Canceling the "Open in app?" displayes an empty page

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7777]
## Prerequisites
Have Youtube, or Maps apps installed.

## Steps to reproduce
1. Go to Settings - Advanced, and enable the "Open links in apps" toggle.
2. Exit settings, and go to youtube.com, or maps.google.com.
3. On the "Open in apps?" tap on "Cancel".
4. Observe the page.

### Expected behavior
The page loads in browser, without issues.

### Actual behavior
The page is blank.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), and Lenovo tab M10 (Android 10)
* Focus version: 107.0a1 Focus Nightly, Beta 106.0b3
* The logcat: [logcat.txt](https://github.com/mozilla-mobile/focus-android/files/9681807/logcat.txt)
* Short video:

https://user-images.githubusercontent.com/40694158/193216693-698517e8-c3d6-4e8d-b755-45db30704c99.mp4

**Comment by iorgamgabriel** [comment]
This issue is not so new was introduced with this pull request https://github.com/mozilla-mobile/android-components/pull/12382 in 103 version . @rpappalax
