### ISSUE TITLE
The uneraseable "y"

### ISSUE THREAD

**Issue by alex-mayorga** [mozilla-mobile/focus-android#778]
Steps:
1. Open Focus.
2. Type "y" no quotes. youtube.com is auto completed
3. Try to delete the typed "y" by pressing "backspace" on the onscreen keyboard.
4. Repeat step 3 indefinitely...

Expected result: Typed "y" is deleted.
Actual result: Only the auto completed "outube.com" is deleted then reappears on a second "backspace" key press.

**Comment by ioana-chiorean** [comment]
Hey @alex-mayorga - what device/OS are u using and which keyboard? 
I am not able to reproduce this on Pixel (7.1.2) with RO/EN GBoard
I can try tomorrow more devices in the office.

**Comment by rtanglao** [comment]
works for me too @alex-mayorga i' also on pixel 7.1.2, english keyboard

**Comment by alex-mayorga** [comment]
This is on a Sony z3c 6.0.1 with latest Xperia Keyboard.

**Comment by MichaelKohler** [comment]
I just installed the RC without having it installed before on a Z3C (Android 6.0.1). I get the "Firefox Focus" screen with the input field in the middle of the screen. When I type "y" then it gets autocompleted to youtube.com, but pressing the backspace to delete *all* the input field is no problem with me. It does not get re-autocompleted to youtube.com as the "y" is deleted as well.

**Comment by vladioan3** [comment]
#2304

**Comment by pocmo** [comment]
See #2304 for some steps to reproduce. @npark-mozilla Are you able to reproduce this with those steps?

**Comment by npark-mozilla** [comment]
@pocmo on Gboard which it is auto set to private mode, I wasn't able to repro it, but on a multilingual keyboard, I had to delete twice to get the 'y' removed. (not counting the deletion of the autocompleted text)

**Comment by pocmo** [comment]
From the PR: We could try TYPE_TEXT_FLAG_NO_SUGGESTIONS.
