### ISSUE TITLE
Clearing browsing history from Settings or system app switcher unexpectedly closes the app (looks like crash)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#779]
Similar to #774: the Settings menu will close if you erase history from Settings.
1. Load a link
1. Click 3-dot menu -> Settings
1. Erase history from menu

Expected: ?
Actual: app closes

Checking with UX on proper behavior.

**Comment by mcomella** [comment]
Another issue with the same cause (we're in a different Activity) is that erasing browsing history with the App Switcher open will close focus and thus close the app switcher.

STR One - in focus:
1. Open focus
1. Enter a url to show the notification
1. Hit the recent app switcher
1. Erase browsing history via notification bar

Expected: ?
Actual: app switcher closes because an app in the switcher was closed

STR Two - outside of focus:
1. Open focus
1. Enter a url to show the notification
1. Hit the home button
1. Hit the recent app switcher
1. Erase browsing history via notification bar

Expected: ?
Actual: app switcher closes because an app in the switcher was closed

---

Maybe we shouldn't be finishing the Activity but rather just swapping fragments over (though this runs the risk of not clearing all of the user's data) which I think would fix this issue.

**Comment by brampitoyo** [comment]
We’ve agreed to push this forward to post-v1. It’s non-trivial to implement and would entail a pretty significant behaviour change.

Here’s my attempt to summarise the discussion that we’ll need to have:

When a URL is loaded on Focus, we show a notification that says “Erase browsing history”.

When you tap on “Erase”, we do two different things depending on whether Focus is your currently active app:

1. **If Focus is your current active app**: “Erase” will close the current tab and show the welcome screen.

2. **If Focus is not your current active app** (e.g. another app is currently active, you’re in Recent Apps, you’re in the home screen, etc.): “Erase” will quit Focus. This means that it won’t show up on Recent Apps list, and the “Erase” notification disappear from the top bar.

The discussion that we need to have is whether on condition 2, we should adopt the “Erase” behavior that we use on condition 1, or stick with the current behaviour as is.

Adopting behaviour on condition 1 means: if Focus is not your current active app, tapping “Erase” will simply close the current tab and show the welcome screen in the background. Focus is not quit. It will still show up on the Recent Apps list, and the “Erase” notification would still show up on the top bar.

**Comment by pocmo** [comment]
[Needs triage]: I want to propose moving this to the next release. The work to support multiple sessions might be helpful to solve this issue.

**Comment by pocmo** [comment]
This will get fixed as part of the multitasking refactoring. :)

**Comment by pocmo** [comment]
Fixed as part of #960.
