### ISSUE TITLE
Figure out what to do with versionName

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla-mobile/focus-android#7797]
In app/build.gradle, we set versionName. It's supposed to be bumped on merge day to follow the current Nightly train, but got missed this time around. We don't see issues in CI because it relies on version.txt instead. AFAIK, Fenix doesn't have any sort of similar version setting outside of version.txt - can we do the same for Focus to simplify things?

Otherwise, at a minimum we need to bump the current one on main to 107.

**Comment by jonalmeida** [comment]
`versionName` is a display only value (for the system and app UI) and is probably not in-sync with fenix/AC is because of oversight. We should align with the others.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802609

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
