### ISSUE TITLE
Darken Android's status bar

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#78]
![statusbar](https://cloud.githubusercontent.com/assets/89638/23059202/a78769f0-f4f8-11e6-846d-0804d51e7f6b.png)

**Comment by antlam** [comment]
Currently (on iOS), we use this UI to visually differentiate when Focus is _on_ versus _not yet engaged_ .

Here's how it breaks down:
When the user has finished loading a page successfully, use the full (brighter) gradient UI.

When the user is in "typing" mode, use the darker gradient. (we also wanted to extend this to error pages but didn't get around to that yet on iOS).
