### ISSUE TITLE
If system kills notification service, there will be no notification but user's private data may still be in app when open

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#780]
From a UX perspective, do we care enough to fix it? From an eng, is it worth the complexity? Note that our `BrowsingNotificationService` is *very* unlikely to be killed on modern devices because it is a foreground notification.

If it's worthwhile, investigate!

---

I believe this to be the case because `BrowsingNotificationService.onStartCommand` returns `START_NOT_STICKY` which means if the notification service (and notification) is killed, the system will not restart it for us. This can lead to the case where the notification is killed but the user's data is still present when they return to the app.

fwiw, if there's enough memory pressure to kill the Service though, I imagine the Activity is also likely to be killed - would browsing history still be saved?

Solution: if we return `START_STICKY` (and store any needed state in persistent storage), we can at least feel good that we're likely to be restarted, but there's no way to prevent this issue entirely.

**Comment by mcomella** [comment]
The code has changed since this bug so it may not be relevant anymore. Additionally, we may want to take this into account while refactoring our erase code (#1569).

Also, since we haven't seen this in the wild and it's primarily about correctness, only do this bug if the changes required are simple, e.g. on startup:
```kotlin
fun onCreate... {
    if (!notificationService.isRunning()) {
        cleanup();
    }
}
```

**Comment by pocmo** [comment]
> Solution: if we return START_STICKY (and store any needed state in persistent storage), we can at least feel good that we're likely to be restarted, but there's no way to prevent this issue entirely.

We used START_STICKY in the past and it bit us. It restarted the service after the process was killed. We ended up with a notification (and restarted service) but no browsing session.

**Comment by pocmo** [comment]
I wonder how likely it is that Android will kill a foreground service and not the process. A foreground service is used for audio playback in the background too. It's not like music randomly stops playing because Android killed the foreground service.

**Comment by mcomella** [comment]
> I wonder how likely it is that Android will kill a foreground service and not the process.

I agree – I wonder if we should just close this because it's another pedantic correctness issue that'll add potentially complex code and take development time but we've never seen in the wild.

> A foreground service is used for audio playback in the background too. It's not like music randomly stops playing because Android killed the foreground service.

I can't remember having personally seen this (_maybe_ on my old phone?) but I've seen reports of Android killing background music from posts on the internet. But this is likely Android killing the process, not just the foreground service.

**Comment by mcomella** [comment]
> I agree – I wonder if we should just close this because it's another pedantic correctness issue that'll add potentially complex code and take development time but we've never seen in the wild.

Feeling this more as time goes on – let's not make P5 our indecision graveyard for issues we don't want to close. We can reopen if necessary. :)

**Comment by pocmo** [comment]
I asked about this on Twitter:
https://twitter.com/Anti_Hype/status/935588849119526912

It seems like the consensus is that Android will always kill the process too - and never just a single component. So in theory this shouldn't be a problem for us - because if the process dies then the session data in memory is gone and the notification disappearing is correct.
