### ISSUE TITLE
Adding locales to Focus may be broken

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#7808]
While talking with Johan and Pascal about issue [#26964](https://github.com/mozilla-mobile/fenix/issues/26964), we realized that [this](https://github.com/mozilla-mobile/fenix/issues/26964#issuecomment-1260310029) might need to be investigated on Focus as well.
I'm not sure if we need another issue for a-c. If someone could help investigate that part it would be great :)

**Comment by mcarare** [comment]
@Delphine In Focus it seems that the list is updated by [mozilla-l10n-automation-bot](url)

This is the last update made to the list:

https://github.com/mozilla-mobile/focus-android/pull/7560 

The added language: Sinhala language (si) (සිංහල) is in the language list on the main branch. 

The languages added in April are also on the release versions on the Play Store. Not sure about the `si` and `skr` added in august.

سرائیکی

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802608

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
