### ISSUE TITLE
Images are not loading at eurocell.co.uk

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#7812]
## Steps to reproduce
1. Navigate to https://www.eurocell.co.uk/.
2. Scroll the page.
3. Observe the products.

### Expected behavior
Images are loading
### Actual behavior
Images are not loading
### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)/ Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)
* Focus version: Firefox Focus Release 105.2.0 (362762015-🦎105.0-2022091003135607🦎)/ Firefox Focus Nightly 107.0a1 (362790510-🦎107.0a1-20221005094233🦎)

1. Reproducible regardless of the status of ETP.
2. Not reproducible using the latest build of Firefox Nightly in Normal Browsing Mode and in Private Browsing Mode.
3. Reproducible on both Release and Nightly Version of Firefox Focus.
4. Screenshot attached:
![Screenshot_2](https://user-images.githubusercontent.com/75027050/194248878-66ae2a42-e89e-4017-93a8-23071ae2b3a2.jpg)
5. Originally reported here: https://github.com/webcompat/web-bugs/issues/111909

**Comment by Mugurell** [comment]
Happens to me also on Fenix and GVE but doesn't happen on desktop. Wondering if it might have to do with https://bugzilla.mozilla.org/show_bug.cgi?id=1520297. To be rechecked after the Bugzilla ticket is done.

**Comment by mcarare** [comment]
Image loading on the specified site seems to be working now.
Can QA also verify? TY!

**Comment by softvision-raul-bucata** [comment]
I was not able to reproduce the issue on the latest build of Firefox Focus Nightly, but I was able to reproduce the issue on Firefox Focus Release.
 
![Screenshot_3](https://user-images.githubusercontent.com/75027050/199926207-0fca431c-9751-4838-ac65-ea1cd565672d.jpg)

 
**Tested with:**

Browser / Version: Firefox Focus Release 106.1.0 (362840108-🦎106.0-221010181815🦎)/ Firefox Focus Nightly 108.0a1 (363080511-🦎108.0a1-20221103095349🦎)
Operating System: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
Operating System: Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)











[inv_44/2022]

**Comment by mcarare** [comment]
@softvision-raul-bucata , Yes the issue still exists on the release version, should be fixed on the next release.
