### ISSUE TITLE
Trackers are not blocked on https://senglehardt.com/test/trackingprotection/test_pages.html

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7821]
## Steps to reproduce
1. Install the latest Beta 106.0b5 build.
2. Go to https://senglehardt.com/test/trackingprotection/test_pages/tracking_protection.html.
3. Observe if the trackers are being blocked by ETP.

### Expected behavior
The social, ads, and analytics trackers are being blocked by default.

### Actual behavior
Trackers aren't blocked on this page.
**This issue occurs intermittent**. If several pages are opened/closed, then the page from step 2 is reopened, the trackers are blocked. Force closing the app, doesn't fix the issue.
However, the ETP panel displays the number of trackers being blocked:

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), Google Pixel (Android 10),  Oppo Reno 6 (Android 12)
* Focus version: Beta 106.0b5, Beta 106.0b1
* NOT reproducible on Focus Nightly 107.0a1 from 10/7
* Logcat: [logcat.txt](https://github.com/mozilla-mobile/focus-android/files/9731760/logcat.txt)
* Screenshots:

![Untitled](https://user-images.githubusercontent.com/40694158/194501204-69a7199c-90ac-49f4-9601-4ccb084d3665.png)

**Comment by sv-ohorvath** [comment]
Also see https://github.com/mozilla-mobile/fenix/issues/7907

**Comment by lobontiumira** [comment]
Reproducible on RC 106.1.0 build with Oppo Reno 6 (Android 12), and Lenovo Tablet M10 (Android 10).

**Comment by AaronMT** [comment]
https://github.com/mozilla-mobile/fenix/issues/7907#issuecomment-1276663560

**Comment by mcarare** [comment]
Issue tracked [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1794130).
