### ISSUE TITLE
Incorrect render after deleting history in picture-in-picture mode

### ISSUE THREAD

**Issue by Ceiphos** [mozilla-mobile/focus-android#7827]
## Steps to reproduce

- Open a video in picture-in-picture
- Delete history via the notification
- Immediately press the Home Button to prevent Focus from opening
- Start Focus

### Expected behavior
Focus renders correctly
### Actual behavior
Incorrect rendering of Focus (Rendered in the size of the picture-in-picture mode). See Screenshot.
### Additional Information
The behavior is persistent when switching Focus to background and opening again
The behavior is non-persistent when closing Focus via the Overview-screen and opening again
The incorrectly rendered Focus is responsive and working normal
As you have to immediately press the Home Button I can reproduce this in about half of the cases. In the other case Focus opens the default page normally after pressing delete history 
### Device information

* Android device: Google Pixel 4a Android 13
* Focus version: 105.2.0 (Build #362762015 105.0.2-20221003135607)
![Screenshot_20221008-100401](https://user-images.githubusercontent.com/63545612/194698727-8e007869-634e-40e8-86c3-0faf3a832023.png)

**Comment by lobontiumira** [comment]
I was able to reproduce briefly this issue on the latest RC build 105.2.0, and on Focus Nightly 107.0a1 with Oppo Reno 6 (Android 12). After re-opening Focus, the picture-in-picture mode was displayed briefly on the top-left corner of the app. 
Please see the slow motion short video below:


https://user-images.githubusercontent.com/40694158/194809618-243662eb-bee6-49af-8d48-2b4ff19327a8.mp4

I was not able to reproduce it on Google Pixel (Android 10) device.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802606

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
Does this bug happen in Fenix on the Oppo Reno 6? Or only in Focus?
