### ISSUE TITLE
"Browsing history cleared" not displayed on Focus debug

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7837]
## Steps to reproduce
1. Open a web site
2. Tap the trash bin icon from the nav bar

## Alternative steps to reproduce
1. Open a web site
2. Swipe and open the system taskbar
3. Tap "Erase and Open" button from the notification

### Expected behavior
Tapping the trash bin icon or the "Erase and Open"button from the notification should display the "Browsing history cleared" snackbar

### Actual behavior
The "Browsing history cleared" snackbar is never displayed

### Device information

* Android device: 
- * Google Pixel 2 (Android 9, x86)
- Google Pixel 3a (Android 11)

* Focus version: latest Main

### Notes
✅ Works properly on latest Nightly

**Comment by iorgamgabriel** [comment]
The snackbar with "Browsing history cleared" should not appear when the widget pop up appears, but in all other instances (when the widget pop up does not appear) the snackbar should indeed show.

**Comment by lobontiumira** [comment]
Verified as fixed on Focus debug build with Google Pixel (Android 10), and an emulator Google Pixel 5 (Android 13, x86-64):

![Screenshot_3](https://user-images.githubusercontent.com/40694158/195290838-f77bedb8-4ac3-41e1-8ee3-6baaa79900db.jpg)

**Comment by AndiAJ** [comment]
Also verified as fixed with #7851
