### ISSUE TITLE
Urls with trailing whitespace should load url, not search

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#784]
When entering a url, whitespace should be trimmed and the resulting string should be either loaded as a url (if it's a url) or searched for (if it's a search term), the way it is on the other browsers.

STR:
Enter url with a trailing space.

Expected:
Url is loaded.

Actual:
Url is searched for on search engine, leading to search results page, not url.

**Comment by ekager** [comment]
I added a leading/trailing space trim before it checks whether the string is a url. Am I oversimplifying?

**Comment by liuche** [comment]
Yep! That's the right fix.

**Comment by ekager** [comment]
Okay! Added trimming in isUrl and normalizeUrl methods in UrlUtils.

**Comment by liuche** [comment]
Closed by #789 .
