### ISSUE TITLE
Target Android 13 (SDK 33)

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#7840]
Latest SDK apps can target is 33: https://developer.android.com/about/versions/13

See also https://github.com/mozilla-mobile/focus-android/issues/7400.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802577

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
