### ISSUE TITLE
Focus is missing URL bar when loading first page

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#785]
I see this regularly on my older GS5 when I load the first page:
![screenshot_2017-06-15-13-41-15](https://user-images.githubusercontent.com/759372/27200947-9bb47a8e-51d0-11e7-808f-be688781d6de.png)

It shortly (5 seconds max?) transitions to show the URL bar and the web view. It's ugly but still functional. I don't see this on faster devices.

**Comment by pocmo** [comment]
Result of triage?

This is likely the result of disabling "clip children" on the view to allow the loading indicator to draw outside the parent view.

**Comment by mcomella** [comment]
> Result of triage?

iirc, we deemed it was not very important and prioritized work with the v1.1 tag.

**Comment by pocmo** [comment]
Re-flagging for triage: This is annoying me and I would like to move it into 2.x. Let's discuss in the triage meeting. :)

**Comment by mcomella** [comment]
In `browser_fragment.xml`, it looks like IWebView is drawing over the background view initially and it's only at some point that the size changes and it no longer draws over the background. I verified this by:
* Visibility = gone in the webView
* Drawing the background view after the ResizeableKeyboardLayout (which contains the webView)
* Setting the background color of the `id/appbar`, which draws after the webView

Looking for a fix...

**Comment by mcomella** [comment]
I didn't have enough time to complete this. @pocmo any ideas we can squeeze in before code freeze?

It looks like the `ResizeableKeyboardLayout`, a `CoordinatorLayout` is the one who resizes its children. I was going to look at the source to see how it does that because otherwise it's black magic that I can't figure out.

**Comment by pocmo** [comment]
I might have made it worse in the past: I've set clipChildren=false in the layout for some of the containers because the progress bar is drawing 1dp over the web content (marginBottom=-1dp). I can't remember seeing those problems before that. I guess the toolbar appearing a split second later isn't a problem as long as the progress bar isn't visible before that. Maybe you can find a way to draw the ProgressBar on top of the content without all the clipChildren=false? Or is there another way to let the ProgressBar appear *with* the Toolbar only?

**Comment by mcomella** [comment]
The reason the toolbar is appearing separately from the progress bar is that they're not actually drawn together. The layout is:
```xml
<BackgroundView>
<ResizeableKeyboardLayout>
  <WebView>
  <AppBarLayout>
    <FrameLayout>
      <ProgressBar>
```

This means the relevant draw order (bottom to top) is:
1. Background
1. Web View
1. Progress bar

And since the web view draws after the background, it initially draws over it, before it gets resized.

If we set the background color in AppBarLayout, all would be fine. However, the reason the background color is done in the `BackgroundView` is because it needs to draw under the system status bar and since it's a gradient, it's non-trivial to start the gradient in `BackgroundView` and continue it in `AppBarLayout`.

Unfortunately, I think clipChildren is unrelated here.

**Comment by pocmo** [comment]
> Unfortunately, I think clipChildren is unrelated here.

Without clipChildren the progress bar does not appear before the toolbar and it looks at least smoother.

**Comment by mcomella** [comment]
> Without clipChildren the progress bar does not appear before the toolbar and it looks at least smoother.

Ah, I didn't notice this behavior.

My PR didn't work (https://github.com/mozilla-mobile/focus-android/pull/917#issuecomment-315013719) and this isn't going to make code freeze so I won't actively be working on this anymore – unassigning.

**Comment by ekager** [comment]
How is this bug impacted by the now restructured UI? (#832)

**Comment by pocmo** [comment]
This part is untouched and I can still see the issue in the last Beta builds :(
