### ISSUE TITLE
Overlapped onboarding CFRs show up sometimes

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#7850]
STR:
1. Clear app data.
2. Dismiss onboarding.
3. Navigate to huffpost.com
4. Scroll down the page with a finger dragged across the screen.
5. Observe that sometimes the CFRs are overlapped. 

<img width="421" alt="Screen Shot 2022-10-11 at 7 46 51 PM" src="https://user-images.githubusercontent.com/1370580/195219201-0bfbf24d-dd04-46a5-a357-6d046b0933e5.png">

**Comment by lobontiumira** [comment]
Maybe this fixed issue helps #6524.

**Comment by jonalmeida** [comment]
I can't remember if I tested this on release or nightly so it might be fixed by the linked bug above. Happy to close this for now as a duplicate until I can confirm.
