### ISSUE TITLE
[Android 13] Focus 107.0a1 Crash Report [@ libhwui.so@0x12a051 ]

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7853]
## Steps to reproduce
I don't have exact STR. I was browsing through a few pages with media files, like https://googlechrome.github.io/samples/muted-autoplay/, and https://walterebert.com/playground/video/hls/.

### Expected behavior
Focus is running smoothly, without crashing.

### Actual behavior
Focus crashed.

### Device information
* Android device: Google Pixel 5 (emulator x86_64, Android 13)
* Focus version: Focus Nightly 107.0a1 from 10/12

**Crash reports:** 
* https://crash-stats.mozilla.org/report/index/c37ce094-33fa-437b-b745-9dffd0221012#tab-details
* https://crash-stats.mozilla.org/report/index/9cccb949-9e40-4370-add9-a3b060221012#tab-details

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802589

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
