### ISSUE TITLE
The colors of the icons from the status bar are not in contrast with the status bar background color

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/focus-android#7860]
## Steps to reproduce
1. From Gmail open a link on a custom tab or open a custom tab from Focus itself.
2. The icons from status bar are not visible for light theme and for dark theme are not in contrast .

### Expected behavior
The colors of the icons from the status bar should be in contrast with the status bar background color.

### Actual behavior
The icons from status bar are not visible for light theme and for dark theme are not in contrast .
### Device information

* Android device: Pixel 3XL android version 12
* Focus version: 106

<img src="https://user-images.githubusercontent.com/8118371/195804822-e76b53b5-92de-4f66-86a4-16703effbe05.png" width="300" height="600" /> 
<img src="https://user-images.githubusercontent.com/8118371/195804835-f7f0db3f-ef12-47a5-9d5a-1a1a2e9f7e69.png" width="300" height="600" />

**Comment by jonalmeida** [comment]
This was fixed indirectly by @mcarare  in Fenix by upgrading AndroidX core dependency from the looks of it.

**Comment by iorgamgabriel** [comment]
https://user-images.githubusercontent.com/8118371/196122239-9a4f6310-1cc9-4359-b8b1-72f1bdfabaca.mp4

I can reproduce this bug on the latest version in Focus and in Fenix .

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 108.0a1 from 10/21 with Samsung Galaxy Note 8 (Android 9), and Oppo Find X3 Lite (Android 11).
