### ISSUE TITLE
Stealth Mode Screenshot

### ISSUE THREAD

**Issue by umertanvir** [mozilla-mobile/focus-android#787]
Unable to take screenshot(s)  in stealth mode . Error message "Could not  take screenshot storage maybe in use"

**Comment by mcomella** [comment]
If Stealth Mode is enabled, the user will be unable to take screenshots – we set Android's secure flag which disables screenshots and hides the app's content in the recent app switcher.

That being said, the error appears to vary depending on device:
* GS5: "Unable to capture screenshot. Prevented by security policy."
* N5: doesn't provide any feedback the screenshot could not be taken (besides not taking the screenshot)

I presume your error message is specific to the device and is just confusing things. :\ However, from an engineering perspective, this is working as expected.

@antlam Do you think we could improve the UX of not being able to take screenshots in some way or should this issue be closed?

**Comment by mcomella** [comment]
See also #718.

**Comment by umertanvir** [comment]
Got it my mistake should be closed. Thanks
