### ISSUE TITLE
Add AD_ID Permission to AndroidManifest.xml for Android 13

### ISSUE THREAD

**Issue by ohall-m** [mozilla-mobile/focus-android#7874]
For Android 13, we need to update the AD_ID Permission.

🚧 **NOTE: Need to coordinate before landing change.**

More info: 
* [Info on Google Play and Advertising ID](https://support.google.com/googleplay/android-developer/answer/6048248?hl=en)
* JIRA Issue [FNXV2-21091](https://mozilla-hub.atlassian.net/browse/FNXV2-21091)
* Bugzilla Issue [1791114](https://bugzilla.mozilla.org/show_bug.cgi?id=1791114)

**Comment by ohall-m** [comment]
Focus Nightly now has the correct flag set in GPS that corresponds to this permission change.

**Comment by mcarare** [comment]
This does not need QA.
