### ISSUE TITLE
Zoom out broken in portrait mode for short pages.

### ISSUE THREAD

**Issue by seanp0** [mozilla-mobile/focus-android#7877]
## Steps to reproduce
For a web page that is less than the height of the screen,  In portrait mode, zoom in, then zoom out.

Here is a simple example that this shows this happening:

```
<!DOCTYPE html><html lang="en-GB"><head><meta charset="utf-8">
    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1" >
    <style>
     main {
         background:#abcdef;
         height:50vh;
         padding:1em;
     }
     #toggle_height:checked ~ main{
         height:110vh;
     }
    </style>
    <title>Simplest zoom fail example</title>
</head><body>
    <input id="toggle_height" type="checkbox"><label for="toggle_height"> check for tall page</label>
    <main>
        <p>In portrait mode, Zoom in, then zoom out.</p>
        <p>If body is shorter than screen height, it doesn't zoom out all the way - bug.</p>
        <p>If body is taller than screen height (toggle checkbox), it does zoom out correctly.</p>
    </main>
</body></html>
```

### Expected behavior
It should zoom out all the way, back to how it was when the page loaded.

### Actual behavior
It doesn't zoom out all the way.  Page remains wider than the screen and can be scrolled sideways.

This just happens in portrait mode.  Seems ok in landscape mode.
Doesn't happen if page content is taller that screen height.

### Device information

* Android device: Fairphone3, Android 11 (8901.4.A.0016.6)
* Focus version: 106.0, buildID 20221010

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802603

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
