### ISSUE TITLE
Sign in with google appears even in private browsing mode

### ISSUE THREAD

**Issue by genericuser256** [mozilla-mobile/focus-android#7879]
## Steps to reproduce
1. Visit a site with "One Tap Support" enabled, eg. twitter.com
2. Sign in with Google banner appears blocking ~1/3 the screen

### Expected behavior
1. This banner doesn't appear 
2. The relevant JS code is not loaded (if possible)

### Actual behavior
1. The banner appears

### Device information
Google Pixel 6 Pro

* Android device: 13
* Focus version: 105.2.0

**Comment by genericuser256** [comment]
Note: 
This seems to be related to this rollout by google on the 12th of Oct.
https://developers.google.com/identity/gsi/web/guides/itp#opt_in_before_oct_12_2022

Other users seeing similar issue:
https://old.reddit.com/r/firefox/comments/y3xetn/google_popup_never_seen_before/
https://old.reddit.com/r/firefox/comments/y677xp/firefox_focus_use_google_account_to_sign_in_pop/

**Comment by mcarare** [comment]
@genericuser256 Having the "Block other content trackers" option enabled does not show the sign-in banner for me.

**Comment by cpeterso** [comment]
> @genericuser256 Having the "Block other content trackers" option enabled does not show the sign-in banner for me.

Since "Sign in with Google" isn't a tracker (though it is an annoyance) and the "Block other content trackers" option does block it, I'm closing this bug as "won't fix".
