### ISSUE TITLE
Back button does not work at answers.microsoft.com 

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#7888]
## Preconditions
Clean profile

## Steps to reproduce
1. Navigate to: https://answers.microsoft.com/en-us/msoffice/forum/all/account-locked-for-weeks-no-reasonnotice-and-no/04bc4b41-a70d-4b5a-b494-7488379b1e7c
2. Accept the "Cookie" Policy.
3. Tap on the back button of the device.
4. Observe the result.

### Expected behavior
The browser navigates to the main page of the browser.

### Actual behavior
The browser is stuck on the answers.microsoft.com page.

### Device information

* Android device: 
Operating System: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
Operating System: Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)
* Focus version:  Firefox Focus Release 106.1.0 (362840108-🦎106.0-221010181815🦎)/ Firefox Focus Nightly 108.0a1 (362911719-🦎108.0a1-20221018094831🦎)

1. Reproducible regardless of the status of ETP.
2. Not reproducible using the latest build of Firefox Nightly in Normal Browsing Mode and in Private Browsing Mode.
3. Reproducible on both Release and Nightly Version of Firefox Focus.
4. ScreenRecording attached:

![back button focus](https://user-images.githubusercontent.com/75027050/196894946-31fca67a-3776-4127-99ba-5ddadf4aabff.gif)

**Comment by Mugurell** [comment]
Can reproduce the issue on both Fenix and Desktop on the first time accessing that link.
Seems like there is an intermediate login page to return to when pressing back and that is redirecting to the page we wanted.
Moving to Bugzilla for more investigation.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796561

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
