### ISSUE TITLE
Rebrand "Reader View" as "Focus mode"

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#7898]
### Why/User Benefit/User Problem
Since https://github.com/mozilla-mobile/focus-android/issues/802 was filed (and closed as stale), the capabilities of Focus has changed. We are focusing on privacy, but more subtly, we are focusing on quick/easy access too.

Reader View in Fenix and Desktop acts as a way to consume articles. In Focus, the incentive can be to have a focus or clear (klar) view of the web.

It blocks intrusive advertising, but that's a harder sell to make since it's a side-effect.

### What / Requirements

Add Reader View to Focus and rebrand it as "Focus mode" or something of that sort that shows up the toolbar.

Enable the feature in Custom Tabs too.

Prompt the user if a page is "readerable" to enable focus mode.

### Acceptance Criteria (how do I know when I’m done?)
When the feature is enabled in Focus and onboarding is added for users to know and how to use it.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802600

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
