### ISSUE TITLE
Renew telemetry expiring <= 109

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/focus-android#7905]

**Comment by lobontiumira** [comment]
Verified [here](https://dictionary.telemetry.mozilla.org/apps/focus_android) that the expiration date for the following metrics is set to "**Never expire**":
- back_button_pressed,
- startup_type,
- mozilla_products,
- autocomplete.domain_added,
- autocomplete.domain_removed,
- autocomplete.favorite_sites_setting_changed,
- autocomplete.list_order_changed,
- autocomplete.top_sites_setting_changed,
- app_opened.browse_intent,
- app_opened.text_selection_intent,
- app_opened.share_intent,
- add_to_home_screen.dialog_displayed,
- add_to_home_screen.add_button_tapped,
- add_to_home_screen.cancel_button_tapped,
- set_default_browser.from_app_settings,
- set_default_browser.from_os_settings,
- set_default_browser.learn_more_opened,
- tab_count.app_backgrounded,
- tab_count.erase_button_tapped,
- tab_count.new_tab_opened,
- tab_count.session_button_tapped,
- tab_count.session_list_closed,
- tab_count.session_list_closed,
- tab_count.session_list_item_tapped,
- custom_tabs_toolbar.action_button_tapped,
- custom_tabs_toolbar.browser_menu_action,
- custom_tabs_toolbar.close_tab_tapped,
- custom_tabs_toolbar.navigation_toolbar_action,
- search_widget.new_tab_button,
- search_bar.entered_url,
- search_bar.performed_search,
- search_bar.add_engine_tapped,
- search_engines.learn_more_tapped,
- search_engines.open_remove_screen,
- search_engines.open_settings,
- search_engines.remove_engines,
- search_engines.restore_default_engines,
- search_engines.save_engine_tapped,
- search_engines.set_default,
- search_suggestions.autocomplete_arrow_tapped,
- search_suggestions.search_tapped,
- search_suggestions.suggestion_tapped,
- search_widget.add_to_home_screen_button,
- search_widget.promote_dialog_shown,
- search_widget.voice_button,
- search_widget.widget_was_added,
- browser.install_source,
- browser.report_site_issue_counter,
- browser.search.ad_clicks,
- browser.search.in_content,
- browser.search.search_count,
- browser.search.with_ads,
- browser.total_uri_count,
- browser_menu.browser_menu_action,
- browser_menu.navigation_toolbar_action,
- show_search_suggestions.changed_from_settings,
- show_search_suggestions.disabled_from_panel,
- show_search_suggestions.enabled_from_panel,
- downloads.download_canceled,
- downloads.download_completed,
- downloads.download_failed,
- downloads.download_paused,
- downloads.download_started,
- downloads.open_button_tapped,
- open_with.installed_firefox,
- open_with.list_displayed,
- open_with.list_item_tapped,
- app_opened.from_icons,
- app_opened.from_launcher_site_shortcut,
- notification.open_button_tapped,
- notifications.notification_tapped,
- advanced_settings.open_links_setting_changed,
- advanced_settings.remote_debug_setting_changed,
- notifications.erase_open_button_tapped,
- app_shortcuts.erase_open_button_tapped,
- app_shortcuts.just_erase_button_tapped,
- tracking_protection_exceptions.allow_list_opened,
- crash_reporter.close_report,
- crash_reporter.displayed,
- tracking_protection.has_ever_changed_etp,
- tracking_protection_exceptions.allow_list_cleared,
- tracking_protection_exceptions.selected_items_removed,
- context_menu.item_tapped,
- onboarding.default_browser_button,
- onboarding.finish_button_tapped,
- onboarding.next_button_tapped,
- onboarding.page_displayed,
- onboarding.skip_button_tapped,
- privacy_settings.block_cookies_changed,
- privacy_settings.safe_browsing_setting_changed,
- privacy_settings.stealth_setting_changed,
- privacy_settings.telemetry_setting_changed,
- privacy_settings.unlock_setting_changed,
- pro_tips.link_in_tip_clicked,
- pro_tips.tip_displayed.
