### ISSUE TITLE
Playstore logo needs drop shadow?

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#791]
The logo in the Play Store probably needs a drop shadow, as the white blends in with the Play Store's background color

![screenshot_20170620-132841](https://user-images.githubusercontent.com/122897/27340673-13f25a12-55a9-11e7-9f06-8b1f0498fc95.png)

**Comment by antlam** [comment]
The white knock-out fox also gives us problems on the listing page, where the backdrop is also white.

**Comment by bbinto** [comment]
Is this something for branding/Sean Martell to fix?

**Comment by pocmo** [comment]
Yeah, our app icons have a drop-shadow for this reason too. (And I think Sean added them).

**Comment by antlam** [comment]
![focus_logo-512](https://user-images.githubusercontent.com/1994820/27665689-7ee06dde-5c23-11e7-9897-5c72e2f5ff69.png)

Does this work? Sean is on leave ATM, so I tried to copy the layer styles he used for the app icon.

It's a 512 x 512 png

**Comment by pocmo** [comment]
@antlam It's uploaded and you can check it out in the PlayStore now. It's definitely much better.

**Comment by antlam** [comment]
Just checked it out, it's better but not perfect. Inherently, this icon just causes a lot of these problems.

Since I have the asset with Sean's styles, I'll see if there's more shadow-ing I can do here.

**Comment by antlam** [comment]
![focus_logo-512-b](https://user-images.githubusercontent.com/1994820/28033317-b2d6b330-6562-11e7-8ae4-ef8c24c78186.png)

This requires a fair amount of finessing but I tried adding more shadowz. I just hesitate to keep making incremental changes to our public-facing assets. 

![focus_logo-512-b](https://user-images.githubusercontent.com/1994820/28033384-f0dd7d44-6562-11e7-8206-66fe9c34521f.png)

**Comment by pocmo** [comment]
I don't think people notice us tweaking the asset of the play store listing. Even if they do it doesn't seem like something that upsets them? :)

**Comment by antlam** [comment]
@pocmo can we try that new asset then? ^

**Comment by pocmo** [comment]
@antlam The new logo is now on Google Play!
