### ISSUE TITLE
Upgrade Jetpack Compose to 1.3.0

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#7915]
A new stable version for Jetpack Compose has been released: [Release notes](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.3.0).

**Comment by mcarare** [comment]
For QA: Check that the following screens/components work as before:

 - onboarding
 - about page
 - biometric auth
 - language list
 - search widget promote dialog
 - site permissions
 - rename top site dialog
 

Thank you!

**Comment by lobontiumira** [comment]
Verified on a local Focus Nightly 108.0a1 build with Google Pixel (Android 10), and Oppo Find X3 Lite (Android 11).
All the elements/pages/features described in the comment above are working correctly.
