### ISSUE TITLE
Adjustments to first run copy

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#792]
The onboarding cards have some strange sentences. I'd replace "a touch to" with "a tap on"; "link to the Web" with "open Web pages"; and replace the sentence in the last card completely with "When a site seems broken, try turning off blocking from the overflow menu."

**Comment by bbinto** [comment]
some more suggestions from UR/copy will come

**Comment by antlam** [comment]
@bbinto does this seem like something we should triage ?

**Comment by bbinto** [comment]
closing as this aligns with Google's way of describing gestures
