### ISSUE TITLE
33ms regression to cold main first frame (10/1)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#7925]
![image](https://user-images.githubusercontent.com/759372/198135194-ecafa6b0-288c-4713-8cae-65f543972f9e.png)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802598

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
