### ISSUE TITLE
Cannot use special characters when editing "add to home screen" shortcut title

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#7930]
See  the discussion [here](https://github.com/mozilla-mobile/focus-android/pull/7919#issuecomment-1293199209). 

https://user-images.githubusercontent.com/13914967/198238294-e3a21a7f-c509-448b-a413-d8b5c4071c14.mp4

Currently, the edit text does not allow autocompletion of special characters (eg: Japanese, Chinese) while using a QWERTY keyboard. 

We should follow the behavior from Fenix.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 109.0a1 from 11/16 with Lenovo tablet M10 (Android 10):

![Screenshot_1](https://user-images.githubusercontent.com/40694158/202216812-83f286a3-d26e-45f6-a239-f9bd2ea97d46.jpg)
