### ISSUE TITLE
Custom tabs opened from the Google News app are not opened in Focus

### ISSUE THREAD

**Issue by marco-c** [mozilla-mobile/focus-android#794]

**Comment by pocmo** [comment]
Unfortunately that's Google News hard-coding Chrome. :(

**Comment by marco-c** [comment]
Shame, I thought they were using normal custom tabs. Time to uninstall Google News ;)

**Comment by pocmo** [comment]
What's interesting: If you get push notifications from Google News then they open the actual default browser. :)
