### ISSUE TITLE
Prevent unintentionally closing tabs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#7945]
As a followup to https://github.com/mozilla-mobile/focus-android/discussions/7938 I think there are at least two ways the app can avoid unintentionally closing tabs.
- a warning when the trash button is tapped - may be too intrusive having this show all the time
- an undo button in the snackbar which appears after the tabs have been closed, similar to that of Fenix:

| Focus | Fenix |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11428869/198952110-608fbe70-dd28-4237-8291-749a0fc2e1e4.png" width=400 /> | <img src="https://user-images.githubusercontent.com/11428869/198951966-861f353a-3248-4eb4-9774-2c6d54ade164.png" width=400 /> |

cc @jeffreygee

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802243

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
