### ISSUE TITLE
How to build this without blobs?

### ISSUE THREAD

**Issue by p-p-q** [mozilla-mobile/focus-android#795]
Browsing this repo I saw several binary files. Is it possible for me to build Focus without any mysterious binaries, using only real source code of the app and all the used libraries or other third party stuff (if any)? If it is possible, will it be functionally identical to the blob-based version distributed here?

**Comment by mcomella** [comment]
Hey @p-p-q – our core developer is on PTO and I'm not familiar with the binary blobs – which ones specifically do you see?

**Comment by p-p-q** [comment]
Hey, I mean these two files for example: https://github.com/mozilla-mobile/focus-android/tree/master/app/libs

**Comment by pocmo** [comment]
- geckoview-latest.aar is a build of geckoview from mozilla-central. It's only needed for build variants that use Gecko. You can build it yourself by following the guide to build Fennec and then run the gradle task for building geckoview (something like assembleGeckoViewWithBinaries):
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_for_Android_build

- telemetry.aar is a build of our telemetry library from this repository:
https://github.com/mozilla-mobile/telemetry-android

Eventually this should be loaded from a "maven" repository.

**Comment by mcomella** [comment]
> Eventually this should be loaded from a "maven" repository.

fwiw, I got this working* for FirefoxData if you want me to take care of it, or want any tips! :)

\* jcenter only but I think it's easy to get it on Maven Central too.
