### ISSUE TITLE
[A11y] The "No"/"Yes" options from the "Add to Home screen" prompt are read as "Cancel

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7966]
## Steps to reproduce
1. Install Focus, and activate the Talkback.
2. Open a page, go to the three-dot meu, and select the "Add to Home screen" option.
3. Using TB gestures, swipe until you reach the "No" or "Yes" options.

### Expected behavior
The reader announces the "No" or "Yes" options.
 
### Actual behavior
The reader announces the "No" or "Yes" options as "Cancel" or "Add".

### Device information
* Android device: Oppo Find X3 Lite (Android 11)
* Focus version: Nightly 108.0a1 from 11/2, Beta 107.0b5

![Screenshot_1](https://user-images.githubusercontent.com/40694158/199499312-361e1937-fa9b-45f3-9c51-b81140f4ff2b.jpg)

**Comment by mcarare** [comment]
IMO the content description is the correct text that should also be used for the visible text. Fenix also uses cancel/ add instead of no/yes.

cc: @jeffreygee for confirmation of the change.

**Comment by jeffreygee** [comment]
@ewachowiak - any thoughts on this? Unfamiliar with these patterns, but shouldn't the text match the VO or is that okay here?

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 108.0a1 from 11/10 with Oppo Reno 6 (Android 12), and Google Pixel 9Android 10).
The "No"/"Yes" options from the Add to homescreen prompt are now replaced by "Cancel"/"Add", and read accordingly by the Voice Assistant.

![Screenshot_2022-11-10-10-59-22-49_11753d9bf2a67eec1c984b8ccb4d0671](https://user-images.githubusercontent.com/40694158/201053093-da06eec4-8429-439b-9192-2d485f36ff11.jpg)

**Comment by lobontiumira** [comment]
Verified also on the latest Focus Beta build 108.0a1 with Sony Xperia Z5 Premium (Android 7.1.1), and Lenovo tablet M10 (Android 10).
