### ISSUE TITLE
[A11y] With talkback enabled, Focus doesn't apply the newly set search engine

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7967]
## Steps to reproduce
1. Install Focus, and activate the Talkback.
2. Open the three-dot meu, and go to Settings - Search - Search engine.
3. Using TB gestures, select a different search engine.
4. Exit the "Choose search engine" page, return to the "Search" page, and observe the default search engine displayed.

### Expected behavior
The search engine set up at step 3 is displayed, and is working accordingly.

### Actual behavior
The search engine is Google (in this case) again, even though I've selected a different one.
Searching for a term, the search engine used is still Google.
Please observe the short video below.

### Device information
* Android device: Oppo Find X3 Lite (Android 11)
* Focus version: Focus Nightly 108.0a1 from 11/2, Beta 107.0b5
* Not reproducible when the talkback is disabled.
* Reproducible also with Wikipedia, DuckDuckGo, it does not have to be a newly added search engine
* Logcat: [logcat.txt](https://github.com/mozilla-mobile/focus-android/files/9920999/logcat.txt)

https://user-images.githubusercontent.com/40694158/199507155-0ff18561-bb5b-4cc9-82ac-94fe579e971f.mp4

**Comment by delia-pop** [comment]
Verified as fixed on the latest Focus Nightly 108.0a1 from 11/04 with Google Pixel 6 (Android 13). The selected search engine with Talkback gestures remains properly selected after returning to the Search screen. The search is also correctly made with the selected search engine.

https://user-images.githubusercontent.com/89388888/200003125-570e0eb0-2a73-4236-b724-367f9e232149.mp4
