### ISSUE TITLE
Keyboard flash when going from url input screen back to Focus main screen

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#797]
When hitting back to go from the URLInputFragment back to the HomeFragment, there's a flash of the keyboard.

STR:
On the url input screen, tap back to hide the keyboard
Tap back to go back to the main screen ("Browse. Erase. Repeat.")

Expected:
See the main screen

Actual:
Keyboard flashes up briefly after returning to main screen

**Comment by pocmo** [comment]
Can you leave a comment when removing the "needs triage" label and not adding a new label? What was the result of triage?

**Comment by bbinto** [comment]
@liuche to confirm if it's still an issue

**Comment by liuche** [comment]
Not an issue anymore.
