### ISSUE TITLE
Search engine plugins are retrieved from a soon-to-be-defunct mozilla-aurora url.

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/focus-android#798]
Search engine plugins are currently retrieved from https://github.com/mozilla-mobile/focus-android/blob/1f3b550574e66352dc295d7e934db9fc88c66824/tools/search/scrape_plugins.py#L19 (and L10n versions a few lines below that) by pulling directly from hg.mozilla.org's mozilla-aurora repository.

That's unfortunate for two reasons:
1. Mercurial's not really meant to be queried like that for raw files. There's got to be a better way (something backed by a CDN?) to pull in this information.
2. The mozilla-aurora repository (along with Mozilla Aurora as a release product) has been discontinued. I don't know how long those files will continue to be available at those URLs.

At the very least, this should be changed to fetch those files from some other not-discontinued repository.

**Comment by pocmo** [comment]
This needs to be filed against the iOS version too (If it's not already).

**Comment by Sdaswani** [comment]
@ekager can we either i) fix this or ii) close it? It's been hanging around forever.

**Comment by ekager** [comment]
This is no longer a file in the project, closing
