### ISSUE TITLE
Avoid using XML entities in localized strings

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#7980]
Filing this in reference to the issue raised [in this PR](https://github.com/mozilla-l10n/android-l10n/pull/517): Focus appears hardcoded once strings get into the l10n repo.
Possible explanation [here](https://github.com/mozilla-l10n/android-l10n/pull/517#issuecomment-1301715040), and in following comment.
CC @ewachowiak @jeffreygee and @rtestard

**Comment by flodolo** [comment]
If you can't use a variable in this context, would it be an option to expose the string in the main XML file with a variable, and generate these XML files as a build step (replacing the variable with the entity)?

The entity won't show up for localization, and you can't have the name hardcoded either, because one language can only pick one, and Klar vs Focus depends on where your Store account is geolocated, not locale. The only alternative is having a string without the product name.

**Comment by Delphine** [comment]
(Hope I'm not adding more confusion, but as I understand it, in the case of [the initial PR](https://github.com/mozilla-l10n/android-l10n/pull/517), having a string that doesn't call out the product name is not an option either, because the string in the initial PR shows up in 3rd party apps).
This general issue remains true, though

**Comment by Delphine** [comment]
@ewachowiak @jeffreygee and @rtestard: I don't know how to move forwards, and landing strings for Focus has been blocked for 23 days at this point.
I want to highlight that in the case of [this related issue](https://github.com/mozilla-l10n/android-l10n/pull/517), this becomes also a legal concern, as "Focus" will appear as hardcoded, although it should legally be called "Klar" in some countries (this is clear by looking at what comes out of [the automation in the PR](https://github.com/mozilla-l10n/android-l10n/pull/517/files#diff-d79fb4d15cc5e3d94c75355597bf9bbbf8102355fb17c7eca37f77d24a08fad8R123))
So this is not only a stability concern.

**Comment by flodolo** [comment]
Another thought: would it be possible to not expose `<!DOCTYPE resources [ <!ENTITY app_name_entity "Focus"> ]>` in the same file where the string referencing it is? I would expect that to carry over the XML entity to the l10n repository.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802596

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
