### ISSUE TITLE
Firefox Focus does not show on Play Store search results

### ISSUE THREAD

**Issue by reinhart1010** [mozilla-mobile/focus-android#799]
When searched in Google Play Store, the Firefox Focus app does not show in the search results.
**Edit**: the bug seems to appear as well in compatible devices. Title and description changed.
![screenshot_2017-06-21-16-18-26](https://user-images.githubusercontent.com/17312341/27376833-7fbfdb08-569d-11e7-8cb9-16ebb9943d17.png)
This screenshot is taken from a compatible Android 6.0 device.

**Comment by Sdaswani** [comment]
Try now. :) Google is just slow ;) .
