### ISSUE TITLE
Focus Analytics status

### ISSUE THREAD

**Issue by comzeradd** [mozilla-mobile/focus-android#801]
If I'm not mistaken, one of the trackers Focus blocks is Google Analytics. What's the status on Focus' own analytics integration. It feels weird to block it for all the websites but [include it](https://github.com/mozilla-mobile/focus-android/blob/973778cbcbeff8cd241f9d3104247fcc446d2e7a/app/build.gradle#L153) in the browser itself to track usage.

**Comment by pocmo** [comment]
Focus does not use Google Analytics.

However we compile Focus against the Analytics SDK. It's a dependency for Adjust (to get the unique advertisment id) - which we use to ..

> [...] determine the origin of Firefox Focus installs by answering the question, “Did this user on this device install Firefox Focus in response to a specific advertising campaign performed by Mozilla?”.

More about this here:
https://github.com/mozilla-mobile/focus/wiki/Install-Tracking-in-Firefox-Focus-with-the-Adjust-SDK
