### ISSUE TITLE
Provide reader-friendly version of visited webpage (reader mode)

### ISSUE THREAD

**Issue by albalitz** [mozilla-mobile/focus-android#802]
_Added by @bbinto_

**Why/User Benefit**
- Helps to render some content better that is not made for phone screen size
- Improves reading experience for long-form content (e.g. news articles)
- Asked by many users and considered a must for a simple, focused browser

**What**
- Option to switch to a more reader friendly version of a web page
- Options to set background/font size and color of the text

**Acceptance Criteria (how do I know when I’m done?)**
- User turn on/off reader-friendly mode 
- Reader-friendly mode extracts all non-text content from page

----
Hi focus team,
since I use focus mostly for reading, a reader view like the one in the desktop version of Firefox and in Firefox for Android would be a great addition here.

**Comment by orschiro** [comment]
This would be awesome!

I have this below RSS feedburner page that just doesn't render well on mobile. 

It doesn't fit the screen.

Having a reader mode would help here. 

Page: http://feeds2.feedburner.com/stadt-bremerhaven/dqXM

**Comment by a-wigand** [comment]
Any update?

**Comment by waleedsamy** [comment]
+1

**Comment by n8willis** [comment]
This whole "stale bot" model is so offensive that I can barely put it into words.
