### ISSUE TITLE
Allow opening local HTML files (content scheme)

### ISSUE THREAD

**Issue by mkaply** [mozilla-mobile/focus-android#803]
Clicking on HTML files that are sent as attachments don't offer Focus as a choice because we don't support 
                `<data android:scheme="content" />`
for html files.

I tried adding it in the manifest, but they still don't open. We should support this so opening HTML files works in Focus.

**Comment by Sdaswani** [comment]
Thanks @mkaply is this a personal itch or something that would be good for partners? That will help us prioritize :) .

**Comment by mkaply** [comment]
Well, I need to get it working in Fennec and I was hoping if you figured it out, it would help us get it working there :).

I think it's definitely something we should look at, since other web browsers support loading content URLs.
