### ISSUE TITLE
Focus Nightly is used in Klar on search shortcut

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#8031]
We've used the wrong app name here and we should fix this as an intermediate solution until the [ENTITY bug](https://github.com/mozilla-mobile/focus-android/issues/7980) is resolved.

https://github.com/mozilla-mobile/focus-android/blob/72236f32a88fd3b256e940c4e3c276547832c61a/app/src/klar/res/values/app.xml#L5

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Klar Nightly 109.0a1 from 11/17:

![Screenshot_2](https://user-images.githubusercontent.com/40694158/202386083-040c762a-77ec-476d-91bd-9a9ddd3a7c15.jpg)
