### ISSUE TITLE
Paused audio starts without the users action on the "Play" option

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#8039]
## Steps to reproduce
1. Load play.christmasfm.com, and start the audio content.
2. Pause the audio from the media notification.
3. Observe the media notification for 5-10 seconds.

### Expected behavior
Nothing is happening, the audio stream is still paused, the notification doesn't modify it's state.

### Actual behavior
The audio is started without the user actioning on the "Play" option from the media notification.

### Device information
* Android device: Lenovo tablet M10 (Android 10)
* Focus version: Nightly 109.0a1 from 11/16, Beta 108.0b1
* Fenix version: Nightly 109.0a1 from 11/16 in both private, and normal mode
* Reproducible also on Chrome
* NOT reproducible with soundcloud.com.
* Logcat: [logcat.txt](https://github.com/mozilla-mobile/focus-android/files/10020635/logcat.txt)
* Video:

https://user-images.githubusercontent.com/40694158/202154402-bae737d1-33b0-40c7-8082-4c970943873d.mp4

**Comment by mcarare** [comment]
From what I am seeing on testing this, the website enters a buffering state when media is paused, and after a while, it restarts the service. You can actually see the previous notification disappearing before a new one with playing media shows up.

The same behavior can be even observed on desktop Firefox and Chrome.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802595

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
