### ISSUE TITLE
blob URLs made with createObjectURL() are blocked

### ISSUE THREAD

**Issue by mikehenrty** [mozilla-mobile/focus-android#804]
@liuche showed me the relevant code, and it looks like blob urls are being blocked here:

https://github.com/mozilla-mobile/focus-android/blob/4dce158c292679e28f0833200dd718f7045dc74b/app/src/webkit/java/org/mozilla/focus/webkit/TrackingProtectionWebViewClient.java#L81

not sure if this is by design or not, but Focus for iOS does not seem to block these.

**Comment by kdavis-mozilla** [comment]
@mcomella Do you have any insight on this problem?

**Comment by mcomella** [comment]
Unfortunately, I don't know any more than what's in this bug – @pocmo (note: on PTO), do you have any ideas?

**Comment by pocmo** [comment]
@mikehenrty Is this preventing you from using a specific site or implementing a web feature? What's the background?

**Comment by mikehenrty** [comment]
We are using this API to implement a web feature for voice.mozilla.org.

Full story: our website downloads audio clips with some important metadata in response headers. This API, createObjectURL, allows us to pass the audio data from an XMLHttpRequest object to an audio element src, which means we still have access to the response headers. If we were instead to just set the audio src (without using XMLHTTPRequest), we don't have access to reponse headers.There are workarounds for this (multiple requests for one), but this method is extremely convenient for this use case.

**Comment by pocmo** [comment]
In the triage meeting we decided to move this to the backlog and not to the v2 list.
