### ISSUE TITLE
Enable New Onboarding Flow by default

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#8042]
Per discussion with @rtestard, and aligning plans for the Onboarding experiment, the request is to enable the new Onboarding flow by default.
We will need to uplift this change to v108 and v107.

**Comment by lobontiumira** [comment]
Verified the new onboarding is displayed in the latest Focus Nightly build 109.0a1 from 11/18. 
Testing devices: Google Pixel 6 (Android 13), and Lenovo tablet M10 (Android 10)

![Untitled](https://user-images.githubusercontent.com/40694158/202735507-c4ab10f9-3252-4e03-936b-aeb7e35be131.png)

**Comment by lobontiumira** [comment]
Verified that the new onboarding is displayed also on the latest Focus Beta 108.0b3.
