### ISSUE TITLE
Support microphone use by web pages (formerly: getUserMedia not supported?)

### ISSUE THREAD

**Issue by mikehenrty** [mozilla-mobile/focus-android#805]
When I go to https://test.webrtc.org, the site says:

"Failed to access your computer's camera and microphone (NotAllowedError)"

..and no prompt is displayed to me. It looks like access to this is blocked by defaults. Is this a security feature or bug?

**Comment by mcomella** [comment]
We [don't currently support the `RECORD_AUDIO` permission](https://github.com/mozilla-mobile/focus-android/blob/09784e886254ae6a398b7156930ebd7efeb2dd91/app/src/main/AndroidManifest.xml#L9) so presumably we don't handle the microphone prompt in the WebView.

**Comment by kdavis-mozilla** [comment]
@mcomella just so we are all on the same page:
- Without a change to Focus on Android it is impossible to record
- This inability to record is a feature not bug in Focus

**Comment by mcomella** [comment]
> Without a change to Focus on Android it is impossible to record

afaict.

> This inability to record is a feature not bug in Focus

I don't know if this is intentional (and thus a feature) – I think @bbinto would know more.

fwiw, we have [an item to add voice search to the url bar on our roadmap](https://trello.com/c/7jmRZTO8/36-add-voice-input) but that doesn't necessarily mean we would support voice recording from web content.

**Comment by liuche** [comment]
This would require an extra Android permission for microphone usage, which we will have to consider in the bigger picture of Focus as a "privacy browser". There is a backlog feature request for voice input, so I will include this in that discussion.

**Comment by liuche** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add voice input](https://trello.com/c/7jmRZTO8/36-add-voice-input)

**Comment by mikehenrty** [comment]
One other thing to mention, the getUserMedia API is available, but always returns a message saying user denied microphone access. This makes it hard for sites who want to help users enable microphone access because my site can't tell the difference between the user explicitly denying access, and the API not being available at all. Probably better would be to not expose the API, so sites can use feature detection.

**Comment by pocmo** [comment]
This not only requires a permission but also additional UI to handle the media requests, clear and show permissions etc.

**Comment by bbinto** [comment]
@ekager, do we have a GeckoView API for this?
