### ISSUE TITLE
Protection renforcée contre le pistage dans Firefox pour Android | Assistance de Firefox pour Androidhttps://support.mozilla.org/fr/kb/protection-renforcee-pistage-firefox-android#w_protection-totale-contre-les-cookies

### ISSUE THREAD

**Issue by Karembit** [mozilla-mobile/focus-android#8066]
https://support.mozilla.org/fr/kb/protection-renforcee-pistage-firefox-android#w_protection-totale-contre-les-cookies

**Comment by cpeterso** [comment]
Is there a problem with Focus or that support article? That support article is about Firefox, but this GitHub issue tracker is about Focus.
