### ISSUE TITLE
Font family and status bar in Play Store thumbnails

### ISSUE THREAD

**Issue by aminalhazwani** [mozilla-mobile/focus-android#807]
I noticed that the typography in the thumbnails is set in San Francisco, Roboto may be more suited :slightly_smiling_face: Also on Firefox Klar the typography is set in San Francisco and Fira Sans. 

Another small detail are the different status bars from one screen to another, we could always use the same default status bar.

**Comment by Sdaswani** [comment]
This is not code-related - just how we look on the Play Store.

**Comment by brampitoyo** [comment]
Good eye, @aminalhazwani!

@Sdaswani Do we know who designed the Play Store label? If I’ve got the original graphic files, I’d be happy to switch the font family.

**Comment by pocmo** [comment]
This doesn't need to track a version I guess? We should just ping mhan via mail.

**Comment by brampitoyo** [comment]
I’ve sent mhan an email. This should be quick to resolve, I think.

**Comment by brampitoyo** [comment]
I’ve updated the Play Store thumbnails (fixed a few other typography issues in other locales along the way) and sent them off to mhan.

Note the fixed status bar, too.

Old:

<img src="https://lh3.googleusercontent.com/_jr0MvNuu9kRvfbrXf629DNhiq6L9C1Tjj8GWWKugBIqyA0IjdUCpcin10IsPqD-nlRQ=h900" height="320">

New:

<img src="https://user-images.githubusercontent.com/51007/27670134-ab1130ec-5cd6-11e7-95d5-42553df5534a.png" height="320">

**Comment by pocmo** [comment]
@brampitoyo Did you hear back from Mike? I wonder if this issue can be closed.

**Comment by brampitoyo** [comment]
I heard back from Mike. He said that he wasn’t able to open my uploaded Sketch files, so I exported them into screenshots and uploaded them in their appropriate folders.

We’re just waiting for Mike to update the Play Store listing with this new screenshot – which shouldn’t take long – and then we can close this issue. Thanks for being patient!

**Comment by brampitoyo** [comment]
The typography of our Google Play Store listing has been updated across all locales. Mike had pushed it live. This issue is now fixed!
