### ISSUE TITLE
Longpress on link menu: Open link with app

### ISSUE THREAD

**Issue by albalitz** [mozilla-mobile/focus-android#815]
An "open with ... app" longpress menu item for some links like for example YouTube, Playstore, or Wikipedia links would be great. Similar to the one in the Firefox for Android app.
That way one wouldn't have to open the initial website in another browser to then be able to open a specific link in a specific app.

**Comment by Sdaswani** [comment]
@ekager can you take a look at this PR?

**Comment by ekager** [comment]
@colintheshots has already started reviewing
