### ISSUE TITLE
Reposition Floating Action Button so it aligns with the rest of the OS

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#817]
On Android’s default Calendar and Messaging app (and a few other third party apps like Twitter), the FAB is located 16dp away from the right and bottom side of the useable screen area.

![messaging-calendar-twitter 2x](https://user-images.githubusercontent.com/51007/27526170-d027f7b0-5a8f-11e7-9b5e-101eae4666a1.png)

On the other hand, our positioning is 24dp away from the edges.

![focus 2x](https://user-images.githubusercontent.com/51007/27526177-d6d86b76-5a8f-11e7-8c29-bbf78213f7c5.png)

It would be good to align with other Android apps here.

**Comment by veyndan** [comment]
As a side note, the reason why all these apps locate their FABs 16dp away from the corner is due to it being specified in the [Material design guidelines](https://material.io/guidelines/components/buttons-floating-action-button.html).

**Comment by veyndan** [comment]
From the link above:

> The floating action button should be placed 16dp minimum from the edge on mobile and 24dp minimum on tablet/desktop.

So the FAB spacing is correct for tablets with the current implementation, but is wrong for phones. The answer **isn't** to just change the margin from 24dp to 16dp as the margin would now be correct for phones but incorrect for tablets.

**Comment by brampitoyo** [comment]
Thanks @veyndan. I should’ve prefixed my comment with the actual quote from the design guidelines:

> The floating action button should be placed 16dp minimum from the edge on mobile and 24dp minimum on tablet/desktop.

@ekager would it be possible to vary the spacing by device?

**Comment by veyndan** [comment]
I'm not sure whether [`compatPadding`](https://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html#setUseCompatPadding(boolean)) is the way to go. It sets 16dp on my phone, but I haven't had a chance to try it out on a tablet yet.

Otherwise using the standard [resource configuration qualifiers](https://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources) are the way to go.

**Comment by ekager** [comment]
@brampitoyo yes! Didn't realize originally that it would change based on the screen size, sorry for the misunderstanding! I added the new dimens based on screen size.

**Comment by pocmo** [comment]
I just merged your PR! :)
