### ISSUE TITLE
CSS workaround for visited links not working on google.com & reddit.com

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#828]

**Comment by mcomella** [comment]
This also happens on reddit: go to reddit, click a post on the home page, hit trash can, go to reddit, post is unexpectedly highlighted.

**Comment by pocmo** [comment]
I can't reproduce this on google.com anymore. I created a test page and can see that we are still removing the "visited" CSS styling in all builds - including the release build.

**Comment by rtanglao** [comment]
i can reproduce on google.ca: see

1. https://www.flickr.com/photos/roland/35991445365/in/datetaken/ 
1. https://www.flickr.com/photos/roland/35991445385/in/datetaken/ (after clearing history this shows the bug))

**Comment by pocmo** [comment]
For everyone who can reproduce this. Please try this:

* Go to http://fennec.pocmo.de/test/visited/
* Click on the test link
* Erase your session
* Go to http://fennec.pocmo.de/test/visited/ again
* Is the link red (has been visited before) or blue (Not visited)?

**Comment by mcomella** [comment]
> Is the link red (has been visited before) or blue (Not visited)?

The link is blue (not visited).

**Comment by ioana-chiorean** [comment]
confirming too - blue :large_blue_circle:

**Comment by pocmo** [comment]
This means the workaround in general is working on your devices. Can you post device model and Android version too?
And you can consistently reproduce this on google.com and reddit.com?

**Comment by mcomella** [comment]
For reddit.com, I can reproduce on:
* GS5, Andy 6.0.1
* N5, 6.0.1

**Comment by pocmo** [comment]
After disabling (and removing updates from) the System WebView APK I can see this issue on a test device now too. Maybe I can see why our workaround is not working now.

**Comment by pocmo** [comment]
` chromium  I  [INFO:CONSOLE(1)] "Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode", source:  (1)`

Using "var" instead of "let" fixes the workaround on those devices. :)

**Comment by npark-mozilla** [comment]
@pocmo I think I still see the issue on reddit.com. (FocusWebKitDebug build on Nexus 5X simulator with API 23/25) I click a reddit thread, then clear history and revisit to see the visited links marked. Same thing if I close the app via recent apps list, and restart the app.  Did I understand the bug correctly?
 
![screen shot 2017-08-28 at 12 07 04 pm](https://user-images.githubusercontent.com/6930774/29782146-6e52cf02-8be9-11e7-844f-1993b632d1dc.png)
