### ISSUE TITLE
Put Focus/Klar APK on mozilla.org

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#830]
Let's not forget our other target audience who 
a) doen't want to use the Google Play Store
b) can't use the Google Play Store

I want to make sure we can still get DAUs etc from these versions.

Sebastian, would you mind checking with people if/how we can get this done for upcoming Focus Android update. Would be nice if it's aligned with the update.

Thanks

**Comment by pocmo** [comment]
For now I was uploading the APKs (RCs and release) to the GitHub release page that also tags the specific state of the code that this release was build from:
https://github.com/mozilla-mobile/focus-android/releases

Those APKs are the same that we uploaded to Google Play.

**Comment by bbinto** [comment]
I think that's a start, and we could ask Joni to put this link on the SUMO page, i.e. "Can Focus can be downloaded outside of the Google Playstore", and then see what's needed to get it on the mozilla.org site.

**Comment by bbinto** [comment]
Is there a way to see how many have downloaded the APK file from the Github release link?

**Comment by sarimak** [comment]
Since today Firefox Klar is available via F-Droid repo. I can't find its package page on f-droid.org yet, maybe becomes available after a nightly refresh of the website => the APK will be available at least there. I installed it and briefly tested, works on both LineageOS 7.1.2 GT-I9300 and stock 5.1.1 SM-P600.

**Comment by bbinto** [comment]
@pocmo I'd still like to see what effort / steps are involved to get it on mozilla.org.

Could you please point me to the steps I (or with your help) have to take.

Thanks

**Comment by bbinto** [comment]
@pocmo any news :) ?

**Comment by pocmo** [comment]
Note yet. There are two things:
* I'm talking to release engineering about how we can automate the releases. As part of that I want to see how we can upload this *somewhere*.
* Next week I want to talk to Sylvestre about automating some of the release management parts. I hope he can show me how we get this (or link the uploaded APK) on mozilla.org. :)

**Comment by pocmo** [comment]
From the meeting today: For Fennec there's a taskcluster job that takes the signed builds and uploads it into an S3 bucket. 

The builds will show up here:
https://archive.mozilla.org/pub/mobile/

archive.mozilla.org is composed of multiple buckets. We could add another bucket to it in which we'd upload our builds. We won't be able to use the taskcluster job as we are building on buddybuild and plan to do that going further. We probably could get buddybuild to upload the builds - I'll have to test that.

**Comment by bbinto** [comment]
friendly ping... @pocmo

**Comment by pocmo** [comment]
Asking for a separate S3 bucket (for archive.mozilla.org) here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1402804

**Comment by pocmo** [comment]
Blocked -> Waiting for the S3 bucket to be set up.

**Comment by pocmo** [comment]
The APKs are now available on archive.mozilla.org:
https://archive.mozilla.org/pub/android/focus/

**Comment by pocmo** [comment]
@bbinto Isn't the last missing piece a link from https://www.mozilla.org/en-US/firefox/focus/ to https://archive.mozilla.org/pub/android/focus/latest/ ?

**Comment by bbinto** [comment]
Submitted work intake [request](https://docs.google.com/document/d/1li_q0WHEETgNvqAGYLaucWo9CzuLxZRe2QOdHYT-ygs/edit#) for web team to take care of the last remaining piece

**Comment by J0WI** [comment]
_bump_

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802031

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
