### ISSUE TITLE
Let users know that they can change the default search engine

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#831]
**User Story**

> I have difficulties finding a way to change their default search engine

**Feature/Suggestion**

* Add an onboarding slide explaining this.
* OR: Add an (one-time?) in-context hint when performing a search

**Tasks**

* [ ] Finalize/Mock UX
* [ ] Implement onboarding slide / hint UI

**Comment by brampitoyo** [comment]
I think that adding an in-context hint is a more natural approach to explain.

@antlam What’s your thought of adding a dismissable hint that looks like this?

![search - mdpi 2x](https://user-images.githubusercontent.com/51007/28002679-00e967d2-6583-11e7-8eb9-2d834f9732f4.png)

**Comment by antlam** [comment]
I have an idea here! will post mocks tomorrow.

**Comment by antlam** [comment]
Update: Meeting set up with Legal to discuss options. Will update here later.

**Comment by bbinto** [comment]
@antlam, I think we agreed, for now, to include this into our first run, is that correct? If so, @mheubusch should include that into #835, correct?

**Comment by antlam** [comment]
Yep, I'll close this and merge this into issue #835

**Comment by antlam** [comment]
@bbinto this issue is closed... and will be merged into #835 , should it be in Ready for QA?

**Comment by npark-mozilla** [comment]
@bbinto as antlam mentioned... this isn't completed right?  if so I'll move it to 'Done'

**Comment by antlam** [comment]
@npark-mozilla you're right! its not complete yet. Sorry for the confusion

**Comment by npark-mozilla** [comment]
Np, i was thinking what should I do with it since putting it to 'Done' will confuse me (or others) in the future, so I removed this from the project. #835 is in the project anyways so it should be okay... I think?
