### ISSUE TITLE
Restructure UI to make searching / typing an URL faster

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#832]
**User Story**

> I want to start a search as quickly and easy as I can

**Task**

- [x]  UX design / mocks
- [x] Implement new UI flow

**Comment by antlam** [comment]
Is this the Home View UI we looked at briefly in SF?

<img width="381" alt="screen shot 2017-06-27 at 9 10 06 am" src="https://user-images.githubusercontent.com/1994820/27779602-f6c539f8-5f78-11e7-9e8f-f41de69a5d04.png">

**WIP**

**Comment by brampitoyo** [comment]
+1 to starting Focus with the URL bar already highlighted and ready to accept text input!

To make things even faster, maybe any URL you currently have in your clipboard is automatically pasted in this URL bar, so all you need to do is tap “Go”.

<img width="382" alt="screen shot 2017-07-04 at 4 08 15 pm" src="https://user-images.githubusercontent.com/51007/27815828-14e735f2-60d3-11e7-83e8-61ef1039c088.png">

Three things to consider here:

1. Would it increase our .apk size by a lot?
2. Does it seem creepy that Focus can “see” into the URL that you’ve copied?
3. Is it a separate feature from what this issue covers?

**Comment by antlam** [comment]
@brampitoyo I like the idea of having the URL that's on the clipboard here. We could even reuse the clipboard icon we had before in our previous paste & go ideas.

But I think we should split this out into a separate issue, then triage - because scope creep. :)

**Comment by antlam** [comment]
![screen shot 2017-07-14 at 3 46 49 pm](https://user-images.githubusercontent.com/1994820/28233430-aad11954-68ab-11e7-9ba5-d08f238fad38.png)

cc @pocmo 

**updated mock**

**Comment by bbinto** [comment]
Positive feedback: https://play.google.com/store/apps/details?id=org.mozilla.klar&reviewId=Z3A6QU9xcFRPR1RwVDBKdW80VDU1TGtQTzlxeDRrOVdKMHc5aXZ0Z25NTlJzWGkxcDlVc2REMG5ycEZaZEhtRjdEWFF1QWNQSVBiYWRfSmtmanlhbmN3NUdz
