### ISSUE TITLE
Settings polish: Explain blocking settings better

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#834]
**User Story**

> I don't understand what the settings mean and why I should care

**Feature/Suggestion**

> Find better ways to communicate what each option is for and why someone would want to use them.

**Comment by pocmo** [comment]
@antlam @brampitoyo Do you have any ideas what we could do here?

**Comment by antlam** [comment]
leaving this one for @brampitoyo :)

**Comment by brampitoyo** [comment]
First stab at explaining what each option means. Each explanation will appear as a small text caption underneath the option.

**Block ad trackers**
Sites that monitor ads you see when you visit a web page, in order to show you ads tailored to your habits

**Block analytics trackers**
Sites that collect, analyse and measure your activities (like tapping and scrolling) when you visit a web page

**Block social trackers**
Social media sites that know when you’re visiting another web page and can show sharing buttons there

I haven’t found a good explainer for **Block content trackers**, but we already have a caveat there.

@antlam and @mheubusch, do you have any feedback about my copy?

**Comment by antlam** [comment]
From a UX perspective, I think we could explore other ways other than copy changes as well. The issue here might just be that reading about these things inside this Settings page in the application is just _one_ of the ways users educate themselves.

**Comment by antlam** [comment]
Thinking about this some more, I think a second description line would be a nice place to start explaining a bit more. 

This also resonates a lot with our Focus for iOS research findings explicitly. So, we should be able to add a second line for both Firefox Focuses! 👍 

@brampitoyo specifically, I think we need to be aware of the line length in this case, there's very little space in this UI and we need to make sure it feels less like a chore to read it and more like "pro-tips" :)

**Comment by antlam** [comment]
![screen shot 2017-07-19 at 2 46 59 pm](https://user-images.githubusercontent.com/1994820/28402105-e15c4928-6cd2-11e7-9da2-1a9e57c94673.png)

As with iOS over on issue https://github.com/mozilla-mobile/focus-ios/issues/146, I've updated Android Settings UI here with room for descriptions, and included the Photon color palette too!

**Comment by pocmo** [comment]
Added "blocked" label -> This is one of the next things we pick up from the list, but we need to finalize the strings first.

**Comment by bbinto** [comment]
@pocmo this will most likely not make it into Aqua as per @mheubusch, the remaining strings for Aqua will come today

**Comment by bbinto** [comment]
We've reached out to Disconnect to confirm the way we describe their block lists. Casey from Disconnect will get back to us on Monday. If we can't get it approved by Monday, we could move this into the next release (worst case, due to L10N deadline) /cc @Sdaswani

**Comment by antlam** [comment]
@bbinto we spoke about this in triage just now but I just wanted to clarify something. If it's wrong, let us know!

Here's what the next steps sounds like:
1. Get in touch with Disconnect about how we should label the Ad, Analytics, and Social trackers we show in our Settings
2. Work with @mheubusch on strings for our Settings
3. Localize new strings with L10N community and Delphine
4. Add to UX mock, Add in product, Hand-off to Eng

Which means this most likely won't make Burgundy :)

**Comment by antlam** [comment]
OK just to clarify, we talked to Michelle just now. And it seems like we are already on step 3.

**Comment by pocmo** [comment]
There's a missing link somewhere. No strings have been added to this issue - and therefore I haven't been able to land any - so none should be in the L10N project for this yet.

**Comment by antlam** [comment]
Update: got string suggestions back but working with @mheubusch on finalizing them for use in Focus

**Comment by antlam** [comment]
Update: 

We have an issue to do this for iOS too. But we're also talking about maybe just describing the whole group now instead of each individual toggle. Followed by a link to learn more.

**Comment by antlam** [comment]
We've started to look at this in iOS here (with some strings in the subtitle section of each switch. https://github.com/mozilla-mobile/focus-ios/issues/272

**Comment by antlam** [comment]
@bbinto as you also pointed out, string freeze is today! since we merged the Milestones, so I'm moving this to Granite* as there's already a lot in Folly, including the UX-heavy "What's New?" feature!

**Comment by antlam** [comment]
From Brian for iOS Focus:

> New strings:
Block ad trackers
Some ads track site visits, even if you don’t click the ads

Block analytics trackers
Used to collect, analyze and measure activities like tapping and scrolling

Block social trackers
Embedded on sites to track your visits and to display functionality like share buttons

Block other content trackers
Enabling may cause some pages to behave unexpectedly

Remove "Describe the group above"; Tif is creating separate issue for it.

**Comment by BrianNJones** [comment]
@antlam these can be updated to strings-approved

**Comment by liuche** [comment]
Added strings in #1557.
