### ISSUE TITLE
Add a "Block Images while on Data" Setting

### ISSUE THREAD

**Issue by ke-d** [mozilla-mobile/focus-android#836]
I just tried Focus and I am really liking the performance and the idea behind it. One feature that is blocking me from using it as a default browser is a setting where if the phone is using mobile data, it blocks images. 

FYI, this setting is in regular Firefox on Android as well. Under Settings ->Advanced ->Data Saver -> Show Images.

This would help those who are on a limited data plan but still want images on wifi.

**Comment by pocmo** [comment]
#188
