### ISSUE TITLE
Use full app name in launcher

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#847]
![launcher-icon-name](https://user-images.githubusercontent.com/89638/27788655-be2bcf6e-5fe9-11e7-9b3a-61d43f280e5b.png)

Left: Current version
Right: Proposed version

**Comment by pocmo** [comment]
@antlam @brampitoyo What do you think about this?

**Comment by antlam** [comment]
I'm fine with either. But I have two questions:

1. Where is this request coming from/ what is the issue with the current label?
2. How did we arrive at the current label?
3. Will this (full name "Firefox Focus" show up completely in all situations? or will it be shortened (Firefo F...)?

**Comment by pocmo** [comment]
> Where is this request coming from/ what is the issue with the current label?

I first saw this from a user being confused it being named "Firefox Focus" everywhere but not in the launcher. In addition to that it's consistent with our other apps: Firefox Beta, Firefox Nightly.

> How did we arrive at the current label?

That was probably my decision in the early prototyping phase. Maybe I was concerned about the length or I just named it "Focus" back then...

> Will this (full name "Firefox Focus" show up completely in all situations? or will it be shortened (Firefo F...)?

So far it looks like it will show up completely everywhere.

**Comment by antlam** [comment]
Thanks for the update! 

I don't know if this is really such a big deal. Especially if we look into the future, this could get kind of long too. Firefox Focus Beta, Firefox Focus Nightly.

@mheubusch @bbinto do you guys have thoughts here? I think this is more than a UX decision. 🐙

**Comment by pocmo** [comment]
> I don't know if this is really such a big deal. Especially if we look into the future, this could get kind of long too. Firefox Focus Beta, Firefox Focus Nightly. Then we will definitely only see "Firefox Fo..." or something :P

There are workarounds for our Beta builds... But overall I do not care so much about them: Let's use the best name ("Focus" or "Firefox Focus") for our actual user base - and not make this depend on our internal builds.

**Comment by bbinto** [comment]
As per marketing, if we can make it fit for the release version, let's go with Firefox Focus.

**Comment by antlam** [comment]
'Make it fit' as in not have ellipsis? I think it might in the App Drawer, but @pocmo will probably know for sure

**Comment by pocmo** [comment]
I tried this on various phones and all of them are able to show "Firefox Focus" on the home screen and inside the app drawer. 👍

**Comment by pocmo** [comment]
I landed the patch. Let's see if we hit any problems on other devices.
