### ISSUE TITLE
Adaptive launcher icons

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#848]
https://developer.android.com/preview/features/adaptive-icons.html

**Comment by pocmo** [comment]
That's something for our backlog and not v2.

@antlam What do you think about that? I would like to have Focus feel modern and support new platform features.

**Comment by antlam** [comment]
This is neat! but I'll need Sean's help since he created the icon asset.

**Comment by pocmo** [comment]
As soon as we build with support for the new SDK features Android will put our icon "on a plate" (on Android 8+) as long as we do not ship with an adaptive icon.

![focus_plate](https://user-images.githubusercontent.com/89638/28610706-82d18154-71e9-11e7-918b-614d1d6b5b88.png)

We should fix this in one of the next releases.

**Comment by antlam** [comment]
I'm going to employ the help of Shorlander here since he has the chops and has been in a lot of meetings around these things. He's been thinking about it _a lot_ ;)
