### ISSUE TITLE
Full screen mode does not work reliably with YouTube

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#855]
We implemented full screen mode in #586. It's working great with all video sites I tested except YouTube.

In the logs I see that we enter full screen mode and immediately get kicked out of it again. In the logs I see that WebView calls the "start full screen" callback and then immediately the "exit full screen callback". You even see that we are in full screen mode for a split second. In rare cases (I think when clicking the full screen button pretty fast after the video starts loading) it to my surprise works and we only get the "start full screen mode" callback. I tested with another WebView based app and could observe exactly the same problem. This issue does not exist when using Chrome directly.

It's not clear whether it's YouTube or WebView that is causing this.

**Comment by pocmo** [comment]
Related issue in the chromium bug tracker:
https://bugs.chromium.org/p/chromium/issues/detail?id=726558

Facebook has exactly the same problem when opening a YouTube URL in the in-app browser. :)

**Comment by mcomella** [comment]
Looking at ^, we could either wait for the Chromium fix & re-evaluate (note: primary person on Chromium skilled enough to do it is out-of-office until July 28th) or look for a work-around. Since it's not our fault, I'm going to look at other issues first and come back if I have time before the Wednesday code freeze.

Sebastian added some more details about our experiences with this issue [in the Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=726558#c16). Here's the repost (because I think it'd be useful for a workaround):

> We are seeing the same issue in Firefox Focus [1] which is based on WebView.
>
> Some additional information:
>
> * The callback for "exit full screen mode" (onHideCustomView) is called immediately after the "enter full screen mode" (onShowCustomView) [WebChromeClient]. Often you can see that the video is in full screen mode for a split second.
> 
> * This only happens on YouTube. Other sites with video content like vimeo.com or ted.com just work.
> 
> * In rare cases onHideCustomView() is not called immediately on YouTube and the video stays in full screen mode. However in this situation the video player button for leaving full screen mode does not work (as if it's not expected to actually be in full screen mode). 
> 
> * As this is only observed on YouTube I'm not sure if this is a WebView issue or maybe something the YouTube website does accidentally?
>
> * I do not see this issue when using Chrome directly.

**Comment by pocmo** [comment]
One thing I tried (just for testing) is to ignore the onHideCustomView() callback, hoping that the video would just stay in full screen mode. Unfortunately I ended up with a white screen. :)

**Comment by pocmo** [comment]
Also: In one of the last meetings we decided that we want to have a SUMO page for this - if we decide to publish with this bug.

**Comment by pocmo** [comment]
From the chromium bug tracker:
> The fix on Youtube side has been mailed here cl/167007227 and will go out next week. However, they suggested to add a way to explicitly detect PIP on our side . foolip@ is that something you can do? It will be nice to have.
> 
> I will go head and remove RBS from this issue since Youtube already did the necessary on their side.

**Comment by pocmo** [comment]
YouTube full screen mode now seems to work.

@npark-mozilla Can you confirm?

**Comment by npark-mozilla** [comment]
@pocmo yes it plays full screen fine on my Nexus 5. only small thing i notice is that during the orientation change the screen goes to lower left corner then expands, but I think that's the webview. I think we can close this issue then?

**Comment by pocmo** [comment]
@npark-mozilla Perfect. Thanks!

**Comment by redmatch-it** [comment]
I'm still facing the same issue... how did you solve that?

**Comment by pocmo** [comment]
@redmatch-it Can you file a new issue with some details?
