### ISSUE TITLE
Update block lists

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#856]
Firefox's tracking protection lists are going to be updated soon. We should follow and update our local copy too after they have merged the PR.

https://github.com/mozilla-services/shavar-prod-lists/pull/23
https://public.etherpad-mozilla.org/p/shavarlist23

**Comment by bbinto** [comment]
@pocmo & @antlam  can you please add t-shirt sizes?

**Comment by pocmo** [comment]
To use the latest blocklists we need to support the DNT headers first: #446

**Comment by antlam** [comment]
It doesn't sound like this needs UX, it will just be a list change in the background right?

**Comment by pocmo** [comment]
> It doesn't sound like this needs UX, it will just be a list change in the background right?

Yeah!

**Comment by bbinto** [comment]
@pocmo not sure if you are the right person to answer that but do you have any idea how big the differences between our list and the updated list are, i.e. +x% additional trackers added etc.?

Or maybe @fmarier knows?

**Comment by pocmo** [comment]
> To use the latest blocklists we need to support the DNT headers first: #446

Reason being: Disconnect removes trackers from the block list if they honor DoNotTrack. However as long as we do not send this header we would get tracked once they disappear from the list.

**Comment by pocmo** [comment]
This is a WebVIew-only issue. GeckoView comes with blocklists and we do not need to update them on our side. I think we can just close this if we intent to switch to GeckoView.

**Comment by bbinto** [comment]
\o/ - great news! Ok, let's close it
