### ISSUE TITLE
Improve/polish notification

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#864]
This is how our notification currently looks like (with actions from #826). It looks rather dull and monotonous.

![notification](https://user-images.githubusercontent.com/89638/27871354-b6f595e6-61a5-11e7-8f5b-0cc74ff073a9.png)

We could at least try to add a highlight color (see follow-up screenshots). Should we also update the wording?

We started with mimicking the Chrome incognito notification - but this one does not feel modern either.

**Comment by pocmo** [comment]
For comparison some other notifications from my device:

![screenshot_20170704-131415](https://user-images.githubusercontent.com/89638/27871543-3dd8da50-61a6-11e7-92ef-ce3e8c571527.png)

**Comment by pocmo** [comment]
Using the FAB color for the notification:

![focus-notification-color](https://user-images.githubusercontent.com/89638/27872099-ece63e88-61a7-11e7-9156-81004da54e5a.png)

**Comment by pocmo** [comment]
On Android O adding the launcher icon looks interesting too.

![with_launcher](https://user-images.githubusercontent.com/89638/27872491-40f924b2-61a9-11e7-9911-d7f0a835953f.png)

However it heavily depends on the system and Android version how the notification will actually look like (as long as we do not define a custom layout). On my Android 5.1 device the notification looks different and the color is used differently too.

**Comment by antlam** [comment]
looks good!
