### ISSUE TITLE
Toolbar gradient colors

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#87]
Currently (on iOS), we use this UI to visually differentiate when Focus is _on_ versus _not yet engaged_ .

When the user has finished loading a page successfully, use the full (brighter) gradient UI.

When the user is in "typing" mode, use the darker gradient. (on iOS, we also wanted to use this for error pages - but didn't get around to it).

**Color codes to be posted**

**Comment by antlam** [comment]
<img width="652" alt="screen shot 2017-02-17 at 9 15 30 am" src="https://cloud.githubusercontent.com/assets/1994820/23075527/ab4babc0-f4f1-11e6-8c1b-2a0c02c1b153.png">

Visual of the states

**Comment by pocmo** [comment]
@antlam Do you have the color codes?

**Comment by antlam** [comment]
Active state:
- 80%
 - Top left: #C43B31 
- Middle: #96368D
- Bottom right: #135EA4
 - On top of
- Background: #363B40

In-active state:
- 20%
 - Top left: #C43B31 
- Middle: #96368D
- Bottom right: #135EA4
 - On top of
- Background: #363B40

**Comment by pocmo** [comment]
Can you give me the combined colors (background + top layer)?

**Comment by antlam** [comment]
Active state:
- Top left: #9B3A4D 
- Middle: #82377D
- Bottom right: #3E4C8A

In-active state:
- Top left: #503B44 
- Middle: #493A50
- Bottom right: #383F53
