### ISSUE TITLE
Add notification action for 'Erase + Start from Home View'

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#870]
From @bbinto (and I'm paraphrasing obvs) 

> What if we had another notification action that allowed the user to 'Erase' their current browsing session **and** 'Open' Focus at the same time? Sometimes I want to just fire off a new search with Focus but I'm in another app.

**Comment by antlam** [comment]
@pocmo how hard would this be?

@mheubusch this is going to be a bit more complicated than 'Open'. Do you have thoughts on this?

**Comment by pocmo** [comment]
Stop. No new features in 1.1 (I removed the label and added the triage label).

I wonder if this could be something for a shortcut action?

Anyhow: I think that's doable. And after #832 this will be "just" switching to the app and erase. Immediately being able to type a new URL / search will be the default for all.

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve notification actions](https://trello.com/c/5vOsYjHR/58-improve-notification-actions)

**Comment by pocmo** [comment]
@antlam @bbermes Maybe this is also a good thing for adding as a shortcut?

**Comment by antlam** [comment]
Shortcuts from the Home screen? Would it be something like "Erase" and "Erase and start a new search"? that could work!... 🤔

**Comment by bbinto** [comment]
@pocmo yes, in addition to the existing shortcut (Erase), we could add the "Erase & start new search". However, would this still make sense though after we do #832?

**Comment by mheubusch** [comment]
@antlam what do you think of 
Firefox Focus
Erase history and open app
(although not sure how this will work on my Samsung - there is an "OPEN" that opens the app with the last site visited appearing in the browser)

**Comment by mheubusch** [comment]
![screenshot_2017-07-27-17-46-59](https://user-images.githubusercontent.com/20115914/28696328-8965f358-72fa-11e7-8287-19de2b104f05.png)

**Comment by pocmo** [comment]
I'll add the string to the repo (and export) today.

@antlam We also need to decide what icon we want to show in the notification on older devices. The firefox like for open - or the trash can? or something else?

**Comment by antlam** [comment]
@pocmo is it ok if we dont supply an icon?

**Comment by pocmo** [comment]
@antlam The API for adding an action to a notification requires supplying an icon. On my Z3C it works if I do not specifiy a valid icon resource id (see screenshot below). However it's not mentioned in the docs that this is supported. So this could be fragile. We would need to test on a variety of devices and (older) Android versions to be sure.

![notification_without_icon](https://user-images.githubusercontent.com/89638/28815940-541e7a74-76a3-11e7-8218-8d4c727eaf7e.png)

**Comment by antlam** [comment]
@pocmo can we use the material rubbish bin? the same one on the FAB

**Comment by pocmo** [comment]
@antlam I just noticed that it suddenly does not fit on the small Z3C (in portrait only) when adding the icon.

![erase_and_open_size](https://user-images.githubusercontent.com/89638/28838083-70ce7d44-76ef-11e7-8a58-b2ac7914b586.png)

**Comment by pocmo** [comment]
I merged the patch so that we can try it on multiple devices.

Regarding the problem mentioned above, we could:

* Live with it. Only small devices with an older version of Android (that shows the icon) are affected.
* Try to ship without showing an icon (but see concerns above)
* Not ship this feature and update the string in the next version (I am very concerned about the size of the string in other languages now.)
* Something else?

^-- @antlam @bbinto

**Comment by antlam** [comment]
I'm fine with this as is actually. I'm not too worried about it.

But something like "Reset" or "Restart" might work? I'll let @mheubusch make the call if she wants to change it.

**Comment by bbinto** [comment]
Definitely not a blocker for this release, and bullet one seems fine for me.

**Comment by pocmo** [comment]
Alright. I'll close this issue and we can file a new one for one of the upcoming releases if we decide to change something.
