### ISSUE TITLE
Developer Options / Advanced settings

### ISSUE THREAD

**Issue by phunkular** [mozilla-mobile/focus-android#871]
I find Firefox Focus to be really truly excellent thanks to it's very basic but strong premise: privacy and simplicity. I have gotten many people to try it and the results are usually positive except in every case everyone has that one feature that they're missing... for me it's having the keyboard appear as soon as you open the app.... for someone else it's bookmarks or firefox sync. 

So instead of suggesting that outright, I thought it would be bettter to suggest to implement an overall 'developer options' settings page where everyone's individual mods can be tested without affecting or detracting from the simplicity of the current UI. So rather than having to vet everyones little suggestions one by one, perhaps we could aim for a space where ideas can be tested freely without any consequence on the current UI... like about:config for Firefox. Something for everyone ;)

Thanks

**Comment by TPS** [comment]
[about:config](about:config) can be accessed since a while ago.
