### ISSUE TITLE
No way to view version/buildid in-app?

### ISSUE THREAD

**Issue by eleemoz** [mozilla-mobile/focus-android#882]
In Firefox, you can use about:support, about:buildconfig, and about:telemetry etc. to find out your buildid, or the source used to build your particular version. There doesn't appear to be a similar function in Focus. When testing new builds, and trying reproduce problems, it would be helpful to be able to verify what version of Focus is installed.

**Comment by mcomella** [comment]
This was added to the "About" page in #590, should be available in our Beta builds, and is expected to be released in v1.1.

The release Focus builds are all version 1.0 for your bug filing needs! :)

**Comment by pocmo** [comment]
In beta builds you can shake the device and press the "(i)" icon to see the build number etc.
