### ISSUE TITLE
Add Buddybuild build number to About page

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#884]
@eleemoz suggested we add Buddybuild build numbers to our Beta builds to help with reproducing & reporting bugs. If we don't ship Betas via Google Play soon (#600), I think this is a great idea!

Looking briefly, it looks like we can get the build number, even without the buddybuild SDK: http://docs.buddybuild.com/docs/displaying-build-number-in-an-android-app-without-sdk-integration

**Comment by pocmo** [comment]
In our buddybuild builds you can shake the device to send feedback. This feedback screen also includes the build number and other meta data.

**Comment by mcomella** [comment]
@eleemoz ^

**Comment by pocmo** [comment]
As mentioned above the Buddybuild number is already visible. However the buddybuild number is the same as the versionCode - and going forward with automated builds and alpha/beta channels I guess it still makes sense to show this number somewhere.

@antlam Do you have any preferences how this number should show up? Next to the version number somehow?

**Comment by antlam** [comment]
@pocmo Next to the version number in About makes sense to me.

For styling, can we just put it in brackets?

`1.2 (Buddybuild #9999)`

**Comment by pocmo** [comment]
@antlam Okay, but can we remove the "Buddybuild" part? I would like to show the build number regardless of whether this build came from buddybuild or not.

**Comment by antlam** [comment]
@pocmo How about this then? Just to be a bit more clear

`1.2 (Build #9999)`
