### ISSUE TITLE
Allow opening of shared URLs

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#889]
Currently Focus only handles Intents to **open** a specific URL. Additionally Focus could also handle Intents when an URL is **shared**. That's what Fennec does too (Shows up as "Add to Firefox").

I saw this SUMO request.
https://support.mozilla.org/en-US/questions/1167043

Technically the SHARE intent is not required to contain an URL. It could be just normal text. In this case we could trigger a search?

**Comment by antlam** [comment]
Or, could we trigger the _start_ of a search? that is, paste the text into the awesome bar with keyboard up so the user could easily edit?

**Comment by pocmo** [comment]
> Or, could we trigger the start of a search? that is, paste the text into the awesome bar with keyboard up so the user could easily edit?

That's a great idea and leaves the user in control.

**Comment by ekager** [comment]
So if the user already had a Focus session - would this just paste the text into the URL bar over their current session? But give them the option to continue away from their old session?

**Comment by antlam** [comment]
Good questions @ekager ! I can spend some time mocking this up later but basically here's the logic I'm thinking about:

- IF Text > paste text into URL bar, keyboard up/active, key cursor at the end of the string. But don't load the search results page (don't commit the search yet)

**Focus is "in session"**
- IF URL > reopen session, paste URL into URL bar, keyboard up/active, URL highlighted. But don't load the URL 

**Focus is not open**
- IF URL > open URL

This should allow users the control they need to 'back out' if this isn't what they expected, but still give them that convenience of having Focus as a Share intent handler. 

@pocmo thoughts?

**Comment by pocmo** [comment]
This introduces a lot of special case handling. Note that for normal "VIEW" intents we just load the website. Regardless of whether there's already a session or not. A quick solution would be to start with the *same* behavior and then test and tweak? (Although not immediately loading a VIEW intent would be super annoying. For SHARE I'm not sure. I would like to just use it for a while?)

**Comment by antlam** [comment]
Talked to @pocmo a bit just now. Revising and unifying the interaction for URLs. ^

**Comment by Gitoffthelawn** [comment]
Can this be done similar to Firefox?

**Comment by pocmo** [comment]
> Can this be done similar to Firefox?

What exactly do you mean? Firefox shows an overlay with "Bookmark", "Open in Firefox" and optionally other devices if Sync is setup. For Focus only "Open" makes sense right now?

**Comment by Gitoffthelawn** [comment]
When another app tries to open a page, Android presents a list of browsers in which the page can be opened.  Firefox is listed, but Focus is not.  I would like to see Focus included in that list.

**Comment by ioana-chiorean** [comment]
@Gitoffthelawn  It might be something on your side - I do get that option.

**Comment by Gitoffthelawn** [comment]
@ioana-chiorean What version of Android did you test?  I tested stock Nougat, and Focus does not appear as an option to load a URL from other apps.

**Comment by ioana-chiorean** [comment]
@Gitoffthelawn 
- Nexus 7 - Android 5.1.2 - appears
- Pixel - Android 7.1.2 - doesn't appear
- Nexus 6P - Android 8.0 - appears

<img src="https://user-images.githubusercontent.com/1391451/28212504-61390faa-68aa-11e7-9b96-927d445cad60.jpg" width="450" height="300" />

**Comment by Gitoffthelawn** [comment]
@ioana-chiorean Great testing!  And fantastic photo!

So it looks like the issue is Android version-dependent.   We should definitely get it working on Nougat.
