### ISSUE TITLE
Do something with "learn more" link in Preferences -> Telemetry

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#89]
We currently show "learn more" under the "Send anonymous usage data" preference. I'm guessing we'll either want to show something when pressing that and/or remove the "learn more" text.

**Comment by st3fan** [comment]
@ahunt on iOS this links to https://support.mozilla.org/1/mobile/3.0/iOS/en-US/usage-data - the 3.0 and iOS parts are the app version and platform. We use this function to generate these SUMO links:

https://github.com/mozilla-mobile/focus/blob/master/Blockzilla/SupportUtils.swift#L14

**Comment by ahunt** [comment]
On Android, tapping anywhere on the preference changes that preference. That makes me wonder if we should move "Learn more" into a separate compact item - we already do that for a "Learn More" link in Fennec's Advanced Preferences:
![learnmore_cropped](https://cloud.githubusercontent.com/assets/1546915/23624855/7b0bca62-02a7-11e7-8753-133318334602.png)

**Comment by ahunt** [comment]
@antlam 
Does this look like an acceptable option? (Ignore the icon for now, that's just a placeholder)
![learnmore_proto1](https://cloud.githubusercontent.com/assets/1546915/23704246/3e4dfdee-0404-11e7-8d86-6e8f14d9e4a9.png)

**Comment by antlam** [comment]
Talked to @ahunt on Slack a bit. 

Looks like we can just underline the "Learn more" text and keep it where it was before but have it link out to a webpage if the user presses on that link versus just flipping the toggle.

**Comment by ahunt** [comment]
Screenshots of this in action:
![landed_learnmore](https://cloud.githubusercontent.com/assets/1546915/23849832/56c70744-07dd-11e7-8664-933d2ed28b91.png)

And what's shown when you click on that (I've scrolled down a little):
![landed_learnmore_content](https://cloud.githubusercontent.com/assets/1546915/23849856/6633228a-07dd-11e7-825c-61527f61d049.png)

**Comment by antlam** [comment]
I think the title isn't necessary. 

But then it makes me think... why aren't we just using a Custom Tab? I briefly talked about this with @pocmo so mostly leaving a comment here in that regard so i dont forget :)

**Comment by ahunt** [comment]
I'm adding custom tabs usage for all info screens in #199, therefore closing this bug for now!
