### ISSUE TITLE
Show search term instead of search query URL

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#891]
In Fennec's awesomebar, if the user searched for something like "swiss chard recipes", they would get to a results page, with a long search query URL. 

Once the user presses the URL, the search term "swiss chard receipes" is displayed instead of the long search query URL. This helps with re-searching and correcting typos. 

@bbinto do we want something similar here? cc @pocmo

**Comment by bbinto** [comment]
That's kinda nice and goes nicely with our get to your (repeated) search sooner.

>v1.1.
