### ISSUE TITLE
Consider adding startup time test

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#892]
I personally find one of the appeals of Focus to be how quickly it starts up & opens links. I think it'd be great to add a test so we can avoid regressing startup times.

@bbinto, do you think this would be worthwhile? i.e. do you think the quick startup times of Focus are an important enough part of the product identity that we should spend time writing a test for it?

fwiw, I think [nimbledroid](http://nimbledroid.com/) provides startup time tests but I'm not sure how much it costs to use.

CC @npark-mozilla since he's been writing most of the UI tests, afaik.

**Comment by npark-mozilla** [comment]
Actually, according to android doc, the launch time to *initial* display gets printed on logcat (https://developer.android.com/topic/performance/launch-time.html#profiling) , and on Z3C:

07-10 16:47:59.895   974  2098 I ActivityManager: Displayed org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity: +1s669ms

it varies somewhat on each run with +- 200ms, but it's around there.  Maybe we could track this info somewhere?

**Comment by bbinto** [comment]
A few questions/comments

- Where would we have to store that info? Core ping? We'd need policy to review
- It'd be great to see if/how we could compare this either with our own Firefox browser apps or other browser apps
- How much work is this to get tracked?

**Comment by bbinto** [comment]
Any news / feedback on this? @mcomella

**Comment by mcomella** [comment]
I didn't see this, sorry.

I originally filed this to prevent startup time regressions. After thinking this over, **I'm not sure it's worth implementing at the moment**:
- We haven't been adding much that would affect startup time (though what background tasks do we run on startup? Maybe we could measure the duration of those instead?)
- I had intended to implement this as time from app launch to end of first page load in a controlled test harness for launching with external links but that's a lot of work (a couple of weeks?) so it's not worth implementing that.
- We could implement something simple with telemetry but I'm not sure it's valuable – we can't really measure time to end of first page load (which is what users want when saying "fast") because pages and networks are inconsistent. Time-to-page-start isn't necessarily helpful because it doesn't indicate when the page ends and any background tasks could slow it down.

@bbinto What do you think? Do you think it's worth pursuing?

---

Here is a quick rundown on how we might implement this if we chose to:

> Where would we have to store that info? Core ping? We'd need policy to review

My intent with this bug is to prevent start-up regressions. As such, I think it depends on how we want to do this. We can measure:
- In the wild via telemetry or in a controlled environment via a test harness
- The amount of time when opening external links, opening the start screen, or opening via a homescreen shortcut
- With different start/end hooks

**In the wild** will help us to identify edge cases but won't let us measure consistently over time (e.g. users upgrade to faster phones) while **a controlled test harness** will let us measure consistently over time, letting us identify specific changes or gradual trends that cause regressions, and letting us back-out regressions when they happen rather than letting them ship.

For **start/end hooks**, we could measure:
1. Time from launch to completed page load (this only really makes sense with a controlled env, but it's probably what we want to measure)
1. Time from launch to `onPageStarted` (when our WebView callback; this may not be useful)
1. Time from launch to view layout (this may not actual be feasible)

In general, I think UI telemetry could appropriate and we could potentially add these measurements as extras in an existing probe.

> - How much work is this to get tracked?

It depends heavily on the implementation we choose. Adding telemetry is pretty simple (t-shirt size S?) but creating consistent, reproducible startup time tests in a harness is more challenging and requires investigation into our CI tools, especially if we also need to compare it to Firefox, which uses a different CI env.
