### ISSUE TITLE
Constant stream of JS SyntaxErrors on reddit.com comment pages

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#893]
I'm seeing tons of errors in the log on a physical device (Moto X 2nd gen). Loading comments on a reddit page takes a really long time (>20 sec). The errors are almost all the "Block-scoped declarations" errors.

> 07-10 14:12:01.342 32436-32436/? I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode", source:  (1)
07-10 14:12:01.343 32436-32436/? I/chromium: [INFO:CONSOLE(0)] "XMLHttpRequest cannot load https://oops.redditmedia.com/api/9/store/?sentry_version=7&sentry_client=raven-js%2F3.10.0&sentry_key=81a4f63ba4664e869150034ae3849f2d. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.reddit.com' is therefore not allowed access. The response had HTTP status code 429.", source: https://www.reddit.com/r/pics/comments/6mf3je/my_friend_challenged_me_to_take_the_most_dramatic/ (0)
07-10 14:12:01.345 32436-32436/? I/chromium: [INFO:CONSOLE(0)] "XMLHttpRequest cannot load https://oops.redditmedia.com/api/9/store/?sentry_version=7&sentry_client=raven-js%2F3.10.0&sentry_key=81a4f63ba4664e869150034ae3849f2d. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.reddit.com' is therefore not allowed access. The response had HTTP status code 429.", source: https://www.reddit.com/r/pics/comments/6mf3je/my_friend_challenged_me_to_take_the_most_dramatic/ (0)

**Comment by bbinto** [comment]
@liuche can you reproduce this our latest version?

**Comment by liuche** [comment]
Checked on a recent build, and I'm not seeing this problem anymore. I'll reopen if it comes up again.
