### ISSUE TITLE
Filter out Focus in the BottomSheet when "Open with..." is clicked

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/focus-android#894]
It makes no sense to open with Focus again so this will help simplify/clarify the list. Furthermore this may also simplify the flow since opening the same url again can be a source of bugs in the future which is unnecessary. We shall take care of the case when Focus is the only browser available, though.

**Comment by ioana-chiorean** [comment]
Just saw this - and I agree
Curious fact is that i see it only on 2/3 devices 

<img src="https://user-images.githubusercontent.com/1391451/28212504-61390faa-68aa-11e7-9b96-927d445cad60.jpg" width="550" height="300" />

**Comment by mitchellkager** [comment]
look into On my fork, I offered a quick and dirty solution to this problem. Can't think of any way to prevent AppCompatDialogFragment from providing same package in getArguments(), so ignoring may be the best action. Tangentially: what behaviour should occur when there are no applications other than Focus available?

One note is that my solution compares to see if the packageName of each AppInfo is equal to the current application's packageName: if you are using, for example, Gecko, you will still be prompted to open the app in Focus. Could potentially instead filter based on the existence of the expression "org.mozilla.focus" within the AppInfo's packageName.

**Comment by pocmo** [comment]
The filtering should probably already happen in Browsers.java so that we do not show this menu item if there's no other browser.

**Comment by mitchellkager** [comment]
Ended up migrating logic to Browsers.java - fit cleaner there anyway. Now, need to look for a place where one can check to see if any browsers are available, choosing not to display the "Open in" menu option if none are.

**Comment by pocmo** [comment]
This is what happens here:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/menu/BrowserMenuAdapter.java#L83
