### ISSUE TITLE
TimeoutException: AssetManager$AssetInputStream.close

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#898]
```
java.util.concurrent.TimeoutException: 
  at android.content.res.AssetManager$AssetInputStream.close(AssetManager.java:577)
  at android.content.res.AssetManager$AssetInputStream.finalize(AssetManager.java:610)
  at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
  at java.lang.Thread.run(Thread.java:818)
```

Reports: 916
Impacted users: 363

**Comment by pocmo** [comment]
Not sure what to do here. The exception seems to happen outside of our code - so that we can't just ignore it. We are reading assets for two reasons: Domain lists for autocomplete and search plugins.

**Comment by pocmo** [comment]
There's nothing helpful when searching for this problem.

We saw this exception a couple of times in Fennec too:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1212204
* https://bugzilla.mozilla.org/show_bug.cgi?id=1298298

**Comment by pocmo** [comment]
Removing 1.1 label -> Right now I don't see any way how we can fix this on our side.

**Comment by pocmo** [comment]
This is currently our top crash (which isn't as dramatic - we are at 99.6% crash-free daily sessions).

**Comment by pocmo** [comment]
AssetInputStream code:
https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/content/res/AssetManager.java#L597

We open assets from two locations:
* UrlAutoCompleteFilter: To load the list of domains.
* SearchEngineManager: To load search engine plugins

For those we could think about wrapping AssetInputStream, overriding finalize() and suppressing the TimeoutException. But I'm not sure what state the device is in when this exception is thrown and we might keep an app alive that will crash with a different error later (and then things get really confusing to debug).

In addition to the things mentioned above there's also WebView loading some internal pages like licenses.html or gpl.html from the assets folder and it might be the case that the problem lies here (and only in specific WebView implementations).

**Comment by bbinto** [comment]
@pocmo mentioned we have yet to find a solution for it and we need a bit more investigation.
