### ISSUE TITLE
Cookies survive 'erasing' browsing history

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#90]
* Go to a website with login, e.g. Facebook
* Login
* Click 'erase' button or kill app
* Go to website again

Expected:
 You should not be logged in because all previous browsing data is erased.

Actual:
 You are still loved in.

**Comment by ahunt** [comment]
This should hopefully be enouhg;
https://developer.android.com/reference/android/webkit/CookieManager.html#removeAllCookies(android.webkit.ValueCallback%3Cjava.lang.Boolean%3E)

We should however also check what other data is stored by default, e.g. we'll probably want to use:
https://developer.android.com/reference/android/webkit/WebView.html#clearCache(boolean)

Then there's also:
https://developer.android.com/reference/android/webkit/WebStorage.html
And all of WebView.clear*

**Comment by ahunt** [comment]
It turns out we already do most of WebView.clear*:
https://github.com/mozilla-mobile/focus-android/blob/726364888a17756b6406898b53f5d94de7ac3fca/app/src/webkit/java/org/mozilla/focus/web/WebViewProvider.java#L82

**Comment by ahunt** [comment]
I'm wondering if we should also manually wipe all webview data directories, i.e.:
app_webview
cache/
cache/org.chromium.android_webview
databases/http_auth.db*
shared_prefs/WebViewChromiumPrefs.xml

With my patch, it seems all the content within those files is properly cleared - completely deleting the files would protect against failures in webview code though. However it's possible the file locations vary between versions (and/or could be changed in future), so trying to delete the files directly could break on random devices and/or upgrades.
