### ISSUE TITLE
Focus does not pass nothingprivate.ml

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#900]
http://www.nothingprivate.ml/ is a demo showing how a user is tracked even when private browsing is used. It seems to know who I am even after erasing my browsing session history. I guess it's using some fingerprinting mechanisms that we can't protect against as long as we are using WebView. But it would be interesting to know what exactly it's using (that affects Focus).

**Comment by pocmo** [comment]
This seems to work in all other browsers too.

**Comment by pocmo** [comment]
Source code:
https://github.com/gautamkrishnar/nothing-private

**Comment by pocmo** [comment]
The website is using ClientJS for fingerprinting:
https://clientjs.org/

**Comment by gautamkrishnar** [comment]
Yes, it uses ClientJS fingerprinting.  Please check this section for more info: https://clientjs.org/#Fingerprints

**Comment by lobontiumira** [comment]
The https://www.nothingprivate.ml/ demo works now on the latest RC 92.1.1 Focus build, using a Samsung Galaxy Note 8 (Android 9).

**Comment by pocmo** [comment]
@lobontiumira "works" meaning it is still identifying you? Or does it not remember your name across session?

**Comment by lobontiumira** [comment]
It remembers me.

**Comment by pocmo** [comment]
Okay, then I'll reopen this issue.

**Comment by lobontiumira** [comment]
Oh, sorry, I misread the issue. Thank you for reopening it!
