### ISSUE TITLE
focus / klar useragent and fingerprinting

### ISSUE THREAD

**Issue by phunkular** [mozilla-mobile/focus-android#902]
Hi there,

I understand that webview is more limited than gecko with regards to hiding from browser fingerprinting. However, I think that it's still important to reduce fingerprinting issues as much as possible when privacy is touted as the main feature.

As such I don't understand why klar and focus don't share the same user agent. There are approximately at least 10 times more downloads of focus to klar (+500k to +50k according to play store), making Klar users more conspicuous by a longshot.

perhaps 'Focus/Klar' instead of just 'Focus' and 'klar' respectively

In addition, anything else that could be done to standardise the user agent could only help focus fulfill its purpose... Different language choices can make some pretty non-standard http accept headings too for instance.

Thanks

**Comment by mcomella** [comment]
Thanks for filing – this is a good point. See also #444 (fingerprinting) and #445 (removing Focus from user agent entirely).

**Comment by pocmo** [comment]
See also #55 - That's where we implemented and discussed the user agent.

**Comment by pocmo** [comment]
And #900 for an example of fingerprinting tracking that works with Focus.

**Comment by phunkular** [comment]
hey thanks for the replies. I had already seen those threads but I felt that this issue was more about there being an unnecessary discrepancy between focus and klar which causes extra privacy implications for klar users.

thanks again

**Comment by nikwen** [comment]
Trying to add information to gauge the severity of the issue.

I ran the test at https://panopticlick.eff.org on the Klar browser and this was the result:

> Your browser fingerprint **appears to be unique** among the 498,628 tested so far.
> 
> Currently, we estimate that your browser has a fingerprint that conveys **at least 18.93 bits of identifying information**.

Further down it stated that out of the ~500k browsers that ran the test so far this had been **the only one** with the browser's user agent and that this was the reason for the unique fingerprint.

> User Agent | 18.93 bits of identifying information | one in 498628.0 browsers have this value | Mozilla/5.0 (Linux; Android 7.1.1) […] Klar […]

Hence, I would strongly recommend switching the user agent to something that is not language dependent!

(I would like to upload the full screenshots but Github sadly doesn't let me right now.)

**Comment by nikwen** [comment]
Here are the screenshots Github didn't let me upload last time.

![screenshot_20170720-220701](https://user-images.githubusercontent.com/3309657/28501876-b024e2be-6fe5-11e7-8698-e1d4e30dbf5b.png)

![screenshot_20170720-220711](https://user-images.githubusercontent.com/3309657/28501880-b7f7ea9a-6fe5-11e7-8f50-68c39b47c22a.png)

![screenshot_20170720-220719](https://user-images.githubusercontent.com/3309657/28501882-bbb960f0-6fe5-11e7-880d-32220f6138e3.png)

**Comment by nikwen** [comment]
I wanted to note that this is also negatively mentioned in the reviews on Google Play. For the German-speaking people:

![bildschirmfoto von 2017-07-23 20-33-25](https://user-images.githubusercontent.com/3309657/28501922-f2b80808-6fe6-11e7-9ef6-301d075375a5.png)

![bildschirmfoto von 2017-07-23 20-33-56](https://user-images.githubusercontent.com/3309657/28501924-f6fcacd4-6fe6-11e7-99a0-3123759d1b60.png)

![bildschirmfoto von 2017-07-23 20-35-50](https://user-images.githubusercontent.com/3309657/28501928-faf356f8-6fe6-11e7-8dce-01671b5cb2df.png)

**Comment by bbinto** [comment]
Confirmed with legal that we can consolidate user agents for Focus/Klar to just Klar.

**Comment by bbinto** [comment]
@pocmo & @antlam (if applicable), can you please add t-shirt sizes?

**Comment by antlam** [comment]
@bbinto unless I'm mistaken, it doesn't seem like there's anything for UX here?

**Comment by pocmo** [comment]
Moved this to Ebony: A contributor has written a patch for this! :)
