### ISSUE TITLE
Wrap optional UI features (refreshButton) in Optional type

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#903]
We [have guards such as][ex]:
```java
        if ((refreshButton = view.findViewById(R.id.refresh)) != null) {
            refreshButton.setOnClickListener(this);
        }
```

which presumably indicate optional UI features, based on the layout. It's inevitable that we forget to check null and we get a crashing `NullPointerException` – let's save ourselves the headache and wrap them in Optional type! e.g.
```java
private Optional<View> refreshButton;
```

We should import a lightweight optional type from Guava, Apache Commons, etc., or write our own.

This assumes we'll never move to Kotlin, which has Optional types built into the type system, given that it adds ~1MB to the APK pre-proguard and a selling point of ours is our small size.

[ex]: https://github.com/mozilla-mobile/focus-android/blob/ee9b7e99943170eb31d79abdeade3cdf765d602f/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java#L159

**Comment by mcomella** [comment]
> This assumes we'll never move to Kotlin,

This may be superseded by #975.

**Comment by pocmo** [comment]
@mcomella Closing this as we now have Kotlin support. :)
