### ISSUE TITLE
Crash when enabling multitasking webview in Android 7.0

### ISSUE THREAD

**Issue by spashx** [mozilla-mobile/focus-android#906]
- Enable developers options into the Android system
- Go to developers options and enable the "multiprocess webview/ execute webview rendering in separate processes " 
- Go to Firefox Focus and search for something
- Crash at the first page rendering

Android 7.0, kernel 3.18.35, Android System Webview 51.0.2704.91, Firefox Focus 1.0 (from Play store)

**Comment by pocmo** [comment]
From the [Android 7.0 docs](https://developer.android.com/about/versions/nougat/android-7.0.html):

> Multiprocess
> 
> Starting with Chrome version 51 in Android 7.0, WebView will run web content in a separate sandboxed process when the developer option "Multiprocess WebView" is enabled.
> 
> We're looking for feedback on compatibility and runtime performance in N before enabling multiprocess WebView in a future version of Android. In this version, regressions in startup time, total memory usage and software rendering performance are expected.

**Comment by pocmo** [comment]
On Android 8.0 I do not see this option in the developer settings anymore.

**Comment by pocmo** [comment]
[Android O Behavior Changes](https://developer.android.com/preview/behavior-changes.html):

> Your app's WebView objects now run in multiprocess mode. Web content is handled in a separate, isolated process from the containing app's process for enhanced security.

And Focus just works fine on Android 8.0. I assume this is only an issue in the (by default) disabled multi-process mode on Android 7. We'd need to look at a stack trace to know more.

**Comment by spashx** [comment]
Hi,
I would gladly help. I'm an IT guy but not an Android dev, could you provide a link describing how I can generate the stack trace ?

**Comment by mcomella** [comment]
Hey @spashx.

You can get the stack trace by getting a log from the device right after the crash occurs. Logs can be taken in "logcat". afaik, the only officially supported way to get logcat data is installing the Android SDK, and running the `adb logcat` command line tool with your device connected but that's a lot of work ([link to the SDK](https://developer.android.com/studio/index.html#downloads), if you're interested).

There are unofficial Android apps and desktop tools to do the same thing that might be simpler but being unofficial I can't vouch for them nor could I give a recommendation to use them.

**Comment by pocmo** [comment]
I've been using Focus on Android 8 for a while now. As stated above multiprocess is enabled for all WebViews on Android 8+. There have been no crashes so far. So it's very likely that the problems described are only happening when enabling the developer setting in Android 7. As this does not affect normal users we decided to not investigate this further.
