### ISSUE TITLE
Deploy Focus to Amazon Store?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#908]
I tried Focus briefly on a Kindle Fire. It seems to work well. Some animations are not smooth.

**Comment by bbinto** [comment]
Reached out to BD to confirm.

**Comment by jgmize** [comment]
similar to https://bugzilla.mozilla.org/show_bug.cgi?id=690820 I can understand the low priority on this, but https://developer.amazon.com/app-submission does look fairly straightforward.
