### ISSUE TITLE
Issue with prepareFocusWebkitDebugDependencies

### ISSUE THREAD

**Issue by djKooks** [mozilla-mobile/focus-android#91]
Hello. I am facing some issue on running focus-android project.
```
Information:Gradle tasks [:app:clean, :app:generateFocusGeckoDebugSources, :app:generateFocusGeckoDebugAndroidTestSources, :app:prepareFocusGeckoDebugUnitTestDependencies, :app:mockableAndroidJar, :app:assembleFocusGeckoDebug]
/Users/kwangin/workspace/focus-android/app/build.gradle
Error:(95, 1) A problem occurred configuring project ':app'.
> Could not get unknown property 'prepareFocusWebkitDebugDependencies' for project ':app' of type org.gradle.api.Project.
Information:BUILD FAILED
Information:Total time: 0.987 secs
Information:1 error
```
I update gradle version in my local repo.
```
classpath 'com.android.tools.build:gradle:2.2.3'
```
Is it a problem?

**Comment by pocmo** [comment]
This sounds like the same problem @npark-mozilla had. Can you help?

**Comment by pocmo** [comment]
Actually the same is now happening on buddybuild too - even though I do not see it locally.

**Comment by djKooks** [comment]
@pocmo Where is `prepareFocusWebkitDebugDependencies` dependency from? Is this related with gecko?

**Comment by npark-mozilla** [comment]
Ah this, I had to comment out the non-applicable lines inside project.afterEvaluate of app folder's build.gradle script for me to run it locally.  So if my Build Variant is set to webkitDebug, I only enabled prepareWebkitDebugDependencies.dependsOn("buildBlocklists") inside the app/build.gradle.  I was wondering why it wasn't needed on buddybuild though, but looks like it is now, I'll check it again on buddybuild.

**Comment by pocmo** [comment]
I have a patch for this in #92 now. This fixes it on buddybuild at least (I still can't reproduce this locally).

**Comment by pocmo** [comment]
@djKooks @npark-mozilla I merged the patch. Can you confirm that this fixed the problem for you too? At least Buddybuild is working again.

**Comment by npark-mozilla** [comment]
@pocmo yup it works well for me locally now!

**Comment by pocmo** [comment]
Thanks!

**Comment by djKooks** [comment]
@pocmo It works well on me too. Thanks!
