### ISSUE TITLE
Telemetry unexpectedly uploads during CI testing

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#915]
afaict, we're uploading telemetry events during UI testing on CI:
* We run `:app:testFocusWebkitReleaseUnitTest` on BB (in addition to other configurations which may also upload)
* The telemetry upload value is initialized [in TelemetryWrapper](https://github.com/mozilla-mobile/focus-android/blob/3961ce6f013bbb61f8f18c1df80e122a346c8a92/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.java#L105) with roughly the following logic: if it's a dev build (BUILD_TYPE is "debug"), then don't upload. Otherwise, get the preference value and if it doesn't exist, upload only if we're not a klar build. Nowhere in here do we look for test configurations.

One case I didn't look into is if perhaps we don't give proper telemetry keys to the application for testing builds (but I assume not – I assume it's the same as the BB).

@pocmo would you agree that we're uploading during testing?

---

Another thing to consider: should BB release builds even be uploading to telemetry? Or should we save that for Google Play builds & BB beta builds?

I think the best way to fix this is to have an argument passed to the app when we start the activity during testing that configures it to disable telemetry uploads.

**Comment by pocmo** [comment]
I'm confused. You mention UI tests, but `:app:testFocusWebkitReleaseUnitTest` is running unit tests (that shouldn't upload).

For UI tests we set up the build variant in buddybuild. Currently this should be focusWebkitAndroidDebugTest only. We were thinking about switching to Beta -> It's closer to what we ship - without most of the debug code. Telemetry is a concern when using beta builds. But the beta telemetry is not used for anything anyways (The test group is waaaaay to small).

> should BB release builds even be uploading to telemetry? Or should we save that for Google Play builds & BB beta builds?

I'm not sure I fully understand the question. Technically there should be no difference between the Buddybuild release builds and the builds that go to Google Play.

> I think the best way to fix this is to have an argument passed to the app when we start the activity during testing that configures it to disable telemetry uploads.

I'm a bit hesitant here. Or at least I want to delay this as long as possible. The more we use those flags the more we test things that are different to what we ship.

**Comment by mcomella** [comment]
> You mention UI tests, but :app:testFocusWebkitReleaseUnitTest is running unit tests (that shouldn't upload).

My bad – I pressed the "JUnit Tests" tab on BB, not the "UI Tests" tab, and didn't look at the name beyond "Release".

> I'm a bit hesitant here. Or at least I want to delay this as long as possible. The more we use those flags the more we test things that are different to what we ship.

This is fair.

> Telemetry is a concern when using beta builds. But the beta telemetry is not used for anything anyways (The test group is waaaaay to small).

fwiw, the smaller test group may not be the case if we switch to Play Beta builds (#600).

**Comment by pocmo** [comment]
> fwiw, the smaller test group may not be the case if we switch to Play Beta builds (#600).

That's true. However I think we'd still deploy release builds to the Play Store Beta channel, for two reasons:
* All release channels need to have the same package names (Okay, that's something we could change)
* Release management can promote builds from the pre-release channels to the release channels. This would be perfect to test early builds and then release them to users. Every difference between beta/release would make this impossible to use.
