### ISSUE TITLE
White screen while playing Vimeo videos 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#925]
Nexus 6P - Android 8.0
Pixel - Android 7.1.2
Focus 1.1. Beta Build #2202

Steps:
- go to Vimeo.com and play a video

Expected results:
- Video is played in full screen without any rendering issues

Actual results:
- when opening the video, a white screen is displayed
- on Nexus 6P with Android 8.0 sometimes it does not pass from the white screen 

See video: https://youtu.be/we85nJFM0dQ

**Comment by sv-ohorvath** [comment]
Also reproducing on Huawei Honor 8 (Android 6.0) & Samsung Galaxy Note 4 (Android 5.0.1).

**Comment by pocmo** [comment]
This is about the temporary white flash at the beginning when starting a video, right?

**Comment by sv-ohorvath** [comment]
Yes, and it's actually worse when resuming videos.

**Comment by pocmo** [comment]
Two ideas here:
* The full screen API of WebView allows to show a progress view until the video is ready. If this is showing at the same time where we see the white screen now then we could instead show some kind of progress / wait screen.
* We hide the browser and show the fullscreen view. Maybe some kind of alpha animation would make this look smoother and avoid this white flash.

**Comment by ioana-chiorean** [comment]
This is still visible with 1.2.1

**Comment by bbinto** [comment]
Any updates on this, i.e. is this still an issue?

**Comment by lobontiumira** [comment]
I did not encounter this issue lately.
Tested again on a debug build 8.13.1 (#1191.0a1-20210608091819), and with 8.16.0 with Samsung Galaxy Note 8 (Android 9), and with Google Pixel (Android 10).
I'll close this issue.
