### ISSUE TITLE
Vimeo.com displayed blank  on Nexus 7 ( 5.1.2) 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#926]
Nexus 7  - Android 5.1.2
Focus 1.1. Beta Build #2202

Steps:
- go to Vimeo.com  

Expected results:
- page is loaded and u can play a video

Actual results:
- page is blank beside the header 

See video: https://youtu.be/dw0cMqSZXk4
Check [log.txt](https://github.com/mozilla-mobile/focus-android/files/1148489/log.txt)

**Comment by bbinto** [comment]
Is this still an issue for you?

**Comment by ekager** [comment]
Closing for now, reopen if still an issue
