### ISSUE TITLE
Focus 1.1. Beta Build #2202 - always prompts that there is an update available, opens #2196

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#928]
Devices:
Huawei Honor 8 (Android 6.0)
Samsung Galaxy Note 4 (Android 5.0.1)
build: Focus 1.1. Beta Build #2202

Steps:
1. Install the latest Focus build: #2202 from dashboard.buddybuild.com
2. With a fresh install/clear data, open Focus.

Expected results:
When the latest build is installed, do not display the update prompt.

Actual results:
The 'update available' prompt is opened on first run. If you choose to update, it goes to build #2196.

**Comment by pocmo** [comment]
Oh weird. It's showing this every time for you? When you click on download then it prompts you to download build 2202 again? Can you shake the device, click on the (i) icon and see if the current build reports to be 2202 too?

This functionality is provided by the buddybuild SDK. If there's a bug then we'd need to report it to them. I haven't had this issue on my phone yet.

**Comment by sv-ohorvath** [comment]
When I click to download the update, it downloads the 2196 build apk. 
I've verified by shaking the device that my current build is 2022.

![screenshot_2017-07-14-18-35-26](https://user-images.githubusercontent.com/4037709/28219183-bc25af54-68c3-11e7-851a-a14a5c856a66.png)

**Comment by ioana-chiorean** [comment]
I always see this - even now with latest build Build #2686

**Comment by pocmo** [comment]
@ioana-chiorean Does it still want to download 2196?

**Comment by ioana-chiorean** [comment]
@pocmo not sure if 2196 (i forgot the number) but an older version for sure

**Comment by ioana-chiorean** [comment]
I can confirm now.
I had installed build 2844 and I got  update notif to 2196

![untitled](https://user-images.githubusercontent.com/1391451/30206179-e9be2e5e-9493-11e7-8467-35621ab11571.png)

**Comment by bbinto** [comment]
@pocmo still an issue we should care about?

**Comment by pocmo** [comment]
> @pocmo still an issue we should care about?

Eventually I want to distribute our Nightly builds via Google Play. This is going to depend on automated signing and uploading though. Until then we might just live with that - especially as this seems to be an issue with the buddybuild SDK and not part of our code.

**Comment by pocmo** [comment]
We stopped using buddybuild. For now preview builds (potentially unstable!) are available here: https://bit.ly/focus-preview-builds
