### ISSUE TITLE
Consider using buddybuild SDK for nightly builds for updates/crash-reporting/etc

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#93]
Getting people testing nightly builds would be nice - but AFAICT you currently need to manually find and install each update. The buddybuild SDK seems to offer automatic updates (similar to what nightly does: you still need to press a button to update), and also crash-reporting and other niceties. It might be worth doing this for nightly builds. (I doubt we'll want this for release though.)

**Comment by ahunt** [comment]
Link:
http://docs.buddybuild.com/docs/integrating-sdk-android

**Comment by pocmo** [comment]
I've enabled the SDK for dev and beta builds. It should be added automatically for builds made and installed through buddybuild.

**Comment by pocmo** [comment]
I didn't transfer everyone to the new builds yet though... :)

**Comment by pocmo** [comment]
Okay, the next builds will be distributed with the "beta" branding and will include the buddybuild SDK.
