### ISSUE TITLE
www.sportsnet.ca/videos does not play

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#931]
Even with all blockers disabled, it only shows the thumbnail of the video, and does not play the video.
![screenshot_20170714-120452](https://user-images.githubusercontent.com/6930774/28220267-d7efba40-688c-11e7-9b68-53d98f5c06d7.png)

**Comment by mcomella** [comment]
I think the problem is we're blocking cookies: I can reproduce on Chrome with cookies disabled.

**Comment by pocmo** [comment]
We do not explicitly block cookies. However on app startup we clean all left over webview files. I think I saw logs that sometimes WebView wants to write to some database that doesn't exist anymore. Maybe this breaks saving cookies too. @ekager You could test disabling all this code that removes files etc. and then see if this fixes the issue. We have been pretty excessive with calling the clean up code. I think we do not need all those calls anymore (especially as we are doing a full clean from the Service when the task is killed anyways).

**Comment by ekager** [comment]
This may be mostly a sportsnet.ca issue. I couldn't load their videos on desktop with FF or Safari either. Works on Chrome. Found similar issues [online](https://www.reddit.com/r/NHLStreams/comments/66u3yo/sportsnet_now_not_working_in_firefoxedge/). 

Strangely enough - the fix for #927 also makes this issue better. It still doesn't play the video, but it launches the video player instead of staying at the thumbnail.

**Comment by npark-mozilla** [comment]
It's not working on FF on android, but it seems to play okay on FF for iOS (latest beta) and Safari iOS. perhaps some android specific issue?

**Comment by pocmo** [comment]
Somehow I can't play any video from this site in any of my desktop browsers (Firefox, Chrome, Safari).

**Comment by pocmo** [comment]
> Somehow I can't play any video from this site in any of my desktop browsers (Firefox, Chrome, Safari).

Oh, now on Chrome on Android I see a small text below the video saying: "This content is unavailable in your region".

**Comment by npark-mozilla** [comment]
After the localstorage fix, the videos are playing fine on the site. Thanks @ekager !
