### ISSUE TITLE
Add support for file uploads (input type=file)

### ISSUE THREAD

**Issue by feikname** [mozilla-mobile/focus-android#937]
I tried to upload a file to a website which has a `<input type="file">` element, and noticed that Focus doesn't bring any UI for file selection currently.

**Edit**: Support for the `multiple` attribute would be nice too, as it seems no major mobile browser really supports it currently.

**Edit 2:** It seems now Chrome supports it. I haven't tested other mobile browsers.

**Comment by Eskuero** [comment]
Yeah I'm really looking forward upload support, would like to be able to use Firefox Send from the phone without having to download a different browser.

**Comment by bbinto** [comment]
https://play.google.com/apps/publish?account=7083182635971239206#ReviewDetailsPlace:p=org.mozilla.focus&reviewid=gp:AOqpTOGW9BN46OARE0sbLYhXvR6ejrwijywQ-gWG7l0hTe7Ty9vuScwoP_Wf_i4ZOopSrN-5HxFZxENpYgT7JsI

**Comment by pocmo** [comment]
This should work in GeckoView (this bug is only for WebView) - but it doesn't seem like it does. I can select files but they do not get uploaded.

**Comment by pocmo** [comment]
* WebView -> Feature
 * GeckoView -> Bug?

**Comment by bbinto** [comment]
Let's keep it simple and only fix the bug for GeckoView (and forget about the WebView aspect)

**Comment by cpeterso** [comment]
I filed a GeckoView bug about fixing <input type="file">:

https://bugzilla.mozilla.org/show_bug.cgi?id=1476810

**Comment by pocmo** [comment]
From the GV bug:

> So the Focus Activity (or Crow Activity) has to customize `GeckoViewPrompt.filePickerRequestCode` > [1] for the file picker to work properly. geckoview_example does that at [2] and [3].
> 
> [1] https://github.com/mozilla-mobile/focus-android/blob/6507f302900fa7f087768dd36a2160d2734ca0a9/app/src/gecko/java/org/mozilla/focus/web/GeckoViewPrompt.java#L57
> [2] https://searchfox.org/mozilla-central/rev/88199de427d3c5762b7f3c2a4860c10734abd867/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/GeckoViewActivity.java#165
> [3] https://searchfox.org/mozilla-central/rev/88199de427d3c5762b7f3c2a4860c10734abd867/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/GeckoViewActivity.java#300

**Comment by pocmo** [comment]
@ekager That might be something we can fix --^
@bbinto This might be a feature we can support easily with GeckoView (if we don't implement it for WebView for now..)

**Comment by brampitoyo** [comment]
User flow

![upload-file 2x](https://user-images.githubusercontent.com/51007/45069142-23f28900-b11f-11e8-8f52-19fbd1d1cccc.png)

1. User taps on “Upload…” or “Browse…” button on a website
2. We show a system permission dialogue to access files stored on the user’s device
    * The system dialogue will also allow the user to “Always Allow” or “Always Deny” (not shown in this mockup)
    * Not recommended: show permission dialogue to access camera (“take pictures and record video”) – we only need access to the file manager
3. Open the phone’s default file manager app, allowing the user to select a file to upload

Since all file manager apps have a feature to select multiple files, can we rely on them to provide this feature, or do we need to build our own custom file browser/selector from scratch?

**Comment by vesta0** [comment]
@pocmo @ekager sounds like this item is ready to be worked on by the Focus team, correct?

**Comment by pocmo** [comment]
Yes, I think we should have everything in GV for that.

**Comment by NotWoods** [comment]
This works in GeckoView now.

**Comment by jonalmeida** [comment]
This does not work in my testing on all current versions from 7.0.18 to 5.0. @NotWoods , which version were you using at the time?

**Comment by MichaelKohler** [comment]
What is the status here? I have a form that correctly uploads files when used in Firefox for Android and Desktop, however with the latest version of Firefox Klar from the Google Play Store it doesn't work correctly. However I'm able to select files, but after that it still says "No file selected" and doesn't correctly upload the file. Should this be working by now or are there still open tasks to be  fully supported?

**Comment by pocmo** [comment]
@Amejia481 This is getting handled by `feature-prompts` right?

**Comment by brampitoyo** [comment]
@pocmo @Amejia481 In terms of UX, I am happy to use the same behaviour as Firefox’s.

This means that selecting the “Choose file” action/button will instantly trigger Files.app.

![screen-20210907-115025](https://user-images.githubusercontent.com/51007/132266334-203892fa-d44c-4abd-86a2-0d684dc938a6.gif)

**Comment by Amejia481** [comment]
> @Amejia481 This is getting handled by `feature-prompts` right?

Yes, exactly :)

**Comment by pocmo** [comment]
@Amejia481 Is anything else needed? Since we integrate that one already. 🤔

**Comment by Amejia481** [comment]
Let's me take a look and report back.

**Comment by Amejia481** [comment]
This should be fixed on `main`.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 9/9 (GV 93.0a1-20210901091701) with Lenovo Tab M10 (Android 10).

**Comment by feikname** [comment]
As a matter of curiosity,  does it support multiple file selection when 'multiple' attribute is specified?

**Comment by lobontiumira** [comment]
Yes, I had gmail opened in a tab, and attached to an email a .mp4 file, a .png file, and a .jpeg file.
The email was sent successfully.
