### ISSUE TITLE
Use Photon icons

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#938]
Filing so I don't forget... 57 is when Photon UI is hitting other Firefoxes

**Update:**
Icons to be replaced:
- [x] <-
- [x] ->
- [x] Refresh
- [x] Stop
- [x] Lock (expanded URL)
- [x] Magnifying glass
- [x] Close
- [x] Link for Multitasking
- [x] Clear
- [x] Notification icon
- [x] Download/document icon
- [ ] Trash Can

**Comment by pocmo** [comment]
SVGs please! :)

**Comment by antlam** [comment]
This is going in iOS during Ebony, perhaps we could match?

**Comment by antlam** [comment]
@pocmo 

[Photon Icons Pack 1.zip](https://github.com/mozilla-mobile/focus-android/files/1304687/Photon.Icons.Pack.1.zip)

Here are some of the .SVGs. I'm locating the others. 

This pack includes the Back, Forward, Refresh, Stop, Lock, Search (magnifying glass), Close, and Link icon.

**Comment by pocmo** [comment]
lock-disabled.svg - This seems to be a new icon - do we intent to use it?

**Comment by pocmo** [comment]
![icons](https://user-images.githubusercontent.com/89638/30475100-f5e310d8-9a05-11e7-89fb-1edf48af936c.png)

**Comment by pocmo** [comment]
^-- Something is wrong with the "link" icon when importing it into Android Studio. I need to check whether the importer is doing something wrong or whether the icon uses an SVG feature that is not supported by Android.

**Comment by pocmo** [comment]
![link](https://user-images.githubusercontent.com/89638/30475477-4154bdf4-9a07-11e7-8bb7-7cbc0b0f3fd9.png)

Okay, used another tool for importing and now the icon looks good.

**Comment by antlam** [comment]
@pocmo awesome. I'll be getting a Photon 'clear' icon next week too.

> lock-disabled.svg - This seems to be a new icon - do we intent to use it?

Not ATM, I left it in there because I feel like we might use it soon. But feel free to omit from the tree for now.

Otherwise looking good!

**Comment by antlam** [comment]
@pocmo Also, here's the glyph for the notification ;)

[Glyphs - Firefox - Black.zip](https://github.com/mozilla-mobile/focus-android/files/1307076/Glyphs.-.Firefox.-.Black.zip)

**Comment by pocmo** [comment]
@antlam We might need PNGs for that. The glyph looks good on Android O but it's broken on Android 5.0 for example:
![device-2017-09-18-155620](https://user-images.githubusercontent.com/89638/30546000-ac228f86-9c8b-11e7-9a2d-eedccad42098.png)

Maybe we are using SVG features that are not supported by Android?
https://developer.android.com/studio/write/vector-asset-studio.html#PSD

**Comment by antlam** [comment]
@pocmo could you tell me what sizes you need for this ?

**Comment by pocmo** [comment]
* hdpi 36x36
  https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/res/drawable-hdpi/ic_notification.png
* xhdpi 48x48
  https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/res/drawable-xhdpi/ic_notification.png
* xxhdpi 72x72
  https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/res/drawable-xxhdpi/ic_notification.png

**Comment by antlam** [comment]
[notification_glyph.zip](https://github.com/mozilla-mobile/focus-android/files/1315303/notification_glyph.zip)

@pocmo here ya go, some PNGs on-dark

**Comment by pocmo** [comment]
![screenshot_1505933110](https://user-images.githubusercontent.com/89638/30661571-c2a2e872-9e44-11e7-9002-430a2cded7ab.png)
![screenshot_1505933115](https://user-images.githubusercontent.com/89638/30661589-ce9311e8-9e44-11e7-86ae-3dde41d798f5.png)

**Comment by antlam** [comment]
[clear_download_SVG.zip](https://github.com/mozilla-mobile/focus-android/files/1319306/clear_download_SVG.zip)

Clear icon! + Download icon! @pocmo 

(let's replace the file icon with this download icon)

These are the last ones for this issue. We are working on a more distinct/Photon-y "Erase" icon for both iOS and Android ATM.

**Comment by pocmo** [comment]
![icons](https://user-images.githubusercontent.com/89638/30690350-32ab5cc4-9ec4-11e7-957f-790dcd5b380f.png)

**Comment by pocmo** [comment]
> These are the last ones for this issue. We are working on a more distinct/Photon-y "Erase" icon for both iOS and Android ATM.

Okay. I'll close this issue here and file a new one. If the icon is available in time then we can move the new issue in Ebony. For now I'll move it to Folly.
