### ISSUE TITLE
Document supported Android versions

### ISSUE THREAD

**Issue by picsi** [mozilla-mobile/focus-android#941]
From 4.4 I can't seem to download it (Klar) from F-Droid, which makes me think it'd be useful to mention what versions are supported by Focus/Klar.

**Comment by pocmo** [comment]
In our repository it's documented as the "minSdkVersion".

And it's shown on Google Play:
![image](https://user-images.githubusercontent.com/89638/28261249-b83186c6-6ade-11e7-9c9e-9a1e4b4501db.png)

If f-droid doesn't show this information then maybe that's something f-droid should take care of?

**Comment by picsi** [comment]
Thanks for the heads up.
