### ISSUE TITLE
Add telemetry for Stealth mode setting change

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#943]
I can't find a probe here https://github.com/mozilla-mobile/focus-android/blob/master/docs/telemetry.md that collects info on how often the setting is changed.

**Comment by 9662** [comment]
Drive by here, but why does a supposedly privacy focused browser have telemetry at all?

**Comment by bbinto** [comment]
Is it pref_secure?

**Comment by pocmo** [comment]
@bbinto Yeah, that's the one. We should send "change" telemetry for it, but not the current state as part of the event ping:
https://github.com/mozilla-mobile/focus-android/blob/master/docs/telemetry.md#settings

But this should be a quick fix.

**Comment by bbinto** [comment]
@9662 I appreciate your comment and feedback.

We always give users the option to turn off telemetry (via settings). To deliver great products for our users, we need to understand how our product is working and how successful we are. Specifically to this case, we want to understand what kind of things are important to our users, i.e. do people care about having a black app drawer or the convenience of being able to take screenshots.

Please read further here: https://www.mozilla.org/en-US/privacy/firefox/
