### ISSUE TITLE
Evaluate if we should remove autocomplete list from address bar

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#958]
- Maybe consider informing users that autocompleting common URLs (youtube.com, cnn.com) is coming from a local list?
- Follow telemetry and usage of this feature

**Comment by bbinto** [comment]
https://appbot.co/apps/1486184-firefox-focus-the-privacy-browser/reviews/549596031

**Comment by Benestar** [comment]
I am very much in favour of removing the autocomplete list altogether. It happened to me too often that I accidentally opened a suggsted url instead of searching for another term that happened to start with the same letters.

**Comment by pocmo** [comment]
Afaik this improved the onboarding experience in Fennec? Anyhow, I think if we want to go forward here then we should move this feature behind a switchboard flag and then try disabling it for a subset of users and then let's see... :)

**Comment by lobontiumira** [comment]
Hello all!
The user has now the option to enable or disable the autocomplete for top sites, or for sites they add from Settings - Search - URL Autocomplete section.
Also, the search suggestions can remain inactive also by disabling the "Get search suggestions" toggle from Settings - Search, or by tapping on "No" on this pop-up that is displayed when a user is typing in the search field:

![Screenshot_4](https://user-images.githubusercontent.com/40694158/154652780-2df179c4-511a-4412-9f9b-3d4e0f63d5da.jpg)

I will close this ticket.
Thank you,
