### ISSUE TITLE
Consider close option when Focus is opened from a referring link / app.

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#963]
via bruck

I click on a link from Twitter, etc… which opens it as default browser (not custom tab) I then maybe click or navigate into some things from that link in Focus. I can't close Focus and be back in the referring app. If it is an app that use custom tabs then it typically gets a close button in the top left corner. ie Open a link from Slack or Gmail and the behavior I expect is there.

**Comment by antlam** [comment]
@pocmo is this the back button behaviour we were addressing initially? with the toast confirmation?

**Comment by antlam** [comment]
Discussed this in triage, but we dont fully understand the original comment. Between supporting custom tabs and the back button behaviour changes we made, it doesn't seem like this is as much of an issue anymore.

Closing for now, we can always refile to be more specific if it's a bug or file a user story if its a larger feature request :)
