### ISSUE TITLE
Left/right gestures to quickly navigate through different pages/history

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#966]
_Added by @bbinto_

**Why/User Benefit**
- User want to have an option to quickly navigate back and forth while performing a task in Focus

**What**
- Gestures to let them swipe through pages/history

**Acceptance Criteria (how do I know when I’m done?)**
- Swipe is implemented in a way that it's not breaking the vertical interactions of the page (e.g. scrolling)
- Probe to define how often this feature is being used, swipe left, and swipe right action should be tracked distinctively 

----

**Comment by antlam** [comment]
I'm not sure how high priority this is for the Android platform given the prominence of the hardware back button. On iOS, this make as lot more sense but I don't think its as commonplace in Android.

@bbinto this feels like a low-priority for UX, could we move this out of Folly and to Under Consideration ?
