### ISSUE TITLE
Find in page

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#967]
_Added by @bbinto_

**Why/User Benefit**
- User can find more quickly what they are looking for on a website
- User have communicate they'd like this feature

**What**
- "Find in page" functionality 

**Acceptance Criteria (how do I know when I’m done?)**
- User can find and access "find in page" functionality
- Probe that tracks how often and by how many users this feature is being triggered

----
Especially useful if you set Focus as your default on Android.

I haven't confirmed this doesn't exist on iOS.

**Comment by antlam** [comment]
Can confirm, this doesn't exist on Firefox Focus for iOS.

**Comment by briankung** [comment]
Ah, I meant to post here and not in iOS, but yes, I would really like this feature!

**Comment by antlam** [comment]
@bbinto I'm going to move this to Granite* since Folly is a non-UX release and already has "What's New?"

Let me know if you disagree! happy to discuss more when you're back :)

**Comment by TPS** [comment]
A little confused by all the label-changing ↑:  Is this _planned_ or just _considering_?

**Comment by antlam** [comment]
@TPS not to worry, the labels are more for our team to co-ordinate the work necessary for a release. 

ATM, this feature is being planned for our Granite release milestone. But as it is with software development, that could still change.

**Comment by vext01** [comment]
I find myself having to open the full firefox app all the time, just to search for a string in the page.

**Comment by brampitoyo** [comment]
Assigning this issue to myself so it’s present on my to-do list.

**Comment by brampitoyo** [comment]
Here are find in page UIs of various Android browsers:

#### Firefox

<img src="https://user-images.githubusercontent.com/51007/39415124-afac2ed8-4c93-11e8-8bd4-053f4f13dcc5.png" width="180">

#### Chrome

<img src="https://user-images.githubusercontent.com/51007/39415098-66341022-4c93-11e8-87f1-f15330f5cf6c.png" width="180">

#### Opera

<img src="https://user-images.githubusercontent.com/51007/39415096-5b899f34-4c93-11e8-91a5-600c56ef5b6b.png" width="180">

#### Samsung Internet

<img src="https://user-images.githubusercontent.com/51007/39415033-791f08a0-4c92-11e8-9484-9959590a82d0.png" width="180">

#### UC

<img src="https://user-images.githubusercontent.com/51007/39415043-a168756c-4c92-11e8-88de-1337d8f08335.png" width="180"><img src="https://user-images.githubusercontent.com/51007/39415044-a41d1e16-4c92-11e8-86af-bd89adc49cc7.png" width="180">

#### Yandex
<img src="https://user-images.githubusercontent.com/51007/39415014-386e414a-4c92-11e8-9f4f-2b4418ed7382.png" width="180">

#### Dolphin

<img src="https://user-images.githubusercontent.com/51007/39414973-d9e2b3ea-4c91-11e8-8d70-329991de57d1.png" width="180">

#### Puffin

<img src="https://user-images.githubusercontent.com/51007/39414992-0d4fc9fc-4c92-11e8-8676-421a7e6ab73b.png" width="180">

#### CM Browser

<img src="https://user-images.githubusercontent.com/51007/39414994-0ff810a6-4c92-11e8-8a93-92ef77826157.png" width="180">

#### APUS

<img src="https://user-images.githubusercontent.com/51007/39415048-b225f3f2-4c92-11e8-99cf-7aecb4d7f091.png" width="180">

**Comment by brampitoyo** [comment]
Here’s my first attempt at desining a find in page UI. It’s what Fennec’s would’ve look like if it was Photonised:

<img src="https://user-images.githubusercontent.com/51007/39461157-eed9e3f6-4d5c-11e8-9d7c-5879279c00e1.png" width="360">

I’m still trying to think of the right colour combination to use.

Currently, Firefox for desktop uses cyan for highlighted text, and magenta for the other highlights. Fennec uses a more muted shade of cyan and no colour for the other highlights. We’ll need to pick a colour from the Photon palette, and make sure that it plays well with the website, no matter what colour it’s displayed on.

**Comment by bbinto** [comment]
I assume (no pressure) UX is not finalized yet, correct? @brampitoyo

**Comment by brampitoyo** [comment]
Not finished, but nearly there!

I still need to think about:

* Entry point (ie. order of placement in the menu)
* Visual design (ie. how much does it need to match vs. differ from Fennec?)

**Comment by boek** [comment]
# In Focus
- [ ] Menu Item to toggle find in page (s)

# In a component
- [ ] Find in page UI (above keyboard) (s)
- [ ] JavaScript to find, highlight and jump to search query (m)
- [ ] Glue code to sync the android UI and JavaScript (m)

**Comment by pocmo** [comment]
@boek WebView has APIs for find-in-page. You will not need to write JavaScript :)

* https://developer.android.com/reference/android/webkit/WebView.html#findAllAsync(java.lang.String)
* https://developer.android.com/reference/android/webkit/WebView#setFindListener(android.webkit.WebView.FindListener)
* https://developer.android.com/reference/android/webkit/WebView.FindListener

**Comment by bbinto** [comment]
Given that exciting news, @boek any updates/revisions on the T-shirt size?

**Comment by boek** [comment]
@bbinto This is still a large, was able to combine the two M's into one though :)

**Comment by bbinto** [comment]
@boek - thanks. So should this be moved (and achievable) to be worked on in 6.0 sprint or 5.2?

**Comment by boek** [comment]
@bbinto 6.0 sounds good. I have a few of the breakdown tickets that I’ve put into 5.2 and completed. I might get this done in 5.2 but I have a few other tickets I need to finish up first

**Comment by TPS** [comment]
What version should we expect this?

& thanks very much, @all. :bow:

**Comment by boek** [comment]
@TPS 6.0 (the next release) 😊

**Comment by TPS** [comment]
I hoped perhaps if a 5.× release was scheduled, it'd make that, but if 6.0 is next, I hope to use a β pretty soon.  I wouldn't _need_ anything else from this. 😁
