### ISSUE TITLE
(BrowserFragment) IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#970]
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

4 | android​.support​.v4​.app | DialogFragment.java​ Line 143 DialogFragment.show
5 | org​.mozilla​.focus​.fragment | BrowserFragment.java ​Line ​510
6 | org​.mozilla​.focus​.fragment | BrowserFragment.java ​Line  501 BrowserFragment.onRequestPermissionsResult
```

![image](https://user-images.githubusercontent.com/89638/28280554-68aa106e-6b24-11e7-9092-4919ff74e638.png)

[View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/99edb87817d35403857716ea57cfd34c)

**Comment by pocmo** [comment]
@ekager This is related to the downloads dialog. Do you have time to look into this?

**Comment by pocmo** [comment]
https://issuetracker.google.com/issues/37067655

**Comment by ekager** [comment]
Yes I can look into this today!
