### ISSUE TITLE
No superfluous authentication warning

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/focus-android#978]
Transferred from [bug 1381835 on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1381835):

Going to e.g. http://www.github.com@buttercookie.de doesn't trigger a warning that the site in question doesn't in fact require authentication [1].

[1] You are about to log in to the site “buttercookie.de” with the username “www%2Egithub%2Ecom”, but the website does not require authentication. This may be an attempt to trick you.

Is “buttercookie.de” the site you want to visit?

**Comment by shwetabhsuman** [comment]
Hi Team,

Please look into this and provide me current update.

Regards
Shwetabh Suman

**Comment by shwetabhsuman** [comment]
Hi Team,

Any update regarding the above issue submitted?

Regards
Shwetabh Suman

**Comment by pocmo** [comment]
It's on the roadmap for one of the next releases.

**Comment by shwetabhsuman** [comment]
Hi Pocmo,

Any acknowledgement/Credit/CVE for this above submission?

Regards
Shwetabh Suman

**Comment by shwetabhsuman** [comment]
Hi Team,

Any update regrading above question ?

Regards
Shwetabh Suman

**Comment by pocmo** [comment]
I talked to the security team at Mozilla. From their assessment this is not a real security issue for which they'd assign a CVE. Also note that so far we haven't released any advisories for Focus.

@buttercookie42 Thanks for your help transferring this bug and making it visible to us. We should be cautious with potential security bugs though - GitHub doesn't allow us to hide issues or completely delete them easily.

**Comment by bbinto** [comment]
@pocmo & @antlam can you please add t-shirt sizes?

**Comment by shwetabhsuman** [comment]
Hi Team,

What about me , I have only the first one to report this issue to mozilla.

Regards
Shwetabh

**Comment by bbinto** [comment]
@shwetabhsuman the t-shirt sizing is a way for us to get effort estimates on how long it would take Eng/UX to finish the task, so we can prioritize.

If you want to take on this issue and start the eng work, we are happy to hear that :)

I hope that makes sense.

**Comment by pocmo** [comment]
Needs more investigation. But it's at least M.

**Comment by antlam** [comment]
@lime124 this sounds related to some of the SSL things you mentioned before too. 

Thoughts on t-shirt sizing?

**Comment by lime124** [comment]
I would give it a small. We just need to figure out the expected behaviour and can probably leverage what other browsers do.

**Comment by bbinto** [comment]
Due to Sebastian's [comment](https://github.com/mozilla-mobile/focus-android/issues/978#issuecomment-321536178), moving this to a P5 for now
