### ISSUE TITLE
Consider adding integration tests for content blocking

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#98]
The tests for Url Matching, and category switching (not yet landed), are quite robust. Having an integration test that loads certain websites and verifies that resources are actually blocked would be nice.

I'm not sure how this could be implemented, we probably can't rely on loading pages from the internet (and those are liable to change too). We'd need to supply our own sites, and have the ability to serve the content that should be blocked.

**Comment by pocmo** [comment]
Ha, I just wanted to file this.

**Comment by pocmo** [comment]
@npark-mozilla I'm going through old issues - Do our UI tests already do that?

**Comment by npark-mozilla** [comment]
no- I don't think we have a test that checks actual content blocking, that's activated on BB. We have AdBlockingTest, but that is disabled on BB.  I was looking into creating a local webpage with ads, but that requires me to actually have an ad account.  would there be a simpler way to simulate a blockable content?

**Comment by bbinto** [comment]
Is this issue still relevant? @npark-mozilla ?

**Comment by npark-mozilla** [comment]
@bbinto yes, actually I believe Bogdan from softvision is working on this as his first test.  will keep you updated.
@bsurd FYI, you can reference this bug when you create your PR.

**Comment by npark-mozilla** [comment]
Ah, I just realized this *is* the bug that we are referencing for the exercise. This will be done soon.
