### ISSUE TITLE
Some URIs aren't correctly understood.

### ISSUE THREAD

**Issue by sys3175** [mozilla-mobile/focus-android#989]
Addresses of local devices are rejected or interpreted as search query but IMO shouldn't be.
Example: local webcam called rpicam per local name server for LAN..
Enter rpicam:8081 into URL bar, and you'll get Address wasn't understood.
Enter rpicam/ which e.g. in Chrome forces the browser to interpret this as URI, you'll get a search result page.
Only if you enclose everything in the http://server:port/ notation it's going to work.

**Comment by ventaquil** [comment]
Same here. When I used custom port on my server (example 3030) I got response _"Undefined protocol"_ but when I added _"http://"_ prefix everything gone correct.

**Comment by grubdragon** [comment]
I can think of two workarounds, one will probably be the right one to do, i.e. investigate why this is happening for a missing "http://" part, or simply append http:// for server:port type URIs.

**Comment by ventaquil** [comment]
@grubdragon missing _"http://"_ part is because I didn't write it in address bar. But why normal Firefox browser for Android knows that it's possible to open this link - and I am not adding _"http://"_ prefix.

![Firefox example](https://user-images.githubusercontent.com/10523774/34984874-94e0c86c-fab2-11e7-9981-a4c1613061ef.png)

**Comment by lobontiumira** [comment]
@sys3175 is this still an issue for you?

**Comment by sys3175** [comment]
92.1.1 (Build #2015832083)
AC: 92.0.15, e00bef534d
GV: 92.0-20210903235534
AS: 82.1.0

I'm seeing this still, but it has changed.

Take my PBX here. Short hostname: pbx

I enter 'pbx' - I get a search for 'pbx' - that is ok.
I enter 'pbx/' - I get a search for 'pbx/' - it should open http://pbx/
I enter pbx:80 - nothing happens - that should not be the case (the same occurs with appended slash)

Only with added domain name pbx.local.mydomain.tld
everything works as expected.

I would not consider this fixed.

In the nightly 94.0a1 (Build #2015835339), the behavior is identical.

In the desktop version (checked on 78.12.0esr), it works as expected.
