### ISSUE TITLE
Add data clearing tests

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#99]
It would be good to have a test to verify that all private data is _really_ cleared when using the erase button. We could do this by iterating over all files in the application directory, and searching for instances of visited URLs, usernames, passwords, cookies, etc. (This would ensure that we don't regress on #90.)

Some of the files of interest are listed in:
https://github.com/mozilla-mobile/focus-android/issues/90#issuecomment-281504819

I'm not too sure how to set up the infrastructure to serve test pages, this is similar to what we'd need in #98.

**Comment by pocmo** [comment]
Yeah, that's a great idea. I was also wondering how we can verify that the blocking does not regress.

I used MockWebServer for some other app that does web requests and where I want to "fake" them in unit tests: https://github.com/square/okhttp/tree/master/mockwebserver

**Comment by pocmo** [comment]
I wrote a test like this some time ago (WebViewDataTest).
