### ISSUE TITLE
WebView retains visited link list in memory until app is closed

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#990]
Reopening an issue for #322 (Also see #828). Mostly to track the Chromium bug here too:
https://bugs.chromium.org/p/chromium/issues/detail?id=709627

**Comment by phunkular** [comment]
just came to report that google was remembering search history even when browsing history was erased... perhaps this is the same bug?

1. go to google.com
2. search something
3. erase browsing history from notification or trashcan icon
4. go back to google.com
5. notice that when you start to type the same search it is guessed straight away and highlighted purple.

I have noticied that this seems to happen less if you leave the app for a while and then use the notification to erase and certainly not after swiping focus away from recents (am using MIUI though so I think that swiping recents might do a litttle more in terms of maybe FC'ing and cache-clearing than default android... not sure). Have noticed that the search terms are preserved even when changing IP with vpn!

**Comment by bbinto** [comment]
Waiting for fix in WebView (no steps to be taken from our end)

**Comment by mcomella** [comment]
Last comment in the bug:

> Passing this to the pool of available bugs. This is probably a good API to add. Unfortunately, I don't think we have bandwidth to add such an API for P.

So either:
1. We fix it ourselves. :) This assumes the WebView support library is released soon though.
1. We wait to at least Android U, which is a ways off.
1. We come up with a work-around (currently #1600? there are a few open issues)

---

> just came to report that google was remembering search history even when browsing history was erased... perhaps this is the same bug?

This was fixed in #1306.

**Comment by pocmo** [comment]
> We wait to at least Android U, which is a ways off.

Why not Q? 😝 

> We come up with a work-around (currently #1600? there are a few open issues)

There's no known workaround for the root problem. Anyhow this issue is for explicitly tracking an upstream fix (-> 'blocked' label). If we have ideas for workarounds then let's file separate issues.

**Comment by bbinto** [comment]
> We fix it ourselves. :) This assumes the WebView support library is released soon though.

Any guesses on timeline?

**Comment by mcomella** [comment]
> Any guesses on timeline?

The first mention I see is [a mailing list post on May 18](https://groups.google.com/a/chromium.org/d/msg/android-webview-dev/4aVzFCd50VA/d4yAVEYVBQAJ) and they mention it in the bug we're tracking here, latest on Nov 21 (so presumably it's still in development) but no indication on when it'd be complete.

However, [from the bug](https://bugs.chromium.org/p/chromium/issues/detail?id=709627#c12):

> No, we cannot add APIs straight into the support library, they must first become android.webkit APIs. We have no definite plans to add an API for this.
>
>---
>
>Passing this to the pool of available bugs. This is probably a good API to add. Unfortunately, I don't think we have bandwidth to add such an API for P.

It sounds like this API must first land in their master branch and then it can be backported, via the support library. This means if we want this API to be added, we'll have to make a fix, wait for the next version of Android to be released, and have made the same fix into the support library (whenever that gets released).

fwiw, making changes to chromium code is not our expertise and it could be difficult (though from ahunt's initial analysis, it doesn't seem too bad!).

> Why not Q? 😝

I guess I got "P-U" stuck in my head, lol.

**Comment by mcomella** [comment]
> This means if we want this API to be added, we'll have to make a fix, wait for the next version of Android to be released,

The Android releases are about yearly and O was just recently released so it'll be at least a year, assuming we (or they) make the fix by then.
