### ISSUE TITLE
"Not blocking" badge does not appear on Pixel, Android 8

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#993]
The badge doesn't seem to appear on my device when disabling blocking.

**Comment by ioana-chiorean** [comment]
Now that you mention - I do not see it either  (I did not know about it much). I can look on other devices Monday at work.

**Comment by ekager** [comment]
I can't reproduce with Pixel API 26 emulator. You both never see the badge?

**Comment by pocmo** [comment]
Yeah, I do not see any badge when disabling content blocking via the menu.

**Comment by pocmo** [comment]
I can see it if I build from master locally. Only our beta builds from Buddybuild are affected. Now they started crashing completely (#1004) - So I'll try debugging this after the crash has been fixed.

**Comment by pocmo** [comment]
Now with the latest build (after clearing buddybuild's cache) it's there! :)
