### ISSUE TITLE
Block Canvas Fingerprint

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/focus-android#996]
Correct me if i'm wrong, wouldn't be useful to add a feature like canvas fingerprint block or (better) obfuscation? Make the device fingerprint less unique can really improve anonimity.

More information:
https://en.wikipedia.org/wiki/Canvas_fingerprinting
https://browserleaks.com/canvas
https://amiunique.org/

This is a third-party Firefox extension that does this:
https://addons.mozilla.org/en/firefox/addon/no-canvas-fingerprinting/

**Comment by lfxc** [comment]
FYI: Firefox 58 to Block Canvas Browser Fingerprinting By Default to Stop Online Tracking

**Comment by pocmo** [comment]
We might depend on GeckoView for that (#13)

**Comment by bbinto** [comment]
So @pocmo, due to GeckoView requirements, is this a blocker than?

**Comment by pocmo** [comment]
> So @pocmo, due to GeckoView requirements, is this a blocker than?

Yes, from what I have seen there's no way to block this happening inside a WebView.

**Comment by cpeterso** [comment]
@bbinto, GeckoView has prefs to block non-user-initiated canvas access. We talked about adding a Klar setting for this as part of Klar+GeckoView's fingerprinting protection. Should we add this bug to the [v6.0 (GeckoView) milestone](https://github.com/mozilla-mobile/focus-android/milestone/22)?

**Comment by cpeterso** [comment]
Canvas fingerprinting protection is a new feature that is not available in WebView, so it doesn't need to be in the initial Klar+GeckoView release (6.0).
