### ISSUE TITLE
Version v1.1 missing in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [mozilla-mobile/focus-android#999]
Dear developer team,

when I take a look in the play store I see that v1.1 is available.

In the F-Droid-repo the current version is v1.0.

What's the reason for this difference? Is there a bug in the build process?

Kind Regards,

Krawei

**Comment by pocmo** [comment]
The builds in f-droid are maintained by the f-droid team:
https://gitlab.com/fdroid/rfp/issues/235

Either try commenting on the linked issue or open a new one. Thanks!

**Comment by Krawei** [comment]
The F-Droid-team told they didn't build the program due to it's "RC1" and "pre-release" tag (see here: https://gitlab.com/fdroid/rfp/issues/274#note_35895504).
Could you please fix this? :)

**Comment by pocmo** [comment]
Oh, you are right. RC1 was stable enough to be the final version we released. I'll need to update the tags.

**Comment by pocmo** [comment]
Tags and release list updated! :)
